### ISSUE TITLE
Mobile app (on Android) crashed after server upgrade to 5.6

### ISSUE THREAD

**Issue by bars83** [mattermost/mattermost-server#10018]
#### Summary
After upgrading to 5.6 mobile app do not work. On lastest mobile app version and on previous version.

#### Steps to reproduce
upgrade 5.5 to 5.6, than run mobile app (android)

#### Expected behavior
Expected mobile app will work normally

#### Observed behavior (that appears unintentional) 
Mobile app crashes with message (in "show details") "java.lang.RuntimeException: Could not invoke NotificationPreferences.getDelivered Notifications at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)..."
![2018-12-18 10-42-27](https://user-images.githubusercontent.com/16895016/50140068-980f0200-02b4-11e9-8ecc-5cc615c908e7.PNG)

![2018-12-18 11-05-55](https://user-images.githubusercontent.com/16895016/50140275-3ef39e00-02b5-11e9-9804-dd79970d4fe4.PNG)

**Comment by lindy65** [comment]
Hi @bars83 

Thanks for the report,

Can you share which device and Android version you are experiencing this?

**Comment by lindy65** [comment]
Hi @bars83 

I believe you will need to upgrade your Android version as the minimum version required to run Mattermost v1.15 app is Android 7.0

Let us know how it goes after you've upgraded your Android version :+1:

**Comment by bars83** [comment]
> Hi @bars83
> 
> I believe you will need to upgrade your Android version as the minimum version required to run Mattermost v1.15 app is Android 7.0
> 
> Let us know how it goes after you've upgraded your Android version

Thanks!
