### ISSUE TITLE
Resizable Sidebar / Hideable

### ISSUE THREAD

**Issue by havedill** [mattermost/mattermost-server#10012]
It would be nice to be able to click/drag the sidebar (where channels are) and resize it/ hide it if desired.

Resizing it and having a channel name abbreviated with ... could make sense;

ex: Town Square once it starts getting cut off would become Tow... (depending on how small you make the sidebar

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback!  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by havedill** [comment]
Will do! Thanks. Couldn't find a requests page when i was looking earlier

**Comment by lindy65** [comment]
Thanks @havedill,

Please post a link to the feature idea forum here so we can track :)

**Comment by jasonblais** [comment]
Thanks @havedill for creating it! I just noticed the feature proposal here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36303472-allow-resizing-and-hiding-of-sidebar

I'll close this issue and we can track the proposal in Uservoice. Thanks for contributing! 🎉
