### ISSUE TITLE
createPost: post creation fails when number of file IDs in list is more than 5

### ISSUE THREAD

**Issue by DenKoren** [mattermost/mattermost-server#10023]
#### Summary
When creating post (HTTP POST request to '/posts' URI) API responses with error model.post.is_valid.file_ids.app_error (Invalid file ids) when number of file IDs provided in request is more than five.

#### Steps to reproduce
Mattermost Version: 5.5.1

* Auth in mattermost API to be able to interact with it.
* Upload 6 or more test files to any channel (including direct channels) or get IDs of already uploaded 6 or more files.
* Try to create a post with 6 or more files attached.

#### Expected behavior
Post is created with files attached.

#### Observed behavior (that appears unintentional) 
API responses with an not-obvious error 'Invalid file IDs' (model.post.is_valid.file_ids.app_error).
The server source code analysis shows this may be an unintentional behavoiur of server.

#### Possible fixes
- change API behaviour so it can accept any amount of files attached to a single post
- OR change error message so user can understand what exactly wrong with file IDs list provided in post creation request.
- AND modify API documentation so it explicitly declares the limitation on amount of files attached to a single post.

Here is the line of code that probably produces the error message.
https://github.com/mattermost/mattermost-server/blob/master/model/post.go#L242

**Comment by jasonblais** [comment]
Thanks @DenKoren! We limit file uploads to 5 per post, but agree we should clearly state it in our documentation and provide a better error message for it.

Have created a ticket for us to track: https://mattermost.atlassian.net/browse/MM-13559

Would you be open to helping improve the experience? Sounds like you already have a good idea on how and where to fix. We'd be happy to guide you if you have any questions.

**Comment by DenKoren** [comment]
I see the following fixes:

#### Server side
I have no idea about how to fix it on server side correctly. 
If the limitation was intended, the server should say it in a message. Error 'incorrect file IDs' is not good for situation when client provided full list of correct IDs obtained from server just a moment ago. It confuses.

#### Documentation
https://api.mattermost.com/#tag/posts says nothing about files count limitation
It is also good to add a notice to https://api.mattermost.com/#tag/files that client can upload as many files as it want, but the amount of files attached to a single post is limited.

**Comment by jasonblais** [comment]
Thanks @DenKoren! Agree, propose we

1. Change the error message server side to be `Uploads limited to 5 files maximum. Please use additional posts for more files.`.

2. Add a note in the `file_ids` parameter description for 'create a post' call and the files section of the API doc to mention the same. [which is what you proposed as well]

**Comment by jasonblais** [comment]
Nice catch @efisuby 

Would you or @DenKoren be open to helping with the following changes?

1. Change the error message server side to be `Uploads limited to 5 files maximum. Please use additional posts for more files.`.

2. Add a note in the `file_ids` parameter description for 'create a post' call and the files section of the API doc to mention the same.

3. Fix description of `filename` parameter description for 'file upload' call.

Many many thanks in advance! 🎉 

PS: First time contributors receive a limited edition mug featuring your username and date of first commit after your changes ship in a Mattermost release. :)

![image](https://user-images.githubusercontent.com/13119842/48648305-dca93400-e9bc-11e8-82b6-fee00c911487.png)

**Comment by jasonblais** [comment]
@DenKoren  @efisuby Thanks again for the reports! I've submitted PRs that should address the above

https://github.com/mattermost/mattermost-server/pull/10055
https://github.com/mattermost/mattermost-api-reference/pull/415
