### ISSUE TITLE
Any way to change default notification sound

### ISSUE THREAD

**Issue by irLinja** [mattermost/mattermost-server#10029]
I can't find any way to change mattermost notification sound to a custom one from my company.
We are using hosted team edition and didn't find anything in docs.

**Comment by jasonblais** [comment]
Hey @irLinja - appreciate your feedback. We have a feature proposal for it - would you be open to upvoting it and participating in the discussion? You get 10 votes in the feature idea forum, and each one influences the future of the project.

https://mattermost.uservoice.com/forums/306457-general/suggestions/8686084-change-notification-sound

**Comment by jasonblais** [comment]
@irLinja I'll close this issue for now and we can monitor it in the feature proposal forum for now https://mattermost.uservoice.com/forums/306457-general/suggestions/8686084-change-notification-sound

Many thanks for the suggestion!
