### ISSUE TITLE
Failed post delete blocks subsequent posts

### ISSUE THREAD

**Issue by gaspode** [mattermost/mattermost-server#10027]
#### Summary
Failed post delete blocks subsequent posts

#### Steps to reproduce
MM Enterprise 5.4.0 on CentOS 7.5
Bug is with web client and also desktop apps (Linux 4.1.2 and Windows 4.2.0-develop)
Post editing is allowed for 60s. Deletions are not allowed.

* User posts in channel
* Hits up-arrow to edit post
* Removes all text, clicks save
* Clicks Delete on "Are you sure you want to delete..." dialog
(Server repeatedly logs permission-denied errors)
* User can no longer post in channel (posts get stuck with activity spinner displayed)

#### Expected behavior
User should not be offered the option to delete the post when it's not allowed. Failed transactions probably shouldn't block further posts

#### Observed behavior (that appears unintentional) 
User is offered option to delete post when editing it despite deletions not allowed. This then blocks posts for the user.

**Comment by jasonblais** [comment]
Thanks @gaspode for the report! I've created a ticket for us to investigate and fix https://mattermost.atlassian.net/browse/MM-13583

**Comment by amyblais** [comment]
Closing this as the Jira ticket has been resolved and tested for upcoming v5.9 release (to be released on March 16th).
