### ISSUE TITLE
Notification badge does not clear on iOS app icon in v 1.15

### ISSUE THREAD

**Issue by felibb** [mattermost/mattermost-server#10026]
#### Summary
Notification badge does not clear on iOS app icon

#### Steps to reproduce
* Receive message; open app, read all unread messages
* Return to home screen

#### Expected behavior
Badge disappears.

#### Observed behavior (that appears unintentional) 
Badge displays obsolete count of unread messages.

#### Environment
iOS app v 1.15, server v 5.1.0, iOS v 11.4.1

#### Comment
Force-quit does not clear badge. Not enough resources to test right now, but the badge might clear if more push messages are received, at least in the same 1-1 chat.

**Comment by felibb** [comment]
> Thanks @felibb for the report. When you say and obsolete count of unread messages, do you mean that there is a red dot without a number count?
No, I mean there is a red dot with the number representing the count of unreads prior to opening the app. Bad wording, sorry.
> Moreover, does this reproduce on previous mobile app versions, or only on the most recent one (v1.15)?
Cannot test anymore, no access to older versions, but cannot remember seeing this issue ever before.

It looks like the badge might clear after another 1-1 chat receives new messages. Temporary glitch? I'll observe more today, and update this issue.

**Comment by lindy65** [comment]
Thanks @felibb 

Please let us know how your observations go and we can investigate further if you are still seeing the issue. To note - we did have an issue of the notification badge not clearing on a previous server version of Mattermost so perhaps upgrading to the latest server version will help resolve the issue if you're still seeing it.

**Comment by amyblais** [comment]
A Jira ticket for this was opened a few days ago: https://mattermost.atlassian.net/browse/MM-13600.

**Comment by amyblais** [comment]
Closing this as the above Jira ticket has been tested internally and the fix will be available in v5.7 release.

Note that there is one related ticket open that will be fixed in a future release: https://mattermost.atlassian.net/browse/MM-13722.

**Comment by adesorme** [comment]
> so perhaps upgrading to the latest server version will help resolve the issue

How can I do this? I'm having the same issue, but no updates are available in the app store. Thanks!

**Comment by amyblais** [comment]
Hi @adesorme, v5.7 server version has been released and it is ready to be downloaded. The next mobile app release is currently a work in process and will be ready in the next few upcoming days.

**Comment by techniker** [comment]
Same here.
