### ISSUE TITLE
[Help Wanted] [MM-12998] UI Automation: Write an automated test using Cypress for "Escape should not close modal while autocomplete is in use"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10034]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12998)

Help write an automated test using cypress for the following test case:

1. Post a message
2. Hit the up arrow to open the "edit modal"
3. In the modal type @ and note the user autocomplete is visible
4. Press the escape key, observe autocomplete closes
5. In the modal type ~ and note the channel autocomplete is visible
6. Press the escape key
7. In the modal click the emoji picker icon
8. Press the escape key

Expected:
On 4. the user auto-complete drop down closes but the edit modal remains open
On 6. the channel auto-complete drop down closes but the edit modal remains open
On 8. the emoji picker closes but the edit modal remains open

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by sapnasivakumar** [comment]
@saturninoabril I would like to work on this

**Comment by saturninoabril** [comment]
Sure, thanks @sapnasivakumar 🎉

**Comment by lindy65** [comment]
@saturninoabril - It seems two issues exist for this same Cypress test.  The other issue already has a PR associated with it: https://github.com/mattermost/mattermost-server/issues/10205. Should we close this one?

**Comment by saturninoabril** [comment]
Oh yes, good catch.  Thanks @lindy65, closing now.
