### ISSUE TITLE
[Help Wanted] [MM-13548] UI Automation: Write an automated test using `cypress` for "Team or System Admin searches and adds new team member"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10039]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13548)

**Test Key**: TS13548

Help write an automated test using cypress for the following test case:
Note: This test assumes you already have an account on the server and have logged in.

1. As Team or System Admin, click hamburger menu > “Add Members to Team”
2. In "Add New Members To [team name] Team" modal, type the first few letters of a user who is on that server but not on the active team in the search box to filter the list
3. Verify list filters as expected
4. Select a user from the list, verify number of users who can be added decrements from 20 to 19
5. Click Go

Expected:
- The added user sees the new team added to the team sidebar
- System message posts in Town Square and Off-Topic "[user2] added to the channel by [user1]" (yes, "channel")
- Added user receives email notification for the mention in the system message

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by courtneypattison** [comment]
I'll attempt this one!

**Comment by courtneypattison** [comment]
When the team member is added, System message posts to Town Square "[user2] added to the team by [user1]" and uses "channel" for Off-Topic. Should it be using "channel" instead of "team"?

**Comment by hanzei** [comment]
Thanks for working on this @courtneypattison! :+1: 

The current behaviour (`master`) is:
- `[user2] added to the team by you.` gets posted in ~town-square
- `[user2] added to the channel by [user1].` gets posted in ~off-topic.

@lindalumitchell Is this the correct behaviour?

**Comment by lindalumitchell** [comment]
Thanks @courtneypattison and @hanzei!

Yes, the stated behavior is correct. The reason is that Town Square is the one required default channel for the team; users cannot leave it. If a user is on the team, they will be in that channel.

Off-Topic is currently a default channel that users are also auto-added to when they join a team, but users can choose to leave Off-Topic.

So the idea is that being added to Town Square is an indicator that the user has joined the team rather than just any one channel, so the message communicates that information.

**Comment by hanzei** [comment]
Thanks @lindalumitchell. :+1: 

Does this solve your questions @courtneypattison?

**Comment by courtneypattison** [comment]
Yes, that's perfect! Thank you @hanzei and @lindalumitchell  :)
