### ISSUE TITLE
[MM-13483] UI Automation: Write an automated test using Cypress for "Cleared search term should not reappear as RHS is opened and closed"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10038]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13483)

**Test Key**: S13483

1. Place the focus in the search box
2. Search for something, e.g. "test"
3. Backspace to clear the search result (or click on the "X" to the right of the search input box)
4. Close the search sidebar
5. Verify the search term does not reappear in the search input box (it is still cleared)
6. Click the pin icon to open the pinned posts RHS

**Expected**: Search term input box is still cleared; search term does not reappear when RHS opens

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by sapnasivakumar** [comment]
@esethna I would like to work on this one

**Comment by saturninoabril** [comment]
Sure, thanks @sapnasivakumar 🎉

**Comment by saturninoabril** [comment]
@sapnasivakumar Let us know if you're working on this. We're happy to help in case you needed.

**Comment by sapnasivakumar** [comment]
I’m traveling this week and will work on it next week.
I’ll reach out if I’m blocked

**Comment by hanzei** [comment]
Hey @sapnasivakumar,

Just want to check if you are still working on this. No problem, if you have to pass this issue.

**Comment by sapnasivakumar** [comment]
@hanzei I'll work on it in the next 2 days

**Comment by hanzei** [comment]
Hi @sapnasivakumar, gently reminder about this issue :wink:

**Comment by sapnasivakumar** [comment]
https://github.com/mattermost/mattermost-webapp/pull/2811
The above PR corresponds to this issue

**Comment by sapnasivakumar** [comment]
> Hi @sapnasivakumar, gently reminder about this issue 😉

@hanzei done :)

**Comment by saturninoabril** [comment]
Thank you @sapnasivakumar 💯 
PR is recently merged.
