### ISSUE TITLE
[Help Wanted] [MM-13225] UI Automation: Write an automated test using Cypress for "Display - Fixed width"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10033]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13225)

Help write an automated test using cypress for the following test case:

1. Go to Account Settings -> Display -> Channel Display Mode -> Edit
2. Select "Fixed width, centered"
3. Save
4. Expand the window to take up your whole screen.

Expected:
- The center channel text should be centered over the textbox 
- The channel intro text at the beginning of a channel (may need refresh or channel switch)

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by cometkim** [comment]
I just started to work on cypress campaign, from this :)

**Comment by jasonblais** [comment]
Yay :tada: Thanks @cometkim :)

**Comment by saturninoabril** [comment]
Thanks @cometkim, PR recently merged.
Closing this now.
