### ISSUE TITLE
[Help Wanted] [MM-13564] UI Automation: Write an automated test using Cypress for "Ellipsis indicates the channel header is too long"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10037]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13564)

1. In a test channel, click on the channel name and select "Edit Channel Header"
2. Type the following:
{noformat}
">quote
newheader newheader newheader newheader newheader newheader newheader newheader newheader newheader"
{noformat}
(must include the quote - does not reproduce without a quote in the header)
3. Hit "Enter" to Save

*Expected*:
After 3) you should see the channel header truncate with an elipses (...) indicating it is too long to fit across the top of the screen.

Clicking on the channel header should still display it in its entirety.

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by manland** [comment]
I'm work on this!

**Comment by saturninoabril** [comment]
Thanks @manland for your contribution!
