### ISSUE TITLE
[Help Wanted] [MM-13473] UI Automation: Write an automated test using `cypress` for "Message Draft - Pencil Icon"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10036]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13473)

Help write an automated test using [cypress|https://www.cypress.io/] for the following test case:
Note: This test assumes you already have an account on the server.

1. Log into https://community.mattermost.com 
2. In a test channel, type some text in the message input box
3. Do not send the post
4. Switch to another channel

Expected:
After 4) you should see a pencil icon to the left of the channel name indicating the channel contains a message draft

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by sapnasivakumar** [comment]
I would like to work on this one

**Comment by jasonblais** [comment]
Thanks @sapnasivakumar!

**Comment by sapnasivakumar** [comment]
@jasonblais I've the following PR for this ticket
https://github.com/mattermost/mattermost-webapp/pull/2251
Can you please let me know if I should be asking for reviews in any specific channel

**Comment by jasonblais** [comment]
@sapnasivakumar Fantastic, thank you! I've queued it for dev review.

**Comment by saturninoabril** [comment]
PR merged 🎉 . Thanks @sapnasivakumar!
