### ISSUE TITLE
[Help Wanted] [MM-12995] UI Automation: Write an automated test using `cypress` for "Cancel out of leaving a team"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10035]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12995)

Help write an automated test using cypress for the following test case:

1. As a member or admin on a team
2. Click main hamburger menu > Leave Team
3. Click "No" in confirmation modal

Expected: Modal closes, user is still on team, still viewing team, no changes

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by pradeepmurugesan** [comment]
I can pick this one

**Comment by hanzei** [comment]
That's a fast PR. Thanks @pradeepmurugesan!

**Comment by saturninoabril** [comment]
PR has been merged.  Thanks @pradeepmurugesan!

Closing this ticket now.
