### ISSUE TITLE
[Help Wanted] [MM-13336] UI Automation: Write an automated test using Cypress for "Delete a parent message that has a reply while RHS is open"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10042]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13336)

**Test Key**: M13336

1. Reply to a message that you have permission to delete
2. Ensure reply thread is open in RHS
3. In center, click [...] > Delete on the parent post
4. Click to verify the deletion on the confirmation modal

*Expected*:
On 3. Confirmation modal warns how many comments will be deleted
On 4. 
- Both parent post and reply are deleted and disappear from the center
- RHS closes
- User does not see `(message deleted)`

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by hanzei** [comment]
Hey @letsila,

Thanks for taking care of this ticket. Let me know, if you have any questions.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/2412
