### ISSUE TITLE
[Help Wanted] [MM-13326] UI Automation: Write an automated test using `cypress` for "Text in bullet points is the same size as text above and below it"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10043]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13326)

**Test Key**: M13326

Help write an automated test using cypress for the following test case:
Note: This test assumes you already have an account on the server and have logged in.

1. In a test channel, post the following:

{noformat}
This is a normal sentence.
<new line> (just make a new line - don't type this in)
1. this is point 1
 - this is a bullet under 1
<new line> (just make a new line - don't type this in)
This is more normal text.
{noformat}

Expected: All text in the post should be the same size. Text in the bullet point should not be larger than the text above or below it.

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by thekiiingbob** [comment]
I'll take this one!

**Comment by saturninoabril** [comment]
I'm late here but sure, thanks @thekiiingbob!

**Comment by saturninoabril** [comment]
PR merged, closing this.
Thanks @thekiiingbob!
