### ISSUE TITLE
[Help Wanted] [MM-13542] UI Automation: Write an automated test using `cypress` for "Open edit modal immediately after making a post"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10040]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13542)

**Test Key**:
M13542

Help write an automated test using [cypress|https://www.cypress.io/] for the following test case:
Note: This test assumes you already have an account on the server.

1. Log into Mattermost instance
2. In a test channel, post a message in a channel
3. Type a second post, with different text from the first one, into the input box
4. Hit 'enter' key and then immediately (as FAST as you can) hit 'arrow-up' to open the edit box
5. If pressed while the new post was still pending, observe the edit box opens for the first post
 - Enter edit text and hit enter
 - Expected: Check the first post and verify that it contains new edited message. Check that the second post remains unchanged with the original message.
6. If the edit box open up for the second post
 - Enter edit text and hit enter
 - Expected: Check the second post and verify that it contains new edited message.
~~6. Press ESC to close edit modal~~
~~7. Press UP again~~

~~Expected:~~
~~Step 5: If you pressed UP while the post was still pending, edit modal opens for previous post~~
~~Step 7: Edit modal opens for the second post"~~

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by sapnasivakumar** [comment]
@esethna i would like to work on this one

**Comment by saturninoabril** [comment]
That's awesome, thanks @sapnasivakumar 🎉

**Comment by hanzei** [comment]
Hey @sapnasivakumar,

How is your work on this ticket going? Can I help with anything?

**Comment by sapnasivakumar** [comment]
@hanzei I'm working on it and will send a PR tomorrow

**Comment by hanzei** [comment]
Great, thanks for the heads up @sapnasivakumar!

**Comment by saturninoabril** [comment]
Hello @sapnasivakumar, I've updated the test steps and verification.  Thanks for asking on the purpose of the original ticket that led us to realize that it's incomplete.

**Comment by sapnasivakumar** [comment]
> Hello @sapnasivakumar, I've updated the test steps and verification. Thanks for asking on the purpose of the original ticket that led us to realize that it's incomplete.

@saturninoabril Will update the corresponding PR in accordance with the new steps. Thank you

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/2522

**Comment by saturninoabril** [comment]
Thanks @sapnasivakumar for your contribution!
