### ISSUE TITLE
[Help Wanted] [MM-13482] UI Automation: Write an automated test using `cypress` for "Timestamp on edited post shows original post time"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10041]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13482)

**Test Key**: M13482

Help write an automated test using cypress for the following test case:
Note: This test assumes you already have an account on the server and have logged in.

1. Post a message, observe the timestamp
2. Click the [...] menu on the post and select Edit
3. Type some edits in the edit text box and save
4. Hover over the timestamp of that post after editing, observe the timestamp
5. Click Reply to open the message in the RHS as well, hover and observe the timestamp in RHS

Expected:
- Hovering over a timestamp shows a full date tooltip in both center and RHS.
- The time should match with the original posting time, not when the post was edited.

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by letsila** [comment]
Hi guys, I'd like to work on this one.

**Comment by saturninoabril** [comment]
Sure @letsila, thanks!

**Comment by hanzei** [comment]
Hey @letsila,

I just want to check how your work on this going. Do you have any questions?

**Comment by letsila** [comment]
Hi @hanzei, I am still on it.

**Comment by hanzei** [comment]
Thanks for the update :+1:. Looking forward to your PR!

**Comment by saturninoabril** [comment]
Thanks @letsila for your awesome contribution!

PR has been merged.  Closing this now.
