### ISSUE TITLE
manifest.json Url

### ISSUE THREAD

**Issue by casparjones** [mattermost/mattermost-server#10047]
#### Summary
Problem with App URL in Chrome OS (manifest.json URL?)

#### Steps to reproduce
Use the Button "add to Homescreen" in Chrome. The App will Open in the subfolder "/static"

#### Expected behavior
I suspect, because in the manifest.json which is under static the URL points to "." the URL is also interpreted wrong by Chrome.  

#### Possible fixes
Maybe it helps to set the URL to "/" or to make "..."?

**Comment by jasonblais** [comment]
Thanks @casparjones for the report! I've filed a JIRA ticket for our team to investigate it further https://mattermost.atlassian.net/browse/MM-13603

**Comment by casparjones** [comment]
Thanks :)

**Comment by amyblais** [comment]
Closing this as the fix for this will be available in v5.8 release (to be released on February 15th).
