### ISSUE TITLE
In which version WebRTC has been removed?

### ISSUE THREAD

**Issue by emresaracoglu** [mattermost/mattermost-server#10045]
Hi,

I am currently using version 5.2. In which version WebRTC has been removed?
Since WebRTC is very important to me, I will upgrade to the latest version in which it is available.

Thank you.

**Comment by jasonblais** [comment]
Hi @emresaracoglu, WebRTC was removed in Mattermost 5.6. All changes are documented here https://docs.mattermost.com/administration/changelog.html

We have several video and audio calling options available in place of WebRTC https://docs.mattermost.com/deployment/video-and-audio-calling.html

Which features and functionality does WebRTC have that made it very important to you and your team? We will take this into account as the purpose was not to reduce scope of what Mattermost has to offer.

**Comment by emresaracoglu** [comment]
Upgraded to Version 5.5.1.
**Thank you for the information.**

I hope that will be published as soon as plugin.
