### ISSUE TITLE
[Help Wanted] [MM-13279] UI Automation: Write an automated test using `cypress` for "Account Settings" > Add Nickname

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10044]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13279)

**Test Key**: AS13279

Help write an automated test using [cypress|https://www.cypress.io/] for the following test case:
Note: This test assumes you already have an account on the server and have logged in.

1. Click on hamburger menu
2. Select Account Settings > General > Nickname > Edit 
3. Type in a Nickname and press "Save"
4. Close Account Settings modal
5. In a channel you belong to, click the channel name and select `Manage Members` (or `View Members`)
6. In the "Search Users" field, type your username

Expected:
- After 3) the Nickname you saved is displayed in the Nickname field
- After 6) your nickname is displayed in parentheses next to your name

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by patniharshit** [comment]
I would like to claim this one :)

**Comment by hanzei** [comment]
Wow, that was a quick PR. Thanks @patniharshit :+1:

**Comment by saturninoabril** [comment]
I'm closing this now.  Forgot to close it when the PR was merged.

Thank you @patniharshit for your contribution!
