### ISSUE TITLE
Opening a Direct Message on mobile first hides it from desktop client

### ISSUE THREAD

**Issue by lannonbr** [mattermost/mattermost-server#10057]
#### Summary
When you open a brand new direct message on mobile, it does not appear on the desktop / web app.

#### Steps to reproduce
Mattermost Server 5.6.0 (Database Schema 5.6.0 & Postgres DB)
Mattermost iOS Client (App version 1.15.1, Build 166)
Mattermost Desktop Client (MacOS) 4.2.0 (4.2.0.61)

1) Have someone open a brand new DM thread that includes yourself
2) Make sure your desktop / web client is closed
3) Open it on a mobile native client (iOS or Android)
4) Open a desktop client and try to find the thread in your Direct Messages section of the sidebar
5) Notice you cannot find the new thread

#### Expected behavior
You should be able to open the thread in a desktop client even if it was opened on mobile

#### Observed behavior (that appears unintentional) 
The thread is not appearing on desktop and disappears on mobile too (likely because the mobile client is trying to sync state with the desktop client)

#### Possible fixes
N/A

**Comment by amyblais** [comment]
Hi @lannonbr, just to confirm, does the Direct Message channel have messages in it?

**Comment by lannonbr** [comment]
Yes it does.

**Comment by amyblais** [comment]
Hi @lannonbr, I wasn't able to reproduce this just now - the only difference with my environment was that I'm on a v5.7 server version as we're getting prepared to release the new version. Would you be open to doing some testing on our [Community server here](https://community.mattermost.com) to see if you can reproduce the issue on the latest version?

If you can reproduce the issue there, can you help with your iOS version as well as your Mac version?

**Comment by amyblais** [comment]
Closing this as we haven't received a response for a while,
