### ISSUE TITLE
Language not set is selected in "Account Settings".

### ISSUE THREAD

**Issue by dupont-kedama** [mattermost/mattermost-server#10051]
#### Summary
Language not set is selected in "Account Settings".
(There is no problem with normal use.)

#### Steps to reproduce
Set as follows.

+ System Console > Localization
  + Default Server Language: Japanese
  + Default Client Language: Japanese
  + Available Languages: English,Japanese
+ The User Account Settings > Display
  + Language: English

#### Expected behavior
When see Account Settings > Display, English is selected.

#### Observed behavior (that appears unintentional) 
Japanese is selected.
![screenshot 389](https://user-images.githubusercontent.com/5292063/50498342-4d933f80-0a83-11e9-9904-0d95547254b0.png)

**Comment by amyblais** [comment]
Hi @dupont-kedama, can you help check the database and see if you have the 'en' locale there? You might then need to manually modify the locale to the desired language in the database and restart the server. Let me know if this helps.

**Comment by dupont-kedama** [comment]
Hi @amyblais, thank you for advice.

> can you help check the database and see if you have the 'en' locale there?

Specifically, where should I check?
This environment is Windows10(Japanese) + MySQL 5.7.22.

**Comment by dupont-kedama** [comment]
Thank you @amyblais.
In the "users" table, the target user's locale value was "en".
After changing the language setting, "System Console > Purge All Caches" or "Ctrl+R" did not change the situation.

Attach a movie when changing the setting for reference.
In this operation, the setting is changed from Japanese to English.

![change_language](https://user-images.githubusercontent.com/5292063/50818941-f4bd8400-136b-11e9-82f1-56042bd9ef27.gif)

**Comment by kaakaa** [comment]
I can reproduce this.
With setting at least one language to **System Console** > **Localization** > **Available Languages**, **Default Client Language** will be displayed in **Language** section in Account Settings.

Mattermost v5.6.0
macOS / Chrome

**Comment by amyblais** [comment]
Thanks all, I was able to reproduce it and opened a ticket here: https://mattermost.atlassian.net/browse/MM-13680.

**Comment by jasonblais** [comment]
Thanks @kaakaa for the fix 🎉
