### ISSUE TITLE
Api method get_user didn't show notify_props

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#10052]
Hello.

I checked the method:
https://your-mattermost-url.com/api/v4/users/{user_id}

And I received a result below:
>{
  "id": "user_Id",
  "create_at": 1542640356185,
  "update_at": 1546005374503,
  "delete_at": 0,
  "username": "username",
  "auth_data": "",
  "auth_service": "",
  "email": "username@domain.com",
  "nickname": "nickname",
  "first_name": "FirstName",
  "last_name": "LastName",
  "position": "Developer",
  "roles": "system_user",
  "last_picture_update": 1544614796782,
  "locale": "en",
  "timezone": {
    "automaticTimezone": "",
    "manualTimezone": "",
    "useAutomaticTimezone": "true"
  }
}

So, there isn't other data from the user profile like notify_props or props. Why?
The server version is 5.5. I see the same situation with last version 5.6.1.

**Comment by jasonblais** [comment]
Thanks @swood for the report! I've reproduced this.

[In the documentation](https://api.mattermost.com/#tag/users%2Fpaths%2F~1users~1%7Buser_id%7D%2Fget) we say that "Sensitive information will be sanitized out." from the response. 

It might be that the `mention_keys` field in notify_props is considered sensitive and hence not returned. I've asked our team to confirm whether this is the case.

```
{
...
"notify_props":
{
"channel":"true",
"comments":"never",
"desktop":"mention",
"desktop_sound":"true",
"email":"true",
"first_name":"false",
"mention_keys":"jason,@jason",
"push":"mention",
"push_status":"away"
},
...
```

**Comment by swood** [comment]
Hey, @jasonblais, do you have any updates?

**Comment by jasonblais** [comment]
@swood I heard back - this is data that other clients don't really need to receive, so we don't send it back.

Is there a use case where you need this information to being sent?

**Comment by swood** [comment]
@jasonblais yes, exactly. I'd like to make a mere mention for a group of people, for example, "@duty". It's a person who is sometimes changing. So, I want to have a method to add or delete this mention or subscribe people on "mention words". Is it clear?

**Comment by swood** [comment]
Yeah, thank you. But could you please open a release page:
>Go to the releases page of this Github repository 
https://github.com/mattermost/mattermost-plugin-autlink/releases

now it shows an error 404.

**Comment by jasonblais** [comment]
@swood That's correct, but contributions to add support for API is welcome and highly appreciated 👍

**Comment by amyblais** [comment]
There hasn't been activity here for a while, so closing this for now,
