### ISSUE TITLE
Inappropriate icon in "Team Statistics".

### ISSUE THREAD

**Issue by dupont-kedama** [mattermost/mattermost-server#10050]
#### Summary
Inappropriate icon in "System Console" > "Team Statistics".

#### Observed behavior
Open "System Console" > "Team Statistics".

+ "Public Channels" -> Team?Members? icon.
+ "Private Channels" -> World?Earth? icon. (Probably the old version icon)

![screenshot 388](https://user-images.githubusercontent.com/5292063/50463489-7a861a80-09cf-11e9-84ce-5b4a25cb5b87.png)

#### Expected behavior

I think this is appropriate.

+ "Public Channels" -> (New) World icon.
+ "Private Channels" -> Padlock icon.

**Comment by jasonblais** [comment]
@dupont-kedama Nice catch, created a ticket here for our team triage https://mattermost.atlassian.net/browse/MM-13601

Would you be open to helping with a pull request?

**Comment by dupont-kedama** [comment]
@jasonblais
I'm sorry. I can not help it.
I am not good at programming, so I can not read the source code.

**Comment by jasonblais** [comment]
@dupont-kedama No worries! Thanks for the initial report, it's currently been triaged for one of our team members.

**Comment by amyblais** [comment]
Closing this as the fix for this will be available in v5.8 release (to be released February 15th).
