### ISSUE TITLE
[5.6.2] drag&drop upload: dragging in a folder results in: "There appears to be a problem with your internet connection."

### ISSUE THREAD

**Issue by somenet** [mattermost/mattermost-server#10064]
#### Summary
When using drag and drop in the web frontend and dragging a folder into a MM-Channel it will display the unexpected error message ``There appears to be a problem with your internet connection.`` on a recent Debian/KDE. (Not sure/Cannot test, if this is a windows issue too)

#### Steps to reproduce
Drag a folder from the desktop into a channel.
+ with single files, the file will get uploaded.
+ with a directory, you will get the error message saying``There appears to be a problem with your internet connection.``

#### Expected behavior
Either an error message saying something like: ``Dont drag in folders. Drag in all files separately``
or what would be even better: Upload all files in that directory.

#### Observed behavior (that appears unintentional) 
Getting the error message saying ``There appears to be a problem with your internet connection.``

#### Possible fixes
Change error message. (or change behavior to upload all files contained.)

**Comment by amyblais** [comment]
Thank you @somenet, I'm able to reproduce this and opened a ticket here: https://mattermost.atlassian.net/browse/MM-13634.

**Comment by amyblais** [comment]
Hi @somenet,

Closing this issue for now as this has been fixed on master and for the upcoming v5.10 server release (to be released in April 16th),
