### ISSUE TITLE
"Address forbidden" error for a slash command calling a HTTPS URL using a local certificate

### ISSUE THREAD

**Issue by ramnes** [mattermost/mattermost-server#10063]
#### Summary

Mattermost doesn't seem to consider locally trusted certificates.

#### Steps to reproduce

* Run `mattermost-integration-giphy` behind a `nginx` that uses a self-signed certificate
* Try calling `https://mattermost-integration-giphy.domain` with `curl`, and then with Mattermost's slash command
* Later, add the public certificate in `/etc/ssl/certs/` and run `sudo update-ca-certificates`
* Try calling again

Mattermost version: 5.0.2

#### Expected behavior

Without the certificate in `/etc/ssl/certs/`, neither `curl` nor the slash command should work.

Once the certificate installed, `curl` should return `OK`, and the slash command should return a funny GIF.

#### Observed behavior (that appears unintentional) 

Without the certificate, `curl` fails, as expected:

```
$ curl https://mattermost-integration-giphy.domain
curl: (60) SSL certificate problem: unable to get local issuer certificate
...
```

So does Mattermost:

```json
{"level":"error","ts":1546600733.9548545,"caller":"web/handlers.go:140","msg":"Command with a trigger of 'giphy' failed","path":"/api/v4/commands/execute","request_id":"***","ip_addr":"192.168.10.240","user_id":"***","method":"POST","err_where":"command","http_code":500,"err_details":"Post https://mattermost-integration-giphy.domain/new_post: address forbidden"}
```

But once the public certificate in `/etc/ssl/certs/`, `curl` works, as expected:

``` 
$ curl https://mattermost-integration-giphy.team-koala.numberly.in
OK
```

But the slash command does not. Mattermost continues to output the same error, just as if the local certificate wasn't existing.

#### Possible fixes

Handling local certificates?

**Comment by amyblais** [comment]
Hi @ramnes,

Our latest server version is v5.6, would you be open to upgrading to the latest version to see if you experience anything different?

**Comment by ramnes** [comment]
I will check on 5.6.0 as soon as possible. Meanwhile, I can already confirm that there is the same issue on 5.4.0.

**Comment by ramnes** [comment]
Same with 5.5.0.

**Comment by amyblais** [comment]
Thank you @ramnes, I'll ask our team to take a look at this.

**Comment by hmhealey** [comment]
Hi @ramnes, is mattermost-integration-giphy.domain running on the same network as the Mattermost server? If so, you may need to configure the `AllowedUntrustedInternalConnections` setting to allow access to the server. By default, Mattermost prevents accessing addresses on the local network so that users outside of the network cannot use it to get into the network. There's more information on that setting [here](https://docs.mattermost.com/administration/config-settings.html#allow-untrusted-internal-connections-to).

**Comment by ramnes** [comment]
@hmhealey They aren't on the same network, and I don't want to allow *untrusted* connections anyway.

**Comment by hmhealey** [comment]
Maybe you can try setting the `SSL_CERT_FILE` or `SSL_CERT_DIR` environment variable when running Mattermost then?

**Comment by ramnes** [comment]
Using `AllowedUntrustedInternalConnections` works, even if they aren't on the same network. I guess it's because the webservice Mattermost tries to call is in a private network (10.0.0.0). Frankly this option needs much more documentation, because it has a really weird name and behavior. I'm still unsure of what the `Untrusted` part means: is it about SSL or not?
