### ISSUE TITLE
GitHub plugin: improvements

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-server#10069]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

There are some help wanted issues for the GitHub plugin here:

https://github.com/mattermost/mattermost-plugin-github/issues

If you're interested in working on one, feel free to comment on it there.

In addition, feel free to join the [GitHub Plugin](https://community.mattermost.com/core/channels/github-plugin) channel for more discussion, questions and feature requests.

**Comment by checkaayush** [comment]
@jwilander This can be closed I guess.

**Comment by jwilander** [comment]
@checkaayush I'm hoping we can open some more help wanted issues for the GH plugin shortly :)

**Comment by hanzei** [comment]
@jwilander What do you think about closing this one, as there arn't to many HWs on the GH plugin repo? And using this force, there should be a ticket for every plugin similar to this one, which doesn't sound ideal.

**Comment by hanzei** [comment]
Replaces by https://github.com/mattermost/mattermost-server/issues/12656
