### ISSUE TITLE
Write an automated test using `cypress` for "Copy a permalink and paste into another channel"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10075]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13675)

**Test Key**: M13675

Help write an automated test using [cypress|https://www.cypress.io/] for the following test case:
Note: This test assumes you already have an account on the server.

1. Log into https://community.mattermost.com 
2. Click on the 3-dot menu to the right of any message in any channel
3. Click on "permalink"
4. Click on "copy link" then on "close"
5. Switch to another channel, Direct or Group Message
6. Paste the copied permalink into the message input box (CTRL+V) and hit "Enter"

Expected:
- Permalink should copy and paste properly 
- Once pasted into a new channel it should render properly
- Clicking on the permalink takes you to the conversation

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by sapnasivakumar** [comment]
@saturninoabril I would like to work on this one

**Comment by hanzei** [comment]
Thanks @sapnasivakumar! :tada:

**Comment by hanzei** [comment]
Hey @sapnasivakumar,

Is there anything I can help you with?

Looking forward to your PR!

**Comment by sapnasivakumar** [comment]
@hanzei I'll try and get the PR ready.
As of now I do not require any support and will ping you in case I need any.
Thank you

**Comment by saturninoabril** [comment]
@sapnasivakumar Let us know if you're working on this. We're happy to help in case you needed.

**Comment by sapnasivakumar** [comment]
I’m traveling this week and will work on it next week.
I’ll reach out if I’m blocked

**Comment by hanzei** [comment]
@sapnasivakumar Also a reminder about this ticket.

**Comment by sapnasivakumar** [comment]
@hanzei I'll work on it in the next 2 days

**Comment by hanzei** [comment]
Great! Thanks for the heads up @sapnasivakumar :rocket:

**Comment by sapnasivakumar** [comment]
@hanzei I would like to pass this ticket on so that someone can pick it up.

**Comment by hanzei** [comment]
Surely @sapnasivakumar. Thanks for the work you put into this ticket and the many others. :+1: Glad to have you as part of the community.

**Comment by composednitin** [comment]
i would like to take this

**Comment by saturninoabril** [comment]
Sure, thanks @composednitin!

**Comment by sourabkumarkeshri** [comment]
Hey,I want to work on this

**Comment by hanzei** [comment]
Sure, thanks @sourabkumarkeshri :tada:
