### ISSUE TITLE
Problem with the background color.

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-server#10074]
#### Summary
If I change the theme to Dark, the background color of the modal will not change.

#### Steps to reproduce
Clone the current mattermost-webapp / matermost-server and run make run to check the problem. Click the Account Settings menu.

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
I can not see words. 
![image](https://user-images.githubusercontent.com/20394843/50816428-e7040080-1363-11e9-8ade-be730e015fae.png)

#### Possible fixes
I think that modify the CSS background element will fix it.

**Comment by amyblais** [comment]
Hi @Gloriashield,

Would you be open to reviewing this page and sending us the relevant details about your environment: https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by Gloriashield** [comment]
Thank you for your interest.

What OS and version is the Mattermost server installed?
- Ubuntu 18.04 (AWS)

What is your Mattermost server version?
- 5.7 (current github mater branch)
- pull https://github.com/mattermost/mattermost-server (webapp) and make run it.

Are you experiencing the issues with the browser webapp, if so which one?
- Chrome 71.0.3578.98 64bit 
- 

Are you experiencing the issues with the Mattermost Desktop App, if so what version and OS?
- Not tested. only tested on web-browser.

Are you experiencing the issues with the Mattermost Mobile App, if so what version and OS?
- Not tested.

Can you send a snippet of the Mattermost server logs around the time of the incident?
- Hm .. it is not compiled. How can I get server logs?

**Comment by hmhealey** [comment]
Hi @Gloriashield, thanks for the report. That was a known issue on the master branch a few days ago, but it should be fixed if you pull the latest version of master.

**Comment by Gloriashield** [comment]
Thanks!
