### ISSUE TITLE
[Help Wanted] [MM-13439] Change "X" to "Cancel" on Profile page

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10078]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13439)

RN mobile apps: Change "X" to "Cancel"  on Edit Profile page

When editing your profile on the mobile apps, we display an "X" on the top left corner which closes the modal without saving the settings.

However, this is not obvious whether it closes the page with or without saving the settings. As a result, some users have hit the "X" button after changing their settings, only to have them discarded without any warning.

To make it more obvious, change "X" to "Cancel", with the "Save" button in top right corner. 

For details see https://community.mattermost.com/core/pl/k1xdd1w3jpytdr1n74exziq9ky

**Comment by dmamills** [comment]
I would like to take this as a first ticket!

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-mobile/pull/2520.

Thanks @dmamills for the contribution!
