### ISSUE TITLE
"mattermost config show" does not exist

### ISSUE THREAD

**Issue by ceving** [mattermost/mattermost-server#10088]
#### Summary
The command `mattermost config show` does not show anything.

#### Steps to reproduce
Version:

    # ./bin/mattermost version
    {"level":"info","ts":1547110807.2463984,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'de' from '/opt/mattermost/i18n/de.json'"}
    {"level":"info","ts":1547110807.2465196,"caller":"app/app.go:204","msg":"Server is initializing..."}
    {"level":"info","ts":1547110807.2482,"caller":"sqlstore/supplier.go:209","msg":"Pinging SQL master database"}
    {"level":"info","ts":1547110807.257917,"caller":"sqlstore/channel_store_experimental.go:47","msg":"Enabling experimental public channels materialization"}
    {"level":"info","ts":1547110807.2908516,"caller":"app/license.go:44","msg":"License key from https://mattermost.com required to unlock enterprise features."}
    {"level":"info","ts":1547110807.290905,"caller":"app/plugin.go:100","msg":"Starting up plugins"}
    Version: 5.5.0
    Build Number: 5.5.1
    Build Date: Thu Dec  6 09:21:58 UTC 2018
    Build Hash: 826252252404c13bf564a8c4fd51616fc2cc4df9
    Build Enterprise Ready: true
    DB Version: 5.5.0

Running on:

    # cat /etc/*release
    CentOS Linux release 7.5.1804 (Core) 
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    
    CENTOS_MANTISBT_PROJECT="CentOS-7"
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"
    
    CentOS Linux release 7.5.1804 (Core) 
    CentOS Linux release 7.5.1804 (Core) 
    
How to reproduce:

    mattermost config show

#### Expected behavior
Description is here:

https://docs.mattermost.com/administration/command-line-tools.html#mattermost-config-show

#### Observed behavior (that appears unintentional) 
This is what my installation says:

    # ./bin/mattermost config show
    Configuration
    
    Usage:
      mattermost config [command]
    
    Available Commands:
      subpath     Update client asset loading to use the configured subpath
      validate    Validate config file
    
    Flags:
      -h, --help   help for config
    
    Global Flags:
      -c, --config string        Configuration file to use. (default "config.json")
          --disableconfigwatch   When set config.json will not be loaded from disk when the file is changed.
    
    Use "mattermost config [command] --help" for more information about a command.

**Comment by hanzei** [comment]
`config show` was added in Mattermost v5.6. (See https://docs.mattermost.com/administration/changelog.html#command-line-interface-cli) Could you please update your server?

**Comment by ceving** [comment]
Sorry my fault.
