### ISSUE TITLE
[Help Wanted] [MM-13697] UI Automation: Write an automated test using Cypress for "Edit post that has attachment, paste text in middle"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10084]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13697)

**Test Key**: M13697

Help write an automated test using cypress for the following test case:
Note: This test assumes you already have an account on the server and have logged in.

1. Post a message with text, plus a file attached
2. Click [...] > Edit on the post and select Edit
3. Paste some additional text in the middle of the message
4. Save

Expected:
- Pasted text should be pasted where the cursor is
- File attachment shouldn't disappear after saving the post

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by adzimzf** [comment]
Hi, I'll pick this one

**Comment by hanzei** [comment]
Thanks @adzimzf! :+1:

**Comment by adzimzf** [comment]
Hi @hanzei,
where user should post message ? in channel or direct message ?
and if it post on direct message should I create 2 users ?

**Comment by saturninoabril** [comment]
Thank you @adzimzf for your contribution!

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/2397
