### ISSUE TITLE
[Help Wanted] [MM-13701] UI Automation: Write an automated test using Cypress for "Consecutive message does not repeat profile info"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10085]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13701)

Help write an automated test using cypress for the following test case:

1. Post `One`
2. Post `Two`
3. Post `Three`
4. Click reply arrow to also observe in RHS 

Expected:
On desktop app, RN apps, and browser in full-width view:
Name and profile pic display on `One` post only, not on `Two` or `Three`

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by manland** [comment]
I'm work on this!

**Comment by hanzei** [comment]
Thanks @manland! :+1:
