### ISSUE TITLE
[Help Wanted] [MM-13747] Add ability to list users to plugin API

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10097]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13747)

Currently the plugin API only supports listing users if you provide a team. It would be useful to be able to list users without providing a team.

Add the following plugin API method:
* `GetUsers(page int, perPage int) ([]*model.User, *model.AppError)`

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by hanzei** [comment]
Thanks @dom3k! :tada:
