### ISSUE TITLE
[Help Wanted] [MM-13749] Add ability to search posts in a team to plugin API

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10099]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13749)

Add the following plugin API method:
* `SearchPostsInTeam(teamId string, params *model.SearchParameter) (*model.PostList, *model.AppError)`

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by awbraunstein** [comment]
I'd like to take this Issue.

**Comment by hanzei** [comment]
Great @awbraunstein! Let me know, if you have any questions.

**Comment by awbraunstein** [comment]
I have a few questions.

1. Did you mean `model.SearchParameter` instead of `model.SearchParameters`?
2. Assuming the answer to 1 is yes, `model.SearchParameter` has "optional" fields that are pointers. Should these all be nil checked?
3. It looks like the function that I need to call also takes in a userId. Should I update the signature to require that as well?

Thanks

**Comment by awbraunstein** [comment]
What should the behavior of a search like `Mattermost in:@john.doe` aka direct message history? Would this just not be supported?

**Comment by jwilander** [comment]
I would much rather handle that through explicit options as part of the API input rather than including it like that as part of the search term/phrase

**Comment by awbraunstein** [comment]
I'm also wondering if searching for `in:@a,b` should still work without a "current user" and should search the direct messages between `@a` and `@b`. Or should we just return an error for any sort of search in a group or direct channel?

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/10106
