### ISSUE TITLE
[Help Wanted] [MM-13748] Add ability to get team statistics to the plugin API

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10098]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13748)

Currently we can get channel statistics from the plugin API but not team statistics. 

Add the following plugin API method:
* `GetTeamStats(teamId string) (*model.TeamStats, *model.AppError)`

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by Sheshagiri** [comment]
I'm in for this.

**Comment by hanzei** [comment]
Great, thanks @Sheshagiri! :+1:
