### ISSUE TITLE
[Help Wanted] [MM-13750] Add ability to search teams to plugin API

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10100]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13750)

Add the following plugin API method:
* `SearchTeams(term string) ([]*model.Team, *model.AppError)`

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by adzimzf** [comment]
Hi, I try pick this issue.

**Comment by jasonblais** [comment]
Thanks @adzimzf! Let us know if you have any questions

**Comment by adzimzf** [comment]
Hi @jasonblais. I think the story is clear.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/10116. Thanks @adzimzf for your contribution! :tada:
