### ISSUE TITLE
Slack Incompatibility: JSON bool fields represented as strings cannot be deserialized

### ISSUE THREAD

**Issue by nlowe** [mattermost/mattermost-server#10108]
#### Summary
Boolean values in JSON Payloads encoded as `"true"` and `"false"` are unsupported in Mattermost.

#### Steps to reproduce
Tested on 5.4.0 and 5.7.0-rc2

1. Create an incoming webhook
2. Send the following payload:

```json
{
    "attachments":[
        {
            "fallback":"Unable to show attachments",
            "fields":[
                {
                    "short":"true",
                    "title":"This doesn't work",
                    "value":"Some Value"
                }
            ]
        }
    ]
}
```

#### Expected behavior
The webhook is accepted and the message is posted

#### Observed behavior (that appears unintentional) 
The following error response is returned:

```json
{"id":"model.incoming_hook.parse_data.app_error","message":"Unable to parse incoming data","detailed_error":"","request_id":"***","status_code":400}
```

and the following log line will be generated:

```json
{"level":"error","ts":1547480456.3552866,"caller":"web/context.go:60","msg":"Unable to parse incoming data","path":"/hooks/***","request_id":"***","ip_addr":"***","user_id":"","method":"POST","err_where":"IncomingWebhookRequestFromJson","http_code":400,"err_details":"json: cannot unmarshal string into Go struct field SlackAttachmentField.short of type bool"}
```

#### Possible fixes
Add a custom type alias for `bool` that implements [`json.Unmarshaler`](https://golang.org/pkg/encoding/json/#Unmarshaler) to support decoding both `"true"`/`"false"` and `true`/`false` to maintain compatibility with Slack, possibly something like:

```golang
type SlackCompatibleBool bool

func (h *SlackCompatibleBool) UnmarshalJSON(data []byte) error {
	str := strings.ToLower(string(data))
	if str == "true" || str == `"true"` {
		*h = true
	} else if str == "false" || str == `"false"`{
		*h = false
	} else {
		return fmt.Errorf("failed to decode %s to bool", str)
	}
	
	return nil
}
```

#### Other Notes
We found this when attempting to use the [Slack Notification Step Template](https://library.octopusdeploy.com/step-templates/07d64408-ac47-490e-ade2-01bab607ed4f/actiontemplate-slack-detailed-notification) for OctopusDeploy. The following fields use strings for boolean types:

* Environment
* Machine
* Tenant
* Username
* Release
* Error Link

As a workaround, all of these can be disabled, but it significantly reduces the usefulness of the notification.

**Comment by amyblais** [comment]
Thank you @nlowe, would you be interested in opening a PR for this?

**Comment by nlowe** [comment]
Most definitely!
