### ISSUE TITLE
Custom Brand Text with standard emojis leads to complete login page failure

### ISSUE THREAD

**Issue by techniker** [mattermost/mattermost-server#10107]
#### Summary
Custom Brand Text with standard emojis embedded (<3 works) leads to complete login page failure.

#### Steps to reproduce
Using version 5.6.2 this behaviour is reproducible by adding or copying emojis into the custom brand text field.
The login page will not be shown, only a white blank page is observed.

#### Expected behavior
Login page should display as expected.

#### Observed behavior (that appears unintentional) 
Adding emojis to the "Custom Brand Text" field leads to a white login page after saving.
This issue has been confirmed using the following browsers:
Chrome, Firefox, Safari.

**Comment by amyblais** [comment]
Hi @techniker,

Do you also have a Custom Brand image uploaded?

I wasn't able to reproduce this just now, but I'm on a v5.7 server as we're getting ready to release a new version, and I have a Custom Brand Image previously uploaded.

**Comment by techniker** [comment]
Hi amyblais,

yes, I do have a custom brand image uploaded.
Did not change any of the custom branding data and after the update to 5.6.2 this failure appeared.
When I remove the emojis (which are no custom emojis) from the custom brand text field, everything works as expected again.

**Comment by techniker** [comment]
Okay, fine. Thanks again!
Will reopen this ticket if the problem persists in v5.7.

**Comment by amyblais** [comment]
Hi @techniker, have you had a chance to test this on v5.7?

**Comment by techniker** [comment]
Seems fixed in v.5.7.0 .
