### ISSUE TITLE
CLI channel move syntax "wrong"

### ISSUE THREAD

**Issue by JtheBAB** [mattermost/mattermost-server#10115]
Hi all

#### Summary
The CLI channel move syntax is not common.

#### Issue
At the moment the channel move is using the syntax:
channel move [destination] [source] --username myusername

but every program that moves something has the syntax:
mv [source] [destination]

By switching the syntax it makes the cli more consistent with other move tools and also within the cli. For example channel rename uses also the schema [source] [destination]
##
I tried to simple flip the arguments in the channel.go but that's not working at all but its clearly limited due to my inexisting program skills

Best regards

JtheBAB

**Comment by amyblais** [comment]
Hi @JtheBAB,

I opened an improvement ticket for this here: https://mattermost.atlassian.net/browse/MM-13787.

**Comment by adzimzf** [comment]
Hi, can I pick this ?

**Comment by amyblais** [comment]
Hi @adzimzf, yes you can work on a fix for this, thank you!

**Comment by jasonblais** [comment]
This command is being migrated to and resolved in the new mmctl tool at https://github.com/mattermost/mmctl/pull/149.

Closing this issue as we won't resolve it in the current Mattermost CLI (instead, we're migrating the new mmctl command into the Mattermost server over time)
