### ISSUE TITLE
Deleting a message should not delete replies to deleted message

### ISSUE THREAD

**Issue by pirtleshell** [mattermost/mattermost-server#10119]
#### Summary
Deleting a message that has comments also deletes all replies to the comment, without consent or permission form the other comment authors, regardless of permissions.

#### Steps to reproduce
1. Have one user post a message and another respond with a reply from the sidebar.
2. Have the original author delete their original message.
3. Note that all subsequent comments on their message are also deleted.

#### Expected behavior
Someone should not be able to delete someone else's messages just because they happened to be making use of the reply feature.

#### Observed behavior (that appears unintentional) 
The entire reply chain is deleted with the original message.

#### Possible fixes
The original message should be replaced with a `(message deleted)` text and the replies to that message should remain. The replies should only be able to be deleted by their author or users with the proper permissions.

**Comment by amyblais** [comment]
Hi @pirtleshell,

This is currently expected behaviour, so I created an improvement/Story ticket: https://mattermost.atlassian.net/browse/MM-13792.

Please let us know if you're interested in helping implement this improvement.

**Comment by amyblais** [comment]
Hi @pirtleshell,

Letting you know that you can follow the progress of this issue also via the Jira ticket I linked above. For the latest updates to the ticket you can add yourself as a watcher. To do this, click on "Start Watching This Issue" in the ticket. This way you’ll be emailed immediately when the ticket status is changed. If you have any issues accessing our Jira instance please let me know.

Let me know if you'd prefer to follow the progress on this issue via the Jira ticket or via this Github Issue?

**Comment by Ryonez** [comment]
Wait, this is a thing? Holy crap...

**Comment by eroller** [comment]
I kind of like this policy. The repliers to the original comment are free to create a new thread addressing the issue if they are not happy. If you are going to allow comments to be deleted then it makes no sense to keep the replies to those comments alive as it would just be confusing to follow. Doesn't facebook keep the replies around and cause confusion/trolling?

**Comment by mpounsett** [comment]
This is STILL a problem.  It really needs to be fixed.

**Comment by jelu** [comment]
This is very unexpected behavior, at least this should be configurable!

**Comment by amyblais** [comment]
Closing as a dup of https://github.com/mattermost/mattermost-server/issues/20024.
