### ISSUE TITLE
[Help Wanted] [MM-13827] [Desktop] Expose Webview Developer Tools via View Menu

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10131]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13827)

We recently [documented](https://github.com/mattermost/mattermost-developer-documentation/pull/221) the steps necessary to open the developer tools for individual webviews in the desktop app, but this would ideally be accessible from the View menu after "Toggle Developer Tools".

This ticket consists of proposing a design to expose this functionality in the desktop app (vs. the manual steps linked above), sharing in https://community.mattermost.com/core/channels/ux-design and getting buy in, and then implementing the required changes in the Desktop app. Note that this feature will not require changes in the webapp and only affect the Desktop app.

**Comment by manland** [comment]
I'm working on this!

**Comment by hanzei** [comment]
Thanks @manland!

**Comment by manland** [comment]
I propose to implement something like that

![selection_162](https://user-images.githubusercontent.com/1492516/52375047-02dfec80-2a5f-11e9-99ec-211fe45db08d.png)

**Comment by manland** [comment]
Discussion on https://community.mattermost.com/core/pl/5jdjfyyq7pdpfc3nyexcgnoiec 

Correct implementation will be :
* Developer tools for "current" server (with no shortcut)
* Developer tools for application wrapper (with the Ctrl+Shift+I)

**Comment by jwilander** [comment]
@manland @lieut-data did https://github.com/mattermost/desktop/pull/926 complete this, or is there other work still to be done here?

**Comment by lieut-data** [comment]
From my perspective, https://github.com/mattermost/desktop/pull/926 suffices to resolve this ticket.
