### ISSUE TITLE
[Help Wanted] [MM-13833] Configure unit tests to log through t.Log

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10137]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13833)

Currently, the app instances created as part of testing dump their logs to STDOUT. This spans the testing output when the verbose flag is given even if the test passes, making it hard to pinpoint failing tests among the logs for the passing ones.

This ticket captures the work required to configure these app instances to route through `t.Log` from the `testing` package. This probably requires some initial refactoring to ensure the `testing.T` instance is available to the unit test in question, as well as the necessary logging proxy and app configuration to emit these logs as such.

**Comment by BK1603** [comment]
I'd like to work on this :smile:
I have some experience with go and servers, but I am a bit new to this repo and might need a little help :sweat_smile:

**Comment by hanzei** [comment]
Hey @BK1603,

Thanks for looking into this! :+1:  Feel free to join the [Mattermost Community Server](https://community.mattermost.com) and ask questions in ~developers. You can also DM @jesse.hallam as the created this ticket.

Looking forward to your PR! :tada:

**Comment by lieut-data** [comment]
Just for added clarity, once this ticket is implemented, the expected behaviour is that running something like:
```
cd app && go test -v
```

will output something like:
```
=== RUN   TestInviteProvider
=== RUN   TestJoinCommandNoChannel
--- PASS: TestJoinCommandNoChannel (1.43s)
=== RUN   TestJoinCommandForExistingChannel
```

instead of emitting logs

**Comment by lieut-data** [comment]
Sigh, wrong button...

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/10272.

Thanks @BK1603 for the contribution! :rocket:
