### ISSUE TITLE
No way to turn off email rate limiting

### ISSUE THREAD

**Issue by Fodoj** [mattermost/mattermost-server#10134]
I could not find any way to disable email rate limiting. Is that so and there is no such feature? Searching around the internet and existing features as well as examining source code of mattermost didnt help much.

**Comment by amyblais** [comment]
Hi @Fodoj,

Would you be open to describing what you are referring to with email rate limiting?

**Comment by Fodoj** [comment]
@amyblais this:

https://github.com/mattermost/mattermost-server/blob/ae76d27b7dbb8f20b35f17153fe77beb8c0d2297/app/server.go#L66
https://github.com/mattermost/mattermost-server/blob/c494f6f8981fb39ae07ac772ec8ec4fdca69d8ed/app/email.go#L25

There is a hard limit of 20 email invitations per hour. So when I try to send out 100 invites, API returns "OK", but in server logs there is an error "Invite emails  rate limited"

**Comment by amyblais** [comment]
Hi @Fodoj,

This was introduced in this PR which was a security-related fix: https://github.com/mattermost/mattermost-server/pull/9063.

Would you be open to creating a Feature request Issue for this in Uservoice?

**Comment by amyblais** [comment]
Closing this Issue as there hasn't been activity on this for a while. 

Please [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html).

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
