### ISSUE TITLE
mattermost-push-proxy recommends Ubuntu 14.04

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost-server#10133]
The requirements section for the [mattermost-push-proxy](https://github.com/mattermost/mattermost-push-proxy) recommends Ubuntu 14.04, which is ending support in April. This should be updated to a newer version of Ubuntu.

**Comment by cpanato** [comment]
We need to update the doc for the latest Ubuntu

**Comment by amyblais** [comment]
Sounds like the docs need updating, so I opened an Issue in the docs repo: https://github.com/mattermost/docs/issues/2481.
