### ISSUE TITLE
[Help Wanted] [MM-13828] Initialize each unit test with a default config.json

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10132]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13828)

Unit tests, by default, run using the `config/config.json` found in the local working directory. On CI, this is not an issue since the file is missing and the instantiated `App` falls back to the `config/default.json`. For developers, however, tweaks in their `config/config.json` can break unit tests in mysterious ways -- e.g. try enabling support for subpaths.

This ticket captures the work required to ensure that each unit tests runs with a default config. The `testlib` package should likely extend some helper methods for running app from a fresh temporary directory into which the `default.json` has been copied. Any changes the unit test might do that result in saving the config.json will then be isolated from future tests, and any changes the developer might have configured for their local setup will no longer impact unit tests.

**Comment by sandlis** [comment]
Is it okay if I give it a try?

**Comment by hanzei** [comment]
Surely @sandlis! :tada: Let us know, if you have any questions. 
Feel free to join on the [Mattermost Community Server](https://community.mattermost.com) and ask questions or propose changes there.

**Comment by sandlis** [comment]
@hanzei Posted my approach here: https://pre-release.mattermost.com/core/pl/6ahinrjgbfyubf43rq1i4a3yxw
Waiting for a response on this.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/10261.

Thank you very much to @sandlis for this awesome contribution!
