### ISSUE TITLE
[Help Wanted] [MM-12746] Migrate user update actions from user_actions.jsx to redux

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10148]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12746)

Part of [https://mattermost.atlassian.net/browse/MM-12581]

* updateUser
* updateUserNotifyProps
* updateUserRoles
* updateActive
* updatePassword
* uploadProfileImage
* autoResetStatus
* switchFromLdapToEmail

----
Since switching to redux we've been moving all the component actions into the redux stores. There are still a bunch of older actions that need to be migrated. The key change that needs to be made is getting rid of functions (primarily located in the actions directory of the web app code) are directly accessing and dispatching redux actions using the global store instance. Often these functions will be imported by a component and used directly.

If needed convert the action to be a redux action, take a look if the action already exists in `mattermost-redux` and prefer the use of the library one unless you need to combine it with other actions into one view action.

Then update all the components that makes use of the action and finally add/update/delete the appropriate *unit tests*

\_\_\_\_\_\_\_

Example: you may have a component and activity such as

```
// actions/foo_actions.js
import \* as FooActions from 'mattermost-redux/actions/foo';

import store from 'stores/redux_store';

export function doSomething()

\{ return store.dispatch(FooActions.doSomething()); \}

// components/my_button.js
import React from 'react';

import

\{doSomething\} from 'actions/foo_actions';







export default class MyButton extends React.PureComponent \{




render() \{




return <button onClick=\{doSomething\}

>

\{'Click me\!'\}</button>;




\}




\}




```

We should never be importing the global instance of the store directly. Instead, its dispatch method should be accessed through a mapDispatchToProps function passed to react-redux's connect function. Generally, this will also remove the need to have a file like `actions/foo_actions.js` or at least remove a significant amount of code from it. In this example, the correct code will look like

```




// components/index.js




import \{connect\} from 'react-redux';




import \{bindActionCreators\} from 'redux';







import \{doSomething\} from 'mattermost-redux/actions/foo';







import MyButton from './my_button';







function mapDispatchToProps(dispatch) \{




return \{




actions: bindActionCreators(\{ doSomething, \}),




\};




\}







export default connect(null, mapDispatchToProps)(MyButton);







// components/my_button.js




import PropTypes from 'prop-types';




import React from 'react';







export default class MyButton extends React.PureComponent \{




static propTypes = \{




actions: PropTypes.shape(\{ doSomething: PropTypes.func, \}),




\}







render() \{




return <button onClick=\{this.props.actions.doSomething\}>\{'Click me\!'\}

</button>;
\}
\}
```

**Comment by MirlanMaksv** [comment]
I am familiar with migration issues, let me take this one

**Comment by hanzei** [comment]
Thanks @MirlanMaksv! :+1:

**Comment by MirlanMaksv** [comment]
I see a pattern in all actions starting with `update`, they 

1. dispatch an action
2. check the result for having `data` or `error` prop
3. call corresponding callback

There are 5 components (or more) that follow these steps, and updating these components require to do step 2 in all of them. For example, lets take `user_settings_general` component. It uses [updateUser](https://github.com/mattermost/mattermost-webapp/blob/7021e27db50a0ade91b6912bbb41a9c41661224a/actions/user_actions.jsx#L357) action, so I am migrating it to use [updateMe](https://github.com/mattermost/mattermost-redux/blob/dcb1a67afb852973d1ecb1a480381c71ab079292/src/actions/users.js#L932) from `mm-redux/actions/users`. After migrating [submitUser](https://github.com/mattermost/mattermost-webapp/blob/0940976902d975c055a2dd6638f1d89d431ab960/components/user_settings/general/user_settings_general.jsx#L266) function that was using  `updateUser` action looks like this:

```js
submitUser = (user, emailUpdated) => {
    ...
    ...
    this.props.actions.updateMe(user).then(
        ({data, error: err}) => {
            if (data) {
                return Promise.resolve(data);
            } else if (err) {
                return Promise.reject({id: err.server_error_id, ...err});
            }
        }
    ).then(
        onSuccess,
        onError
    );
}
```

I want to ask if I need to duplicate first `.then` block in all components, or I need move the code in `.then` block into a new function. Looks like this in code:

```js
submitUser = (user, emailUpdated) => {
    ...
    ...
    this.props.actions.updateMe(user)
        .then(checkForError)
        .then(
        onSuccess,
        onError
    );
}
```

**Comment by hanzei** [comment]
@saturninoabril Can you please take a look at the questions above?

**Comment by saturninoabril** [comment]
Thanks @hanzei.
@MirlanMaksv Moving it into new onSuccess and onError functions looks neat but since those will be used only once the Promise resolve, I'd prefer to have it inside the `.then`. With minimal change, it can be something like:
```javascript
this.props.actions.updateMe(user).then(({data, error: err}) => {
    if (data) {
        this.updateSection('');
        this.props.actions.getMe();
        const verificationEnabled = this.props.sendEmailNotifications && this.props.requireEmailVerification && emailUpdated;
        if (verificationEnabled) {
            this.setState({emailChangeInProgress: true});
        }
    } else if (err) {
        let serverError;
        if (err.message) {
            serverError = err.message;
        } else {
            serverError = err;
        }
        this.setState({serverError, emailError: '', clientError: '', sectionIsSaving: false});
    }
});
```

**Comment by MirlanMaksv** [comment]
Ok. Is it OK If I use promise chain moving `data` and `error` checks into first `then` block, and putting callbacks into second? In that way I would not have to touch callbacks

**Comment by saturninoabril** [comment]
@MirlanMaksv Thank you for your contribution!

I'm closing this now.
