### ISSUE TITLE
Add a count for pinned posts header icon

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10145]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10272)

This improvement involves both client-side (ReactJS), server-side (Go) and mobile (React Native) changes:

*Client-side*

Add a count, similar to the channel member icon, to the pinned post icon in the channel header.

The count should increment when a post is pinned and decrement when a post is unpinned.

![image](https://user-images.githubusercontent.com/13119842/51790047-4a60a180-215e-11e9-9b67-bb3ca928a05d.png)

*Server-side*

There are a few implementation options to consider in order to ensure this change won't decrease server performance. We advice loadtesting server-side changes using our [loadtest tool|https://github.com/mattermost/mattermost-load-test].

1. Use a SELECT query the Posts table to update the pinned posts count.
2. Store the pin count in the Channel Props? When a post is pinned then the count increased, when deleted decreased. That way no dedicated SQL query is required. Requires a database migration.
3. Create a separate table for tracking pinned posts. Requires a database migration.

Note that we already send a WebSocket event when a post gets pinned, since users viewing a post getting pinned in a channel see the update in real time.

*React Native*

![image](https://user-images.githubusercontent.com/13119842/51790052-577d9080-215e-11e9-9c6b-ef0e88ac1e10.png)

**Comment by vineelya** [comment]
@esethna  this sounds like an interesting feature. My dev env setup is not working well. :-(

**Comment by hanzei** [comment]
Hey @vineelya,

Thanks for looking into this. :+1: See https://github.com/mattermost/mattermost-server/issues/10121#issuecomment-460036487 for my answer on the dev setup.

**Comment by vineelya** [comment]
@hanzei What is HackFest tag ?  Why did you remove Up For Grabs tag?

**Comment by esethna** [comment]
@vineelya Mattermost is running a "Hackfest" where you can win awesome swag for pull requests, see details here: https://mattermost.com/hackfest2019/

We remove the "Up for Grabs" label when someone is working on the ticket. Let us know if you are not working on this one we can add the label back so someone else from the community can take it.

**Comment by hanzei** [comment]
Hey @vineelya,

I just want to check how your work on this going. Do you have any questions?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by jkl5616** [comment]
Well, this seems to be a very interesting feature! I'd like to work on this.

**Comment by hanzei** [comment]
Awesome! Indeed this is a handy feature. Thanks for working on this :+1:

**Comment by hanzei** [comment]
Hey @jkl5616,

How is your work going? Do you have any questions?

**Comment by jkl5616** [comment]
@hanzei Sorry for late. I am working on this issue right now.
I think that the simplest way to add a pinned posts count is to use `channel/stats` API, like `member_count`.
Will it be an appropriate way to implement?

**Comment by jkl5616** [comment]
@hanzei Can you check for the above question?

**Comment by hanzei** [comment]
@mkraft Can you help with the above question? I'm not certain that this is the right approach.

**Comment by mkraft** [comment]
@jkl5616 Yes I think adding `pinned_count` to `/api/v4/channels/:channel_id/stats` makes a lot of sense.

**Comment by jkl5616** [comment]
> @jkl5616 Yes I think adding `pinned_count` to `/api/v4/channels/:channel_id/stats` makes a lot of sense.

Okay, then I'll do as that approach, thanks!

**Comment by biva** [comment]
@jkl5616 Thanks for your job! Would you also be interested to add a "Pin icon" next to the "Flag" icon? Like this:
![image](https://user-images.githubusercontent.com/9964305/62713451-0bf54a80-b9fd-11e9-82b8-45453f097e31.png)

I submitted an issue but there's no progress on it up to now :( https://github.com/mattermost/mattermost-server/issues/10380

Thanks for your consideration!

**Comment by jkl5616** [comment]
@hanzei @mkraft 
Should UI handle both newer and older `/api/v4/channels/:channel_id/stats` api?
For example, for the older version of api, we can display original pinned post icon. Otherwise, we can display the icon with count.

**Comment by mkraft** [comment]
@jkl5616 Yes the UI should handle both older and newer versions and showing the original icon or the icon with count sounds sensible to me.

**Comment by bbodenmiller** [comment]
This is handy. Any chance of count of flagged follow ups?
