### ISSUE TITLE
[Help Wanted] [MM-9454] Update transition on send icon

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10157]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9454)

From: https://pre-release.mattermost.com/core/pl/zconkmo4xjgejc8kyi4c86bnnr

Update send icon transition to match attached GIF.

**Comment by courtneypattison** [comment]
I'm on it!

**Comment by hanzei** [comment]
Thanks @courtneypattison! :+1:
