### ISSUE TITLE
Add autocomplete to edit post screen

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10159]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13842)

Repro:
1. send a message on the mobile app
2. Long press, then tap Edit
3. Attempt to type an @-mention or use the channel autocomplete by typing ~

Observed: No autocomplete appears

Expected: Autocomplete appears above the text input box in the edit post screen exactly the same as when typing in the channel or a thread.

**Comment by chuttam** [comment]
Mind if I take this one?

**Comment by hanzei** [comment]
Sure, thanks for working on this @chuttam :+1:
