### ISSUE TITLE
[Help Wanted] [MM-8647] Plugin framework: markdown in plugin system console help text fields

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10167]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8647)

Right now for help text in the plugin system console we only support plain text. Would be nice to use markdown for links, numbering, etc.

----

You can find more information about plugins in our developer documentation: https://developers.mattermost.com/extend/plugins/

If you have any questions, let us know!

**Comment by hanzei** [comment]
@frnkshin is working on this.

**Comment by hanzei** [comment]
Hey @frnkshin,

How is your working going? Can I help with anything?

**Comment by jasonblais** [comment]
This has been closed by https://github.com/mattermost/mattermost-webapp-2467

@frnkshin let us know if you'd be interested taking on another introductory plugin ticket? There are a few open here: https://github.com/mattermost/mattermost-server/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22Difficulty%3A+Introductory%22+label%3A%22Up+For+Grabs%22
