### ISSUE TITLE
Show rendered emojis in the text composition areas

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10163]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13844)

Repro:
1. Type a message containing an emoji (either typed out or selected using the emoji picker)

Observed: emojis do not render in the text area, instead remain as text until they are posted

Expected: 
Emojis turn into rendered emojis in the text area, when
1) They are selected in the emoji picker
2) They are selected from the emoji autocomplete
3) They are typed in full with the trailing colon (ie ":smile:")

![Uploading image.png…]()

Once converted to an emoji, pressing backspace removes the emoji from the text area

Note that this should apply to the center pane text area, right-hand side text area, edit post modal, edit channel header modal, and edit channel purpose modal.

**Comment by gabrieljackson** [comment]
I will grab this one!

**Comment by hanzei** [comment]
Great, thanks @gabrieljackson! :+1: :tada:

**Comment by esethna** [comment]
Hi @gabrieljackson just checking how this is going?

**Comment by cpoile** [comment]
I'll take this one!

**Comment by hanzei** [comment]
Thanks @cpoile! :tada:

**Comment by ChrisDobby** [comment]
I'll take this if that's OK?

**Comment by hanzei** [comment]
Sure, that's great :tada: You might want to take inspiration from https://github.com/mattermost/mattermost-webapp/pull/2634

**Comment by ChrisDobby** [comment]
Is this along the right lines?

![textbox-with-emoji](https://user-images.githubusercontent.com/434389/73561763-81445400-4451-11ea-8579-1c23409eadb9.gif)

**Comment by hanzei** [comment]
That looks amazing @ChrisDobby :tada: 

Feel free to open a PR soon so people can try it out and provide more in depth feeback.

**Comment by ChrisDobby** [comment]
Finally got around to creating a PR!

**Comment by esethna** [comment]
@ChrisDobby let us know if you're still working on this and I can reassign to you :)

**Comment by ChrisDobby** [comment]
I can't believe I forgot about this! If it's OK I'd like to finish this off @esethna ?

**Comment by esethna** [comment]
Absolutely, thanks @ChrisDobby!
