### ISSUE TITLE
Add autocomplete to edit channel screen

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10160]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13843)

Repro on mobile:
1. tap on a channel name to open the channel menu
2. Tap Edit Channel
3. In the "Header" section, attempt to type an @-mention or use the channel autocomplete by typing ~

Observed: No autocomplete appears

Expected: Autocomplete appears above the text input box in the "Header" section, exactly the same as when typing in the channel or a thread.

Note: The autocomplete should not work in the "Name" or "Purpose" fields of the Edit Channel screen, since these fields cannot be interacted with in the same way as the channel header.

**Comment by hahmadia** [comment]
I'll take a look at this :)

**Comment by hahmadia** [comment]
Complete! Awaiting code review and testing on iPhone.
