### ISSUE TITLE
Allow plugins to have a completely custom system console settings page

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10168]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11831)

Right now, plugins can use the plugin manifest (plugin.json) to create a System Console settings page by listing a number of settings and their types (text, boolean, dropdown, etc.). This works well for a lot of basic cases but does not allow for a lot of customization.

To let plugins have more control over what settings they can expose to admins, add the ability for plugins to completely replace their system console settings page with a custom built React component/view.

This will entail adding a client-side register function (something akin to `registerSystemConsolePage`) that receives a React component as an argument and then renders this component instead of the regular generated System Console page for the plugin.

You'll likely to need work in these areas:
* https://github.com/mattermost/mattermost-webapp/blob/master/plugins/registry.js
* https://github.com/mattermost/mattermost-webapp/tree/master/components/admin_console
* https://github.com/mattermost/mattermost-server/blob/master/model/manifest.go

----

You can find more information about plugins in our developer documentation: https://developers.mattermost.com/extend/plugins/

If you have any questions, let us know!

**Comment by amassaro** [comment]
I'd like to grab this one.

**Comment by hanzei** [comment]
Hey @amassaro,

How is your work on this issue going? Do you have any questions?

**Comment by amassaro** [comment]
No questions at this time. I have been asking relevant questions to @jwilander through DM on MM.

**Comment by hanzei** [comment]
Hey @amassaro,

Just checking if you are still working on this? Can we help with anything?

**Comment by Hyaxia** [comment]
Is someone working on this one?

**Comment by hanzei** [comment]
Surely @Hyaxia :+1:

**Comment by hanzei** [comment]
No. Do you want to take over this ticket @Hyaxia?

**Comment by Hyaxia** [comment]
@hanzei Then I will try to tackle it.
Not sure how much time it should take, considering I'll have to dive into the plugins side of mattermost which is new to me, but I hope not too long.

**Comment by Hyaxia** [comment]
Sorry for this back and forth, but as time passes I don't think I can manage to finish it in time, got too much to deal with ATM.

**Comment by hanzei** [comment]
Hey @Hyaxia,

No problem, I added the `Up For Grabs` label back. Thanks for the heads up. :+1:

**Comment by lieut-data** [comment]
We're pivoting on this front with respect to the system console, since we don't want plugins to /completely/ replace their own configuration (we still want to programmatically render an enable/disable option). This ticket is subsumed by https://github.com/mattermost/mattermost-server/issues/10320.
