### ISSUE TITLE
[MM-13388] Tapping outside of post textbox should execute actions on other elements

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10162]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13388)

Repro steps on mobile:
1) Tap on the post textbox to bring up the keyboard
2) Tap outside of the post textbox on an existing post

Expected: Any action should be executed with the keyboard open and then close the keyboard, for example: The keyboard closes and the thread view opens from tapping on that post. Same with long press, keyboard closes and post menu appears.
Observed: The keyboard closes, but the action does not get executed

Note: The same expected should apply to the "Jump to" channel search results

**Comment by enahum** [comment]
I'm doing this one
