### ISSUE TITLE
[Help Wanted] [MM-9622] Plugin framework: allow plugins to create link tooltips

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10172]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9622)

Below is an example of what the link tooltip may look like: 

![image](https://user-images.githubusercontent.com/13119842/51839355-004efb80-22d7-11e9-9858-5c8e3deb14ed.png)

Though optional, we highly recommend submitting a pull request for the Mattermost Demo Plugin that adds link tooltips based on the code changes for this ticket, showcasing the new functionality: https://github.com/mattermost/mattermost-plugin-demo

**Comment by kosgrz** [comment]
It's a very interesting ticket. I could do it.

**Comment by kosgrz** [comment]
Hey @hanzei . I have one question. Should plugins be able to customize the position, delay amount and the distance between the tooltip and the link? Or only content of the tooltip should be customizable?

**Comment by hanzei** [comment]
Hey @kosgrz, Thanks for the questions. I'm passing this one over to @jasonblais as the is the PM of this ticket.

**Comment by jasonblais** [comment]
Hey @kosgrz - excellent question. And thanks for picking up this ticket!

Would you have use cases in mind where it would be good to customizing those aspects of the tooltip?

We could customize, say, the delay and the distance, but if we had a good default value for each, I'm wondering if plugin creators would need to customize it.

**Comment by kosgrz** [comment]
Hey @jasonblais. I have two use cases in mind where the delay might be relevant.

For example, a plugin creator might want to create requests to external API's every time, when the custom tooltip is shown. In this situation, the delay to show the tooltip should be a little longer to avoid creating the tooltip every time when the mouse incidentally enters the link.

Another use case would be when a plugin creator puts just simple text in the tooltip. In that case, we could allow him to make the delay as short as possible.

What do you think about this?

**Comment by jasonblais** [comment]
Thanks @kosgrz for the additional context, very helpful.

At the moment, when you hover icons in the channel header (e.g. pin icon, flag icon), there is a slight delay until the tooltip is shown.

Would that delay be sufficient for both use cases - when an external API is called and when a simple text tooltip is displayed, including when the mouse incidentally enters the link?

**Comment by kosgrz** [comment]
@jasonblais you're right. The default delay is sufficient. There is no need to customise these params. I will create PR soon!

**Comment by jasonblais** [comment]
Sweet, thanks @kosgrz! :tada:
