### ISSUE TITLE
[Help Wanted] [MM-13851] Add a UserWasCreated(c *plugin.Context, user *model.User) hook for server-side plugins

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10174]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13851)

Add a UserWasCreated(c *plugin.Context, user *model.User) hook for server-side plugins.

This allows plugins to, for instance, inform users about their existence.

**Comment by kosgrz** [comment]
I could take this as my first `Go` issue.

**Comment by 090max** [comment]
I m ready for this

**Comment by hanzei** [comment]
Hey @090max,

@kosgrz is allready working in this. Would you mind looking into [another go ticket](https://github.com/mattermost/mattermost-server/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Up+For+Grabs%22+label%3AGo) or a [ReactJS ticket](https://github.com/mattermost/mattermost-server/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Up+For+Grabs%22+label%3AReactJS) if you are familiar with this framework?

**Comment by 090max** [comment]
Ok
