### ISSUE TITLE
Plugin framework: Add an npm watcher that redeploys the webapp side of plugins on changes

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10171]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13850)

The goal is to improve continuous development experience for plugin authors

**Comment by hanzei** [comment]
PR: https://github.com/mattermost/mattermost-plugin-starter-template/pull/39

**Comment by cpoile** [comment]
Implemented here: https://github.com/mattermost/mattermost-plugin-jira/pull/255. Will move to plugin-starter-template, demo, and sample after its been used for a bit.
