### ISSUE TITLE
Add confirmation dialog when posting a message with `at-channel`

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10185]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13849)

Currently the webapp displays a confirmation dialog when posting a message with an `at-channel` `at-all` mention in a channel with over 5 members.

We need to add this confirmation dialog to the mobile app.

Note this dialog is enabled/disabled by the System Console config "Show @channel and @all confirmation dialog" (`EnableConfirmNotificationsToChannel`)

**Comment by courtneypattison** [comment]
I'll try this one :) I've looked into it a little bit and am wondering if there are any shared utils between `mattermost-webapp` and `mattermost-mobile`. Specifically, I would like to use `containsAtChannel()` from `mattermost-webapp` `post_utils`. Should I just copy this function and its dependencies over?

**Comment by jasonblais** [comment]
Thank you @courtneypattison!

@hmhealey @enahum would you know the answer to Courtney's question?

**Comment by enahum** [comment]
You could move that function to mattermost-redux and then use the same reference in both the webapp and mobile

**Comment by courtneypattison** [comment]
@enahum Thank you! I guess it's time to learn redux :) Also, I forgot to ask, are there any dummy users I can add to a test channel in community.mattermost.com to make it a channel with more than 5 users?

**Comment by jasonblais** [comment]
> are there any dummy users I can add to a test channel in community.mattermost.com to make it a channel with more than 5 users?

Not on community.mattermost.com, but we have a public test instance that has several test accounts, would you be open to creating an account there? I've attached a screenshot of some of the test users and an invite link for the test instance is here: https://mysql.test.mattermost.com/signup_user_complete/?id=353fff15eeccb99b54c30158c43e4ee6

![image](https://user-images.githubusercontent.com/13119842/55660667-8a36ab80-57d5-11e9-8045-d74630c0b2a8.png)

**Comment by courtneypattison** [comment]
@jasonblais That is perfect! Thank you!

**Comment by hmhealey** [comment]
> I guess it's time to learn redux

It's good to know, but you might not need it for just this. Despite the name of that library, it contains a bunch of shared code alongside our Redux stuff.

**Comment by hanzei** [comment]
Hey @courtneypattison,

How are you doing with this ticket? Did the test server work for you? Do you have further questions?

**Comment by courtneypattison** [comment]
@hanzei Sorry! I've been busy and haven't made much progress on this ticket. I should have time next week but feel free to put it up for grabs in case someone else wants to give it a shot :)

**Comment by hanzei** [comment]
Hey @courtneypattison, Thanks for the heads up! I've made this ticket available for the public again, but it would be great, if you work on this when you have the time.

**Comment by hahmadia** [comment]
I'll take a look into this.
Thanks :)

**Comment by hanzei** [comment]
Awesome, thanks @hahmadia :tada:

**Comment by hahmadia** [comment]
@hanzei Completed. Just waiting for a code review and help with a problem I encountered.
Thanks :)
