### ISSUE TITLE
Support for Android split screen

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10186]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10281)

GitHub issue: [https://github.com/mattermost/mattermost-mobile/issues/1097]

Repro:
1. Open the app on your Android device
2. Hold down the "recent apps" button

Observed: Screen will split with a pop-up error "App might not work in split screen" and then shows MM icon but it's frozen. You have to kill the app and re-open it. (see screenshot)
Expected: App enters split screen mode

**Comment by jkl5616** [comment]
I'd like to start my contribution from this. Can I take this one?

**Comment by hanzei** [comment]
Hey @jkl5616,

Thank for your interest in this project. Surely you can take this one. Let us know, if you have any questions.

**Comment by enahum** [comment]
PR to implement this here https://github.com/mattermost/mattermost-mobile/pull/2898
