### ISSUE TITLE
[Help Wanted] [MM-9478] 508 Compliance: Set focus to the first Edit button of a tab of Account Settings

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10189]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9478)

Set focus to the first Edit button of a tab of Account Settings
- General (Edit of Full Name)
- Security (Edit of Full Password)
- Notifications (Edit of Desktop notifications)
- Display (Edit of Theme)
- Sidebar (Edit of Group unread channels)
- Advanced (Edit of Send messages on CTRL+ENTER)

Reference PR: https://github.com/mattermost/mattermost-webapp/pull/637

**Comment by manland** [comment]
I'm work on this!

**Comment by manland** [comment]
Hi @esethna How to have a reviewer for my [PR](https://github.com/mattermost/mattermost-webapp/pull/2300) ?

**Comment by esethna** [comment]
Thanks @manland, PR looks great! Moved to dev review

**Comment by tejasbubane** [comment]
This can be closed @esethna

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/2300

Thanks for pointing this out @tejasbubane :+1:
