### ISSUE TITLE
[Help Wanted] [MM-13872] UI Automation: Write an automated test using `cypress` for "Create a Team"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10199]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13872)

**Test Key**: TS13872

Help write an automated test using [cypress|https://www.cypress.io/] for the following test case:

Note: This test assumes you already have an account on the server and have permissions to create teams.

1. Log into https://community.mattermost.com 
2. Click hamburger main menu
2. Click `Create a New Team`
3. Enter team name and click `Next`
4. Change the URL if you like (optional) and click `Finish`

Expected:
- You are taken to Town Square of your new team
- Team name displays correctly at top of LHS
- If viewing on browser, URL is correct"

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by adzimzf** [comment]
Hi, I'll take care of this

**Comment by hanzei** [comment]
Awesome @adzimzf! :+1:

**Comment by saturninoabril** [comment]
Thanks @adzimzf for your contribution 🎉 
I'm closing this now.
