### ISSUE TITLE
[Help Wanted] [MM-13381] RN: Add reply option to mobile long press context menu 

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10191]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13381)

Repro:
1) long press on a post in the mobile app

Observed:  Context menu appears but "Reply" is not an option. User has to tap on a post to discover the reply functionality.
Expected: Add "Reply" as an option to the long press context menu so it's more discoverable.

Design: https://projects.invisionapp.com/share/85OBMG2YUSE#/screens/322747599
Assets attached for the reply icon

**Comment by courtneypattison** [comment]
I'll try this one :)

**Comment by hanzei** [comment]
Thanks @courtneypattison for taking care of this issue. :rocket:  Let us know if you have questions.
