### ISSUE TITLE
slack import: is message threading implemented?

### ISSUE THREAD

**Issue by ftc2** [mattermost/mattermost-server#10203]
#### Summary
Threaded messages imported from slack do not appear as threads/replies.

#### Steps to reproduce
```
Mattermost Version: 5.7.0
Database Schema Version: 5.7.0
Database: postgres
```

`sudo /opt/mattermost/bin/mattermost import slack TEAM_NAME /path/to/slack_export.zip`

This export contained ~130k messages and ~60 users, and it was done on a fresh mattermost installation.

#### Expected behavior
Some messages in the slack export were threaded. After importing into mattermost, they should still be visible in a threaded context.

#### Observed behavior (that appears unintentional) 
After importing into mattermost, the messages are visible. However, their thread context is lost. They just look like normal messages and not replies.

#### Possible fixes
Message threading is obviously supported in mattermost. Are threads from slack just not implemented in the importer, or is this a bug? Thanks

**Comment by ftc2** [comment]
https://github.com/mattermost/mattermost-server/blob/6325c5b569e00bd1e5af58190868994a503f84ec/app/slackimport.go#L51-L63

actually, i don't see `thread_ts` in there, so i'm guessing it's not implemented.

i think it would be really nice to have...

**Comment by amyblais** [comment]
Hi @ftc2,

Yes I believe that importing threads is not supported yet. Please [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html). If you submit a feature request, please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by ftc2** [comment]
thank you. i made a uservoice suggestion for it:
https://mattermost.uservoice.com/forums/306457-general/suggestions/36721660-implement-threads-in-slack-import-tool

in slack, replies are standalone objects. it works via a `thread_ts` (thread timestamp) attribute. `thread_ts` refers to the `ts` (timestamp) of the parent post. if a post has `thread_ts` == `ts`, then it is the beginning of a thread.

possible approach: 
import all posts except for ones where `thread_ts` != `ts` (as these are replies to other posts). once that's done, go back and import the replies since their parents will have already been imported.

**Comment by amyblais** [comment]
Thank you for opening the feature request! If you're interested in implementing any of these features, please feel free to open a pull request and/or ask any questions.
