### ISSUE TITLE
[Help Wanted] [MM-13909] UI Automation: Write an automated test using `cypress` for "Escape should not close modal when an autocomplete drop down is in use"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10205]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13909)

**Test Key**: M13909

Help write an automated test using cypress for the following test case:
Note: This test assumes you already have an account on the server and have logged in.

1. Post a message
2. Hit the up arrow to open the "edit modal"
3. In the modal type @ and note the user autocomplete is visible
4. Press the escape key, observe autocomplete closes
5. In the modal type ~ and note the channel autocomplete is visible
6. Press the escape key
7. In the modal click the emoji picker icon
8. Press the escape key

Expected:
- On 4. the user auto-complete drop down closes but the edit modal remains open
- On 6. the chanel auto-complete drop down closes but the edit modal remains open
- On 8. the emoji picker closes but the edit modal remains open

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by manland** [comment]
I'm work on this!

**Comment by saturninoabril** [comment]
Thanks @manland for your contribution!
