### ISSUE TITLE
incomplete search results

### ISSUE THREAD

**Issue by ftc2** [mattermost/mattermost-server#10204]
#### Summary
Message searching returns only a subset of expected results (possibly only the *n* most recent results).

#### Steps to reproduce
```
Mattermost Version: 5.7.0
Database Schema Version: 5.7.0
Database: postgres
(no license)
```

I imported ~130k messages and ~60 users from slack into a fresh mattermost installation for testing.

I then tried searching from the Mattermost macOS client.

#### Expected behavior
When searching 'foo', return *all* messages containing the term 'foo'.

#### Observed behavior (that appears unintentional) 
Search results appear to be limited to recent messages.

The result set returned appears to be correct and chronologically contiguous with no omissions between the first and last results, but there are messages missing beyond the last result.

Said another way, it appears to be correctly returning posts with indices in the range [0, *n*], but posts in the range [*n*+1, *end*] are not in the results (index 0 corresponds to the most recent message).

I have not determined if *n* is the same for every search query.

I've verified that the older messages do exist in the mattermost db. I can find them by searching for them more specifically.

#### Possible fixes
Is it capped in the SQL query or something?

**Comment by amyblais** [comment]
Hi @ftc2,

Here is more information on how Search currently works: https://docs.mattermost.com/help/getting-started/searching.html.

There are limitations and issues in the Search function in general, and we have several Jira tickets open to improve this feature (https://mattermost.atlassian.net/browse/MM-5466).

If you want to, you could maybe consider using Elasticsearch: https://docs.mattermost.com/deployment/elasticsearch.html.

**Comment by ftc2** [comment]
hi @amyblais,

thank you for your reply. i have read the docs about searching, but it doesn't help.

is the *number* of search results returned one of the limitations you're aware of? like, is it capped for some reason? search works great for the first however many results, but it's just not returning ones beyond that (chronologically).

elasticsearch support is an enterprise-only feature, correct? i don't have an enterprise license, otherwise i'd happily try it.

**Comment by amyblais** [comment]
@grundleborg Do you know the answer to the above question - "search results appear to be capped at 100 results for some reason. i can never get more than 100 for any query, and scrolling to the end of the results doesn't load more. do you know where i might look to un-cap this?"

**Comment by ftc2** [comment]
i opened a uservoice suggestion to add unlimited search results to team edition: https://mattermost.uservoice.com/forums/306457-general/suggestions/36721723-unlimited-search-results

Harrison Healey had this to say (paraphrased):

you can see that paging isn't supported:

https://github.com/mattermost/mattermost-server/blob/master/app/post.go#L821

and the sql uses `LIMIT 100`:

https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/post_store.go#L834

**Comment by amyblais** [comment]
Hi @ftc2, 

Thank you for opening the feature request!
