### ISSUE TITLE
Different browsers show different menu items

### ISSUE THREAD

**Issue by alecisec** [mattermost/mattermost-server#10219]
#### Summary
Mattermost (browser) will show different menus depending on browser, using the same login. i.e. Edge will show 'system console' and 'add members to team' whereas chrome will not.

#### Steps to reproduce
Version 5.5.0, browsers Chrome, IE, Edge, Firefox

#### Expected behavior
What I believe to be websocket errors prevent menu items from appearing, it's unclear why this is tied to websocket connectivity. Other websocket-reliant behavior (i.e. 'user is typing' messages) work correctly in this environment.

#### Observed behavior (that appears unintentional) 
Items do not appear on the menu

#### Possible fixes
I suspect this is a websocket issue, I've had the issue before and resolved it by populating the config values WebsocketURL and AllowCorsFrom - these however, have been checked this time and appear to be set correctly.

**Comment by amyblais** [comment]
Hi @alecisec,

Can you help share your Mattermost server logs as well as Chrome console errors?

**Comment by amyblais** [comment]
Hi @alecisec, I'll close this Issue for now as there haven't been updates here. Please re-open this Issue with relevant additional details if the problem persists.

**Comment by alecisec** [comment]
There is no log events which are relevant as this is a client-side rendering issue. The URI for each of the menu items can be reached but aren't presented in the menu

**Comment by amyblais** [comment]
@alecisec 

Are you using a Proxy server?
Is the Mattermost server internal or external?
Do you see any Console errors in Firefox or Chrome?

**Comment by alecisec** [comment]
The mattermost is hosted on EC2 behind a load balancer (ALB), 
No proxy, 
will check console for errors soon

**Comment by amyblais** [comment]
Hi @alecisec, would you be open to posting this on our Forum site for further troubleshooting: https://forum.mattermost.org/? Our community members are more active there and somebody will probably have additional thoughts on what the issue might be. Please include relevant console errors.

**Comment by amyblais** [comment]
Hi @alecisec, here are instructions on how to log in via a web browser and generate an HAR so we can verify that the appropriate requests are being forwarded: https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting.

**Comment by alecisec** [comment]
After some troubleshooting we determined this is caused by a combination of Forcepoint and using either Chrome or Firefox, by using either Edge behind Forcepoint or any browser on a separate connection the menu items appear normally. So it appears it's related to websockets however the browsers display no error and the 'User is typing....' updates work fine so it's still something of a mystery.

**Comment by amyblais** [comment]
Hi @alecisec, apologies for not being able to resolve this case... I'll close this issue for now as there is a workaround.
