### ISSUE TITLE
Notifications with self-hosted push proxy not showing sender name/channel name

### ISSUE THREAD

**Issue by tjhorner** [mattermost/mattermost-server#10220]
#### Summary

When using a self-hosted push proxy (any version — I have tested with multiple 3.x, 4.x, and 5.x versions, including latest master), the notification title does not appear. This is the same for both DMs and channels within teams.

This doesn't seem to be related to #5416.

#### Steps to reproduce

1. Set up a push proxy server (v5.4.0)
2. Configure it to a custom Mattermost client's (v1.16.0) needs (e.g. set up APNS cert/FCM key)
3. Point your Mattermost server (v5.7.0) to that proxy server
4. Send a message to yourself from another user

#### Expected behavior

The notification should look like this, with the sender name intact (this notification was sent from Mattermost's HPNS):

<img width="472" alt="image" src="https://user-images.githubusercontent.com/2646487/52192867-0413de00-2801-11e9-80e1-23fe388d07b1.png">

(Unable to test on iOS since Mattermost's HPNS does not work with custom iOS clients)

#### Observed behavior (that appears unintentional) 

Notifications appear without sender names on both Android and iOS (sent with self-hosted push proxy server):

<img width="472" alt="image" src="https://user-images.githubusercontent.com/2646487/52192951-7e446280-2801-11e9-8ed8-730273815b0e.png">

Notice how the sender name was replaced with the app's name ("SRND Chat"). The second notification is from the "Town Hall" channel.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/2646487/52193045-fb6fd780-2801-11e9-8804-411e26450c42.png">

It's worth noting that the threads are also incorrect on the iOS app (everything is grouped in to the same thread, probably with no ID).

<img width="472" alt="image" src="https://user-images.githubusercontent.com/2646487/52193159-949eee00-2802-11e9-8104-2b2bba021eac.png">

The app also tends to ask existential questions due to this bug.

#### Possible fixes

I took a look at both the mobile client's code and the push proxy's code — I couldn't find any specific pieces that may be the culprit, but I can confirm that it's the push proxy's fault (notifications received on the same client build from the HPNS server appear just fine, just not the ones from the custom server).

Neither the push proxy nor the Mattermost server produce any error/warning logs.

**Comment by tjhorner** [comment]
Some new developments. I tried running it locally from source on my MacBook. It worked just fine — name showed up and everything. I packaged it with `make dist` and ran it on our production server. It didn't work! I'm thinking it has something to do with either it being in a Docker container or it being accessed via HTTP. I have no idea why either of those could cause this weird issue, though.

**Comment by tjhorner** [comment]
@amyblais Thanks. I think I've determined that it only happens within a Docker environment, which is really weird. It happens with both the official docker image for the push proxy as well as our own build.

**Comment by amyblais** [comment]
@tjhorner,

A community member took a look at this and had some questions:

What does "it" refer to in your second message?
Where is the Dockerfile which builds https://hub.docker.com/r/mattermost/mattermost-push-proxy?
Any other examples for "existential questions"? (Might help to determine their origin.)

**Comment by tjhorner** [comment]
@amyblais 

I edited my second comment for clarification.

The Dockerfile for the push proxy is here: https://github.com/mattermost/mattermost-kubernetes/blob/master/docker/push-proxy/Dockerfile

The existential questions part was sort of a joke — a team member sent me that message and the sender name didn't show, so it seemed as if the app was asking me directly

**Comment by tjhorner** [comment]
Another update: We started running this on top of our VM (instead of Docker) and sender name shows up in notifications. This works for now, but it would be nice to see why this happens only in Docker containers. Such a bizarre bug!

**Comment by amyblais** [comment]
Hi @tjhorner,

From a community member:

You should, if possible, try to look at Android device logs (e.g. with adb) to check if the clients receive different push notifications (e.g. missing a title) with different push proxies. Just to make sure that it's not the client doing different things for different proxies - even if the messages are the same.

**Comment by tjhorner** [comment]
Sorry for the delay, @amyblais. I can debug the notifications sometime next week. For the meantime, we discovered that [this Docker image](https://github.com/jostyee/docker-mattermost-push-proxy) works perfectly fine.

**Comment by amyblais** [comment]
Closing this for now as there haven't been updates for a while. If the problem persists, please re-open this issue and we'll continue to investigate.
