### ISSUE TITLE
C syntax highlighting

### ISSUE THREAD

**Issue by Evils-Devils** [mattermost/mattermost-server#10221]
#### Summary
The `C` keyword does not work for code block syntax highlighting.

#### Steps to reproduce
Tested on server version 5.7.0 with desktop client version 4.2.0.

#### Expected behavior
Correct syntax highlighting on code blocks when the `C` or `c` keyword is used.

#### Observed behavior (that appears unintentional) 
While the `cpp` keyword does apply syntax highlighting,
it shows `C/C++` as the language, and from that i would expect `C` to be a valid keyword to use this.

#### Possible fixes
highlight.js "supports" C as an [alias](https://github.com/highlightjs/highlight.js/blob/master/src/languages/cpp.js#L98) for C++ but this is [not used](https://github.com/mattermost/mattermost-webapp/blob/master/utils/syntax_highlighting.jsx#L72).

**Comment by hanzei** [comment]
Hey @Evils-Devils,

Thanks for the report! I can confirm that the highlighting doesn't work for `c`. Would you be open to submitting a fix for this?

**Comment by Evils-Devils** [comment]
If i thought i'd be comfortable building the server and webapp from source i'd have done so but this stuff's a bit out of my league.
I'm hoping someone with a build/test environment set up wants to give this a try.

**Comment by amyblais** [comment]
Opened a bug ticket here: https://mattermost.atlassian.net/browse/MM-13951.

**Comment by amyblais** [comment]
Closing this as a Help Wanted Issue was opened here: https://github.com/mattermost/mattermost-server/issues/10229.
