### ISSUE TITLE
[Help Wanted] [MM-13951] Allow "C" to be used for code block syntax highlighting

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10229]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13951)

Original report: https://github.com/mattermost/mattermost-server/issues/10221

*Summary*
The `C` keyword does not work for code block syntax highlighting.

*Steps to reproduce*
Tested on server version 5.7.0 with desktop client version 4.2.0.

*Expected behavior*
Correct syntax highlighting on code blocks when the `C` or `c` keyword is used.

*Observed behavior*
While the `cpp` keyword does apply syntax highlighting,
it shows `C/C++` as the language, and from that i would expect `C` to be a valid keyword to use this.

*Possible fixes*
highlight.js "supports" C as an alias (https://github.com/highlightjs/highlight.js/blob/master/src/languages/cpp.js#L98) for C++ but this is not used (https://github.com/mattermost/mattermost-webapp/blob/master/utils/syntax_highlighting.jsx#L72).

**Comment by manland** [comment]
I'm work on this!

@hanzei It's possible to add `sh` as `bash` alias ? Every time I need to edit my previous post...

**Comment by crspeller** [comment]
@manland Go for it. I think that's useful.
