### ISSUE TITLE
Links ending with an underscore are not properly auto-detected

### ISSUE THREAD

**Issue by nlowe** [mattermost/mattermost-server#10222]
#### Summary
Links ending with an underscore are not properly auto-detected

#### Steps to reproduce
1. Post a message with a link ending with an underscore
  * For example: `https://app.sharebase.com/#/document/5163072/share/3-3fs0NF4kyFzTW7ikiH4--bc7RN8Y_`

#### Expected behavior
The link is detected and rendered correctly. When clicked, it opens the URL with an underscore at the end of the path

#### Observed behavior (that appears unintentional) 
The underscore on the end of the link is not included in the automatic link detection:

![image](https://user-images.githubusercontent.com/794251/52216972-80d8a380-2865-11e9-9eca-b98e443d78d2.png)

When clicked, the underscore is left off. I can work around this by manually making the link, which is cumbersome: 

```markdown
[https://app.sharebase.com/#/document/5163072/share/3-3fs0NF4kyFzTW7ikiH4--bc7RN8Y_](https://app.sharebase.com/#/document/5163072/share/3-3fs0NF4kyFzTW7ikiH4--bc7RN8Y_)
```

I also noticed that the link in the preview block is correct, it's just the converted link in the message that is missing the underscore:

![image](https://user-images.githubusercontent.com/794251/52217314-2be95d00-2866-11e9-80c5-9f0b18fac695.png)

#### Possible fixes
This appears to be an issue with the markdown [auto-linker](https://github.com/mattermost/mattermost-server/blob/85c60f1402ecb14d647bc869d2af884342edbb48/utils/markdown/autolink.go#L100). When adding a test for it:

```diff
diff --git a/utils/markdown/autolink_test.go b/utils/markdown/autolink_test.go
index 997124338..c04589f8d 100644
--- a/utils/markdown/autolink_test.go
+++ b/utils/markdown/autolink_test.go
@@ -112,6 +112,12 @@ func TestParseURLAutolink(t *testing.T) {
                        Position:    5,
                        Expected:    "http://www.example.com",
                },
+               {
+                       Description: "link ending with an underscore",
+                       Input:       "This is http://example.com/foo_",
+                       Position:    12,
+                       Expected:    "http://example.com/foo_",
+               },
                {
                        Description: "link in asterisks",
                        Input:       "This is **ftp://example.com**",
```

It fails in the manner I'm seeing:

```golang
$ go test ./utils/markdown/...
--- FAIL: TestParseURLAutolink (0.00s)
    --- FAIL: TestParseURLAutolink/link_ending_with_an_underscore (0.00s)
        autolink_test.go:150:
                Error Trace:    autolink_test.go:150
                Error:          Not equal:
                                expected: "http://example.com/foo_"
                                actual  : "http://example.com/foo"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -http://example.com/foo_
                                +http://example.com/foo
                Test:           TestParseURLAutolink/link_ending_with_an_underscore
FAIL
FAIL    github.com/mattermost/mattermost-server/utils/markdown  0.104s
```

Is there a good reason for ending the link on an underscore?

**Comment by amyblais** [comment]
Actually I was able to reproduce this, so I opened a ticket here: https://mattermost.atlassian.net/browse/MM-13990.

**Comment by amyblais** [comment]
Hi @nlowe, letting you know that the ticket was closed for now as currently this follows GitHub markdown standard and a special case for this would add complexity for limited value.

**Comment by nlowe** [comment]
@amyblais Yeah I saw the update on the Jira ticket. I'll talk to my application developers to see if we can change our link format to be supported by a wider variety of markdown implementations.
