### ISSUE TITLE
Write an automated test using `cypress` for "Tutorial - Navigation and Links"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10234]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13989)

**Test Key**: On13989

Help write an automated test using [cypress|https://www.cypress.io/] for the following test case:

Note: This test assumes you already have an account on the server and have permissions to create teams.

1. Create a new user and observe tutorial in center channel
2. Click on the second navigation dot on the tutorial intro screen, verify second tutorial page displays
3. Click Off-Topic in left-hand-side (LHS)
4. Click on the app icons on the tutorial screen
5. Click the Next button on the tutorial intro screen

Expected:
- Clicking LHS highlights Off-Topic in LHS, but tutorial continues to display.
- Clicking the app icons should take you to the download page for apps.
- Can continue through to finish the tutorial, and then Off-Topic channel displays in center

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by amassaro** [comment]
I'd like to grab this one.

**Comment by saturninoabril** [comment]
@amassaro As mentioned in the [Community UI Automation channel](https://community.mattermost.com/core/pl/6ndsga6ubbdmmqnkrh183z9reo), there's a mismatch between this GH issue and the referenced Jira ticket [MM-13989](https://mattermost.atlassian.net/browse/MM-13989).  I've corrected the content of this issue.

Really sorry about it.

**Comment by hanzei** [comment]
Hey @amassaro,

I just want to check how your work on this going. Do you have any questions?

**Comment by amassaro** [comment]
During the initial confusion of the description discussed above, I had completed the other cypress test, the transitioned to https://github.com/mattermost/mattermost-server/issues/10168. I am still working towards a solution on that one atm. If we need to hand this back off to someone to keep the e2e moving that is fine with me.

**Comment by hanzei** [comment]
There is no time pressure on this ticket @amassaro. Just wanted to check how you are doing.

**Comment by hanzei** [comment]
Hey @amassaro,

Are you still working on this issue?

**Comment by bnoggle** [comment]
I can take this one.

**Comment by hanzei** [comment]
Thanks for taking a shot @bnoggle

**Comment by saturninoabril** [comment]
Thank you @bnoggle!
Closing this issue.
