### ISSUE TITLE
Share extension should search all DMs/GMs on the server

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10231]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13813)

Original report: https://github.com/mattermost/mattermost-mobile/issues/2517

*Steps to reproduce*
1. Share an image using the share extension
2. Search for a Direct Message or Group Message on the server

*Expected behavior*
Share extension should search all DMs/GMs on the server

*Observed behavior*
Search field can search only DMs/GMs open in your sidebar

**Comment by andrewbrown00** [comment]
Designs for the Mobile Share Extensions:

[Android](https://invis.io/59S6KONFPNT#/365108240_Project_Details_-_Android)
[iOS](https://invis.io/59S6KONFPNT#/365108342_Project_Details_-_iPhone)

Please reach out with any questions or concerns 😄

**Comment by enahum** [comment]
Closing as dup of https://github.com/mattermost/mattermost-server/issues/11263
