### ISSUE TITLE
Improve timezone selector component and list of timezones

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10232]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10022)

Timezones must be enabled using the experimental config "ExperimentalTimezone"

______

This ticket is to update the current timezone selector UX in Account Settings > Display > Timezone

1. Update component to a drop down list: 
https://projects.invisionapp.com/share/W6QBT1ZJAFK#/screens/344809032
https://projects.invisionapp.com/share/W6QBT1ZJAFK#/screens/344809033
2. Update list of available timezones to this: https://github.com/dmfilipenko/timezones.json/blob/master/timezones.json
3. When "Automatic" is selected, disable the dropdown: https://projects.invisionapp.com/share/W6QBT1ZJAFK#/screens/344811834/comments

**Comment by R-Wang97** [comment]
I can try this!

**Comment by R-Wang97** [comment]
I can try taking a look at this!

**Comment by hanzei** [comment]
Hey @R-Wang97,

Do are you doing with this ticket? Do you have questions?

**Comment by R-Wang97** [comment]
Hey @hanzei, I've been busy recently, so I haven't had much of a chance to look at it. Could somebody else take over for me?

**Comment by jasonblais** [comment]
Certainly, no worries @R-Wang97! I'll add the `Up for Grabs` label back.

**Comment by Willyfrog** [comment]
I'd like to take a look into this one

**Comment by jasonblais** [comment]
Great, thank you @Willyfrog!

**Comment by jasonblais** [comment]
@lieut-data confirming point 2 in [issue description](https://github.com/mattermost/mattermost-server/issues/10232#issue-406869226) still applies following latest changes to timezones.json?

**Comment by lieut-data** [comment]
Not the timezones.json, specifically, but to the hard-coded list now in the server: https://github.com/mattermost/mattermost-server/blob/master/services/timezones/default.go

**Comment by hanzei** [comment]
Hey @Willyfrog,

How are you doing with this ticket? Do you have any questions?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by lisakycho** [comment]
Hi, I can try to work on this!

**Comment by jasonblais** [comment]
Great, thank you @lisakycho!

**Comment by Willyfrog** [comment]
Hi, sorry @hanzei , life got in the way and was away for quite some time. I see @lisakycho already started, so I can share what I had if that helps him

**Comment by lisakycho** [comment]
@jasonblais, when you say update the list of available timezone, am i just updating the file `services/timezones/default.go` and calling the timezones the same way?

**Comment by jasonblais** [comment]
> when you say update the list of available timezone, am i just updating the file services/timezones/default.go and calling the timezones the same way?

@asaadmahmood or @esethna would you know? I think you're more familiar with this help wanted issue

**Comment by asaadmahmood** [comment]
I think so. @jwilander, can you confirm?

**Comment by jwilander** [comment]
Yes that would be correct, as of https://github.com/mattermost/mattermost-server/pull/10311 the timezones.json was deprecated in favour of the hardcoded list. So if updates to the timezones are needed, it should be done to the hardcoded list.

**Comment by hanzei** [comment]
Hey @lisakycho,

Does the above answers solve your question?

**Comment by lisakycho** [comment]
@jwilander should I make my own struct to hard code this?

**Comment by jwilander** [comment]
There's already a slice of the timezones here https://github.com/mattermost/mattermost-server/blob/master/services/timezones/default.go

You would just need to update that if you need to change the timezones @lisakycho

**Comment by lisakycho** [comment]
@jwilander right but that contains an array of strings while the new timezones are an array of objects, not sure what type to declare for that array if i just replace the data.

**Comment by jwilander** [comment]
I'm not entirely sure, might take some investigation on your part. I think you can just keep it as an array of strings and update it to contain all the timezones in that list under the `utc` fields here https://github.com/dmfilipenko/timezones.json/blob/master/timezones.json#L45

**Comment by hanzei** [comment]
@lisakycho Do you have any outstanding questions?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by vintik** [comment]
@hanzei I'd like to work on this please.

**Comment by hanzei** [comment]
Alle yours, @vintik :+1:

**Comment by saturninoabril** [comment]
Hello @vintik, sorry but I'm currently working on this and finalizing the changes already.  I forgot to make comment on this issue. Would you mind if you look for another help-wanted ticket?

**Comment by esethna** [comment]
@saturninoabril how is this going?

**Comment by hmhealey** [comment]
@saturninoabril Do you happen to have a WIP branch around for this?

**Comment by esethna** [comment]
@saturninoabril do you have a branch with this that we can take over or link to?

**Comment by esethna** [comment]
@vintik looks like Saturn isn't working on this anymore, still interested in taking this ticket?

**Comment by saturninoabril** [comment]
@esethna @hmhealey Sorry for late response. I searched with my branches and I can't find the one on the webapp. That might have wiped out when I replaced my laptop. Here are the [server](https://github.com/mattermost/mattermost-server/compare/master...saturninoabril:timezone-release) and [redux](https://github.com/mattermost/mattermost-redux/compare/master...saturninoabril:timezone-release) branches but I don't think it will be helpful.

**Comment by IndushaS** [comment]
Hello @esethna, I'd like to try and work on this.

**Comment by jasonblais** [comment]
Thanks @IndushaS! :tada:

**Comment by esethna** [comment]
Yay, thanks @IndushaS. How's this going, need any help or guidance?
