### ISSUE TITLE
Desktop client crash on goBack shortcut key in help window

### ISSUE THREAD

**Issue by ookull** [mattermost/mattermost-server#10244]
#### Summary
Mattermost desktop client crashes if _back_ shortcut key is pressed in help window

#### Steps to reproduce
Open help window, click some link and then press alt-leftarrow (common shortcut to navigate to previous page).

#### Expected behavior
No crash

#### Observed behavior (that appears unintentional) 
```
Application: Mattermost 4.2.0
Platform: Linux 4.18.0-3-amd64 x64
TypeError: focusedWindow.goBack is not a function
    at click (.../mattermost-desktop-4.2.0-linux-x64/resources/app.asar/main_bundle.js:12806:25)
    at MenuItem.click (.../mattermost-desktop-4.2.0-linux-x64/resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (.../mattermost-desktop-4.2.0-linux-x64/resources/electron.asar/browser/api/menu.js:29:13)
```

**Comment by amyblais** [comment]
Hi @ookull, I don't have a Linux environment, so I'll ask our team to help test this,

**Comment by amyblais** [comment]
When you say "help window" are you referring to the window that opens when you click the "Help" link in the bottom right corner?

**Comment by ookull** [comment]
> When you say "help window" are you referring to the window that opens when you click the "Help" link in the bottom right corner?

yes

**Comment by hanzei** [comment]
Thanks for the report @ookull. I was able to reproduce the problem.

@amyblais Would you open a ticket for this please?

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-14035.

**Comment by amyblais** [comment]
Hi @ookull,

Letting you know that the above Jira ticket was replaced with this one: https://mattermost.atlassian.net/browse/MM-14349.

Also letting you know that you can follow the progress of this issue also via the Jira ticket I linked above. For the latest updates to the ticket you can add yourself as a watcher. To do this, click on "Start Watching This Issue" in the ticket. This way you’ll be emailed immediately when the ticket status is changed. If you have any issues accessing our Jira instance please let me know.

Let me know if you'd prefer to follow the progress on this issue via the Jira ticket or via this Github Issue?

**Comment by hanzei** [comment]
Hey @ookull,

This issue has been fixed on `master` and will be fixed in the next release of the desktop app.

Closing this one.
