### ISSUE TITLE
[Help Wanted] [MM-14012] UI Automation: Write an automated test using `cypress` for "Focus move to main input box when a character key is selected"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10245]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14012)

**Test Key**: M14012

Help write an automated test using [cypress|https://www.cypress.io/] for the following test case:

Note: This test assumes you already have an account on the server and have permissions to create teams.

1. Left click on any post to move the focus out of the main input box
2. Push a character key such as "A"
3. Open the "..." menu on a post in the main or reply thread to move the focus out of the main input box
4. Push a character key such as "A" 

Expected: Focus is moved back to the main input and the keystroke is captured

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by courtneypattison** [comment]
I'll try to write this test :)

**Comment by hanzei** [comment]
Great @courtneypattison! :+1: Let me know, if you have any questions.
