### ISSUE TITLE
[Help Wanted] [MM-13975] Add Terms of Service and Privacy Policy links to About Mattermost modal

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10242]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13975)

Propose adding Terms of Service and Privacy Policy links to About Mattermost modal.

There isn't currently a way to access either once you're logged in. This was a requirement when reviewing customer feedback, where About Mattermost dialog might be an easy place to add it to.

See screenshots for UI on where the the links should appear, both for webapp and mobile.

##### Webapp:
![image](https://user-images.githubusercontent.com/13119842/52311749-0ea3b400-2976-11e9-8f6f-487d2daebc41.png)

##### Mobile:
![image](https://user-images.githubusercontent.com/13119842/52311755-15322b80-2976-11e9-8d82-faac3f2b3440.png)

**Comment by R-Wang97** [comment]
I can take a look at this!

**Comment by hanzei** [comment]
Great, thanks @R-Wang97! :tada:
