### ISSUE TITLE
[MM-14014] UI Automation: Write an automated test using Cypress for "Recently used emojis are shown 1st"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10246]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14014)

**Test Key**: M14014

Help write an automated test using cypress for the following test case:
1. Select an emoji reaction for post
2. Add a reaction that is not included in the recently used emojis 
3. Open the the emoji reaction list again 

*Expected*:
Emoji selected in step 2. is now listed in the top left in the Recently Used section

**Comment by adzimzf** [comment]
Hi,
I'll take care of this.

**Comment by saturninoabril** [comment]
Sure @adzimzf, thanks!

**Comment by hanzei** [comment]
Hey @adzimzf,

I want to check out how are you going with this ticket. Do you have any questions?

**Comment by adzimzf** [comment]
Hi, @hanzei.
There's no any questions. Sorry for delay, I just went home from long holiday.
But the PR is almost done, just need a few changes to fix.
I'll push it asap.

**Comment by hanzei** [comment]
Thanks for the heads up! Looking forward to your Pr. :+1:

**Comment by saturninoabril** [comment]
Thank you @adzimzf for your contribution.

Closing this now.
