### ISSUE TITLE
[MM-8427] Gitlab Mattermost CLI not usable because i18n Directory is missing 

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10250]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8427)

See original report: https://gitlab.com/gitlab-org/gitlab-mattermost/issues/102
See duplicate ticket for additional context: https://mattermost.atlassian.net/browse/MM-6839

Summary
Can not delete a Team because the Mattermost CLI is missing the i18n Directory

Steps to reproduce
It used to work with Mattermost 3.*, since upgrading to Mattermost 4.0 it stopped working

execute /opt/gitlab/embedded/bin/mattermost --config=/var/opt/gitlab/mattermost/config.json team remove team on Mattermost Server

Expected behavior
Execute the command an delete the Team "team"

Observed behavior
The CLI could not find the i18n directory, I actually could find the i18n directory with the path /opt/gitlab/embedded/service/mattermost/i18n

**Comment by ajeethkannan** [comment]
Hi, I will work on this. I am a new contributor. I would start with this introductory issue.

**Comment by hanzei** [comment]
Given that most of the CLI command have been removed with https://github.com/mattermost/mattermost-server/pull/17995 can this ticket be closed?

**Comment by jasonblais** [comment]
Yea, this is no longer applicable with the new mmctl command. Team is working on updating the docs for GitLab users in the coming weeks.
