### ISSUE TITLE
I don't have an issue with the server I have an issue with the Webapp

### ISSUE THREAD

**Issue by julian-weinert** [mattermost/mattermost-server#10263]
Unfortunately matterost.com redirects me to here to report bugs.
The bug I found has nothing to do with the server.

Why can't people create issues for the WebApp?
Don't you want to improve it?

**Comment by amyblais** [comment]
Hi @julian-weinert, you can report both server and webapp bugs here. You can also post troubleshooting issues on the Forum: https://forum.mattermost.org/.
