### ISSUE TITLE
[MM-14105] Long-press menu cannot be dragged up when rotating device to landscape while menu is open

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10275]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14105)

When rotating the device form portrait to landscape while the long press menu is open, the menu can no longer be dragged up. 

This will only happen when rotating the device while the menu is open. The functionality of the menu is fine in other more common cases.

This is not a regression in 1.16

Repos in Android and iOS

 !RNMenu.jpg|thumbnail! 

Steps:
- Set the device in portrait mode
- Long-press a post to open the menu
- Rotate the device into landscape
- Attempt to drag he menu up to see the other options 
*Expected*: All menu options can still be used
*Observed*: Only the top item is visible and the menu can not be dragged up

**Comment by jkl5616** [comment]
I'd like to work on this!

**Comment by hanzei** [comment]
That was a fast PR. Thanks @jkl5616!
