### ISSUE TITLE
Emoji picker search should ignore leading colon

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10276]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14018)

The search for emoji functionality on RN should ignore a leading colon when looking for matches:

![image](https://user-images.githubusercontent.com/13119842/53303788-9590d180-383c-11e9-8815-4405bedd52c6.png)

instead of requiring me to strip it only to find the matching one that has a leading colon:

![image](https://user-images.githubusercontent.com/13119842/53303791-9a558580-383c-11e9-8a4c-c32dfcef8cfc.png)

Note: this should apply to all emoji picker search on web and mobile

**Comment by bkmgit** [comment]
Hi, interested in this.

**Comment by jasonblais** [comment]
Than you @bkmgit!

**Comment by hanzei** [comment]
Hey @bkmgit,

How is your work on this ticket going? Can we help with anything?

**Comment by bkmgit** [comment]
Still working on this. Thanks for checking.

**Comment by hanzei** [comment]
Great, thanks for the heads up!

**Comment by hanzei** [comment]
Hi @bkmgit,

Just wanting to check if you are still working on this ticket.

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by eshyong** [comment]
Hi, I'm interested in working on this ticket if no one else is.

**Comment by jasonblais** [comment]
Great, thank you @eshyong! If you have any questions, don't hesitate to let us know

**Comment by eshyong** [comment]
Should the query also ignore trailing colons? 

i.e. if I have the query `:slightly_smiling_face:`, it should return 🙂 , right?

**Comment by eshyong** [comment]
@jasonblais 

Also, I created a branch that should fix the issue, but I could use your guidance for writing tests – it looks like there is [no existing test file](https://github.com/mattermost/mattermost-webapp/tree/master/components/emoji_picker) for `emoji_picker.jsx`.

**Comment by jasonblais** [comment]
@eshyong Yes, ignoring trailing colons makes sense to me. (Cc: @esethna) 

@saturninoabril @hanzei would you be open to help guide expected tests and coverage for this fix?

**Comment by hanzei** [comment]
I'm not knowable enough to give guidance about this. @saturninoabril can you help?

**Comment by saturninoabril** [comment]
@eshyong @hanzei Sure and sorry for the delay as I was out and partially unavailable for the past weeks.  I'll look into it today.

**Comment by saturninoabril** [comment]
@eshyong Minimum test coverage will be per code change.  Per your commit, that could be just around the `handleFilterChange` by passing several event target values.
```
wrapper.instance().handleFilterChange(event); // mock event where it has test value
// check if this.props.actions.searchCustomEmojis is called and with correct param
// check state changes depending on event value
```

**Comment by eshyong** [comment]
So, I started writing a test file for my change, but I'm getting the following error when running jest tests:

```
➜  mattermost-webapp git:(MM-14018) node node_modules/jest/bin/jest.js components/emoji_picker/emoji_picker.test.jsx
 FAIL  components/emoji_picker/emoji_picker.test.jsx
  components/emoji_picker/EmojiPicker
    ✕ should ignore leading colon on handleFilterChange (93ms)

  ● components/emoji_picker/EmojiPicker › should ignore leading colon on handleFilterChange

    TypeError: Cannot read property 'offsetHeight' of undefined

      179 |             }
      180 |         });
    > 181 |         this.divHeight = this.emojiPickerContainer.offsetHeight;
          |                                                    ^
      182 |     }
      183 |
      184 |     UNSAFE_componentWillUpdate(nextProps, nextState) { // eslint-disable-line camelcase

      at EmojiPicker.offsetHeight [as componentDidMount] (components/emoji_picker/emoji_picker.jsx:181:52)
      at node_modules/enzyme/build/ShallowWrapper.js:284:22
      at Object.fn [as batchedUpdates] (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:709:16)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:283:26)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous> (components/emoji_picker/emoji_picker.test.jsx:24:25)
```

Can someone help me debug this? It's breaking when I call `shallow` to render the component. My test code is [here](https://github.com/eshyong/mattermost-webapp/compare/79840f90f8a98d70dc6fe38c52c9dc03b1dc7152...1bf0500e7fb6526b13904ac17520e0c8631a1d4e).

**Comment by eshyong** [comment]
It looks like `this.emojiPickerContainer` is a React ref, but I don't understand how those work.

**Comment by saturninoabril** [comment]
Oh, test seems to be complicated on this component. Since your change is not really tied up to a component and can be a utility function, one option is to move it to `utils/emoji_utils.jsx`, like:
```
export function filterEmojiSearchInput(text) {...}
```
then add test to `utils/emoji.test.jsx`, like:
```javascript
describe('filterEmojiSearchInput', () => {
    const testCases = [
        {input: 'smile', output: 'smile'},
        {input: 'SMILE', output: 'smile'},
        {input: ':smile', output: 'smile'},
        {input: ':SMILE', output: 'smile'},
        {input: 'smile:', output: 'smile'},
        {input: 'SMILE:', output: 'smile'},
        {input: ':smile:', output: 'smile'},
        {input: ':SMILE:', output: 'smile'},
    ];

    testCases.forEach((testCase) => {
        test(`'${testCase.input}' should return '${testCase.output}'`, () => {
            expect(filterEmojiSearchInput(testCase.input)).toEqual(testCase.output);
        });
    });
});
```

**Comment by eshyong** [comment]
Thanks @saturninoabril. Created a PR [here](https://github.com/mattermost/mattermost-webapp/pull/3064). Haven't yet gotten to signing the CLA, but the code can be reviewed in the meantime.

**Comment by saturninoabril** [comment]
Thank you @eshyong for your contribution!
