### ISSUE TITLE
[MM-14126] UI Automation: Write an automated test using `cypress` for "Message Draft Pencil Icon - No text, only file attachment"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10274]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14126)

Help write an automated test using [cypress|https://www.cypress.io/] for the following test case:
Note: This test assumes you already have an account on the server.

TEST KEY: M14126

1. Log into [https://community.mattermost.com]
2. In a test channel, attach a file (do not type or space in the message input box)
3. Do not send the post
4. Switch to another channel

Expected:
After 3) you should see a pencil icon to the left of the channel name indicating the channel contains a message draft

See our end-to-end testing documentation for reference \- [https://developers.mattermost.com/contribute/webapp/end-to-end-tests/]

**Comment by tejasbubane** [comment]
I will give this a try.

**Comment by saturninoabril** [comment]
Sure @tejasbubane, thanks!

**Comment by hanzei** [comment]
Hey @tejasbubane,

I just want to check how your work on this going. Do you have any questions?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by composednitin** [comment]
I would like to grab this one

**Comment by saturninoabril** [comment]
@composednitin Great, thanks!

**Comment by saturninoabril** [comment]
@composednitin thank you for your contribution!
PR merged, closing this issue now.
