### ISSUE TITLE
Mattermost uses the key position on keyboard and not the letter typed for some shortcuts

### ISSUE THREAD

**Issue by florck** [mattermost/mattermost-server#10283]
#### Summary
Mattermost uses the key position on keyboard and not the letter typed for some shortcuts

#### Steps to reproduce
Use a non standard keyboard layout in webapp (bépo for french).

Type cmd + v (which is on the touch that would write an «u» on a standard layout mapping)

This will open the upload window instead of pasting the clipboard content, like if I would have typed cmd + u

#### Expected behavior
I expect to get a paste if I type cmd + v and if I type cmd + u to get the upload window, whatever the layout I use.

#### Observed behavior (that appears unintentional) 
 It is not normal that the physical position of the keyboard key is used here. 

I think no-one get it before because only few ergonomical keyboards will move the U and the V letters from the keyboard.

What OS and version is the Mattermost server installed?
docker image of gitlab-ce official image from docker hub

What is your Mattermost server version?
5.3.1 but bug existing since a very very long time

Are you experiencing the issues with the browser webapp, if so which one?
Chrome, chromium, rambox and firefox

Are you experiencing the issues with the Mattermost Desktop App, if so what version and OS?
not tested

Are you experiencing the issues with the Mattermost Mobile App, if so what version and OS?
not relevant (issue with keyboard shortcuts)

Can you send a snippet of the Mattermost server logs around the time of the incident?
not relevant

Are you running Mattermost in a container and/or using container orchestration?
yes, gitlab image on docker, no orchestration

**Comment by amyblais** [comment]
Hi @florck,

Can you also help with more information on your environment from here: https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by florck** [comment]
Done :)

**Comment by amyblais** [comment]
Hi @florck,

We've done some fixes around keyboards in the past few releases - would you be able to do some testing on our test server here and let me know if you see any difference (it's currently on v5.8 RC version): https://community.mattermost.com?

If the issue looks the same there, I'll open a bug ticket for this.

**Comment by florck** [comment]
Hi @amyblais , I confirm this sounds good in the web version on community.mattermost.com.

Thank you a lot, only to wait gitlab to integrate the new release.
