### ISSUE TITLE
Plugin framework: add ability to upload other plugins to the plugin API

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10289]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14190)

Plugins should be able to upload other plugins. To accomplish this add a `UploadPlugin(file io.Reader) (*model.Manifest, *model.AppError)` method to the plugin API.

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/.

You'll want to look at these files:

- https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
- https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

----

This ticket is part of a larger campaign for adding plugin API methods. See here: https://github.com/mattermost/mattermost-server/issues/9458

**Comment by gupsho** [comment]
In the argument for the api, is it reader to the .tar.gz bundle for plugin?

**Comment by tomasmik** [comment]
@gupsho Do you want to take this or can I?

**Comment by gupsho** [comment]
@tomasmik please go ahead and take it. I will take another one.

**Comment by hanzei** [comment]
> In the argument for the api, is it reader to the .tar.gz bundle for plugin?

Yes, it is.

**Comment by hanzei** [comment]
On thing still to discuss is, if this methods should overwrite an existing installation of the plugin. I'm [1/5](https://docs.mattermost.com/process/training.html#out-of-5) on just overwriting, but there might be better solutions like only overwriting, when this updates the plugin version.

**Comment by hanzei** [comment]
@tomasmik Do you want to pick this up?

**Comment by tomasmik** [comment]
If it's ok that I will take some time to do this, then sure.

I do not have mattermost-server set up on my new laptop.

**Comment by hanzei** [comment]
@tomasmik Take the time you need. Let me know, if you have any questions or need help with the dev setup. Feel free to DM me on the [Mattermost Community Server](https://community.mattermost.com).

**Comment by fcorrea** [comment]
I'll take this one

**Comment by hanzei** [comment]
Sorry @fcorrea, this ticket is already taken. Please take a look a the other open Help Wanted ticket: https://github.com/mattermost/mattermost-server/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+Help+Wanted+label%3A%22Up+For+Grabs%22

If you have further questions, feel free to DM me on the [Mattermost Community Server](https://community.mattermost.com).

**Comment by fcorrea** [comment]
I'm sorry @hanzei and @tomasmik ! I've mistakenly assumed it was "Up for Grabs" and that it was fine to take a look.
I'm stepping way from this one for now.

**Comment by hanzei** [comment]
Hey @tomasmik,

Just want to check how your work on this issue is going. Can I help with anything?

**Comment by tomasmik** [comment]
@hanzei hey, terribly sorry had some IRL troubles. I've set up the dev environment and am planning to work on this this weekend. I will let you know about my progress.

**Comment by hanzei** [comment]
Hey @tomasmik,

Checking in again: Did you successfully set up your dev environment?

**Comment by tomasmik** [comment]
I will have to drop the work. I'm facing some issues which are making it impossible to work on this. Im very sorry.

**Comment by hanzei** [comment]
No problem @tomasmik. Thanks for the heads up.

**Comment by hanzei** [comment]
@fcorrea do you still want to work on this?

**Comment by fcorrea** [comment]
> @fcorrea do you still want to work on this?

Hey @hanzei. I'm currently tackling other issue but I'll keep an eye on this one. If it's still hanging when I'm done with the other, i'll pick it up. Otherwise, feel free to leave it open.

**Comment by hanzei** [comment]
I will take care of this.

**Comment by kevinetienne** [comment]
I'll pick this one, please.

**Comment by lieut-data** [comment]
Terrific! Thanks @kevinetienne :)

**Comment by lieut-data** [comment]
@kevinetienne, anything we can do to help with your efforts here?

**Comment by hanzei** [comment]
Hey @kevinetienne,

do you have any questions?

**Comment by kevinetienne** [comment]
@hanzei no I have tweaked you pr and I was basically working on a test but didn't got too far, I'll push it today and see where we go from there.

**Comment by hanzei** [comment]
@kevinetienne Just want to touch bases: Can I help you in any way to get the tests going?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by niklabh** [comment]
Here is a pull request: https://github.com/mattermost/mattermost-server/pull/12232
