### ISSUE TITLE
[Help Wanted] [MM-14192] Render hyperlinks in Message Attachment title

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10292]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14192)

Hyperlinks in Message Attachment titels currently don't get rendered. This ticket is about fixing this. This should be fixed in both the webapp and and the mobile app.

[Matterpoll](https://github.com/matterpoll/matterpoll) can be used to test this. You can use e.g. `/poll "Do you like https://mattermost.com?"` to generate a post with a hyperlink in the Message Attachment title.

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by kosgrz** [comment]
I could do it!

**Comment by hanzei** [comment]
Thanks again @kosgrz. You are doing a great job! :tada:
