### ISSUE TITLE
[Help Wanted] [MM-14191] Render emojis in Interactive Message Buttons

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10290]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14191)

Currently emojis in Interactive Message Buttons don't get rendered. This should be changed to allow integrations to use them properly. This ticket is about fixing this. This should be fixed in both the webapp and and the mobile app.

[Matterpoll](https://github.com/matterpoll/matterpoll) can be used to test this. You can use e.g.  `/poll "Do you like pizza?" ":+1:" ":-1:"` to generate a post with  Interactive Message Buttons.

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by kosgrz** [comment]
I can do it!

**Comment by jasonblais** [comment]
You're fantastic, thanks @kosgrz!
