### ISSUE TITLE
Welcome Bot message points to not found page on http://contributor-covenant.org

### ISSUE THREAD

**Issue by fcorrea** [mattermost/mattermost-server#10303]
#### Summary
The Welcome Bot in use on the nightly build server contains a broken link to http://contributor-covenant.org/version/1/3/0/code_of_conduct.txt 

#### Steps to reproduce
Register with a new user on the nightly test build at https://community.mattermost.com
After successful logon, click on the "Welcome Bot" direct message and look for "Contributor Code of Conduct"
Click on it and it will navigate to a non existing page on http://contributor-covenant.org

#### Expected behavior
It should point to https://www.contributor-covenant.org/version/1/4/code-of-conduct

#### Observed behavior (that appears unintentional) 
A page containing an alert with "Page Not Found"

#### Possible fixes
Review if the latest version of the code of conduct is still applies to Mattermost and fix the broken link pointing it to https://www.contributor-covenant.org/version/1/4/code-of-conduct

**Comment by amyblais** [comment]
Hi @fcorrea,

Also letting you know that you can follow the progress of this issue also via the Jira ticket I linked above. For the latest updates to the ticket you can add yourself as a watcher. To do this, click on "Start Watching This Issue" in the ticket. This way you’ll be emailed immediately when the ticket status is changed. If you have any issues accessing our Jira instance please let me know.

Let me know if you'd prefer to follow the progress on this issue via the Jira ticket or via this Github Issue?

**Comment by fcorrea** [comment]
Hey @amyblais 

I'm already subscribed via github so I'll just keep an eye.

**Comment by cpanato** [comment]
Merged the fix, will deploy asap
closing

thanks for finding the issue
