### ISSUE TITLE
[MM-14252] UI Automation: Write an automated test using Cypress for "After clearing search query, search options display"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10308]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14252)

*Test Key: S14252*

Repro steps:
1. Search for any random word you know will return results
2. Click on the "x" displayed to the right of the search term in the search box
3. Click in the search box

Expected:
- After 2) the search query should clear and search results remain in the RHS
- After 3) focus should be placed in the search box and "search options" should be displayed

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by joshuabezaleel** [comment]
I never tried Cypress but can I take a shot on this? I will have a look at the [End-to-end-tests](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) page.

**Comment by hanzei** [comment]
Sure @joshuabezaleel, thanks for looking into this. Let us know, if you have questions!

**Comment by hanzei** [comment]
Hey @joshuabezaleel,

Are you still working on this issue? Can we help with anything?

**Comment by joshuabezaleel** [comment]
Hi @hanzei , I am really sorry for the inactivity.
I do not think that I have the adequate knowledge nor experience especially time to tackle on this issue.  I am afraid that it will just slow the progress down. I think this issue will be better off assigned to someone with more ready experience. 
Hope that I can still take issues and won't be a burden in the future.

Thank you very much @hanzei 🙂

**Comment by hanzei** [comment]
Hey @joshuabezaleel,

Thanks for the follow up on this ticket.

No problem, if you step down from a ticket. I will just make this available for the public again.

In the future you might just volunteer for one ticket at a time. This way you don't overload yourself with work.

Looking forward to your contribution!

**Comment by composednitin** [comment]
Hi,
I would like to contribute in cypress automation testing, I would like to take this ticket

**Comment by hanzei** [comment]
Surely @composednitin. Let us know, if you have any questions.

**Comment by saturninoabril** [comment]
Thank you @composednitin for your contribution!
