### ISSUE TITLE
[Help Wanted] [MM-13091] Review, improve and test the push proxy docker image

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10314]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13091)

Currently the Mattermost push proxy (responsible for sending push notifications to the Apple/Google push notification services) is being built as a docker image here https://github.com/mattermost/mattermost-kubernetes/blob/master/docker/push-proxy/Dockerfile.

Need to do the following:
- Review the Dockerfile and make improvements as necessary (follow best practices, etc.)
- Test the image to make sure it works and runs properly
- Move the Dockerfile to live in the official push proxy repo here https://github.com/mattermost/mattermost-push-proxy
- Remove the Dockerfile from the mattermost-kubernetes repo

If you have questions or need help, message `@joram` or `@cpanato` in the ~Kubernetes on community.mattermost.com

**Comment by stylianosrigas** [comment]
I will pick up this ticket.
