### ISSUE TITLE
[MM-13964] JIRA plugin: automatically convert JIRA-formatted messages to Mattermost Markdown

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10316]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13964)

Some work may have already being started here: https://github.com/mattermost/mattermost-plugin-jira/tree/hackathon

**Comment by stevepartridge** [comment]
I'd like to give this one a try.
