### ISSUE TITLE
[MM-14281] Multiselect throws a warning when selecting an item

### ISSUE THREAD

**Issue by courtneypattison** [mattermost/mattermost-server#10317]
#### Summary
Multiselect throws a warning when selecting an item because each item does not have a unique key.

#### Steps to reproduce
Login > Hamburger Menu > Add Members to Team > Select a User

#### Expected behavior
Warning should not show up in console when multiselecting.

#### Observed behavior (that appears unintentional) 
The following warning occurs in the console when selecting a user to add to a team:
```
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `Select`. See https://fb.me/react-warning-keys for more information.
    in MultiValue (created by Select)
    in Select (created by StateManager)
    in StateManager (created by MultiSelect)
    in div (created by MultiSelect)
    in div (created by MultiSelect)
    in div (created by MultiSelect)
    in MultiSelect (created by AddUsersToTeam)
```
#### Possible fixes
The `valueKey` prop from React Select is no longer supported with version 2.x., instead there is a `getOptionValue` prop. Use `getOptionValue={(option) => option.id}` in [MultiSelect](https://github.com/mattermost/mattermost-webapp/blob/9f2732db4d7a4d13525099732bf91409f4216fd5/components/multiselect/multiselect.jsx#L304) and remove `valueKey='id'` from AddUsersToTeam, ChannelnviteModal, ChannelSelectorModal, MoreDirectChannels, and TeamSelectorModal. I could create a PR to show what I mean if desired :)

**Comment by amyblais** [comment]
Hi @courtneypattison,

A PR will be appreciated!

I also opened a ticket for tracking: https://mattermost.atlassian.net/browse/MM-14281.
