### ISSUE TITLE
[Help Wanted] [MM-14263] Review, improve and split out push proxy helm chart

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10313]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14263)

Currently, the Mattermost push proxy (responsible for sending push notifications to the Apple/Google push notification services) lives here as part of the Mattermost enterprise helm chart: https://github.com/mattermost/mattermost-kubernetes/tree/master/mattermost-helm/charts/mattermost-push-proxy

This chart was thrown together fairly quickly and likely has lots of room for improvement.

Need to do the following:
- Review and make improvements to the existing push proxy chart
- Move the push proxy helm chart to the official push proxy repo under a folder called "helm" https://github.com/mattermost/mattermost-push-proxy
- Remove the push proxy helm chart from the mattermost-kubernetes repo
- Update the mattermost-kubernetes repo to use the new helm chart as a dependency

If you have questions or need help, message `@joram` or `@cpanato` in the ~Kubernetes on community.mattermost.com

**Comment by stylianosrigas** [comment]
I will pick up this ticket.

**Comment by stylianosrigas** [comment]
After discussion with @cpanato the push-proxy chart will temporarily sit under https://github.com/mattermost/mattermost-kubernetes/tree/master/charts/ and proper refactoring will enable independent use of the push-proxy Helm chart. In the future the push-proxy chart will be moved in a central location and will be added as dependency in mattermost-enterprise-edition.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-kubernetes/pull/62

Thanks @stylianosrigas
