### ISSUE TITLE
[Help Wanted] [MM-12667] Allow including deactivated users in bulk import

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10319]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12667)

From a customer:
On importing legacy chat room data, the import will error out if a post’s user is not in mattermost. So in order to properly import conversations, it seems I would need to import a chunk of disabled/inactive users. I do not see a field on the bulk import script options to include deactivated users.

Developer Note: this should be done by allowing the property to be included in a bulk import

**Comment by sandlis** [comment]
Is it okay if I give it a try?

**Comment by jasonblais** [comment]
Certainly, thank you @sandlis!

**Comment by sandlis** [comment]
@jasonblais Thanks! 
Does legacy data here means data from previous mattermost versions or other chat softwares like slack?

**Comment by wiersgallak** [comment]
@sandlis Legacy data means data from other chat softwares.  We want to support the use case where a user may have once be active, but is no longer so customers can to retain the conversation history (posts) of the inactive users.  Our bulk import currently does not allow you to import inactive users, so customers currently need to add the users as active and then deactivate them after the import.  This improvement would allow them to add them as inactive from the bulk import. 

Let me know if you have any further questions.

**Comment by sandlis** [comment]
Thanks @wiersgallak 
I have posted my query on how to reproduce this [here](https://pre-release.mattermost.com/core/pl/wet4shc63f8nppanw6egiuxhjc)

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/10353.

Thanks @sandlis!
