### ISSUE TITLE
[Help Wanted] [MM-11148] Convert mattermod to use structured logging

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10315]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11148)

Mattermod is the automated moderator that responds to GitHub issues, spins up test servers and performs other tasks. It lives here https://github.com/mattermost/mattermost-mattermod.

Like many of our other repositories, mattermod is currently using l4g which is now deprecated. We are moving to use mlog (https://github.com/mattermost/mattermost-server/tree/master/mlog) instead.

For this ticket, drop use of l4g in mattermod in favour of structured logging via mlog.

As part of this, we may want to expose a `mattermod logs` cmd in the spirit of https://mattermost.atlassian.net/browse/MM-11146, or perhaps factor out mlog from mattermost-server into a separate repository with its own cmds as such.

If you have any questions or concerns, feel free to message `@jesse.hallam` or `@joram` in the ~Developers channel on community.mattermost.com

**Comment by fcorrea** [comment]
I'll take this one

**Comment by hanzei** [comment]
Thanks @fcorrea for taking care of this one.

**Comment by fcorrea** [comment]
Ok, PR is up. 
I've decided to leave the CLI out of the way for now since I think factoring out mlog and adding commands to it would be better.
Please, let me know what you guys think.

**Comment by jwilander** [comment]
https://github.com/mattermost/mattermost-mattermod/pull/22
