### ISSUE TITLE
Mattermost plugin enable via "MM_" variable doesn't work

### ISSUE THREAD

**Issue by Hayyk** [mattermost/mattermost-server#10310]
Hello

#### Summary
Mattermost plugin enable via "MM_" variable doesn't work

#### Steps to reproduce
Same issue as https://forum.mattermost.org/t/automatically-activate-plugin/6289

#### Expected behavior
MM_PLUGINSETTINGS_ENABLEUPLOADS=true works fine but MM_PLUGINSETTINGS_PLUGINSTATES_COM.GITHUB.MATTERPOLL.MATTERPOLL_ENABLE=true doesn't work
Also tried MM_PLUGINSETTINGS_PLUGINSTATES_JIRA_ENABLE=true which didn't work either

Once I enable the plugin from console and delete the plugin, then after uploading it again automatically enables the plugin.

#### Observed behavior (that appears unintentional) 
it should enable plugin without any manual action

**Comment by Hayyk** [comment]
@amyblais @hanzei The issue isn't related to specific plugin itself, it doesn't work with any plugin even with jira which is coming with mattermost by default.

**Comment by hanzei** [comment]
I can confirm that this is a Matterpoll problem.

FYI: People have run into this problem before:
- https://forum.mattermost.org/t/automatically-activate-plugin/6289
- https://community-daily.mattermost.com/core/pl/eoateesy83rkbxwfz3q364c7ny

**Comment by Hayyk** [comment]
This is plugin problem and not matterpoll plugin problem only. User that faced the same issue before also mentioned that it's not working with jira either.
https://community-daily.mattermost.com/core/pl/oyra3sbgwfftdmzzin4uhuz5ny

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-14282.

**Comment by levb** [comment]
FWIW, https://mattermost.atlassian.net/browse/MM-11930 and https://mattermost.atlassian.net/browse/MM-14282 have both been closed

**Comment by amyblais** [comment]
Hi @Hayyk, letting you know that the Jira ticket was closed as our developers determined that we're not going to work on this in the near future. We'll revisit this later, so I'll close this Github issue for now.
