### ISSUE TITLE
[Help Wanted] [MM-13341] Add an upgrade test to verify schema

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10329]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13341)

In the past there have been cases where freshly installed Mattermost instances have had a slightly different database schema than old existing Mattermost instances that have gone through the upgrade code. When this happens it can lead to issues that are hard to find the cause for or diagnose, or just general diverging of Mattermost instances from what we expect.

We should add a test when building that verifies the upgrade code produces the same schema as building a fresh database from scratch.

Exactly how the test should work is open for ideas. If you would like to discuss it, feel free to ask `@jesse.hallam` or `@jesus.espino` in the ~Developers channel on community.mattermost.com

**Comment by sandlis** [comment]
Is it okay if I give this a try?

**Comment by hanzei** [comment]
Surely, @sandlis, that would be awesome!
