### ISSUE TITLE
[Help Wanted] [MM-11426] Use gzip for API responses

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10325]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11426)

If possible, we should make it so that the Mattermost server can respond to REST API requests with compressed data (via gzip) to reduce the amount of bandwidth used. This should be done as long as the client supports it based on the request's `Accept-Encoding` header, and we should then have the web and mobile apps request data with that header.

If you have any questions, feel free to ask `@harrison` or `@christopher` in the ~Developers channel on community.mattermost.com

**Comment by kishan-1234** [comment]
Hi I would like to work on this

**Comment by jwilander** [comment]
Hi @kishan-1234, just checking if you've had a chance to make any progress on this?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by checkaayush** [comment]
Hey @hanzei, I'd like to give this a shot! 

I'll need some pointers to get started though. I'm thinking on the lines of something which uses:
```go
type gzipResponseWriter struct {
        io.Writer
        http.ResponseWriter
}
```
I'm not sure of a clean way to add this along with the header check across endpoints.

**Comment by hanzei** [comment]
Awesome, thanks for taking care of this @checkaayush!

@jwilander Would you please take look at the above question?

**Comment by jwilander** [comment]
Hi @checkaayush, that could work but I'd suggest taking a look at https://github.com/NYTimes/gziphandler. We use that for creating handlers for gzipping some static files here https://github.com/mattermost/mattermost-server/blob/master/web/static.go#L41 and we could probably do something similar for the REST API

If you want to discuss it further, feel free to ping me in [our "Developers" community channel](https://community.mattermost.com/core/channels/developers). That way we can get input from multiple people on any proposed changes/ideas

**Comment by jwilander** [comment]
Hi @checkaayush, are you still interested in working on this? If not I'll switch it to up for grabs

**Comment by checkaayush** [comment]
@jwilander I don't think I'll be able to work on this at present. Please make it up for grabs.

**Comment by tylarb** [comment]
I'd like to take a look at this @jwilander

**Comment by jwilander** [comment]
Thanks for working on this @tylarb !
