### ISSUE TITLE
[Help Wanted] [MM-13721] Fix the etag function GetEtagForProfilesNotInTeam

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10324]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13721)

Etags are used for cache validation. When an HTTP client makes a request to the server, the server sometimes returns an Etag in a header. The next time the client makes that same request it includes that Etag. The server then evaluates that header to determine if anything changed. If nothing changed a 304 Not Modified is returned to the client with an empty response body. This can save computation time and network bandwidth.

The REST API endpoint GET /users has multiple Etags. The one for querying users not in a team is called GetEtagForProfilesNotInTeam. The query to resolve GetEtagForProfilesNotInTeam looks at the most recent `UpdateAt` for users not in the given team. However, if any but the most recent such user is added to the team, the etag won't change despite those users having a newer `UpdateAt`: because they won't be considered in the set anymore.

Update the query to appropriately cover this case.

If you have any questions, feel free to ask `@jesse.hallam` or `@joram` in the ~Developers channel on community.mattermost.com

**Comment by jfrerich** [comment]
I would like to take this ticket

**Comment by hanzei** [comment]
Thanks @jfrerich!

**Comment by levb** [comment]
https://github.com/mattermost/mattermost-server/pull/10360
