### ISSUE TITLE
[Help Wanted] [MM-14270] UI Automation: Write an automated test using `cypress` for "Delete a parent message that has a reply: Reply RHS"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10323]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14270)

Test Key: M14270
Help write an automated test using cypress for the following test case:
Note: This test assumes you already have an account on the server and have logged in.

1. Make a post
2. Open the reply thread fir the post and post a reply
3. Return to center channel view
4. In center, click [...] > Delete on the parent post

Expected:
- Confirmation modal warns how many comments will be deleted
- Both parent post and reply are deleted and disappear from both center and RHS
- user who deleted the post does not see `(message deleted)`

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests

**Comment by d28park** [comment]
I can give this a shot to familiarize myself with Cypress and MM's E2E testing procedure!

**Comment by saturninoabril** [comment]
Thank you @d28park for your contribution!

PR has been merged. Closing this ticket now.
