### ISSUE TITLE
[Help Wanted] [MM-14283] UI Automation: Write an automated test using `cypress` for "Compact view: Line breaks remain intact after editing"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10322]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14283)

*Test Key: M14283*

Steps:
1. In Account Settings > Display > Message Display, click Edit
2. Select `Compact` and click Save
3. Close Account Settings modal
4. Now that you are in compact view, post the following three lines as a message (`First line` of text, then blank newline in the middle, then `Text after`...):

First line of the post with a line break following

Text after the line break

5. Edit the post by adding the characters `, edited` at the end of the last line (don't change the line breaks)
6. Save

Expected:
1. Line breaks do not change; blank line is still between the two lines of text
2. Edits are there
3. `(edited)` displays

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by thekiiingbob** [comment]
I'd like to try and tackle this one. Can probably get to it over the weekend.

**Comment by jasonblais** [comment]
Awesome, thanks @thekiiingbob!

**Comment by sudheerDev** [comment]
Closing the issue as PR is merged.
