### ISSUE TITLE
[Help Wanted] [MM-14145] Investigate changing the config store Set to automatically Save

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10338]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14145)

The config store currently requires a after a . Ideally, would automatically , but a number of app unit tests and likely app business logic assumes otherwise.

Investigate changing this. To start, change the code to automatically and then see what breaks. Suggest capping this to 4 mana and reporting back, as it may prove intractable to change this underlying assumption (which is a perfectly valid outcome, assuming it’s justified.)

**Comment by cpoile** [comment]
I'd love to take a stab at this!

**Comment by hanzei** [comment]
Thanks for looking into this @cpoile. :tada: 
Let me know if you have any questions.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/10377
