### ISSUE TITLE
[Help Wanted] [MM-13566] Throw an error accessing Set.length or Map.length in dev mode

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10331]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13566)

To avoid issues like https://community.mattermost.com/core/pl/rjkkfnupdfb99mqp7kej7xa3ea, let's find a way to make Set.length and Map.length throw an error when accessed in dev mode. This will help track down current instances of this problem as well, which should be fixed at the same time.

If you have any questions or would like to discuss the ticket, feel free to ask `@harrison` or `@enahum` in the ~Developers channel on community.mattermost.com

**Comment by steveperjesi** [comment]
Looks good, I'll take this one.

**Comment by hanzei** [comment]
Thanks @steveperjesi for looking into this! :+1:

**Comment by steveperjesi** [comment]
PR submitted
https://github.com/mattermost/mattermost-webapp/pull/2404

**Comment by e-ninja0** [comment]
Submitted a PR for this GB issue: https://github.com/mattermost/mattermost-webapp/pull/2545

**Comment by hmhealey** [comment]
This has been merged into master and will be going into the 5.12 release
