### ISSUE TITLE
[Help Wanted] [MM-14291] Improve mattermod test server setup

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10339]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14291)

https://github.com/mattermost/mattermost-mattermod monitors issues in the mattermost repository to automate certain workflows. One such workflow is for a GitHub user to apply the "Setup Test Server" label, triggering mattermod to create a test server using that build for evaluation by the reviewers.

Often changes are required on the pull request, but in order to get a new test server, it is necessary both to remove the label and delete manually all prior comments from mattermod before a new "Setup Test Server" label takes effect. I suspect the current implementation uses the posts on the PR to decide if it's already done the work in question. A modest improvement might be to realize the old test server had been deleted (using the post mattermod emits when it does so), and drive the creation of a new server when the label reappears. It may also be possible to maintain metadata in a local database and use that to synchronize.

Investigate and make a proposal on https://community.mattermost.com/core/channels/developers, get community buy-in on the changes, and then proceed with an implementation.

**Comment by stylianosrigas** [comment]
I will have a look at this.

**Comment by hanzei** [comment]
Thanks @stylianosrigas for looking into this. This will be super helpful :rocket:
