### ISSUE TITLE
[Help Wanted] [MM-13877] Update System Console > Users > User Status Filter Name "None" to "All Users"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10333]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13877)

Change filter to be "All Users" instead of "None" to better indicate that the filter includes all users instead of none, which could imply no users.

**Comment by tejasbubane** [comment]
I will take this one.
