### ISSUE TITLE
mattermost-redux fail to build with npm ci and npm install

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10334]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13942)

Some contributors have reported that mattermost-redux failed to build when installed while building the webapp, this is definitely true when building the mobile apps using `npm ci`.

It seems that npm ci and sometimes npm install will fail to trigger the prepare hook causing the app to skip to build itself.

Proposed Workarounds:
* Only build the mm-redux library before publishing and use the ES6 version in the web and mobile apps
* Use a different hook instead of prepare to build the mm-redux

**Comment by KuSh** [comment]
Hi, is that still relevant now that mattermost-redux is a package of mattermost-webapp ?

**Comment by hanzei** [comment]
Good catch @KuSh , this ticket can indeed be closed.
