### ISSUE TITLE
Emoji added to an existing post doesn't display for sender

### ISSUE THREAD

**Issue by tmulholl** [mattermost/mattermost-server#10343]
#### Summary
An emoji added to an existing post doesn't immediately display for the sender. It does display immediately for the receiver.

#### Steps to reproduce
Environment details:
Mattermost Version: 5.7.1
Database Schema Version: 5.7.0
Database: mysql
Operating system: Windows 10
Browser: Chrome Version 72.0.3626.109 (Official Build) (64-bit)

1. User A sends a message to User B (in a direct message - I haven't tested others)
2. User B adds an emoji to User A's post

#### Expected behavior
The emoji should immediately display on User A's post - for both User A and User B.

#### Observed behavior
The emoji only shows immediately for User A. After about 10 minutes, the emoji does display for User B without doing anything.

### User A's view
![image](https://user-images.githubusercontent.com/12263254/53206511-6127d600-35ee-11e9-87e0-2ca2231061ec.png)

---
### User B's view
![image](https://user-images.githubusercontent.com/12263254/53206449-3a699f80-35ee-11e9-8d59-f6fc42e213c8.png)

**Comment by amyblais** [comment]
Hi @tmulholl, is this on webapp or the mobile app?

**Comment by tmulholl** [comment]
This is on the webapp. I shared the browser and operating system in the steps to reproduce.

**Comment by amyblais** [comment]
Thank you, we have a ticket to fix this and it is currently scheduled for v5.9 release: https://mattermost.atlassian.net/browse/MM-14187.

There was also a similar issue on the mobile app but it has been fixed for v1.16.1 dot release which will be available in the app stores within the next few days.

**Comment by amyblais** [comment]
Closing this as the above ticket has been fixed for v5.9 release (available on March 16th).
