### ISSUE TITLE
Channel does not refresh automatically on iPhone mobile app

### ISSUE THREAD

**Issue by tmulholl** [mattermost/mattermost-server#10340]
I searched for an existing bug and below is the closest I could find to it. It may or may not be related.
https://mattermost.atlassian.net/browse/MM-14021

#### Summary
Sometimes when going to a channel on the iPhone mobile app, the channel is missing the latest post. If you force a refresh, the post will display.

#### Steps to reproduce
I have yet to consistently reproduce it. I think it may have something to do with how much time has spanned since User B (the receiver) last used the mobile app. And/or User B receives a message in a team/channel other than the one they are currently viewing. Below are the usual steps of how it manifests itself.

Environment details:
-iPhone app version 1.16.0 (Build 175)
-Server version 5.7.0 (Build 5.7.1)
-Database: mysql

1. User A sends a message in a channel (I've seen it happen in both private and public)
1. If needed, User B navigates to the correct team/channel

#### Expected behavior
Regardless if User B is already in the correct channel or if they have to navigate to it, the new post should automatically be displayed.

#### Observed behavior (that appears unintentional) 
The channel is not updated automatically with the new post. Instead, the user must do a manual refresh by pushing the screen up.

**Comment by amyblais** [comment]
Hi @tmulholl, I've seen this sometimes too but as you said it's hard to reproduce consistently. I'll ask our team tomorrow if other's have seen it too and whether we already have a ticket open to address this.

**Comment by amyblais** [comment]
Hi @tmulholl, can you help upgrade to the latest server version and mobile version to see if you can still reproduce the issue?

**Comment by tmulholl** [comment]
Hi -

Looks like the latest mobile version isn’t available yet. When it is, we will give it a try and let you know what we find. 

Thanks.

**Comment by amyblais** [comment]
Hi @tmulholl,

The latest server version is v5.8 and it is available to download: https://mattermost.com/download/.

The latest mobile version is v1.16.1 and available to download: http://about.mattermost.com/mattermost-ios-app/.

**Comment by amyblais** [comment]
Closing this for now as we haven't received updates for a while. If the issue persists, please upgrade to the latest versions. If upgrading doesn't help, please re-open this issue and we can continue to investigate.
