### ISSUE TITLE
[MM-11828] Plugin framework: Add the ability to have lists in the plugin system console settings

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10342]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11828)

Currently the plugin pages on the system console are limited to static fields.

We want to add support for arrays of structures. 

For example, currently the autolink plugin is unable to be configured in the system console because it requires an array of structures: https://github.com/mattermost/mattermost-plugin-autolink/

**Comment by cpoile** [comment]
I'd love to take a crack at this!

**Comment by hanzei** [comment]
Thanks for looking into this @cpoile! :tada:

**Comment by manland** [comment]
Hi! @cpoile thanks for the key/value pair implementation.

@jasonblais @hanzei @levb do you think it's enougth or should I try to implem an array ?

For my plugin I need an array of pair of string. Or an array of channel selector. I can start with a channel selector an then add an array of them ? What do you think ?

**Comment by hanzei** [comment]
Hey @manland,

I posted my thoughts on this topic in the PR. You can find them in https://github.com/mattermost/mattermost-server/pull/10384#issuecomment-471619885. Would you mind sharing your thoughts in the PR?

**Comment by hanzei** [comment]
If you are interested in adding a new `type` for the plugin setting to select a channel, it would be highly appreciated.

**Comment by Wipeout55** [comment]
Hey does this still need work? I would love to take it on if so :)

**Comment by jasonblais** [comment]
@cpoile Curious on your thoughts if you have a recommendation on next steps for [your open PR](https://github.com/mattermost/mattermost-server/pull/10384), and if there are areas @Wipeout55 can help with?

**Comment by cpoile** [comment]
@jasonblais @Wipeout55 I'm not sure what the next steps are. I think we needed PM and design work on that before moving forward. And now we might be moving to a different method for setting pages which would remove the need for this (but that could be a long-term goal, Jason?). The PR itself is not super useful as a starting point, given that we don't know what we want yet. :)

**Comment by Wipeout55** [comment]
Okay thanks @cpoile! I'll take on something else for now.

**Comment by cpoile** [comment]
@Wipeout55 after today's meeting, I now know that even if we offer a different way to do system console settings, we will still offer the old (simpler) way. So if this looks interesting, please take it -- we'll just have to assign some PM and designer time to get it ready for you. :)

**Comment by Wipeout55** [comment]
Okay great! I'm definitely still interested, but I've taken on another ticket as well (MM-14727). I'm not sure if there's any priority on what I should work on first, but let me know if there is. I'll probably start on the other ticket first if there is no preference, as it seems a bit more in-depth.

**Comment by jasonblais** [comment]
@Wipeout55 Given MM-14727 is well-defined, let's start with that one. It's also a good improvement to the bot developer experience 👍

**Comment by hanzei** [comment]
@jasonblais @cpoile What do you think about closing this issue for now? It still needs a lot of design from our side.

**Comment by jasonblais** [comment]
@hanzei Good point, we should. I had turned the original ticket to a design ticket last week for us to revisit: https://mattermost.atlassian.net/browse/MM-11828
