### ISSUE TITLE
[Help Wanted] [MM-11142] Console logging should be human readable during development

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10349]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11142)

Mattermost switched to using structured logging through the new mlog package (https://github.com/mattermost/mattermost-server/tree/master/mlog) to make it easier for third-party systems to process and parse the logs. However, this made it harder for a human to read the defaults logs.

For this ticket, update Mattermost to default to console logging in a human readable format while running for development.

Note that production console logs should continue to default to be structured, in particular to support the Docker environment where all logs are emitted via STDOUT.

If you have any questions or want to discuss the ticket, feel free to ask `@christopher` or `@jesse.hallam` in the ~Developers channel on community.mattermost.com

**Comment by d28park** [comment]
Hello, new to Mattermost. Working on this to get a grasp of the logging process.

**Comment by jasonblais** [comment]
Thanks @d28park! Looks like this ticket has a PR here: https://github.com/mattermost/mattermost-server/pull/10352

Would you be interested picking another ticket that's up for grabs? Appreciate your interest!

https://github.com/mattermost/mattermost-server/labels/Up%20For%20Grabs

**Comment by d28park** [comment]
Thanks, I'll look around!

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/10352. Thanks @cpoile! :tada:
