### ISSUE TITLE
[MM-12958] Support running two Mattermost instances on the same domain using subpaths

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10345]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12958)

Mattermost has the ability to run on a subpath of a domain. For example, instead of hosting at chat.example.com you could host Mattermost at example.com/chat.

Right now, however, you cannot host two Mattermost instances at different subpaths of the same domain. E.g. example.com/chat1 and example.com/chat2

One reason for this that the browser cookies are across the whole domain, not the subpath, so you can't be logged into two independent servers running on two different subpaths. For example, if you logged in to example.com/chat1 then went to example.com/chat2 and logged in, you would be logged out of example.com/chat1 because the cookie would get overridden.

For this ticket:
- Update the cookies used by Mattermost to include the subpath
- Test running two Mattermost instances at a subpath to make sure that it works and fix any other problems that arise

If you have any questions or want to discuss the ticket, feel free to ask `@jesse.hallam` or `@harrison` in the ~Developers channel on community.mattermost.com

**Comment by cpoile** [comment]
@esethna I'd love to take a look at this

**Comment by d28park** [comment]
I am taking a look at this.

**Comment by hanzei** [comment]
Thanks for taking care of this @d28park! Let us know, if you have any questions.

**Comment by jwilander** [comment]
@d28park have you had a chance to make an progress on this? Feel free to let us know if you have any questions

**Comment by d28park** [comment]
@jwilander yup, I'm making some progress on this. Fixing up some bugs and will reach out in the developers channel if I get stuck

**Comment by jwilander** [comment]
Awesome, thanks @d28park
