### ISSUE TITLE
[Help Wanted] [MM-5994] [Redux] Split out constants even more

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10362]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-5994)

Split out the constants in general.js into more files, such as channels.js, users.js etc.

Please be aware that this will affect [mattermost-webapp](https://github.com/mattermost/mattermost-webapp) and [mattermost-mobile]‌(https://github.com/mattermost/mattermost-mobile)

**Comment by JayaKrishnaNamburu** [comment]
Hi, @hanzei please correct me, if I am not clear on this, so the [file](https://github.com/mattermost/mattermost-redux/blob/master/src/constants/general.js) should be split into two sub-files depending on the use case and then files depending on these in web-app and mobile-app should be updated right?

**Comment by hanzei** [comment]
@enahum Could you please provide some more guidance on this? Thanks for helping out!

**Comment by enahum** [comment]
Perhaps best to ask @jwilander as he filed the ticket.. I don't have the context for this

**Comment by jwilander** [comment]
I filed the ticket two years ago :P I'm not sure it's even still needed, the constants look to be pretty well split out right now. @JayaKrishnaNamburu if you want to come up with a proposal for splitting out general.js some more (or moving constants from it to other appropriate files) I'd be ok with that but I don't think we really need any big changes here

**Comment by JayaKrishnaNamburu** [comment]
Ok @jwilander i will pick up someting else from the existing issues 😄  👍

**Comment by jwilander** [comment]
Closing as I don't think this is needed anymore
