### ISSUE TITLE
[Help Wanted] [MM-14319] UI Automation: Write an automated test using `cypress` for "Theme Colors - Code"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10366]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14319)

*Test Key: AS14319*

1. Post the code block:
```
code
```
2. Observe the color of the posted code block
3. Go to Account Settings -> Display -> Theme
4. Select "Custom Theme", "Center Channel Styles"
5. Change only the `Code` theme, observe the color change immediately in center behind the Account Settings modal
6. Save
7. Observe the code block still shows as the updated color
8. Refresh

Expected:
- Code theme selection works properly, and selected code theme is reflected in a code block.
- Code theme selection saves properly, and "sticks" after a refresh.

**Comment by m3phistopheles** [comment]
I'll nab this one

**Comment by hanzei** [comment]
Great, thanks @m3phistopheles! :tada:

**Comment by m3phistopheles** [comment]
I accidentally confused this story with, MM-14318. Claiming that one and leaving this one up for grabs

**Comment by saturninoabril** [comment]
@m3phistopheles No worries and thanks for letting us know.

**Comment by thekiiingbob** [comment]
I can snag this one.

**Comment by saturninoabril** [comment]
Sure, thanks @thekiiingbob!

**Comment by saturninoabril** [comment]
Thanks @thekiiingbob!  PR is now merged into master.

Closing this now.
