### ISSUE TITLE
[Help Wanted] [MM-14320] UI Automation: Write an automated test using `cypress` for "at-here.", "at-all." and "at-channel." (ending in a period) still highlight"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10368]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14320)

*Test Key: M14320*

1. Post `@here. @channel. @all.` 
(Ensure each mention is followed by a period)

Expected:
The @-mentions are highlighted but the period is not

**Comment by letsila** [comment]
Hi guys, I'd love to help on this one.

**Comment by hanzei** [comment]
Hey @letsila,

Thanks for taking care of this ticket. Let me know, if you have any questions.

**Comment by saturninoabril** [comment]
Thank you @letsila!  PR is recently merged.

Closing this issue now.
