### ISSUE TITLE
Write an automated test using `cypress` for "Theme Colors - Color Picker"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10367]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14318)

*Test Key: AS14318*

1. Go to Account Settings -> Display -> Theme
2. Select "Custom Theme"
3. Use one of the color pickers to edit the theme
4. Save

Expected:
Custom theme colors are saved.

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by m3phistopheles** [comment]
claiming this one!

**Comment by saturninoabril** [comment]
Sure, thank you @m3phistopheles!

**Comment by a-arias** [comment]
I'm going to take this ticket 💃
