### ISSUE TITLE
Slack import via CLI not importing any messages

### ISSUE THREAD

**Issue by kaizimmer1** [mattermost/mattermost-server#10371]
The CLI migration of Slack messages does not work as intended. I am using Mattermost Enterprise version 5.7.0. Users and channels are imported, but none of the messages (except for polls).

My command line used was:
/opt/mattermost-5.7/bin/mattermost import slack <teamname> <filename.zip>

The output (log) looks like this:
root@xyz:/opt/mattermost-5.7# bin/mattermost import slack dstar-teambbaw /home/kai/slack_import/all/all.zip 
{"level":"info","ts":1551177733.7805972,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'de' from '/opt/mattermost-5.7/i18n/de.json'"}
{"level":"info","ts":1551177733.780683,"caller":"app/app.go:143","msg":"Server is initializing..."}
{"level":"info","ts":1551177733.782219,"caller":"sqlstore/supplier.go:207","msg":"Pinging SQL master database"}
{"level":"info","ts":1551177733.8068542,"caller":"app/license.go:44","msg":"License key from https://mattermost.com required to unlock enterprise features."}
{"level":"info","ts":1551177733.8069105,"caller":"app/plugin.go:130","msg":"Starting up plugins"}
Running Slack Import. This may take a long time for large teams or teams with many messages.
{"level":"info","ts":1551177736.2932286,"caller":"sqlstore/post_store.go:1286","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}
{"level":"warn","ts":1551177736.3451405,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.345193,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3452196,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3452492,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3452692,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3453047,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.35326,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3532999,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3533292,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3533506,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3533683,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.353417,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3649633,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3650622,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3651018,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3651724,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.367854,"caller":"app/slackimport.go:504","msg":"Slack Import: Unable to import Slack channel: zufällig."}
{"level":"warn","ts":1551177736.36852,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.394871,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3949351,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3949645,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3949907,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3950202,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3950863,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3951156,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3951511,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3951712,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3951924,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3952148,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3952627,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3953009,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3953254,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3953457,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3953676,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3953915,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3954177,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.3954403,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.395468,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177736.395493,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177737.3745327,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177744.738198,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=bot_add."}
{"level":"warn","ts":1551177748.3095849,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=app_conversation_join."}
{"level":"warn","ts":1551177748.3101313,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.310163,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3101745,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3101897,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3102381,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3102922,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3107128,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.310746,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3107712,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3107827,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3108277,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3108397,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=channel_archive."}
{"level":"warn","ts":1551177748.310848,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3108616,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.310873,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3108819,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3108897,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3216293,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3216846,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3216956,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3217137,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3217242,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3217466,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.3217752,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"warn","ts":1551177748.321783,"caller":"app/slackimport.go:397","msg":"Slack Import: Unable to import the message as its type is not supported: post_type=message, post_subtype=thread_broadcast."}
{"level":"info","ts":1551177748.3445663,"caller":"app/admin.go:141","msg":"Purging all caches"}
{"level":"info","ts":1551177748.3456972,"caller":"app/license.go:44","msg":"License key from https://mattermost.com required to unlock enterprise features."}

Mattermost Slack Import Log

User Created:
===============

The integration / slack bot user with the email slackimportuser_ @ localhost and password has been imported.

Added channels:
=================

The Slack channel generally already exists as an active Mattermost channel. Both channels were merged.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
allgemein
Could not import Slack channel by chance.
The slack channel machine room already exists as an active Mattermost channel. Both channels were merged.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
maschinenraum
Der Slack-Kanal links existiert bereits als aktiver Mattermost-Kanal. Beide Kanäle wurden zusammengeführt.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
links
Der Slack-Kanal alerts existiert bereits als aktiver Mattermost-Kanal. Beide Kanäle wurden zusammengeführt.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
alerts
Der Slack-Kanal github existiert bereits als aktiver Mattermost-Kanal. Beide Kanäle wurden zusammengeführt.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
github
Der Slack-Kanal lex existiert bereits als aktiver Mattermost-Kanal. Beide Kanäle wurden zusammengeführt.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.

Der Slack-Kanal infrastruktur existiert bereits als aktiver Mattermost-Kanal. Beide Kanäle wurden zusammengeführt.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
Konnte Slack-Benutzer ? nicht zum Kanal hinzufügen.
infrastruktur

Notizen:
=======

* Some messages may not be imported because they are not supported by this importer.
* Messages from Slack-Bot are currently not supported.
* Further error messages could be found in the server logs.

Finished Slack Import.

{"level":"info","ts":1551177748.3462687,"caller":"app/app.go:216","msg":"Stopping Server..."}
{"level":"info","ts":1551177748.3462815,"caller":"app/web_hub.go:120","msg":"stopping websocket hub connections"}
{"level":"warn","ts":1551177748.34629,"caller":"app/web_hub.go:125","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","ts":1551177748.3464823,"caller":"app/plugin.go:193","msg":"Shutting down plugins"}
{"level":"info","ts":1551177748.3465455,"caller":"sqlstore/supplier.go:850","msg":"Closing SqlStore"}
{"level":"info","ts":1551177748.346671,"caller":"app/app.go:237","msg":"Server stopped"}

**Comment by amyblais** [comment]
Hi @kaizimmer1, are those messages in public channels?

**Comment by kaizimmer1** [comment]
Yes, all are in public channels.

**Comment by amyblais** [comment]
@grundleborg Do the error messages above give an indication what might be wrong? If not, I'll continue to troubleshoot with the reporter.

**Comment by grundleborg** [comment]
Two things I can see here:

1. It looks like there are many messages of sub-type `thread_broadcast`. Our importer does not currently support this message type so they will not be imported. Are all the messages that are missing of this type, or are there others of different types that are failing to be imported too?

2. My German isn't great, but I'm seeing a lot of `Could not add Slack User ? to the Channel`. Perhaps this is the issue. Do your Slack users all have the `Username` set? I don't think this is mandatory any more on Slack, but our importer does not work for users with no username.

**Comment by kaizimmer1** [comment]
1. Not all messages are of type thread_broadcast, e.g. this one is not imported, also:
 '   {
        "client_msg_id": "80f32688-bb6c-485e-85d4-e234cc061c03",
        "type": "message",
        "text": "wir hatten gerade eine Sitzung mit ihm",
        "user": "UDCNGVBPE",
        "ts": "1547550453.052900"
    },'
2. Now i converted the users.json file from slack export with 
'perl -p -i -e 's/real_name_normalized/username/msg' users.json' 
to make sure everybody has a username in the profile section and imported it again. 
But still the importer complains:
'User zimmer has no email address in the slack export file. Using zimmer@example.com as a placeholder. The user should update his email address, as soon as he logged in. 
Merged slack user with existing mattermost user with identical address zimmer@example.com and username zimmer.'

Should i delete existing users/teams and start over again?

**Comment by amyblais** [comment]
Hi @kaizimmer1,

If emails are not present in the Slack export archive, then placeholder values will be generated and the System Admin will need to update these manually. More details here https://docs.mattermost.com/administration/migrating.html#using-the-imported-team.

**Comment by amyblais** [comment]
I'll close this for now as there haven't been updates on this for a while.

Please re-open this issue if the problem persists or if you have any further questions,
