### ISSUE TITLE
Delete message from a specific day

### ISSUE THREAD

**Issue by emresaracoglu** [mattermost/mattermost-server#10373]
Hello,

How can I delete all messages from a specific day from the database? 

Mattermost: 5.5.1
Datebase v: 5.5.0
Datebase: postgres

**Comment by amyblais** [comment]
Hi @emresaracoglu,

I believe you can do that via Data Retention: https://docs.mattermost.com/administration/data-retention.html.

Other than that, I don't think there is a way to remove messages from database.

**Comment by emresaracoglu** [comment]
I'm going to try this. 👍

Also, I think the can actually be such a feature in admin console. What do you think?

**Comment by amyblais** [comment]
Awesome, sounds good!

Also, appreciate your feedback - would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
