### ISSUE TITLE
[Help Wanted] [MM-14358] UI Automation: Write an automated test using `cypress` for "Message Draft Pencil Icon visible in channel switcher"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10381]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14358)

Test Key: M14358
Help write an automated test using cypress for the following test case:

*Steps*:
1. In a test channel, type some text in the message input box
2. Do not send the post
3. Switch to another channel
4. Press CTRL/CMD+K (RN apps "Jump to")
5. Type the first few letters of the channel name you typed the message draft in

*Expected:*
After 5) you should see a pencil icon to the left of the channel name in the filtered list

See our end-to-end testing documentation for reference \- [https://developers.mattermost.com/contribute/webapp/end-to-end-tests]

**Comment by kelvintyb** [comment]
Would like to pick this one up :)

**Comment by saturninoabril** [comment]
@kelvintyb Sure, thanks!

**Comment by saturninoabril** [comment]
Thank you @kelvintyb for your contribution 💯 

PR has been merged.  Closing this now.
