### ISSUE TITLE
Big selects in Interactive Dialogs aren't usable

### ISSUE THREAD

**Issue by andrey-yantsen** [mattermost/mattermost-server#10385]
#### Summary
When you have a `select` element in the dialog and it's the first — you can't really use it. E.g. in the following screenshot I have an element with 3 options, but only the last one is visible (webapp or macos desktop):

![image](https://user-images.githubusercontent.com/629281/53605391-4be31680-3baf-11e9-86a0-bbc560b13e55.png)

#### Steps to reproduce
Create following dialog (go-code):

```
model.Dialog{
		Title:       "Registering the Bot",
		SubmitLabel: "Register",
		Elements: []model.DialogElement{
			{
				DisplayName: "Talks in which languages to show?",
				Name:        "languages",
				Type:        "select",
				Default:     "en",
				Options: []*model.PostActionOptions{
					{"English", "en"},
					{"Russian", "ru"},
					{"English + Russian", "en,ru"},
				},
			},
			{
				DisplayName: "Day of Week for the talks",
				Name:        "schedule_dow",
				Type:        "select",
				Placeholder: "Select the day of week",
				Default:     "5",
				Options: []*model.PostActionOptions{
					{"Monday", "1"},
					{"Tuesday", "2"},
					{"Wednesday", "3"},
					{"Thursday", "4"},
					{"Friday", "5"},
				},
			},
		},
	}
```

#### Expected behavior
You can use any option registered in the select.

#### Observed behavior (that appears unintentional) 
You can use only ones which were lucky to fit on the screen.

**Comment by amyblais** [comment]
Hi @andrey-yantsen,

Can you help share some quick details about your environment, such as Mattermost server version and OS version of Mac?

**Comment by andrey-yantsen** [comment]
Sure think, completely forgot about it, sorry. I have the MM running in a local docker (set up by your manual https://docs.mattermost.com/install/docker-local-machine.html) under macOS, here a the version details:

```
Mattermost Version: 5.6.5
Database Schema Version: 5.6.0
Build Hash: 7f10b8349810f571de096e2430bcb56ab3527ae1
EE Build Hash: none
Webapp Build Hash: 2b187bfbc17c20ca66f4c371614de120734c2f05
Build Date: Sat Feb 16 16:15:10 UTC 2019
```

Google Chrome version: 72.0.3626.119.

I've just noticed, that it's not the latest version, I'll update the server today and try again.

**Comment by andrey-yantsen** [comment]
Unfortunately it's the same with the latest version:

```
Mattermost Version: 5.8.0
Database Schema Version: 5.8.0
Build Hash: 24f11a12758fe75ce06269be7f9fb7bb790aec43
EE Build Hash: none
Webapp Build Hash: e860f87e30c9502f2387b67e31e53a07b9110663
Build Date: Fri Feb 15 23:00:03 UTC 2019
```

**Comment by andrey-yantsen** [comment]
Seems like it'll be fixed after mattermost/mattermost-webapp#2235

**Comment by amyblais** [comment]
Closing this as the PR has been merged to master. The fix for this will be available in v5.10 release (to be released in April 16th).

**Comment by amyblais** [comment]
Reopening this since the PR had to be reverted as it caused other issues.

Link to Jira ticket for tracking this improvement: https://mattermost.atlassian.net/browse/MM-14489.

**Comment by amyblais** [comment]
I'll close this issue for now as a "duplicate" as we've opened a Help Wanted issue for this here: https://github.com/mattermost/mattermost-server/issues/10627.
