### ISSUE TITLE
Permissions aren't reverted after removing License

### ISSUE THREAD

**Issue by hectorskypl** [mattermost/mattermost-server#10383]
#### Summary
Permissions aren't reverted after removing E10/E20 license.

#### Steps to reproduce

- Install Mattermost v5.6/5.7/5.8
- Obtain a Evaulation E10/E20 Mattermost License
- Install this license
- Set the system permissions
- Remove The license
- Permissions aren't reverted to state before install the license.

#### Expected behavior
Expected will be revert permission to default Team instalation.

**Comment by amyblais** [comment]
Hi @hectorskypl, just to confirm, you're referring to these settings: https://docs.mattermost.com/deployment/advanced-permissions.html?

**Comment by hectorskypl** [comment]
Hi @amyblais, Yes this is it!

**Comment by amyblais** [comment]
@hectorskypl,

For now, one of our product managers gave feedback that since permissions and roles are stored in the database, they are not changed by removing the license. She'll confirm with some of our developers and report back as soon as there's more information.

**Comment by amyblais** [comment]
A developer confirmed that the above is the case, so as a conclusion this is not a bug.

You can use this [CLI command](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-permissions-reset) to reset permissions settings back to Team Edition.
