### ISSUE TITLE
[Help Wanted] [MM-11697] Environment variable override incorrectly saves back to config.json

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10388]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11697)

Environment variable overrides (e.g. MM_SERVICESETTINGS_SITEURL=[http://example.com]) are incorrectly written back to the configuration when it is saved.

Update the config store to maintain a copy of the config loaded without environment variable overrides, and a copy with the variables overridden. Then, when Set() is called, iterate over the known, overridden fields and use the previously loaded values instead. Calling Get() should continue to return a configuration reflecting the “merged” state, with environment variables overriding settings.

**Comment by cpoile** [comment]
I'd love to take this on!

**Comment by hanzei** [comment]
Thanks for taking care of jet another ticket, @cpoile! :rocket:
