### ISSUE TITLE
Pin Icon directly accessible

### ISSUE THREAD

**Issue by biva** [mattermost/mattermost-server#10380]
In order to pin a message, I have to click on the 3 dots, and then 'Pin to channel'. Same for 'Unpin'.

![image](https://user-images.githubusercontent.com/9964305/53568316-eb79b800-3b61-11e9-95d5-15c498d511ef.png)

Would it be possible to have an icon to pin it directly, either next to the "Flag" icon on the left (my prefered solution, like the picture below), or next to the Emoji icon on the right?

![image](https://user-images.githubusercontent.com/9964305/53569295-2aa90880-3b64-11e9-8980-5d04b0c62e6b.png)

Thanks!

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @biva,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by biva** [comment]
Done here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36980743-add-a-pin-icon-directly-accessible

Thanks :)

**Comment by amyblais** [comment]
Awesome, thank you!
