### ISSUE TITLE
[MM-14384] Demo plugin: add and document interactive (ephemeral) preview capability

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10392]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14384)

https://github.com/mattermost/mattermost-server/pull/10258 added the ability to display interactive preview messages. See https://github.com/levb/mattermost-giphy-plugin for an example. 

We should add a demonstration of the capability, and the necessary documentation to the demo plugin, https://github.com/mattermost/mattermost-plugin-demo.

Specifically we should demonstrate and document:
1. How to set up PostActions and their context for ephemeral messages.
2. The use of the experimental UpdateEphemeralMessage and DeleteEphemeralMessage APIs, including the need to set the ChannelId correctly on the Post
3. The caveats that PostActionIntegrationResponse.Update does not work with ephemeral posts.

**Comment by scottleedavis** [comment]
I am interested in doing this one.  :)
