### ISSUE TITLE
Upgrade docs has a typo in it, in step 14

### ISSUE THREAD

**Issue by khronosschoty** [mattermost/mattermost-server#10399]
https://docs.mattermost.com/administration/upgrade.html step 14 has a typo in it.

sudo mv client/plugins~/ mattermost/client/plugins

should read

sudo mv client/plugins~/ client/plugins

or else the example is inconsistent (or did I miss something?)

**Comment by hanzei** [comment]
Hey @khronosschoty,

Thanks for the report. Would you be open on providing a PR to fix this?

**Comment by amyblais** [comment]
@khronosschoty, also a minor note that you can open documentation related issues in the Docs project: https://github.com/mattermost/docs/issues.

**Comment by amyblais** [comment]
A PR was opened by another community member here: https://github.com/mattermost/docs/pull/2574.

**Comment by amyblais** [comment]
Closing this as the doc PR has been merged.
