### ISSUE TITLE
[Help Wanted] [MM-14375] UI Automation: Flaky test on some test specs

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10398]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14375)

Flaky tests are from the following specs:
- channel/edit_message_spec.js
- channel/message_draft_spec.js
- channel/message_spec.js
- post_header/post_header_spec.js
- team/teams_spec.js

**Comment by 192-sean** [comment]
Assign me please

**Comment by saturninoabril** [comment]
Thanks @192-sean!  We can't directly assign it to your account (as it's limited to core committers only) but sure you may take it 💯

**Comment by hanzei** [comment]
Hey @192-sean,

I just want to check how your work on this going. Do you have any questions?

**Comment by 192-sean** [comment]
Hey sorry unsubscribe me to this one. I've been too busy.

**Comment by saturninoabril** [comment]
Thanks @192-sean for the update and no worries.  I'll take this one.
