### ISSUE TITLE
Documentation - Bulk Import - Field of User Object wrong

### ISSUE THREAD

**Issue by 7-plus-t** [mattermost/mattermost-server#10396]
### Summary
Error in bulk import documentation

#### Steps to reproduce
Go to https://docs.mattermost.com/deployment/bulk-loading.html#user-object
Field `use_military_time` is wrong, should be `military_time`.

#### Expected behavior
Documentation is correct.

#### Observed behavior (that appears unintentional) 
See 
> Steps to reproduce

#### Possible fixes
See `import_types.go`:
```
UseMilitaryTime    *string `json:"military_time,omitempty"`
```
Fix documentation https://docs.mattermost.com/deployment/bulk-loading.html replace `use_military_time` with `military_time`.

**Comment by amyblais** [comment]
Hi @7-plus-t, would you be interested in opening a PR for these issues? Let me know your thoughts.

Also, in the future you can open documentation related issues in the Docs project: https://github.com/mattermost/docs/issues.

**Comment by 7-plus-t** [comment]
Hi @amyblais,
I've opened a PR for it: https://github.com/mattermost/docs/pull/2576

**Comment by amyblais** [comment]
Awesome! It's reviewed and merged. Would you also like to submit a PR for the other issue you submitted? https://github.com/mattermost/mattermost-server/issues/10395

**Comment by 7-plus-t** [comment]
@amyblais Will do. I actually think #10395 should be split into two separate issues.
