### ISSUE TITLE
[Help Wanted] [MM-14399] Demo plugin: add missing hooks (UserHasBeenCreated, FileWillBeUploaded)

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10408]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14399)

The demo plugin should showcase the use of all the hooks some hooks are missing.

Missing hooks:
- UserHasBeenCreated
- FileWillBeUploaded

**Comment by gupsho** [comment]
I can take this.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-demo/pull/23
