### ISSUE TITLE
Inline link with nested parentheses does not work

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10407]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14040)

Original report: https://forum.mattermost.org/t/inline-link-with-nested-parentheses-does-not-work/6651

*Summary*
Not a regression.
Posting an inline link with nested parentheses in the URL does not work.

*Steps to reproduce*
1. Post this message: " how about: [hmm](https://somewhere?param=(currentUser()))? "

*Expected behavior*
Expect inline link with title hmm and URL https://somewhere?param=(currentUser())

*Observed behavior*
No inline link. The original markdown syntax appears directly. However, part of the URL (https://somewhere?param=) is then detected as an auto link and becomes clickable.

**Comment by scottleedavis** [comment]
I'd like to try this one.  Not sure I understand the problem though.

**Comment by hanzei** [comment]
@amyblais Could you help defining the problem a bit more, as you created the ticket.

**Comment by amyblais** [comment]
It came from this community report: https://forum.mattermost.org/t/inline-link-with-nested-parentheses-does-not-work/6651. Let me know what needs to be clarified and I can ping our developers.

**Comment by hanzei** [comment]
Hey @scottleedavis,

Do you need more information to work on this? Is the one from the forum enough?

**Comment by scottleedavis** [comment]
I believe I understand well now, thank you @amyblais and @hanzei !

**Comment by scottleedavis** [comment]
The issue appears to be with the version of marked being used.  When updating to the latest 0.6.2, the problem is solved, however seems to cause issues elsewhere with markdown rendering currently.

**Comment by scottleedavis** [comment]
Turns out, I should have been using mattermost/marked.  Made the change there, and will pull in the appropriate repo hash when it is approved.
