### ISSUE TITLE
[Help Wanted] [MM-14432] UI Automation: Write an automated test using `cypress` for "Identical Message Drafts - Autocomplete shown in each channel"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10409]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14432)

*Test Key: M14432*
Help write an automated test using cypress for the following test case:

*Steps:*
1. Start a draft in Channel A containing just "@"
2. Switch to Channel B, in which there was no draft previously composed.
3. Start a draft in Channel B also containing just "@"
4. Switch back to Channel A

*Expected:*
After 1) At mention auto-complete appears in Channel A
After 3) At mention auto-complete appears in Channel B
After 4) At mention auto-complete is preserved in Channel A

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests

**Comment by oliverJurgen** [comment]
Would like to take this

**Comment by jasonblais** [comment]
Thanks @oliverJurgen!

**Comment by saturninoabril** [comment]
Thanks @oliverJurgen, PR has been merged 🎉
