### ISSUE TITLE
config.json gets overwritten every time the Mattermost service starts or restarts

### ISSUE THREAD

**Issue by dwest-galois** [mattermost/mattermost-server#10404]
#### Summary
config.json gets overwritten every time the Mattermost service starts or restarts

#### Steps to reproduce
I am using Puppet to control this config file, but you can also reproduce this by doing the following:
1. Shut down Mattermost
2. Copy your 'config.json' file (or '/etc/mattermost.json' in my case) to 'config_backup.json'
3. Edit the 'config_backup.json' and make a non-config affecting change, such as moving the "PrivacySettings" block to the bottom of the config file"

>     "PrivacySettings": {
>         "ShowEmailAddress": true,
>         "ShowFullName": true
>     }
 
4. Copy that file over the top of the original 'config.json' and then use a "diff" to confirm that both files are identical.
  `cp config_backup.json config.json`
  `diff config.json config_backup.json`

5. Confirm the timestamp of the last change made to that file
`
ls -l config.json
`

6. Start the Mattermost service (CentOS7)
`systemctl start mattermost`

7. Check the `config.json` file and the "PrivacySettings" code block will have reverted back to its original location.

8. Check the timestamp of the file and you will notice that the file had been modified at the same time you started the mattermost service
`
ls -l config.json
`

9. Perform a "diff" between the two files and you will see the config change differences.
  `diff config.json config_backup.json`

Versions for reference:
OS: Centos 7.6.1810
Mattermost: 5.8
Puppet: 5.5.10
Puppet Module: 2.11.0 https://forge.puppet.com/liger1978/mattermost 

#### Expected behavior
After upgrading to Mattermost 5.8 from 5.6 I noticed that every time I restart the mattermost service, it seems to rewrite the `config.json` file (in my case, I am using /etc/mattermost.json).  This happens whether I start the service from a full shutdown or restart it.  I am using Puppet to manage the configuration, so every time it sees a change in the config file, it will rewrite it with what it thinks it should be and then restarts the service.  This restart will then cause Mattermost to overwrite that config file with its own config, which is usually just a slight variation of it.  Things like indentation and quotation marks are sometimes different.  Config block ordering is also different.  This restart might not be noticeable to most users since they use a web client and a service restart happens pretty quick behind the scenes.  If you are utilizing the API, this can be more problematic, because it will drop any open sessions.

#### Observed behavior (that appears unintentional) 
Performing a restart on the service shows that the file is being altered during the startup process

> [root@white ~]# ls -l /etc/mattermost.json
> -rw-r--r--. 1 mattermost mattermost 15621 Mar  4 13:50 /etc/mattermost.json
> [root@white ~]# systemctl restart mattermost
> [root@white ~]# ls -l /etc/mattermost.json
> -rw-r--r--. 1 mattermost mattermost 15621 Mar  4 13:53 /etc/mattermost.json

Checking the logs shows that the config is being loaded from the config file, but says nothing about writing to it.

> Mar  4 13:50:46 white mattermost: {"level":"info","ts":1551736246.7553136,"caller":"app/server.go:197","msg":"Current working directory is /opt/mattermost-5.8.0"}
> Mar  4 13:50:46 white mattermost: {"level":"info","ts":1551736246.7554328,"caller":"app/server.go:198","msg":"Loaded config file from /etc/mattermost.json"}
> Mar  4 13:50:46 white mattermost: {"level":"info","ts":1551736246.805759,"caller":"sqlstore/post_store.go:1287","msg":"Post.Message supports at most 4000 characters (4000 bytes)"}
> Mar  4 13:50:46 white mattermost: {"level":"info","ts":1551736246.8096826,"caller":"jobs/workers.go:68","msg":"Starting workers"}
> Mar  4 13:50:46 white mattermost: {"level":"info","ts":1551736246.8097816,"caller":"app/server.go:402","msg":"Starting Server..."}
> Mar  4 13:50:46 white mattermost: {"level":"info","ts":1551736246.8103366,"caller":"app/server.go:462","msg":"Server is listening on [::]:8065"}
> Mar  4 13:50:46 white mattermost: {"level":"info","ts":1551736246.810541,"caller":"jobs/schedulers.go:72","msg":"Starting schedulers."}
> Mar  4 13:50:46 white mattermost: {"level":"info","ts":1551736246.8244796,"caller":"app/web_hub.go:75","msg":"Starting 4 websocket hubs"}

It seems to be rewriting the config file using cached settings or settings from the `System Console`.  Manually editing the file and then choosing "Reload Configuration from Disk" does not to retain the changes.  Neither does clearing the cache and then reloading the config from disk.

This might be related to #10402 or #10388 .

#### Possible fixes
I am actually not sure if this really is a bug or an intended action.  Rewriting a config file on startup does not feel like a good way to manage the settings.  It is also problematic if you maintain the file in a configuration management system, like Puppet.  Ideally, I would like it to only write the config file if you are saving a change in the 'System Console'.   If this is an intended action, then I would like an option to disable writing the config to disk so that I can manage it entirely in Puppet.

**Comment by lieut-data** [comment]
Thanks for the report, @dwest-galois. Unfortunately, this behaviour is currently by design. The Mattermost service assumes it has full write control over the configuration file, and will update it to match defaults or internal formatting as required.

I agree that it would be ideal not to write to the config.json unless a user takes some action. Moving forward, we are iterating on a solution that actually backs the configuration in the database (requiring but a single database connection string to kickstart the process).

As a stop gap, you might consider populating Puppet with the version of the config.json that Mattermost first writes to disk on startup, and then make your changes relative to that — Mattermost will write to the file on disk, but it the effective bytes won’t change.

**Comment by dwest-galois** [comment]
Okay, thank you for looking at this.  If this is the intended behavior, then I will tackle this from the puppet side of things.

**Comment by dwest-galois** [comment]
I just wanted to add an update to this.  This turned out to be an issue with a couple values in Hiera conflicting with a couple of values in Mattermost.  Specifically, `ServiceSettings/EnableOnlyAdminIntegrations` and `TeamSettings/EnableTeamCreation` were both getting set to `True` when Mattermost rebooted, while my hiera config had them set to `False`.   I suspect that Mattermost is controlling those values in the `Advanced Permissions` scheme in the `System Console` and then forcefully writing them to the JSON file during startup.  This might be leftover from the transition to the new scheme, but let me know if I am wrong.  You can find more details in the following Issue:

https://gitlab.com/harbottle/puppet-mattermost/issues/44

**Comment by lieut-data** [comment]
Thanks for the follow-up, @dwest-galois! Indeed, `EnableOnlyAdminIntegrations` and `EnableTeamCreation` have both been deprecated and moved into advanced permissions -- see https://docs.mattermost.com/administration/changelog.html#removed-and-deprecated-features for more details.
