### ISSUE TITLE
[Help Wanted] [MM-14246] Plugin framework: support transactional semantics with KV Store

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10410]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14246)

The KVStore used by plugins doesn't handle concurrent writes to the same key elegantly. While there is no data corruption, it is impossible for two instances of the same plugin (in an HA environment) to avoid stomping on a concurrent change, making some data models tricky to implement (e.g. a vote counting record with multiple users writing).

As a step towards improving this, let's consider an extension to the API:
```go
// KVGetWithChangeId will retrieve a value based on the key, including a monotonically increasing change identifier to help manage concurrent writes. Returns nil for non-existent keys.
KVGetWithChangeId(key string) ([]byte, int64, *model.AppError)

// KVSetWithChangeId will store a key-value pair, unique per plugin, rejecting the change if the changeId has been increased concurrently.
KVSetWithChangeId(key string, changeId int64, value []byte) *model.AppError
```

The implementation would use a transaction behind the scenes. This only helps avoid concurrent writes to the same key, but might still solve a large class of problems.

**Comment by e-ninja0** [comment]
Grabbing this to work on next.

**Comment by hanzei** [comment]
Thanks you very much @e-ninja0! :rocket:

**Comment by ali-farooq0** [comment]
Had a conversation with @lieut-data and @hmhealey and settled on adding `KVCompareAndSwap(key string, old []byte, new []byte) *model.AppError` instead of the initial proposal.

Conversation: 
https://community.mattermost.com/core/pl/w69gts46p7dwm84epsm7i9gtjc
https://community.mattermost.com/core/pl/6uu3qs3ccbgdzp7hdpzgpqqnno

**Comment by ali-farooq0** [comment]
Created a PR for this
https://github.com/mattermost/mattermost-server/pull/10634

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/10634
