### ISSUE TITLE
[Help Wanted] [MM-14491] If a link tooltip has a button in the tooltip, a user cannot click it because the popover will be hidden when the cursor leaves the link

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10424]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14491)

If a link tooltip has a button in the tooltip, a user cannot click it because the popover will be hidden when the cursor leaves the link.

Proposal is to avoid hiding the popover when the cursor is moved away from the link embedded to the button.

**Comment by jasonblais** [comment]
@kosgrz Is looking at this one :)
