### ISSUE TITLE
[Help Wanted] [MM-14548] UI Automation: Write an automated test using Cypress for "Search results Right-Hand-Side: Post a comment"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10437]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14548)

*Test Key: S14548*

*Repro Steps:*
1. In any channel, post message `asparagus`
2. Search for the term `asparagus`
3. Click the reply icon next to a search result
4. Observe right-hand-side switches from search results view to reply thread view
5. Type in a reply `Replying to asparagus` and press Enter

*Expected:*
- Stays in reply / message thread view and the reply is posted

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by thekiiingbob** [comment]
I'll take this one.

**Comment by saturninoabril** [comment]
Sure and thanks @thekiiingbob 🚀

**Comment by saturninoabril** [comment]
Thank you @thekiiingbob.  PR has been merged recently.
