### ISSUE TITLE
Confusing username message

### ISSUE THREAD

**Issue by limenleap** [mattermost/mattermost-server#10436]
#### Summary
Some new users are getting confused with the message for the new username

#### Steps to reproduce
This is Ux issue. People are getting confused

#### Expected behavior
The English used in the hint is misleading and quite verbose. People seem to follow it "exactly" and end up with unnecessarily complex usernames

#### Observed behavior (that appears unintentional) 
See the photo

#### Possible fixes
Change the wording and make it clearer

![image](https://user-images.githubusercontent.com/20351066/54200263-013b9580-44f1-11e9-80cf-d39d3ffb283d.png)

**Comment by amyblais** [comment]
@limenleap Thank you for reporting this. @esethna Do I create a ticket for UX to improve the help text?

**Comment by amyblais** [comment]
Hi @limenleap, letting you know that I've opened a ticket for our UX team here: https://mattermost.atlassian.net/browse/MM-14583.

**Comment by andrewbrown00** [comment]
Hi @limenleap, I'm Andrew, I'm on the Product & UX team at Mattermost. I was wondering if you have time to jump on a Zoom call (~10 minutes) to provide feedback around the proposed changes to the helper text when creating a username.

**Comment by amyblais** [comment]
Hi @limenleap,

Letting you know that we opened a Help Wanted issue here for our community to work on this improvement: https://github.com/mattermost/mattermost-server/issues/10552.

Feel free to work on the issue if you're interested to, and let us know if you have any questions.

Closing this for now as a duplicate,
