### ISSUE TITLE
Please separate the archiving channel API and leaving channel API

### ISSUE THREAD

**Issue by ferstar** [mattermost/mattermost-server#10432]
I learned about this API from here: [Delete a channel](https://api.mattermost.com/#tag/channels%2Fpaths%2F~1channels~1%7Bchannel_id%7D%2Fdelete)

It seems that both archiving channel and leaving channel are using the same API: `DELETE /channels/{channel_id}`, and this caused a problem:

> To avoid invalidation of incoming web hooks service caused by members mis-archiving channels, I use Nginx regex filter ignoring `DELETE /api/v[0-9]+/channels/(.+)` requests.
> At first this solution was perfect until one day I wanted to leave a channel.
> **I CANNOT LEAVE ANY CHANNEL BECAUSE I BLOCKED the archiving channel API**, and unfortunately both archiving channel and leaving channel are using the same API

I expect the APIs of these two functions(leave, archive) to be separated, thx:-)

**Comment by amyblais** [comment]
@crspeller Should I create an improvement ticket to fix this behaviour?

**Comment by crspeller** [comment]
@ferstar Hi. They are actually two separate APIs however your regex is catching both:
Archive channel: `DELETE /api/v4/channels/{channel_id}`
Leave channel: `DELETE /api/v4/channels/{channel_id}/members/{user_id}`

**Comment by ferstar** [comment]
@crspeller I changed my regex to `/api/v[0-9]+/channels/[0-9a-z]+$` and it worked, thanks for your reply.
