### ISSUE TITLE
[MM-14530] Render emojis in Message Attachment field titels

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10433]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14530)

Emojis in Message Attachment field titles currently don't get rendered. This ticket is about fixing this. This should be fixed in both the webapp and and the mobile app.

[Matterpoll](https://github.com/matterpoll/matterpoll) can be used to test this. You can use e.g.`/poll "Do you like pizza?" ":+1:" ":-1:"` and then end the poll to see a post with emojis in field titles.

If you have any questions or would like feedback, feel free to ask in the (https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by lisakycho** [comment]
I would love to work on this.
Could I get some pointers on how to add plugins?

**Comment by hanzei** [comment]
Thanks for looking into this @lisakycho! :+1: 
For testing purposes you can use [Matterpoll](https://github.com/matterpoll/matterpoll). Guidance on how to install this plugin can be found in the [Readme](https://github.com/matterpoll/matterpoll#installation).
Let me know if this helps.

**Comment by lisakycho** [comment]
@hanzei 
Sorry, I think I'm confused about what this ticket wants after testing it out.

![image](https://user-images.githubusercontent.com/15200562/55108549-7387aa80-5099-11e9-856c-059af8ad8e44.png)

In my test case are you looking to replace the "Yes" and "No" with the emojis?

**Comment by hanzei** [comment]
When you create a poll with `/poll "Do you like pizza?" ":+1:" ":-1:"` and end it, it currently looks like this:
![Screenshot from 2019-03-27 21-50-01](https://user-images.githubusercontent.com/16541325/55111311-650db300-50da-11e9-8e5e-091b6a36c5b1.png)
As you can see the two emojis `:+1:` and `:-1:` don't get rendered. This ticket is about fixing this.

**Comment by lisakycho** [comment]
@hanzei I don't seem to even get that bug on my pre-release mattermost. I've pulled from the latest server and webapp and have v1.0.3 of matterpoll locally. 

Here is what my poll looks like:
![image](https://user-images.githubusercontent.com/15200562/55113226-265d0600-50a4-11e9-93d3-83dad5b795bf.png)
![image](https://user-images.githubusercontent.com/15200562/55113242-2eb54100-50a4-11e9-8559-da1d317d5f91.png)

**Comment by hanzei** [comment]
@lisakycho You need to specify the answers options of the poll. Currently you are using the default answers `Yes` and `No`. Try `/poll "Do you like pizza?" ":+1:" ":-1:"` instead

**Comment by lisakycho** [comment]
@hanzei 

I’ve cloned matterpoll repo and tried to run the command make to make the distributable file to upload to my local mattermost. 
When I do this I get errors such as “undefined: testutils.GetLocalizer” even though I have not made any changes yet after pulling it.  
I’ve pulled several times to update my branch but I’m unsure why I am getting undefined methods. 
I can show you the full error logs if you need.

**Comment by hanzei** [comment]
@lisakycho You can just use the [latest release from GitHub](https://github.com/matterpoll/matterpoll/releases/tag/v1.0.3).

**Comment by jasonblais** [comment]
Hey @lisakycho, were you able to resolve the errors you were seeing?

**Comment by lisakycho** [comment]
Hi, @jasonblais 
yes I'm still getting errors.
I've tried to clean my build by removing the server/vendor, pulled from master and tried to `make` (to make the distributable file) again but still getting errors that it cannot find packages.

The reason I can't use the distributable file linked my hanzei is because if I make changes to these files there is no way I can test this without making a distributable file.
I have used this file on my local mattermost to confirm the bug.

**Comment by jasonblais** [comment]
@hanzei Would you have insight based on the note above?

**Comment by hanzei** [comment]
> The reason I can't use the distributable file linked my hanzei is because if I make changes to these files there is no way I can test this without making a distributable file.

Why do you need to make changes? The latest release should be fine.

**Comment by hanzei** [comment]
If you really need to make changes to the code base, you can try to switch back to an older version via `git checkout v1.0.3`.

**Comment by lisakycho** [comment]
Thank you so much for your help @hanzei, I think i misunderstood the ticket at first!! 
I created a pull request with my changes!
