### ISSUE TITLE
[Help Wanted] [MM-14575] Automatically serve static files for plugins

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10447]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14575)

See [https://community.mattermost.com/core/pl/qm9houtcx7rgtf9akeyci5htqr] for full context.

Plugins should be able to include static files in the bundle, to be served automatically by the mattermost-server.

* Plugins bundle the files that should be served in a directory named public.
* After the plugin bundle is uploaded and the plugin enabled, the server takes care of serving these files under [http://$SITE_URL/plugin/$PLUGIN_ID/public/].
* The change should update the sample plugin’s Makefile, and the demo plugin with an example.

**Comment by happygaijin** [comment]
I put some code together for this. I still need to test some things though.

**Comment by jasonblais** [comment]
Thank you! Removed `Up For Grabs` label for now

**Comment by happygaijin** [comment]
https://github.com/mattermost/mattermost-server/pull/10476
https://github.com/mattermost/mattermost-plugin-sample/pull/33
https://github.com/mattermost/mattermost-plugin-demo/pull/24
