### ISSUE TITLE
[Help Wanted] [MM-14571] UI Automation: Write an automated test using `cypress` for "at-mention still triggers notification if username is not listed in words that trigger mentions"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10441]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14571)

*Test Key:* N-14571

Steps:
1. Click the hamburger main menu
2. Select "Account Settings" then select "Notifications"
3. Click “Edit” to the right of “Words that trigger mentions”
4. De-select "Your non-case sensitive username"
5. Ensure that your username does not appear in the "Other non-case sensitive words, separated by commas" box
5. Click “Save”
6. Use another account to post a message @-mentioning your username

Expected:
You receive a notification with a mention jewel on the channel and your username is highlighted.

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by thekiiingbob** [comment]
I'd like to take this one.
