### ISSUE TITLE
[Help Wanted] [MM-14570] UI Automation: Write an automated test using `cypress` for "Words that trigger mentions - Deselect username"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10442]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14570)

*Test Key:* N-14570

Steps:
1. Click the hamburger main menu
2. Select "Account Settings" then select "Notifications"
3. Click “Edit” to the right of “Words that trigger mentions”
4. De-select "Your non-case sensitive username"
5. Click “Save”
6. Use another account to post a message containing your username

Expected:
Username does not highlight, and mention is not triggered

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by thekiiingbob** [comment]
I'll take this one since I just worked on the other at-mention/notification work.

**Comment by saturninoabril** [comment]
Thanks @thekiiingbob 🚀

**Comment by saturninoabril** [comment]
PR has recently merged.  Thank you @thekiiingbob for your contribution!

Closing this issue now.
