### ISSUE TITLE
[Help Wanted] [MM-14576] Add p.API.GetBundlePath()

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10448]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14576)

See https://community.mattermost.com/core/pl/qm9houtcx7rgtf9akeyci5htqr for full context.

We should add a `GetBundlePath() string` method to the plugin APIs, and then guide plugin developers to use that to access static (bundled) files from their Go code.

This will allow future flexibility of storing the assets elsewhere.

See also related ticket https://mattermost.atlassian.net/browse/MM-14575 (https://github.com/mattermost/mattermost-server/issues/10447)

**Comment by hanzei** [comment]
I will take care of this one.
