### ISSUE TITLE
[Help Wanted] [MM-14577] UI Automation: Write an automated test using `cypress` for "Un-pinning and pinning a post removes and adds badge"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10449]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14577)

Test Key: M14577
Help write an automated test using cypress for the following test case:

*Steps*:
1. On a message in center channel and click [...] > Pin to channel 
2. Also flag that same message
3. Click flag icon in channel header to view the list of flagged posts, observe message in RHS flagged posts list
4. In center channel, click [...] > Un-pin from channel, observe Pinned badge removed in center and RHS
5. In center channel, click [...] > Pin to channel

*Expected*:
After step 2: Post appears in flagged list, and displays Pinned badge
After step 4: Post still appears in flagged list, and Pinned badge is removed in both center and RHS
After step 5: Pinned badge returns on message in both center and RHS

**Comment by oliverJurgen** [comment]
Would like to take this

**Comment by saturninoabril** [comment]
Sure, thanks @oliverJurgen!

**Comment by jespino** [comment]
Fixed by mattermost/mattermost-webapp#2577
