### ISSUE TITLE
Mattermost Plugin Bounty Program

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#10457]
## Mattermost Plugin Bounty Program
 
Mattermost has launched a plugin bounty program to work with our integrations community to create highly-requested plugins.

The bounty per plugin ranges from $1,000 to $2,000. The period for submissions is March 16 - May 16, 2019.

If you’re interested joining the program,
- Sign in to https://community.mattermost.com, join the Contributors team and direct message @jason.blais, or
- Email jason[at]mattermost.com with the subject “Mattermost Plugin Bounty Program”

### Eligibility

Eligibility is limited to countries we can pay the bounty to. Wires to notable banks are preferred, but other options exist. Please contact us to ensure eligibility.

Moreover, submissions must meet the criteria specified in “Open Projects” section. See below for further details.

Paid staff or hiring candidates on a paid audition are not eligible to participate.

### Rules

Multiple submissions are considered on a first-come first-serve basis. If the first submission meets the bounty criteria for a plugin, the first submission receives the bounty.
 
If multiple people are interested working on the same plugin, we encourage people to work together. The bounty is allocated equally to all contributors. However, Mattermost reserves the right to split the bounty unequally, for instance, when one of the contributors completed majority of the work.

At all times, Mattermost reserves the right to decide if a submission receives a bounty, but we aim to set clear expectations and strive for transparency and fairness throughout the process.

To submit your plugin for a bounty
 - Publish it in a GitHub repository licensed under Apache 2.0 or MIT
 - Share the link via
   - direct message to @jason.blais in https://community.mattermost.com, or
   - email to jason[at]mattermost.com with the subject “Mattermost Plugin Bounty Program”

Mattermost may ask you to transfer the repository under the https://github.com/mattermost organization for long-term maintenance. If so, we’ll take steps to ensure you are credited for your work and recognized as the original creator. For an example project transferred to Mattermost, see https://github.com/mattermost/desktop. 

### Resources

 - Plugin documentation: https://developers.mattermost.com/extend/plugins/
 - Sample plugin: https://github.com/mattermost/mattermost-plugin-sample 

### Open Projects

Submissions accepted on March 16 - May 16, 2019.

#### Cisco WebEx Meetings Server

Bounty: $2,000
Repository name: mattermost-plugin-webex

Requirements:
 - Uses the Mattermost plugin framework
   - Plugin documentation: https://developers.mattermost.com/extend/plugins/
   - Sample plugin: https://github.com/mattermost/mattermost-plugin-sample 
 - Meets the functionality and quality of the existing Zoom plugin: https://github.com/mattermost/mattermost-plugin-zoom
 - Supports On-Prem version of Cisco WebEx Meetings Server
 - Meets Mattermost user experience criteria defined in https://docs.mattermost.com/developer/fx-guidelines.html 
 - Includes a README file with a screenshot of the plugin in action, list of features, an installation guide and a development guide. For an example, see https://github.com/mattermost/mattermost-plugin-github/blob/master/README.md 

#### Skype for Business

Bounty: $1,000
Repository name: mattermost-plugin-skype-for-business

Requirements:
 - Uses the Mattermost plugin framework
   - Plugin documentation: https://developers.mattermost.com/extend/plugins/
   - Sample plugin: https://github.com/mattermost/mattermost-plugin-sample 
 - Meets the functionality and quality of the existing Zoom plugin: https://github.com/mattermost/mattermost-plugin-zoom
 - Meets Mattermost user experience criteria defined in https://docs.mattermost.com/developer/fx-guidelines.html 
 - Includes a README file with a screenshot of the plugin in action, list of features, an installation guide and a development guide. For an example, see https://github.com/mattermost/mattermost-plugin-github/blob/master/README.md 

#### Jenkins

Bounty: $1,500
Repository name: mattermost-plugin-jenkins

Requirements:
 - Uses the Mattermost plugin framework
   - Plugin documentation: https://developers.mattermost.com/extend/plugins/
   - Sample plugin: https://github.com/mattermost/mattermost-plugin-sample
 - Meets the functionality and quality of the Slack-Jenkins app: https://slack.com/apps/A0F7VRFKN-jenkins-ci
 - Supports the following functionality
   - Trigger jobs with and without parameters
   - Get logs from a job in a file attachment, not as a message (this is because the logs can be huge, so it’s easier to preview a file attachment)
   - Get artifacts
   - Get test results
   - Configure/create/delete jobs
 - Meets Mattermost user experience criteria defined in https://docs.mattermost.com/developer/fx-guidelines.html
 - Includes a README file with a screenshot of the plugin in action, list of features, an installation guide and a development guide. For an example, see https://github.com/mattermost/mattermost-plugin-github/blob/master/README.md 

#### GitLab

Bounty: $1,000
Repository name: mattermost-plugin-gitlab

Requirements:
 - Uses the Mattermost plugin framework
   - Plugin documentation: https://developers.mattermost.com/extend/plugins/
   - Sample plugin: https://github.com/mattermost/mattermost-plugin-sample 
 - Meets the functionality and quality of the existing GitHub plugin: https://github.com/mattermost/mattermost-plugin-github 
 - Meets Mattermost user experience criteria defined in https://docs.mattermost.com/developer/fx-guidelines.html 
 - Includes a README file with a screenshot of the plugin in action, list of features, an installation guide and a development guide. For an example, see https://github.com/mattermost/mattermost-plugin-github/blob/master/README.md 

### Current Participants

 - Cisco WebEx Meetings Server: `eriktate`
 - Skype for Business: `kosgrz`
 - Jenkins: `waseem18`
 - GitLab: `manland`, `checkaayush`

**Comment by kosgrz** [comment]
I started working on the Skype for Business plugin :).

**Comment by checkaayush** [comment]
@jasonblais Quick questions:

1. For Cisco WebEx Meetings Server, there doesn't seem to be an API for supporting the on-prem version. See [this](https://community.cisco.com/t5/cloud-collaboration/cwms-onprem-apis/td-p/3517534). How should that part be handled?

2. For Skype for Business, I looked at [this](https://docs.microsoft.com/en-us/skype-sdk/trusted-application-api/docs/overview) for the API. It is in developer preview and isn't (and might never be) supported for production usage outside of Microsoft Teams. How to proceed in that case?

**Comment by checkaayush** [comment]
I'm starting work on the Gitlab plugin.

**Comment by jasonblais** [comment]
Thank you @checkaayush for your interest!

1. Good observation. I'm not sure - though we have someone working on the on-prem version so we'll see if they find an approach
2. Some progress has been made with skype Web SDK, more details here: https://community.mattermost.com/core/pl/wjx3gn79bbr38x5wnpazdezfho

And thanks for your interest on the GitLab plugin! Two notes:
1. Please reach out to me to ensure eligibility - we want to make sure we're able to pay the bounty for you! You can either
   - Sign in to https://community.mattermost.com, join the Contributors team and direct message @jason.blais, or
   - Email jason[at]mattermost.com with the subject “Mattermost Plugin Bounty Program”
2. Another community member shared interest about the GitLab plugin as well. You could build one yourself, or collaborate with @manland - if you're open to and interested collaborating, I've created a public channel to discuss the plugin here: https://community.mattermost.com/core/channels/plugin-gitlab

Thanks again for your interest 👍

**Comment by manland** [comment]
Hello @checkaayush 

I have started the implementation and I will share soon my first work on [manland/mattermost-plugin-gitlab](https://github.com/manland/mattermost-plugin-gitlab).

Today I can login and display report tasks. Before sharing it i have to : 
* implements webhooks
* modify the front

If you want to discuss I'm on https://community.mattermost.com/core/channels/plugin-gitlab

BTW : thanks you @jasonblais for the link between us ;)

**Comment by jasonblais** [comment]
We received the following submissions from our contributors who won the bounties!

1. @manland - GitLab https://github.com/manland/mattermost-plugin-gitlab
2. @kosgrz - Skype for Business https://github.com/kosgrz/mattermost-plugin-skype4business
3. @waseem18 - Jenkins https://github.com/waseem18/mattermost-plugin-jenkins

Thanks to all participants! For phase 2 of the bounty program, see: https://github.com/mattermost/mattermost-server/issues/10915
