### ISSUE TITLE
Add password type for Interactive Dialogs

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10460]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14593)

Interactive Dialogs allow integrations to receive some form-styled input from users and have that input submitted back to the integration. An Interactive Dialog consists of a list of elements. These elements have a defined type such as `text` or `select`. Elements with the type `text` can also have a sub type, that defines how the field is shown and what keyboard is used.

This ticket is about adding a sub type `password`. When `subtype` is set to `password` the characters  of the field should be obfuscated when written.

This ticket requires changes in both the web app and the mobile app.

For more information about Interactive Dialog, see https://docs.mattermost.com/developer/interactive-dialogs.html

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by goku321** [comment]
Can I take this one up?

**Comment by hanzei** [comment]
Sure. Thanks for working on this @goku321 :tada:

**Comment by goku321** [comment]
I need some help on this ticket. I did some code walk-through but couldn't figure out where to add password type. It would be helpful if i can get some starting point.

**Comment by hanzei** [comment]
Hey @goku321,

On the server side the type is defined by the `subtype` field in the payload. See https://docs.mattermost.com/developer/interactive-dialogs.html#text-elements

Or are you talking about the webapp part?

**Comment by goku321** [comment]
Hi @hanzei,
Thanks for your input. And, yes I was talking about the webapp part.

**Comment by hanzei** [comment]
@jwilander Can you help with the questions above? I'm not to familiar with the webapp code.

**Comment by jwilander** [comment]
@goku321 you'll likely want to make some changes in here to return a password input when the type is `password`
https://github.com/mattermost/mattermost-webapp/blob/master/components/interactive_dialog/dialog_element.jsx

**Comment by goku321** [comment]
@jwilander Thanks, this was helpful. A question: Would it be better to add a 'password' string to the array `validTypes` inside https://github.com/mattermost/mattermost-webapp/blob/master/components/widgets/settings/text_setting.jsx ?

**Comment by jwilander** [comment]
Yeah I think that'd be great @goku321 👍

**Comment by goku321** [comment]
Just a heads-up that I am working on the mobile app changes and currently, writing test cases for the changes made.

**Comment by hanzei** [comment]
This issue is resolved. Thank you very much @goku321 :tada:
