### ISSUE TITLE
Add radio type in Interactive Dialogs

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10465]
Interactive Dialogs allow integrations to receive some form-styled input from users and have that input submitted back to the integration. An Interactive Dialog consists of a list of elements. These elements have a defined type such as `text` or `select`.

This ticket is about adding a `radio` type for Dialog elements. Setting this type for an element should render a list of radio button options that allow the user to quickly select an option, like:

```
( ) Engineering
( ) Sales
( ) Administration
```

Notes: 
- The list of options is provided via `options', similar to the `select` type.
- The default value is the first element of the list. The integration might change this by setting `default' to one of the defined options.

This ticket requires changes in both the web app and the mobile app.

For more information about Interactive Dialog, see https://docs.mattermost.com/developer/interactive-dialogs.html

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14274)

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For general technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers). For plugins, integrations and the REST API, please [join our Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by sdcaulley** [comment]
I would like to take this on.

**Comment by sdcaulley** [comment]
Is there someone I can talk to about dialog_element.jsx

**Comment by hanzei** [comment]
@sdcaulley Thanks for working on this issue. Would you mind posting your questions in the ~Developers Channel on the [Mattermost Community Server](https://community.mattermost.com)? This is the easiest way to get a couple of people looking a this.

**Comment by hanzei** [comment]
Hey @sdcaulley,

How is your work on this going? Do you still have questions?

**Comment by sdcaulley** [comment]
Hi @hanzei 
Going it slow. This application is different enough from ones I have worked on in the past that it is taking me some time to trace through the various connections, and see how things work.  

No questions at the moment.

**Comment by sdcaulley** [comment]
Ok....I have a question/suggestion.  This issue is for the addition of radio button into the interactive dialog.  There is a file -  /components/admin_console/radio_setting.jsx - that already seems to be doing what this issue is asking for (at least for the web app.  I haven't looked at the mobile app yet.)  It seems to me that the smart thing to do is copy the text_setting.jsx pattern - have the element in /components/widgets/setting and then call it where needed like in /components/admin_console/text_setting.jsx.  

That is more of a code restructure then just new code insertion, and I do not want to go ahead with it until someone official has a look at it.

**Comment by hanzei** [comment]
@lieut-data Can you help with this? I'v not to familiar with this part of the code.

**Comment by lieut-data** [comment]
@sdcaulley, in general we're not opposed to refactoring to reduce code duplication and increase clarity. Can you elaborate on your proposal a bit to help me understand better?

**Comment by sdcaulley** [comment]
@lieut-data 
When going though the code I observed that there was a pattern for the text inputs in forms:
    - in /components/widgets there is TextSetting.jsx
    - Both InteractiveDialog and AdminConsole use this component for building forms.
    - in /components/admin_console there is RadioSetting.jsx that is set up very similar to /components/widgets/TextSetting.jsx
    - I propose that the pattern started with TextSetting be continued with RadioSetting:
        - move /components/admin_console/radio_setting.jsx to /components/widgets with the other global *_setting.jsx files.
        - create a new /components/admin_console/radio_settings.jsx file that calls the one in widgets (following the text_setting.jsx pattern).

This will make the RadioSettings component available globally - including InteractiveDialog (which is what this issue is asking for) - and follows and already emerging pattern.

**Comment by lieut-data** [comment]
@sdcaulley, that seems like a great suggestion! cc @jespino re: insight into ongoing efforts around common components.

**Comment by jespino** [comment]
@sdcaulley @lieut-data Thanks, yes, this is very related to our approach to reusable components. I would suggest to move that to `components/widgets/inputs`, and there we can create the `text_input.jsx`, `radio_input.jsx` and anything else that we need.

One important thing here is the widgets library must be consistent with the rest of the widgets (scss file aside to the component, the component root element should have the class with the same name as the component, for example `InputText` component should have `className="InputText"` in the root element and that components doesn't use ever redux).

**Comment by sdcaulley** [comment]
@jespino I understand what you are saying here about the composition of the elements.  I am a bit confused about the redux part though.  Two of the components in `components/widgets/inputs` reference `mattermost-redux/utils/helpers`, is that not considered redux?

Also, for clarification, the components in `components/widgets/inputs` seem to be for specific use cases, is this the best place for the components that are currently in `components/widgets/settings`?  Or maybe a better question is: what is the intended difference between `components/widgets/inputs` and `components/widgets/settings`?

**Comment by jespino** [comment]
@sdcaulley For me, in both cases are inputs but a `settings` folder works for me too, it depends on the intention of the component and which is the use cases, is for a setting representation or is for an input representation that is used in the settings? that is the key.

About the `mattermost-redux/utils/helpers`, yes I think I express wrongly my point there, the idea is they don't need any data from the store to work (and none of the its children). From that module we use just utility functions that doesn't need the store data at all.

**Comment by jespino** [comment]
By the way, there is a component that have access to the store, but needs to be removed from the widgets library or redesigned to not use it.

**Comment by sdcaulley** [comment]
@jespino Thank you for the clarification.  I am very new to this code base, so I am still working on the thought processes behind where components are placed.  Looking at how the InteractiveDialog component is currently set up, and where it is currently pulling its elements from, the `components/widgets/settings` seems to be the best place.  It would at least be following the already established pattern.

And thank you for the clarification on redux.

**Comment by jespino** [comment]
@sdcaulley that works for me. Let me know if you have any other questions 😊

**Comment by lieut-data** [comment]
@sdcaulley, anything I can to do help with your efforts here?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by patrickkang** [comment]
Can i grab this one?

**Comment by hanzei** [comment]
Sure, please go ahead @patrickkang :+1:

**Comment by hanzei** [comment]
Thank you very much @patrickkang for implementing this :tada: :+1:
