### ISSUE TITLE
[Help Wanted] [MM-14636] UI Automation: Write an automated test using `cypress` for "System Messages wrap properly"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10474]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14636)

*Test Key: Mult14636*

*Steps:*
1. Change any channel header to something relatively long
2. Observe the resulting system message

*Expected:*
System messages should display correctly and wrap to a second line of text when needed

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by reflog** [comment]
I'll take this one!

**Comment by hanzei** [comment]
Thanks @reflog!
