### ISSUE TITLE
Write an automated test using `cypress` for "Remove Team Icon"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10470]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14632)

*Test Key: TS14632*

*Steps:*
1. On a team that has a team icon
2. Go to main menu > Team Settings > Team Icon > Edit
3. Click the `x` in the top right corner of the image, then click "Cancel".
4. Click the `x` in the top right corner of the image, then click "Save". 

*Expected:*
After 3)  Team icon is NOT removed.
After 4)  Team icon is removed from modal, left-hand-side header and team sidebar (if you're on multiple teams)

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by cannalee90** [comment]
I'll take this one

**Comment by Druthi** [comment]
I'll take this one!

**Comment by hanzei** [comment]
Thanks for working on this @Druthi. :tada:  Let me know if you have any questions.

**Comment by Druthi** [comment]
@hanzei No questions at the moment! This is my first issue so looking through the docs and getting a feel of the process.

**Comment by saturninoabril** [comment]
Hello @Druthi, just checking on this.  If you have question, let me know or you may also join our community at https://community-release.mattermost.com/core/channels/ui-test-automation

**Comment by hanzei** [comment]
Hey @Druthi, just want to check if you are still working on this.

**Comment by hanzei** [comment]
Thanks for the update, @Druthi :+1:

**Comment by veera83372** [comment]
@hanzei  @cpanato  Could one of you please assign this to me?

**Comment by hanzei** [comment]
Thanks for the quick PR @veera83372 :tada:

**Comment by VishalSwarnkar** [comment]
I'll take this one! if it's still open to accept

**Comment by jasonblais** [comment]
@VishalSwarnkar Indeed it is, thanks for your interest! If any questions, let us know

**Comment by VishalSwarnkar** [comment]
@jasonblais I have raised PR but one of the require thing is failing "
cla/mattermost — VishalSwarnkar needs to sign the CLA" not sure what need to be done

**Comment by M-ZubairAhmed** [comment]
@VishalSwarnkar please sign this agreement https://mattermost.org/mattermost-contributor-agreement/

**Comment by srkgupta** [comment]
Testcase added and merged. Closing this PR.
