### ISSUE TITLE
[Help Wanted] [MM-14633] UI Automation: Write an automated test using `cypress` for "Leave all teams"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10471]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14633)

*Test Key: TS14633*

*Steps:*
1. Click main menu > Leave Team
2. Click Yes
3. Repeat until no more teams, observe team selection page
4. Click `Logout` in top left

*Expected:*
- After 3) User sees list of teams available to join (and/or Create a Team)
- After 4) User is logged out

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by CooperAtive** [comment]
I'll take this one

**Comment by hanzei** [comment]
Thanks @CooperAtive!
