### ISSUE TITLE
[Help Wanted] [MM-14634] UI Automation: Write an automated test using `cypress` for "Email address already exists"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10472]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14634)

*Test Key: On14634*

*Steps:*
1. Create a new user with an email log in then log out of that server
2. Create another new user by entering the same email address you used in 1)
3. Enter any username and any password and click to create the account

*Expected:*
- Error message displays below the Create Account button that says "An account with that email already exists"

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by prapti** [comment]
I'll take this one

**Comment by saturninoabril** [comment]
Sure, thanks @prapti!

**Comment by saturninoabril** [comment]
Thank you @prapti for your contribution!
