### ISSUE TITLE
[Help Wanted] [MM-14635] UI Automation: Write an automated test using `cypress` for "Channel name already exists"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10473]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14635)

*Test Key: Mult14635*

*Steps:*
1. Create a channel or note the name of an existing channel 
2. Create a new public or private channel on the same team and give it the same name
3. Save

*Expected:*
- User gets a message saying "A channel with that name already exists on the same team"

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by prapti** [comment]
I'll take this one?

**Comment by saturninoabril** [comment]
Great, thanks @prapti!

**Comment by saturninoabril** [comment]
PR merged.  Closing now.

Thanks @prapti!

**Comment by prapti** [comment]
Thank you @saturninoabril and @sudheerDev !
