### ISSUE TITLE
Disable telemetry by default

### ISSUE THREAD

**Issue by duijf** [mattermost/mattermost-server#10488]
#### Summary

Telemetry and user tracking is enabled by default.

#### Steps to reproduce

1. Install Mattermost

#### Expected behavior

Mattermost does not send tracking information to third party providers by default. Crash reporting is opt-in.

#### Observed behavior (that appears unintentional) 

Mattermost sends tracking information to third parties by default.

#### Possible fixes

Please changing the default of this setting to `false`. This was a really big surprise for us to have enabled. We disabled this immediately and we wouldn't have enabled this in the first place.

If you are worried that you won't receive enough crash reporting / data from new installs, you can ask admins if they want to enable this during the setup process.

**Comment by amyblais** [comment]
Hi @duijf,

This documentation outlines the reasons it's enabled and what data is collected: https://docs.mattermost.com/administration/telemetry.html.

Let us know if you have any further questions.

**Comment by amyblais** [comment]
Hi @duijf,

This was forwarded to our product managers and they will take your feedback into consideration as we will work on improving administrator on-boarding experience and our privacy policy.

I'll close this issue for now as we haven't received further feedback, but please re-open this issue if you have any further questions.

Thank you for the feedback,
