### ISSUE TITLE
Write an automated test using `cypress` for "Search "in:[username]" returns results in GMs"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10482]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14673)

*Test Key: S14673*
1. Open a GM with any group of users (can click "More... on sidebar and select 2 or more user if there are no GMs on sidebar)
2. Post specif text in the GM
3. Click in the "Search" input box
4. Type "in:"
5. Locate the usernames for that Group Message channel for the GM opened in step 1 and hit "enter"
6. Type a search term from step 2.
7. Hit "enter"

Expected:
Results for the search term you entered in step 6. are returned

**Comment by composednitin** [comment]
I would like to take this one

**Comment by hanzei** [comment]
Hey @composednitin,

Thanks for taking a shot. Let us know if you have questions.

**Comment by a-arias** [comment]
I'm going to work on this one 💃

**Comment by saturninoabril** [comment]
Sure and thanks @a-arias!

**Comment by saturninoabril** [comment]
@a-arias Thank you for your contribution!
