### ISSUE TITLE
[MM-14672] UI Automation: Write an automated test using `cypress` for "Search "in:[username]" returns results in DMs"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10481]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14672)

*Test Key: S14672*
1. Open a DM with any user (can click "More... on sidebar and select a user if there are none)
2. Post specif text in the DM
3. Click in the ""Search"" input box
4. Type "in:"
5. Locate the username for the DM opened in step 1 and hit ""enter"" (RN \- tap on username)
6. Type a search term from step 2.
7. Hit "enter"

*Expected*:
Results for the search term you entered in step 6. are returned

**Comment by composednitin** [comment]
I would like to take this one

**Comment by saturninoabril** [comment]
@composednitin Sure, thanks!

**Comment by saturninoabril** [comment]
Thank you @composednitin!
PR is merged.  Closing this issue.
