### ISSUE TITLE
5.8.1 has "Localization setting initialized" problem. 

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-server#10499]
#### Summary
Localization setting data(3 languages) initialized when I restart mattermost-server. 

#### Steps to reproduce
It was very simple. Change your localization setting (ex: English to Korean) and restart mattermost server. It will be change to English / English  / Select... 

#### Expected behavior
I have to change these setting at every-time.

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/20394843/54972402-bd578e80-4fce-11e9-9566-b58856c01166.png)

#### Possible fixes
I think that 5.8.1 has some problem when it save config.json file. I could not reproduce it when I sued 5.7.x.

Best regards,
KIM

**Comment by amyblais** [comment]
Hi @Gloriashield,

This issue was fixed in v5.9 release. Would you be open to upgrading your server?

**Comment by Gloriashield** [comment]
Dear @amyblais ,

Thanks for your advice. You are right. I upgraded my server to 5.9.0 and can fix it. 

Regards, KIM
