### ISSUE TITLE
Embed Mattermost in iframe

### ISSUE THREAD

**Issue by limenleap** [mattermost/mattermost-server#10491]
Documentation here https://docs.mattermost.com/integrations/embedding.html does not seem to work

Kindly point to the correct documentation on how to embed the community version of Mattermost. I have installed 5.8

Thanks

**Comment by amyblais** [comment]
Hi @limenleap, can you help with more details on what is not working when you attempt to use to the documentation?

**Comment by limenleap** [comment]
The iframe embedding is not possible because the file indicated there /mattermost/mattermost/web/templates/head.html is nowhere in the installation I have. I am using Mattermost 5.8

Also I don't use Ngnix as the reverse proxy. Instead I am using Caddy

**Comment by amyblais** [comment]
Hi @limenleap,

I asked our community / team about this and it appears that this is old documentation and that this would actually be a feature request (While it was possible to embed Mattermost via iframe some time ago, that's apparently no longer the case. See, e.g.: this forum entry https://forum.mattermost.org/t/how-can-we-load-mattermost-in-iframe/165/8).

**Comment by amyblais** [comment]
Hi @limenleap,

It would be awesome if you're able to share this idea on our feature request forum here: https://mattermost.uservoice.com/forums/306457-general.

I'll close this Issue for now as this is a feature request,
