### ISSUE TITLE
[MM-14651] Remove max length from LinkMetadata Value

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10503]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14651)

As reported [here](https://community-daily.mattermost.com/core/pl/sjic9i7sa7yffkyys8epy31u3h), some links can generate OpenGraph previews that are too long to store in the database. These can be cached in memory and will be sent back to clients, but they will be re-requested periodically as people load the post.

To fix this, we should remove the max length from the Value column of the LinkMetadata table (see [here](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/link_metadata_store.go#L25)) and add some migration logic to [upgrade.go](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/upgrade.go) to change the type of the column from `varchar(4096)` to `text` on Postgres (MySQL already uses the correct type).

**Comment by joshuabezaleel** [comment]
Hi everyone, if it's okay I want to ask several things.
1. At the issue description, the name of the column written is "Value" while at the [link_metadata_store.go](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/link_metadata_store.go#L25), the column with the length of 4096 is called "data". Are these referring to the same column? 
2. If I want to add the code for changing the column type, does this mean that I have to enable the 5.11.0 version and insert the altering code there? Or I used the current (5.10.0)? 

Thank you very much. Hoping everyone has a great day 🙂

**Comment by Willyfrog** [comment]
I'd like to take a stab at this. I do have a few questions, though as I'm not sure that would be the ideal approach.
Wouldn't it prevent further errors to limit the amount of info we are gathering from OG, and even the description have a max num. of characters? solution would be a little bit more complex, but we wouldn't be storing so much useless data into the database, so I'd guess this would prevent further complications in the future.
