### ISSUE TITLE
[Help Wanted] [MM-14681] In integrations backstage, no feedback to user when search returns no results

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10505]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14681)

Repro:

1. Go to System Console > Custom Integrations, and enable all integration methods.
2. Switch back to a Mattermost team
3. Go to Main Menu > Integrations > Incoming Webhooks.
4. Create an incoming webhook, via "Add Incoming Webhook"
5. Once created, in Main Menu > Integrations > Incoming Webhooks, use a search term that returns no results, call it [search_term].

Observed: Empty box with no feedback
![image](https://user-images.githubusercontent.com/13119842/55043854-65407c80-500e-11e9-8784-f9e8d29e4588.png)

Expected: Box with text "No incoming webhooks match **[search_term]**", similar to below
![image](https://user-images.githubusercontent.com/13119842/55043862-6d002100-500e-11e9-8b24-a7e9da34178d.png)

NOTE: This should apply to all integration methods. Texts are provided below:
 - "No incoming webhooks match **[search_term]**"
 - "No outgoing webhooks match **[search_term]**"
 - "No slash commands match **[search_term]**"
 - "No OAuth 2.0 applications match **[search_term]**"
 - "No bot accounts match **[search_term]**" [bot accounts are accessible in `../integrations/bots`)

**Comment by reflog** [comment]
I'll take this one

**Comment by reflog** [comment]
I've implemented the bulk of it, except for:
> "No bot accounts match [search_term]" [bot accounts are accessible in ../integrations/bots)
I'm not sure where the bot integration sits

**Comment by CooperAtive** [comment]
Darn I just finished the same task, with the exception of bot accounts. Came here to open PR. Guess I should have mentioned I was working on it!
