### ISSUE TITLE
[Help Wanted] [MM-14730] UI Automation: Write an automated test using Cypress for "Channel Header : Markdown quote"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10501]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14730)

*Test Key: CS14730 - Channel Header : Markdown quote*

*Steps:*
1. Navigate to any test channel
2. Click channel name > Edit Channel Header
3. Add a header to start with a quote, such as the following, then click "Save":

`>This is a quote in the header`

*Expected:*
- The quote icon should be fully visible, not cut off

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by reflog** [comment]
I'll take this one

**Comment by hanzei** [comment]
Go ahead, thanks @reflog!

**Comment by saturninoabril** [comment]
Thank you @reflog for your contribution!

PR has been merged.  Closing this issue now.
