### ISSUE TITLE
Duplicate links posted

### ISSUE THREAD

**Issue by GeordieR** [mattermost/mattermost-server#10514]
#### Summary
Posting a link in a private channel on the web client duplicated the link two more times so that there were three links in total posted.

#### Steps to reproduce
- Post just a link in a private channel
- The link should now have duplicated twice
- Refreshing the page doesn't fix the issue

#### Expected behavior
The messages shouldn't post more than once.

#### Observed behavior (that appears unintentional) 
Three messages were posted instead of one. 

> Mattermost Version: 5.7.2
> Database Schema Version: 5.7.0
> Database: postgres

**Comment by GeordieR** [comment]
Updated the title and description after discovering that not being able to edit posts after a period of time was indeed a feature and not a bug

**Comment by amyblais** [comment]
Hi @GeordieR,

I wasn't able to reproduce this just now, however I'm on a v5.10 server version as we're getting ready to release that version next month. Would you be able to do a quick test on our [community server here](https://community.mattermost.com) to see if you can see the issue on the latest version?

If you still see the issue on the latest, can you help with more details about your environment including device, OS and version?

**Comment by GeordieR** [comment]
Sorry I didn’t get around to this today, I’ll have a go tomorrow and let you know if I can reproduce it. I think this one might be quite elusive.

**Comment by GeordieR** [comment]
I wasn't able to replicate this on the community server. I'll close this issue and if I see it happen again I'll re-open it with more details.

Geordie
