### ISSUE TITLE
[Webapp] Links to unread messages received in email don't work on community server

### ISSUE THREAD

**Issue by checkaayush** [mattermost/mattermost-server#10524]
#### Summary
Links to go to unread post on community.mattermost.com received in emails don't seem to work.

#### Steps to reproduce
Wait for an unread message's email to arrive in your inbox. Click on "Go To Post".

#### Expected behavior
Link should take us to the attached post.

#### Observed behavior (that appears unintentional) 
 The link doesn't open. It changes to https://community.mattermost.com/core/pl/<SOME_ID> but doesn't open.

#### Possible fixes
NA

**Comment by amyblais** [comment]
Hi @checkaayush,

I wasn't able to reproduce this just now. Do you know if it was a link to a private or public channel?

**Comment by checkaayush** [comment]
> Hi @checkaayush,
> 
> I wasn't able to reproduce this just now. Do you know if it was a link to a private or public channel?

Private channel.

**Comment by amyblais** [comment]
@checkaayush 

1. Is it a private channel you're able to access?
2. Did you see any error message or just a blank screen?

**Comment by checkaayush** [comment]
> 1. Is it a private channel you're able to access?
Yes. It's a direct message to me.

> 2. Did you see any error message or just a blank screen?
Just a blank screen.

**Comment by amyblais** [comment]
Hi @checkaayush,

I'm able to reproduce this with a direct message channel. I opened a bug ticket here: https://mattermost.atlassian.net/browse/MM-14793.

Thank you for reporting this,

**Comment by amyblais** [comment]
Hi @checkaayush, I'm not able to reproduce this on community server anymore, can you help confirm if you still see this?

**Comment by checkaayush** [comment]
I don't see this issue anymore. Seems to have been fixed. @amyblais
