### ISSUE TITLE
[Webapp] Admin password reset `maxlength=22`

### ISSUE THREAD

**Issue by tobast** [mattermost/mattermost-server#10523]
#### Summary
When resetting a user password through the admin console, the new password field has a `maxlength=22` attribute, which may break password resets silently.

#### Steps to reproduce
Go to the admin console, on the Users page. Select some user with password authentication. Open the dialog to reset their password. Enter any password longer that 22 chars, validate.

#### Expected behavior
The user may log in with their new, longer than 22 chars, password, since the actual password length limit is 64 chars.

#### Observed behavior (that appears unintentional) 
Since the `<input type="password">` field has a `maxlength=22` attribute, all the characters entered beyond the 22nd are plainly ignored. This is not visible, since the password characters are bullets, and 22 characters fill up the field length. This is furthermore not visible when copy/pasting a randomly generated password — a common admin task.

The password is thus silently truncated to its first 22 characters, and the user may not log in with their new password (unless they understand the issue and truncate it to 22 characters).

It is worth noting that altering manually (through the browser console) the `maxlength` to `64` results in a correctly reset password.

#### Possible fixes

* Change the `maxlength` to 64 (probably not the best idea)
* Remove alltogether `maxlength`, and leave the check to the password validation.

The second option is, IMO, far better, since a user entering a password of 70 characters will be warned that their password was not set, instead of truncating it silently.

**Comment by amyblais** [comment]
Hi @tobast,

What Mattermost server version are you currently on?

**Comment by tobast** [comment]
@amyblais The Mattermost server is 5.9.0, but our webapp is still based on 5.7.0 (we have a few commits on top of them). It might have been fixed in latest versions, I did not think of checking that. Sorry if that's the case!

**Comment by amyblais** [comment]
@tobast No worries, I wasn't able to reproduce on the latest version, so if you're able to test this on the latest then we can see if it might be fixed.

**Comment by tobast** [comment]
@amyblais After upgrading our webapp to 5.9 (ie. based against the `release-5.9` branch of the repository, with none of our local commits changing anything to the admin interface), I can confirm that the issue is still present for me.

**Comment by amyblais** [comment]
Hi @tobast,

Perhaps I tested it incorrectly, I opened a ticket for our team to take a look: https://mattermost.atlassian.net/browse/MM-14973.

**Comment by DSchalla** [comment]
Hi @tobast,
I've opened a pull request that removes the length limit from the password reset dialog, it should now only be enforced by the server-side length validation (max length = 72 currently)

**Comment by amyblais** [comment]
Closing this as the fix will be available in upcoming v5.12 release,
