### ISSUE TITLE
[Help Wanted] [MM-14784] UI Automation: Write an automated test using `cypress` for "An ellipsis indicates the channel header is too long - DM"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10520]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14784)

Test Key: *M14784 - An ellipsis indicates the channel header is too long - DM*
1. Login is a test user
2. Open Account Setting and enable Compact View on the Display tab
3. Open a DM with any other user (can start new DM using "More..." if none are available
4. Click the channel name in the DM header and select "Edit Channel Header"
5. Enter the following:
\_>quote
newheader newheader newheader newheader newheader newheader newheader newheader newheader newheader\_
(must include the >quote \- does not reproduce without a quote in the header)
6. Press or click "Enter" to Save

Expected:

* After 6) you should see the quotation marks displaying in the channel header, and ellipses (...) indicating the header is too long to fit across the top of the screen.

* Clicking on the channel header should still display it in it's entirety.

**Comment by reflog** [comment]
i'll take this one

**Comment by saturninoabril** [comment]
Thank you @reflog for your contribution.

PR has been merged. Closing now.
