### ISSUE TITLE
Mention for user that starts with "all" does not style/highlight their entire username.

### ISSUE THREAD

**Issue by kchutskoff** [mattermost/mattermost-server#10530]
#### Summary
Writing `@user` in a post for a user who's name starts with "all" only highlights "all" and not the remainder of their name.

#### Steps to reproduce
1) Have or create a user in the system that starts with "all" (example, "allan")
2) In a channel with that user, write `@allan` and send the post.

#### Expected behavior
The entire username `@allan` should be highlighted

#### Observed behavior (that appears unintentional) 
The highlight style only highlights `@all` and does not highlight the rest of the user's name (in this case, `@allan`)
![Mattermost_2019-03-28_11-59-24](https://user-images.githubusercontent.com/1940865/55185190-0c2d3180-5151-11e9-9d38-505c118b3388.png)

#### Possible fixes
This appears to be a regression from https://mattermost.atlassian.net/browse/MM-13847

### Versions
Mattermost Enterprise Edition
Mattermost Version: 5.9.0
Database Schema Version: 5.9.0
Database: mysql
Client? Version: 4.1.2 (Windows 10 native, from Help topbar dropdown)

**Comment by amyblais** [comment]
Thank you, I was able to reproduce it and opened a bug ticket here: https://mattermost.atlassian.net/browse/MM-14801

**Comment by amyblais** [comment]
I'll close this issue for now as this has been fixed for the upcoming v5.10 release,
