### ISSUE TITLE
Write an automated test using `cypress` for "Team Admin can use Next button to page through list in Manage Members"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10544]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14868)

*Test Key: TS14868 - "Team Admin can use Next button to page through list in Manage Members"*

*Steps:*
1. Create a new team, then post the command `/test users 60` so that you are team admin on a team with more than 50 users
2. Click hamburger main menu and select Manage Members to open Manage Members dialog
3. Click the "Next" button to view the next page of users
4. Click "Next" a few more times to page through the list
5. Click "Previous" at least once to page backward in list

*Expected:*
- Member count below the search bar reads "XX - YY members of YY total". e.g. "51-75 members of 75 total"

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by patterns** [comment]
I'm interested in making this E2E test. I don't know Cypress, but I have written selenium / spec flow tests on some enhancements in the past.

**Comment by hanzei** [comment]
Hey @patterns,

Thanks for you interest in this project and E2E tests. You can find an overview about E2E test at https://developers.mattermost.com/contribute/webapp/end-to-end-tests/. Feel free to also join [the UI Test Automation channel](https://community.mattermost.com/core/channels/ui-test-automation) on the Mattermost Community server.

**Comment by hanzei** [comment]
Hey @patterns,

After reading the documentation: Do you have any questions about the E2E test framework?

**Comment by shrmpy** [comment]
@hanzei I've had couple questions, but asked them in the UI Automation channel in community.mattermost.com. The issue I'm working through right now surfaced last night after I performed a rebase. I can't get any Cypress tests to run further than cy.apiLogin(), after the rebase.

**Comment by hanzei** [comment]
@shrmpy Would you mind sharing the output of your console?

**Comment by patterns** [comment]
@hanzei Sorry, I saw that there was a resolution from pr-mattermost-webapp-2985 (https://mattermost/mattermost-webapp/pull/2985). Did a new rebase, ran the test to check again, and things are ok. just made my MM14868 pull request (https://github.com/mattermost/mattermost-webapp/pull/2990).

**Comment by hanzei** [comment]
Awesome @patterns :+1: I've requested reviews for your PR.
