### ISSUE TITLE
[Help Wanted] [MM-14890] Logs endpoint always returns an empty line

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10558]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14890)

Repro:
1. Fire a request for [the logs endpoint](https://api.mattermost.com/#tag/system%2Fpaths%2F~1logs%2Fget) following the documentation.

Observed: The last line of the response is always `"\n"`. If the `logs_per_page` query parameter is set to, for example 5, the response will contain 4 lines and the `“\n”` line.
Expected: The response should contain 5 log lines, or 10000 if not `logs_per_page` query parameter is set.

**Comment by reflog** [comment]
I'll take this one
