### ISSUE TITLE
Add Ability To Install Plugin For Specific Team Or Channel

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#10556]
#### Summary
We have a mattermost plugin for internal use in our organization. Several times we have wanted to make some changes to it but wanted to do limited testing before rolling out the changes to the masses. Currently, Mattermost doesn't provide any way to do a team/channel limited plugin deployment.

Any thoughts of if it would be a useful feature?

**Comment by hanzei** [comment]
Could you elaborate a bit why do you think this is needed? If you want to test a plugin, why not use a test server/local dev environment.

**Comment by amyblais** [comment]
I'll close this issue for now as there hasn't been updates on this for a while,
