### ISSUE TITLE
Improve help text and error message for choosing username on the signup page

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10552]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14583)

*Help text:* "You can use lowercase letters, numbers, periods, dashes, and underscores."

https://projects.invisionapp.com/share/B7R4BUHYZCS#/screens/353427679_Recommendation_-_Helper_Text_Improvements

*Error message for username that does not meet requirements:* "Usernames have to begin with a lowercase letter and be 3-22 characters long. You can use lowercase letters, numbers, periods, dashes, and underscores."

https://projects.invisionapp.com/share/B7R4BUHYZCS#/screens/353633806

**Comment by mdizzy** [comment]
I found what appears to be the line I need to change here
https://github.com/mattermost/mattermost-webapp/blob/50c7ae2d31742f207bd7beadded725fc59e84edb/components/signup/signup_email/signup_email.jsx#L273

But that's just for the web app, do we need to change on the mobile apps as well? Is there a centralized string resource dictionary of some sorts that the project uses? How are we handling globalization?

**Comment by mdizzy** [comment]
Ahhh...was looking in the wrong place I'm in the right repository now.  onward and upward.

**Comment by jasonblais** [comment]
Glad you found it :) Are you interested taking this help wanted issue?

**Comment by lisakycho** [comment]
I can take a shot at this! 
Are we just changing the visual text for this?

**Comment by jasonblais** [comment]
@lisakycho Thanks! And that's correct, there are two changes:

1. Updated help text for username on the account creation screen
![image](https://user-images.githubusercontent.com/13119842/58218901-b9966e80-7cd6-11e9-890a-c5c5da188203.png)

2. Updated error message text for username field
![image](https://user-images.githubusercontent.com/13119842/58218920-cdda6b80-7cd6-11e9-8fea-e8ae6c2f6ada.png)

**Comment by lisakycho** [comment]
@hanzei, is there anything else I can do to close this?

**Comment by hanzei** [comment]
Hey @lisakycho,

I reached out to Eric asking him to review your PR soon. You should get a review on your PR this week. Sorry for the delay.
