### ISSUE TITLE
[5.10.0] subpath url not working

### ISSUE THREAD

**Issue by duynb** [mattermost/mattermost-server#10563]
Hi,

In 5.8.0 it was working when I config like this:

`SiteURL": "http://localhost:8065/room`

And the site auto redirect to `http://localhost:8065/room/teamName`

Now in 5.10.0, it tell me the error `team does not exist`
(or sometime it gets the redirect loop)

Is there any update on this?

Thanks.

**Comment by amyblais** [comment]
Hi @duynb, did you see this on RC-2?

**Comment by amyblais** [comment]
Hi @duynb, Our QAs were not able to reproduce this on RC-2. Would you be open to sharing any log errors?

**Comment by duynb** [comment]
Hi @amyblais, 

This is current status:
`./bin/platform version` and the version shown `Version: 5.10.0`

json file settting: `"SiteURL": "http://localhost:8065/company"`
Open in old tab: `http://localhost:8065/error?type=team_not_found`
Open incognito: `http://localhost:8065/company/?redirect_to=%2Fcompany%2F`  (loop)

Here is the log:
```
{"level":"info","ts":1554737163.1971455,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'en' from '/var/www/html/mattermost/i18n/en.json'"}
{"level":"info","ts":1554737163.1974487,"caller":"app/server_app_adapters.go:58","msg":"Server is initializing..."}
{"level":"info","ts":1554737163.2004933,"caller":"sqlstore/supplier.go:219","msg":"Pinging SQL master database"}
{"level":"info","ts":1554737163.2742908,"caller":"filesstore/localstore.go:33","msg":"Able to write files to local storage."}
{"level":"info","ts":1554737163.278554,"caller":"mlog/log.go:164","msg":"Starting up plugins"}
{"level":"info","ts":1554737166.3270802,"caller":"app/server.go:191","msg":"Current version is 5.10.0 (dev/Thứ sáu, 05 Tháng tư năm 2019 09:28:01 UTC/7c9837d9b165792993163131522ee65c3f42d9ec/none)"}
{"level":"info","ts":1554737166.3271396,"caller":"app/server.go:192","msg":"Enterprise Enabled: false"}
{"level":"info","ts":1554737166.32721,"caller":"app/server.go:194","msg":"Current working directory is /var/www/html/mattermost"}
{"level":"info","ts":1554737166.3272471,"caller":"app/server.go:195","msg":"Loaded config","source":"file:///var/www/html/mattermost/config/config.json"}
{"level":"info","ts":1554737166.3323014,"caller":"sqlstore/post_store.go:1293","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}
{"level":"info","ts":1554737166.4046953,"caller":"jobs/workers.go:68","msg":"Starting workers"}
{"level":"info","ts":1554737166.404802,"caller":"app/server.go:391","msg":"Starting Server..."}
{"level":"info","ts":1554737166.4049914,"caller":"app/server.go:457","msg":"Server is listening on [::]:8065"}
{"level":"info","ts":1554737166.409758,"caller":"jobs/schedulers.go:72","msg":"Starting schedulers."}
{"level":"info","ts":1554737166.4148436,"caller":"app/web_hub.go:75","msg":"Starting 8 websocket hubs"}
{"level":"info","ts":1554737238.292963,"caller":"scheduler/worker.go:78","msg":"Worker: Job is complete","worker":"Plugins","job_id":"wam1fqri67bqx8otgsy6pcf1bw"}
{"level":"info","ts":1554737298.2478862,"caller":"scheduler/worker.go:78","msg":"Worker: Job is complete","worker":"Plugins","job_id":"xrpp7qpw3pb33yffbxny9h7gxc"}
{"level":"info","ts":1554737346.6983972,"caller":"app/server.go:302","msg":"Stopping Server..."}
{"level":"info","ts":1554737346.699589,"caller":"app/web_hub.go:120","msg":"stopping websocket hub connections"}
{"level":"info","ts":1554737346.6999264,"caller":"app/plugin.go:193","msg":"Shutting down plugins"}
{"level":"info","ts":1554737346.7147458,"caller":"sqlstore/supplier.go:912","msg":"Closing SqlStore"}
{"level":"info","ts":1554737346.7169259,"caller":"jobs/workers.go:184","msg":"Stopped workers"}
{"level":"info","ts":1554737346.716999,"caller":"jobs/schedulers.go:140","msg":"Stopping schedulers."}
{"level":"info","ts":1554737346.7198796,"caller":"jobs/schedulers.go:75","msg":"Schedulers stopped."}
{"level":"info","ts":1554737346.7199135,"caller":"app/server.go:335","msg":"Server stopped"}
```

I was packaged this from the source code  using `make package` last week.
I'll try to re-package it and check again.

Thank you.  :)

**Comment by duynb** [comment]
I tried again, and it still happened. Here is my processes:

 - Clone new branch `release-5.10`  mattermost-server
 - Clone new branch `release-5.10`  mattermost-webapp
 - `cd mattermost-server` => `make run`
 - The web run ok and created json config file `config/config.json`
 - Stop the server and modified the config file to `http://localhost:8065/company`
 - Start again the server.

=> the redirect loop `http://localhost:8065/company/?redirect_to=%2Fcompany%2F`.

Not sure it's just on my environment or not. I'll try on another environment, or will wait to other new versions.

Thank you.

**Comment by amyblais** [comment]
Hi @duynb, v5.10 is now officially released. Would you be able to upgrade to v5.10 and see if you still hit this issue?

**Comment by duynb** [comment]
@amyblais ,

It's ok now.

More info:
 - When using `make package` from the server code, seem it's still the redirect loop.
 - When running `make build` in the webapp and copy all files in dist to the client directory in the server => it works fine.

Thank you very much for your support.
