### ISSUE TITLE
[5.10.0-rc2] LogSettings.FileFormat is coming back but may be unused

### ISSUE THREAD

**Issue by maruTA-bis5** [mattermost/mattermost-server#10562]
#### Summary
LogSettings.FileFormat was [removed in 4.10](https://github.com/mattermost/docs/blob/8372d5479b2c792a39c072578a5727c768a96920/source/administration/changelog.md#changes-to-team-edition-and-enterprise-edition-6).
This property is coming back in 5.10.0-rc2.
but i couldn't find any code using this configuration.

#### Steps to reproduce
Get configuration via api `GET /api/v4/config`.

#### Expected behavior
`FileFormat` property not contains in `LogSettings` section.

#### Observed behavior (that appears unintentional) 
`FileFormat` found in `LogSettings` section (value is empty).
```
"LogSettings":{"EnableConsole":true,"ConsoleLevel":"DEBUG","ConsoleJson":true,"EnableFile":true,"FileLevel":"INFO","FileJson":true,"FileFormat":"","FileLocation":"","EnableWebhookDebugging":true,"EnableDiagnostics":true}
```

#### Possible fixes
If this is intentional, please explain this change in changelog.

**Comment by amyblais** [comment]
Hi @maruTA-bis5,

I've opened a ticket here to ask our team about this today: https://mattermost.atlassian.net/browse/MM-14970.

**Comment by amyblais** [comment]
Hi @maruTA-bis5, letting you know that ``LogSettings.FileFormat`` has been removed from v5.10 now. I'll close this issue for now,
