### ISSUE TITLE
Write an automated test using Cypress for "Emojis show as jumbo in reply thread"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10574]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15011)

*Test Key: M15011 - Emojis show as jumbo in reply thread*
*Test Group: Messaging*

*Steps:*
1. Click reply on any post
2. In the input box of the reply thread make a post that consists of only a few emojis and no text (use the emoji picker or keyboard)

*Expected:*
- Emojis show as jumbo

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by srkgupta** [comment]
I can pick this up.

**Comment by srkgupta** [comment]
I will pick this one

**Comment by hanzei** [comment]
Thanks @srkgupta :+1:

**Comment by saturninoabril** [comment]
Thank you @srkgupta!  PR recently merged 🎉

**Comment by srkgupta** [comment]
Thanks @saturninoabril
