### ISSUE TITLE
Write an automated test using Cypress for "Emojis are not jumbo when accompanied by text"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10576]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15012)

*Test Key: M15012 - Emojis are not jumbo when accompanied by text*
*Test Group: Messaging*

*Steps:*
1. In either the main or reply thread make a post that has emojis and some text as well

*Expected:*
- Emojis are shown in the normal size 

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by prapti** [comment]
I'll take this one?

**Comment by prapti** [comment]
I'll take this one

**Comment by saturninoabril** [comment]
Great, thanks!

**Comment by hanzei** [comment]
Hey @prapti,

How is your work on this going? Can we help with anything?

**Comment by prapti** [comment]
Hi @hanzei 
I am going to submit a PR for this ticket next week. Sorry for being out of the loop.

**Comment by hanzei** [comment]
Hey @prapti,

I just want to gently remind you about this :wink:

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by a-arias** [comment]
Hey guys I just created a PR for this issue, please take a look an let me know what you think 💃

**Comment by saturninoabril** [comment]
Great, thanks @a-arias!

**Comment by saturninoabril** [comment]
Thanks @a-arias! PR has been merged.  Closing this issue now.
