### ISSUE TITLE
Write an automated test using Cypress for "Main Menu stays open"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10573]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15009)

*Test Key: AS15009 - Main Menu stays open*
*Test Group: Account Settings*

*Steps:*
1. Log into the same server as two different users A and user B
2. Navigate to the same team and channel with both users
3. As user A, click on the hamburger to open the main menu
4. As user B, post a message in the channel both users are viewing

*Expected:*
- Main Menu remains open for User A

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by composednitin** [comment]
Hi,
I would like to take this one

**Comment by hanzei** [comment]
Thanks @composednitin :+1:

**Comment by hanzei** [comment]
Hey @composednitin,

How is your work going? Can I help with anything?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by larkox** [comment]
May I take this one?
