### ISSUE TITLE
[MM-15008] UI Automation: Write an automated test using Cypress for "Sign In Forgot password - Email address has account on server"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10572]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15008)

*Test Key: "SA15008 - Sign In Forgot password - Email address has account on server"*
*Test Group: Sign-in/Authentication*

*Steps:*
On a server with site URL and email settings configured:
1. Go to the login page where you enter username & password
2. Click "I forgot my password"
3. Enter an email that has an account on the server and that you can access
4. Go to your email account, find the email sent by Mattermost and click the "Reset password" button
5. Enter a new password
6. Sign in with the account, using the new password

*Expected:*
- Log in screen should display "password updated successfully"
- Sign-in is successful

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by cometkim** [comment]
> Go to your email account, find the email sent by Mattermost and click the "Reset password" button

Is there any possible route for accessing email or generated url from cypress?

**Comment by saturninoabril** [comment]
Yes, we're using inbucket as email testing application. That should be accessible by querying name of test user, e.g. `http://localhost:9000/mailbox?name=user-1`
<img width="1161" alt="Screen Shot 2019-04-21 at 9 19 22 AM" src="https://user-images.githubusercontent.com/5334504/56464209-f0970d00-6416-11e9-9f7f-19c85368892c.png">

**Comment by cometkim** [comment]
oh, interesting! Thanks for the info @saturninoabril

**Comment by saturninoabril** [comment]
I'm taking this to initially introduce test in validating email.
