### ISSUE TITLE
[MM-15010] UI Automation: Write an automated test using Cypress for "Pinning or un-pinning older post does not cause it to display at bottom of channel"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10575]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15010)

*Test Key: M15010 - Pinning or un-pinning older post does not cause it to display at bottom of channel*
*Test Group: Messaging*

*Steps:*
1. Ensure there are a couple pinned posts in the channel already
2. Scroll up in the channel to find an older post
3. Click [...] > Pin to channel
4. Scroll down and verify that message you just pinned does not display at bottom in center channel (as newest in channel)
5. Click pin icon to view pinned posts in right-hand-side, verify sorted by newest at top
6. Scroll back up to the post you pinned in step 3 (or up to any older pinned post)
7. Click [...] > Un-pin from channel

*Expected:*
- When pinned, older post should retain its position in the center channel and should not move down to display as newest message (at the bottom)
- Pinned posts right-hand-side should display with newest at top
- When un-pinned in center, post disappears from pinned posts list in right-hand-side

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by prapti** [comment]
I'll take this one

**Comment by saturninoabril** [comment]
Sure, thanks!

**Comment by prapti** [comment]
Question on test step 5: does "sorted by newest at top" mean the the last pinned post (newest pinned) at the top of the pinned post list or the newest posted on the CENTER at top? I'm assume the latter?

**Comment by saturninoabril** [comment]
Yes, it's the latter - "the newest posted on the CENTER at top"

**Comment by saturninoabril** [comment]
Thank you @prapti for your contribution 🎉
