### ISSUE TITLE
[MM-15052] UI Automation: Write an automated test using `cypress` for "All channel types highlight properly on sidebar"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10586]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15052)

Test Key: write an automated test using cypress for the following test case:Note: This test assumes you already have an account on the server and have logged in.

1. Position the mouse pointer over a public or private channel in the drawer
2. Position the mouse pointer over a DM or GM in the drawer

Expected:
on 1. the channel becomes highlighted
on 2. the channel becomes highlighted and an "x" is visible near the right edge to remove the channel from the drawer. 

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests

**Comment by CooperAtive** [comment]
I'll take this one

**Comment by saturninoabril** [comment]
Sure, thanks @CooperAtive 🎉

**Comment by CooperAtive** [comment]
Looks like doing a test on this using the :hover pseudo class to add styling or show/hide and add styling will not work.

You can force elements to show, and force clicks on hidden elements, but you can't actually force the hover state. Cypress has had an open [issue](https://github.com/cypress-io/cypress/issues/10) on this for many years.

**Comment by saturninoabril** [comment]
Yes, you're right.  Can you think of an alternative approach for this test case?  Maybe checking if the sidebar channel is highlighted or not is not feasible.  I'm thinking if we could just test if it has "remove button" or not.
- for private/public channels - should not have remove button
- for DM.GM channels - should have remove button

Any thoughts?

**Comment by CooperAtive** [comment]
Sorry for the delay, had some family visit and was taking them around.

I believe that test can be implemented, but it would not actually test the hover behavior. I'll add that test and open the PR.

**Comment by saturninoabril** [comment]
No worries and thanks
