### ISSUE TITLE
[MM-14917] RN Android: Push notification settings are only saved when closing settings page

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10582]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14917)

Any changes made to the settings on Settings > Notifications > Mobile are not saved until you hit the back button to return to the Settings > Notifications screen.

Repro steps:
1) Log into Mattermost
2) Go to Settings > Notifications > Mobile
3) Change the Send Notifications setting and tap Save on the modal that appears
4) Lock your phone
5) As another user on another device, mention that user
6) Unlock your phone and tap the back button to return to Settings > Notifications
7) Lock your phone and have the other user mention you again

Observed: The change in notification settings doesn't apply to the message sent in step 5, but it does apply to the one sent in step 7
Expected: The change in notification settings applies as soon as you tap Save and close the modal

**Comment by renatopeterman** [comment]
Hey guys, maybe I can help on this.
Looks like the method should be triggered somewhere (maybe on `setState` callback?) on both methods below on `NotificationSettingsMobileAndroid` class:

![Screenshot 2019-04-19 20 32 23](https://user-images.githubusercontent.com/2411367/56448061-a7de3780-62e2-11e9-8df8-4fbaa8fcbd6a.png)

Is it correct?

**Comment by jasonblais** [comment]
@renatopeterman Thank you for the PR! Sorry for missing your question earlier. I'll queue the pull request for review. 👍

**Comment by renatopeterman** [comment]
@jasonblais Awesome! No problem, just let me know when you have some feedback.
