### ISSUE TITLE
Cannot connect through authenticated proxy with Mattermost Client 4.2.1 on Windows x64.

### ISSUE THREAD

**Issue by UberPinguin** [mattermost/mattermost-server#10584]
#### Summary
Cannot connect through authenticated proxy: `ERR_TUNNEL_CONNECTION_FAILED(-111)`

#### Steps to reproduce
Using Mattermost 4.2.1 for Windows x86_64 in an environment with a proxy that requires authentication.
When Mattermost prompts for proxy credentials, enter them and click Login.

#### Expected behavior
The Mattermost client should authenticate with and tunnel its connection through the proxy, connecting the user to the remote Mattermost server.
Proxy credentials should be cached for future connections in the same session.

#### Observed behavior (that appears unintentional) 
An error page is displayed, "Cannot connect to Mattermost", with some basic troubleshooting guidelines and the error code `ERR_TUNNEL_CONNECTION_FAILED(-111)`.
When the page is refreshed, Mattermost prompts for the proxy credentials again.

**Comment by UberPinguin** [comment]
This also fails in 4.2.0, but works in 4.1.2.

**Comment by amyblais** [comment]
Hi @UberPinguin, What Mattermost server version are you on and do you see any log errors?

**Comment by amyblais** [comment]
@yuya-oc / @deanwhillier / @JtheBAB do you happen to know if this is a known issue on the desktop app?

**Comment by deanwhillier** [comment]
I'm afraid I don't yet have any experience with the Desktop App and proxies. We will have to look into it if others with more domain knowledge don't have a ready answer. @yuya-oc, @wget, @svelle, @hmhealey, thoughts?

**Comment by JtheBAB** [comment]
The biggest change between 4.1 and 3.2 was the electron build. Perhaps a issue with the electron build that 4.2 is using?

**Comment by UberPinguin** [comment]
Hi @amyblais ,
The server is 5.7.0. I don't have access to the server's logs, but I can ask their admin to check while I try connecting.

**Comment by amyblais** [comment]
Hi @UberPinguin, this looks similar to this report https://github.com/mattermost/desktop/issues/965 and the reporter submitted a PR here https://github.com/mattermost/desktop/pull/966. We're working on reviewing the PR and will make a decision if we need to cut a dot release for it.

**Comment by pisymbol** [comment]
I have the exact same issue on OSX (10.14.4) with MM 4.2.1.62. Sometimes if I let it just sit the client eventually reloads and re-establishes the connection. Very strange.

**Comment by wget** [comment]
@pisymbol @UberPinguin I merged the fix for https://github.com/mattermost/desktop/issues/965 today and this fixes the issue I have with my dev instance protected by HTTP basic Auth (https://mattermost.dev.wget.be). User: wget Pass: 12345
