### ISSUE TITLE
Plugin settings link doesn't appear after upload until refreshed

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#10589]
#### Summary
Plugin settings link doesn't appear after upload until refreshed.

#### Steps to reproduce
1. Obtain a Mattermost plugin having at least one settings. I used the [XKCD Mattermost Plugin](https://github.com/TecHunter/mattermost-xkcd-plugin/releases) for demo.
1. Upload the plugin to Mattermost.

#### Expected behavior
1. On plugin upload, three options appear in the plugin section - `Enable`, `Remove` and `Settings`.

#### Observed behavior (that appears unintentional) 
1. On plugin upload, only options appear in the plugin section - `Enable`, `Remove`. The `Settings` section appear only after a page reload.

See attached screencast for demo -
![screencast](https://imgur.com/download/syiFC0G/)

**Comment by amyblais** [comment]
Thank you @harshilsharma, I'm able to reproduce this, but just checking with QAs on if this is a regression.

**Comment by harshilsharma63** [comment]
@amyblais you may definitely confirm this, but from what I've experienced this didn't occur previously.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-15076.

**Comment by jasonblais** [comment]
@harshilsharma huge thanks for your report! Will triage with our team on Tuesday. 

Wondering if you'd be open to helping with a fix for it?

**Comment by hanzei** [comment]
This got fixed with https://github.com/mattermost/mattermost-webapp/pull/2668
