### ISSUE TITLE
[Help Wanted] [MM-15073] Hide bot accounts from System Console > Users

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10596]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15073)

There's no value added to list bots on the page that I see - you can manage permissions, tokens, enable/disable state all in the Bot Accounts page.

One thing that would be missed is managing teams the bot belongs to, but SysAdmin can do that on the command line.

As a result, proposal is to hide bot accounts from System Console > Users page.

**Comment by CooperAtive** [comment]
I'll take this one.

**Comment by jasonblais** [comment]
Thanks @CooperAtive 👍 ;)
