### ISSUE TITLE
[Help Wanted] [MM-14842] Desktop app: Clicking the tooltip button dismisses the tooltip (Windows)

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10603]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14842)

Found while testing MM-14491. The solution works as expected in all browsers and the Mac dekstop app.
On the Windows desktop app, there's an issue where clicking the button a few times will hide the tooltip.
I don’t see a consistency in regards to how many clicks are required for the tooltip to be dismissed, sometimes it will be dismissed after the first click.
  
Reproduces on 4.2.1. and 4.3.

*Steps*:
1. Install and enable the attached plugin on https://postgres.test.mattermost.com
2. Open this post: https://ci-linux-postgres.mattermost.com/lindy-1234/pl/yq9x4didotfafpzcqu4wa6u9xe
3. Hover the hyperlinked word in the post and make sure the tooltip with the button shows up

*Observed*: Clicking the button a few times will hide the tooltip. See gif: 
 !tooltip.gif! 
*Expected*: User can click the button an infinite number of times without it being dismissed.

**Comment by jasonblais** [comment]
@kosgrz will take a look at it :)
