### ISSUE TITLE
Can't send direct message via API

### ISSUE THREAD

**Issue by winmasta** [mattermost/mattermost-server#10605]
#### Summary
Trying to send direct message but didn't succeed

#### Steps to reproduce
API v4
First I have tried to send direct message via POSTS endpoint wit body:
{"channel_id": "o5o44zkpcjgnumq38k1eyzsxrw", "message": "123"} where
o5o44zkpcjgnumq38k1eyzsxrw is system admin user ID
and I've got "You do not have the appropriate permissions" but my user is system admin

Next I've tried to create direct message channel via CHANNELS/DIRECT endpoint with
body:["xnhwgaiffffhzk6388cxnqgcze"], where xnhwgaiffffhzk6388cxnqgcze is regular user
ID but got "Invalid or missing user_ids in request body"

#### Expected behavior
I've expected to post direct message.

#### Observed behavior (that appears unintentional) 
I've got really strange errors.

#### Possible fixes
Have no idea, sorry.

**Comment by amyblais** [comment]
Hi @winmasta,

What Mattermost server version are you on? Can you post the full errors you're seeing?

**Comment by winmasta** [comment]
```winmasta@mattermost:~$ docker exec -it mattermost-docker_app_1 mattermost version```
Version: 5.9.0
Build Number: 5.9.0
Build Date: Fri Mar 15 22:02:44 UTC 2019
Build Hash: 5ef499caae2bb751438b19151a9fcb4b27830bca
Build Enterprise Ready: true
DB Version: 5.9.0

```winmasta@winmasta-laptop ~ $ curl -X POST -i -H 'Authorization: Bearer MY_TOKEN' -d '{"channel_id": "o5o44zkpcjgnumq38k1eyzsxrw", "message": "123"}' https://mattermost.kireva.com/api/v4/posts```
HTTP/1.1 403 Forbidden
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 17 Apr 2019 00:12:45 GMT
Content-Type: application/json
Content-Length: 178
Connection: keep-alive
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 100
X-Ratelimit-Reset: 1
X-Request-Id: iz7rnybzm3gejqheneq3tz41py
X-Version-Id: 5.9.0.5.9.0.7ae723f71688c31d96bf37d4fe579e1e.false

{"id":"api.context.permissions.app_error","message":"You do not have the appropriate permissions","detailed_error":"","request_id":"iz7rnybzm3gejqheneq3tz41py","status_code":403}

```winmasta@winmasta-laptop ~ $ curl -X POST -i -H 'Authorization: Bearer MY_TOKEN' -d '["o5o44zkpcjgnumq38k1eyzsxrw"]' https://mattermost.kireva.com/api/v4/channels/direct```
HTTP/1.1 400 Bad Request
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 17 Apr 2019 00:13:33 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 100
X-Ratelimit-Reset: 1
X-Request-Id: ue4h5fsuobf3zr68jymxnytixa
X-Version-Id: 5.9.0.5.9.0.7ae723f71688c31d96bf37d4fe579e1e.false

{"id":"api.context.invalid_body_param.app_error","message":"Invalid or missing user_ids in request body","detailed_error":"","request_id":"ue4h5fsuobf3zr68jymxnytixa","status_code":400}

**Comment by amyblais** [comment]
@maruTA-bis5 / @hanzei / @avasconcelos114 would one of you know if there is a bug here?

**Comment by maruTA-bis5** [comment]
Hi @winmasta, @amyblais.
The create direct messsage channel request is invalid.

### Request
Request body is array of _two user ids to be in the direct message_.
```
> POST http://localhost:8065/api/v4/channels/direct
> Accept: application/json
> Authorization: Bearer rd5q8aknf3b67dqyww8me5o3jr
> Content-Type: application/json
["979fx8wpapgqtejc8cqt9zunyr","1ha7wwiz4t8nipkk3waydk3mko"]
```
### Response
```
< 201
< Content-Length: 335
< Content-Type: application/json
< Date: Sun, 21 Apr 2019 08:11:47 GMT
< X-Request-Id: fsks177hdjfgunnphs7sf4u5oc
< X-Version-Id: 5.9.0.5.9.0.6fcb851edc18c37b9212332a3811b402.false
{"id":"z7yxn3hso7yoimiq836oohhbde","create_at":1555834307058,"update_at":1555834307058,"delete_at":0,"team_id":"","type":"D","display_name":"","name":"1ha7wwiz4t8nipkk3waydk3mko__979fx8wpapgqtejc8cqt9zunyr","header":"","purpose":"","last_post_at":0,"total_msg_count":0,"extra_update_at":0,"creator_id":"","scheme_id":null,"props":null}
```
Field "id" is the DM channel's channel_id.
You specify this id to request payload of create post.

**Comment by winmasta** [comment]
Now it's clear thanks.
