### ISSUE TITLE
[Help Wanted] [MM-14726] When searching, and there are no disabled bots returned by search, hide the Disabled section break

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10610]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14726)

Repro:

1. Create two bot accounts named "Test" and "Hello"
2. Disable the "Hello" bot
3. Search for "Test" in bot accounts list

Observed: Disabled section break shows even though there are no disabled bot accounts returned in search.

![image](https://user-images.githubusercontent.com/13119842/56132505-212f0080-5f58-11e9-8a69-b6c220c9b825.png)

Expected: Do not show disabled section break if there are no disabled bot accounts returned in search.

**Comment by liusy182** [comment]
By following steps, I am not able to repro as of [this commit]( https://github.com/mattermost/mattermost-webapp/tree/6c53eb7f5cf4486482689adb226ab87a06c7ba65). Disabled section did not show up for me.

**Comment by hanzei** [comment]
@jasonblais Would you please take a look at the above question?

**Comment by jasonblais** [comment]
Great! Thanks @liusy182 for the heads up (and Hanzei for the ping). I've tested and indeed can no longer reproduce. Closing 👍
