### ISSUE TITLE
[MM-15113] UI Automation: Write an automated test using Cypress for "Click another user's emoji reaction to add it"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10612]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15113)

*Test Key: M15113 - Click another user's emoji reaction to add it*
*Test Group: Messaging*

*Steps:*
1. Have another user add an emoji reaction to a post
2. Click on their reaction to add the same reaction from your user
3. Click on the + icon to open the reaction emoji picker and select another reaction to add
4. Click on each of the reactions you added

*Expected:*
- After 2) the number shown on the reaction is incremented by 1 and the background color changes
- After 3) the emoji reaction you selected is added to the post
- After 4) the emoji reactions you added are removed

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by VolatianaYuliana** [comment]
Hi! I'd love to work on this issue :)

**Comment by hanzei** [comment]
Hey @VolatianaYuliana,

Thanks for working on this! Let us know, if you have any questions.

**Comment by saturninoabril** [comment]
Thank you @VolatianaYuliana for your contribution!

**Comment by VolatianaYuliana** [comment]
My pleasure :)
