### ISSUE TITLE
[Help Wanted] [MM-15123] Migrate "WebHook.GetIncomingByChannel" to Sync by default

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10617]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15123)

Mattermost is migrating its Store layer to be sync by default, and only use Async when needed and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `GetIncomingByChannel` in the `WebHook` store.

The expected way to implement it is, go to the `WebHook` store implementation in the `store/sqlstore/` directory, modify the method `GetIncomingByChannel` to return directly an object from the `model` module, and a `*model.AppError` (removing the `store.Do` wrapper). After that, you must modify the interface defined in `store/store.go` to match with the changes. Then, you should execute `make store-mocks` to rebuild the mocks with the new interface. And finally, modify the rest of the code (tests included) to use the new interface of the function properly.

Example: mattermost/mattermost-server#10613

**Comment by s4kh** [comment]
Also trying this one.

**Comment by hanzei** [comment]
Thanks @s4kh :tada:

**Comment by s4kh** [comment]
Do I have to return a pointer of `var webhooks []*model.IncomingWebhook` (&webhooks) or just the array?

**Comment by hanzei** [comment]
I'm not sure I get the questions. The return value should be `[]*model.IncomingWebhook`. Does this help?

Would you please try `go test -v -run='TestWebhookStore' ./store/sqlstore/`?

**Comment by s4kh** [comment]
Ok, got it. Thanks for the quick reply.
