### ISSUE TITLE
[MM-13879] Add Edit profile button to RHS menu and own profile pop-over

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10624]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13879)

In the mobile app:

1. Add "Edit Profile" button above the "Settings" option in the right panel menu
https://projects.invisionapp.com/share/NCQCLAKUJA8#/screens/345054216

2. Tapping on the users own username in posts or their profile image in the top of the right panel menu opens the users own profile pop-over

 !screenshot-1.png|thumbnail!  !screenshot-2.png|thumbnail! 

3. Add an "Edit" button in the header of the users own profile pop-over.
https://projects.invisionapp.com/share/NCQCLAKUJA8#/screens/345054213

**Comment by jkl5616** [comment]
I'd like to work on this!

**Comment by hanzei** [comment]
Thanks @jkl5616 :tada:
