### ISSUE TITLE
In interactive dialogs, render autocomplete lists below the input field by default

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10627]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14489)

Current behaviour: In interactive dialogs, the autocomplete list for "select" input fields always open above the field.

However, if the input field is at the top of the dialog, there may not be enough space to render the autocomplete. See attached for an example

![image](https://user-images.githubusercontent.com/13119842/56231941-a0523080-604d-11e9-91d6-53155a203385.png)

Proposed behaviour: Open the autocomplete below the field by default. In cases where there isn't enough space to render the autocomplete list below the field, render it above it.

Need to ensure this won't break other cases where the autocomplete is used.

**Comment by jasonblais** [comment]
@andreistanciu24 @asaadmahmood created a Help Wanted ticket for us to track this improvement

**Comment by hanzei** [comment]
@jasonblais What is the status of this? Is someone working on this?

**Comment by jasonblais** [comment]
@andrevasconcelos, @asaadmahmood and I have been talking about this in community, most latest was last week

**Comment by hanzei** [comment]
Hey @andrevasconcelos,

Just want to check how your work on this ticket is going. Do you need help?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by Vitao18** [comment]
Hey, Can I take this one?

**Comment by jasonblais** [comment]
@Vitao18 Certainly! If you have any questions as you work on it, don't hesitate to let us know!

**Comment by jasonblais** [comment]
Hey @Vitao18, how are things going? Any questions we can help you with so far?

**Comment by sk409** [comment]
I would like to work on this issue.

**Comment by sk409** [comment]
Autocomplete lists seem to be rendered below by default now.
Is this issue already fixed?
![スクリーンショット 2022-10-03 22 59 23](https://user-images.githubusercontent.com/25968819/193596511-87cd9138-777c-41df-9bbf-d7fb037e084b.png)

**Comment by esethna** [comment]
Most likely already fixed, thanks though!
