### ISSUE TITLE
[Help Wanted] [MM-14723] Add system console setting to enable/disable the creation of bot accounts using the REST API.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10638]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14723)

The setting will need to be added to the system console.

The bot accounts backstage UI should be hidden when creation is disabled.

*Title*: Enable Bot Accounts
*Options*: true/false (default: false)
*Help Text*: When true, bot accounts can be used for integrations in Integrations > Bot Accounts. Bot accounts are similar to user accounts except they cannot be used to log in. See documentation to learn more.

NOTE: “documentation” above links to https://mattermost.com/pl/default-bot-accounts

If you have any questions or design clarifications of the proposed improvement, reach out to @jasonblais on GitHub, or jason.blais on https://community.mattermost.com

**Comment by jasonblais** [comment]
Reopend at https://github.com/mattermost/mattermost-server/issues/10776
