### ISSUE TITLE
Interactive dialog's describe text color is too dark to see.

### ISSUE THREAD

**Issue by ninanung** [mattermost/mattermost-server#10632]
#### Summary
In the few basic themes, interactive dialog's text is barely visible like this.
![](https://postfiles.pstatic.net/MjAxOTA0MTdfMTk1/MDAxNTU1NDkzNzExMjI2.ucBNckUpYgcZTv4rHF5sQbJ5iCjvm-7VF-5NKzbWKhYg.eONCI2oiUlGwF9sv38RuM51Ae0_zLc6kq-ZX7gRYyqwg.PNG.ninanung/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2019-04-17_%EC%98%A4%ED%9B%84_6.07.47.png?type=w773)
![](https://postfiles.pstatic.net/MjAxOTA0MTdfMTcw/MDAxNTU1NDkzNzExMjI4.vh-lXrsrGzt-iUKJjRY06z_fXpPcnPLaNPlivbTVXtog.zLSppLLasq01i3ik3L_jm22ofWyM9RcS5XOH1D30BMMg.PNG.ninanung/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2019-04-17_%EC%98%A4%ED%9B%84_6.25.23.png?type=w773)

#### Steps to reproduce
I tested with basic 4 theme. `Mattermost Dark` and `Windows Dark` theme's dialog text was too dark.

#### Expected behavior
Clear visibility.

#### Observed behavior
Bad visibility.

#### Possible fixes
Text-color style needs to be changed according to theme.

*** Mobile has similar issue.
*** I didn't test the custom theme, but i think at least four basic theme should be changed.

**Comment by amyblais** [comment]
Thank you @ninanung, I opened a ticket for our UX team to look at: https://mattermost.atlassian.net/browse/MM-15174.

**Comment by amyblais** [comment]
I'll close this for now as this has been fixed for the upcoming v5.11 release (which will be released on May 16th). Please re-open this issue if you have any further questions,
