### ISSUE TITLE
 Can't use ephemeral post api.

### ISSUE THREAD

**Issue by yth0625** [mattermost/mattermost-server#10641]
####  Summary
I always return a 403 error when using [this](https://api.mattermost.com/#tag/posts%2Fpaths%2F~1posts~1ephemeral%2Fpost) API.

#### Steps to reproduce
Server: Mattermost v5.10
1. Prepare a Personal Access Token (Admin account)
2. Call the [Post Ephemeral](https://api.mattermost.com/#tag/posts%2Fpaths%2F~1posts~1ephemeral%2Fpost) API
3. Receive a 403 response

#### Expected behavior
Creating an ephemeral post to selected `user_id`

#### Observed behavior (that appears unintentional) 
Received a 403 error even though I am using an admin account
The url, header and response of the api I called.
![image](https://user-images.githubusercontent.com/29148223/56341900-733e8300-61f1-11e9-8658-0207910704ba.png)
body:
![image](https://user-images.githubusercontent.com/29148223/56342002-bdbfff80-61f1-11e9-8f7e-8cb2343837cf.png)

**Comment by amyblais** [comment]
@maruTA-bis5 / @hanzei Do you know if there is a bug here?

**Comment by hanzei** [comment]
@cored Are you using team edition or enterprise edition?

**Comment by cored** [comment]
@hanzei Not sure, but I think you made a mistake with my handle?

**Comment by maruTA-bis5** [comment]
I tried in 5.10.0 Team Edition, there are no problem to send ephemeral message.

- Use mattermost/mattermost-preview:5.10.0 docker image
- Bearer token is a system admin's personal access token.
- user_id is the target user to display ephemeral message (not admin).

### Request
```
4 19, 2019 7:46:54 午前 org.glassfish.jersey.logging.LoggingInterceptor log
情報: 1 * Sending client request on thread main
1 > POST http://192.168.99.100:8065/api/v4/posts/ephemeral
1 > Accept: application/json
1 > Authorization: Bearer 5haowhmbcfb7ujxzx3caa4a6fr
1 > Content-Type: application/json
{"user_id":"h6ihx3dei3gxmgu768a79raixh","post":{"channel_id":"z14jhfambpg8byoiudopta339c","message":"Hello World!"}}
```

### Response
```
4 19, 2019 7:46:54 午前 org.glassfish.jersey.logging.LoggingInterceptor log
情報: 1 * Client response received on thread main
1 < 201
1 < Content-Length: 356
1 < Content-Type: application/json
1 < Date: Thu, 18 Apr 2019 22:46:57 GMT
1 < X-Request-Id: cnus637dk7bsumkkjgnsjhudqa
1 < X-Version-Id: 5.10.0.5.10.0.ee35de5854fdfae40da514226baf938e.false
{"id":"dccue6k8mfr3mmu317iojjnrtr","create_at":1555627617172,"update_at":0,"edit_at":0,"delete_at":0,"is_pinned":false,"user_id":"dtm391jk6jga3xxphpqra6j1by","channel_id":"z14jhfambpg8byoiudopta339c","root_id":"","parent_id":"","original_id":"","message":"Hello World!","type":"system_ephemeral","props":{},"hashtags":"","pending_post_id":"","metadata":{}}
```

**Comment by hanzei** [comment]
Sorry @cored, I somehow pinged the wrong person.

**Comment by yth0625** [comment]
@hanzei I using enterprise edtion.

**Comment by jespino** [comment]
ok, then is a permissions related problem, your user is system admin user?

**Comment by yth0625** [comment]
@jespino yes i using system admin token.

**Comment by amyblais** [comment]
Hi @yth0625, do you see the same issue if you try with this suggestion above https://github.com/mattermost/mattermost-server/issues/10641#issuecomment-484718417?

**Comment by yth0625** [comment]
@amyblais Yes, I used admin access token and general user_id, but an error occurs.

**Comment by jespino** [comment]
@yth0625 can you use this new remote CLI command mmctl (https://github.com/mattermost/mmctl), login in your account as a system admin (using `mmctl auth login` command), and then run `mmctl permissions show system_admin` and verify that `create_post_ephemeral` is granted there? if you are using linux, you can do it easily with `mmctl permissions show system_admin | grep ephemeral`.

**Comment by amyblais** [comment]
Closing this for now as there hasn't been updates on this for a while. Please re-open this issue if the problem persists.

**Comment by naggie** [comment]
I had this issue too -- please see https://github.com/mattermost/mattermost-server/issues/13274#issuecomment-1248713506 for the command I used to fix it. Hope this helps anyone coming from google.
