### ISSUE TITLE
[MM-15194] Migrate "Emoji.Save" to Sync by default

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10642]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15194)

Mattermost is migrating its Store layer to be sync by default, and only use Async when needed and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `Save` in the `Emoji` store.

The expected way to implement it is, go to the `Emoji` store implementation in the `store/sqlstore/` directory, modify the method `Save` to return directly an object from the `model` module, and a `*model.AppError` (removing the `store.Do` wrapper). After that, you must modify the interface defined in `store/store.go` to match with the changes. Then, you should execute `make store-mocks` to rebuild the mocks with the new interface. And finally, modify the rest of the code (tests included) to use the new interface of the function properly.

Example: mattermost/mattermost-server#10613

**Comment by EmilLuta** [comment]
I'd love to give this a go if that's alright.

**Comment by hanzei** [comment]
Thanks @EmilLuta!

**Comment by jespino** [comment]
@EmilLuta How is everything going? Let me know if you need any help :)

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by jesper-apsis** [comment]
Can I give it a try?

**Comment by hanzei** [comment]
Surely, @jesper-apsis. Let me know, if you have any questions.

**Comment by jesperhansen17** [comment]
Hi @hanzei, I took on this issue above. But I realized that I was logged in on the wrong Github account. So I just want to let you know that this is the account I will contribute with.

Everything is going well, will shortly open PR.

**Comment by hanzei** [comment]
Hey @jesperhansen17, thanks for the heads up. :wink: Looking forward to your PR.
