### ISSUE TITLE
[Help Wanted] [MM-15161] Add support for bots to create ephemeral messages

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10640]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15161)

Currently ephemeral posts created by bots just show the default icon and username.

If you have any questions, reach out to @jasonblais on GitHub, or jason.blais on https://community.mattermost.com

**Comment by scottleedavis** [comment]
I am interested in this one.  :)

**Comment by jasonblais** [comment]
@scottleedavis Awesome, thank you 🎉

**Comment by scottleedavis** [comment]
I had originally misunderstood this issue.  I had thought ephemeral posts were not working for bots....   it is the icon and the username that should be updated.  

<img width="329" alt="Screen Shot 2019-04-24 at 8 38 32 PM" src="https://user-images.githubusercontent.com/2914443/56708330-1ea77600-66d1-11e9-9b99-81f560f0d34a.png">

**Comment by scottleedavis** [comment]
@jasonblais Is it out of scope to attempt to have 'BOT' as part of the username?  user popover?

**Comment by hanzei** [comment]
This issue was wrongly labelled. The server side is fine, but this needs changes in both apps.

**Comment by scottleedavis** [comment]
<img width="329" alt="Screen Shot 2019-04-24 at 8 38 32 PM" src="https://user-images.githubusercontent.com/2914443/56725065-03545f00-6701-11e9-8fcf-d1b0d6c814b2.png">

**Comment by scottleedavis** [comment]
<img width="402" alt="Screen Shot 2019-04-25 at 2 22 36 AM" src="https://user-images.githubusercontent.com/2914443/56725088-0ea78a80-6701-11e9-913a-e6a9e9debff8.png">
