### ISSUE TITLE
Config migrate SAML keys and certificates

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10654]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15197)

https://mattermost.atlassian.net/browse/MM-13895 introduced the config migrate command, allowing a config.json to be put into the database (or vice versa). This ticket is to extend that migrate command to handle SAML keys and certificates.

When SAML is configured using a file-based config.json, the server writes the keys and certificates into the config/ directory next to config.json, and records a path to the corresponding files in config.json itself. When SAML is configured using a database-based config, the server writes the keys and certificates into a ConfigurationFiles table in the database, and records the "path" in the Configurations table within the database. This is all abstracted by the config package in mattermost-server. 

When config migrate is invoked, the existing config should be examined to look for any SAML keys and certificates (SAMLSettings.IdpCertificateFile, SAMLSettings.PublicCertificateFile, SAMLSettings.PrivateKeyFile), and these should be added to the new config. It is not necessary to read/write files manually: use the GetFile and SetFile interface on the appropriate config object instead.

**Comment by therealpuneeth20** [comment]
I'd like to take this up.

**Comment by hanzei** [comment]
Great, thanks @therealpuneeth20. :+1:  As allays: Let us know if you have any questions.

**Comment by hanzei** [comment]
@RajatVaryani will work on this

**Comment by RajatVaryani** [comment]
Thanks @hanzei

**Comment by RajatVaryani** [comment]
@lieut-data Just want to get quick feedback if we are on the same page and have some questions. 

For testing, I think we should generate mocks for Store interface in the config package. What do you think?

**Comment by lieut-data** [comment]
Hi @RajatVaryani, I don't think it's necessary to mock the store interface. Ideally, your unit tests would test file -> database and database -> file, and simply verify that the target store contains the test certificates put into the source store.

Happy to elaborate if you need more help!

**Comment by lieut-data** [comment]
Thanks again, @RajatVaryani!

**Comment by RajatVaryani** [comment]
> Thanks again, @RajatVaryani!

Most Welcome! Thanks for guidance as well.
