### ISSUE TITLE
[MM-14725] User deactivation flow for users who manage bot accounts

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10662]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14725)

**Current behaviour**:

If a user creates bot accounts, but is subsequently deactivated, their bot accounts are disabled as well. However, the System Admin is not aware of this upon deactivation.

**Proposed behaviour**:

1 - Update text for warning dialog when a System Admin deactivates a user who has created at least one bot account.

Current text:
![image](https://user-images.githubusercontent.com/13119842/56391514-e8fc1c00-61fc-11e9-9324-085cfb578e1a.png)

Proposed text:

```
This action deactivates \{user\}.

* They will be logged out and not have access to any teams or channels on this system.
* Bot accounts they manage will be disabled along with their integrations. Learn how to re-enable them.

Are you sure you want to deactivate \{user\}?
```

where "Learn how to re-enable them" links to https://mattermost.com/pl/default-bot-accounts-re-enable

2 - After user deactivation, if a user managed bot accounts which were disabled upon user deactivation, send a self-DM notification to all System Admins of the system. The message will appear as a system message:

```
\{user\} was deactivated. The user managed the following bot accounts which have now been disabled.

* \{bot1\}
* \{bot2\}

Do not worry - you can take ownership of each bot by enabling it at Integrations > Bot Accounts and creating new tokens for the bot.

For more information, see our documentation.
```

where

 - "Integrations > Bot Accounts" should link to the respective page at https://<mattermost-url>.com/<team>/integrations/bots
 - "documentation" links to https://mattermost.com/pl/default-bot-accounts-re-enable

3 - From the list of disabled bots, any user with permissions to create bots can re-enable the bot and generate new token(s) for it. Re-enabling automatically takes ownership for that user.

**Comment by jasonblais** [comment]
For now, this improvement was simplified and re-created at https://github.com/mattermost/mattermost-server/issues/10863. Closing
