### ISSUE TITLE
Write an automated test using Cypress for "No Status on a System Message"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10676]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15240)

*Test Key: Mult15240 - No status on a system message*
*Test Group: Multi Team + DMs*

*Steps:*
1. Trigger a system message that wraps to a second line
2. You can do this by editing a channel header to contain a long string of text

*Expected:*
- System message should not have status indicator in standard or compact view

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by Jonany** [comment]
Starting to work on this but I have a few questions. I've never used Mattermost before so I'm not familiar with what system messages and status indicators are. Is the system message the tooltip that is displayed when you click on the channel header?

**Comment by saturninoabril** [comment]
Hi @Jonany, thank you for working on this.

System message is an auto-generated post to a channel. Example is when a user is added to a channel --  see last message posted in the screenshot.
![Screen Shot 2019-05-31 at 5 07 42 PM](https://user-images.githubusercontent.com/5334504/58695110-27bdee00-83c7-11e9-9baf-5704762adc79.png)

System message doesn't have status indicator (pointed by red arrow) as compared to normal user with status indicator (green arrow) like online, away, etc...

I'm inviting you to join our community at https://community.mattermost.com, say hi to community and get a chance to know more about Mattermost.

Let me know if you'd like to grab this ticket so that others are aware that it's already taken.

**Comment by Jonany** [comment]
@saturninoabril That makes much more sense! :smile: Thanks! 

I actually already joined the community and just said hi to everyone in the Contributors channel :smiley_cat: 

Yes, I would like to take this ticket.

**Comment by hanzei** [comment]
Hey @Jonany,

How is your work going? Do you have questions?

**Comment by Jonany** [comment]
Hi @hanzei,

I've been on vacation and had some trouble with my Linux install but I plan on submitting a pull request this week.

**Comment by hanzei** [comment]
Great, looking forward to your PR!

**Comment by hanzei** [comment]
If you have issues with the installation, feel free to ask for the on the [Mattermost Community Server](https://community.mattermost.com).

**Comment by Jonany** [comment]
@saturninoabril The file is currently `cypress/integrations/onboarding/multi_team/no_status_on_system_message_spec.js`. Should I change it to something like `cypress/integrations/multi_team/system_message_spec.js`?

**Comment by saturninoabril** [comment]
Thanks for asking @Jonany!
Re: folder, sounds good to me the `cypress/integration/multi_team/system_message_spec.js`.

Yup, that's the key difference but I'm seeing that too on my local test server.

**Comment by Jonany** [comment]
@saturninoabril Interesting. My test server is also not displaying the Mattermost logo for the system message. Any idea what might be going on? My branch is up-to-date with Mattermost master.

![mattermost_system_message_screenshot](https://user-images.githubusercontent.com/13025459/60235386-2ddfa700-986d-11e9-9c39-3ab6267b1afb.png)

**Comment by saturninoabril** [comment]
Hmm, I'm don't know why but it's working fine on me.  I'm also on latest master.

**Comment by Jonany** [comment]
@saturninoabril in that case, I think I'll try a new fork.

**Comment by Jonany** [comment]
@saturninoabril From what I can tell from `/components/post_view/post/post.jsx` (lines 176-183), the main difference between system posts and user posts is that system posts have the `post--system` class. The `<span class="status-wrapper"` is applied to both post types by the profile picture `components/profile_picture.jsx`.

**Comment by Jonany** [comment]
I must be missing something. From the looks of this code from `components/profile_picture.jsx` the only difference is that the `alt` is empty on the system message. I also diffed the HTML from a system message and user message and there were no differences in the status section. However, the status SVG is visible on the user message and not visible on the system message.

```JavaScript
    render() {
        if (this.props.userId) {
            return (
                <OverlayTrigger
                    ref='overlay'
                    trigger='click'
                    placement='right'
                    rootClose={true}
                    overlay={
                        <ProfilePopover
                            userId={this.props.userId}
                            src={this.props.src}
                            isBusy={this.props.isBusy}
                            hide={this.hideProfilePopover}
                            isRHS={this.props.isRHS}
                            hasMention={this.props.hasMention}
                        />
                    }
                >
                    <span className='status-wrapper'>
                        <img
                            className='more-modal__image rounded'
                            alt={`${this.props.username || 'user'} profile image`}
                            width={this.props.width}
                            height={this.props.width}
                            src={this.props.src}
                        />
                        <StatusIcon status={this.props.status}/>
                    </span>
                </OverlayTrigger>
            );
        }
        return (
            <span className='status-wrapper'>
                <img
                    className='more-modal__image rounded'
                    alt=''
                    width={this.props.width}
                    height={this.props.width}
                    src={this.props.src}
                />
                <StatusIcon status={this.props.status}/>
            </span>
        );
    }
```

**Comment by Jonany** [comment]
So I'm thinking the best option is to check if the SVG that displays the status icon is visible. Thoughts?

**Comment by saturninoabril** [comment]
Thanks @Jonany for your contribution!
