### ISSUE TITLE
Inline Images In Markdown Preview Don't Get Expanded

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#10687]
#### Summary
When using inline image via markdown and switching to markdown preview, the message areas remains the same size irrespective of the image size, causing the image to appear in a narrow slit with scrollbars.

#### Steps to reproduce
1. Make sure you markdown preview is enabled
1. type a message with large inline image via markdown - `![make it so](https://i.stack.imgur.com/MNeE7.jpg)` for example. Don't send the message.
1. Switch to markdown preview.
1. Notice how the inline image in the preview appears in the narrow message box.

Also note that this doesn't happen with, for example, a list.

#### Expected behavior
The message box should expand, just like it does with, for example, with a list, so that image preview can be easily viewed.

#### Observed behavior (that appears unintentional) 
Message box's size remains unchanged, making it difficult to view a large inline image.

See attached screengrab -

![](https://media.giphy.com/media/SXrbkS7JaiMmlyDU8l/giphy.gif)

**Comment by amyblais** [comment]
Thank you @harshilsharma63, opened a ticket here: https://mattermost.atlassian.net/browse/MM-15273.

**Comment by harshilsharma63** [comment]
Thanks @amyblais!

**Comment by amyblais** [comment]
Closing this as the bug has been fixed for upcoming v5.12 release,
