### ISSUE TITLE
[MM-14968] If a bot has a long username the bot tag can get truncated in Reply thread 

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10682]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14968)

If a bot has a long username the bot tag can get truncated in Reply thread. We should truncate the letters of the username but always keep the tag visible.

I did not see this occur on Mattermost mobile apps.

![image](https://user-images.githubusercontent.com/13119842/56605592-80cd8180-65d2-11e9-85f5-1a153b6915af.png)

![image](https://user-images.githubusercontent.com/13119842/56605606-888d2600-65d2-11e9-851c-78a1e5af8736.png)

#### Steps:
- Go to Main Menu > Integrations. Click on Bot Accounts to open a list of previously created bot accounts, if any. 
- Create a bot with a long username - at least 15 characters 
- Create a post as the bot
- View the post created above in the reply thread

##### Current:

![image](https://user-images.githubusercontent.com/13119842/56605618-8e830700-65d2-11e9-81b9-ca5b7e66a061.png)

##### Expected:

![image](https://user-images.githubusercontent.com/13119842/56605633-96db4200-65d2-11e9-9e2d-97ad18d51df2.png)

#### Questions

If you have questions, you can ask `jasonblais` or `asaadmahmood` on this GitHub issue.

**Comment by lisakycho** [comment]
Hi, I would like to attempt this one!
Quick question about making a bot to test with, would I need to make a bot similar to `mattermost-bot-sample-golang` or can is there a way to rename a bot?

**Comment by jasonblais** [comment]
Thanks @lisakycho! And a great question. You can create a bot account by going to Main Menu > Integrations. Click on Bot Accounts to open a list of previously created bot accounts, if any. Then create a new bot account.

I updated the issue description as well.

Let me know if that helps you get started?

**Comment by lisakycho** [comment]
Sorry @jasonblais, I have another question! After making the bot, I can't seem to figure out how to post as the bot.

**Comment by jasonblais** [comment]
Hey @lisakycho, I saw your question got a response from Chris here: https://community.mattermost.com/core/pl/bnzfw7wtkff5bkmgrjxfc98pih

Let me know if that was helpful? Happy to help you!

**Comment by jasonblais** [comment]
To add, a curl command to do a bot post is below:

```curl
curl -i -X POST -H 'Content-Type: application/json' -d '{"channel_id":"3wbu8ue9g3fj7eobezpsqnamih", "message":"This is a message from a bot", "props":{"attachments": [{"pretext": "Look some text","text": "This is text"}]}}' -H 'Authorization: Bearer 669dydgnytbb9qcsbhuqz3imhe' https://botaccounts.test.spinmint.com/api/v4/posts
```

**Comment by jasonblais** [comment]
Hi @lisakycho, just touching base how things are going and if you have any questions for this ticket?

**Comment by lisakycho** [comment]
@jasonblais, I got to a point where the bot name will be shorted on the RHS, but when i inspect it the bot indicator does not live outside col_name. 
I will look into this future this week.

**Comment by jasonblais** [comment]
@lisakycho Thanks for the heads up!

I'd be happy to test the changes you have so far, if you're open to submitting a pull request. Perhaps it doesn't need to live outside col_name.

**Comment by lisakycho** [comment]
@jasonblais, hey i submitted a rough draft of my pull request in hopes that I can get some help.
I tried to put the styling in `_post.scss`, but it kept getting overwritten and wasn't sure if I was putting it in the right place.
When i inline the styling it seems to somewhat work. 
Any help would be great!

**Comment by jasonblais** [comment]
Thank you @lisakycho! I'll ask Asaad to help review the changes so far 👍
