### ISSUE TITLE
[MM-15228] Do not hide profile pic in consecutive bot account posts

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10681]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15228)

Change bot posts to NOT hide the profile pic, username and timestamp in consecutive posts. This is consistent with webhook posts where "from_webhook" prop shows all the info in consecutive posts.

Also, for remind bot and NPS bot, the designs specified that certain posts should always show the profile image instead of that section being hidden for consecutive bot posts.

This can be adjusted as we get feedback on bot accounts.

**Comment by scottleedavis** [comment]
Interested in this one.  :)
