### ISSUE TITLE
[MM-15218] Add support for Interactive Dialog with no elements

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10686]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15218)

Interactive Dialogs allow integrations to receive some form-styled input from users and have that input submitted back to the integration. An Interactive Dialog consists of a list of elements.

Currently there a dialog has to have at least one element. This ticket is is about allowing integrations Dialogs with no elements. These can e.g. be used for confirmation dialogs.

This ticket requires changes in the [Mattermost server](https://github.com/mattermost/mattermost-server/).

For more information about Interactive Dialog, see [https://docs.mattermost.com/developer/interactive-dialogs.html](https://docs.mattermost.com/developer/interactive-dialogs.html).

If you have any questions or would like feedback, feel free to ask in the [Extensions channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by andresoro** [comment]
So in api4/integration_action.go, the openDialog handler checks for elements like so: 
```
var dialog model.OpenDialogRequest
if dialog.Dialog.Elements == nil || len(dialog.Dialog.Elements) == 0 {
		c.SetInvalidParam("dialog.elements")
		return
	}

```

To satisfy this we could simply drop that statement and allow dialogs to have no elements. I could add a separate test case for this. As far as I know so far, api4/integration_action.go is the only place the check for elements is made.

**Comment by hanzei** [comment]
That is correct @andresoro.

As a bonus task: I would be great if you would write a simple integrations that creates such dialog. That would make testing much easier. But this is just optional.

**Comment by andresoro** [comment]
Apologies if I’m asking for too much hand holding, but how should I write the integration? An example in the codebase would set me on track.

**Comment by hanzei** [comment]
No problem. You just use [Matterpoll](https://github.com/matterpoll/matterpoll), a plugin that creates polls. It uses Interactive Dialogs to add new options to a poll. You can modify the dialog create in https://github.com/matterpoll/matterpoll/blob/master/server/plugin/api.go#L273-L289 to have no element and use this for testing.

**Comment by hanzei** [comment]
After some investigation I think changes to the webapp and mobile app will be needed, too.

**Comment by andresoro** [comment]
While my knowledge of react is pretty limited, I found that the Elements prop for the Interactive Dialog component is a required prop [mattermost-webapp/components/interactive_dialog/interactive_dialog.jsx](https://github.com/mattermost/mattermost-webapp/blob/c57779a31b7164565f5d2fd9d234eebb6537009b/components/interactive_dialog/interactive_dialog.jsx#L20). 

To support interactive dialog with no elements we'd probably have to modify to component to not require elements, and perhaps do a check before we render the dialog. So I think this paired with the changes to the openDialog handler in api4/integration_action.go should be what we need to add support. 

I could get started on this and also create test integrations with Matterpoll.

**Comment by hanzei** [comment]
That would be awesome! Thanks @andresoro :+1:

**Comment by andresoro** [comment]
Hey @hanzei, so I've made the changes in the server and web-app to support interactive dialogs with no elements and I'm in the process of adding test cases. I am still a little confused with how to make an integration with Matterpoll. I forked it and made the change you suggested earlier but I am still unsure to see if it works or not.

**Comment by hanzei** [comment]
Hey @andresoro, thanks for the heads up! I can provide an example to test this by myself, if you want. I don't want to overburden you with figuring out how matterpoll works.

**Comment by jasonblais** [comment]
Thanks @andresoro for the contribution! Closing this issue

**Comment by hanzei** [comment]
This still needs to be implemented on mobile.

**Comment by janvt** [comment]
Just added a PR for mobile.

**Comment by Domvel** [comment]
I suggest to offcial include [MatterPoll](https://github.com/matterpoll/matterpoll) to Mattermost. It's a nice must-have feature. And in our case, we can't use plugins because there is a bug in the plugin feature of Mattermost. But anyway... this should be an official part of Mattermost. What do you think?

**Comment by hanzei** [comment]
Hey @Domvel,

As the maintainer of MatterPoll I'v honoured by your world. Glad you enjoy this plugin! But it's not up to me to decide if MatterPoll should be pre-packed or not.

cc @aaronrothschild @jasonblais on this question

**Comment by jasonblais** [comment]
@Domvel what is the bug in plugins that's preventing you from installing Matterpoll?

**Comment by aaronrothschild** [comment]
> Hey @Domvel,
> 
> As the maintainer of MatterPoll I'v honoured by your world. Glad you enjoy this plugin! But it's not up to me to decide if MatterPoll should be pre-packed or not.
> 

@Domvel @hanzei The toolkit team is currently building out the "Integrations Marketplace" which will let us remove all pre-packaged plugins from being bundled with the server.  The marketplace will let you scroll through a dynamic list of available plugins for your current server version, and easily install them.  At first, only Mattermost controlled repositories/plugins will be in the marketplace with popular community plugins like Matterpoll hopefully following soon afterwards.

**Comment by hanzei** [comment]
This is resolved. Thank you very much @janvt :+1:

**Comment by hanzei** [comment]
This is resolved. Thank you very much @janvt :+1:
