### ISSUE TITLE
Images in GitLab issues are sometimes broken in Mattermost

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10684]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14972)

The changes mentioned on this issue should be submitted to GitLab repository https://gitlab.com/gitlab-org/gitlab-ce/

When integrating with GitLab via webhooks, posts resulting from that integrations sometimes have broken images. These images are coming from GitLab as relative links, which means Mattermost isn't able to find the image and render it in the channel.

 - This post is from a comment on an issue, and it has a broken relative link: https://community.mattermost.com/core/pl/unqywr1rdpghmrobrnei1ay7xh
 - This post is from the start of a new issue, and it has a working absolute link: https://community.mattermost.com/core/pl/ns8rpsw56byfpy7iducu6qkrzw

The actual comment and issue both include relative links, so there must be some transformation happening for new issues that doesn't occur with comments.

Possible fix: it seems to be some different behaviour between the [IssueMessage](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/models/project_services/chat_message/issue_message.rb) used for things like "issue opened" and the [NoteMessage](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/models/project_services/chat_message/note_message.rb) used for things like "user commented on..."

**Comment by lieut-data** [comment]
This issue was reportedly fixed in https://gitlab.com/gitlab-org/gitlab-ce/issues/20720:
> From GitLab 11.2, simple image references are rewritten to use an absolute URL
in webhooks.
