### ISSUE TITLE
Channel switcher auto-complete doesn't function properly when auto-completing the name of a person who is the first person named in a group DM channel - Mattermost Server 5.10 

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-server#10698]
#### Summary
Auto-complete doesn't function properly when auto-completing the name of a person who is the first person named in a group DM channel 

#### Steps to reproduce
- Create multiple group DM channels with PERSON A listed first 
- Switch from viewing user names to full names under display settings 
- Create more group DM channels with PERSON A listed 
- CTRL+K to switch channels 
- Start to type the name of the first person
- Use the arrow key to scroll down 

Appears on community.mattermost.com but not on oss.mattermost.com 

#### Expected behavior
- Down arrow key allows me to go down the list 

#### Observed behavior (that appears unintentional) 

Duplicate Group DMs shown, and can't arrow down past them 

![image](https://user-images.githubusercontent.com/177788/56735636-dca32200-671a-11e9-80ea-8a01675e04e5.png)

![image](https://user-images.githubusercontent.com/177788/56735608-c2694400-671a-11e9-9201-a610a810080b.png)

![image](https://user-images.githubusercontent.com/177788/56735619-cac17f00-671a-11e9-953c-0c65dbae5a8b.png)
![image](https://user-images.githubusercontent.com/177788/56735693-052b1c00-671b-11e9-8602-98af32632299.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

NOTE: Please let me know if I'm eligible for [a Bug Hunter Coin](https://forum.mattermost.org/t/mattermost-bug-hunter-awards/4979) on this report? I can be reached at 855 El Camino Real, 13A-168, Palo Alto, CA, 94301. I'd like test out the experience of getting one. Btw, one benefit of the coin program is that it only applies to filing a ticket in GitHub and not just adding the info in a channel.

**Comment by amyblais** [comment]
Hi @it33,

Is this reproducing for you consistently and is there any other additional information you might be able to share (e.g. OS and version)?

I wasn't able to reproduce this and our QAs weren't able to reproduce it so far either.

**Comment by hanzei** [comment]
I've run into the same problem.

Environment:
- Linux desktop app
- https://community.mattermost.com
- `v5.10.0`

Steps to repo:
- Open a DM channel to `@remindbot` and let it stay on the LTS
- Open the channel switcher in **any** channel.
- Type `rem`

Observed behaviour:
![Screenshot from 2019-04-28 07-55-01](https://user-images.githubusercontent.com/16541325/56859483-ee3f3080-698b-11e9-87fc-d1ce6e468597.png)
I also can't use the keyboard to select the channel.

Expected behaviour:
- Remindbot only shows up once
- I can select an entry with the keyboard.

**Comment by it33** [comment]
@amyblais yes, I'm still having the issue. Not sure if this is related but as I try different searches for channel sometimes I get the wrong results in auto-complete, e.g. "ar" doesn't appear in any of these results: 

![image](https://user-images.githubusercontent.com/177788/56959809-a0e5cf00-6b03-11e9-976d-beb5a6efb43b.png)

This list can stay there for 10 seconds or more (i..e if it's a lazy-load issue it takes a while). When I leave the tab and navigate back then it looks like it works: 

![image](https://user-images.githubusercontent.com/177788/56959890-e86c5b00-6b03-11e9-9130-88a0a6fe3dab.png)

However the original problem of duplicate channels and then down arrow being able to move past the duplicate entries, is still here

![image](https://user-images.githubusercontent.com/177788/56959926-076aed00-6b04-11e9-9c1c-59ac6e8679be.png)

**Comment by amyblais** [comment]
I opened a bug ticket for this here: https://mattermost.atlassian.net/browse/MM-15363.

I'll look into the Bug Hunter Coin shortly,

**Comment by jwilander** [comment]
I started looking at this last night and I think I have discovered the issue causing the duplicate GMs that @it33 is seeing. I'll be submitting a fix for that sometime today. The issue that @hanzei is seeing is related but different and is a known issue that's going to require a significant reworking of our autocomplete suggestion to fix so at this time it's not worth the effort, see https://mattermost.atlassian.net/browse/MM-11193

**Comment by amyblais** [comment]
@it33 I've coordinated with Corey to send out a Bug Hunter Coin for you. Thank you for reporting this!

**Comment by amyblais** [comment]
Closing this issue as this has been fixed for upcoming v5.12 release (to be released in June 16th).
