### ISSUE TITLE
[MM-15297] Migrate "Preference.Get" to Sync by default

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10721]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15297)

Mattermost is migrating its Store layer to be sync by default, and only use Async when needed and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `Get` in the `Preference` store.

The expected way to implement it is, go to the `Preference` store implementation in the `store/sqlstore/` directory, modify the method `Get` to return directly an object from the `model` module, and a `*model.AppError` (removing the `store.Do` wrapper). After that, you must modify the interface defined in `store/store.go` to match with the changes. Then, you should execute `make store-mocks` to rebuild the mocks with the new interface. And finally, modify the rest of the code (tests included) to use the new interface of the function properly.

Example: mattermost/mattermost-server#10613

**Comment by ivanaairenee** [comment]
I'd like to try taking this if that's okay

**Comment by hanzei** [comment]
Surely, @ivanaairenee. :+1: Thanks for taking of this. Let me know, if you have any questions.

**Comment by ivanaairenee** [comment]
Hi @hanzei, this is my first time making a PR and I have a [test failure on Jenkins](https://build.mattermost.com/blue/organizations/jenkins/mp%2Fmattermost-server-pr-new/detail/PR-10811/3/pipeline)

```
+ docker-compose --no-ansi run --rm start_dependencies
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?
        Supported filenames: docker-compose.yml, docker-compose.yaml
Terminated
script returned exit code 1
```

Any pointers to any documentation or community discussion I can look at?

**Comment by hanzei** [comment]
Hey @ivanaairenee, this seams to be a failure with our build system. I restarted the build and it should run smoothly now.
