### ISSUE TITLE
On OS X `make stop-server` leaves plugin processes running

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10735]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14827)

Steps to reproduce:

* Set up a dev environment on Mac OSX
  ```
   Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64
   go version go1.12.1 darwin/amd64
  ```
* `make run-server`
* `ps aux | grep 'plugin-darwin-amd64'` - observe one or more plugin processes running
* `make stop-server`
* `ps aux | grep 'plugin-darwin-amd64'` - observe the plugin processes still running

Expected: plugin processes to terminate when the mattermost-server process exits

**Comment by scottleedavis** [comment]
I am interested in doing this one.
