### ISSUE TITLE
Build a 1-click Mattermost app on DigitalOcean marketplace (DigitalOcean Droplets)

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10733]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15308)

DigitalOcean has published guides on how to publish 1-click apps on their marketplace (DigitalOcean Droplets).

We would like to publish an app as well, but need help building the 1-click Mattermost apps and sending the information for us to publish.

Link to marketplace: https://marketplace.digitalocean.com/vendors
Link to guide: https://marketplace.digitalocean.com/vendors/getting-started-as-a-digitalocean-marketplace-vendor
Additional information about building marketplace images manually: https://github.com/digitalocean/marketplace-partners/blob/master/marketplace_docs/build-an-image.md

DigitalOcean supports the following operating systems:
 - Debian 9 (stretch)
 - Ubuntu 18.04 (LTS)
 - Ubuntu 16.04 (LTS)
 - CentOS 7.x
 - CentOS 6.x

Their respective Mattermost install guides can be found here: https://docs.mattermost.com/guides/administrator.html#installing-mattermost

If you need any assistance or have questions, please reach out to `jasonblais` or `wget` by replying to this GitHub issue.

**Comment by andrewsomething** [comment]
Excited to see interest in getting Mattermost in the DO marketplace! Happy to make an intro to the team at their if it's helpful.

**Comment by carmo-evan** [comment]
I'd like to do this.

**Comment by carmo-evan** [comment]
I've created the droplet and taken a snapshot:

`48023112    mattermost-1559734268274    snapshot    Ubuntu                  false     25`

I've reached out to the Digital Ocean Marketplace Team to gather next steps.

**Comment by carmo-evan** [comment]
Let me copy you on the email.

**Comment by avdrav** [comment]
Just tried to use the droplet for MM that appears in DO's marketplace, but I am unable to connect to the web admin interface (port 8605).

I am able to ping/ssh into the box.  Is there something I am missing to get this to work?

**Comment by jasonblais** [comment]
This is completed, will close, thanks @carmo-evan and @cpanato!
