### ISSUE TITLE
cant find module “mattermost-redux/action/errors”

### ISSUE THREAD

**Issue by lycaste** [mattermost/mattermost-server#10748]
#### Summary
cant find module “mattermost-redux/action/errors”

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
macos mojave10.14
node version 10.15
npm version：6.9.0
step 1：
git clone  mattermost-webapp
cd mattermost-webapp
make test 
all tests are passed
step 2：
make run 
then open the chrome with localhost：8065
chrome always loading
and console shows:
cant find module “mattermost-redux/action/errors”

**Comment by lycaste** [comment]
i download the https://releases.mattermost.com/5.10.0/mattermost-5.10.0-linux-amd64.tar.gz 
copy the client folder to server floder 
chrome console also show cant find module “mattermost-redux/action/errors”

**Comment by amyblais** [comment]
Hi @lycaste,

Which install instructions were you following for this?

**Comment by amyblais** [comment]
@sven Are you familiar with this error?

**Comment by amyblais** [comment]
@svelle Are you familiar with this error?

**Comment by lycaste** [comment]
follow developer guide

**Comment by enahum** [comment]
In your dev env, go to node_modules/mattermost-redux and then run npm installl.

It is very likely that the prepare script of mattermost-redux did not run when fetching the webapp dependencies

**Comment by amyblais** [comment]
Closing this as there hasn't been updates on this for a while. Please re-open this issue with relevant information if the issue persists.
