### ISSUE TITLE
Bulk import process shouldn't abort due to a failed image import

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10754]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13033)

Original report: https://github.com/mattermost/mattermost-server/issues/9794

If an image exceeds the current hard-coded internal limit of image size, the bulk import process will fail with error "uploadFile: File above maximum dimensions could not be uploaded".  Bulk import should not abort.  This failure should be considered a warning instead and the warning should be printed.

**Comment by liusy182** [comment]
working on this

**Comment by liusy182** [comment]
should import continue upon ALL upload-related error, or it should only continue when the error is specifically due to image size?

**Comment by hanzei** [comment]
@grundleborg Would you please take a look at the above question?

**Comment by grundleborg** [comment]
@liusy182 I think it should cover image dimensions and file size, but probably nothing else for the moment.
