### ISSUE TITLE
Write an automated test using Cypress for "Multi-team Logout"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10759]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15348)

*Test Key: Mult15348*
*Test Group: Multi-team & DMs*

*Steps:*
As the same user in two tabs on the same browser:
1. Open Team A on browser tab A
2. Open Team B on browser tab B
3. Log out of Team A

*Expected:*
- Logged out on both tabs and redirected to sign-in page

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by tbhmogy** [comment]
Cypress does not support multi-tabs and cannot be processed.
https://docs.cypress.io/guides/references/trade-offs.html#Multiple-tabs

**Comment by cometkim** [comment]
FYI @tbhmogy, [jump to conv](https://community.mattermost.com/core/pl/bytnrds7j3da5mo46saxrgh8ae)

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
