### ISSUE TITLE
Don't let bots create other bot accounts

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10753]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14722)

Repro:

1. Create Bot Account (Bot1)
2. As Bot1, try to Create Bot Account (Bot2) via the API

Observed: Bot account created
Expected: Bot1 is denied access to create a bot account.

You cannot log in as a bot account, so this should be disabled at the API level.

**Comment by scottleedavis** [comment]
@jasonblais I'd like to do this one
