### ISSUE TITLE
UX defect: Sorting BOTs at the bottom of channel member list below offline users is not working

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10752]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14767)

Sorting BOTs at the bottom of channel member list below offline users is not working.

BOTs should not have a status and as such, should always be sorted below the offline users. 

![StatusSort](https://user-images.githubusercontent.com/16541325/56899450-c2a76d80-6a93-11e9-87b5-3b7450fe9578.PNG)

Steps:
- Open a channel that contains sevral BOT users
- Select the channel members button to view the drop-down list
- Note the sorting of the channel members

**Expected**: All users are sorted by status with BOTs listed below Offline users 

**Observed**: BOT users are mixed in

**Comment by CooperAtive** [comment]
I'll take this one

**Comment by hanzei** [comment]
Thanks for taking care of this @CooperAtive! :+1:

**Comment by jasonblais** [comment]
@CooperAtive Thank you so much! This is really really helpful as we're trying to finish bot accounts in time for June 16th release.

If you're open to and interested helping, there are these three Help Wanted tickets for bot accounts we'd love to have help with

 - https://github.com/mattermost/mattermost-server/issues/10683
 - https://github.com/mattermost/mattermost-server/issues/10822
 - https://github.com/mattermost/mattermost-server/issues/10821
