### ISSUE TITLE
Team Override Scheme garbles `roles` property on Team `members` API call

### ISSUE THREAD

**Issue by sadohert** [mattermost/mattermost-server#10750]
#### Summary
When a Team Override Scheme is applied to a team and the user membership of the team is accessed using REST endpoint `/api/v4/teams/{{team_id}}/members`, the `roles` property for each user is returned as gibberish

#### Steps to reproduce
* Create a new Mattermost Team.
* Request the members of the new team using `{{mattermost_host}}/api/v4/teams/{{team_id}}/members`
Note:  The new team should have one user and the output appears similar to below, with the `roles` property set to sane values:
```json
    {
        "team_id": "4gsntesnyffu8f7q53nb3fdcxo",
        "user_id": "d551pr957inrdbqo83uweyodnh",
        "roles": "team_user team_admin",
        "delete_at": 0,
        "scheme_user": true,
        "scheme_admin": true,
        "explicit_roles": ""
    }
```
* Create and apply a new [Team Override Scheme](https://docs.mattermost.com/deployment/advanced-permissions.html?highlight=team%20override#team-override-scheme-e20) to the new team.  Use the default permissions that are created for the scheme.
* Request the members of the new team using REST endpoint `{{mattermost_host}}/api/v4/teams/{{team_id}}/members`
Note: The `roles` property appears garbled/transformed to non-human readable values, as below
```json
    {
        "team_id": "4gsntesnyffu8f7q53nb3fdcxo",
        "user_id": "d551pr957inrdbqo83uweyodnh",
        "roles": "oppt1atfwpni3yr6d8w7wd4ray ks5bandrfjbbdcaise6atcjbur",
        "delete_at": 0,
        "scheme_user": true,
        "scheme_admin": true,
        "explicit_roles": ""
    }
```

#### Expected behavior
The `roles` property should still be human-readable/sane after applying the "Team Override Scheme"

#### Observed behavior (that appears unintentional) 
The `roles` property in the response to `{{mattermost_host}}/api/v4/teams/{{team_id}}/members` is not readable

#### Environment
Reproduced on Server v5.9 and v5.10

**Comment by amyblais** [comment]
Hi Stu, opened a bug ticket: https://mattermost.atlassian.net/browse/MM-15326.
