### ISSUE TITLE
Avatar and Images posted to chat are missing?

### ISSUE THREAD

**Issue by mcarpenterjr** [mattermost/mattermost-server#10756]
#### Summary
Avatar and Images in chat are missing.

#### Steps to reproduce
Not sure if it is reproducible, this was occurring on 5.09 and I have since updated to 5.10

#### Expected behavior
Avatars and Images display as expected.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

We both have custom avatars, but they're not displaying;
![image](https://user-images.githubusercontent.com/11430497/56922583-875a6e00-6a96-11e9-971d-e775aafc8af9.png)

This is where an image was uploaded into the chat and was once displayed,
![image](https://user-images.githubusercontent.com/11430497/56922648-b4a71c00-6a96-11e9-9af3-eb2dde8e559e.png)

This was sudden and I cannot think of anything that would have prompted this to occur, the server mattermost is running on is an Ubuntu 18.04 instance, and Bot Avatars display without issue.

**Comment by amyblais** [comment]
Hi @mcarpenterjr,

Are you using an image proxy? If yes, more information about troubleshooting this issue is here: https://docs.mattermost.com/administration/image-proxy.html#local-image-proxy.

**Comment by mcarpenterjr** [comment]
Nope, storage settings are set to local. and the data dir is ./data/.

This did solve a portion of my issue though, when making a backup for previous upgrades the file ownership, of the data dir, must have changed from `mattermost:mattermost` to `root:root`. I was able to restore ownership back to mattermost and most of the issue is now fixed. However, a number of user avatars are missing.

**Comment by amyblais** [comment]
@mcarpenterjr, I'll continue to investigate.

Perhaps it's related to this issue: https://github.com/mattermost/mattermost-server/issues/10679.

**Comment by amyblais** [comment]
Can you help confirm that your image proxy is disabled?

Avatars go through the image proxy if you're using a webhook with an override_image or if you're posting a link to the profile image.

Our developers mentioned that this issue sounds that the permissions might be misconfigured.

**Comment by mcarpenterjr** [comment]
Image proxy is definitely disabled.

Most of my images and avatars have been restored, there was an issue with the ownership of the images folder.
Unfortunately, there are still handful of accounts that their avatar has not been restored.

**Comment by amyblais** [comment]
Hi @mcarpenterjr, do you know any more details about those missing avatars, e.g. do they have a different size or are they a different type than those avatars that do show up? Do you see any errors in logs?

**Comment by mcarpenterjr** [comment]
None of the avatars changed, they were copied directly from a backup before I upgraded. So since I've opened this issue most avatars have returned, slowly, and I think there are just a handful left that have yet to show up.

If I wanted to find a log relating to this, where would I go?

**Comment by amyblais** [comment]
I'll close this issue for now as there hasn't been updates for a while, please re-open this issue where needed.
