### ISSUE TITLE
Migrate "Channel.SaveDirectChannel" to Sync by default

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10768]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15355)

Mattermost is migrating its Store layer to be sync by default, and only use Async when needed and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `SaveDirectChannel` in the `Channel` store.

The expected way to implement it is, go to the `Channel` store implementation in the `store/sqlstore/` directory, modify the method `SaveDirectChannel` to return directly an object from the `model` module, and a `*model.AppError` (removing the `store.Do` wrapper). After that, you must modify the interface defined in `store/store.go` to match with the changes. Then, you should execute `make store-mocks` to rebuild the mocks with the new interface. And finally, modify the rest of the code (tests included) to use the new interface of the function properly.

Example: mattermost/mattermost-server#10613

**Comment by iomodo** [comment]
I have a question. Should the `CreateDirectChannel` method signature also be changed? I'd change `StoreChannel` to `(*model.Channel, *model.AppError)`

**Comment by iomodo** [comment]
@jespino I'll take a stab at this, just want to know the answer to the question above.

**Comment by jespino** [comment]
Hi @iomodo, we are splitting the migration of the store in small pieces, one method per PR, but in this case makes a lot of sense to change `CreateDirectChannel` at the same time (because is based on `SaveDirectChannel`) so... up to you, that will be welcome, for sure :)

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/10846. Thanks for the contribution @iomodo!
