### ISSUE TITLE
The 'New Messages' message does not show all new messages.

### ISSUE THREAD

**Issue by ryliejamesthomas** [mattermost/mattermost-server#10779]
#### Summary
The 'New Messages' message (see image attached) does not show all new messages in history. If there are messages older than a certain time (it's not even long, like a day or so) they are hidden and there is no indication that there are more _new_ messages, just that there are older, seemingly already-read messages.

![screenshot_19-05-02_09-53-01](https://user-images.githubusercontent.com/25972447/57050886-139ca900-6cc2-11e9-94a2-39dbc1d3f5e4.png)

Behaviour is the same on electron (Linux) and web client.

#### Steps to reproduce
Check for new messages on an active channel, click on 'Load more messages' above the 'New Messages' line.

#### Expected behavior
I expect that the 'New messages' message will be above all new messages, or _at least_ some kind of indication that they are not _all_ of the new messages

#### Observed behavior (that appears unintentional) 
Loading more messages reveals that there are more new messages / missed coversation that I was completely unaware of.

**Comment by amyblais** [comment]
Hi @ryliejamesthomas,

Thank you for the report, what Mattermost server version are you on?

**Comment by amyblais** [comment]
Hi @ryliejamesthomas,

We have a ticket open for this here https://mattermost.atlassian.net/browse/MM-13663. It will be fixed along with other scrolling improvements were working on (https://mattermost.atlassian.net/browse/MM-11209).

**Comment by ryliejamesthomas** [comment]
Thanks Amy.

Here's the info. I found:

> Mattermost Version: 5.9.0
> Database Schema Version: 5.9.0
> Database: mysql

**Comment by hanzei** [comment]
@ryliejamesthomas Would you please upgrade to the latest version and test again?

**Comment by amyblais** [comment]
Closing as this has been implemented for upcoming v5.14 release,
