### ISSUE TITLE
Add system console setting to enable/disable the creation of bot accounts using the REST API.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10776]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14723)

The setting will need to be added to the system console.

The bot accounts backstage UI should be hidden when creation is disabled.

*Title*: Enable Bot Accounts
*Options*: true/false (default: false)
*Help Text*: When true, bot accounts can be used for integrations in Integrations > Bot Accounts. Bot accounts are similar to user accounts except they cannot be used to log in. See documentation to learn more.

NOTE: “documentation” above links to https://mattermost.com/pl/default-bot-accounts

If you have any questions or design clarifications of the proposed improvement, reach out to @jasonblais on GitHub, or jason.blais on https://community.mattermost.com

**Comment by jasonblais** [comment]
Hey @andresoro! I thought to ping you on this help wanted issue - I noticed you've worked on integrations-related pull requests with migrating webhook methods to Sync, and changing the openDialog to support dialogs with no elements.

This would be another integrations-related ticket where you'd get exposed to Mattermots config.json settings and bot accounts.

Thought you might be interested, but if not, that's totally fine :)

**Comment by andresoro** [comment]
Hey @jasonblais I will definitely take a look at this. Unfortunately this is a busy week for me (finals week) so I may not be able to work at the pace I'd like on this issue. I will update with progress and ask any questions if they arise.

**Comment by jasonblais** [comment]
Sounds great, thank you @andresoro - and good luck on your finals!! 👍

**Comment by andresoro** [comment]
Hey @jasonblais, just an update; I've been taking cursory looks at this so far but I'm going to begin working on this ticket this weekend.

**Comment by jasonblais** [comment]
Great, thank you @andresoro :tada:

**Comment by andresoro** [comment]
Ok, so I think the basic idea is to add another field in the System Console Integrations section to enable/disable creation of bot accounts using REST API. To do this we can add a field like EnableBotAccountsThroughApi to the ServiceSettings struct in model/config.go and then check the flag whenever the server gets an API request to create a bot. I can implement this and add test cases where appropriate. 

One question: this also requires changes to the web app, correct?

**Comment by jasonblais** [comment]
@andresoro That's correct 👍 

And changes will be required for web app, for the System Console part. You can add the new setting to System Console > Integrations > Features section, above `Enable Personal Access Tokens`.

We're planning to add two other settings for bot accounts, so we'll likely create its own page, but for now this setting can go to the general Features section.

**Comment by saxon-y** [comment]
what is system console
