### ISSUE TITLE
Edited text lost when selecting text and cursor moves outside edges of dialog

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-server#10771]
#### Summary
When editing a message if text is selected and cursor leaves the edges of the modal dialog the model dialog closes and data in draft message is lost 

#### Steps to reproduce
Edit a message in web app, select text and allow cursor to pass the edge of the model dialog

#### Expected behavior
In other apps like Discord selecting text and leaving the edges of a model doesn't affect the user experience: 

![image](https://user-images.githubusercontent.com/177788/56962308-143f0f00-6b0b-11e9-8313-8105111f27c5.png)

#### Observed behavior (that appears unintentional) 
In Mattermost, selecting text and allowing the cursor to overshoot the edge of the modal dialog causes the dialog to close and lose the user's data. 

![image](https://user-images.githubusercontent.com/177788/56962340-28830c00-6b0b-11e9-8ded-2bbf6af044f3.png)

#### Possible fixes
1. Update the UX guidelines so that model dialogs only close when a user clicks outside the modal dialog and not on other actions. 
2. Add a confirmation before an edit dialog with modified text closes that the user is okay discarding her changes.

**Comment by amyblais** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-15172.

**Comment by amyblais** [comment]
Closing this as this bug has been fixed for the upcoming v5.12 release,

**Comment by sirmspencer** [comment]
The change logs only mention the channel rename modal. Can anyone confirm that the edit post model is also fixed?

**Comment by JonathonReinhart** [comment]
FYI Mattermost dev team: It really helps when you reference the commit/PR that fixes an issue when you close it.
