### ISSUE TITLE
Autolinking doesn't capture entire link containing matching curly brackets

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10774]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13837)

Original report: https://forum.mattermost.org/t/auto-hyperlink-drops-trailing-curly-brace/6556

Oddly enough, the server's markdown parser does handle this correctly, likely because it's translated from GitHub's Markdown parser. Comparing the server's code with the clients, it looks like more characters, including curly brackets, are considered as extra punctuation that is trimmed from the end of the link. We should fix this issue by having the clients match the server in what they remove from the end of the link.

The list of characters the server considers as trailing punctuation are here: https://github.com/mattermost/mattermost-server/blob/master/utils/markdown/autolink.go#L248

#### Repro steps:
1. Make a post such as 
```
Let's try http://example/result?things={stuff}
```
2. View the post on mobile or in the web app

Observed: The final } is not included as part of the link
Expected: The final } is included as part of the link, similar to if it was a regular bracket

#### Notes: 

Changes should be made both in the mattermost-webapp and mattermost-mobile repositories.

**Comment by jkl5616** [comment]
As I observed, mattermost-webapp is using mattermost/marked as a markdown parser. 
Directly executing mattermost/marked with url above showed same problem, so mattermost/marked need to be fixed.
Likewise, in the case of mattermost-mobile, mattermost/commonmark need to be fixed in the same matter.

**Comment by hanzei** [comment]
That is a good observation. Would you be open on submitting a PR for `mattermost/marked`?

**Comment by hahmadia** [comment]
I would like to give a go at this ticket.
Thanks :)

**Comment by hahmadia** [comment]
This issue has been fixed and addressed in both the mobile and webapp markdown parsers:
[WebApp Fix](https://github.com/mattermost/marked/pull/13)
[Mobile Fix](https://github.com/mattermost/commonmark.js/pull/8)

**Comment by hanzei** [comment]
That was fast, thanks @hahmadia

**Comment by hanzei** [comment]
@hmhealey Should the dependencies to `commonmark.js` and `marked` get updates individually or just with the next general dependency update?

**Comment by hmhealey** [comment]
They should be updated sooner so that we can get this resolved and tested. I think we only do the usual dependency upgrades on libraries that aren't forked.

@hahmadia Would you be able to submit PRs to the web and mobile app repositories to update the versions of each library?

**Comment by hahmadia** [comment]
@hmhealey @hanzei 

Webapp: https://github.com/mattermost/mattermost-webapp/pull/3354
Mobile: https://github.com/mattermost/mattermost-mobile/pull/3070
