### ISSUE TITLE
Create a plugin that adds a sed-style replacement for editing the most recent post

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10772]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15344)

In other chat systems like IRC, users can use a command like to quickly edit the most recent post. For example:

1. Post "Goo evening everyone"
2. Notice you made a spelling error ("Goo" vs "Good")
3. Post "s/Goo/Good"

Desired behaviour:
 - Post from step 1 updates to "Good evening everyone"
 - Ephemeral message returned back to the user from "System" with a post "Your message was updated with `s/Goo/Good`"
 
To create a plugin, use the [sample plugin to get started](https://github.com/mattermost/mattermost-plugin-sample) and refer to the plugin documentation for details, such as [how to register a slash command via the API](https://developers.mattermost.com/extend/plugins/server/reference/#API.RegisterCommand). Our demo plugin also has an example of using a slash command - [see documentation here](https://github.com/mattermost/mattermost-plugin-demo/tree/master/server#command_hooksgo).

**Comment by jasonblais** [comment]
@hanzei please help add any other labels that may be appropriate. This might be a "good first issue" for someone interested in plugins

**Comment by evan1024** [comment]
I'll try to tackle this after setting up the dev environment tonight.

**Comment by jasonblais** [comment]
Great, thank you @evan1024!! 🎉

**Comment by jasonblais** [comment]
Great, thank you @evan1024!! 🎉 

If you have any questions, don't hesitate to let us know :)

**Comment by evan1024** [comment]
Will do!

**Comment by vaibhavsingh97** [comment]
Though I am still learning Golang but I would love to take this.

**Comment by evan1024** [comment]
I've finished a draft of the plugin outlined here [issue-mattermost-server-10772](https://github.com/mattermost/mattermost-server/issues/10772). 
It seems to work well. Here's the repo: https://github.com/evan1024/mattermost-plugin-replace/blob/master/server/plugin.go

I was not able to write meaningful tests, though. Is there a way to mock users and posts in the testing file?

Also, once I'm done, how should I go about submitting the plugin for approval and publishing?

**Comment by jasonblais** [comment]
@evan1024 Great, thank you so much!! 

@hanzei would you have an example of how to mock users and posts in the testing file for meaningful unit tests?

@evan1024 As for submitting the plugin for approval and publishing - that's a good question. The process at the moment is:
1. Create a release for the plugin to https://github.com/evan1024/mattermost-plugin-replace/releases
2. Add a short documentation on how to install the plugin, similar to https://github.com/jespino/mattermost-plugin-draw#installation
3. Submit it to our [Integrations Directory](http://integrations.mattermost.com) for review https://integrations.mattermost.com/submit-an-integration/

We're also working on a more structured integrations review process, feedback welcome :) https://docs.google.com/document/d/1nfGuGadJcEFeyxVNy3ytQcn5RXFVC3Z5SS0jMZHFMg0/edit#heading=h.kp69l76lhnjk

**Comment by carmo-evan** [comment]
@jasonblais I've updated the README file with the installation instructions. I'll wait for @hanzei before I do the other steps, since I want to include the unit tests before I create a release/submit it for review.

**Comment by carmo-evan** [comment]
I was able to figure out mocking by reading the [Matterpoll test code](https://github.com/matterpoll/matterpoll/blob/master/server/plugin/plugin_test.go). I'll create the release and submit it tonight.

**Comment by carmo-evan** [comment]
Submitted https://github.com/carmo-evan/mattermost-plugin-replace.

**Comment by jasonblais** [comment]
Thank you @carmo-evan!! This is great stuff.

I noticed the command is `/s Goo/Good` for the plugin instead of `s/Goo/Good`.  Was this intended?

**Comment by carmo-evan** [comment]
@jasonblais Yes, because having the command tab open every time you started a sentence with the letter "s" would get pretty annoying pretty fast. Another option would be `/s/Goo/Good` which could end up being just unnecessary typing, IMO. I can change that if you'd like me to, though.

**Comment by jasonblais** [comment]
@carmo-evan makes sense.

If the command autocomplete tab wasn't opened upon typing `s`, do you think it would be fine?

The reason why `s/Goo/Good` was proposed originally is that this follows what Hipchat, IRC and other systems use - and I'd be totally okay not opening the autocomplete in this case if it doesn't start with a slash.

**Comment by carmo-evan** [comment]
Let me try that.

**Comment by carmo-evan** [comment]
@jasonblais @hanzei after reviewing the docs and the server code, I don't think there's a way to register a command that does not start with a `/`. Correct me if I'm wrong, but I don't think the usage `s/Goo/Good` is achievable without a change to some server code, besides the plugin code. `/s/ Goo/Good` is the closest thing achievable now without a core change. Please advise.

**Comment by jasonblais** [comment]
Hm, I see, thanks for looking into this. @hanzei curious if you'd have recommendations.

**Comment by carmo-evan** [comment]
@jasonblais talked to @hanzei and I believe it's working as intended now. Please let me know if this is the desired behavior in the video: https://drive.google.com/file/d/1K3Uw40CsRHyi7_Br1IX6rk4XQuiS-Kqx/view

Or in this gif:
![ezgif-1-1ce5d820fbb6](https://user-images.githubusercontent.com/34245571/57619164-4c0a7580-7553-11e9-82e9-92b26a456761.gif)

**Comment by jasonblais** [comment]
That looks fantastic, thank you @carmo-evan! I noticed it posts the `s/lik/like` in the channel as well?

**Comment by carmo-evan** [comment]
Hi!

Not quite. I was able to reject the new post, which causes it to not really
display to other users. It does appear as a "pending" post for the OP, so
I'm working on a way to make it disappear altogether.

**Comment by jasonblais** [comment]
@carmo-evan Great, then that looks exactly as expected for me 👍

**Comment by jasonblais** [comment]
@carmo-evan Let me know if you had any questions about above about the "pending" state, happy to help out

**Comment by carmo-evan** [comment]
@jasonblais thanks. I opened a conversation [here](https://community.mattermost.com/core/pl/pmxpgd9sbjya9dzexc1kuqziir). The general consensus was that there's no real good way to remove that pending status as of right now, and that it's an issue that's common enough that might warrant adding that capability to plugins at some point. @DSchalla, @levb, and @crspeller started a conversation about it but I'm not clear what the conclusion was.

**Comment by jasonblais** [comment]
Thanks for the heads up! I've posted a reply in the thread https://community.mattermost.com/core/pl/mwdht9e3a3b59x8q3dhtb1xajo

**Comment by carmo-evan** [comment]
@jasonblais I guess this can be closed?

**Comment by jasonblais** [comment]
Indeed, thanks! I'll also give v0.2 a quick test 👍
