### ISSUE TITLE
Write an automated test using Cypress for "Whitespace with emojis does not affect size"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10777]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15381)

*Test Key: M15381 - Whitespace with emojis does not affect size*
*Test Group: Messaging*

*Steps:*
1. In the message box, press SHIFT+ENTER to create a newline
2. Paste or type the following as the second line of the message and post:
:book: :key: :gem:
3. Post three spaces followed by the same emoji again and post (can type or copy/paste):
    :book: :key: :gem:

*Expected:*
- In first post, newline does not render and emoji appear jumbo sized
- In second post, three leading spaces appear and emoji appear jumbo sized

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by Jonany** [comment]
Started work on this. Is there a standard way of determining if the emojis are jumbo? The only difference I see is that the jumbo emoji are wrapped in a span with the class "all-emoji".

**Comment by saturninoabril** [comment]
No standard way but verification should be able to differentiate as compared to when emoji is rendered normally (small size, 21x21).  "all-emoji" is a good start but I'll recommend to have an extra check to its dimension of 32x32.

**Comment by Jonany** [comment]
@saturninoabril I did notice the dimensions but I was looking for something more general. A "jumbo" class for example. But if in the absence of that, I'll go with the dimensions. Thanks! :smiley_cat: Could you assign this ticket to me, please?

**Comment by saturninoabril** [comment]
Oh right, "jumbo" class sounds straightforward, though it was not named like that when it was first introduced.  
We can't assign an issue directly to you but commenting on the issue and removing "Up For Grabs" means it's all yours 🎉.

**Comment by Jonany** [comment]
Update: coding is all done. Just giving it a once over before submitting a pull request. I've had some trouble with my Linux install but I hope to submit the pull request either today or tomorrow.
