### ISSUE TITLE
Combining Send messages on CTRL+ENTER with Code block setting

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10789]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12900)

UX to think about how those two settings will be combined.
Conversation: [https://pre-release.mattermost.com/core/pl/4aarykr9ytys9cxtt9kuey4jxr]

======================================================================

Proposed Solution:  Replace existing two settings with one setting and three options within the expanded view of the setting.  

Send messages on CTRL \+ ENTER

- `On for all messages`
- `On only for code blocks starting with ``` `
- `Off`

Help text: `When enabled, CTRL + ENTER will send the message and ENTER inserts a new line.`

In condensed view, the setting will show what option has been selected

**Comment by hanzei** [comment]
@esethna Does this need changes in both mobile and web app?

**Comment by esethna** [comment]
@hanzei only webapp for this ticket

**Comment by carmo-evan** [comment]
I can try doing this one.

**Comment by hanzei** [comment]
Thanks @carmo-evan :tada:
