### ISSUE TITLE
Write an automated test using Cypress for "Focus move from Recent Mentions to main input box when a character key is selected"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10783]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15406)

*Test Key: M15406* - *Focus move from Recent Mentions to main input box when a character key is selected Test*
*Test Group: Messaging*

*Steps:*

1. Click the flag icon to open the flagged posts RHS to move the focus out of the main input box
2. Push a character key such as "A"
3. Click the @ icon to open the Recent mentions RHS to move the focus out of the main input box
4. Push a character key such as "A"

*Expected:*
Anytime you push a character key such as "A" the focus is moved back to the main input and the keystroke is captured

See our end-to-end testing documentation for reference - [https://developers.mattermost.com/contribute/webapp/end-to-end-tests/|https://developers.mattermost.com/contribute/webapp/end-to-end-tests/]

**Comment by a-arias** [comment]
I'm going to work on this one 🔢

**Comment by hanzei** [comment]
Thanks for taking a shot @a-arias :rocket:
