### ISSUE TITLE
Find the channel ID if it is already created

### ISSUE THREAD

**Issue by gothraven** [mattermost/mattermost-server#10782]
#### Summary
This is more like a question than an issue.
Sometimes there is no way for a bot to create a new channel by NAME because it is already created, and no way to get the Channel without fetching all channels list and iterating through most of them to get the channel you want.

#### Steps to reproduce
```python
api_key = 'key...'
client = SlackClient(api_key)
result = client.api_call("channels.create", name='test')
if not result['ok'] and result['error'] == 'name_taken': 
 ... some way to find the channel ID
```

#### Expected behavior

the behavior seems fine, though it would've been better if it would like something like this

```
{'ok': False, 'error': 'name_taken', channel: {...}, 'headers': {...}}
```

#### Observed behavior (that appears unintentional) 
```
{'ok': False, 'error': 'name_taken', 'headers': {...}}
```

#### Possible fixes
I don't know for now

**Comment by amyblais** [comment]
@hanzei / @maruTA-bis5 Does this sound good for me to open a Jira ticket?

**Comment by gothraven** [comment]
Sorry I have no idea why I posted a slack related issue here !
