### ISSUE TITLE
Update to email batching System Console help text

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10786]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-7897)

Change help text for System Console > Notifications > Email > Enable Email Batching to

1) 

{code}
When true, users can have email notifications for multiple direct messages and mentions combined into a single email, configurable in **Account Settings > Notifications**. Email batching in High Availability mode is planned but not yet supported.
{code}

2) *If Site URL NOT set*: 
{code}
When true, users can have email notifications for multiple direct messages and mentions combined into a single email, configurable in **Account Settings > Notifications**. Email batching in High Availability mode is planned but not yet supported.

You must have Site URL configured in **Configuration > Site URL** for email batching to be enabled.
{code}

NOTE: This is more than just a string change, as I propose we don't have custom help text if HA is enabled/disabled (right now there is). 

The text "Email batching in High Availability mode is planned but not yet supported." should always appear, because if an admin switches from TE to EE, they wouldn't be aware that email batching no longer works.

Relevant file: https://github.com/mattermost/platform/blob/master/webapp/components/admin_console/email_settings.jsx

**Comment by Alamin02** [comment]
Hi, I'm interested to work on this.

**Comment by hanzei** [comment]
Sorry for the deplay. Thanks for working on this @Alamin02! :+1:

**Comment by hanzei** [comment]
Hey @Alamin02,

Just want to check how are you doing. Do you have any questions?

**Comment by Alamin02** [comment]
I'm so sorry I got caught up for some personal issues. Sorry for the very late reply. I'll be working on it from today.

**Comment by hanzei** [comment]
Hey @Alamin02, just want to check if you are still working on this

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by kuchcakova** [comment]
Hi, I'd like to take up this issue.

**Comment by hanzei** [comment]
Hi @kuchcakova,

How is your work on this going? Can help help with anything?

**Comment by nodefourtytwo** [comment]
Is there an issue related to "Email batching in High Availability mode is planned but not yet supported"? If so, could someone link it? I'm not able to find it.

**Comment by jasonblais** [comment]
@amyblais would you know if a ticket exists?

**Comment by amyblais** [comment]
@nodefourtytwo Can you help with more details on what bug you're seeing?

**Comment by nodefourtytwo** [comment]
@amyblais Email batching is not available if the High Availability mode is enabled. Apparently it's planned (from the doc: "Email batching in High Availability mode is planned but not yet supported"). Is there a way to follow the status of this feature?

**Comment by amyblais** [comment]
@nodefourtytwo There is an open feature request ticket but it's internal/private. There is another ticket open here that you can follow which is to first resolve a technical blocker for allowing email batching in HA: https://mattermost.atlassian.net/browse/MM-7548.

**Comment by KuSh** [comment]
Hello,

Is this issue still relevent?
It seems the option is not available if `configIsFalse('ServiceSettings', 'SiteURL')` or `it.configIsTrue('ClusterSettings', 'Enable')`

**Comment by DaDummy** [comment]
Seems like this issue is still relevant and was prematurely closed. I just ran into the very issue that site URL was configured, but the option was still greyed out without explanation.
