### ISSUE TITLE
Allow plugins to override ephemeral posts

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10797]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15324)

Mattermost supports plugins that offer powerful features for extending and deeply integrating with both the server and web/desktop apps: https://developers.mattermost.com/extend/plugins/

Currently, plugins can override a regular message posted to a channel using [registerPostTypeComponent](https://developers.mattermost.com/extend/plugins/webapp/reference/#registerPostTypeComponent) - this allows a webapp plugin to render a custom body for posts with a specific type prefixed with 'custom_'.

The proposed change is to make this component work with ephemeral posts as well, which are only visible to the user.

A sample use case is for our [Mattermost GitHub plugin](https://github.com/mattermost/mattermost-plugin-github), where "/github todo" returns an ephemeral message with items to do in GitHub. We would like to replace the resulting message with a custom UI instead of the hard to read Markdown list it is today, as attached below.

![image](https://user-images.githubusercontent.com/13119842/57247898-090a4880-700f-11e9-8074-0dd44f5ffc3e.png)

If you have any questions about the proposed change, ask `jasonblais` or `hanzei` on this GitHub issue, or message them on https://community.mattermost.com.

**Comment by jasonblais** [comment]
@hanzei can you help add the appropriate labels for this ticket?

**Comment by cpoile** [comment]
@jasonblais send this to me, if we want to implement [MM-15411](https://mattermost.atlassian.net/browse/MM-15411) for this sprint. I just ran into this as a blocker.

**Comment by hanzei** [comment]
@jasonblais Done

**Comment by jasonblais** [comment]
+:+1:

**Comment by scottleedavis** [comment]
I'd like to try this one @hanzei @jasonblais :)

**Comment by hanzei** [comment]
Greet! :rocket: Thanks for all your work, Scott!

**Comment by hanzei** [comment]
Hey @scottleedavis,

I'm wondering if you would be interested in submitting a PR to the demo plugin that makes use of this new feature? Would be cool to show this new possibility in the plugin.

**Comment by scottleedavis** [comment]
Sounds great @hanzei , will do.  👍
