### ISSUE TITLE
make test - syntax error near unexpected token `('

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10796]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15231)

#### Error Message 

From in mattermost-server directory:

```
sh: -c: line 0: syntax error near unexpected token `(' 
sh: c: line 0: `tail -n +2 ./cmd/mattermost/commands/cprofile-TestConfigMigrate_Should_work_passing_to_and_no_from_(taking_the_default_config_file)-1.out >> cover.out ; rm "./cmd/mattermost/commands/cprofile-TestConfigMigrate_Should_work_passing_to_and_no_-from_(taking_the_default_config_file)-1.out"'
make: *** [test-server] Error 1
```

#### Reproduce 

Run in the mattermost-server directory.

#### Description of Failure

The error coming at the end of is from the following test found in .  Note the parenthesis in the test name.  This is the cause of the make test error.

```
t.Run("Should work passing --to and no --from (taking the default config file)", func(t *testing.T) {
    assert.NoError(t, th.RunCommand(t, "config", "migrate", "--to", sqlDSN))
})
```

1. produces a file named based on the name of the test.
2. runs the script containing the following command:
    ```
    {{find . -name 'cprofile*.out' -exec sh -c 'tail -n +2 \{} >> cover.out ; rm "\{}"' \\;}}
    ```
3. The unix command returns the filename but does not have escaped parenthesis.
4. The portion of the command fails because it expects the parenthesis escaped.

**Comment by jasonblais** [comment]
@hanzei can you help add the difficulty level for this ticket?

**Comment by hanzei** [comment]
@jasonblais Done

**Comment by carmo-evan** [comment]
I can also take a look into this if [this other issue](https://github.com/mattermost/mattermost-server/issues/10800) is not up for grabs anymore.

**Comment by jasonblais** [comment]
Thanks @carmo-evan! Removed `up for grabs` label, the other issue is indeed taken and has a PR submitted
