### ISSUE TITLE
Rage Emoticon Pattern doesn't get converted into actual emoji

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10807]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14250)

\[Master\]‌\[Community\]‌\[Community-Daily\]‌\[Desktop\]

Typing the Rage emoticon pattern into a post does not get converted into the Rage emoji as expected.

Steps:

# Type {{:@}} or into a post and submit.

Expected: The emoticon pattern would get converted into the Rage emoji

Actual: The {{@}} symbol is highlighted like a mention

The codebase has a regular expression to support this emoticon pattern, but the code for handling mentions is processing it first and so the pattern is never converted into the emoji.

Works as expected on mobile

**Comment by hanzei** [comment]
Thanks for taking a look @seansackowitz! :+1:
