### ISSUE TITLE
Write an automated test using Cypress for "Join/leave messages (including combined): Usernames are links, open profile pop-overs"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10806]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15445)

*Test Key: CS15445 - Join/leave messages (including combined): Usernames are links, open profile popovers*
*Test Group: Channel Settings*

*Steps:*
1. Add a user to a channel
2. On the system message advising a user was added to the channel, click the username link
3. Add three users to another channel
4. On the system message advising users were added to the channel (combined) that includes a link such as "and 2 others", click to expand the usernames, then click each username link

*Expected:*
- In each case, the user's profile pop-over displays when their username is clicked, and the pop-over is fully visible

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by VolatianaYuliana** [comment]
hello! I'd like to take this one :)

**Comment by saturninoabril** [comment]
Sure, thanks @VolatianaYuliana!

**Comment by saturninoabril** [comment]
PR is recently merged.

Thank you @VolatianaYuliana for your contribution!
