### ISSUE TITLE
Accessibility issue - Excel table copy problem

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-server#10802]
#### Summary
If I copy and paste excel sheet, Mattermost 5.10.0 will be converted to markdown format. Previously, images and text were posted together. The markdown format often corrupts the table. Is there a way to selectively use markdown or image?

#### Steps to reproduce
1. Select and copy a specific area in Excel.
2. Paste in the message input box.
3. Send the message.

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/20394843/57271956-631d1380-70cc-11e9-99f6-a5a9dbbf008f.png)

#### Possible fixes
Changing the table to markdown is very useful. However, the table might be damaged, so it would be nice if the user could select it. telegram is a very good example.

![image](https://user-images.githubusercontent.com/20394843/57272039-c0b16000-70cc-11e9-8008-f00a158b691f.png)

**Comment by amyblais** [comment]
Thank you @Gloriashield, opened a ticket here: https://mattermost.atlassian.net/browse/MM-15458.

**Comment by amyblais** [comment]
Letting you know that the Jira ticket was closed as won't fix since the behaviour you described also matches Github's behaviour.
