### ISSUE TITLE
Support converting bot accounts to user accounts with email/password login through the CLI

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10800]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15441)

Following this PR https://github.com/mattermost/mattermost-server/pull/10672, you can convert a user account to a bot through the CLI with

```
mattermost user convert [emails, usernames, userIds] --bot
```

This ticket is to add the opposite of that, which is to convert a user account into a bot

```
mattermost user convert botusername —-user --email new.email@email.com --password password
```

When converting a bot to a user, the same options should be supported as when creating a user: https://docs.mattermost.com/administration/command-line-tools.html#mattermost-user-create.

**Comment by carmo-evan** [comment]
I'd like to take a stab at this if it's still up for grabs.
