### ISSUE TITLE
Replace cp -r with cp -R in Makefiles on server, webapp, mobile

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10816]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15496)

See: https://unix.stackexchange.com/questions/18712/difference-between-cp-r-and-cp-r-copy-command for justification for this change. `cp -r` is not portable while `cp -R` is.

**Comment by JerryFireman** [comment]
I took a look at the three makefiles but I could not find any instances of cp -r that needed to be replaced. Please let me know I am missing something. If so, I would be happy to address.

**Comment by jasonblais** [comment]
@crspeller would you be open to helping with the above question?

> I took a look at the three makefiles but I could not find any instances of cp -r that needed to be replaced. Please let me know I am missing something. If so, I would be happy to address.

**Comment by crspeller** [comment]
@JerryFireman Looks like your right. That's what I get for making a ticket without checking myself!
