### ISSUE TITLE
System Console lists deleted users on first load, team admins as members

### ISSUE THREAD

**Issue by torgeirl** [mattermost/mattermost-server#10814]
#### Summary
- `System Console` > `Users` wrongfully lists former members of a team on first load. After a reload of the page the removed users are no longer listed.
- `Team Admins` are listed as `Member` in the same view.

#### Steps to reproduce - (A) deleted users listed as member
1. Delete an user from a team.
2. Go to `System Console` > `Users` and filter for that team.
3. Notice the deleted member is listed as a member, and that the number of members in the left-hand corner count that member.
4. Refresh (Ctrl+R) the page and notice how the member disappears and the count adjusts.

#### Steps to reproduce - (B) team admin listed as (regular) member
1. Promote a team member to team admin. 
2. Go to `System Console` > `Users` and filter for that team.
3. Notice the newly deputized team admin is listed as a regular member.
4. Click `Member v` for the deputized team member, select `Manage Teams` and notice how that lists the user correctly.

Currently using `4.10.9 ESR` (update to `5.9 ESR` scheduled later this Month).

#### Expected behavior
- The deleted member shouldn't the listed on the first time the page loads.
- A team admin should be listed as `Team Admin`, not `Member`.

#### Observed behavior (that appears unintentional)
In the screenshot below, the two instances of `Member` are actually team admins while the `System Admin` have deleted themselves from the team. When refreshed, the member count drops to two and the removed System Admin is (correctly) now longer listed as a member.

![Screenshot from 2019-05-09 16-37-38](https://user-images.githubusercontent.com/796053/57463569-52f76680-727b-11e9-936f-2279d70844a6.png)

#### Possible fixes
- n/a

**Comment by amyblais** [comment]
Hi @torgeirl, thank you for the reports.

**(A) deleted users listed as member**
I wasn't able to reproduce the first issue either on v5.8 or v5.11 RC, so it has probably been fixed on a recent release. When you upgrade to v5.9, would you be able to re-test it and let us know if you can still reproduce it?

**(B) team admin listed as (regular) member**
The second report looks like a feature request since currently we only have either Member or System Admin in the System Console. I can ask our PMs whether this behaviour is something we're planning to change in the future or whether I should open a feature request issue for this.

**Comment by torgeirl** [comment]
> When you upgrade to v5.9, would you be able to re-test it and let us know if you can still reproduce it?

@amyblais: will do!

**Comment by amyblais** [comment]
Hi @torgeirl,

One of our PMs said that we are looking at adding additional reporting for teams in the system Console, which would allow system admins to see the team admin. We are currently working on designs but I'm not able to say when it will be ready.

**Comment by torgeirl** [comment]
> > When you upgrade to v5.9, would you be able to re-test it and let us know if you can still reproduce it?
> 
> @amyblais: will do!

I'm unable to reproduce the issue in v5.9.
