### ISSUE TITLE
Emojis overlap when rendered in messages 

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-server#10825]
#### Summary
Emojis overlap when rendered in messages 

#### Steps to reproduce
Paste the below into a message: 
😈🤣👘😘🥳🥳😋🥳😋🥳😛🤨😎😏😛🤓😋😖🤨😫😫😚😒😋☹️🤨🥳😒😒🤪😖😋😒😋🤨😏😩🤨😀🤨😇🧐🙃🤨🙃😟😛😔🧐☹️🤬😱😳🤫🤫😥😳🤔😨🤗😢😑🤢🤢🤢🤮🤮😪😑😑🤔😴🤭😵😑😷🤐🤐👙👨‍👧‍👧👨‍👨‍👧‍👦👚👩‍👦‍👦👔👩‍👧‍👦👠👩‍👦‍👦👨‍👦‍👦🥼

#### Expected behavior
Emojis render without overlapping 

Discord as an example: 
![image](https://user-images.githubusercontent.com/177788/57570516-b686ae80-73b7-11e9-9ba0-7ae6a4de48c0.png)

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

Emojis overlap: 
![image](https://user-images.githubusercontent.com/177788/57570495-82ab8900-73b7-11e9-897b-e31cefee197d.png)

#### Possible fixes
Propose a Help Wanted ticket for this, maybe just some CSS to adjust and size? 

This could be an interesting starter project to appeal to someone interested in making a difference to the look and feel of the product--without getting carried away...

**Comment by amyblais** [comment]
Thank you @it33, opened a bug ticket here: https://mattermost.atlassian.net/browse/MM-15551.

**Comment by amyblais** [comment]
Closing this issue as this bug has been fixed for upcoming v5.13 quality release,
