### ISSUE TITLE
Mobile app (iOS + Android): Filtered list not showing bot account icon

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10821]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15442)

The channel drawer shows an regular DM icon instead of the bot icon for bot accounts when filtering the channel drawer.

* Open the channel drawer
* Filter the list to show a bot account

Observed: isBot property is undefined and a regular DM icon is shown
Expected: isBot property is not null and bot icon is shown for bot accounts.

Notes:
1. To create a bot account, you can go to Main Menu > Integrations > Bot Accounts > Add Bot Account.
2. Changes are required in mattermost-mobile repository.

**Comment by scottleedavis** [comment]
Hey!  Interested in this one. :)
