### ISSUE TITLE
URI doesn't work anymore

### ISSUE THREAD

**Issue by ppodevin** [mattermost/mattermost-server#10834]
#### Summary
URI like spotify:track:XXXX does not work on mattermost 5.9.0 (not tested on other 5.X)

#### Steps to reproduce
Send an URI to a channel, it wont be colored as a link (therefore not being clickable).
![image](https://user-images.githubusercontent.com/12099945/57620519-4af43b00-7589-11e9-832b-8f69faa1a883.png)
Worked well on mattermost 4.X (tested on 4.9)

#### Expected behavior
same as http://link.to with expected application
![image](https://user-images.githubusercontent.com/12099945/57620538-58a9c080-7589-11e9-8c71-e1d1cdd69ea0.png)

**Comment by amyblais** [comment]
Hi @ppodevin, do you know if there are other types of URL that don't work?

**Comment by ppodevin** [comment]
I know that http:// and ftp:// work, but I don't use any other type of URL,
as far as I can test, only http and ftp protocoles seams to be reconized as
URL.

**Comment by ppodevin** [comment]
Here is an other example :
![image](https://user-images.githubusercontent.com/12099945/57762990-d7753980-7700-11e9-9359-aa38baf72ef9.png)

Working on 4.9 like expected :
![image](https://user-images.githubusercontent.com/12099945/57763139-1c00d500-7701-11e9-8b15-d43af812eb4d.png)

**Comment by amyblais** [comment]
Opened a bug ticket here: https://mattermost.atlassian.net/browse/MM-15600.

**Comment by amyblais** [comment]
Hi @ppodevin, I checked with our team about this and they said there is a setting here that you might need to set for those links to work: https://docs.mattermost.com/administration/config-settings.html#custom-url-schemes.

**Comment by ze0** [comment]
@amyblais 
I'm in the same team as @ppodevin, I confirm that with the documentation you have linked everything works perfectly well (spotify/steam/git).
The ticket can be closed.
Thank you.

**Comment by amyblais** [comment]
Glad to hear it!
