### ISSUE TITLE
UpdateEphemeralPost doesn’t update more than once

### ISSUE THREAD

**Issue by scottleedavis** [mattermost/mattermost-server#10832]
#### Summary
UpdateEphemeralPost does not update the post a second time.

#### Steps to reproduce
Call UpdateEphemeralPost on the same post a second time.

#### Expected Behavior 
UpdateEphemeralPost can update a post any number of times.

#### Observed behavior (that appears unintentional) 
An api error occurs on the second call.

**Comment by amyblais** [comment]
Hi @scottleedavis, 

What API error do you see when you encounter this issue?

**Comment by scottleedavis** [comment]
Hey @amyblais ,

When trying to replicate the api error, it appears it was an error in my own code for testing.  My apologies.
