### ISSUE TITLE
Add KVCompareAndSetWithExpiry to plugin API

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10850]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15590)

We have KVCompareAndSet and KVSetWithExpiry. 

What would be useful in some situations is a KVCompareAndSetWithExpiry combining their functionality.

**Comment by gupsho** [comment]
I can take this.

**Comment by hanzei** [comment]
Thanks for taking care of this, @gupsho!

**Comment by hanzei** [comment]
Closing this as https://mattermost.atlassian.net/browse/MM-16822 is a better approach to tackle this.
