### ISSUE TITLE
Update text for warning dialog when a System Admin deactivates a user who has created at least one bot account.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10863]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15655)

**Current behaviour**:

If  a) ServiceSettings.DisableBotsWhenOwnerIsDeactivated is set to "true", and b) if a user creates bot accounts but is subsequently deactivated, then their bot accounts are disabled as well. However, the System Admin is not aware of this upon deactivation.

**Proposed behaviour**: 

(Note: Only applies when ServiceSettings.DisableBotsWhenOwnerIsDeactivated is set to "true")

1 - Update text for warning dialog when a System Admin deactivates a user who has created at least one bot account.

Current text:
 
![image](https://user-images.githubusercontent.com/13119842/57976854-72e40400-79b8-11e9-8396-afd0cc0a5499.png)

Proposed text:

```
This action deactivates \{user\}.

* They will be logged out and not have access to any teams or channels on this system.
* Bot accounts they manage will be disabled along with their integrations. To enable them again, go to Integrations > Bot Accounts. Learn more about bot accounts.

Are you sure you want to deactivate \{user\}?
```

where "Learn more about bot accounts" links to https://mattermost.com/pl/default-bot-accounts

**Comment by pradeepmurugesan** [comment]
I can wok on this 👍

**Comment by pradeepmurugesan** [comment]
@jasonblais the given link is throwing a 404 https://mattermost.com/pl/default-bot-accounts

**Comment by jasonblais** [comment]
Hey @pradeepmurugesan! That's "expected" for now - I'm working on documentation for bot accounts - once finished, we'll add a redirect from https://mattermost.com/pl/default-bot-accounts to that doc page.

This will happen before the 5.12 release date on June 16th.

Thanks for picking up this ticket!

**Comment by jasonblais** [comment]
Hey @pradeepmurugesan, let me know if you have any questions about this ticket?

**Comment by pradeepmurugesan** [comment]
@jasonblais  Thanks for checking.. Just saw the message.. A PR is already up for the task. Kindly review
