### ISSUE TITLE
Regression: Bot tag missing for bots in channel switcher (CMD/CTRL+K)

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10865]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15586)

1. Download the latest version of the remind plugin from https://github.com/scottleedavis/mattermost-plugin-remind/releases
2. Upload it via System Console > Plugins
3. Go back to a Mattermost channel, hit CMD/CTRL+K to open the channel switcher, then type "remind"

Observed: No bot tag appears next to the bot's name

Expected: Bot tag appears to the right of the bot name
![image](https://user-images.githubusercontent.com/13119842/57933697-f227e980-788b-11e9-8ae2-1363aab8f59c.png)

**Comment by scottleedavis** [comment]
I am interested in working on this one.
