### ISSUE TITLE
Access History is a GDPR violation

### ISSUE THREAD

**Issue by streaps** [mattermost/mattermost-server#10877]
#### Summary
I believe the excessive logging of IP addresses without the user's consent is a GDPR violation. IP addresses are personal data.

#### Steps to reproduce
IP addresses can be viewed in "Access History". I'm not sure for how long they are kept, but on my server it is for over 30 days (since the first login of the user).

Server: Mattermost 5.10 Team

#### Possible fixes
* Disable logging of IP addresses by default
* Add a global config option to set the number of days the IP addresses are stored
* Ask user for explicit consent and/or add a configuration option per user account

**Comment by amyblais** [comment]
Hi @streaps, thank you for the report. I will ask our team to take a look at this,

**Comment by wiersgallak** [comment]
We have reviewed your request and per article [49 of the GDPR](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679&from=EN), this falls under the extent of processing personal data for the purpose of ensuring network and information security. Moreover:

- You can control access to the logs via restricted access to the System Console and the server.
- As a self-hosted software, you have full control and ownership of the logs, with the ability to set up a purge schedule to meet your needs.
 - You can use a reverse proxy to provide obfuscation to IP addresses.

**Comment by amyblais** [comment]
Hi @streaps, I'll close this issue for now as there hasn't been feedback on this for a while. Please comment below or re-open this issue if you have any further questions on this.

Thank you for the report,
