### ISSUE TITLE
Allow plugins to dismiss posts through the MessageWillBePosted hook

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10883]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15694)

Allow plugins to dismiss posts through the `MessageWillBePosted` hook. The `mattermost-server/plugin` package should define and export a new, const error to be used when a post should be dismissed.

For additional context, see https://community.mattermost.com/core/pl/mwdht9e3a3b59x8q3dhtb1xajo

**Comment by jasonblais** [comment]
@carmo-evan here's the help wanted ticket for the changes we discussed couple of days ago

**Comment by lieut-data** [comment]
Posting this here for extra context:
> I like the semantics of wanting to dismiss a post, but I wonder if we could just reserve and export an error code to mean dismiss in this case instead of having to create an "invalid" post as such.

**Comment by carmo-evan** [comment]
@jasonblais thanks! I'll work on it.

**Comment by carmo-evan** [comment]
After talking to @lieut-data , it was decided we'd signal the dismissal by passing in a custom error message that could be added to this if statement:
https://github.com/mattermost/mattermost-redux/blob/master/src/actions/posts.js#L237-L238

However, in testing I noticed that this action is not quite working:
https://github.com/mattermost/mattermost-redux/blob/master/src/actions/posts.js#L240

My theory is that it doesn't work because it returns a function, and not an action:
https://github.com/mattermost/mattermost-redux/blob/master/src/actions/posts.js#L907

If I substitute it for this function, it works just fine:
https://github.com/mattermost/mattermost-redux/blob/master/src/actions/posts.js#L122

I'd like to know from some redux-savvy people if this makes sense @jwilander @hmhealey

**Comment by jwilander** [comment]
@carmo-evan we use [redux-thunk](https://github.com/reduxjs/redux-thunk) as a middleware to allow returning functions as actions. That should work fine. Do you have a link to your changes? I can better help explain what might be happening if I can see those

**Comment by carmo-evan** [comment]
My change is pretty minor. It'd be just adding a new error id to that if statement, as follows:

```                   
if (error.server_error_id === 'api.post.create_post.root_id.app_error' ||
    error.server_error_id === 'plugin.message_will_be_posted.dismiss_post' ||
    error.server_error_id === 'api.post.create_post.town_square_read_only'
) {
        actions.push(postRemoved(data));
    } else {
        actions.push(receivedPost(data));
}```

**Comment by carmo-evan** [comment]
This is the behavior I'm experiencing with `removePost()`, which is the current version of the code.
![ezgif-1-f8bb7b6d6fca](https://user-images.githubusercontent.com/34245571/58256452-09a81c00-7d3d-11e9-9c31-1a861b30910d.gif)



And this is what happens with `postRemoved()` instead.
![ezgif-1-0961ed53c178](https://user-images.githubusercontent.com/34245571/58256552-365c3380-7d3d-11e9-8351-308276fecafc.gif)

**Comment by carmo-evan** [comment]
@hanzei @lieut-data can you review my comments above please? We'll need to merge a redux change together with the server changes in https://github.com/mattermost/mattermost-server/pull/10921

**Comment by lieut-data** [comment]
@lieut-data, can you setup the https://github.com/reduxjs/redux-devtools and watch the sequence of actions (noting that some of them might be batched)? Time-travel can come in handy here to narrow down just what is happening.

**Comment by carmo-evan** [comment]
Will do it tonight.

**Comment by carmo-evan** [comment]
@lieut-data it looks like an issue of incompatibility of redux-batch-actions and thunks
https://github.com/tshelburne/redux-batched-actions/issues/3

**Comment by carmo-evan** [comment]
Implementing this polyfill suggestion fixes the issue.

**Comment by lieut-data** [comment]
Great investigation -- that makes a lot of sense. The polyfill seems reasonable, though I find some of this state flow unnecessarily complex and wonder "if there's a better way." Suggest pinging @hmhealey for feedback when you have a PR for review.

**Comment by carmo-evan** [comment]
Here's a draft https://github.com/mattermost/mattermost-redux/pull/840/files
