### ISSUE TITLE
Visible SMTP Server Password in System Console

### ISSUE THREAD

**Issue by tumbl3w33d** [mattermost/mattermost-server#10909]
#### Summary
SMTP Server Password visible in system console. It's not a big deal, but good practice is to now show entered passwords. At least I cannot think of any other application that does that.

#### Steps to reproduce
Enter your password into the form field.

#### Expected behavior
The password cannot be read by someone standing next to me (i.e., it's a password type input field)

#### Observed behavior (that appears unintentional) 
Password is visible in clear.

#### Possible fixes
N/A

#### Environment
Mattermost Version: 5.11.0
Firefox 60.6.3esr (64-bit)

**Comment by amyblais** [comment]
Thank you @tumbl3w33d, I opened a bug ticket for this here: https://mattermost.atlassian.net/browse/MM-15734.

**Comment by amyblais** [comment]
Hi @tumbl3w33d, letting you know that the Jira ticket was closed because this is actually a feature request. Would you be open to sharing this idea in our feature request forum here: https://mattermost.uservoice.com/forums/306457-general?

**Comment by tumbl3w33d** [comment]
Hiding secrets from prying eyes is a feature for you? ó_Ò

I know - "don't kill the messenger". I will create a feature request for it.
