### ISSUE TITLE
Allow plugins trigger interactive dialogs even without clicking an interactive button/menu or using a slash command

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10900]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15340)

Currently, the [OpenDialogRequest](https://github.com/mattermost/mattermost-server/blob/master/model/integration_action.go#L193) to trigger an [interactive dialog](https://docs.mattermost.com/developer/interactive-dialogs.html) requires a TriggerId, which is generated when the dialog is opened via an interactive button, menu or a slash command.

When a plugin triggers an interactive dialog outside of these three user actions, the TriggerId does not get generated and as a result, the dialog doesn't open.

This prevents certain use cases for plugins, such as when a user triggers a dialog via Main Menu item [described here](https://forum.mattermost.org/t/interactive-dialog-in-plugin/7115).

Proposed change: Allow plugins to trigger interactive dialogs even when the TriggerId is empty.

**Comment by scottleedavis** [comment]
If/when this is up for grabs I'd be interested.  (unless this is for someone else, that is ok.  :)

**Comment by hanzei** [comment]
Surely, go ahead @scottleedavis. Glad, you are looking into this!
