### ISSUE TITLE
Add a "/crash" command for demo plugin

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10901]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15584)

Add a "/crash" command for [demo plugin](https://github.com/mattermost/mattermost-plugin-demo). When used, the Demo Plugin crashes.

The intent is to use this command to effectively test auto-restarting plugins upon crashing, MM-13507

**Comment by scottleedavis** [comment]
If/when this is up for grabs I'd be interested.  (unless this is for someone else, that is ok.  :)

**Comment by jasonblais** [comment]
@scottleedavis It's available, I'll let you grab it :)
