### ISSUE TITLE
Add a separate post type for /me messages and update formatting

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10902]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-2954)

Community Report: https://github.com/mattermost/platform/issues/3987

System message formatting was updated, but formatting for /me was not updated to match. 

1. Create a new post type constant for /me posts (model/post.go)
2. Modify the /me command to create a post with that type without the asterisks in the post message (app/command_me.go)
3. Have the mobile and web apps render the message with the same formatting as system messages (components/post_markdown/system_message_helpers.jsx in the web app and app/components/post_body/post_body.js in the mobile app)

**Comment by mounicapaladugu** [comment]
Is this up for grabs? The Difficulty is hard for this one, but I can probably break in down and start working

**Comment by hanzei** [comment]
Hey @mounicapaladugu,

Yes, this is up for grabs. I just forgot to add the label. If you keep comfortable trying this ticket, do ahead! :+1:

**Comment by Dak425** [comment]
Mind if I have a crack at this myself?

**Comment by mounicapaladugu** [comment]
sure. I haven't started working on this yet.

**Comment by Dak425** [comment]
@hanzei One question I have, since this is my first time attempting to contribute to this project.

For step three which involves formatting the message to be formatted the same as system messages, "the message" is referring to the response received by the clients from the server upon a successful creation of a /me message, is that correct?

**Comment by hanzei** [comment]
That is correct @Dak425 :+1:

**Comment by hmhealey** [comment]
Web and server changes for this are in. Mobile changes are still a work in progress. These changes should be backwards compatible as well, so `/me` messages should look the same as they did before on mobile in the mean time

**Comment by jasonblais** [comment]
Thanks @Dak425 for the contribution!
