### ISSUE TITLE
Timezone suggestion box could not scrolling.

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-server#10916]
#### Summary
If you click on the suggestion box scroll bar of the Timezone, the suggestion box will close.
Version: 5.11.0 / 5.10.0

#### Steps to reproduce
1. Do not check the automatic Timezone setting.
2. Click the input box.
3. Click the scroll bar of suggestion box.
4. The suggestion box will close.

#### Expected behavior
See above, please.

#### Observed behavior (that appears unintentional) 
![TimeZone](https://user-images.githubusercontent.com/20394843/58218951-f3518e80-7d43-11e9-9bff-9204ceea97a9.gif)

#### Possible fixes
You should be able to move to desired location using the scroll bar.  (This is a common use case.)

**Comment by amyblais** [comment]
Thank you @Gloriashield, we have a ticket open for this here: https://mattermost.atlassian.net/browse/MM-15459.

**Comment by amyblais** [comment]
Closing this for now as this bug has been fixed for an upcoming v5.12 release,
