### ISSUE TITLE
Linking channels doesn't work right after an opening parenthesis

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-server#10913]
#### Summary
Linking channels doesn't work right inside `(...)`

#### Steps to reproduce
Write `(~somechannel is broken)` with `somechannel` being a valid channel name

#### Expected behavior
`~somechannel` linking to the channel.

#### Observed behavior (that appears unintentional) 
It remains plaintext

#### Possible fixes
Fix the boundary check to determine what's part of the channel name; probably it's a regex that doesn't consider `(` a valid boundary where a `~link` can start.

Example message showing the bug: https://community.mattermost.com/core/pl/sw8midapp3gutkn1tbg7r93ieh

**Comment by amyblais** [comment]
Thank you @ThiefMaster, bug ticket here: https://mattermost.atlassian.net/browse/MM-15749.

**Comment by amyblais** [comment]
This has been fixed for upcoming v5.13 release,
