### ISSUE TITLE
Always return JSON in /oauth/access_token

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-server#10924]
Currently in case of an error such as an invalid authorization code, this endpoint returns HTML with a 500 status code.

This should be a 4xx status code and also JSON (since that's what's sent in case of success) - currently an oauth client using it needs to check for errors first because of course the HTML that is returned by that endpoint is not valid JSON...

**Comment by amyblais** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-15835.
