### ISSUE TITLE
redirect_to information not used after gitlab login, breaking oauth provider flow when not logged in yet

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-server#10943]
When logging in through gitlab (or any other oauth provider), the redirect_to param pointing to the URL to go to after successfully logging in is lost. It's included in the base64-encoded oauth state in `GetOAuthLoginEndpoint`, but never used after completing the oauth login flow. `CompleteOAuth` still receives the state props, but the `redirect_to` value is never used!

---

While this is just a minor annoyance for normal links to mattermost (deep links don't work because of it unless you are already logged in), it breaks things when using Mattermost's OAuth *provider*:

Imagine I go to Awesome App X ("X") which uses Mattermost's OAuth provider to log in.
So I'm redirect to Mattermost during X's oauth flow and presented with its login page. All fine so far. I click on the "GitLab" login button and complete the login. But now, instead of getting the oauth consent screen (or being redirected to the app if already authorized), I end up in mattermost itself. The **only** way to recover here is to manually go back to X and start its oauth flow again (which will now succeed since I'm already logged-in in Mattermost)

**Comment by amyblais** [comment]
Ticket for reference: https://mattermost.atlassian.net/browse/MM-15836.
