### ISSUE TITLE
Add progressive backoff for Ensure* plugin helper methods.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10958]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15267)

See https://github.com/mattermost/mattermost-server/pull/10542#discussion_r277337785 for original request.

The proposal is to add a progressive backoff, which is immediately, after 128ms, 256ms, up to three times, instead of waiting the current second.

We should make this into a function that can be used in all kinds of Ensure* plugin helper methods.

**Comment by liusy182** [comment]
Will be working on this

**Comment by mounicapaladugu** [comment]
are you working on this issue? if not, can i grab this one?

**Comment by liusy182** [comment]
please go ahead @mounicapaladugu thanks!

**Comment by crspeller** [comment]
@mounicapaladugu Let me know if you have any questions.

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by jesperhansen17** [comment]
Can I give this one a try?

**Comment by hanzei** [comment]
Sure. Thanks @jesperhansen17 :+1:

**Comment by mjthomp95** [comment]
I'd like to work on this.

**Comment by jesperhansen17** [comment]
Hi @jespino, I'm almost ready to open a PR for this issue. Is there any docs/logs for these kind of updates that also needs an update?

**Comment by hanzei** [comment]
You can add a short note to `EnsureBot` but other then that no doc updates are neeeded.
