### ISSUE TITLE
Add "Enabled" next to "post:all" and "post:channels" checkboxes in Bot Account creation and edit screens

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10959]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15329)

Repro steps #1:

1. Go to System Console > Integrations > Features, set "Enable Bot Account Creation" to "true"
2. Go to Main Menu > Integrations > Bot Accounts
3. Click "Add Bot Account"

Repro steps #2:

1. Go to System Console > Integrations > Features, set "Enable Bot Account Creation" to "true"
2. Go to Main Menu > Integrations > Bot Accounts
3. For an existing bot account, click "Edit"

Observed: On the page, there are two checkboxes with no text beside it. This is inconsistent with other setting screens such as that in Account Settings

 !image-2019-04-29-09-51-17-775.png|thumbnail! 

Proposed change: Add "Enabled" next to "post:all" and "post:channels" checkboxes in Bot Account creation and edit screens

 !image-2019-04-29-09-42-45-037.png|thumbnail!

**Comment by bolariin** [comment]
I would like to resolve this
