### ISSUE TITLE
Scrolling not working on iOS signup

### ISSUE THREAD

**Issue by manuelfischer** [mattermost/mattermost-server#11004]
#### Summary
Can not scroll sign-up page on iOS (Safari & Chrome) in portrait view. This prevents users from registering with a shared invite url.

#### Steps to reproduce
On any mattermost server, go to signup page (e.g. https://community.mattermost.com/signup_email) with an iPhone, try to scroll page

#### Expected behavior
Scrolling should work

#### Observed behavior (that appears unintentional) 
Scrolling does not work at all. Switching to landscape mode, scrolling works at the outer left / right borders.

**Comment by amyblais** [comment]
Hi @manuelfischer, thank you, I opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-15935.

**Comment by amyblais** [comment]
Closing this for now as a fix for this has been submitted for the upcoming 5.12 release,
