### ISSUE TITLE
"status_code":500 received when attempting to retrieve SAML metadata via API

### ISSUE THREAD

**Issue by admin-cdn1cloud** [mattermost/mattermost-server#11016]
#### Summary
https://site.example.com/api/v4/saml/metadata returns "status_code":500 when service provider private key and public certificate are not present.

#### Steps to reproduce
Mattermost Version: 5.11.0
Database Schema Version: 5.11.0
Database: postgres

1. Configure SAML 2.0 settings
1a. Leave "Enable Encryption" option to false
1b. DO NOT provide key or cert files

Browse to https://site.example.com/api/v4/saml/metadata

#### Expected behavior
Some SAML service providers do not have the option for encrypting SAML assertions. There is no reason to upload certificates that won't be used. You should be able to disable SAML assertion encryption and still perform SAML functions.

#### Observed behavior (that appears unintentional) 
The following error is given:
`{"id":"api.admin.saml.metadata.app_error","message":"An error occurred while building Service Provider Metadata.","detailed_error":"","request_id":"gta1gmdz5tngdpnakwq1qfypxe","status_code":500}`

Once a private key and certificate are uploaded, you are able to retrieve the server's metadata. Even with "Enable Encryption" set to false.

#### Possible fixes
I didn't look through the code, but I am assuming there is a requirement that fields must be populated before the metadata file is generated. I believe these two fields, private key and public cert should not be required in order to generate the metadata file.

**Comment by amyblais** [comment]
Hi @admin-cdn1cloud, I asked our team about this and they said this is currently working as expected. Do you have any further questions regarding this?

**Comment by admin-cdn1cloud** [comment]
While I disagree with the developers assessment of this working as designed, is there any way to make it more obvious to the end user that certificates are **required** even when you don't use them? 

Ideally don't give the user the option within the UI to not upload them. Change the UI to force the user to upload certificates if that is the desired state. I spent 3 hours troubleshooting this issue not knowing it was the developers intention to **require** certificates but the UI doesn't tell me it's required.

**Comment by amyblais** [comment]
Hi @admin-cdn1cloud, thank you for your feedback. I opened a ticket for our UX team to take look at your feedback: https://mattermost.atlassian.net/browse/MM-15998.

**Comment by amyblais** [comment]
This was implemented in 5.18 release,
