### ISSUE TITLE
`/api/v4/saml/certificate/status` returns wrong statuses

### ISSUE THREAD

**Issue by maruTA-bis5** [mattermost/mattermost-server#11030]
#### Summary
`/api/v4/saml/certificate/status` returns wrong statuses in server v5.10.1 and v5.11.0.

#### Steps to reproduce
1. Start new Mattermost server instance using docker (mattermost/mattermost-preview).
2. Set "Enable Personal Access Token" to `true` and create system admin's token.
3. Request certificate status using curl: `curl -i -H 'Authorization: Bearer <token>' http://<hostname>/api/v4/saml/certificate/status`

#### Expected behavior
`idp_certificate_file`, `private_key_file`, and `public_certificate_file` are `false` because these files are not uploaded.
The server v5.9.1 was this behavior.
```
$ curl -i -H 'Authorization: Bearer arjxceeyhpgriff8hrzu7cqdrh' http://192.168.99.100:8065/api/v4/saml/certificate/status
HTTP/1.1 200 OK
Content-Type: application/json
Expires: 0
X-Request-Id: fkkt8soqi7fjtq88yjq8ectgsw
X-Version-Id: 5.9.0.5.9.1.b3aa4caac113c9554cf7f3da2236ebed.false
Date: Sun, 02 Jun 2019 09:14:10 GMT
Content-Length: 87

{"idp_certificate_file":false,"private_key_file":false,"public_certificate_file":false}
```

#### Observed behavior (that appears unintentional) 
`idp_certificate_file`, `private_key_file`, and `public_certificate_file` are `true` even if not uploaded certificate files.
```
$ curl -i -H 'Authorization: Bearer jjgw49admig7ugkq3td91aknby' http://192.168.99.100:8065/api/v4/saml/certificate/status
HTTP/1.1 200 OK
Content-Type: application/json
Expires: 0
X-Request-Id: x5hg7n8sybde3eff1iubwt1eqa
X-Version-Id: 5.11.0.5.11.0.446edef4c4c6ad05b16e73a589c45f5d.false
Date: Sun, 02 Jun 2019 09:24:50 GMT
Content-Length: 84

{"idp_certificate_file":true,"private_key_file":true,"public_certificate_file":true}
```

**Comment by amyblais** [comment]
Thank you @maruTA-bis5, I'll ask our team about this.

**Comment by lieut-data** [comment]
@amyblais, @maruTA-bis5: I can confirm this bug. If the configured SAML values are empty strings, the code incorrectly checks the existence of the parent folder instead.

**Comment by amyblais** [comment]
Ticket for reference: https://mattermost.atlassian.net/browse/MM-16064.
