### ISSUE TITLE
When a plugin registers a component in the team sidebar, display team sidebar even if user only belongs to one team

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11055]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15666)

*CONTEXT*

A plugin can register a bottom team sidebar component displaying a plugin icon, documented here: https://developers.mattermost.com/extend/plugins/webapp/reference/#registerBottomTeamSidebarComponent

An example is also attached below:

![image](https://user-images.githubusercontent.com/13119842/58901970-3dd1f400-86d0-11e9-8e39-30c3be5e4af3.png)

Currently, the component is not rendered if the user is only on one team and the team sidebar is not shown.

*PROPOSED CHANGE*

Render registerBottomTeamSidebarComponent even if the user belongs to just one team. In such a case, we would display the team sidebar with: 

a) Single team icon for the team you belong to, along with a "+" icon to create or join other teams if the user has permissions to do so. These are rendered at the top of the team sidebar.

![image](https://user-images.githubusercontent.com/13119842/58902006-4cb8a680-86d0-11e9-9f97-c1a309522a84.png)

b) Registered plugin component at the bottom of the team sidebar

**Comment by jasonblais** [comment]
@hanzei Please help add difficulty level when you have a moment, thanks!

**Comment by lieut-data** [comment]
The difficulty with this ticket is that the GitHub plugin renders a left sidebar header component depending on the number of active teams. It doesn’t make sense to force open the team sidebar when plugins /could/ be a bit more intelligent. It might make sense to streamline this for plugins, but I’m no longer convinced it makes sense to assume the team sidebar should be shown.

**Comment by Vaelor** [comment]
@lieut-data What exactly does 'more intelligent' plugins mean in this context?
I'm currently trying the mattermost-gitlab-plugin and I'm missing all the sidebar buttons with the counters. What would be an alternative to the view in the sidebar? The top part of the sidebar?

**Comment by Vaelor** [comment]
@lieut-data Thanks for the clarification! Wasn't sure if that was what you meant :-)
