### ISSUE TITLE
Remove the hard-coded post menu divider from Jira, and add it in the webapp for all plugins

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11054]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15943)

Remove the hard-coded post menu divider from Jira, and add it in the webapp for all plugins.

Then, anytime a new plugin item get added, the divider automatically gets added as well. See an example of the divider for the Jira plugin

![image](https://user-images.githubusercontent.com/13119842/58898409-81c0fb00-86c8-11e9-974b-a9afbaea98ff.png)

Note that the css was already added to the webapp with https://github.com/mattermost/mattermost-webapp/pull/2821

Hence, the only change is to
1) take the HTML from the Jira plugin [here|https://github.com/mattermost/mattermost-plugin-jira/blob/jira2/webapp/src/components/post_menu_actions/create_issue/create_issue.jsx]

```
                <li
                    className='MenuItem__divider'
                    role='menuitem'
                />
```

2) and add it into the webapp with the proper markup logic.

**Comment by Azero123** [comment]
Can I take this one?

**Comment by lieut-data** [comment]
Go for it, @Azero123!

**Comment by hanzei** [comment]
Hey @Azero123,

How is your work going? Do you have questions?

**Comment by Azero123** [comment]
hey hanzel, sorry i have been working on a different issue and have been pretty slammed this week. but i do have a question, do we have an existing jira server i could connect my mattermost dev server to? or do i need to make a new one?

**Comment by hanzei** [comment]
@levb Do we have a jira server that @Azero123 can use?

**Comment by lieut-data** [comment]
@hanzei, @Azero123 -- I don't think we have a JIRA server available, but I suspect we can safely iterate on this one without. It should be possible to verify the divider being added for new plugins, and a spot check on the JIRA plugin changes should confirm its removal.

Hopefully we'll have a better story for plugin testing like this in the near future.

**Comment by hanzei** [comment]
@Azero123 Does the answer above solve your problem?

**Comment by lieut-data** [comment]
Marking this one as available again due to inactivity.

**Comment by janvt** [comment]
Think I figured this one out, will submit a PR later.

One clarification, the divider should appear once above all plugin menu items? Or once per plugin (if there are multiple plugins)?

**Comment by lieut-data** [comment]
@janvt, I believe the intent is to add it once per plugin. @aaronrothschild, thoughts?

**Comment by aaronrothschild** [comment]
I'm not sure if the original intent was to differentiate from "plugins" and "built-in functions".  I don't think we need the divider between each plugin.  I think it should show up once at the top of the list of plugins 1/5.  
However, if @asaadmahmood has differing thoughts I will defer to him.

**Comment by asaadmahmood** [comment]
The intent was to add a divider between default actions, and actions that were further added by plugins, not necessarily between plugins.

**Comment by asaadmahmood** [comment]
The intent was to add a divider between default actions, and actions that were further added by plugins, not necessarily between plugins.

**Comment by janvt** [comment]
Sounds good. Once before all plugins is relatively easy, once before each plugin would require some reworking of the plugin system, as far as I can see with my React skills. :)

**Comment by adityayavagal** [comment]
Hello can I grab this one? If yes please I need someone for help as I'm new open source contribution

**Comment by hanzei** [comment]
@adityayavagal Sorry, this issue isn't available. @janvt is currently working on it. You can find all available tickets with this query: https://github.com/mattermost/mattermost-server/issues?q=is%3Aopen+label%3A%22Up+For+Grabs%22+sort%3Aupdated-desc

**Comment by saturninoabril** [comment]
PR has been merged.  Thanks @janvt!
