### ISSUE TITLE
React bootstrap splitbutton dropdown text color doesn't change according to theme

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#11059]
#### Summary
React bootstrap splitbutton dropdown text color doesn't change according to theme.

The SplitButton dropdown -
![](https://i.imgur.com/9MQanS8.png)

The DOM element and the style causing text color -

![](https://i.imgur.com/zKZMv7G.png)

As can be seen in the second screenshot, the CSS selector is independent of `bs-style` variant. Indeed it doesn't fix with changing the style as I have verified locally.

#### Steps to reproduce
1. Use any plugin which has a SplitButton in a modal.
1. Open the modal.
1. Notice the text color of the dropdown items is always `#333333` instead of depending on the theme.

#### Expected behavior
SplitButton dropdown item text color should be dependent on the theme to make it contrasting.

#### Observed behavior (that appears unintentional) 
SplitButton dropdown item text color is always `#333333`, independent of the theme.

#### Possible fixes
Since the background color is coming from `centerChannelBg`, the text color should come from `centerChannelColor`. 

I'm on Mattermost 5.11, running via `make run` locally.

**Comment by amyblais** [comment]
Hi @harshilsharma63, I asked our team about this but didn't get a response yet. As a first step, is this something you're open to work on? If not, I'll open a bug ticket to get more attention to this from our team.

**Comment by harshilsharma63** [comment]
@amyblais Yes, I think I can work on this one.

**Comment by harshilsharma63** [comment]
I've created a pull request in webapp for fixing this - https://github.com/mattermost/mattermost-webapp/pull/2950

**Comment by amyblais** [comment]
Ticket for reference here: https://mattermost.atlassian.net/browse/MM-16405.

**Comment by jaatboys** [comment]
Your content is excellent but I think the codeexampler website multilevel inheritance is also the best <a href="https://www.codeexampler.com/csharp-multilevel-inheritance">multilevel inheritance in c# with example</a>
