### ISSUE TITLE
Retry automatically when message fails to send

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11052]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13081)

Case: message fails to send due to lack of network connection at time of sending

Current:
Message shows in it's pending state (red info icon, decreased opacity) and won't attempt to send again until the user retries manually.

Expected:
Message shows in pending state as is does currently, but once a connection is re-established, messages are posted in their queued order (unless they are deleted in their pending state before reconnecting)

**Comment by hanzei** [comment]
@esethna Would you please check if these labels are correct?

**Comment by vickywane** [comment]
> Blocked on MM-13050 so we are sure we aren't sending duplicate messages 

@hanzei  this isn't clear to me

**Comment by Mindaugas-Jacionis** [comment]
I would like to try and tackle this issue, but I am not sure if it is not blocked by other issue. 
I cannot access `MM-13050` task on Jira. 

If it is not blocked, I'd grab and work on it. 🙂

**Comment by hanzei** [comment]
@esethna Can you help with this? Can community member work on this?

**Comment by Mindaugas-Jacionis** [comment]
@hanzei I've got some help from @enahum and started working on the issue 😉

**Comment by hanzei** [comment]
Thanks for working on this @Mindaugas-Jacionis :+1:

**Comment by hanzei** [comment]
Hey @Mindaugas-Jacionis,

Did any questions came up while working on this? Looking forward to this feature.

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by lukeb2e** [comment]
Can the related issue https://mattermost.atlassian.net/browse/MM-13050 also be made available to the public?

Seems that there is related information to the issue. See first comment.

**Comment by hanzei** [comment]
Unfortunately that is a security issue and can't be published. The given that it's resolved, I've removed the link to it.

**Comment by esethna** [comment]
Closing this issue as there may be some UX issues with automatically sending messages, especially if there is a large queue of them. Will revisit this with the UX team and reopen when an appropriate solution is determined, perhaps auto-retrying within a specified time period only, then displaying the pending state if still unsuccessful.
