### ISSUE TITLE
Custom branding text + image are not visible in app or webapp in mobile view.

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#11067]
#### Summary
Custom branding text + image are not visible in native app or webapp in mobile view.

#### Steps to reproduce
load custom branded mm webapp on mobile phone.

or

try to login in native app.

#### Expected behavior
Text and Image visible in mobile webbrowsers and possibly between inputting server-url and username+pw on native apps.

**Comment by amyblais** [comment]
Hi @somenet, what server version and mobile version are you on?

**Comment by somenet** [comment]
recent.

**Comment by amyblais** [comment]
Hi @somenet, I believe this is not supported yet on the mobile view, similar to the mobile app. There is a ticket for this here: https://mattermost.atlassian.net/browse/MM-9361. Would you also like to share this in our feature request forum here: https://mattermost.uservoice.com/forums/306457-general?
