### ISSUE TITLE
Help code review BigBlueButton plugin repository

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#11070]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

Blindside Networks has contributed a great open source web conferencing BigBlueButton for Mattermost.

The source and documentation are available here: https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton

We're looking for help from our communities to code review the plugin and offer suggestions for improvements and fixes. Bonus for submitting a PR for those fixes!

**Comment by ffdixon** [comment]
I'm the Product Manager for [BigBlueButton](http://docs.bigbluebutton.org/).  

We'd be interested in working with any developer familiar with Mattermost plugins that would like to review, improve, or extend the BigBlueButton integration with Mattermost.

If you are running Mattermost behind a corporate firewall and you are looking for a web conferencing solution that also works behind your firewall (i.e. you can run it locally like Mattermost), definitely check out BigBlueButton.

**Comment by harshilsharma63** [comment]
@jasonblais I can review the server part of the plugin sometime this week.

**Comment by jasonblais** [comment]
Great, thank you @harshilsharma63! That would be great 👍

**Comment by ffdixon** [comment]
Ditto!

**Comment by harshilsharma63** [comment]
Any ideas on how I can add review comments? We need to diff the whole codebase.

**Comment by harshilsharma63** [comment]
If the repository owner can [create an empty branch](https://stackoverflow.com/questions/34100048/github-create-empty-branch) and a PR from master into this empty branch, I and other reviewers can add the review comments over there.

**Comment by jasonblais** [comment]
@harshilsharma63 An option is to do the following:

1. `git checkout --orphan dummy-branch`
2. commit the basic files that aren't going to be code reviewed
3. push to upstream/dummy-branch
4. commit everything we want to review to a new dummy-master branch
5. make a PR for dummy-master -> dummy-branch
6. comment on that PR

Also submitted a PR to document these in the dev docs https://github.com/mattermost/mattermost-developer-documentation/pull/304

**Comment by harshilsharma63** [comment]
@jasonblais yes, exactly. But this needs to be done on the original repo. Pushing the dummy branch would need write access.

Or I can do all that in my fork, but I'm not sure how convenient if will be for other folks. Thoughts?

**Comment by jasonblais** [comment]
Good point, wondering if someone on your team @ffdixon would be open to helping with steps 1 - 5 above (pushing a dummy branch and opening a PR for @harshilsharma63 to review)?

**Comment by ffdixon** [comment]
@harshilsharma63 we've made you a collaborator on https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/ -- let us know if that gets you going.

**Comment by harshilsharma63** [comment]
@ffdixon that worked. Thanks!

**Comment by harshilsharma63** [comment]
@jasonblais I had to make a minor change to the steps you mentioned.

1. take a backup of project dir
1. create dummy master branch with no code -
        
        git checkout --orphan dummy-master #create the dummy master branch
        git rm -rf . #remove everything from this branch
        git push origin dummy-master

1. Create `dummy-feature` branch from `dummy-master` -

        git checkout -b dummy-feature
        # copy. everything from backup except the .git dir
        git add .
        git commit -m "Full checkin"
        git push origin dummy-feature

1. Create a PR from dummy-feature -> dummy-master

**Comment by jasonblais** [comment]
Thanks! Updated the doc PR accordingly: https://github.com/mattermost/mattermost-developer-documentation/pull/304

**Comment by harshilsharma63** [comment]
Updated review PR created here - https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/pull/44/

**Comment by harshilsharma63** [comment]
@jasonblais @ffdixon I've added review comments for server component of the plugin.

**Comment by jasonblais** [comment]
Great, thank you! I'll let Fred chime in on the review comments as well 👍

**Comment by jasonblais** [comment]
Thanks @harshilsharma63 for the help :) Closing this issue
