### ISSUE TITLE
Create a new System Console page for existing bot account config.json settings

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11083]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15180)

Create a new page in System Console called "Bot Accounts", which lives below "Integrations > Integration Settings" section in the left-hand sidebar. It should have the following two settings:

1. For ServiceSettings.CreateBotAccounts, move the existing System Console setting for "Enable Bot Account Creation" from System Console > Integrations > Features to the new "System Console > Integrations > Bot Accounts" page.

2. For ServiceSettings.DisableBotsWhenOwnerIsDeactivated, add the following setting to the UI.

{code}
Title: Disable bot accounts when owner is deactivated
Options: true/false (default: true; setting not configurable if bot accounts disabled)
Help Text: When a user is deactivated, disables all bot accounts managed by the user. To re-enable bot accounts, go to **Integrations > Bot Accounts**.
{code}

**Comment by zkry** [comment]
Hello, if possible I would like to work on this.

**Comment by jespino** [comment]
Sure! Thanks @zkry

**Comment by jespino** [comment]
Fixed by mattermost/mattermost-webapp#2954
