### ISSUE TITLE
Notification time not respected

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-server#11152]
Server: 5.11.0

#### Steps to reproduce
1. Set e-mail notification time to 15 minutes
2. Minimize Windows desktop app or swipe Android mobile app (no push)
3. Someone writes to you

#### Expected behavior
Get an e-mail after 15 minutes

#### Observed behavior (that appears unintentional) 
Got an e-mail right away

**Comment by amyblais** [comment]
Hi @licaon-kter, I wasn't able to reproduce this on an upcoming v5.12 release server. When you upgrade to v5.12, would you be open to testing this out again if you still see the issue?

**Comment by licaon-kter** [comment]
Yes, will do.

**Comment by amyblais** [comment]
I'll close this for now, but please reopen this issue once you have upgraded and tested this issue. If the issue persists, please help with more information about your environment and any log errors,

**Comment by licaon-kter** [comment]
Yeah, I skipped 5.12, and went to 5.12.1, and yes, appears fixed, thanks.
