### ISSUE TITLE
Cannot get desktop notifications

### ISSUE THREAD

**Issue by brandon69147** [mattermost/mattermost-server#11150]
Installed Mattermost 5.11 using MySQL 5.7 locally hosted on Hyper V Windows Server 2016.

Cannot get desktop notifications to work using Desktop App and/or Microsoft Edge and/or Chrome.

Websearch doesn't provide much insight...

**Comment by amyblais** [comment]
Hi @brandon69147,

Potentially the sound might be muted by some OS settings. Would you be able to check Focus Assist or Notifications & Actions settings? If this doesn't help, we can continue to troubleshoot.

**Comment by amyblais** [comment]
I'll close this issue for now as we haven't received feedback for a while. Please re-open this issue with relevant additional details if the issue persists.
