### ISSUE TITLE
Move non-API OAuth endpoints from api4 to web package

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11192]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10584)

There are a bunch of non-API OAuth endpoints in the api4 package. Since they are API independent, they should be moved out and into the web package. This will prevent extra work when/if the api4 package is deprecated/removed and when future versions are as well.

The routes can be found in api4/oauth.go they are the ones that are have the prefix `api.BaseRoutes.Root` as they are not api routes.

**Comment by lurcio** [comment]
I'm up for taking this one

**Comment by hanzei** [comment]
Thanks for working on this, @lurcio! :+1:
