### ISSUE TITLE
Add convenience KeyValueStore JSON functions to plugin API

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11193]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8602)

Add functions

KVGetJSON(key string, value interface\{}) error

KVSetJSON(key string, value interface\{}) error

KVCompareAndSetJSON(key string, oldValue interface\{}, newValue interface\{}) error

KVSetWithExpiryJSON(key string, value interface\{}, expireInSeconds int64) error

To the plugin helpers: [https://github.com/mattermost/mattermost-server/blob/master/plugin/helpers.go|https://github.com/mattermost/mattermost-server/blob/master/plugin/helpers.go|smart-link]

**Comment by zkry** [comment]
I'd like to work on this one.

**Comment by zkry** [comment]
I do have a question though on how these functions will map to the KV functions of the API interface. I assume that these functions to be added will just be wrappers for the API interface. So for example, these functions take as input `interface{}` but the API interface works on `[]byte`. I was thinking to just do a type assertion from `interface{}` to `[]byte` and return an error if it fails. So for example, the set would look like this:
```
func (p *HelpersImpl) KVSetJSON(key string, value interface{}) error {
	data, ok := value.([]byte)
	if !ok {
		return errors.New("value was not able to be asserted to []byte")
	}
	err := p.API.KVSet(BOT_USER_KEY, data)
	return err
}
```

Another sort of unrelated question is dealing with the signature for KVGetJSON. It seems that it should be different from KVSetJSON and simmilar to API.KVGet. Is this right?

**Comment by jespino** [comment]
Thanks @zkry! Probably here @jwilander or @levb can give you more information :)

**Comment by jwilander** [comment]
@zkry I would suggest using [json.Marshal](https://golang.org/pkg/encoding/json/#Marshal) to get the `[]byte` JSON encoding of `value`. If you just cast to `[]byte` it will fail every time unless the caller has already done the encoding which would defeat the purpose of the helper function.

And yes, your assumption that these helpers would just be wrappers around the API interface is correct 👍 

For your last question, for `KVGetJSON` you would want to pass in the key as a string and the interface you want to unmarshal into with https://golang.org/pkg/encoding/json/#Unmarshal

**Comment by zkry** [comment]
Ok, that makes sense now. Thanks 🙂

**Comment by lieut-data** [comment]
Thanks again, @zkry!
