### ISSUE TITLE
Move LaTeX support to a plugin

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11195]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-5998)

Move LaTeX support out of the core product and into a plugin.

Currently LaTeX support is in [https://github.com/mattermost/mattermost-webapp/blob/master/components/latex_block.jsx|https://github.com/mattermost/mattermost-webapp/blob/master/components/latex_block.jsx|smart-link] 

Implement a plugin to replace this functionality including any necessary changes to the framework to make it happen. 

Remove LaTeX support from the core product.

**Comment by kosgrz** [comment]
I can do it :rocket:!

**Comment by jespino** [comment]
Awesome!, thanks @kosgrz!

**Comment by jasonblais** [comment]
https://mattermost.atlassian.net/browse/MM-18315 was opened to productize the relevant plugin and eventually make it available in the marketplace.
