### ISSUE TITLE
Migrate "Channel.AutocompleteInTeam" to Sync by default

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11213]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16347)

Mattermost is migrating its Store layer to be sync by default, and only use Async when needed and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `AutocompleteInTeam` in the `Channel` store.

The expected way to implement it is, go to the `Channel` store implementation in the `store/sqlstore/` directory, modify the method `AutocompleteInTeam` to return directly an object from the `model` module, and a `*model.AppError` (removing the `store.Do` wrapper). After that, you must modify the interface defined in `store/store.go` to match with the changes. Then, you should execute `make store-mocks` to rebuild the mocks with the new interface. And finally, modify the rest of the code (tests included) to use the new interface of the function properly.

Example: mattermost/mattermost-server#10613

**Comment by rvillablanca** [comment]
I am working on this issue ;)

**Comment by rvillablanca** [comment]
In the `storetest/channel_store.go` the test `testChannelStoreSearchInTeam` is using this refactor method like this:
```go

	for name, search := range map[string]func(teamId string, term string, includeDeleted bool) store.StoreChannel{
		"AutocompleteInTeam": ss.Channel().AutocompleteInTeam,
		"SearchInTeam":       ss.Channel().SearchInTeam,
	}
```
Due to this signature has changed, I have modify `SearchInTeam` to make this test work, but this last method uses `performSearch`  in `sqlstore/channel_store.go`, this will impact to `SearchMore` in the `ChannelStore`.

Summarizing, I'll refactor `Channel.AutocompleteInTeam`, `Channel.SearchInTeam` and `Channel.SearchMore`.

What do you think @jespino ?

**Comment by jespino** [comment]
@rvillablanca sounds good to me.
