### ISSUE TITLE
 Allow select and copying channel header text using native handling

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11262]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14303)

Repro:
1. Open channel menu on RN
2. Hold down finger on the channel header or purpose or link (see tap areas in the designs)

Observed: Nothing
Expected: 
* Purpose: https://projects.invisionapp.com/share/QSS5C2CWUKF#/screens/365987960/comments
* Header: https://projects.invisionapp.com/share/QSS5C2CWUKF#/screens/365988016/comments
* Links in header purpose or posts: https://projects.invisionapp.com/share/QSS5C2CWUKF#/screens/365988017/comments

**Comment by hanzei** [comment]
@eric Would you please check if the labels are correct and fix the description of this ticket?

**Comment by tekminewe** [comment]
hi @esethna @hanzei i think i can help on this issue
