### ISSUE TITLE
Web design: Add infinite scroll to Select Teams screen

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11265]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13160)

Currently, the Select Teams screen (the one that lets the user join open teams) only loads one page of joinable teams, so if there are more open teams, there is no way to see/join them from the UI.

Infinite scrolling should be used to load more teams.

You can use the CLI command `mattermost sampledata --help` to generate teams.

{panel:bgColor=#eae6ff}

*Functionality*

- The list container is set to a max-width of 800px.
- The list container should scale in width based on the users viewport and device. *This is the current functionality and should remain the same. We’re just increasing the default width.*
- The height of the list container will depend on the the viewport height while respecting the text links and footer. The min-height of the list container should be set to 180px (about  3 1/2 rows when on a mobile device. This will mean the page will require scrolling too, not ideal and probably and corner case. This is definitely small but we’ll be reworking this screen/flow and will need to rethink the footer since it occupies a lot of valuable space on smaller devices.
- Added a mobile example on an iPhone 5 with a reworked footer and tweaks to the font-sizes which should scale for mobile that doesn't eat up as much space. 

*Notes*
- If this can be implemented and usable without reworking the footer and text for smaller devices we can keep it as-is.
- The primary focus here is to place the list inside a container with infinite scrolling, but I ran into a few spacing issues when mocking this out in the browser inspector that cause usability challenges.

*Desktop*
!postgres.test.mattermost.com_select_team.png|thumbnail! !postgres.test.mattermost.com_select_team-inspector.png|thumbnail! 

*Mobile*
!postgres.test.mattermost.com_select_team-iPhone5.png|thumbnail! 

*Animation*
!scrolling-animation.gif|width=400,height=296!

{panel}

**Comment by hanzei** [comment]
@eric Would you please check if the labels are correct and fix the description of this ticket?

**Comment by AGMETEOR** [comment]
@hanzei I am currently giving this a shot.

**Comment by hanzei** [comment]
Thanks @AGMETEOR

**Comment by esethna** [comment]
Hi @AGMETEOR, how is this going?

**Comment by AGMETEOR** [comment]
@esethna right now I am creating a component that can wrap other components or even some jsx, then trigger a callback that's passed in every time we scroll to the bottom. I have managed to create such a component and trying to hook into the select_teams page.

**Comment by AGMETEOR** [comment]
@esethna I should be able to raise a PR for this EOD on Friday :)

**Comment by AGMETEOR** [comment]
@esethna I can raise a WIP PR but I think I don't have rights to put a `WIP` label

**Comment by AGMETEOR** [comment]
@esethna I have something working, I need to clean it up a little more that's why I still have a draft PR. [Here it is](https://github.com/mattermost/mattermost-webapp/pull/3165)

**Comment by esethna** [comment]
Thanks @AGMETEOR, please keep us informed of your progress

**Comment by AGMETEOR** [comment]
@esethna I just took the PR I raised for this from draft... it's now ready for review.

**Comment by esethna** [comment]
@AGMETEOR let us know if you're still working on this and I'll reassign to you :)

**Comment by esethna** [comment]
Thanks @AGMETEOR for completing this!
