### ISSUE TITLE
No prompt to grant permissions if Mattermost was denied photo permissions on the device

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11266]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12879)

Original report: https://forum.mattermost.org/t/ios-select-avatar-issues/5961

If Mattermost doesn't have permission to the photo library because the user denied the first prompt, the app should prompt to give permission to send the user to settings app to manually change the permission.

Expected screen:

*"Mattermost Beta" would like to access your photos*
Upload photos and videos to your Mattermost instance or save them to your device. Open Settings to grant Mattermost Read and Write access to your photo library.

[Don't Allow] [Settings]

Don't Allow: Dismissed modal and no change in permissions
Settings: Takes user to the settings app at the appropriate screen to adjust permissions for Mattermost

**Comment by tekminewe** [comment]
hi @esethna I think i can help with this issue, but i see that the camera permission having the same problem, are we going to fix it with this issue too?

**Comment by jespino** [comment]
Thanks @tekminewe!
