### ISSUE TITLE
White bar on test instance

### ISSUE THREAD

**Issue by ShalokShalom** [mattermost/mattermost-server#11268]
#### Summary
A white bar appears on test instance when scrolling down. 

#### Steps to reproduce
Test instance. See Screenshot. 

#### Expected behavior
Blocked scrolling. 

#### Observed behavior (that appears unintentional) 
White bar. 

#### Possible fixes
Idk. 

![Screenshot_20190618_182754](https://user-images.githubusercontent.com/6344099/59702205-7bb63880-91f7-11e9-99fc-b21f1deebb4a.png)

**Comment by amyblais** [comment]
Hi @ShalokShalom. To give you the best help we can, could you review [this web page](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues) and send us the relevant environment details, logs, config files, etc. so we can diagnose this issue?

**Comment by ShalokShalom** [comment]
Since this is the test environment, you provide...?

I have closed this instance, so no chance for logs. 

Anything else, that I can do?

**Comment by ShalokShalom** [comment]
It is Firefox, on Linux. Current version.

**Comment by amyblais** [comment]
Hi @ShalokShalom, since you've closed the instance, have you seen this on other servers?

**Comment by ShalokShalom** [comment]
I have tried to reproduce and cant do it.

**Comment by amyblais** [comment]
Thank you for letting me know. I'll close this issue for now, but if you see this problem again please re-open this issue and we can investigate further,
