### ISSUE TITLE
Add status icons on "add member to channel" list

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11264]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9695)

Original report here: https://github.com/mattermost/mattermost-server/issues/8258

*Summary*

The Add Members lists, from Channel name drop-down > 'Add Members' do not display the status icon on users' profile pictures.
Status icons are currently displayed on all other Members lists.

*Steps to reproduce*

1. Log in to Mattermost - Version: 4.7.0 (4.7.0-rc2)
5. Select any public or private channel
6. Select the Channel name dropdown, above the chat window
7. Select 'Add Members'
8. View 'Add New Members to [channel_name]' list

*Expected behavior*

All Members lists display a status icon on a user's profile picture from the Channel name drop-down > Manage (or View or Add) Members

*Observed behavior*
Selecting Channel name drop-down > 'Add Members' displays a list of users, but does not display a status icon on a user's profile picture.

**Comment by Sheshagiri** [comment]
does it involve UI changes as well(`mattermost-webapp`)?

**Comment by jespino** [comment]
Oops, I tagged it wrongly, yes it's mainly `mattermost-webapp` changes

**Comment by Siddharth-Ashri** [comment]
I'll take this one. Ive been learning react and would love to contribute to Open-Source project like this.

**Comment by hanzei** [comment]
Hey @Siddharth-Ashri,

Thanks for taking a shot on this issue. Feel free to join the [Mattermost Community Server](https://community.mattermost.com) and ask any questions you have there.

**Comment by amoury** [comment]
I would love to contribute to this one...is it done already?

**Comment by Siddharth-Ashri** [comment]
Do I have to setup both the web app and the server?

**Comment by hanzei** [comment]
@Siddharth-Ashri Yes, you have. Let me know, if you need further help.

**Comment by hanzei** [comment]
@amoury Thanks for your interest in this issue. Currently @Siddharth-Ashri is working on this.

We mark available ticket will the "Up For Grabs" label. With the following query you can find all React ticket that are available: https://github.com/mattermost/mattermost-server/issues?q=is%3Aopen+label%3ATech%2FReactJS+label%3A%22Up+For+Grabs%22

**Comment by hanzei** [comment]
Hey @Siddharth-Ashri,

Do you successfully set up your dev environment? Looking forward to your PR.

**Comment by Siddharth-Ashri** [comment]
Hey @hanzei  I've been having some trouble trying to set up the environment I've got the server up and running but for some reason front-end does not show up. I will try again later tonight. and try to upload a PR ASAP

**Comment by Siddharth-Ashri** [comment]
> Hey @Siddharth-Ashri,
> 
> Do you successfully set up your dev environment? Looking forward to your PR.

Hi @hanzei  I am having issues setting up my dev environment, where can I get some help? I have tried asking in the contributor community but I have not yet received a response.

**Comment by hanzei** [comment]
Hey @Siddharth-Ashri, did you got your dev environment running? If not, feel  free to ping me on the community server.

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity. @Siddharth-Ashri let me know, if you still want to work on this.

**Comment by amoury** [comment]
@hanzei I am still interested to give this a shot

**Comment by hanzei** [comment]
Awesome, thanks @amoury :tada:

**Comment by amoury** [comment]
@hanzei Thanks for assigning it to me. I am trying to setup the server part and ran into this error

```
ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint mattermost-postgres (f4a30d706fc2216ca64a378ecf5557eb1bb06c4eebe125c1f298f948101a15bd): Error starting userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
make: *** [start-docker] Error 1
```

I ran docker ps to check if there was any container running on port `5432`, but there is none. Can you please give me some direction on how I can get around this? 
Thanks

**Comment by hanzei** [comment]
@amoury Would you please check what ` sudo lsof -i -P -n | grep LISTEN | grep 5432` reports?

**Comment by amoury** [comment]
@hanzei Running that command gives me this. To me it looks like postgres is running and listening to the connection. But still running the `curl ping` command does not return me the JSON.

<img width="1002" alt="Screen Shot 2019-09-25 at 10 11 05 AM" src="https://user-images.githubusercontent.com/16633104/65573841-d68cc800-df7c-11e9-96ad-3496cf15c987.png">

**Comment by hanzei** [comment]
@amoury Would you mind sending me a DM on the [Mattermost Community Server](https://community.mattermost.com)? This conversation is driving away from the original topic.

**Comment by amoury** [comment]
@hanzei Here is my PR for this issue -  https://github.com/mattermost/mattermost-webapp/pull/3825 
Thanks

**Comment by hanzei** [comment]
This doesn't seem to be an issue any longer.

**Comment by hanzei** [comment]
@esethna You are correct, thanks for double checking :+1:

**Comment by courtneypattison** [comment]
I'll take this one :)

**Comment by esethna** [comment]
@courtneypattison note that there's another PR in progress in this area so please take a look to avoid conflicts :)

https://github.com/mattermost/mattermost-webapp/pull/7172

**Comment by courtneypattison** [comment]
@esethna Thank you for the heads up! Some of the files overlap, but it looks like they should be simple merges.

**Comment by zefhemel** [comment]
@courtneypattison by now @asaadmahmood's changes have been merged. Nevertheless having the online status appear in the new model would still be awesome. Would you still be up to adapt this PR (or create a new one) to adjust your work to the new model?

**Comment by courtneypattison** [comment]
@zefhemel Thank you for letting me know :) My merging skills are iffy, so I created a new PR.
