### ISSUE TITLE
Bot account creation causes "access token added" email to bot user

### ISSUE THREAD

**Issue by maruTA-bis5** [mattermost/mattermost-server#11310]
#### Summary
When created bot account, sent "access token added" email to bot user.

#### Steps to reproduce
Reproduce in 5.12.0 EE without license, or 5.12.0 TE.
1. Set enable bot account creation
2. Create new bot account

#### Expected behavior
No email sent, or send to bot created user.

#### Observed behavior (that appears unintentional) 
Email that subject is "Personal access token added to your account" was sent to `<bot username>@localhost`.

#### Possible fixes
In master, guard to don't send emails to bot users found.
https://github.com/mattermost/mattermost-server/blob/2f36158adbf34297871af7f51fc130c86fa63047/app/session.go#L253-L258
But in tag v5.12.0 or branch release-5.12, it was not found.
https://github.com/mattermost/mattermost-server/blob/v5.12.0/app/session.go#L263-L265

**Comment by amyblais** [comment]
Hi @maruTA-bis5, I wasn't able to reproduce this just now on a TE server, but not sure if some of my settings are different. Is this something you would be open to creating a PR for?

**Comment by amyblais** [comment]
Hi @maruTA-bis5, are there any other config settings or additional repro steps that could help me reproduce this?

**Comment by maruTA-bis5** [comment]
I try repro in fresh environment and these steps are reproducable.
1. Download mattermost-team-5.12.0-linux-amd64.tar.gz and extract it.
2. Set these configurations from System Console
    1. SMTP server & port
    2. Enable Email Notifications to `true`
    3. Enable Bot Account Creation to `true`
3. Go to Integrations > Bot Accounts backstage 
4. Add Bot Account to create new bot account
    - This causes sent email to `bot-username@localhost`. Attach email captured by inbucket: [captured-email.txt](https://github.com/mattermost/mattermost-server/files/3318651/captured-email.txt)

[config-te.json.txt](https://github.com/mattermost/mattermost-server/files/3318648/config-te.json.txt) is full config.json.

**Comment by amyblais** [comment]
This was fixed with this ticket for v5.14: https://mattermost.atlassian.net/browse/MM-15777.

**Comment by maruTA-bis5** [comment]
I see. I'm waiting for 5.14 release. 
Thank you for investigate issue.
