### ISSUE TITLE
Dont notify bots to be added in channel on mentioning

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#11329]
Currently when we mention a bot account in a channel, an ephemeral message is posted by Mattermost asking the bot to be added in the channel. I don't think this is required for bot accounts as they can interact with a channel without being a member in it.

This is an unnecessary notification and bothers each user, each time they mention a bot.

I propose removing this message for bot accounts.

**Comment by amyblais** [comment]
@harshilsharma, for some reason I wasn't able to reproduce this just now, do you have any additional repro steps to help me reproduce this?

**Comment by harshilsharma63** [comment]
@amyblais sorry about the delay in responding.

I've created a [channel on pre-release](https://pre-release.mattermost.com/core/channels/gh-11329-demo#) for demonstrating this and have added you in there as well. You can try it out over there.

I've found that the what I've described above only hapenns if the bot has been added to the current team.

So I added `Surveybot` bot user to `Contributors` team on pre-release. Now if you tag `@Surveybot` in any channel, it will show you this -

![](https://i.imgur.com/PUpCTtE.png)

**Comment by amyblais** [comment]
Thank you, ticket here: https://mattermost.atlassian.net/browse/MM-16744.
