### ISSUE TITLE
Support relative links in interactive message buttons

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11352]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10982)

Plugin can create posts with interactive message buttons and menus.  When creating such posts, a callback URL has to be provided. More information about this can be found at [https://docs.mattermost.com/developer/interactive-messages.html](https://docs.mattermost.com/developer/interactive-messages.html)

When a user presses such a button or selects an entry in the menu, a http request is made to the provided URL. Plugins may respond to these requests via their hook, and thus must configure the appropriate SiteURL. Fetching this from the config and pushing it down requires a non-trivial amount of code.

There has also been problems in the past where admins had to set to in order to allow plugins to even respond to their own interactive message buttons.

And if the SiteURL changes unexpectedly, or the plugin fails to account for the presence of a subpath, random issues might crop up.

To solve the issues outlined above, we should support relative URLs as callbackURLs. So instead of e.g. `http://community.mattermost.com/subpath/plugins/com.github.matterpoll.matterpoll/some/path` the callback URL would be `/plugins/com.github.matterpoll.matterpoll/some/path`. The infrastructure would take care of routing this within the server without further configuration.

**Comment by streamer45** [comment]
I can take a stab at this but I definitely need some additional info. 
I am new to the codebase so please forgive me if I say something that doesn't make sense or if it's plainly wrong.  I took some time to investigate the issue and have a couple of questions:

- Is this behaviour something that we want only for calls related to plugins? 
- Should this be handled by simply checking that the incoming callback URL is a valid relative URL to a plugin (URL starts with "/plugins/"), prepend the ```SiteURL``` and subpath (if exists) and run it exactly as before, or should it all be handled/routed separately?

**Comment by hanzei** [comment]
Hey @streamer45,

Thanks for looking into this :+1: 

- Yes, this is only for plugins.
- The former way is just fine :+1: 

Let me know, if you have additional questions.

**Comment by streamer45** [comment]
thank you for the clarification @hanzei.
I'll have a PR ready soon.
