### ISSUE TITLE
request: Is it possible to use Preact instead of React ? 

### ISSUE THREAD

**Issue by catastrop** [mattermost/mattermost-server#11357]
https://github.com/preactjs/preact

**Comment by catastrop** [comment]
please consider this

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @catastrop.

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by catastrop** [comment]
@amyblais, i have posted the idea

**Comment by amyblais** [comment]
Thank you!
