### ISSUE TITLE
Emoji doesn't include gender-neutral variants

### ISSUE THREAD

**Issue by clarfon** [mattermost/mattermost-server#11366]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

#### Summary
Emoji require usage of gender variants and does not allow gender-neutral variants.

#### Expected behavior
Unicode emoji added gender variants (e.g. `:man_shrugging:` and `:woman_shrugging:`), but there are still gender-neutral variants available. Despite the fact that most emoji sets do not include gender-neutral variants, the fact that shortcodes cannot be used for gender-neutral variants (e.g. `:shrugging:`) is counter-intuitive and requires a user to pick the gender of their shrug, profession, or zombie in order to post an emoji. In the raw unicode representation, this will omit the gender variant, and for clients that show system emoji, this will use that variant from the font instead.

#### Observed behavior (that appears unintentional) 
Right now a lot of common emoji (like `:shrugging:`) require gender variants like (`:man_shrugging:`) and (`:woman_shrugging:`).

#### Possible fixes
This should be as straightforward as modifying the contents of `model/emoji_data.go` to match an emoji shortcode list which includes gender-neutral variants. I know for a fact that GitHub's list has these problems, and the list may be the same as the one GitHub uses.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @clarfon.

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
I'll close this issue for now, but I hope you are open to creating a feature request issue and we can then track this request there,

**Comment by clarfon** [comment]
Hi,

I consider this a bug, not a request for a new feature, but I can try to get around to posting that at some point.
