### ISSUE TITLE
make package reported error `tar: Option --wildcards is not supported`  on macOS 10.14.5

### ISSUE THREAD

**Issue by jk2K** [mattermost/mattermost-server#11370]
#### Summary
`make package` not work, get error `tar: Option --wildcards is not supported`

#### Steps to reproduce
```bash
make build-client
make build
make package
```

#### Expected behavior
generate package, no error

#### Observed behavior (that appears unintentional) 
package did generated, but get error, 

#### Possible fixes
https://superuser.com/questions/318809/linux-os-x-tar-incompatibility-tarballs-created-on-os-x-give-errors-when-unt
```brew
brew install gnu-tar
```
replace tar with gnu-tar on macOS

**Comment by amyblais** [comment]
Hi @jk2K, Thank you for the report. Did you try the troubleshooting steps on the link you posted, or does this seem to be a bug on Mattermost's side?

**Comment by jk2K** [comment]
It seems that the build scripts has a compatibility issue on Mattermost's side

**Comment by amyblais** [comment]
Hi @jk2K, would you be able to help with a link to the developer setup documentation you were following for this?

**Comment by ali-farooq0** [comment]
Ran into this myself, https://github.com/mattermost/mattermost-server/pull/13629 should address this issue, as we no longer need to re-tar prepackaged plugins anymore.
