### ISSUE TITLE
Removing a link preview on web app doesn't remove it on mobile app

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11404]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16468)

Not a regression, checked older versions of the app and they have the same behavior.

Steps:
1. Post a link on the web app
2. Remove the link preview from the post
3. Log in to the mobile app and open the same channel

Observed: URL and link preview are shown in the post
Expected: URL is shown without the preview

**Comment by imisshtml** [comment]
https://www.apollographql.com/docs/react/advanced/caching/#inmemorycache

**Comment by mzaks** [comment]
I'll take this one

**Comment by esethna** [comment]
Closed with https://github.com/mattermost/mattermost-mobile/pull/2939

Thanks @mzaks!
