### ISSUE TITLE
MMCSRF cookie not created after upgrade until after logging out and logging in

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#11408]
#### Summary
`MMCSRF` cookie is not created in browsers after upgrade from 5.11 to 5.12 until the user logs out and logs in again.

#### Steps to reproduce
1. Start from and existing installation of Matermost v5.11
1. Login in from any browser (I've tried on Chrome and Firefox).
1. Upgrade Mattermost to v5.12.
1. Run `document.cookie` in browser console. Notice that it only shows the `MMUSERID` cookie.
1. Logout and log in again from browser.
1. Run `document.cookie` in browser console. Notice that it now shows `MMUSERID` along with `MMCSRF` cookie.

#### Expected behavior
`MMCSRF` cookie should be available to any already-logged in users upgraded from 5.11 to 5.12.

#### Observed behavior (that appears unintentional) 
`MMCSRF` cookies is only set after logging out and back in.

**Comment by amyblais** [comment]
@harshilsharma A response from a dev:

"We decided against that during the implementation since we don't enforce it yet and enforcement will be turned on with v6.0, where it was mentioned that a force logout would be most likely there anyway."

Does this help?

**Comment by harshilsharma63** [comment]
@amyblais thanks for looking into this.

I issue here is not just the absence of `MMCSRF`  cookie, but rather plugins relying on it to communicate from webapp component to the server component. The HTTP endpoints created in server component of plugin may require logged in Mattermost user. This can be check on plugin side by the presence of `Mattermost-User-Id` HTTP header.

As per [this code](https://github.com/mattermost/mattermost-server/blob/dbe330511eb45dcfaca1b5a5fd7e5097d50fc83a/app/plugin_requests.go#L133), the above specified header is inserted on if CSRF check passed, which relies on the presence of `MMCSRF` cookie in Mattermost webapp.

For example, [this bug in Standup Raven](https://github.com/standup-raven/standup-raven/issues/64) is caused by absence of `MMCSRF` cookie.

**Comment by amyblais** [comment]
@harshilsharma Response from a dev (summarized):

There is also the workaround using a header. There doesn't seem to be anything we can do here at this point. If the plugin sets the XmlHttpRequest header properly there won't be a problem right now, and with v6.0 we can force a logout when we enable enforcement.

**Comment by harshilsharma63** [comment]
@amyblais I tested this again and `XMLHttpRequest` does work with 5.12. My bad.

Thanks for looking into this again!
