### ISSUE TITLE
Change the perfectScrollbar to not use the jquery approach (And upgrade to 1.4.0)

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11422]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16541)

Now we use perfectScrollbar 0.8.1 and we use the jQuery interface to use it. We are trying to get rid of jQuery in our source code, so in this case we want to remove the usage of the jQuery interface and replace it with the vanilla javascript interface. By the way would be great to migrate to version 1.4.0 (the last version).

**Comment by fm2munsh** [comment]
I'll grab this one
