### ISSUE TITLE
Remove JQuery Dragster dependency

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11429]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16639)

Now we use a small jquery library call jquery-dragster (placed in non_npm_dependencies directory) to handle the drag and drop events in the components/file_upload/file_upload.jsx file. We want to remove that dependency handling that events directly using vanilla javascript. This can be done migrating jquery-dragster to something in vanilla javascript and store it in the utils directory, or directly rewriting how the drag and drop events are handled in the components/file_upload/file_upload.jsx file.

**Comment by goku321** [comment]
Interested in taking this one.

**Comment by jespino** [comment]
Awesome, thanks @goku321! ✨

**Comment by hanzei** [comment]
Hey @goku321, Do you have any questions about this ticket?

**Comment by goku321** [comment]
Hi @hanzei due to workload I am not able to make progress on this one yet but this is definitely on my to-do list. I know I delayed it a lot but I need a couple of days to make some progress. If I am not able to work on this I will let you know. Thank you for your patience

**Comment by hanzei** [comment]
Thank you very much for the update @goku321 :+1:

**Comment by hanzei** [comment]
Hey @goku321,

There was a confusion from @niklabh about the Help Wanted process. He didn't knew that you claimed this ticket and opened a PR for. Sorry for this.

**Comment by goku321** [comment]
@hanzei No problem. Thanks @niklabh , this ticket was long overdue :sweat_smile:
