### ISSUE TITLE
No warning or error when trying to share long text from share extension

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11431]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15469)

Repro steps
1) Find a web page with text that's too long to be posted (over the number of characters specified in config.MaxPostSize in the client config. If undefined would default to 4000 characters)
2) Select the text in the device's browser
3) Select Share from the context menu
4) Click "Post" in the share extension screen

Observed: There's no warning to say that the text is too long
Expected: Similar to iOS, show a dialog that states "Content text shared in Mattermost must be less than xxxxx characters." with an OK button. Clicking okay brings user back to share extension screen where they can edit the text.

**Comment by chuttam** [comment]
Mind if I pick this one up, @esethna ?

**Comment by hanzei** [comment]
Sure, thanks @chuttam
