### ISSUE TITLE
Thumbs down sorts before thumbs up in emoji picker on first use

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11437]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14213)

Emojis are sorted by recently used as these rules: https://mattermost.atlassian.net/browse/MM-12861

But there are cases on first use that still feel off. For example, the first use of "thumbs" will sort thumbs down before thumbs up. We've heard this via multiple channels.

Expected: When the search term matches and there are no recently matching emoji, sort first thumbsup, then thumbsdown, and then custom emoji.

Needs implementation on Webapp and Mobile app

**Comment by anchepiece** [comment]
@enahum It looks like an additional rule could adjust sort in special cases. It may be useful to use the defined emoji index.

Are there more reported cases beyond thumbsup/down?

**Comment by jasonblais** [comment]
cc @esethna @hmhealey as Elias may be out

**Comment by esethna** [comment]
@anchepiece as far as we know this is the only custom sorting we need at the moment

**Comment by nevyangelova** [comment]
Grabbing this today.

**Comment by jasonblais** [comment]
Thanks @nevyangelova :tada:
