### ISSUE TITLE
Remove the full screen "Refresh" button when opening a team or channel with no cached data when offline

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11435]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13083)

Repro:
1. Switch to a team that has no cached data when the app is offline > observe screen 1
2. Switch to a channel that has no cached data when the app is offline > observe screen 2

Team - no cache:
 !image-2018-11-19-15-18-05-867.png|thumbnail! 

Channel - no cache:
 !image-2018-11-19-15-22-06-660.png|thumbnail! 

Expected:

Team: Use the same screen as for "Team Not Found"

Channel: Show pulsing channel loading animation with the standard "Offline" connection bar at the top of the channel

**Comment by jasonblais** [comment]
Looks like this was done via https://mattermost.atlassian.net/browse/MM-16251
