### ISSUE TITLE
Complete migration of channel_actions to redux actions

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11442]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12588)

This is part of the technical debt epic
Details at https://mattermost.atlassian.net/browse/MM-12173

Migrate channel_actions to redux actions and update all the necessary components

**Comment by amorriscode** [comment]
👋 I'll tackle this one.

**Comment by amorriscode** [comment]
@hanzei @esethna I had a question about doing the work for this one but never got a reply. Unfortunately I don't have time to complete the ticket now so perhaps we could add the `Up For Grabs` tag back on?

Sorry!

**Comment by hanzei** [comment]
Hey @amorriscode,

I'm sorry for missing your question. Still, thanks for the time you spend with this issue.

**Comment by AGMETEOR** [comment]
@hanzei I would like to try this out. However, @amorriscode had a question up there that I think when answered would give me some more guidance on how to complete this.

**Comment by hanzei** [comment]
Awesome, thanks @AGMETEOR :tada:

**Comment by hanzei** [comment]
@saturninoabril Can you help with the question? https://github.com/mattermost/mattermost-server/issues/11442#issuecomment-506570031

**Comment by saturninoabril** [comment]
I think this ticket is no longer valid and should just be updated to which action to migrate.  The integration part is almost done, just need to get rid off using global `store`.  I'd recommend to make this as "Complete migration of [channel_actions](https://github.com/mattermost/mattermost-webapp/blob/0d40e9395528371530d5f625edbdc792f5e3aaeb/actions/channel_actions.jsx) to redux actions", particularly
- autocompleteChannels
- autocompleteChannelsForSearch

Will update the ticket accordingly.

**Comment by AGMETEOR** [comment]
Thank you @saturninoabril , I will attempt this now.

**Comment by AGMETEOR** [comment]
@saturninoabril I have a draft PR up for this... working to complete migrations for all the other actions in `channel_actions.js`
