### ISSUE TITLE
Complete migration of diagnostic_actions to redux actions

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11440]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12583)

This is part of the technical debt epic
Details at https://mattermost.atlassian.net/browse/MM-12173

Migrate diagnostic_actions to redux actions and update all the necessary components

**Comment by goku321** [comment]
This one as well?

**Comment by jespino** [comment]
Great!

**Comment by goku321** [comment]
Hi @jespino I will not be able to work on this at the moment. Can you please put `Up For Grabs` label again? Thank you for your patience.

**Comment by hanzei** [comment]
Hey @goku321,

Thanks for the heads up. :+1:

**Comment by hanzei** [comment]
Sure, thanks @AGMETEOR

**Comment by AGMETEOR** [comment]
Just a question for @jespino , do I have to first make some changes in the mattermost-redux codebase? For example, I might need to add a `actions/diagnostics.ts` in mattermost-redux then as an example for migrating `trackEvent` in the webapp's `diagnostics_actions.js` file, I add something like this to mattermost-redux
```
export function trackEvent(category: string, event:string, props: object): ActionFunc {
    return bindClientFunc({
        clientFunc: Client4.trackEvent,
        onRequest: DiagnosticTypes.TRACK_EVENT_REQUEST,
        onSuccess: [DiagnosticTypes.TRACK_EVENT_SUCCESS],
        onFailure: DiagnosticTypes.TRACK_EVENT_FAILURE,
        params: [
           category,
           event,
           props,
        ],
    });
}
```

**Comment by AGMETEOR** [comment]
Hello @hanzei , I just wanted to draw your attention to this :)

**Comment by hanzei** [comment]
@sudheerDev Can you help with this question?

**Comment by jasonblais** [comment]
Hi @sudheerDev / @jespino, wondering if you can help with the question above, or direct to someone who can?

**Comment by jespino** [comment]
@AGMETEOR Sorry for the super super super late reply about this. The idea is to migrate this only for the webapp part, so I don't see the need of the changes in the mattermost-redux repo.

My proposal would be migrate what are utility functions to `utils/diagnostics.tsx` and migrate the actions to something like your `trackEvent` action function proposal.

**Comment by AGMETEOR** [comment]
@jespino thanks a lot. I have forgotten about this issue. Will try working on it again.

**Comment by jespino** [comment]
@AGMETEOR Thanks! and sorry again about the delay.
