### ISSUE TITLE
Mixup between stdout and stderr in CLI

### ISSUE THREAD

**Issue by grahamj42** [mattermost/mattermost-server#11475]
#### Summary
mattermost CLI output written to stderr, log info written to stdout  

#### Steps to reproduce
Version 5.12.0 on Ubuntu 18.04.1.
Execute **bin/mattermost channel list test** where *test* is a team.
The wanted output is buried in the middle of log messages (see below).

#### Expected behavior
**bin/mattermost channel list test 2>/dev/null** outputs the list of channels.

#### Observed behavior (that appears unintentional) 
**bin/mattermost channel list test 2>/dev/null** outputs just the log messages.
**bin/mattermost channel list test >/dev/null** outputs the list of channels.

Output without redirection :

`root@myserver:/opt/mattermost# bin/mattermost channel list test
{"level":"info","ts":1561841701.5011215,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'fr' from '/opt/mattermost/i18n/fr.json'"}
{"level":"info","ts":1561841701.5014064,"caller":"app/server_app_adapters.go:58","msg":"Server is initializing..."}
{"level":"info","ts":1561841701.5117211,"caller":"sqlstore/supplier.go:224","msg":"Pinging SQL master database"}
{"level":"info","ts":1561841701.600447,"caller":"filesstore/localstore.go:33","msg":"Able to write files to local storage."}
{"level":"info","ts":1561841701.6015565,"caller":"app/license.go:41","msg":"License key from https://mattermost.com required to unlock enterprise features."}
{"level":"info","ts":1561841701.6055357,"caller":"mlog/log.go:164","msg":"Starting up plugins"}
{"level":"info","ts":1561841704.1156027,"caller":"app/server.go:213","msg":"Current version is 5.12.0 (5.12.0/Sat Jun 15 09:02:50 UTC 2019/bfd66aa445a2df8c6ed6ba9f2567021ecf6c9f3b/403add5df2a572f676fd9da85ad80623cb00b88a)"}
{"level":"info","ts":1561841704.1158009,"caller":"app/server.go:214","msg":"Enterprise Enabled: true"}
{"level":"info","ts":1561841704.115916,"caller":"app/server.go:216","msg":"Current working directory is /opt/mattermost"}
{"level":"info","ts":1561841704.1160095,"caller":"app/server.go:217","msg":"Loaded config","source":"file:///opt/mattermost/config/config.json"}
{"level":"info","ts":1561841704.1258245,"caller":"sqlstore/post_store.go:1277","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}
{"level":"error","ts":1561841704.2297244,"caller":"app/server.go:728","msg":"Elasticsearch.start: Elasticsearch est dÃ©jÃ  arrÃªtÃ©, "}
{"level":"info","ts":1561841704.2302732,"caller":"app/license.go:41","msg":"License key from https://mattermost.com required to unlock enterprise features."}
test-project
town-square
{"level":"info","ts":1561841704.23641,"caller":"app/server.go:324","msg":"Stopping Server..."}
{"level":"info","ts":1561841704.2364964,"caller":"app/web_hub.go:120","msg":"stopping websocket hub connections"}
{"level":"warn","ts":1561841704.2365742,"caller":"app/web_hub.go:125","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","ts":1561841704.237095,"caller":"app/plugin.go:193","msg":"Shutting down plugins"}
{"level":"info","ts":1561841704.2379272,"caller":"sqlstore/supplier.go:917","msg":"Closing SqlStore"}
{"level":"info","ts":1561841704.238245,"caller":"app/server.go:357","msg":"Server stopped"}`

The **version** command is the exception, it goes to stdout.

I think this is what the ticket PLT-5615 / MM-5809 was reporting, but it was not particularly clear.

You have ticket MM-16077 open for the same problem in *loadtest*.

CLI syntax messages are correctly sent to stderr.

The log messages do not appear in the case of a syntax error. They don't seem appropriate for the use of a CLI.
 
#### Possible fixes
Sorry, haven't looked yet.

**Comment by grahamj42** [comment]
I have now changed the option "Output logs to console" to false, and the CLI becomes usable, but the problem still stands - logs should use stderr and command output stdout (or if you want to be clever, open a new handle for log output to the console, and one can separate system errors from application errors).

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-16728.

**Comment by grahamj42** [comment]
@streamer45, @jespino Thank you for your rapid response.
