### ISSUE TITLE
"You joined" Verification email on master.test.mattermost.com has wrong URL

### ISSUE THREAD

**Issue by bnoggle** [mattermost/mattermost-server#11498]
#### Summary
When you sign up on master.test.mattermost.com, the email verification email that the system sends includes the wrong URL.

#### Steps to reproduce
To recreate:
1.  Go to the sign up form ( https://master.test.mattermost.com/signup_user_complete/) (get a team invite if required).
2.  Click the Email and Password button.
3.  Sign up with Email page displays.  In the What's your email address? edit box, type an email address where you can receive email.
4.  In the Choose your username edit box, type a username.
5.  In the Choose your password edit box, type a password.
6.  Click Create Account.
7.  Wait for the email.

#### Expected behavior
The email should contain the proper URL for the master test server.

#### Observed behavior (that appears unintentional) 
The URL includes an extra .com.

#### Possible fixes
Please remove the extra .com from the text and links (including the button).
![comcom](https://user-images.githubusercontent.com/25042684/60537413-1883d600-9cce-11e9-8b74-933dd63be13e.jpg)

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-16729.

**Comment by amyblais** [comment]
Closing this as the ticket was closed as invalid. That server is just configured incorrectly and the SiteURL is set to `master.test.mattermost.com.com`. It will be fixed by removing the second .com.
