### ISSUE TITLE
"app/webhook.go:113","msg":"Event POST failed, err=invalid character '<' looking for beginning of value"}

### ISSUE THREAD

**Issue by mihai-satmarean** [mattermost/mattermost-server#11500]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bug report in one concise sentence
When configuring an outgoing webhook to connect to rasa server the calling of the user @chatbot in this case results in error in logs
#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
- create an user called chatbot
- create an outgoing webhook that triggers on "@chatbot" 
- address to the user in the channel "@chatbot hi"

#### Expected behavior
Describe your issue in detail
we expect that the outgoing webhook sends the call to the rasa server

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
"app/webhook.go:113","msg":"Event POST failed, err=invalid character '<' looking for beginning of value"}
#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by mihai-satmarean** [comment]
I had tapped to the wrong port.

**Comment by andzejsp** [comment]
> I had tapped to the wrong port.

What did you exactly do i face similar problem
```
{"level":"error","ts":1619797357.1766503,"caller":"app/webhook.go:112","msg":"Event POST failed.","error":"invalid character '<' looking for beginning of value"}
```
Whenever i enter mattermost webhook keywords in channel i get the error log above.

I have local rasa x server on VM and mattermost server on seperate VM and i follwed the guide on adding webhook to credidential.yml. I even tried webhook token and bot token, none of them work.
I set up the default chat-bot in rasa opensource using rasa init. Im not sure if thats the case. Do i need to create blank bot model to connect to mattermost?

Would be cool if someone could help me

**Comment by softmastx** [comment]
Anybody know to to fix this issue?
