### ISSUE TITLE
Login page keeps completely white

### ISSUE THREAD

**Issue by christianlupus** [mattermost/mattermost-server#11524]
#### Summary
Nothing but a plain white page is displayed on iOS Safari when visiting a mattermost site.

#### Steps to reproduce
Visit the start (home) page of the current mattermost docker image (version ac1da4b0d362 at the time of writing) using Safari on iOS 9.3.5.

#### Expected behavior
The login page is correctly displayed.

#### Observed behavior (that appears unintentional) 
Nothing at all is shown. The page stays completely empty and white.
I do not see any error messages anywhere prominent on the screen. There might be a way to open web development tools where additional errors might be visible.

In any other browser I tried, the page is fully functional.

#### Additional Information
I peeked into the communication between the docker container and the apache reverse proxy using a network sniffer. I made a dump of this: [dump.zip](https://github.com/mattermost/mattermost-server/files/3362839/dump.zip)

When looking into the dump I saw an (unauthorized) access to `/api/v4/logs` that contains an error message in a JSON object. (I just masqueraded my domain to avoid even a dumb crawler to find the URL directly.)
```
msg: SyntaxError: Strict mode does not allow function declarations in a lexically nested statement. row: 1 col: 0 stack: undefined url: https://example.com/static/5.f052b14aad39cd5375df.js
```

**Comment by christianlupus** [comment]
Update: The device is running IOS 9.3.5. Just for reference.

**Comment by amyblais** [comment]
Hi @christianlupus, we currently support iOS 11+ versions: https://docs.mattermost.com/install/requirements.html#mobile-apps.

**Comment by christianlupus** [comment]
@amyblais Although I would prefer the web version over the installing the app, you merely tell me that older devices will simply put not be supported and that there is no chance/trick/workaround to make things working, right?

**Comment by amyblais** [comment]
Hi @christianlupus, you mentioned your app version so I may have misunderstood. What server version are you on?

**Comment by christianlupus** [comment]
I am running on Mattermost 5.8.0. Or do you mean the deployment server or similar?

**Comment by amyblais** [comment]
@christianlupus A few more questions:

1. What Safari version are you on?
2. Do you see this issue on Safari when you use desktop app or webapp on a computer?
3. Are there any other users on your server who can confirm if they are seeing the same issue on iOS 11+?

**Comment by christianlupus** [comment]
Dear @amyblais, sorry for the late reply. I had to personally look at my parents device, as my father was not able to extract the needed data.

>     1. What Safari version are you on?

According to [this site](https://www.whatismybrowser.com/detect/what-version-of-safari-do-i-have) it is Safari 9:
![IMG_0701](https://user-images.githubusercontent.com/8202922/62005094-4a058b00-b12e-11e9-837c-61108b0da735.PNG)

If you need more elaborate information like build number etc, please tell me where I can look them up.

>     2. Do you see this issue on Safari when you use desktop app or webapp on a computer?

Unfortunately we do only have one single iOS device here. Other machines are Windows/Linux based. On these there is no such problem but well, these are completely different machines.

>     3. Are there any other users on your server who can confirm if they are seeing the same issue on iOS 11+?

No other users confirm the problem as only a very narrow user base is there.

**Comment by jasonblais** [comment]
Hey @christianlupus, would you be open to updating the Safari version? We support Safari version 11 and later: https://docs.mattermost.com/install/requirements.html#mobile-web

You should be able to update the browser via the "How to update Safari" link in your first screenshot

**Comment by christianlupus** [comment]
@jasonblais I would be open to update if this was possible. Unfortunately that is not the case: My father is using an (comparably old) iPad that has Safari 9 bundled with iOS 9.3. There are no updates for the named iPad available according to his research.

The link you mention just points to a site describing to upgrade Safari for a MacBook or similar. For the iPad present there is no option according to the apple site to update Safari.

I saw that there is some requirement stated in the link you provided (see above in this thread). The thing is that I do not get the reason why a certain software is required as mattermost is (technically) just a website with quite a bunch of Javascript. So where does the requirement come from?

**Comment by jasonblais** [comment]
@christianlupus I don't remember specifically for Safari 9, but we've had instances in the past where older browser versions caused issues (e.g. login fails, UI elements not rendered correctly, security vulnerabilities) leading to a broken experience. This is what you might be experiencing here with the blank page.

For the aforementions reasons, along with the effort to maintain and test older versions, we tend to support the versions officially supported by the vendor: https://docs.mattermost.com/process/software-requirements.html

I know this doesn't resolve the particular issue you're seeing on the iPad, but I'm hoping it helps give some context on why that would be,
