### ISSUE TITLE
Check Go version in Makefile

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#11530]
#### Summary
Newer community members often stumble over our Go version requirements. Let's add a Makefile check that asserts the currently required version to help improve discoverability.

#### Steps to reproduce
- Install Go 1.11 or earlier
- make run-sever

#### Expected behavior
Clear error message

#### Observed behavior (that appears unintentional) 
Unexpected compilation errors

**Comment by Hyaxia** [comment]
Will try to tackle this one :)

**Comment by lieut-data** [comment]
Thank, @Hyaxia!
