### ISSUE TITLE
mattermost-webapp build error.

### ISSUE THREAD

**Issue by iamxvbaba** [mattermost/mattermost-server#11558]
#### Summary
mattermost-webapp build failure.
#### Steps to reproduce
windows 10
node: v10.16.0
npm: 6.9.0
1.git clone https://github.com/mattermost/mattermost-webapp.git && cd mattermost-webapp
2.make test
#### Expected behavior
success.
#### Observed behavior (that appears unintentional) 
error log:
3341 silly saveTree `-- zen-observable@0.8.14
3342 verbose stack Error: Command failed: git clone --mirror -q git://github.com/mattermost/react-bootstrap.git E:\xuhui\nodejs\node_cache\_cacache\tmp\git-clone-2fd769c4\.git --config core.longpaths=true
3342 verbose stack /cygdrive/e/xuhui/nodejs/node_cache/_cacache/tmp/git-clone-2fd769c4/E:\xuhui\nodejs\node_cache\_cacache\tmp\git-clone-2fd769c4\.git: No such file or directory
3342 verbose stack
3342 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
3342 verbose stack     at ChildProcess.emit (events.js:198:13)
3342 verbose stack     at maybeClose (internal/child_process.js:982:16)
3342 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
3343 verbose cwd D:\xuhui\goproject\src\github.com\mattermost\mattermost-webapp
3344 verbose Windows_NT 10.0.17134
3345 verbose argv "E:\\xuhui\\nodejs\\node.exe" "E:\\xuhui\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3346 verbose node v10.16.0
3347 verbose npm  v6.9.0
3348 error code 1
3349 error Command failed: git clone --mirror -q git://github.com/mattermost/react-bootstrap.git E:\xuhui\nodejs\node_cache\_cacache\tmp\git-clone-2fd769c4\.git --config core.longpaths=true
3349 error /cygdrive/e/xuhui/nodejs/node_cache/_cacache/tmp/git-clone-2fd769c4/E:\xuhui\nodejs\node_cache\_cacache\tmp\git-clone-2fd769c4\.git: No such file or directory
3350 verbose exit [ 1, true ]

**Comment by rprobotics** [comment]
Can you confirm how much of the path "/cygdrive/e/xuhui/nodejs/node_cache/_cacache/tmp/git-clone-2fd769c4/E:\xuhui\nodejs\node_cache_cacache\tmp\" exists?

I just installed npm/nodejs on Windows 10 and everything built correctly for me. I see that the mattermost directory is on your D:\ drive, and node.exe is on E:\, it seems like a pathing problem most likely.

**Comment by iamxvbaba** [comment]
> Can you confirm how much of the path "/cygdrive/e/xuhui/nodejs/node_cache/_cacache/tmp/git-clone-2fd769c4/E:\xuhui\nodejs\node_cache_cacache\tmp" exists?
> 
> I just installed npm/nodejs on Windows 10 and everything built correctly for me. I see that the mattermost directory is on your D:\ drive, and node.exe is on E:, it seems like a pathing problem most likely.


Thank you. I will try it.
