### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Use keyboard navigation in emoji picker"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11568]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16738)

__Test Key: M16738 - Use keyboard navigation in emoji picker__
__Test Group: Messaging__

__Steps:__
1. Open any emoji picker (can be in center message box or RHS reply box, or reaction in center or RHS)
2. Press down arrow a few times
3. Press right arrow a couple times
4. Press up arrow a couple times

__Expected:__
- Emoji picker highlight moves up, down, left, right according to the arrow you press
- When opening the emoji picker on a post that is not near the bottom of the channel, ensure that you are not scrolled up or down unexpectedly.

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by irbrad** [comment]
I'm going to take a look at this one.

**Comment by saturninoabril** [comment]
Sure, thanks @irbrad!

**Comment by saturninoabril** [comment]
Thank you @irbrad for your contribution!

PR has been merged.  Closing this now.
