### ISSUE TITLE
Write an automated test using Cypress for "Replying to an older bot post that has some attachment pretext before the message attachment"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11574]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16734)

__Test Key: M16734 - Replying to an older bot post that has some attachment pretext before the message attachment__
__Test Group: Messaging__

__Steps:__
1. Create a bot and post a message in a channel.  Posted message is in a form of message attachment which is similar to how the Jira plugin posts in ~Bugs channel, that is at least one day old (and has had subsequent messages posted after it in the channel). See ``cy.task('postMessageAs', {...})`` on how to post message as if it’s posted in the past.
2. Click "reply" from [...] menu to reply to a message 
3. In right hand sidebar, make a reply post
4. Send and verify reply appears
5. Close the RHS / go back to center channel view

__Expected:__
After 5) you should see "Commented on [bot]’s message: Attachment pretext" on the line below your username on the post showing at the bottom of the center channel, e.g. "Commented on Jira's message: [username] created Bug MM-XXXXX"
See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by lawikip** [comment]
I will take this one.

**Comment by lawikip** [comment]
This can be closed

**Comment by saturninoabril** [comment]
Thanks @lawikip for looking and thank you for your contribution!
