### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Reply to older message"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11570]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16730)

__Test Key: M16730 - Reply to older message__
__Test Group: Messaging__

__Steps:__
1. Click "reply" from [...] menu to reply to a message that is at least one day old (and has had newer messages posted after it in the channel).  See ``cy.task('postMessageAs', {...})`` on how to post message as if it’s posted in the past.
2. In right hand sidebar (RN apps: open reply thread), attach a file
3. Send and verify reply appears
4. Close the RHS / go back to center channel view

__Expected:__
- Date timestamp for first and subsequent posts are correct. 
- Comment appears at the bottom of the center channel with an intro line "Commented on {username}'s message:"  and a line beside the comment

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by irbrad** [comment]
This is similar to #11571 so I'm going to take this one as well.

**Comment by saturninoabril** [comment]
Sure and thanks @irbrad!

**Comment by saturninoabril** [comment]
@irbrad Looks like a PR was submitted for this issue.  Feel free to look for other issue, thanks
