### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Filtered emojis are sorted by recency, then begins with, then contains (alphabetically within each)"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11573]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16739)

__Test Key: M16739 - Filtered emojis are sorted by recency, then begins with, then contains (alphabetically within each)__
__Test Group: Messaging__

__Steps:__
- Post the following emoji in a message: ``:guardsman:``
- In a separate message post the following emoji: ``:white_small_square:``
- Click the emoji icon on the message box to open the emoji picker
- Observe :white_small_square: is listed first, and :guardsman: is listed second, in Recently Used section
- Type "sma" in the emoji search filter box

__Expected:__
In filtered list, recently used emoji are first, in alphabetical order: :guardsman: :white_small_square:
Followed by emoji that start with "sma" in alphabetical::small_airplane: :small_blue_diamond: :small_orange_diamond: :small_red_triangle: :small_red_triangle_down:
Followed by emoji that contain "sma" in alphabetical: :arrow_down_small: :arrow_up_small: :black_medium_small_square: :black_small_square: :sun_behind_small_cloud: :white_medium_small_square:
NOTE: If you have recently used an emoji that matches the search term, you'll see it in the results as well, so it might not match exactly what is listed above
See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by a-arias** [comment]
Going to work on this one since I love emojis :p

**Comment by jespino** [comment]
Thanks @a-arias! :dancer: 🎉🍧🎊

**Comment by a-arias** [comment]
PR is ready to review https://github.com/mattermost/mattermost-webapp/pull/3238

**Comment by saturninoabril** [comment]
Thanks @a-arias for your contribution!

Closing this issue now.
