### ISSUE TITLE
Write an automated test using Cypress for "Replying to an older post by a user that has no content (only file attachments)"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11571]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16731)

__Test Key: M16731 - Replying to an older post by a user that has no content (only file attachments)__
__Test Group: Messaging__

__Steps:__
1. On a post that has only file attachments, that is at least one day old (and has had subsequent messages posted after it in the channel). See ``cy.task('postMessageAs', {...})`` on how to post message as if it’s posted in the past.
2. Click "reply" from [...] menu to reply to a message 
3. In right hand sidebar, make a reply post
4. Send and verify reply appears
5. Close the RHS / go back to center channel view

__Expected:__
After 5) You should see "Commented on [user]’s message: [File name 1] plus 1 other file" on the line below your username on the post showing at the bottom of the center panel
NOTE: If the post you replied to had only ONE file attached, the "plus 1 other file" part of the "commented on..." line will not show
See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by irbrad** [comment]
I'm going to jump on this issue.

**Comment by saturninoabril** [comment]
Sure, thanks @irbrad

**Comment by hanzei** [comment]
@irbrad Do you have any questions?

**Comment by lawikip** [comment]
I will take this

**Comment by hanzei** [comment]
Awesome, thanks @lawikip

**Comment by hanzei** [comment]
Do you have any questions @lawikip about this ticket?

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
