### ISSUE TITLE
Slack Team Import fails to attach files to messages

### ISSUE THREAD

**Issue by probabble** [mattermost/mattermost-server#11616]
#### Summary

Importing Slack team fails to attach files provided by Advanced Slack Exporter.

#### Steps to reproduce
```
Version: 5.9.0
Build Number: 5.9.0
Build Date: Fri Mar 15 22:02:32 UTC 2019
Build Hash: 5ef499caae2bb751438b19151a9fcb4b27830bca
Build Enterprise Ready: false
DB Version: 5.9.0
```
#### Expected behavior
Attached files should be attached to the messages after import.

#### Observed behavior (that appears unintentional) 
A slack team was exported from the normal slack export tool and processed with the slack advanced export tool to collect images and users. 

An import of the resulting file was attempted:
```
mattermost import slack myteam.zip
```

Many warning messages appear:
```
{"level":"warn","ts":1562947811.38912,"caller":"app/slackimport.go:404","msg":"Slack Import: Unable to attach the file to the post as the latter has no file section present in Slack export."}
```

The JSON files in the export have entries that look like:
![image](https://user-images.githubusercontent.com/3421159/61142894-b2454300-a485-11e9-93b1-02d39b94a923.png)

The end result has zero files uploaded to the file store (I tried S3 connection and local file storage with the same result).

#### Possible fixes
Looks like this was fixed in a commit from yesterday! https://github.com/mattermost/mattermost-server/commit/5690df9d959078bb1017dfd7e36abc4274bd890f

I believe this issue should stay open until the fix is actually released?

**Comment by forkwhilefork** [comment]
Hi team, I've run into this issue trying to import my existing Slack data into my Mattermost server (running v5.13.2). When will this fix be released released in a build?
