### ISSUE TITLE
Audio activation like discord do ?

### ISSUE THREAD

**Issue by gamersalpha** [mattermost/mattermost-server#11622]
Hello there, 

so i m just installed my matermost instance, and work like a charm, litlle problem with android app not working, i m still looking for the reason, but so now my question how activate the video and sound like we can see on discord is a realy cool features ?

?

thanks to all

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @gamersalpha,

Would you like to [contribute this idea in the feature request forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Thanks @gamersalpha for the feedback, I'll close the issue here and we track it in the [feature request forum linked previously](https://mattermost.uservoice.com/forums/306457-general/)

**Comment by gamersalpha** [comment]
HEllo, 

why closed this thread, this a features wreally really apréciated

**Comment by jasonblais** [comment]
Hey @gamersalpha! Thanks for your feedback. We monitor feature proposals in our [feature idea forum](https://mattermost.uservoice.com/forums/306457-general), so that members can discuss and upvote them. We primarily use this repository for bug reports :)
