### ISSUE TITLE
PNG Image as team icon shows white background

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#11621]
#### Summary
PNG image set as team icons shows a white background.

#### Steps to reproduce
Use any PNG image with some transparency as team icon and notice a white background appearing on transparent parts.

#### Expected behavior
No forced white background should appear when a PNG image is used as team icon.

#### Observed behavior (that appears unintentional) 
A forced white background appear when a PNG image is used as team icons.

#### Possible fixes
Remove `background-color` team this style -

![](https://i.imgur.com/bmF82ma.png)

**Comment by amyblais** [comment]
@harshilsharma I believe this is currently a known issue. It is documented here: https://docs.mattermost.com/help/settings/team-settings.html#team-icon. Let us know if you're interested in submitting a fix for this.

**Comment by harshilsharma63** [comment]
@amyblais here you go - https://github.com/mattermost/mattermost-webapp/pull/3134

**Comment by hmhealey** [comment]
I already posted this in the PR, but this is intended as per https://mattermost.atlassian.net/browse/MM-10354

**Comment by amyblais** [comment]
I'll close this issue for now based on the comments on the PR.
