### ISSUE TITLE
Messages missing in desktop app after standby.

### ISSUE THREAD

**Issue by kix23** [mattermost/mattermost-server#11647]
#### Summary
Messages missing in desktop app after standby.

#### Steps to reproduce
1. open Mattermost client
1. put computer in standby mode 
1. send messages from other user
1. wake up the standby client
1. don't see received messages due standby time (also no notice about it)
1. clear and reload cache (ctl+shift+r) or wait up to 6 hours (https://mattermost.uservoice.com/forums/306457-general/suggestions/34594582-clear-cache-automatically-at-set-time-or-do-not-ca)
1. get missed messages

Tested with Client Version 4.2.0 and 4.2.1 on Windows.
Server Version 5.12.2

#### Expected behavior
Would be nice, if the received messages at standby time where displayed.

#### Observed behavior (that appears unintentional) 
Messages received during standby time of the computer running the desktop client are not shown.

#### Possible fixes
Clear and reload cache when client wakes up from standby.

**Comment by kix23** [comment]
Maybe this is a client issue.. but worked fine before last server update.. so who knows?
Maybe a mod can move it?

**Comment by amyblais** [comment]
Hi @kix23, this has been fixed in v5.12.4 and v5.13 releases, please upgrade your server to see if your issue resolves.

**Comment by kix23** [comment]
yes. seems that the update to 5.13 did the trick. thank you.
if it happens again i will reopen.
