### ISSUE TITLE
failure to display author info in 5.12

### ISSUE THREAD

**Issue by jimscarver** [mattermost/mattermost-server#11668]
#### Summary
Clicking on message author in web or windows app 5.12.4 gets ```Invariant Violation:``` error
#### Steps to reproduce
enter a channels having messages .
Click on avatar or user name of messaged authored by another user.
#### Expected behavior
popup of user info
Describe your issue in detail
user info is only displayed for yourself. Nothing happens for other authors.
#### Observed behavior (that appears unintentional) 
nothing happens But the following error is logged in the chrome javascript console:
```
react-dom.production.min.js:198 Invariant Violation: You should not use <Link> outside a <Router>
    at invariant (https://chat.diglife.coop/static/plugins/bigbluebutton/bigbluebutton_eefa74634ad6bbc3_bundle.js:570:15)
    at Link.render (https://chat.diglife.coop/static/plugins/bigbluebutton/bigbluebutton_eefa74634ad6bbc3_bundle.js:13498:54)
```

**Comment by amyblais** [comment]
Hi @jimscarver, can you help clarify what you mean by "user info is only displayed for yourself. Nothing happens for other authors."

Also, can you help with more information about your environment such as OS and version, device and browser?

**Comment by jimscarver** [comment]
Clicking on myself on a post I authored I see my user info.
![image](https://user-images.githubusercontent.com/3037201/61531277-5eda7400-a9f4-11e9-8962-faea19a51ae8.png)

Clicking on anyone else I do not get the user info and get the error in the javascript console. The results are the same on chrome, firefox and the windows MM client.

We are running under cloudron on ubuntu 18.04. 

Looking at the error it appears the bigbluebutton integration is causing the error in the latest mattermost release.

**Comment by jimscarver** [comment]
I found this report of the problem https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/issues/45

We did not have the issue before the latest mattermost update.

**Comment by amyblais** [comment]
Thank you for finding the report. A workaround is to disable the plugin for now and wait for a fix.

**Comment by jimscarver** [comment]
https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/issues/45?email_source=notifications&email_token=AAXFQEPZRRPBWHOYW5X2QADQDILWXA5CNFSM4HZHFDPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3W3O7I#issuecomment-518895485
