### ISSUE TITLE
Review and update docs on how to install Mattermost Team Edition Helm Chart in GitLab Helm Chart deployment

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#11675]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17116)

Few months ago, a merge request was opened to add documentation on how to install Mattermost Team Edition Helm Chart in GitLab Helm Chart deployment.

However, it has been a few months and it would be good to confirm the documentation is still valid, and make any updates as needed.

In particular, here are the steps involved:
1. Review the documentation in the original merge request (https://gitlab.com/charts/gitlab/merge_requests/767) and attempt to run Mattermost Team Edition Helm Chart in GitLab Helm Chart deployment. Note any issues, and aim to resolve them with documentation.
2. Review feedback shared by GitLab staff and community, and address them in documentation.
3. Update the existing merge request, or submit a new one, for any documentation updates

**Comment by jasonblais** [comment]
@consideratio wondering if you were interested helping with this ticket? You had previously added excellent comments on the GitLab merge request (https://gitlab.com/charts/gitlab/merge_requests/767)

**Comment by consideRatio** [comment]
@jasonblais ah thanks for the mention and encouragement!

I gave it a second pass, I'm quite motivated to help but very low on time. I hope to squeeze some in anyhow. I'm very excited about both GitLab and Mattermost :D

**Comment by jasonblais** [comment]
Great, thank you @consideRatio! Definitely understand on time, but all help is much appreciated 🙏 :D

**Comment by jasonblais** [comment]
This has been taken by our tech writer, closing, thanks @consideRatio for the help!!
