### ISSUE TITLE
Elastic Server is too RAM and CPU hungry for large deployments OnPremise and OnCloud.

### ISSUE THREAD

**Issue by joeblew99** [mattermost/mattermost-server#11681]
#### Summary
For large scale multi site deployments OnPremsie and Cloud we are hitting the limits with Elastic. It takes too much CPU and RAM.

#### Steps to reproduce
Latest production version.

#### Expected behavior
Describe your issue in detail

#### Possible fixes

We could solve this by changing over to the golang equivalent.

I raised this over here: https://mattermost.uservoice.com/forums/306457-general/suggestions/38203747-replace-elastic-search-with-blast-search-100-go

We would also be able to use it for Monitoring and Log indexing.

I know this is a big ticket item, and i am happy to work on this long term with the team.

**Comment by amyblais** [comment]
Thank you for raising the feature request ticket! Please open a pull request if you are interested / have time to work on this. I'll close this for now as this can be tracked via the uservoice issue,
