### ISSUE TITLE
Add ID label to user detail page

### ISSUE THREAD

**Issue by bradjcoughlin** [mattermost/mattermost-server#11718]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors, please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

### Summary
Add and ID label to the user information "card" on the user detail page per the design specification. Ticket link: https://mattermost.atlassian.net/browse/MM-17374

### Steps to reproduce
In the System Console, navigate to User Management > Users and click on a username to view the `/admin_console/user_management/user/{user_id}` page.

### Expected behavior
Per the design specification, a label containing the user id should be displayed in the header area of the user card:
<img width="846" alt="user-card-with-id-spec" src="https://user-images.githubusercontent.com/44858354/61979033-92467100-afa7-11e9-8bd4-66a48cea276e.png">

### Observed behavior 
Observe that there is no ID visible in the top right of the user information "card":
<img width="752" alt="user-card-without-id" src="https://user-images.githubusercontent.com/44858354/61978754-f0bf1f80-afa6-11e9-9055-f00b54bbda1f.png">

### Possible fixes
Take a look at [admin_user_card.jsx](https://github.com/mattermost/mattermost-webapp/blob/master/components/admin_console/admin_user_card/admin_user_card.jsx) and the related [admin_user_card.scss](https://github.com/mattermost/mattermost-webapp/blob/master/components/admin_console/admin_user_card/admin_user_card.scss).

**Comment by wyze** [comment]
I can take this one.
