### ISSUE TITLE
Personal token not shown

### ISSUE THREAD

**Issue by EugenMayer** [mattermost/mattermost-server#11721]
#### Summary
When creating a personal token and clicking on save, nothing is shown The spinner on the save buttons goes forever. Reloading the page does display a token, but you cannot see the secret anymore

#### Steps to reproduce
- activate personal tokens under integrations
- try to create a personal token in Account Settings -> security

#### Expected behavior
One could see the token secret

#### Observed behavior (that appears unintentional) 
The token secret is never displayed, the save button throbber goes forever. After some time, 502 is thrown on the POST xhr

logs:

```
{"level":"error","ts":1564243964.842158,"caller":"mlog/log.go:172","msg":"Failed to send \"Personal access token added\" email successfully","path":"/api/v4/users/REDACTED/tokens","request_id":"REDACTED","ip_addr":"217.93.163.58","user_id":"REDACTED","method":"POST","err_where":"SendUserAccessTokenAddedEmail","http_code":500,"err_details":"SendMail: Failed to open TLS connection, EOF"}
```
#### Specs
Docker based 5.13.2, see https://github.com/EugenMayer/mattermost-boilerplate for easy startup

**Comment by EugenMayer** [comment]
Looking at the actual error message it seems to be related to an issue that the email server ( SMTP configuration ) cannot be reached. Beside that is probably a configuration error, i suggest this exception should be catched and the token should be displayed in the UI nevertheless

**Comment by jasonblais** [comment]
@EugenMayer Thank you for the report. I've opened a Jira issue for it here: https://mattermost.atlassian.net/browse/MM-17396

Would you be open to helping with a fix for it?

PS: The issue sounds similar to https://github.com/mattermost/mattermost-server/pull/11027, which resolved this same scenario for bot accounts. It appears we need to fix it separately for personal access tokens created for user accounts.

**Comment by jasonblais** [comment]
We've investigated and should be fixed with https://github.com/mattermost/mattermost-server/pull/11027, scheduled for 5.14 release
