### ISSUE TITLE
SMTP authentication setting ConnectionSecurity is reversed

### ISSUE THREAD

**Issue by danhimalplanet** [mattermost/mattermost-server#11724]
I am using Mattermost version 5.13.1 
https://github.com/mattermost/mattermost-docker/commit/91701c543d217fcaf3dcbe160866abd31d1bcac9 

I have a file docker-compose.prod.yml https://gist.github.com/danhimalplanet/32bb63e17f0026ea7e85f4f958cfcdff

how I create the directories mattermost uses:
>        mkdir -p volumes/app/mattermost/{client-plugins,config,data,logs,plugins}/
>        mkdir -p volumes/db/var/lib/postgresql/data/

how I build it:
>       docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

how I start it:
>      docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d app db

I set the SMTP settings, Test, and Save
<img width="743" alt="proof 1" src="https://user-images.githubusercontent.com/1118177/62012182-b769e980-b137-11e9-9a04-7bef3216ce80.png">

Notice I set "TLS" for Connection Security

In my screenshot, I cut out the SMTP server name domain name and the password for the user, but Github makes the screenshot look like I didn't set them.

After I hit save, here are the EmailSettings from volumes/app/mattermost/config/config.json

> "EmailSettings": {
        "EnableSignUpWithEmail": true,
        "EnableSignInWithEmail": true,
        "EnableSignInWithUsername": true,
        "SendEmailNotifications": false,
        "UseChannelInEmailNotifications": false,
        "RequireEmailVerification": false,
        "FeedbackName": "",
        "FeedbackEmail": "",
        "ReplyToAddress": "",
        "FeedbackOrganization": "",
        "EnableSMTPAuth": true,
        "SMTPUsername": "mattermost-admin@amazing.domain",
        "SMTPPassword": "secret.password",
        "SMTPServer": "smtp.amazing.domain",
        "SMTPPort": "587",
        "ConnectionSecurity": "STARTTLS",
        "SendPushNotifications": true,
        "PushNotificationServer": "https://push-test.mattermost.com",
        "PushNotificationContents": "generic",
        "EnableEmailBatching": false,
        "EmailBatchingBufferSize": 256,
        "EmailBatchingInterval": 30,
        "EnablePreviewModeBanner": true,
        "SkipServerCertificateVerification": false,
        "EmailNotificationContentsType": "full",
        "LoginButtonColor": "#0000",
        "LoginButtonBorderColor": "#2389D7",
        "LoginButtonTextColor": "#2389D7"
    },

Notice the value:  "ConnectionSecurity": "STARTTLS",

If I set in the ui "Connection Security" to be "STARTTLS", and save,
ConnectionSecurity will be set to "TLS" in config.json

**Comment by danhimalplanet** [comment]
In my screenshot, I cut out the password and server name, but Github makes it look like I didn't set them at all, trust me, they were there!

**Comment by jasonblais** [comment]
Thank you for the clear repro steps! Created a Jira ticket for our engineers to take a look https://mattermost.atlassian.net/browse/MM-17393

**Comment by jasonblais** [comment]
@danhimalplanet we've got a fix submitted and scheduled for 5.14 release: https://github.com/mattermost/mattermost-webapp/pull/3299
