### ISSUE TITLE
Override LHS bot icon in demo plugin

### ISSUE THREAD

**Issue by ali-farooq0** [mattermost/mattermost-server#11731]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16903)

We've extended PluginAPI as part of 

It would be great for the demo plugin to use this functionality.

I'll be attaching a few SVG icons that can be used for the demo plugin

**Comment by QamarFarooq** [comment]
Ill take this one guys

**Comment by QamarFarooq** [comment]
pr created https://github.com/mattermost/mattermost-plugin-demo/pull/59
