### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Words that trigger mentions support Chinese"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11745]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17445)

**Test Key:** M17445

**Title:** Words that trigger mentions support Chinese
    
**Steps:**
1. Main Menu > Account Settings > Notifications > Words that trigger mentions
2. Set the notification keyword to the following (can copy and paste):
番茄
3. Have another user post that same string `番茄`
4. In a different channel, have the other user post the following string:
 我爱吃番茄炒饭
        
**Expected:**
After 3) and 4) mention is triggered, and keyword is highlighted
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by nadalfederer** [comment]
I'll take this
