### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Terms that are not valid emojis render as plain text "

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11748]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17443)

**Test Key:** M17443

**Title:** Terms that are not valid emojis render as plain text 
    
**Steps:**
1. In the main or reply input box enter a text string between colons that does not refer to a valid emoji, such as :pickle: 
2. Post the message
3. Paste the following timestamp in message box and post:

on Mon Jun 03 16:15:11 +0000 2019
        
**Expected:**
The posts display as text (as opposed to blank spaces) such as:

:pickle:
on Mon Jun 03 16:15:11 +0000 2019
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by larkox** [comment]
May I take this one?
