### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Visual verification of "Searching" animation for Flagged and Pinned posts"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11741]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17442)

**Test Key:** M17442
**Test folder:** `/cypress/integration/messaging`
**Title:** Visual verification of "Searching" animation for Flagged and Pinned posts
    
**Steps:**
1. Click on the "Pinned Posts" icon to the left of the "Search" box and observe the top of the RHS

2. Click on the "Flagged Posts" icon to the right of the "Search" box and observe the top of the RHS
        
**Expected:**
After 1, and before pinned posts are loaded, verify that you see a "Searching..." animation

After 2, and before flagged posts are loaded, verify that you see a "Searching..." animation
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by sij507** [comment]
@saturninoabril I would like to work on this ticket

**Comment by saturninoabril** [comment]
@sij507 Awesome, thank you for you interest!  Let me know if you need anything about this ticket.

**Comment by hanzei** [comment]
@sij507 Do you have any questions?

**Comment by sij507** [comment]
@hanzei No, I have committed the ticket, anything else I need to do?

**Comment by hanzei** [comment]
@sij507 Did you submit a PR to the webapp repo (https://github.com/mattermost/mattermost-webapp) with your changes yet? If not, this is the next step.

**Comment by sij507** [comment]
@hanzei Thanks, done!

**Comment by saturninoabril** [comment]
PR has been merged.  Thanks @sij507 for your contribution!
