### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Focus to remain in RHS textbox each time Reply arrow is clicked "

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11747]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17450)

**Test Key:** M17450

**Title:** Focus to remain in RHS textbox each time Reply arrow is clicked 
    
**Steps:**
1. Click Reply arrow on post to open RHS
2. Focus away from RHS textbox
3. Click reply arrow on post in same thread
        
**Expected:**
1. RHS textbox is focused the first time Reply arrow is clicked
2. RHS textbox is again focused the second time, when already open
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by sij507** [comment]
@saturninoabril I'll take this one

**Comment by saturninoabril** [comment]
Thanks @sij507 for your contribution!

PR has been merged.  Closing this now.
