### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Channel shortlinking still works when placed in brackets"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11749]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17451)

**Test Key:** M17451

**Title:** Channel shortlinking still works when placed in brackets
    
**Steps:**
1. Post the following, where "somechannel" is the name of an existing public channel:
"(~somechannel)"
        
**Expected:**
The "~somechannel" text is hyperlinked and links to the channel
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by jordeguevara** [comment]
I'll work on this 🗡

**Comment by saturninoabril** [comment]
Sue and thanks @jordeguevara!

**Comment by hanzei** [comment]
Hey @jordeguevara, Do you have any questions about this ticket? Happy to help!

**Comment by saturninoabril** [comment]
PR has been merged - https://github.com/mattermost/mattermost-server/issues/11749
Thanks @jordeguevara for your contribution!
