### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Focus will move to main input box after a new channel has been opened"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11742]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17449)

**Test Key:** M17449

**Title:** Focus will move to main input box after a new channel has been opened
    
**Steps:**
1. Open the reply thread on a post
2. Place the focus inside the RHS input box
3. Use ctrl+k to open the channel switcher and select another channel
4. Channel selected opens
        
**Expected:**
When channel is opened, focus is moved to main input box
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by sij507** [comment]
@saturninoabril I'll take this one

**Comment by saturninoabril** [comment]
Sure and thanks @sij507!
