### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Emojis preceeded by 4 or more spaces are always treated as markdown"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11743]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17446)

**Test Key:** M17446

**Title:** Emojis preceeded by 4 or more spaces are always treated as markdown
    
**Steps:**
1. Create a post with four space characters followed by a colon and an upper-case D, like so:
    :D
2. Create a post with four space characters followed by a an emoji such as:
    :taco:
        
**Expected:**
Both emoji are shown as code blocks, not rendered as emoji
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by cpanato** [comment]
@metanerd is working on that

**Comment by saturninoabril** [comment]
Thank you @metanerd!
PR merged.  Closing this now.
