### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Markdown correctly parses "://///" and doesn't break the channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11744]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17444)

**Test Key:** M17444

**Title:** Markdown correctly parses "://///" and doesn't break the channel
    
**Steps:**
1. Post the following in a test channel with existing message history:

://///

2. Refresh the page
        
**Expected:**
Messages in the channel are loaded as expected
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by allenlai18** [comment]
I will work on this!

**Comment by saturninoabril** [comment]
@allenlai18 PR has been merged.  Thank you for your contribution!

**Comment by allenlai18** [comment]
do you usually close these?

**Comment by saturninoabril** [comment]
Oh right, thanks for checking.
