### ISSUE TITLE
Write an automated test using Cypress for "Filtering by first name with Korean characters"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11755]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17459)

**Test Key:** M17459

**Title:** Filtering by first name with Korean characters
    
**Steps:**
1. Set a user's first name to the following:

정트리나/trina.jung/집단사무국(CO)

2. Log in as another user and view a channel you and the other user are both in, plus other users as well
3. Ensure keyboard is set to 2-Set Korean
4. Type `@` and the beginning of the other user's first name: `정트리나`
        
**Expected:**
  - Autocomplete list does not filter down to only display users that match the string

  - The matching user may be highlighted

  - Pressing Tab does autofill the message box with the matching user's username, and pressing Enter posts the mention
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by nadalfederer** [comment]
I'll take this

**Comment by nadalfederer** [comment]
@saturninoabril hi, I've not found cypress docs about typing on one keyboard and it being output in another language

> From an English keyboard set to output in Korean, typing the following letters after the @ should produce the correct characters: wjdxmflsk

can you help how to achieve this in cypress

**Comment by saturninoabril** [comment]
I've updated the description.  You may directly type the message with `@정트리나`.
