### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Scroll to bottom when sending a message"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11750]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17454)

**Test Key:** M17454

**Title:** Scroll to bottom when sending a message
    
**Steps:**
1. Login as User1 and open a channel Channel1. 
2. On another browser, login as User2 and ensure User2 has access to Channel1. 
3. As User2, navigate to a different channel other than Channel1. 
4. As User1, submit a very very long post (containing around 30-40 lines) on Channel1
5. As User2, switch to Channel1 and note that you're scrolled to the New Message line. 
6. Post a message on that channel (Do not reply)
7. Check if you are scrolled to the bottom after sending a message
        
**Expected:**
User should be automatically scrolled to the bottom after sending a message
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by nadalfederer** [comment]
I'll take this
