### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "System message limited options"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11754]
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

---
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17458)

**Test Key:** M17458

**Title:** System message limited options
    
**Steps:**
1. Add or update a channel header
2. Observe the resulting system message if can react, flag, pin or delete
        
**Expected:**
1. Emoji reactions are not available on system messages
2. Flag not available on system messages
3. Pin not available on system messages
4. If permissions allow, can click [...] > Delete to delete system message
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by hanzei** [comment]
Hey @ashishmahi,

Thanks for the PR! Next time please leave a short message in the issue before you start working on it. Thanks :+1:

**Comment by saturninoabril** [comment]
Available for grab.

**Comment by larkox** [comment]
May I take this one?

**Comment by hanzei** [comment]
Sure, thanks @larkox :+1:
