### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Emojis show as jumbo in main thread - Multi emoji, no text, including unicode and emoticon"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11761]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17457)

*__Test Key:__* M17457
*__Title:__* Emojis show as jumbo in main thread - Multi emoji, no text, including unicode and emoticon

__Steps:__*
1. In any channel, copy, paste, and post the following:
 :thumbsup: 🤟

__Expected:__*
All three emoji show as jumbo:
smile, thumbs up, i-love-you gesture

See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by a-arias** [comment]
Going to work on this ticket 💃

**Comment by saturninoabril** [comment]
Sure and thanks @a-arias!

**Comment by saturninoabril** [comment]
Thanks @a-arias!  PR has been merged.

Closing this now.
