### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Typing using CJK keyboard"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11760]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17456)

*__Test Key:__* M17456
*__Title:__* Typing using CJK keyboard

__Steps:__*
1. Switch your keyboard to a Chinese, Japanese, or Korean keyboard (settings vary by OS)
- In general: Should be able to add in System / Keyboard settings, then view Mattermost, then click or tap keyboard settings icon to toggle it

2. Type characters in message box and post; you will likely see some characters combining as you type, and that is the expected behavior
3. Open reply to that message, type a reply, post the reply
If you want to repro a specific Korean example:
- Set keyboard to use 2-Set Korean
- Type the following sequence of letters (do not copy/paste): dkssuggktpdy
- Verify some characters combined as you typed
- Press Enter to post
- Post should appear as:
- undefined
-  안녕하세요

(Incorrect behavior: Input and/or post looks like this, with each keystroke appearing as an individual character: "ㅎㅏㄴㄱㅡㄹㅇㅣㅂㄹㅕㄱㅁㅜㄴㅈㅔ")
*
__Expected:__*
Both message and reply post as expected, with some characters combining as you type
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by nadalfederer** [comment]
I'll take this

**Comment by jasonblais** [comment]
Hey @nadalfederer, just touching base to see if you have questions so far? :)

**Comment by nadalfederer** [comment]
Thanks for the ping. I've missed this, I'll create a PR in the next few days

**Comment by jasonblais** [comment]
Great, thanks @nadalfederer!
