### ISSUE TITLE
Write an automated test using Cypress for "Edit post uses device autocorrect"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#11762]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17453)

*__Test Key:__* M17453
*__Title:__* Edit post uses device autocorrect
*
__Steps:__*
1. Create a new post
2. Long press on the post and select Edit Post
3. Type a word incorrectly and hit space
4. Finish a sentence with a period, start a new sentence
5. Start typing a common word, but don't complete it
*
__Expected:__*
3. Typos are autocorrected
4. text is capitalized at the start of sentences. 
5. Text suggestions are displayed above the keyboard (on iOS, if enabled).
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Comment by jordeguevara** [comment]
I would like to work on this one

**Comment by NiroshaV** [comment]
I'll take this one

**Comment by jasonblais** [comment]
Hey @NiroshaV, just touching base to see if you have any questions so far? :)

**Comment by NiroshaV** [comment]
@jasonblais working on other automation PR and manual PR's(mattermost). Please make this available for public

**Comment by jasonblais** [comment]
Sounds good, thanks @NiroshaV for the help on https://github.com/mattermost/mattermost-webapp/pull/4460 :)

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
