### ISSUE TITLE
Highlight matched text in search results

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11763]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----
**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12247)

Should be done on the mobile repo: https://github.com/mattermost/mattermost-mobile

Search results should have matching text highlighted as it does in the web app. This includes highlighting matching words, quoted phrases, emojis, hashtags, at mentions, and wildcards (such as `boat*` matching boats and boating). A full list of things that should be highlighted is here: https://github.com/mattermost/mattermost-server/blob/master/tests/test-search.md

There'll likely be significant overlap between this ticket and the one to add mention highlighting to mobile (https://mattermost.atlassian.net/browse/MM-5957), but there are at least a couple major differences that may make this more complicated:1. This needs to support Elasticsearch and non-Elasticsearch results. Elasticsearch results include the exact strings matched by the server while we have to parse the search string for non-Elasticsearch to find matching parts of the text (including doing wildcard matching)2. On the web app, we support highlighting in multiline code blocks by using some tricky CSS. This may not be possible on mobile, although it would be good to try to add this still.

**Comment by hanzei** [comment]
@esethna Can you help fix the text of this issue?

**Comment by emilioicai** [comment]
I'll take this one

**Comment by enahum** [comment]
this is a dup issue. closing
