### ISSUE TITLE
Space at end of username breaks member search

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-server#11776]
#### Summary
Space at end of username breaks member search in various member dialogs

#### Steps to reproduce
Go to manage members dialog of team and type `@someusername ` and include trailing space (Markdown is trimming the space in example here). Notice user does not show unless trailing space is removed.

#### Expected behavior
User shows with or without trailing space

#### Observed behavior (that appears unintentional) 
User does not show with trailing space included

#### Possible fixes
Trim inputs

**Comment by jasonblais** [comment]
Hey @bbodenmiller, thanks for the report! Can you help share which Mattermost server version you're running? And confirming you have it running in GitLab omnibus, if I remember correctly?

I was trying to reproduce, but I was unable to, so perhaps this was an issue on an earlier Mattermost release.

![image](https://user-images.githubusercontent.com/13119842/62397283-6301a800-b543-11e9-9b3c-b6eeb198c10f.png)

**Comment by bbodenmiller** [comment]
Looks fixed after latest update.
