### ISSUE TITLE
Unable to start if mailserver is listening but not responding

### ISSUE THREAD

**Issue by guikcd** [mattermost/mattermost-server#11777]
#### Summary
Mattermost is unable to start if mailserver is listening but not really responding.

#### Steps to reproduce

* Version informations:
`Version: 5.13.0`
`Build Number: 5.13.2`
`Build Date: Wed Jul 24 17:25:26 UTC 2019`
`Build Hash: 9a8b0906fdbf2c2a309db2400f4bcc5902800e2c`

* Configuration (config.json):

```
        [...]
        "SMTPUsername": "",
        "SMTPPassword": "",
        "SMTPServer": "localhost",
        "SMTPPort": "25",
        [...]
```

* Reproduction

You can break the mailserver used, or instead install `netcat-openbsd` and bind the port 25/tcp:
```
# nc -l -p 25 &
```
Then start mattermost.

#### Expected behavior
Mattermost could display a console `DEBUG` message (i can propose the Pull Request) and abort the connection within a given timeout.

#### Observed behavior (that appears unintentional) 
Mattermost start but is stuck:

```
Aug  1 22:02:19 chat mattermost[19149]: {"level":"info","ts":1564689739.1237967,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'fr' from '/srv/mattermost/i18n/fr.json'"}
Aug  1 22:02:19 chat mattermost[19149]: {"level":"info","ts":1564689739.1251771,"caller":"app/server_app_adapters.go:58","msg":"Server is initializing..."}
Aug  1 22:02:19 chat mattermost[19149]: {"level":"debug","ts":1564689739.1273336,"caller":"utils/html.go:31","msg":"Parsing server templates at /srv/mattermost/templates"}
Aug  1 22:02:19 chat mattermost[19149]: {"level":"info","ts":1564689739.1383843,"caller":"sqlstore/supplier.go:224","msg":"Pinging SQL master database"}
Aug  1 22:02:19 chat mattermost[19149]: {"level":"debug","ts":1564689739.2219186,"caller":"sqlstore/preference_store.go:41","msg":"Deleting any unused pre-release features"}
```

`Strace` shows that one process tries to connect to `25/tcp`:

```
[...]
connect(14, {sa_family=AF_INET, sin_port=htons(25), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(4, EPOLL_CTL_ADD, 14, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=2569088496, u64=139765099867632}}) = 0
epoll_pwait(4, [{EPOLLOUT, {u32=2569088496, u64=139765099867632}}], 128, 0, NULL, 1) = 1
getsockopt(14, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
getpeername(14, {sa_family=AF_INET, sin_port=htons(25), sin_addr=inet_addr("127.0.0.1")}, [112->16]) = 0
[...]
```

#### Possible fixes

* As mentioned in *expected behavior*, a debug message in `ConnectToSMTPServerAdvanced` can be a good start.

* [The code logic that handle the connection](https://github.com/mattermost/mattermost-server/blob/98ff5fab3243ffa3cbd239770e49582c0944dbc5/services/mailservice/mail.go#L102) use `net.Dial` and `tls.Dial` which does not use a timeout. BTW, it seems that it is impossible to use a timeout with `tls.Dial` (see https://groups.google.com/forum/#!topic/golang-nuts/7p61fSVtJ5k)

**Comment by jasonblais** [comment]
Thanks @guikcd! @jespino  or @DSchalla does the above proposed change mentioned in **expected behaviour** seem reasonable?

**Comment by jespino** [comment]
@jasonblais My question is, If I'm unable to connect to the server which would be the expectation? Run the server without mailing support? do not run the server at all? If my server is sooo busy that it doesn't respond in the timeout during the startup, I going to try to reconnect later?

**Comment by jasonblais** [comment]
@jespino I would expect the Mattermost server to run without mailing support in that case - but we should send some kind of a notice to the admin like a log message informing it, as suggested previously. That's an approach we've taken with other similar services. Attempting to reconnect later might be an option too.

Or would there be unintended consequences I'm not thinking about?

**Comment by jespino** [comment]
@jasonblais my concern is, a log message saying "your email is not enable due timeout" can be easily oversee, so I would expect something more "obvious" like a warning at the top of the application, like other warnings that we have.

**Comment by jasonblais** [comment]
@jespino I totally agree, but this problem isn't unique to email timeout -- it's the same with [compliance exports](https://mattermost.atlassian.net/browse/MM-11124), plugins, LDAP sync jobs and others.

Katie has been exploring options for an "admin notifications board" which would be a more effective way to notify admins of these kinds of errors.

We could add a special case and notify admins about the SMTP server. I'm 0/5, but if you feel strongly about it, we can spec it out.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-17797.

**Comment by isacikgoz** [comment]
As far as I see there is a way to add `timeout` to the `tls.Dial(...)` function. Therefore, we can add it therefore we won't get stuck at this step.

After this, as @jespino suggested, we can make server to display an error in the application to inform the admin.
