### ISSUE TITLE
Installing a plugin via URL causes NPE

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-server#11808]
On `v5.14-RC1` installing a plugin via URL causes an NPE on the server. This effectively prevents admins from using this feature.

**Comment by hanzei** [comment]
@lindy65 Is this worth a bug hunter coin?

**Comment by lindy65** [comment]
Hi @hanzei 

Is there a Jira ticket open for this issue?

All bug reports are valid for bug hunter coins.  I am not involved in the "awarding" of bug hunter coins though so perhaps @coreyhulen can chime in on the process.

**Comment by marianunez** [comment]
This could be possibly related to [MM-17475](https://mattermost.atlassian.net/browse/MM-17475)

**Comment by hanzei** [comment]
> Is there a Jira ticket open for this issue?

No, there isn't. I can open one, if you want. But it would just be a copy of this issue.

**Comment by lindy65** [comment]
Thanks @hanzei 

We should have a Jira ticket for every bug report so it would be great if you can file one :) Even if it's just a dupe of this issue...

**Comment by hanzei** [comment]
Done https://mattermost.atlassian.net/browse/MM-17590

**Comment by lindy65** [comment]
Thanks @hanzei :)
