### ISSUE TITLE
Add option to use custom MinIO secret for the Mattermost operator

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-server#11817]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17531)

The [Mattermost Operator](https://github.com/mattermost/mattermost-operator) is a Kubernetes operator that manages the lifecycle of a Mattermost installation.

Currently, the Minio secrets are randomly generated. However, some users might want to define a custom secret.

For this ticket implement adding a field to the ClusterInstallation custom resource for the user to set a custom secret for Minio.

**Comment by adi-mishra** [comment]
I want to give this a shot. :)

**Comment by hanzei** [comment]
Thanks for working on this @adi-mishra :+1:

**Comment by adi-mishra** [comment]
Given that work on this has been started in https://github.com/mattermost/mattermost-operator/pull/64 . It might be appropriate to assign this to ankitrgadiya.

**Comment by ankitrgadiya** [comment]
@adi-mishra Thanks. I can take this up
