### ISSUE TITLE
Implement NodeSelector for Mattermost operator

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-server#11814]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17528)

The [Mattermost Operator](https://github.com/mattermost/mattermost-operator) is a Kubernetes operator that manages the lifecycle of a Mattermost installation.

Currently we have `NodeSelector` as a field in the type definition for a ClusterInstallation, however, this is not implemented to set mattermost to use a specific node.

See the field here https://github.com/mattermost/mattermost-operator/blob/master/pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go#L46

For this ticket implement node selection for the Mattermost ClusterInstallation custom resource.

Read https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ for more details on node selection.

**Comment by lpadgett** [comment]
I'll do this one!

**Comment by lpadgett** [comment]
I think this might be better left to someone else upon some investigation - I think I should learn more about Kubernetes first. Sorry!

**Comment by lpadgett** [comment]
I think this might be better left to someone else upon some investigation - I think I should learn more about Kubernetes first.

**Comment by jozuenoon** [comment]
I up for grabbing that :)

**Comment by jwilander** [comment]
Thanks @lpadgett and @jozuenoon
