### ISSUE TITLE
Add database write check to the ping API endpoint

### ISSUE THREAD

**Issue by gabrieljackson** [mattermost/mattermost-server#11813]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17554)

The Mattermost server offers the ability to perform an "enhanced" health check via the `api/v4/system/ping` endpoint. The two checks currently performed are for the database and backend file store.

The database health check is currently a read-only check of the Systems table. It would be good to update this check to include a write test as well.

Here are the steps involved to complete this task:
1. Update the "enhanced health check" ping endpoint functionality to include a write to the database. Ideally, this could be something like writing a new row to the Systems table that includes a timestamp or other arbitrary value, and then reading that value and ensuring it is correct. When doing this, the old database values created for this check should be deleted or updated as to not leak needless data.
2. Update or add any unit tests as necessary.

**Comment by jesperhansen17** [comment]
Can I have a look at this one?

**Comment by hanzei** [comment]
Sure. Thanks @jesperhansen17 :+1:
