### ISSUE TITLE
Add option for custom DB root/user password when using the mysql-operator for Mattermost operator

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-server#11816]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17530)

The [Mattermost Operator](https://github.com/mattermost/mattermost-operator) is a Kubernetes operator that manages the lifecycle of a Mattermost installation.

Currently, the root/user password for the database are randomly generated. However, some users might want to define a custom password.

For this ticket implement adding a field to the ClusterInstallation custom resource for the user to set a custom password for the root/user for the database.

Note that if the an external database is being used, this custom password field should be ignored.

**Comment by phillipahereza** [comment]
@jwilander I'll take this one

**Comment by Sheshagiri** [comment]
I will give this a try.

**Comment by jwilander** [comment]
https://github.com/mattermost/mattermost-operator/pull/80 should cover this
