### ISSUE TITLE
Pressing ENTER on the RN apps on iPad w/ keyboard does not send the message

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-server#11812]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14306)

When you have a physical keyboard attached to an iPad and you're typing up a post, if you press enter it creates a new line (even when my user setting is set to send on ENTER for desktop). This is really annoying as you would expect it to behave like the desktop when I have the keyboard attached.

Note: If using the virtual keyboard ENTER is still expected to add a new line.

**Comment by enahum** [comment]
closing in favor of https://github.com/mattermost/mattermost-server/issues/8797
