### ISSUE TITLE
Implement Affinity for Mattermost operator

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-server#11815]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17529)

The [Mattermost Operator](https://github.com/mattermost/mattermost-operator) is a Kubernetes operator that manages the lifecycle of a Mattermost installation.

Currently we have `Affinity` as a field in the type definition for a ClusterInstallation, however, this is not implemented to set mattermost to use specific nodes.

See the field here https://github.com/mattermost/mattermost-operator/blob/master/pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go#L49

For this ticket implement node affinity using the existing field.

Read https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity for more information on node affinity.

**Comment by jesperhansen17** [comment]
Can I look at this one?

**Comment by jwilander** [comment]
That'd be great @jesperhansen17 !

**Comment by ankitrgadiya** [comment]
@jesperhansen17 Are you still working on it? I'd like to pick it too.

**Comment by jesperhansen17** [comment]
Yes @ankitrgadiya, I'm still working on this. Will let you know otherwise.

**Comment by jesperhansen17** [comment]
@ankitrgadiya, go ahead and do this one. Realise I need to get more experience on Kubernetes.

**Comment by ankitrgadiya** [comment]
@jesperhansen17 Sure.
