### ISSUE TITLE
Allow using external S3/MinIO instances with the Mattermost operator

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-server#11822]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17587)

The [Mattermost Operator](https://github.com/mattermost/mattermost-operator) is a Kubernetes operator that manages the lifecycle of a Mattermost installation.

Currently when using the Mattermost operator you must have the minio-operator installed and you must use the Minio instance that creates. Some users may want to use S3 or an externally hosted MinIO instead.

For this ticket update the ClusterInstallation custom resource to allow specifying an external S3/MinIO, similar to how users can specify an external database.

Note that if an external S3/MinIO is provided, the Mattermost operator should be able to run without the minio-operator.

**Comment by jkl5616** [comment]
I'll take this!

**Comment by jwilander** [comment]
Awesome, thanks @jkl5616 !

**Comment by jwilander** [comment]
Hi @jkl5616 just checking on how this ticket is going? Let me know if you need any help

**Comment by jwilander** [comment]
Cloud team is working on this in-house
