### ISSUE TITLE
Dos channel with svg file upload

### ISSUE THREAD

**Issue by NgoHuy** [mattermost/mattermost-server#11824]
I installed mattermost for my team. After that, team member found critical problem with svg render.
After anyone on channel upload malicious svg, mattermost client will be hang forever until close and reopen again.
I attach malicious svg here for debugging.

Best regards,
Severus
[test.zip](https://github.com/mattermost/mattermost-server/files/3475881/test.zip)

**Comment by NgoHuy** [comment]
in system admin, I see the error: 
```
{"level":"error","ts":1565161716.3456411,"caller":"app/file.go:675","msg":"Failed to parse SVG","error":"XML syntax error on line 1: expected /> in element"}
{"level":"error","ts":1565161719.4741485,"caller":"mlog/log.go:172","msg":"msg: TypeError: n.searchInput.blur is not a function row: 1 col: 365762 stack: TypeError: n.searchInput.blur is not a function url: https://teamwork.vietsunshine.com.vn/static/5.8f4edf63ea0d1d376f2f.js","path":"/api/v4/logs"
```

**Comment by amyblais** [comment]
Hi @NgoHuy, please submit vulnerability reports via responsibledisclosure@mattermost.com.

Here is our responsible disclosure policy: https://mattermost.com/security-vulnerability-report/.

**Comment by amyblais** [comment]
Please let me know if you have any issues submitting this report via the email address I linked above,
