### ISSUE TITLE
User count not updated if user automatically joins channel

### ISSUE THREAD

**Issue by hahmadia** [mattermost/mattermost-server#11823]
#### Summary
User count does not update when a user automatically joins a channel.

#### Steps to reproduce
Open a tab and login into your account and wait in the off-topic channel.
Open a tab in incognito and sign up for the same team through the GUI.
After signing up, you should automatically join the off-topic channel.
Notice on the incognito tab, the number of users displayed is 2.
In the first tab you opened it will still display the number of user as 1. This problem persists unless you refresh browser or switch to another channel and back.

#### Expected behavior
When the new user joins on tab 2, the correct number of users should be displayed on both tabs.

#### Possible fixes
When a user automatically joins a channel after signing up, the `user_added` websocket event does not get broadcasted. We should broadcast this message after a user is added to a team.

#### Screenshot
(Notice the discrepancy in the user count in the top right corner) . 
![usercountnotupdate](https://user-images.githubusercontent.com/17804942/62642256-513d4d80-b913-11e9-82ab-5bb84a7f5674.png)

**Comment by amyblais** [comment]
Thank you, opened a ticket here: https://mattermost.atlassian.net/browse/MM-17604.

**Comment by hahmadia** [comment]
@amyblais Update original post with a screenshot. Thanks for creating the ticket.
