### ISSUE TITLE
Search result with 2 characters

### ISSUE THREAD

**Issue by biva** [mattermost/mattermost-server#11833]
The search function is limited to words with 3 characters or more. Words with 2 characters are not searched. Even if I use * to complete the word.

It's a limitation for me. For example, we often use CI fo Commercial Invoice. Looking for "CI" or "CI*" doesn't give any result.

Would it be possible to improve this? I read https://mattermost.atlassian.net/browse/MM-5466 but I did not find any related topic.

Thanks!

**Comment by amyblais** [comment]
Hi @biva, are you on Mysql or postgres? Is Elasticsearch enabled on your server?

**Comment by biva** [comment]
Hi, I'm on Mysql, and Elasticsearch is not enabled (I'm on the team edition, 5.13.0). But I think this behaviour is normal, as far as I read in the documentation (https://docs.mattermost.com/help/getting-started/searching.html)
> Like many search engines, common words such as the, which, and are (known as “stop words”), as well as two-letter and one-letter search terms, are not shown in search because they typically return too many results. See database documentation on MySQL and Postgres for a full list.

**Comment by amyblais** [comment]
It looks to be expected behaviour. I'll close this issue for now, thank you for the feedback!

**Comment by biva** [comment]
@amyblais Even if it's an expected behaviour following the documentation, I think it's a limitation. Isn't it possible to remove it? And allow the search for 2-characters words? Thanks

**Comment by amyblais** [comment]
Hi @biva, you can share improvement feedback on our ideas forum here: https://mattermost.uservoice.com/forums/306457-general. If you're interested in implementing this, please let us know or open a pull request!
