### ISSUE TITLE
Pass ProfilePopover `hide` through to plugin components

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#11842]
The ProfilePopover can be extended in a number of points, but we don't currently give those extensions the power to dismiss the popover. Native components receive the `hide` function callback, and it makes sense to extend this to plugins as well.

JIRA: https://mattermost.atlassian.net/browse/MM-17661

-----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by MatthewDorner** [comment]
I'll take this.

**Comment by lieut-data** [comment]
Thanks, @MatthewDorner!

**Comment by hanzei** [comment]
Thanks for your contribution @MatthewDorner :tada:
