### ISSUE TITLE
Add EnsureChannel helper

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#11845]
Similar to EnsureBot, add an EnsureChannel helper, returning the resulting channel id:

```go
func (p *HelpersImpl) EnsureChannel(channel *model.Channel) (string, error)
```

If the channel already exists, update any “safe” metadata provided by the call, e.g. name, url, description. If the channel is private but was meant to be public (or vice-versa), return an error since it may not be safe to automatically fix this.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-16809

**Comment by ankitrgadiya** [comment]
I'd like to pick it up.

**Comment by lieut-data** [comment]
Terrific! Thanks, @ankitrgadiya :)
