### ISSUE TITLE
Move Docs repository pipeline from travis to circleci

### ISSUE THREAD

**Issue by cpanato** [mattermost/mattermost-server#11853]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17694)

The [docs repository](https://github.com/mattermost/docs) today uses travis ci to build and deploy the docs website.
We would like to move that to circleci as part of our migration to circleci

This ticket is about creating the new pipeline to do the same steps we have for travis but on circleci.

note: you can use the aws-s3 circleci orb for the copy
note2: you can reach [at]cpanato in our community server to talk about the secrets and enable the repository on circleci

**Comment by metanerd** [comment]
I'll take this one.

**Comment by cpanato** [comment]
fixed in https://github.com/mattermost/docs/pull/2932
