### ISSUE TITLE
[Mattermod] Remove the build checks and add the docker image check

### ISSUE THREAD

**Issue by cpanato** [mattermost/mattermost-server#11855]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17696)

[Mattermod](https://github.com/mattermost/mattermost-mattermod) checks and wait for the build become green to create or update the Test servers (see: https://github.com/mattermost/mattermost-mattermod/blob/master/server/spinwick.go#L79) we would like to remove this check and check if the docker image is available. when it is available continue the mattermod process.

To complete this ticket we also need to update the build pipeline for mattermost-server and for mattermost-webapp to push earlier the docker image, we need to build the package and if we were successful to build we build the docker and push the image.

references: 
mattermost-server: https://github.com/mattermost/mattermost-server/blob/master/build/Jenkinsfile.pr#L262
mattermost-webapp: https://github.com/mattermost/mattermost-webapp/blob/master/.circleci/config.yml#L170

**Comment by ankitrgadiya** [comment]
I want to take this up.

**Comment by cpanato** [comment]
@ankitrgadiya go for it
