### ISSUE TITLE
SMTP "Test Connection" button always reports success.

### ISSUE THREAD

**Issue by malteklaassen** [mattermost/mattermost-server#11850]
#### Summary
"Test Connection" button for SMTP appears to do nothing but still reports "No errors were reported while sending an email. Please check your inbox to make sure.".

#### Steps to reproduce
Version: Mattermost Server 5.13.2
OS: Ubuntu 18.04
Browser used: Firefox 68.0.1

1. Install as per instructions at https://docs.mattermost.com/install/install-ubuntu-1804.html (using mysql).
2. Create system_admin account and log in using a browser.
3. Go to System Console -> Environment -> SMTP
4. Enter server details (in my case the intended settings would be localhost port 587 with smtp authentication and STARTTLS, but that appears to be irrelevant).
5. Click "Save"
6. Click "Test Connection".
(order of 5 and 6 can be reversed for the same beaviour)

#### Expected behavior
The Mattermost Server should attempt a connection to the specified server and send a testmail.

#### Observed behavior (that appears unintentional) 
Nothing happens, apart from the "No errors were reported while sending an email. Please check your inbox to make sure."-message being displayed.
When testing with a real (and otherwise working) postfix instance running on the same machine no connection is made/shown in the mailserver logs. When sniffing the network traffic on the machine hosting the mattermost server there is no traffic using the specified port.

When entering non-existing domains with arbitrary ports still no connection attempt is made but the "No errors were reported while sending an email. Please check your inbox to make sure."-message is still displayed.

Mattermost debug log (test mail requested e.g. at `1565443534.5962827`):
```
{"level":"info","ts":1565443504.899063,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'"}
{"level":"info","ts":1565443504.9035242,"caller":"app/server_app_adapters.go:58","msg":"Server is initializing..."}
{"level":"debug","ts":1565443504.9106047,"caller":"utils/html.go:31","msg":"Parsing server templates at /opt/mattermost/templates"}
{"level":"info","ts":1565443504.9138322,"caller":"sqlstore/supplier.go:224","msg":"Pinging SQL master database"}
{"level":"debug","ts":1565443505.054388,"caller":"sqlstore/preference_store.go:41","msg":"Deleting any unused pre-release features"}
{"level":"info","ts":1565443505.0603514,"caller":"filesstore/localstore.go:33","msg":"Able to write files to local storage."}
{"level":"debug","ts":1565443505.061809,"caller":"utils/license.go:84","msg":"We could not find the license key in the database or on disk at /opt/mattermost/config/mattermost.mattermost-license"}
{"level":"info","ts":1565443505.062199,"caller":"app/license.go:41","msg":"License key from https://mattermost.com required to unlock enterprise features."}
{"level":"info","ts":1565443505.0669098,"caller":"mlog/log.go:164","msg":"Starting up plugins"}
{"level":"info","ts":1565443507.717946,"caller":"sqlstore/post_store.go:1279","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}
{"level":"debug","ts":1565443508.5811563,"caller":"plugin/hclog_adapter.go:33","msg":"starting plugin","plugin_id":"com.mattermost.nps","wrapped_extras":"pathplugins/com.mattermost.nps/server/dist/plugin-linux-amd64args[plugins/com.mattermost.nps/server/dist/plugin-linux-amd64]"}
{"level":"debug","ts":1565443508.5860217,"caller":"plugin/hclog_adapter.go:33","msg":"plugin started","plugin_id":"com.mattermost.nps","wrapped_extras":"pathplugins/com.mattermost.nps/server/dist/plugin-linux-amd64pid1816"}
{"level":"debug","ts":1565443508.586094,"caller":"plugin/hclog_adapter.go:33","msg":"waiting for RPC address","plugin_id":"com.mattermost.nps","wrapped_extras":"pathplugins/com.mattermost.nps/server/dist/plugin-linux-amd64"}
{"level":"debug","ts":1565443508.6032338,"caller":"plugin/hclog_adapter.go:33","msg":"plugin address","plugin_id":"com.mattermost.nps","wrapped_extras":"address/tmp/plugin795508818networkunixtimestamp2019-08-10T15:25:08.602+0200"}
{"level":"debug","ts":1565443508.6033466,"caller":"plugin/hclog_adapter.go:33","msg":"using plugin","plugin_id":"com.mattermost.nps","wrapped_extras":"version1"}
{"level":"debug","ts":1565443508.6088655,"caller":"mlog/sugar.go:15","msg":"Activating NPS plugin","plugin_id":"com.mattermost.nps"}
{"level":"info","ts":1565443508.6139731,"caller":"mlog/sugar.go:19","msg":"Ensuring Surveybot exists","plugin_id":"com.mattermost.nps"}
{"level":"debug","ts":1565443508.6198235,"caller":"mlog/sugar.go:15","msg":"Failed to create Surveybot. Attempting to find existing one.","plugin_id":"com.mattermost.nps","err":"SqlUserStore.Save: store.sql_user.save.username_exists.app_error, user_id=njhtkfx147rg7p5i8ctzfsqkmr, Error 1062: Duplicate entry 'surveybot' for key 'Username'"}
{"level":"debug","ts":1565443508.6251822,"caller":"mlog/sugar.go:15","msg":"Found Surveybot","plugin_id":"com.mattermost.nps"}
{"level":"debug","ts":1565443508.6268826,"caller":"mlog/sugar.go:15","msg":"NPS plugin activated","plugin_id":"com.mattermost.nps"}
{"level":"debug","ts":1565443508.6289124,"caller":"plugin/health_check.go:51","msg":"Plugin health check job starting. Sending health check pings every 30s seconds."}
{"level":"info","ts":1565443508.6289737,"caller":"app/server.go:213","msg":"Current version is 5.13.0 (5.13.2/Wed Jul 24 17:25:26 UTC 2019/9a8b0906fdbf2c2a309db2400f4bcc5902800e2c/1ab74b3ea1137c385e03a9982dce917a4128f903)"}
{"level":"info","ts":1565443508.629457,"caller":"app/server.go:214","msg":"Enterprise Enabled: true"}
{"level":"info","ts":1565443508.6298695,"caller":"app/server.go:216","msg":"Current working directory is /opt/mattermost"}
{"level":"info","ts":1565443508.630175,"caller":"app/server.go:217","msg":"Loaded config","source":"file:///opt/mattermost/config/config.json"}
{"level":"debug","ts":1565443508.7265205,"caller":"jobs/schedulers.go:29","msg":"Initialising schedulers."}
{"level":"info","ts":1565443508.7266994,"caller":"jobs/workers.go:68","msg":"Starting workers"}
{"level":"info","ts":1565443508.728003,"caller":"app/server.go:413","msg":"Starting Server..."}
{"level":"info","ts":1565443508.7287889,"caller":"app/server.go:479","msg":"Server is listening on [::]:8065"}
{"level":"debug","ts":1565443508.742833,"caller":"api4/plugin.go:20","msg":"EXPERIMENTAL: Initializing plugin api"}
{"level":"info","ts":1565443508.7444937,"caller":"app/web_hub.go:75","msg":"Starting 2 websocket hubs"}
{"level":"debug","ts":1565443508.7450888,"caller":"web/web.go:28","msg":"Initializing web routes"}
{"level":"debug","ts":1565443508.7454562,"caller":"utils/subpath.go:84","msg":"Rewriting static assets","from_subpath":"/","to_subpath":"/"}
{"level":"debug","ts":1565443508.764184,"caller":"web/static.go:31","msg":"Using client directory at /opt/mattermost/client"}
{"level":"info","ts":1565443508.7669535,"caller":"commands/server.go:105","msg":"Sending systemd READY notification."}
{"level":"debug","ts":1565443508.7718801,"caller":"sqlstore/session_store.go:227","msg":"Cleaning up session store."}
{"level":"debug","ts":1565443508.7721326,"caller":"sqlstore/tokens_store.go:72","msg":"Cleaning up token store."}
{"level":"debug","ts":1565443508.772351,"caller":"sqlstore/command_webhook_store.go:88","msg":"Cleaning up command webhook store."}
{"level":"debug","ts":1565443508.7725668,"caller":"migrations/worker.go:44","msg":"Worker started","worker":"Migrations"}
{"level":"debug","ts":1565443508.7725883,"caller":"scheduler/worker.go:36","msg":"Worker started","worker":"Plugins"}
{"level":"debug","ts":1565443508.7726066,"caller":"jobs/jobs_watcher.go:39","msg":"Watcher Started"}
{"level":"info","ts":1565443508.772641,"caller":"jobs/schedulers.go:72","msg":"Starting schedulers."}
{"level":"debug","ts":1565443508.773703,"caller":"app/web_hub.go:434","msg":"Hub for index 0 is starting with goroutine 3917"}
{"level":"debug","ts":1565443508.773824,"caller":"app/web_hub.go:434","msg":"Hub for index 1 is starting with goroutine 3918"}
{"level":"debug","ts":1565443508.7755191,"caller":"jobs/schedulers.go:167","msg":"Next run time for scheduler MigrationsScheduler: 2019-08-10 15:26:08.775505668 +0200 CEST m=+64.281074240"}
{"level":"debug","ts":1565443508.7763443,"caller":"jobs/schedulers.go:167","msg":"Next run time for scheduler PluginsScheduler: 2019-08-11 15:25:08.776336598 +0200 CEST m=+86404.281905171"}
{"level":"debug","ts":1565443509.011233,"caller":"web/handlers.go:58","msg":"GET - /api/v4/websocket"}
{"level":"debug","ts":1565443509.0583096,"caller":"web/handlers.go:58","msg":"GET - /api/v4/plugins/webapp"}
{"level":"debug","ts":1565443509.0694838,"caller":"web/handlers.go:58","msg":"GET - /api/v4/users/me/teams/k3a5g9sympbdxpx4hwuizb87qh/channels"}
{"level":"debug","ts":1565443509.0727582,"caller":"web/handlers.go:58","msg":"GET - /api/v4/users/me/teams/k3a5g9sympbdxpx4hwuizb87qh/channels/members"}
{"level":"debug","ts":1565443509.0748963,"caller":"web/handlers.go:58","msg":"GET - /api/v4/channels/xhifk7zdrjgdfgcsyfnb6ts58h/posts"}
{"level":"debug","ts":1565443509.0805905,"caller":"web/handlers.go:58","msg":"GET - /api/v4/users/me/teams/unread"}
{"level":"debug","ts":1565443510.3528497,"caller":"web/handlers.go:58","msg":"GET - /api/v4/websocket"}
{"level":"debug","ts":1565443510.4061067,"caller":"web/handlers.go:58","msg":"GET - /api/v4/plugins/webapp"}
{"level":"debug","ts":1565443515.520599,"caller":"web/handlers.go:58","msg":"GET - /api/v4/logs"}
{"level":"debug","ts":1565443525.130306,"caller":"web/handlers.go:58","msg":"POST - /api/v4/email/test"}
{"level":"debug","ts":1565443525.1304817,"caller":"mlog/log.go:160","msg":"CSRF Header check failed for request - Please upgrade your web application or custom app to set a CSRF Header"}
{"level":"debug","ts":1565443532.5125432,"caller":"web/handlers.go:58","msg":"PUT - /api/v4/config"}
{"level":"debug","ts":1565443532.5128522,"caller":"mlog/log.go:160","msg":"CSRF Header check failed for request - Please upgrade your web application or custom app to set a CSRF Header"}
{"level":"debug","ts":1565443532.535602,"caller":"jobs/workers.go:108","msg":"Workers received config change."}
{"level":"debug","ts":1565443532.5356817,"caller":"jobs/schedulers.go:185","msg":"Schedulers received config change."}
{"level":"debug","ts":1565443532.544616,"caller":"jobs/schedulers.go:167","msg":"Next run time for scheduler MigrationsScheduler: 2019-08-10 15:26:32.544600673 +0200 CEST m=+88.050169313"}
{"level":"debug","ts":1565443532.5466743,"caller":"jobs/schedulers.go:167","msg":"Next run time for scheduler PluginsScheduler: 2019-08-11 15:25:32.546658743 +0200 CEST m=+86428.052227370"}
{"level":"debug","ts":1565443534.5962827,"caller":"web/handlers.go:58","msg":"POST - /api/v4/email/test"}
{"level":"debug","ts":1565443534.596485,"caller":"mlog/log.go:160","msg":"CSRF Header check failed for request - Please upgrade your web application or custom app to set a CSRF Header"}
{"level":"debug","ts":1565443537.1217308,"caller":"web/handlers.go:58","msg":"GET - /api/v4/logs"}
```

I would include the pcap and the mailserver log but they are just empty :wink:

#### Possible fixes
-

**Comment by amyblais** [comment]
Hi @malteklaassen, our QAs tested this and couldn't reproduce this issue as described; they see expected behaviour on upcoming v5.14 release and also on v5.12.5:

 - With valid SMTP config: they receive the verification email and the success message as expected when testing the connection.
 - With invalid SMTP credentials they see error on testing connection and do not receive the email. ``Connection unsuccessful: Connection unsuccessful: SendMail: Failed to authenticate on SMTP server, 535 Authentication Credentials Invalid - undefined``.
 - With invalid SMTP server they see error on testing connection and do not receive the email
Connection unsuccessful: ``Connection unsuccessful: SendMail: Failed to open TLS connection, dial tcp: lookup dockerhost: Temporary failure in name resolution - undefined``.

Wondering if you are open to sharing any additional information such as your config settings?

**Comment by malteklaassen** [comment]
Of course. I hope I managed to remove all secrets and identifiers ;)

[mattermost-config.json.txt](https://github.com/mattermost/mattermost-server/files/3504461/mattermost-config.json.txt)

**Comment by amyblais** [comment]
@malteklaassen 

1. You could try setting ``SendEmailNotifications`` to True.
2. You could take a look at these troubleshooting steps: https://docs.mattermost.com/install/smtp-email-setup.html#checking-your-smtp-server-is-reachable.
3. There is a bug to be fixed in v5.14 that might affect this: https://mattermost.atlassian.net/browse/MM-17393.

Let me know if none of the above help and we'll continue to troubleshoot.

**Comment by malteklaassen** [comment]
Setting `SendEmailNotifications` to `True` does indeed fix the problem, thank you :)
It seems a bit counterintuitive that the simple connection test would depend on the `SendEmailNotifications` setting though & it definitely shouldn't just fail silently while reporting success.
Have a wonderful end of the week.

**Comment by aleqx** [comment]
I chased my tail for quite a while until I found this thread. Frustrating. I'd like to make a plea to the devs to **please** give a red **error** instead of "success" when clicking "Test Connection". Something like: "Error: You need to enable Email Notifications in *Site Configuration > Notifications > Enable Email Notifications* in order to activate and test SMTP settings." ... instead of saying "No errors were reported ..." on green.

The latter is highly misleading - and time wasting for everyone, including yourselves having to deal with these reports :)

**Comment by aleqx** [comment]
In fact, this is an actual bug, because the config page for *Site Configuration > Notifications > Enable Email Notifications* says `When false, email invitations and user account setting change emails are still sent as long as the SMTP server is configured.`

That's actually not true. If set to false then it doesn't actually work, and the "Test Connection" button doesn't do anything either.

**Comment by agnivade** [comment]
Indeed, this can be confusing. I have filed https://mattermost.atlassian.net/browse/MM-26021 to track this. Please feel free to subscribe to that.

**Comment by aleqx** [comment]
That's a step in the right direction. However, see my post above: even with a less misleading error message, it would still be a bug and a problem as SMTP is supposed to work even when notifications are disabled.

**Comment by agnivade** [comment]
That's right, I haven't looked into that part. Would you be open to filing a new issue for that? This feels like it needs to be tracked separately.

**Comment by aleqx** [comment]
I think the current issue could simply be reopen given it wasn't actually resolved. There is another pone which is caused by the same underlying issue: https://github.com/mattermost/mattermost-docker/issues/408. Opening a third one would probably become even more confusing.

**Comment by agnivade** [comment]
I think the current issue is what I opened the JIRA ticket for. The issue that you mention is also related but is a different bug IMO, as they deal with different things. Reopening this one might cause some confusion because there are actually 2 issues here.

I agree that the docker issue can be closed. The JIRA ticket that I created, along with the new issue should track both these problems.

Thanks.

**Comment by aleqx** [comment]
What I'm saying is that the one you opened isn't the problem as SMTP should work regardless.

**Comment by agnivade** [comment]
Ok, perhaps I am not able to understand you correctly. From what I understand you reported 2 issues- 

> That's actually not true. If set to false then it doesn't actually work, and the "Test Connection" button doesn't do anything either.

I had opened an issue for the second part.

In any case, I opened a ticket to track the first problem here: https://mattermost.atlassian.net/browse/MM-26033. Please feel free to add your observations there.

**Comment by qnxor** [comment]
To re-explain: there is only one issue here: the fact that SMTP doesn't work if notifications are disabled. It should ALWAYS work. When you fix that, the other becomes a non-issue.

**Comment by agnivade** [comment]
That's correct. The 2 issues I created are more of specific work items to fix this. But overall, what you said is right.
