### ISSUE TITLE
Mark manifest.[go|js] as a generated file

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#11862]
The `manifest.go` and `manifest.js` files in the [starter plugin](https://github.com/mattermost/mattermost-plugin-starter-template) should leverage a `.gitattributes` file to configure `linguist-generated=true` and mark it as a generated file. Include a human readable comment in each file (by updating the manifest tool generating same) to the effect that this file is generated from the manifest.json in the root.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-16814

**Comment by ethervoid** [comment]
@lieut-data I'd like to pick this one

**Comment by ethervoid** [comment]
@lieut-data PR done, wait for review :)

**Comment by lieut-data** [comment]
Thanks, @ethervoid!
