### ISSUE TITLE
Add top-level `recover` to prevent a plugin panic from crashing the server

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#11863]
In discussing [https://github.com/mattermost/mattermost-server/pull/11276](https://github.com/mattermost/mattermost-server/pull/11276), we identified the need to intercept panics from code triggered by plugin APIs and recover from them more generally. Use the code in the linked PR to illustrate the problem, but the solution should be generic so as to prevent the server from crashing when a plugin invokes invalid code through the API.

For clarity, it is not necessary to intercept panics within the plugin process itself – that is ultimately the responsibility of the author of the plugin. This ticket is exclusively to prevent the server from crashing by being told to invoke an invalid code path.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-17377

**Comment by jozuenoon** [comment]
I'm up for grabs :)

**Comment by hanzei** [comment]
Thanks @jozuenoon :+1:

**Comment by lieut-data** [comment]
It turns out to be impossible to add such a top-level recover given the translation across `net/rpc`.
