### ISSUE TITLE
Formatting for quoted text

### ISSUE THREAD

**Issue by alexappsnet** [mattermost/mattermost-server#11861]
When answering the questions with > quoting it shows both the question and answer with the same text style and same alignment. It is hard to tell where the question ends and where the answer starts.

![image](https://user-images.githubusercontent.com/53881940/62881710-fd0ce180-bcf5-11e9-989a-6c9b3bebc055.png)

Result is:

![image](https://user-images.githubusercontent.com/53881940/62881738-0eee8480-bcf6-11e9-9948-7d5a682b93e8.png)

**Comment by amyblais** [comment]
Hi @alexappsnet, do you see the same issue if you leave a space between the question and the answer?

**Comment by alexappsnet** [comment]
With the empty line, it is formatting just perfect! But the problem is that I am not the writer in our mattermost. I am the reader. So it would be nice if it can format even without an empty line.

![image](https://user-images.githubusercontent.com/53881940/62885988-c9cf5000-bcff-11e9-87f3-bebdd5e395a3.png)

**Comment by amyblais** [comment]
@alexappsnet, I believe this has always existed this way, so I'd encourage you to open an improvement request on our new ideas forum here: https://mattermost.uservoice.com/forums/306457-general. If you're interested in implementing this improvement, let us know.

**Comment by alexappsnet** [comment]
It seems this is a feature. A single > sign is enough in first line is enough. All multi-line text after this character is assumed as "quoted text". And the answer should be after the empty line. So, the empty line is the separator! Now I get it. But I should say it is confusing. It would be nice to have it natural without reading instructions.
