### ISSUE TITLE
Getting text/plain MIME type from .js of any Plugin

### ISSUE THREAD

**Issue by Akito13** [mattermost/mattermost-server#11869]
#### Summary
JavaScript related MIME Type error, that does not make any sense.

#### Steps to reproduce
1. Change `Directory` and `ClientDirectory` of subsection `Plugins` within `config/config.json`
 from `./plugins` and `client/plugins` to `/opt/mattermost/plugins` and `/opt/mattermost/client/plugins`.
2. Change it back.

#### Expected behavior
Everything should work normally. I changed back what I did change, so the previous behaviour should be restored.

#### Observed behavior (that appears unintentional) 
```
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). 4 mattermost.url:1:1
Loading com.mattermost.nps plugin index.js:92:16
Loading github plugin index.js:92:16
The resource from “https://mattermost.url/static/plugins/com.mattermost.nps/com.mattermost.nps_22a1fb0412ededf3_bundle.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff). github
Loading failed for the <script> with source “https://mattermost.url/static/plugins/com.mattermost.nps/com.mattermost.nps_22a1fb0412ededf3_bundle.js”. github:1:1
The resource from “https://mattermost.url/static/plugins/github/github_2a2194694636b8f0_bundle.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff). github
Loading failed for the <script> with source “https://mattermost.url/static/plugins/github/github_2a2194694636b8f0_bundle.js”. github:1:1
```

#### Possible fixes
It has something to do with plugins in general. **Not** a specific one.

Excluded causes:
* permissions
* wrong path(s)
* configuration error
* reverse proxy

Disabling plugins, plugin by plugin, makes the website work without plugins, again. It has to be disabled plugin by plugin, just disabling the plugin feature does not make it work.

I already restored from a backup and it still does not work. ???

**Comment by amyblais** [comment]
@hanzei / @kosgrz Do you know if there is a bug here?

**Comment by Akito13** [comment]
I left the server running over night, returned to it, switched plugins back on within the System Console, restarted the server and it works now. (This way did not work before.) I have no idea what happened, as I didn't touch the server during that time. I don't know if this is closable, as it's not clear whether this issue was directly connected to Mattermost or not. It's getting weirder and weirder.

**Comment by svelle** [comment]
@Akito13 what Mattermost server version are you running?

Also could you provide some info on the machine where the server is running on? What OS is it and more important are the mime-types setup correctly?

**Comment by amyblais** [comment]
@Akito13 I'll close this for now as there hasn't been further updates for a while. Please re-open this issue if the issue persists,

**Comment by E-Learning-FHDO** [comment]
If anyone else stumbles over this problem, it helped me to delete the content under /var/cache/nginx/ and restart the nginx server.
