### ISSUE TITLE
System Console > Search doesn't return results for individual plugins

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#11897]
The system console supports searching for settings, but doesn’t currently return any plugin-specific settings. The `generateIndex` method currently only examines the static admin definition, and doesn’t take into account the loaded plugins and their respective settings.

To remedy this, it will be necessary to pass the plugin schemas when invoking `generateIndex`. See the `makeGetPluginSchema` for how to render a specific plugin’s schema: this method should be reused out to create the necessary structure modelling the schema for all loaded plugins.

Additionally, the index is currently cached in the `onFilterChange` method of the `AdminSidebar`:

```javascript
        if (this.idx === null) {
            this.idx = generateIndex(this.context.intl);
        }
```

It will be necessary to invalidate this cache whenever a plugin has been loaded.

Feel free to install the  to iterate during development. Be sure to test with more than one plugin.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-16313

**Comment by pradeepmurugesan** [comment]
I can work on this ticket ✔️

**Comment by hanzei** [comment]
Thanks @pradeepmurugesan :+1:

**Comment by pradeepmurugesan** [comment]
Proposed a solution and the implementation idea in the community. Waiting for the discussion and approval. https://community.mattermost.com/core/pl/1t6xg8wnyfbk3bsmhxuopwhqie

**Comment by lieut-data** [comment]
Thanks so much, @pradeepmurugesan!
