### ISSUE TITLE
Add support for plugins to close the right-hand sidebar

### ISSUE THREAD

**Issue by marianunez** [mattermost/mattermost-server#11893]
Currently, plugins can override the right-hand sidebar (RHS) with their custom component using the [registerRightHandSidebarComponent](https://developers.mattermost.com/extend/plugins/webapp/reference/#registerRightHandSidebarComponent) which returns a redux action they can dispatch to open the RHS.

The webapp should be extended to give the plugins the ability to also close the RHS as well by:

- Returning the action to close the RHS from `registerRightHandSidebarComponent`

- The action should only be allowed to close the RHS if the component displayed is from the plugin dispatching the action. For example: a plugin opens the RHS then a user clicks on search or mentions which updates the RHS, if the plugin calls close RHS should have no effect. 

Additionally, update the [plugin-demo](https://github.com/mattermost/mattermost-plugin-demo) to show how to close the RHS by clicking the action button in the header after it was previously open. 

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-17810

**Comment by Lisenish** [comment]
Can I take this one?

**Comment by marianunez** [comment]
Sure! Thanks @Lisenish

**Comment by Lisenish** [comment]
@marianunez Please take a look. Also, I have one question in MR about support of that action in the plugin.

**Comment by marianunez** [comment]
Thanks @Lisenish! What is the question you have?

**Comment by Lisenish** [comment]
@marianunez I've found that I forgot to submit review comment in the night yesterday 🤦‍♂. Here it is https://github.com/mattermost/mattermost-plugin-demo/pull/60#discussion_r316914531 but @lieut-data already addressed that issue in some way too.
