### ISSUE TITLE
deleted user continues to be shown until restart

### ISSUE THREAD

**Issue by joriki** [mattermost/mattermost-server#11907]
#### Summary
When a user is deleted via the command line, messages about them joining channels persist until the database is restarted.
#### Steps to reproduce
- Using Mattermost 5.13.2 and mysql 5.7.27:
- Create a new user. (The user is automatically added to the town square channel, and a message that they joined appears there.)
- Delete the user via the command line ([`mattermost user delete new_user`](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-user-delete)).

#### Expected behavior
All traces of the user should immediately disappear.

#### Observed behavior (that appears unintentional) 
The message that the user joined the town square remains visible to other users for quite some time (in my case about a quarter of an hour), even though MySQLWorkbench shows that it's been deleted from the `Posts` table of the database. It disappears if the database server is restarted.

**Comment by amyblais** [comment]
Hi @joriki, do you also still see the deleted user in member lists such as channel member lists until after restart?

Does the deleted user disappear when reloading or deleting cache or only when you restart the server?

By default, the client(s) in which your sessions are connected on do not get automatically refreshed to clear the existing cache after you deleted the user. In this way it is normal to see the deleted user until after you reload the client.

**Comment by joriki** [comment]
Hi @amyblais ,

a simple page reload is enough to remove the user from the town square channel member list.

The message that the user joined persists after a page reload and even after "Clear Cache and Reload". It only disappears when the server is restarted. (I'd originally removed it by restarting the database server (`service mysql restart`); I just noticed that it's also removed by a mattermost server restart (`service mattermost restart`).)

**Comment by ahmaddanialmohd** [comment]
Hello, @joriki 

I have tried to reproduce this issue on Mattermost version **5.14.1** and can confirm that a page reload removes the user and the user's posts from the channel. No server restart was required.

Can you please confirm if you are still seeing the issue after an upgrade to the latest version?

**Comment by amyblais** [comment]
I'll close this for now as there hasn't been updates on this for a while. Please re-open this if the suggestion above doesn't help,
