### ISSUE TITLE
Add support for introductory markdown paragraph in interactive dialogs

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#11902]
Interactive Dialogs allow integrations to receive some form-styled input from users and have that input submitted back to the integration. To allow integrations to show more information in the dialog, dialogs should have an optional introduction message. This would be placed above the first element and below the title.

The `model.Dialog` struct should be extended in the server with an `IntroductionText` `string` element expecting markdown formatted text. The webapp and mobile repositories should be updated to render paragraph. Older versions of the webapp or mobile app should be verified to simply ignore this field without error.

For more information about interactive dialogs, see [https://docs.mattermost.com/developer/interactive-dialogs.html](https://docs.mattermost.com/developer/interactive-dialogs.html).

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-15219

**Comment by reflog** [comment]
@tgkouras - good luck! Removing 'Up for Grabs' label.

**Comment by hanzei** [comment]
Thank you very much for implementing this feature @tgkouras :tada:
