### ISSUE TITLE
Use github.com/banzaicloud/k8s-objectmatcher for all resource reconciliation comparisons

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-server#11919]
The [Mattermost Operator](https://github.com/mattermost/mattermost-operator) is a Kubernetes operator that manages the lifecycle of a Mattermost installation.

Part of the job of the operator is to make sure that all resources that the operator cares about for its installations/deployments are correct and up to date. If they are not correct or up to date, then we reconcile them. We do comparisons of the resources frequently using some custom code but there is a library for this that is more complete, github.com/banzaicloud/k8s-objectmatcher.

For this ticket replace all comparisons like this https://github.com/mattermost/mattermost-operator/blob/master/pkg/controller/clusterinstallation/minio.go#L68 with the k8s-objectmatcher from banzaicloud.

This pull request has an example of it being used for one resource https://github.com/mattermost/mattermost-operator/pull/47/files.

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16722)

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by jozuenoon** [comment]
I'm up for grabs!

**Comment by jwilander** [comment]
Awesome, thanks @jozuenoon !
