### ISSUE TITLE
macOS App crash Internal error: webContents

### ISSUE THREAD

**Issue by Remmi-Demmi** [mattermost/mattermost-server#11911]
The mac app crashes on startup with a prompt window:

The Mattermost app quit unexpectedly. Click "Show Details" to learn more or "Reopen" to open the application again.
Internal error: webContents 'crashed' event has been emitted
->details:
Application: Mattermost 4.2.3
Platform: Darwin 18.7.0 x64
Error: webContents 'crashed' event has been emitted
    at WebContents.mainWindow.webContents.on (/Applications/Mattermost.app/Contents/Resources/app.asar/main_bundle.js:601:11)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7) 

It used to work for the first day (no further update was installed). Next time i booted up my mac the error message occured and the app stopped working ever since.
The Browser version works as intended.

![image](https://user-images.githubusercontent.com/54276334/63270081-bab84700-c297-11e9-96e3-817ea73350f7.png)

Any help is appreciated!
Running the latest version of MacOS: Mojave 10.14.6 (18G87)

**Comment by amyblais** [comment]
Hi @Remmi-Demmi,

1. Have you clicked “Show Details” on the dialog to get logs?
2. Please try clearing the cache via CTRL+SHIFT+R (or View > Clear Cache and Reload).
3. Please try going to App Settings (via CTRL+COMMA or File > Settings) and unselect hardware acceleration.

**Comment by Remmi-Demmi** [comment]
Hi @amyblais 
Thank you for your reply. 
i posted the details in the original message:

Application: Mattermost 4.2.3
Platform: Darwin 18.7.0 x64
Error: webContents 'crashed' event has been emitted
at WebContents.mainWindow.webContents.on (/Applications/Mattermost.app/Contents/Resources/app.asar/main_bundle.js:601:11)
at emitTwo (events.js:126:13)
at WebContents.emit (events.js:214:7)

I cant access the settings due to the prompt message and View/clear cache is greyed out. 
I tried deleting the app with AppCleaner, did a restart, reinstalled the app but the problem persists.

**Comment by Remmi-Demmi** [comment]
UPDATE: So it seems the app crashes once i have plugged in my external monitor (DP to usb-c) once its disconnected the app works as intended. i made sure to untick hardware acceleration and cleared the cache.
The problem is reproducible when i plug in my external monitor.

**Comment by amyblais** [comment]
@Remmi-Demmi What Mattermost server version are you on?

**Comment by sudheerDev** [comment]
@Remmi-Demmi Can you check if you can replicate the issue on browser as well?  if it originates from webapp we can get better stack trace that way.

**Comment by Remmi-Demmi** [comment]
@amyblais sry for the late reply. not sure how to find out. We are a company and i guess we run it on one of our servers. So far only i have this issue. the macOS app runs fine for others. If u need further details on the server i can consult our IT guys.
in the webapp it shows this info:

Mattermost Team Edition
All your team communication in one place, instantly searchable and accessible anywhere.

Mattermost Version: 5.12.4
Database Schema Version: 5.12.0
Database: postgres

@sudheerDev the browser version is running fine.

**Comment by sudheerDev** [comment]
@Remmi-Demmi Thanks for the report. Sorry for the delayed reply. 

Couple more questions. 
Is this specific to any channel?.
I see that your desktop screen is 4k. Can you scale down the resolution to say full HD and see if you can repo this?

**Comment by Remmi-Demmi** [comment]
@sudheerDev Hi! Sorry to replay so late. 
In the meantime i just swapped my screen which solved the issue for me. Its the same screen model so i doubt this was a hardware related issue. The screen resolution is at 1440p here (same as the other screen i used)
Since i dont have the screen anymore i cant try a lower res to repo the issue. sorry for that. 
All i can say is that i didnt change any drivers or cables and the screen works well now. i guess it was due to a faulty/broken software on the screen that messed up macOS/Mattermost. Whats weird is that both screens use the same software version and are up to date. i even reset the old screen.  anyways, changing the screens solved it and everything works as intended. 
If u should have further questions i'll be happy (and try) to asnwer them :)

**Comment by amyblais** [comment]
Thank you, I'll close this for now as the issue seems to be resolved,
