### ISSUE TITLE
Enforce minimum server version comment in `plugin/api.go`.

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#11910]
In `plugin/api.go`, we document the minimum required server version to use an API, e.g.:

```go
// UpdateUserActive deactivates or reactivates an user.
//
// Minimum server version: 5.8
UpdateUserActive(userId string, active bool) *model.AppError
```

This means that the API was first added to Mattermost 5.8, and simply won't be available in earlier versions. 

Let's add a build-check that ensures this comment is present and well formatted as the last comment prior to all methods on the `API` interface. Methods without an explicit comment are implicitly supported in Mattermost 5.2 and later and should be updated as part of this ticket to be explicit. Once this issue is resolved, new API methods without a well-formed minimum server version comment should fail the build.

Use Go reflection to solve this problem. Do not rely on grep.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-17889

**Comment by pbitty** [comment]
Hello.  I am interested in working on this issue.  May I claim it?

**Comment by hanzei** [comment]
Surely @pbitty, thanks for working on this :+1:

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/11941

**Comment by lieut-data** [comment]
Thanks again, @pbitty!

**Comment by pbitty** [comment]
No prob!
