### ISSUE TITLE
Expose unsanitized configuration to plugins

### ISSUE THREAD

**Issue by ali-farooq0** [mattermost/mattermost-server#11926]
The `GetConfig` plugin API currently sanitizes the config (https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go#L81), removing database credentials, etc.

Let's expose a `GetUnsanitizedConfig` that does not have this restriction. Note that it would be unsafe to change the behaviour of GetConfig as it exists today, in case plugins happen to forward this data to clients, hence the proposal for a new API.

Looking to expand Plugin API here: https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go#L16

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17911)

-----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by rvillablanca** [comment]
I have a little time so I'd like to take this task
