### ISSUE TITLE
Slack import puts images in the wrong place

### ISSUE THREAD

**Issue by forkwhilefork** [mattermost/mattermost-server#11927]
#### Summary
Importing a Slack archive (including attachments pulled in with the slack-advanced-exporter) puts the attachments in the wrong place and owned by the wrong user.

#### Steps to reproduce
Version 5.14.0
1. export a Slack workspace to a zip file
2. use the slack-advanced-exporter to add the emails and attachments
3. use the Mattermost CLI to import this archive
4. try to look at pictures in a Mattermost channel

#### Expected behavior
Images should appear in messages as normal.

#### Observed behavior (that appears unintentional) 
Images do not appear in chat:
![image](https://user-images.githubusercontent.com/1574946/63398281-14556a00-c39b-11e9-85ff-9cf374f51ff3.png)
The following message can be observed in the browser console:
![image](https://user-images.githubusercontent.com/1574946/63398339-41098180-c39b-11e9-9e2c-e7240e2c5ef9.png)
I have Mattermost installed in `/opt/mattermost`. Images that appear correctly (i.e. ones in posts that were not imported from Slack) exist in `/opt/mattermost/data`. Images from the imported posts exist in `/opt/mattermost/bin/data` and are owned by `root` (which is the user from which I ran the import). I can resolve this problem by copying the files to the correct location and chowning them to the Mattermost user.

There are no errors during the import process relating to these images.

#### Possible fixes
I'm not sure where the import code lives (or if it's publicly accessible), but I expect this will be a simple matter of putting the files in the correct place.

**Comment by amyblais** [comment]
@svelle Do you know if this is related to the new feature and if there is a bug here?

**Comment by svelle** [comment]
@amyblais not necessarily. I've had other customers use the importer just fine without any issues. Maybe it's dependant on from where the command was run. At least it looks to me from the paths noted above. 

I'll try and repro tomorrow.

**Comment by forkwhilefork** [comment]
I believe I ran the command from `/root`, if that helps.

**Comment by svelle** [comment]
@forkwhilefork I tested this locally and can confirm that the data is placed in the directory from which the command is called (e.g. /root/ if run as root user from home). 
I'll open an issue for this and we'll see how we'll handle it from there.

Thanks again for reporting this!

**Comment by svelle** [comment]
> In your bug report, please also note that the files are owned by the user that runs the command. I had to chown the files to the Mattermost user before they would appear correctly in the client.

Bug report can be found [here](https://mattermost.atlassian.net/projects/MM/issues/MM-18061)

Running the mattermost binary as root is not recommended, though.

**Comment by amyblais** [comment]
Documentation has been updated with this PR: https://github.com/mattermost/docs/pull/2968.

**Comment by amyblais** [comment]
Closing as this was documented and the Jira ticket was closed as won't fix.
