### ISSUE TITLE
Add support to use AWS S3 

### ISSUE THREAD

**Issue by cpanato** [mattermost/mattermost-server#11923]
The [Mattermost Operator](https://github.com/mattermost/mattermost-operator) is a Kubernetes operator that manages the lifecycle of a Mattermost installation.

Currently, the Minio is the backend to store all the files/images for a Mattermost installation. We would like to have the AWS S3 option

For this ticket implement the new fields to support the user to select AWS S3 instead of MinIO.
need to implement:
 - read the AWS S3 secret with all information needed.
 - switch from minio to S3 and not deploy minio when using the AWS S3 option

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17907)

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by jwilander** [comment]
@cpanato this is a duplicate of https://github.com/mattermost/mattermost-server/issues/11822 right?

**Comment by cpanato** [comment]
yes looks like, closing
