### ISSUE TITLE
Display LHS bot Icon in web app

### ISSUE THREAD

**Issue by ali-farooq0** [mattermost/mattermost-server#11925]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17422)

As part of https://mattermost.atlassian.net/browse/MM-15452, API was created to set/get/delete LHS bot icons, however there was no way for a client to know if a Bot user had LHS icon set. This story is to add the missing piece to let the clients know if a bot has LHS icon image set. This will enable webclients to fetch svgs if LHS icon is set, otherwise use the default icon, as opposed to ALWAYS fetching bot icon and reverting to default icon only when it fails to fetch.

Following are the necessary changes required to make the above happen

1. Add last_icon_update (timestamp field) field to model.Bot (stored all the way through to the DB)
2. Add a dynamic bot_last_icon_update field to model.User, filled in from Bot.last_icon_update
3. Revert this PR https://github.com/mattermost/mattermost-webapp/pull/3311
4. Use user.bot_last_icon_update to check if BotIcon is set
5. Use InlineSVG Component if bot icon is set, use default bot icon otherwise

After implementing this correctly, https://mattermost.atlassian.net/browse/MM-17294  should not be seen.

Use attached svg files for testing

**Comment by renilJoseph** [comment]
@ali-farooq0 hi, i started working on this. Could you please give some guidance. The column of User table is not getting updated.
`user, _ := a.Srv.Store.User().Get(botUserId)` - current value of user.BotLastIconUpdate is false. So i update it.
`user.BotLastIconUpdate = true
a.Srv.Store.User().Update(user, false)`
Then i read from db using the first command above, and user.BotLastIconUpdate is still false.

**Comment by hanzei** [comment]
@renilJoseph FYI I fixed the JIRA ticket link in your PRs.
