### ISSUE TITLE
Hide "Add to channel" option for users removed from a team

### ISSUE THREAD

**Issue by gabrieljackson** [mattermost/mattermost-server#11920]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17413)

Recently, the profile popup (appears when you click a user's name) was modified to hide the "Add to channel" option for users that are not part of the current team. The reason for this is that user wouldn't have permission to view or post in any of the channels on that team.

As a follow-up to this. We would like to remove the same "Add to channel" option in the profile popup for users who were on a given team, but are no longer part of that team. Right now, the "Add to channel" button is shown, and trying to add the user results in an error.

**Comment by kartik0709** [comment]
Hi, I would like to work on this ticket. Can I have it?

**Comment by hanzei** [comment]
Sure, thanks @kartik0709 :+1:

**Comment by niklabh** [comment]
Here is a pull request: https://github.com/mattermost/mattermost-webapp/pull/3634

Is it needed to be done for mattermost-mobile also?

**Comment by hanzei** [comment]
@kartik0709 Sorry for the confusion. @niklabh mistakenly thought this issue was up for grabs.

**Comment by kartik0709** [comment]
@hanzei its okay. I'll pick another one.
