### ISSUE TITLE
Add support to set mysql db backups

### ISSUE THREAD

**Issue by cpanato** [mattermost/mattermost-server#11924]
The [Mattermost Operator](https://github.com/mattermost/mattermost-operator) is a Kubernetes operator that manages the lifecycle of a Mattermost installation.

Currently, the mattermost operator does not support the backup for the DB, the user need to create using the manifests and controller for the presslabs mysql operator.

For this ticket implement the new fields and the code to support the definition of the db mysql backups via mattermost operator

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17908)

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by ankitrgadiya** [comment]
I would like to take this up.

**Comment by hanzei** [comment]
Thanks @ankitrgadiya
