### ISSUE TITLE
Move mattermost-load-test pipeline to Circleci

### ISSUE THREAD

**Issue by cpanato** [mattermost/mattermost-server#11922]
Currently, the repository [mattermost-load-test](https://github.com/mattermost/mattermost-load-test) is using a Jenkins pipeline

We would like to move that to Circleci
Some requirements:
- the step "Load Test on Kubernetes" should be removed when creating the Circleci
- and when we have a TAG "vX.Y.Z" we should build the load test docker image and push to docker hub. the PRs and master/branches should build and push as well

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-17927

**Comment by cpanato** [comment]
@metanerd will be working on this

**Comment by hanzei** [comment]
Closing this. Thanks @metanerd :+1:
