### ISSUE TITLE
webapp: custom profile fields + custom emoji - do not like eachother

### ISSUE THREAD

**Issue by somenet** [mattermost/mattermost-server#11940]
#### Summary
Adding custom emoji to custom profile fields wont render custom emoji, but will render built-in emoji.

#### Steps to reproduce
add custom emoji to a custom profile field, reload webapp.

#### Expected behavior
Custom emoji being rendered as are built-in emoji.

#### Observed behavior (that appears unintentional) 
custom emoji are not being rendered until they are used elsewhere (e.g. in a post)

![Screenshot_20190823_043641](https://user-images.githubusercontent.com/5354356/63563222-a8bcf980-c560-11e9-9d8e-dbfe456077de.png)

**Comment by amyblais** [comment]
Hi @somenet, are you using this plugin https://github.com/mattermost/mattermost-plugin-custom-attributes?

**Comment by amyblais** [comment]
Hi @somenet, do you have an update on this?

If you are using the plugin I mentioned above, the documentation says that "The Name field can include Markdown, emojis and links." Does this apply in your case?

**Comment by amyblais** [comment]
I'll close this for now as there hasn't been updates on this for a while. Please re-open this issue with relevant additional information if the issue persists,
