### ISSUE TITLE
App slows down when opening a channel with large number of animated emoji

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11946]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15792)

Android app gets slowed down when in a channel with a large number of animated emoji. App resumes working normally after switching to a different channel.
This only effects the Android app, iOS works as usual  in this scenario.

Original community report: [https://github.com/mattermost/mattermost-mobile/issues/2828|https://github.com/mattermost/mattermost-mobile/issues/2828]

Apparently when rendering multiple images on Android it can consume a lot of memory and CPU cycles until the app becomes fully unresponsive, this can be related to the underlying fresco library used on Android to render images.

Possible solutions: 

* Tweak the fresco library configuration (more info can be found [in this blog post|https://medium.com/in-the-hudl/configure-fresco-in-react-native-28c2bc7dcc4d])
* Replace fresco with [React Native FastImage|https://github.com/DylanVann/react-native-fast-image]

**Comment by kdenz** [comment]
Can I help on this? Thanks

**Comment by kdenz** [comment]
So I've successfully replicated this issue using my favorite :parrot: lol
![image](https://user-images.githubusercontent.com/12795428/63952085-7c016880-cab1-11e9-93e5-26c3b882fc51.png)
Now gonna try to optimize it

**Comment by kdenz** [comment]
@enahum @esethna 
Hi guys, I think I've found the solution, which to replace use of fresco with `react-native-fast-image`

Tried but doesn’t work
- Use RN 0.60 and update fresco from 1.10.0 to 2.0.0
- Reduce the same gif size from 12kb to 2kb

What I've tried that works is on the rn-0.60 branch, use `react-native-fast-image` 7.0.2 (requires rn 0.60) to replace the `<Image/>` component in emoji.js
- And you can see below both UI and JS thread are at 50+ FPS.
- One problem that remains is that -> the rendering of gifs are slow initially, which consumes up the whole JS thread, but this is same issue with Fresco. What's much better now is that the UI thread almost never affected by the JS thread consumption, unlike Fresco, which gifs seem to consume both JS and UI threads
 
![image](https://user-images.githubusercontent.com/12795428/64062326-aec57100-cc17-11e9-820c-3b0e410a0bc1.png)

**Comment by enahum** [comment]
@kdenz was this on top of the rn-60 branch? feel free to submit a PR ;)

then we can focus on the server to optimize the images in general including gifs

**Comment by enahum** [comment]
This issue has been resolved
