### ISSUE TITLE
Add line numbers to code blocks that have syntax highlighting

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11953]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17059)

Repro: Post a code block with syntax highlighting such as 

```go
testing line 1
testing line 2
testing line 3
```

Observed: Code blocks on webapp do not show line numbers
 !image-2019-07-17-08-21-41-867.png|thumbnail! 

Expected: Code blocks show line numbers on the left of each code block line, only when syntax highlighting is used on the code block, see image:
!image-2019-07-17-08-18-59-962.png|thumbnail!

**Comment by PunitGr** [comment]
Hey @esethna, I would love to take this up :)

**Comment by PunitGr** [comment]
Hey @esethna, I was debugging and found that we are using `highlight.js` for rendering `markdown` and they don't have support for adding line numbers which is mentioned here: https://highlightjs.readthedocs.io/en/latest/line-numbers.html

On further search the work around could be either use https://github.com/wcoder/highlightjs-line-numbers.js/ or we use some other library for rendering code. :)
Please let me know what would you guys suggest in this case or if there is any other work around. :)

**Comment by PunitGr** [comment]
@esethna Hey, please check https://github.com/mattermost/mattermost-webapp/pull/3578.
This can also be a work around for this. 🙂

**Comment by esethna** [comment]
Hi @PunitGr commented in your PR
