### ISSUE TITLE
Selecting an emoji from emoji picker should insert it at the cursor position

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11954]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17388)

Repro steps: 

1. Write a text in the send box of the channel (or RHS Thread)
2. Move the cursor to the beginning of the line.
3. Select an emoji from the emoji picker. 
4. Emoji is inserted at the end of the line. 

Expected: 
Emoji should be inserted where the cursor is at the time of selection.

**Comment by AGMETEOR** [comment]
Hello @esethna just an update on this. I have made a working implementation that's still a bit rough on the edges and just needs some code refactoring. Otherwise, the emojis are now inserted where the cursor is.
