### ISSUE TITLE
React Native: Add the option to convert public channels to private in the channel info screen

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11952]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15443)

A feature to do this was implemented by a community member https://github.com/mattermost/mattermost-webapp/pull/418 but was omitted on the mobile app.

This ticket is to include the ability for system/team admins to convert a public channel to a private one from mobile, similar to webapp.

In the mobile channel menu, above "Edit Channel" add "Convert to Private Channel"

When tapped, show a confirm dialog:

```
Convert channel_name to Private?

When you convert channel_name to a private channel, history and membership are preserved. Publicly shared files remain accessible to anyone with the link. Membership in a private channel is by invitation only.

The change is permanent and cannot be undone.
```
Buttons: Cancel, OK

_____________________

Webapp Help Wanted ticket: 
Github: https://github.com/mattermost/mattermost-server/issues/7775
Jira: MM-1662

**Comment by avasconcelos114** [comment]
Hey! :)

Thought I'd give this ticket a go and just submitted a PR for it
