### ISSUE TITLE
GetTeamMembers plugin API inluces deleted entities

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#11959]
#### Summary
`GetTeamMember()` plugin API returns deleted entities as well.

#### Steps to reproduce
Call `GetTeamMember()` with a team and user combination which is deleted.

#### Expected behavior
`GetTeamMember()` shouldn't return deleted entities.

#### Observed behavior (that appears unintentional) 
`GetTeamMember()` returns deleted entities as well.

#### Possible fixes
Include a flag `includeDeleted` as third argument in `GetTeamMember()` along with `teamID` and `userID`. Then return deleted items based on the value of this flag.

**Comment by harshilsharma63** [comment]
I'd be willing to implement this if Mattermost accepts this as a feature.

**Comment by amyblais** [comment]
I'll close this for now as there hasn't been updates on this for a while. I hope you'll open a feature request issue for this or take a look if Jesse's suggestion above helps,
