### ISSUE TITLE
Use react-custom-scrollbars for System Console left-hand sidebar

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-server#11956]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12051)
    
It's implementing the changes made for channel sidebar to the System Console: https://github.com/mattermost/mattermost-webapp/pull/1673

Currently scrolling is not a great experience on the left-hand side for Windows/Firefox.

**Comment by PunitGr** [comment]
Hey @jespino, I would love to take this up. :)

**Comment by niklabh** [comment]
@jespino  i would love to take this up

**Comment by jespino** [comment]
Awesome!

**Comment by niklabh** [comment]
https://github.com/mattermost/mattermost-webapp/pull/3530
