### ISSUE TITLE
Desktop: Push Notification Actions

### ISSUE THREAD

**Issue by skyvalleyhigherpraise** [mattermost/mattermost-server#11963]
#### Summary
When Mattermost is not in the foreground and a push notification is displayed, clicking the notification window triggers Mattermost to go to the channel, but does not bring it to the foreground focus.

#### Steps to reproduce
Click on a push notification once it pops.

#### Expected behavior
Bring app to the foreground and go to the channel.

#### Observed behavior (that appears unintentional) 
Push notification disappears, Mattermost is triggered to go to the channel, but the app does not come to the foreground focus.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-18131.

**Comment by skyvalleyhigherpraise** [comment]
Thank you.  Tracking the updates.  Happen to have a timeline for when the fix version will be released?

**Comment by amyblais** [comment]
Closing as this will get fixed for v4.3 desktop app release with this PR: https://github.com/mattermost/desktop/pull/1040. v4.3 is currently scheduled to be released on October 16th (together with server v5.16 release), but any delays may be possible.
