### ISSUE TITLE
Bulk export omits direct messages from a user to themselves

### ISSUE THREAD

**Issue by guzo** [mattermost/mattermost-server#11971]
#### Summary
Posts from a user to themselves are silently ommited in bulk exports (i.e. `bin/mattermost export bulk --all-teams data.json`), thus losing valuable information.

#### Steps to reproduce
In the MM webclient:
* `Ctrl+k <any_channel_name> <return>` to open a channel
* `lemon_curry` to write a server-unique message there
* `Ctrl+k <your_username> <return>` to open a DM channel with only yourself present
* `lemon_curry` to write a server-unique message there

In system shell, as a user with sufficient rights:
* `/opt/mattermost/bin/mattermost export bulk --all-teams >(grep lemon_curry) >/dev/null`
* (alternatively, if you don't like bash-specific features) `/opt/mattermost/bin/mattermost export bulk --all-teams data.json; grep lemon_curry data.json`

#### Expected behavior
I expect `mattermost export bulk` to create a file containing both messages, so that `mattermost import bulk` can import them. For a user named "guzo" and channel named "test_channel", `grep` should print something like this:
```
{"type":"post","post":{"team":"drt","channel":"test_channel","user":"guzo","message":"lemon_curry","create_at":1566901514999,"reactions":null,"replies":null}}
{"type":"direct_post","direct_post":{"channel_members":["guzo","guzo"],"user":"guzo","message":"lemon_curry","create_at":1566901514990,"flagged_by":null,"reactions":null,"replies":null,"attachments":null}}
```

#### Observed behavior (that appears unintentional) 
The file `mattermost export bulk` creates does not contain the direct message I wrote to myself. `grep` prints:
```
{"type":"post","post":{"team":"drt","channel":"test_channel","user":"guzo","message":"lemon_curry","create_at":1566901514999,"reactions":null,"replies":null}}
```

What's worth noting is that import support seems to already exist (or at least seems to allow for a workaround): I've appended the 2nd line from the "Expected behavior" section above to the `.json` file and was able to successfully import it using:
```
yes YES | /opt/mattermost/bin/mattermost reset
# add the line from the example above
/opt/mattermost/bin/mattermost import bulk out.json --apply
/opt/mattermost/bin/mattermost user password guzo $TESTPASS
```

Version info:
```
root@mattermost-ubuntu-s-1vcpu-1gb-fra1-01:~# /opt/mattermost/bin/mattermost version | grep -v ^\{
Version: 5.11.0
Build Number: 5.11.0
Build Date: Wed May 15 19:25:27 UTC 2019
Build Hash: 692d1be91eafb64328ce21bcd18671288eb5139b
Build Enterprise Ready: true
DB Version: 5.11.0
```

#### Possible fixes
I'd guess that the problem seems to be [here](https://github.com/mattermost/mattermost-server/blob/89a79e2e9f097d4be8e36798de36d964dd636eca/app/export.go#L573). I don't have time to test it on my own build, but changing `"channel_members":["guzo","guzo"]` from the "Expected behavior" section to just `"channel_members":["guzo"]` indeed results in a failure to import the relevant `"direct_post"`.

Other potential issues with related code that I've stumbled upon:
- [The commit introducing the export feature](https://github.com/mattermost/mattermost-server/commit/9abd4dd7dc8bbfc96fea29382d8c77386632e4d1) has a few other comments about it not supporting single-member channels. There doesn't seem to be anything related to that on your [JIRA](https://mattermost.atlassian.net/issues/?jql=text~"single%20member%20channel"), hence my mention of it here.
- A limit of 1000 posts seems to be hardcoded in a few [locations](https://github.com/mattermost/mattermost-server/search?q=GetDirectPostParentsForExportAfter&unscoped_q=GetDirectPostParentsForExportAfter).

**Comment by guzo** [comment]
Thanks for your reply @amyblais. I have never used go, and as such I might not be the best person to implement a fix for that.

Just double-checking: is the feature idea forum a good place to re-report this, given that it seems to be a bug/poorly documented unexpected behavior in an existing feature, rather than an idea for a feature that does not exist yet?

**Comment by amyblais** [comment]
Makes sense, I opened a bug ticket here: https://mattermost.atlassian.net/browse/MM-18215.

**Comment by guzo** [comment]
Thank you, @amyblais!

**Comment by amyblais** [comment]
Feature is scheduled for v5.20,
