### ISSUE TITLE
Privacy - Push notifications ignore the "ShowFullName" setting

### ISSUE THREAD

**Issue by kosimus** [mattermost/mattermost-server#11981]
#### Summary
Push notifications ignore the "ShowFullName" setting, which generates a serious privacy problem.

#### Steps to reproduce
1. Use Mattermost version: 5.14.0 and mobile app version 1.22.1
2. Make sure you have a team mate with their full name present in their profile.
3. Make sure that "ShowFullName" in config.json is set to false.
4. Make sure your own display preferences for Teammate Name Display are set to Show first and last name.
5. Have them send you a DM.
6. Observe that you can see their full first and last name in the push notification, even though the server settings prohibit that.

#### Expected behavior
Push notifications should respect the "ShowFullName" config.json setting and prioritize it over the display settings of any regular user (admins are not really a concern).

#### Observed behavior (that appears unintentional) 
Push notifications on mobile appear to be ignoring the "ShowFullName" config.json setting, which generates a serious privacy problem. Full first and last name can be obtained by anyone just by receiving a message.

#### Possible fixes
It seems that it just grabs the display value for push notifications and email notifications directly from the preferences and ignores the server privacy settings: 
https://github.com/mattermost/mattermost-server/blob/master/app/notification_push.go#L158

**Comment by amyblais** [comment]
This is fixed for the upcoming v5.15 release, to be released on September 16th.

**Comment by kosimus** [comment]
Awesome, thank you :).
