### ISSUE TITLE
Jira plugin: up for grabs issues (link)

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-server#11984]
[Help wanted](https://github.com/mattermost/mattermost-plugin-jira/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22up+for+grabs%22+label%3A%22help+wanted%22) issues in the [Mattermost Jira plugin](https://github.com/mattermost/mattermost-plugin-jira) repository.

To see the full list, **[CLICK HERE](https://github.com/mattermost/mattermost-plugin-jira/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22up+for+grabs%22+label%3A%22help+wanted%22)**

Usually there is a mix of easy and medium difficulty tickets there, for both Go and JavaScript/React. Since this ticket is a placeholder, please comment and update tickets in [Mattermost Jira plugin](https://github.com/mattermost/mattermost-plugin-jira) directly.

Mattermost Jira Plugin supports a two-way integration between Mattermost and Jira. This plugin supports Jira Core and Jira Software products, for Server, Data Center and Cloud platforms. It has been tested with versions 7 and 8.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by cored** [comment]
I have some bandwidth to work on this @levb

**Comment by levb** [comment]
@cored Welcome! Please feel free to pick a ticket from the link above, and comment there so that we know you are working on it.

**Comment by hanzei** [comment]
Replaced by https://github.com/mattermost/mattermost-server/issues/12656
