### ISSUE TITLE
Autolink plugin: up for grabs issues (link)

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-server#11985]
[Help wanted](https://github.com/mattermost/mattermost-plugin-autolink/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22up+for+grabs%22+label%3A%22help+wanted%22) issues in the [Mattermost Autolink plugin](https://github.com/mattermost/mattermost-plugin-autolink) repository.

To see the full list, **[CLICK HERE](https://github.com/mattermost/mattermost-plugin-autolink/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22up+for+grabs%22+label%3A%22help+wanted%22)**

Usually there is a mix of easy and medium difficulty tickets there, for both Go and JavaScript/React. Since this ticket is a placeholder, please comment and update tickets in [Mattermost Autolink plugin](https://github.com/mattermost/mattermost-plugin-autolink) directly.

Mattermost Autolink Plugin creates regular expression (regexp) patterns that are reformatted into a Markdown link before the message is saved into the database. Use it to add custom auto-linking on your Mattermost system, such as adding links to your issue tracker based on the regexp patterns.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by hanzei** [comment]
Replaced by https://github.com/mattermost/mattermost-server/issues/12656
