### ISSUE TITLE
can't read or delete very large channel

### ISSUE THREAD

**Issue by lexusag** [mattermost/mattermost-server#11983]
#### Summary
can't read or delete very large channel

#### Steps to reproduce
post in channel about 1 000 000 messages

#### Expected behavior
someone in our company has setup automatic post in one channel and after i noticed it was too 
 late

#### Observed behavior (that appears unintentional) 
#trying to read messages in client
2019-08-29T09:19:04.016+0300    error   mlog/log.go:172 Unable to get the parent post for the channel   {"path": "/api/v4/channels/oksgnw6erjg6uc1ym3wmzqg37o/posts", "request_id": "e5tpdy8hm3bqtjujjsksw6hi9a", "ip_addr": "217.20.179.193", "user_id": "8zsphm7m5prmud4cgbwftekq3r", "method": "GET", "err_where": "SqlPostStore.GetLinearPosts", "http_code": 500, "err_details": "channelId=oksgnw6erjg6uc1ym3wmzqg37o err=context deadline exceeded"}
#trying to delete channel in cli
/opt/mattermost/bin/mattermost channel delete oksgnw6erjg6uc1ym3wmzqg37o
Unable to delete channel 'busfor-drive-ru' error: SqlPostStore.PermanentDeleteByChannel: Unable to delete the posts by channel, channel_id=oksgnw6erjg6uc1ym3wmzqg37o, context deadline exceeded

#### Possible fixes
maybe optimizing this query could help
https://github.com/mattermost/mattermost-server/blob/a92c830e570fac8378c96dc47054daa461539d37/store/sqlstore/post_store.go#L760
maybe some tips for mysql config or instructions for correct way to delete channel manually.

**Comment by amyblais** [comment]
@lexusag Would you be open to reviewing this page and sending us the relevant information about your environment: https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by lexusag** [comment]
@amyblais 
is it enough?
`centos-release-7-6.1810.2.el7.centos.x86_64
mysql  Ver 14.14 Distrib 5.7.24

mattermost version
Version: 5.13.0
Build Number: 5.13.2
Build Date: Wed Jul 24 17:25:26 UTC 2019
Build Hash: 9a8b0906fdbf2c2a309db2400f4bcc5902800e2c
Build Enterprise Ready: false
DB Version: 5.13.0

user OS
Windows 10 Pro 1903

Windows Desktop App version
4.2.1
`

**Comment by amyblais** [comment]
@lexusag You can archive a channel from the channel settings > archive channel. You can also use these CLI commands: https://docs.mattermost.com/administration/command-line-tools.html#mattermost-channel.

What do you mean by not being able to read the channel?

**Comment by lexusag** [comment]
@amyblais when i trying open channel in client the channel displayed like it's empty and i got error in log file
```
2019-08-29T09:19:04.016+0300 error mlog/log.go:172 Unable to get the parent post for the channel {"path": "/api/v4/channels/oksgnw6erjg6uc1ym3wmzqg37o/posts", "request_id": "e5tpdy8hm3bqtjujjsksw6hi9a", "ip_addr": "217.20.179.193", "user_id": "8zsphm7m5prmud4cgbwftekq3r", "method": "GET", "err_where": "SqlPostStore.GetLinearPosts", "http_code": 500, "err_details": "channelId=oksgnw6erjg6uc1ym3wmzqg37o err=context deadline exceeded"}
```

**Comment by amyblais** [comment]
@lexusag If it's a bot or integration that posts the messages, maybe you can request stopping using it for now and then trying to delete the channel. 

Are you able to view the channel if you reload / clear cache?

**Comment by lexusag** [comment]
@amyblais we already stopped that bot, and after tuning mysql and encreasing server performance we can read messages in channel. but still can't delete it. is it okay to just delete it in mysql db?

**Comment by lieut-data** [comment]
@lexusag, we are improving the performance of exactly this query in the upcoming v5.18 (cc @reflog).

While we don't generally advocate for manual edits to the database, it should in general be safe to remove posts by matching on the appropriate `ChannelId`. cc @grundleborg / @jespino for feedback on this.

**Comment by lexusag** [comment]
@amyblais @lieut-data Thanks

**Comment by jespino** [comment]
It depends, other related table would be the compliance one, if they are using compliance exports, they can find problems there, if not looks safe. Still certain data is going to end orphan, I can think in reactions or file attachments
