### ISSUE TITLE
Footer is not rendered in message attachments

### ISSUE THREAD

**Issue by nfriend** [mattermost/mattermost-server#11994]
#### Summary
Footers are not rendered in [message attachments](https://docs.mattermost.com/developer/message-attachments.html).

#### Steps to reproduce

Send a message like this:

```json
{
    "text": "I am a test message!",
    "attachments": [
        {
            "text": "And here’s an attachment!",
            "footer": "This is the footer",
            "footer_icon": "https://assets.gitlab-static.net/uploads/-/system/project/avatar/13083/logo-extra-whitespace.png?width=64"
        }
    ]
}
```

Mattermost version:

<img width="593" alt="Screen Shot 2019-08-30 at 8 58 39 AM" src="https://user-images.githubusercontent.com/1638631/64019015-64070480-cb04-11e9-9281-a4d3fe20def8.png">

#### Expected behavior
The `footer` and `footer_icon` fields are rendered.  As a reference, [here is how these fields are rendered in Slack:](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22I%20am%20a%20test%20message!%22%2C%22attachments%22%3A%5B%7B%22text%22%3A%22And%20here%E2%80%99s%20an%20attachment!%22%2C%22footer%22%3A%22This%20is%20the%20footer%22%2C%22footer_icon%22%3A%22https%3A%2F%2Fassets.gitlab-static.net%2Fuploads%2F-%2Fsystem%2Fproject%2Favatar%2F13083%2Flogo-extra-whitespace.png%3Fwidth%3D64%22%7D%5D%7D)

<img width="538" alt="Screen Shot 2019-08-30 at 8 53 53 AM" src="https://user-images.githubusercontent.com/1638631/64018803-cad7ee00-cb03-11e9-9b94-73b4821b2e02.png">

#### Observed behavior (that appears unintentional) 
No footer is rendered.

#### Other details
This is a [known issue](https://docs.mattermost.com/developer/message-attachments.html#known-issues).

**Comment by nfriend** [comment]
Even though this issue is called out as a [known issue in the documentation](https://docs.mattermost.com/developer/message-attachments.html#known-issues), I was unable to find any reference to this issue on [UserVoice](https://mattermost.uservoice.com/forums/306457-general?query=footer) or [Jira](https://mattermost.atlassian.net/browse/MM-16539?jql=status%20%3D%20Open%20AND%20text%20~%20%22footer%22), so I'm opening this bug report to bring awareness and help prioritize this issue 🙂

**Comment by amyblais** [comment]
Ticket for reference: https://mattermost.atlassian.net/browse/MM-18430.

**Comment by hanzei** [comment]
This issue is fixed thanks to the awesome work from @nfriend :tada:
