### ISSUE TITLE
Add typescript support for typescript to mattermost-plugin-starter-template

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-server#12019]
Add support to use typescript in the plugins adding the changes need in the `.babelrc`, `webpack.config.json`, `.eslintrc.json` and `package.json` files, and adding the `tsconfig.json` file.

The approach expected here is to compile typescript through babel instead of through typescript directly, you can see an example of this in the PR [https://github.com/mattermost/mattermost-webapp/pull/3472,](https://github.com/mattermost/mattermost-webapp/pull/3472,) the PR is pretty big but you only have to pay attention to the previously mentioned files.

If you have any question you can contact with “jesus.espino” in https://community.mattermost.com.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-18155

**Comment by niklabh** [comment]
Can i take this up?

I have created a PR: https://github.com/mattermost/mattermost-plugin-starter-template/pull/64

**Comment by hanzei** [comment]
Thanks for working on this @niklabh :+1:
