### ISSUE TITLE
Clicking on a file:// link does not work (usecase: synced files with several users)

### ISSUE THREAD

**Issue by biva** [mattermost/mattermost-server#12042]
#### Summary
Clicking on a file:// link does not work for local folders.

I'm not sure if I should post this here or on https://github.com/mattermost/desktop

#### Steps to reproduce
- Create a link to a local file `[My local file](C:\Docs\locafile.docx)`
- Click on the link

#### Expected behavior
The file (or the folder) should be opened

#### Observed behavior (that appears unintentional) 
- On Desktop, it doesn't do anything
- On Firefox, it opens a blank page

#### Possible fixes
This issue has been reported several times: https://github.com/mattermost/desktop/issues/579 , https://github.com/mattermost/desktop/issues/772 , https://github.com/mattermost/desktop/issues/821
Apparently, this is intentional as explained by @yuya-oc because:
> - Accepting local resources would allow to execute programs via malicious link
> - There is no situation where an user would want to share their local files without attached files.

In my usecase, we use Nextcloud to sync files within our group. And we have the same letter and path for local files. This is why we often share the file path instead of the file itself, to save data. We would love to be able to open the link directly.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @biva,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by biva** [comment]
Done here: https://mattermost.uservoice.com/forums/306457-general/suggestions/38520490-enable-the-click-on-a-file-link

**Comment by amyblais** [comment]
Thank you! Closing this as this can be tracked via the feature request,
