### ISSUE TITLE
Webapp: Remove border on code blocks

### ISSUE THREAD

**Issue by last-partizan** [mattermost/mattermost-server#12057]
When using dark theme light gray border on code blocks looks a bit off.

![Screenshot from 2019-09-05 16-36-15](https://user-images.githubusercontent.com/301015/64346910-ab592d80-cffb-11e9-8634-713d56878e4e.png)

It can be fixed either by removing border in `.post code code`, or by adding dark border in dark colorschemes for code.

**Comment by amyblais** [comment]
@last-partizan Would you be interested in opening a pull request for this for devs to review?

**Comment by last-partizan** [comment]
@amyblais yes, i can do it.

**Comment by lindalumitchell** [comment]
@amyblais do we need a JIRA ticket to track this as well? I didn't see one, but wasn't sure if this is on a different process.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-18615.
