### ISSUE TITLE
Leaving Channel on Desktop

### ISSUE THREAD

**Issue by natc66** [mattermost/mattermost-server#12076]
#### Summary
Cannot leave channel successfully on desktop app and browser.

#### Steps to reproduce
On macOS Mojave version 10.14.5
Mattermost desktop app (for macOS) version 4.2.3
Google Chrome browser version 76.0.3809.132

In the browser Mattermost and/or on the macOS Mattermost app, join a public channel and then use the dropdown options from the channel name to "leave channel."

#### Expected behavior
When clicking "leave channel" on a public channel (I have not tested this on private channels), the text "You left the channel" appears. However, I am still a member of the channel according to the list of members in the top right, can still see the channel in the list of public channels on the left, and still see all messages within the channel. There is no message that says "You have joined the channel" after the initial "You left the channel" message.

This does not happen on the mobile app and I am able to successfully leave channels. This then updates correctly on desktop browser and desktop app (the channel is removed from the sidebar public channel list and I have the option to join the public channel when I click on "more..."). If I leave a channel on my mobile app and have the channel open on either desktop browser and/or desktop app, I am still removed from said channel (he channel is removed from the sidebar public channel list and I have the option to join the public channel when I click on "more...") the channel page does not show any messages and shows the name of the channel.

When I attempt to leave channel on the desktop app and the desktop browser, I have made sure that I do not have Mattermost open anywhere else (other computer or mobile phone, browser, or desktop). This does not affect my ability to leave a channel.

**Comment by amyblais** [comment]
Hi @natc66, what Mattermost server version are you on?

**Comment by natc66** [comment]
5.13.2 but we will be updating to 5.14.2 within the next week

**Comment by amyblais** [comment]
We fixed a bug related to this issue in v5.14: https://mattermost.atlassian.net/browse/MM-17281. Let's hope it's the same bug and that your issue gets resolved when you upgrade.

**Comment by natc66** [comment]
Hopefully! I will follow up when we do upgrade. Thanks for responding!

**Comment by amyblais** [comment]
@natc66 Do you see either any Mattermost log errors or Console errors when this happens?

**Comment by natc66** [comment]
(Apologies in advance I'm not super tech savvy)

Server Logs show these two messages repeating quite a bit: {"level":"error","ts":1564183551.3571172,"caller":"mlog/log.go:172","msg":"Failed to upgrade websocket connection","path":"/pnsntalk/api/v4/websocket","request_id":"mibafmg5yjb8idp48aa8e5tnjc","ip_addr":"172.28.21.33","user_id":"tkyxtctku3bojbxwjswsyk3wbr","method":"GET","err_where":"connect","http_code":500,"err_details":""}
{"level":"error","ts":1564183552.8237376,"caller":"api4/websocket.go:28","msg":"websocket connect err: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}

Otherwise, I'm not quite sure what I should be looking for. Is there something in specific or could you point me more directly to where I should be looking. Sorry!

**Comment by amyblais** [comment]
@natc66 I've asked our team about this and waiting for their feedback. Perhaps as a next step you could try these troubleshooting steps related to websockets:
 - https://docs.mattermost.com/install/troubleshooting.html#failed-to-upgrade-websocket-connection
 - https://docs.mattermost.com/install/troubleshooting.html#websocket-closed-or-websocket-re-established-connection

**Comment by natc66** [comment]
Hi @amyblais I was just able to talk to our system admin about these issues and apparently those two errors were related to something else. He has said that he receives a 403 when trying to leave a channel. Sorry for the false lead, and I will let you know if he figures anything else out.

**Comment by amyblais** [comment]
@natc66 Do you have updates from your system admin?

**Comment by amyblais** [comment]
I'll close this for now as there hasn't been updates for a while, but I hope you will re-open this issue if the problem persists and share any additional relevant information that might help us troubleshoot this issue further. Thanks,
