### ISSUE TITLE
go module unable to access 'https://git.apache.org/thrift.git/'

### ISSUE THREAD

**Issue by sowmiyamuthuraman** [mattermost/mattermost-server#12125]
#### Summary
While Running mattermost for development, the following error occurs
`fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Operation timed out
go: error loading module requirements
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/sowmiya/Go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:`

**Comment by sowmiyamuthuraman** [comment]
I resolved the issue by adding `replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0` in the go.mod file. Is this the correct way to do it?

**Comment by amyblais** [comment]
Hi @sowmiyamuthuraman, would you be open to joining our [community server](https://community.mattermost.com) and then posting your question either in the [Developers channel](https://community.mattermost.com/core/channels/developers) or [Peer-to-peer channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our developers or other community members will most likely be able to answer your question.

**Comment by niklabh** [comment]
This is needed for individual plugins also. Can i make a PR

**Comment by hanzei** [comment]
Thanks for fixing this @niklabh :+1:
