### ISSUE TITLE
Can not use api/v4/websocket with trailing slash

### ISSUE THREAD

**Issue by DanielRuf** [mattermost/mattermost-server#12166]
#### Summary
Currently we use socket.io client to connect to the mattermost instance. But it adds a trailing slash and this causes a 404.

`http://localhost:8065/api/v4/websocket/?EIO=3&transport=polling&t=MqWUUcJ` does not work.
See https://github.com/socketio/socket.io-client-swift/issues/297

#### Steps to reproduce
Go to `http://localhost:8065/api/v4/websocket/` - returns a 404.

#### Expected behavior
It should not return a 404.

#### Observed behavior (that appears unintentional) 
A different result is returned.

#### Possible fixes
Optionally support trailing slash for the same endpoint.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-18827.

**Comment by amyblais** [comment]
Closing as this has been fixed for upcoming v5.17 release,
