### ISSUE TITLE
Mattermost Push Proxy not building with Go 1.13

### ISSUE THREAD

**Issue by wget** [mattermost/mattermost-server#12202]
#### Summary
Mattermost Push Proxy cannot be built with Go 1.13 because of changes to the go vet shadow tool.

#### Steps to reproduce
* Simply change the build CI to Golang 1.13 (or use a rolling release GNU/Linux distribution like ArchLinux which already has Go 1.13)
* Realize the shadow tool has changed because all vet flags are not recognized anymore.

#### Expected behavior
Go vet step passes

#### Observed behavior (that appears unintentional) 
https://circleci.com/gh/wget/mattermost-push-proxy/4

#### Possible fixes
* Remove shadow check like I had to do for the ArchLinux package: https://aur.archlinux.org/cgit/aur.git/diff/PKGBUILD?h=mattermost-push-proxy
* Or fix the shadow code upstream
* Or use another vet tool.

**Comment by amyblais** [comment]
@wget Is this related to the discussion in the Installers and Images channel? Would you like me to open a Jira ticket for this and assign to someone?

**Comment by wget** [comment]
@amyblais Hi Amy. Yes, it is. But no need to link back to the conversation. The conversation on the Mattermost chat was rather convoluted, let's keep this bug report alone, let's keep it stupid simple :)

**Comment by wget** [comment]
And if you want to play with Jira, it is up to you. I hate Jira :-1: 
Just put me in CC of that bug, that way I don't loose track of it. Since on Arch Linux we were directly impacted.

**Comment by amyblais** [comment]
Ok, no worries, I'll assign you on this Github issue for now.

**Comment by agnivade** [comment]
Old bug. The shadowing problem was fixed. Closing this.
