### ISSUE TITLE
Mattermost error ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-server#12225]
#### Summary
Bug report in one concise sentence

Mattermost end user gets unexplained ERR_CERT_AUTHORITY_INVALID error message. 

![image](https://user-images.githubusercontent.com/177788/64922088-f9023280-d77f-11e9-8f50-7a1a65e49d20.png)

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

Unexplained error in Mattermost 

#### Expected behavior
Describe your issue in detail

Per the Mattermost UX Guidelines on [fast, obvious, forgiving](https://docs.mattermost.com/developer/fx-guidelines.html#fast-obvious-forgiving) the web search "ERR_CERT_AUTHORITY_INVALID mattermost" should explain to an end user what's happened to their system. 

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

Randomly got error message: 
![image](https://user-images.githubusercontent.com/177788/64922088-f9023280-d77f-11e9-8f50-7a1a65e49d20.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

SEO the error message with the word Mattermost

**Comment by it33** [comment]
After clicking "Yes" the application crashes: 

![image](https://user-images.githubusercontent.com/177788/64960717-b0627c00-d848-11e9-8fa4-7fa2cd55d5b0.png)

**Comment by amyblais** [comment]
@it33 I'll share this with the team. Would you be open to checking what Mattermost desktop app version you're on? You can click the "Help" button to find out.

<img width="516" alt="Screenshot at Sep 16 09-35-06" src="https://user-images.githubusercontent.com/29708087/64962443-6fc52b80-d865-11e9-9195-38c8a3fff32b.png">

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-18602.

**Comment by it33** [comment]
Thanks Amy, I'm on 4.2.3 ![image](https://user-images.githubusercontent.com/177788/65047212-e79f5e80-d916-11e9-91b9-16c18e8c6a15.png)

**Comment by amyblais** [comment]
Closing as this will be fixed via upcoming changes made as part of https://mattermost.atlassian.net/browse/MM-13145 in the upcoming desktop app 4.3 release. 

4.3 is currently scheduled to be released on October 16th,
