### ISSUE TITLE
Channels moved via CLI move back when editing them afterwards via web

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-server#12252]
#### Summary
Moving a channel via the `./mattermost channel move` CLI and then editing it via web results in the channel moving back to the old team.

#### Steps to reproduce
1. `mattermost channel move team2 team1:mychannel --username myname`
2. Edit e.g. the header of the channel

#### Expected behavior
The channel remains in the new team.

#### Observed behavior (that appears unintentional) 
The channel moves back to the old team. I confirmed this by checking the `teamid` in the `channels table which changed back.
This does not happen if I send a message to the channel before editing the header.

Tested in Mattermost v5.13 and v5.15.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-18631.

**Comment by amyblais** [comment]
@ThiefMaster We discussed with devs that this is likely a consequence of the CLI not invalidating the server caches and thus notifying clients. This likely won’t be fixed until we move to the mmctl framework for the CLI. One of our devs are working on moving to the mmctl framework in a future release so this bug will be fixed along with that.
