### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Clicking on airplane icon does not open file attachment modal but sends the message"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12267]
**Test Key:** M18677
**Test folder:** ``/cypress/integration/messaging``
**Title:** Clicking on airplane icon does not open file attachment modal but sends the message
    
**Steps:**
1. Log in on browser, narrow window to mobile view 
2. Type some characters in the message box 
3. Click the aeroplane Send icon 
        
**Expected:**
Message sends

(File attachment modal does not open)
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18677](https://mattermost.atlassian.net/browse/MM-18677)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by allenlai18** [comment]
I am working on this.  

https://github.com/mattermost/mattermost-webapp/pull/4173

**Comment by allenlai18** [comment]
and this one was merged. as well .  https://github.com/mattermost/mattermost-webapp/pull/4173

**Comment by saturninoabril** [comment]
Thanks for checking.  Also did close the corresponding Jira ticket.
