### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Mobile view: Post options menu (3-dots) is present on a reply post in RHS"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12268]
**Test Key:** M18679
**Test folder:** ``/cypress/integration/messaging``
**Title:** Mobile view: Post options menu (3-dots) is present on a reply post in RHS
    
**Steps:**
1. On Webapp mobile view, click on reply to an existing post.
2. Type a message and click on Add comment.
        
**Expected:**
After 2) you can still see the 3-dot post options menu visible to the right of your post and clicking on the menu opens it and displays post options
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18679](https://mattermost.atlassian.net/browse/MM-18679)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by M-ZubairAhmed** [comment]
Can i take this one, first time writing an e2e test, might take some time to get familiar with cypress
