### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "At-mention user autocomplete does not overlap with channel header when drafting a long message containing a file attachment"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12263]
**Test Key:** M18667
**Test folder:** ``/cypress/integration/messaging``
**Title:** At-mention user autocomplete does not overlap with channel header when drafting a long message containing a file attachment
    
**Steps:**
1. Go to a public channel and attach a file in a message draft
2. Type multiline text into the message box
```
h
h
h
h
h
h
h
h
h
h
h
h
```
3. On a new line, type "@" to open the at-mention user autocomplete
        
**Expected:**
Autocomplete doesn't overlap with channel header
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18667](https://mattermost.atlassian.net/browse/MM-18667)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one? Also, what do you mean with the second step? Feels like there is something missing.

**Comment by saturninoabril** [comment]
@larkox Sure and thanks for catching up.  I've updated step 2.
