### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Trying to type in middle of text should not send the cursor to end of textbox"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12272]
**Test Key:** M18683
**Test folder:** ``/cypress/integration/messaging``
**Title:** Trying to type in middle of text should not send the cursor to end of textbox
    
**Steps:**
1. Start typing in the post textbox
2. Click in the middle of the text you started typing
3. Start typing again
        
**Expected:**
Cursor stays where it is and it should not move to the end of text
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18683](https://mattermost.atlassian.net/browse/MM-18683)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by jespino** [comment]
Sure!

**Comment by larkox** [comment]
At least on the current version, I am not able to get Cypress to do this. Whenever I ask Cypress to click anywhere in the element, it just activate the focus and get to the end of the line. This behaves different if I am the one manually making the click.

Therefore, I think this is not possible to automatise under the restrains of Cypress.

**Comment by saturninoabril** [comment]
PR has been merged.  Thank you @larkox for your contribution!
