### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "RHS fetches messages on socket reconnect when a different channel is in center"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12271]
**Test Key:** M18682
**Test folder:** ``/cypress/integration/messaging``
**Title:** RHS fetches messages on socket reconnect when a different channel is in center
    
**Steps:**
1. Reply to a post from another test user
2. Keep the RHS open but switch to a different channel in the center
3. Disconnect from internet
4. Have the other test user from step 1) comment on your reply from the RN app
5. Re-connect to the internet
        
**Expected:**
The post made by the test user during your network disconnect appears in the RHS
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18682](https://mattermost.atlassian.net/browse/MM-18682)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by saturninoabril** [comment]
Sure and thanks @larkox!
