### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Posts change order when being sent quickly"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12285]
**Test Key:** M18698
**Test folder:** ``/cypress/integration/messaging``
**Title:** Posts change order when being sent quickly
    
**Steps:**
1 - Post a series of numbers rapidly one after the other — i.e., Type 1, hit enter, type 2, hit enter, etc. —
        
**Expected:**
The posts don't reshuffle as you post but instead post in the order you sent them.
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18698](https://mattermost.atlassian.net/browse/MM-18698)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by saturninoabril** [comment]
@larkox Sure and thanks!

**Comment by saturninoabril** [comment]
PR has been merged.  Thank you @larkox for your contribution!
