### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Leave a long draft in reply input box"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12288]
**Test Key:** M18700
**Test folder:** ``/cypress/integration/messaging``
**Title:** Leave a long draft in reply input box
    
**Steps:**
1. Open the reply thread for a post
2. Type a post that is several lines long but do not post it (can be done with whitespace)
3. As the post becomes longer note the input box becomes taller to accomodate the text
4. Open the reply thread for a a different post in the channel 
5. Re-open the reply thread from step 1
        
**Expected:**
Input box height has not changed
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18700](https://mattermost.atlassian.net/browse/MM-18700)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by kosgrz** [comment]
I can do it :)

**Comment by saturninoabril** [comment]
Thanks @kosgrz!
