### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Delete a GIF from RHS reply thread, other user viewing in center and RHS sees GIF preview disappear from both"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12284]
**Test Key:** M18692
**Test folder:** ``/cypress/integration/messaging``
**Title:** Delete a GIF from RHS reply thread, other user viewing in center and RHS sees GIF preview disappear from both
    
**Steps:**
If testing on mobile, have User 2 view on mobile and User 1 posting on whatever you like

User 1 posts:
1) Post a message, and a reply to that message
2) Post another reply that contains the following:

https://media1.giphy.com/media/l41lM6sJvwmZNruLe/giphy.gif

User 2 views:
3) View the message thread posted in steps 1-2, both in the center channel and right-hand sidebar (mobile just view reply thread, aka the `Message Details` screen)

User 1 deletes:
4) Delete the reply posted in step 2 (the giphy link; the second reply)
        
**Expected:**
- Second reply including GIF (posted in 2) disappears from center channel and RHS (mobile verify disappears from `Message Details` view)

- "(message deleted)" does not display for deleter

- (N/A for mobile apps:) On refresh, RHS closes
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18692](https://mattermost.atlassian.net/browse/MM-18692)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?
