### ISSUE TITLE
Write an automated test using Cypress for "Large number of emoji reactions wrap into multiple lines"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12289]
**Test Key:** M18712
**Test folder:** ``/cypress/integration/messaging``
**Title:** Large number of emoji reactions wrap into multiple lines
    
**Steps:**
1. Post a large number of emoji reactions on a post (>15)
2. Open the post in the RHS
3. Observe the emoji in the center channel and in RHS
        
**Expected:**
Emoji wrap into multiple lines and don't cause horizontal scroll in both center channel and RHS
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18712](https://mattermost.atlassian.net/browse/MM-18712)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by jganobsik** [comment]
Working on this test

**Comment by saturninoabril** [comment]
@jganobsik Thanks!

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
