### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Autocomplete should close if tildes are deleted using backspace"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12287]
**Test Key:** M18707

**Title:** Autocomplete should close if tildes are deleted using backspace
    
**Steps:**
1. Make a post 
2. Hit the "up" arrow to open the edit modal 
3. Insert a tilde (~) at the beginning of the post to be edited 
4. Delete the tilde by backspacing
        
**Expected:**
After 2) Edit modal opens

After 3) autocomplete opens

After 4) autocomplete closes
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18707](https://mattermost.atlassian.net/browse/MM-18707)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by iwataka** [comment]
I'd like to take this issue @saturninoabril

**Comment by saturninoabril** [comment]
@iwataka Sure and thanks!
