### ISSUE TITLE
UI Automation: Write an automated test using Cypress for ""Message too long" warning text"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12282]
**Test Key:** M18689
**Test folder:** ``/cypress/integration/messaging``
**Title:** "Message too long" warning text
    
**Steps:**
1. Post a message in any center channel.
2. Create a reply thread by clicking the {{Reply}} button on the post.
3. In the reply box on RHS, type (paste) a long comment longer than the number of characters allowed.16383
        
**Expected:**
Notice the warning message "Your message is too long..." doesn't overlap with the reply text.
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18689](https://mattermost.atlassian.net/browse/MM-18689)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by cinlloc** [comment]
I would like to work on it.

**Comment by saturninoabril** [comment]
@cinlloc Sure and thanks!
