### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Delete a Message during reply, other user sees `(message deleted)`"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12281]
**Test Key:** M18693
**Test folder:** ``/cypress/integration/messaging``
**Title:** Delete a Message during reply, other user sees `(message deleted)`
    
**Steps:**
1. Have another user post a message in a channel you can see
2. Click the reply arrow to *start* to reply to the message (but do not post the reply; just view the reply thread and start to type a reply in the reply box)
3. Have the other user delete the message they posted, [...] > Delete
4. After the other user has deleted the parent message, press Enter to send your reply
5. Observe the modal that appears, then click `Okay` to close it (leave RHS open)
6. Enter another reply and press Enter or tap to send
        
**Expected:**
Your view:
The deleted parent post shows as (message deleted). 
When try to post the reply anyway, a modal (FYI specifically the PostDeletedModal) is shown that tells you "Someone deleted the message on which you tried to post a comment." The RHS / reply thread should remain open, and the reply draft remains in text box.

The other user, who deleted the message, should not see "(message deleted)" in any way because of your unsent reply

When you close the warning modal and try to send a second reply, the modal appears again.
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18693](https://mattermost.atlassian.net/browse/MM-18693)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
Would this test make sense using only one browser?

Cypress does not allow multiple browsers (https://docs.cypress.io/guides/references/trade-offs.html#Multiple-browsers-open-at-the-same-time ), and there are some workarounds, but I am not sure they will work fine for these tests.

What do you think?

**Comment by larkox** [comment]
I think I found a viable workaround for this. May I take this one?

**Comment by saturninoabril** [comment]
@larkox Cool.  `cy.postMessageAs` to post as another user and `cy.externalRequest` to delete a post might be useful for this.
