### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Markdown preview: inline image"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12286]
**Test Key:** M18714
**Test folder:** ``/cypress/integration/messaging``
**Title:** Markdown preview: inline image
    
**Steps:**
1. Make sure your markdown preview is enabled (Account Settings > Advanced > Preview pre-release features > Show markdown preview option in message input box = Yes)
2. Type a message with large inline image via markdown - ``![make it so](https://i.stack.imgur.com/MNeE7.jpg)`` for example. Don't send the message.
3. Switch to markdown preview by clicking on "Preview" below right of message input box
        
**Expected:**
The message box should expand, just like it does with, for example, with a list, so that image preview can be easily viewed.

NOTE: you may still have to scroll if the image doesn't fit into the height of the expanded message input box but you should not see just the image in a narrow slit with scrollbars.
Also, the image shouldn't ovelap with other markdown images. See https://mattermost.atlassian.net/browse/MM-18190 for more details.
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18714](https://mattermost.atlassian.net/browse/MM-18714)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by saturninoabril** [comment]
@larkox That's awesome, thanks!

**Comment by srkgupta** [comment]
PR submitted and merged
https://github.com/mattermost/mattermost-webapp/pull/4233
