### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Markdown quotation paragraphs"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12291]
**Test Key:** M18703
**Test folder:** ``/cypress/integration/messaging``
**Title:** Markdown quotation paragraphs
    
**Steps:**
1. Post the following in a test channel (in one post, three lines of text with blank line between each):

>this is

>really

>three quote lines
        
**Expected:**
Quotes icon shows just once, at left of the first line, with the other two lines below left-aligned with the first line, with space between each line
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18703](https://mattermost.atlassian.net/browse/MM-18703)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by saturninoabril** [comment]
@larkox Sure and thanks!

**Comment by saturninoabril** [comment]
@larkox Thank you for your contribution!
