### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Permalink to first post in channel shows endless loading indicator above"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12294]
**Test Key:** M18701
**Test folder:** ``/cypress/integration/messaging``
**Title:** Permalink to first post in channel shows endless loading indicator above
    
**Steps:**
1. Create a new private or public channel
2. Post a few times in the channel
3. Get the permalink to the first post
4. Post that link in a different channel then follow it back
        
**Expected:**
Verify that there isn't an endless loading loop above the post
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18701](https://mattermost.atlassian.net/browse/MM-18701)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by jgbaylon** [comment]
I'll take this one.

**Comment by saturninoabril** [comment]
@jgbaylon Sure and thanks!

**Comment by saturninoabril** [comment]
@jgbaylon Thank you for your contribution!
