### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Edit post with "strikethrough" and ensure channel auto-complete closes after second tilde (~~)"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12297]
**Test Key:** M18710
**Test folder:** ``/cypress/integration/messaging``
**Title:** Edit post with "strikethrough" and ensure channel auto-complete closes after second tilde (~~)
    
**Steps:**
1. Type a post into the input box and hit "enter" key
2. Hit the "up" arrow to open the edit modal
3. Position cursor at the beginning of the post and type two tildes (~~), observe channel autocomplete open then close
4. Position cursor at the end of the post and type two tildes (~~), observe channel autocomplete open then close
5. Hit "enter" key
        
**Expected:**
After 5) edited post is shown in the channel, with "strikethrough" formatting

(In steps 3 and 4, typing the first tilde should open the channel autocomplete, but as soon as you type the second tilde channel autocomplete should close)
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18710](https://mattermost.atlassian.net/browse/MM-18710)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by jespino** [comment]
sure, go ahead :)

**Comment by saturninoabril** [comment]
PR is now merged.  Thanks @larkox for your contribution!
