### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Leave a long draft in the main input box"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12298]
**Test Key:** M18699
**Test folder:** ``/cypress/integration/messaging``
**Title:** Leave a long draft in the main input box
    
**Steps:**
1. Type a post that is several lines long but do not post it (can be done with whitespace)
2. As the post becomes longer note the input box becomes taller to accomodate the text
3. Switch to a different channel and then return 
        
**Expected:**
at step 1. Verify the post textbox should expand and collapse on all browsers right when the text wraps onto the next line
3. Input box height has not changed
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18699](https://mattermost.atlassian.net/browse/MM-18699)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?
