### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Input box on main thread can expand with RHS closed"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12292]
**Test Key:** M18711
**Test folder:** ``/cypress/integration/messaging``
**Title:** Input box on main thread can expand with RHS closed
    
**Steps:**
Without any type of RHS open:
1. Type a post that is several lines long (can be done with SHIFT+ENTER blank newlines)
2. As the post becomes longer note the input box becomes taller to accommodate
        
**Expected:**
Text box continues to expand for each new line until it reaches about 50%. The box then begins to scroll once its maximum height has been reached

Note: 
- If viewing the bottom of the channel when you start to type the post, recent posts above the message box move upward as the message box expands, so they are not covered
- If you are scrolled up in the center channel when you start to type the post, the message box expands over the posts (the posts do not move up)
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18711](https://mattermost.atlassian.net/browse/MM-18711)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by ashishmahi** [comment]
can i pick this one ?

**Comment by ashishmahi** [comment]
@saturninoabril  :
When you say text box should grow upto 50% , 50% of what ? 
50 % what component  ?

**Comment by larkox** [comment]
Hello Saturnino. Before taking on this one, would you mind explaining what you mean with RHS? I am not sure what you are referring to, so before getting into this issue I would like to know what it is so I can see if I can take on it.

**Comment by amyblais** [comment]
@larkox RHS refers to the right-hand-sidebar. Does this help?

**Comment by larkox** [comment]
Great. I expected it to be that, but I wanted to make sure. May I take this one?
