### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Visual verification of tooltips on post hover menu"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12299]
**Test Key:** M18697
**Test folder:** ``/cypress/integration/messaging``
**Title:** Visual verification of tooltips on post hover menu
    
**Steps:**
In a test channel, 
1. Make a post in the center panel
2. To the right of the message you've just posted, hover your mouse over each option in the "post menu" (the ..., emoji reaction, reply arrow)
        
**Expected:**
After 2) you should see while hovering left to right over the options, tooltips appear for:
- "More actions"
- "Add reaction"
- "Reply"
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18697](https://mattermost.atlassian.net/browse/MM-18697)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
I'm working on this PR :)
