### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Link preview - Removing it from my view removes it from other user's view"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12296]
**Test Key:** M18708
**Test folder:** ``/cypress/integration/messaging``
**Title:** Link preview - Removing it from my view removes it from other user's view
    
**Steps:**
1. Log in as two different users viewing the same channel in two different browsers
2. Post a link that has a collapsible preview, such as:
https://www.bbc.com/news/uk-wales-45142614 
(see Known Issues for notes on which links are collapsible)
3. Verify both users see the link preview (make sure enabled in Account Settings and System Console if needed)
4. Have the user who posted it click the collapse arrows to collapse the preview
5. Verify preview did *not* collapse for other user
6. Have the user who posted it click the arrows to re-expand the link preview
7. Then click the `x` on the link preview to remove it
        
**Expected:**
Collapse / expand only affects current user's view

On clicking the `x`, preview is removed for all users.

Notes:
- OpenGraph expand/collapse arrows are only for the image, and only for big ones that appear below the text
- If you need to find a new link to test, news articles often have large images
- YouTube videos also have expand/collapse arrows
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18708](https://mattermost.atlassian.net/browse/MM-18708)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by saturninoabril** [comment]
@larkox Sure and thanks!

**Comment by srkgupta** [comment]
Closing the issue as the PR is merged
