### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Center channel input box doesn't overlap with RHS"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12290]
**Test Key:** M18705
**Test folder:** ``/cypress/integration/messaging``
**Title:** Center channel input box doesn't overlap with RHS
    
**Steps:**
1. Resize the window so that it goes into tablet view
2. Open the RHS and post enough comments in that thread that the comment box goes to the bottom of the screen
3. Scroll to the bottom of the RHS
        
**Expected:**
Center channel input box doesn't overlap with the RHS and the "Add Comment" button is visible
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18705](https://mattermost.atlassian.net/browse/MM-18705)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by jgbaylon** [comment]
I'll take this one.

**Comment by saturninoabril** [comment]
@jgbaylon Sure and thanks!

**Comment by srkgupta** [comment]
PR submitted and merged:
https://github.com/mattermost/mattermost-webapp/pull/4246
