### ISSUE TITLE
Write an automated test using Cypress for "Recent mentions search doesn't fully expand in tablet view until results are fully loaded"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12302]
**Test Key:** M18696
**Test folder:** ``/cypress/integration/messaging``
**Title:** Recent mentions search doesn't fully expand in tablet view until results are fully loaded
    
**Steps:**
1. Sign in to Mattermost on Chrome and shrink the window to about halfway horizontally so that it displays in tablet view
2. Click the "@"-icon to open recent mentions search
        
**Expected:**
Search expands fully just like for others like flagged posts
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18696](https://mattermost.atlassian.net/browse/MM-18696)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by a-arias** [comment]
I'm going to take this one @saturninoabril

**Comment by jespino** [comment]
Great @a-arias

**Comment by saturninoabril** [comment]
@a-arias Thanks for looking into this, just checking progress.

**Comment by jasonblais** [comment]
I'll open this back up for grabs due to inactivity. @a-arias If you're still interested working on this, let us know! :)

**Comment by rodel-calasagsag** [comment]
@saturninoabril @jasonblais I would like to take this one if no one's working on this yet

**Comment by saturninoabril** [comment]
Sure, thanks!

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
