### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Remove last post in channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12300]
**Test Key:** M18716
**Test folder:** ``/cypress/integration/messaging``
**Title:** Remove last post in channel
    
**Steps:**
1) View an empty channel (such as a DM channel with a user you've never messaged)
2) Make a post
3) Delete that post
        
**Expected:**
The channel is still displayed
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18716](https://mattermost.atlassian.net/browse/MM-18716)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
I submitted a PR :)

**Comment by hanzei** [comment]
Thanks @josephk96

**Comment by saturninoabril** [comment]
Thanks [Joseph](https://github.com/josephk96) for your contribution1
