### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Channel is removed from Unreads section if user navigates out of it via permalink"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12306]
**Test Key:** M18713
**Test folder:** ``/cypress/integration/messaging``
**Title:** Channel is removed from Unreads section if user navigates out of it via permalink
    
**Steps:**
1. As UserA copy the permalink of a post in any channel and paste it into another test channel mentioning UserB in the post
2. As UserB, open the unread channel that has a permalink to a post in another channel
2. As UserB, click on the permalink
        
**Expected:**
UserB is taken to the linked post and the channel that UserB navigated away from is removed from "Unreads" section
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18713](https://mattermost.atlassian.net/browse/MM-18713)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by saturninoabril** [comment]
@larkox Sure and thanks!

**Comment by saturninoabril** [comment]
@larkox Thank you for your contribution!  Closing this now.
