### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Compact view: Markdown quotation"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12304]
**Test Key:** M18704
**Test folder:** ``/cypress/integration/messaging``
**Title:** Compact view: Markdown quotation
    
**Steps:**
1. Use `> ` to post text formatted as a quotation
2. View in compact view (Account Settings > Display > Message Display > Compact)
        
**Expected:**
No extra space before quotation, quotes image does not overlap with username
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18704](https://mattermost.atlassian.net/browse/MM-18704)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by a-arias** [comment]
I'm going to take this one @saturninoabril  :D
