### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Input box on main thread can expand with RHS open"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12303]
**Test Key:** M18709
**Test folder:** ``/cypress/integration/messaging``
**Title:** Input box on main thread can expand with RHS open
    
**Steps:**
1. Open the reply thread for a post and return the focus to main input box
2. In center channel (with RHS open), type a post that is several lines long (can be done with SHIFT+ENTER blank newlines)
3. As the post becomes longer note the input box becomes taller to accomodate
        
**Expected:**
Text box continues to expand for each new line until it reaches about 50%. The box then begins to scroll once its maximum height has been reached

Note: 
- If viewing the bottom of the channel when you start to type the post, recent posts above the message box move upward as the message box expands, so they are not covered
- If you are scrolled up in the center channel when you start to type the post, the message box expands over the posts (the posts do not move up)
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18709](https://mattermost.atlassian.net/browse/MM-18709)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by saturninoabril** [comment]
Available for grab.

**Comment by larkox** [comment]
May I take this one?

**Comment by saturninoabril** [comment]
Thanks @larkox!
