### ISSUE TITLE
Cannot send messages containing Unicode char U+2025 Two Dot Leader

### ISSUE THREAD

**Issue by reftel** [mattermost/mattermost-server#12311]
#### Summary
Sending a message containing Unicode char U+2025 (Two Dot Leader, ‥) fails.

#### Steps to reproduce
Send a message containing U+2025, from the web UI, either to a channel or in a private chat.

#### Expected behavior
Expected the message to be sent.

#### Observed behavior (that appears unintentional) 
Message gets a "Retry - Cancel" button bar on the right, and does not get sent.

#### Possible fixes
Not known.

**Comment by amyblais** [comment]
Hi @reftel, Would you be open to reviewing this page and sending us any relevant additional information about your environment: https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

Are you able to reproduce this on our [community server](https://community.mattermost.com/core/)?

**Comment by mstaalesen** [comment]
Not able to reproduce on the community-server. The message was posted to the channel / direct message when tested.

**Comment by amyblais** [comment]
@reftel Do you have an update on this?

**Comment by amyblais** [comment]
I'll close this for now as we haven't received updates on this,
