### ISSUE TITLE
Hide Inactive Users by default under user management

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#12319]
#### Summary
Bug report in one concise sentence

Hide Inactive Users by default under user management

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

System Console --> User Management

#### Expected behavior
Describe your issue in detail

When a server has quite a few users, the Inactive Users, Active Users (Members) and System Admins get all mixed up, while filtering is possible, it would be good to hide away Inactive Users by default.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

Always, System Console --> User Management

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

When a server has quite a few users, the Inactive Users, Active Users (Members) and System Admins get all mixed up, while filtering is possible, it would be good to hide away Inactive Users by default.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @arjitc,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
I'll close this for now as there hasn't been updates on this, but I hope you will open a feature request for this and the other issue https://github.com/mattermost/mattermost-server/issues/12318 for further discussion,

**Comment by tmotyl** [comment]
here is a similar feature idea: https://mattermost.uservoice.com/forums/306457-general/suggestions/44133915-filter-out-inactive-users-in-mattermost-system-con
