### ISSUE TITLE
User Management only allows filtering of inactive and admin users

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#12318]
#### Summary
The User Management feature under System Console only allows for filtering of 
1. Admin users
2. Inactive users

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

1. Click on System Console
2. User Management
3. Try to filter under "User Status"

#### Expected behavior

The User Management feature under System Console should allow filtering of, 
1. Admin users
2. Inactive users
3. Normal Users/Members

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

The User Management feature under System Console only allows for filtering of 
1. Admin users
2. Inactive users

![image](https://user-images.githubusercontent.com/363587/65359718-fd649a80-dc1a-11e9-8727-6f6e4ea45420.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

Allow filtering / selecting of all 3 types of users

1. Admin users
2. Inactive users
3. Normal Users/Members

**Comment by amyblais** [comment]
Hi @arjitc, this feature is currently planned but not yet scheduled for a release.

Would you also like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?
