### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Floating timestamp in mobile view"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12324]
**Test Key:** M18759
**Test folder:** ``/cypress/integration/messaging``
**Title:** Floating timestamp in mobile view
    
**Steps:**
1. Narrow your browser or desktop app so it goes into mobile view
2. View a channel that has at least several days of messages
3. Scroll up in the channel, observe the floating timestamp / date indicator
        
**Expected:**
Floating date indicator should change the date to reflect the messages being viewed
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-18759](https://mattermost.atlassian.net/browse/MM-18759)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by Jonany** [comment]
I'll take this one :)

**Comment by saturninoabril** [comment]
Sure and thanks @Jonany!

**Comment by Jonany** [comment]
@saturninoabril Any suggestion on how to generate several days worth of data? `make test-data` only generates data from yesterday.

**Comment by saturninoabril** [comment]
You may use `cy.postMessageAs` and set `createAt` to desired previous date.  One example is [here](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/channel/message_reply_spec.js#L29-L32).

**Comment by Jonany** [comment]
Thanks!

**Comment by saturninoabril** [comment]
Available for grab.

**Comment by nadalfederer** [comment]
I'll take this

**Comment by jasonblais** [comment]
Hey @nadalfederer, let us know if you have any questions so far? :)

**Comment by nadalfederer** [comment]
Thanks for the ping. I've missed this, I'll create a PR in the next few days

**Comment by jasonblais** [comment]
Thanks @nadalfederer :)
