### ISSUE TITLE
Missing GetScheme(schemeid string) method in the Plugin APIs

### ISSUE THREAD

**Issue by chahat-arora** [mattermost/mattermost-server#12383]
I am trying to find a user role using a plugin and i am using a team override scheme.

**Comment by amyblais** [comment]
@chahat-arora Is this something you're working on or is this a request to add this improvement?

**Comment by amyblais** [comment]
@chahat-arora Do you have an update on this?

**Comment by chahat-arora** [comment]
@amyblais Is there any other way to do this?

**Comment by amyblais** [comment]
Hi @chahat-arora, if you have a request to add functionality, you can share it on our feature request forum here: http://www.mattermost.org/feature-requests/. If you're interested in working on this, feel free to open a PR and link to it here.

**Comment by amyblais** [comment]
I'll close this issue for now as we haven't received updates for a while. I hope you will open a feature request issue for this,

**Comment by chahat-arora** [comment]
I need to fetch current admins (system/team/channel) with the help of a plugin where a `Team Override Schemes` is defined.
