### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "/ autocomplete list can scroll"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12599]
**Test Key:** I19168

**Test folder:** `/cypress/integration/integrations`

**Title:** / autocomplete list can scroll
    
**Steps:**
1. In a test channel, type "/"
2. Scroll through the slash command autocomplete list
        
**Expected:**
Autocomplete scrolls as expected.
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-19168](https://mattermost.atlassian.net/browse/MM-19168)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by asbillings07** [comment]
I'd like to try my hand at this one if it's still available.

**Comment by asbillings07** [comment]
submitted PR for it.

**Comment by saturninoabril** [comment]
Sorry @asbillings07 and thank you for your time and effort but I'm closing this as duplicate (my fault).  Also I [commented on your PR](https://github.com/mattermost/mattermost-webapp/pull/3949#issuecomment-541613031).
