### ISSUE TITLE
Write an automated test using Cypress for "/shrug test"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#12600]
**Test Key:** I19167

**Test folder:** `/cypress/integration/integrations`

**Title:** /shrug test
    
**Steps:**
1. With User1 and User2 on same server and User2 has desktop notifications turned on
2. In a test channel User1 types "/shrug test" and post
        
**Expected:**
User1 and User2 see message "test ¯\_(ツ)_/¯"
User2's desktop notification shows that the message is from User1 (not "webhook")
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-19167](https://mattermost.atlassian.net/browse/MM-19167)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by Jondyr** [comment]
I'm interested in taking this one

**Comment by Jondyr** [comment]
Freeing this one up because of lack of time to look into it.

**Comment by MCRayRay** [comment]
I know a bit about Cypress and Go, so I should be able to take a look at this. :-)

**Comment by jespino** [comment]
Awesome, Thanks @MCRayRay!

**Comment by saturninoabril** [comment]
@MCRayRay Just checking progress of this ticket.

**Comment by MCRayRay** [comment]
@saturninoabril hi, sorry about this, I completely forgot I had taken this on. I have deassigned myself as I am unable to make this change at this particular time.

**Comment by saturninoabril** [comment]
No worries and thanks for letting me know.

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
