### ISSUE TITLE
Firefox 60.9.0esr does not display who else reacted with an emoji

### ISSUE THREAD

**Issue by bk138** [mattermost/mattermost-server#12694]
#### Summary
Firefox 60.9.0esr on Debian Buster does not display who else reacted with an emoji.

It _does_ work with Firefox 69.0.2 on MacOS.

#### Steps to reproduce
Use Firefox 60.9.0esr to connect to Mattermost 5.14.2, let someone else react to a message with an emoji, hover over the shown emoji.

#### Expected behavior
Popover appears, showing which team member(s) reacted.

#### Observed behavior (that appears unintentional) 
No popover appears.

**Comment by amyblais** [comment]
@bk138 I'm not 100% sure if this is something we can fix if this is an issue on a specific browser version and works on the latest browser release. Do you know if Firefox has known issues around emojis?

**Comment by bk138** [comment]
@amyblais I don't know if Firefox has known issues around emoji. 

I posted this issue since it affects all Debian-stable Firefox users, which might be quite an amount of people. I can also perfectly well understand the MM team not wanting to support an older Firefox ESR release, but I don't know your policy in this regard. If it is "supported on the latest browser release", then I am fine to close this issue :-)

**Comment by amyblais** [comment]
@bk138 I tested this on Firefox 68.1.0 which seems to be the latest ESR. This bug seems to be fixed there too. Would you be open to upgrading to the latest ESR? https://www.mozilla.org/en-US/firefox/organizations/all/

**Comment by amyblais** [comment]
I checked with developers and they said we'd probably not fix this in this case. Thank you for reporting this! I'll close this issue for now,
