### ISSUE TITLE
Readme should point Contributing Code link to developers.mattermost.com

### ISSUE THREAD

**Issue by anchepiece** [mattermost/mattermost-server#12721]
#### Summary
Readme should use updated Contributing Code link in section [Get Involved](https://github.com/anchepiece/mattermost-server#get-involved)

#### Steps to reproduce
Clicking "Contributing Code" leads to https://docs.mattermost.com/developer/contribution-guide.html

#### Expected behavior
Clicking "Contributing Code" should point directly to the https://developers.mattermost.com/contribute/getting-started/ page

#### Observed behavior (that appears unintentional) 
Current documentation page has no title and a message "See contribution guidelines at" with an updated link

#### Possible fixes
README.md line 49

**Comment by amyblais** [comment]
@anchepiece Would you be interested in submitting a fix for this?

**Comment by anchepiece** [comment]
@amyblais Sure. Fix incoming.
