### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by mkvaghani** [mattermost/mattermost-server#12755]
Mattermost Server Running success, Mattermost webapp was tested success. 
But it shows blank when open the URL http://localhost:8065/

When I inspect the elements in google chrome, it shows me following errors
```
main.0557a9608f37d6ebab1d.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
manifest.json:1 Failed to load resource: the server responded with a status of 404 (Not Found)
manifest.json:1 Manifest: Line: 1, column: 5, Unexpected data after root element.
```

The link http://localhost:8065/static/manifest.json  
Shows 404 page not found. 

Using Docker 18.09 on MacOS.
Go Lang : go version go1.13.1 darwin/amd64
Mattermost Apps, server and webapp run without any errors.

Any idea?

**Comment by amyblais** [comment]
@mkvaghani What Mattermost server version are you on?

**Comment by lieut-data** [comment]
@mkvaghani, did you run step 5 in the [developer setup](https://developers.mattermost.com/contribute/webapp/developer-setup/)?

> Link the client directory in your server with the dist directory in your webapp:
```
ln -nfs $(go env GOPATH)/src/github.com/mattermost/mattermost-webapp/dist $(go env GOPATH)/src/github.com/mattermost/mattermost-server/client
```

**Comment by mkvaghani** [comment]
Hi,

Yes It works after  Link this client directory.  :)

`ln -nfs $(go env GOPATH)/src/github.com/mattermost/mattermost-webapp/dist $(go env GOPATH)/src/github.com/mattermost/mattermost-server/client`

this works !

**Comment by sozojunaid** [comment]
> @mkvaghani, did you run step 5 in the [developer setup](https://developers.mattermost.com/contribute/webapp/developer-setup/)?
> 
> > Link the client directory in your server with the dist directory in your webapp:
> 
> ```
> ln -nfs $(go env GOPATH)/src/github.com/mattermost/mattermost-webapp/dist $(go env GOPATH)/src/github.com/mattermost/mattermost-server/client
> ```

how to link plz give me idea !!
