### ISSUE TITLE
[Docker] fix latest tag

### ISSUE THREAD

**Issue by J0WI** [mattermost/mattermost-server#12756]
#### Summary
https://github.com/mattermost/mattermost-docker/issues/397#issuecomment-525881880:
the latest tag of `mattermost/mattermost-team-edition` is outdated and only tags with minor releases (like `5.15.1`) are available. `5` or `5.15` are not available, which makes it hard to maintain.

#### Steps to reproduce
`docker run mattermost/mattermost-team-edition`

#### Expected behavior
getting latest release

#### Observed behavior (that appears unintentional) 
getting a release that is several weeks old

#### Possible fixes
- maintain tags like `latest`, `5` and `5.15`
- https://github.com/mattermost/mattermost-docker/issues/361

**Comment by amyblais** [comment]
@cpanato Would you be able to take a look at this?

**Comment by cpanato** [comment]
we dont push latest and `5` or `5.15` but sounds a nice to have. will implement that when I have some time

**Comment by cpanato** [comment]
fixed
```
mattermost/mattermost-team-edition:5
mattermost/mattermost-team-edition:5.17
mattermost/mattermost-team-edition:5.17.0
```

and
 
```
mattermost/mattermost-enterprise-edition:5
mattermost/mattermost-enterprise-edition:5.17
mattermost/mattermost-enterprise-edition:5.17.0
```
