### ISSUE TITLE
Error with manifest.json

### ISSUE THREAD

**Issue by 00Spider47** [mattermost/mattermost-server#12818]
#### Summary
Server is failing to load the resource.

#### Steps to reproduce
Setup the developer and server app using developer setup guidelines.
Issue exists in latest version.

#### Expected behavior
The Server should load resources.

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/45037094/66917211-962fdf80-f03a-11e9-86da-cad717b75d35.png)

**Comment by lieut-data** [comment]
@00Spider47, this file should be generated as part of the webpack build process. Can you check your `dist/` directory to see if the file is present?

I just ran a `make clean` and freshly installed `node_modules` and can confirm the file is created successfully.

**Comment by 00Spider47** [comment]
Yeah.It is Present.Still i'm receiving the error.Would it be fine if i just run the command make-clear again or do i have to remove and install node_modules for attaining this.

![image](https://user-images.githubusercontent.com/45037094/66977691-8957ce00-f0c4-11e9-904f-20c125baf977.png)

**Comment by lieut-data** [comment]
Curious. Can you try opening your developer tools network tab and disabling caching to see if that makes any difference?

![image](https://user-images.githubusercontent.com/1023171/67110465-33108b00-f1a9-11e9-859e-1018a828b2c6.png)

**Comment by 00Spider47** [comment]
@lieut-data : I got it working buddy.Thanks
@amyblais : You can marked it as closed
