### ISSUE TITLE
WebApp: ``get team invite link`` button gone.

### ISSUE THREAD

**Issue by somenet** [mattermost/mattermost-server#12832]
I just upgraded one of our MM-instances - the one that doesnt come with gitlab - in the anticipation of guest accounts.

It seems that all the team-invite methods (by mail and by link) were merged into the new button ``invite people``.

The problem is: I cannot find the ``get team invite link`` button anymore at all.

The old link still works, but both instances I manage - one E10-academic and one Team-Edition -  heavily rely on invite-links.
Therefore I would kindly ask you to fix this asap and not after a month and/or possibly give me instructions on how to safely downgrade to 5.15 until this is fixed.

#### Summary
``get team invite link`` button is gone from WebApp, which is a major problem - downgrade instructions?

#### Steps to reproduce
+ Open burger-menu.
+ Find only ``invite people`` there.
  + submenus dont show any invite links too.

#### Expected behavior
The new invite-people interface showing the current invite-link, if selecting ``invite members``

The new invite-people interface showing an invite-link that creates guest accounts instead of regular members and ties them to the selected channel(s), if selecting ``invite guests``

#### Observed behavior (that appears unintentional) 
No invite-links anywhere. Not for users, nor for guests.

**Comment by amyblais** [comment]
@somenet Would you be able to share a screenshot of what you're seeing?

**Comment by somenet** [comment]
If guests are disabled, I get automatically this
![image](https://user-images.githubusercontent.com/5354356/67105952-133d8f00-f1ca-11e9-9ab7-ea5689f6122f.png)

If guests are enabled, I get these.
![image](https://user-images.githubusercontent.com/5354356/67106045-2fd9c700-f1ca-11e9-93d8-4ba4a78787d3.png)

![image](https://user-images.githubusercontent.com/5354356/67106072-3bc58900-f1ca-11e9-9522-970156c24c77.png)

![image](https://user-images.githubusercontent.com/5354356/67106093-47b14b00-f1ca-11e9-9cf2-36a8b81f90c2.png)

**Comment by somenet** [comment]
Browser is Chromium 
```
Chromium | 76.0.3809.100 (Developer Build) built on Debian 10.0, running on Debian 10.1 (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Linux
JavaScript | V8 7.6.303.29
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
```

**Comment by amyblais** [comment]
@somenet Would you be open to sharing more details about your config settings, such as:
 - https://docs.mattermost.com/deployment/advanced-permissions.html
 - https://docs.mattermost.com/administration/config-settings.html#signup

**Comment by somenet** [comment]
Cannot reproduce this anymore.

Maybe this was some kind of browser caching issue?
