### ISSUE TITLE
Improve display of file and image thumbnails on mobile

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#12841]
See Design and assets: https://projects.invisionapp.com/share/9XRRHMSBV6D#/screens/360642221

Note: If interested in taking on this project please see the supplementary notes on each design slide that detail the functional behaviour. Please also join our Native Mobile Apps channel https://community.mattermost.com/core/channels/native-mobile-apps to ask any questions and receive guidance from our core team

![image](https://user-images.githubusercontent.com/14333569/67131812-06656f00-f1bb-11e9-9af7-a003557f71fd.png)

![image](https://user-images.githubusercontent.com/14333569/67131823-12e9c780-f1bb-11e9-979b-bce2e2a5c579.png)

![image](https://user-images.githubusercontent.com/14333569/67131833-1bda9900-f1bb-11e9-873a-80a18b2a1d63.png)

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-10813

**Comment by chuttam** [comment]
Mind if I have a go at this one?

**Comment by enahum** [comment]
@chuttam all yours ;)

**Comment by esethna** [comment]
@chuttam sweet! Please let us know in the ~Native Mobile Apps channel if you have any questions on implementation or design and we'll be happy to help right away. https://community-release.mattermost.com/core/channels/native-mobile-apps
