### ISSUE TITLE
Complete tests for executeCommand action

### ISSUE THREAD

**Issue by marianunez** [mattermost/mattermost-server#12849]
`executeCommand` in `actions/command.js` in the web app needs unit tests to ensure that it handles the following commands properly:

- `leave`
- `settings`
- `collapse/leave`

Feel free to refactor the function if necessary to make it easier to test.

Example PR: https://github.com/mattermost/mattermost-webapp/pull/3815

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-17937

**Comment by pradeepmurugesan** [comment]
@marianunez I can pick up this follow up issue 👍

**Comment by marianunez** [comment]
Thanks @pradeepmurugesan 👍

**Comment by jasonblais** [comment]
Hey @pradeepmurugesan, let us know if you're still open to working on this one? Let us know if you have any questions!

In the meantime, I'll open this up for grabs :)

**Comment by nadalfederer** [comment]
can I take this

**Comment by marianunez** [comment]
That would be great! Thanks @nadalfederer!
