### ISSUE TITLE
Uploading a file to mattermost

### ISSUE THREAD

**Issue by suryaatevellore** [mattermost/mattermost-server#12847]
I am trying to upload a file to a locally hosted mattermost server, and I am totally lost in the example provided here https://api.mattermost.com/#tag/files. I am using node.js on my end , and here is my code.
```
	var url = '/api/v4/posts';
    console.log("This is what the url looks like " + url);
    let options = getDefaultOptions(url, "POST");
    var imageURL = 'xyz.png';
    var dataString = `{"channel_id":"${channel}", "filename": ${imageURL}`};
    options.body = dataString;request(options, function (error, response, body) 
    {
        if( error )
            {
                console.log( chalk.red( error ));
                return; // Terminate execution.
            }
        console.debug( response );
        return body;

    });
```

**Comment by amyblais** [comment]
@suryaatevellore Are you seeing errors?

**Comment by ali-farooq0** [comment]
@suryaatevellore There are a bunch of options that you have to set before sending out the request in JS.

You can use [mattermost-redux Client4](https://github.com/mattermost/mattermost-redux/blob/28384d6c5605bc73895bd10f3e726a9911fc4dd6/src/client/client4.js#L27) to upload files. Here is an example in the webapp where Client4 is used to upload a file.

https://github.com/mattermost/mattermost-webapp/blob/2ddd75a7a2ac414a40c668c6b9ad18408a0ed57b/actions/file_actions.jsx#L17

**Comment by amyblais** [comment]
I'll close this issue for now as there hasn't been updates for a while. If the issue persists, please re-open this for further troubleshooting,
