### ISSUE TITLE
Feature Requests: Set Default Theme from system console

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [mattermost/mattermost-server#12843]
Title says it all. It would be nice if you could set a default theme(with your company or project colors) and let your site's users change it if they want.

**Comment by amyblais** [comment]
@Th3Whit3Wolf Feel free to open feature requests here: http://www.mattermost.org/feature-requests/. Let us know if you're interested in implementing this.

**Comment by amyblais** [comment]
I'll close this for now as there hasn't been updates on this, but I hope that you will consider opening a feature request issue for this,
