### ISSUE TITLE
Redirect user archived channel view if a channel is archived while viewing it

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#12855]
#### NEW CHANGES TO BEHAVIOUR

This requires changes in mattermost-redux, mattermost-webapp, and mattermost-mobile

Suppose a user is viewing a channel, and someone else archives it. 
 - observed: User redirected to Town Square
 - new expected: The user stays in the channel. Channel changes to read-only mode as shown on the screenshot below. Additional specification notes:
    - "Archived" channel icon on the left-hand sidebar, next to the channel name been viewed (use this Font Awesome icon https://fontawesome.com/v4.7.0/icon/archive)
    - "You are viewing an archived channel. [Close Channel]" in place of the message box
    - Clicking "Close Channel" button closes the channel, removes the channel from the sidebar and redirects user to "town-square" channel
    - Switching to another channel also removes the archived channel from the sidebar

Web:
![image](https://user-images.githubusercontent.com/14333569/67237387-00140480-f400-11e9-93c8-f1c5f00e32d7.png)

Mobile:
![image](https://user-images.githubusercontent.com/13119842/67217223-61cd7200-f3f2-11e9-9ef9-16075be4e710.png)

NO CHANGES TO EXISTING BEHAVIOUR (including for completeness and QA testing):
1. The user who archives the channel is redirected to Town Square.
2. A system message is posted in the channel to indicate that a user archived the channel.
3. For users who are members of the channel but are not viewing it when archived, the channel disappears from the channel sidebar.

NOTE: In order to view archived channels, you must have [ViewArchivedChannels ](https://docs.mattermost.com/administration/config-settings.html#allow-users-to-view-archived-channels-experimental) config setting enabled.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-19338

For any questions, reach out to @jasonblais on GitHub or @jason.blais on https://community.mattermost.com for any questions.

**Comment by ChrisDobby** [comment]
I'll pick this one up if that's OK?

**Comment by jasonblais** [comment]
@ChrisDobby That would be great, thank you!!

There is some work in progress for archived channels via https://github.com/mattermost/mattermost-server/issues/12854, so I'm going to ask @crspeller to share if you should take any of that work into account while working on this ticket.

**Comment by crspeller** [comment]
@ChrisDobby I think all this work should be in the webapp. So if you want to avoid conflicts you can check out https://github.com/mattermost/mattermost-webapp/pull/4116 and base your PR off of that branch. When it gets merged you can rebase off master.

**Comment by jasonblais** [comment]
@crspeller Does it need any changes in the mattermost-mobile repo for mobile changes?

**Comment by crspeller** [comment]
@jasonblais @ChrisDobby Yes. This will need mobile changes as well.

**Comment by crspeller** [comment]
@ChrisDobby Looks like this was done as part of the above ticket. Sorry for the confusion!
