### ISSUE TITLE
Custom emojis that are scaled down look awful

### ISSUE THREAD

**Issue by toojazzy** [mattermost/mattermost-server#12859]
#### Summary
Emojis are not scaled down properly resulting in severe quality drop as compared with other solutions

#### Steps to reproduce
Add this custom emoji https://i.imgur.com/j4RuUHv.png and use it, it will look awful, try the same in Slack, it will look great, here are the screenshots how it looks:
in mattermost: https://i.imgur.com/OSnsJ4z.png
in slack: https://i.imgur.com/Swj6ScS.png
It happens in linux client as well as in browser (chrome, newest stable)

#### Expected behaviors
I would expect the emojis to be resized properly

#### Observed behavior (that appears unintentional) 
Instead, the emojis are resized with awful filtering

#### Possible fixes
I don't know how to fix it, probably use normal scaling method that electron exposes because nothing ever had this problem

**Comment by amyblais** [comment]
Hi @toojazzy, did you follow these steps to add the custom emoji: https://docs.mattermost.com/help/settings/custom-emoji.html? What Mattermost server version are you on?

**Comment by toojazzy** [comment]
I followed this method that you posted, the server version is 5.16.0 and client version is 4.3.0, its self hosted, same behavior is happening in the browser as well, I also upload the exact same image I used to make the emote
![monkas](https://user-images.githubusercontent.com/53616039/67291333-ad127e00-f4e1-11e9-8851-617dae1240e6.png)

**Comment by amyblais** [comment]
@toojazzy Do you see this on Linux only or also other devices?

**Comment by toojazzy** [comment]
@amyblais It happens on Linux desktop client and on Chrome which is platform independent. My resolution is 1920x1080, on macs retina it looks ok because of the higher DPI.

**Comment by amyblais** [comment]
@toojazzy Would you be open to testing if you see the same issue on our [community server](https://community.mattermost.com/core/). I wasn't able to reproduce this on Mac, Chrome so far.

**Comment by toojazzy** [comment]
As I wrote it will not be happening on Macs because it has higher resolution, try it on full HD display, 1920x1080

**Comment by amyblais** [comment]
@toojazzy I don't have a HD display available, that is why I asked if you'd be open to do a quick test on our [community server](https://community.mattermost.com/core/). I'll ask our team if somebody can help test this.

**Comment by gigawhitlocks** [comment]
I can reproduce this on my server, version 5.17, Linux desktop client (Fedora), on both my 1440p display as well as my 1080p display.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-20651.

**Comment by toojazzy** [comment]
It was not resolved and was marked as Cannot reproduce, why? It is clearly reproducible on non retina displays. Are you serious about issues being sent to you?

**Comment by amyblais** [comment]
Thanks for letting me know. I've reopened the ticket and sent it back to UX triage to see if it can be further investigated or opened as a Help Wanted issue.
