### ISSUE TITLE
Gitlab oauth - Could not parse auth data out of gitlab user object

### ISSUE THREAD

**Issue by mkvaghani** [mattermost/mattermost-server#12876]
<code>Error : 
Could not parse auth data out of gitlab user object

http://localhost:8065/error?message=Could+not+parse+auth+data+out+of+gitlab+user+object&s=MEYCIQDIvRT5qfCg0uGumz3hB2DXQBgBGYYfXLh9dTiH7LzBbAIhANeKq4KKrBuLrukEDKIhlseC8ZNtqXV-_0yFxKohXR7A

</code>

When we use gitlab oauth login with wordpress oauth server then we received "Could not parse auth data out of gitlab user object."
I've checked response json object which is same as the gitlab json. 

 
#### Steps to reproduce
Install mattermost and Enable authentication with GitLab.
In wordpress our wp oauth server is working fine with other chat clients.

#### Expected behavior
Login to mattermost or return token

**Comment by amyblais** [comment]
What Mattermost and Gitlab versions are you using? What browser and device? Would you be open to sharing your Gitlab config settings? https://docs.mattermost.com/administration/config-settings.html#gitlab

**Comment by mkvaghani** [comment]
Thank you for quick reply. 

Mattermost v5.16.0 -> Clone from github https://github.com/mattermost/mattermost-server.git


I am using following code at http://localhost/wordpress/api/v4/user/index.php 

```
<?php
header('Content-Type: application/json');
$service_url = 'http://localhost/wordpress/oauth/me?access_token='.$_GET['access_token'] ;
$curl = curl_init($service_url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false); // If the url has https and you don't want to verify source certificate
$curl_response = curl_exec($curl);
if ( headers_sent() ) {
    return;
}
header('Content-Type: application/json');
echo $curl_response;
curl_close($curl);
exit
?>
```
Gitlab Configuration settings from system console as follow.

```
Application ID: QaCQNzQpn0AbRDhmcC1FmKTI3hUxg5vTfFdkeKFD
Application Secret Key:6d2SuptucslRIoPZQQHOzg2n22fLxnpoG1jFdPex
GitLab Site URL: http://localhost
User API Endpoint: http://localhost/wordpress/api/v4/user
Auth Endpoint: http://localhost/wordpress/oauth/authorize
Token Endpoint: http://localhost/wordpress/oauth/token
```


At Wordpress oauth server, I've added following client

```
Client Name: Mattermost Chat
Redirect URI: http://localhost:8065/signup/gitlab/complete
Client ID: QaCQNzQpn0AbRDhmcC1FmKTI3hUxg5vTfFdkeKFD
Client Secret: 6d2SuptucslRIoPZQQHOzg2n22fLxnpoG1jFdPex
Client Scope(s): basic
```

I've used following settings in config.json of mattermost 


```
"GitLabSettings": {
        "Enable": true,
        "Secret": "6d2SuptucslRIoPZQQHOzg2n22fLxnpoG1jFdPex",
        "Id": "QaCQNzQpn0AbRDhmcC1FmKTI3hUxg5vTfFdkeKFD",
        "Scope": "basic",
        "AuthEndpoint": "http://localhost/wordpress/oauth/authorize",
        "TokenEndpoint": "http://localhost/wordpress/oauth/token",
        "UserApiEndpoint": "http://localhost/wordpress/api/v4/user"
    },

```

**Comment by mkvaghani** [comment]
Hey @amyblais   
I have solved the issue.  It was conflict in config.js and Gitlab Console
I forgot to change **UserApiEndpoint** in config.js


Now I'm getting another problem.  In redirect_url, I am getting /wordpress/wordperss 2 times
while in Admin Console and config.js I've added GitLab Site URL: http://localhost/wordpress

```
http://localhost/wordpress/wp-login.php?redirect_to=http%3A%2F%2Flocalhost%2Fwordpress%2Fwordpress%2Foauth%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3DQaCQNzQpn0AbRDhmcC1FmKTI3hUxg5vTfFdkeKFD%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8065%252Fsignup%252Fgitlab%252Fcomplete%26state%3DeyJhY3Rpb24iOiJsb2dpbiIsInRva2VuIjoicjRnd2g5YmE2NWRwNTl4enphYjlzODd1ZXVxZGl0OW51Z2RrNG5xdWNzYjdpZHd5N3Vmd2ljcXB1Y3JiZWliMSJ9%26scope%3Dbasic
```

Thank you

**Comment by amyblais** [comment]
@hmhealey Do you know if the above errors is related to Gitlab?

**Comment by mkvaghani** [comment]
@amyblais  @hmhealey  I think it is not related to Gitlab, it is something in mattermost file where it parse gitlab url.
When we run gitlab instance in directory, then it re-write gitlab url with double. While run gitlab instance direct on domain, it does not gives any wrong url.

**Comment by hmhealey** [comment]
While we don't specifically prevent it, we don't officially support using GitLab login with other login providers. That being said, this error seems to indicate that either your OAuth is configured incorrectly or Wordpress is responding to requests differently than GitLab, so it runs into a case that Mattermost doesn't know how to handle. Wordpress may be responding with an error or something that Mattermost doesn't like
