### ISSUE TITLE
Posting using emojis  from OS-keyboard gives error

### ISSUE THREAD

**Issue by sphr** [mattermost/mattermost-server#12940]
#### Summary
Users can not send a message if it contains a emoji selected from the operating systems built in emoji keyboard.

#### Steps to reproduce
Install 5.16.0 and use mysql (mariadb 10.3) and log in to the chat.
Then bring up the operating systems built in smiley keyboard instead of mattermosts emojipicker, whatever emoji you pick will render an error upon submitting.

Mobile app users will see a red questionmark while web browsers will see a Retry/Cancel box.
The bug appears in mobile apps on android, ios and when using web brosers.

#### Expected behavior
When selecting an emoji using the systems built in keyboard and send the message I expect the post to be sent and accepted, perhaps converted to mattermosts colon prefixed ones.

#### Observed behavior (that appears unintentional) 
The post request seems to trigger 500 internal server error in the api at /api/v4/posts

**Comment by sphr** [comment]
> @sphr Which OS and version are you seeing this on (e.g. Windows 10)?

I have managed to replicate this on all webbrowsers I've gotten hand on; ios+safari, android+chrome, ipados+chrome, win10+chrome/firefox/edge. macos+chrome/firefox/safari.

**Comment by sphr** [comment]
I get this error in the logs: 
`
{"level":"error","ts":1572278383.0301757,"caller":"mlog/log.go:174","msg":"Unable to save the Post","path":"/api/v4/posts","request_id":"<removed>","ip_addr":"<removed>","user_id":"<removed>","method":"POST","err_where":"SqlPostStore.Save","http_code":500,"err_details":"id=<remoed>, Error 1366: Incorrect string value: '\\xF0\\x9F\\x99\\x8C' for column `mattermost`.`Posts`.`Message` at row 1"}
`

Updated my intital post with information that we use mysql (mariadb 10.3)

**Comment by sphr** [comment]
The windows 10 emoji picker pops up when pressing [windows]+[.(dot)].

**Comment by amyblais** [comment]
@sphr Would you be able to check if you're able to post OS emojis on our community server and if you experience developer console errors: https://community.mattermost.com/core?

**Comment by sphr** [comment]
> @sphr Would you be able to check if you're able to post OS emojis on our community server and if you experience developer console errors: https://community.mattermost.com/core?
I am not able to reproduce it on the community server.

I have two different docker instanes running 5.16.1 and 5.16.2 conneting to two different mariadb galera sql-clusters both running version: 5.5.5-10.3.18-MariaDB-log MariaDB Server. Both dockerinstances show the same problem. My setup is on team edition, not enterprise as your community server is.

mysql> SELECT default_character_set_name FROM information_schema.SCHEMATA
    -> WHERE schema_name = "mattermost-test";
+----------------------------+
| default_character_set_name |
+----------------------------+
| utf8mb4                    |
+----------------------------+
1 row in set (0.00 sec)

mysql> use mattermost-test;
Database changed
mysql> SELECT CCSA.character_set_name FROM information_schema.`TABLES` T,
    ->        information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA
    -> WHERE CCSA.collation_name = T.table_collation
    ->   AND T.table_schema = "mattermost-test"
    ->   AND T.table_name = "Posts";
+--------------------+
| character_set_name |
+--------------------+
| utf8mb4            |
+--------------------+
1 row in set (0.00 sec)

mysql> SELECT character_set_name FROM information_schema.`COLUMNS`
    -> WHERE table_schema = "mattermost-test"
    ->   AND table_name = "Posts"
    ->   AND column_name = "Message";
+--------------------+
| character_set_name |
+--------------------+
| utf8mb4            |
+--------------------+
1 row in set (0.00 sec)

**Comment by sphr** [comment]
Found and fixed my problem! The documentation is at one place incorrect, here: https://docs.mattermost.com/install/trouble_mysql.html?highlight=utf8

There is a equal sign incorrectly replaced with a hyphen on this line, which I of course copied.
"mmuser:*mmuser-password*@tcp(*host-name-or-IP*:3306)/mattermost?charset-utf8mb4,utf8&readTimeout-30s&writeTimeout-30s"

**Comment by amyblais** [comment]
@sphr Interesting, let me know if you're open to opening a pull request to update it, or let me know if you would like me to.

**Comment by sphr** [comment]
@amyblais I went ahead and attempted to open a pull request on my own, This is a first for me, hope I followed the guidelines correctly.

**Comment by amyblais** [comment]
Awesome! Approved and merged the PR.
