### ISSUE TITLE
Incorrect import of package

### ISSUE THREAD

**Issue by vladislavhirko** [mattermost/mattermost-server#12981]
Hello, i use mattermost sdk and when i add go.mod to my project i can't start it, because one of package which you use has incorrent import address: 

> build command-line-arguments: cannot load github.com/nicksnyder/go-i18n/i18n: module github.com/nicksnyder/go-i18n@latest (v2.0.2+incompatible) found, but does not contain package github.com/nicksnyder/go-i18n/i18n

**Comment by amyblais** [comment]
@vladislavhirko Would you be open to asking about this on our [Developers channel here](https://community.mattermost.com/core/channels/developers)? One of our devs will probably know how to help with this.

**Comment by amyblais** [comment]
There is a thread about this in Developers channel. Latest post: https://community-release.mattermost.com/core/pl/khou5uh6ytrc9f3n6fpwjg7coo.

**Comment by amyblais** [comment]
Closing for now as there hasn't been updates on this for a while. Please re-open this issue if the problem persists or continue the discussion in the Developers channel linked above,
