### ISSUE TITLE
Remote Error TLS: Bad Certificate

### ISSUE THREAD

**Issue by hackdefendr** [mattermost/mattermost-server#12990]
#### Summary
Remote Error TLS: Bad Certificate

#### Steps to reproduce
1. Generate certificate using Windows Certificate Manager (mmc)
2. Import CA certificate into Ubuntu per normal procedure
3. Restart services
4. Client using Personal Access Token is denied stating certificate signed by unknown authority.

#### Expected behavior
Logging in normally via the web interface works without issue. Only when a bot user tries to connect using personal access tokens does the error show up.

#### Observed behavior (that appears unintentional) 
{"level":"error","ts":1572624597.1887794,"caller":"http/server.go:3010","msg":"http: TLS handshake error from xx.xx.xx.xx:36486: remote error: tls: bad certificate","source":"httpserver"}

#### Possible fixes
Mattermost server needs to recognize CA certificates via the OS, in this case Ubuntu 18.04.3.

**Comment by amyblais** [comment]
@hackdefendr What Mattermost server version are you on?

**Comment by hackdefendr** [comment]
I am running latest version 5.16.1.  

FYI this is an integration with a SOAR application called Demisto (Palo Alto). The bot user account has an option to ignore certificate errors, but that isn't working apparently. The bad certificate error comes from mattermost.

**Comment by hackdefendr** [comment]
Is there some place I could put the CA certificate so that Mattermost server will see it?

**Comment by amyblais** [comment]
I'm cleaning up some older issues. If you need further assistance on this, I recommend reaching out to our devs / community via https://forum.mattermost.com/ or via our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help).
