### ISSUE TITLE
"A new version of Mattermost is available" notification remains after selecting to "Refresh the app now"

### ISSUE THREAD

**Issue by uusijani** [mattermost/mattermost-server#13000]
#### Summary
Selecting the "Refresh the app now" link from update notification doesn't make the notification go away.

#### Steps to reproduce
Have MM server updated to latest release. Open an existing session of the web app in Firefox. See the refresh prompt, select "Refresh the app now".

#### Expected behavior
Web page is refreshed, the notification goes away.

#### Observed behavior (that appears unintentional) 
Web page is refreshed, but the update notification is still there, still prompting to refresh.

#### Verbose version
With some of the most recent updates (perhaps 5.16 and newer), the "Refresh the app now" link in the update notification ("A new version of Mattermost is available") on the web app did not make that notification go away for myself and another user. The link did cause a refresh of the page content, but the notification persisted. Meanwhile the version being reported by "About Mattermost" was the correct (5.16.2).

Ctrl+shift+r or other hard refresh attempts did not have an effect, but logging out and then back in to the site finally did make the notification go away.

We're both Firefox users, and due to the nature of the issue it was difficult to tell if this was browser-specific, but a fresh login using Chrome (while the previous session in Firefox still showed the notification) did not bring up the notification in the new session.

The issue, though irritatingly persistent while it lasted, was still relatively ephemeral, and now that it's gone, I wouldn't know how to reproduce it before the next server update. That said, I'll happily provide more details if I can.

**Comment by amyblais** [comment]
@uusijani Can you help with more details on your announcement banner settings https://docs.mattermost.com/administration/config-settings.html#announcement-banner?

I haven't seen this issue on Chrome, so it is possible that this is an issue on Firefox. I can try to reproduce this on Firefox next time we have an update on our internal server.

Also, next time you see this issue it might be helpful to observe Mattermost logs or console logs for any errors.

**Comment by uusijani** [comment]
Hi @amyblais, thanks for taking a look!

Here are the banner settings:

    # grep -i banner config.json 
            "EnablePreviewModeBanner": true,
            "EnableBanner": false,
            "BannerText": "",
            "BannerColor": "#f2a93b",
            "BannerTextColor": "#333333",
            "AllowBannerDismissal": true

I should also mention that I've previously enabled Developer Mode (`"EnableDeveloper": true`), but I'm not sure it's related, since the notification in this issue has the normal blue background, not a purple one.

The issue reappeared today for the other affected user, then kept disappearing and reappearing under testing, but we were unable to pin down any specific reason. Their browser console (Firefox) only has this:

    websocket connecting to wss://[redacted]/api/v4/websocket websocket_client.jsx:35:20

and the server log meanwhile only has this line repeated:

    mlog/log.go:174	{"name":"TypeError","message":"NetworkError when attempting to fetch resource.","stack":""}	{"path": "/api/v4/logs", "request_id": "g8wwo8yu57djmkipjxjxn7hy3y", "ip_addr": "[redacted]", "user_id": "[redacted]", "method": "POST", "err_where": "client", "http_code": 0, "err_details": ""}

(where user_id is the one for the affected user.)

**Comment by amyblais** [comment]
@uusijani We're curious if your server is set up using a subpath, e.g. https://servername.mattermost.com/subpathname?

**Comment by uusijani** [comment]
@amyblais No subpath, just the plain domain.

**Comment by uusijani** [comment]
This hasn't manifested itself in ages anymore, so it's probably fixed.
