### ISSUE TITLE
Go minor version should be 13

### ISSUE THREAD

**Issue by rvillablanca** [mattermost/mattermost-server#13014]
#### Summary
Go minor version should be 13

Currently the go minor version is set to 12. If I try to compile with go version `1.12.13` (the latest of release 1.12) then I get:

`app/response_transfer.go:52:25: rt.headers.Clone undefined (type http.Header has no field or method Clone)` 

It seems the `Clone()` method was added in go `1.13`

#### Steps to reproduce

Use any version of golang `1.12` releases and then complile mattermost

For linux for example
```bash
make build-linux
```

#### Expected behavior
Compilation without errors

#### Observed behavior

```bash
make build-linux
Build Linux amd64
env GOOS=linux GOARCH=amd64 go install -i  -mod=vendor -ldflags '-X "github.com/mattermost/mattermost-server/model.BuildNumber=dev" -X "github.com/mattermost/mattermost-server/model.BuildDate=mié nov  6 01:07:14 UTC 2019" -X "github.com/mattermost/mattermost-server/model.BuildHash=3c532b267270cdbe58fdc6f7238279b477745fb2" -X "github.com/mattermost/mattermost-server/model.BuildHashEnterprise=none" -X "github.com/mattermost/mattermost-server/model.BuildEnterpriseReady=false"' ./...
# github.com/mattermost/mattermost-server/app
app/response_transfer.go:52:25: rt.headers.Clone undefined (type http.Header has no field or method Clone)
make: *** [build/release.mk:6: build-linux] Error 2
```

#### Possible fixes

Change in Makefile the `MINIMUM_SUPPORTED_GO_MINOR_VERSION` variable from 12 to 13

**Comment by hanzei** [comment]
Good catch @rvillablanca :+1:

**Comment by crspeller** [comment]
@rvillablanca Good catch. Thanks!
