### ISSUE TITLE
 Removal of unused status flags in Schemes requests state object

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-server#13029]
Remove unused status flags from https://github.com/mattermost/mattermost-redux/blob/master/src/reducers/requests/schemes.js

We have a pattern to track API requests success, failure and progress states by making respective redux actions like

```javascript

export function getRolesByNames(rolesNames: Array<string>) {
    return bindClientFunc({
        clientFunc: Client4.getRolesByNames,
        onRequest: RoleTypes.ROLES*BY_NAMES*REQUEST,
        onSuccess: <RoleTypes.RECEIVED*ROLES, RoleTypes.ROLES_BY_NAMES*SUCCESS],
        onFailure: RoleTypes.ROLES*BY_NAMES*FAILURE,
        params: [
            rolesNames,
        >,
    });
}

```

which modify the redux state of requests object 

```javascript

export default (combineReducers({
    getRolesByNames,
    getRoleByName,
    getRole,
    editRole,
}): (RolesRequestsStatuses, GenericAction) => RolesRequestsStatuses);

```

Most of these state objects are not needed because we don't consume them either in webapp or in mobile app repo.

The proposed solution is to remove any dispatches with success, failure or progress along with the reducer and initial state entity by checking their dependency in both webapp and mobile app repos.

If the redux state for the request is used only in one component we can use react state instead of redux so, we can remove the entity 

PR's for reference: 
Redux PR: https://github.com/mattermost/mattermost-redux/pull/748
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2490
Web PR: https://github.com/mattermost/mattermost-mobile/pull/2496

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-13545

**Comment by nadalfederer** [comment]
I'll take this

**Comment by jespino** [comment]
Great, thanks @nadalfederer! :tada:
