### ISSUE TITLE
The word "every" is missing from the English (UK) dictionary

### ISSUE THREAD

**Issue by jakeolenick** [mattermost/mattermost-server#13022]
#### Summary
![Annotation 2019-11-07 122622](https://user-images.githubusercontent.com/5423072/68389009-d4ac4c00-0159-11ea-8c52-5c7084c9225e.png)

The word "every" is missing from the English (UK) dictionary

#### Steps to reproduce
Version 4.2.3, the word "every" is missing from the English (UK) dictionary.

#### Expected behavior
The word "every" should not have a red underline. It is a word in both UK and US English and now I've written it so many times it's starting to look like it isn't one, but it definitely is: https://en.wiktionary.org/wiki/every

#### Observed behavior (that appears unintentional) 
There is a red underline under the word "every" when I type it.

#### Possible fixes
Add the word "every" to the English (UK) dictionary.

**Comment by GCHQ77703** [comment]
Spelling seems to be handled by the browser, not Mattermost itself.  You can add it to your local dictionary normally by right clicking --> add to dictionary.

**Comment by amyblais** [comment]
@jakeolenick Did the above suggestion help?

**Comment by amyblais** [comment]
Closing as there hasn't been updates on this for a while. Please re-open this issue if the problem persists,
