### ISSUE TITLE
Add example usage of EnsureBot to the Demo Plugin

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-server#13027]
The existing implementation would be replaced to use EnsureBot with options. This is a follow up on [https://github.com/mattermost/mattermost-server/pull/12153](https://github.com/mattermost/mattermost-server/pull/12153|smart-link) .

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-19970

**Comment by promulo** [comment]
Hello, may I take this one as my first issue? :slightly_smiling_face:
