### ISSUE TITLE
Modal pops down when attempting to scroll down to see if there are more emoji

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-server#13028]
iPhone 6s, iOS 12

1. In a test channel, make a post
2. Long press on the post and select ""Add Reaction""
3. Repeat step 2) until you have about 12 reactions on the post
4. Long press on ONE of the emoji reactions on the post"
5. Swipe up to fully open the drawer and scroll to bottom of reaction list in one motion
6. Swipe up again as if to try to scroll further

Observed: List jumps down a little bit on each swipe up
Expected: Not sure; maybe something less jumpy to indicate the end of the list?

Screen recordings in [comment below ]( https://mattermost.atlassian.net/browse/MM-13669?focusedCommentId=55748&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-55748).

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-13669

**Comment by ami9000** [comment]
I can take this!
