### ISSUE TITLE
URGENT: WebApp does not allow logging in and displays "please enter your password"

### ISSUE THREAD

**Issue by hahmadia** [mattermost/mattermost-server#13034]
#### Summary
I suspect that https://github.com/mattermost/mattermost-webapp/commit/5e89abcbfafadb3c0b070121d8884a84c3a68e12 introduces a bug which breaks the WebApp and does not allow a user to sign in. 

#### Steps to reproduce
1. Check out the latest master branch on WebApp repo
2. Try to login into any account

#### Expected behavior
Able to login without error

#### Observed behavior (that appears unintentional) 
Not able to login no matter what account you use and the error `Please enter your password` is displayed.

#### Possible fixes
I'm not sure what the possible fix would be but I suspect that https://github.com/mattermost/mattermost-webapp/commit/5e89abcbfafadb3c0b070121d8884a84c3a68e12 introduces the bug. Checking out any commit before this will fix the problem. 

![GH13034](https://user-images.githubusercontent.com/17804942/68490506-151dcf80-0217-11ea-866d-ce2e440e6b5f.gif)

**Comment by amyblais** [comment]
@hahmadia Are you not able to log in to the community servers?

**Comment by amyblais** [comment]
Ticket open to fix: https://mattermost.atlassian.net/browse/MM-19995.

**Comment by hahmadia** [comment]
Fixed in https://github.com/mattermost/mattermost-webapp/pull/4170
