### ISSUE TITLE
Issue while searching user

### ISSUE THREAD

**Issue by RajatVaryani** [mattermost/mattermost-server#13035]
#### Summary
Something wrong while tagging a person in thread. 

#### Steps to reproduce
1. Go to any thread
2. Search for `@chris`

**The issue is only for `@chris.jeanty `**

#### Expected behavior
Search should be displaying result in a proper way

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/37879062/68493874-52b04600-0273-11ea-9e7c-0217f4005501.png)

#### Possible fixes
-

**Comment by amyblais** [comment]
@RajatVaryani What version of Mattermost did you see this issue on?

**Comment by RajatVaryani** [comment]
@amyblais This is happening on the community server.

**Comment by amyblais** [comment]
What OS and version are you on?

**Comment by RajatVaryani** [comment]
@amyblais I am on macOS Mojave Version `10.14.6`.

**Comment by amyblais** [comment]
@RajatVaryani Are you seeing this issue consistently? Is this on webapp or desktop app?

**Comment by RajatVaryani** [comment]
Yes I am facing it consistently. It's desktop app.

**Comment by amyblais** [comment]
@RajatVaryani Are you on desktop app v4.3.1 version? 
I want to open a bug ticket for this and just want to gather basic information about your environment.

**Comment by RajatVaryani** [comment]
I am on `Version 4.2.1 (4.2.1.62)`

**Comment by amyblais** [comment]
Would you be open to trying this on v4.3.1 desktop version?

**Comment by RajatVaryani** [comment]
Yes I tried. The issue is no more reproducible. I am closing the issue. 
Thank you.
