### ISSUE TITLE
System message when a mentioned user is not in the channel is grammatically wrong in German

### ISSUE THREAD

**Issue by jmairboeck** [mattermost/mattermost-server#13044]
#### Steps to reproduce
Have Mattermost in German and write a message mentioning a user who is not in the current channel.

#### Expected behavior
The system message that follows this should be grammatically correct.

#### Observed behavior (that appears unintentional) 
The following message appears:

> @username wurde erwähnt, befinden sich aber nicht im Kanal. Möchten Sie sie zu diesem privaten Kanal hinzufügen? Sie werden Zugriff auf den Nachrichtenverlauf haben.

This appears to be a literal translation of the English "singular they" to avoid pronoun issues. However, this looks at least strange in German where "sie" (the 3rd person plural form) can't be used for the singular case.

It seems that the message is split between [multiple internal messages](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/de.json#L2442). This would need to be changed to get a grammatically correct translation. At least there need to be different cases for singular and plural also for the other message parts.

#### Possible fixes
The pronoun issue is not as easily avoidable in German than in English because we have no equivalent of the "singular they" (yet). It would have to be something like

> @username wurde erwähnt, befindet sich aber nicht im Kanal. Möchten Sie ihn/sie zu diesem privaten Kanal hinzufügen? Er/Sie wird Zugriff auf den Nachrichtenverlauf haben.

(which also looks a bit ugly, but I can't find a better way to write this).

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-20043.
