### ISSUE TITLE
Add unit tests to "LogsCmd" to use testify

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#13046]
Mattermost is increasing the unit test coverage for the [mmctl CLI tool](https://github.com/mattermost/mmctl). Through the use of a mocked client that will simulate the interactions with the server, the goal is to create a suite of tests that check the tool's behavior in a flexible and robust way.

This Help Wanted issue covers the addition of unit tests to the `LogsCmd` command, in the `commands/logs.go` file. The expected way to add these tests is to create a test function in the `commands/logs_test.go` file and add one `s.Run` block for each possible test case.

For more information on how to add a unit test to mmctl, take a look at the campaign blogpost: https://developers.mattermost.com/blog/unit-testing-mmctl-commands/

Example: mattermost/mmctl#37

If you have questions about the ticket or you need any help, feel free to contact `miguel.delacruz` in https://community.mattermost.com/

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-20028)

**Comment by zujko** [comment]
I can pick this up

**Comment by mgdelacroix** [comment]
Great, thanks for working on this @zujko! :tada:
