### ISSUE TITLE
Deleted messages are emailed

### ISSUE THREAD

**Issue by levigo-systems** [mattermost/mattermost-server#13064]
#### Summary
Notifications of a new message get also emailed if the message was already deleted at the chat.

#### Steps to reproduce
We are using Mattermost 5.16.1.
1. Enable the email notifications on user B
2. Send a chat message from user A to user B
3. Delete the chat message 
4. Look at the mailbox from user B -> There you can see the deleted message

#### Expected behavior
In the email there shouldn't be the deleted message.
Possible behavior:
1. No Mail 
2. "This message got deleted"

#### Observed behavior (that appears unintentional) 
-

#### Possible fixes
-

**Comment by amyblais** [comment]
@levigo-systems Emails are sent for all notifications when email notifications are enabled. You could enable email batching and choose how often emails get sent: https://docs.mattermost.com/administration/config-settings.html#enable-email-batching. 

In Enterprise Edition you can hide email content: https://docs.mattermost.com/administration/config-settings.html#email-notification-contents.

**Comment by levigo-systems** [comment]
You can hide some content but this is not the solution for this issue.
If a user wants notifications with the full message body, we are still running into the problem.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by levigo-systems** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/39034261-do-not-send-notification-emails-if-chat-message-go

**Comment by amyblais** [comment]
Thank you! This can be followed via the feature idea forum,
