### ISSUE TITLE
Migrate emojiIdCacheByName cache from store/sqlstore/emoji_store.go to the new store/localcachelayer

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-server#13070]
Mattermost is migrating the old way to implement caches moving them behind a transparent layer on to of the store and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `emojiIdCacheByName` cache variable in the `store/sqlstore/emoji_store.go` file to the `store/localcachelayer`.

The expected way to implement it is, go to the `store/sqlstore/emoji_store.go` file get all the code that is related to the cache variable `emojiIdCacheByName` and move it to the `store/localcachelayer`

Besides is expected to generate tests mocking the database store, and checking that the cache behavior is the expected one.

Example: mattermost/mattermost-server#13045

If you have any question, you can contact with `jesus.espino` at https://community.mattermost.com

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-20107

**Comment by larkox** [comment]
May I take this one?

**Comment by jespino** [comment]
Sure, go ahead
