### ISSUE TITLE
Erroneous Go module path

### ISSUE THREAD

**Issue by Helcaraxan** [mattermost/mattermost-server#13077]
#### Summary
After stumbling over this project while debugging a third-party dependency issue I realised that the project is not specifying it's Go module path correctly.

In the current state the `go.mod` file sets it to:
```text
github.com/mattermost/mattermost-server
```
However, given that the project is already at v5 the path should instead be:
```text
github.com/mattermost/mattermost-server/v5
```
or even
```text
github.com/mattermost/mattermost-server/v6
```
if you follow the recommended practice of releasing a new major version when migrating a v2+ project to Go modules.

Although there are workarounds, as well as a little lenience built into the Go toolchain, the current erroneous path can (and will) result in import issues for Go projects depending on this one.

For more details please see the [Go wiki](https://github.com/golang/go/wiki/Modules) on the topic. And more specifically [this sub-section](https://github.com/golang/go/wiki/Modules#incrementing-the-major-version-when-first-adopting-modules-with-v2-packages).

Am also happy to answer below any other questions related to modules that this issue might raise. 

#### Steps to reproduce
N.A.

#### Expected behavior
N.A.

#### Observed behavior (that appears unintentional) 
N.A.

#### Possible fixes
Fix the module path and (potentially) tag a v6 with the modified path.

**Comment by cpoile** [comment]
Hello @Helcaraxan -- yep, we're aware of the problem and we're in the process of fixing it (not a quick fix, unfortunately). Until we finish it, you can use a specific hash in your go.mod, like so:
```
	github.com/mattermost/mattermost-server v0.0.0-20190911153551-9c3fc4ab9f30
```
Does that help for now?

**Comment by Helcaraxan** [comment]
Hello @cpoile.

That's alright. I was not running into any issues. I simply spotted the problem with the module path while debugging another dependency issue where `mattermost-server` was involved in an indirect fashion.

Might I ask why this is "not a quick fix"? Is it due to the fact that you want to tag a v6 at the same time?

**Comment by lieut-data** [comment]
@Helcaraxan, sorry for the delay on this one -- we've got a pending fix over at https://github.com/mattermost/mattermost-server/pull/13186.

**Comment by Helcaraxan** [comment]
Thank you very much for the update @lieut-data, it's much appreciated.

Great to say that this is being addressed. 🙂
