### ISSUE TITLE
Unable to see Add Incoming Webhook

### ISSUE THREAD

**Issue by craph** [mattermost/mattermost-server#13079]
#### Summary
I'm unable to create an incoming webhook in my docker Mattermost team edition.

#### Steps to reproduce

1. Run the official docker Mattermost container

1. Check that Enable Incoming Webhooks is set to True

1. Try to find the "Add incoming webhook"

#### Expected behavior
I can't find the button to add incoming webhooks

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/14820052/68776855-0aa57080-0631-11ea-9fee-72cc8e7ff412.png)

**Comment by craph** [comment]
Sorry it was my fault of misunderstanding the documentation here : https://docs.mattermost.com/developer/webhooks-incoming.html#simple-incoming-webhook

Please could you add to switch back to the Team view after enabling the Incomming / Outgoing Webhooks because the :

> Go to "Main menu" is not to clear I think

**Comment by amyblais** [comment]
@craph Would you be open to re-opening this issue in the docs repo https://github.com/mattermost/docs/issues?

**Comment by craph** [comment]
Hi @amyblais ,

I have open a new issue : https://github.com/mattermost/docs/issues/3157 as you requested

**Comment by amyblais** [comment]
Thank you! I made it into Help Wanted for now,
