### ISSUE TITLE
Migrate profilesInChannelCache cache from store/sqlstore/user_store.go to the new store/localcachelayer

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-server#13073]
Mattermost is migrating the old way to implement caches moving them behind a transparent layer on to of the store and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `profilesInChannelCache` cache variable in the `store/sqlstore/user_store.go` file to the `store/localcachelayer`.

The expected way to implement it is, go to the `store/sqlstore/user_store.go` file get all the code that is related to the cache variable `profilesInChannelCache` and move it to the `store/localcachelayer`

Besides is expected to generate tests mocking the database store, and checking that the cache behavior is the expected one.

Example: mattermost/mattermost-server#13045

If you have any question, you can contact with `jesus.espino` at https://community.mattermost.com

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-20096

**Comment by phillipahereza** [comment]
@jespino can I work on this

**Comment by jespino** [comment]
Sure! Thanks @phillipahereza

**Comment by jasonblais** [comment]
Hey @phillipahereza, let us know if you're still open to working on this one? Let us know if you have any questions!

In the meantime, I'll open this up for grabs :)

**Comment by larkox** [comment]
May I take this one?

**Comment by jasonblais** [comment]
Go for it! 🚀

**Comment by jasonblais** [comment]
By the way @larkox, you, `@nadalfederer` and `@m-zubairahmed` are doing a ton which is awesome. I'm also curious if you had interest tackling a help wanted issue that was [at a harder level](https://github.com/mattermost/mattermost-server/issues?utf8=%E2%9C%93&q=label%3A%22Up+For+Grabs%22+label%3ADifficulty%2F3%3AHard) for a challenge?

Totally no worries if not yet, all in all, huge thanks for your help, you're really making an impact here!! :tada:

**Comment by larkox** [comment]
Thanks Jason!
Yes, I have in mind also tackling harder level issues. Nevertheless, I like to keep doing these lower level issues because they get me to parts of the code I still do not know in a way I can get more used to the general code and structure of the project.
You will hear soon of me in one of those!

**Comment by jasonblais** [comment]
>  I like to keep doing these lower level issues because they get me to parts of the code I still do not know in a way I can get more used to the general code and structure of the project.

Sounds like a great plan! Thanks again for all you do :)
