### ISSUE TITLE
Increase max dimesion for the image

### ISSUE THREAD

**Issue by Adammmmmmmmmmmmmmmmmmm** [mattermost/mattermost-server#13084]
Hello.

So here is an issue.
When I want to add image to conversation I am getting an error "20191113_164727 (1).jpg dimensions (5760 by 4312 pixels) exceed the limits"
AFAIK it is hardcoded by:
`MaxImageSize         = 6048 * 4032 // 24 megapixels, roughly 36MB as a raw image`

So it is ‭24,385,536‬ pixels.
And my photo have 24,837,120 pixels

Diff is only 451,584.

So I propose to increase this limit for modern smartphones or implement some autocompresor like on facebook.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by amyblais** [comment]
I'll close this for now but I hope you will open a feature request issue for this or let us know if you're interested in implementing this,
