### ISSUE TITLE
Migrate tool dependencies to be tracked in go.mod

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#13088]
### Problem

The mattermost codebase uses several tools like `megacheck`, `mgotool`, `mockery` etc. to achieve various tasks. However, the versions of these tools are not tracked in go.mod and directly fetched from the tip of their respective repos. This is a source of discrepancy and possible bugs because one single update from the tool developer might break things in the codebase.

It is also not straightforward to track the dependencies because for it to appear in go.mod, it has to be part of the repo codebase. Fortunately, we have an official recommendation on how to approach this: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module.

#### Approach:

The core idea is to use a tools.go file under a separate build tag so that it is ignored when building the repo. But the dependencies inside the file will get tracked in go.mod because commands like `go  mod tidy` looks into _all_ files under all build tags.

However, there is a slight complication in our case because all of our dependencies are vendored. But we don't want the tools also to be vendored, just their versions tracked.

An effective way around this is to have a sub-module with a separate go.mod file under a `tools` directory. While sub-modules within a single repo are discouraged, but in this case, there is no extra code in that module and its sole purpose is to track the tool dependencies. And as a concrete example, [golangci-lint](https://github.com/golangci/golangci-lint/tree/master/tools) also does the same.

This solves both of our problems of tracking tool dependencies as well as not getting them vendored.

EDIT: We will also be installing the tools in a `bin` directory inside the repo root so as to not pollute any global namespace with one repo's tools. As different repos can use different versions of a tool. And it is good to keep one repo's tools localized within the repo. Similar to `node_modules/bin` directory.

#### Future solutions:

https://github.com/golang/go/issues/34506#issue-497899555 is the correct solution to this where we can have separate go.mod files - one for the repo, and one for the tools. For eg. `go.mod` and `go.tools.mod`. And we can use `go.tools.mod` when working with tools. But this will only probably be available in 1.15.

Until then, the above approach is good enough.

I will be sending a PR tagging this issue as a reference.

/cc @hanzei @reflog

**Comment by reflog** [comment]
@agnivade - I am not sure that this problem is critical enough to add this additional complication. If it's planned for Go 1.15 - my vote is to wait for it. 2/5 on this

**Comment by agnivade** [comment]
> I am not sure that this problem is critical enough to add this additional complication

I see. Do you not think relying on tools to be stable at tip poses a risk of breakage ? Especially when modules are now available ? It takes us back to the GOPATH days when we already have something at our disposal. It also means tool authors have more freedom to change things at tip, which makes it even more riskier. Personally, I believe this is a problem worth addressing.

IMHO, there isn't much difference between this approach and what will be in 1.15. It's just that there won't be a need for a sub-module. But other than that, we will still have the tools.go and the go.mod files.

WDYT ?

**Comment by reflog** [comment]
I don't mind fixing this, but I know there are a few people who will object to having submodules just because of this. Pinging @crspeller and @jespino

**Comment by agnivade** [comment]
Fair enough, the submodule thing is a concern for me too. However, after discussing with a Go team member (@heschik) on slack, we came to the decision that since the submodule does not contain any code whatsoever (and given that golangci already use it), there shouldn't be any complications. Hence, I suggested this.

Open to hearing any likely issues that can arise from this.

**Comment by heschik** [comment]
`-modfile` is in 1.14. Only `-g` was pushed.

**Comment by crspeller** [comment]
I think I agree with @reflog here. If this issue is going to be fixed by go officially next version, let's just wait for that. Unless we are running into critical issues.

**Comment by agnivade** [comment]
Oh I see that it's already in tip ! That's great, let's wait for 1.14 then. Thanks for your input @reflog and @crspeller !
