### ISSUE TITLE
Reduce the size of web app using code splitting and tree shaking.

### ISSUE THREAD

**Issue by MathewtheCoder** [mattermost/mattermost-server#13097]
#### Summary
Currently the entire webapp with Messaging and admin has to be downloaded by the user to use the website.

#### Expected behavior
1) We need to lazy load only required portions of webapp. 
2) If tree shaking is supported by the modules used we have to take advantage.

#### Possible fixes
Use react new feature **Lazy** and **Suspence** to lazy load required portions.
Also importing only required functions from big modules would also help reduce our bundle size. That is apply Tree shaking to eliminate as much dead code as possible.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by amyblais** [comment]
I'll close this for now as we haven't received feedback on this for a while. I hope you will open a feature request issue for this,
