### ISSUE TITLE
Unable to reference channel in a message with !

### ISSUE THREAD

**Issue by craph** [mattermost/mattermost-server#13092]
#### Summary
In a channel when I want to reference another public channel I'm unable to do it by using !

#### Steps to reproduce
1. Use the latest docker container of Mattermost.

1. Create another public channel

1. In town-square type ! and none other public channel appear

#### Expected behavior
Other public channel should appear when ! is type like mentionned here : 

- https://mattermost.atlassian.net/browse/MM-1498

- https://mattermost.atlassian.net/browse/MM-1618

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/14820052/68878518-2760a780-0708-11ea-91d5-117c833f91e8.png)

Nothing appear here.

So, what is the correct shortcut to link to another public channel for members and not members of the referenced public channel ? 

**Should I use `!` or `~` ?**

Thank you very much for your help.

Best regards,

**Comment by amyblais** [comment]
You can use ``~``.

**Comment by craph** [comment]
Thank you @amyblais for your answer.

But why use `~`  because in the two links I mentionned in my previous message explains to use `!`

There is no documentation about that.

**Comment by amyblais** [comment]
@craph Those are old Jira tickets. You can open a doc issue in the docs repo for us to add documentation for it.

**Comment by amyblais** [comment]
Actually, it's already in the documentation: https://docs.mattermost.com/help/messaging/keyboard-shortcuts.html#messages. 

Feel free to open an issue in the docs repo if you'd like to suggest making it clearer,
