### ISSUE TITLE
Search input of channel members modal not working correctly

### ISSUE THREAD

**Issue by Pomyk** [mattermost/mattermost-server#13095]
#### Summary
Search input of channel members modal clears it's value when typing.

#### Steps to reproduce
Using current master branch, when I type something into the search of members modal the input keeps resetting. Search works, but it's hard to write something longer than 1-2 letters.

#### Expected behavior
The input shouldn't be resetting.

#### Possible fixes
Git bisect leads to: https://github.com/mattermost/mattermost-webapp/pull/3725

**Comment by amyblais** [comment]
Thank you, opened a ticket here: https://mattermost.atlassian.net/browse/MM-20180.
