### ISSUE TITLE
KVSetWithOptions(): Unexpected behaviors presents with nil values when EncodeJSON enabled

### ISSUE THREAD

**Issue by ilgooz** [mattermost/mattermost-server#13131]
### Summary
When `EncodeJSON=true`, `isSet, err := KVSetWithOptions(key, newValue, options)` API behaves unexpectedly while dealing with `nil` values.

Unexpected behavior happens for both cases when  `PluginKVSetOptions.OldValue` or `newValue` set to `nil`.

**Unexpected behavior 1: OldValue=nil, newValue=anything**
When `OldValue=nil`, even if the _key_ is never used before, _newValue_ cannot be set (`isSet=false`, `err=nil`). 

Expected behavior is to be able to set the _newValue_ if there is nothing set before for the same _key_ when `OldValue=nil`.

The reason of this behavior is, `OldValue=nil` gets marshaled to JSON before comparison query made to the database. _OldValue=nil_ gets interpreted as a `null` JSON value which is represented as `[110 117 108 108]` in bytes.

When comparison query made to the DB, it checks for `OldValue=[110 117 108 108]` where it actually needs to check for `OldValue=[]` which is zero bytes.

As a result, a match cannot be found for `OldValue=nil` in the DB and this makes it impossible to set a _newValue_ with the condition of if there is no old value, in other means, if there is no set made for the _key_ before.

**Unexpected behavior 2: OldValue=anything or not used, newValue=nil**
_newValue_ interpreted and written as `null` in other means as `[110 117 108 108]` in bytes to the database.

When we make a regular _KVGet()_ we get a `[110 117 108 108]` data which is not OK because we meant deleting the existent value by passing a nil _newValue_ in the first place.

The expected behavior here is to get an empty byte slice returned by a call to _KVGet()_.

We also don't want `[110 117 108 108]` value to be set for the _key_ because if we fix the 1st unexpected behaviour and use _KVSetWithOptions()_ with  `OldValue=nil`, this time there will be a value in the DB and old values will not match again.

### Steps to reproduce 
Use the below code for testing the **1st** unexpected behavior:
```go
options = model.PluginKVSetOptions{
  EncodeJSON: true,
  Atomic: true,
  OldValue: nil,
}
isSet, err := KVSetWithOptions("a-never-used-new-key", true, options)
// OBSERVED: you'll notice isSet=false & err=nil
// EXPECTED: we expect isSet=true & err=nil
```

Use the below code for testing the **2nd** unexpected behavior:
```go
options = model.PluginKVSetOptions{
  EncodeJSON: true,
}
isSet, err := KVSetWithOptions("another-already-set-key", nil, options)
// OBSERVED & EXPECTED: you'll notice isSet=true & err=nil
data, err = p.API.KVGet("another-new-key")
// OBSERVED: you'll notice data=[110 117 108 108] & err=nil
// EXPECTED: we expect data=[] & err=nil
```

### Possible fixes
One possible fix to skip marshaling `OldValue` and `newValue` when `EncodeJSON=true`. This way:

* **for the 1st unexpected behavior:** When `OldValue=nil`, DB query will expect there is no insert made for the _key_ while inserting the _newValue_. Otherwise DB insert operation return with an error. 

* **for the 2nd unexpected behavior:** `newValue=nil` will not get manipulated as `[110 117 108 108]`. Current code already behaves in a way to delete existent DB record for the _key_ when `newValue=nil`.

/cc @lieut-data, @g3rv4

**Comment by lieut-data** [comment]
Great eagle eyes, @ilgooz -- My inclination is to revert the change from v5.18 so that we can address these issues properly before the public release. Of course, this will be much easier once we move all of this to a separate repository.

@hanzei, any objections with the plan to revert?
