### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Can change Site Name setting"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13170]
**Test Key:** SC20335

**Test file:** `/cypress/integration/system_console/ui_and_api/customization_spec.js`

**Title:** Can change Site Name setting
    
**Steps:**
1. Login as sysadmin and visit the page "/admin_console/site_config/customization" directly
2. Change set value and save
        
**Expected:**
1. Verify that the setting, help text and set value is visible and match text
2. Verify that the value is save, directly via REST API
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-20335](https://mattermost.atlassian.net/browse/MM-20335)

Sample PR: https://github.com/mattermost/mattermost-webapp/pull/4262/files

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by sij507** [comment]
@saturninoabril I am not sure what you mean by "Verify that the setting, help text and set value is visible and match text", can you explain a bit more in details? Thanks!

**Comment by saturninoabril** [comment]
@sij507 Thanks for asking.

<img width="924" alt="Screen Shot 2019-11-21 at 7 57 07 AM" src="https://user-images.githubusercontent.com/5334504/69288554-ec450380-0c34-11ea-81e3-7489c1eed0b5.png">

[1] Check that the [setting name is visible and matches the text](https://github.com/mattermost/mattermost-webapp/pull/4262/files#diff-4e2f1cb9fa9c43aec2745e547d241001R27-R29)

[2] Check that the [input box has default value](https://github.com/mattermost/mattermost-webapp/pull/4262/files#diff-4e2f1cb9fa9c43aec2745e547d241001R54-R57).  The default value depends on the [setup before running the test](https://github.com/mattermost/mattermost-webapp/pull/4262/files#diff-4e2f1cb9fa9c43aec2745e547d241001R13-R17).

[3] Verify that the [help text is visible and matches the text](https://github.com/mattermost/mattermost-webapp/pull/4262/files#diff-4e2f1cb9fa9c43aec2745e547d241001R31-R52)

**Comment by sij507** [comment]
@saturninoabril Thanks! I would like to work on this ticket.

**Comment by saturninoabril** [comment]
@sij507 Cool, thanks!

**Comment by sij507** [comment]
@saturninoabril The site name's setting name and help text don't have element id. I am not familiar with creating element id. I tried, but couldn't figure out how and where to create the element id. Would you mind giving me an example of the site name's setting name and help text? Thanks!

**Comment by saturninoabril** [comment]
Sure, you may add the following data-testid.  Let me know if that works.

```diff
--- a/components/widgets/settings/setting.tsx
+++ b/components/widgets/settings/setting.tsx
@@ -23,7 +23,10 @@ const Setting: React.FC<Props> = ({
     helpText,
 }: Props) => {
     return (
-        <div className='form-group'>
+        <div
+            data-testid={inputId}
+            className='form-group'
+        >
             <label
                 className={'control-label ' + labelClassName}
                 htmlFor={inputId}
@@ -32,7 +35,10 @@ const Setting: React.FC<Props> = ({
             </label>
             <div className={inputClassName}>
                 {children}
-                <div className='help-text'>
+                <div
+                    data-testid={inputId + 'help-text'}
+                    className='help-text'
+                >
                     {helpText}
                 </div>
                 {footer}
```

```diff
--- a/components/widgets/settings/text_setting.tsx
+++ b/components/widgets/settings/text_setting.tsx
@@ -58,6 +58,7 @@ export default class TextSetting extends React.Component<WidgetTextSettingProps>
 
             input = (
                 <textarea
+                    data-testid={this.props.id + 'input'}
                     id={this.props.id}
                     style={style}
                     className='form-control'
```

**Comment by sij507** [comment]
@saturninoabril Thanks, it works, please review.

**Comment by jasonblais** [comment]
Thanks @sij507 for the contribution!
