### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Can change About Link setting"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13177]
**Test Key:** SC20341

**Test file:** `/cypress/integration/system_console/ui_and_api/customization_spec.js`

**Title:** Can change About Link setting
    
**Steps:**
1. Login as sysadmin and visit the page "/admin_console/site_config/customization" directly
2. Change set value and save
        
**Expected:**
1. Verify that the setting, help text and set value is visible and match text
2. Verify that the value is save, directly via REST API
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-20341](https://mattermost.atlassian.net/browse/MM-20341)

Sample PR: https://github.com/mattermost/mattermost-webapp/pull/4262/files

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by fm2munsh** [comment]
I'll grab this one

**Comment by saturninoabril** [comment]
@fm2munsh Awesome, thanks!
