### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Can change Site Description setting"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13178]
**Test Key:** SC20332

**Test file:** `/cypress/integration/system_console/ui_and_api/customization_spec.js`

**Title:** Can change Site Description setting
    
**Steps:**
1. Login as sysadmin and visit the page "/admin_console/site_config/customization" directly
2. Change set value and save
        
**Expected:**
1. Verify that the setting, help text and set value is visible and match text
2. Verify that the value is save, directly via REST API
        
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Jira ticket**: [MM-20332](https://mattermost.atlassian.net/browse/MM-20332)

Sample PR: https://github.com/mattermost/mattermost-webapp/pull/4262/files

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by sij507** [comment]
@saturninoabril I will work on this ticket

**Comment by saturninoabril** [comment]
@sij507 Cool, thanks!

**Comment by saturninoabril** [comment]
@sij507 Just checking progress of this ticket.

**Comment by sij507** [comment]
@saturninoabril Sorry for the delay, I was traveling this month.  Please review when you have time, thanks!

**Comment by saturninoabril** [comment]
@sij507 no worries and thanks! Have a safe travel and happy holidays!
