### ISSUE TITLE
Simplify the way editing a message works

### ISSUE THREAD

**Issue by carlspring** [mattermost/mattermost-server#13184]
1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.

This is a change request.

2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).

It does not involve security.

3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

# Summary

When you edit a message, a new pop-up appears in which you have to change the text. In most modern chat systems, when you hit the up arrow in the text field, it will display the text of the previous message and you'll simply be able to edit it. If you hit up again and keep hitting it, it will keep scrolling up to earlier messages and you would be able to update them this way too.

I think that this is a much simpler and straight-forward way to do it. It's intuitive and will feel natural to a lot of other users who are acustomed to this and I would therefore like to raise this change request!

Thanks for all your hard work and I hope this could help improve the user experience for others as well!

**Comment by amyblais** [comment]
Thanks, appreciate your feedback,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by amyblais** [comment]
I'll close this for now, but I hope you will open a feature request issue for this or let us know if you're interested in implementing this,
