### ISSUE TITLE
Failed to persist config to mysql when there are CJK characters in config.

### ISSUE THREAD

**Issue by qiuyuzhou** [mattermost/mattermost-server#13204]
#### Summary
I deploy mm with env var MM_CONFIG="mysql://xxxxxx".
Failed to set TeamSettings.SiteName to a string with CJK characters:
```
2019-11-23T20:41:54.648525+08:00 error mlog/log.go:174 path=/api/v4/config 
request_id=nw59nacmttngpnzbwdg8qke67o ip_addr=27.38.249.244 
user_id=mhw6fzaiptridbbz99pf64b9oy method=PUT err_where=saveConfig http_code=500 
err_details=failed to persist: failed to record new configuration: 
Error 1366: Incorrect string value: '\xE9\xA1\xBA\xE9\x81\x93...' for column 'Value' at row 1 An error occurred saving the configuration
```
I have tried store config in postgresql db, it's work with CJK characters.

#### Steps to reproduce
mm 5.17.0
On a MM which store config in mysql database. [Configuration in the Mattermost Database](https://docs.mattermost.com/administration/config-in-database.html)
Try to set `Customization > Site Name` to CJK content(你好世界).

#### Possible fixes

Maybe it should use `blob` type for the `Data` column in table `Configurations`
The column `data` in table `ConfigurationFiles`  also should be blob type then it could store binary file in it.

**Comment by amyblais** [comment]
@qiuyuzhou Do you know if this is a new issue in v5.17.0?

I'm wondering if any of these articles may help:
 - https://docs.mattermost.com/install/i18n.html
 - https://docs.mattermost.com/install/requirements.html#database-software

**Comment by qiuyuzhou** [comment]
The chat messages with CJK characters could be persist and full-text search in the same mysql database.
I guess the problem is not in the DB layer.
@amyblais

**Comment by qiuyuzhou** [comment]
After some dig, I have found the `Posts` table has `DEFAULT CHARSET=utf8mb4`, but the `Configureations` table has `DEFAULT CHARSET=latin1`.

Workaround manual modify the character set:
```sql
ALTER TABLE `Configurations` MODIFY COLUMN Value mediumtext CHARACTER SET utf8mb4;
```
Suggest update these code
https://github.com/mattermost/mattermost-server/blob/27375cd081ca5a193a85a4501ec43c1651216147/config/database.go#L99-L103
to
```golang
_, err = db.Exec(`ALTER TABLE Configurations MODIFY Value MEDIUMTEXT CHARACTER SET utf8mb4`)
```

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-20695.
