### ISSUE TITLE
Documentation on muting channels is unclear

### ISSUE THREAD

**Issue by nmatt** [mattermost/mattermost-server#13210]
From reading the documentation on muting channels, I can't figure out the following: Does one still get (a) desktop and (b) e-mail notifications for direct mentions on a muted channel?

**Comment by amyblais** [comment]
@nmatt Would you be open to re-opening this issue on the docs repo here https://github.com/mattermost/docs/issues and someone on our team can help update the docs?

**Comment by nmatt** [comment]
Done (https://github.com/mattermost/docs/issues/3187), sorry about the wrong repo.
