### ISSUE TITLE
System Console 'Find settings' does not index plugin names properly.

### ISSUE THREAD

**Issue by GCHQ77703** [mattermost/mattermost-server#13218]
#### Summary
System Console 'Find settings' does not index plugin names.

#### Steps to reproduce
1. Install Mattermost v5.16.3 with 'Jira' prepackaged plugin
2. Go to System Console as an administrative user.
3. Search for 'Jira'

#### Expected behavior
It comes up with the 'Jira' plugin section.

#### Observed behavior (that appears unintentional) 
It comes up with nothing

#### Possible fixes
Index the list of names to a better extent.  Interestingly, 'J' does highlight 'JIRA'.

**Comment by amyblais** [comment]
We have an existing ticket that will be implemented in 5.18: https://mattermost.atlassian.net/browse/MM-16313. Does this describe your issue?

**Comment by GCHQ77703** [comment]
Yep, my bad.  Evidently my 'JIRA-fu' is not up to it.
