### ISSUE TITLE
SMTP module doesn't properly send email credentials to Zoho

### ISSUE THREAD

**Issue by KerimG** [mattermost/mattermost-server#13224]
Mattermost Version: 5.17.1
Database Schema Version: 5.17.0
Database: postgres
nginx version: nginx/1.14.0 (Ubuntu)

#### Summary
I am not sure if this is related to Zoho but it appears as though Mattermost doesn't correctly send the email credentials.

#### Steps to reproduce
Create a zoho account and use smtp.zoho.eu as SMTP server.
Server: smtp.zoho.eu
Port: 465
Auth: true
Username: zoho.com account
Password: mystrongpassword

#### Expected behavior
I expect that the test email is sent successfully. I tried the SMTP settings in other applications (such as Thunderbird) to make sure it's not some credentials error or something and the SMTP settings work.

#### Observed behavior (that appears unintentional) 
SMTP test returns

```
Connection unsuccessful: Connection unsuccessful: SendMail: Failed to close connection to SMTP server, 553 Relaying disallowed as @ - undefined
```

Related System Console server log:

```
{"level":"error","ts":1574850126.0702078,"caller":"mlog/log.go:174","msg":"Connection unsuccessful: SendMail: Failed to close connection to SMTP server, 553 Relaying disallowed as @","path":"/ibmi.chat/api/v4/email/test","request_id":"gpjj8gg9tj8oznrnpnqwizanoo","ip_addr":"176.95.130.239","user_id":"18gqt73dd385xdxrexgtcdzkew","method":"POST","err_where":"testEmail","http_code":500,"err_details":""}
```

It appears as though the email credentials aren't being sent to the SMTP server.

**Comment by amyblais** [comment]
Hi @KerimG, would you be able to share your SMTP settings as well as your email settings from the config.json or System Console?

**Comment by KerimG** [comment]
Hey @amyblais 

yes, sure.

```json
        [...]
        "EnableSMTPAuth": true,
        "SMTPUsername": "email@ibmi.chat",
        "SMTPPassword": "mycoolpassword",
        "SMTPServer": "smtp.zoho.eu",
        "SMTPPort": "465",
        "ConnectionSecurity": "TLS",
        [...]
```

Is this enough? The System Console basically shows the same.

**Comment by D0d0** [comment]
Hey @KerimG,

I am aware that this is an old issue, but were you able to solve it?

**Comment by amyblais** [comment]
I'm cleaning up some older issues. If you need further assistance on this, I recommend reaching out to our devs / community via https://forum.mattermost.com/ or via our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help).
