### ISSUE TITLE
Extend ShouldProcessMessage to filter out from_webhook posts

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13259]
Extend [ShouldProcessMessage](https://github.com/mattermost/mattermost-server/blob/a63684fcb5e3ba7b7522b35c29a4cb27779ba823/plugin/helpers_bots.go#L120) to filter out any post with a `from_webhook` prop, unless a new `AllowWebhook` option is true.

Be sure to extend both the [TestProcessMessage](https://github.com/mattermost/mattermost-server/blob/a63684fcb5e3ba7b7522b35c29a4cb27779ba823/plugin/helpers_bots_test.go#L344) unit test to cover this new functionality.

This issue is a follow-up to the changes made for https://mattermost.atlassian.net/browse/MM-16709, and surfaced from the discussion at https://github.com/mattermost/mattermost-server/pull/12539#issuecomment-540782982.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-19508

**Comment by nadalfederer** [comment]
@lieut-data Hi, I would like to take this.

**Comment by lieut-data** [comment]
Terrific! Thanks, @nadalfederer :)
