### ISSUE TITLE
Incomplete security Audit system

### ISSUE THREAD

**Issue by giuliocomi** [mattermost/mattermost-server#13256]
The current Audit system is not logging many important security events.
Current architecture, its weaknesses and patches or proposals are all detailed for convenience in the attached document.
[enhanced_audit_system.pdf](https://github.com/mattermost/mattermost-server/files/3906421/enhanced_audit_system.pdf)

Thanks to @DSchalla for amazing support and review.

**Comment by jasonblais** [comment]
@DSchalla With #13258 closed and https://github.com/mattermost/mattermost-server/pull/13967 merged, should we close this issue? Do we have any follow up tickets?

**Comment by DSchalla** [comment]
I think that makes sense, thanks @jasonblais and as mentioned in the PR, appreciate your contribution @giuliocomi!

**Comment by giuliocomi** [comment]
> I think that makes sense, thanks @jasonblais and as mentioned in the PR, appreciate your contribution @giuliocomi!

My pleasure, thank you @DSchalla for the interesting discussions!
