### ISSUE TITLE
Support different interactive message button styles

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13260]
To improve [Slack compatibility](https://api.slack.com/docs/message-buttons), support a new `color` field to style interactive buttons. The value can be one of the following:

* an arbitrary six-character hexadecimal value representing the colour
* "default",
* "primary"
* "danger"
* any of the existing theme constants

Example theme:

```
{
  "sidebarBg": "#2b333d",
  "sidebarText": "#ffffff",
  "sidebarUnreadText": "#c5d0de",
  "sidebarTextHoverBg": "#24272d",
  "sidebarTextActiveBorder": "#2761d6",
  "sidebarTextActiveColor": "#c5d0de",
  "sidebarHeaderBg": "#333c47",
  "sidebarHeaderTextColor": "#c5d0de",
  "onlineIndicator": "#26a970",
  "awayIndicator": "#e0b333",
  "dndIndicator": "#ea0b0f",
  "mentionBj": "#24272d",
  "mentionColor": "#ffffff",
  "centerChannelBg": "#faf9f9",
  "centerChannelColor": "#3d3f44",
  "newMessageSeparator": "#ff8800",
  "linkColor": "#3084bb",
  "buttonBg": "#26a970",
  "buttonColor": "#ffffff",
  "errorTextColor": "#fd5960",
  "mentionHighlightBg": "#fff2bb",
  "mentionHighlightLink": "#3084bb",
  "codeTheme": "github",
  "mentionBg": "#24272d"
}
```

As part of this ticket, propose appropriate theme colours to use for "default”, “primary” and “danger” such that they work across themes. Look at various dialogs in the existing application for guidance.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-10160

**Comment by hanzei** [comment]
This also needs to be implemented for mobile, right?

**Comment by lieut-data** [comment]
Yes, good reminder, @hanzei!

**Comment by RyanCommits** [comment]
Looking into this

**Comment by lieut-data** [comment]
Thanks, @RyanCommits!

**Comment by lieut-data** [comment]
@RyanCommits, would you be open to helping make these same changes for the webapp? I realized that my reply to @hanzei's comment above might have suggested this was /mobile-only/, but it should apply to both frontend applications.

**Comment by RyanCommits** [comment]
> @RyanCommits, would you be open to helping make these same changes for the webapp? I realized that my reply to @hanzei's comment above might have suggested this was /mobile-only/, but it should apply to both frontend applications.

I can't make any promises right now... If anyone wants to split the work and take on the web app side of this ticket in the meantime, that would be ideal. 

I'll update this thread if I manage to find some spare time though.

**Comment by lieut-data** [comment]
Sounds good, @RyanCommits! I'll leave you assigned here, but add the `Up For Grabs` label back to give this issue attention. If someone is interested in helping with the webapp changes required here, feel free to jump in!
