### ISSUE TITLE
Extend QuickInput component with 'x' to clear text

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13262]
Extend the existing [QuickInput](https://github.com/mattermost/mattermost-webapp/blob/master/components/quick_input.jsx) with an optional 'x' that clears the input when clicked. See the plugin marketplace as an example:

![image](https://user-images.githubusercontent.com/1023171/69894568-b7e9db00-12f7-11ea-8c12-9f5d63fe24fb.png)

Once this component supports that functionality, remove the duplicate code in other components, such as that introduced in [https://github.com/mattermost/mattermost-webapp/pull/3955](https://github.com/mattermost/mattermost-webapp/pull/3955).

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-20068

**Comment by larkox** [comment]
May I take this one?
