### ISSUE TITLE
Allow edit of image in post

### ISSUE THREAD

**Issue by sirmspencer** [mattermost/mattermost-server#13261]
#### Summary
Allow editing or, at minimum, removal of an image from a post. 

#### Steps to reproduce
Post a message with an image attached.  Select edit.  There are no edit options for the attached image.

#### Expected behavior
Show an option to edit or remove the image from the post.

**Comment by amyblais** [comment]
I'm closing this for now as there hasn't been updates on this for a while, but I hope that you will open a feature request issue for this at https://mattermost.uservoice.com/forums/306457-general.

**Comment by ntraut** [comment]
It looks like this feature request:
https://mattermost.uservoice.com/forums/306457-general/suggestions/32349940-ability-to-modify-attached-files-when-editing-a-me
