### ISSUE TITLE
Allow calculating minimum server version for plugins in an automated fashion

### ISSUE THREAD

**Issue by harshilsharma2** [mattermost/mattermost-server#13265]
Currently, if someone uses a plugin API, they need to manually keep track of the highest Mattermost version used by any API, and set that as the minimum supported Mattermost version for a plugin.

This is not a very good way to do things when the last time you check for that was months ago and now you want to update minimum supported Mattermost version.

I propose creating a mechanism, perhaps CLI tool in go or npm, that allows to calculate this version automatically.

**Comment by amyblais** [comment]
I believe some work for this has been done for upcoming 5.18 release: 
 - https://mattermost.atlassian.net/browse/MM-17888
 - https://mattermost.atlassian.net/browse/MM-19265
 - https://mattermost.atlassian.net/browse/MM-19153
