### ISSUE TITLE
Trailing slash on marketplace URL results in spurious 404

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13271]
When a plugin marketplace URL is configured with a trailing slash (i.e. [https://api.integrations.mattermost.com/](https://api.integrations.mattermost.com/)), the plugin marketplace fails to load, reporting a 404.

Under the covers, the server tries to connect to [https://api.integrations.mattermost.com//api/v1/plugins](https://api.integrations.mattermost.com//api/v1/plugins) – notice the duplicate /. Our lambda function doesn't handle this path correctly, but ideally the server would normalize the URL first before joining the desired path.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-20620

**Comment by fm2munsh** [comment]
I'll grab this one

**Comment by lieut-data** [comment]
Thanks, @fm2munsh!
