### ISSUE TITLE
Port the "team rename" subcommand from Mattermost CLI to mmctl

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#13279]
This ticket includes the creation of a "team rename" subcommand in mmctl based on the Mattermost CLI command that can be found in `cmd/mattermost/commands/team.go`. 

To achieve this, the command can use the [Update a Team endpoint](https://api.mattermost.com/#tag/teams%2Fpaths%2F~1teams~1%7Bteam_id%7D%2Fput), and it should mimic the structure, arguments and behavior of the Mattermost CLI command.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-20824)

**Comment by M-ZubairAhmed** [comment]
can i work on this? i havent worked on cli before, will need a little help before i start

**Comment by mgdelacroix** [comment]
Sure @M-ZubairAhmed! Don't worry about the help, if you have any questions you find me in http://community.mattermost.com as `miguel.delacruz` :)
