### ISSUE TITLE
POST to /v4/posts/ephemeral results in 403

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#13274]
After running into #12702 - this time with [interactive message buttons](https://github.com/mattermost/mattermost-server/issues/12702#issuecomment-560158936) , I decided to apply a workaround: creating the ephemeral posts by myself, therefore not triggering the slack compatibility layer.

The docs say, it should be possible to create ephemeral posts by myself.
https://api.mattermost.com/#tag/posts%2Fpaths%2F~1posts~1ephemeral%2Fpost

Well... Its not.

#### Summary
calling POST /v4/posts/ephemeral as a sysadmin gives me 403

##### Step1: login (removed unnecessary info)
``someone@mattermost ~ % curl -i -d '{"login_id":"someone","password":"..."}' http://localhost:8065/api/v4/users/login``
```
{
  ...
  'username': 'someone',
  'roles': 'system_user system_admin',
  ...
}
```

##### Step2: POST to /v4/posts/ephemeral
``someone@mattermost ~ % curl -d '{ "user_id": "$my_ID", "post":{ "channel_id": "$some_public_debug_channel_id", "message": "asdf" }}' -H 'Content-Type: application/json' -H 'Authorization: Bearer ...' http://localhost:8065/api/v4/posts/ephemeral | json_pp``

##### Step3: Get a 403 :(
```
{
   "message" : "You do not have the appropriate permissions",
   "id" : "api.context.permissions.app_error",
   "status_code" : 403,
   "request_id" : "...",
   "detailed_error" : ""
}
```

#### Expected behavior
getting my ephemeral post sent to myself.

#### Observed behavior (that appears unintentional) 
The 403 error.

**Comment by lieut-data** [comment]
Thanks for the report, @somenet — can you check if your system administrator is part of the channel? By default, we still apply some membership checks, even for super users, although it might not be warranted in this case.

**Comment by somenet** [comment]
I am a member of the channel, but i am not a Team Admin or Channel Admin there and obviously cannot change that by clicking only.

**Comment by shubb30** [comment]
I don't know if it is the same issue, but I am getting the same 403 error when I try to just post a message via the API.

I was trying to follow the directions from https://docs.mattermost.com/developer/bot-accounts.html, and I got the same 403 error.

I then tried logging into the API as my user (which is a system-admin), and I get the same response.

Both my user and the bot account are members of the channel.

```
$ curl -i -X POST -H 'Content-Type: application/json' -d '{"channel_id":"my-channel", "message":"This is a message from a bot", "props":{"attachments": [{"pretext": "Look some text","text": "This is text"}]}}' -H 'Authorization: Bearer <token>' https://mmv.my-company.com/api/v4/posts


HTTP/1.1 403 Forbidden
Server: nginx/1.15.6
Date: Thu, 12 Mar 2020 22:47:18 GMT
Content-Type: application/json
Content-Length: 178
Vary: Accept-Encoding
X-Request-Id: yr9b...19cqa
X-Version-Id: 5.14.0.5.14.0.4c5774b880462a829b2bf264df5aa6cc.false
Strict-Transport-Security: max-age=15724800; includeSubDomains

{"id":"api.context.permissions.app_error","message":"You do not have the appropriate permissions","detailed_error":"","request_id":"yr9b...19cqa","status_code":403}
```

**Comment by lieut-data** [comment]
Apologies for the loooong delay in replying here, @someone-somenet-org. I tried to reproduce locally:
```
> http :8065/api/v4/users/me | jq '.roles'
"system_admin system_user"

> http POST :8065/api/v4/posts/ephemeral user_id=ndk45jfiy7rdpcwi87h6wwnwke post:='{"channel_id":"g8b8cm8xsin8zy1qkegu4hmdfw", "message":"test"}'
HTTP/1.1 201 Created
Content-Length: 364
Content-Type: application/json
Date: Fri, 24 Apr 2020 12:23:37 GMT
Vary: Accept-Encoding
X-Request-Id: 66nmz6g9tfrqjd8r7jrfx3nihe
X-Version-Id: 5.24.0.dev.5f98343aaa48b6694bb5812c77b3f278.false

{
    "channel_id": "g8b8cm8xsin8zy1qkegu4hmdfw",
    "create_at": 1587731017776,
    "delete_at": 0,
    "edit_at": 0,
    "hashtags": "",
    "id": "pzg66q9zmib9tkgsyctzxpy6cy",
    "is_pinned": false,
    "message": "test",
    "metadata": {},
    "original_id": "",
    "parent_id": "",
    "pending_post_id": "",
    "props": {},
    "reply_count": 0,
    "root_id": "",
    "type": "system_ephemeral",
    "update_at": 0,
    "user_id": "ndk45jfiy7rdpcwi87h6wwnwke"
}
```

and successfully got an ephemeral post sent my way:
![image](https://user-images.githubusercontent.com/1023171/80212145-59f2c280-860d-11ea-9c04-df6c68eefb9e.png)

I repeated this successfully in public channels, private channels, and DMs. I was also able to send ephemeral messages to users other than myself (who were not system administrators).

I'm wondering if my server configuration is different than yours. By chance, are you still able to reproduce this problem, and can you share your sanitized `config.json`?

**Comment by someone-somenet-org** [comment]
Nope, doesnt work for me.

``curl -i -d '{ "user_id": "$MY_USER_ID", "post":{ "channel_id": "$public_channel_i_am_in_id", "message": "asdf" }}' -H 'Content-Type: application/json' -H 'Authorization: Bearer $MY_TOKEN' http://localhost:8065/api/v4/posts/ephemeral``

```
HTTP/1.1 403 Forbidden
Content-Type: application/json
Vary: Accept-Encoding
X-Request-Id: b4he9y5oz3rr7r6eh6zpsaks3h
X-Version-Id: 5.22.0.5.22.0.fb947e471693191d722b7c1d15ab9ea5.true
Date: Sun, 26 Apr 2020 14:52:38 GMT
Content-Length: 179

{"id":"api.context.permissions.app_error","message":"You do not have the appropriate permissions.","detailed_error":"","request_id":"b4he9y5oz3rr7r6eh6zpsaks3h","status_code":403}
```

How do I submit the config non-publically?

**Comment by lieut-data** [comment]
@someone-somenet-org, I've looked at the code again and can't see anything in the configuration that would matter in this case. If you take a look at your `Permissions` table in the database for the `system_admin` role, can you confirm that it has `create_post_ephemeral` among the many permissions?

**Comment by someone-somenet-org** [comment]
`select permissions from roles where name='system_admin'`
`` manage_team_roles revoke_user_access_token manage_private_channel_properties assign_system_admin_role read_public_channel create_emojis delete_public_channel create_bot read_others_bots read_bots remove_others_reactions manage_incoming_webhooks remove_user_from_team manage_system_wide_oauth create_private_channel manage_others_outgoing_webhooks delete_emojis delete_others_emojis create_team list_team_channels add_user_to_team edit_others_posts manage_public_channel_properties invite_guest invite_user manage_jobs remove_reaction upload_file use_channel_mentions use_slash_commands get_public_link list_private_teams edit_other_users manage_team create_user_access_token promote_guest manage_channel_roles list_users_without_team view_members manage_oauth manage_slash_commands manage_bots manage_system demote_to_guest delete_private_channel import_team read_channel read_user_access_token create_public_channel create_post manage_private_channel_members join_public_channels delete_post manage_outgoing_webhooks view_team manage_roles manage_others_slash_commands edit_post manage_others_bots create_post_public add_reaction delete_others_posts manage_others_incoming_webhooks manage_public_channel_members join_private_teams``

**Comment by someone-somenet-org** [comment]
I cross-checked against another MM-instance, which was setup with mm 5.19.
`create_post_ephemeral` Is the only permission that is missing...

**Comment by someone-somenet-org** [comment]
Adding `create_post_ephemeral` to the corresponding field fixes it and it seems its not deleted again, when I edit and store the permissions via https://.../admin_console/user_management/permissions/system_scheme

So I guess its some old migration issue or something like that.

**Comment by naggie** [comment]
I just had the same issue on my mattermost 7.2 server, migrated many times since 2016.

@someone-somenet-org -- thank you for pushing me in the right direction. I've found a command that fixes this, should anyone else have this problem:

```
sudo -u mattermost  mmctl --local permissions add system_admin create_post_ephemeral
```
