### ISSUE TITLE
Port the "user activate" subcommand from Mattermost CLI to mmctl

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#13278]
This ticket includes the creation of a "user activate" subcommand in mmctl based on the Mattermost CLI command that can be found in `cmd/mattermost/commands/user.go`.

To achieve this, the command can use the [Update User Active status](https://api.mattermost.com/#tag/users%2Fpaths%2F~1users~1%7Buser_id%7D~1active%2Fput) endpoint, and it should mimic the structure, arguments and behavior of the Mattermost CLI command.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-20826)

**Comment by larkox** [comment]
May I take this one?

**Comment by mgdelacroix** [comment]
Sure @larkox, thanks!! :confetti_ball:
