### ISSUE TITLE
Parallelize plugin loading on startup

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13319]
Sever startup time is slow with 10+ plugins, since we bootstrap then serially. Investigate doing so in parallel to improve server startup speed.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-20941

**Comment by RajatVaryani** [comment]
@lieut-data I am happy to contribute.

**Comment by lieut-data** [comment]
Thanks, @RajatVaryani! No special tools: if you enable all prepackaged plugins, for example (configure bogus settings as needed just to get them to start up), and then restart the server, you'll see a long delay while everything is unpacked.

It would be great to start by logging some trace messages here that records the total startup time.

**Comment by lieut-data** [comment]
Hi @RajatVaryani! Are you still interested in this ticket?

**Comment by RajatVaryani** [comment]
> Hi @RajatVaryani! Are you still interested in this ticket?

Hello @lieut-data. Yes, I am interested working on this.  I could not work due to holidays. I will start the work pretty soon.
