### ISSUE TITLE
Setting `Require Email Verification` should be independent from setting `Enable Email Notifications`

### ISSUE THREAD

**Issue by GauthierPLM** [mattermost/mattermost-server#13312]
#### Summary
Setting `Require Email Verification:` should be independent from setting `Enable Email Notifications:` so it can be enabled even if `Enable Email Notifications` are disabled when an SMTP server is configured.

#### Steps to reproduce

- Setup a Mattermost 5.17 instance.
- Configure SMTP settings and make sure they are working
- Disable `Enable Email Notifications:`

#### Expected behavior
`Enable Email Notifications` and `Require Email Verification` settings should not be linked as long as a SMTP server is configured. 

`Require Email Verification` setting should have effect even if `Enable Email Notifications` is disabled.

#### Observed behavior (that appears unintentional) 
As stated by `Enable Email Notification` ("When false, email invitations and user account setting change emails are still sent as long as the SMTP server is configured."), emails such as invitations, address verification or email change are still sent even when `Enable Email Notifications` is disabled.

When `Enable Email Notifications` is disabled, `Require Email Verification` is also disabled and set to false in settings but emails are still sent.

#### Use case

I have a Mattermost instance in my company. Our employees wish to not receive email notifications as long as their mobile phone is connected to Mattermost (which is the case for all employees) and we took the decision to disable notifications for now.

However, we want to keep sending all other system emails (email verification, etc...). Right now, the interface is confusing and might lead user to believe no emails are sent. Also, I should be able to set `Require Email Verification` from notifications. Right now, with `Enable Email Notifications` disabled but SMTP configured, there is no way to disable `Require Email Verification`.

Ideally, it would be possible to change which email address sends these systems emails. I guess that currently, Notifications settings are used but this is not clear.

This seems related to #13038

**Comment by amyblais** [comment]
@GauthierPLM Can you confirm if you're still getting email notifications when ``Enable Email Notifications`` is disabled? We have an existing ticket for that here to fix it: https://mattermost.atlassian.net/browse/MM-20260.

**Comment by GauthierPLM** [comment]
@amyblais when `Enable Email Notifications`, I still receive systems emails (such as confirmation emails) but not emails notifications for new messages (intended behaviour).

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-20956.

**Comment by amyblais** [comment]
@GauthierPLM The team determined that this would be a feature request and that it is not currently possible to send email verification if other email notifications are disabled.

**Comment by GauthierPLM** [comment]
@amyblais I can assure you that it's possible to send email verification even when other email notification are disabled.

In my instance, I configured the SMTP server and **disabled** `Enable Email Notifications`. My users continue to receive emails for invitation or email verification, as well as password reset. This works as long as SMTP server is configured. It is even stated in the `Enable Email Notification`: 

> `Enable Email Notification`: ("When false, email invitations and user account setting change emails are still sent as long as the SMTP server is configured."), emails such as invitations, address verification or email change are still sent even when Enable Email Notifications is disabled.

I confirmed that with at least 5 of my users on version 5.17.0.

[It's also stated in Mattermost documentation.](https://docs.mattermost.com/administration/config-settings.html#enable-email-notifications)

**Comment by amyblais** [comment]
@GauthierPLM Is the issue you're seeing that even though Require Email Verification setting is **disabled** in System Console / config.json, you're **still getting email verification emails** since SMTP is configured (and Enable Email Notifications is disabled)?

Email invitations are different from email verifications, so I just wanted to make sure.

**Comment by GauthierPLM** [comment]
I want **to continue to receive email verification** (as it is now) and I want that the setting `Require Email Verification` match this.

Right now, `Require Email Verification` is marked as disabled as soon as `Enable Email Notifications` is disabled and thus do not match the real behaviour. `Require Email Verification` should match what Mattermost do independently of `Enable Email Notifications`.

My initial message explains exactly the situation and how things should be:

- When SMTP is configured, `Enable Email Notifications` should NOT disable `Require Email Verification`.
- `Require Email Verification` should match the real behaviour of Mattermost.
- As long as an SMTP is configured, `Require Email Verification` should control the sending of verification emails.

I don't understand why it would make sense to have `Enable Email Notifications` controlling  `Require Email Verification` as it is now. Email verification is not a notification and both settings should not be related. They are not even in the same section in system console...

**Comment by amyblais** [comment]
I asked our PM lead about this and it was confirmed that this would be an improvement instead of a bug.

However, we will open an improvement Jira ticket to plan how we could change the existing behaviour and to think about how these settings should be changed. One of our PMs responsible for this area will open the ticket. He is off this week, so I will follow up next week on the link to the Jira ticket once it's created.

**Comment by amyblais** [comment]
A ticket for this was opened here https://mattermost.atlassian.net/browse/MM-21373 and it is awaiting peer review.

We did recreate it as a bug ticket because the Require Email Verification toggle is misrepresenting what is happening on the back-end (the verification email is still being sent when set to false).

**Comment by thefactremains** [comment]
update: we separated this into 2 issues. 
An [improvement](https://mattermost.atlassian.net/browse/MM-21682) (to remove the link between the two settings) 
and a [bug](https://mattermost.atlassian.net/browse/MM-21373) (since the email is being sent when the setting dictates that it should not)

**Comment by amyblais** [comment]
This is fixed for upcoming v5.22 release, scheduled for April 16th,
