### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Long lists of selections are scrollable "

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13338]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Long lists of selections are scrollable 

**Steps:**
1. Locate a message attachment menu (like users) that would have many selections
2. Click in / Tap on the message attachment menu box
3. Scroll up and down the list of selections
        
**Expected:**
- The list of selections is scrollable

**Test Key:** IM21035

**Test Folder:** `/cypress/integration/interactive_menu`
**Test code arrangement:**
```
describe('Interactive Menu', () => {
    it('IM21035 - Long lists of selections are scrollable ', () => {
        // code
    });
});
```

**Note:**
- see [interactive_menu/basic_options_spec.js](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js) for related test
- refer to [docs for more info about Interactive Messages: Buttons and Menus](https://docs.mattermost.com/developer/interactive-messages.html)

**Jira ticket**: [MM-21035](https://mattermost.atlassian.net/browse/MM-21035)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by M-ZubairAhmed** [comment]
I will take this one

**Comment by saturninoabril** [comment]
@M-ZubairAhmed Thank you and happy holidays!

**Comment by M-ZubairAhmed** [comment]
happy holidays @saturninoabril :santa: :mrs_claus:
