### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Clicking in / Tapping on the message attachment menu box opens list of selections"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13337]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Clicking in / Tapping on the message attachment menu box opens list of selections

**Steps:**
1. Locate a message attachment menu
2. Click in / Tap on the message attachment menu box
        
**Expected:**
- The list of selections opens

**Test Key:** IM21037

**Test Folder:** `/cypress/integration/interactive_menu`
**Test code arrangement:**
```
describe('Interactive Menu', () => {
    it('IM21037 - Clicking in / Tapping on the message attachment menu box opens list of selections', () => {
        // code
    });
});
```

**Note:**
- see [interactive_menu/basic_options_spec.js](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js) for related test
- refer to [docs for more info about Interactive Messages: Buttons and Menus](https://docs.mattermost.com/developer/interactive-messages.html)

**Jira ticket**: [MM-21037](https://mattermost.atlassian.net/browse/MM-21037)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by M-ZubairAhmed** [comment]
Can i grab this one

**Comment by saturninoabril** [comment]
@M-ZubairAhmed Awesome, thanks!
