### ISSUE TITLE
Write an automated test using Cypress for "Selecting a Number with the up/down arrows within the "Number Selector" field"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13336]
**Test Key:** ID21033

**Test Folder:** `/cypress/integration/interactive_dialog`

**Title:** Selecting a Number with the up/down arrows within the "Number Selector" field
    
**Steps:**
1. In a message input box (center channel or RHS), type "/dialog" and hit "Enter"
2. Click/tap on the "Number" field
3. Click/tap on the up/down arrows that appear on the right

On RN app: Number keyboard should show up to enter input.
        
**Expected:**
After 1) Interactive dialog modal opens and ephemeral post confirming you used the slash command to open the dialog is made
After 2) you should see the up/down arrows appear on the right
After 3) you should see the number increase when clicking/tapping the up arrow and decreasing when clicking/tapping on the down arrow

**Test code arrangement:**
```
describe('Interactive Dialog', () => {
    it('ID21033 - Selecting a Number with the up/down arrows within the "Number Selector" field', () => {
        // code
    });
});
```

**Note:**
- see tests at `cypress/integration/interactive_dialog` folder for reference
- refer to [docs for more info about Interactive Dialogs](https://docs.mattermost.com/developer/interactive-dialogs.html)

**Jira ticket**: [MM-21033](https://mattermost.atlassian.net/browse/MM-21033)

See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by rodel-calasagsag** [comment]
hi @saturninoabril I would like to take this one

**Comment by saturninoabril** [comment]
Awesome, thanks!

**Comment by hanzei** [comment]
@rodel-calasagsag Just wanted to check if you are still working on this issue and if you have any questions.

**Comment by jfrerich** [comment]
This issue appears stale and I’m adding the `Up For Grabs` label.  If work is ongoing, please remove the label.  If there is an existing PR, please also link it to the issue.  Thanks!

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
