### ISSUE TITLE
Write an automated test using Cypress for "Individual "User" and "Channel" screens are scrollable"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13333]
**Test Key:** ID21031

**Test Folder:** `/cypress/integration/interactive_dialog`

**Title:** Individual "User" and "Channel" screens are scrollable
    
**Steps:**
1. In a message input box (center channel or RHS), type "/dialog" and hit "Enter"
2. Click/tap in the "User Selector" field and scroll within the list
3. Click/tap in the "Channel Selector" field and scroll within the list
        
**Expected:**
After 1) Interactive dialog modal opens and ephemeral post confirming you used the slash command to open the dialog is made
After 2) and 3) you should be able to scroll up and down within the lists using either the up/down arrows or the mouse

**Test code arrangement:**
```
describe('Interactive Dialog', () => {
    it('ID21031 - Individual "User" and "Channel" screens are scrollable', () => {
        // code
    });
});
```

**Note:**
- see tests at `cypress/integration/interactive_dialog` folder for reference
- refer to [docs for more info about Interactive Dialogs](https://docs.mattermost.com/developer/interactive-dialogs.html)

**Jira ticket**: [MM-21031](https://mattermost.atlassian.net/browse/MM-21031)
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?
