### ISSUE TITLE
Write an automated test using Cypress for "Password element check"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13335]
**Test Key:** ID21032

**Test Folder:** `/cypress/integration/interactive_dialog`

**Title:** Password element check
    
**Steps:**
1.  Create an incoming webhook where it sends dialog with password
        
**Expected:**
1. Dialog should render correctly,
- verify that the password is masked on enter of text

**Test code arrangement:**
```
describe('Interactive Dialog', () => {
    it('ID21032 - Password element check', () => {
        // code
    });
});
```

**Note:**
- see tests at `cypress/integration/interactive_dialog` folder for reference
- refer to [docs for more info about Interactive Dialogs](https://docs.mattermost.com/developer/interactive-dialogs.html)

**Jira ticket**: [MM-21032](https://mattermost.atlassian.net/browse/MM-21032)
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by swarnv02** [comment]
I am interested in this ticket, please assign

**Comment by saturninoabril** [comment]
Awesome, thanks @swarnv02!

**Comment by VishalSwarnkar** [comment]
@saturninoabril Sorry for the confusion, by mistake I have requested you from my official account, do you mind unassigning swarnv02 and assign to vishalswarnkar. Both of them are my account it is just that swarnv02 is an official account and vishalswarnkar is personal.

**Comment by saturninoabril** [comment]
No worries, and thanks @VishalSwarnkar!

**Comment by VishalSwarnkar** [comment]
Ready for review : https://github.com/mattermost/mattermost-webapp/pull/5397

**Comment by saturninoabril** [comment]
Thank you @VishalSwarnkar for your contribution! Closing this now.
