### ISSUE TITLE
Write an automated test using Cypress for "Boolean element check"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13334]
**Test Key:** ID21034

**Test Folder:** `/cypress/integration/interactive_dialog`

**Title:** Boolean element check
    
**Steps:**
1.  Create an incoming webhook where it sends dialog with boolean element
        
**Expected:**
1. Dialog should render correctly,
- verify that the boolean element renders correctly

**Test code arrangement:**
```
describe('Interactive Dialog', () => {
    it('ID21034 - Boolean element check', () => {
        // code
    });
});
```

**Note:**
- see tests at `cypress/integration/interactive_dialog` folder for reference
- refer to [docs for more info about Interactive Dialogs](https://docs.mattermost.com/developer/interactive-dialogs.html)

**Jira ticket**: [MM-21034](https://mattermost.atlassian.net/browse/MM-21034)
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by larkox** [comment]
May I take this one?

**Comment by jasonblais** [comment]
Certainly, thanks @larkox! Wow, you're working on a lot :)

**Comment by saturninoabril** [comment]
PR merged.  Closing.
