### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Change selection in RHS / Message Thread"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13341]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Change selection in RHS / Message Thread

**Steps:**
Continuing from 5) in the above test
1. In the RHS / message thread, click in / tap on the message attachment menu box (or click on the dropdown arrow to the right of the message attachment menu box) 
2. Select a different option to the one you selected in the center panel
        
**Expected:**
After 2) the selection in the center panel changes to show the selection you made in the RHS and an ephemeral message is posted advising the selection you made

**Test Key:** IM21044

**Test Folder:** `/cypress/integration/interactive_menu`
**Test code arrangement:**
```
describe('Interactive Menu', () => {
    it('IM21044 - Change selection in RHS / Message Thread', () => {
        // code
    });
});
```

**Note:**
- see [interactive_menu/basic_options_spec.js](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js) for related test
- refer to [docs for more info about Interactive Messages: Buttons and Menus](https://docs.mattermost.com/developer/interactive-messages.html)

**Jira ticket**: [MM-21044](https://mattermost.atlassian.net/browse/MM-21044)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by M-ZubairAhmed** [comment]
I got this
