### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Using up/down arrow keys to make selection"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13342]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Using up/down arrow keys to make selection

**Steps:**
1. Locate a message attachment menu
2. Click in the message attachment menu box (or click on the dropdown arrow to the right of the message attachment menu box)
3. Hit the down arrow a few times
4. Hit the up arrow a couple of times
        
**Expected:**
- Using the down arrow should move the highlight down the list of selections 
- Using the up arrow should move the highlight up the list of selections

**Test Key:** IM21043

**Test Folder:** `/cypress/integration/interactive_menu`
**Test code arrangement:**
```
describe('Interactive Menu', () => {
    it('IM21043 - Using up/down arrow keys to make selection', () => {
        // code
    });
});
```

**Note:**
- see [interactive_menu/basic_options_spec.js](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js) for related test
- refer to [docs for more info about Interactive Messages: Buttons and Menus](https://docs.mattermost.com/developer/interactive-messages.html)

**Jira ticket**: [MM-21043](https://mattermost.atlassian.net/browse/MM-21043)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by lurcio** [comment]
Hi! I'll take a look at this one.
