### ISSUE TITLE
Write an automated test using Cypress for "Selected options with long usernames are not cut off in the RHS"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13345]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Selected options with long usernames are not cut off in the RHS

**Steps:**
1. On a message attachment menu that provides for username selection, click on dropdown to the right of the menu
2. Select an option of a username that is quite long
3. Click on reply to the right of the original integration message posted
        
**Expected:**
- Option is displayed in the text box
- Ephemeral message posts (only visible to you) showing the selection you have made
- RHS opens
- Username selected displays properly (truncated) and is not just cut off

**Test Key:** IM21038

**Test Folder:** `/cypress/integration/interactive_menu`
**Test code arrangement:**
```
describe('Interactive Menu', () => {
    it('IM21038 - Selected options with long usernames are not cut off in the RHS', () => {
        // code
    });
});
```

**Note:**
- see [interactive_menu/basic_options_spec.js](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js) for related test
- refer to [docs for more info about Interactive Messages: Buttons and Menus](https://docs.mattermost.com/developer/interactive-messages.html)

**Jira ticket**: [MM-21038](https://mattermost.atlassian.net/browse/MM-21038)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by M-ZubairAhmed** [comment]
Question : After creating a new user with very long username, how do i make webhook request for users, 

following this from docs _**https://docs.mattermost.com/developer/interactive-messages.html#message-menus-for-users**_

**Comment by jasonblais** [comment]
@M-ZubairAhmed Are you familiar with [Postman](https://www.getpostman.com/) or another tool to make web requests? 

As long as you send a JSON included in the linked doc, you'll be able to test the UI functionality.

Let me know if the above helps, happy to share more concrete steps if you're less familiar with this area. :)

**Comment by M-ZubairAhmed** [comment]
thank you @jasonblais , let me try that

**Comment by M-ZubairAhmed** [comment]
Hi, Sorry for disturbing holidays, i have another questions 

For testing purpose, Instead of creating a user with very long username and then getting list of user name inside the attachment. Can i just create a small list of options like this :
```js
const options = [
    {text: 'Option 1', value: 'option1'},
    {text: 'Looooooooooooooooooooooooooooooooooooooooooooong', value: 'option2'},
    {text: 'Option 3', value: 'option3'},
];
```

**Comment by saturninoabril** [comment]
Thanks @M-ZubairAhmed! In Cypress, you may have it as:

```javascript
const userOptions = getMessageMenusPayload({dataSource: 'users'});
cy.postIncomingWebhook({url: incomingWebhook.url, data: userOptions})
```

**Comment by M-ZubairAhmed** [comment]
![Screenshot from 2019-12-24 17-06-40](https://user-images.githubusercontent.com/17708702/71411586-d8c8f600-2641-11ea-9fab-edb2cc3f4d6d.png)

As per API specifications, longest username can be of lenght 22, which i created in the above screen shot. But as per the ticket username should be truncated which i dont see the screen shot above. Is this how it should be ?

**Comment by jasonblais** [comment]
cc @saturninoabril on above after the holidays :)

**Comment by saturninoabril** [comment]
Oh thanks for clarifying. It's the inconsistency between the webapp (22 limit - old implementation) and the server ([64 limit](https://github.com/mattermost/mattermost-server/blob/master/model/user.go#L55) - with APIv4 intro).  I'll bring it up on our next dev meeting as I couldn't remember if we talked about it before.
For Cypress testing, you may create long username directly via API by using  `cy.createNewUser`.  One good example is at  https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/channel/channel_name_tooltips_spec.js#L105-L112.

**Comment by M-ZubairAhmed** [comment]
thank you @saturninoabril . I will wait for further instructions
Yes i have been created long user name with that command itself, here is the WIP PR
https://github.com/mattermost/mattermost-webapp/pull/4594/files
