### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Searching within the list of options"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13340]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Searching within the list of options

**Steps:**
1. Locate a message attachment menu
2. Click in / Tap on the message attachment menu box (or click on the dropdown arrow to the right of the message attachment menu box)
3. Start typing the first few letters of a username, channel or option 
        
**Expected:**
- The list of options displays only those that match what you have typed

**Test Key:** IM21039

**Test Folder:** `/cypress/integration/interactive_menu`
**Test code arrangement:**
```
describe('Interactive Menu', () => {
    it('IM21039 - Searching within the list of options', () => {
        // code
    });
});
```

**Note:**
- see [interactive_menu/basic_options_spec.js](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js) for related test
- refer to [docs for more info about Interactive Messages: Buttons and Menus](https://docs.mattermost.com/developer/interactive-messages.html)

**Jira ticket**: [MM-21039](https://mattermost.atlassian.net/browse/MM-21039)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by lurcio** [comment]
Hi, I’ll take a look at this one!

**Comment by saturninoabril** [comment]
@lurcio Awesome, thanks!
