### ISSUE TITLE
Write an automated test using Cypress for "Using up/down keys to make a selection from SEARCH results"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13346]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Using up/down keys to make a selection from SEARCH results

**Steps:**
1. Locate a message attachment menu
2. Click in the message attachment menu box (or click on the dropdown arrow to the right of the message attachment menu box)
3. Start typing the first few letters of a username, channel or option 
4. Use your up/down keys to navigate within this list of search results
        
**Expected:**
- Using the down arrow should move the highlight down the list of selections 
- Using the up arrow should move the highlight up the list of selections

**Test Key:** IM21041

**Test Folder:** `/cypress/integration/interactive_menu`
**Test code arrangement:**
```
describe('Interactive Menu', () => {
    it('IM21041 - Using up/down keys to make a selection from SEARCH results', () => {
        // code
    });
});
```

**Note:**
- see [interactive_menu/basic_options_spec.js](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js) for related test
- refer to [docs for more info about Interactive Messages: Buttons and Menus](https://docs.mattermost.com/developer/interactive-messages.html)

**Jira ticket**: [MM-21041](https://mattermost.atlassian.net/browse/MM-21041)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by mjthomp95** [comment]
I can work on this.

**Comment by saturninoabril** [comment]
@mjthomp95 Awesome, thanks!

**Comment by jasonblais** [comment]
Hey @mjthomp95, let us know if you have any questions so far, we'd be happy to help. Thanks so much for your interest on this :)

**Comment by mjthomp95** [comment]
Yes sorry been a busy holiday season. I'll be reaching out on the developer channel soon.

**Comment by jasonblais** [comment]
Thanks @mjthomp95! Sounds good, appreciate the follow-up. Happy holidays!

**Comment by mjthomp95** [comment]
Sorry. I just came seem to get it done. I won't be able to finish this up. :disappointed:

**Comment by jasonblais** [comment]
Hey @mjthomp95, thanks for the heads up! No worries, I'll open it up for grabs.

Hope to see you around when you have more time! Really appreciate your >10 contributors last year, it's really helped the team 🎉

**Comment by larkox** [comment]
May I take this one?

**Comment by saturninoabril** [comment]
Sure, thanks @larkox!
