### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Enter selects the option"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13344]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Enter selects the option

**Steps:**
1. Locate a message attachment menu 
2. Click in the message attachment menu box (or click on the dropdown arrow to the right of the message attachment menu box) 
3. Start typing the first few letters of a username, channel or option
4. Once you have a match for what you're searching for, hit "enter"
        
**Expected:**
- The selection you made is inserted in the menu box and an ephemeral message is posted advising the selection you made

**Test Key:** IM21036

**Test Folder:** `/cypress/integration/interactive_menu`
**Test code arrangement:**
```
describe('Interactive Menu', () => {
    it('IM21036 - Enter selects the option', () => {
        // code
    });
});
```

**Note:**
- see [interactive_menu/basic_options_spec.js](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js) for related test
- refer to [docs for more info about Interactive Messages: Buttons and Menus](https://docs.mattermost.com/developer/interactive-messages.html)

**Jira ticket**: [MM-21036](https://mattermost.atlassian.net/browse/MM-21036)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by M-ZubairAhmed** [comment]
I am working on this

**Comment by saturninoabril** [comment]
@M-ZubairAhmed Awesome, thanks!
