### ISSUE TITLE
UI Automation: Write an automated test using Cypress for "Selection is mirrored in RHS / Message Thread"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#13343]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Selection is mirrored in RHS / Message Thread

**Steps:**
1. Locate a message attachment menu 
2. Click in / Tap on the message attachment menu box (or click on the dropdown arrow to the right of the message attachment menu box) 
3. Start typing the first few letters of a username, channel or option
4. Once you have a match for what you're searching for, hit "enter"
5. Click the "reply" arrow to the right of the message
        
**Expected:**
After 4) 
- The selection you made is inserted in the menu box and an ephemeral message is posted advising the selection you made
After 5) The RHS / message thread opens showing the same selection you made in the center panel

**Test Key:** IM21040

**Test Folder:** `/cypress/integration/interactive_menu`
**Test code arrangement:**
```
describe('Interactive Menu', () => {
    it('IM21040 - Selection is mirrored in RHS / Message Thread', () => {
        // code
    });
});
```

**Note:**
- see [interactive_menu/basic_options_spec.js](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js) for related test
- refer to [docs for more info about Interactive Messages: Buttons and Menus](https://docs.mattermost.com/developer/interactive-messages.html)

**Jira ticket**: [MM-21040](https://mattermost.atlassian.net/browse/MM-21040)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by M-ZubairAhmed** [comment]
Working on this one
