### ISSUE TITLE
Day picker in after/before search doesn't honor the user's timezone override.

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#13351]
### Summary
Day picker in after/before search doesn't honor the user's timezone override.

#### Steps to reproduce
1. Allow users to set their own timezones by enabling `Timezone` settings in the `Experimental` section in `System Console`.
1. Update your timezone to something that has a different date that what you have in your location right now. For example at the time of the creation of this issue, t was 8th December here in India and 7th December in Alaska. So I set my timezone to `US/Alaska`.
1. Refresh the webapp just to be safe.
1. In chat search bar type `after:` . A day picker will popup with the current day highlighted.
1. Notice that the highlighted day is today's day in your current location, not in the location of your set timezone.

#### Expected behavior
Day picker in after/before search should honor the user's timezone override.

#### Observed behavior (that appears unintentional) 
Day picker in after/before search doesn't honor the user's timezone override.

#### Possible fixes
Something related to this being discussed on react-day-picker GitHub repo - https://github.com/gpbl/react-day-picker/issues/130

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-21096.
