### ISSUE TITLE
Request for Documentation: Update mattermost-server README.md to replace pre-release links.

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-server#13376]
Mattermost user `jesse.hallam` from https://community.mattermost.com has requested the following be documented:

```
Thanks for pointing that out, @lenucksi -- pre-release.mattermost.com and community.mattermost.com are actually the same servers. But we should really update the README.md on mattermost-server this to point at the authoritative name.
```

See the original post [here](https://community.mattermost.com/_redirect/pl/9nzyqs3ewbrrjmyrhmrge4yjmo).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by lieut-data** [comment]
We should also look at clarifying the language, since we speak about pre-release in somewhat similar terms as the demo server.
