### ISSUE TITLE
Get userId of the user mentioned in slash command req.body

### ISSUE THREAD

**Issue by programmersstudio** [mattermost/mattermost-server#13411]
Hi Team,

I just have started using matter most previously I used slack.
I was planning to migrate my apps to matter most but I am facing one issue.

In slack when we run command - `/myapp hi @usernmae` gives us req.body.text as `hi <username|userID>`. I cannot find this functionality anywhere, Does matter most support this thing?

**Comment by amyblais** [comment]
Thank you for reporting this. I've asked our team about this to find out if this is a bug or a feature request.

**Comment by jasonblais** [comment]
Hey @programmersstudio,

We don't have an exact mapping of that format into Mattermost - and moreover, usernames are deprecated in Slack.

Let me know what your use case and we might be able to better assist you? Here are also a few helpful resources:
 - https://developers.mattermost.com/integrate/slash-commands/
 - https://grundleborg.github.io/posts/mattermost-custom-slash-command-aws-lambda/

**Comment by amyblais** [comment]
Closing this for now as we haven't received feedback for a while. Please re-open this issue if the problem persists,
