### ISSUE TITLE
There is a bug during switching channels that pins your view to some random location weeks before the latest post. 

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-server#13422]
#### Summary

From Hacker News: https://news.ycombinator.com/item?id=21822537
```
Used Mattermost for a year, and I can attest to it's shittiness. There is a bug during switching channels that pins your view to some random location weeks before the latest post. The result is that switching channel in Mattermost has a 60% chance of requiring you to spend the next 30 seconds scrolling the window to the bottommost-recent-message. Horrible.
```
// breaking template here a bit as this is from community

**Comment by jasonblais** [comment]
I replied with

```
Mattermost PM here, I agree that this is not a good experience, thank you for sharing @jetru.
There is development in progress to let you jump directly to new messages when you land on the oldest unread message in a channel. This lets you get directly to the latest message.

I'm not entirely sure if this is the same use case you have, but if you're open to testing the new development and share feedback, we'd love to hear!

Pull request with an open test server is available here: https://github.com/mattermost/mattermost-webapp/pull/4132#issuecomment-566993406
```

If this is the same issue, then https://github.com/mattermost/mattermost-webapp/pull/4132 should resolve it. PM/Dev/QA review in progress.

Related Jira tickets
https://mattermost.atlassian.net/browse/MM-19537
https://mattermost.atlassian.net/browse/MM-19533

**Comment by sid-kap** [comment]
@jasonblais I experience the same bug, and it is not going to the oldest unread message. This happens even in channels where I have seen all the messages, and it still often scrolls to some random message from weeks ago even if I've read all the messages in between.

**Comment by jasonblais** [comment]
@sid-kap Thanks for reaching out! Few questions to see if we can narrow down the cause:

1 - Which Mattermost server version do you have?
2 - Which browsers or Desktop App does it reproduce for you?
3 - How often do you notice this? (e.g. how many times a day)

**Comment by jasonblais** [comment]
@sid-kap I heard from one of your colleagues the answer to 1. But if you're open to sharing any more information for questions 2 and 3, that'll be helpful.

There are scrolling fixes and improvements coming in Mattermost v5.20, releasing on Feb 16th.

**Comment by sid-kap** [comment]
Thanks for following up on this! I only use the Mattermost Mac desktop app, and I notice it maybe 2-4 times a day.

**Comment by jasonblais** [comment]
Hi @sid-kap, thanks for letting us know. I've reached out to our Apps team to help take a look (cc @amyblais @sudheerDev)

**Comment by jasonblais** [comment]
@sid-kap In the meantime, I would encourage your System Admin to upgrade to the latest Mattermost release, v5.19, from https://mattermost.com/download. Please also ensure you have the latest Mattermost Mac desktop app from https://mattermost.com/download/#mattermostApps

**Comment by sudheerDev** [comment]
@sid-kap Hey, Does this happen on first visit to channel? i.e you see a loading indicator before seeing the posts in channel? Or does it happen on a recurring visit?

**Comment by sid-kap** [comment]
It happens on recurring visits, I don't see a loading indicator when I'm switching channels and this happens
