### ISSUE TITLE
Disabled AD user can still access Mattermost

### ISSUE THREAD

**Issue by levigo-systems** [mattermost/mattermost-server#13428]
#### Summary
If a user is disabled in the AD, it still can access Mattermost until the account is logged out.

#### Steps to reproduce
Mattermost-Version: 5.17.0
Database-Version: 5.17.0

1. Configure a LDAP connection to an AD
2. Login with an AD user
3. Disable the AD user via AD
4. Use Mattermost on the AD user -> Should still work
5. Check the systemconsole -> The user is still activated (ldap sync was already running)

#### Expected behavior
1. The user token should expire -> exclusion of the user
2. The user should be deactivated in Mattermost user backend

**Comment by amyblais** [comment]
@levigo-systems Wondering if this document may help: https://docs.mattermost.com/deployment/sso-ldap.html#how-does-deactivating-users-work.

If not, would you be open to sending more information from here: https://docs.mattermost.com/process/support.html#ldap-issues?
