### ISSUE TITLE
Autoresponder should not reply to bot DMs

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-server#13421]
#### Summary

When a user has the Autoresponder configured to respond to messages, it will respond to any DMs sent to the user. When a bot messages the user, the Autoresponder should not respond.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-20157

#### Steps to reproduce

Set user Out of Office with an auto-response message. See [here](https://mattermost.atlassian.net/browse/MM-20157) for details.

Have a bot send a DM to you. You can use [the documentation](https://docs.mattermost.com/developer/bot-accounts.html) to set up the Bot Account.

#### Expected behavior

The Autoresponder does not reply to the bot's message.

#### Observed behavior

The Autoresponder replies to the bot's message.

![image](https://user-images.githubusercontent.com/6913320/71055167-a9d2f180-2122-11ea-8c14-202ff164d93f.png)

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by nmlc** [comment]
Can I grab this one?

**Comment by mickmister** [comment]
@nmlc Yes, thanks for contributing!
