### ISSUE TITLE
Wrong field name and description for device_id in "PUT: /users/sessions/device"

### ISSUE THREAD

**Issue by Bamiiup** [mattermost/mattermost-server#13442]
Instead of 'device_id', there is should be token at least for android.

**Comment by amyblais** [comment]
Would you be open to sharing more details about your environment via https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by amyblais** [comment]
@Bamiiup Is there any additional information you'd be able to share?

**Comment by amyblais** [comment]
Closing this for now but I hope you will be able to share more details on this if the problem persists.
