### ISSUE TITLE
"onTouchEnd got false" console error

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-server#13452]
#### Summary
On console we can see an error related to "onTouchEnd" receiving a boolean instead of a function.

#### Steps to reproduce
Run mattermost server and go to /. Check the console there

#### Expected behavior
No console errors

#### Observed behavior (that appears unintentional) 
Error appearing

#### Possible fixes
Follow the instructions in the error message

**Comment by larkox** [comment]
I will take care of this.

**Comment by jasonblais** [comment]
Thanks @larkox :)
