### ISSUE TITLE
Incorrect last updated date on Mattermost integratiopns page

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#13454]
#### Summary
The last updated date on Standup Raven integrations page is either incorrect and I'm incorrectly guessing it's meaning.

#### Steps to reproduce
1. Visit https://integrations.mattermost.com/standup-raven/
1. Notice the `Date Last Updated` value.
1. Now compare it with release dates on https://github.com/standup-raven/standup-raven/releases .

#### Expected behavior
From what I understand, `Date Last Updated` for a plugin is the latest date when a release was published. If this is correct, then `Date Last Updated` should have been `December 7, 2019`.

#### Observed behavior (that appears unintentional) 
`Date Last Updated` is being displayed as `October 5, 2019`.

**Comment by jasonblais** [comment]
@amyblais or @aaronrothschild can help share the process for updating these dates when they're back from holidays. I believe we update the directory once every 2 months. We should ideally have a more automated way of pulling this information, or the creator sharing updates,

**Comment by harshilsharma63** [comment]
+1 for automated updated. You can pick date of latest released artifact that is not marked `pre-released`. Of course that applies only to GitHub (and maybe to GitLab?).

Or maybe remove the field all together from integrations page?

**Comment by amyblais** [comment]
This is fixed. I update the page every month except on December.

**Comment by jasonblais** [comment]
Thank you Amy! @harshilsharma63 okay to close?

**Comment by harshilsharma63** [comment]
@jasonblais surely! The updated date looks fine now.
