### ISSUE TITLE
Many UI automation tests are failing in interactive_menu/basic_options_spec.js

### ISSUE THREAD

**Issue by M-ZubairAhmed** [mattermost/mattermost-server#13520]
#### Summary
In UI automation test suite **integration/interactive_menu/basic_options_spec.js**, following tests are failing due to same element not found error.

#### Steps to reproduce
- Start the webhook
- Start cypress test
- Open `integration/interactive_menu/basic_options_spec.js` test

#### Expected behavior
Tests should not fail

#### Observed behavior (that appears unintentional) 
![Screenshot from 2019-12-24 14-22-01](https://user-images.githubusercontent.com/17708702/71404526-af50a000-262a-11ea-8d61-1aeb8b6a1a62.png)

All errors are same where they fail to find the message input field

#### Possible fixes
It should find the element by placeholder instead
`cy.findByPlaceholderText('Select an option...')`

If you can, link to the line of code that might be responsible for the problem
https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/interactive_menu/basic_options_spec.js#L107

**Comment by M-ZubairAhmed** [comment]
This is a legit issue as confirmed by @saturninoabril,
Just saying because this was not tagged :smile:

**Comment by saturninoabril** [comment]
Thanks @M-ZubairAhmed for fixing those!

**Comment by saturninoabril** [comment]
Thanks @M-ZubairAhmed for filing and fixing the tests!

**Comment by M-ZubairAhmed** [comment]
Always happy to help Saturnino
