### ISSUE TITLE
Enable to detect since when a user is offline (manual & disconected)

### ISSUE THREAD

**Issue by enzolutions** [mattermost/mattermost-server#13528]
#### Summary
Currently, using the UX, we cannot determine the last time a user when offline. this is a useful feature compared with flowdock.com, as you can see in the following image

![Screen Shot 2019-12-27 at 6 26 42 am](https://user-images.githubusercontent.com/907914/71488129-12347800-2873-11ea-8b03-867c8fc2b357.png)

#### Steps to reproduce
mattermost Server 5.16
Open a conversation 1-1 with any user, and if it is offline, we cannot determine since when that user is offline

#### Expected behavior
Open a conversation 1-1 with any user and if is offline.  Display as part of user status since when the user is offline.

#### Possible fixes

**Comment by enzolutions** [comment]
Feature Idea link: https://mattermost.uservoice.com/forums/306457-general/suggestions/39340675-enable-to-detect-since-when-a-user-is-offline-man

**Comment by amyblais** [comment]
Thank you!
