### ISSUE TITLE
Proposing changes to Channel rename command in mmctl to be uniform with team rename

### ISSUE THREAD

**Issue by M-ZubairAhmed** [mattermost/mattermost-server#13533]
#### Summary
@mgdelacroix and i had a discussion regarding how the rename command be for teams, He also expressed that we should follow the same for rename commands when possible for other places.

### Current situation in Channel rename command vs in Team rename cmd
https://github.com/mattermost/mmctl/blob/c5c3887d51392f65603c38c64bcd6f141a49b1e5/commands/channel.go#L347

#### Minimum args
Channel rename  -> `Required minimum of 2 args, one for old name and new name`
Team rename -> `Required minimum of 1 args, just for old name`

#### Structure of command
Channel rename  -> `channel rename myteam:mychannel newchannelname --display_name "New Display Name`
Team rename -> ` team rename old-team --name 'new-team' --display_name 'New Display Name`

#### Flags
Channel rename  -> `Mandatory require both name and display name`
`name is taken via arg and display name via flag`
Team rename -> `Atleast one name or display flag is required`
`Both new name and display name are via flags`

### Proposed changes
The updated rename channel could be 
```bash
  channel rename myteam:oldchannel --name 'new-channel' --display_name 'New Display Name'
  channel rename myteam:oldchannel --name 'new-channel'
  channel rename myteam:oldchannel --display_name 'New Display Name'
```

**Comment by jasonblais** [comment]
From #13462, sounded like you were open to submitting a PR for review?

**Comment by M-ZubairAhmed** [comment]
Yes @jasonblais will submit a pr for this :-)
