### ISSUE TITLE
The height and width parameters in inline image(mattermost markdown) doesn't work in mattermost version v5.18.0 .

### ISSUE THREAD

**Issue by jatinjtg** [mattermost/mattermost-server#13539]
#### Summary
height and width parameter in inline image doesn't work.

#### Steps to reproduce
mattermost server-version - 5.18.0
Send a message with body
 ```![Mattermost](https://imgsv.imaging.nikon.com/lineup/dslr/df/img/sample/img_01.jpg =50x76 "Mattermost Icon")```
The image height and width remains same and are not set to 50x76.
![image](https://user-images.githubusercontent.com/50952137/71575020-47f68c80-2b11-11ea-8323-21cd27e904c5.png)

#### Expected behavior
mattermost server-version - 5.17.0 or lower 
Send a message with body 
```![Mattermost](https://imgsv.imaging.nikon.com/lineup/dslr/df/img/sample/img_01.jpg =50x76 "Mattermost Icon")```
The image height and width are set to 50x76.
![image](https://user-images.githubusercontent.com/50952137/71574939-f77f2f00-2b10-11ea-934a-4404a99f1e79.png)

**Comment by chetanyakan** [comment]
This seems to be a regression in Mattermost Markdown.

**Comment by jasonblais** [comment]
Thanks for the report! We've reproduced it and opened a bug ticket to resolve https://mattermost.atlassian.net/browse/MM-21421

Anyone in the community open to helping with a fix?

**Comment by abdusabri** [comment]
@jasonblais I can look into this

**Comment by jasonblais** [comment]
Thank you @abdusabri!

**Comment by abdusabri** [comment]
I've a fix ready, and I will submit a PR today or tomorrow

**Comment by amyblais** [comment]
PR: https://github.com/mattermost/mattermost-webapp/pull/4623.

**Comment by abdusabri** [comment]
Thanks Amy.

@jasonblais, I'll unassign myself now since a PR already exists :)

**Comment by jasonblais** [comment]
Ah I see, sorry about that @abdusabri :(

**Comment by abdusabri** [comment]
> Ah I see, sorry about that @abdusabri :(

No worries! 🙂
