### ISSUE TITLE
Access mattermost on my domain without 8065

### ISSUE THREAD

**Issue by ugintl** [mattermost/mattermost-server#13548]
I have a domain, but I am unable to access mattermost on it. I have to add :8065 to access mattermost. Why is that? How I can access it on my domain like http://mydomain.com?

I followed this tutorial to install mattermost

https://idroot.us/install-mattermost-ubuntu-18-04-lts/

**Comment by amyblais** [comment]
Hi @ugintl,

Have you followed our official instruction guide here: https://docs.mattermost.com/install/install-ubuntu-1804.html?

Would you be open to posting this on our troubleshooting forum here as others may have seen the same issue? http://forum.mattermost.org/

**Comment by ugintl** [comment]
The tutorial I have followed is similar to what you have shared. When I add my domain to Site Url field, it gives not valid error, but if I put :8065 to the domain, it accepts it.

**Comment by amyblais** [comment]
@ugintl Thank you for opening the troubleshooting forum post! One of our support engineers has responded to your post there. https://forum.mattermost.org/t/access-mattermost-on-my-domain-without-8065/8750/2
