### ISSUE TITLE
another backslash rendering error (like #7601)

### ISSUE THREAD

**Issue by rular** [mattermost/mattermost-server#13546]
We use Mattermost to paste e.g. Windows-registry-links. 
we encountered, that sometimes the backslashes are stripped from rendering like #7601. 

We found out that this time this happens, when a "{" is following.
![backslash](https://user-images.githubusercontent.com/3407850/71658491-8f189380-2d44-11ea-9d3c-07ea4dc44e16.png)

**Comment by amyblais** [comment]
@hmhealey Do you know if this a markdown related bug or if Github markdown has this same issue?

**Comment by hmhealey** [comment]
This is intended since `\{` is an escape sequence for `{`. The same thing happens on GitHub.

@rular We recommend surrounding the text in backticks for text like that since it prevents the escaping like
~~~
Here is the key: `[HKEY_CLASSES_ROOT\CLSID\{53BEDF0B-4E5B-4183-8DC9-B844344FA104}]`
~~~

**Comment by rular** [comment]
yep, working. Thanks for workaround

**Comment by rular** [comment]
Thank you for voting me „thumbs up“! ;-)

Mit freundlichem Gruß
