### ISSUE TITLE
Some tests leave temporary databases

### ISSUE THREAD

**Issue by Pomyk** [mattermost/mattermost-server#13566]
#### Summary
Running server tests leaves temporary databases.

#### Steps to reproduce
run `make test-server` then list databases (for example "show databases;" in mysql).

#### Expected behavior
No new databases.

#### Observed behavior (that appears unintentional) 
Currently running all tests leaves 4 dbs in mysql and 2 in postgresql.

#### Possible fixes
Offending tests are in:
 - config/
 - store/sqlstore/
 - store/localcachelayer/

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-21520.

**Comment by hanzei** [comment]
Thanks for the quick fix @Pomyk :+1:
