### ISSUE TITLE
When writing post eventHandler for key pressed executes over 200 ms per key

### ISSUE THREAD

**Issue by soisetu** [mattermost/mattermost-server#13565]
#### Summary
When writing post, eventHandler for key pressed takes over 200 ms per key

#### Steps to reproduce
Mattermost 5.18.0
Type fast and UI is lagging when user has lots of channels.

#### Expected behavior
Writing post is smooth.

#### Observed behavior (that appears unintentional)

Debugged with Chrome profiling tool: mapAndSortChannelIds executes about in 140ms.
My channels:
17 favorites
35 public channels
13 private channels
129 direct messages

![eventhandler](https://user-images.githubusercontent.com/12621578/71762966-0aae4800-2edf-11ea-942d-20b066dca0d6.png)
![mapAndSortChannelIds](https://user-images.githubusercontent.com/12621578/71762967-0da93880-2edf-11ea-8ddb-84d3aa182f10.png)

**Comment by amyblais** [comment]
@soisetu What OS and version are you on? What browser are you using?

**Comment by soisetu** [comment]
Hi @amyblais and sorry about missing OS and browser specs.

Win 10, version 1809
Vivaldi, Chrome, Edge, Firefox, Mattermost Desktop App

Edge and Firefox are little better but still lagging.

**Comment by soisetu** [comment]
Problem seems to be this function call to getOrderedChannelIds: https://github.com/mattermost/mattermost-webapp/blob/master/components/sidebar/index.js#L46

**Comment by amyblais** [comment]
@soisetu Thank you! We have been investigating this issue with https://mattermost.atlassian.net/browse/MM-20349, and you may have helped us find the root cause of the issue. We'll try to fix this for v5.19.
