### ISSUE TITLE
Introduce webapp tests to mattermost-plugin-starter-template

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13571]
Extend the [mattermost-plugin-starter-template](https://github.com/mattermost/mattermost-plugin-starter-template) with the necessary boilerplate to support webapp tests.

See [https://github.com/mattermost/mattermost-plugin-jira/tree/master/webapp](https://github.com/mattermost/mattermost-plugin-jira/tree/master/webapp) as an example.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-18539

**Comment by M-ZubairAhmed** [comment]
can i take a stab at this?

**Comment by hanzei** [comment]
Sure, that would be great @M-ZubairAhmed :tada:
