### ISSUE TITLE
Only stop caching 404s from the /static/plugins/* endpoint

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13570]
As of MM-20948, we switched to `Cache-Control: no-cache` to require validation before every request of a plugin asset. This was only done to avoid incorrectly caching 404s, preventing a missing file request from “poisoning” the cache.

We can refine the approach to wrap the [http.FileServer](https://golang.org/pkg/net/http/#FileServer) to pre-check if the file in question exists and return the 404 without the old `Cache-Control` headers. Otherwise, we can emit the desire cache control headers and then delegate the normal file serving behaviour, restoring the original performance for the loading of plugin bundles.

There would be a small window in which the file might get deleted, frustrating this solution, but it shouldn’t materially impact the problem being solved here.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-20944

**Comment by dlclark** [comment]
I can take a look at this one.

**Comment by lieut-data** [comment]
Thanks, @dlclark!

**Comment by lieut-data** [comment]
Thanks again, @dlclark!

**Comment by dlclark** [comment]
No problem, glad to help!
