### ISSUE TITLE
Converge on strconv.ParseBool in the REST API

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13597]
We have a mix of `== "true"` and `strconv.ParseBool(...)` in the [api4](https://github.com/mattermost/mattermost-server/tree/master/api4) package when parsing boolean REST parameters.

Let's converge on using [strconv.ParseBool](https://golang.org/pkg/strconv/#ParseBool) both for consistency, and to simplify consumption of the REST API. Bonus points for writing a go vet test that checks for comparisons against the string `"true"` in the api4 package.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-21618

**Comment by vesari** [comment]
I'd like to work on this if I may?

**Comment by lieut-data** [comment]
Thanks, @vesari!

**Comment by lieut-data** [comment]
Thanks again, @vesari!
