### ISSUE TITLE
Logs with plugin

### ISSUE THREAD

**Issue by vladislavhirko** [mattermost/mattermost-server#13619]
Hello I try to create plugin, and I use mattermost-server API for deleting posts 
```
p.API.DeletePost(post.Id)
```
And when I print logs to console, i have something like that: 

![Screenshot from 2020-01-13 18-27-50](https://user-images.githubusercontent.com/55532072/72274164-4f02bc00-3634-11ea-90ae-437b2f6396ef.png)

And I don't undertang what is it...
When i try to delete aboute 500-1500 msgs
Some of them isn't deletes (i dont know why?!)
I requested posts with API 
```
 p.API.GetPostsSince(...)
```
Whats wrong with you logrus and API?

**Comment by amyblais** [comment]
@maruTA-bis5 @hanzei Do you know if this is a bug?

**Comment by lieut-data** [comment]
@vladislavhirko, are you able to share a complete example that reproduces the problem? Is it specific to trying to delete 500-1500 messages, or does this reproduce when trying to delete just just one message? 

The `DeletePost` API is currently not idempotent: if you try to delete a post that's already deleted, you will get an error whose underlying type is `sql.ErrNoRows`. Might that explain some of your symptoms?

The `dpanic` warning sounds like a separate issue: hopefully with a complete reproduction example I can help debug more.

**Comment by amyblais** [comment]
Closing this for now as we haven't heard feedback for a while. Please re-open this issue if the problem persists,
