### ISSUE TITLE
Size data for in-line images do not have any effect

### ISSUE THREAD

**Issue by dmarkdvt** [mattermost/mattermost-server#13611]
#### Summary
When you add some siza data for in-line images you still get the picture shown in it´s original size.

#### Steps to reproduce
Mattermost Server 5.18.0 & 5.18.1
Mattermost Webapp
Mattermost Client 4.2.0 & 4.3.2
Mattermost Mobile 1.26.2

Try this:
```
![Placeholder](https://via.placeholder.com/350x150 =100)
![Placeholder](https://via.placeholder.com/350x150 =50x50)
```

#### Expected behavior
When I add some siza data for an in-line image I want to see the image in my wished size.

#### Observed behavior (that appears unintentional) 
When you add some siza data for in-line images you still get the picture shown in it´s original size.

#### Possible fixes
I don´t have a fix for it.

**Comment by amyblais** [comment]
@dmarkdvt Does this issue sound similar as https://github.com/mattermost/mattermost-server/issues/13539?

**Comment by dmarkdvt** [comment]
> @dmarkdvt Does this issue sound similar as #13539?

@amyblais: Yes it does. :)
