### ISSUE TITLE
Recognize multi-line slash commands without requiring trailing space after trigger word.

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13642]
When providing a multi-line payload to a slash command, it’s currently necessary to add a space character immediately after the trigger word (e.g. `/standup \n<payload>`) instead of being able to start the newline right away (e.g. `/standup\n<payload>`).

Fix this in [ExecuteCommand](https://github.com/mattermost/mattermost-server/blob/b71a6b9f8dafc17a5c3d5b0772c67c989f839a3a/app/command.go#L158) by splitting /once/ on any whitespace character, and then reassembling safely. Be sure to write good unit tests to prevent regressions!

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-21343

**Comment by allenlai18** [comment]
i am interesting in looking into this

**Comment by lieut-data** [comment]
@allenlai18, I'd suggest trying to tweak the way we split apart the words instead, vs. trying to modify the payload. Could we detect the first non-whitespace character in the string and extract the trigger word up to that? That would also eliminate the need to split the whole command apart by spaces only to rejoin it.
