### ISSUE TITLE
SMTP, 550 Incorrect sender header (Check your FROM) #1 in 5.17.2+

### ISSUE THREAD

**Issue by sokoow** [mattermost/mattermost-server#13648]
1. Confirm you’re filing a new issue. [Search existing tickets in Jira]
This is a new issue

2. Confirm your issue does not involve security. 
it doesn't seem to be security

#### Summary
Recently there's some SMTP setting changes, one of our mattermost 5.17.2 servers stopped sending emails, and when we test smtp connection, we got ```SMTP, 550 Incorrect sender header (Check your FROM) #1``` constantly

#### Steps to reproduce
Pretty much upgrade mattermost server and test smtp

#### Expected behavior
Should be sending emails

**Comment by amyblais** [comment]
@sokoow Would be open to sharing what SMTP setting changes you've recently made, as well as all your config settings related to SMTP? Thanks,

**Comment by sokoow** [comment]
It's a pretty standard TLS setup on port 487, nothing fancy. Unfortunately it's shared with other services so I can't share configs. Funny thing is that we do have from field set, unless we're missing something.

**Comment by amyblais** [comment]
@sokoow Are there any additional errors you're seeing in the logs?

**Comment by sokoow** [comment]
@amyblais yeah, but they're pretty much saying same:

```
{"level":"error","ts":1579587049.152367,"caller":"mlog/log.go:174","msg":"Connection unsuccessful: SendMail: Can't close a connection to SMTP, 550 Incorrect sender header (Check your FROM) #1","path":"/api/v4/email/test","request_id":"icou4hfn5i8kz8m7xref3q1ezo","ip_addr":"XXX","user_id":"axy9jyu5e7yhzn1zqmrue1p3bh","method":"POST","err_where":"testEmail","http_code":500,"err_details":""}

{"level":"warn","ts":1579671420.5892699,"caller":"app/email_batching.go:244","msg":"Unable to send batched email notification","email":"email@email.com","error":"SendMail: Can't close a connection to SMTP, 550 Incorrect sender header (Check your FROM) #1"}

```

**Comment by amyblais** [comment]
@sokoow Have you had a chance to take a look at the troubleshooting tips here: https://docs.mattermost.com/install/smtp-email-setup.html#troubleshooting-smtp?

**Comment by sokoow** [comment]
Hey, it was our fault - some smtp/dns settings on our side got messed up, sorry for that
