### ISSUE TITLE
SMTP with Yahoo: Connection unsuccessful: SendMail: 550 Request failed; Mailbox unavailable - undefined

### ISSUE THREAD

**Issue by Delawen** [mattermost/mattermost-server#13652]
#### Summary
I am trying to use yahoo SMTP to send emails.

#### Steps to reproduce
Configure a basic free Yahoo email on the SMTP settings and test it ("Test Connection").  See my configuration on the image below.

An error will be shown (mine in Spanish):
`Connection unsuccessful: Connection unsuccessful: SendMail: Error ajuste "Dirección Desde", 550 Request failed; Mailbox unavailable - undefined`

Which may translate to:
`Connection unsuccessful: Connection unsuccessful: SendMail: Error in settings "Email from", 550 Request failed; Mailbox unavailable - undefined`

#### Expected behavior
I should be able to send emails using that SMTP.

#### Observed behavior (that appears unintentional) 

![image](https://user-images.githubusercontent.com/726590/72723837-01c9a180-3b82-11ea-87ed-197afd5a97ff.png)

#### Possible fixes
Could be this? https://stackoverflow.com/a/51084780/469932

**Comment by Delawen** [comment]
The config.json file had a different "FeedbackEmail" and that confused my configuration. Would be good to add this to troubleshooting or a warning on this page to check that.

Thanks rubber ducks! I will close but not remove in case someone else has the same issue.

**Comment by sphuber** [comment]
Just want to report that I think I experienced a similar problem. I setup a Mattermost server with v5.30.1 and configured my SMTP server details but got  the following error:
```
Connection unsuccessful: Connection unsuccessful: SendMail: Failed to close connection to SMTP server., 550 5.2.0 Spam message rejected
```
Setting the key `EmailSettings.FeedbackEmail` to the same value as that of `EmailSettings.SMTPUsername` fixed the problem for me.
