### ISSUE TITLE
Mattermost admin_console needs footer padding

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#13673]
When you scroll up and down on within the admin_console of Mattermost frequently the last "Features" entry under "EXPERIMENTAL" is blocked out. There needs to be some footer padding below this so that browsers that use Chromium do not cover this up and make it seem inaccessible to administrators. It just has an awkward feel of being so close to the bottom. Ex:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/2Nur8JYd/Pasted_Image_1_21_20__2_08_PM.png)

**Comment by amyblais** [comment]
@ylluminate What Mattermost server version and OS are you on?

**Comment by ylluminate** [comment]
Mattermost 5.18.0 on Chrome 79.0.3945.130 on macOS 10.15.2.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-21983.

**Comment by amyblais** [comment]
This is fixed for upcoming v5.22 release, scheduled for April 16th,
