### ISSUE TITLE
bug header dosen't close when save and cancel  it 

### ISSUE THREAD

**Issue by lbouquinUniv** [mattermost/mattermost-server#13681]
hi, 

I've got a problem when i want changer header of Chanel. We can modify it but popup doesn't close.

![prob_header](https://user-images.githubusercontent.com/57000474/72877900-31031e80-3cfa-11ea-945e-ecb8b5b479e7.png)

**Comment by amyblais** [comment]
Hi @lbouquinUniv, what Mattermost server version are you using and what OS are you on?

**Comment by lbouquinUniv** [comment]
it's 5.18.1 version and I use alpine3.10 in docker

**Comment by amyblais** [comment]
@lbouquinUniv We fixed an issue for this in v5.19.0, would you be open to upgrading to the latest version to see if your issue is fixed?

**Comment by amyblais** [comment]
Closing this for now as we haven't received an update for a while, please re-open this issue if v5.19 doesn't resolve it,
