### ISSUE TITLE
Mattermost user nickname input should allow maximum of 64 characters instead of 22

### ISSUE THREAD

**Issue by kenrick95** [mattermost/mattermost-server#13680]
#### Summary

<img width="573" alt="Screenshot 2020-01-22 at 3 11 47 PM" src="https://user-images.githubusercontent.com/3090380/72872960-8c003a00-3d29-11ea-8c79-a43267a97d4c.png">

In https://github.com/mattermost/mattermost-server/pull/3186, `maxlength` of 22 characters was added to the webapp nickname input element, but since `nickname` field in database schema is 64 character long (checked on both [mysql](https://github.com/mattermost/mattermost-server/blob/master/scripts/mattermost-mysql-5.0.sql#L1006) and [postgresql](https://github.com/mattermost/mattermost-server/blob/master/scripts/mattermost-postgresql-5.0.sql#L609), it should be 64 instead of 22 characters.

#### Extra information

(this shouldn't matter, but I include this info for completeness)

- Mattermost Version: 5.19.0
- Database Schema Version: 5.19.0
- Database: mysql

#### Possible fixes

Change [this constant value](https://github.com/mattermost/mattermost-webapp/blob/2d74172f1c6e72395d53c58103a32968c6d320a4/utils/constants.jsx#L1318) to 64.

**Comment by amyblais** [comment]
I asked our team about this here: https://community.mattermost.com/core/pl/8k73mu51tjyy98xaanaooeknbr.

**Comment by amyblais** [comment]
@kenrick95 Responses from our team:

 - The 22 character limit is to ensure the Nickname displays without truncating (based on casing or language) in the LHS.
 - Database length was changed to be higher for things like nicknames because it needs to accommodate LDAP sync.
 - The team feels that making the decision on the length of the field should be based more on the UX than the current length of the database field so long as the length is less than or equal to the database field (easier to change front end limit than database field lengths).

Does this help?

**Comment by kenrick95** [comment]
I see, but even then, having a 22-character nickname usually already entails that the display will be truncated in the LHS sidebar

![Screenshot 2020-01-23 at 9 53 02 AM](https://user-images.githubusercontent.com/3090380/72950402-3e85da80-3dc6-11ea-9753-644c2548a9af.png)

A real use case that I faced in my company is that we often utilize this nickname field to indicate our out-of-office period. While using nickname field is not ideal, this is what we're currently have and some people who knows this 22-character limit that are only imposed on the front-end will remove the "maxchar" attribute so we can save more texts in it.

<img width="967" alt="Screenshot 2019-08-16 at 2 11 25 PM" src="https://user-images.githubusercontent.com/3090380/72950795-5578fc80-3dc7-11ea-9cfa-1041650c4f83.png">

![Screenshot 2020-01-23 at 9 59 08 AM](https://user-images.githubusercontent.com/3090380/72950723-23679a80-3dc7-11ea-8444-86ac622f4787.png)


I understand that this "feature request" may not made it to the mattermost core as it may have big UX impact to the users. Hence, feel free to close this issue.

Thanks a lot!

**Comment by amyblais** [comment]
@kenrick95 I see, an additional option that may help with communicate out-of-office times:

 - Enable [Automatic Replies](https://docs.mattermost.com/administration/config-settings.html#enable-automatic-replies-experimental) which will notify other users that the person is off if they try to message the user.

We are also planning for a feature that enables adding a custom status: https://mattermost.uservoice.com/forums/306457-general/suggestions/17728987-status-labels.

**Comment by kenrick95** [comment]
That feature request on user voice is exactly what is needed instead of "hacking" the nickname field. Thanks a lot!
