### ISSUE TITLE
Chat messages "disappear" when clicking Add Emoji option

### ISSUE THREAD

**Issue by pabnogon** [mattermost/mattermost-server#13740]
**Summary:** When clicking **Add Emoji** option, messages of the related chat are sort of hidden, so while the emojis table is displayed, you can't see the messages of the conversation (See images attached).

I'm curently using version 4.2.3

**Steps to reproduce:**

1. Go to a conversation/chat that has messages written in it.
2. Click _Add Emoji_ icon so the table with emojis is displayed.

**Expected behavior:** Messages are still shown when clicking this option.

**Observed behavior:** Messages are like hidden when clicking this option.

![2020-01-23_12h25_07](https://user-images.githubusercontent.com/47986635/72982376-35553780-3ddf-11ea-8703-32ec192d6020.png)
![2020-01-23_12h25_19](https://user-images.githubusercontent.com/47986635/72982378-38e8be80-3ddf-11ea-9042-1c6a55c883a7.png)
![2020-01-23_12h25_30](https://user-images.githubusercontent.com/47986635/72982383-3ab28200-3ddf-11ea-8eed-c96a814b92b0.png)

**Comment by amyblais** [comment]
@pabnogon v4.2.3 is your desktop app version, would you be open to upgrading to v4.3.2 desktop app version (it is our latest version)? 

Also, what Mattermost server version are you on? You can find it from Main Menu > About Mattermost.

**Comment by pabnogon** [comment]
Sorry, see attached proper info related to the version I'm currently using
![2020-01-23_14h40_47](https://user-images.githubusercontent.com/47986635/72989457-97696900-3dee-11ea-887d-08075ff57436.png)

**Comment by amyblais** [comment]
@pabnogon Thank you! 

Do you see the same issue on our latest desktop app version? You can download the latest from here: https://mattermost.com/download/#mattermostApps.

What OS and version are you on? (E.g. Windows 10)

Can you help share any log errors you see via the instructions here https://docs.mattermost.com/install/desktop.html#reporting-issues?

**Comment by pabnogon** [comment]
I thought I was in the latest desktop app version, got confused between 4.2.3 and 4.3.2.
Not happening this anymore in the latest version.

I am running it in Windows 10 Enterprise.

Thanks!

**Comment by amyblais** [comment]
Awesome, good to hear that the issue is fixed!
