### ISSUE TITLE
Cannot join developer channel - the link in "getting started" page is invalid

### ISSUE THREAD

**Issue by fzyzcjy** [mattermost/mattermost-server#13750]
#### Summary
The "step 1: Sign up to our Mattermost site" is invalid in https://developers.mattermost.com/contribute/getting-started/ .

#### Steps to reproduce
Click that link in step1 (i.e. https://community.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676 ) and you will see 

> The invite link was invalid. Please speak with your Administrator to receive an invitation.

#### Expected behavior
able to join

#### Observed behavior (that appears unintentional) 
not able to join

#### Possible fixes
update the link

**Comment by amyblais** [comment]
@fzyzcjy Would you be open to moving this issue here: https://github.com/mattermost/mattermost-developer-documentation/issues. I can then make it into Help Wanted. If you're interested in helping to fix this, please let us know!

**Comment by amyblais** [comment]
Actually I went ahead and opened a PR for this: https://github.com/mattermost/mattermost-developer-documentation/pull/517.

**Comment by fzyzcjy** [comment]
Thanks
