### ISSUE TITLE
word "team" overflows into next line in Main Menu

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#13772]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bug report in one concise sentence

When you open the Main Menu, the word "team" overflows into the next line

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

Version: 5.19.1
OS: Windows 10
Screen: 15.6" 1920 x 1080

Open the "Main Menu" and the word "team" overflows into the next line

#### Expected behavior
Describe your issue in detail

When you open the Main Menu, the word "team" overflows into the next line, this creates a larger button/option in the dropdown which looks a bit off ?

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

![image](https://user-images.githubusercontent.com/363587/73218315-c598d100-417f-11ea-802d-397dace315bb.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

Couple of options come to mind,
1. Drop the sub-text (ie, Add or invite people to the team) as no other option in the main menu has this sub-text
or
2. Make the main-menu wider to fit the word "team" in the same line

**Comment by amyblais** [comment]
We have an existing ticket here: https://mattermost.atlassian.net/browse/MM-21870.
