### ISSUE TITLE
UI/UX: Organizing Teams on Sidebar

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#13787]
Currently for Mattermost servers that have many teams it becomes unwieldy to manage / prioritize teams. Could we please have a function to help organize these better?

I believe that this would take perhaps one of two forms or both:

1) Allow drag-n-drop organization to move teams into a non-alphabetical order.  The reason that this is important is that most "teams" do not like to have their names "modified".  For example, Company "A-Team" may be a lower priority to most users in a Mattermost server and thus it might need to go down where "Z-Team" might normally be located.  However, you don't want to inadvertently inform "A-Team" that they're low priority by naming them something like "15) A-Team" or "z) A-Team", etc. to make them move down the priority list.  Getting creative with alphabetical sorting is just inappropriate and offensive to clients who can't / shouldn't be forced into understanding this kind of situation in a chat system where they're part of more than one team - or not and then wonder why on earth their team name is so weird...

2) Facilitate "folders" / groups that would allow us to expand them (similar to how macOS Finder's list view works).  This would allow some organization / grouping and the use of names, but I believe it's a bit more complex.  I think it would be SUPER useful to have this function, but I believe it should be implemented AFTER a drag-n-drop organizational function is implemented since this folder concept would need the drag and drop functionality for organizational purposes.  It would sure be nice to have personal organizational folders like "Work", "Rotary/some-service-organization", "Church", "City Council", "Personal", "Company A (that has multiple teams), etc.

**Comment by amyblais** [comment]
@ylluminate Thank you for sharing, there is an open PR here from a community member: https://github.com/mattermost/mattermost-webapp/pull/4042. Original Help Wanted ticket is here: https://github.com/mattermost/mattermost-server/issues/12621.

This is mainly for the first scenario you outlined above for now.

**Comment by ylluminate** [comment]
Wow wow wow wow, thank you for pointing that out.  What can we do to get this pushed in STAT?  As I noted on that, this first issue would be marvelous and would take some monkeys off my back right now re: the usage of Mattermost (which I'm not willing to move away from, but that won't stop them from complaining until this is in place).

**Comment by amyblais** [comment]
I found that there is a thread about this here: https://community.mattermost.com/core/pl/kky9gjmdc7g38ys3piixxibwyy.

``jason.blais`` just asked help for moving this PR forward: https://community.mattermost.com/core/pl/4ch1r689yt8pzrfxf6z3z76ibe

**Comment by amyblais** [comment]
Please feel free to open a feature request for the second suggestion here https://mattermost.uservoice.com/forums/306457-general!

**Comment by ylluminate** [comment]
@amyblais you'll have to forgive me, I really don't like UserVoice at all and haven't for years.
