### ISSUE TITLE
Guest-Accounts: UI: Account creation looks like it errored out, but actually worked

### ISSUE THREAD

**Issue by somenet** [mattermost/mattermost-server#13780]
#### Summary
When creating a guest-accounts from its invite-eMail the user gets an error stating that their email-address is not allowed to be used, independent of whether guest-allowed-domains was left empty or specified to the tested domain.

The problem is: it actually worked and they can login now, but were not added to the specified channels.

#### Steps to reproduce
+ Restrict system-registrations to a domain (like `@tuwien.ac.at`)
+ Dont restrict `Whitelisted Guest Domains` (it actually doesnt seem to matter if nothing was set or the domain was restricted to `@gmail.com`)
+ Invite yourself with another email-address (like `@gmail.com`)
+ set channel to `off-topic`
+ open a incognito-window in browser
  + login to your gmail
  + click on `Join Team`
  + fill any username + pw
  + get something that looks like an "error message"

![screen_20200128_163206](https://user-images.githubusercontent.com/5354356/73280452-d5033300-41ee-11ea-8bb3-315e5a086b60.png)

The account was actually successfully created and can be used to login **BUT** was not added to any of the specified channels. When logging in, I get this.

![screen_20200128_163310](https://user-images.githubusercontent.com/5354356/73281766-ba31be00-41f0-11ea-8aa6-5b0ab854e21e.png)

On another note: It would be good to show to which addresses the registration is restricted and/or allow it to customize the registration page via `sysconsole -> Customization`.

#### Expected behavior
Getting an OK + redirect to login-page instead of what seems like an error message.

#### Observed behavior (that appears unintentional) 
Not getting any positive registration-feedback and instead getting something resembling an error message.

**Comment by somenet** [comment]
Addition: It works as expected, if the guest's domain is in the system-wide domain restrictions.

**Comment by amyblais** [comment]
Thank you, we have an existing ticket open here: https://mattermost.atlassian.net/browse/MM-22067.

**Comment by amyblais** [comment]
Fixed for upcoming v5.20 release,
