### ISSUE TITLE
Utils.hasSoundOptions shouldn't exclude firefox

### ISSUE THREAD

**Issue by cork** [mattermost/mattermost-server#13807]
#### Summary
Utils.hasSoundOptions excludes firefox, I suspect this is cause it once didn't support .mp3 files. This hasn't been the case for a long time though, so i think it is time to allow firefox to get notification sounds too.

#### Steps to reproduce
1. Open mattermost in firefox.
2. Get a notification from a team member in a direct chat or channel.

#### Expected behavior
The ding sound should be played

#### Observed behavior (that appears unintentional) 
You get the system notification but unless the system notifier plays sounds you don't hear anything.

#### Possible fixes
Utils.hasSoundOptions that excludes firefox.

**Comment by Ths2-9Y-LqJt6** [comment]
I'll take this one!

**Comment by Ths2-9Y-LqJt6** [comment]
We should also update Account Settings -> Notifications -> Desktop Notifications.  Right now it says:

> Notification sounds are available on IE11, Safari, Chrome and Mattermost Desktop Apps.

And with this change it should say:

> Notification sounds are available on Firefox, IE11, Safari, Chrome and Mattermost Desktop Apps.

As an aside, now that [Edge is actually Chromium](https://support.microsoft.com/en-us/help/4501095/download-the-new-microsoft-edge-based-on-chromium), I assume we should open a separate ticket on adding support for Edge?  

@Willyfrog or @hmhealey  - as commenters on the last PR, maybe you have thoughts on either of these points?

**Comment by Ths2-9Y-LqJt6** [comment]
Oh!! Interesting! There's conflict on what the message says:

```
egrep -r 'user.settings.notifications.sounds_info":|defaultMessage="Notification sounds' i18n/*json components/user_settings/notifications/*
i18n/de.json:  "user.settings.notifications.sounds_info": "Benachrichtigungstöne sind in IE11, Safari, Chrome und den Mattermost-Desktop-Apps verfügbar.",
i18n/en.json:  "user.settings.notifications.sounds_info": "Notification sounds are available on Edge, Safari, Chrome and Mattermost Desktop Apps.",
i18n/es.json:  "user.settings.notifications.sounds_info": "Los sonidos de notificación están disponibles en IE11, Edge, Safari, Chrome y Aplicaciones de Escritorio de Mattermost.",
i18n/fr.json:  "user.settings.notifications.sounds_info": "Les sons de notification sont disponibles sur IE11, Edge, Safari, Chrome et les applications de bureau Mattermost.",
i18n/it.json:  "user.settings.notifications.sounds_info": "I suoni di notifica sono disponibili in IE11, Edge, Safari, Chrome e l'app desktop di Mattermost.",
i18n/ja.json:  "user.settings.notifications.sounds_info": "通知音はIE11、Safari、Chrome、Mattermostデスクトップアプリで利用できます。",
i18n/ko.json:  "user.settings.notifications.sounds_info": "알림 사운드는 IE11, Edge, Safari, Chrome 및 Mattermost 데스크탑 애플리케이션에서 사용할 수 있습니다.",
i18n/nl.json:  "user.settings.notifications.sounds_info": "Notification sounds are available on IE11, Safari, Chrome and Mattermost Desktop Apps.",
i18n/pl.json:  "user.settings.notifications.sounds_info": "Dźwięk powiadomień dostępny jest w IE11, Safari, Chrome i aplikacjach pulpitowych Mattermost.",
i18n/pt-BR.json:  "user.settings.notifications.sounds_info": "Sons para notificações estão disponíveis no IE11, Safari, Chrome e Mattermost Desktop Apps.",
i18n/ro.json:  "user.settings.notifications.sounds_info": "Sunetele de notificare sunt disponibile pe aplicațiile Desktop IE11, Safari, Chrome și Mattermost.",
i18n/ru.json:  "user.settings.notifications.sounds_info": "Звуки уведомлений доступны в IE11, Edge, Safari, Chrome и Mattermost Desktop.",
i18n/tr.json:  "user.settings.notifications.sounds_info": "Bildirim sesleri IE11, Safari, Chrome ve Mattermost Masaüstü Uygulaması ile kullanılabilir.",
i18n/uk.json:  "user.settings.notifications.sounds_info": "Звуки повідомлень доступні в IE11, Edge, Safari, Chrome і Mattermost Desktop.",
i18n/zh-CN.json:  "user.settings.notifications.sounds_info": "通知声音可在 IE11、Edge、Safari、Chrome 以及 Mattermost 桌面应用使用。",
i18n/zh-TW.json:  "user.settings.notifications.sounds_info": "通知音效支援 IE11、Safari、Chrome 跟 Mattermost 桌面應用程式。",
components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap:              defaultMessage="Notification sounds are available on Edge, Safari, Chrome and Mattermost Desktop Apps."
components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap:              defaultMessage="Notification sounds are available on Edge, Safari, Chrome and Mattermost Desktop Apps."
```

So *both* `IE11` and `Edge` aren't uniformly mentioned.  Again, I know it's not this ticket, but I'm in there now so I wanted to flag it.

I'll work to update these i18n strings seperate from fixing IE11/Edge status ; )

**Comment by Willyfrog** [comment]
For the translation strings, my guess is that the translations are not updated. Not sure how to handle that.

New chromium based Edge should be tested and then decide on next steps for it.

And yes, text on settings should be changed to reflect current condition once there is a patch to fix it. The original PR was not accepted as the author didn't want to sign the CLA.
