### ISSUE TITLE
Feature Request: Rapid History Navigator

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#13801]
So many of us are thrilled with the auto scroll back in history, it helps a lot.  There is some room to make going back in history very far more attainable / user friendly:

Please implement a mechanism to go back via some mechanism by weeks, months and years. I fear that a calendar might be too bulky, but some kind of a slider or button / tab arrangement might make this fairly efficient. It might be possible to put some kind of draw / slider at the top that you can pull down and navigate it more like Time Machine in macOS.

This is especially a problem for those of us who have moved to MatterMost from HipChat and other services where we have years of history and some projects and notes require such navigation.

**Comment by amyblais** [comment]
Please feel free to open a feature request for this here https://mattermost.uservoice.com/forums/306457-general!
