### ISSUE TITLE
Problem occurs when I write a message with 2 bytes characters.

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-server#13806]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
This problem occurs when I write a message with 2 bytes characters. I tested it clean installed 5.19.1 on Ubuntu 18.04. (This problem is general.)

#### Steps to reproduce
1. Send a message other user using 2 bytes characters.
2. You must never type 1 byte character at the end of message. (Very important)
3. He received this message.

However,

A. Move to another conversation, now.
B. You can see the icon changed to "Writing" that chat room before.
C. If I will visit same chat room again, I can see my last message in input message box. (Of course, my message already send.)

#### Expected behavior
If the message was sent successfully, no message should remain in the message input box.

#### Observed behavior (that appears unintentional) 
The message remains in the box.

#### Possible fixes
Here is a temporary solution:
1. Use 1 byte characters (dot and etc) at the end of the message.
2. Press Enter twice.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-22233.

**Comment by amyblais** [comment]
Fixed for upcoming v5.20 release,
