### ISSUE TITLE
Space in content-type breaks integration with 3rd party apps

### ISSUE THREAD

**Issue by mulderbaba** [mattermost/mattermost-server#13808]
Mattermost server tries to parse the content-type along with the charset as stated in [here](https://github.com/mattermost/mattermost-server/blob/a63684fcb5e3ba7b7522b35c29a4cb27779ba823/web/webhook.go#L41). 

This breaks integrating with apps (built by Spring 5.x) where no space is defined between the mime type and charset type, which is ``application/x-www-form-urlencoded;charset=UTF-8``.

According to [HTTP spec](https://tools.ietf.org/html/rfc7230#section-3.2.3) the whitespace is optional, so parsing should gracefully handle this optional whitespace.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-22247.

**Comment by ethervoid** [comment]
@mulderbaba Merged [here](https://github.com/mattermost/mattermost-server/commit/c8a923d9e3fe039a5239aaa9a990ef4a02a686a5). In the next version, 5.22, will be available.
