### ISSUE TITLE
Mattermost plugins doesnt work on Mobile app 

### ISSUE THREAD

**Issue by aminzafarghandi** [mattermost/mattermost-server#13803]
Dears,
Some mattermost plugins like voice message , jira and ... doesnt work on mobile app . 
Do you have any plan to resolve this issue . and if your answer is positive , what is your estimated time ?

#### Summary
Mattermost doesnt support some plugins like voice on mobile client

**Comment by amyblais** [comment]
Closing as a duplicate. https://github.com/mattermost/mattermost-mobile/issues/3883
