### ISSUE TITLE
export particular channel

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#13829]
Hello dear team.

Would it be possible to export into CSV the particular channel from the team? I only found the way to export the whole team with the only limit by the time.

**Comment by swood** [comment]
Also, I tried to export data to CSV on my working instance of Mattermost (version 5.19.1) and got SIGSEGV:

```
./bin/mattermost export csv /mattermost/data/export/export.csv -c /mattermost/config/config_docker.json --exportFrom=12345
{"level":"info","ts":1580923052.0994718,"caller":"sqlstore/post_store.go:1351","msg":"Post.Message has size restrictions","max_characters":16383,"max_bytes":65535}
MessageExport feature not available
{"level":"info","ts":1580923052.280846,"caller":"app/server.go:346","msg":"Stopping Server..."}
{"level":"info","ts":1580923052.2809463,"caller":"app/web_hub.go:125","msg":"stopping websocket hub connections"}
{"level":"warn","ts":1580923052.2809944,"caller":"app/web_hub.go:130","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","ts":1580923052.2815228,"caller":"app/plugin.go:280","msg":"Shutting down plugins"}
{"level":"info","ts":1580923052.2866275,"caller":"sqlstore/supplier.go:907","msg":"Closing SqlStore"}
{"level":"info","ts":1580923052.286731,"caller":"app/server.go:384","msg":"Server stopped"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12034c4]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/v5/cmd/mattermost/commands.buildExportCmdF.func1(0x241a880, 0xc000223880, 0x1, 0x4, 0x0, 0x0)
	github.com/mattermost/mattermost-server/v5@/cmd/mattermost/commands/export.go:159 +0x124
github.com/spf13/cobra.(*Command).execute(0x241a880, 0xc000223800, 0x4, 0x4, 0x241a880, 0xc000223800)
	github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x2421400, 0x0, 0x66e00, 0xc00003c0b8)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
github.com/mattermost/mattermost-server/v5/cmd/mattermost/commands.Run(...)
	github.com/mattermost/mattermost-server/v5@/cmd/mattermost/commands/root.go:15
main.main()
	github.com/mattermost/mattermost-server/v5@/cmd/mattermost/main.go:30 +0x87
```

As I noticed, the feature is not available. Should I use the manual export from the database directly instead of the util higher-level like Mattermost?
By the way, I think this is a bad practice when the software falling down with the SIGSEGV.

**Comment by amyblais** [comment]
Hi @swood, I'll ask our team about this.

**Comment by lieut-data** [comment]
@amyblais / @swood, there is indeed a bug here, in that after outputting:
```
MessageExport feature not available
```

the code continues on to try to use the `nil` MessageExport struct. We should fix that as a separate issue -- @amyblais, can you file same?

@swood I believe this feature at large requires an enterprise license to work correctly. Do you have the appropriate license configured when running this export command?

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-22372.

**Comment by swood** [comment]
@lieut-data I don't have an enterprise license, an only general one, or community to say better. Does it mean the export to the CSV is unreachable anyway even if you fix this bug?
Does any change to use this feature with community license?
And, I would like to re-ask my original question. Does it correct there is no way to export only one channel from the team? The only whole team export to jsonl-format and after filter it with the grep?

**Comment by lieut-data** [comment]
@swood, the `csv` (and other "compliance"-related exports) are indeed enterprise-only at this time. I don't know if there's any plans on that front.

With respect to your original question, I believe you're correct: there is no way to export only one channel from the team. Though instead of `grep` to filter, I'd suggest a tool like https://stedolan.github.io/jq/, and just `select` the rows matching the channel of interest.

**Comment by swood** [comment]
@lieut-data  can I ask you about the message:
```
Bulk export for posts containing a single member is not supported
```

How can I detect the Id or name of this channel and handle export it?

**Comment by lieut-data** [comment]
@swood, I admit to not being familiar with that message. Is it being emitted from the tool? Or from our documentation?

**Comment by swood** [comment]
@lieut-data It is indeed from the Mattermost's bulk export tool.

**Comment by lieut-data** [comment]
@swood, I'm having trouble finding any reference to that in the code. Can you share a longer log context? Alternatively, I bet @grundleborg knows to what this is referring given his first-hand experience here.

**Comment by grundleborg** [comment]
That message is saying that you can't export a self-DM channel (i.e. a direct message channel with yourself). We only recently (5.20 IIRC) added the support for this.

**Comment by lieut-data** [comment]
Haha! That explains why my grepping isn't finding anything :p -- thanks, @grundleborg! @swood, hopefully updating to v5.20 will address the immediate roadblock you're facing.

**Comment by swood** [comment]
I have another one question by this topic. I tried to make full export and I got an error:
```
{"level":"info","ts":1581358284.4360383,"caller":"app/export.go:82","msg":"Bulk export: exporting emoji"}
{"level":"info","ts":1581358284.5054996,"caller":"app/export.go:87","msg":"Bulk export: exporting direct channels"}
{"level":"info","ts":1581358288.501164,"caller":"app/export.go:92","msg":"Bulk export: exporting direct posts"}
SqlPostStore.GetDirectPostParentsForExportAfter: Unable to get direct posts, context deadline exceeded
{"level":"info","ts":1581358298.5015373,"caller":"app/server.go:346","msg":"Stopping Server..."}
{"level":"info","ts":1581358298.5015996,"caller":"app/web_hub.go:125","msg":"stopping websocket hub connections"}
{"level":"warn","ts":1581358298.5016224,"caller":"app/web_hub.go:130","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","ts":1581358298.5020928,"caller":"app/plugin.go:280","msg":"Shutting down plugins"}
{"level":"info","ts":1581358298.5067883,"caller":"sqlstore/supplier.go:907","msg":"Closing SqlStore"}
{"level":"info","ts":1581358298.5069292,"caller":"app/server.go:384","msg":"Server stopped"}
Error: SqlPostStore.GetDirectPostParentsForExportAfter: Unable to get direct posts, context deadline exceeded
```

How can I export direct messages as well?

**Comment by lieut-data** [comment]
Hmm, that seems like a performance issue fetching the posts from the database. @grundleborg, is this by chance a known issue with direct post exports?

**Comment by swood** [comment]
@lieut-data 
During this conversation, I realised you guys didn't think to make a proper export tool. So, I will write my own. Do you mind I will publish it when I'll finish it?

**Comment by wiersgallak** [comment]
@swood I'd be interested in learning more about what your thoughts are on the tool and where you'd like to see it published.  Feel free to detail here or reach out to me on our community server as @katie.wiersgalla

**Comment by grundleborg** [comment]
> Hmm, that seems like a performance issue fetching the posts from the database. @grundleborg, is this by chance a known issue with direct post exports?

No knows issue that I'm aware of - I certainly haven't seen many reports of it failing like this.

@swood is the server under a lot of load, or does it have a very large number of Posts in the database? I'd be interested in getting a sense for this so we can go test a similar size database and see if we need to make some performance enhancements to the bulk export SQL queries.

For an immediate workaround, you can extend the database query timeout in your `config.json`. For example, if you are using MySQL, in `SqlSettings` there is a key-value that looks similar to this: `"DataSource": "mmuser:xxxxx@tcp(dockerhost:3306)/mattermost_test?charset=utf8mb4,utf8\u0026readTimeout=30s\u0026writeTimeout=30s",` - by changing the `readTimeout` value in that string to a larger number, you can allow slower queries to complete without the `context deadline exceeded` error message occurring.

**Comment by swood** [comment]
@grundleborg In the main team I have the counts like you can see on screenshot:
https://prnt.sc/r16drb

It is only one team on my instance.

Yes, I indeed can extend the limit, but, I need a CSV export, I still need to parse Jsonl and convert it into the CSV. So, I decided to write my export tool and publish in on the GitHub. Maybe someone will face the same issue.
The main features will:
- format export in CSV appropriate for Slack import;
- export only one channel.

If you'd like to add something feel free to do it.
