### ISSUE TITLE
The Get posts for a channel API miss some post when using since parameter.

### ISSUE THREAD

**Issue by XD1234567** [mattermost/mattermost-server#13846]
#### Summary
The `Get posts for a channel` API can't get all posts in a channel from a certain time stamp when using since parameters

#### Steps to reproduce
1. Better create a new channel for testing.
2. Assume channel create timestamp is A.Then,post number 1 to 1000 to a channel for testing.This will make the channel has 1001 posts(number 1 to 1000 and a "xxx joined the channel" post) from timestamp A.
3. Set the `since` parametre to a vaule which is smaller than A,make a http Get request to the channle.

#### Expected behavior
I understand that I can get 1000 posts at most when I using `since` parameter to make the `Get posts for a channel` API request.So I should get 100 posts which is from number 1000 to number 1 after the HTTP requesting.

#### Observed behavior (that appears unintentional) 
I don't get the whole 1000 numbers.In my case,I don't get the number 634 post. Weirdly,I get the "xxx joined the channel" post instead.
So let's say I want get all the post in a certain channel from a certain timestamp.With this probelm,I will always miss some posts if there are many posts exit.
By the way,I am using Windows docker previerw version 5.18.0-rc1 mattermost server.And I found the same probelm in version 5.10 mattermost server which is installed on ubuntu. 

#### Possible fixes
I am confused.Please fix this!!

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-22417.

**Comment by lieut-data** [comment]
@XD1234567, would you be open to sharing a bulk export of the channel in question for help in reproducing? See https://docs.mattermost.com/administration/bulk-export.html for more details.

**Comment by XD1234567** [comment]
> @XD1234567, would you be open to sharing a bulk export of the channel in question for help in reproducing? See https://docs.mattermost.com/administration/bulk-export.html for more details.

Any idea how I can export the posts I need in a Windows docker preview version Mattermost?I tried something like `docker exec -it mattermost-preview mattermost export bulk F:\bulk_data.json --all-teams`,but it won't work..

**Comment by lieut-data** [comment]
Ah, hmm, I confess I'm not familiar with the details of executing in that specific environment. Can you share any errors from running the tool? Note that it shouldn't be necessary to specify a path to the file: ideally you can just capture the output from docker and pipe it on your shell's side to a file of your choosing.

**Comment by XD1234567** [comment]
@lieut-data ,I will put the output of teminal here.
```
root@f9736f1a76f7:/mm# mattermost export bulk file.json --all-teams
{"level":"info","ts":1581574230.6135662,"caller":"utils/i18n.go:83","msg":"Loaded system translations","for locale":"en","from locale":"/mm/mattermost/i18n/en.json"}
{"level":"info","ts":1581574230.6140878,"caller":"app/server_app_adapters.go:58","msg":"Server is initializing..."}
{"level":"info","ts":1581574230.622722,"caller":"sqlstore/supplier.go:212","msg":"Pinging SQL","database":"master"}
{"level":"error","ts":1581574230.693947,"caller":"app/server_app_adapters.go:125","msg":"SiteURL must be set. Some features will operate incorrectly if the SiteURL is not set. See documentation for details: http://about.mattermost.com/default-site-url"}
{"level":"info","ts":1581574230.7056613,"caller":"mlog/log.go:166","msg":"Starting up plugins"}
{"level":"error","ts":1581574230.7059147,"caller":"app/plugin.go:151","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: no such file or directory"}
{"level":"info","ts":1581574230.7060792,"caller":"app/server.go:217","msg":"Current version is 5.18.0 (5.18.0-rc1/Tue Dec  3 20:13:47 UTC 2019/20f13aa07eb468e29bc0dd1a52941cb7c4532ccb/none)"}
{"level":"info","ts":1581574230.706173,"caller":"app/server.go:218","msg":"Enterprise Enabled: false"}
{"level":"info","ts":1581574230.706377,"caller":"app/server.go:221","msg":"Printing current working","directory":"/mm"}{"level":"info","ts":1581574230.7064087,"caller":"app/server.go:222","msg":"Loaded config","source":"file:///mm/mattermost/config/config.json"}
{"level":"info","ts":1581574230.7183805,"caller":"mlog/log.go:166","msg":"Starting up plugins"}
{"level":"error","ts":1581574230.7184515,"caller":"app/plugin.go:151","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: no such file or directory"}
{"level":"info","ts":1581574230.7200565,"caller":"sqlstore/post_store.go:1351","msg":"Post.Message has size restrictions","max_characters":16383,"max_bytes":65535}
{"level":"info","ts":1581574230.7699301,"caller":"mlog/log.go:166","msg":"Starting up plugins"}
{"level":"error","ts":1581574230.7702782,"caller":"app/plugin.go:151","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: no such file or directory"}
{"level":"info","ts":1581574230.8314946,"caller":"mlog/log.go:166","msg":"Starting up plugins"}
{"level":"error","ts":1581574230.8316402,"caller":"app/plugin.go:151","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: no such file or directory"}
{"level":"info","ts":1581574230.839034,"caller":"app/export.go:57","msg":"Bulk export: exporting version"}
{"level":"info","ts":1581574230.8613136,"caller":"app/export.go:62","msg":"Bulk export: exporting teams"}
{"level":"info","ts":1581574230.864542,"caller":"app/export.go:67","msg":"Bulk export: exporting channels"}
{"level":"info","ts":1581574230.8679774,"caller":"app/export.go:72","msg":"Bulk export: exporting users"}
{"level":"info","ts":1581574230.8770578,"caller":"app/export.go:77","msg":"Bulk export: exporting posts"}
{"level":"info","ts":1581574234.826162,"caller":"app/export.go:82","msg":"Bulk export: exporting emoji"}
{"level":"info","ts":1581574234.8270447,"caller":"app/export.go:87","msg":"Bulk export: exporting direct channels"}
{"level":"info","ts":1581574234.8290977,"caller":"app/export.go:92","msg":"Bulk export: exporting direct posts"}       {"level":"info","ts":1581574234.8316784,"caller":"app/server.go:346","msg":"Stopping Server..."}
{"level":"info","ts":1581574234.8318102,"caller":"app/web_hub.go:125","msg":"stopping websocket hub connections"}      {"level":"warn","ts":1581574234.831849,"caller":"app/web_hub.go:130","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","ts":1581574234.8332984,"caller":"sqlstore/supplier.go:907","msg":"Closing SqlStore"}
{"level":"info","ts":1581574234.8336623,"caller":"app/server.go:384","msg":"Server stopped"}
```
No file.json was generated...
Any idea? Sorry I am not familiar with shell programming.

**Comment by lieut-data** [comment]
Yes, that's super helpful -- thanks @XD1234567!

**Comment by agnivade** [comment]
Hi @XD1234567 - I looked into this and indeed the posts can be missing. However, after an extensive [discussion](https://community-daily.mattermost.com/core/channels/developers-server/s1ab7695z3rqumsgsdsj91gp1h) with the team, we came to the conclusion that both our mobile and web clients heavily rely on this API, and they have their own logic to fill up any gaps in the post order. At this point, we don't know the risks of changing the API to return consecutive posts, as things might break silently.

So unfortunately, we have to call this "expected behavior" and I will be updating the documentation to reflect that shortly. There is a ticket filed with the mobile team(you can see it in the thread linked) to properly investigate this API's behavior and confirm what, if anything actually breaks if we change this.

I apologize for the inconvenience caused. And I fully agree that this should be fixed.

In the mean time, as a temporary workaround, I'll note that this only happens with the `since` parameter. The same API also supports `after` and `before` params which will return posts from a given reference postId, and that does not suffer from this problem.

**Comment by agnivade** [comment]
https://api.mattermost.com/#tag/posts/paths/~1channels~1{channel_id}~1posts/get is updated now. I will go ahead and close this.

**Comment by XD1234567** [comment]
@agnivade  Thanks for your and your team's  effort.I'm glad we find this problem anyway.
