### ISSUE TITLE
Team invite link doesn't open correct team on webclient

### ISSUE THREAD

**Issue by hekeli** [mattermost/mattermost-server#13883]
Using 5.17.3 team version.

When using team invite like this:
https://mattermost.foo/signup_user_complete/?id=teaminviteid

..and the user is prompted for login, and completes Gitlab OAuth (dunno if this matters for this issue), the browser web UI does not force focus/switch view to that team. Assume the user belongs to many teams, and is already a member in that too.

If the user was already logged in previously (session open in browser), and uses that same link, the correct team is always opened/focused on regardless of current view.

To me this is a bug since I believe the link should switch team view correctly whether logging in or not. As we have many of these team links in our intra, we often get questions "why the correct team doesn't open".

**Comment by amyblais** [comment]
@hekeli Would you be open to sharing more details about your environment here https://docs.mattermost.com/process/support.html#general-questions-for-any-issues along with reproduction steps and observed behaviour?

**Comment by amyblais** [comment]
I'll close this for now as we haven't received additional information for a while. Please re-open this issue if the problem persists with relevant additional information,
