### ISSUE TITLE
How to disable System notification on Channel when change member?

### ISSUE THREAD

**Issue by diahai** [mattermost/mattermost-server#13880]
Hi,
How can I disable notification when someone join to or remove from a channel.
Ex 1: @jimmy and 6 others were added to the channel by you.
Ex 2: @nancy and 2 others joined the channel.
Ex 3: @nicholas was removed from the team.

Thanks!

**Comment by amyblais** [comment]
@diahai System-wide, you can disable this setting for default channels: https://docs.mattermost.com/administration/config-settings.html#enable-default-channel-leave-join-system-messages.

For specific accounts, you can go to Main Menu > Account Settings > Advanced > Enable Join/Leave Messages > Off.

**Comment by amyblais** [comment]
We haven't received an updated for a while so I'll close this for now. Let me know if the above doesn't help,

**Comment by ike5** [comment]
The redirect link does not work.

**Comment by anx-ag** [comment]
Try this link: https://docs.mattermost.com/configure/experimental-configuration-settings.html#exp-enabledefaultchannelleavejoinmessages

**Comment by ike5** [comment]
> @diahai System-wide, you can disable this setting for default channels: https://docs.mattermost.com/administration/config-settings.html#enable-default-channel-leave-join-system-messages.
> 
> For specific accounts, you can go to Main Menu > Account Settings > Advanced > Enable Join/Leave Messages > Off.

Does this apply to all users if you are an admin?
