### ISSUE TITLE
Feature: Separate max file size for profile pictures from Maximum File Size config

### ISSUE THREAD

**Issue by checkaayush** [mattermost/mattermost-server#13903]
#### Summary
Maximum file size supported is 1000 MB for profile picture in account settings on commnuity hosted version. 

#### Steps to reproduce
1. Head over to community-release.mattermost.com.
2. Go to Account Settings > General Settings > Profile Picture
3. Message says maximum file size supported is 1000 MB.

#### Expected behavior
Maximum file size supported should be way less than 1000 MB.

#### Observed behavior (that appears unintentional) 
Maximum file size supported is 1000 MB.

#### Possible fixes
Separate the 2 values, at least for display purposes, to sane limits as per the use-case.

**Comment by amyblais** [comment]
I will close this for now as we haven't received feedback for this for a while, but I hope you will open a feature request issue for this!
