### ISSUE TITLE
make build Error

### ISSUE THREAD

**Issue by goodforever** [mattermost/mattermost-server#13907]
flag provided but not defined: -trimpath
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [build-linux] Error 2

**Comment by amyblais** [comment]
@goodforever Would you be open to joining our community server's Developer channel and asking about this there? See: https://community.mattermost.com/core/channels/developers. One of our developers or other community members should be able to help you.

**Comment by goodforever** [comment]
need update to go.1.13
