### ISSUE TITLE
Plugins won't start up

### ISSUE THREAD

**Issue by nicgentile** [mattermost/mattermost-server#13913]
#### Summary
Plugins won't start up 

#### Steps to reproduce
Noticed my Mattermost instance had died, logged in to restart it, and then got an error about plugins not working.

Last night before I ended work, it was running fine.

Version  5.19.1

#### Expected behavior
Plugis are supposed to work.

#### Observed behavior (that appears unintentional) 
Logged in today after noticing Mattermost was not running. When I started it, I got this error. Mattermost is running but plugin aren't.

{"level":"info","ts":1582016335.50474,"caller":"app/server.go:221","msg":"Printing current working","directory":"/opt/mattermost/bin"}
{"level":"info","ts":1582016335.5048149,"caller":"app/server.go:222","msg":"Loaded config","source":"file:///opt/mattermost/config/config.json"}
{"level":"info","ts":1582016335.5890172,"caller":"sqlstore/post_store.go:1351","msg":"Post.Message has size restrictions","max_characters":16383,"max_bytes":65535}
{"level":"info","ts":1582016335.596303,"caller":"mlog/log.go:166","msg":"Starting up plugins"}
{"level":"error","ts":1582016335.5964403,"caller":"app/plugin.go:151","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: no such file or directory"}
{"level":"info","ts":1582016335.7522671,"caller":"mlog/log.go:166","msg":"Starting up plugins"}
{"level":"error","ts":1582016335.7524264,"caller":"app/plugin.go:151","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: no such file or directory"}
{"level":"info","ts":1582016335.7559245,"caller":"jobs/workers.go:68","msg":"Starting workers"}
{"level":"info","ts":1582016335.7715344,"caller":"jobs/schedulers.go:74","msg":"Starting schedulers."}
{"level":"info","ts":1582016335.7912693,"caller":"app/web_hub.go:75","msg":"Starting websocket hubs","number_of_hubs":4}
{"level":"info","ts":1582016335.839121,"caller":"app/server.go:440","msg":"Starting Server..."}
{"level":"info","ts":1582016335.8398187,"caller":"app/server.go:506","msg":"Server is listening on [::]:8065"}
{"level":"error","ts":1582016337.5897057,"caller":"mlog/log.go:174","msg":"Plugins have been disabled. Please check your logs for details.","path":"/api/v4/plugins/webapp","request_id":"wubb1fe$
{"level":"error","ts":1582016598.0404346,"caller":"mlog/log.go:174","msg":"Plugins have been disabled. Please check your logs for details.","path":"/api/v4/plugins/webapp","request_id":"f87rrdc$
{"level":"error","ts":1582016606.13601,"caller":"mlog/log.go:174","msg":"Plugins have been disabled. Please check your logs for details.","path":"/api/v4/plugins","request_id":"coamoyxikf895ex5$
{"level":"error","ts":1582016614.0225697,"caller":"mlog/log.go:174","msg":"Plugins have been disabled. Please check your logs for details.","path":"/api/v4/plugins/statuses","request_id":"ay7f5$
{"level":"info","ts":1582016635.487013,"caller":"mlog/log.go:166","msg":"Starting up plugins"}
{"level":"error","ts":1582016635.4871387,"caller":"app/plugin.go:151","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: no such file or directory"}

#### Possible fixes
No idea.

**Comment by amyblais** [comment]
@nicgentile Would you be able to help try if re-enabling plugins fixes the issue?

**Comment by nicgentile** [comment]
No. This did not work.

But this did.

Changed  "ClientDirectory": ./client/plugins", to  "ClientDirectory": "/opt/mattermost/client/plugins", and it went back to normal.

**Comment by lieut-data** [comment]
@nicgentile, the server needs write access to `/opt/mattermost/client/plugins` to unpack any webapp-related resources. I wonder if your working directory changed between your normal server startup process and when you restarted it -- that would explain the inability to find `./client/plugins` and thus finish starting plugins.

Switching to an absolute path definitely avoids this problem, but the root cause of the original report is usually working directory related.

**Comment by MoonCactus** [comment]
Just to chime in: got the same errors and @lieut-data fix worked for me as well (specify the absolute path in the config.json). I really did nothing special to this instance of mattermost, it was just installed as I always do in `/opt/mattermost`.

As such the service is started with a regular `service mattermost start`. I quite understand why it would complain when the cwd is wrong, but the source of the problem may looked for upstream imho

Interestingly, the error did not prevent mattermost from running though, it just showed in my logs as  `{"level":"error","ts":1583226657.587722,"caller":"app/plugin.go:151","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: no such file or directory"}` (I do not use plugins actually)

**Comment by nicgentile** [comment]
Since this is fixed for me, closed. Hopefully the necessary fixes will be applied in the next release.
