### ISSUE TITLE
App window is blank after startup - needs to be restarted to display interface

### ISSUE THREAD

**Issue by tomicakorac** [mattermost/mattermost-server#13920]
#### Summary
If Mattermost App is set to auto-start when Windows starts, its window doesn't display interface or anything, it's just completely white. After restarting the app, it works fine.

#### Steps to reproduce
1. Install Mattermost app for Windows;
2. Set Mattermost app to start automatically when OS starts.

#### Expected behavior
App interface and content should be visible.

#### Observed behavior (that appears unintentional) 
App interface is completely white (apart from the top menu).

#### Possible fixes
Sorry, can't be of much help here.

**Comment by amyblais** [comment]
@tomicakorac What Windows version are you on? What Mattermost server version and desktop app versions are you on?

**Comment by Arsaell** [comment]
I encounter the same issue on linux (Debian 9 and Debian 10, Cinnamon DE). 
It can also be fixed by clicking on "Settings" in the notification bar applet (the settings panel appears fine), and then exiting the settings. The app then reloads as in normal startup, and works fine from there.

**Comment by tomicakorac** [comment]
Windows 10 Enterprise version: 1890; OS build: 17763.1039
I am not sure about the Mattermost server version, I don't think I have access to that. My desktop app version is 4.3.1.

Also, I apologise if I've posted the issue in the wrong repository, this is where I was redirected from the Mattermost website issue reporting tool.

**Comment by amyblais** [comment]
@tomicakorac @Arsaell Would you be open to testing if v4.4.0 fixes the issue? You can download it via https://mattermost.com/download/#mattermostApps.

**Comment by Arsaell** [comment]
The problem is the same with the updated version 4.4

**Comment by amyblais** [comment]
@tomicakorac Have you had a chance to test this on v4.4?

@Arsaell Would you be able to share your logs following these instructions: https://docs.mattermost.com/install/desktop.html#reporting-issues?

**Comment by tomicakorac** [comment]
@amyblais I have. I'm not still sure of the result. To give the context, I have a VPN (company computer), so after startup I need to enter a password to connect to the internet. By the time I do, Mattermost is already up and displays the 'can't find the server' error. However as soon as I connected, the interface reloaded. This looks promising.

I'll re-test without VPN as soon as I reach my office, probably tomorrow.

**Comment by tomicakorac** [comment]
@amyblais 4.4.0 seems to have resolved this issue for me. Thanks for the assistance. I am going to close this thread now. @Arsaell can you please open a new issue for Linux client if you still need assistance?
