### ISSUE TITLE
Unintended LDAP group sync with base dn missing

### ISSUE THREAD

**Issue by DVTrast** [mattermost/mattermost-server#13922]
#### Summary
The LDAP group sync is activated by itself(?!) and not successful due to missing base dn.

#### Steps to reproduce
Mattermost Server 5.18.1
Mattermost Server 5.19.0
Mattermost Server 5.20.1

Execute a ldap sync.

#### Expected behavior
No or a successful group sync.

#### Observed behavior (that appears unintentional) 
I can not tell where the Group sync is coming from. All options for that are disabled. Is that by default? The only thing which was activated is MFA.

Mattermost error: error retrieving ldap groups — LDAP Result Code 2 "Protocol Error": 
LDAP error: conn=170005 op=1 SRCH base="(null)" scope=2 filter="(|(objectClass=group)(objectClass=groupOfNames)(objectClass=groupOfUniqueNames))", invalid attribute request

The SRCH base is empty but should be filled. The does not know where to search. The user request instead is working because the SRCH base is not empty.

#### Possible fixes
Don´t have one.

**Comment by amyblais** [comment]
@DVTrast Our devs took a look and said that this sounds like a bug, but they doubt that it's coming from LDAP Group Sync, since that is definitely guarded by a configuration check. 

It would be great if you're able to share more details, including additional log info and configuration settings.

**Comment by sbishel** [comment]
Please obfuscate any sensitive information in the configuration file.

**Comment by DVTrast** [comment]
The config.json is original. Our settings are in the config.env file.

Here is our configuration and the log:

Environment-Configuration:

MM_LDAPSETTINGS_BASEDN='dc=gv,dc=at'
MM_LDAPSETTINGS_BINDPASSWORD='xxxxx'
MM_LDAPSETTINGS_BINDUSERNAME='USER'
MM_LDAPSETTINGS_CONNECTIONSECURITY='TLS'
MM_LDAPSETTINGS_EMAILATTRIBUTE='mail'
MM_LDAPSETTINGS_ENABLE=true
MM_LDAPSETTINGS_ENABLESYNC=true
MM_LDAPSETTINGS_FIRSTNAMEATTRIBUTE='givenName'
MM_LDAPSETTINGS_IDATTRIBUTE='uid'
MM_LDAPSETTINGS_LASTNAMEATTRIBUTE='sn'
MM_LDAPSETTINGS_LDAPPORT=636
MM_LDAPSETTINGS_LDAPSERVER='vgd.tirol.local'
MM_LDAPSETTINGS_LOGINIDATTRIBUTE='gvtirolemployeeid'
MM_LDAPSETTINGS_NICKNAMEATTRIBUTE='cn'
MM_LDAPSETTINGS_POSITIONATTRIBUTE='telephoneNumber'
MM_LDAPSETTINGS_SKIPCERTIFICATEVERIFICATION=true
MM_LDAPSETTINGS_USERFILTER='(&(gvStatus=active)(objectClass=gvOrgPerson))'
MM_LDAPSETTINGS_USERNAMEATTRIBUTE='gvTirolEmployeeId'


Mattermost-Log:

{"level":"info","ts":1582101432.420183,"caller":"mlog/log.go:166","msg":"LDAP Sync Phase","workername":"EnterpriseLdapSync","current_phase":"github.com/mattermost/mattermost-server/v5/enterprise/ldap.(*LdapSyncWorker).phase7GetLdapGroups-fm"}
{"level":"error","ts":1582101432.4470024,"caller":"mlog/log.go:174","msg":"Failed job","workername":"EnterpriseLdapSync","error":"LdapSession.getAllGroups: error retrieving ldap groups, LDAP Result Code 2 \"Protocol Error\": ","job_id":"8xptdhwh3i8ipr174cga7tnrpc"}


LDAP-Log:

vgd [26/Feb/2020:08:35:58.599595555 +0100] conn=247015 SRCH type=srch op=1 base="(null)" scope=2 filter="(|(objectClass=group)(objectClass=groupOfNames)(objectClass=groupOfUniqueNames))," attrs="d" RESULT op=1 err=2 errname=protocol_error tag=101 nentries=0 etime=0.0000089778 CONNECTION fd=4099 slot=4099 from=10.10.10.2 to=10.10.10.1 ssl=true binddn="USER" method=128 version=3 op=1

Do you need more?

**Comment by sbishel** [comment]
Could you turn on LDAP Tracing?
MM_LDAPSETTINGS_TRACE=true

I would be interested in the LDAP logs that appear after the line containing - 
`current_phase="github.com/mattermost/mattermost-server/v5/enterprise/ldap.(*LdapSyncWorker).phase7GetLdapGroups-fm" workername=EnterpriseLdapSync`

**Comment by DVTrast** [comment]
I turend on the LDAP tracing. Here is the log entry after the line which is mentioned in the command before:

Feb 27 08:26:50 server mattermost: {"level":"error","ts":1582788410.3669686,"caller":"mlog/log.go:174","msg":"Failed job","workername":"EnterpriseLdapSync","error":"LdapSession.getAllGroups: error retrieving ldap groups, LDAP Result Code 2 \"Protocol Error\": ","job_id":"d9naperzt3n58y43yftufmhp4w"}

**Comment by sbishel** [comment]
I'm looking for the lines that contain "ldap-trace".
{"level":"error","ts":1582817979.548556,"caller":"log/log.go:172","msg":"ldap-trace: LDAP Request: (Universal, Constructed, Sequence and Sequence of) Len=159 \"<nil>\"\n MessageID: (Universal, Primitive, Integer) Len=1 \"2\"\n Search Request: (Application, Constructed, 0x03) Len=153 \"<nil>\"\n Base DN: (Universal, Primitive, Octet String) Len=20 \"dc=mm,dc=test,dc=com\"\n Scope: (Universal, Primitive, Enumerated) Len=1 \"2\"\n Deref Aliases: (Universal, Primitive, Enumerated) Len=1 \"3\"\n Size Limit: (Universal, Primitive, Integer) Len=1 \"0\"\n Time Limit: (Universal, Primitive, Integer) Len=1 \"60\"\n Types Only: (Universal, Primitive, Boolean) Len=1 \"false\"\n Or: (Context, Constructed, 0x01) Len=86 \"<nil>\"\n Equality Match: (Context, Constructed, 0x03) Len=20 \"<nil>\"\n Attribute: (Universal, Primitive, Octet String) Len=11 \"objectClass\"\n Condition: (Universal, Primitive, Octet String) Len=5 \"group\"\n Equality Match: (Context, Constructed, 0x03) Len=27 \"<nil>\"\n Attribute: (Universal, Primitive, Octet String) Len=11 \"objectClass\"\n Condition: (Universal, Primitive, Octet String) Len=12 \"groupOfNames\"\n Equality Match: (Context, Constructed, 0x03) Len=33 \"<nil>\"\n Attribute: (Universal, Primitive, Octet String) Len=11 \"objectClass\"\n Condition: (Universal, Primitive, Octet String) Len=18 \"groupOfUniqueNames\"\n Attributes: (Universal, Constructed, Sequence and Sequence of) Len=26 \"<nil>\"\n Attribute: (Universal, Primitive, Octet String) Len=0 \"\"\n Attribute: (Universal, Primitive, Octet String) Len=0 \"\"\n Attribute: (Universal, Primitive, Octet String) Len=6 \"member\"\n Attribute: (Universal, Primitive, Octet String) Len=12 \"uniqueMember\"","source":"stdlog"}

**Comment by DVTrast** [comment]
In which log can I find the entry "ldap-trace"? We can´t find it.

**Comment by amyblais** [comment]
@DVTrast Do you mean that LDAP Group Sync is running even though you don't seem to have it configured on your instance under System Console > Groups (Beta)?

The ldap-trace should be in mattermost.log if you have the setting enabled.

**Comment by DVTrast** [comment]
Yes correct. Under System Console > Groups (Beta) we have no groups configured.

**Comment by amyblais** [comment]
@DVTrast Would you be open to enabling that setting? Please see https://docs.mattermost.com/deployment/ldap-group-sync.html#enabling-ad-ldap-group-synchronization.

**Comment by DVTrast** [comment]
@amyblais Thank you - the problem is solved.

**Comment by eni23** [comment]
We have the exact same issue, after an Upgrade from 5.9 LTS to 5.19 LTS LDAP sync is not working anymore. We cannot enable the group sync feature, what to do?
