### ISSUE TITLE
Centralize ID validation

### ISSUE THREAD

**Issue by mkraft** [mattermost/mattermost-server#13938]
ID validation is done using disparate code throughout the Mattermost server code. We would like the validation to be centralized to a single function or method. Any instance of `len(foo) != 26` (etc) should be replaced with the centralized function/method.

Note that there is an existing function `model.IsValidId` which could either be used or be the basis for the solution.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-22682

**Comment by RajatVaryani** [comment]
@mkraft I would like to work on it. Few thoughts/questions brewing in my mind

- The bigger problem we are trying to solve is of the visibility of the function. The natural place I look for such methods is in `validations.go` or something on similar lines. However many of the validations methods are in [utils](https://github.com/mattermost/mattermost-server/blob/master/model/utils.go) which is an [antipattern](https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common). I propose creating a validations.go in model package and moving the functions which seem apt.
- I can also replace the use of `!= 26` with `model.IsValidId`. I could find 98 matches across 39 files on a case by case basis.

Thoughts?

**Comment by mkraft** [comment]
@RajatVaryani Yes that sounds good as long as you can put the validations there without dependency cycles.

**Comment by RajatVaryani** [comment]
Folks, I won't be able to contribute. Please make it open to the public.

**Comment by shibasisp** [comment]
If no one is working on this, I would like to pick this up!

**Comment by hanzei** [comment]
Hi @shibasisp, just wanted to check if you have any questions about the ticket. Please let us know if you need any help

**Comment by shibasisp** [comment]
Apologies for the delay. Been stuck up in some personal work. Will try to wrap it up as soon as possible.
