### ISSUE TITLE
Return error in parseDSN func

### ISSUE THREAD

**Issue by upwell** [mattermost/mattermost-server#13931]
https://github.com/mattermost/mattermost-server/blob/17f2cd665dec34b96c8f980c0035d70b8f557109/config/database.go#L138-L144

I ran into this code snippet while checking error handling logic in mattermost-server. It looks like at L142, **an error is created but never handled or returned**. Is this by purpose or just a minor bug?

**Comment by ali-farooq0** [comment]
Good find @upwell! I believe that does look like a bug, that line should be returning an error. I believe that was updated as part of https://github.com/mattermost/mattermost-server/pull/12250/files

**Comment by ali-farooq0** [comment]
Turning this into a help-wanted issue. @upwell will you be up for working on this issue before i make it available to public?

**Comment by upwell** [comment]
@ali-farooq0  Sure. I will work out a PR for this issue. Returning the error could fix this issue.
