### ISSUE TITLE
Extend plugin API to get/update/delete user preferences

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13940]
Extend the plugin API with the following:

```go
GetPreferencesForUser(userId string) ([]model.Preference, *model.AppError)
UpdatePreferencesForUser(userId string, []model.Preference) *model.AppError
DeletePreferencesForUser(userId string, []model.Preference) *model.AppError
```

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-21307

**Comment by NassimBounouas** [comment]
Hi @lieut-data, I'm interested in working on this issue. I'll join the "Developers" community channel for my technical questions.

**Comment by lieut-data** [comment]
Thanks, @NassimBounouas!
