### ISSUE TITLE
Support different interactive message button styles on webapp

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-server#13952]
To improve [Slack compatibility](https://api.slack.com/docs/message-buttons), support a new `color` field to style interactive buttons. This ticket captures the work required in the webapp, with support for the mobile app already supported by [https://github.com/mattermost/mattermost-mobile/pull/3896](https://github.com/mattermost/mattermost-mobile/pull/3896) .

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-22734

**Comment by kosgrz** [comment]
I'd like to do it :)
