### ISSUE TITLE
mattermost aws sdk and AWS Identity and Access Management OpenID Connect (OIDC) serviceaccounts

### ISSUE THREAD

**Issue by neilharris123** [mattermost/mattermost-server#13953]
I've been trying to authenticate to s3 storage via a EKS serviceaccount created via eksctl with the [OIDC feature ](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html)without success. 

I discovered that its only possible to use these service accounts with certain SDKs as described [here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html), and listed below:

Java (Version 2) — 2.10.11
Java — 1.11.704
Go — 1.23.13
Python (Boto3) — 1.9.220
Python (botocore) — 1.12.200
AWS CLI — 1.16.232
Node — 2.521.0
Ruby — 2.11.345
C++ — 1.7.174
.NET — 3.3.652.1
PHP — 3.110.7

From what I gather, mattermost uses MinIO SDK to interact with AWS S3 storage. 

As this doesn't appear to be supported, this will make it impossible to use serviceaccount created though this method with mattermost and S3 as the storage source. 

Is there anyway of getting around this, or is there any plans to use a different SDK in the future?

**Comment by amyblais** [comment]
@neilharris123 Would you be open to posting this in the troubleshooting forum in case others have seen this issue: https://forum.mattermost.org/?

Other option is that you could join our [community server's Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) and one of our community members may be familiar with this issue.

**Comment by rrey** [comment]
Hi ! I'm having the same issue, is there any place in the forum that this issue was solved ?

**Comment by amyblais** [comment]
I'm cleaning up some older issues. If you need further assistance on this, I recommend reaching out to our devs / community via https://forum.mattermost.com/ or via our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help).
