### ISSUE TITLE
Cannot close DM with myself

### ISSUE THREAD

**Issue by NOP64** [mattermost/mattermost-server#13951]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
I cannot close a direct message that I have started with only myself.

#### Steps to reproduce
1. Press "+" near `Direct Messages`.
2. Enter only your own user name.
3. Chat.
4. Close by trying to press `X` next to your name in the DM list.

Happens on desktop app v4.3.1.3679 (community-daily) and Chrome-based browser (community). Chromium v80.0.3987.87

#### Expected behavior
DM to be dismissed.

#### Observed behavior (that appears unintentional) 
It goes away but the conversation comes back. No visible error messages.

#### Possible fixes
unknown
![DM-close](https://user-images.githubusercontent.com/20288229/75456065-0f740300-5948-11ea-99c0-8df99377afea.gif)

**Comment by amyblais** [comment]
@NOP64 Are you able to close it after switching to another channel?

**Comment by amyblais** [comment]
Actually I opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-22740.
