### ISSUE TITLE
Environment variables for nested dictionary values in config.json do not work

### ISSUE THREAD

**Issue by neilharris123** [mattermost/mattermost-server#13963]
I've been trying to add Mattermost environment variables for values in the "PluginSettings" section of the config.json file. 
For example, in the following example, if I wanted to add a variable for encryptionkey so that it overrides the value in config.json, according to the logic in the documentation, I would need to add and environment variable with the name MM_PLUGINSETTINGS_PLUGINS_GITHUB_ENCRYPTIONKEY . 

```
"PluginSettings": {
    ...
    "Plugins": {
        "github": {
            "encryptionkey": "<your encryption key>",
            "githuboauthclientid": "<your oauth client id>",
            "githuboauthclientsecret": "<your oauth client secrete",
            "githuborg": "<your github org>"
            "webhooksecret": "<your webhook secret>"
        },
    ...
    "PluginStates": {
        ...
        "github": {
            "Enable": true
        },
        ...
    }
},
```
However, this doesn't work. The variable is passed to the container, but it has no affect on the actual configuration. This is the same if I try to create a variable for any of these nested keys. 

Is this a limitation with the capabilities of Mattermost? The ability to do this is vital, because, without it, sensitive data would need to be added to the config.json file, and this isn't a good practice.

**Comment by lieut-data** [comment]
Hi @neilharris123! Unfortunately, this is indeed a known limitation, and I agree it prevents best practices here. I thought we had a ticket tracking this, but couldn't find one, so created https://mattermost.atlassian.net/browse/MM-22831.
