### ISSUE TITLE
Plugin Marketplace API does not pass `page`, `per_page`, and `server_version` query parameters to Mattermost Marketplace service API

### ISSUE THREAD

**Issue by teyotan** [mattermost/mattermost-server#13964]
#### Summary
Plugin Marketplace API does not pass `page`, `per_page`, and `server_version` query parameters to Mattermost Marketplace service API.

#### Steps to reproduce
Hit GET method for Plugin Marketplace API (/api/v4/plugins/marketplace) with varying `page`, `per_page`, and `server_version` query parameters, and the result won't change.

#### Expected behavior
Mattermost Server version: v5.20.0
The API should return the result according to given query params. Examples:
1. Given per_page is 5, the result should give at most 5 plugins.
2. Given per_page is 3 and page is 1, the result should be different when given per_page is 3 and page is 2.
3. Given server_version is 5.16.0, the API should return only plugins that is compatible with mattermost server version 5.16.0.

#### Observed behavior (that appears unintentional) 
These query params seems just ignored by the server. The MarketplacePluginFilter type has all these params coded, so I reckon that this is an unintentional behavior.

#### Possible fixes
I think `mattermost-server/app/plugin.go line 516` is the one responsible for this behavior. Instead of sending all params from the request, it sends a hard coded MarketplacePluginFilter

```
mattermost-server/app/plugin.go
line: 516

	// Fetch all plugins from marketplace.
	marketplacePlugins, err := marketplaceClient.GetPlugins(&model.MarketplacePluginFilter{
		PerPage:       -1,
		ServerVersion: model.CurrentVersion,
	})
```

If this is a valid issue, mind if I do this? I found this issue when working on https://github.com/mattermost/mattermost-server/issues/13899. Many thanks!

**Comment by amyblais** [comment]
@ali-farooq0 Do you know if this is a bug and if we can turn this into a Help Wanted?

**Comment by lieut-data** [comment]
@teyotan, thanks for the report! At this point in time, the behaviour is intentional: while the marketplace API supports paging, we intentionally fetch the entire set of plugins and page internally given the need to merge locally installed plugins and support our own paging strategy for results we display in the webapp.

We made the marketplace flexible enough to support other types of clients, but aren't currently relying on that behaviour in the server.
