### ISSUE TITLE
Where is the implementation of the ElasticsearchInterface class

### ISSUE THREAD

**Issue by nfjava** [mattermost/mattermost-server#13977]
Mattermost is a particularly good software, I am learning the implementation inside, I did not find the implementation of the ElasticsearchInterface class in the source code, may I ask where this is?

![image](https://user-images.githubusercontent.com/6111534/75741465-9ad50600-5d45-11ea-90d6-f1f61abffb12.png)

**Comment by agnivade** [comment]
Hello @nfjava, unfortunately the implementation is not in our open-source version. It's in our enterprise layer.

**Comment by nfjava** [comment]
I see， thank you very much.
