### ISSUE TITLE
Not able to edit messages 

### ISSUE THREAD

**Issue by pallavisontakke** [mattermost/mattermost-server#13970]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Not able to edit messages 

#### Steps to reproduce
Version:
Mattermost Version: 5.19.1
Database Schema Version: 5.19.0
Database: postgres

When I add a comment , I can see it fine on mattermost. However, I can't edit it. Edit button is seen, but after editing , I can't click the Save button.

#### Expected behavior
Ability to edit message was there till a few days back.

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/13624181/75651979-f5a42a00-5c7f-11ea-806a-940ecc546764.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by pallavisontakke** [comment]
My OS is macOS Catalina , Version 10.15.2

**Comment by amyblais** [comment]
@pallavisontakke Do you see any Mattermost log errors or any console errors?

**Comment by pallavisontakke** [comment]
This issue got fixed when I upgraded to the recent version 4.4
