### ISSUE TITLE
Guest invite fails due to upper case in email

### ISSUE THREAD

**Issue by torgeirl** [mattermost/mattermost-server#13972]
#### Summary
Guest invite to team fails without further explanation if the guest's email contains upper case letters.

#### Steps to reproduce
Try to add a guest to a team with an email address containing at least one upper case letter.

#### Expected behavior
Either the casing to be ignored, or at least a message asking the email to be all lower case.

#### Possible fixes
Case sensitivity seems to be a wider problem for the platform (some examples: issues #3062 and #3349). Email addresses are inherently case-insensitive (upper case is purely a readability-future), and should be treated that way. `JohnDoe`, `johndoe` and `JOHNdoe` should all the treated the same. For some services such as Gmail, even `john.doe` would be treated the same.

As an absolute minimum, the user experience of running into Mattermost's limited case sensitivity support should be understandable error messages that explain that the input in question needs to be provided in lower case.

**Comment by amyblais** [comment]
This is scheduled for v5.21 release: https://mattermost.atlassian.net/browse/MM-22037.
