### ISSUE TITLE
admin invite user to team but member not seen team (redirect to this page /select_team )

### ISSUE THREAD

**Issue by PhilippeAccorsi** [mattermost/mattermost-server#13973]
#### Summary

We have migrate from Mattermost 5.0 to 5.20.1 and when I invite user in my team, the user create his account and after that when he try to connect on my team, he seen all channel (2sec) and after that the page ` https://im.algoo.fr/select_team` and its just possible to create new team. If he click on back link (in top left of the page), login page is show 1sec and url come back here.

Admin can add this member in all private channel (so member exist on this team) but member can't access.

#### Steps to reproduce

Version de Mattermost : 5.20.1
Version du schéma de la base de données : 5.20.0
Base de données : postgres

To reproduce:
- invite user on team whis link like this `https://<mattermost_url>/signup_user_complete/?id=qso4x6wf6byp3qh79n36oai6gh`

#### Observed behavior (that appears unintentional) 

No error visible, user seen team page 2second and after that redirect is make to this url `https://<mattermost_url>/select_team`

**Comment by PhilippeAccorsi** [comment]
The member receive notification and after click on link, mattermost seem to be working. I don't understund what is going on (I have lost 2h to try restarting service, delete and recreate user, etc.).
If you don't have an idea about this bug you can close this issue.

**Comment by amyblais** [comment]
@philippe-granet 

1. Is the team a public or a private team, or are there any domain restrictions?
You can check via "Team Settings > Allow anyone to join this team" and "Team Settings > Allow only users with a specific email domain to join this team". 

2. Does the team have space for additional users? You can check via https://docs.mattermost.com/administration/config-settings.html#max-users-per-team

**Comment by amyblais** [comment]
@PhilippeAccorsi ^ Sorry, at-mentioned a wrong user in my previous message.

**Comment by PhilippeAccorsi** [comment]
> @philippe-granet
> 
>     1. Is the team a public or a private team, or are there any domain restrictions?
>        You can check via "Team Settings > Allow anyone to join this team" and "Team Settings > Allow only users with a specific email domain to join this team".
> 
Team is available for all user whis account on us instance of mattermost, and we have no domain verification.

>     2. Does the team have space for additional users? You can check via https://docs.mattermost.com/administration/config-settings.html#max-users-per-team

We just have 40 users but yesterday I change parameter to 500 (in console).

Today, when member try to access, problem appear again. But the member can access to the team if he use url like this `https://<mattermost_url>/landing#/algoo/`


All channel are private. Before upgrading to 5.20.1, we have added one user without any problem.

**Comment by PhilippeAccorsi** [comment]
I see some other problem with my team. I can remove user from my team but after that Its impossible to add again this member on my team. No option permit to invite again. I don't see any option for an administrator to add member on team. 

Maybe something going wrong when I have updated mattermost from 5.0 to 5.20.1 ?  Or missing something when upgrade?

**Comment by stefaneidelloth** [comment]
We also had issues with invitation links. Don't know if its due to server or desktop app. As a workaround I could manually add new colleagues to the teams (Team Menu => Invite People => Invite People).

**Comment by amyblais** [comment]
@PhilippeAccorsi If all the channels are private, does that user have access to those channels?

**Comment by PhilippeAccorsi** [comment]
> @PhilippeAccorsi If all the channels are private, does that user have access to those channels?

Yes after adding user in channel. But user can access to mattermost just if he used link available from email notification. Its not possible to use url like 40 other user used.


I have tested to invite another user (me for testing) in my team and its a same issue. All new user can't access correctly.

**Comment by amyblais** [comment]
@PhilippeAccorsi There are no server log errors or console errors?

**Comment by PhilippeAccorsi** [comment]
We have tested connection from login page and I can see that for this user in log of server
~~~
{"level":"error","ts":1583227905.361703,"caller":"mlog/log.go:175","msg":"You do not have the appropriate permissions","path":"/api/v4/users/autocomplete","request_id":"huu358ingbgyfe3m5k3x9s87ky","ip_addr":"x.x.x.x","user_id":"ipj1dji74ifpmpdp4brntzzb7o","method":"GET","err_where":"Permissions","http_code":403,"err_details":"userId=ipj1dji74ifpmpdp4brntzzb7o, permission=read_channel"}
~~~

And in web page we seen that :
~~~
GET /api/v4/teams/wd4rj65hnfbjdmrgbktabzcbrc/channels/name/town-square?include_deleted=true HTTP/1.1
Host: x.X.x
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: /
Accept-Language: fr
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
DNT: 1
Connection: keep-alive
Cookie: MMAUTHTOKEN=e1r7789so78exeawm6cduhmtca; MMUSERID=ipj1dji74ifpmpdp4brntzzb7o; MMCSRF=ua1opb7rkpgqtykbudbwszrhor
~~~

~~~
HTTP/1.1 404 Not Found
Server: nginx
Date: Tue, 03 Mar 2020 15:56:43 GMT
Content-Type: application/json
Content-Length: 170
Connection: keep-alive
Expires: 0
Vary: Accept-Encoding
X-Request-Id: hx9ad5eprpg3tkus1tpawom8qy
X-Version-Id: 5.20.0.5.20.1.995cf7d47308008908f3f315e4f9bdfd.false

{"id":"store.sql_channel.get_by_name.missing.app_error","message":"Le canal n'existe pas","detailed_error":"","request_id":"hx9ad5eprpg3tkus1tpawom8qy","status_code":404}
~~~

When user is connected in one firefox tab, if he open new tab and just give url https://<mattermost_url> connection not working but if he write https://<mattermost_url>/algoo its work.

But for other people giving https://<mattermost_url> make direct redirection to https://<mattermost_url>/algoo/channels/town-square  (I not seen new user in town-square, and I can add user in this private channel. Thats working before upgrade).

**Comment by PhilippeAccorsi** [comment]
I have also tested `./mattermost integrity --verbose` but I don't understund result and if its good or not. For exemple: `Found 147 records in relation Channels orphans of relation Teams` and 
~~~
Found 2 records in relation Status orphans of relation Users
  Child is missing Parent 5iq9efff8brh5qp1189p3i49xa (Status.UserId)
  Child is missing Parent adzbeta7xjdndbg3wtafsits9r (Status.UserId)
~~~

**Comment by PhilippeAccorsi** [comment]
I think the issue is just because new user is not added to Town Sqaure (default channel), and I can't add member in this channel and I not seen where I can defined another default channel or just not activate this channel.

So when user try to login, mattermost try to open this channel, and its not possible because user is not member of this channel. So mettermost not permit to join the team directly. 

So what command can I used to add member in this channel? (I don't find any command to make this).

**Comment by PhilippeAccorsi** [comment]
I have find to add member in Town Square with this command `./mattermost channel add algoo:town-square <user_email>@algoo.fr <user_name>`, after this command Town Square says 12 member in this channel but if I count manually I seen 13 member in list of member. I think something going wrong with this channel.

**Comment by PhilippeAccorsi** [comment]
I have find an error since last update of mattermost. Service used by systemctl used platform instead of mattermost. I have changing this and now I can seen correct number of user in Town Square. So I need to make more test to be sure all working good now.

In upgrade documentation, I not have seen information about changing platform to mattermost in service config. (When I have installed mattermost I have create this `sudo touch /lib/systemd/system/mattermost.service`, visible in documentation).

**Comment by PhilippeAccorsi** [comment]
So its not working (to invite new user in my team). I have tested in same time to add ExperimentalDefaultChannels with public channel => not working
User can access to this channel with `https://<mattermost_url>/algoo/channels/bac-a-sable` but without this explicit path, mattermost try to go in Town Square channel and just show message about no team available for user.

I don't have more idea.

**Comment by amyblais** [comment]
@PhilippeAccorsi Have you had a chance to read through all the upgrade notes between v5.0 - 5.20 release https://docs.mattermost.com/administration/important-upgrade-notes.html? For example, it explains the move from platform binary to mattermost binary.

**Comment by PhilippeAccorsi** [comment]
You are right, I have read this documentation many time but I have not understand correctly information about systemd :(

Today, the user can access directly on mattermost instance and to Town Square since I have added user manually in town square yesterday. So I need to test again to invite new user in mattermost to see if its working correctly or not.

**Comment by amyblais** [comment]
Closing as this is an old issue, but feel free to re-open if it still reproduces,
