### ISSUE TITLE
Interactive messages do not work in direct messages

### ISSUE THREAD

**Issue by dansmithy** [mattermost/mattermost-server#13980]
#### Summary
Interactive messages do not work in direct messages.

Note: This issue looks similar: https://github.com/mattermost/mattermost-server/issues/10688

#### Steps to reproduce
* Using version 5.18.0
* Use the REST API to post a direct message to a known user that contains an interactive element (either button or menu). This works. Example payload in JSON format:

```json
{
 "channel_id": "{THE DIRECT CHANNEL ID}",
 "props": {
           "attachments": [
                           {
                            "actions": [
                                        {
                                         "name": "Click me",
                                         "integration": {
                                                         "url": "http://host.docker.internal:8080/mattermost",
                                                         "context": {
                                                                     "message": "Context message"
                                                                     }
                                                         }
                                         }
                                        ],
                            "text": "A button to click"
                            }
                           ]
           }
 }
```

* Using the webapp (or mobile app) as the known user, click on the interactive element.

#### Expected behavior
* From the point of view of the webapp user, I expect the button to work
* From the point of view of an integration developer, I expect my integration to receive a payload from Mattermost, just as it does if the interactive message was posted in a channel.
* Alternatively, if interactive messages are unsupported in direct messages, I would have expected my message post to fail, reporting back that interactive elements are not permitted.

#### Observed behavior (that appears unintentional) 
* My integration does not receive any payload on the endpoint associated with the action.
* From the point of view of the webapp user, nothing happens. 
* Looking at Chrome dev tools, I can see that the webapp posted to `http://localhost:8065/api/v4/posts/zcrco8hbppbutgyazoahngfgca/actions/tiprgoyh53fj3edmfi6q3thkye` and get back a response like this:

```
{"id":"store.sql_team.get.find.app_error","message":"Unable to find the existing team","detailed_error":"","request_id":"s3tbgf44cfb7dyszioobwa63yh","status_code":404}
```

#### Possible fixes
Not looked at the code.

**Comment by hanzei** [comment]
Hi @dansmithy,

Thanks for the report. Could you double check that you are using 5.18? We fixed exactly this issue with https://github.com/mattermost/mattermost-server/pull/13248. Otherwise, could you please update to 5.20 and check again?

**Comment by dansmithy** [comment]
@hanzei Yes, using 5.18. Is 5.20 available as a Docker image? I was running the docker-preview build. Not sure how best to run 5.20, so grateful for any pointers.

**Comment by dansmithy** [comment]
@hanzei It does using with version 5.19.

Have managed to test and believe it is working correctly: payload arrives with an empty string for `team_id` and `team_domain`, but that makes sense given the context.

Thanks for getting back. Closing issue.
