### ISSUE TITLE
Find desktop / mobile version run by users connected to the server

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#13981]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary

A view or similar in the admin side to find the desktop app version, mobile app version run by the user connected to mattermost would be very welcome, certain users may be running outdated versions which might hamper their experience and/or security related issues may pop up in the long run. 

I know mattermost has a certain app-version requirement, but it would be good to have a view in the admin side, so that the admin can communicate the same to the users to update their software.

I understand this may be more of a feature request but I think it could be a good addition to improve user experience (for example, the Desktop 4.4.0 app / UI is very good compared to the previous versions)

#### Steps to reproduce
N/A

#### Expected behavior

Maybe under Manage Users --> a small line or 2 would appear for Last Seen Desktop App Version and Last Seen Mobile App Version

#### Observed behavior (that appears unintentional) 

N/A

#### Possible fixes

Maybe under Manage Users --> a small line or 2 would appear for Last Seen Desktop App Version and Last Seen Mobile App Version

**Comment by amyblais** [comment]
Thanks for bringing this up and this makes sense!
We have a ticket open here to address this https://mattermost.atlassian.net/browse/MM-21602.

**Comment by amyblais** [comment]
This was done via https://github.com/mattermost/mattermost-mobile/pull/4488.
