### ISSUE TITLE
Document sql store 'SqlTeamStore' methods (Task 1)

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-server#13995]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-22994)
    
We want to improve our internal API documentation using godoc to ease the
development process for everybody.

This `Help Wanted` issue is to add the documentation to the following methods
(file: [store/sqlstore/team_store.go](https://github.com/mattermost/mattermost-server/tree/master/store/sqlstore/team_store.go)):

- SqlTeamStore.Save
- SqlTeamStore.Update
- SqlTeamStore.SaveMember
- SqlTeamStore.UpdateMember

An example of already migrated methods can be found here:

- https://github.com/mattermost/mattermost-server/pull/13896

**Comment by abdulsmapara** [comment]
I am interested in learning to add documentation using godoc and complete this task.

**Comment by jespino** [comment]
Awesome! thanks @abdulsmapara! :tada:
