### ISSUE TITLE
Application hides behind the taskbar upon minimize to maximize with a left window taskbar.

### ISSUE THREAD

**Issue by Jeffreyjelly** [mattermost/mattermost-server#14024]
1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
-doesn't exist
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
-doesn't involve

#### Summary
Features get hidden behind a left mounted windows task bar.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
(4.4.0) Set the task bar to be docked on the left side of your window with windows 10 and proceed to minimize and re-expand the mattermost window.

#### Expected behavior
The server options and 3 dot menu is hidden behind the task bar upon the window changing it's location automatically.

#### Observed behavior (that appears unintentional) 
See steps to produce.

#### Possible fixes
N/A

**Comment by amyblais** [comment]
@Jeffreyjelly Would you be open to re-opening this in the desktop app repo https://github.com/mattermost/desktop/issues?

Also if you can include what server version you're on and any screenshots.

**Comment by Jeffreyjelly** [comment]
yeah, I just noticed it was in the wrong location. will do.

**Comment by Jeffreyjelly** [comment]
moved to https://github.com/mattermost/desktop/issues/1228
