### ISSUE TITLE
Pasting some images in Firefox also adds the file as random text

### ISSUE THREAD

**Issue by Selion05** [mattermost/mattermost-server#14027]
#### Summary
Pasting an image also adds the file as text in firefox

#### Steps to reproduce
Mattermost Version: 5.20.1
OS: Manjaro 19.0.2 Kyria
Kernel: x86_64 Linux 5.5.7-1-MANJARO
firefox: Mozilla Firefox 73.0.1

Paste an image in firefox (chrome works)

e.g I use  a script for screenshots
```
#!/usr/bin/env sh
FN=/tmp/scrot.png
scrot -s $FN && xclip -sel clip -t image/png -i $FN && rm $FN
```

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/21970846/76209068-4926f280-6201-11ea-82cf-c8a9b4424e08.png)

**Comment by amyblais** [comment]
@Selion05 Does this only happen when you use a script? Does this happen with all file types?

**Comment by Selion05** [comment]
okay this seems trickier then I thought... 

> Does this only happen when you use a script?
If I copy a file with a file manager I just get the file path. E.g. in  

nautilus:

```
x-special/nautilus-clipboard
copy
file:///home/leo/test.jpg
```
thunar: 

`/home/leo/test.jpg`

but this is "normal".
> Does this happen with all file types?

Since you can also paste files on github I test it here as well as comparison. 


## png
`xclip -sel clip -t image/png -i test.png`
|                    | Firefox    | Chrome  |
| --------------- |-------------| -------------|
| mattermost | garbage and file | file |
| github         | file           |  file |


## jpg
`xclip -sel clip -t image/jpeg -i test.jpg`
|                    | Firefox    | Chrome  |
| --------------- |-------------| -------------|
| mattermost | garbage | nothing |
| github         | garbage    |  nothing |


## plain text file
`xclip -sel clip -t text/plain -i test.txt`
|                    | Firefox    | Chrome  |
| --------------- |-------------| -------------|
| mattermost |  file content  |  file content  |
| github         | file content    |   file content 

## files
[test.txt](https://github.com/mattermost/mattermost-server/files/4342715/test.txt)
![test](https://user-images.githubusercontent.com/21970846/76844694-f4592c80-683d-11ea-9ed1-9fe74968ef3e.png)
![test](https://user-images.githubusercontent.com/21970846/76844710-fb803a80-683d-11ea-8038-56b9f95111d1.jpg)

**Comment by fawick** [comment]
I am experiencing the same issue.

Firefox 74.0 and Mattermost 5.21.0.

A workaround for me is to paste the clipboard into Gimp first, then copy it again from there. Pasting that second clipboard picture works in Firefox, then. I reckon that the content-type of whatever Gimp is putting into the clipboard is different to 'image/png'.

So, I wonder, is there some difference in the content-handling for 'image/png' in the Mattermost front-end code between Firefox and Chrome?

**Comment by amyblais** [comment]
Thanks all, opened a ticket here: https://mattermost.atlassian.net/browse/MM-23516.

**Comment by esethna** [comment]
@fawick @Selion05 would either of you be open to submitting a fix for this? We're opening this as Help Wanted

**Comment by fawick** [comment]
I'd love to but I wouldn't even know where to start. I'd be glad to take some pointer, though.

**Comment by fawick** [comment]
@esethna Would you be able to provide some info in which source files / functions I should start too look? As a absolute newbie to the Mattermost code base and with close to none Javascript / front-end experience the entry barrier is pretty large.

**Comment by esethna** [comment]
@fawick feel free to ask for some guidance in our contributors channel: https://community-daily.mattermost.com/core/channels/tickets

**Comment by luryus** [comment]
This issue still seems to be unresolved. I could try to fix this!
