### ISSUE TITLE
Permalink in private chat while in a team that someone doesn't have access to doesn't allow them to click the permalink

### ISSUE THREAD

**Issue by Jeffreyjelly** [mattermost/mattermost-server#14035]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Permalinks to private chats shouldn't be team specific.

Originally opened on https://github.com/mattermost/desktop/issues/1230

#### Steps to reproduce
Permalink a private chat in a private chat while in a group someone doesn't have access to and send it to them and they can't use the permalink.

#### Expected behavior
Permalinks to private chats shouldn't be team specific.

#### Observed behavior (that appears unintentional) 

![](https://user-images.githubusercontent.com/4224835/76102346-df5ade80-5f9d-11ea-8b08-cee1175d880c.png)

#### Possible fixes
N/A

**Comment by amyblais** [comment]
We have a ticket open for this here: https://mattermost.atlassian.net/browse/MM-22476.

**Comment by amyblais** [comment]
This is fixed for upcoming v5.23 release,
