### ISSUE TITLE
Desktop notifications not working in Windows 10

### ISSUE THREAD

**Issue by bpauquette** [mattermost/mattermost-server#14041]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Desktop notifications not working in Windows 10 using google chrome. 

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Mattermost Version: 5.19.0
Database Schema Version: 5.19.0
Database: postgres

#### Expected behavior
When my name or any of the keywords mentioned in my account settings are prefaced with the 
@ character I expect a desktop notification.

#### Observed behavior (that appears unintentional) 
I requested a team member to mention my name in a thread and no desktop notification appeared

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@bpauquette Would you be open to re-opening this issue in the desktop repo https://github.com/mattermost/desktop/issues?
Also, please add details about your desktop app version.

**Comment by amyblais** [comment]
We haven't received an update for a while, so I'll close this for now. Please re-open this issue on the desktop app repo if the issue persists on the latest desktop app version (v4.4.0).
