### ISSUE TITLE
5.21.0 won't build without makefile patch

### ISSUE THREAD

**Issue by alerque** [mattermost/mattermost-server#14052]
Testing the recently tagged 5.21.0 release I'm having trouble building normally.

```
Cleaning
rm -Rf dist
go clean  -mod=vendor -i ./...
go: inconsistent vendoring in /home/caleb/projects/aur/mattermost/src/src/github.com/mattermost/mattermost-server:
        go.uber.org/atomic@v1.5.1: is explicitly required in go.mod, but vendor/modules.txt indicates go.uber.org/atomic@v1.4.0
        go.uber.org/multierr@v1.4.0: is explicitly required in go.mod, but vendor/modules.txt indicates go.uber.org/multierr@v1.2.0
        go.uber.org/zap@v1.13.0: is explicitly required in go.mod, but vendor/modules.txt indicates go.uber.org/zap@v1.10.0
        golang.org/x/image@v0.0.0-20200119044424-58c23975cae1: is explicitly required in go.mod, but vendor/modules.txt indicates golang.org/x/image@v0.0.0-20190910094157-69e4b8554b2a
        golang.org/x/net@v0.0.0-20200114155413-6afb5195e5aa: is explicitly required in go.mod, but vendor/modules.txt indicates golang.org/x/net@v0.0.0-20191119073136-fc4aabc6c914
        golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9: is explicitly required in go.mod, but vendor/modules.txt indicates golang.org/x/sys@v0.0.0-20191002091554-b397fe3ad8ed

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
```

I gather the build wants something like this (but just this simple start this doesn't actually build):

```patch
--- Makefile    2019-12-28 12:38:41.471311251 +0100
+++ Makefile.new    2019-12-28 12:41:37.194305874 +0100
@@ -48,8 +48,8 @@
 # Golang Flags
 export GO111MODULE=on
 GOPATH ?= $(shell go env GOPATH)
-GOFLAGS ?= $(GOFLAGS:) -mod=vendor
+GOFLAGS ?= $(GOFLAGS:) -mod=mod
 GO=go
 DELVE=dlv
 LDFLAGS += -X "github.com/mattermost/mattermost-server/v5/model.BuildNumber=$(BUILD_NUMBER)"
```

Is this something than needs to be fixed in the packaging or is there a perhaps a caching problem with go having stashed something with builds from previous versions?

**Comment by agnivade** [comment]
This is a new feature with Go 1.14 that verifies the modules.txt in vendor mode. Can you try with master ? I remember fixing this.

**Comment by alerque** [comment]
@agnivade Maybe, I'll give it a shot.

**Comment by amyblais** [comment]
@agnivade Do we know if this is something concerning that also needs to be fixed for v5.21? Is there a PR / Jira ticket I can reference?

**Comment by alerque** [comment]
@agnivade It seems like I can build `master` normally, so yes this got fixed somewhere between the 5.21.0 tag and `HEAD`.

Might I suggest an urgent dot-release to account for this? It's going to be a blocker for Arch Linux packaging (which is what I was working on when I bumped into this) or at least require backporting whatever patches fixed it in order to release 5.21.

**Comment by agnivade** [comment]
I didn't realise Arch Linux has their own packaging for Mattermost. Is it a strict policy to build it always with the latest Go release ? FWIW, we haven't shifted our build pipelines to use 1.14 yet. Normal users can anyways get the 5.21 release from our servers.

In any case, I will leave the backport decision to @amyblais.

**Comment by alerque** [comment]
@agnivade Arch Linux has had [packaging for Mattermost in AUR](https://aur.archlinux.org/packages/mattermost/) (Arch User Repository) since 0.6.0 and I would wager it is far more common to use this packaging that the "standard" upstream releases. There has been talk for a while now about moving it into the pre-built [community] package repository but that has been held up on some small issues.

Yes it is a strict policy to build with the latest Go :wink:! Arch is a rolling release and that's the only version of Go currently available. I think you'll also find this affects a number of other distros (Gentoo, OpenSUSE, Alpine, Nix, etc.).

Personally I think it's a mistake to think of people who use distro packages as "abnormal" users. In the Linux world normal users are those who reach for their distro packages first. Ubuntu's super long release cycles and locked versions of old packages has been pushing a lot of people away from that, but most other distros encourage native packages. If anything making sure things work for distro packagers would be the best way to ensure the most adoption and ease of use for normal end users.

**Comment by agnivade** [comment]
Thanks for the info ! Sorry if I implied users of distro packages as "abnormal", that wasn't my intention :) That is something I am very passionate about. From my knowledge of https://github.com/mattermost/mattermost-server/issues/4176, I just assumed that there was no distro packaging anywhere. Pardon my ignorance.

**Comment by alerque** [comment]
@agnivade Roger that.

Arch & Debian kind of come at this from opposite ends. The Debian philosophy is typically to cater to the _lowest_ common denominator. This gets aggravated even farther in Ubuntu because it is technically downstream of Debian plus they have LTS cycles. The net effect cat be some staggeringly old libraries that don't get updating because they would break some other old software that's also held back because some other app can't handle newer libraries.

Upshot: new software or things under heavy development is often hard to get packaged.

Rolling releases (Arch, PLD, Gentoo, OpenSUSE Tumbleweed) cater to to the _highest_ common denominator. As long as a basic core set of packages required to boot and run don't break, new libraries are typically packaged soon after they are released.

Upshot: It's really easy to use new software, but some old projects that don't keep pace can eventually be kicked to the curb because it becomes too much of a burden to patch them to work with new libraries.

Different strokes ... as a software project unfortunately you have both problems to deal with.

**Comment by alerque** [comment]
@agnivade On the subject of "no distro packaging anywhere", Arch is not even the only distro with packaging. You can find a partial list on [repology](https://repology.org/project/mattermost/versions). Notably several BSD sources seem to have pretty up to date packaging and all the other *nix options are surprising current. Mac (Homebrew) and Windows (Scoop) packaging seems to have fallen behind. Also not shown on Repology but there are [unofficial Debian/Ubuntu packages out there](https://build.opensuse.org/repositories/home:zfbartels/mattermost-server).

**Comment by alerque** [comment]
Any hope of a backport & patch version release or are Arch folks stuck waiting for the next full minor version release cycle?

**Comment by amyblais** [comment]
This was discussed with devs and we feel that this is not a critical issue as this is related to dependencies and not the codebase.

Would you be open to updating to v5.22? We have just cut an RC-1 for v5.22 today.

**Comment by matoro** [comment]
> This was discussed with devs and we feel that this is not a critical issue as this is related to dependencies and not the codebase.
> 
> Would you be open to updating to v5.22? We have just cut an RC-1 for v5.22 today.

Of course, when it gets released.  Not a huge deal, just letting you know that there are downstream distro packagers that build from source (I also run in production at work from my own packages, so double invested in making sure things build properly).
