### ISSUE TITLE
Cypress test: "Inline markdown image that is a link, opens the link"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14069]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Inline markdown image that is a link, opens the link

**Steps:**
1. Make sure your markdown preview is enabled (Account Settings > Advanced > Preview pre-release features > Show markdown preview option in message input box = Yes) 
2. Post the following in a test channel
```
[![Build Status](https://travis-ci.org/mattermost/platform.svg?branch=master)](https://travis-ci.org/mattermost/platform)
```
3. Click on the image in the post
        
**Expected:**
On 3) Link opens in a new browser window

**Test Key:** M23350

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23350 - Inline markdown image that is a link, opens the link', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23350](https://mattermost.atlassian.net/browse/MM-23350)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
I'd like to do this pare! @saturninoabril

**Comment by josephk96** [comment]
I can't find the proper test case in the google sheet though

**Comment by saturninoabril** [comment]
Thanks bro! Yep, those in separate HW (help-wanted) tickets like this is not included in the spreadsheet, but I'll add it. Please use MM-T188 for the test key - https://automation-test-cases.vercel.app/test/MM-T188

**Comment by josephk96** [comment]
Thanks for adding it pare! I created a PR for this :)

To save you a few clicks, here it is -
https://github.com/mattermost/mattermost-webapp/pull/6127

Have a great day man!

**Comment by saturninoabril** [comment]
Thanks bro! Have great day to you!

**Comment by saturninoabril** [comment]
Thanks @josephk96! Closing this issue now.
