### ISSUE TITLE
Cypress test: "CTRL/CMD+K - Open private channel using arrow keys and Enter"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14078]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** CTRL/CMD+K - Open private channel using arrow keys and Enter

**Steps:**
1. Press CTRL+K (Windows) or CMD+K (Mac)
2. Type the first letter of a private channel in the "Switch Channels" modal message box
3. Use up/down arrow keys to highlight a private channel
4. Press ENTER
        
**Expected:**
Private channel opens, with focus in the message box

**Test Key:** M23358

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23358 - CTRL/CMD+K - Open private channel using arrow keys and Enter', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23358](https://mattermost.atlassian.net/browse/MM-23358)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by djanda97** [comment]
I will work on this.

**Comment by saturninoabril** [comment]
Awesome, thanks @djanda97! Let me know if you need anything.
