### ISSUE TITLE
Cypress test: "Correct Spacing between Emojis"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14076]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Correct Spacing between Emojis

**Steps:**
1. Add a variety of built-in emoji and custom emoji to the same post. Ensure at least 20 different emoji are selected. 
2. Check if the emojis are stacked up with equal spaces and are lined up properly. 
        
**Expected:**
Emojis should be stacked up with equal spaces and are lined up properly

**Test Key:** M23355

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23355 - Correct Spacing between Emojis', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23355](https://mattermost.atlassian.net/browse/MM-23355)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by syuo7** [comment]
I want to work on this issue :)

**Comment by saturninoabril** [comment]
Awesome, thanks @syuo7!

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
