### ISSUE TITLE
Cypress test: "Autocomplete should match entries with spaces"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14074]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Autocomplete should match entries with spaces

**Steps:**
1. Create a channel with the name e.g. Ask Anything
2. Add channel purpose e.g for asking any questions 
3. Navigate to any channel and type ~for asking
4. Repeat the steps using @ name last name e.g. @ john smith
        
**Expected:**
3. auto complete should allow space character and not close after space is typed for as long as there are matching entries
4. should be allowed to use spaces between first and last name, as long as there are matching users autocomplete should not close after space character

**Test Key:** M23363

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23363 - Autocomplete should match entries with spaces', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23363](https://mattermost.atlassian.net/browse/MM-23363)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by ManuelPortero** [comment]
Hi is possible work in that ? Would be my third contribution so probably i would ask you once or twice .
Regards.
Manuel Portero.

**Comment by saturninoabril** [comment]
Sure, thanks for your interest @ManuelPortero! I'll be assigning this issue to you. Feel free to let me know if you have question.

**Comment by jfrerich** [comment]
This issue appears stale and I’m adding the `Up For Grabs` label.  If work is ongoing, please remove the label.  If there is an existing PR, please also link it to the issue.  Thanks!

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
