### ISSUE TITLE
Cypress test: "Flagged parent post:  reply count remains in center channel and is correct"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14073]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Flagged parent post:  reply count remains in center channel and is correct

**Steps:**
1. Using two test accounts, create a conversation of a parent post and 5 or so replies (or use conversation created above)
2. From the center channel, flag the parent post and then click on the "flagged posts" icon to open flagged posts in the RHS (observe at this stage that reply count is correct in center channel)
3. In the RHS reply to the flagged parent post
4. Without closing the RHS after you posted a reply in 3) click on the "flagged posts" icon again
        
**Expected:**
Reply count remains in center channel and is correct

**Test Key:** M23354

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23354 - Flagged parent post:  reply count remains in center channel and is correct', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23354](https://mattermost.atlassian.net/browse/MM-23354)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by swarnv02** [comment]
I am interested in this ticket, please assign

**Comment by saturninoabril** [comment]
Sure and thanks @swarnv02!

**Comment by VishalSwarnkar** [comment]
Sorry for the confusion, by mistake I have requested you from my official account, do you mind unassigning swarnv02 and assign to vishalswarnkar. Both of them are my account it is just that swarnv02 is an official account and vishalswarnkar is personal.

**Comment by saturninoabril** [comment]
No worries, and thanks @VishalSwarnkar!

**Comment by saturninoabril** [comment]
Outdated. Closing. Will publish new HW.
