### ISSUE TITLE
Cypress test: "Typing should show up right away when editing a message using the up arrow"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14075]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Typing should show up right away when editing a message using the up arrow

**Steps:**
1. Post a message
2. Hit the up arrow to open the "edit modal"
3. Begin typing straight away as quickly as you can
        
**Expected:**
There is no delay in letters appearing in the edit modal, no text is lost, and no text appears in the center panel in the background

**Test Key:** M23347

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23347 - Typing should show up right away when editing a message using the up arrow', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23347](https://mattermost.atlassian.net/browse/MM-23347)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
Hi @saturninoabril I'd like to work on this :)

**Comment by saturninoabril** [comment]
Hello bro, sure! This qualifies for Hackfest too. Also we have lots here - https://docs.google.com/spreadsheets/d/1gn12iXQbswP1fAcp4alEIfJdFuB1DlFu9CzW89zm598/edit#gid=1650809354 😄

**Comment by josephk96** [comment]
Thanks dude! Sorry I've been AWOL for the past few months, I'll try to be more active, especially with the Hackfest going on :)

**Comment by saturninoabril** [comment]
No worries and glad to hear from you again 😄

**Comment by saturninoabril** [comment]
Thanks @josephk96 for your contribution! Closing.
