### ISSUE TITLE
Cypress test: "Deactivated users are not shown in Direct Messages modal"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14087]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Deactivated users are not shown in Direct Messages modal

**Steps:**
1. Click on the "+" symbol beside the DIRECT MESSAGES menu on the left hand side.
2. Observe the list in the Direct Messages modal.
        
**Expected:**
Deactivated users are not listed

Note: Deactivated user may be shown if you have previous messaging history with that user, in which case that is expected

**Test Key:** M23349

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23349 - Deactivated users are not shown in Direct Messages modal', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23349](https://mattermost.atlassian.net/browse/MM-23349)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by AkaZecik** [comment]
I would like to work on it

**Comment by saturninoabril** [comment]
@AkaZecik Sure and thanks!
