### ISSUE TITLE
Cypress test: "Draft with only 2 byte characters shouldn't remain after posting"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14086]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Draft with only 2 byte characters shouldn't remain after posting

**Steps:**
1. Select 2-Set Korean keyboard
2. Press g b
3. Hit enter, observe message posts
4. Switch channels
5. Observe that there is not a draft icon next to the channel you just posted in and switched away from
6. Switch back to the channel where you posted

        
**Expected:**
The message box is empty (no draft present)

**Test Key:** M23362

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23362 - Draft with only 2 byte characters shouldn't remain after posting', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23362](https://mattermost.atlassian.net/browse/MM-23362)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
Hi @saturninoabril , I'd like to work on this. Just to clarify, I have to type 휴 , press enter and make sure that when switching channels the draft icon (little pencil icon) isn't next to the name of the original channel, am I correct?

**Comment by saturninoabril** [comment]
Sure and yes that's correct!
