### ISSUE TITLE
Cypress test: "Emoji characters followed by punctuation"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14085]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Emoji characters followed by punctuation

**Steps:**
1. Post emoji characters of ":)" followed by "=" without space in between
        
**Expected:**
Should render smiling face emoji with "=" next to it

**Test Key:** M23360

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23360 - Emoji characters followed by punctuation', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23360](https://mattermost.atlassian.net/browse/MM-23360)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by syuo7** [comment]
I will try this issue!

**Comment by saturninoabril** [comment]
Awesome, thanks @syuo7!
