### ISSUE TITLE
Cypress test: "Focus remains in the RHS text box"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14081]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Focus remains in the RHS text box

**Steps:**
1) Log into webapp
2) Open reply thread (RHS) on any post
3) Add some text to RHS text box
4) Click on Preview 
5) Click on Add Comment
6) Start typing again
        
**Expected:**
Focus to remain in the RHS text box

**Test Key:** M23361

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23361 - Focus remains in the RHS text box', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23361](https://mattermost.atlassian.net/browse/MM-23361)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by clarmso** [comment]
I've recreated the PR here: https://github.com/mattermost/mattermost-webapp/pull/5722
