### ISSUE TITLE
Cypress test: "CTRL/CMD+K - Find GM by matching username, full name, or nickname, even if that name isn't displayed"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14080]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** CTRL/CMD+K - Find GM by matching username, full name, or nickname, even if that name isn't displayed

**Steps:**
1. Ensure there is a GM open that includes at least one user with full name and nickname set
2. Press CTRL+K (Windows) or CMD+K (Mac)
3. Depending on teammate name display settings, filter the list to find the GM by searching on a term that is not displayed

In other words, if you have a GM including user `@username, Firstname Lastname, nickname`, and display is set to show username:
Press CTRL+K (Windows) or CMD+K (Mac)
Type `las`
You should see the GM with @username come up as a search result
        
**Expected:**
GM channel including the user you searched on should be returned

**Test Key:** M23357

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23357 - CTRL/CMD+K - Find GM by matching username, full name, or nickname, even if that name isn't displayed', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23357](https://mattermost.atlassian.net/browse/MM-23357)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
@saturninoabril , I'd like to do this pare!

**Comment by saturninoabril** [comment]
Thanks @josephk96! Please use MM-T1226 as the test key - https://automation-test-cases.vercel.app/test/MM-T1226

**Comment by josephk96** [comment]
Sure thing!
