### ISSUE TITLE
Cypress test: "CTRL/CMD+K - Open DM using mouse"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14082]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** CTRL/CMD+K - Open DM using mouse

**Steps:**
1. Press CTRL+K (Windows) or CMD+K (Mac)
2. Type the first letter of another user's username (who you don't already have a DM channel open with, but who you can log in as) in the "Switch Channels" modal message box
3. Scroll down to the "Other Channels" section and locate the user
4. Use your mouse to choose the user and open the DM channel
5. Send a DM
6. Log in as the other user
        
**Expected:**
DM channel with that user opens (no Javascript errors), with focus in the message box

Other user receives the DM

**Test Key:** M23359

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23359 - CTRL/CMD+K - Open DM using mouse', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23359](https://mattermost.atlassian.net/browse/MM-23359)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
I'd like to do this, Saturn :)

**Comment by saturninoabril** [comment]
Awesome, thanks Joseph!

**Comment by saturninoabril** [comment]
Thanks @josephk96 for your contribution! Closing.
