### ISSUE TITLE
Cypress test: "Pinned parent post: reply count remains in center channel and is correct"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#14084]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

**Title:** Pinned parent post: reply count remains in center channel and is correct

**Steps:**
1. Using two test accounts, create a conversation of a parent post and 5 or so replies
2. From the center channel, pin the parent post to the channel
        
**Expected:**
Reply count remains in center channel and is correct

**Test Key:** M23346

**Test Folder:** `/cypress/integration/messaging`
**Test code arrangement:**
```
describe('Messaging', () => {
    it('M23346 - Pinned parent post: reply count remains in center channel and is correct', () => {
        // code
    });
});
```

**Jira ticket**: [MM-23346](https://mattermost.atlassian.net/browse/MM-23346)

---
If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
I'd like to work on this!

**Comment by saturninoabril** [comment]
Awesome, thanks my friend!

**Comment by josephk96** [comment]
No problem bro!
