### ISSUE TITLE
Google+ API is being deprecated

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/mattermost-server#14091]
Our [Google SSO Docs](https://docs.mattermost.com/deployment/sso-google.html) include instructions to use the Google+ API, which has been deprecated.

Possible Solutions:

- Use [Google SAML SSO](https://support.google.com/a/answer/6262818?hl=en)
- Use [Google Identity Platform](https://developers.google.com/identity/)

Related ticket: https://mattermost.atlassian.net/browse/MM-14874.

Original ticket: https://github.com/mattermost/mattermost-server/issues/13991

**Comment by justinegeffen** [comment]
If you're interested in taking on this documentation request, let us know by commenting on the issue.  The documentation that needs to be updated is located here: https://docs.mattermost.com/deployment/sso-google.html. The submitter of this issue (@icelander) may have additional links and content available. 

- If you're a new contributor take a look through the [Technical Writing Handbook](https://handbook.mattermost.com/operations/research-and-development/product/product-technical-writing-team-handbook#processes) to learn more about our processes. 

- For technical advice or questions, please join our [Developers community channel.](https://community.mattermost.com/core/channels/developers).

- For stylistic, formatting, or other questions join the [Documentation community channel](https://community.mattermost.com/core/channels/documentation).

We look forward to your contribution!

**Comment by KuSh** [comment]
Hi, this seems to have been fixed
