### ISSUE TITLE
Running mattermost in a /subdir returns 404 errors for UI plugins.

### ISSUE THREAD

**Issue by sphr** [mattermost/mattermost-server#14106]
#### Summary
When running mattermost in a /subdir on a server, plugins loose track of the path and assume the root.

#### Steps to reproduce
Configure mattermost to run on a example.tld/subdir/ in the config.json then install a plugin that uses the webserver to launch resources, for instance the zoom or standup-raven one.

#### Expected behavior
I expect plugins to get the real full pwd from the mattermost config that I have configured to include /subdir not just the domain and append /plugins to it

#### Observed behavior (that appears unintentional) 
404 not found errors on plugins such as zoom and standup-raven.

#### Possible fixes
A workaround so far has been to unload all plugins affected, edit the main.js file to point to /subdir/plugins instead of just /plugins and then load the plugin. This ofcourse resets each time mattermost is restarted.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-23411.

**Comment by harshilsharma63** [comment]
I think this is something all plugin developers have to keep in mind. I'd recommend including this in [plugin best practices](https://developers.mattermost.com/extend/plugins/best-practices/) page.

**Comment by amyblais** [comment]
Closing as this has been covered via https://github.com/mattermost/mattermost-plugin-zoom/pull/93 and https://developers.mattermost.com/extend/plugins/webapp/best-practices/#using-the-mattermost-servers-siteurl-in-your-web-app-plugin.
