### ISSUE TITLE
Text (Message) Entry Field: monospace (fixed-width / non-proportional) font option

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#14115]
Some of us use MatterMost for applications that include code and formatted text entry. Often we find ourselves wanting to precisely format spacing and other things.  This is difficult to do in non-monospace fonts for text entry.

It would be nice to have a monospace option or a simple toggle beside the text entry field that would allow us to move between proportional and monospace/fixed-width fonts.  

From adding complexity to the UI / UX, I could see some people not being super happy so simply enabling this toggle option in the preferences would be fine.

**Comment by amyblais** [comment]
Please feel free to open a feature request for this here https://mattermost.uservoice.com/forums/306457-general!

**Comment by ylluminate** [comment]
@amyblais I have done as you've requested: 

* https://mattermost.uservoice.com/forums/306457-general/suggestions/44264310-text-message-entry-field-monospace-fixed-width
* https://forum.mattermost.org/t/feature-request-text-message-entry-field-monospace-fixed-width-non-proportional-font-option/12285

PLEASE make it possible to have more votes. Unfortunately UserVoice consumes a vote for each feature request! That means that you will lose valuable input from users that have more feature requests than the allowed "votes"!!!
