### ISSUE TITLE
Google Cloud Monitoring: Unable to receive webhooks

### ISSUE THREAD

**Issue by tech348712013870132** [mattermost/mattermost-server#14116]
I am trying to get the Google Cloud Monitoring Notifications working with Mattermost webhooks.

The GCloud config is very simple:

<img width="442" alt="Screenshot 2020-03-20 at 18 26 08" src="https://user-images.githubusercontent.com/45794753/77189706-474e1080-6ad8-11ea-9b49-4fc1eb7c14e7.png">

I have created an incoming webhook in Mattermost and pasted the resulting link within the Gcloud dialog (Endpoint URL). When I test the connection via the button the webhook gets triggered but with the following cryptic error message:

`{"level":"error","ts":1584724230.932094,"caller":"mlog/log.go:175","msg":"No text specified","path":"/hooks/xxx","request_id":"xxx","ip_addr":"xxx","user_id":"","method":"POST","err_where":"HandleIncomingWebhook","http_code":400,"err_details":""}`

Is there no way to get this working folks?

**Comment by amyblais** [comment]
@tech348712013870132 Would you like to re-open this issue on our troubleshooting forum here https://forum.mattermost.org/ in case other community members have experienced this?

I'm not sure if GCloud Monitoring is supported in Mattermost or not.

**Comment by amyblais** [comment]
Closing as this is an old issue, but feel free to re-open if it still reproduces,

**Comment by dbacinski** [comment]
Google Cloud Monitoring is sending HTTP GET webhooks but mattermost only accepts HTTP POST, I am also looking for a simple way to integrate it.
