### ISSUE TITLE
Images downloaded with a name change have no extension

### ISSUE THREAD

**Issue by chris-fady** [mattermost/mattermost-server#14128]
#### Summary
No extension on images downloaded

#### Steps to reproduce
- Click download on a image file
- Change name of file (notice that no option to save as a specific file format exists)
- Check that the downloaded has no extension and is not recognized as an image file

#### Expected behavior
Downloaded as an image with a proper extension, given the extension already exists on the file present in Mattermsot (image appears as IMG_XXX.PGN).

**Comment by amyblais** [comment]
@chris-fady What Mattermost server version are you on and what OS are you using?

**Comment by chris-fady** [comment]
@amyblais Desktop app on Windows 4.1.2

**Comment by amyblais** [comment]
@chris-fady Would you be open to upgrading to desktop app v4.4.0 to see if the problem persists?

**Comment by chris-fady** [comment]
@amyblais Solved indeed! May I suggest implementing an alert on "check for updates" directly in the app?

**Comment by amyblais** [comment]
Glad to hear it!

An auto-update feature is planned and has been discussed by our team, but we need to revisit the implementation and technical details after we implemented MSI (beta) on Windows for v4.3.0.
