### ISSUE TITLE
Mattermost vs Nginx

### ISSUE THREAD

**Issue by WizardKid** [mattermost/mattermost-server#14135]
Hi I have searched for any related issues but couldnt find any. Was reluctant to open an issue due to most company's response time. The issue I am having is related to whenever i installed nginx for ssl certificate. the current issue is that i am getting an error that state the 443 port is in use. 
current error: `sudo systemctl status mattermost.service
● mattermost.service - Mattermost
   Loaded: loaded (/lib/systemd/system/mattermost.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-03-24 13:48:12 UTC; 6s ago
  Process: 21354 ExecStart=/opt/mattermost/bin/mattermost (code=exited, status=1/FAILURE)
 Main PID: 21354 (code=exited, status=1/FAILURE)
`

**Comment by WizardKid** [comment]
Logfile: 

> {"level":"info","ts":1585055921.4230976,"caller":"sqlstore/post_store.go:1354","msg":"Post.Message has size restrictions","max_characters":16383,"max_bytes":65535}
{"level":"info","ts":1585055921.4319515,"caller":"jobs/workers.go:68","msg":"Starting workers"}
{"level":"info","ts":1585055921.444287,"caller":"jobs/schedulers.go:74","msg":"Starting schedulers."}
{"level":"info","ts":1585055921.4487157,"caller":"app/web_hub.go:75","msg":"Starting websocket hubs","number_of_hubs":4}
{"level":"info","ts":1585055921.4685364,"caller":"app/server.go:470","msg":"Starting Server..."}
{"level":"error","ts":1585055921.4696865,"caller":"commands/server.go:81","msg":"listen tcp :443: bind: address already in use"}
{"level":"info","ts":1585055921.4697404,"caller":"app/server.go:372","msg":"Stopping Server..."}
{"level":"info","ts":1585055921.46976,"caller":"app/web_hub.go:125","msg":"stopping websocket hub connections"}
{"level":"info","ts":1585055921.470759,"caller":"app/plugin.go:266","msg":"Shutting down plugins"}
{"level":"warn","ts":1585055921.4731016,"caller":"plugin/hclog_adapter.go:51","msg":"error closing client during Kill","plugin_id":"com.mattermost.nps","wrapped_extras":"errunexpected EOF"}
{"level":"warn","ts":1585055921.473171,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"com.mattermost.nps"}
{"level":"info","ts":1585055929.2618182,"caller":"jobs/workers.go:184","msg":"Stopped workers"}
{"level":"info","ts":1585055929.2619133,"caller":"jobs/schedulers.go:145","msg":"Stopping schedulers."}
{"level":"info","ts":1585055929.2619474,"caller":"jobs/schedulers.go:77","msg":"Schedulers stopped."}
{"level":"info","ts":1585055929.2619653,"caller":"sqlstore/supplier.go:916","msg":"Closing SqlStore"}
{"level":"info","ts":1585055929.2632372,"caller":"app/server.go:414","msg":"Server stopped"}

**Comment by amyblais** [comment]
@WizardKid Would you be open to posting this on our troubleshooting forum here: https://forum.mattermost.org/. Our community and support team are more actively responding to issues there.

I can also optionally ask our team on our [Peer-to-Peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) to take a look at this issue.
