### ISSUE TITLE
Read-only Town Square for select teams

### ISSUE THREAD

**Issue by kelsiuss** [mattermost/mattermost-server#14145]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Cannot make specific teams' Town Square read-only

#### Steps to reproduce
Have 2+ teams on a server, turn on ExperimentalTownSquareIsReadOnly flag to true, affects all teams on server but would only expect to affect the current.

#### Expected behavior
I'd expect to be able to only lock down one specific team's Town Square to be read-only.

#### Observed behavior (that appears unintentional) 
All teams Town Squares were affected and placed in read-only mode

**Comment by amyblais** [comment]
@kelsiuss What Mattermost server version are you on?

**Comment by amyblais** [comment]
@kelsiuss Would you be open to sharing more details about your environment?

**Comment by kelsiuss** [comment]
Yes, sorry about the late response. We're on MM 5.21.

Our application is using one team as our internal team (direct employees), while our other team is an external team (customers, guests, etc). We do not want those users to be able to communicate in Town Square on the external team, but we encourage the internal team to use it to openly communicate to the rest of their co-workers.

**Comment by jasonblais** [comment]
Hi @kelsiuss - the `ExperimentalTownSquareIsReadOnly` setting affects the Town Square for all teams on the system.

However, we are actually releasing read-only channels in E20, which allow you to create read-only announcement channels more freely. This is coming in v5.22, releasing on Apr 16th (tomorrow!)
