### ISSUE TITLE
Desktop: Push Notification Actions

### ISSUE THREAD

**Issue by skyvalleyhigherpraise** [mattermost/mattermost-server#14155]
**Summary**
When Mattermost is not in the foreground and a push notification is displayed, clicking the notification window triggers Mattermost to go to the channel, but does not bring it to the foreground focus.
This was fixed in prior version of MM, but is back in 4.4.0 [Desktop: Push Notification Actions](https://github.com/mattermost/mattermost-server/issues/11963)

**Steps to reproduce**
Click on a push notification once it pops.

**Expected behavior**
Bring app to the foreground and go to the channel.

**Observed behavior (that appears unintentional)**
Push notification disappears, Mattermost is triggered to go to the channel, but the app does not come to the foreground focus.

**Possible fixes**
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@skyvalleyhigherpraise What server version are you on?

**Comment by skyvalleyhigherpraise** [comment]
@amyblais Here is what I've located in desktop:

Mattermost Enterprise Edition
Modern communication from behind your firewall.

**Mattermost Version:** 5.14.1
**Database Schema Version:** 5.14.0
**Database:** mysql

LMK if you need something else.

**Comment by amyblais** [comment]
@skyvalleyhigherpraise I realized this bug was actually fixed in the webapp repo in server v5.16.0 release: https://github.com/mattermost/mattermost-webapp/pull/3718.
Would you be open to upgrading?

**Comment by skyvalleyhigherpraise** [comment]
@amyblais Our IT department is not prioritizing MM server upgrades atm.  Thus, our agents are stuck with upgrading the desktop app at best.
