### ISSUE TITLE
Activity in muted channels indicated in browser tab and team list

### ISSUE THREAD

**Issue by torgeirl** [mattermost/mattermost-server#14162]
#### Summary
Activity in muted channels cause the browser tab text to get a `*` icon prefix as if there's new activity for you. Same goes for the team icon list, where the muted channel's team gets a `•` icon next to it.

#### Steps to reproduce
Mute a channel with some activity on one of your team, and switch to another. Switch to another tab in your browser. Whenever the browser tab gets `*` icon prefix switch back to the Mattermost tab. You will see that a few of the times the team where you muted the channel has a `•` icon next to it in the team icon list, and switching to it will reveal there's only been activity in the muted channel. The activity does not need to contain `@channel` or other tags.

#### Expected behavior
Peace and quiet.

#### Observed behavior (that appears unintentional) 
Hints of activity relevant to me, turning out to be chat in muted channels.

**Comment by amyblais** [comment]
@torgeirl What server version and OS are you on?

**Comment by torgeirl** [comment]
> @torgeirl What server version and OS are you on?

@amyblais: we're running server version 5.21, and I'm accessing it using Google Chrome 80.0 on a Fedora 31 computer (all latest versions I believe).

I just recently noticed this issue, but it could be older since our usage pattern has changed due to COVID19. The activity in teams I don't participate in have increased manifold (membership by being a team admins).

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-23639.

**Comment by torgeirl** [comment]
@bradjcoughlin, @hmhealey: really appreciate you taking the time to fix this! :pray:
