### ISSUE TITLE
Writing text and starting to write preformatted block in the same message causes text to disappear

### ISSUE THREAD

**Issue by cmistrata** [mattermost/mattermost-server#14170]
#### Summary
If I begin writing a message, and then try to paste multiple lines of text from github into a preformatted block in another line of the same message, the original text I've written will disappear. Trying to undo the changes to the message does not cause the text to reappear.

#### Steps to reproduce
Using version 4.1.2, using the Windows app, using GPU Hardware acceleration in settings.
Using version 4.4.0, using the Windows app, using GPU Hardware acceleration in settings.

#### Expected behavior
No part of my message is deleted.

#### Observed behavior (that appears unintentional) 
If I have a message like

message
\`\`\`
text from a github file
\`\`\`

when I try to paste "text from a github file" after the first line of backticks, "message" will disappear and is unrecoverable by using ctrl+z. The message is recoverable by clicking into another chat and coming back, but this causes the pasted preformatted text to disappear.

**Comment by amyblais** [comment]
@cmistrata Do you see the same issue on desktop app v4.4.0?

**Comment by cmistrata** [comment]
I've updated my Mattermost version to 4.4.0, and will use it for a bit and see if it happens to me again. I couldn't get this to occur reliably in 4.1.2, but will update in like a week if it does or doesn't happen.

**Comment by cmistrata** [comment]
I've been using version 4.4.0 for a week, and had this issue occur again for the first time today. I noticed by clicking away from the chat I'm in and coming back to it, I'm able to recover the "message" part of my message, but the "preformatted text" disappears, if that's clear. Also some more detail, trying to recover the message using ctrl+z does not work.

**Comment by amyblais** [comment]
Do you have access to Jira to check if this ticket describes the issue you're seeing https://mattermost.atlassian.net/browse/MM-23933?

**Comment by cmistrata** [comment]
Yes, that describes the issue I'm seeing

**Comment by cmistrata** [comment]
Also noticed it only occurs when pasting multiple lines of text, updated again

**Comment by amyblais** [comment]
This is fixed for upcoming v5.23 release,
