### ISSUE TITLE
Old flagged posts do not reliably appear when opening "flagged" sidebar

### ISSUE THREAD

**Issue by RalfJung** [mattermost/mattermost-server#14186]
#### Summary
I flagged some posts around two years ago. Recently I realized those fail to show up when I click the "flagged" button, unless I then also click "Jump" on a more recent flagged post.

#### Steps to reproduce
Mattermost version 5.19.1 (with GitLab)

* I flagged some posts in 2018.
* Now when I click the "flagged" button, they do not show up.
* However, some more recent flagged posts show up. When I click "jump" on one of them, suddenly the missing flagged posts appear! (Or maybe only some of them, I am not sure if there are even older ones that are still missing.)

#### Expected behavior
Clicking the "flagged" button should list everything I flagged, ever.

#### Observed behavior (that appears unintentional) 
Some messages are missing from "flagged".

#### Possible fixes
Sorry, not familiar with your codebase.

**Comment by amyblais** [comment]
@RalfJung What OS and version are you on?

**Comment by RalfJung** [comment]
@amyblais  You mean on my client? Firefox 75 beta on Linux (Debian testing).

**Comment by ethervoid** [comment]
@RalfJung Thank you for taking the time to report this issue.

Do you know how many flagged posts do you have?

I'm asking this because right now we're only showing the first 60 flagged posts but we have an [open issue](https://mattermost.atlassian.net/browse/MM-17005) to improve that

**Comment by RalfJung** [comment]
Good point. When I reported the issue I had 4 flagged posts total (well, 4 that it would show after "jump"ing).

**Comment by ethervoid** [comment]
Oh I see. Then we should start looking somewhere else. Thank you :)

**Comment by amyblais** [comment]
Closing as this is an old issue, feel free to re-open if this still reproduces,
