### ISSUE TITLE
Wrong Date Ordering in Site Statistics

### ISSUE THREAD

**Issue by iBigQ** [mattermost/mattermost-server#14205]
#### Summary
The dates in the `system console` -> `site statistics` are in wrong order.

#### Steps to reproduce
Using mattermost 5.19.1, open the site statistics on the website. 

#### Expected behavior
Number of posts/users is plotted on a continuous timeline

#### Observed behavior (that appears unintentional) 
Some dates (concrete days) are missing in the timeline (x-axis). They are appended after the last day with zero-values.

![image](https://user-images.githubusercontent.com/6987420/78121758-14771700-740c-11ea-8cda-155c3908bb4a.png)

#### Possible fixes
Referring to the screenshot, I assume that on the wrongly ordered dates, there indeed was no post (zero-value).

**Comment by iBigQ** [comment]
btw using postgresql (not sure if relevant)

**Comment by lindy65** [comment]
Thanks for the report @iBigQ - I've reproduced your issue and have filed https://mattermost.atlassian.net/browse/MM-23782 to track.

**Comment by iBigQ** [comment]
Bug tracker says its fixed in v5.27. Cannot confirm myself because I am running the latest LTS v5.25. Anyway, I believe in you guys!
