### ISSUE TITLE
matter most drop requests that bigger than 7900 characters

### ISSUE THREAD

**Issue by valdemarpavesi** [mattermost/mattermost-server#14207]
We do have this problem that our Alert send to MatterMost Incoming Webhooks will be discarded.

`
level=error ts=2020-04-01T15:28:21.657Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=109 err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 400: {\"id\":\"web.incoming_webhook.attachment.app_error\",\"message\":\"Maximum attachments length is 7900 characters, received size is 8036\",\"detailed_error\":\"\",\"request_id\":\"6wppy9kxhtrgmnzbd7mwhykx6a\",\"status_code\":400}"
`

Version: 4.3.0
Database: mysql

**Comment by amyblais** [comment]
@valdemarpavesi What Mattermost server version are you on?
Does the same issue happen on desktop app v4.4.0?

**Comment by agnivade** [comment]
This is fixed from 4.4.0 onwards. I would also suggest to upgrade to a newer version like an ESR release. 4.3.0 is very old.

@amyblais - OP's server version itself is 4.3.0.

**Comment by amyblais** [comment]
I'll close this for now as we haven't received feedback for a while. I hope you will be able to upgrade your server version and then let us know if you still experience the issue,
