### ISSUE TITLE
Please remove release 99.99

### ISSUE THREAD

**Issue by teadur** [mattermost/mattermost-server#14265]
#### Summary
I understand the problem isnt mattermost-server but rather check_mattermost script but as of many people could be using the script i'm kindly asking could release 99-99 be removed https://github.com/mattermost/mattermost-server/compare/release-99.99 because it brakes release parsing.

#### Steps to reproduce
Try to use check_mattermost script: https://github.com/shoreless-ltd/check_mattermost

#### Expected behavior
There is no test release 99.99

#### Observed behavior (that appears unintentional) 
[CRITICAL] Mattermost Version 5.14.0.5.14.0.453 too old. Latest: 99.99

#### Possible fixes
As of this is test release, it could be removed

**Comment by amyblais** [comment]
Not sure exactly who to ping, maybe @cpanato or @metanerd ^

**Comment by cpanato** [comment]
we can remove

**Comment by cpanato** [comment]
done
