### ISSUE TITLE
Custom emojis fail to import

### ISSUE THREAD

**Issue by jacki-522** [mattermost/mattermost-server#14285]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Custom emojis fail to import on bulk import load.

#### Steps to reproduce
Run the bulk import load commands.

#### Expected behavior
Have the custom emojis present in migrated enviornment

#### Observed behavior (that appears unintentional) 
import command validates with no errors but upon "apply", we get the error "Error reading import emoji file."
After deleting the emoji lines out of the import file, the import completes with no errors.

#### Possible fixes
N/A

**Comment by amyblais** [comment]
@svelle Would you be familiar with this issue?

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-38759.
