### ISSUE TITLE
Bulk export fails to export/import all data

### ISSUE THREAD

**Issue by jacki-522** [mattermost/mattermost-server#14284]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bulk export fails to export custom emojis and direct messages

#### Steps to reproduce
Running the bulk export command
https://docs.mattermost.com/administration/bulk-export.html#
Running version 5.21

#### Expected behavior
Custom emojis do not export and neither do direct messages.

#### Observed behavior (that appears unintentional) 
Failure messages at export and custom emojis/direct messages not in export file. After the command fails to on exporting the custom emojis, it errors out and does not continue on to export direct messages. We are assuming the export command runs in a specific order and quits after an error is detected.

#### Possible fixes
The instructions for bulk export have us change to "/opt/mattermost/bin" directory. However the custom emojis are located in "/opt/mattermost/data/emojis". 
If you cd to "/opt/mattermost" and run the command "sudo bin/mattermost export bulk file.json --all-teams", everything exports.

**Comment by amyblais** [comment]
@svelle Would you be familiar with this issue?

**Comment by svelle** [comment]
@jacki-522 thanks for pointing this out. I opened a PR to fix the docs. The /opt/mattermost/bin location is incorrect and outdated, so running the command from /opt/mattermost is actually the correct and preferred way.

@amyblais added you as reviewer for the PR to fix this.
