### ISSUE TITLE
Custom OAuth provider support.

### ISSUE THREAD

**Issue by prathik-kaliyambath** [mattermost/mattermost-server#14293]
##### Summary:
  This is not an issue per se. But I was wondering if there's anyway to integrate a Custom OAuth provider 
  with mattermost (For eg, FB Oauth, Auth0 or something hosted and managed by a third party like Ory 
  hydra)
  I have seen that this has been discussed multiple times in various forums and partly is implemented for 
  the enterprise edition, but is there any hope of having a similar feature for the team edition as well?

**Comment by amyblais** [comment]
@prathik-kaliyambath Are you referring to this https://docs.mattermost.com/developer/oauth-2-0-applications.html?

**Comment by prathik-kaliyambath** [comment]
@amyblais No, I was thinking of using a custom OAuth server hosted on a separate domain. The link you've mentioned is basically docs to use Mattermost as an OAuth server which we do not intend to do.

**Let me explain in detail** : We have a standard OAuth2.0 server hosted at auth.domain.com, which all our apps are using for authorisation. Now, we want to be able to create a Mattermost session and call all its APIs without any further authentication steps, since repeating the login procedure just to login to Mattermost is redundant and a bad UX. So, one must be able to login programatically to Mattermost and generate a Mattermost Authtoken using the token obtained from our provider (auth.domain.com) . As far as I can see and understand Mattermost is only providing Gitlab based login among all 3rd party login providers, we want this to be generic so that any standard OAuth2.0 provider can be used for the same. Let me know what are your thoughts on this,  and what is the possibility for getting it merged if we were to build this feature.

PS: This feature is available in many other open source alternatives we were evaluating, Rocketchat being one of them, but we were considering Mattermost due to it being in GoLang, and due to the fact that it fit our use case quite well, but since authorisation is such a vital part of the flow, the lack of support for generic OAuth servers is hugely inhibiting for us.

**Comment by ysaakpr** [comment]
Basically, we need to make Mattermost as a resource server in OAuth flow, Any other application who owns user session should able to call matter most apps. This needed for deep integration of Mattermost into our apps. We would like to contribute if there any feature request already for this.

**Comment by WestFarmer** [comment]
@prathik-kaliyambath why you closed this ?

**Comment by prathik-kaliyambath** [comment]
@WestFarmer hey, we made a fork based off this repo which has generic OAuth enabled. Do check it out, might be of help.

https://github.com/bettermost/mattermost-server

**Comment by WestFarmer** [comment]
@prathik-kaliyambath thanks dude do your fork support role/group[ mapping ?

**Comment by prathik-kaliyambath** [comment]
@WestFarmer no, roles are as is in the fork, only custom oauth support and clustering support via redis are added. If you want to add the roles as a feature, you're welcome to submit a PR.
