### ISSUE TITLE
More efficient full text search for Mattermost?

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#14306]
Happened across an article that I thought I'd drop here for consideration just in case it might help to improve Mattermost if perhaps the concept from Ruby on Rails could be extended to Go + PGSQL: 
[Full Text Search in Milliseconds with Rails and PostgreSQL](https://pganalyze.com/blog/full-text-search-ruby-rails-postgres)

Discussion here: https://www.reddit.com/r/ruby/comments/g2gnlb/full_text_search_in_milliseconds_with_rails_and/

**Comment by amyblais** [comment]
Please feel free to open a feature request for this here https://mattermost.uservoice.com/forums/306457-general!

**Comment by ylluminate** [comment]
Does the Bleve implementation now facilitate this @amyblais @jasonblais? I will add something more generic to UserVoice if not.

**Comment by jasonblais** [comment]
@ylluminate Thanks for your question! Bleve is intended to be a more efficient search engine, but I'm not familiar how it performs with respect to Ruby on Rails & Postgres search you're referencing https://docs.mattermost.com/deploy/bleve-search.html

Have you tried a Bleve search engine, or is this something you noticed Mattermost now supports (as experimental)?

**Comment by ylluminate** [comment]
@jasonblais I'm not actually asking about this in relation to RoR and PGSQL, but rather offering the core desired request of a speedy full text search. I believe it does, so I'll just ignore this at this point.  I've been having trouble searching in more refined fashions insomuch that we have 33 teams that are used for organizational purposes. I was looking at options to expand searching between teams, but I really don't have time to implement even a plugin for it at the moment.

**Comment by jasonblais** [comment]
@ylluminate Got it, that makes sense. Bleve may help solve some of the challenges you're seeing. However, cross-team search is something we don't yet support, but have desire to do so. There is an open feature proposal for that specific use case: https://mattermost.uservoice.com/forums/306457-general/suggestions/20081047-search-through-all-teams
