### ISSUE TITLE
Save button is not viewable in web app from Safari on mobile device

### ISSUE THREAD

**Issue by shred86** [mattermost/mattermost-server#14323]
#### Summary
“Save” button is not viewable in the web app from a mobile (e.g. Apple iPad using Safari) unless you search for “save”.

#### Steps to reproduce
Using an Apple iPad with Safari on the latest Mattermost version (5.22.0):
1) Access a system console setting and make a change to bring up the “Save” button.
2) Note that you can’t see the “Save” button.
3) Do a search for “save” in the browser and the “Save” button will now appear.

#### Expected behavior
User should not have to search for the word “save” for the “Save” button to appear. 

#### Observed behavior (that appears unintentional) 
Missing button: https://i.imgur.com/NmhnpfX.png
Button showing after searching: https://i.imgur.com/SHuKolA.png

#### Possible fixes
Changes to styling to make it compatible with mobile web browsers.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-24361.

**Comment by Tjelfe** [comment]
This error still persists on Chromebooks in tablet mode. The button gets visible when switching to desktop mode.
