### ISSUE TITLE
On Mobile APP after update to 4.3.0 all channel's are "This Channel is read-only"

### ISSUE THREAD

**Issue by CPC954** [mattermost/mattermost-server#14325]
After Google Play Store recently warned for update of Mattermost app, we did the update but then notice that all Channel's are "read-only". 

Please check these because i do believe your mobile app should work in any version! This way we can't revert to previous version and we do have a problem unless we update server and for that we do have to spend a certain amount of time that we don't have now.. 

Mattermost Team Edition 4.3.0
Database: mysql

**Comment by amyblais** [comment]
@CPC954 Would you be open to upgrading your server version as v4.3.0 is not a supported version anymore? We support versions v5.19.0 and later.

**Comment by amyblais** [comment]
We have a fix queued for this for v1.30.1,

**Comment by amyblais** [comment]
Mobile v1.30.1 dot release has been released and will be available in the app stores soon,
