### ISSUE TITLE
Mattermost PGP key expired

### ISSUE THREAD

**Issue by JakubOnderka** [mattermost/mattermost-server#14354]
Hi, I tried to verify Mattermost installation file by GPG, but your PGP key, that is available at https://keybase.io/mattermost, is expired (since 2020-04-02). Even version 5.22, released at  2020-02-16, is signed by this expired key.

It will be possible to publish new key and sign latest release again with new key?

Thank you

**Comment by metanerd** [comment]
@JakubOnderka Thank you for reporting this! This should be fixed now. Sorry about any issues this caused.
