### ISSUE TITLE
Post reactions are missing after Slack import

### ISSUE THREAD

**Issue by Leopold702** [mattermost/mattermost-server#14364]
#### Summary
Post reactions are missing after Slack import

#### Steps to reproduce
1. Download Slack export
2. Download attachments and user emails via Slack Advanced Exporter
3. Import resulting archive to Mattermost 5.22.0 using CLI tool
4. Relocate _data_ folder from the _/mattermost/bin_ folder

After performing the above steps I verified the newly imported team. All the items seems to be in place, except for emoji reactions to posts. Those were completely missing.

#### Expected behavior
Post reactions should be properly imported along with all other data since both Slack and Mattermost support them.

I tried to import the same Slack archive to Rocket Chat and reactions were imported there just fine.

**Comment by amyblais** [comment]
Would you be open to upvoting this feature request https://mattermost.uservoice.com/forums/306457-general/suggestions/39933091-add-support-for-emoji-reactions-in-slack-import?

**Comment by Leopold702** [comment]
Do you mean that this feature isn't implemented yet? If so, then it doesn't seem that my vote will make implementation any closer since apparently nobody but me interested in it.

Maybe you know if there is some workaround for this? Is there is some way to import reactions separately?

**Comment by amyblais** [comment]
@svelle Would you know if there is a workaround?

**Comment by svelle** [comment]
I don't know of any workaround. Sorry.
