### ISSUE TITLE
Plugins can't be activated

### ISSUE THREAD

**Issue by stoffel1984** [mattermost/mattermost-server#14383]
Hi,

i'm new to mattermost and running it on an Centos7-VM.
If i upload plugins, they can't be activated and i should read the log file.

Could Annone her?

here's the log:

Apr 27 16:13:51 localhost mattermost: {"level":"info","ts":1588004031.0244684,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:14:51 localhost mattermost: {"level":"info","ts":1588004091.097298,"caller":"scheduler/worker.go:78","msg":"Worker: Job is compl$
Apr 27 16:15:51 localhost mattermost: {"level":"info","ts":1588004151.1568506,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:16:51 localhost mattermost: {"level":"info","ts":1588004211.2188616,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:17:51 localhost mattermost: {"level":"info","ts":1588004271.2903645,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:18:51 localhost mattermost: {"level":"info","ts":1588004331.3524723,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:19:51 localhost mattermost: {"level":"info","ts":1588004391.4109025,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:20:51 localhost mattermost: {"level":"info","ts":1588004451.4828408,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:21:51 localhost mattermost: {"level":"info","ts":1588004511.553157,"caller":"scheduler/worker.go:78","msg":"Worker: Job is compl$
Apr 27 16:22:51 localhost mattermost: {"level":"info","ts":1588004571.6221716,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:23:51 localhost mattermost: {"level":"info","ts":1588004631.6804593,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:24:51 localhost mattermost: {"level":"info","ts":1588004691.7409816,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$
Apr 27 16:25:41 localhost mattermost: {"level":"error","ts":1588004741.6080756,"caller":"app/plugin.go:97","msg":"Unable to activate plugi$
Apr 27 16:25:43 localhost mattermost: {"level":"error","ts":1588004743.7855132,"caller":"app/plugin.go:97","msg":"Unable to activate plugi$
Apr 27 16:26:51 localhost mattermost: {"level":"info","ts":1588004811.868886,"caller":"scheduler/worker.go:78","msg":"Worker: Job is compl$
Apr 27 16:27:06 localhost mattermost: {"level":"error","ts":1588004826.384004,"caller":"app/plugin.go:97","msg":"Unable to activate plugin$
Apr 27 16:28:06 localhost mattermost: {"level":"info","ts":1588004886.9421437,"caller":"scheduler/worker.go:78","msg":"Worker: Job is comp$

**Comment by amyblais** [comment]
@stoffel1984 What Mattermost server version are you on? What OS and version are you on?

**Comment by stoffel1984** [comment]
@amyblais Mattermost Team 5.8.0-1 on Linux CentOS 7.

**Comment by amyblais** [comment]
Our supported versions include v5.19.0 and later. Would you be open to upgrading?

**Comment by stoffel1984** [comment]
yes, it's nearly a naked system. 
1 vcore
4GB RAM
40 GB 

will that be enough for the newest version?

**Comment by amyblais** [comment]
You can find more details on Hardware requirements here: https://docs.mattermost.com/install/requirements.html#hardware-requirements.
