### ISSUE TITLE
Refactor SQL queries in store/sqlstore/plugin_store.go to use the squirrel builder

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#14424]
Mattermost is replacing the SQL queries of the store layer to use the [squirrel builder](https://github.com/Masterminds/squirrel). This help wanted issue is to change the usages of raw SQL queries in the file `store/sqlstore/plugin_store.go`.

The expected way to implement this is to search in the `store/sqlstore/plugin_store.go` file for all the strings containing a SQL query and rewrite them with squirrel. To do so, we must obtain the query builder using the `getQueryBuilder()` method from the store struct, and use it to build the same query that we have in the string.

You can find more information on how to use squirrel in [the official package documentation](https://godoc.org/github.com/Masterminds/squirrel).

Example Pull Request: https://github.com/mattermost/mattermost-server/pull/14393

If you have questions about the ticket or you need any help, feel free to contact `miguel.delacruz` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-24664

**Comment by joshuabezaleel** [comment]
Hi @mgdelacroix , I am interested in this issue but I want to clarify several things before taking on this if that's okay with you:
1. For query statement that's already using gorp's statement like [this one](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/plugin_store.go#L58), do we also have to rewrite it using the squirrel and pass it to the appropriate statement of the store's `getReplica().<statement>`?
2. I am sorry if it's just me but I can't seem to find the equivalent of the `ON DUPLICATE KEY UPDATE` on MySQL like in [this line](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/plugin_store.go#L67) mapped to the squirrel's features. Should we also use a separate insert and update like what the PostgreSQL's [do](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/plugin_store.go#L58-L64) at the previous section? 

Thank you very much! :slightly_smiling_face:

**Comment by mgdelacroix** [comment]
Hi @joshuabezaleel! Let me try and clarify your points:

 1. For those cases it won't be necessary. This tickets are focused on rewriting only those SQL queries that we have now in plan strings.
 2. For the cases where squirrel doesn't provide with specific functions, you can use a combination of `Prefix`, `Suffix` and `Expr`. For example, a possible solution for that query would be:

```go
queryString, args, err := ps.getQueryBuilder().
	Insert("PluginKeyValueStore").
	Columns("PluginId", "PKey", "PValue", "ExpireAt").
	Values(kv.PluginId, kv.Key, kv.Value, kv.ExpireAt).
	SuffixExpr(sq.Expr("ON DUPLICATE KEY UPDATE PValue = ?, ExpireAt = ?", kv.Value, kv.ExpireAt)).
	ToSql()
```

Hope those answers to be helpful. Please let me know if you are interested in going for the ticket :)

**Comment by joshuabezaleel** [comment]
Hi @mgdelacroix , Thank you very much for a really helpful explanation! Sorry that I missed the `SuffixExpr` when reading the Godoc. 

I've put up a PR for this issue. Looking forward to hearing from you! :slightly_smiling_face:

**Comment by mgdelacroix** [comment]
No worries @joshuabezaleel, thanks a lot for your PR!! :smile:
