### ISSUE TITLE
Slash command doesn't print image_url on web app

### ISSUE THREAD

**Issue by harf18** [mattermost/mattermost-server#14458]
#### Summary
Slash command with attachement doesn't print image_url on webapp.

#### Steps to reproduce
Create a slash command with one attachement and one image_url. Example : 
```
{
   "response_type": "in_channel",
      "attachments": [{
         "color": "#FF8000",
        "title": "Afficher la carte VAC",
        "title_link": "https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_23_APR_2020/Atlas-VAC/PDF_AIPparSSection/VAC/AD/AD-2.LFBI.pdf",
        "image_url": "https://www.ulmevasion26.com/images/sampledata/LFHE.jpg"
   }]
}
```

#### Expected behavior
Mattermost Version: 5.22.1
Database Schema Version: 5.22.0
Database: postgres
The rendering of slash command doesn't include the image_url on mattermsost webapp but an empty space. It's working on android mobile app and slack
the html code is like :

```
<div id="messageAttachmentList_7p77s6bod7dwuqifadwx1pojja" class="attachment__list">
	<div class="attachment ">
		<div class="attachment__content">
			<div class="clearfix attachment__container attachment__container--">
				<h1 class="attachment__title"><a class="attachment__title-link" href="https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_23_APR_2020/Atlas-VAC/PDF_AIPparSSection/VAC/AD/AD-2.LFBI.pdf" target="_blank" rel="noopener noreferrer">Afficher la carte VAC</a></h1>
				<div>
					<div class="attachment__body attachment__body--no_thumb">
						<div class="attachment__image-container">
							<div class="image-loading__container attachment__image" style="max-width: 839px;">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 839 1191" style="max-height: 1191px; max-width: 839px; vertical-align: middle;"></svg>
							</div>
							<div class="file-preview__button"><img class="attachment__image" aria-label="file thumbnail" tabindex="0" src="https://metar.aero-club-poitou.fr/api/command-vac/img/AD-2.LFBI.pnghttps://www.ulmevasion26.com/images/sampledata/LFHE.jpg">
							</div>
						</div>
					</div>
					<div style="clear: both;"></div>
				</div>
			</div>
		</div>
	</div>
</div>
```

**Comment by amyblais** [comment]
@harf18 Do you see any Mattermost server log errors?

**Comment by harf18** [comment]
Yes, no errors on logs. If i activate DEBUG level, I can see this : 

{"level":"debug","ts":1588597633.2418153,"caller":"app/command.go:400","msg":"Executing command","command":"vac","user_id":"sgsd3xhkwtbtxdudq7zdnt9uqe"}

**Comment by harf18** [comment]
On web app : 
![Sélection_366](https://user-images.githubusercontent.com/320044/80969157-71098f80-8e19-11ea-82ad-8322dffa09b6.png)

On Android APP :
![Screenshot_20200504-134516_Mattermost](https://user-images.githubusercontent.com/320044/80969468-f12ff500-8e19-11ea-97e4-195b21adcb16.jpg)

**Comment by harf18** [comment]
Sorry, it was my addblocker
