### ISSUE TITLE
Read-only channels but with threads allowed

### ISSUE THREAD

**Issue by ilyakonovalenko** [mattermost/mattermost-server#14453]
Hello,

It would be nice to have an ability to restrict messages in the channel but allow messages in the threads for the channel.

So that channel looks like a forum. Only answers to the posts are allowed.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @ilyakonovalenko,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by ilyakonovalenko** [comment]
Yes, sure. I have already created a post here: https://mattermost.uservoice.com/forums/306457-general/suggestions/40335820-read-only-channels-but-with-threads-allowed

**Comment by amyblais** [comment]
Thank you!

**Comment by rus183** [comment]
Hi!  

Is there any update on this feature request?  
Has the ability to make a channel read-only for root posts while still allowing all users to reply in threads been implemented, or is it planned on the roadmap?

This use case is still very relevant (announcement / moderated channels with discussion only in threads), so I wanted to check the current status.

Thanks!
