### ISSUE TITLE
Dualing Automatic Direct Message Replies

### ISSUE THREAD

**Issue by SemperRuminare** [mattermost/mattermost-server#14460]
#### Summary
When 2 users have automatic replies they will continue to message each other forever. (Battle-bots DM style)

#### Steps to reproduce
Mattermost Version: 5.22.0
- User 1 enables Automatic Direct Message Replies
- User 2 enables Automatic Direct Message Replies
- User 1 or 2 messages the DM channel without going online and disabling Automatic Direct Message Replies

#### Expected behavior
- Bots reply once to each other and then stop messaging.

#### Observed behavior (that appears unintentional) 
- Bots continue to reply to each other until the end of days.
![image](https://user-images.githubusercontent.com/2375683/80974492-cbd9c180-8dee-11ea-815c-86341ce4f9ef.png)

#### Possible fixes
- Need to check if the message is an automatic reply and do not message back if that is the case or implement a counter per DM message thread.

**Comment by amyblais** [comment]
This has been fixed for upcoming v5.23 release: https://github.com/mattermost/mattermost-server/pull/14410.
