### ISSUE TITLE
Aliases for custom emojis

### ISSUE THREAD

**Issue by Roy-Orbison** [mattermost/mattermost-server#14482]
#### Summary
Allow multiple names separated by space/comma to used internally as aliases.

#### Steps to reproduce
Hamburger menu > Custom Emoji > Add Custom Emoji

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @Roy-Orbison,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by JacobDB** [comment]
Would love to see this too, even for built in emoji. I constantly get confused by "tada" representing the "party popper" emoji. Being able to set custom aliases would be fantastic.

**Comment by Roy-Orbison** [comment]
I did post the suggestion, I should have linked it here. Feel free to add your votes to that instead, and your wise suggestion that it should be for all emojis.

https://mattermost.uservoice.com/forums/306457-general/suggestions/40364041-allow-aliases-for-custom-emojis
