### ISSUE TITLE
Switching channels often hangs and then places me 1-2 weeks in the past

### ISSUE THREAD

**Issue by tgstan** [mattermost/mattermost-server#14495]
#### Summary
Switching channels often hangs and then places me 1-2 weeks in the past

#### Steps to reproduce
I'm running Mattermost 4.4.1 for macOS connecting to enterprise server 5.19.1. This problem has existed for some time. I've updated my client several times in hopes it would fix the problem, but it never does. Perhaps it's a server problem?

I'm in one channel, scrolled all the way to the bottom (newest message). I switch to another channel to look at something. Then I switch back to the previous channel. No new messages were posted there since I left, but instead of being placed at the newest message, it hangs for a few seconds and eventually places me 1-2 weeks in the past.

#### Expected behavior
Place me where I was in the conversation, not hang for a while and then place me 1-2 weeks in the past.

**Comment by amyblais** [comment]
What Mattermost server version are you on? @tgstan

**Comment by tgstan** [comment]
> enterprise server 5.19.1

**Comment by agnivade** [comment]
I believe there is already a ticket for this somewhere. Perhaps @sudheerDev or @hmhealey would know.

**Comment by tgstan** [comment]
I tried searching before opening this. If there is a ticket, apparently I didn't search for the right thing.

**Comment by sudheerDev** [comment]
@tgstan Hey, Here is a link to a forum thread https://forum.mattermost.org/t/switching-to-unread-channel-displays-arbitrarily-old-messages/9221/20. yes, there should be a ticket somewhere as well. Would you be interested in updating to 5.22v to check if this issue is resolved for you?

**Comment by tgstan** [comment]
We're on ESR now. We're not so interested in going to the latest feature release to get a bug fix. Is there any chance that could be backported to 5.19.x?

**Comment by amyblais** [comment]
There have been fixes for this in v5.20 - v5.21 but I wasn't aware that it's also reproducing on v5.19. We can backport this to v5.19 @sudheerDev.

**Comment by tgstan** [comment]
After some internal discussion, we're willing to go to v5.21 since it's fixed there.

**Comment by amyblais** [comment]
It seems from Sudheer's comment that there were additional fixes for this in v5.22, he might have more context into whether v5.21 fully fixes it.

**Comment by sudheerDev** [comment]
@tgstan I suggest for 5.22v or 5.23v which will be released soon. There was a similar issue in 5.21v as well. This happens for users with specific screen resolution and with a chrome/desktop app.  

I can suggest a couple of workarounds that help fix this problem for now. 
1. Zoom out the app by a notch. 
2. Use an alternate browser such as firefox.

**Comment by tgstan** [comment]
OK, we'll wait for v5.23 if it'll be out soon.

Thanks!
