### ISSUE TITLE
AWS S3 Prefix/Suffix

### ISSUE THREAD

**Issue by dpanic** [mattermost/mattermost-server#14498]
#### Summary
At the moment, it is only possible to use root of the bucket. It will be nice to be able to use subfolder of the bucket. Some of us have more than 50 buckets...adding even single one more is chaos.

#### Expected behavior
Be able to set S3Prefix in order to use s3://bucket_name/s3_prefix/s3_object

#### Observed behavior (that appears unintentional) 
{"level":"error","ts":1588836886.5756383,"caller":"mlog/log.go:175","msg":"Encountered an error writing to S3.","path":"/api/v4/users/ukya4pnarjdfzcor3s8grs4ohc/image","request_id":"zhjgrjesuir9pr7r8hb9k4t3qh","ip_addr":"127.0.0.1","user_id":"ukya4pnarjdfzcor3s8grs4ohc","method":"GET","err_where":"WriteFile","http_code":500,"err_details":"Bucket name contains invalid characters"}

Thank you!

**Comment by amyblais** [comment]
What Mattermost server version and OS are you on?

**Comment by dpanic** [comment]
5.22.1
Linux Ubuntu 18.04.4

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @dpanic,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by dpanic** [comment]
Hey, done: https://mattermost.uservoice.com/forums/306457-general/suggestions/40397779-aws-s3-prefix-suffix

About implementing, I am too busy at the moment. If nobody votes up, probably I will implement it myself, but not now, maybe in 2-3 months.

Thanks!

**Comment by amyblais** [comment]
Sounds good, thank you!

**Comment by dpanic** [comment]
Hey @amyblais I am interested in implementing this PR.
