### ISSUE TITLE
Refactor SQL queries in store/sqlstore/channel_member_history_store.go to use the squirrel builder

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#14502]
Mattermost is replacing the SQL queries of the store layer to use the [squirrel builder](https://github.com/Masterminds/squirrel). This help wanted issue is to change the usages of raw SQL queries in the file `store/sqlstore/channel*member_history*store.go`.

The expected way to implement this is to search in the `store/sqlstore/channel*member_history*store.go` file for all the strings containing a SQL query and rewrite them with squirrel. To do so, we must obtain the query builder using the `getQueryBuilder()` method from the store struct, and use it to build the same query that we have in the string.

You can find more information on how to use squirrel in [the official package documentation](https://godoc.org/github.com/Masterminds/squirrel).

Example Pull Request: https://github.com/mattermost/mattermost-server/pull/14393

If you have questions about the ticket or you need any help, feel free to contact `miguel.delacruz` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-24946

**Comment by rajnmithun** [comment]
Can I work on this?

**Comment by gabriel-viviani** [comment]
Hello @rajnmithun, are you still working on this one?

**Comment by oyediyildiz** [comment]
May I take this one if no one else is working on it?

**Comment by jfrerich** [comment]
This issue appears stale and I’m adding the `Up For Grabs` label.  If work is ongoing, please remove the label.  If there is an existing PR, please also link it to the issue.  Thanks!

**Comment by jecepeda** [comment]
HI @jfrerich can I take it? I would like to work on it

**Comment by agnivade** [comment]
All yours @jecepeda !

**Comment by jfrerich** [comment]
@jecepeda, that was quick!  It's all yours.  Thanks!

**Comment by jecepeda** [comment]
Hi @jfrerich @agnivade I just did the PR! If you need something more please tell me.

Best

**Comment by jfrerich** [comment]
Awesome turnaround time, @jecepeda!  I see the PR and reviewers have been assigned. Thanks for the PR and contribution!

**Comment by mgdelacroix** [comment]
Closed by https://github.com/mattermost/mattermost-server/pull/15529
