### ISSUE TITLE
Refactor SQL queries in store/sqlstore/command_webhook_store.go to use the squirrel builder

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#14504]
Mattermost is replacing the SQL queries of the store layer to use the [squirrel builder](https://github.com/Masterminds/squirrel). This help wanted issue is to change the usages of raw SQL queries in the file `store/sqlstore/command*webhook*store.go`.

The expected way to implement this is to search in the `store/sqlstore/command*webhook*store.go` file for all the strings containing a SQL query and rewrite them with squirrel. To do so, we must obtain the query builder using the `getQueryBuilder()` method from the store struct, and use it to build the same query that we have in the string.

You can find more information on how to use squirrel in [the official package documentation](https://godoc.org/github.com/Masterminds/squirrel).

Example Pull Request: https://github.com/mattermost/mattermost-server/pull/14393

If you have questions about the ticket or you need any help, feel free to contact `miguel.delacruz` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-24948

**Comment by joshuabezaleel** [comment]
May I have a shot on this? :slightly_smiling_face:

**Comment by mgdelacroix** [comment]
Sure! All yours :)

**Comment by joshuabezaleel** [comment]
Hi @mgdelacroix , I want to clarify something first if that would be okay with you.
Since I can't use `UseCount  +1` as a value for `.Set()` statement for [this](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/command_webhook_store.go#L73) particular query, should I retrieve the value of `UseCount` first to be used for the `queryBuilder` for this particular query? 

Thank you very much! :slightly_smiling_face:

**Comment by joshuabezaleel** [comment]
Hi @mgdelacroix , so sorry for the ping, just a friendly reminder on the clarification question. Thank you! Sorry for the trouble. Thank you! :slightly_smiling_face:

**Comment by mgdelacroix** [comment]
Hi @joshuabezaleel, apologies for the delay. I think for this particular case you can try using `.Set("UseCount", sq.Expr("UseCount + 1"))` to evaluate the expression as part of the set clause. Please let me know if that works and we would look into another solution if it doesn't :)

**Comment by joshuabezaleel** [comment]
No worries @mgdelacroix , I think your recommendation do the trick since the test passed. Thank you very much, truly appreciate it! :slightly_smiling_face: . I've put a PR on this :slightly_smiling_face:
