### ISSUE TITLE
Users not matching on mixed-case SAML assertions (and possibly other places)

### ISSUE THREAD

**Issue by justledbetter** [mattermost/mattermost-server#14525]
#### Summary
Systems that use mixed-case in the attribute targeted for username may encounter errors logging users in.

#### Steps to reproduce
* Create a user account in SAML provider, ensure username attribute is all lowercase.
* Login and observe the user account is created in Mattermost with an all-lowercase username
* Logout from Mattermost and modify the user's profile in SAML provider to use Mixed Case username attribute
* You should get an error stating that the user could not be created because they already exist.

#### Expected behavior
Mixed-case usernames should not break the system (just as mixed-case e-mails should not).

#### Observed behavior (that appears unintentional) 
On user creation, the user's profile is passed through a basic sanitization routine in `model/user.go:337-338`.  This converts the user's e-mail address and username to all lowercase (and removes disallowed unicode characters).

In the event that the account doesn't exist (if the server allows SAML JIT), assuming the SAML code calls the standard model functions to create the new user account, this will also get cleaned up. (I'm making assumptions about how the Enterprise code looks; I may be way off base).

However, if you look at the way MM pulls users up when they're logging in, we'll have a mismatch if the SAML assertion comes in anything other than all lowercase, since (I assume) the SAML code is calling `SqlUserStore.GetByAuth()` from `store/sqlstore/user_store.go:928`.

This function adds this authdata directly to the where clause, presumably from the SAML assertion without any modification in `store/sqlstore/user_store.go:934`.

Note that there may be additional malware possible using unsanitized unicode at this point in time as well, if it's not checked in the SAML assersion prior to here.  This is hopefully mitigated by the fact that users are hopefully not able to set their SAML assertions to random strings.

#### Possible fixes
Change user_store.go:934 to:

```
Where("u.AuthData = ?", strings.ToLower(authData)).
```

And user_store.go:988 to:

```
query := us.usersQuery.Where("u.Username = ?", strings.ToLower(username))
```

And user_store.go:1006-1010 to:

```
query = query.Where("Username = ? OR Email = ?", strings.ToLower(loginId), strings.ToLower(loginId))
...
query = query.Where("Username = ?", strings.ToLower(loginId))
...
query = query.Where("Email = ?", strings.ToLower(loginId))
```

If there is a function gatekeeping all of these that I'm missing, my apologies for the oversight.

(Note that we could instead change the SQL statement itself to "u.AuthData = tolower(?)" for marginally better performance, but this would require a new index.)

**Comment by justledbetter** [comment]
Thinking about it further, I'm incorrect in thinking the SQL `xxx = lower(?)` would require an additional index.  It was late and I was being silly.

Would definitely recommend doing this in-database rather than in Golang, since databases are generally designed to be optimally efficient with stuff like this.

**Comment by amyblais** [comment]
@justledbetter What Mattermost server version are you on? What OS and version are you on?

**Comment by justledbetter** [comment]
5.22.0
RHEL 7

(All files referenced in my report are from the master branch.)

**Comment by sbishel** [comment]
Should definitely be investigated by Enterprise team.  Thanks @justledbetter

**Comment by sbishel** [comment]
Jira ticket - https://mattermost.atlassian.net/browse/MM-25282

**Comment by justledbetter** [comment]
I'm working on writing a patch (and associated tests) for this, hope to have a PR for it shortly.

**Comment by justledbetter** [comment]
Fix submitted via PR-14587
