### ISSUE TITLE
Mobile Log in doesn't pull server

### ISSUE THREAD

**Issue by SemperRuminare** [mattermost/mattermost-server#14553]
#### Summary
Mobile Users experience a blank page with limited functionality that sometimes breaks Mattermost. Workaround required to restore functionality. Believe it is tied to pulling the server the user is on

#### Steps to reproduce
Current User Id: 381cipon6tdhfkghshqp7uey5r 
Current Team Id: Server 
Version: 5.22.0 (Build 5.22.0) 
App Version: 1.30.1 (Build 287) App Platform: android 

I believe this is tied to pulling the correct team Id, because the team is defaulted to "Server" in place of Team Id. I have heard of this issue on both Android and iOS, and both admin and normal accounts. Our workaround (below) has worked on both.

I have tried limiting my team to 1 to see if it would default me into that particular team. I still experienced this issue even being in 1 team. This then limited our workaround, as the team menu was not available.

#### Expected behavior
When logging in, you should be directed the last team you were messaging on.

#### Observed behavior (that appears unintentional) 
Instead of getting the last team, I end up at a blank screen that looks like this:
![Screenshot_20200512-143629_Mattermost](https://user-images.githubusercontent.com/2375683/81764614-f3402680-949f-11ea-84fa-8770a4c2b3fd.jpg)

I believe it might be tied to pulling the correct team, as the team ID returns "Server" instead of the team ID.
Current User Id: 381cipon6tdhfkghshqp7uey5r Current Team Id: Server Version: 5.22.0 (Build 5.22.0) App Version: 1.30.1 (Build 287) App Platform: android 

Swiping left gives me a menu with no channels. I am able to find users, and DM them, but only that DM thread is available. Typing in the search yields an critical error where MM needs to relaunch.
![Screenshot_20200512-143640_Mattermost](https://user-images.githubusercontent.com/2375683/81764615-f3d8bd00-949f-11ea-8095-0a3830b1ddd8.jpg)

Swiping right gives me a normal menu screen. I am able to access all functionality fairly normally, except for recent mentions.
![Screenshot_20200512-143651_Mattermost](https://user-images.githubusercontent.com/2375683/81764616-f3d8bd00-949f-11ea-9541-59348ec36606.jpg)
![Screenshot_20200512-143704_Mattermost](https://user-images.githubusercontent.com/2375683/81764617-f4715380-949f-11ea-981a-28fa4f968290.jpg)

Swiping left twice gives me the team list. When I click a team, all normal functionality is restored. When the user has only 1 team, this workaround is not accesible.
![Screenshot_20200512-143725_Mattermost](https://user-images.githubusercontent.com/2375683/81764618-f4715380-949f-11ea-8f21-cd013221c461.jpg)

#### Possible fixes
I'm not sure if this is tied to pulling the team or our DoD Instance that is the root of this issue. Ideally, if it cannot find the server it should not default to a blank state with no way to frix.

**Comment by amyblais** [comment]
@SemperRuminare What Android version are you on?

**Comment by SemperRuminare** [comment]
Version 10 (Kernel 4.9.186)

**Comment by amyblais** [comment]
@SemperRuminare Would you be able to share more details on what you mean by "defaulted to Server"?

**Comment by SemperRuminare** [comment]
Yes, per "steps to reproduce" section, current team Id is "Server," not any particular Team Id.

Current User Id: 381cipon6tdhfkghshqp7uey5r
Current Team Id: Server
Version: 5.22.0 (Build 5.22.0)
App Version: 1.30.1 (Build 287) App Platform: android

**Comment by amyblais** [comment]
@SemperRuminare I asked our team about this but they're unsure about where the "Server" team id comes from. Did you start seeing this after an upgrade or has this been like this before? Have you made any recent changes to your server?

**Comment by SemperRuminare** [comment]
No changes recently - we're on 5.22.0 and have been since the middle of April. We're on the DoD server.

**Comment by SemperRuminare** [comment]
So I believe this issue started when I upgraded to 1.30.1

**Comment by enahum** [comment]
@SemperRuminare do you happen to have the config setting for `ExperimentalPrimaryTeam` set ?

**Comment by enahum** [comment]
Also are you getting the current team id from the `Report a problem` option?

I'm trying to  identify where in the codebase the word `Server` might get set as the id, but I cannot find anything like that anywhere...

**Comment by enahum** [comment]
and another question, is it always the same word `Server` as the team Id ?

**Comment by enahum** [comment]
do you know if this happens right after opening a push notification or does it happen at login?

**Comment by SemperRuminare** [comment]
> Also are you getting the current team id from the Report a problem option?

Yes, this was autogenerated.

> do you know if this happens right after opening a push notification or does it happen at login?

This happens on login. I am able to DM people but it only allows me to see that DM channel. If I am not logged in I don't get push notifications so I can't test that.

> and another question, is it always the same word Server as the team Id ?
Yes. Tested again. Same word.

> @SemperRuminare do you happen to have the config setting for ExperimentalPrimaryTeam set ? 

Will get back to you later today when I can pull the config.

**Comment by SemperRuminare** [comment]
Yes, it is set to: "ExperimentalPrimaryTeam": "Welcome" 

Should this be lowercase to be the same as our team url?

**Comment by enahum** [comment]
> Should this be lowercase to be the same as our team url?

Its something that I’m going to test. Is everyone a member of that team?

Regardless Welcome != Server, but will try and figure it out

**Comment by SemperRuminare** [comment]
Changed to lowercase, didn't fix the issue.

![image](https://user-images.githubusercontent.com/2375683/82087280-c701f100-96bd-11ea-8fbb-5ad9f44cf819.png)

**Comment by enahum** [comment]
The thing is it seems you can reproduce this easily and I have yet to reproduce it once :/

**Comment by enahum** [comment]
@SemperRuminare that’ll be great, can we coordinate for monday? You can look me up in the community.mattermost.com server

**Comment by SemperRuminare** [comment]
During our call, Elias and I discovered that teamID is not "Server" but it is null
Current User Id: 381cipon6tdhfkghshqp7uey5r
Current Team Id: 
Server Version: 5.22.0 (Build 5.22.0)
App Version: 1.30.1 (Build 287) App Platform: android

**Comment by SemperRuminare** [comment]
This error was worked around by disabling "ExperimentalPrimaryTeam" on config, it can't find primary team for some reason - not sure why, Elias is going to do some more testing on his end.

**Comment by shred86** [comment]
Having "ExperimentalPrimaryTeam" enabled appears to also hide the + icon/button on the left hand side below teams. I thought this was just a flaw in the current UI design where only users with the permission to add teams could see the + icon/button, but it seems to have been based on having "ExperimentalPrimaryTeam" enabled.
