### ISSUE TITLE
Direct group messages disappear from "direct messages" list after opening. 

### ISSUE THREAD

**Issue by daanvV** [mattermost/mattermost-server#14564]
#### Summary
Direct group messages disappear from "direct messages" list after opening. 

#### Steps to reproduce
Set direct messages sorted to "recent"
Someone sends you a direct group message. 
Open the message (in my case I opened it on my OnePlus phone). Exit the app. 
Try to find the message again on mattermost web app under direct messages --> not able to find. 
If you open the "more" option below you can find it by searching for the person that sent it to you (if you remember who that is). 

I am using brave browser, windows 10. 

#### Expected behavior
Expected to find the group direct message at the top (most recent) of the direct messages section. 

#### Observed behavior (that appears unintentional) 
Group direct message disappears. 

#### Possible fixes
No idea.

**Comment by amyblais** [comment]
@daanvV Would you be able to help share more information about your environment from here: https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by daanvV** [comment]
I don't know how to check logs.. hopefully this helps
Phone
![WhatsApp Image 2020-05-13 at 21 07 09](https://user-images.githubusercontent.com/23032482/81854172-d1a57480-955d-11ea-832e-05cb5b8461b8.jpeg)
Web
![image](https://user-images.githubusercontent.com/23032482/81853920-6e1b4700-955d-11ea-8681-1a63617763f1.png)

**Comment by amyblais** [comment]
Thanks, opened a ticket here https://mattermost.atlassian.net/browse/MM-25146.

**Comment by amyblais** [comment]
This is fixed in upcoming Mobile app v1.32 release,
