### ISSUE TITLE
Collapsing public channels via chevron makes the channel filter appear broken

### ISSUE THREAD

**Issue by Matterchen** [mattermost/mattermost-server#14566]
#### Summary
If you (inadvertently) collapse the public channel list, clicking on the channel filter button has no effect and appears to be broken.

#### Steps to reproduce
1. v5.22.3
2. Click on the collapse public channel chevron (see image)
3. Click on the larger channel filter button

<img width="248" alt="Collapse channels" src="https://user-images.githubusercontent.com/33878967/81870667-3398b680-952b-11ea-9d70-301414f19612.png">

#### Expected behavior
Expect to show/hide unread channels.

#### Observed behavior (that appears unintentional) 
Public channel list remains unchanged (shows unread channels only).

It was very difficult to see the chevron state, and only after using a different browser and several minutes did I realize what was happening.

#### Possible fixes
The collapse public channel chevron is redundant. Either remove it, or make the channel filter button override the chevron state.

**Comment by amyblais** [comment]
@Matterchen Would you like to submit this feedback via the channel sidebar feedback survey here: https://docs.google.com/forms/d/e/1FAIpQLSdfhLIbtfXR6507tSbufjKphoYdUDD7b7WE7AJHZyKB8oom2w/viewform?

If you prefer not to I can open a Jira bug ticket for this.

**Comment by amyblais** [comment]
@Matterchen Following up on this, would you like to submit this via the feedback form, or would you prefer that I open a Jira ticket for this?

**Comment by chenilim** [comment]
Thanks Amy! I missed the earlier email, but have just filed feedback on the form, linking to this issue.
