### ISSUE TITLE
LaTeX Markdown

### ISSUE THREAD

**Issue by SemperRuminare** [mattermost/mattermost-server#14582]
#### Summary
LaTeX markdown does not work in 5.22.0 per instructions in markdown guide.
https://github.com/mattermost/mattermost-server/issues/11195
https://docs.mattermost.com/help/messaging/formatting-text.html

#### Steps to reproduce
Typed:
```latex
X_k = \sum_{n=0}^{2N-1} x_n \cos \left[\frac{\pi}{N} \left(n+\frac{1}{2}+\frac{N}{2}\right) \left(k+\frac{1}{2}\right) \right]
```

#### Expected behavior
Same as markdown guide
![image](https://user-images.githubusercontent.com/2375683/82072704-1cca9f00-96a6-11ea-94a2-80aae4942236.png)

#### Observed behavior (that appears unintentional) 
Attempted to copy example from markdown guide gives me this output:
![image](https://user-images.githubusercontent.com/2375683/82072536-e0973e80-96a5-11ea-9da4-245796f2896d.png)

#### Possible fixes
I think this was moved to the plugin only, if that's the case, just need to update markdown guide.

**Comment by amyblais** [comment]
@SemperRuminare What OS and version are you seeing this on?

**Comment by SemperRuminare** [comment]
Server: 5.22.0
OS: Windows 10

**Comment by amyblais** [comment]
@SemperRuminare I wasn't able to reproduce but happy to investigate further. Do you see any log errors or console errors when this issue happens? Is this on webapp or desktop app?

**Comment by SemperRuminare** [comment]
Web-app, no log errors or console errors.

**Comment by coreyhulen** [comment]
I think `Enable Latex Rendering` is default off now?  That prop use to be default on, I think it got switched to default off for security along the way somewhere.  We should add a note to the documentation to make it more obvious.  @amyblais can you help verify it's default off and add a note in the docs.

**Comment by SemperRuminare** [comment]
Yes, this was the issue. It works when I enable it in the system console. D'uh!

**Comment by amyblais** [comment]
Fixed via https://github.com/mattermost/docs/pull/3631
