### ISSUE TITLE
[feature request] render percent encoding to readable characters in links pasted into chat

### ISSUE THREAD

**Issue by aol-nnov** [mattermost/mattermost-server#14602]
When pasted into chat, render percent-encoded URLs into readable characters

i.e. instead of displaying https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D1%8B

show https://ru.wikipedia.org/wiki/Географические_координаты

I propose changing text only, not the href of an `<a>` tag

xposted from https://github.com/mattermost/desktop/issues/1294

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @aol-nnov,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by aol-nnov** [comment]
@amyblais I tried to, but it seems, uservoice is banned in our country, as I mentioned in the original ticket. So, I've headed directly to issue tracker.

**Comment by amyblais** [comment]
No worries, I've added the feature request here https://mattermost.uservoice.com/forums/306457-general/suggestions/40524850-render-percent-encoding-to-readable-characters-in.

**Comment by aol-nnov** [comment]
@amyblais this idea got 13 votes already! Any chance this issue might be reopened?

Thank you!
