### ISSUE TITLE
New message indicator is broken when a webhook owned by you posts to channel

### ISSUE THREAD

**Issue by WGH-** [mattermost/mattermost-server#14612]
#### Summary
When there're unread messages that are posted by a webhook you own, the "Unread messages start here" indicator is not shown.

#### Steps to reproduce
1. Create a webhook.
2. Post some messages through it to a channel that's not currently open on your screen.
3. Open a channel.

#### Observed behavior (that appears unintentional) 

The channel will show that there's some messages unread (indicated by the bold text in the sidebar). However, there will be either no "Unread messages" separator at all, or it will be before message posted by some other user, if any.

#### Possible fixes
I think this is caused by the fact that webhook messages are attributed to its creator, and mattermost-redux skips own messages when calculating where to place the indicator:

https://github.com/mattermost/mattermost-redux/blob/4aa23838f96f94326bdc8b291d7674079da8bb5d/src/utils/post_list.ts#L101-L110

I'll send a PR shortly.

**Comment by WGH-** [comment]
Another fix would be to not attribute webhook message to its owner.  I think it might be even better.

**Comment by amyblais** [comment]
@WGH- What Mattermost server version did you see this on and do you know if this is a new issue?

**Comment by WGH-** [comment]
I don't think this is a new issue. I've seen it on 4.8.0, 5.12.0 and 5.23.0.

**Comment by WGH-** [comment]
There's another case where attributing webhook messages to its owner cause sweird behaviour. When your webhook mentions someone not in the channel, you see system message "XXX annd YYY were mentioned but they are not in the channel. Would you like to add them to the channel? They will have access to all message history.". This is very annoying when your webhook is doing bridging from another chat system.

I guess it's better to stop attributing webhook messages to its owner rather than patch `!isFromWebhook(post)` all over the place.

**Comment by amyblais** [comment]
Opened a ticket for tracking: https://mattermost.atlassian.net/browse/MM-25571.
