### ISSUE TITLE
Plugins - those that modify the UI aren't working

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-server#14622]
On CentOS 6 64bit, 5.22 was working fine and I upgraded to 5.23, all plugins were active too _(I tend to check them, eg, I also did this at some point https://github.com/mattermost/mattermost-server/issues/13913#issuecomment-587882355 else they're not used)_ but a couple of days later a sudden power issue restarted the server. Everything appeared to be working ok, but I don't remember checking plugins too.

While today I did look, and the plugins, while "active" in console, don't actually have triggers in the UI (web app or desktop app).

Log of a restart _(yes, I've downgraded to 5.22 thinking it will help, but no, log is the same on 5.23)_: https://gist.github.com/licaon-kter/e3c17b1883bfad81e41a238143503eab

Plugins section of config: https://gist.github.com/licaon-kter/49fe5ba7dc84bb040dc60d95d645b1bb

## What do I see?
Slash based plugins like meme, remind, poll can be triggered ok.
UI based plugins like file-list, jitsi, draw can't be used since their UI elements _(buttons)_ aren't actually on screen.

Any thoughts?

**Comment by lieut-data** [comment]
@licaon-kter, can you share your browser's console log on a fresh load? It should show what plugins are being loaded, and any corresponding errors.

**Comment by licaon-kter** [comment]
Didn't have time to look in depth yet, but today the buttons were present (no restart or anything modified server side). I'll try to grep the logs and find out, if possible, when they started to work.

**Comment by licaon-kter** [comment]
Logs don't help, there's no entries that would suggest a "switch to working".

Also, unixtimestamps, really? What ingests your logs?

/closed for now
