### ISSUE TITLE
Migrate AppError to error from store/sqlstore/compliance_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#14639]
Mattermost is migrating all usages of the `AppError` type to the more idiomatic `error` type. `AppError` is a loaded error type containing fields like HTTP Status code which is not really necessary for errors coming from the DB layer. We should migrate to using normal types satisfying the error interface.

This ticket is about migrating all usages of AppError from `store/sqlstore/compliance_store.go` to return a normal error. The migration should use the error types defined in `store/errors.go`. If the need should arise to add another specific error type, feel free to add it. For any generic error that is not something like an invalid input, or something not found, we can just wrap the error using `errors.Wrap(f)` and return it.

And then in the app layer, we would need to convert the `error` type to the usual `AppError`. Essentially moving the `AppError` creation from the store layer to the app layer. This means we need a switch case to check for the type of error and appropriately convert to the correct AppError. It can be something like:

```go
if _, err := a.Srv().Store.Bot().Update(bot); err != nil {
	var nfErr *store.ErrNotFound
	var appErr *model.AppError
	switch {
	case errors.As(err, &nfErr):
		return model.MakeBotNotFoundError(nfErr.Id)
	case errors.As(err, &appErr): // in case we haven't converted to plain error.
		return appErr
	default: // last fallback in case it doesn't map to an existing app error.
		return model.NewAppError("DeleteBotIconImage", "app.bot.patchbot.internal_error", nil, err.Error(), http.StatusInternalServerError)
	}
}
```

Also note that the error codes need to be changed from being a store level code (`store.<>.edit.error`) to something like `app.<>.edit.internal_error`.

Example Pull Request: #14339

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-25478

**Comment by agnivade** [comment]
Done !

**Comment by agnivade** [comment]
Hi @farah - how is it going with this ? Please let us know if there's anything we can help with.  :)

**Comment by farah** [comment]
@agnivade Apologies for the delay! I was working on this at this moment. I had some confusion but I think I sorted it out by reading previous migration PRs, I hope to submit the PR by tonight.

**Comment by agnivade** [comment]
Awesome. Looking forward to it. :)

**Comment by farah** [comment]
One quick question, in the original PR you had:

```
Since this is a gradual migration, this means that the error inspection
code will be duplicated across the app layer whenever a store method
is invoked. But all of that should go away once we start propagating
the errors higher up the hierarchy.
```

Do you have an example of the last sentence? Not sure how the code duplication will go away .

**Comment by agnivade** [comment]
The example won't come until we actually start the migration of the app layer errors too :)

By "de-deduplication", I mean that the the switch cases for different error types will merge to a single app layer call rather than multiple store layer call inside a single app method.

For example, 

```go
func (a *App) SomeMethod() (t *T, err *AppError) {
 err := store1call()
 switch {
  ..
  ..
 }

 err = store2call()
  switch {
   ..
   ..
  }
}
```

Would change to 
```go
func (a *App) SomeMethod() (t *T, err error) {
 err := store1call()
 if err != nil {
  return errors.Wrap(err, "store1call")
  }

 err = store2call()
  if err != nil {
  return errors.Wrap(err, "store2call")
  }
}
```
And the switch case will move to the api layer. Does that help clarify ?

**Comment by farah** [comment]
Thanks for the great explanation @agnivade, makes sense now.
