### ISSUE TITLE
Post search returns empty results when specifying channel and exclusions

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-server#14641]
#### Summary
At first, We can get all the posts in the channel if we do a search with only a query that specifies the channel (e.g.: `in:town-square`). However, if we add an exclusion word to that query, the search results will be empty. (e.g.: `in:town-square -test`)

(If we specify both an exclusion word and a search word, it will return a matching result. (e.g.: `in:town-square foo -test`)

In https://community.mattermost.com/core, that query (e.g.: `in:town-square -test`) works fine, so this issue may not reproduce in Elasticsearch environment.

* **My environment**
  * Mattermost: v5.22, v5.23 (Not Enterprise)
  * DB: MySQL

#### Steps to reproduce
1. Search posts with a query like `in:channel_name -test` in Mattermost UI

#### Expected behavior
* Return results including all posts that are posted in `channel_name` and aren't having the word `test`.

#### Observed behavior (that appears unintentional) 
* Returned empty results

#### Possible fixes
I've done a little investigation on how to fix it, but I haven't come to a solution.

MySQL seems to return empty results when searching only for exclusion words.
https://dev.mysql.com/doc/refman/5.7/en/fulltext-boolean.html
> Note: The - operator acts only to exclude rows that are otherwise matched by other search terms. Thus, a boolean-mode search that contains only terms preceded by - returns an empty result. It does not return “all rows except those containing any of the excluded terms.”

I also considered adding a wildcard as a search word  in the following location when only an exclusion word was specified, but it didn't work.
https://github.com/mattermost/mattermost-server/blob/aad76a13e8381fc2a7c79d37d842d530c450a728/store/sqlstore/post_store.go#L1240

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-25508.

**Comment by kaakaa** [comment]
I tried to reproduce this in v5.27 and v5.28, but this issue is not happened. This issue seems to be resolved. Thanks 👍
