### ISSUE TITLE
Document theme CSS variables in plugin development guide

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#14645]
Sometimes plugins just have to rely on injecting CSS into the page for styling, for example, when a 3rd party React component doesn't accept custom styling. This creates a problem when trying to match Mattermost's dynamic theme with the component.

However, one can very easily use CSS variables which Mattermost already has over at https://github.com/mattermost/mattermost-webapp/blob/master/sass/base/_css_variables.scss

I just discovered it while debugging something and feel it would have made my life easier if I knew this existed all this time 😛 .

I'd like to suggest documenting this officially as a way of styling plugins dynamically based on the theme, in addition to [`theme` React prop](https://developers.mattermost.com/extend/plugins/webapp/reference/#theme)

**Comment by amyblais** [comment]
@harshilsharma Thanks for the report, would you like to re-open this issue in the developer docs repo https://github.com/mattermost/mattermost-developer-documentation/issues?

**Comment by harshilsharma63** [comment]
@amyblais done. The new issue is over here - https://github.com/mattermost/mattermost-developer-documentation/issues/630
