### ISSUE TITLE
"bin/mattermost permissions reset": System admin can no longer manage emoji.

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#14642]
## Summary
I just recently discovered `bin/mattermost permissions reset`.

After running it, the the System Admin can no longer manage emoji and I cannot give myself said permissions either.

#### Steps to reproduce
+ Run: `bin/mattermost permissions reset`.
+ Restart mattermost.service

#### Expected behavior
`Full permissions granted to System Administrators.` Actually meaning having all permissions. :)

#### Observed behavior (that appears unintentional) 
![screen_20200524_110544](https://user-images.githubusercontent.com/5354356/82750180-a406c980-9dae-11ea-9d98-09a417abbcdf.png)

![screen_20200524_110734](https://user-images.githubusercontent.com/5354356/82750224-da444900-9dae-11ea-9dd0-7663ca2a64cf.png)

#### Possible fixes
Maybe:
+ Fix the `permissions reset` command to re-add all permissions.
+ Make the `System Admin` status (`manage_system`?) bypass almost all permission checks.
+ Allow the `System Admin` status (`manage_system`?) to manage other system-admin priviledges. (I dont like Sysadmins to be able to edit other's posts, for example)

**Comment by someone-somenet-org** [comment]
The config has `"RestrictCustomEmojiCreation": "all"`, but the config option to change that as described here: https://docs.mattermost.com/administration/config-settings.html is no longer present?

**Comment by amyblais** [comment]
Opened a bug ticket here: https://mattermost.atlassian.net/browse/MM-25507.
