### ISSUE TITLE
Mattermost is not able to distribute messages after VPN tunnel creation and closing

### ISSUE THREAD

**Issue by avolynet** [mattermost/mattermost-server#14653]
#### Summary
Message to all channel members is not sent after VPN tunnel creation and closing

#### Steps to reproduce
1. Start Mattermost (I can write messages) 
2. Open a VPN tunnel via GPC
3. Upload files and close tunnel
4. Post a message in a channel in Mattermost 

We are you using: Mattermost Version: 5.21.0 Database Schema Version: 5.21.0 
We are experiencing the issues with the browser webapp using different browsers: Chrome, IE

#### Expected behavior
Message was sent in the channel to all members

#### Observed behavior 
Mattermost is not able to distribute the message. The message shows “Retry/Cancel” in the upper right corner. Nothing happens. I cannot receive messages any more. 
After restart and reconnect to the Mattermost server, my message is gone.
We just tried to send a content like this: 
![image](https://user-images.githubusercontent.com/65913499/82830753-3d250580-9ebf-11ea-82e1-90d1fb25b28c.png)

#### Possible fixes
No ideas.  It seems that the Mattermost client looses it´s network connection when I start the GPC VPN.

**Comment by amyblais** [comment]
@avolynet 
1. Can you help with your environment details from here for all affected users https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?
2. What do you mean by "Message was sent in the channel to all members"? Does it mean some people see the message and others don't?

**Comment by avolynet** [comment]
@amyblais 

I updated the description and provided more information
BR

**Comment by amyblais** [comment]
@avolynet Do you see any log errors or developer console errors?

**Comment by Willyfrog** [comment]
it might be that the VPN software is messing with your DNS?
can you open the devtools, get into the network tab and do the whole process and see what the response is when you post the message?
does reloading the tab fixes the issue?

**Comment by amyblais** [comment]
Closing as this is an old issue, feel free to re-open if the issue is back,
