### ISSUE TITLE
Cant move a channel to a different teamspace due to missing users

### ISSUE THREAD

**Issue by pixelbrackets** [mattermost/mattermost-server#14681]
#### Summary
Cant move a channel to a different teamspace due to missing users.

#### Steps to reproduce
Mattermost 5.23.0

1. Move a channel from previous teamspace to new teamspace using `./bin/mattermost channel move [new team] [previous team]:[channel] --username [username] --remove-deactivated-users`

#### Expected behavior
Move the channel.

#### Observed behavior (that appears unintentional) 
Error message `Unable to move channel` `error: MoveChannel` is shown, because not all users of the channel in the previous team are members of the new team.

However, I cant use the commandline to solve this issue. I can only add or remove users, but not list all users of a channel or team.

#### Possible fixes
- Provide a command to list all users of a channel
  - This could be used to add the users to the new team using `./bin/mattermost team add`
- …or provide an option to migrate missing users automatically (if an user of the channel is missing in the new team, then add the user as member in this very moment)

**Comment by amyblais** [comment]
@grundleborg Do we currently have any bug or feature ticket open related to this?

**Comment by grundleborg** [comment]
We won't be fixing this in the built-in legacy CLI, but we do have a ticket to address it in mmctl - https://mattermost.atlassian.net/browse/MM-21464
