### ISSUE TITLE
TeX code cannot be highlighted when LaTeX rendering is enabled

### ISSUE THREAD

**Issue by schtandard** [mattermost/mattermost-server#14683]
#### Summary
When the Enable Latex Rendering option is enabled to allow rendering of math formulas, TeX source code cannot be highlighted anymore.

in order to allow users to use codehighlighting when sharing la/tex code, we are decided to add two new codeblock suffixes:
- texcode
- latexcode
which won't get pickup by the latex renderer, and can be used to show highlighted code.

[Jira Ticket](https://mattermost.atlassian.net/browse/MM-25668)

#### Steps to reproduce
Set the Enable Latex Rendering to true, then try to post something like
````text
```tex
\documentclass{article}

\begin{document}

Hello World!

\end{document}
```
````

#### Expected behavior
Of the language names `tex` and `latex`, only `tex` is mentioned in the [text formatting documentation][formatting-doc] section on syntax highlighting, while only `latex` is mentioned in the section on rendering math. Thus, the code should be highlighted as TeX code, like this:
```tex
\documentclass{article}

\begin{document}

Hello World!

\end{document}
```

#### Observed behavior (that appears unintentional) 
The code is interpreted as MathJax input and thus marked as incorrect by printing it back in red.
In practice this means that teams that want to talk about TeX code cannot render LaTeX formulas and vice versa.

#### Possible fixes
I can imagine two ways to fix this.
- One could distinguish between the language identifiers `tex` and `latex` to make one of them render math formulas and one of them highlight source code.
- More in line with the integration of MathJax into Markdown in other services (e.g. [Stackexchange][math.sx]), one could switch to a syntax based on `$` for rendering math. A syntax of single dollar signs (`$a + b = c$`) for inline math and double dollar signs (`$$a + b = c$$`)  for display math would also be more in line with TeX syntax.

  Since rendering math is something totally different from code blocks, a separate syntax would probably be more appropriate anyways. It would break backwards compatibility somewhat, though.

[formatting-doc]: https://docs.mattermost.com/help/messaging/formatting-text.html
[math.sx]: https://math.stackexchange.com/

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-25668.

**Comment by amyblais** [comment]
@schtandard This was determined to be a feature request, would you be open to creating a feature request issue for this here https://mattermost.uservoice.com/forums/306457-general?

**Comment by schtandard** [comment]
@amyblais I created a [feature request][feature-request] for the dollar sign syntax.

However, I would still consider the conflict between displaying TeX source code and parsing MathJax input a bug which should
- either be fixed by making ```` ```tex```` still highlighting source code while ```` ```latex```` is interpreted as MathJax input, as documented
- or be documented as intended behavior by adding `latex` to the list of supported languages for code highlighting and adding `tex` to the documentation of the Enable Latex Rendering option. A warning that enabling this option removes the ability to highlight TeX source code should also be added.

Obviously, I would prefer the first option, though the second one would certainly be realized more easily.


[feature-request]: https://mattermost.uservoice.com/forums/306457-general/suggestions/40576936-use-dollar-signs-for-mathjax-input-instead-of-pars

**Comment by amyblais** [comment]
@hmhealey Can you help confirm that I should open a bug ticket for above ^

**Comment by hmhealey** [comment]
Yeah, it sounds like a bug. Back when Latex rendering was added, I'm pretty sure it was supposed to use `tex` to print the source code and `latex` to render it properly. That must've changed at some point.

**Comment by hmhealey** [comment]
Actually, I was wrong about that. They both rendered the latex [from the beginning](https://github.com/mattermost/mattermost-server/pull/1351/files#diff-679db143ef363d2321bf05339657483cR72).

**Comment by Willyfrog** [comment]
after grooming we came to the conclussion to fix it by adding two new suffixes for codeblocs:
`'''texcode` and `'''latexcode` that displays codehighlight but doesn't trigger the renderer.

**Comment by hmhealey** [comment]
For anyone interested in working on this, if you have any questions, feel free to message me here or on our community server (https://community.mattermost.com) where I'm `@harrison`

**Comment by 14Richa** [comment]
Hey team, I am not able to reproduce the above issue. can I get more context n this?

**Comment by hmhealey** [comment]
@14Richa Basically, there's no way to post raw Latex or Tex code and have it appear with proper syntax highlighting currently. Back when Latex support was added, we added it by replacing the tex and latex languages in the code block with the rendered latex, so there's no way to actually use syntax highlighting with latex.

For example, posting
~~~
```latex
\sqrt{x * y + 2}
```
~~~
on GitHub looks like
```latex
\sqrt{x * y + 2}
```
but in Mattermost, it looks like
![Screen Shot 2020-07-16 at 10 38 04 AM](https://user-images.githubusercontent.com/3277310/87684618-74da5c00-c750-11ea-8d9a-06ff0618882c.png)
and there's no way to have it post the raw code like GitHub.

We want to make it so that
~~~
```latexcode
\sqrt{x * y + 2}
```
~~~
posts a syntax-highlighted code block in Mattermost.

**Comment by 14Richa** [comment]
Got it @hmhealey. Thanks! :)

**Comment by 14Richa** [comment]
> Actually, I was wrong about that. They both rendered the latex [from the beginning](https://github.com/mattermost/mattermost-server/pull/1351/files#diff-679db143ef363d2321bf05339657483cR72).

Hey @hmhealey, I was working on this issue, but was not able to find markdown.jsx file in web app codebase. Can you please help?

**Comment by Willyfrog** [comment]
I think it moved [to the webapp repo](https://github.com/mattermost/mattermost-webapp/tree/master/utils/markdown)

**Comment by 14Richa** [comment]
Cool. @Willyfrog Thanks! :)

**Comment by hmhealey** [comment]
Yeah, that's right. It's `renderer.tsx` in the linked folder. The original PR that I linked is really old, and we've moved stuff around a lot since then.

**Comment by 14Richa** [comment]
Hey @hmhealey, I have created a Pr for the above issue. As it is my first contribution it would be great if I can get a feed back. :)
