### ISSUE TITLE
In mattermost message box when iam copy pasting some content its happening twice  

### ISSUE THREAD

**Issue by richhamseth** [mattermost/mattermost-server#14697]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
While pasting some data in text box its getting entered twice 

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Version: 5.22.0
Build Number: 5.22.1

#### Expected behavior
Describe your issue in detail
While pasting some data in text box its getting entered twice 

#### Observed behavior (that appears unintentional) 
While pasting some data in text box its getting entered twice 
eg: hello worldhello world

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@richhamseth Would you be open to help fill in the requested details here too?

**Comment by amyblais** [comment]
Closing as this is an old issue, feel free to re-open if the issue still reproduces on the latest version,
