### ISSUE TITLE
After moving a channel to a different new team using cli commands, the channel still shows in the old team as well as in the new team

### ISSUE THREAD

**Issue by richhamseth** [mattermost/mattermost-server#14696]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Migrated created private channel into new team it reoccupy in old team as well

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Version: 5.22.0
Build Number: 5.22.1

#### Expected behavior
1. I created two team in mattermost (eg: team1 and team2) 
2. next i created private channel in team1
3. I tried to move that channel to team2 using cli commands 
4. it got migrated but channel occurs in the team1 as well 

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
when i opened that channel in my old team (team1) its keep on loading
when i opened that channel in my new team (team2) i can able see my text messages in that
my intention is like i don't want that moved channel to be in that old channel

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by richhamseth** [comment]
@amyblais updated

**Comment by amyblais** [comment]
@richhamseth Do you see any Mattermost log errors from the time this issue occurred?

**Comment by richhamseth** [comment]
@amyblais no i didn't noticed any error logs

**Comment by amyblais** [comment]
@richhamseth 
1. Thanks, do you see any Console log errors?
2. Are there any deactivated users in the channel you tried to move?
3. Are all the members in the channel you tried to move already in the new team?
4. What CLI command did you use to move the channel to the new team?

**Comment by richhamseth** [comment]
> @richhamseth
> 
> 1. Thanks, do you see any Console log errors?
> 2. Are there any deactivated users in the channel you tried to move?
> 3. Are all the members in the channel you tried to move already in the new team?
> 4. What CLI command did you use to move the channel to the new team?

1. I didn't noticed any errror logs
2. no deactivated users are their in that channel
3. yes all the members in the channel i tried to move already in the new team
4. mattermost channel move teamName channelID --username name

**Comment by richhamseth** [comment]
@amyblais thanks for your support, Actually I have updated my mattermost server(from 5.22.0 to 5.23.0 ) day before yesterday. I tried the same thing again it worked without any issue
