### ISSUE TITLE
Channels created through the API are duplicating in the client

### ISSUE THREAD

**Issue by ttauri** [mattermost/mattermost-server#14713]
#### Summary
Channels created through the API are duplicating in the client

#### Steps to reproduce
Mattermost Version: 5.21.0
Database Schema Version: 5.21.0

- Create a channel using API
- Add users

#### Expected behavior
Only one new channel is displayed in the client.

#### Observed behavior
If channel grouping option (Account Settings -> Side bar -> Channel grouping and sorting)
is set to "Channels grouped by type" then channel appears in Direct Messages and Public/Private Channels 
<img width="217" alt="Screenshot 1" src="https://user-images.githubusercontent.com/8362431/83418274-00f82480-a42c-11ea-8caa-7f8bae816d11.png">

If channel grouping is set to "Combine all channel types" more than one copy of the channel can appear
![Image Pasted at 2020-6-1 13-51](https://user-images.githubusercontent.com/8362431/83418479-55030900-a42c-11ea-848c-a6620c3bb11b.jpg)
<img width="224" alt="Screenshot 2020-06-01 at 16 46 42" src="https://user-images.githubusercontent.com/8362431/83418486-57fdf980-a42c-11ea-97f8-438dc90d80e9.png">

**Comment by amyblais** [comment]
@ttauri We fixed an issue related to this in v5.22: https://mattermost.atlassian.net/browse/MM-23427. Would you be open to upgrading to v5.22 or v5.23 to see if your issue gets fixed?

**Comment by ttauri** [comment]
Thank you, I will try to do it.
