### ISSUE TITLE
Signup password min length error messages is inconsistent

### ISSUE THREAD

**Issue by Matterchen** [mattermost/mattermost-server#14747]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Signup password error length is inconsistent.

#### Steps to reproduce
1. Open a signup invite link (encountered on v5.23)
2. Fill in the email and name
3. Enter a 1-character password
 error is: Your password must contain between 5 and 64 characters.
4. Enter a 5-character password
 error is: Your password must contain at least 10 characters made up of at least one lowercase letter, at least one uppercase letter, at least one number, and at least one symbol (e.g. "~!@#$%^&*()").

#### Expected behavior
Length in error messages should be consistent

#### Observed behavior (that appears unintentional) 
One message says 5, the other 10.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Thanks, opened a bug ticket: https://mattermost.atlassian.net/browse/MM-25762.
