### ISSUE TITLE
Editing Header locks up the UI

### ISSUE THREAD

**Issue by mayurjobanputra** [mattermost/mattermost-server#14763]
#### Summary
Editing the header in a chanell locks up the UI on web, or in the app

#### Steps to reproduce
Latest version of the app and server. Hosting is on kamatera. To reproduce, open a channel, and click "Set a Header". 

#### Expected behavior
When I click "Set a Header" in a channel, the modal window does appear for editing, and I can edit the header, but once I click save, the modal window doesn't go away. Clicking cancel also has no effect and the modal window remains in place. I have to reload the video in order to proceed.

#### Observed behavior (that appears unintentional) 
The modal window (for editing the header) doesn't go away when clicking cancel or save

#### Possible fixes
I cannot

**Comment by amyblais** [comment]
@mayurjobanputra Would you be able to help confirm your Mattermost server version and desktop app version, as well as your OS and version? Do you see any log errors?
