### ISSUE TITLE
iOS messages containing emojis fail to send

### ISSUE THREAD

**Issue by michaelkozakovsc** [mattermost/mattermost-server#14775]
#### Summary
iOS messages containing emojis fail to send

#### Steps to reproduce

App version: 1.31.2 (build 296)
Server Version: 5.22.3

#### Expected behavior
Messages should deliver

#### Observed behavior (that appears unintentional) 
![IMG_D32E39E0DC3C-1](https://user-images.githubusercontent.com/22355373/84077960-16c69600-a9a6-11ea-9d3d-f364bb6b358e.jpeg)

**Comment by amyblais** [comment]
@michaelkozakovsc What iOS version are you on? Are you able to reproduce this on v1.32 beta version?

**Comment by mkozakov** [comment]
hi @amyblais not sure how to get the beta! im on ios 13.4.1.

I looked at the server logs, seeing this message whenever i try to post an emoji from the app:

{"level":"error","ts":1591885718.0757122,"caller":"mlog/log.go:175","msg":"Unable to save the Post.","path":"/api/v4/posts","request_id":"cd5ygohk8byjibzc5hhjn84zbw","ip_addr":"_______","user_id":"ynrbea57etnyfdoipdskjo7wbe","method":"POST","err_where":"SqlPostStore.Save","http_code":500,"err_details":"Error 1366: Incorrect string value: '\\xF0\\x9F\\x98\\xAF' for column 'Message' at row 1"}

**Comment by mkozakov** [comment]
ok i found an old issue that i wasn't able to find before - it resolved this problem: https://github.com/mattermost/mattermost-server/issues/5760

This bad config value came from the bitnami one-click config - how do we make sure other people's configs don't default to this bad value?

**Comment by amyblais** [comment]
Would you be open to sharing a link to where to get the bitnami one-click config?

**Comment by mkozakov** [comment]
This is where my image came from (the image included a config.json)

https://console.cloud.google.com/marketplace/details/bitnami-launchpad/mattermost

**Comment by JimmySorza** [comment]
> ok i found an old issue that i wasn't able to find before - it resolved this problem: #5760
> 
> This bad config value came from the bitnami one-click config - how do we make sure other people's configs don't default to this bad value?

yes I had the same problem and the #5760 resolved it -> https://github.com/mattermost/mattermost-server/issues/5760#issuecomment-288784179
