### ISSUE TITLE
Slow loading since 5.22

### ISSUE THREAD

**Issue by tuxity** [mattermost/mattermost-server#14780]
#### Summary
Mattermost is very very slow since 5.22, loading channel messages takes lots of time, and editing a message take a bit more than 11 seconds.
Note: I wasn't able to reproduce channel messages loading issue every time, only message editing.

Tested with Firefox, desktop app, iOS app. 
I also tried to disable all plugins, purge MM cache, remove rate limiting, rebuild app/db docker image (I use mattermost-docker). The server isn't overloaded at all, can't find errors in app and db consoles.

I have to downgrade to 5.21.0 to fix the loading time, at this version everything takes less than 1s to load.

#### Steps to reproduce
MM-server: 5.23.1

- Post a message in a channel or DM
- Edit the message
- Submit
- Wait

#### Expected behavior
Loading channel messages shouldn't be that long, neither editing a message.

#### Observed behavior (that appears unintentional) 

Screen record of web app with firefox devtools opened: https://we.tl/t-ZVhURxc6sW

**Comment by agnivade** [comment]
Hi @tuxity. Thanks for the very detailed report. I have a couple of follow up questions which might help us to debug this further.
- On the post editing delay, do you see anything interesting in the logs at a DEBUG level ? Does this only happen during editing a post, and not when creating a post ? What DB are you using ? Would you be able to check the slow query logs and see if there's any query in particular which is slowing down ?
- On the channel messages delay, do you happen to have a lot of archived channels by any chance ? We have an open issue to fix that.

**Comment by tuxity** [comment]
- The delay is indeed only when updating the message, not when posting it. I use postgres 9.4 as a database.
- I don’t know if we have a lot, but we do have a few yes maybe ~15/20?To give you an idea, statistics says 189 channels (idk if it includes archived ones) 46 active users, 12988156 messages.

I will do more tests tomorrow with logs in debug mode and slow query logs, when the team will be sleeping. I downgrade the version for now so they can work correctly.

Do you have a link to the issue about archived channels ?

**Comment by agnivade** [comment]
> I will do more tests tomorrow with logs in debug mode and slow query logs, when the team will be sleeping. 

That sounds great.

> Do you have a link to the issue about archived channels ?

Sure. https://mattermost.atlassian.net/browse/MM-25563

**Comment by amyblais** [comment]
@sudheerDev FYI this report may be related to https://github.com/mattermost/mattermost-server/issues/14755.

**Comment by agnivade** [comment]
#14755 is an issue that happens only on Firefox. This seems like a server side issue to me.

**Comment by sudheerDev** [comment]
Yes, @agnivade the other related ticket is a client-side issue and this isn't. This seems to be 
 client platform-independent issue

**Comment by tuxity** [comment]
A bit more information on slow endpoints:

- GET `/api/v4/users/XXX/channels/YYY/posts/unread?limit_after=30&limit_before=30` (91 messages, 47.33 ko) took also a bit more than ~12 sec to load
- PUT `/api/v4/posts/WWW/patch`

I don't think it's related to archived channels since it's a different endpoint

I also tried to start postgres container like this to log slow queries: `command: postgres -c log_min_duration_statement=2000 -c log_destination=stderr` and no slow queries

**Comment by agnivade** [comment]
Yes, I have seen it. Thanks.

**Comment by agnivade** [comment]
I took a look at the commits that changed from 5.21 to 5.22. The only thing which stands out to me is the skipThreads implementation for posts.

For the unread API, does it happen for all channels ? Same question for patch post too.

Please also give us the debug logs for the duration when these slow calls are happening. Thanks. And a HAR dump of the requests with a matching set of debug logs would be very appreciated.

@reflog - anything you can think of from skipThreads that might affect this?

**Comment by reflog** [comment]
@agnivade - I don't see it. skipThreads would cause **less** database load and it's not used in PATCH at all. So I don't think this is it :(

**Comment by agnivade** [comment]
I was referring to the unread posts endpoint. But yes, in general I would agree. I am trying to see if it's channel specific or happens everywhere.

**Comment by tuxity** [comment]
Updated last night to 5.24.2 and it seems to works fine this time

**Comment by agnivade** [comment]
That's good to hear @tuxity !

**Comment by agnivade** [comment]
Hi @tuxity - just checking if there anything else pending on this issue?

**Comment by tuxity** [comment]
Nothing, It's ok now we can close the issue

**Comment by agnivade** [comment]
Perfect, thank you!
