### ISSUE TITLE
"username" parameter does not override username in incoming webhook

### ISSUE THREAD

**Issue by paalbra** [mattermost/mattermost-server#14801]
#### Summary
"username" parameter does not override username in incoming webhook. This seem to only be an issue on web/desktop. Android/iOS displays the name in the "username" parameter.

https://developers.mattermost.com/integrate/incoming-webhooks/

Mattermost Version: 5.23.0
Database Schema Version: 5.23.0
Database: postgres

#### Steps to reproduce
Send something like:
```
{"attachments": [{"color": "#aaaaaa", "text": "Test 123\n\n:tada:"}], "channel": "@myuser", "username": "My fancy username"}
```

#### Expected behavior
You should see "My fancy username" as the username in chat.

#### Observed behavior (that appears unintentional) 
Web/desktop displays the real username (no override). Android/iOS displays "My fancy username".

Screenshots:
![mobile](https://user-images.githubusercontent.com/265215/84429824-15f16680-ac29-11ea-946c-6cb281458b8a.png)
![web](https://user-images.githubusercontent.com/265215/84429832-1689fd00-ac29-11ea-86f6-52622b628cfe.png)

#### Possible fixes
No idea

**Comment by lieut-data** [comment]
Thanks for the report, @paalbra! I'm unable to reproduce this on v5.23 or master alongside the latest mobile application. Both web and mobile correctly display the override when set, and correctly suppress it when the server is configured to disallow overrides.

Is there a chance your web/desktop assets aren't up-to-date relative to your v5.23 server? You can check the "About Mattermost" in the main menu to see the `Webapp Build Hash`. Is this a regression in that it used to work for you previously?

**Comment by paalbra** [comment]
I'm pretty sure it worked before (on web), but I can't guarantee it and I don't know when the change happened (I just noticed the behavior yesterday) .

Hashes:

Build Hash: ed1576d007a09b07574b18784b9eabb3d8c9db53
EE Build Hash: 9d6d6b0a601330640d7cfe0e64be5ea6a41436d4
Webapp Build Hash: 33ea86b0d3f67c7d00f1e2996acd4427fd5852f4

Are these wrong/outdated?

**Comment by lieut-data** [comment]
@paalbra, those hashes look good, so your webapp appears to be up-to-date. I'm stumped, since I've double checked the mobile code and confirmed they all use the same logic to decide when to override.

Does this happen for all webhooks? On a whim: does clearing your webapp cache make any difference?

**Comment by paalbra** [comment]
This is very weird. A different webhook behaves correctly (username parameter rendered for both web and mobile).

I'm going to try to investigate why/if these webhooks are somehow different. Could it be that they're different inside the application because of when/at what mattermost version they were created?

I've tried different browsers. They render the same name. So I don't believe this is a caching problem. Or did you refer to some other cache than the browser?

**Comment by paalbra** [comment]
I can add that I've confirmed that other people see the same behavior on their devices.

**Comment by paalbra** [comment]
Also: The webhook with the problems was created in January 2019. I am not sure what Mattermost version we were using at the time.

**Comment by lieut-data** [comment]
> Could it be that they're different inside the application because of when/at what mattermost version they were created?

It's possible, but upon reviewing the code, nothing stands out to me as to why that would matter in this case. Perhaps you might take a look at the webhook configuration in the database to see if anything stands out? You might also create and test with a new incoming webhook and the same configuration to see if the issue reproduces as such.

**Comment by paalbra** [comment]
@lieut-data Are you able to provide the queries I should run in the database? I'm not familiar with the schema

**Comment by lieut-data** [comment]
@paalbra, you can query all the webhooks in the system with something like:
```
SELECT * from IncomingWebhooks WHERE Id = '<id of webhook>'
```

Where the `<id of webhook>` is the URL that's part of the webhook target (i.e. `b51mtkh38bydxyk9jdcpbnyxmo` in `http://localhost:8065/hooks/b51mtkh38bydxyk9jdcpbnyxmo`).

**Comment by paalbra** [comment]
Here is two hooks. The top one is the one not working properly (this is a production environment and I've scrambled the data)
```
             id             |   createat    |   updateat    |   deleteat    |           userid           |         channelid          |           teamid           |      displayname       |               description               |    username    | iconurl | channellocked
----------------------------+---------------+---------------+---------------+----------------------------+----------------------------+----------------------------+------------------------+-----------------------------------------+----------------+---------+---------------
 6abe565eecaf7496e16f9df769 | 1548853980000 | 1553776140000 |             0 | 2e99bf79cb43b34380fcdeb375 | ba00081787111481d1dec5dad2 | 1c0ecfe96f7cca60b28cbad473 | asdfgh@qwer            | Words words words                       | username       |         | f
 b144a03408dba417b3cbd79e8a | 1569876230000 | 1569876380000 |             0 | 4821ad08b04803c69b329e9238 | 6d263faee58c180d97656de6a3 | 1c0ecfe96f7cca60b28cbad473 | zxcv-ghjk              | zxcv-ghjk                               | username2      |         | f
```

**Comment by paalbra** [comment]
The user that isn't working properly is a bot user. We've tried to revert this, but the username override still doesn't work.

I just noticed on my Window 10 computer that the OS notification (via Firefox) displays the correct overridden name (the removed name is the normal username for the user).
![notification](https://user-images.githubusercontent.com/265215/85383790-b35d6c00-b540-11ea-8e14-a81fc94a733a.png)

We're considering if we just should delete the user now. This seem very weird to me...

**Comment by paalbra** [comment]
The user with the problem is a bot user. We've tried to revert this, but the override still does not work.

I just noticed that on my Windows 10 computer the OS notification (via Firefox) displays the overridden username (the removed username is the normal username for the user).
![notification](https://user-images.githubusercontent.com/265215/85384283-48f8fb80-b541-11ea-84b9-92d2d99634e5.png)

We're wondering if we should just try to delete this user now. This problem seems very weird to me..

**Comment by paalbra** [comment]
There is a "-" in the username of the user that doesn't work. I can't see that this possibly should make a difference(?), but I guess it's worth mentioning.

**Comment by paalbra** [comment]
> The user with the problem is a bot user. We've tried to revert this, but the override still does not work.

Hold up. We restarted the service this night. Today the the overridden name is displayed properly on all platforms.

Was a restart needed for the "unboting" to take effect? Maybe this issue is related to the user being a bot user?

**Comment by paalbra** [comment]
The restart was related to an upgrade. We're here now:

Mattermost Version: 5.24.1
Database Schema Version: 5.24.0
Database: postgres

Build Hash: b1c4b118f089389ea71744342342fd5654a150b7
EE Build Hash: 8239891909042ef8e47e2b81b5d515ec65d8938c
Webapp Build Hash: d680c73ace274c55119103075ba079225ee96d50

**Comment by lieut-data** [comment]
Aha, the bot user is definitely the issue here. With that bit, I was able to reproduce your observations here. Thanks for helping us track this one down! I've filed https://mattermost.atlassian.net/browse/MM-26493 to get to the bottom of why.
