### ISSUE TITLE
Footer text in invite email is not translated

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-server#14809]
#### Summary
Email footer in only invitation email isn't translated.

**Invite email (footer is not translated)**
<img width="674" alt="スクリーンショット 2020-06-14 14 16 54" src="https://user-images.githubusercontent.com/1453749/84585874-1408ec80-ae4f-11ea-9654-1c982b4df7c2.png">

**Change email address (footer is translated)**

<img width="678" alt="スクリーンショット 2020-06-14 14 47 23" src="https://user-images.githubusercontent.com/1453749/84585878-23883580-ae4f-11ea-884c-0d73ba15e604.png">

#### Steps to reproduce
1. Change locale (to `ja`) for server
2. Restart server
3. Send invitation

#### Expected behavior
Translated all words into Japanese

#### Observed behavior (that appears unintentional) 
Only footer isn't translated

#### Possible fixes
only when "invite_body", Fixed value `model.DEFULAT_LOCALE` is used. (The locale value in the server configuration should be set here, but I haven't seen how to bring the locale value up to this point)

https://github.com/mattermost/mattermost-server/blob/81a87533a9441fd113b964997b97b4f235399567/app/email.go#L331
https://github.com/mattermost/mattermost-server/blob/81a87533a9441fd113b964997b97b4f235399567/app/email.go#L403

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-26052
