### ISSUE TITLE
Pasting code replaces all previously written text

### ISSUE THREAD

**Issue by divinebovine** [mattermost/mattermost-server#14800]
#### Summary
Pasting code from GitHub replaces the entire text buffer with the code. Any text that was already written is wiped out. This is frustrating when I'm writing up description of the code and want to paste the code after the description. I am using the electron app if it makes a difference.

#### Steps to reproduce
Mattermost Version: 5.20.1
Database Schema Version: 5.20.0
Build Hash: 0e1a9f7e530061cdd2c7c17899e458afe2c83a9b
EE Build Hash: 551cbd55b9c0d896b5886f42fc0193c9b97edb33
Webapp Build Hash: fc08a2b49f1a994164697d2c51442baf21812d1f
Build Date: Sun Feb 16 15:51:14 UTC 2020

1. Type some text into the chat window
1. Go to github and copy some random code
1. Paste into chat window

#### Expected behavior
Code gets pasted below the previously written text.

#### Observed behavior (that appears unintentional) 
Replaces all text with code.

**Comment by amyblais** [comment]
@divinebovine This has been fixed in v5.23 release: https://mattermost.atlassian.net/browse/MM-23933.

**Comment by divinebovine** [comment]
@amyblais Thank you, I searched the issues before hand but I guess I missed it.
