### ISSUE TITLE
The username is not highlighted (indicating that I have unread messages).

### ISSUE THREAD

**Issue by lwelniak** [mattermost/mattermost-server#14829]
After the last upgrade to 5.23, we are experiencing some weird behavior of an app. Time to time, the username is not highlighted when a new message occurs. 
I cannot give a specific path to repeat the error because I have not noticed the regularity / repetition of its occurrence. Nevertheless, this is problematic, because at random the application does not show me that someone is expecting my answer.

**Comment by amyblais** [comment]
@lwelniak What OS and version are you on? Do you see any log errors? Would you have any screenshots of the issue?

**Comment by mlesiakalb** [comment]
I'm facing the same issue. I am operating on osx. 

- Client version: http://www.bankflex.net
- server version: Mattermost Version: 5.23.0

**Comment by mlesiakalb** [comment]
I'm facing the same issue. I am operating on osx.

Client version: I'm facing the same issue. I am operating on osx.

Client version: 4.4.2
server version: Mattermost Version: 5.23.0
server version: Mattermost Version: 5.23.0

**Comment by amyblais** [comment]
Is this happening on webapp, desktop app, or both?

**Comment by mlesiakalb** [comment]
desktop app for sure. I am not sure about web version since i am not using it :)

**Comment by mlesiakalb** [comment]
Another case: 

Client version: v 4.4.2
Operating system: ubuntu 18.04.3 LTS

the same backend (5.23.0)

**Comment by amyblais** [comment]
Following up on this. Do you see any log errors? Would you have any screenshots of when the issue occurs?
