### ISSUE TITLE
Channel Name contains invalid characters in Bulk Import

### ISSUE THREAD

**Issue by shubhamchinda-sc** [mattermost/mattermost-server#14824]
I was trying to use **[Bulk Import feature](https://docs.mattermost.com/deployment/bulk-loading.html)** of mattermost but as I try to validate the **jsonl** format I get this error : 

```
BulkImport: Channel name contains invalid characters., 
Error occurred on data file line 3
```

My JSONL data : 
```
{"type": "version", "version": 1}
{"type": "team", "team": {"name": "demo", "display_name": "Demo Team", "type": "O", "description": "Stock platform", "allow_open_invite": true}}
{"type": "channel", "channel": {"team": "demo", "name": "General", "display_name": "General", "type": "O"}}
{"type": "channel", "channel": {"team": "demo", "name": "Test", "display_name": "Test", "type": "O"}}
{"type": "user", "user": {"username": "shubhamchinda", "email": "shubhamchinda@gmail.com", "password": "@Shubham07", "nickname": "shubham", "first_name": "Shubham", "last_name": "Chinda", "teams": [{"name": "demo", "channels": [{"name": "General", "notify_props": {"desktop": "default", "mark_unread": "all"}}, {"name": "Test", "notify_props": {"desktop": "default", "mark_unread": "all"}}]}]}}
{"type": "user", "user": {"username": "test12", "email": "test@12", "password": "test@12", "teams": [{"name": "demo", "channels": [{"name": "General", "notify_props": {"desktop": "default", "mark_unread": "all"}}, {"name": "Test", "notify_props": {"desktop": "default", "mark_unread": "all"}}]}]}}
```

I don't know what's causing this error as the name of channel is just a simple string "General".

Any help would be highly appreciated. Thanks :)

**Comment by amyblais** [comment]
@shubhamchinda-sc What Mattermost server version are you on? What OS and version are you on? Are there any other log errors that you see?

**Comment by shubhamchinda-sc** [comment]
@amyblais 

I'm using 5.22.0 version of MM.

My **Os* : Ubuntu 18.04.4 LTS

No I don't see any log errors.

**Comment by jespino** [comment]
@shubhamchinda-sc you are using upper case values in the `name` field, the `name` fiedl should be always lowercase characters (`[a-z0-9]`) or `-` or `_`, and always start from a lowercase character.

**Comment by Shubhamchinda** [comment]
yeah @jespino , I figured that out but forgot to close this one.

Thanks anyways. I  appreciate it.

**Comment by jespino** [comment]
@Shubhamchinda great, thanks
