### ISSUE TITLE
Add 'Mark Read' option in right click of Channel(or Group) to clear notification icon

### ISSUE THREAD

**Issue by csankhala** [mattermost/mattermost-server#14828]
I suggest to have 'Mark read' option for any Channel in Mattermost.

There may have few groups which are integrated to get notification of JIRA updates or Jenkins to build status. Loads of messages are received there and one will see notification icon until one open that channel.

It will be great if Mattermost provides 'Mark Read' kind of function to clear particular channel notifications without opening channel chat.

I would recommend having this as a right-click option of a channel.

**Comment by amyblais** [comment]
@csankhala What Mattermost server version are you on? What OS and version are you on? Are there any other log errors that you see? Can you help fill in reproduction steps and excepted behaviour?

**Comment by csankhala** [comment]
Thanks, @amyblais for bringing my attention here. I almost forget to add detailed requirement in a hurry.

I have edited description. I have not attached any logs, steps, os version as i am suggesting improvement/feature here. Revert back if more details needed.

**Comment by amyblais** [comment]
@csankhala Thanks! Would you be open to sharing this in our feature request forum here https://mattermost.uservoice.com/forums/306457-general?

**Comment by csankhala** [comment]
done. https://mattermost.uservoice.com/forums/306457-general/suggestions/40721149-add-mark-read-option-in-right-click-of-channel-o
