### ISSUE TITLE
Email Sender / From Address

### ISSUE THREAD

**Issue by hickscorp** [mattermost/mattermost-server#14839]
This might not be a bug, more like a feature request.

The emails sent by Mattermost have their "Sender" field set to the SMTP username from Mattermost's configuration. It'd be really nice to allow something else - in most case it's something like `no-reply@domain.tld`.

Edit: I realise that my description of the issue terrible. A bit more explanations:
- There is no way for the administrative user to set the `EmailSettings.FeedbackEmail` and `EmailSettings.FeedbackName` configuration options from the UI.
- Even when doing so using the `mattermost` CLI, the changes are not reflected. I double-checked that the configuration was set using `mattermost config show` and it is - it's just not being used.

**Comment by amyblais** [comment]
@hickscorp Are you on Enterprise Edition E20?

**Comment by amyblais** [comment]
I checked the settings you described and it seems they are currently available in E20 only: https://docs.mattermost.com/administration/config-settings.html#email-notification-contents.
