### ISSUE TITLE
images in OpenGraph link previews not rendered when image proxy enabled

### ISSUE THREAD

**Issue by jetpackdanger** [mattermost/mattermost-server#14855]
#### Summary
When local image proxy is enabled images in OpenGraph link previews are not rendered.

#### Steps to reproduce
Observed with 5.22.1, reproduced in 5.23.1.  Enable link previews. Enable local image proxy. Paste "https://ubuntu.com/blog/fips-certification-ubuntu-18-04-lts" into a channel.

#### Expected behavior
The link preview should be rendered as it would be with the image proxy disabled.

#### Observed behavior (that appears unintentional) 
Image was not rendered. Reviewed browser network console and observed HTTP status 500 responses. Examined one of the 500s and observed that the URL is of the form

    https://mattermost.example.com/api/v4/image?url=https%3A%2F%2Fmattermost.example.com%2F%2Fapi%2Fv4%2Fimage%3Furl%3Dhttps%253A%252F%252Fadmin.insights.ubuntu.com%252Fwp-content%252Fuploads%252F4054%252FUbuntu_FIPS_Certification_Ubuntu_18-04.png

which appears to be the correct URL with an extra step of image-proxy applied.

Taking the "url" parameter and url-decoding it yields

    https://mattermost.example.com//api/v4/image?url=https%3A%2F%2Fadmin.insights.ubuntu.com%2Fwp-content%2Fuploads%2F4054%2FUbuntu_FIPS_Certification_Ubuntu_18-04.png

which loads successfully.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@jetpackdanger What OS and version are you on? Do you see any additional Mattermost server log errors?

**Comment by jetpackdanger** [comment]
Actually it seems this has been fixed between 5.22.1 and 5.23.1. I thought I was running 5.23.1 locally but in fact it was also 5.22.1.

**Comment by jetpackdanger** [comment]
Looks like I spoke too soon; it seems to happen with 5.23.1 also, although not entirely reliably.

@amyblais We're running the Enterprise build of 5.23.1 on a two-node clustered k8s deployment. We originally observed this problem with 5.22.1.  The OS is Ubuntu 20.04 LTS.  There doesn't seem to be any unusual logging related to the problem. From poking around in my browser's debug console it seems that 500s are returned to the client via the response body but not are not otherwise logged (unless maybe I need to enable debug logging?).

I'll try to come up with a solid reproduction and will report back.

**Comment by amyblais** [comment]
Closing as this is an old issue, feel free to re-open if the issue still reproduces on the latest version,
