### ISSUE TITLE
Mattermost crashes after "Trust Sert" on error ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by p01arbear** [mattermost/mattermost-server#14863]
#### Summary
The problem #12225 is still here.

Server: 5.23.0
Desktop: 4.5.0
OS: Debian 10 with lastest updates

![err](https://user-images.githubusercontent.com/16598339/85119726-dcbd8580-b22a-11ea-8fbf-bb2ef3639f41.png)
#### Observed behavior (that appears unintentional) 
After "Trust Insecure Sertificate" I have a [crash](https://github.com/mattermost/mattermost-server/files/4803774/err.log).

**Comment by amyblais** [comment]
@p01arbear 
1. What Mattermost desktop app version are you on?
2. What Mattermost server version are you on?
3. What OS and version are you on?

**Comment by Willyfrog** [comment]
@p01arbear thanks for the report!
the file you attached seems to be the code for rudder.

is there any log file in the directory where your desktop app config is? (seen it is linux, it depends on how you installed, but most likely it'll be in `~/.config/Mattermost`

Also, that url shouldn't give you any certificate problems, does navigating with your browser to https://cdn.rudderlabs.com/ gives you any problems (there should be the lock icon and look right)

**Comment by p01arbear** [comment]
I've updated versions in the first message.

> is there any log file in the directory where your desktop app config is?

No any logs in `~/.config/Mattermost/logs/`

> does navigating with your browser to https://cdn.rudderlabs.com/ gives you any problems

No

> Also I recomend to upgrade to the latest version and see if you have any problems with certificates there.

It's strange, but after update to 4.5.0 the problem has disappeared soon (after several crashes and manual restarts).
So I can't reproduce it anymore. But it would be great that app will not crash even once :)
Thank you for the help!

**Comment by Willyfrog** [comment]
> It's strange, but after update to 4.5.0 the problem has disappeared soon

there were several changes around the code that handles that, so I was hoping one will help you :)

> But it will be great if app doesn't crash even once after update :)

Definitely! I'll try to take a look at that in the future

**Comment by josip-matic** [comment]
My colleague has similar problem. She using like me 5.1.1 Desktop version on Windows 10. 
![Uploading mattermost-issue.png…]()
