### ISSUE TITLE
Add option on teammate name display to show username if not nickname exists

### ISSUE THREAD

**Issue by 3v1n0** [mattermost/mattermost-server#14864]
#### Summary
There's no way to show the nickname or the username (if no nick is set)

#### Steps to reproduce
- In Account Settings -> Display -> Teammate Name Display

You can choose to see the username, the first and last names or nickname falling-back to First and Last name, but there's no one to give priority to nickname over the username.

#### Expected behavior
There's a selectable item "Show nickname if one exists, otherwise show username"

So that the first and last names are never shown, unless required.

#### Observed behavior (that appears unintentional) 

No such option is available

#### Possible fixes

Add an option to "Show nickname if one exists, otherwise show username"

**Comment by amyblais** [comment]
@3v1n0 Thank you, would you like to share this idea on our feature request forum here https://mattermost.uservoice.com/forums/306457-general?

**Comment by 3v1n0** [comment]
> @3v1n0 Thank you, would you like to share this idea on our feature request forum here https://mattermost.uservoice.com/forums/306457-general?

Ok, added as https://mattermost.uservoice.com/forums/306457-general/suggestions/40706974-add-option-to-show-nickname-or-username-never-rea
