### ISSUE TITLE
Does support hidden and disable input in Interactive Dialogs ?

### ISSUE THREAD

**Issue by tatdatpham** [mattermost/mattermost-server#14873]
Sometime we need send some hidden input value to integration server and fix some value (user can't change)
So currently, does Mattermost support hidden and disable input form ?

**Comment by amyblais** [comment]
@tatdatpham Would you be open to asking about this on our [community server's Peer-to-Peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? I'm not sure of the answer to your question but one of our other staff or community members may be able to help you.
