### ISSUE TITLE
500 on fetch read channel messages

### ISSUE THREAD

**Issue by Eluminae** [mattermost/mattermost-server#14894]
#### Summary

This endpoint seems the only one to fetch read channel messages. But we have to use limit_after=1 and hack results to fetch actually only read messages.

#### Steps to reproduce

Simply Get the endpoint with limit_after to 0 (zero)

#### Expected behavior

GET api/v4/users/{user_id}/channels/{channel_id}/posts/unread?limit_after=0

should fetch the last 60 read messages

#### Observed behavior (that appears unintentional) 

500 returned

**Comment by Eluminae** [comment]
In fact it is worse than that. 

With this constraint on the limit_after > 0 we actually can't guess which messages are read and which are not.

I expected to pop the last one and make magic but if my user is up to date with all messages, I don't want to pop-out the last message. This will cause displaying read messages as unread.

**Comment by Eluminae** [comment]
I found a way to bypass the problem using my other issue https://github.com/mattermost/mattermost-server/issues/14891

Anyway Mattermost will think every last channel message as unread. It will so return me this unread message with this endpoint, closing the circle.

I think work should be done to fetch only read messages with one endpoint.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-26535
