### ISSUE TITLE
Mark a channel as Read

### ISSUE THREAD

**Issue by stacyharper** [mattermost/mattermost-server#14891]
Hello there,

I'm working on a Weechat Mattermost Backend but I got an issue marking my channels posts as read:

ATM, I use the `api/v4/users/{user_id}/posts/{post_id}/set_unread` endpoint but this prevent me to actually mark the post as READ.

Browsing my channels will mark all of them as unread (in official apps) cause the last message is included in the "from the post" range.

I'm looking for a way (an endpoint?) that could actually mark the channel "as read from the post_id".

Is there any way to do this ?

Thanks a lot in advance.

**Comment by amyblais** [comment]
@Eluminae What Mattermost server version are you on?

**Comment by Eluminae** [comment]
I'm on 5.24.0
