### ISSUE TITLE
API: Get posts for direct messages

### ISSUE THREAD

**Issue by neszt** [mattermost/mattermost-server#14900]
#### Summary
Trying to get posts for direct messages

I can get posts for channels
```
curl -H "Authorization: Bearer $token" $api_url/channels/$channel_id/posts?since=$epoch
```
 but i  can't find way to get posts for direct messages.

**Comment by amyblais** [comment]
@neszt What error do you see when trying to get posts for direct message channels?

**Comment by jespino** [comment]
@neszt to give you some context, direct messages, are just an special type of channels, so if you have the `channel_id` of the direct message, it should work.

**Comment by neszt** [comment]
@jespino thanks, how to get a direct message's channel id? I tried:
```
curl -H "Authorization: Bearer xxxxxx" https://mm.example.com/api/v4/teams/xxxxxx/channels/name/@username

{"id":"api.context.404.app_error","message":"Sorry, we could not find the page.",
"detailed_error":"There doesn't appear to be an api call for the url='/api/v4/teams/xxxxxx/channels/name/@username'.
Typo? are you missing a team_id or user_id as part of the url?","status_code":404}[18]
```

**Comment by jespino** [comment]
@neszt you can get the list of your channels, for example with something like: 
`curl -H "Authorization: Bearer xxxxxx" https://mm.example.com/api/v4/users/me/teams/xxxxxxx/channels`

**Comment by neszt** [comment]
@jespino it works, but i only got channel id list for channels, not for direct messages
```
Mattermost Version: 5.24.1
Database Schema Version: 5.24.0
```

**Comment by jespino** [comment]
@neszt you don't receive any `"type": "D"` channel there? Have the user that is making the request any direct message with any other user?

**Comment by neszt** [comment]
@jespino i got only ```"type": "O"```. I'am a little bit unsure about your "request" word. I use my mattermost user and i have about 20 direct messages with others with lot of conversation in the past months.

**Comment by neszt** [comment]
@jespino thank you the help, now i got all the channels. It was my fault, the "users/me" was the key.
