### ISSUE TITLE
Bulk import (2 users) hangs when Bleve Indexing is enabled

### ISSUE THREAD

**Issue by derek-shnosh** [mattermost/mattermost-server#14914]
#### Summary
Performing a bulk import of 2 users via `.json` file hangs when Bleve Indexing is enabled.

#### Steps to reproduce
Enable Bleve Indexing, attempt a bulk import via SSH bash.

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
With Bleve enabled, I was trying to `--validate` a bulk import of 2 new users (my preferred method) using a `.json` file, and it just hung on `{"level":"info","ts":1593106985.4862027,"caller":"bleveengine/bleve.go:157","msg":"EXPERIMENTAL: Starting Bleve"}`. 

I entered break sequence after 2 mins;

```bash
$ bin/mattermost import bulk users.json --validate
{"level":"info","ts":1593106985.4862027,"caller":"bleveengine/bleve.go:157","msg":"EXPERIMENTAL: Starting Bleve"}
^C
$ 
```

#### ~~Possible fixes~~ Workaround
I temporarily disabled Bleve experimental feature and the command ran fine with both `--validate` and `--apply`. The Bleve **Index Now** button/feature seems to work, ran it again before disabling it and it completed after 3 minutes.

**Comment by amyblais** [comment]
@mgdelacroix FYI ^ not sure if we first want to have QA testing this.

**Comment by derek-shnosh** [comment]
There was some chat on the Mattermost community server and a subsequent [PR#3173](https://github.com/mattermost/docs/pull/3713) to explain the behavior and workaround. This is OK to close.
