### ISSUE TITLE
Managing a running MM using "bin/mattermost" with bleve enabled will hang indefinitely/deadlock.

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#14919]
#### Summary
When trying to create a user on a running instance with bleve enabled, running: `bin/mattermost user create --system_admin --username someone --email someone@example.com --password Password01` will hang indefinitely on:
`2020-06-26T01:19:21.819+0200    info    bleveengine/bleve.go:157        EXPERIMENTAL: Starting Bleve`

(This is a diffrent instance than the one described in: #14918 )

#### Steps to reproduce
Server 5.24.1
+ get yourself a test instance with bleve enabled.
+ start it.
+ try to create a user, using bin/mattermost
+ enjoy your hang/deadlock.

#### Expected behavior
Bleve not deadlocking management commands.

#### Observed behavior (that appears unintentional) 
a hang/deadlock.

**Comment by amyblais** [comment]
Our devs are looking into this. In the meanwhile we've added some troubleshooting steps here: https://docs.mattermost.com/administration/command-line-tools.html#troubleshooting.

**Comment by licaon-kter** [comment]
Seeing the same on update to 5.26, had to edit config bleve to false then retry

But now Bleve won't activate as save button on its page rotates forever

**Comment by agnivade** [comment]
This appears to be a known issue: https://docs.mattermost.com/administration/changelog.html#id23

> Enabling Bleve search engine makes the Command Line Interface (CLI) mutually exclusive with the running server. This issue does not apply when using mmctl Command Line Tool.

The current workaround is to use mmctl in local mode to perform any administration tasks.

**Comment by ylluminate** [comment]
Had the same problem with `mattermost` - ultimately took 2196 minutes for Bleve to complete indexing on our smallish server. Problem with `mmctl` is that it is not yet feature complete from what I'm experiencing. For example, moving channels from one team to another seems to be missing.
