### ISSUE TITLE
API to list the posts metioned me

### ISSUE THREAD

**Issue by bill2004158** [mattermost/mattermost-server#14926]
#### Summary
similar like "Get a list of flagged posts"
https://api.mattermost.com/#tag/posts/paths/~1users~1{user_id}~1posts~1flagged/get
is there any api the return the posts that metioned me.

as a user, when I login, I prefer to see the posts that metioned me from all the teams/channels that I could see,  including direct chat.
because those posts require me to process,
I prefer to see them in a single list, rather than find them from each team/group.
and I will not missing any post.

**Comment by jespino** [comment]
@bill2004158 we don't have an API for that, but have that functionality in our application that does exactly that, we do it by searching using the user mention keywords, so for example my user is `jesus.espino` si I search for posts with the term `@jesus.espino`, but if I have other mention terms, it would be added to the search.

**Comment by bill2004158** [comment]
hi @jespino , thanks for reply.
yes, I have saw that feature.
https://api.mattermost.com/#tag/posts/paths/~1teams~1{team_id}~1posts~1search/post
it seems that API only can search 1 team?
is it possible search the post cross all the teams that current user joined.

**Comment by jespino** [comment]
No, in our API the searches of posts are scoped by teams, you would need to execute N queries, one per team.
