### ISSUE TITLE
Hyphenated words are searched separately by 'Recent Mentions' listing

### ISSUE THREAD

**Issue by hillpd** [mattermost/mattermost-server#14920]
#### Summary
Adding a hyphenated word to your 'Words That Trigger Mentions' will break the 'RECENT MENTIONS' listing. The hyphen gets ignored and many unrelated messages appear. 

#### Steps to reproduce
Add a hyphenated word (like "spot-check") to your 'Words That Trigger Mentions'
Click on 'See recent mentions'
The 'RECENT MENTIONS' list includes messages that do contain the full hyphenated word. For the "spot-check" example, a message that just includes "spot" or "check" will appear in the listing. 

How can we reproduce the issue (what version are you using?)
Mattermost Version: 5.23.1
Database Schema Version: 5.23.0

#### Expected behavior
Expect to see only recent mentions that include the full mention phrase.

#### Observed behavior (that appears unintentional) 
The 'RECENT MENTIONS' list includes messages that do contain the full hyphenated word. For the "spot-check" example, a message that just includes "spot" or "check" will appear in the listing.

**Comment by amyblais** [comment]
Are you using Elasticsearch and are you on Mysql or Postgres?

We have a Jira epic for various search related improvements: https://mattermost.atlassian.net/browse/MM-21973.

**Comment by hillpd** [comment]
I'll confirm the specifics of our setup.

It looks like this is a known issue with Elasticsearch, with a work-around discussed in this thread:
https://discuss.elastic.co/t/searching-for-exactly-a-hyphenated-word/161216/2

**Comment by hillpd** [comment]
We are using Postgres directly.

**Comment by amyblais** [comment]
It seems this is currently documented as a known issue here: https://docs.mattermost.com/help/getting-started/searching.html#differences-between-mysql-and-postgres-search.
