### ISSUE TITLE
notify_all.question is only asked for @all and @channel, not @here

### ISSUE THREAD

**Issue by julian-klode** [mattermost/mattermost-server#14950]
#### Summary
Pull request #6250 implemented a warning when sending messages with `@all` or `@channel` to many users, but the same does not apply to `@here`, which has the same behavior as the other two.

#### Steps to reproduce
Send message with `@here` to large group

#### Expected behavior
Get warned that you're pinging everyone

#### Observed behavior (that appears unintentional) 
It just gets sent.

#### Possible fixes
I think the code does like `contains(@all) || contains(@channel)` somewhere that needs another case added for @here.

**Comment by amyblais** [comment]
@julian-klode Would you be open to upvoting this feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/38546479-confirm-before-sending-at-here-like-it-is-already? If you're interested in implementing it, please let us know.

**Comment by julian-klode** [comment]
I mean, I guess it's just changing https://github.com/mattermost/mattermost-webapp/blob/master/components/create_post/create_post.jsx#L1228 and the messages below it, but building and testing that scares me a bit at the moment.
