### ISSUE TITLE
Search by any word in First Name field

### ISSUE THREAD

**Issue by mthaddon** [mattermost/mattermost-server#14957]
#### Summary
We use an external login provider that provides a "Full Name" field. In the web UI this show as "Full Name" but in the Android app I can see that it's in the "First Name" field, and the "Last Name" field is empty. This seems slightly inconsistent, but in any case, we'd like to be able to search by first name or last name, but we are unable to search by Last Name, presumably because it's doing a full text match on "First Name" rather than splitting on spaces and allowing us to search by any word in that field.

#### Steps to reproduce
We're running 5.23.1. I'm unsure of the exact steps to reproduce as I can't change Full Names because they're provided by our login provider, but I would assume if you add a full name (e.g. "Tom Haddon") to the "First Name" field in a mobile client and then try to search for "Haddon" it would also fail to be searchable.

#### Expected behavior
To be able to search by any word in the "First Name" field.

#### Observed behavior (that appears unintentional) 
You can only search by the full contents of the "First Name" field.

**Comment by amyblais** [comment]
@mthaddon Does this happen when trying to search direct message channels? 

I wonder if this is somewhat related to https://forum.mattermost.org/t/editing-full-name-gets-overwritten-with-gitlab-sso/9970/4.

**Comment by mthaddon** [comment]
It does, yes - we're not able to search by someone's last name in direct message channels either.

In terms of the forum post, we do already get "This field is handled through your login provider. If you want to change it, you need to do so through your login provider" when trying to edit that field manually, which is good.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-26728.

**Comment by amyblais** [comment]
@mthaddon Which external login provider do you use?

**Comment by mthaddon** [comment]
The login provider is login.ubuntu.com.

**Comment by agnivade** [comment]
@mthaddon - Are you still experiencing the issue now?

- What is the search backend you are using? Is that DB search/elasticsearch/Bleve?
- Can you show us the DB row for the affected user from the users table? (Feel free to anonymize any output as necessary)
- Which part of the search UI are you using? Autocomplete or searching users?

**Comment by agnivade** [comment]
@mthaddon - We looked into this. Our search always does a prefix match for first name and last name. So if your first name entry is "Hello World", then you need to search with "Hello" and not "World". My last name is "De Sarker". But while searching for it, I'd search with "De", not "Sarker".

I'd suggest to either search by username or nickname to disambiguate, or otherwise adjust the login provider to set both first names and last names.
