### ISSUE TITLE
Automatically add authenticated users to a team

### ISSUE THREAD

**Issue by mthaddon** [mattermost/mattermost-server#14958]
#### Summary
We'd like to be able to add all users to a team on login (login is gated by an external provider, so we know anyone who can login should be in this team).

#### Steps to reproduce
We already have the experimental "Primary Team" option set to the team we want users added to, but as far as we can tell from grepping the webapp code, the primary team is not consulted during the signup flow. Given this feature is marked as experimental, maybe it's just not done yet. As a result, new users are asked to join the team

#### Expected behavior
When "Primary Team" is set, new users are added to that team. Alternatively, a new option is added to enable this behaviour.

#### Observed behavior (that appears unintentional) 
New users are not added to the "Primary Team".

**Comment by someone-somenet-org** [comment]
We do this via bot. As we want a combination of welcome message(s) and team + channels joind to have new users in.

-> https://git.somenet.org/pub/jan/mattermost.git/blob/HEAD:/somebot/modules/WSOnboarding.py

**Comment by amyblais** [comment]
Building on the response above, this may also help https://github.com/mattermost/mattermost-plugin-welcomebot/blob/master/README.md.

**Comment by amyblais** [comment]
If the above suggestions didn't help, please help open a feature request at https://mattermost.uservoice.com/forums/306457-general! Closing as this is an old Issue,
