### ISSUE TITLE
Close Channel for archived channel is not taking user back to previous channel

### ISSUE THREAD

**Issue by Vars-07** [mattermost/mattermost-server#14968]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Close Channel for archived channel is not taking user back to previous channel

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
1) Navigate to any DM
2) Search for Archived Channel
3) Notice it is not redirecting to last channel.

<img width="1278" alt="test" src="https://user-images.githubusercontent.com/19248012/86513822-e4844900-be2a-11ea-8d5c-55749d12c278.png">

#### Expected behavior
Describe your issue in detail
It should redirect to the previous DM chat.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
Should be redirected back to chat as in case of channel.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by Vars-07** [comment]
Will pick it up.

**Comment by esethna** [comment]
Hi @Vars-07, hows this fix going? Any questions we can help with?

cc// @jgilliam17

**Comment by jgilliam17** [comment]
Jira issue: https://mattermost.atlassian.net/browse/MM-26916

**Comment by Vars-07** [comment]
Yes, I am working on it, found another issue while working on this issue, started looking into it.

**Comment by jfrerich** [comment]
Hi @Vars-07, thanks for the issue submission!  Do you have any updates?
