### ISSUE TITLE
False unread messages 

### ISSUE THREAD

**Issue by cosmo222** [mattermost/mattermost-server#14980]
#### Summary
On one of teams in our mattermost instance i have notification about unread messages, but when i go to team i don't see any unread messages. It appears both in web browser or android app. 
#### Steps to reproduce

Mattermost Version: 5.24.2
Database Schema Version: 5.24.0
Database: mysql

#### Observed behavior (that appears unintentional) 
![Zrzut ekranu z 2020-07-07 14-36-48](https://user-images.githubusercontent.com/18347433/86783618-da4b9000-c060-11ea-81bd-fd6a2603ab92.png)

![Zrzut ekranu z 2020-07-07 14-37-13](https://user-images.githubusercontent.com/18347433/86783639-dfa8da80-c060-11ea-9dbc-b5485bbab08a.png)

![Zrzut ekranu z 2020-07-07 15-30-03](https://user-images.githubusercontent.com/18347433/86788848-e63a5080-c066-11ea-8fed-30d0d946099a.png)

#### Possible fixes

**Comment by cosmo222** [comment]
Ok problem solved, someone for fun removed name from channel and it wasn't present on channel list but had unread. 

I don't know how someone did it but channel name was empty.

**Comment by ahmaddanialmohd** [comment]
Hi @cosmo222 

By default, you cannot remove the channel name from the UI as you will be presented with the following error:

![image](https://user-images.githubusercontent.com/49461314/86867174-f274eb00-c104-11ea-8ed0-206e0b6700a3.png)

I am guessing that there was a database edit done to remove the channel name on the backend. Renaming the channel via CLI shows the following:

![image](https://user-images.githubusercontent.com/49461314/86867744-f2291f80-c105-11ea-996f-af8be3359a1b.png)
