### ISSUE TITLE
`MfaRequired` function does not log errors when finding the user

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost-server#15041]
#### Summary

The `MfaRequired` function does not log errors when finding the user

#### Steps to reproduce

1. Set up a Mattermost server w/ MFA required and log in
2. Modify the user ID in the database so that it does not match what is stored in your session
3. Make a request

#### Expected behavior

The user is logged out and an error message in the logs indicates that the user could not be found in the database.

#### Observed behavior (that appears unintentional) 

The log output only indicates that the session expired and MFA is required, with no indication as to the root cause of the issue.

#### Possible fixes

[This line](https://github.com/mattermost/mattermost-server/blob/de6a57cdc32f5bafabf1bb9ce9c5d846baf5fb60/web/context.go#L155) uses the user store to find a user by ID with [this function](https://github.com/mattermost/mattermost-server/blob/90ff87a77ff79be46d3b40c74297874e585e8c08/store/sqlstore/user_store.go#L330). However, if an error is returned by `c.App.GetUser` the application will only display a debug message indicating the session expired, even if the session is valid 

This should be improved to log the error returned by `c.App.GetUser` and only send the `api.context.session_expired.app_error` if the session is in fact expired. Also, the error returned from `c.App.GetUser` should be put into an error log message so admins can diagnose the issue.

**Comment by agnivade** [comment]
Yeah, we need to pass the err.Error in the AppError and change the id to something else. The code just assumes that userID not found == session expired.

**Comment by adolsalamanca** [comment]
I could help with this one :)

**Comment by agnivade** [comment]
Hey @adolsalamanca - sorry about that. I already started to work on this one.
