### ISSUE TITLE
Database Schema Upgrade to 5.22.0

### ISSUE THREAD

**Issue by cbarrac** [mattermost/mattermost-server#15058]
#### Summary
Index creation failed due to (MySQL) DB schema in 'Schemes' table.

#### Steps to reproduce
Docker-container based upgrade from  mattermost/mattermost-team-edition:release-5.21 to  mattermost/mattermost-team-edition:release-5.22, with MySQL database (image library/mysql:5.7.31).
Server was originally created on release-5.12.0.

#### Expected behavior
No errors

#### Observed behavior (that appears unintentional) 
{"level":"error","ts":1595043816.7204974,"caller":"sqlstore/supplier.go:919","msg":"Failed to create index","error":"Error 1170: BLOB/TEXT column 'DefaultChannelGuestRole' used in key specification without a key length"}

#### Possible fixes
Database schema was showing column type 'text' for the DefaultChannelGuestRole column:
```
mysql> describe Schemes;
+-------------------------+--------------+------+-----+---------+-------+
| Field                   | Type         | Null | Key | Default | Extra |
+-------------------------+--------------+------+-----+---------+-------+
| Id                      | varchar(26)  | NO   | PRI | NULL    |       |
| Name                    | varchar(64)  | YES  | UNI | NULL    |       |
| DisplayName             | varchar(128) | YES  |     | NULL    |       |
| Description             | text         | YES  |     | NULL    |       |
| CreateAt                | bigint(20)   | YES  |     | NULL    |       |
| UpdateAt                | bigint(20)   | YES  |     | NULL    |       |
| DeleteAt                | bigint(20)   | YES  |     | NULL    |       |
| Scope                   | varchar(32)  | YES  |     | NULL    |       |
| DefaultTeamAdminRole    | varchar(64)  | YES  |     | NULL    |       |
| DefaultTeamUserRole     | varchar(64)  | YES  |     | NULL    |       |
| DefaultChannelAdminRole | varchar(64)  | YES  |     | NULL    |       |
| DefaultChannelUserRole  | varchar(64)  | YES  |     | NULL    |       |
| DefaultTeamGuestRole    | text         | YES  |     | NULL    |       |
| DefaultChannelGuestRole | text         | YES  |     | NULL    |       |
+-------------------------+--------------+------+-----+---------+-------+
```
Altering the type of the column allows the upgrade to proceed (now on release-5.26):
```
alter table Schemes modify DefaultChannelGuestRole varchar(64);
```
(Size based upon https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/scheme_store.go)
Also altered 'DefaultTeamGuestRole' to varchar(64) whilst here.

**Comment by agnivade** [comment]
Hi @cbarrac - this is essentially https://mattermost.atlassian.net/browse/MM-23545. This is an issue with the migration of the DB code. The column change was part of a migration in version 5.12 as you can see here: https://github.com/mattermost/mattermost-server/blob/316d22c8f1f6eb91445fb23e216eeb6636519187/store/sqlstore/upgrade.go#L684

But I am assuming when the server was initially installed at 5.12, somehow the migration code didn't run. I am not sure how. Did you install a release build of 5.12? Or some other version? As you can see from the JIRA ticket, this was tested by upgrading from 5.11 to other versions and all of them had the schema properly upgraded.

I think the best course is to manually alter the column types as you have mentioned.
