### ISSUE TITLE
Use react-router in routes registered by plugins

### ISSUE THREAD

**Issue by agarciamontoro** [mattermost/mattermost-server#15054]
Thanks to recent changes in the webapp (see PR [#5367](https://github.com/mattermost/mattermost-webapp/pull/5367/)), plugins now have the ability to register custom routes, both under `/plug/:pluginId/` and under `/:teamId/:pluginId/`. There is a really simple example of how to use this new feature in the demo plugin repository: see [PR #102](https://github.com/mattermost/mattermost-plugin-demo/pull/102).

The goal of this ticket is to improve the previous example in the [mattermost-plugin-demo repository](https://github.com/mattermost/mattermost-plugin-demo), registering a more complex component that uses some of the features provided by [react-router](https://reacttraining.com/react-router/web/guides/quick-start) to manage subpaths under the new route. For example, we can register a new component under the team route `/:teamId/:pluginId/demo`, that has a couple of subpaths:

- `/:teamId/:pluginId/demo/sub_path`
- `/:teamId/:pluginId/demo/sub_path_with_query?param=value`

These subpaths must be managed by the root component registered before, using, for example, a `<Switch>` component, that will render a different element depending on the path. In the case of the path with query parameters, we can use the props provided by react-router to change the rendering of the element depending on the parameters.

Some considerations:

- The goal of this ticket is not to demonstrate all of the features provided by react-router, but just a few of the most useful ones, in order to showcase that they are natively available. The ones described here may be a good starting point, but feel free to add any that you personally consider useful.
- The UI of the registered component is not important in this ticket. For instance, the current example linked above simply renders a line of text. The focus should be on demoing the code, so keeping the UI as simple as possible will work.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-25826

**Comment by fmsilva1996** [comment]
I would like to work on this issue, if it's still available?

**Comment by agarciamontoro** [comment]
All yours, @fmsilva1996! If you have any doubt, don't hesitate to ask. You can also send me a DM in Mattermost at `@alejandro.garcia` :)
