### ISSUE TITLE
add `user description` in account settings

### ISSUE THREAD

**Issue by graykode** [mattermost/mattermost-server#15072]
#### Summary
- new feature suggestion
- I want to add a new attribute about `user description` in account settings. or Is there any feature that can use `user description`?
https://github.com/mattermost/mattermost-server/blob/bec2f366a713743bc4495df8a69b615ef078126c/model/user.go#L76

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @graykode,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by graykode** [comment]
@amyblais Thanks for the reply. I created a new feature (https://mattermost.uservoice.com/forums/306457-general/suggestions/40949806-user-description)
