### ISSUE TITLE
Document mattermost-plugin-api/cluster in plugin docs

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#15089]
There is a very interesting feature for Mattermost plugins being used in demo plugin - https://github.com/mattermost/mattermost-plugin-demo/blob/d647f1ed7fdc384f5bc163a6bba689ab4293704e/server/activate_hooks.go#L72

This specific example demonstrates running scheduled jobs in the plugin in HA mode. This is currently not documented in Mattermost server plugins [documentation](https://developers.mattermost.com/extend/plugins/server/hello-world/). It would be really helpful if we documented this.

**Comment by amyblais** [comment]
Thanks, would you like to re-open this issue in the developer docs repo here https://github.com/mattermost/mattermost-developer-documentation/issues?

**Comment by harshilsharma63** [comment]
@amyblais hey, done! - https://github.com/mattermost/mattermost-developer-documentation/issues/672
