### ISSUE TITLE
mattermost server using 100% of CPU until manually restarted

### ISSUE THREAD

**Issue by JohnRillos** [mattermost/mattermost-server#15092]
#### Summary
The `mattermost` process was stuck using 100% of the server's CPU, causing the chat to be completely unresponsive.

#### Steps to reproduce
The immediate trigger for this is unknown.  This seems to happen at random.
Running Mattermost Enterprise (trial) `5.25.0`.  I recently updated it from Mattermost `5.16.0` so this might be related.
Host specs: Digitalocean droplet running Ubuntu 18.04.3 LTS x86_64
CPU: Intel Xeon Gold 6140 (1) @ 2.294GHz

#### Expected behavior
I expect Mattermost CPU usage to be low enough to be usable.  Typical observed CPU usage is ~1%.

#### Observed behavior (that appears unintentional) 
The `mattermost` process (`/opt/mattermost/bin/mattermost`) began using 100% of the server's CPU resources, causing the chat to be completely unresponsive.  Trying to use the client just resulted in a loading indicator.  It was stuck this way for several hours until I was able to SSH in and restart the process.  The problem happened again the next day.

#### Possible fixes
Don't know what actual fix could be.  Short-term fix is restarting the process with `systemctl restart mattermost`.

**Comment by ahmaddanialmohd** [comment]
Hello, @JohnRillos 

Would you mind sharing the `mattermost.log` snippet when the CPU spike happens so we can understand what is going on in the backend first?

Trying to understand if the resource is being consumed by the increase of active connections made by users, database connection, API calls, etc.

**Comment by JohnRillos** [comment]
Logs from July 21, 9:35:53 PM (last logs from before the server was restarted) -> July 22, 4:26:54 PM (when I restarted the server)
```
{"level":"info","ts":1595385353.862093,"caller":"jobs/schedulers.go:74","msg":"Starting schedulers."}
{"level":"info","ts":1595385353.8848143,"caller":"app/license.go:40","msg":"License key from https://mattermost.com required to unlock enterprise features."}
{"level":"info","ts":1595385353.90418,"caller":"app/server.go:525","msg":"Starting Server..."}
{"level":"info","ts":1595385353.9046874,"caller":"app/server.go:594","msg":"Server is listening on [::]:8065","address":"[::]:8065"}
{"level":"info","ts":1595385353.9048836,"caller":"commands/server.go:106","msg":"Sending systemd READY notification."}
{"level":"info","ts":1595453213.959015,"caller":"utils/i18n.go:83","msg":"Loaded system translations","for locale":"en","from locale":"/opt/mattermost/i18n/en.json"}
{"level":"info","ts":1595453213.9637296,"caller":"app/server_app_adapters.go:58","msg":"Server is initializing..."}
{"level":"info","ts":1595453213.9700403,"caller":"sqlstore/supplier.go:227","msg":"Pinging SQL","database":"master"}
{"level":"error","ts":1595453214.0309172,"caller":"app/server_app_adapters.go:152","msg":"Mail server connection test is failed: SendEmailNotifications is not true"}
{"level":"info","ts":1595453214.0356054,"caller":"app/license.go:40","msg":"License key from https://mattermost.com required to unlock enterprise features."}
{"level":"info","ts":1595453214.042185,"caller":"mlog/log.go:167","msg":"Starting up plugins"}
```
Note that `1595385353` (July 21, 9:35pm) is _not_ when the server started using 100% CPU.  That started around July 22nd, ~2:10pm and lasted until I restarted at 4:25pm.

**Comment by agnivade** [comment]
Hi @JohnRillos - This is likely https://mattermost.atlassian.net/browse/MM-26584.

To gather some more data around this, would you be able to do the following when this happens?

- `kill -SIGQUIT $(pgrep mattermost)`
- `journalctl -u mattermost -n 4000 --no-pager > out.txt`

**Comment by JohnRillos** [comment]
Sure, I'll try that if I see this again.  What's interesting is that this server is under very little load at all since there's fewer than 10 users.

**Comment by BaaaZen** [comment]
We had the same problem as @JohnRillos yesterday. Our Mattermost server also isn't high loaded (~25 users, but only active while working time). And the problem occured in the middle of the night (~2:45am) when nobody was active.

I sadly removed the docker container and so the logs of the container while restarting. If it happens again I'll try to provide the output logs, too.

**Comment by agnivade** [comment]
@BaaaZen - Thanks. What is the server version you are running? Did this start happening after you upgraded from a certain version?

**Comment by BaaaZen** [comment]
We're using 5.25.0. I've updated (from version 5.24.1) at the 17th June and the problem occured yesterday for the first time.

**Comment by agnivade** [comment]
This is very interesting. Thank you!
