### ISSUE TITLE
Edit comment box has the wrong markdown example

### ISSUE THREAD

**Issue by DanGid14** [mattermost/mattermost-server#15103]
#### Summary
Edit comment box has the wrong markdown example for striking through my text

#### Steps to reproduce
Go to edit a message and look at the examples below the text box for formatting

#### Expected behavior
Display the correct markdown syntax for striking through my text(~~someText~~)

#### Observed behavior (that appears unintentional) 
I don't have the correct markdown syntax, (--someText--). See screenshot below
![mm](https://user-images.githubusercontent.com/68700449/88303320-d1b0b600-ccfe-11ea-9816-7baa39c0943e.png)

#### Possible fixes
Just change the example to use the correct syntax

**Comment by amyblais** [comment]
@DanGid14 What Mattermost server version are you on? Can you help with an example for an expected behaviour?

**Comment by DanGid14** [comment]
I am on version 4.4.2

**Comment by DanGid14** [comment]
Well I am expecting to see ~~ instead of -- for the example which my screenshot is demonstrating.

**Comment by amyblais** [comment]
@DanGid14 That might be your desktop app version - you can find the server version from Main Menu > About Mattermost.
