### ISSUE TITLE
Interactive Message Update not replacing original

### ISSUE THREAD

**Issue by skyghost2210** [mattermost/mattermost-server#15111]
## Summary
The interactive button is not working as expected. I have posted this issue on mattermost forum and I have found a similar issue but nobody reply
My issue: https://forum.mattermost.org/t/cannot-make-the-attachment-disappear-after-hitting-updated-button/10173/2
Similar issue:  https://forum.mattermost.org/t/interactive-message-update-not-replacing-original/10016/2
Mattermost documentation: https://docs.mattermost.com/developer/interactive-messages.html#message-buttons ( See the gif )

#### Steps to reproduce
Mattermost 5.24.0

#### Expected behavior
I have an interactive message with action buttons, but when I reply to the action the original message supposed to be replaced

#### Observed behavior (that appears unintentional) 
A new message is appearing above the original message

#### Possible fixes
I don't have

**Comment by kaakaa** [comment]
I encountered same issue.

My assumption is that the cause is [here](https://github.com/mattermost/mattermost-server/blob/1e53fe85ad42653f1cbdeb9a1d4447bc3b6d7b3d/app/integration_action.go#L222).
