### ISSUE TITLE
Harden headers

### ISSUE THREAD

**Issue by ArchangeGabriel** [mattermost/mattermost-server#15121]
While analysing response headers coming from Mattermost, I’ve figured they are some common ones missing, namely:
```
X-XSS-Protection "1; mode=block";
X-Content-Type-Options "nosniff";
```
Thus, I’m adding them with the `add_header` option of nginx, but I think it would be better if those could be incorporated directly in Mattermost.

I’m not familiar enough with the project to know where to patch for those, since I can find multiple reference to headers with the search tool (e.g. https://github.com/mattermost/mattermost-server/blob/4c50c7c59b6c1b0c75a5aaa2661d4c77144c9067/web/oauth.go, https://github.com/mattermost/mattermost-server/blob/5cb16c9fc7f4664be8d5a1e403f8e312d9f1389d/services/imageproxy/local.go, https://github.com/mattermost/mattermost-server/blob/2de5f75f4748546fe9018c090a6afc5757302a53/web/handlers.go).

**Comment by amyblais** [comment]
@ArchangeGabriel Would you be open to creating a feature request for this here https://mattermost.uservoice.com/forums/306457-general?

Our security team gave feedback that X-Xss-Protection is not necessary since CSP enforces this already - please see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection. For nosniff, they don't see any harm either.

**Comment by ArchangeGabriel** [comment]
> @ArchangeGabriel Would you be open to creating a feature request for this here https://mattermost.uservoice.com/forums/306457-general?

I don’t want to create yet another account honestly.

> Our security team gave feedback that X-Xss-Protection is not necessary since CSP enforces this already - please see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection. For nosniff, they don't see any harm either.

From the page you’ve linked `they can still provide protections for users of older web browsers that don't yet support CSP.`. Sure, Mattermost will likely not work very well in this case, but you never know!

(JFYI, those missing headers were reported by https://securityheaders.com/)
