### ISSUE TITLE
Export is taking a lot of time

### ISSUE THREAD

**Issue by yogeshkk** [mattermost/mattermost-server#15133]
#### Summary
We have to migrate Matermost to the new one Matermost so we need to export and import to the new one but export is taking a lot of time. In 12 hours the command is still running and I got file size around 1.6M and growing at a very slow rate 

We are running Matermost in k8s. 
mattermost-prod-app:5.7.0

I have checked in grafana there is no memory or CPU spike or throttling. 

```
/mattermost # mattermost export bulk /mattermost/tmp/bulk_data.json --all-teams
{"level":"info","ts":1595914186.0362265,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'en' from '/mattermost/i18n/en.json'"}
{"level":"info","ts":1595914186.036294,"caller":"app/app.go:143","msg":"Server is initializing..."}
{"level":"info","ts":1595914186.0489316,"caller":"sqlstore/supplier.go:207","msg":"Pinging SQL master database"}
{"level":"info","ts":1595914186.4530478,"caller":"app/license.go:42","msg":"License key valid unlocking enterprise features."}
{"level":"info","ts":1595914186.4530838,"caller":"app/plugin.go:130","msg":"Starting up plugins"}
```

#### Steps to reproduce
kubectl exec into mattermost pod and run the export command

#### Expected behavior
It should able to export faster. Is there any suggestion to make export faster as we have to plan migration activity.

**Comment by yogeshkk** [comment]
Thanks @agnivade  for your reply.

I will try --worker and will let you know. We are not migrating to fresh new instant. We have one already in place we are merging this to that. We want to persevere all groups and history so we are planning on exporting data out of this and importing to the new ones. 

Can we set up a new version MM as read-only server and point to the old database just for backup?

**Comment by agnivade** [comment]
Ah I see. So if the objective is to merge two data sets, you can upgrade this old instance to use a newer mattermost. And then use bulk export (which should be much faster) to extract out the data from there. And once you have that, import it into your final MM server.

Will that work?

**Comment by yogeshkk** [comment]
As we are planning to decommission this we were not keeping this up to the latest but in this case, We can plan to upgrade before migration. 

We are at 5.7 which minimum version you recommend (the latest)? also, the upgrade document does not cover the K8S upgrade do we have the same somewhere?

**Comment by agnivade** [comment]
Yes, I was suggesting to upgrade because then we would get the latest code which will allow us to export faster. This is purely for that purpose. I would suggest to upgrade to the latest quality release of 5.25.1.

For k8s, we have a page here: https://docs.mattermost.com/install/install-kubernetes.html?src=dl#installing-mattermost-on-kubernetes. For more questions feel free to ask them in the ~Developers: Cloud channel on community.mattermost.com.

**Comment by agnivade** [comment]
Hey @yogeshkk - just checking in on this. Were you able to resolve this?

**Comment by yogeshkk** [comment]
@agnivade Hi.. sorry forgot about this. Yes, we upgraded MM and it works. Thanks Will be closing this.
