### ISSUE TITLE
Github connect: this version of browser not supported message

### ISSUE THREAD

**Issue by matttbc** [mattermost/mattermost-server#15141]
#### Summary
GitHub plugin can't connect to organisation

#### Steps to reproduce
Install and configure GitHub plugin. In a channel /github connect

#### Expected behavior
I believe this should launch the Github connection window

#### Observed behavior (that appears unintentional) 
Popup says 'This version of your browser is no longer supported by Mattermost
Download the Mattermost app or use a supported browser for a better experience.'
![image](https://user-images.githubusercontent.com/45286822/88823129-a3c6e800-d1bc-11ea-8e23-c973dd7762cc.png)

**Comment by amyblais** [comment]
@matttbc What browser are you on?
