### ISSUE TITLE
Slack import processes only the users

### ISSUE THREAD

**Issue by M4N0JKUM4R** [mattermost/mattermost-server#15150]
When I exported all the data from the Slack team, the files are good with 10,000+ messages inside all of them. I tried to import it into my new Google Cloud instance and message was "The import was successful" but it just imported the users. No channels, no messages. What could go wrong in following the simple 2 steps?

**Comment by amyblais** [comment]
@M4N0JKUM4R Would you be able to help share more details from here: https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?
