### ISSUE TITLE
Easier change of focus for threads

### ISSUE THREAD

**Issue by riggasconi** [mattermost/mattermost-server#15175]
Currently the right section of the app (thread) changes only if I click on "reply". It'd be good if it changed whenever I clicked on any message, be that part of a thread or a single one (it'd be coupled in both the mid and right sections).

**Comment by amyblais** [comment]
Thanks, appreciate your feedback,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
