### ISSUE TITLE
Attachment size limit affects custom plugin size

### ISSUE THREAD

**Issue by dj5k** [mattermost/mattermost-server#15184]
#### Summary
The setting `Maximum File Size` responsible for limiting "Maximum file size for message attachments" (as per description) also affects the size limit of custom plugins that are uploaded through the UI or the CLI. This connection is not explained anywhere to my knowledge.

#### Steps to reproduce
Mattermost server version 5.25.1 - E10 license

* Go to system console -> file storage and set `Maximum File Size` to e.g. 25
* Try to upload a plugin that exceeds that size, e.g. https://github.com/moussetc/mattermost-plugin-dice-roller/releases/tag/v3.0.0 (35 mb)

#### Expected behavior
Multiple possibilities:
Ideally don't have the same upload size limitation as the attachment files, but rather none or a separate one.  
Or document the fact that this limit applies to plugin uploads in the description text where plugins are uploaded / installed.

#### Observed behavior (that appears unintentional) 

The upload starts but eventually there is an error displayed in the system console below the upload button reading `Received invalid response from the server.` with HTTP status code 400.

#### Possible fixes

Easiest would likely be an update to the description text and documentation. I'm not well versed enough to point to the code where uploaded plugin size is checked.

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-27517.

**Comment by Tragen** [comment]
Today I had the same problem and found this bug report
https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/issues/101
For me there is also no reason to limit the plugin upload file size because of this parameter.

**Comment by amyblais** [comment]
Closing as the documentation for this has been merged https://github.com/mattermost/docs/pull/5013.
