### ISSUE TITLE
Ldap authentication not working but test is successful (no information on logs)

### ISSUE THREAD

**Issue by aseques** [mattermost/mattermost-server#15190]
I am trying to setup the LDAP authentication on my recently installed mattermost instance. After a bit of checking (and copying from other apps connected to the same AD server) i got the test working 

![Screenshot_20200806_140457](https://user-images.githubusercontent.com/555542/89529908-dccf1000-d7ed-11ea-8d2b-25e8649c8292.png)

#### Steps to reproduce

Mattermost Version: 5.25.2
Database Schema Version: 5.25.0
Database: mysql
Licensed to: https://matter.example.com
#### Expected behavior
Users should be able to authenticate when valid users / passwords are introduced.

#### Observed behavior (that appears unintentional) 

After configuring everything so mattermost can connect to my AD server, I can't synchronize the users neither login using AD credentials, the only error is requesting me to enter a valid email or username (I tried both and still can't login)

> {"level":"error","ts":1596715190.7180276,"caller":"mlog/log.go:175","msg":"Enter a valid email or username and/or password.","path":"/api/v4/users/login","request_id":"1g4gnggmpbfhufnp5n44tstmor","ip_addr":"::1","user_id":"","method":"POST","err_where":"login","http_code":401,"err_details":""}
> {"level":"error","ts":1596715190.893361,"caller":"mlog/log.go:175","msg":"Enter a valid email or username and/or password.","path":"/api/v4/users/login","request_id":"34973jwctfbxmb5ky1b1awg1yr","ip_addr":"127.0.0.1","user_id":"","method":"POST","err_where":"login","http_code":401,"err_details":""}

I enabled  tracing in config.json to see if there was more information but I couldn't get much more (that I can understand at last)
See also attached the configuration file (some parts redacted) with the settings I currently have.

[trace_logs.txt](https://github.com/mattermost/mattermost-server/files/5034753/trace_logs.txt)
[config.txt](https://github.com/mattermost/mattermost-server/files/5034760/config.txt)

**Comment by amyblais** [comment]
@aseques Did you have a chance to look through the troubleshooting doc for tips: https://docs.mattermost.com/deployment/sso-ldap.html#i-updated-a-user-account-in-ad-ldap-and-they-can-no-longer-log-in-to-mattermost?

**Comment by aseques** [comment]
Hi @amyblais, I already checked on that page and others, but I couldn't find the message in any of the forums, bugs of mattermost.

**Comment by mkraft** [comment]
@aseques Probably `objectGUID` is not the configuration value you want for `LoginIdAttribute`, unless your users are logging in with, like, `raUGqSO5G06DmgFJnGXxKw==`. Probably you'll want to use either `userPrincipalName` or `sAMAccountName`.

**Comment by aseques** [comment]
Great, it seems that it worked, I tried changing only the 'Login field name" and it  didn't work, after setting both "Login field name" and "ID attribute", login started working.

![Screenshot_20200810_090028](https://user-images.githubusercontent.com/555542/89758395-f28f4e80-dae7-11ea-8d99-8f11dffd9260.png)

Worth noting that the configuration tip is misleading here (specially because when set to wrong value I get no reply from server)

> The attribute in the AD/LDAP server used as a unique identifier in Mattermost. It should be an AD/LDAP attribute with a value that does not change **such as uid for LDAP or objectGUID for Active Directory**. If a user's ID Attribute changes, it will create a new Mattermost account unassociated with their old one.

**Comment by aseques** [comment]
Worth adding too, that using 'userPrincipalName' in the email field let some users without login with the error 
> "Couldn't save the user","error":"User.IsValid: Invalid email.
Changing the attribute to 'email' fixed the issue.

**Comment by amyblais** [comment]
Got feedback from devs that this would be a potential config UX and/or docs improvement. Our UX team is currently redesigning this section for improved usability.

**Comment by aseques** [comment]
Thanks, I'm closing it.
