### ISSUE TITLE
i18n (Chinese) search doesn't work.

### ISSUE THREAD

**Issue by tru2dagame** [mattermost/mattermost-server#15233]
#### Summary
Chinese search doesn't work.

#### Steps to reproduce
Following with the setup doc: https://docs.mattermost.com/install/i18n.html#id1
You can't see the sql trace debug with `to_tsvector('simple_zh_cfg', 'xxxx') @@ to_tsquery('simple_zh_cfg', 'xxxx');`

#### Expected behavior
The `simple_zh_cfg` setting is stick with `english`.

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/1673006/89994772-27073400-dcbb-11ea-8328-37e184fd6184.png)

![image](https://user-images.githubusercontent.com/1673006/89996228-1f488f00-dcbd-11ea-8d3a-96940835b030.png)

#### Possible fixes
Use `default_text_search_config` when searching:

![image](https://user-images.githubusercontent.com/1673006/89996041-e27c9800-dcbc-11ea-9444-f65b9adabc54.png)

It seems this commit https://github.com/mattermost/mattermost-server/commit/04d43b072c541670a6650acdee38004c0edcde51 write down the fixed `english` parameter

**Comment by amyblais** [comment]
@tru2dagame Could one of these threads help:
 - https://forum.mattermost.org/t/aliyun-postgresql-cant-config-default-text-search-config-how-to-enable-chinese-search/7931/6
 - https://forum.mattermost.org/t/default-text-search-config-setting-not-used/9850

If not, I'm happy to continue troubleshooting,

**Comment by amyblais** [comment]
Also, what Mattermost server version and OS are you on?

**Comment by tru2dagame** [comment]
Hi @amyblais,

- The first forum post is going to set `default_text_search_config`. 

That isn't my case. I have successfully set that value due to the document

- The second forum post is the problem.

https://mattermost.atlassian.net/browse/MM-25554
> Right now we have `english` hardcoded as part of the text search functions in Postgres.
It seems no update for over two months.

My Mattermost server version is `5.25.2`.

Let me clarify my the problem:
- I can search Chinese words the post by manually searching raw sql in postgres. That means the Postgres EXTENSION `zhparser` is installed correctly.
- But I can't search Chinese correctly in the Mattermost GUI clients. From the debug log I can it always use the hardcoded `english` when searching.

**Comment by tru2dagame** [comment]
Hi @amyblais, any updates for this?

**Comment by gleke** [comment]
Hi @amyblais, any updates for this?

**Comment by gleke** [comment]
Hi @tru2dagame,my qq:237401117,Hope to have a chance to communicate with you

**Comment by amyblais** [comment]
The ticket https://mattermost.atlassian.net/browse/MM-25554 is in one of our dev team's queue but not scheduled for a release yet.

**Comment by Sharuru** [comment]
Have tried migrate from PostgreSQL to MySQL during new year holiday but seems failed.
No idea about how to convert the user credential in the database.
Can accept reset all user password after migrate, but I can not login in the admin account :(

I think CJK text search issue should be considered for those PostgreSQL users while Mattermost is being used by more and more people nowadays.

**Comment by Sharuru** [comment]
Any updates? 

https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/post_store.go#L1895

**Comment by agnivade** [comment]
Hi all, I've raised a PR here: https://github.com/mattermost/mattermost-server/pull/20472. Thank you for your patience.
