### ISSUE TITLE
Write Cypress test: "MM-T486 Users with the same firstname in their username should not get a mention when one of them leaves a channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15256]
This is part of __Cypress Test Automation Hackfest 🚀__.  Please read more at https://github.com/mattermost/mattermost-server/issues/15120.

See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article class="mb-32"><h1 class="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tighter leading-tight md:leading-none mb-12 text-center md:text-left">MM-T486 Users with the same firstname in their username should not get a mention when one of them leaves a channel</h1><div class="max-w-2xl mx-auto"><div><h3>Steps </h3>Users with the same firstname in their username should not get a mention when one of them leaves a channel<br>––––––––––––––––––––––––––<ol><li>Create two test users - "test" and "test.one"</li><li>"test" user create a new channel and add "test.one" to it</li><li>"test.one" go to the new channel so that the mention badge received for being added to the channel disappears</li><li>"test" user go to Off-Topic channel</li><li>"test.one" leave the new channel you were added to by "test" user</li></ol><h3>Expected</h3><ul><li>"test" user should not receive a mention when "test.one" leaves the channel</li></ul><hr></div></div></article>

**Test Folder:** `/cypress/integration/notifications`
**Test code arrangement:**
```
describe('Notifications', () => {
    it('MM-T486 Users with the same firstname in their username should not get a mention when one of them leaves a channel', () => {
        // code
    });
});
```

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
I'd like to do this please!

**Comment by josephk96** [comment]
For this, since Cypress doesn't support multiple browsers, would it be okay if I logout and login as the other user several times? I know it's expensive, but I'm not sure what would be a better way to do it

**Comment by saturninoabril** [comment]
Thanks @josephk96 and yup, that's fine.

**Comment by josephk96** [comment]
Thanks for the quick reply Saturn!

**Comment by jfrerich** [comment]
PR merged.  Closing.
