### ISSUE TITLE
Write Cypress test: "MM-T398 Use team invite link to sign up using email and password"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15257]
This is part of __Cypress Test Automation Hackfest 🚀__.  Please read more at https://github.com/mattermost/mattermost-server/issues/15120.

See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article class="mb-32"><h1 class="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tighter leading-tight md:leading-none mb-12 text-center md:text-left">MM-T398 Use team invite link to sign up using email and password</h1><div class="max-w-2xl mx-auto"><div><h3>Steps </h3><ol><li>Go to Main Menu ➜ Invite People and click 'Copy Link' next to the Team Invite Link</li><li>Copy the link</li><li>Log out or open an incognito window</li><li>Paste the link in</li><li>On the Sign Up page, click "Email and password"</li><li>Enter a username and email address that you can access (can use plus sign, such as `linda+test@mattermost.com), and a password</li><li>Click "Create Account"</li><li>Verify URL on `You are almost done...` screen does not have `undefined` team name</li><li>Receive email with link to verify email address, click the link (or open it in incognito window), and enter password</li></ol><h3>Expected</h3><ul><li>Step 8. Starting in v5.24 URL in address bar does not have an `undefined` team name appended</li><li>Email verification is successful and account is created.</li><li>On the login page, email is pre-filled with focus on the password field.</li><li>Once filled out you are redirected to the login page</li><li>If the email address and username you use is properly formatted you <strong>do not</strong> see an error that reads "<em>Enter a valid email or username and/or password, or sign in using another method.</em>"&nbsp;</li></ul><hr></div></div></article>

**Test Folder:** `/cypress/integration/onboarding`
**Test code arrangement:**
```
describe('Onboarding', () => {
    it('MM-T398 Use team invite link to sign up using email and password', () => {
        // code
    });
});
```

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
I'd like to do this please!

**Comment by saturninoabril** [comment]
Sure and thanks @josephk96!

**Comment by josephk96** [comment]
No problem @saturninoabril !
Just a few quick questions -
1. When I visit the team invite link that I copied from the 'Invite People' modal, I don't see 'Email and password', I am automatically directed to that screen. Are there any authentication plugins that I have to install first? If so, could you please link me to a file that I could use for reference?
2. For step 8, I am not seeing the 'You are almost done...' screen, after inputting my user details and creating the account, I am automatically redirected to the team page. Am I missing something?

Thanks Saturn!

**Comment by saturninoabril** [comment]
1. It's in the case where other authentication options are enabled like with SAML, Gitlab, etc. Since it's being reset and disabled for every Cypress run, it's good to assume that it's redirected to Signup page.
2. You'll need to update the config to require email verification. `{"EmailSettings": {"RequireEmailVerification": true}}`

**Comment by josephk96** [comment]
Thanks for the clarification, Saturn, it was very helpful!

**Comment by saturninoabril** [comment]
Thanks @josephk96! PR merged; closing this now.
