### ISSUE TITLE
Write Cypress test: "MM-T385 Invite new user to closed team using email invite"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15258]
This is part of __Cypress Test Automation Hackfest 🚀__.  Please read more at https://github.com/mattermost/mattermost-server/issues/15120.

See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article class="mb-32"><h1 class="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tighter leading-tight md:leading-none mb-12 text-center md:text-left">MM-T385 Invite new user to closed team using email invite</h1><div class="max-w-2xl mx-auto"><div><h3>Steps </h3><ol><li>Ensure that Main Menu ➜ Team Settings ➜ Allow any user with an account on this server... is set to `No`</li><li>Ensure "Allow only users with a specific email domain to join this team" is blank (i.e. any email address can be invited)</li><li>Open Main Menu and click `Invite People`</li><li>Enter an email address you can access (test user may access email via inbucket)</li><li>Click `Invite Members`</li><li>Check your email, and open the email with subject line:</li><li>`[Mattermost] invited you to join Team</li><li>Open the `Join Team` link in a separate / incognito browser</li><li>Create a new account using the email address you sent the invite to</li></ol><h3>Test Data</h3><img src="https://smartbear-tm4j-prod-us-west-2-attachment-rich-text.s3.us-west-2.amazonaws.com/embedded-f3277290f945470c4add5d21ef3dc7ca7b74388fc7152bfb6b99ae58c66a95a8-1579118958795-2020-01-15_15-08-40.png" style="width: 175px;" class="fr-fil fr-dii"><img src="https://smartbear-tm4j-prod-us-west-2-attachment-rich-text.s3.us-west-2.amazonaws.com/embedded-f3277290f945470c4add5d21ef3dc7ca7b74388fc7152bfb6b99ae58c66a95a8-1579118985721-2020-01-15_15-07-48.png" style="width: 123px;" class="fr-fil fr-dii"><h3>Expected</h3>New user is viewing Town Square channel of that team and "Welcome to Mattermost" tutorial is displayed in the center channel<hr></div></div></article>

**Test Folder:** `/cypress/integration/team_settings`
**Test code arrangement:**
```
describe('Team Settings', () => {
    it('MM-T385 Invite new user to closed team using email invite', () => {
        // code
    });
});
```

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephk96** [comment]
I'd like to give this a try bro!

**Comment by saturninoabril** [comment]
Awesome, thanks @josephk96!

**Comment by saturninoabril** [comment]
https://github.com/mattermost/mattermost-webapp/pull/6222 merged. Thanks @josephk96! Closing.
