### ISSUE TITLE
Write Cypress test: "MM-T645 Delete Incoming Webhook"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15254]
This is part of __Cypress Test Automation Hackfest 🚀__.  Please read more at https://github.com/mattermost/mattermost-server/issues/15120.

See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article class="mb-32"><h1 class="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tighter leading-tight md:leading-none mb-12 text-center md:text-left">MM-T645 Delete Incoming Webhook</h1><div class="max-w-2xl mx-auto"><div><h3>Steps </h3>Delete Incoming Webhook<br>–––––––––––––––––––––––––<br>1. Create an incoming webhook and send a webhook message to a channel. Verify that the message is posted into the channel<br>2. Click "Delete" next to the existing incoming webhook<br>3. Click "Delete" in the confirmation dialog<br>4.Again, send a webhook message to a channel.<h3>Expected</h3><ul><li>The webhook is removed and does post a message into a channel.</li></ul><hr></div></div></article>

**Test Folder:** `/cypress/integration/integrations/incoming_webhook`
**Test code arrangement:**
```
describe('Incoming Webhook', () => {
    it('MM-T645 Delete Incoming Webhook', () => {
        // code
    });
});
```

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by JeremyShih** [comment]
Hi, I would like to take this one.
