### ISSUE TITLE
Write Cypress test: "MM-T307 Cancel a file upload"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15259]
This is part of __Cypress Test Automation Hackfest 🚀__.  Please read more at https://github.com/mattermost/mattermost-server/issues/15120.

See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article class="mb-32"><h1 class="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tighter leading-tight md:leading-none mb-12 text-center md:text-left">MM-T307 Cancel a file upload</h1><div class="max-w-2xl mx-auto"><div><h3>Steps </h3>Cancel a file upload<br>–––––––––––––––––––––––––<ol><li>Click the paper clip icon on the message box and select a LARGE file to attach</li><li>Quickly, while it's still uploading, click or tap the `X` on the file attachment thumbnail (while it still shows loading indicator)</li></ol><h3>Expected</h3><ul><li>Upload is canceled</li><li>Thumbnail disappears</li><li>Can attach a different file, let it finish uploading, and post the message with that attachment.</li></ul><hr></div></div></article>

**Test Folder:** `/cypress/integration/files_and_attachments`
**Test code arrangement:**
```
describe('Files and Attachments', () => {
    it('MM-T307 Cancel a file upload', () => {
        // code
    });
});
```

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by jfrerich** [comment]
PR merged. Closing
