### ISSUE TITLE
Write Cypress test: "MM-T2382 Center channel scroll"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15253]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article class="mb-32"><h1 class="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tighter leading-tight md:leading-none mb-12 text-center md:text-left">MM-T2382 Center channel scroll</h1><div class="max-w-2xl mx-auto"><div><h3>Steps </h3>Center channel scroll<br>————————————————————————————<ol><li>As the test user open a channel and scroll all the way to the bottom</li><li> As another user, make several post in the channel</li><li>As the test user observe the open channel</li></ol><h3>Expected</h3><ul><li>As post appear from the other user, the channel is scrolled down so that post are always visible</li></ul><hr></div></div></article>

**Test Folder:** `/cypress/integration/scroll`
**Test code arrangement:**
```
describe('Scroll', () => {
    it('MM-T2382 Center channel scroll', () => {
        // code
    });
});
```

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by saturninoabril** [comment]
Thanks @M-ZubairAhmed for taking this one!

**Comment by jfrerich** [comment]
This issue appears stale. and I’m removing the `Up For Grabs` label.  If work is ongoing, please re-add the label.  If there is an existing PR, please link it to the issue.  Thanks!

**Comment by jfrerich** [comment]
This issue appears stale. and I’m adding the `Up For Grabs` label.  If work is ongoing, please remove the label.  If there is an existing PR, please link it to the issue.  Thanks.

**Comment by seongwon-kang** [comment]
This test is already exists in https://github.com/mattermost/mattermost-webapp/blob/e9cda6cd7ffe11d6f6cf1794c61368c201c6dd69/e2e/cypress/integration/scroll/channel_scroll_spec.js#L58

**Comment by saturninoabril** [comment]
@seongwon-kang Oh, thanks for checking! Closing.
