### ISSUE TITLE
Write Cypress test: "MM-T334 Drag and Drop - Error message expected when trying to drop a folder"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15260]
See our [end-to-end testing documentation](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article class="mb-32"><h1 class="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tighter leading-tight md:leading-none mb-12 text-center md:text-left">MM-T334 Drag and Drop - Error message expected when trying to drop a folder</h1><div class="max-w-2xl mx-auto"><div><h3>Steps </h3>Drag and Drop - Error message when trying to drop a folder<br>–––––––––––––––––––––––––<ol><li>Drag and drop a folder into a Mattermost channel in the center</li><li>Open a thread in the RHS that is long enough to scroll up in so you don't see the message input box</li><li>Drag and drop a folder into the RHS</li></ol><h3>Expected</h3><ul><li>Error message saying "Folders cannot be uploaded. Please drag all files separately"</li><li>In the RHS, make sure you are automatically scrolled to the bottom and can see the error message.</li></ul><hr></div></div></article>

**Test Folder:** `/cypress/integration/files_and_attachments`
**Test code arrangement:**
```
describe('Files and Attachments', () => {
    it('MM-T334 Drag and Drop - Error message expected when trying to drop a folder', () => {
        // code
    });
});
```

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by vithun** [comment]
Hi, I'm interested in picking this up. This will be my first contribution here.

**Comment by vithun** [comment]
<img width="525" alt="Screenshot 2020-08-16 at 20 53 56" src="https://user-images.githubusercontent.com/767595/90342786-d49f7d80-e002-11ea-89da-b4c3356e0345.png">

The Cypress `attachFile` command seems to internally depend on fixtures. And when I refer to a folder name itself rather than a specific file, it doesn't seem capable of recognising it.

**Comment by vithun** [comment]
There's a related issue here: https://github.com/abramenal/cypress-file-upload/issues/69

Will see if there's another way around this.

**Comment by vithun** [comment]
Thought I'll trick the test to think it's a directory by uploading multiple files. That approach doesn't work for two reasons:
- Uploading multiple files seems to be a valid operation.
- Looking at the implementation [here](https://github.com/mattermost/mattermost-webapp/blob/e71ac4d7c7df64ae11f885a54697ed1b8eac5bf6/components/file_upload/file_upload.jsx#L357-L381), it does look like this error comes up when an empty list of files is encountered after directories are excluded.
  - So if I'm unable to pass through a directory, I'll have to next figure out passing an empty file list somehow. But even if that works, it's cheating a bit at this point as I'm looking at implementation details when writing an E2E test – which isn't great.

Any thoughts @saturninoabril?

**Comment by saturninoabril** [comment]
Hello @vithun! Thanks for your interest.
Right, multiples files upload is valid. No, it's different from empty list of files. You'll get "'You are uploading an empty file: {filename}'" in that case.
Let me see.

**Comment by saturninoabril** [comment]
Closing as not currently possible to automate with Cypress.
