### ISSUE TITLE
"Channel Grouping and Sorting" description inverted

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#15272]
Currently the admin description for "Channel Grouping and Sorting" is flipped:
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/lluY2evG/2020-08-16_12-55-17.jpeg)

This was rather confusing when moving up to .26 and wanting to enable this channel grouping functionality.

**Comment by amyblais** [comment]
@ylluminate Those settings are two different features. Can you help with repro steps, expected behaviour, and observed behaviour to help me understand the issue you're facing better?

**Comment by amyblais** [comment]
Closing as this is an old Issue, but feel free to re-open it if it still reproduces,
