### ISSUE TITLE
[MM-24753] Improve error message when plugin crashes during slash command execution

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-server#15285]
#### Summary

When using a slash command that crashes a plugin, the user receives an unfriendly message.

Observed:
> Command with a trigger of '/jira' not found. Click here to send as a message.

Expected:
> Plugin for the `jira` command is not working. Please contact your system administrator.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-24753

**Comment by asimsedhain** [comment]
Hey, I would like to try this.
