### ISSUE TITLE
mmctl - how to move channels between teams?

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#15298]
Is there a way to move channels between teams with `mmctl`? Due to the testing and adoption of Bleve, many of us are seeing the hang issues and similarly seeing / receviing recommendations to use `mmctl` instead of `mattermost` for admin functions.

When will see see `mmctl` have feature parity with `mattermost`?  For example, we don't seem to currently be able to move channels between teams with `mmctl`.

**Comment by amyblais** [comment]
It seems this is explained here https://github.com/mattermost/mmctl/blob/master/docs/mmctl_channel_move.rst.

@mgdelacroix / @isacikgoz Should I ask Justine to document it (https://docs.mattermost.com/administration/mmctl-cli-tool.html)?

**Comment by ylluminate** [comment]
Interesting. Right, I hunted and hunted for that, but kept running into this documentation where it's absent: https://docs.mattermost.com/administration/mmctl-cli-tool.html#mmctl-channel
