### ISSUE TITLE
Ambiguous documentation regarding supported PostgreSQL versions

### ISSUE THREAD

**Issue by robert-scheck** [mattermost/mattermost-server#15295]
#### Summary, Steps to reproduce and Observed behavior
As of writing, https://docs.mattermost.com/administration/important-upgrade-notes.html is unfortunately ambiguous about the supported PostgreSQL versions: It currently says that PostgreSQL 10 is supported for the latest Mattermost version, while it also says that PostgreSQL 10+ is required for new installations. Given there is already PostgreSQL 12, this unfortunately leaves open whether Mattermost supports PostgreSQL 12 or just 10.x. So does the "+" actually mean 10.x-only or really 10/11/12/...? This should never be left for guessing to the administrator, but always be clearly documented.

#### Expected behavior
Clear, non-ambiguous documentation of supported PostgreSQL versions, as e.g. Red Hat Enterprise Linux 8 and CentOS 8 are only shipping PostgreSQL 12.x (rather than ancient PostgreSQL versions).

#### Possible fixes
Please note that I do not know which versions of PostgreSQL are actually really supported by Mattermost, so the following are just textual suggestions for the documentation to improve the situation, while the actual versions needs to be inserted properly indeed.

  * "New installs will require PostgreSQL 10.x, but PostgreSQL 11 (or later) is not yet supported."
  * "New installs will require PostgreSQL 10 (or later), but PostgreSQL 14 (or later) is not yet supported."

**Comment by amyblais** [comment]
Our devs are looking into this,

**Comment by amyblais** [comment]
We have confirmed that we support PostgreSQL 11. Dev team will need to run tests to determine whether we officially support PostgreSQL 12.

**Comment by robert-scheck** [comment]
Thank you. Is there already any intermediate status update for PostgreSQL 12?

**Comment by amyblais** [comment]
We have a ticket open to do tests on PostgreSQL 12: https://mattermost.atlassian.net/browse/MM-28550.

**Comment by robert-scheck** [comment]
Is there meanwhile any rough estimation when this will be handled?

**Comment by amyblais** [comment]
@robert-scheck An update: testing was completed and all Postgres 10, 11 and 12 versions passed and are working.

**Comment by robert-scheck** [comment]
Cool! Now, only the documentation needs to be clarified. My proposal is:

> "New installs will require PostgreSQL 10 (or later), but PostgreSQL 13 (or later) is not yet supported."

**Comment by amyblais** [comment]
Closing out some older issues, this can be re-opened as needed,

**Comment by TwizzyDizzy** [comment]
I totally concur with the original sentiment of this issue. By now, PostgreSQL `14.x` is the most recent version.

Yet we can only infer from the documentation combined with the [ticket mentioned above](https://mattermost.atlassian.net/browse/MM-28550), that the most recent supported PostgreSQL version is 12. And that was for Mattermost `5.30` (according to JIRA), which means, effectively, that if you want to play it safe you will only go with `10.x` which will be going EOL this november (`2022-11-10`).

Is there an actual process or testing scenario (publicly or internally) that checks for PostgreSQL compatability?

Cheers
Thomas

**Comment by robert-scheck** [comment]
@amyblais, could you re-open this pleae, because the documentation part seems still not to be covered…

**Comment by TwizzyDizzy** [comment]
@amyblais there you go: https://github.com/mattermost/docs/issues/5778

Cheers
Thomas
