### ISSUE TITLE
Highlighting text and moving mouse off-screen causes further text to be written right to left

### ISSUE THREAD

**Issue by mattinmir** [mattermost/mattermost-server#15296]
#### Summary
Highlighting text and moving mouse off-screen causes further text to be written right to left

#### Steps to reproduce
Using Mattermost desktop app, version 4.4.0
Have Mattermost open on one monitor, with a second connected monitor to the left
In a channel text bar, type some letters, then highlight the text right-to-left with the mouse, making sure the mouse leaves the left side of the screen and enters the second monitor on the left. The mouse movement should be swift, moving slowly can't replicate the issue
Now continue typing and each new letter that is typed appears at the left of the text bar (text is still left-aligned)

#### Expected behavior
Text should continue to be written left-to-right

#### Observed behavior (that appears unintentional) 
Each new letter that is typed appears at the left of the text bar (text is still left-aligned)

**Comment by amyblais** [comment]
@mattinmir Do you see the same issue on desktop app v4.5.0?
What OS and version are you on?
What Mattermost server version are you on?
Does this also reproduce on webapp?
