### ISSUE TITLE
"Start trial" message is unreadable in System Console with dark theme on first load

### ISSUE THREAD

**Issue by Matterchen** [mattermost/mattermost-server#15311]
#### Summary
Black text on dark background in the "Start trial" message on v5.26.

#### Steps to reproduce
1. Enable dark theme
2. Open System Console
3. Click on SAML or AD/LDAP

#### Expected behavior
See Start trial message

#### Observed behavior (that appears unintentional) 
Start trial message has black text on dark background, which is unreadable.
<img width="980" alt="Unreadable start trial message" src="https://user-images.githubusercontent.com/33878967/90671635-d5563080-e209-11ea-9911-f87e99a25a8c.png">

Refresh (Cmd+R) of browser makes the background white

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-27972.
