### ISSUE TITLE
Can't mark as unread on mobile

### ISSUE THREAD

**Issue by talmahaj** [mattermost/mattermost-server#15333]
#### Summary
When long pressing a message, no option to mark as unread on iOS

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Using newest version on iOS
Am in a DM with another person
Tapping message opens up options, but mark as unread no longer appears as an option

#### Expected behavior
Message options would include "mark as unread"

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@talmahaj I believe I've seen this occasionally in the past, but don't have specific repro steps.

Which server version are you on? Is this happening for you consistently, or only occasionally?

**Comment by JugarBoliche** [comment]
I have noticed the same issue, where Mark as Unread is no longer an option on iOS mobile app when long pressing on a message in a channel. We are on 5.27.0 and I am also on the most up to date version of the iOS app that is available (1.35.1). I am not sure when it stopped working though.

**Comment by amyblais** [comment]
I'll close this for now as it's an older issue, but feel free to re-open it if the issue persists on the latest version,
