### ISSUE TITLE
CircleCI Plugin Bounty ($2,000 for winners, Sept 1 - Oct 31, 2020)

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#15352]
## Mattermost Plugin Bounty Program

Mattermost has launched a plugin bounty program to work with our integrations community to create highly-requested plugins for:

* CircleCI
* Nagios
* Bitbucket
* Splunk

The bounty for each plugin is $2,000, plus an exclusive Mattermost swag bag! The period for submissions is September 1 - October 31, 2020.

If you’re interested joining the program:

* Sign in to https://community.mattermost.com, join the Contributors team and direct message @jason.blais, or
* Email jason[at]mattermost.com with the subject “Mattermost Plugin Bounty Program”

### Eligibility

To be eligible for the cash prize, please complete the following before submitting your plugin:

1. [Contributor License Agreement (CLA)](https://mattermost.org/mattermost-contributor-agreement/) - you have completed this if you’ve contributed to Mattermost before
2. Signed acknowledgement of the eligibility requirements and rules of the Bounty Program as described in this issue.
3. [Banking information form](https://docs.google.com/forms/d/e/1FAIpQLScw5E8h2z7QOuoabPjvcCqQ4mMdiPikXNODEaCGbuI4IsgF-w/viewform) - allows our finance department to verify we are able to send the prize to you. Eligibility is limited to countries we can pay the bounty to. Wires to notable banks are preferred, but other options exist.
4. [Vendor information form](https://docs.google.com/forms/d/e/1FAIpQLSf4LGalOMbN_tIFOmZzl4PmxfNkANOf-sE4r_Pp9u5zI7tbzQ/viewform) - this lets us easily contact you if we have any questions, and also allows us to send you a swag bag. Notes:

  - You will need to submit a W-9 (for US based participants) or W-8BEN (for non-US based participants)
  - Please mark “N/A” for the question “What is your federal tax classification” if you are a non-US based
  - For banking information, please put "N/A" in the field for ABA Routing Number if you don't have one. If your bank has a specific BIC/Swift Code then this should be entered in the Swift Code field.

Moreover, submissions must meet the criteria specified in “Open Projects” section below. If you have any questions about eligibility, sign in to https://community.mattermost.com, join the Contributors team and direct message @jason.blais, or email jason[at]mattermost.com with the subject “Mattermost Plugin Bounty Program”.

Paid staff or hiring candidates on a paid audition are not eligible to participate in this bounty program.

### Rules

Multiple submissions are considered on a first-come first-served basis. If the first submission meets the bounty criteria, the first submission receives the bounty.

If multiple people are interested in working on the same integration, we encourage people to work together. The bounty is allocated equally to all contributors. However, Mattermost reserves the right to split the bounty unequally, for instance, when one of the contributors completed the majority of the work.

At all times, Mattermost reserves the right to decide if a submission receives a bounty, but we aim to set clear expectations and strive for transparency and fairness throughout the process.

To submit your entry for a bounty

1. Publish it in a GitHub repository licensed under Apache 2.0 or MIT
2. Share the link via

  - direct message to @jason.blais in https://community.mattermost.com, or
  - email to jason[at]mattermost.com with the subject “Mattermost Plugin Bounty Program”

Mattermost may ask you to transfer the repository under the https://github.com/mattermost organization for long-term maintenance. If so, we’ll take steps to ensure you are credited for your work and recognized as the original creator. For an example project transferred to Mattermost, see https://github.com/mattermost/desktop.

If selected, you agree to abide by all state and local taxes of your country/region and Mattermost is not responsible for assessing such matters for you. Moreover, if you are a prize winner based in the US, we are required by the IRS to issue a 1099 form for money or prizes earned greater than $600 in any given calendar year.

### Open Projects

Submissions accepted September 1 - October 31, 2020.

#### CircleCI

Bounty: $2,000
Repository name: mattermost-plugin-circleci
Project that can be used as a starting point: https://github.com/chetanyakan/mattermost-plugin-circleci 

Requirements:
1. Uses the Mattermost plugin framework
  - Plugin documentation: https://developers.mattermost.com/extend/plugins 
  - Sample plugin: https://github.com/mattermost/mattermost-plugin-sample 
2. Meets the functionality and quality of the existing Jenkins plugin https://github.com/mattermost/mattermost-plugin-jenkins. This includes
  - Webhook notifications about successful and failed CircleCI builds
  - Slash commands to:
      - Trigger jobs with and without parameters
      - Get logs from a job in a file attachment, not as a message (this is because the logs can be huge, so it’s easier to preview a file attachment)
      - Get artifacts
      - Get test results
      - Configure/create/delete jobs
3. Meets the requirements for adding a community plugin to the marketplace https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/#requirements-for-adding-a-community-plugin-to-the-marketplace

If a specific requirement cannot be met, let us know.

#### Nagios

See https://github.com/mattermost/mattermost-server/issues/15354 for details.

#### Splunk

See https://github.com/mattermost/mattermost-server/issues/15353 for details.

#### Bitbucket

See https://github.com/mattermost/mattermost-server/issues/15351 for details.

**Comment by jasonblais** [comment]
If you're interested in the CircleCi plugin bounty, come join our Mattermost channel at https://community.mattermost.com/core/channels/plugin-circleci

@nathanaelhoun is now actively working on it, and collaborators are welcome!

**Comment by harshilsharma63** [comment]
@jasonblais can you clarify what is expected in regards to "Telemetry with basic usage statistics"?

**Comment by jasonblais** [comment]
@harshilsharma63 I removed the 'telemetry' requirement, no need to worry about it for this bounty :)

**Comment by jasonblais** [comment]
@harshilsharma63 @chetanyakan @pradeepmurugesan @darklord19 @nathanaelhoun

Given some of the above commands are not supported by CircleCI API, the requirements have been updated. They were previously shared in CircleCI channel (https://community.mattermost.com/core/channels/plugin-circleci), but to ensure everyone is clear on the updated requirements, please see below for the updates.

If any questions, let me know.

Requirements:
1. Uses the Mattermost plugin framework
  - Plugin documentation: https://developers.mattermost.com/extend/plugins 
  - Sample plugin: https://github.com/mattermost/mattermost-plugin-sample 
2. Meets the following functionality:
  - Webhook notifications about successful and failed CircleCI builds
  - Slash commands to:
      - Trigger jobs (without parameters)
      - At least four slash commands with the following conditions:
           - Each command has a valid use case for a developer or DevOps practitioner
           - Uses at least 3 of the stable v2 APIs (stable APIs are for insights, pipeline, workflow and project). See https://circleci.com/docs/api/v2 for more
3. Meets the requirements for adding a community plugin to the marketplace https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/#requirements-for-adding-a-community-plugin-to-the-marketplace

**Comment by jasonblais** [comment]
There were also some questions about what happens if two teams submit a different plugin:

1. We'll evaluate submissions on a first-come first-serve basis - if the first submission meets the required criteria, they win the bounty
2. We'll evaluate a project in the state that it was submitted at.
 - Example: If a project is submitted on Oct 4, features added after Oct 4 won't be considered (unless you explicitly re-submit the project). Instead we'll either build the plugin from a commit made on or before Oct 4, or download the relevant release binary. This is to ensure fairness across team submissions.
3. If a team submits a project early, other teams can continue to submit theirs until Oct 31st deadline. 
4. Updates to README.md, CONTRIBUTING.md and other documentation that does not ship with the plugin binary are fine even after the deadline. However, the documentation at the time of submission must [meet the requirements for adding a community plugin to the marketplace](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/#requirements-for-adding-a-community-plugin-to-the-marketplace).

Hope this helps with clarification - otherwise please feel free to ask more questions :)

**Comment by jasonblais** [comment]
The plugin submission period has now ended.
