### ISSUE TITLE
Error when joining a channel twice consecutively

### ISSUE THREAD

**Issue by dalcde** [mattermost/mattermost-server#15366]
#### Summary

If one attempts to join a channel twice in rapid succession (in particular, making the second call before the first one terminates), mattermost gives an error.

#### Steps to reproduce
Run the following command to join a channel (twice)
```
$ curl -X POST -H 'Authorization: Bearer accesstoken' -d '{"user_id": "userid"}' 'http://mattermost.host/api/v4/channels/channelid/members' & \
  curl -X POST -H 'Authorization: Bearer accesstoken' -d '{"user_id": "userid"}' 'http://mattermost.host/api/v4/channels/channelid/members'
```
The console output is
```
{"id":"api.channel.add_user.to.channel.failed.app_error","message":"Failed to add user to channel.","detailed_error":"","request_id":"wfxz6wk74iggbxb1zgagw1rsde","status_code":500}[1]  + done       curl -X POST -H 'Authorization: Bearer accesstoken' -d
{"channel_id":"channelid","user_id":"userid","roles":"channel_user","last_viewed_at":0,"msg_count":0,"mention_count":0,"notify_props":{"desktop":"default","email":"default","ignore_channel_mentions":"default","mark_unread":"all","push":"default"},"last_update_at":1598772443398,"scheme_guest":false,"scheme_user":true,"scheme_admin":false,"explicit_roles":""}%
```
The logs at the server are
```
{"level":"error","ts":1598772443.4120314,"caller":"app/channel.go:1263","msg":"Failed to add member","user_id":"userid","channel_id":"channelid","error":"CreateChannel: A channel member with that ID already exists., ChannelMembersexists  pq: duplicate key value violates unique constraint \"channelmembers_pkey\""}
{"level":"error","ts":1598772443.4123588,"caller":"mlog/log.go:190","msg":"Failed to add user to channel.","path":"/api/v4/channels/73uy6kj1jb8wdqrf3ti6zies6r/members","request_id":"wfxz6wk74iggbxb1zgagw1rsde","ip_addr":"172.24.0.1","user_id":"userid","method":"POST","err_where":"AddUserToChannel","http_code":500,"err_details":""}
```
#### Expected behavior
Both calls are successes, which is the case if the `&` is replaced by a `&&`.

**Comment by dalcde** [comment]
Another variant discovered with errors
```
{"level":"error","ts":1598844161.277252,"caller":"mlog/log.go:190","msg":"Failed to record channel member history.","path":"/api/v4/channels/channelid/members","request_id":"mczhiwgxn7y4mko5xq7mc4uusy","ip_addr":"172.18.0.1","user_id":"userid","method":"POST","err_where":"AddUserToChannel","http_code":500,"err_details":"LogJoinEvent userId=userid channelId=channelid joinTime=1598844161274: pq: duplicate key value violates unique constraint \"channelmemberhistory_pkey\""}
```
and
```
{"id":"app.channel_member_history.log_join_event.internal_error","message":"Failed to record channel member history.","detailed_error":"","request_id":"mczhiwgxn7y4mko5xq7mc4uusy","status_code":500}
```

**Comment by jasonblais** [comment]
@dalcde Thanks! Can you help share which Mattermost server version you're on? (You can find this from the main menu in the top left corner of Mattermost window, then selecting "About Mattermost")

@saturninoabril would you be open to trying to see if you can reproduce this issue?

**Comment by dalcde** [comment]
This is tested with Mattermost 5.26.0

**Comment by saturninoabril** [comment]
Sure @jasonblais.

I tried and got the same error logs. Then, looking at the channel, I can see that the user is actually added.

I believe the error is expected.  Using `&`, both requests got into the store layer and were both trying to save into the DB. The first one is successfully saved and eventually the second one threw an error (which is expected). Using `&&`, the first request saved directly into the DB. On return, the second request will try to query if user is a channel member. If found, then it returns successfully too.

**Comment by dalcde** [comment]
My main issue is that the the *client* receives an error, when it should
have been a success. I would expect an error to indicate the user is not
in the channel instead.

**Comment by saturninoabril** [comment]
No, with `&` it's actually an error on the other request. I believe it should be handled properly by the client.
