### ISSUE TITLE
Mattermost opensource HA setup issue

### ISSUE THREAD

**Issue by vasanth3855** [mattermost/mattermost-server#15369]
Hi,

Issue : "Invalid State" on mattermost page
Setup : 

1. Mattermost-5.22 and mattermost-LDAP-2.0 setup on 2 servers with load balancer.
2. Linux
3. Apache2
4. PHP7.3.21

When I try to login with Mattermost-LDAP, it alows me to login first time after clearing the cache, then I get "Invalid State" error. But when I click on "Back to Mattermost" it redirects me to mattermost channels page.
![image](https://user-images.githubusercontent.com/64240554/91682446-3247d400-eb84-11ea-9adc-6495e112d9fc.png)

Is there any specific configuration for HA setup?, please help me to resolve this issue.

Thanks,
Vasanth

**Comment by jasonblais** [comment]
Hi @vasanth3855, can you help share more about "mattermost-LDAP-2.0"? Are you using the officially supported AD/LDAP support with Mattermost? https://docs.mattermost.com/deployment/sso-ldap.html

**Comment by vasanth3855** [comment]
Hi @jasonblais, 

I'm using the Mattermost-LDAP (https://github.com/Crivaledaz/Mattermost-LDAP)
I'm using the opensource one.

Thanks,
Vasanth

**Comment by jasonblais** [comment]
Hi @vasanth3855, thank you for confirming. We don't support the LDAP module you referenced as it's community-managed, so I would encourage you to open an issue in their repo.

You also mentioned HA setup - we have documentation for it available at https://docs.mattermost.com/deployment/cluster.html, and we'd be happy to help you out if you have any questions about its setup.

**Comment by vasanth3855** [comment]
Hi @jasonblais, thanks for the update.

Issue has been fixed just by delaying the logout request.
By setting the sleep(2) before killing the session in Mattermost Ldap.

Thanks,
Vasanth
