### ISSUE TITLE
Sort last chats

### ISSUE THREAD

**Issue by SamuelGabriel** [mattermost/mattermost-server#15362]
#### Summary
Currently the chat section (direct messages) is not sorted by who I had last conversation with, but by alphabet. Most messengers (Slack, WhatsApp, Facebook) use a sorting based on last activity. This is very useful 

#### Steps to reproduce
My version is 4.5.2

#### Expected behavior
Direct messages in order of last activity. Maybe even giving a badge to unanswered threads, s.t. it is even easier to come back to unanswered direct chats.

#### Observed behavior (that appears unintentional) 
<img width="208" alt="Screenshot 2020-08-28 at 10 19 58" src="https://user-images.githubusercontent.com/9828297/91538365-07f1de80-e918-11ea-89ad-a12594632ea3.png">

#### Possible fixes
Sort and/or add some icon to remember of unanswered messages.

**Comment by amyblais** [comment]
Channels can be sorted by recency when this setting is enabled: https://docs.mattermost.com/administration/config-settings.html#sidebar-organization-experimental. However, it will apply to all channels.

You can also upvote this feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/40489678-private-channels-and-messages-to-be-sorted-by-the
