### ISSUE TITLE
Message loss may occur when the message is sent quickly enough to comment or the network is not good

### ISSUE THREAD

**Issue by jack9603301** [mattermost/mattermost-server#15377]
# Summary

Message loss may occur when the message is sent quickly enough to comment or the network is not good

# Steps to reproduce

The A side sends data at a certain frequency, and the B side may lose packets when the speed is too fast or the network is not ideal

# Expected behavior

Even if the network environment is not ideal or end A sends data too fast, the message should not be lost

# Observed behavior

If I send from A side

```
1
2
3
4
5
6
7
8
9
```

At the B end:

```
2
3
8
9
```

**Comment by jack9603301** [comment]
No Body?

**Comment by jasonblais** [comment]
@jack9603301 Thanks for the issue report. Can you help share more about your environment, in particular:

1. What OS and version is the Mattermost server installed? E.g.: Ubuntu 18.04
2. What Mattermost server version do you have? (You can find this by navigating to the main menu in top left corner of the Mattermost window, then choosing "About Mattermost")
3. Are you experiencing the issue with the browser webapp, if so which one?
4. Does the issue reproduce with several users?
5. Can you send a snippet of the Mattermost server logs around the time of the incident? They are typically located in `/opt/mattermost/logs`

**Comment by jack9603301** [comment]
1. I use debian10
2. 5.26.0
3. I don’t really understand what it means, but in my case, it’s not that you can’t send messages, but that the B-side must refresh to view new messages in some cases.
4. I don’t have enough subjects for full testing, but on my side, this situation has always existed
5. No meaningful information was found in the log

ps: I am using a cluster file system with the backend configured as glusterfs, and three load balancing cluster configurations running mattermost+php session synchronization+nginx reverse proxy.

**Comment by jack9603301** [comment]
1. I use debian 10
2. Mattermost version is 5.26.0, database Schema version is 5.26.0, database is mysql
3. I don’t quite understand what you mean. My situation here is not that I can’t send it out, but that the B-side must be refreshed at some point to see the results. Is this because of a problem with the push mechanism. I hope that even if the network is not ideal, it should only be pushed slowly, rather than not receiving
4. I don’t have enough subjects for full testing, but on my side, this situation has always existed
5. No meaningful clues found in the log

ps: I am using a cluster file system with the backend configured as glusterfs, and the load balancing cluster configuration of running mattermost+php session synchronization+nginx reverse proxy on the stage

**Comment by jack9603301** [comment]
I feel I have found the problem. The nginx reverse proxy communication of websocket in the cluster environment requires special methods such as message queue to be solved. Otherwise, messages received by other servers will be discarded. How to solve this problem?

**Comment by jasonblais** [comment]
@jack9603301 To start, I recommend following our install and configuration documentation for NGINX proxy : https://docs.mattermost.com/install/install-ubuntu-1804.html#installing-nginx-server

**Comment by jack9603301** [comment]
@jasonblais I follow the nginx deployment recommendations. But the difference is that my backend adopts a 3-node cluster high-availability configuration. Is there a way to solve the cross-server problem of websocket, or do I have to deploy mattermost at a single point?

**Comment by jasonblais** [comment]
@jack9603301 got it. Are you using a 3-node cluster for the Mattermost server as well? https://docs.mattermost.com/deployment/cluster.html

If not, that may be one option to explore.

**Comment by jack9603301** [comment]
@jasonblais Does the open source version support this feature?

**Comment by ahmaddanialmohd** [comment]
@jack9603301 Just chiming in on this real quick. The cluster deployment is available for E20 Enterprise offering based on the documentation shared by @jasonblais. May I know if you are currently utilizing this offering?

**Comment by jack9603301** [comment]
Currently in the open source non-enterprise E20 state, the server is now working in the active and standby state
