### ISSUE TITLE
Error when sending large response to slash command

### ISSUE THREAD

**Issue by dkmonaghan** [mattermost/mattermost-server#15384]
#### Summary
Sending a very large response to a slash command does not behave as expected

#### Steps to reproduce
Mattermost Version 5.25.2
Database Schema Version 5.25.0 (mysql)

#### Expected behavior
When sending a very large response (>16,000 characters) to a /slash command, the response should be split over multiple messages

#### Observed behavior (that appears unintentional) 
The message is not sent at all, and the user receives: "Command 'xxxx' failed to post response. Please contact your System Administrator'.

System log contains:
`{"level":"error","ts":1599064914.0699768,"caller":"app/command.go:505","msg":"error occurred in handling command response post","error":"Post.IsValid: Invalid message., id=rqaffthu1igmfbi691nr18mmfw"}`

#### Other
This doesn't appear to be an issue with the formatting of our message or anything. If we adjust our API endpoint to only return a smaller subset of data, the command works fine. If we return our full dataset, we get the above behaviour.

The API docs at: https://docs.mattermost.com/developer/slash-commands.html 

State that "if the text is longer than the allowable character limit per post, the message is split into multiple consecutive posts, each within the character limit." - however this does not seem to happen in our environment.

**Comment by dkmonaghan** [comment]
I have just upgraded to 5.26.1, which made no difference.

**Comment by amyblais** [comment]
@iomodo / @mickmister Would you know if there is a bug here?

**Comment by iomodo** [comment]
Looks like a bug, we should investigate

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-28500.
