### ISSUE TITLE
API v4 /users/{id} returning incomplete response

### ISSUE THREAD

**Issue by dkmonaghan** [mattermost/mattermost-server#15394]
#### Summary
The /users/{id} endpoint in API v4 does not return all the information the documentation suggests it should.

#### Steps to reproduce
Make an API call to /users/{id} in v5.26.1

#### Expected behavior
The response should contain lots of metadata about the user, see Response samples at: 
https://api.mattermost.com/#tag/users/paths/~1users~1username~1{username}/get

#### Observed behavior (that appears unintentional) 
A much shorter response is returned, missing attributes such as `notify_props`, `email_verified`, etc.
```
(
    [id] => ********************
    [create_at] => 1596466998285
    [update_at] => 1599179614900
    [delete_at] => 0
    [username] => ********************
    [auth_data] =>
    [auth_service] =>
    [email] => ********************
    [nickname] => Dan
    [first_name] => Dan
    [last_name] => Monaghan
    [position] => ********************
    [roles] => system_admin system_user
    [last_picture_update] => 1597141019127
    [locale] => en
    [timezone] => stdClass Object
        (
            [automaticTimezone] =>
            [manualTimezone] =>
            [useAutomaticTimezone] => true
        )

)
```

**Comment by streamer45** [comment]
Hi @dkmonaghan,

as the API endpoint documentation states, the result will be sanitized, meaning that all sensitive information will be excluded from the response.

These are the fields/attributes of the user object that get removed during sanitization:

```
password
auth_data
mfa_secret
email_verified
allow_marketing
notify_props
last_password_update
failed_attempts

email (based on permissions/configuration)
first_name (based on permissions/configuration)
last_name (based on permissions/configuration)
auth_service (based on permissions/configuration)
```

**Comment by dkmonaghan** [comment]
@streamer45 thanks for your response.

I see, okay. What we're trying to achieve is setting someone's "Out Of Office" status via the API. We've found we can do this by using the PATCH method on /users/{id} to set their notify_props, but in setting the Out Of Office status, this wipes out all their other notification settings.

We were hoping to read notify_props, inject their Out Of Office, and then re-set all of notify_props. Is there a better way to solve this problem?

Best,
Dan

**Comment by agnivade** [comment]
Hey @dkmonaghan - yes this is a quirk of the API. You'll notice that the PATCH method does return the `notify_props`. So what you could do is a so-called "empty patch", by just passing the user_id and nothing else, which won't patch anything, but return you the full user response along with `notify_props`. You could then update the notify_props accordingly by injecting the right thing, and then do a patch again.

**Comment by dkmonaghan** [comment]
> Hey @dkmonaghan - yes this is a quirk of the API. You'll notice that the PATCH method does return the `notify_props`. So what you could do is a so-called "empty patch", by just passing the user_id and nothing else, which won't patch anything, but return you the full user response along with `notify_props`. You could then update the notify_props accordingly by injecting the right thing, and then do a patch again.

Thanks for the reply. I'll give that a go, thank you!
