### ISSUE TITLE
/posts/{post_id}/thread endpoint returns wrong order

### ISSUE THREAD

**Issue by dalcde** [mattermost/mattermost-server#15395]
The order field returned by `/posts/{post_id}/thread` often has duplicate
entries and occasionally has results in the wrong order.

This was tested on 5.26.0 and happens consistently --- I've never had a correct response

**Comment by streamer45** [comment]
Hi @dalcde,

it appears that the endpoint doesn't sort the posts.
As far as duplicates were you able to get more than one? As far as I can see the only duplicate would be the post with the id that gets fetched by the request which should always in first position in the `order` list.

**Comment by dalcde** [comment]
That sounds right to me.

**Comment by amyblais** [comment]
@streamer45 Do I open a bug ticket?

**Comment by streamer45** [comment]
@agnivade could you have a look at this? Not sure if it's relevant anymore.

**Comment by agnivade** [comment]
From what I can see, there is no order imposed in the SQL query. So the results are not meant to be ordered. Most probably the client does the ordering.

I think Channels team should be able to clarify this further. /cc @ashishbhate @Willyfrog
