### ISSUE TITLE
Spell checking for Spanish is not working as expected

### ISSUE THREAD

**Issue by itil2020** [mattermost/mattermost-server#15402]
#### Summary
Spell checking for Spanish is incorrect

#### Steps to reproduce
Having selected Spanish (ES) as spelling language and writing the word "la bentana" (the window) which correctly would be "la ventana", there are no suggestions that seem correct.
we use latest MM clients on Win and Mac v4.5.3.

#### Expected behavior
It does not fail with all words, but for example "canet" , which would be "carnet". or as mentioned above "bentana" -> "ventana". 
In general, words should be suggested, which are closer (more similar) to the written word.

#### Observed behavior (that appears unintentional) 
![mm1](https://user-images.githubusercontent.com/70890253/92375303-3c784e00-f101-11ea-810b-fe1c078d960f.png)

#### Possible fixes
n/a

**Comment by Willyfrog** [comment]
Hi there! thanks for reporting.
I'm afraid that's a desktop bug, we are currently using a library (simple-spellchecker) which gets confused by the word if the typo is in the first character, but it shows the right word if the typo is in any other.

<img width="281" alt="Screen Shot 2020-09-09 at 13 07 54" src="https://user-images.githubusercontent.com/1515906/92591428-26ec5b00-f29e-11ea-8cc5-e3177d842572.png">

Anyway, in the next version it will most likely be removed in favor of electron's own mechanism. It uses google suggestions so it will definitely do a better job.

I'll close the issue, but feel free to reopen if you consider it necessary.
