### ISSUE TITLE
Impossible to produce @ symbol due to addition of conflicting hotkey

### ISSUE THREAD

**Issue by k-x-p** [mattermost/mattermost-server#15417]
#### Summary
Cannot produce @ symbol with Estonian keyboard layout due to Alt Gr being remapped as a hotkey

#### Steps to reproduce
1) Use Estonian keyboard layout
2) Press Alt Gr + 2 or Ctrl + Alt + 2 (key combination for @ symbol in Estonia keyboard layout)
* Mattermost version 4.2.1. Windows 8.1.

#### Expected behavior
Prints @ symbol to the active textbox (e.g. message on channel, private message)

#### Observed behavior (that appears unintentional) 
Changes to the second team in my teams list (on the left). Impossible to address certain people or channels.

#### Possible fixes
Change hotkey mappings to something that doesn't block one of the most important features in chat or at least allow us to remap it.

**Comment by amyblais** [comment]
@k-x-p Do you see the same issue on the latest desktop app version (v4.5)?

**Comment by k-x-p** [comment]
Got ahead of myself with being annoyed, sorry about that. 

Since the app gave me a message yesterday to refresh it to update to the latest version, i assumed it was the latest (as that was also when the issues started). When downloading the latest client (4.5.3) manually, Alt gr seems to be working.
