### ISSUE TITLE
Unarchive channel option missing for non-team and system admins

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-server#15427]
#### Summary
Unarchive channel option missing for non-team and system admins

https://mattermost.com/blog/mattermost-5-22-read-only-channels-channel-moderation-settings-in-e20/#:~:text=Unarchive%20channels%20directly%20from%20the%20Mattermost%20interface

https://docs.mattermost.com/help/getting-started/organizing-conversations.html#unarchiving-a-channel

#### Steps to reproduce
1. Archive channel
1. Open archived channel as non-team and system admin, no unarchive channel option listed

Using 5.25.3

#### Expected behavior
Per https://docs.mattermost.com/help/getting-started/organizing-conversations.html#unarchiving-a-channel anyone should be able to unarchive channel

![image](https://user-images.githubusercontent.com/1192780/92790429-9d519180-f360-11ea-8ee4-5115ab3a54bf.png)

#### Observed behavior (that appears unintentional) 
No unarchive option for non-team and system admins

![image](https://user-images.githubusercontent.com/1192780/92790359-91fe6600-f360-11ea-93b0-0fe32389a75e.png)

**Comment by bbodenmiller** [comment]
@allenlai18 any ideas here what's going on?

**Comment by amyblais** [comment]
@bbodenmiller Would you be open to sharing more details about your environment from here https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by bbodenmiller** [comment]
@amyblais 

- Mattermost 5.25.3
- Desktop app and all web browsers
- Tested from Windows 10
- RHEL 7.7
- Not running in container
- Haven't tested from mobile app

**Comment by amyblais** [comment]
Is this a public or a private channel?
Do you see the same with all channels?

**Comment by bbodenmiller** [comment]
@amyblais it's definitely happening for public channels. I don't have an archived private channel handy to test it with.

It appears to be happening with all archived channels for teams in which I'm not team admin. In teams where I am team admin unarchive option appears correctly.

**Comment by amyblais** [comment]
There is an open ticket regarding permissions for unarchiving channels where an enterprise licence is present: https://mattermost.atlassian.net/browse/MM-22664. Maybe this is related to the issue you're seeing?

**Comment by DHaussermann** [comment]
Hi @bbodenmiller just to help me pin down the behavior you're issue, can you confirm you're server has an enterprise license? If so, only System admins and Teams admins would see the option. 

The ticket linked by @amyblais is to implement permissions such that this can be set for other roles when using an Enterprise server.

**Comment by bbodenmiller** [comment]
@amyblais @DHaussermann I'm using community edition installed via GitLab Omnibus so I don't think this is the same issue...

**Comment by amyblais** [comment]
A ticket was opened to review this: https://mattermost.atlassian.net/browse/MM-28877.

**Comment by amyblais** [comment]
A note in the ticket from a PM: "Updated documentation so that it is accurate to behavior.  Closing bug ticket, added note to [MM-22664: Implement a permission setting to control Unarchive channel](https://mattermost.atlassian.net/browse/MM-22664) to check the behavior in Team Edition as part of any new changes to permissions."
