### ISSUE TITLE
Translation problem: Welcome message in "Town Square" (German)

### ISSUE THREAD

**Issue by juergensachs** [mattermost/mattermost-server#15430]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.
#### Summary
The german traslated welcome text for Channel "Town Square" is a "little bit wrong"

#### Steps to reproduce
Look in new german client on top of the default channel "Town Square"The current text is
" ...  Jeder wird automatisch ein permanentes Mitglied in diesem Kanal, wenn **_Sie_** dem Team beitreten."

#### Observed behavior (that appears unintentional) 
The current text is " ...  Jeder wird automatisch ein permanentes Mitglied in diesem Kanal, wenn **_Sie_** dem Team **_beitreten_**."

#### Expected behavior
Text better should be "... in diesem Kanal, wenn **_er_** dem Team **_beitritt_**."

#### Possible fixes
-

![grafik](https://user-images.githubusercontent.com/35423700/92887984-35a94e00-f415-11ea-91d5-a658d3c7cec6.png)

**Comment by amyblais** [comment]
@juergensachs Would you like to suggest this edit via our translation server? You can find instructions here on how you can join: https://docs.mattermost.com/developer/localization.html#initial-translation
