### ISSUE TITLE
Add end to end tests to the "userCreateCmdF" mmctl command

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#15486]
Mattermost is increasing the end to end test coverage for the [mmctl CLI tool](https://github.com/mattermost/mmctl). The goal is to create a suite of tests that check the main logic paths of each command and ensure that they work against a running server.

This Help Wanted issue covers the addition of end to end tests to the `userCreateCmdF` command, in the `commands/user.go` file. The expected way to add these tests is to create a test function in the `commands/user_e2e_test.go` file and add one `s.Run` block for each possible test case.

Thanks to the good amount of already existing unit tests that the commands have, it is not necessary to write an end to end test for every possible logic path of the command; the main focus should be in covering the happy path, the error path and the cases where the user doesn't have permissions to perform an action.

To help with the test process, there are some helpers that can be used. The `s.SetupTestHelper().InitBasic()` chain will create a set of default users, teams and channels to be used during the tests, `s.RunForAllClients` is useful when a test case should be valid for a sysadmin user, a [local mode user](https://docs.mattermost.com/administration/mmctl-cli-tool.html#local-mode) and an unprivileged user, and `s.RunForSystemAdminAndLocal` will test a block for both a sysadmin user and a local mode user. Please take a look at the example pull request to see how all these work.

Example: mattermost/mmctl#202

For instructions on how to set up the end to end tests, take a look at [the corresponding section of the mmctl README](https://github.com/mattermost/mmctl#end-to-end-tests).

If you have questions about the ticket or you need any help, feel free to post your question in [the community CLI channel](https://community.mattermost.com/core/channels/cli) or contact `miguel.delacruz` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-28671

**Comment by sirMackk** [comment]
Hi @mgdelacroix, I'm interested in working on this issue. Thanks for writing an in-depth description, I think I understand enough to get started.

**Comment by mgdelacroix** [comment]
That's great, thanks for your interest @sirMackk!! It's all yours!! :)
