### ISSUE TITLE
Migrate string-refs to functional ones: this.refs.filter

### ISSUE THREAD

**Issue by Willyfrog** [mattermost/mattermost-server#15518]
## Context:

String references are deprecated in React, and they will eventually disappear. Since [React 16.3](https://github.com/facebook/react/blob/master/CHANGELOG.md#1630-march-29-2018) there is the new api to use for reference creation `createRef` which improved the way to handle them greatly. Callbacks refs still have some valid usage, so we might make exceptions with those, please raise the issue if you feel you need to use them.

## How to migrate

Go to ./components/plugin_marketplace/marketplace_modal.js and look for usage of this.refs.filter. Once you find them:

1. Remove usage `this.refs.some-reference`
1. Add a `this.some-reference = React.createRef()`
1. Change code depending on `this.refs.some-reference` into using `this.some-reference.current`. Be aware that this might be accessed by files other than the one that defined it. Also, you might need to refactor the code to keep behaviour the same.
1. If there are [e2e tests](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) using that functionality run them to ensure it works as expected. Optionally consider adding any new tests that might ensure it functions as expected.
1. Look for any other this.refs used in the file and do the same.

## Example of migrated code

* [PR #5753](https://github.com/mattermost/mattermost-webapp/pull/5753)

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-28782

**Comment by hardikmodi1** [comment]
I can work on this

**Comment by Willyfrog** [comment]
thanks for taking the issue!

**Comment by hanzei** [comment]
This ticket is not longer valid as the migration was done in a other PR. Still, thanks for looking into this @hardikmodi1 :+1:
