### ISSUE TITLE
SqlSetting DB password encryption

### ISSUE THREAD

**Issue by vasanth3855** [mattermost/mattermost-server#15521]
Hi, is there any way to encrypt the Sql password and keep it in config.json?

**Comment by agnivade** [comment]
Hey @vasanth3855 - the securing of passwords (or secrets management in general) is typically left to the application deployer, not the application itself.

There are several options to achieve this. One is to use the [.pgpass](https://www.postgresql.org/docs/current/libpq-pgpass.html) file in Postgres or the equivalent in MySQL. Alternatively, you can use a secret management system like [vault](https://www.hashicorp.com/products/vault) or something equivalent to load all the necessary information required to start an application and then pass them using environment variables.

**Comment by axhiao** [comment]
hi @agnivade , do you know where i can find the password of mysql in development environment? I am new to this project. Thank you!

**Comment by agnivade** [comment]
If you use the docker development setup, the config.json should be auto-created for you. You can find the password in the `SqlSettings` section.

If you want to know from where it gets set, check this file https://github.com/mattermost/mattermost-server/blob/537b5a5b677b57fc982244f74a72ada26ca53284/build/docker-compose.common.yml#L8
