### ISSUE TITLE
Provide an official upgrade path from MySQL to PostgreSQL

### ISSUE THREAD

**Issue by Roy-Orbison** [mattermost/mattermost-server#15531]
#### Summary
If PostgreSQL is the preferred/superior database for Mattermost, there should be a supported upgrade path to it.

#### Possible fixes
As per related issue #4911, `pgloader` seems to be the tool of choice for migrating to PostgreSQL. It would be great if the Mattermost team could provide a [load command file][1] for it. This would enable the admin to create a new install (of the same version) so that so the schema can be known correct, then the tool need only migrate the data across.

[1]: https://pgloader.readthedocs.io/en/latest/tutorial/tutorial.html#id13

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-28890.

**Comment by amyblais** [comment]
I'll close this one as a Help Wanted Issue was opened for this (linked above ^).
