### ISSUE TITLE
Newcommers to private channels should not have access to the past logs

### ISSUE THREAD

**Issue by mquinson** [mattermost/mattermost-server#15561]
Hello,

when a new user is invited to a private channel, s.he can access all the past logs as if s.he was a member of the channel from Day 1. I see this as a sort of privacy pitfall, as you have to control your language thinking of who *may* be invited in the future. That's not exactly what I'd call a private discussion channel.

My use case is that we are using mattermost to discuss our research project that is centered around a simulation tool (called SimGrid). I can perfectly imagine how we discuss together about a concurring project and then later introduce a postdoc coming from that group. That may have really ... unfortunate outcomes.

It would be much more natural and less error prone if users could only see the logs produced during the period where they were a member of the channel. 

Of course, my proposal is not a secure protection because a channel member could always leak what is said in here. But that's already better than the current situation where everything is leaked by accident on a systematic manner.

Thanks for this great tool,

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @mquinson,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by mquinson** [comment]
Thanks for the pointer, @amyblais. I've posted this feature request as https://mattermost.uservoice.com/forums/306457-general/suggestions/41559319-newcommers-to-private-channels-should-not-have-acc

Shall I close this github issue or leave it open?

**Comment by amyblais** [comment]
Thank you! I can close this one for now,
