### ISSUE TITLE
Public document links not working in web & desktop app

### ISSUE THREAD

**Issue by NOP64** [mattermost/mattermost-server#15599]
#### Summary
Creating a public link from a document in a DM then pasting that link in the same DM (or other) fails to show document. Gives a "Team Not Found" page.

#### Steps to reproduce
1. Start a DM conversation with yourself.
2. Upload a local document.
3. Get a public link for the document.
4. Paste link into same DM conversation.
5. Click on that new link.
6. Observe error.

Tested with web browser (Mattermost Version: master.2066.8118cac, Database Schema Version: 5.28.0) and macOS desktop app.

Build Hash: 8118cac350bdae368cbc1931780230c1388f96fa
EE Build Hash: adb07acb1c44e77cd024d4843d039b311bd3165b
Webapp Build Hash: 87374f08ee4eaece82451ec20b4bb6b9e6d7a499
Build Date: Thu Sep 24 05:31:32 UTC 2020

#### Expected behavior
I expect the document to be displayed.

#### Observed behavior (that appears unintentional) 
Got a "Team Not Found" error. saying "The team you're requesting is private or does not exist. Please contact your Administrator for an invitation."

#### Possible fixes
unknown.

**Comment by amyblais** [comment]
Thanks for the report, opened a bug: https://mattermost.atlassian.net/browse/MM-29049
