### ISSUE TITLE
problem with uploading files 200Mb+ to MM

### ISSUE THREAD

**Issue by akulpeissov** [mattermost/mattermost-server#15602]
#### Summary
There is a problem with uploading files over 200Mb in MatterMost on premises instalation

#### Steps to reproduce
MatterMost Server 5.27.0 with MySQL database

#### Expected behavior
I need to upload large files to MM. I've configured Max File Size in System Console and in cofig,json to 10Gb. It's ok with files less than 200Mb. But when I try to upload files 200Mb+ MM starts uploading, reaches 100% and then says "There was a problem uploading your files." after Processing. There is enogh disk space on server and no problem with uploading files to the server with WinSCP.
![MM](https://user-images.githubusercontent.com/71869419/94239827-332a1680-ff34-11ea-9663-674beec53749.JPG)

**Comment by amyblais** [comment]
@akulpeissov Are you aware of any firewall or proxy in the network that could be affecting this? Is there anything in front of the network? If you've configured a proxy like NGINX in front of Mattermost, check your configuration setting ```client_max_body_size 50M``` (this would be found in the ```/etc/nginx/sites-available/mattermost``` file); and make the necessary changes to it. For example https://docs.mattermost.com/install/config-proxy-nginx.html. Then reboot the proxy.

If the above doesn't help, can you help share your Mattermost server logs when the issue happens again? Please also provide us with a HAR file.

**Comment by akulpeissov** [comment]
> @akulpeissov Are you aware of any firewall or proxy in the network that could be affecting this? Is there anything in front of the network? If you've configured a proxy like NGINX in front of Mattermost, check your configuration setting `client_max_body_size 50M` (this would be found in the `/etc/nginx/sites-available/mattermost` file); and make the necessary changes to it. For example https://docs.mattermost.com/install/config-proxy-nginx.html. Then reboot the proxy.
> 
> If the above doesn't help, can you help share your Mattermost server logs when the issue happens again? Please also provide us with a HAR file.

Hi @amyblais 
There is no firewall. I installed nginx after I've opened this issue. Yes I'm aware of configuration 'client_max_body_size' and I've already configured it. Nothing changed since.
Here is my logs from MatterMost server, Nginx and HAR file:
[logs.zip](https://github.com/mattermost/mattermost-server/files/5292067/logs.zip)

**Comment by streamer45** [comment]
@akulpeissov 

I removed the log files since they may contain sensitive information about your installation.
Will take a look at this issue now and let you know.

**Comment by streamer45** [comment]
From the logs it looks like the MM server is crashing. This could be an out of memory issue.
How much RAM does your instance have? Is MM running in a container?

**Comment by akulpeissov** [comment]
> From the logs it looks like the MM server is crashing. This could be an out of memory issue.
> How much RAM does your instance have? Is MM running in a container?

hi @streamer45,
Yeah, it's really because of memory issue. I've made RAM 6Gb and uploaded 500Mb file. Why is MM using RAM when proccessing uploaded files? Is it bug or something?

**Comment by streamer45** [comment]
@akulpeissov 

That depends on your definition of bug but it's definitely something that needs improving. We are currently in the process of moving away from storing uploaded files in memory. We have a [open PR](https://github.com/mattermost/mattermost-server/pull/15616) that will fix this issue.

**Comment by akulpeissov** [comment]
> @akulpeissov
> 
> That depends on your definition of bug but it's definitely something that needs improving. We are currently in the process of moving away from storing uploaded files in memory. We have a [open PR](https://github.com/mattermost/mattermost-server/pull/15616) that will fix this issue.

Thank you, @streamer45 
Appreciate your help! I hope this issue will be fixed soon 👍

**Comment by amyblais** [comment]
Closing as this was fixed in v5.30.0 release,
