### ISSUE TITLE
Migrate string-refs to functional ones: this.refs.scrollbars

### ISSUE THREAD

**Issue by Willyfrog** [mattermost/mattermost-server#15619]
## Context:

String references are deprecated in React, and they will eventually disappear. Since [React 16.3](https://github.com/facebook/react/blob/master/CHANGELOG.md#1630-march-29-2018) there is the new api to use for reference creation `createRef` which improved the way to handle them greatly. Callbacks refs still have some valid usage, so we might make exceptions with those, please raise the issue if you feel you need to use them.

## How to migrate

Go to ./components/search*results/search*results.jsx and look for usage of this.refs.scrollbars. Once you find them:

1. Remove usage `this.refs.some-reference`
1. Add a `this.some-reference = React.createRef()`
1. Change code depending on `this.refs.some-reference` into using `this.some-reference.current`. Be aware that this might be accessed by files other than the one that defined it. Also, you might need to refactor the code to keep behaviour the same.
1. If there are [e2e tests](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) using that functionality run them to ensure it works as expected. Optionally consider adding any new tests that might ensure it functions as expected.
1. Look for any other `this.refs` used in the file and repeat from the begining.

## Example of migrated code

* [PR #5753](https://github.com/mattermost/mattermost-webapp/pull/5753)

## Questions

you can ask for help messaging @guillermo.vaya or posting in the ~webapp channel in the community server

**Comment by VolatianaYuliana** [comment]
Hey @Willyfrog I would like to work on this

**Comment by Willyfrog** [comment]
sure! thanks a lot for working on this one :)
