### ISSUE TITLE
Reaction Added/Removed Plugin Hook

### ISSUE THREAD

**Issue by shieldsjared** [mattermost/mattermost-server#15624]
#### Summary
I currently have a desire to build a plugin that depends on reactions (specifically, having knowledge of when reactions are added and removed from posts).  Scanning through the documentation and source, I haven't found an efficient way to do this.

#### Possible fixes
Based on a [discussion in the community toolkit channel](https://community.mattermost.com/core/pl/iazsj6ch6t865ek5y4oornzrko), it was recommended that the best course of action would be to simply expose hooks for these events, namely `ReactionCreated` and `ReactionDeleted` (to be fired _after_ the event has occurred).  A possible design may also include _before_ events as well.

I'm happy to submit a PR to add this functionality... Hoping to gather feedback and an initial blessing to provide this contribution.  Thanks!

(As an aside, the plugin that I'd like to build is a "user-ratings" plugin. My team has a few emoji reactions that we reserve for special "kudos" or "praise" (such as the `:star:`).  Ideally the plugin would monitor posts, and credit users who receive reactions with the configured reaction types.  The user's credit/rating would appear in the user popover).

**Comment by amyblais** [comment]
@shieldsjared Based on the discussion in the channel, I believe it's fine if you open a pull request for this. 

The product team rarely looks at Github issues on this repo, so I feel that a pull request will generate further reviews / discussions from the product managers on this as needed.

**Comment by aaronrothschild** [comment]
@shieldsjared Hey - I'm a PM at Mattermost and am all for this addition.  Let me know if any questions come up.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/15765
