### ISSUE TITLE
Inefficient ID column definitions (in MySQL at least)

### ISSUE THREAD

**Issue by Roy-Orbison** [mattermost/mattermost-server#15631]
#### Summary
Multi-byte, variable length column definitions are used for columns that always contain 26 lowercase ASCII characters.

#### Steps to reproduce
View an ID column info in a new install, e.g.:
```mysql
SHOW FULL COLUMNS FROM Users LIKE 'Id';
```

#### Expected behavior
Field | Type | Collation | Null | Key | Default | Extra | Privileges | Comment
-- | -- | -- | -- | -- | -- | -- | -- | --
Id | char(26) | ascii_bin | NO | PRI | NULL |   |  select,insert,update,references

#### Observed behavior (that appears unintentional) 

Field | Type | Collation | Null | Key | Default | Extra | Privileges | Comment
-- | -- | -- | -- | -- | -- | -- | -- | --
Id | varchar(26) | utf8mb4_general_ci | NO | PRI | NULL | | select,insert,update,references

#### Possible fixes
Use a fixed width column and a restricted character set:
```mysql
ALTER TABLE `Users` MODIFY `Id` CHAR(26) COLLATE 'ascii_bin' NOT NULL;
```

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-29122.

**Comment by agnivade** [comment]
Yes, this is more efficient. But there is a significant cost to making such large-scale schema changes on production databases. Until the benefit is higher than the cost, it's hard to justify such a change. I'll keep this in mind when in future we are making a breaking change for a major version release.

**Comment by Roy-Orbison** [comment]
Is it not possible to make it the default for new installs, without changing existing ones? Perhaps that'll cause further issues.

**Comment by agnivade** [comment]
That has caused major headaches in the past because of different customers ending up with different schemas depending on when they started to use Mattermost.

**Comment by agnivade** [comment]
Hey @Roy-Orbison - I looked into this in some more details. I am unable to find any references to why using `CHAR` would be more efficient than `VARCHAR`.

In fact, in the Postgres documentation, it's explicitly mentioned:

> There is no performance difference among these three types, apart from increased storage space when using the blank-padded type, and a few extra CPU cycles to check the length when storing into a length-constrained column. While character(n) has performance advantages in some other database systems, there is no such advantage in PostgreSQL; in fact character(n) is usually the slowest of the three because of its additional storage costs. In most situations text or character varying should be used instead.

https://www.postgresql.org/docs/current/datatype-character.html

If a column has always `n` characters, for Postgres it doesn't seem to make a difference whether you store in char or varchar. Erwin comes to the same conclusion [here](https://dba.stackexchange.com/a/89433/210257) as well.

I am curious to know if you have any references that talk of any other differences.

**Comment by Roy-Orbison** [comment]
How odd that storing a fixed length would be less performant. I only knew about MySQL/MariaDB as that's what I've used in the past.

I just read this https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_char.28n.29_even_for_fixed-length_identifiers so now I wonder why it's even possible to use a `CHAR(N)` type in Postgres at all.

**Comment by agnivade** [comment]
I believe there was an implementation gap in the older versions. However, newer versions closed the gap making the `char(n)` type moot. But for compatibility reasons, they can't remove it obviously.
