### ISSUE TITLE
Improve UI for image preview modal

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#15658]
Summary:
Improve the aesthetic layout of how image & file previews look when a user clicks an attachment to a post.

**Figma Design File**:
[https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A0](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A0)

![image](https://user-images.githubusercontent.com/31866506/121244523-f5c0ab80-c86c-11eb-88db-c38e5634cee1.png)

![image](https://user-images.githubusercontent.com/31866506/121244636-18eb5b00-c86d-11eb-88bd-67f3dae5a541.png)
 
**Theming Notes**

  * For this modal we are breaking from using the theme colors for most things using full black (#00000) with various opacities.
  * This modal will stay this style regardless of the chosen theme. (similar to how tooltips are theme agnostic)
  * The file type colors are also theme agnostic (word, excel, powerpoint, pdf and the blue ones)
  * The blue “Download” buttons WILL adhere to the chosen theme. For example if you chose dark theme it would be that green/teal color, use the themed components for this.

**Common Functionality Notes**

  * Hover over the icon buttons will display the following tooltips
    * Copy public link ([prototype with animation example](https://www.figma.com/proto/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=169%3A1220&viewport=417%2C117%2C0.5&scaling=min-zoom))
    * Download file
    * Close preview
  * Hovering over the action bar buttons will display the following tooltips:
    * Zoom out
    * Zoom in
    * Zoom (the “Automatic Zoom” dropdown)
    * Fullscreen
    * Hand tool
  * Keyboard left and right arrows should trigger left and right preview navigation
  * Clicking on the modal BG will close the preview
  * Pressing the “Esc” keyboard key will close the preview
  * Max Height:
    * Total height - header height - (2 x 48px for the vertical padding)
  * Max Width:
    * Total width - (2 x 48px for the horizontal padding)

**Large Images -** [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A1)

  * Maximum width and height for any attachment being displayed should as follows:
    * Maximum height = preview height - header height - (2 x 48px)
    * Maximum width = preview width - (2 x 48px)

**Zoom Toolbar** - [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=166%3A2655)

  * When hand tool is toggled on and you hover over the image:
    * mouse icon will be: Open Hand
    * mouse icon on click will be: Closed Hand
  * When you have your mouse pressed, you can then drag the zoomed image around until its outer edges hit the view area edges
  * For images only: Holding down the spacebar will toggle the Hand Tool, and letting go of the spacebar will untoggle it. This will be ignored if the user toggles it on via the toolbar first.
  * When hovered over anything else the mouse icon will revert to: Arrow

**Zoom Functionality**
  * Try to mimick as closely as possible the zoom functionality from [this library](https://mozilla.github.io/pdf.js/web/viewer.html)
We will be using this library for PDF’s, Word, Excel and PPT.
  * As soon as the zoom level hits past a point where the object is larger then the screen realestate, requireing horizontal or vertical scroll bars, the “Hand Tool” should automatically be toggled on.
  * The Zoom out icons will be disabled when a user opens the preview modal. 
  * Once user has ‘Zoomed in’ one level the Zoom out  icon will be enabled, and the dropdown will update to display the zoom level.
  * Choosing Automatic zoom from the dropdown will reset the preview back to the default (size when first opened) size and set the Zoom out.
  * Clicking the Zoom out button should stop zooming after the preview reaches the default (size when first opened) size and set the Zoom out icons to disabled, while reseting the dropdown to “Automatic Zoom”.
  * For the number of zoom steps / items in the dropdown, please match the mozilla library mentioned above.

**Small Images -** [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A13)

  * The contents will always be centered horizontally and vertically

**Audio Files -** [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A70)

  * Once the audio loads, auto play it
  * Pressing the keyboard enter or space key should play / pause the audio.

**Video Files -** [Figma Design - Play](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A106) - [Figma Design - Pause](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=208%3A52)

  * Once the video loads, auto play it
  * Pressing the keyboard enter or space key should trigger play or pause for the video.
  * Once the video starts playing, the controls (showing large pause button with dimming overlay) fade away after 1000ms
  * Once a user moves their mouse over on the player area the video controls return
  * If a user clicks on the large pause button, the video pauses and the large button switches to a play button
  * if the users mouse is inactive for 1000ms or the mouse is not hovered over the video area the video controls will hide.

**PDF - Single Page** [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A142)

  * The PDF preview should match the default behaviors of this mozilla library that we will be leveraging: https://mozilla.github.io/pdf.js/web/viewer.html
  * The zoom level will default with the “Automatic Zoom” setting.
  * Notice the 48px for the top padding
  * Keyboard shortcuts to support
    * Up and down arrows
    * Page up and page down
    * Home and End

**PDF - Multi Page** [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=663%3A79)

  * When a multi-page PDF is open, the page sidebar will automatically toggle open.
  * The spacing between pages should be 24px, im noting this because the second page appears below the scroll line when defaulted to “Automatic Zoom”
  * Also take note of the 8px rounded corners of the document pages.

**PDF - Find in document** [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=665%3A80)

  * When the find in document toggle is clicked, the find panel slides down with the input field already selected.
  * The highlight all feature will automatically and always be set to true, we wont be showing the toggle for it. (referencing the mozilla library functionality)
  * We will also supressing / not showing or using the “Match case” or “Whole words” feature.

**Code -** [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A161)

  * I recommend we use something like the open source Monaco editor for code previews, for added click interactions and the code preview panel on the right
  * [https://microsoft.github.io/monaco-editor/](https://microsoft.github.io/monaco-editor/)

**Loading Preview** - [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A25)

  * Circular indicator is intended to be consistent with the new mobile image gallery.
  * The circular track fills with color, as the indicator moves from 0 to 360 degrees.
  * The animation speed and style should reference:
    * [https://material.io/design/components/progress-indicators.html#circular-progress-indicators](https://material.io/design/components/progress-indicators.html#circular-progress-indicators)
    * Scroll down to the “Types” subsection to see the animation.

**MS Office filetypes as PDF previews**

  * We will use the same previewer library as referenced for PDF's above, leveraging the same functionality
  * Here are the designs for the different file types:
    * [Word](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=166%3A158)
    * [Excel](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=166%3A663)
    * [Powerpoint](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=166%3A1069)

**Other known filetypes without previews**

  * The filetype will show up entered in the screen with the following info
    * Icon
    * Filename
    * “Preview is not supported for this filetype”
    * Button - “Download File”
  * Here are the designs for the following unsupported known filetypes:
    * [Unsupported Audio Files](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A56)
    * [Unknown](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=125%3A42)
    * [Patch Files](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=166%3A1881)
    * [Compressed Files](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=166%3A2287)
  * All of the icons are available as part of the Compass Icons font.

**Responsive Layouts**

  * 768 px available and above - [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=169%3A9)
    * In this example the width is 800 wide, but this design would just adjust all the way down to 768 in width.. below that it will switch to the mobile layout (see next screen)
  * 767 px available and below - [Figma Design](https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=169%3A384)
    * In this example the width is 700 wide, we would adjust the layout to match consistently with the mobile app.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-12104

**Comment by esethna** [comment]
Given this is an advanced help wanted ticket, if anyone is interested in taking on this feature please reach out to me here or at @eric.sethna on our [community ](https://community.mattermost.com) server before diving too deeply into the project.

**Comment by justintucker** [comment]
@esethna Are all mattermost issues listed under this repo? I'm not seeing anything in [webapp repo](https://github.com/mattermost/mattermost-webapp/).

**Comment by esethna** [comment]
@justintucker yes almost all the open help wanted issues are listed here in the server repository, there are different labels for code and feature area involved for each. 

Were you interested in taking on this issue?

**Comment by justintucker** [comment]
@esethna I was considering this issue or the notifications issue. I wanted to ensure I can get the local environment up and running before I do.

**Comment by esethna** [comment]
@justintucker cool, let us know if you need any help. Would be psyched for you to pick up this issue!

**Comment by esethna** [comment]
@justintucker let us know if you're taking on this ticket :)

**Comment by justintucker** [comment]
@esethna I'm going to pass on this for now.

**Comment by mrbenito** [comment]
I for one would like to see this. Our users (~6k users) share high resolution images that require they zoom to see. Instead the default functionality downloads the image to their machine where they have to open it in a local image viewer, THEN zoom in.. Typically these images are single use and temporal so they end up junking up the user's computer. FWIW we moved from Rocket.chat which supported this feature by default. Looking to get click to open then click to zoom back.

**Comment by esethna** [comment]
@mrbenito can you share an example of an image for testing purposes?

**Comment by mrbenito** [comment]
> @mrbenito can you share an example of an image for testing purposes?

Sure. Here's a recording to also show context. https://www.loom.com/share/46f952f650df4be4b7fff6bc872ff0b1
Here's the image seen in the recording.
![Image Pasted at 2021-1-13 14-34](https://user-images.githubusercontent.com/5737267/104509962-74643600-55b8-11eb-986f-5a0de767c9b2.png)

**Comment by esethna** [comment]
Got it, super helpful @mrbenito! This improvement covers exactly this to give users zoom controls and expand the preview modal functionality. We'll be working on this soon if it's not picked up by a contributor before that

**Comment by AshishDhama** [comment]
@esethna would Like to take it forward let me know when can we discuss this.

**Comment by esethna** [comment]
Completed internally

**Comment by freem-trg** [comment]
Hi Eric! @esethna 
We are also interested in the image zoom feature. But it feels like it was never deployed into production. 
Are there any plans for it?

**Comment by esethna** [comment]
@freem-trg, correct, the modal enhancement was merged to production but the zooming was never completed. We'd be open to accepting a contribution for adding that functionality based on the designs and functional notes in the description of this ticket ^: https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?type=design&node-id=166-2655&mode=design&t=8djT9Mvej1htzVWr-4

**Comment by TheStu** [comment]
I created [this branch](https://github.com/TheStu/mattermost/commit/b454d96c786df8ab2a7ae8b69227f461896559ea) to address image zooming, as it's a feature my team is looking for. I didn't realize there was already a design spec for the feature so what I've done is a bit different than what is outlined above. I'm happy to submit a PR for my branch as is, or could change the design to fit the spec above.

Note that I just used an existing image zoom library for that functionality, I'm not sure how the Mattermost team feels about adding a dependency for that.

**Comment by esethna** [comment]
@TheStu thanks for the interest! I messaged you in Mattermost. Please go ahead and submit the PR and that'll get the conversation started with the right folks

**Comment by esethna** [comment]
> Note that I just used an existing image zoom library for that functionality, I'm not sure how the Mattermost team feels about adding a dependency for that.

@hmhealey looping you in on the question about adding the dependency for image zooming in the preview modal. Please loop in others as/if needed. ^

**Comment by hmhealey** [comment]
That looks like it'd work great. It's MIT-licensed and looks well maintained, and those are the two most important things for us apart from it just working correctly
