### ISSUE TITLE
Store mmctl's configuration files following the XDG spec

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#15679]
We want to update the location of the mmctl's configuration file. For this new location:

* We should follow the XDG Base Directory Specification for configuration and other files. For the case of `mmctl`, this means moving the configuration to the `$XDG_CONFIG_HOME` directory.
* We should provide the user with a global flag and environment variable to point to a specific location for the configuration file in case they want to use a custom path.
* After the change, mmctl should still support using the old location, so it should do a priority search of: flag/environment variable, then XDG location and finally the old `$HOME/.mmctl`

To start looking into this ticket, check the `getConfigFilePath` function in the `commands/auth_utils.go` file.

If you have questions about the ticket or you need any help, feel free to post your question in [the community CLI channel](https://community.mattermost.com/core/channels/cli) or contact `miguel.delacruz` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-28433

**Comment by muety** [comment]
I'd love to give it try here! :slightly_smiling_face:

**Comment by mgdelacroix** [comment]
Thanks @muety, all yours!

**Comment by muety** [comment]
Got it, thanks! That makes things a lot clearer now.
