### ISSUE TITLE
All non-submit buttons in the system console should be set to type='button'

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-server#15682]
#### Summary

Since buttons inside a form tag are treated as submit buttons by default, any button in the system console not labeled as `type='button'` is treated is a submit button. Pressing enter (even when the button does not have focus) results in a click of the button. This causes a plugin's generated secret to unintentionally regenerate for example. Each non-submit button needs to have `type='button'` to defend against this.

#### Steps to reproduce

Navigate to the system console Web Server page, i.e. http://localhost:8065/admin_console/environment/web_server . Click into the `Listen Address` field. Press enter and observe the behavior.

#### Expected behavior

Nothing should happen

#### Observed behavior (that appears unintentional) 

`Test Live URL` button is triggered

#### Possible fixes

Any non-submit button in the [mattermost-webapp/tree/master/components/admin_console](https://github.com/mattermost/mattermost-webapp/tree/master/components/admin_console) folder needs to have the `type='button'` attribute so it is not treated as a submit button. See https://github.com/mattermost/mattermost-webapp/pull/6595 for an example.

**Comment by outofgamut** [comment]
I'll take this one!

**Comment by mickmister** [comment]
> Can I take this one?

Absolutely! Thanks @outofgamut!!

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/6600
