### ISSUE TITLE
Allow mmctl list users command to filter by team

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#15686]
As part of this ticket, we should implement a new flag for the `mmctl user list` command. This new `--team` flag should filter the listed users by a team. A proposed solution would be to use this endpoint:

https://api.mattermost.com/#tag/teams/paths/~1users~1{user_id}~1teams~1members/get

to get all the members of a team, and then fetch their user information and display it.

Feature request coming from https://github.com/mattermost/mmctl/issues/195

If you have questions about the ticket or you need any help, feel free to post your question in [the community CLI channel](https://community.mattermost.com/core/channels/cli) or contact `miguel.delacruz` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-28194

**Comment by anthonydurot** [comment]
I would like to work on this, but I wonder, shouln't the issue be in mattermost/mmctl repository ?

**Comment by mgdelacroix** [comment]
Hi @anthonydurot, I've assigned you the issue, thanks for working on this!

We decided to centralize all the Mattermost related issues in a single repository so it's easier to filter and find things to work on. You can filter by `area/CLI` to find all the CLI tickets or by `difficulty/1:Easy` to find all the easy ones independently of their repository, for example :slightly_smiling_face:

**Comment by anthonydurot** [comment]
Hi @mgdelacroix I'm truly sorry but I'm busy right now and I couldn't investigate this issue. I unassigned myself so that someone else have the opportunity to work on this for Hacktoberfest :)

**Comment by mgdelacroix** [comment]
No problem @anthonydurot and thanks for the heads up!

**Comment by darkLord19** [comment]
@mgdelacroix Hi Miguel, I'd like to work on this. I had one simple doubt, can you please clarify "This new --team flag should filter the listed users by a team" this by giving some example?

**Comment by mgdelacroix** [comment]
Hi @darkLord19! Thanks for taking a look at the issue :slightly_smiling_face: 

> Does this mean that if --team < team name > flag is given then we print only users who are part of that team?

Exactly, the idea is to be able to list only the users that are members of a given team.
