### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T669 Custom slash command in DM and GM"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15697]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T669 Custom slash command in DM and GM</h1>
<div>
<div>
<h3>Steps </h3>Custom slash command in DM and GM<br>–––––––––––––––––––––––––<ol><li>Run custom slash command in DM and GM</li></ol><h3>Expected</h3><ul><li>Works as expected</li><li>Bot returns block of text similar to the following:<br><br></li></ul><em>{"text":"channel_id=usmwa4yh4pbrpkbr8yhqbb1dga\nchannel_name=3ic78ixonb8k7buno7nijig5xc__mqb95owbm3rqugqd79bmbkfg5r\ncommand=/test-message\nresponse_url=https://postgres.test.mattermost.com/hooks/commands/t3651ud5nbr6bpcwwmhkhsuzca\nteam_domain=abcs\nteam_id=w8w9bwh3gbne7x6g5we9fygjph\ntext=\ntoken=pzxcxnrmeffhfnwtxkpq1r6naa\ntrigger_id=YnM1NGV1ZGljYmZpdG5zM3VleDE3amM1N3k6M2ljNzhpeG9uYjhrN2J1bm83bmlqaWc1eGM6MTU3ODY4MDQ4NTI4NzpNRVVDSVFETEVaa2lpV3VZaFpJTzRteXR4QzlpaHBrRUl1UEtHR2xnNEFZL0E1SWNOUUlnVWlNZDBENUgvUjRkVkxpWnd3dDR0YUhvZkUwa2FCSE9sVXdITjVmZ1BNUT0=\nuser_id=3ic78ixonb8k7buno7nijig5xc\nuser_name=steve", "response_type": "in_channel"}<br></em><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/integrations``
**Test code arrangement:**
```
describe('Integrations', () => {
    it('MM-T669 Custom slash command in DM and GM', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by Mishrasubha** [comment]
Can I work on this?

**Comment by saturninoabril** [comment]
Welcome @Mishrasubha and sure!

**Comment by saturninoabril** [comment]
Opening help-wanted issue for grab again. Feel free to pick it up again if you'd like @Mishrasubha.

**Comment by yasserfaraazkhan** [comment]
@saturninoabril I'll be taking this up,

I'll be adding some more e2e steps of creating custom slash commands for GM and DM, and then verify if the commands are working.

**Comment by nidak7** [comment]
@amyblais I guess, this can be closed

**Comment by yasserfaraazkhan** [comment]
@amyblais I guess, this can be closed
