### ISSUE TITLE
Prevent using --format json in the mmctl logs subcommand

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#15693]
The `--format json` instructs `mmctl` to format a command’s output as `json`, but it the case of the mmctl logs command it can be confusing as the server endpoint is not returning the logs in that format and `mmctl` can’t do a meaningful conversion. As part of this ticket we should state in the command's documentation that the `--format` flag cannot be used and print an error if it is.

If you have questions about the ticket or you need any help, feel free to post your question in [the community CLI channel](https://community.mattermost.com/core/channels/cli) or contact `miguel.delacruz` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-29053

**Comment by attiss** [comment]
Hi there @mgdelacroix!
I'm interested in working on this issue, can I take it? :)
