### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T560 Browser tab and team sidebar unreads and mentions - Mention in different team"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15703]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T560 Browser tab and team sidebar unreads and mentions - Mention in different team</h1>
<div>
<div>
<h3>Steps  #1</h3>Browser tab and team sidebar unreads and mentions - Mention in different team<br>–––––––––––––––––––––––––<ol><li>With an account on two teams, view team A, make sure no unreads or mentions</li><li> Have another user view team B</li><li>Have the other user post an at-mention for you in any channel on on team B</li></ol><h3>Expected</h3><ul><li>Browser tab displays: (1) * channel - [team name] Mattermost</li><li>Team sidebar: Small dot left of team B icon in team sidebar, and a mention badge in top right corner of the badge with number "1"</li><li>Favicon should stay blue (not turn red) when there are mentions indicated</li></ul><hr><h3>Steps  #2</h3>Team sidebar icon - Badge with mention count increments when added to channel<br>–––––––––––––––––––––––––<ol><li>With an account on two teams(A&amp;B), view and remain on team A</li><li>Have another user view team B</li><li>Have the other user add you to channel on team B</li></ol><h3>Expected</h3><ul><li>Browser tab - Mention badge increases e.g. (2)*</li><li>Team sidebar - Mention badge in top right corner of the team B icon with number "1" or if the existing badge count is present it should incremented to reflect test user being added to new channel on this team</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/notifications``
**Test code arrangement:**
```
describe('Notifications', () => {
    it('MM-T560 Browser tab and team sidebar unreads and mentions - Mention in different team', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by seongwon-kang** [comment]
I'll work on this.

**Comment by saturninoabril** [comment]
Sure and thanks @seongwon-kang!

**Comment by seongwon-kang** [comment]
@saturninoabril is there any method for get favicon? I tried `link[rel=icon]`, but href of favicon image changes randomly.

**Comment by saturninoabril** [comment]
One option is to save base favicon image at `/fixtures` folder and compare its image content to the one generated from href. Image content comparison can be [like in this lines](https://github.com/catalintomai/mattermost-webapp/blob/master/e2e/cypress/integration/emoji/custom_emoji_spec.js#L188-L194).

Different topic: It's not mention in this issue but since there are two steps for this test case, please put each step in a separate `it` blocks, like:
```
it('MM-T560_1 Browser tab and team sidebar unreads and mentions - Mention in different team', () => {...});
it('MM-T560_2 Team sidebar icon - Badge with mention count increments when added to channel', () => {...});

**Comment by seongwon-kang** [comment]
Thanks @saturninoabril! I'll try it later.
