### ISSUE TITLE
Write Mobile App E2E test with Detox: "MM-T3207 Leave private channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15707]
See our [documentation for Mobile app end-to-end testing with Detox](https://developers.mattermost.com/contribute/mobile/e2e/) for reference.

<article>
<h1>MM-T3207 Leave private channel</h1>
<div>
<div>
<h3>Steps </h3>Leave private channel<br>————————————————————————————<ol><li>On a private channel, tap channel name</li><li> Tap Leave Channel</li><li>Tap Yes on confirmation modal</li></ol><h3>Expected</h3><ul><li>Redirects to Town Square</li><li>Channel no longer listed in channel drawer</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/detox/e2e/test/smoke_tests``
**Test code arrangement:**
```
describe('Smoke Tests', () => {
    it('MM-T3207 Leave private channel', () => {
        // code
    });
});
```

Notes:
1. Mobile App E2E requires Mattermost server instance.
- See our [documentation](https://developers.mattermost.com/contribute/server/developer-setup/) on how to run a local server instance.
- If server is running and accessible other than the default `http://localhost:8065`, you may pass `SITE_URL` environment variable.
2. The default sysadmin credential is username:"sysadmin" and password:"Sys@dmin-sample1"
- It's automatically generated by `make test-data` at `mattermost-server` folder
- If using credential other than the said default, you may pass `ADMIN_USERNAME` and `ADMIN_PASSWORD` environment variables.

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephbaylon** [comment]
Detox PR: https://github.com/mattermost/mattermost-mobile/pull/5352
