### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T558 Browser tab unreads -  Tab in background, viewing same team, same channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15706]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T558 Browser tab unreads -  Tab in background, viewing same team, same channel</h1>
<div>
<div>
<h3>Steps </h3>Browser tab unreads -  Tab in background, viewing same team, same channel<br />--------------------<br />1. User A: On teams A and B, ensure no unreads. Open team A and view Town Square<br />2. User A: Switch to view a different browser tab<br />3. User B: On team A<br />4. User B: Post a message in Town Square (that User A has open in a background tab)<h3>Expected</h3>User A sees browser tab title: <br /><br />* Town Square - [team name] Mattermost<br /><br />(Desktop app hover mouse over icon in taskbar to see it)<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/notifications``
**Test code arrangement:**
```
describe('Notifications', () => {
    it('MM-T558 Browser tab unreads -  Tab in background, viewing same team, same channel', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by shreyaa-sharmaa** [comment]
Hey, I would like to work on it. Can I get assigned to this?

**Comment by saturninoabril** [comment]
Sure and thanks @shreyaa-sharmaa!

**Comment by saturninoabril** [comment]
Sure @joremysh! Thanks!

**Comment by poflankov** [comment]
Is it doable at all with Cypress?
Cypress does not seem to support browser tabs: https://docs.cypress.io/guides/references/trade-offs#Permanent-trade-offs

**Comment by saturninoabril** [comment]
Thanks for checking @poflankov! You're right as this is not possible with Cypress. Closing now.

**Comment by poflankov** [comment]
I think this ticket has the same problem:
https://github.com/mattermost/mattermost-server/issues/15702
