### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T561 Browser tab and team sidebar - direct messages don't add indicator on team icon in team sidebar (but do in browser tab)"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15700]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T561 Browser tab and team sidebar - direct messages don't add indicator on team icon in team sidebar (but do in browser tab)</h1>
<div>
<div>
<h3>Steps </h3>Browser tab and team sidebar - direct messages don't add indicator on team icon in team sidebar (but do in browser tab)<br />--------------------<br />1. User A: Join teams A and B. Open team A<br />2. User B: Join team B<br />3. User B: Post a direct message to user A<h3>Expected</h3>User A: <br />- Browser tab: (1) * Town Square - [team name] Mattermost<br />- Team sidebar: No unread / mention indicator in team sidebar on either team<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/notifications``
**Test code arrangement:**
```
describe('Notifications', () => {
    it('MM-T561 Browser tab and team sidebar - direct messages don't add indicator on team icon in team sidebar (but do in browser tab)', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by seongwon-kang** [comment]
I'm working on this.
