### ISSUE TITLE
Write Mobile App E2E test with Detox: "MM-T3206 Edit private channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15709]
See our [documentation for Mobile app end-to-end testing with Detox](https://developers.mattermost.com/contribute/mobile/e2e/) for reference.

<article>
<h1>MM-T3206 Edit private channel</h1>
<div>
<div>
<h3>Steps </h3>Edit private channel<br>————————————————————————————<ol><li>On a private channel where policy allows you to edit channel header etc., tap a channel name</li><li> Tap `Edit Channel`, verify Save button is dimmed until changes are made</li><li> Add text to the channel name</li><li> Type text in Purpose field</li><li> Type text in Header field and tap Return to get new line</li><li> Tap a second line of text</li><li>Tap Save</li></ol><h3>Expected</h3><ul><li>Edit modal closes, channel info is displayed</li><li>The changes you made are displayed</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/detox/e2e/test/smoke_tests``
**Test code arrangement:**
```
describe('Smoke Tests', () => {
    it('MM-T3206 Edit private channel', () => {
        // code
    });
});
```

Notes:
1. Mobile App E2E requires Mattermost server instance.
- See our [documentation](https://developers.mattermost.com/contribute/server/developer-setup/) on how to run a local server instance.
- If server is running and accessible other than the default `http://localhost:8065`, you may pass `SITE_URL` environment variable.
2. The default sysadmin credential is username:"sysadmin" and password:"Sys@dmin-sample1"
- It's automatically generated by `make test-data` at `mattermost-server` folder
- If using credential other than the said default, you may pass `ADMIN_USERNAME` and `ADMIN_PASSWORD` environment variables.

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephbaylon** [comment]
Detox PR: https://github.com/mattermost/mattermost-mobile/pull/5352
