### ISSUE TITLE
Write Mobile App E2E test with Detox: "MM-T3204 Add user to private channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15713]
See our [documentation for Mobile app end-to-end testing with Detox](https://developers.mattermost.com/contribute/mobile/e2e/) for reference.

<article>
<h1>MM-T3204 Add user to private channel</h1>
<div>
<div>
<h3>Steps  #1</h3>Add user to private channel<br>————————————————————————————<ol><li>Tap the name of a private channel where you have permission to add members</li><li>&nbsp;Tap `Add Members`</li></ol><h3>Expected</h3><ul><li>A list of users on the server should be displayed</li></ul><br><br><hr><h3>Steps  #2</h3><ol><li>Type the beginning of a user's name in the search box</li></ol><h3>Expected</h3><ul><li>Your keyboard should pop up so you can type in the name of a user.</li><li>The list should filter as you type in the name and display all users matching your input</li></ul><hr><h3>Steps  #3</h3><ol><li>Select user and tap `Add`</li></ol><h3>Expected</h3><ul><li>The circle should show blue with a white tick (selected)</li></ul><hr><h3>Steps  #4</h3><ol><li>Tap Add</li></ol><h3>Expected</h3><ul><li>The user should be added to the channel, total number of members next to "manage members" menu option should increase by the number of users added to the channel and a system message should display in the channel showing which members were added to the channel.</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/detox/e2e/test/smoke_tests``
**Test code arrangement:**
```
describe('Smoke Tests', () => {
    it('MM-T3204 Add user to private channel', () => {
        // code
    });
});
```

Notes:
1. Mobile App E2E requires Mattermost server instance.
- See our [documentation](https://developers.mattermost.com/contribute/server/developer-setup/) on how to run a local server instance.
- If server is running and accessible other than the default `http://localhost:8065`, you may pass `SITE_URL` environment variable.
2. The default sysadmin credential is username:"sysadmin" and password:"Sys@dmin-sample1"
- It's automatically generated by `make test-data` at `mattermost-server` folder
- If using credential other than the said default, you may pass `ADMIN_USERNAME` and `ADMIN_PASSWORD` environment variables.

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephbaylon** [comment]
Detox PR: https://github.com/mattermost/mattermost-mobile/pull/5352
