### ISSUE TITLE
Write Mobile App E2E test with Detox: "MM-T3202 Leave public channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15714]
See our [documentation for Mobile app end-to-end testing with Detox](https://developers.mattermost.com/contribute/mobile/e2e/) for reference.

<article>
<h1>MM-T3202 Leave public channel</h1>
<div>
<div>
<h3>Steps  #1</h3>Leave public channel<br>————————————————————————————<ol><li>Tap on "leave channel"</li></ol><h3>Expected</h3><ul><li>A message is displayed on screen asking whether or not you want to leave the channel</li></ul><hr><h3>Steps  #2</h3><ol><li>Tap on "yes"</li></ol><h3>Expected</h3><ul><li>You should be removed from the channel and be redirected to Town Square</li><li>If you had tapped on "no", the message should just close and your view remains in channel info</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/detox/e2e/test/smoke_tests``
**Test code arrangement:**
```
describe('Smoke Tests', () => {
    it('MM-T3202 Leave public channel', () => {
        // code
    });
});
```

Notes:
1. Mobile App E2E requires Mattermost server instance.
- See our [documentation](https://developers.mattermost.com/contribute/server/developer-setup/) on how to run a local server instance.
- If server is running and accessible other than the default `http://localhost:8065`, you may pass `SITE_URL` environment variable.
2. The default sysadmin credential is username:"sysadmin" and password:"Sys@dmin-sample1"
- It's automatically generated by `make test-data` at `mattermost-server` folder
- If using credential other than the said default, you may pass `ADMIN_USERNAME` and `ADMIN_PASSWORD` environment variables.

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by cinlloc** [comment]
:hand: I would like to work on this.

**Comment by cinlloc** [comment]
Sorry I will not be able to do it, I turned myself to more Javascript oriented issues. You can add the `Up-For-Grabs` label again.

**Comment by saturninoabril** [comment]
@cinlloc No worries and thanks!

**Comment by josephbaylon** [comment]
Detox PR: https://github.com/mattermost/mattermost-mobile/pull/5352
