### ISSUE TITLE
Write Mobile App E2E test with Detox: "MM-T3205 Remove user from private channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15711]
See our [documentation for Mobile app end-to-end testing with Detox](https://developers.mattermost.com/contribute/mobile/e2e/) for reference.

<article>
<h1>MM-T3205 Remove user from private channel</h1>
<div>
<div>
<h3>Steps </h3>Remove user from private channel<br>————————————————————————————<br>Ideally, use two devices and watch on the removed user's app / browser as they're removed from the channel to verify they are redirected to Town Square<ol><li>Tap the name of a private channel</li><li> Tap `Manage Members`</li><li> Type the beginning of a user's name in the search box</li><li>Select user and tap `Remove`</li></ol><h3>Expected</h3><ul><li>User is removed from channel:</li><li>Member count decrements by one</li><li>System message posts in channel for the user who removed them</li><li>If watching as the removed user, that user sees Town Square, and the channel is removed from their channel drawer list</li><li>User that was removed now also sees a message in a modal (from desktop) advising them they have been removed (if viewing channel while removed).</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/detox/e2e/test/smoke_tests``
**Test code arrangement:**
```
describe('Smoke Tests', () => {
    it('MM-T3205 Remove user from private channel', () => {
        // code
    });
});
```

Notes:
1. Mobile App E2E requires Mattermost server instance.
- See our [documentation](https://developers.mattermost.com/contribute/server/developer-setup/) on how to run a local server instance.
- If server is running and accessible other than the default `http://localhost:8065`, you may pass `SITE_URL` environment variable.
2. The default sysadmin credential is username:"sysadmin" and password:"Sys@dmin-sample1"
- It's automatically generated by `make test-data` at `mattermost-server` folder
- If using credential other than the said default, you may pass `ADMIN_USERNAME` and `ADMIN_PASSWORD` environment variables.

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by josephbaylon** [comment]
Detox PR: https://github.com/mattermost/mattermost-mobile/pull/5352
