### ISSUE TITLE
Write Mobile App E2E test with Detox: "MM-T3201 Create public channel"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#15716]
See our [documentation for Mobile app end-to-end testing with Detox](https://developers.mattermost.com/contribute/mobile/e2e/) for reference.

<article class="mb-32"><h1 class="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tighter leading-tight md:leading-none mb-12 text-center md:text-left">MM-T3201 Create public channel</h1><div class="max-w-2xl mx-auto"><div><h3>Steps </h3><ol><li>From the channels list, tap on the "+" displayed to the right of "PUBLIC CHANNELS"</li><li>Tap on "create" in the top right of the screen</li><li>Type in a name, observing that the `Create` button is not tappable until at least 2 characters have been entered</li><li>Type in a purpose that has multiple returns (new lines)</li><li>Type in a header that is an emoji (such as ` :taco: `)</li><li>Tap "Create" in the top right of the screen</li></ol><h3>Expected</h3>On step 1, a list of existing channels should be displayed.<br>On step 2, a screen enabling you to name your channel should be displayed.<br>On step 6,<br><ul><li>The new channel should be created and you should be redirected to the new channel</li><li>You can tap the channel name to view and verify channel purpose and header</li></ul><br><hr></div></div></article>

**Test Folder:** ``/detox/e2e/test/smoke_tests``
**Test code arrangement:**
```
describe('Smoke Tests', () => {
    it('MM-T3201 Create public channel', () => {
        // code
    });
});
```

Notes:
1. Mobile App E2E requires Mattermost server instance.
- See our [documentation](https://developers.mattermost.com/contribute/server/developer-setup/) on how to run a local server instance.
- If server is running and accessible other than the default `http://localhost:8065`, you may pass `SITE_URL` environment variable.
2. The default sysadmin credential is username:"sysadmin" and password:"Sys@dmin-sample1"
- It's automatically generated by `make test-data` at `mattermost-server` folder
- If using credential other than the said default, you may pass `ADMIN_USERNAME` and `ADMIN_PASSWORD` environment variables.

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by hectorgabucio** [comment]
I'll do this!

**Comment by saturninoabril** [comment]
Welcome @hectorgabucio and thanks!
