### ISSUE TITLE
[MM-28980] Inconsistent behaviour in channel mentions in message attachments

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-server#15740]
#### Summary
This ticket was originally filed on Jira: https://mattermost.atlassian.net/browse/MM-28980
When creating a channel mention link with `fmt.Sprintf("~%s", channel.Name)` in a message attachment, the behaviour is both inconsistent and buggy:
- If the link is contained in the Title field, it does not render as a link on mobile, but it works on webapp.
- If the link is contained in the Pretext field, the link works on both, but does force a page refresh on webapp (this is not expected).
- If the link is contained in the Text field, it works on mobile, but it ends in a Not Found page on webapp.

#### Steps to reproduce
1. Build a post such as
```
post := &model.Post{
	Message: message,
	Props: map[string]interface{}{
		"attachments": []*model.SlackAttachment{
			{
				Title: fmt.Sprintf("~%s", channel.Name),
				Text:    fmt.Sprintf("~%s", channel.Name),
				Pretext: fmt.Sprintf("~%s", channel.Name),
			},
		},
	},
}
```
2. Send the post to a user.
3. Read the post from the webapp and test all three links.
4. Read the post from the mobile app and test all three links.

#### Expected behavior
The link should in all cases redirect to the channel without a page refresh nor opening a different tab.

#### Possible fixes
For the mobile problem, probably the text is just not parsed through the Markdown parser.
For webapp, there might be problems in the markdown parser, so it mark the links properly as internal links.

**Comment by jufab** [comment]
FYI, my PR is only for the webapp issue
