### ISSUE TITLE
containerized mattermost fails to start

### ISSUE THREAD

**Issue by laur89** [mattermost/mattermost-server#15767]
#### Summary
    docker run--name='mattermost' -p '8065:8065/tcp' -v '/host/opt/mattermost':'/mattermost':'rw' 'mattermost/mattermost-team-edition:master'

Running container created w/ command above causes container start to fail with
> /entrypoint.sh: exec: line 7: mattermost: not found

#### Steps to reproduce
- run container as described in Summary above

#### Expected behavior
Container starts up successfully

#### Observed behavior (that appears unintentional) 
Container immediately exits due to `mattermost` not found on PATH

#### Possible fixes
Is mattermost installed in user homedir which is not on PATH? Or should we install mm explicitly into `/mattermost/bin` that already is included no our PATH?

**Comment by ahmaddanialmohd** [comment]
Hi, @laur89 

May I know which documentation / article did you refer to when you setup Mattermost with Docker? Just trying to understand the process you undergo when you ran into the issue so I can make sense of the `/entrypoint.sh: exec: line 7: mattermost: not found` that you are seeing.

> should we install mm explicitly into /mattermost/bin that already is included no our PATH?

I don't quite understand the possible fixes that you are proposing here. Would you mind elaborating it a little bit more?

Have you tried running the following instead and verify the outcome?

```
docker run--name='mattermost' -p '8065:8065/tcp' -v '/host/opt/mattermost':'/mattermost/bin':'rw' 'mattermost/mattermost-team-edition:master'
```

**Comment by laur89** [comment]
Your example made me realize my fault! I was mounting local directory at `/mattermost` where the installed binary is at.
Removing the mount (or mounting elsewhere) solves the issue.
Thanks.
