### ISSUE TITLE
Migrate string-refs to functional ones: this.refs[this.state.theme]

### ISSUE THREAD

**Issue by Willyfrog** [mattermost/mattermost-server#15843]
## Context:

String references are deprecated in React, and they will eventually disappear. Since [React 16.3](https://github.com/facebook/react/blob/master/CHANGELOG.md#1630-march-29-2018) there is the new api to use for reference creation `createRef` which improved the way to handle them greatly. Callbacks refs still have some valid usage, so we might make exceptions with those, please raise the issue if you feel you need to use them.

## How to migrate

Go to ./components/user*settings/display/user_settings_theme/user_settings*theme.jsx and look for usage of this.refs<this.state.theme>. Once you find them:

1. Remove usage `this.refs.some-reference`
1. Add a `this.some-reference = React.createRef()`
1. Change code depending on `this.refs.some-reference` into using `this.some-reference.current`. Be aware that this might be accessed by files other than the one that defined it. Also, you might need to refactor the code to keep behaviour the same.
1. If there are [e2e tests](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) using that functionality run them to ensure it works as expected. Optionally consider adding any new tests that might ensure it functions as expected.
1. Look for any other `this.refs` used in the file and repeat from the begining.

## Example of migrated code

* [PR #5753](https://github.com/mattermost/mattermost-webapp/pull/5753)

## Questions

you can ask for help messaging @guillermo.vaya or posting in the ~webapp channel in the community server

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA ticket: https://mattermost.atlassian.net/browse/MM-29404

**Comment by parulc7** [comment]
@Willyfrog Can I take up this issue?

**Comment by Willyfrog** [comment]
hello @parulc7 ! let me know if you need any help/clarification with the issue :)

**Comment by Willyfrog** [comment]
moving it back to `up for grabs`

@parulc7 let us know if you want to work on this again :)

**Comment by haardikdharma10** [comment]
Hey @Willyfrog, question here, how should [this.state.theme] be converted? 

`this.this.StateThemeRef = React.createRef();`

Is this the correct approach to do it, if not then please can you help me with it?:)

**Comment by Willyfrog** [comment]
hello @haardikdharma10 and thanks for taking a look at this one.

i've been looking through the code and seems these references are no longer being used, so I'd just delete the code around those and test that everything keeps working the same. Would that be ok with you?

**Comment by haardikdharma10** [comment]
Yes @Willyfrog, that sounds good!

**Comment by Willyfrog** [comment]
sorry! i meant to remove entirely, I don't think we are using that
