### ISSUE TITLE
Mattermost Windows client cannot hold its fixed size and position

### ISSUE THREAD

**Issue by kaksikanaa** [mattermost/mattermost-server#15856]
#### Summary
Mattermost Windows client cannot hold its fixed size and position.

#### Steps to reproduce
Start and use Mattermost Windows client for a while on external 4K monitor and monitor it's behaviour.

#### Expected behavior
Client should start in the pixel perfect position and size where it was last time used and keep it that way while using the client no matter what is done within the app during that time.

#### Observed behavior 
I've use Mattermost on the right side of 4K resolution separate screen. I open it always to its minimun width and maximum height to the screen and I want to keep it that way. The right side should be just visible etc. After using the client for a while, it's size and sometimes the position is changed over time. It moves towards screen center in horisontal aspect and it also is wider than as a start. Sometimes the height also is streched and the botton goes under the Windows taskbar! 

I could not recall any written or send message to cause this behaviour, I've just notice this after a while.

#### Possible fixes
No idea than the questions... is this electron related thing? 4K resolution? Windows problem? Is it possible that the content area / message area live the life it's own depending the messages received or send and the content on them?

**Comment by kaksikanaa** [comment]
![Slide1](https://user-images.githubusercontent.com/15322015/95326800-cefc4080-08ab-11eb-8dfa-a153d8974984.JPG)
![Slide2](https://user-images.githubusercontent.com/15322015/95326809-d4f22180-08ab-11eb-8f70-4683c8d2376f.JPG)

**Comment by kaksikanaa** [comment]
By minimum widht I've mean the least widht before the left panels collabse and become unvisible (app. 1065pixels on my screen because I have mote than one team memberships.

**Comment by amyblais** [comment]
@kaksikanaa What Mattermost desktop app version and Mattermost server version are you on?

**Comment by kaksikanaa** [comment]
Hello, sorry for the looooong delay... this is resolved as it seems to be that the client could not handle (as many other applications as well) the unofficial advanced display scaling settings in Windows. I've used something like +134% etc. and then this problem is present but i I've use 125% or 150% there is no problem.

**Comment by kaksikanaa** [comment]
This is resolved
