### ISSUE TITLE
Direct Message - Get users, pages

### ISSUE THREAD

**Issue by olekwoj** [mattermost/mattermost-server#15918]
When loading users in Direct Message in Web, the Desktop application, don't downloaded all users. The problem concerns download pages - "users? Page=0&per_page=100 ”, but the next occurrence is page 2, not page 1 - users? Page=2&per_page=100 ”, it is a mistake.

**Comment by olekwoj** [comment]
In file 6.b01505bd244c62a4307d.js I changed ...e=>{**const t=e?e+1:0;**"any"===this.props.restrictDirectMessage?this.props.actions.getProfiles(t,100)... 
to 
...e=>{**const t=e?e:0**;"any"===this.props.restrictDirectMessage?this.props.actions.getProfiles(t,100)...
and now is ok.

**Comment by amyblais** [comment]
Closing as a dup of https://forum.mattermost.org/t/direct-message-i-cant-see-all-users/10541
