### ISSUE TITLE
[5.28.0] mmctl for am64 linked against libc.musl-x86_64.so.1

### ISSUE THREAD

**Issue by szutt** [mattermost/mattermost-server#15979]
#### Summary
Binary mmctl from https://releases.mattermost.com/5.28.0/mattermost-team-5.28.0-linux-amd64.tar.gz is linked against the 
libc.musl-x86_64.so.1

#### Steps to reproduce
ldd mmctl 
        linux-vdso.so.1 (0x00007ffcffd1c000)
        libc.musl-x86_64.so.1 => not found

#### Expected behavior
ldd mmctl 
        linux-vdso.so.1 (0x00007ffe50cf7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f647dd9c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f647d9fd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f647dfb9000)

#### Possible fixes
I think this compilation was a mistake (binary for Alpine ?)

**Comment by amyblais** [comment]
Thanks, we're working on a fix https://mattermost.atlassian.net/browse/MM-29740.

**Comment by szutt** [comment]
Thanks !

**Comment by szutt** [comment]
Build 5.28.1 seems okay, thx !
