### ISSUE TITLE
Picture Link Preview not working

### ISSUE THREAD

**Issue by Nisutec** [mattermost/mattermost-server#15971]
#### Summary
At the moment the picture link preview does not work with all links
The following screenshot shows that the link preview will not be displayed.
![The Problem](https://p52.p0.n0.cdn.getcloudapp.com/items/KouwZgZK/Image%202020-10-15%20at%202.40.20%20PM.png?v=02b2489e1434788f0fecf6e6d25fa387)

#### Steps to reproduce
- Send the following Link to a mattermost chat or private conversation
https://drops.n-tp.de/YEuyXYJ5
- After sending the link the picture link preview will not be displayed.

#### Expected behavior
When I send this link to other chatting system the image link preview will display for example the following preview. 
![Expected behavior](https://p52.p0.n0.cdn.getcloudapp.com/items/OAuJgkgp/Image%202020-10-15%20at%202.40.35%20PM.png?v=0b5c7d9d57e725f94313727ed4d1903e)

#### Observed behavior (that appears unintentional) 
The picture link preview will not be displayed.

#### Possible fixes
-

**Comment by amyblais** [comment]
@Nisutec What Mattermost server version are you on? Does it work if you have Website Link Previews enabled in Account Settings?

**Comment by Nisutec** [comment]
The Server Version is Mattermost Enterprise Edition 5.21.0.
Where i can find the "Website Link Previews" Account Setting.
I only find the Picture Link Preview Setting.

![Settings](https://p52.p0.n0.cdn.getcloudapp.com/items/eDuPjQzo/Image%202020-10-15%20at%203.47.59%20PM.png?v=3c2db4b9de39e50c2ee6a101caa2f130)

**Comment by amyblais** [comment]
@Nisutec Your System Admin will probably enable Link Previews in the system console: https://docs.mattermost.com/administration/config-settings.html#enable-link-previews.

Also, please note that we support server versions v5.25.0 and above.

**Comment by Nisutec** [comment]
Ok thank you for the fast help i will check if this setting is enabled
