### ISSUE TITLE
Add end to end tests to the "configEditCmdF" mmctl command

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/mattermost-server#15981]
Mattermost is increasing the end to end test coverage for the [mmctl CLI tool](https://github.com/mattermost/mmctl). The goal is to create a suite of tests that check the main logic paths of each command and ensure that they work against a running server.

This Help Wanted issue covers the addition of end to end tests to the `configEditCmdF` command, in the `commands/config.go` file. The expected way to add these tests is to create a test function in the `commands/config_e2e_test.go` file and add one `s.Run` block for each possible test case.

Thanks to the good amount of already existing unit tests that the commands have, it is not necessary to write an end to end test for every possible logic path of the command; the main focus should be in covering the happy path, the error path and the cases where the user doesn't have permissions to perform an action.

To help with the test process, there are some helpers that can be used. The `s.SetupTestHelper().InitBasic()` chain will create a set of default users, teams and channels to be used during the tests, `s.RunForAllClients` is useful when a test case should be valid for a sysadmin user, a [local mode user](https://docs.mattermost.com/administration/mmctl-cli-tool.html#local-mode) and an unprivileged user, and `s.RunForSystemAdminAndLocal` will test a block for both a sysadmin user and a local mode user. Please take a look at the example pull request to see how all these work.

Example: mattermost/mmctl#202

For instructions on how to set up the end to end tests, take a look at [the corresponding section of the mmctl README](https://github.com/mattermost/mmctl#end-to-end-tests).

If you have questions about the ticket or you need any help, feel free to post your question in [the community CLI channel](https://community.mattermost.com/core/channels/cli) or contact `miguel.delacruz` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-29733

**Comment by SezalAgrawal** [comment]
Can I pick this task?

**Comment by SezalAgrawal** [comment]
Hi @mgdelacroix, configEditCmdF does not have any unit tests to refer to. Can you please guide me what all test cases I can cover in end to end test?

**Comment by mgdelacroix** [comment]
Hi @SezalAgrawal, and apologies for the late response. I think that for the case of config edit we should cover only two cases, the case of a successful config edit and a permissions error.

**Comment by mgdelacroix** [comment]
Hi @SezalAgrawal! Are you still planning to work on this issue? Is there anything we can help with?

**Comment by SezalAgrawal** [comment]
Yes, I will try to wrap it up this week.

**Comment by SezalAgrawal** [comment]
Hi @mgdelacroix, for the successful test case, can you guide me on how should I mock the editor?

**Comment by isacikgoz** [comment]
Hey @SezalAgrawal Not tested but as a quick hack I think you can set the `EDITOR` environment variable to something simply does nothing before the test. E.g. `echo`. With that, the command would not fail when we run it as `exec.Command(editor, file.Name())`.

**Comment by SezalAgrawal** [comment]
Hi @isacikgoz, I was also thinking to use this, but then how can I cover a successful scenario, which edits the config? The function `configEditCmdF` creates a temp file, edits it, removes it. If we were passing a file instance to the function, then I could have mocked the file.

**Comment by isacikgoz** [comment]
@SezalAgrawal we don't need to mock the file, we simply want to test if we edit the config and see the response from the server. Actually we can use `sed` as an editor here. We can simply create a script file, assign it to the `EDITOR` variable so that it will be our editor. The file can following lines (this is for macOS btw): 

```bash
#! /bin/bash

sed -i'old' 's/\"EnableSVGs\": true/\"EnableSVGs\": false/' $1
rm $1'old'
```

After that, we can check if the value is changed after the command.
