### ISSUE TITLE
select dropdown only show once

### ISSUE THREAD

**Issue by jk2K** [mattermost/mattermost-server#16042]
### Summary
select dropdown only show once

dropdown menu no longer appears

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

mattermost 5.26

#### Expected behavior
Describe your issue in detail

show dropdown options every time

![image](https://user-images.githubusercontent.com/4025839/96579963-2b2e7e00-130a-11eb-8e50-f32ed4110358.png)

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

dropdown options only show once

![image](https://user-images.githubusercontent.com/4025839/96598062-114c6580-1321-11eb-8c60-60093f6acfbc.png)

**Comment by amyblais** [comment]
@jk2K Can you help describe where the dropdowns are located (where are the screenshots taken from)?

**Comment by jk2K** [comment]
@amyblais I updated the screenshoot, dropdown options should be `aresweb`, `aresmobile`, `aresjenkins`，I deployed a mattermost instance, and created a integration that can open dialogs when users click message buttons

**Comment by jk2K** [comment]
fixed in version 5.28
