### ISSUE TITLE
Missing DB constraints

### ISSUE THREAD

**Issue by nerzhul** [mattermost/mattermost-server#16068]
#### Summary
Hello, thanks for mattermost

i looked up your db scheme today to perform some cleanup on one of my instances and i saw that you are not using constraints to prevent database inconsistency problems.
I'm here focusing on posts which have different ids in multiple tables. If you delete an entry on post table (for various reasons) the postid is always present in other tables, which means garbage.

#### Steps to reproduce
Delete a post by id on posts table.
Other tables having postid reference has orphan records

#### Expected behavior
When you delete a post from posts table it drop the referenced postid from other tables

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes

```
ALTER TABLE fileinfo ADD CONSTRAINT fileinfo_postid_fkey FOREIGN KEY (postid)
	   REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE reactions ADD CONSTRAINT fileinfo_postid_fkey FOREIGN KEY (postid)
	   REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE;
```

This fix is on what i observed in the DB, but you may  have many other references needing those constraints to ensure db inconsistency.
This will also permit to shorten your enterprise license cleanup model by just deleting posts by date without searching in other tables where they are referenced.

**Comment by amyblais** [comment]
@nerzhul I asked our team and our dev mentioned that this is a known fact. We don't use foreign keys to enforce referential integrity. This was a conscious choice motivated by performance reasons. This can of course lead to issues when people manually delete DB entries. To mitigate this we have an integrity check CLI command to aid system admins in checking their DB state (https://docs.mattermost.com/administration/command-line-tools.html#mattermost-integrity).
