### ISSUE TITLE
Images in Markdown not showing if enabled local proxy

### ISSUE THREAD

**Issue by ybudimirov** [mattermost/mattermost-server#16097]
#### Summary
Images in Markdown not showing

#### Steps to reproduce
**OS: Ubuntu 18.04.3 LTS
Mattermost Version: 5.28.1 (docker)**
AllowedUntrustedInternalConnections set to server private ip: 172.30.0.x/32
Enable image proxy: SystemConsole->Environment->image proxy
Send message: 
`
![test](https://camo.githubusercontent.com/6db5a07d93819ee616798a5448d0b1c1746f6b45/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67)
`

#### Logs

nginx.log
`
172.29.0.2 - - [28/Oct/2020:12:56:11 +0000] "GET /api/v4/image?url=https%3A%2F%2Fcamo.githubusercontent.com%2F6db5a07d93819ee616798a5448d0b1c1746f6b45%2F68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67 HTTP/1.1" 301 194 "-" "mattermost-5.28.0"
`
`
172.29.0.2 - - [28/Oct/2020:12:56:11 +0000] "GET /api/v4/image?url=https%3A%2F%2Fcamo.githubusercontent.com%2F6db5a07d93819ee616798a5448d0b1c1746f6b45%2F68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67 HTTP/1.1" 401 186 "http://mattermost.example.com/api/v4/image?url=https%3A%2F%2Fcamo.githubusercontent.com%2F6db5a07d93819ee616798a5448d0b1c1746f6b45%2F68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67" "mattermost-5.28.0"
`
`
client_ip - - [28/Oct/2020:12:56:11 +0000] "GET /api/v4/image?url=http%3A%2F%2Fmattermost.example.com%2Fapi%2Fv4%2Fimage%3Furl%3Dhttps%253A%252F%252Fcamo.githubusercontent.com%252F6db5a07d93819ee616798a5448d0b1c1746f6b45%252F68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67 HTTP/2.0" 403 29 "-" "Mozilla/5.0 Gecko/20100101 Firefox/82.0"
`

mattermost.log
`
{"level":"debug","ts":1603864799.6437383,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"POST","url":"/api/v4/posts","request_id":"xu1nrj53mtr4db64kyboqxwoqw","status_code":"201"}
{"level":"debug","ts":1603864800.4476974,"caller":"imageproxy@v0.10.0/imageproxy.go:403","msg":"error fetching remote image: Get \"http://mattermost.example.com/api/v4/image?url=https%3A%2F%2Fcamo.githubusercontent.com%2F6db5a07d93819ee616798a5448d0b1c1746f6b45%2F68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67#0x0\": Get \"http://mattermost.example.com/api/v4/image?url=https%3A%2F%2Fcamo.githubusercontent.com%2F6db5a07d93819ee616798a5448d0b1c1746f6b45%2F68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67\": address forbidden, you may need to set AllowedUntrustedInternalConnections to allow an integration access to your internal network","image_proxy":"local"}
{"level":"debug","ts":1603864800.4479585,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"GET","url":"/api/v4/image","request_id":"z3jb9yp8a3rdumwidpo4mrrxoa","status_code":"500"}
`

mattermost.log added server internal ip: 172.30.0.199/32  to AllowedUntrustedInternalConnections:
`
{"level":"debug","ts":1603867354.7957444,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_typing"}
{"level":"debug","ts":1603867355.3988767,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"POST","url":"/api/v4/posts","request_id":"pkn7jc1whtyz3qwh5ja67umbby","status_code":"201"}
{"level":"debug","ts":1603867356.2161462,"caller":"mlog/log.go:208","msg":"Invalid or expired session, please login again.","path":"/api/v4/image","request_id":"r163josme7fitdmqwkskpw41ee","ip_addr":"172.29.0.2","user_id":"","method":"GET","err_where":"","http_code":401,"err_details":"UserRequired"}
{"level":"debug","ts":1603867356.2164347,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"GET","url":"/api/v4/image","request_id":"r163josme7fitdmqwkskpw41ee","status_code":"401"}
{"level":"debug","ts":1603867356.2170804,"caller":"imageproxy@v0.10.0/imageproxy.go:411","msg":"content-type not allowed: \"application/json\"","image_proxy":"local"}
{"level":"debug","ts":1603867356.2172604,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"GET","url":"/api/v4/image","request_id":"3o6fjuk9kinsbnkk3c8hodxtjy","status_code":"403"}
`

#### Expected behavior
Image appears in chat

#### Observed behavior (that appears unintentional) 
Image from url works fine
Image from attachment works fine
Image from markdown didn't work
![2020-10-27_172707](https://user-images.githubusercontent.com/12114831/97326325-90d7b880-187c-11eb-8654-c94e3cf234cf.png)

#### Possible fixes
SystemConsole->Environment->Web Server -> Site URL:
Change url from http:// to https:// and now Markdown image should work fine.

**Comment by amyblais** [comment]
@ybudimirov What environment are you on (OS and version)?
Do you see any errors in server logs or in the developer console?
Which version did you upgrade from?

**Comment by ybudimirov** [comment]
@amyblais  Thank you for help!
OS: Ubuntu 18.04.3 LTS
Added logs to first post.
Upgraded from: 5.23

AllowedUntrustedInternalConnections is set to server internal ip: 172.30.0.199

**Comment by amyblais** [comment]
@hmhealey Would you be familiar with the errors here?

**Comment by hmhealey** [comment]
> `{"level":"debug","ts":1603864800.4476974,"caller":"imageproxy@v0.10.0/imageproxy.go:403","msg":"error fetching remote image: Get \"http://mattermost.example.com/api/v4/image?url=https%3A%2F%2Fcamo.githubusercontent.com%2F6db5a07d93819ee616798a5448d0b1c1746f6b45%2F68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67#0x0\": Get \"http://mattermost.example.com/api/v4/image?url=https%3A%2F%2Fcamo.githubusercontent.com%2F6db5a07d93819ee616798a5448d0b1c1746f6b45%2F68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67\": address forbidden, you may need to set AllowedUntrustedInternalConnections to allow an integration access to your internal network","image_proxy":"local"} `

This error is the one that looks the most important. In that case, did you post the `https://camo.githubusercontent.com` link or did you post `http://mattermost.example.com/api/v4/image?...` as the image there?

When I post the example you have above with the local image proxy enabled, it works fine for me without setting AllowedUntrustedInternalConnections.

**Comment by ybudimirov** [comment]
@hmhealey  Thank you for your reply!

Issue was related to the Site URL.
SystemConsole->Environment->Web Server -> Site URL:
Changed url from http:// to https:// and now Markdown image works fine.

If you need you can replicate the same behavior via next steps:
```
OS ubuntu 18.04
# setup docker and docker-compose
sudo apt-get install docker.io docker -y
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
# setup Mattermost from docker repo
git clone https://github.com/mattermost/mattermost-docker.git
cd mattermost-docker
mkdir -p ./volumes/app/mattermost/{data,logs,config,plugins,client-plugins}
chown -R 2000:2000 ./volumes/app/mattermost/
# create certificate and key for Mattermost domain(filenames is important!!!)
volumes/web/cert/cert.pem 
volumes/web/cert/key-no-password.pem
# start MM
docker-compose up
# login to MM
# configure MM domain use http://url
SystemConsole->Environment->Web Server->Site URL
# enable image proxy
SystemConsole->Environment->image proxy
# send message to MM
![test](https://camo.githubusercontent.com/6db5a07d93819ee616798a5448d0b1c1746f6b45/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67)

**Comment by hmhealey** [comment]
Thanks for the heads up. That makes sense that that would help. The server has some code in it to prevent it from trying to add the image proxy to image URLs that are already going through the image proxy. Since the Site URL was incorrect, it must've tried to load the already-proxied image URL through the image proxy which would definitely confuse things.
