### ISSUE TITLE
Can't use Special Characters in password

### ISSUE THREAD

**Issue by sailfish009** [mattermost/mattermost-server#16114]
#### Summary
Can't use Special Characters in password

#### Steps to reproduce
set password with special character when register account

#### Expected behavior
should have to logged in without any problem.

#### Observed behavior (that appears unintentional) 
login failed, log attempt locked, reset email didn't worked.
finally reset admin password with command.

#### Possible fixes
currently only have to set password weak alphabet numeric combination.

**Comment by amyblais** [comment]
@sailfish009 What environment are you on (OS and version)?
What Mattermost server version are you on?

**Comment by sailfish009** [comment]
$ /opt/mattermost$ sudo -u mattermost ./bin/mattermost version

```
Version: 5.28.0
Build Number: 5.28.1
Build Date: Mon Oct 19 15:20:59 UTC 2020
Build Hash: d991504714aded3b97f95fea8f78a01e6ea125bb
Build Enterprise Ready: true
DB Version: 5.28.0
```

**Comment by amyblais** [comment]
What are your password settings set to https://docs.mattermost.com/administration/config-settings.html#password-requirements?

**Comment by amyblais** [comment]
What login method do you use (e.g. email and password, SAML, etc.?)
Do you see any server log or console errors?

**Comment by sailfish009** [comment]
> 
> 
> What are your password settings set to https://docs.mattermost.com/administration/config-settings.html#password-requirements?

normal password combination like "pwgen -sy" (length 16)

> What login method do you use (e.g. email and password, SAML, etc.?)
Do you see any server log or console errors?

yeah, some golang url error message, i don't remember right now.

**Comment by amyblais** [comment]
Thanks, is there any other information you can help share about your environment or reproduction steps that could help me reproduce this?

**Comment by sailfish009** [comment]
> Thanks, is there any other information you can help share about your environment or reproduction steps that could help me reproduce this?

OS: ubuntu 20.10 64bit
DB: postgresql 13

**Comment by lieut-data** [comment]
@sailfish009, it would be helpful if you could provide a sample password that reproduces here. It doesn't have to be the one you used originally -- just something that `pwgen` spits out and fails to work in your environment. Of course, if you are willing to abandon and share the original that caused this issue, that would be great as well!

Under the covers, we /should/ be agnostic with respect to the password characters you provide. The server can require a minimum level of complexity, but shouldn't reject any valid Unicode password. Given your report, we definitely need to figure out what went wrong here and an example password that fails would help tremendously.
