### ISSUE TITLE
Image / gif URLs render less cleanly on Mattermost than Discord

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#16185]
When some images are shared on Discord via their GIF function a nice simple GIF is displayed. Example:

URL: https://tenor.com/view/h%c3%a2m-frog-toad-frog-l%e1%ba%afc-wiggle-gif-14557565
Screenshot: 
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/kpuwegy2/Image%202020-10-31%20at%208.40.36%20PM.png)

This URL is rendered with text and not just the image (arguably much less effective) in Mattermost:
![mm example](https://p153.p0.n0.cdn.getcloudapp.com/items/WnurXOAr/Image%202020-10-31%20at%208.41.42%20PM.png)

Can Mattermost be made to render the image like Discord does it with just the image and no text in such cases?

**Comment by seongwon-kang** [comment]
![image](https://user-images.githubusercontent.com/56567660/97948850-23281100-1dd5-11eb-92af-34cbec270224.png)
Image will display when you upload image url directly. I didn't tested this on Discord, It works like your screenshot when you post url? (`https://tenor.com/view/h%c3%a2m-frog-toad-frog-l%e1%ba%afc-wiggle-gif-14557565`)

**Comment by seongwon-kang** [comment]
I tests this now, Discord transforms url into gif automatically.

**Comment by seongwon-kang** [comment]
How about post this in https://mattermost.uservoice.com/forums/306457-general ?
