### ISSUE TITLE
System Console item is missing after server migration.

### ISSUE THREAD

**Issue by taikim8484** [mattermost/mattermost-server#16187]
Hi everyone!

I have just migrated my own Mattermost server from a k8s cluster to the other.
But then, my root system admin account is missing System Console item in the menu list.
I'm unable to access system console via https://server/admin_console directly as well, it thrown 403, please check the attachment below.
![alt text](https://i.ibb.co/ssLfsf0/Screen-Shot-2020-11-01-at-12-12-36.png "Logo Title Text 1")
Is there anyone has met this issue yet? Thank you so much!

**Comment by amyblais** [comment]
@taikim8484 

1. Have you had a chance to take a look at our troubleshooting guide related to websockets https://docs.mattermost.com/install/troubleshooting.html#server-administration?
2. Are there any server log errors you can share?

**Comment by amyblais** [comment]
We haven't received a response for a while so I'll close this for now - please reopen this issue if the problem persists.
