### ISSUE TITLE
Log message "Failed to send welcome email on create admin user" seems misleading

### ISSUE THREAD

**Issue by TheRND** [mattermost/mattermost-server#16207]
#### Summary
Log message "Failed to send welcome email on create admin user" seems misleading

#### Steps to reproduce
Create user with API call with email notifications off

#### Expected behavior
Log message does not read like it was new chat admin created

#### Observed behavior (that appears unintentional) 
Message are misleading now
 
#### Possible fixes
Change message to something like "Failed to send welcome email to new user, created by system admin"

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-30270

**Comment by amyblais** [comment]
Already fixed in Cloud; to be fixed in self-managed v5.34 (April 16th) release.
