### ISSUE TITLE
Sign in with gitlab fail when mattermost use non-standard https port

### ISSUE THREAD

**Issue by cnhongwei** [mattermost/mattermost-server#16215]
## Summary
Sign in with gitlab fail when mattermost use non-standard https port

#### Steps to reproduce
I use Self-Managed gitlab and mattermost, i just use non-standard https port.
examples:  https://gitlab.xxx.com:3443 https://mattermost.xxx.com:3443
when i sign in with gitlab on mattermost, get error: "Error 令牌请求得到错误的回复。Back to Mattermost"
the mattermost log is "{"level":"error","ts":1604548978.0031,"caller":"web/oauth.go:282","msg":"AuthorizeOAuthUser: 令牌请求得到错误的回复。, response_body={\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}, status_code=400"}"

i test use 443 https port, sign with gitlab success

#### Expected behavior
sign with gitlab success

**Comment by amyblais** [comment]
@cnhongwei There was an issue related to this some time ago https://github.com/mattermost/mattermost-server/issues/13059, but it was fixed via https://github.com/mattermost/mattermost-docker/pull/474.

Does the above issue seem related to the issue you're seeing? If not, what Mattermost server version are you currently on?

**Comment by cnhongwei** [comment]
@amyblais   this bug is different from #13059. 
I check gitlab's log

```
Processing by Oauth::TokensController#create as JSON
  Parameters: {"client_id"=>"e1c4fc5b85e462068968be9960e64758a20a3c5034aaf5a73cef1699c8a8592a", "client_secret"=>"[FILTERED]", "code"=>"[FILTERED]", "grant_type"=>"authorization_code", "redirect_uri"=>"https://xxxxx.com/signup/gitlab/complete"}
Completed 400 Bad Request in 84ms (Views: 0.2ms | ActiveRecord: 40.6ms | Elasticsearch: 0.0ms | Allocations: 16308)
```
the parameter of "redirect_uri" is error.  the https port is not contained. But I set the "SiteURL": "https://xxxxx.com:3443" in mattermost's config.json file.
 
mattermost code in web/oauth.go:271
```go
uri := c.GetSiteURLHeader() + "/signup/" + service + "/complete"
body, teamId, props, err := c.App.AuthorizeOAuthUser(w, r, service, code, state, uri)
```
I guess c.GetSiteURLHeader() get wrong SiteURL.

**Comment by amyblais** [comment]
@cnhongwei What Mattermost server version are you on and did you experience this issue on previous versions?

**Comment by cnhongwei** [comment]
Mattermost Version: 5.28.1
Database Schema Version: 5.28.0
Database: postgres
Gitlab: 13.5.1

I use the mattermost first and didn't use previous versions.

**Comment by cnhongwei** [comment]
I add https port number into web/oauth.go:271
```go
uri := c.GetSiteURLHeader() + "/signup/" + service + "/complete"
```

then login success, but browser redirect url is erorr after login success

I also add https port number into web/oauth.go:328
```go
redirectUrl = c.GetSiteURLHeader()
```

login success and browser redirect succes.

so i recommend GetSiteURLHeader() method get http/https port from request head['X-Forwarded-Port'] or use SiteURL propertity in config.json

**Comment by amyblais** [comment]
@hmhealey Would this be a Gitlab related issue that you're familiar with?

**Comment by hmhealey** [comment]
No, I'm not familiar with it. It seems like a general issue with our OAuth code. I can file a ticket with what I think is going on.

**Comment by hmhealey** [comment]
https://mattermost.atlassian.net/browse/MM-30490

**Comment by agnivade** [comment]
Hi @cnhongwei - it seems like your environment is not setting the correct `Host` header along with the port that Mattermost expects. We set the `siteURLHeader` from here:https://github.com/mattermost/mattermost-server/blob/8e221c1895fc42a41edc73c2e9fc09e3c98aaf43/web/handlers.go#L156.

So the `Host` header should contain any custom port that is used. Can you check if the correct Host header is being passed to Mattermost?

Are you using nginx in front of your application? Can you show me the the `proxy_set_header Host` directive from your config?

If nginx runs on a different port, then using `$http_host` or `$host` might not pass the right port to Mattermost. And you might need to set the backend server's port explicitly.

**Comment by cnhongwei** [comment]
I change "proxy_set_header Host $host" to "proxy_set_header Host $host:$server_port;" in nginx config.
it reolves my problem.

thanks everybody!

**Comment by agnivade** [comment]
Thanks for the confirmation @cnhongwei !
