### ISSUE TITLE
Disallow that users leave a Team

### ISSUE THREAD

**Issue by Breee** [mattermost/mattermost-server#16214]
We want to assign groups of people to teams. These teams do not change and they are a private space. 
(1) Users are not allowed to Leave their team, (2) Users are not allowed to join another team.

- In the settings we see that you can disallow that people Join Teams.  

It would be nice, if we can also disallow that people Leave a Team. 

Did we not find the right setting,  or is this not implemented?

**Comment by amyblais** [comment]
@Breee As far as I know we don't have a setting for it yet. Feel free to open a feature request for this. There is one related feature request open here, so feel free to upvote it if you want to: https://mattermost.uservoice.com/forums/306457-general/suggestions/31928344-add-a-system-console-option-to-hide-the-leave-tea.
