### ISSUE TITLE
Mattermost makes no real redirect to /login, but only changes the path.

### ISSUE THREAD

**Issue by Breee** [mattermost/mattermost-server#16229]
#### Summary
Mattermost does not redirect to /login, but instead it just changes the path. This makes it impossible to redirect /login to another auth source, for example directly to Gitlab.

#### Steps to reproduce
Enter chat.example.com
look at the actual requests fired by your browser.

#### Expected behavior
1. Enter chat.example.com.
2. If the user is not logged in, redirect to chat.example.com/login 

#### Observed behavior (that appears unintentional) 
1. Enter chat.example.com.
2. Just the URL in the browser is changed, no redirect happens. 

#### Possible fixes
Redirect chat.example.com to chat.example.com/login, if a user is not logged in. 

is this intended?

**Comment by amyblais** [comment]
@Breee What Mattermost server version are you on? Can you help share a screenshot of what screen you see when accessing "chat.example.com"?
