### ISSUE TITLE
Patch "Gitlab" button

### ISSUE THREAD

**Issue by Breee** [mattermost/mattermost-server#16228]
I'm using keycloak as oauth provider,  with the help of the gitlab client. 
I'd like to patch the Login Button for "Gitlab" and replace the Text / the Icon

Could you point me to the right files / the best way to do this?

**Comment by Breee** [comment]
added to `/mattermost/client/7.d3cb0b37f39fe6e1f885.css`

```
.signup-team__container .btn.btn-custom-login.gitlab{
    background: #333335;
}

.signup-team__container .btn.btn-custom-login.gitlab .icon {
    background-image: url(/static/files/keycloak.png) !important;
    display: block !important;
    }
    
.signup-team__container .btn.btn-custom-login>span>span {
display: none !important;
} 
.signup-team__container .btn.btn-custom-login>span:after {
line-height: normal !important; 
content: 'Keycloak' !important;
}
```

works fine so far ;)

**Comment by DavidSteinbauer** [comment]
@Breee Thanks for your code! I made plugin for it today using this [plugin](https://github.com/discourse/mattermost-css-hacks).

Just replace your css with the default.
this is the plugin:
[custom_css.tar.gz](https://github.com/mattermost/mattermost-server/files/5506493/custom_css.tar.gz)
