### ISSUE TITLE
Messages posted today may appear as "Yesterday"

### ISSUE THREAD

**Issue by maruTA-bis5** [mattermost/mattermost-server#16259]
#### Summary
In the following environment, the message posted today was sometimes displayed as "Yesterday".

- JST (UTC+9) for both server and client PC time zones
- `"ExperimentalTimezone": false` in config.json
- Mattermost Version: Team Edition 5.28.1, Enterprise Edition (unlicensed) 5.29.0-rc2
- Windows 10 + Firefox, Desktop App, Google Chrome

#### Steps to reproduce
Post a message between 00:00 and 09:00 JST in the above environment

#### Expected behavior
Posts at JST 07:00 (UTC 22:00) should be labeled "Today".

#### Observed behavior (that appears unintentional) 
Posts at JST 07:00 (UTC 22:00) are labeled "Yesterday".

![image](https://user-images.githubusercontent.com/1310661/98810652-e0180e80-2462-11eb-82b9-110d9d4bffa8.png)

According to the content posted on Twitter by other Japanese user, "Yesterday" is displayed before JST 09:00 (UTC 00:00), and "Today" is displayed after that time.
(https://twitter.com/ken_kiku/status/1323061018004660225)

#### Possible fixes
As a workaround, setting `ExperimentalTimezone` to `true` will display it correctly.

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-30489.

**Comment by haardikdharma10** [comment]
Hey @maruTA-bis5, I think changing ExperimentalTimezone to true [here](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/fixtures/partial_default_config.json#L490-#L493) will do the job. Can you please confirm so that I can go ahead and make the change? Thanks!

**Comment by haardikdharma10** [comment]
Also, @amyblais, can you assign this to me? :)

**Comment by haardikdharma10** [comment]
@amyblais, I am sorry for the trouble but can you tag a few developers who can confirm whether what I wrote above sounds good? Thank you!

**Comment by amyblais** [comment]
@calebroseland Can you help with the question here https://github.com/mattermost/mattermost-server/issues/16259#issuecomment-726686534?

**Comment by calebroseland** [comment]
@haardikdharma10 this seems like a discrepancy between the date-part ('Yesterday'/'Today') and the time-part. 

e.g. when `ExperimentalTimezone: false`, the relative-time parsing in [datetime.ts](https://github.com/mattermost/mattermost-webapp/blob/master/utils/datetime.ts#L50-L51) is explicitly UTC-based if no timezone is provided, whereas the Date constructor used to parse the value in timestamp.tsx implicitly uses the client/browser timezone.


Maybe removing the explicitly-UTC there would do the trick?
```diff
-    const momentA = moment.utc(a.getTime());
-    const momentB = moment.utc(b.getTime());
+    const momentA = moment(a);
+    const momentB = moment(b);
```

**Comment by haardikdharma10** [comment]
@calebroseland, thanks for the explanation. I appreciate your time:) I'll give it a go.
