### ISSUE TITLE
Slack color import different format

### ISSUE THREAD

**Issue by webmake** [mattermost/mattermost-server#16268]
#### Summary
It seems that slack has changed their format of exporting color schemes
![image](https://user-images.githubusercontent.com/5016464/99064119-2b8b0380-25ae-11eb-9aed-a86dbeef35bf.png)

#### Steps to reproduce
#1A1D21,#121016,#3A2D3B,#FBFAF7,#27242C,#FBFAF7,#2EB67D,#BD3855,#4A154B,#FBFAF7

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-30531

**Comment by amyblais** [comment]
Already fixed in Cloud; to be fixed in self-managed v5.34 (April 16th) release.
