### ISSUE TITLE
Post Dropdown Sub Menu is misaligned

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-server#16272]
Plugins can add items to the post dropdown menu, including submenus that pop over to the side of the menu. The submenus are currently misaligned. The task here is to fix the rendering of the submenus so that they are horizontally aligned with the parent menu’s option.

The [demo plugin](https://github.com/mattermost/mattermost-plugin-demo) can be used to test this. You will need to install and enable the plugin for the submenus to be rendered.

#### Screenshots

![image](https://user-images.githubusercontent.com/6913320/99131697-d36df480-25e1-11eb-8140-68629cd8001e.png)

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-26644

**Comment by joelazwar** [comment]
Hi I'd like to work on this issue :)

**Comment by mickmister** [comment]
It's all yours! Thanks @joelazwar!!

**Comment by mickmister** [comment]
Hi @joelazwar, I hope you are doing well. Do you have any questions about this ticket?

**Comment by joelazwar** [comment]
hey @mickmister sorry, have been really busy lately and hadnt had time work on this. You could unassign me if you'd like since I'm still quite busy

**Comment by mickmister** [comment]
No problem, thanks @joelazwar!

**Comment by rolwin100** [comment]
@mickmister can you please tell me how to set up the demo plugin in local can't find any proper docs for it.

**Comment by rolwin100** [comment]
@mickmister can I take this up

**Comment by rolwin100** [comment]
I think it is already fixed

**Comment by mickmister** [comment]
Indeed this seems to be fixed in 5.26. Thanks @rolwin100!
