### ISSUE TITLE
Smiley in last Message causes scrolling bug

### ISSUE THREAD

**Issue by georg-cloud** [mattermost/mattermost-server#16276]
#### Summary
When the last message i got in a chat contains a smiley and I mouse-over it, I can scroll further down into blank space.

#### Steps to reproduce
Version 4.4.0 (4.4.0.5682)
Open a chat - for example to one self (you)
Post a Smiley - for example :) (different smileys cause different extents of the bug)
Hover the mouse over the message which contains the Smiley
Scroll down

#### Expected behavior
I would expect the scrolling to behave in the same way it does everywhere else in the chat.

#### Observed behavior (that appears unintentional) 
<img width="1210" alt="Mattermost Bug" src="https://user-images.githubusercontent.com/58072899/99236541-9e3aef80-27f7-11eb-96d9-39b584d459b3.png">

**Comment by amyblais** [comment]
@georg-cloud Our minimum supported server version is v5.25.0. Would you be open to upgrading?
