### ISSUE TITLE
loadtest: add file descriptors limit sanity check to the agent

### ISSUE THREAD

**Issue by streamer45** [mattermost/mattermost-server#16284]
### Introduction

This is a load-test specific issue to be implemented and submitted under the [official load-test  tool repository](https://github.com/mattermost/mattermost-load-test-ng).

Our load-test tool is used to test Mattermost application under heavy load, simulating real-world usage of a server installation at scale.

### Description

Load-test agents require 1 file descriptor per simulated user (ws connection) plus a fixed amount (up to 500) for the HTTP connections pool.

When running either `ltapi` or `ltagent` commands we should do a sanity check to make sure the current file descriptors limit (`syscall.RLIMIT_NOFILE`) is compatible with the configured maximum number of users and return an error otherwise.

### Need help?

If you have questions about the ticket or you need any help, feel free to post your question in [~Developers: Performance](https://community.mattermost.com/core/channels/developers-performance) or contact `claudio.costa` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-30334

**Comment by agnivade** [comment]
@CandyZack - Would you be interested in taking this one?

**Comment by CandyZack** [comment]
@agnivade Sure. I will give it a try! Assign me this issue.

**Comment by agnivade** [comment]
Hi @CandyZack - how is it going with this? Let us know if we can help in any way.

**Comment by CandyZack** [comment]
@agnivade  Sorry for delay. Was loaded with work 😩, and I missed this.
I need help with testcases. I have mentioned this in the PR
