### ISSUE TITLE
Update Bundled plugin packages for next server version to be shipped

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-server#16295]
Update plugins to these version (versions taken from Marketplace repo):
- mattermost-plugin-zoom-v1.4
PLUGIN_PACKAGES += mattermost-plugin-autolink-v1.2.1 
PLUGIN_PACKAGES += mattermost-plugin-nps-v1.1.0
PLUGIN_PACKAGES += mattermost-plugin-custom-attributes-v1.2.0
PLUGIN_PACKAGES += mattermost-plugin-github-v2.0
PLUGIN_PACKAGES += mattermost-plugin-welcomebot-v1.2
PLUGIN_PACKAGES += mattermost-plugin-aws-SNS-v1.1
PLUGIN_PACKAGES += mattermost-plugin-antivirus-v0.1.2
PLUGIN_PACKAGES += mattermost-plugin-jira-v3.0.1 (with browser auth fix) 
PLUGIN_PACKAGES += mattermost-plugin-gitlab-v1.2.0
PLUGIN_PACKAGES += mattermost-plugin-jenkins-v1.1

https://github.com/mattermost/mattermost-server/blob/221f70a6cb4645d660df5339ab1921fd497bd7df/Makefile#L87

**Comment by hanzei** [comment]
Moved to JIRA: https://mattermost.atlassian.net/browse/MM-30709
