### ISSUE TITLE
Version bump on pre-bundled IR plugin

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-server#16294]
@itao and @cpoile - Do you want to bundle in a newer version of the Incident response plugin with server versions that get shipped out?  Updating this will result in that version going out with the server bundle, so that airgapped servers get those plugins and updates for them:   https://github.com/mattermost/mattermost-server/blob/221f70a6cb4645d660df5339ab1921fd497bd7df/Makefile#L98

**Comment by itao** [comment]
Yes! Thanks for the ping

@cpoile I believe we're on v1.1.1 now, correct? Could you also include Channel Export?

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/16323
