### ISSUE TITLE
Change receiver name for (me *InvitePeopleProvider) in app/slashcommands/command_invite_people.go to be more idiomatic

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#16299]
The Mattermost codebase has a lot of methods with receiver names as `me`. This is a carry-over from other Object Oriented languages and not idiomatic Go as pointed out [here](https://github.com/golang/go/wiki/CodeReviewComments#receiver-names).

This ticket is about changing the receiver name from `me` to something more suitable for `(me *InvitePeopleProvider)` in `app/slashcommands/command_invite_people.go`.

Example Pull Request: #16298

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-30705

**Comment by CandyZack** [comment]
@agnivade  I would to resolve this issue. Can you please assign it to me?
