### ISSUE TITLE
Messages are loaded very slowly when using Mattermost 5.26 or higher

### ISSUE THREAD

**Issue by salmiakk** [mattermost/mattermost-server#16317]
#### Summary
Messages are loaded very slowly when using Mattermost 5.26 or higher

#### Steps to reproduce
Install Mattermost 5.26 or higher with mattermost-docker manifests and Postgres 13.1 (although the issue was present on Postgres 9.5 as well). Our instance has ~600 channels and ~3 000 000 messages, Team edition.
Try to read older messages.

#### Expected behavior
Messages are loading as fast as on Mattermost 5.25.

#### Observed behavior (that appears unintentional) 
Messages on all channels are loading very slowly (eg. ~8 seconds), making the user experience very poor. Searching through all messages takes a lot of time as well (~13 seconds for a common keyword). While loading, CPU usage on the server serving Mattermost (measured via htop) is around 100% - by postgres process. It seems that the queries take much longer to execute on 5.26+ than on 5.25. If we downgrade, it all returns back to normal.

Clients used: Chromium 83.0.4103.116, Mattermost desktop client v.4.6.1 (Linux)

At first I tried upgrading Postgres from 9.5 to 13.1, but that didn't change much. Since 5.25 works fine on the same machine, I doubt that it is missing resources like CPU or RAM.

**Comment by lieut-data** [comment]
@salmiakk, you mentioned v5.26 or higher -- can you confirm this remains an issue in v5.29?

**Comment by salmiakk** [comment]
Yes, the same happens in v5.29. Initially I upgraded from 5.21 to 5.29, then tried older versions, and 5.25 is the latest that works nicely

**Comment by lieut-data** [comment]
Something is definitely taxing the Postgres instance on that machine -- can you enable the slow query log and share what shows up? Temporarily configuring `log_min_duration_statement = 1000` should help surface queries that take longer than a second and help us pinpoint why things are slow for you.
