### ISSUE TITLE
Long Delay When Changing Theme

### ISSUE THREAD

**Issue by ivanivkovic** [mattermost/mattermost-server#16313]
#### Summary
When changing the Account Settings > Display > Theme in Mattermost, the GUI seems to be jammed for a long time, for about 5-10 seconds, tested on community.mattermost.com.
Using Google Chrome

#### Steps to reproduce
Try to change the theme in Account Settings and click Save. Unable to check the exact version.
https://community.mattermost.com/core/channels/developers

#### Expected behavior
No delay after clicking Save.

#### Observed behavior (that appears unintentional) 
Nothing could be clicked and the cursor is a pointer for a long time, at least 6-7 seconds.

**Comment by amyblais** [comment]
@ivanivkovic I wasn't able to reproduce - I'm on Mac, Chrome.

Which OS and version are you on? Do you see any errors in developer console when the issue happens?

**Comment by amyblais** [comment]
We haven't received a response for a while so I'll close this for now - please reopen this issue if the problem persists.
