### ISSUE TITLE
Weirdness in Threads table, Participants column.

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#16320]
While trying to understand the db changes that came with MM 5.29.0 in order to update my [db+fs-cleaner](https://git.somenet.org/pub/jan/mattermost-privileged.git/blob/HEAD:/maintenance/db.py) I came across weird behavior in the `Threads` table.

Namely: When I post a thread and reply to said thread more than once, i get added to the participants list
![image](https://user-images.githubusercontent.com/5354356/99687520-09e5bc80-2a85-11eb-99a4-0e2983abae7d.png)

But when I delete one of my replies I am removed from the participants list.
![image](https://user-images.githubusercontent.com/5354356/99687659-339ee380-2a85-11eb-9361-3b3e2bfb8405.png)

#### Steps to reproduce
+ Post a thread starting post.
+ Reply twice.
+ Delete any of your reply posts.

#### Expected behavior
To stay in the participants list as long as I have at least one reply in the thread.

#### Observed behavior (that appears unintentional) 
I got removed from the participants in a thread while i still have posts in said thread.

#### Possible fixes
It is obviously really early in development of the new threads (I cant await them!)
But it looks like unexpected behavior to me, so I better reported it.
+ Not sure, if it would not be better to use indexes on the posts table instead of creating this list in a column...

**Comment by amyblais** [comment]
@reflog Is this and https://github.com/mattermost/mattermost-server/issues/16321 known issues?

**Comment by someone-somenet-org** [comment]
<nitpicking>
Also tablename `Threadmemberships` is inconsistent with other membership tables. ;)
+ `teammembers`
+ `channelmembers`
+ `groupmembers`
+ And then there is `threadmemberships`.
</nitpick>

**Comment by reflog** [comment]
@someone-somenet-org thanks for reporting this, it's indeed a bug!
Fixed in https://github.com/mattermost/mattermost-server/pull/16353

**Comment by amyblais** [comment]
Closing as this was fixed in v5.29.1,
