### ISSUE TITLE
editing /me post behaves diffrently in Webapp and Android-App.

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#16327]
Using `/me text1` and editing the resulting post (to `text2`) shows diffrent text in Webapp and Android-App.

While the Webapp seems to display the prop `"message"` (=`text1`) the Android app displays the posts message-text (=`text2`).

MM 5.29.0
Android-App 1.37.0 (Please sync the version numbers across all apps!)

#### Steps to reproduce
+ `/me text1`
+ edit post to `*text2*`
+ Webapp now shows `text1` - while Android-App shows `text2`.

#### Expected behavior
+ Be able to edit my own messages. (why allow editing of all shash-command results, except for `/me`?)
+ See the same text in all applications.

#### Observed behavior (that appears unintentional) 
Webapp
![image](https://user-images.githubusercontent.com/5354356/99735250-91065500-2ac4-11eb-8172-703fa705eb12.png)

Android
![IMG_20201120_000940](https://user-images.githubusercontent.com/5354356/99735445-ea6e8400-2ac4-11eb-922e-ef10b6df04e2.jpg)

DB
![image](https://user-images.githubusercontent.com/5354356/99735537-0e31ca00-2ac5-11eb-9cd7-8b1a00847c36.png)

#### Possible fixes
Get rid of the property "message". Also possibly remove the post-type "me" - What is its usecase anyway?

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-30810

**Comment by amyblais** [comment]
Scheduled for v5.32 (February 16th) release
