### ISSUE TITLE
Post edits and deletes propagate inconsistently.

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#16339]
When editing a post while the andoid-app is offline (airplane mode) and said phone+app comes online again edits get propagated and the cached posts get updated.

Deleting posts will not propagate to the Android app, if it is offline at the time of post-deletion.

If you edit a post and then delete it, while the Android app is offline, the edit nor the deletion will get propagated after the app comes online again.

#### Steps to reproduce
+ Android-App: Be online. Remeber/read a post.
+ Set phone to airplane mode.
+ Edit post from other app/webapp.
+ Come online with Android-App again.

-> post is updated. (good!)

+ Android-App: Be online. Remeber/read a post.
+ Set phone to airplane mode.
+ Delete post from other app/webapp.
+ Come online with Android-App again.

-> post stays visible. (bad!)

+ Android-App: Be online. Remeber/read a post.
+ Set phone to airplane mode.
+ Edit post from other app/webapp.
+ Delete post from other app/webapp.
+ Come online with Android-App again.

-> post is not updated and the original, un-edited version stays visible. (bad!)

#### Expected behavior
Edits + Deletes to propagate equally.

#### Observed behavior (that appears unintentional) 
Deleted posts are ignored while fetching of changes since last view, leading to them not disappearing or updating if they were edited before they were deleted while the Android-App was offline.

#### Possible fixes
Fetching deleted messages should somehow indicate that they were deleted and the Android app should remove these cached posts as it does when posts are updated.

**Comment by amyblais** [comment]
Thanks, opened a ticket https://mattermost.atlassian.net/browse/MM-30857

**Comment by amyblais** [comment]
Closing as this is fixed for upcoming Mobile app v1.38 release (December 16th release),
