### ISSUE TITLE
Change receiver name for (me *TestHelper) in app/helper_test.go to be more idiomatic

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#16337]
The Mattermost codebase has a lot of methods with receiver names as `me`. This is a carry-over from other Object Oriented languages and not idiomatic Go as pointed out <here>(https://github.com/golang/go/wiki/CodeReviewComments#receiver-names).

This ticket is about changing the receiver name from `me` to something more suitable for `(me *TestHelper)` in `app/helper_test.go`.

Example Pull Request: #16298

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-30825

**Comment by CandyZack** [comment]
@agnivade  can I pick this and related issues together?

**Comment by agnivade** [comment]
Sure, you want me to assign all of them to you?

**Comment by CandyZack** [comment]
yup, will do that in a single PR

**Comment by agnivade** [comment]
Since these structs spread out across multiple packages and files, a single PR might get too big to review properly. I also have a couple more issues after this. It might be simpler to keep them small and isolated to a single struct. You are obviously most welcome to send all PRs at once. :)

Let me assign all of them to you. Thanks for your time @CandyZack.
