### ISSUE TITLE
Broken links on https://mattermost.com/superstars/

### ISSUE THREAD

**Issue by darkLord19** [mattermost/mattermost-server#16352]
href are pointing to broken links which results in 404 returns.

For example,
Become a Mattermost contributor today href link is pointing to https://mattermost.com/superstars/"https://mattermost.com/contribute/" which is wrong and should point to https://mattermost.com/contribute/ instead.

**Comment by darkLord19** [comment]
@jasonblais is this the correct place to create issues for mattermost website? I wasn't able to find repo for mattermost website. Assuming it is not open sourced, opening issue here.

**Comment by jasonblais** [comment]
@darkLord19 Thank you for noticing! This is now be resolved, thanks for letting us know. 

Reporting here is fine, since the website contents aren't in a GitHub repository :+1:
