### ISSUE TITLE
while integrating the outlook calendar, its not showing the calendar in the dropdown

### ISSUE THREAD

**Issue by AswaniGajraj** [mattermost/mattermost-server#16380]
#### Summary
while integrating the outlook calendar, it's not showing the calendar in the dropdown

#### Steps to reproduce
1. Connect outlook calendar.
2. Enter the credentials
3. In the next screen the dropdown is coming blank. but selecting the blank value is working.

#### Expected behavior
It should show the calendar name

**Comment by amyblais** [comment]
@AswaniGajraj Is this https://github.com/mattermost/mattermost-plugin-mscalendar the plugin are you using? Would you be open to re-opening these issues in that plugin's Github repository (if there is an availability to open issues there)?
