### ISSUE TITLE
Remove model.AppError from store/storetest package

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#16419]
We are in the process of removing `model.AppError` completely from the `store` package. We have removed it from the `sqlstore` package, but there are still a couple left in some other packages under `store`.

This ticket is about removing `model.AppError` from the storetest package.

These are some remnants remaining from the AppError migration. We need to remove all the `model.AppError` occurences and change any code that's needed for the tests to still pass.

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by msal4** [comment]
I'll work on this one after all three previous issues are resolved

**Comment by agnivade** [comment]
Hey @msal4 - how is it going with this one? :) Anything that we can do to help you with?

**Comment by mahmud2011** [comment]
In case it's still up for grabs assign me.

**Comment by agnivade** [comment]
Ah sorry @mahmud2011, this issue isn't valid  anymore as we concluded that there wasn't anything to be done.
