### ISSUE TITLE
Change the text of the ephemeral message from "You can only show..." to "You can only see..." 

### ISSUE THREAD

**Issue by haardikdharma10** [mattermost/mattermost-server#16423]
Help contribute to the [Incident Management Plugin](https://github.com/mattermost/mattermost-plugin-incident-management)!

Today, running `/incident commander [@username] `from within a non-incident channel shows the following message:

`You can only show the commander from within the incident's channel.`

Let’s change this to:

`You can only see the commander from within the incident's channel.`

Similar issue: #16400

**Comment by haardikdharma10** [comment]
cc: @lieut-data

**Comment by lieut-data** [comment]
Hi @haardikdharma10! Did you mean to create a clone of the https://github.com/mattermost/mattermost-server/issues/16400 issue?

**Comment by haardikdharma10** [comment]
Haha, no worries. Can I go ahead and fix this?

**Comment by lieut-data** [comment]
Yes, please!

**Comment by lieut-data** [comment]
Thanks again, @haardikdharma10 :)
