### ISSUE TITLE
iOS MM Classic: cannot return to main menu after opened a gif from a message

### ISSUE THREAD

**Issue by dimgord** [mattermost/mattermost-server#16500]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Cannot return to main menu/view after opened a gif from a message in iOS Mattermost Classic application 

#### Steps to reproduce
iOS Mattermost Classic

Mattermost Enterprise Edition

Modern communication from behind your firewall.

Mattermost Version: 5.26.2
Database Schema Version: 5.26.0
Database: postgres

Click on a gif preview image in a message (not the link!).  Click Open button.

#### Expected behavior
I would suggest something like Close or Back button in the view.

#### Observed behavior (that appears unintentional) 

Click on a gif preview image in a message (not the link!) and observe modal dialog with Open button.  Click Open and observe a single view with the image in it.  The only possible action now is to select it and copy - no return point from the view to main Mattermost view.
![A8EE2AAE-9538-44B4-BB6D-E3C4C4AAFC5E](https://user-images.githubusercontent.com/24552509/101206261-e4d47a80-363c-11eb-9f87-8087ceaad304.jpeg)
![9D89089B-51E9-43AC-B9E9-5EE499799014](https://user-images.githubusercontent.com/24552509/101206263-e4d47a80-363c-11eb-84c5-62ab01bcb4a1.png)

**Comment by amyblais** [comment]
@dimgord I'll test this - one question: is there a reason you prefer the classic app over the newer app https://play.google.com/store/apps/details?id=com.mattermost.rn&hl=en?

**Comment by dimgord** [comment]
@amyblais sorry for delay, missed your comment.  Business app eats up my ios battery, usage - > 70% daily :/

**Comment by amyblais** [comment]
@dimgord 

> Business app eats up my ios battery, usage - > 70% daily :/

Would you consider upgrading your server version to a more recent version to see if it helps with using the Business app? You could optionally do some testing on our [community server](https://community.mattermost.com/core/channels/release-checklist) which is on the latest version.

As for the bug report, are you able to swipe to get out of the preview screen?

**Comment by dimgord** [comment]
@amyblais 

> As for the bug report, are you able to swipe to get out of the preview screen?

Swipe doesn't work, in any directions :) Just checked

> Would you consider upgrading your server version to a more recent version to see if it helps with using the Business app? 

It is our company server, I will try to contact them and ask to upgrade

> You could optionally do some testing on our community server which is on the latest version.

How do I do it on my iPhone?

Thank you,
Dmitry

**Comment by amyblais** [comment]
I believe a fix for this was released some time ago, but please re-open this if the issue still persists,
