### ISSUE TITLE
SMTP PLAIN AUTH doesn't work with localhost

### ISSUE THREAD

**Issue by frezbo** [mattermost/mattermost-server#16540]
#### Summary

SMTP `PLAIN AUTH` doesn't work with host being `localhost`

#### Steps to reproduce

Mattermost server code at https://github.com/mattermost/mattermost-server/blob/master/services/mailservice/mail.go#L75 adds the port address to the `smtp.PlainAuth` method, whereas I think `smtp.PlainAuth` only expects the hostname.

From [Go Doc](https://golang.org/pkg/net/smtp/#PlainAuth):

```
PlainAuth will only send the credentials if the connection is using TLS or is connected to localhost. Otherwise authentication will fail with an error, without sending the credentials.
```

I've written a sample go code to demonstrate the behavior

##### Example 1

```go
package main

import (
	"net/smtp"
	"testing"
)

func TestSMTP(t *testing.T) {
	auth := smtp.PlainAuth("", "user", "<redacted>", "localhost:1025")
	to := []string{"<redacted>"}
	msg := []byte("To: <redacted>\r\n" +
		"From: <redacted>\r\n" +
		"Subject: Hi!\r\n" +
		"\r\n" +
		"Testing hydroxide.\r\n")
	err := smtp.SendMail("localhost:1025", auth, "<redacted>", to, msg)
	if err != nil {
		t.Logf("Testing %s", err)
	}
}
```

SMTP logs

```bash
220 localhost ESMTP Service Ready
EHLO localhost
250-Hello localhost
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250 AUTH PLAIN
QUIT
221 2.0.0 Goodnight and good luck
```

with the `port` provided in the `smtp.PlainAuth` method the Go client closes the connection as specified in the docs

##### Example 2

```go
package main

import (
	"net/smtp"
	"testing"
)

func TestSMTP(t *testing.T) {
	auth := smtp.PlainAuth("", "user", "<redacted>", "localhost")
	to := []string{"<redacted>"}
	msg := []byte("To: <redacted>\r\n" +
		"From: <redacted>\r\n" +
		"Subject: Hi!\r\n" +
		"\r\n" +
		"Testing hydroxide.\r\n")
	err := smtp.SendMail("localhost:1025", auth, "<redacted>", to, msg)
	if err != nil {
		t.Logf("Testing %s", err)
	}
}
```

SMTP logs

```bash
220 localhost ESMTP Service Ready
EHLO localhost
250-Hello localhost
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250 AUTH PLAIN
AUTH PLAIN <redacted>
235 2.0.0 Authentication succeeded
<removed since its not relevant>
```

With the port removed from `smtp.PlainAuth` email sending works.

#### Expected behavior

SMTP Plain Auth works with localhost

#### Observed behavior (that appears unintentional)

The Connection to the server is closed with an un-authenticated message

#### Possible fixes

Remove the server port from here: https://github.com/mattermost/mattermost-server/blob/master/services/mailservice/mail.go#L75

I think this issue also links to an old closed issue here https://github.com/mattermost/mattermost-server/issues/5493

I'm ready to put in a pull request if the analysis is correct. Waiting for response from maintainers.

**Comment by frezbo** [comment]
Any maintainers can help me out here? Thanks

**Comment by amyblais** [comment]
@frezbo Would you be open to posting this on our troubleshooting forum here: https://forum.mattermost.org/? Our support team is more active there and may be able to help determine what the solution could be here. I've asked our dev team to take a look at this a couple times but I haven't received feedback.

**Comment by bbodenmiller** [comment]
@frezbo maybe try `127.0.0.1` rather than `localhost`?

**Comment by frezbo** [comment]
@bbodenmiller I just tried it and using `127.0.0.1` also doesn't work, since the port number is passed to the `smtp.PlainAuth` method
