### ISSUE TITLE
Issue with transparency in webapp

### ISSUE THREAD

**Issue by darkLord19** [mattermost/mattermost-server#16544]
When we open sidebar menu after scrolling sidebar, then scroll bar is overlapping over the sidebar menu.
<img width="1440" alt="Screenshot 2020-12-12 at 11 11 45 PM" src="https://user-images.githubusercontent.com/16662014/102090609-aceee380-3e43-11eb-9912-e71f308448ba.png">

**Comment by amyblais** [comment]
@darkLord19 

1. What OS and version is the Mattermost server installed?
2. What is your Mattermost server version?
3. Are you experiencing the issues with the browser webapp, if so which one?
4. Can you send a snippet of the Mattermost server logs around the time of the incident?

**Comment by darkLord19** [comment]
@amyblais issue is seen on community server so I think you'd know more about OS and  version. I looked in About Mattermost and found following info,
```
Mattermost Version: ee_live_bb43e5c00b7fa42169eb45f7b4e38c1118c7e575_9f16e221b12b6ca8d70957100796465d1b64cfc2_543
Database Schema Version: 5.30.0
Database: mysql

Build Hash: bb43e5c00b7fa42169eb45f7b4e38c1118c7e575
EE Build Hash: 9f16e221b12b6ca8d70957100796465d1b64cfc2
Webapp Build Hash: 8f10cbd13975b830101518e4eef5240c41277f92

Build Date: Wed Dec 9 15:03:05 UTC 2020
```
I am not sure what do you mean by browser webapp. I was accessing community server using Firefox.

**Comment by amyblais** [comment]
For some reason I can't reproduce this on community.mattermost.com on Firefox. Are there any additional details you can provide before I open a ticket? E.g.
1. Does this reproduce consistently?
2. Does this reproduce for you locally or on any servers you host?
3. Is your zoom level at 100%?

**Comment by darkLord19** [comment]
1) Yes I can reproduce consistently.
2) Haven't tried.
3) yes my zoom level is at 100%
Another detail of any significance will be the OS which is MacOS in my case.

Attaching gif of issue in action.
![out1](https://user-images.githubusercontent.com/16662014/102115915-36ada980-3e62-11eb-82cc-f2fba1511643.gif)

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-31345.

**Comment by hmhealey** [comment]
@darkLord19 Does that issue still reproduce on community? I'm not seeing that issue myself, but we're on a newer build on community now

**Comment by darkLord19** [comment]
I am still seeing it in sidebar menu

**Comment by darkLord19** [comment]
![ezgif-5-e191d8603a46](https://user-images.githubusercontent.com/16662014/123311621-00ee2980-d545-11eb-83fd-5b0d87f9ed69.gif)

**Comment by hmhealey** [comment]
Thanks for the update. This'll have to be something that gets fixed when the menu components are rewritten. The way they're structured right now and where they're located in the DOM makes this virtually impossible to fix. They need to be rendered outside the sidebar to get above the scroll bar.
