### ISSUE TITLE
EnableUploads set to true in config.json but uploads blocked in System Console

### ISSUE THREAD

**Issue by moniquemurphy** [mattermost/mattermost-server#16570]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
EnableUploads is set to `true` in `config.json` but the buttons to Choose File/Upload are disabled in System Console.

#### Steps to reproduce
Using version 5.29.0. Edit `config.json` to set `"EnableUploads": true`. Run `bin/mattermost config validate` to ensure config file is valid. Restart mattermost server with `sudo systemctl restart mattermost`. Exit out of Mattermost desktop client for OS X and reopen. Go to System Console --> Plugin Management, try to click on Choose File/Upload (cursor has "no" symbol). 

#### Expected behavior
Expected System Console to allow uploads after change to config.json and server restart.

#### Observed behavior (that appears unintentional) 
![Screen Shot 2020-12-16 at 11 37 19 AM](https://user-images.githubusercontent.com/13872721/102385107-0fa2c500-3f93-11eb-8d7d-d133428c35e8.png)
Buttons to upload are disabled.

#### Additional info
I also edited `ExperimentalChannelSidebarOrganization` in `config.json` at the same time and set that to `always_on`. When I saved and restarted the server, those options appeared as expected in the desktop client, so I am confident the `config.json` changes were picked up properly in general.

**Comment by amyblais** [comment]
@moniquemurphy Have you tried with ``Require Plugin Signature:`` set to ``false``? Based on the help text for the setting: "When true, uploading plugins is disabled and may only be installed through the Marketplace."

**Comment by moniquemurphy** [comment]
@amyblais Thank you, that fixed the issue!
