### ISSUE TITLE
mattermost-webapp missing v5.30.0 and v5.30.1 tags

### ISSUE THREAD

**Issue by PokeMMO** [mattermost/mattermost-server#16582]
#### Summary
mattermost-webapp missing v5.30.0 and v5.30.1 tags

#### Steps to reproduce
https://github.com/mattermost/mattermost-webapp/tree/v5.30.0
https://github.com/mattermost/mattermost-webapp/tree/v5.30.1

#### Expected behavior
Tag should exist

#### Observed behavior (that appears unintentional) 
There are usually matching tags in the mattermost-webapp repository.

#### Possible fixes
Create and push tags

**Comment by amyblais** [comment]
@metanerd / @jaydeland FYI

**Comment by metanerd** [comment]
Thank you for the report @PokeMMO ! This should be resolved now. It really was unintentional.
