### ISSUE TITLE
Create a govet check to check for idiomatic empty string comparisons

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#16596]
### Background

The Mattermost codebase has a weird anti-pattern of checking empty strings by doing `len(s) != 0` or `len(s) == 0`. They should just be `s != ""` or `s == ""`.  https://github.com/mattermost/mattermost-server/commit/6487d0ca91c66cfe292301585901ac5f84f776e5 does an initial pass of fixing some of these, but it's manually done and obviously there are still issues remaining in the codebase.

This ticket is about creating a new go vet analyzer pass to automatically flag these occurences.

### Implementation

The objective would be to create a new analyzer pass to https://github.com/mattermost/mattermost-govet which checks for code patterns like `len(s) != 0` or `len(s) == 0` and flags them.

After that, we would need to fix all of those occurences and finally enable the pass in CI.

Please feel free to reach out to `agniva.de.sarker` on community.mattermost.com if you have any questions.

**Comment by darkLord19** [comment]
I'd like to work on this

**Comment by agnivade** [comment]
Awesome!
