### ISSUE TITLE
Improve import process performance by streaming archive contents

### ISSUE THREAD

**Issue by streamer45** [mattermost/mattermost-server#16617]
### Introduction

The [import process job](https://github.com/mattermost/mattermost-server/blob/40e16ba07f08102bcf92b263fa885677c223ad4c/jobs/import_process/worker.go#L83) is used to automatically load pre-existing data into a Mattermost server.
This currently works by extracting the whole input archive (.zip) file and then feeding the included `import.jsonl` plus a path to the extracted files to the [`App.BulkImportWithPath()`](https://github.com/mattermost/mattermost-server/blob/40e16ba07f08102bcf92b263fa885677c223ad4c/app/import.go#L125) function. 
The current approach is not optimal since it requires extracting the whole content of the import archive in a temporary directory before doing any processing. Doing this could be unfeasible for very large import files. 

### Description

A better approach would be to make use of the zip contents by streaming them directly from the archive file to where needed by the import process. 
This can be achieved through the use of readers and writers but needs some modification to the `App.BulkImport()` logic.

Where to look to get started:

- https://golang.org/pkg/archive/zip - standard library zip file handling API
- https://github.com/mattermost/mattermost-server/blob/master/jobs/import_process/worker.go - import job
- https://github.com/mattermost/mattermost-server/blob/master/app/import.go - import process

### Need help?

If you have questions about the ticket or you need any help, feel free to post your question in [~Developers: Server](https://community.mattermost.com/core/channels/developers-server) or contact `claudio.costa` in https://community.mattermost.com/

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-31612

**Comment by antwigambrah** [comment]
I would love to work on it

**Comment by streamer45** [comment]
@antwigambrah 
Sounds great :+1: Let us know if you need any help :)

**Comment by streamer45** [comment]
@antwigambrah

How's everything going with this?

**Comment by antwigambrah** [comment]
@streamer45 Closed a DB issue a while back .  Getting back to it

**Comment by gigawhitlocks** [comment]
This has become higher priority as it relates to my work, @streamer45 @antwigambrah would you mind if I took this over?

**Comment by antwigambrah** [comment]
@gigawhitlocks Yes

**Comment by streamer45** [comment]
@antwigambrah 

Just to confirm. Are you okay with this issue being handled by @gigawhitlocks or did you already have an implementation ready to share?

**Comment by antwigambrah** [comment]
@streamer45 I was working on an implementation but had to pause . He can work on it .

**Comment by streamer45** [comment]
Sounds good. Thanks :+1:

**Comment by gigawhitlocks** [comment]
Thanks!

**Comment by gigawhitlocks** [comment]
I just noticed that this issue is closed. This should be resolved, now, with the merging of #17659 . Mind if I close it?

**Comment by streamer45** [comment]
> I just noticed that this issue is still open. This should be resolved, now, with the merging of #17659 . Mind if I close it?

Go ahead and thanks for the great effort there :+1:
