### ISSUE TITLE
Syntax-highlited quote shows the type of syntax over the text

### ISSUE THREAD

**Issue by OndrejGl** [mattermost/mattermost-server#16647]
#### Summary
Syntax-highlited quote shows a box with type of syntax over the quoted text, when the text is over the whole width of the text window.

#### Steps to reproduce
Send message as:
\``` bash
for f in $(find /mnt/scratch03/tmp/yyyyyyyy/voxceleb2020/v2_dur600_fbank64_v3/egs/voxceleb2_dev_orig_with_aug_no_sil.TRN -name "egs.*.ark"); do x=$( (LD_LIBRARY_PATH=/mnt/matylda4/yyyyyyyyyyyy/usr/cuda-10.1/lib64 /mnt/matylda4/yyyyyyyyy/tmp/horovod/train.voxceleb_paja01.fbank64augOK.ResNet152.fmargin03.v04.warmup10.3gpus.64x2.1ep.dir/ResNet152_add_margin_embed256_3gpu/nnet3-copy-egs-to-feats  ark:$f   ark:/dev/null   2>&1 )| grep LOG | sed "s@.*Converted \(.*\) neural-network.*@\1@") ; echo "$f $x"; done
\```

Then try to copy the text in the sent message from the begining to the end, or one character before the end.

#### Observed behavior (that appears unintentional) 
Little box describing the type of syntax (in the example above it displays "Bash") covers part of the text.  This is bothersome if one wants to select text that is covered by the box (e.g. from the begining to the end of the line, or couple of characters before the end).

#### Possible fixes
Display the box with the syntax type elsewhere or make it disappear when the cursor hovers over it.

**Comment by OndrejGl** [comment]
Screenshot:
<img width="651" alt="Screen Shot 2021-01-08 at 15 12 00" src="https://user-images.githubusercontent.com/62648721/104052361-e53ad500-51e9-11eb-811f-4f159e88a613.png">

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-31872

**Comment by hmhealey** [comment]
Closing this since we now have a good workaround for this with the Copy Code Block button that was added
