### ISSUE TITLE
Easier method for allowing admins to include custom themes

### ISSUE THREAD

**Issue by mthaddon** [mattermost/mattermost-server#16658]
#### Summary
This is a feature request for an easier method for admins to include custom themes.

#### Steps to reproduce
Currently deploying a Mattermost instance with custom themes (for instance, company-branded colours) requires manually patching https://github.com/mattermost/mattermost-webapp. 

#### Expected behavior
Admins should be able to deploy Mattermost and specify custom themes in place of the existing ones (or an addition to the existing ones) without having to patch mattermost-webapp. This could be done in a number of ways (e.g. configuration or being stored in the database), but should persist across version upgrades.

Additionally it would be ideal if admins could specify the default theme for users, as well as having full control over the list of themes available.

#### Observed behavior (that appears unintentional) 
Currently we patch mattermost-webapp, making changes to `components/admin_console/admin_definition.jsx`, `utils/constants.jsx` and including custom images in `images/themes` that we reference in the changes we've made to `utils/constants.jsx`.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @mthaddon,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by mthaddon** [comment]
I've posted this as https://mattermost.uservoice.com/forums/306457-general/suggestions/42401788-easier-method-for-allowing-admins-to-include-custo.

**Comment by amyblais** [comment]
Awesome, thank you!
