### ISSUE TITLE
Android App v1.38.1 doesn't call /api/v4/users/sessions/device

### ISSUE THREAD

**Issue by PokeMMO** [mattermost/mattermost-server#16676]
#### Summary

Android app v1.38.1 does not register device.

#### Steps to reproduce

Logging into a server with the v1.38.1 Android does not receive push notifications, but the "Test Push" notification button works.
I am using Gitlab as SSO, and am not sure if this is relevant.

#### Expected behavior

The android app should call `/api/v4/users/sessions/device` and start receiving push notifications.

#### Observed behavior (that appears unintentional) 

Under Account Settings->Security->Sessions it shows as "Android" instead of the expected "Android Native App"
![image](https://user-images.githubusercontent.com/2398581/104302973-6089d880-54c1-11eb-8fdf-693294c344b0.png)

Downgrading to v1.36.0 correctly calls `/api/v4/users/sessions/device` after signin. (I could not find a v1.37.0 to verify with)

#### Possible fixes

Have not looked that far.

**Comment by amyblais** [comment]
Thank you, we have submitted a fix for this https://github.com/mattermost/mattermost-mobile/pull/5104 and are currently testing it for the next mobile app release,
