### ISSUE TITLE
Unknown column 'UnreadMentions'

### ISSUE THREAD

**Issue by tsipizic** [mattermost/mattermost-server#16678]
#### Summary
We are getting the error
"Error 1054: Unknown column 'UnreadMentions' in 'field list'"
in the logs. Upon inspection in the database the ThreadMemberships table does not contain this column although it was supposed to be added in version 5.29.1. We are now running version 5.30.1 and the problem still persists. The database schema version is at 5.30.0.
#### Steps to reproduce
We updated from 5.29 to 5.29.1 and then 5.30.1

**Comment by amyblais** [comment]
@reflog Would you know what the issue might be?

**Comment by reflog** [comment]
@amyblais there appears to be a problem with merge on upgrade.go that caused the new column not to be added.
I'll prepare the PR, but can you advise where should it be cherry picked?

**Comment by amyblais** [comment]
This was fixed in v5.31 and v5.30.x / v5.29.x backports,
