### ISSUE TITLE
No close/back button in permanent link media preview

### ISSUE THREAD

**Issue by matthiss** [mattermost/mattermost-server#16703]
#### Summary
No "close" or "back" button when viewing photos or videos shared as public links.

#### Steps to reproduce
Mattermost version 4.5.4
Mattermost Version: 5.29.1
Database Schema Version: 5.29.0
Database: postgres

1. share photo in chat
2. click photo to preview -> X for closing appears in upper right corner
![mattermost_correct_preview](https://user-images.githubusercontent.com/10980315/104730215-ec0d9e80-5739-11eb-9cee-31dee81dc9fd.png)
3. click "get public link"
4. post link in chat
5. click public link -> preview opens
6. Image Preview can't be closed by "X" or "back" button
![mattermost_bad_preview](https://user-images.githubusercontent.com/10980315/104730261-00519b80-573a-11eb-91a5-b3e287701819.png)

#### Possible fixes
Only way to get back is by clicking the Menu > History > Back
A button should be implemented for one-click-solution

**Comment by amyblais** [comment]
Opened a ticket https://mattermost.atlassian.net/browse/MM-32039

**Comment by amyblais** [comment]
@matthiss Would you be able to share details on what OS and version you're on? Are you using the mobile browser view?

**Comment by matthiss** [comment]
I'm using Ubuntu 20.04 using the standalone client. Reproduced this issue on several machines.

**Comment by amyblais** [comment]
@matthiss I've had trouble reproducing this, would you have a sample file for me to test with? Is this happening with 100% screen resolution?

**Comment by amyblais** [comment]
Queued for next desktop app release, v4.7.
