### ISSUE TITLE
editing a message to one with a command does not behave correctly

### ISSUE THREAD

**Issue by merlin8282** [mattermost/mattermost-server#16754]
#### Summary
When a message has been sent, editing it to change it to a message with a "command" (like /me) does not execute that command but simply print it.

#### Steps to reproduce
Example:
1st message: " /me maybe found bugz" (notice the trailing whitespace)
Edited message: "/me maybe found bugz"

#### Expected behavior
print "maybe found bugz" as a /me message

#### Observed behavior (that appears unintentional) 
printed is "/me maybe found bugz"

#### Possible fixes
idk

**Comment by amyblais** [comment]
We have this fix https://mattermost.atlassian.net/browse/MM-30810 (also same as https://github.com/mattermost/mattermost-server/issues/16327) queued for the next release, does this seem like the same issue?
