### ISSUE TITLE
can not access localhost:8065 on windows version.

### ISSUE THREAD

**Issue by beanhacker** [mattermost/mattermost-server#16762]
hi,
   i compiled windows version of mattermost server, and add config file as config.json in attachment.
   then i run the server, err.log in attachment also.

[err.log](https://github.com/mattermost/mattermost-server/files/5840608/err.log)

[config.zip](https://github.com/mattermost/mattermost-server/files/5840614/config.zip)

**Comment by amyblais** [comment]
@beanhacker Would you be open to posting this on our troubleshooting forum here: https://forum.mattermost.org/? Our support team is more active there and can help determine what the cause of the issue is.
