### ISSUE TITLE
Demo server is down

### ISSUE THREAD

**Issue by vn971** [mattermost/mattermost-server#16764]
In the main README of this project, there is a section called "Try out Mattermost": https://github.com/mattermost/mattermost-server/#try-out-mattermost

The Demo server linked there is down. Is it known? Is it expected?

Thanks

**Comment by amyblais** [comment]
I'm unsure but it looks like it's no longer in service. I've opened a PR for our team to review.

**Comment by vn971** [comment]
If I click on the first link BTW, I get this:

> :warning: The invite link was invalid. Please speak with your Administrator to receive an invitation.

Is that expected? I know it's unrelated, I'm just a bit confused

**Comment by amyblais** [comment]
Thanks, I'll fix it with the above PR.

**Comment by amyblais** [comment]
Fixed now,
