### ISSUE TITLE
Can't delete a team using mmctl in Mattermost Cloud

### ISSUE THREAD

**Issue by innovaciones** [mattermost/mattermost-server#16804]
#### Summary
Can't delete a team using mmctl, I get this error message: "Unable to delete team 'my-team-name' error: : Permanent team deletion feature is not enabled. Please contact your System Administrator."

#### Steps to reproduce
From the command line:
mmctl team delete my-team-name --confirm

#### Expected behavior
It should delete the team

#### Observed behavior (that appears unintentional) 
I'm also getting this error message: "WARNING: server version 5.30.0.cloud-tag.69900bf9f453ab9d33f8d5540d99c857.true doesn't match mmctl version 5.31.0"

#### Possible fixes
Could be a permission restriction on Mattermost Cloud

**Comment by ahmaddanialmohd** [comment]
Hello, @innovaciones 

Just attempted this on my end and verified that it is reproducible:

```
Ahmad-Danials-MacBook-Pro:~ ahmaddanial$ mmctl team delete whatmattermost --confirm
Unable to delete team 'whatmattermost' error: : Permanent team deletion feature is not enabled. Please contact your System Administrator.,
```

While I did not get the same WARNING message as yours, I can see the different version that we have here.

```
Ahmad-Danials-MacBook-Pro:~ ahmaddanial$ mmctl version
mmctl v5.30.0 -- 689bd041b5aa02183721fda0c4e9a4e3d84fab15
```

Getting in touch with the Cloud team to verify what missing feature that needs to be enabled. Keep you posted.

**Comment by ahmaddanialmohd** [comment]
Hi, @innovaciones 

To further assist you with this matter, please raise a support ticket to support@mattermost.com and mention my name together with this github issue URL.

I will then further assist you with the issue that we are dealing with her. Thanks!

**Comment by innovaciones** [comment]
Hello Ahmad, I never got a response from support@mattermost.com after I sent my email, but nvm I finally found out a way to delete a team using mmctl, you need to set EnableAPITeamDeletion from config.json from false to true, here is the command to do it from mmctl:

mmctl config set ServiceSettings.EnableAPITeamDeletion true
mmctl team delete my-team-name --confirm

And now it works!

**Comment by ahmaddanialmohd** [comment]
Hi, @innovaciones 

Sorry for the initial radio silence but thanks again for sharing the solution. Responded to your ticket as well as it was already weekend on my side when it came in. 

Have a good day!
