### ISSUE TITLE
5.31.0 Some Values in config.json Were Replaced by ********************************

### ISSUE THREAD

**Issue by nevrending** [mattermost/mattermost-server#16817]
#### Summary
Running Mattermost 5.31.0 in Kubernetes setup
8 keys in config.json suddenly replaced by ********************************
They are:
- ServiceSettings.GfycatApiSecret
- ServiceSettings.SplitKey
- SqlSettings.DataSource
- SqlSettings.AtRestEncryptKey
- FileSettings.PublicLinkSalt
- EmailSettings.SMTPPassword
- ElasticsearchSettings.Password

#### Steps to reproduce
I'm not actually sure when and how this happened.
Mattermost container crashed and won't start.
Log said: `invalid DSN: missing the slash separating the database name`
Figured that the above keys values' have been replaced with ********************************

Fortunately I have backed up the config.json, so after restoring SqlSettings.DataSource, Mattermost runs again.
I tried setting EmailSettings.SMTPPassword from the System Console GUI and it was saved in plaintext in config.json.
So I figured that the values being replaced by ******************************** is not an intended behaviour.

#### Expected behavior
Config values are left intact.

**Comment by nevrending** [comment]
Was about to post the above to https://forum.mattermost.org/ but then

![image](https://user-images.githubusercontent.com/4745298/106156770-0f265c80-61d6-11eb-87cc-beb782c5da9d.png)

**Comment by streamer45** [comment]
Hi @nevrending ,

those asterisks are what we use when we sanitize a config. We essentially add them to remove sensitive information. 
What's strange however is that the config got written to disk as such.

Do you have any CLI commands running perhaps that could have triggered this?

**Comment by nevrending** [comment]
Hi @streamer45 ,
Thanks for your response and explanation.

I believe I don't. But I activated/use some experimental features, if that's relevant.

![image](https://user-images.githubusercontent.com/4745298/106230800-68c57000-6244-11eb-9a2a-133da5ecad7d.png)

**Comment by streamer45** [comment]
Hi @nevrending ,

any additional info on your installation can be relevant for sure.
Do you have any plugin enabled? If possible, can you share the `PluginSettings` section from your `config.json`?
Feel free to blank any sensitive information it might have.

**Comment by nevrending** [comment]
Sure @streamer45 , here it is.

```json
"PluginSettings": {
        "Enable": true,
        "EnableUploads": true,
        "AllowInsecureDownloadUrl": false,
        "EnableHealthCheck": true,
        "Directory": "./plugins",
        "ClientDirectory": "./client/plugins",
        "Plugins": {
            "antivirus": {
                "clamavhostport": "clamav.mattermost.svc.cluster.local:3310",
                "scantimeoutseconds": 10
            },
            "com.github.moussetc.mattermost.plugin.giphy": {
                "apikey": "<redacted>",
                "disablepostingwithoutpreview": true,
                "displaymode": "full_url",
                "language (giphy\u0026tenor only)": "en",
                "provider": "tenor",
                "rating": null,
                "rendition": "fixed_height_small",
                "renditiongfycat": "gif100px",
                "renditiontenor": "mediumgif"
            },
            "com.mattermost.welcomebot": {
                "WelcomeMessages": [
                    {
                        "Actions": [
                            {
                                "ActionType": "automatic",
                                "ChannelsAddedTo": [
                                    "<redacted>",
                                    "<redacted>"
                                ]
                            }
                        ],
                        "DelayInSeconds": 5,
                        "Message": [
                            "### <redacted> {{.UserDisplayName}} <redacted> {{.Team.DisplayName}}!",
                            "",
                            "<redacted> @<redacted>",
                            "",
                            "<redacted>"
                        ],
                        "TeamName": "<redacted>"
                    }
                ]
            }
        },
        "PluginStates": {
            "antivirus": {
                "Enable": true
            },
            "com.github.moussetc.mattermost.plugin.giphy": {
                "Enable": true
            },
            "com.mattermost.nps": {
                "Enable": false
            },
            "com.mattermost.plugin-channel-export": {
                "Enable": true
            },
            "com.mattermost.plugin-incident-management": {
                "Enable": false
            },
            "com.mattermost.welcomebot": {
                "Enable": true
            }
        },
        "EnableMarketplace": true,
        "EnableRemoteMarketplace": true,
        "AutomaticPrepackagedPlugins": true,
        "RequirePluginSignature": false,
        "MarketplaceUrl": "https://api.integrations.mattermost.com",
        "SignaturePublicKeyFiles": []
    },
```

**Comment by streamer45** [comment]
@nevrending 

It would help if you could provide the server logs before the crash.
Also, I will open a ticket to investigate this further. Please let us know if it were to happen again.

**Comment by streamer45** [comment]
Created https://mattermost.atlassian.net/browse/MM-32415

**Comment by nevrending** [comment]
@streamer45 
after checking out the issue link and read on the other 2 config related issues, I realised that I misunderstood your previous question.

I was having a difficulty to set the Welcome Message Bot Plugin's settings in `config.json` and then tried using `mmctl` to accomplish that. In the end I still didn't manage to put the settings in place, so mounted the volume on another container to modify `config.json`.

I have the `mmctl` logs here
```bash
brew update

brew install mmctl

mmctl auth

mmctl auth login

mmctl auth login https://<redacted>.<redacted>.<redacted> --name <redacted> --username <redacted> --password <redacted>

mmctl config get PluginSettings.Plugins --format json

mmctl config set PluginSettings.Plugins --format json {"antivirus":{"clamavhostport":"clamav.mattermost.svc.cluster.local:3310","scantimeoutseconds":10},"com.github.moussetc.mattermost.plugin.giphy":{"apikey":"<redacted>","disablepostingwithoutpreview":true,"displaymode":"full_url","language (giphy\u0026tenor only)":"en","provider":"tenor","rating":null,"rendition":"fixed_height_small","renditiongfycat":"gif100px","renditiontenor":"mediumgif"},"com.mattermost.welcomebot":{"WelcomeMessages":[{"TeamName":"<redacted>","DelayInSeconds":5,"Message":["### <redacted> {{.UserDisplayName}} <redacted> {{.Team.DisplayName}},"","<redacted> @<redacted>.","","<redacted>"],"Actions":[{"ActionType":"automatic","ChannelsAddedTo":["<redacted>","<redacted>"]}]}]}}

mmctl config set PluginSettings.Plugins --format json {\"antivirus\":{\"clamavhostport\":\"clamav.mattermost.svc.cluster.local:3310\",\"scantimeoutseconds\":10},\"com.github.moussetc.mattermost.plugin.giphy\":{\"apikey\":\"<redacted>\",\"disablepostingwithoutpreview\":true,\"displaymode\":\"full_url\",\"language (giphy\\u0026tenor only)\":\"en\",\"provider\":\"tenor\",\"rating\":null,\"rendition\":\"fixed_height_small\",\"renditiongfycat\":\"gif100px\",\"renditiontenor\":\"mediumgif\"},\"com.mattermost.welcomebot\":{\"WelcomeMessages\":[{\"TeamName\":\"<redacted>\",\"DelayInSeconds\":5,\"Message\":[\"### <redacted> {{.UserDisplayName}} <redacted> {{.Team.DisplayName}},\"\",\"<redacted> @<redacted>.\",\"\",\"<redacted>\"],\"Actions\":[{\"ActionType\":\"automatic\",\"ChannelsAddedTo\":[\"<redacted>\",\"<redacted>\"]}]}]}}

mmctl config set PluginSettings.Plugins -h

mmctl config get PluginSettings.Plugins --format json

export MMCTL='{"antivirus":{"clamavhostport":"clamav.mattermost.svc.cluster.local:3310","scantimeoutseconds":10},"com.github.moussetc.mattermost.plugin.giphy":{"apikey":"<redacted>","disablepostingwithoutpreview":true,"displaymode":"full_url","language (giphy\u0026tenor only)":"en","provider":"tenor","rating":null,"rendition":"fixed_height_small","renditiongfycat":"gif100px","renditiontenor":"mediumgif"},"com.mattermost.welcomebot":{"WelcomeMessages":[{"TeamName":"<redacted>","DelayInSeconds":5,"Message":["### <redacted> {{.UserDisplayName}} <redacted> {{.Team.DisplayName}},"","<redacted> @<redacted>.","","<redacted>"],"Actions":[{"ActionType":"automatic","ChannelsAddedTo":["<redacted>","<redacted>"]}]}]}}'

echo MMCTL

echo $MMCTL

mmctl config set PluginSettings.Plugins --format json $MMCTL

mmctl config show --format json
```

Regarding the crash log, I'll try to dig the servers for that.
But the Mattermost container crashed due to SqlSettings.DataSource 's value of `********************************`

**Comment by streamer45** [comment]
Thank you @nevrending , that's really valuable information. Just to understand further, did the issue occur right after those `mmctl` command executed? That's why it would be interesting to see the server logs, not cause of the crash itself which is expected but to see what could have triggered the config issue before that.

**Comment by amyblais** [comment]
I'll close this for now as it's an older issue, but feel free to re-open it if the issue persists on the latest version,
