### ISSUE TITLE
Categories dropdown must be scrollable and automatically positioned

### ISSUE THREAD

**Issue by andreasciamanna** [mattermost/mattermost-server#16811]
#### Summary

When adding a channel/user to a category, the selection is cropped if it's near the far bottom of the viewport.

#### Steps to reproduce

1. Have several exiting categories (the number depends on where you are using Mattermost, but it must be at least 4, as far as I can see).
2. Have a channel/user not already in a category, shown at the very bottom of the left sidebar.
3. Click the channel/user menu (vertical ellipsis).
4. Click on "Move to".

#### Expected behavior

1. Move the same channel/user around the middle of the sidebar.
2. Depending on the position, the number of categories, and the viewport height, you will see the full or at least a list with more options.

Full list:

![image](https://user-images.githubusercontent.com/181780/106124633-95518d00-615b-11eb-80a6-1fce9d8cc793.png)

Longer list, but still cropped:
![image](https://user-images.githubusercontent.com/181780/106124823-cd58d000-615b-11eb-91b9-2d1c30eb2705.png)

#### Observed behavior (that appears unintentional) 

You will see only the first 4+ category: the rest are hidden, and the selector is not scrollable.

![image](https://user-images.githubusercontent.com/181780/106124584-879c0780-615b-11eb-9f62-b8bb2baf7974.png)

#### Possible fixes

1. Position the list so that the block is always fully visible.
2. If the list is still too long, make the selection list scrollable.
3. (optional) Add a filter feature.

**Comment by amyblais** [comment]
@hmhealey @jgilliam17 Do you know if we already have a ticket for this or if we are planning to fix this either for GA or post-GA?

**Comment by hmhealey** [comment]
I'll see if we can open a separate ticket for this or if it'll have to be addressed with the menu component rewrite we have planned. The current system for doing this definitely has some limitations that we might not be able to address yet.

As a workaround, you can also drag and drop channels into those categories. If the category you want to move something to is nearer to the bottom of the list, hopefully it's close by drag and drop

**Comment by andreasciamanna** [comment]
> As a workaround, you can also drag and drop channels into those categories. If the category you want to move something to is nearer to the bottom of the list, hopefully it's close by drag and drop

It's what I've been doing: the last two screenshots show exactly that.

It's a bug with an easy to workaround. 
At least, for those who realise there is workaround :)

**Comment by hmhealey** [comment]
Unfortunately, this isn't something we're able to fix easily. It'll have to come when we redo the menu components in the coming months. I filed a ticket to make sure this case is addressed though:

https://mattermost.atlassian.net/browse/MM-32400

Thanks for the report!
