### ISSUE TITLE
make run-server command fails

### ISSUE THREAD

**Issue by girish17** [mattermost/mattermost-server#16826]
#### Summary
`sudo make run-server` command when executed  on Ubuntu 20.04 LTS fails despite having `go` [latest version](https://golang.org/dl/go1.15.7.linux-amd64.tar.gz) installed as mentioned in [developer-setup guidelines](https://developers.mattermost.com/contribute/server/developer-setup/).

#### Steps to reproduce
Follow the developer setup mentioned [here](https://developers.mattermost.com/contribute/server/developer-setup/) on Ubuntu 20.04 GNU/Linux LTS

#### Expected behavior
Should build the server and start it

#### Observed behavior (that appears unintentional) 
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
make: go: Command not found
MMCTL already exists in bin/mmctl not downloading a new version.
/bin/sh: 1: go: not found
/bin/sh: 1: go: not found
/bin/sh: 1: go: not found
/bin/sh: 1: [: -gt: unexpected operator
/bin/sh: 3: [: -lt: unexpected operator
/bin/sh: 6: [: -lt: unexpected operator
Starting docker containers
go run ./build/docker-compose-generator/main.go mysql postgres inbucket  minio | docker-compose -f docker-compose.makefile.yml -f /dev/stdin run --rm start_dependencies
/bin/sh: 1: go: not found
ERROR: Top level object in '/dev/stdin' needs to be an object not '<class 'NoneType'>'.
make: *** [Makefile:152: start-docker] Error 1

#### Possible fixes
Check the 'Makefile` and resolve the problem.

**Comment by haardikdharma10** [comment]
Hi @girish17, I believe your `docker-compose.yml` file might be empty or might have indent problems.

**Comment by girish17** [comment]
It is not empty and has no indent problems.  Below are the contents of
docker-compose.yml in the mattermost-server directory -

version: '2.4'
services:
  mysql:
    container_name: mattermost-mysql
    ports:
      - "3306:3306"
    extends:
        file: build/docker-compose.common.yml
        service: mysql
  postgres:
    container_name: mattermost-postgres
    ports:
      - "5432:5432"
    extends:
        file: build/docker-compose.common.yml
        service: postgres
  minio:
    container_name: mattermost-minio
    ports:
      - "9000:9000"
    extends:
        file: build/docker-compose.common.yml
        service: minio
  inbucket:
    container_name: mattermost-inbucket
    ports:
      - "10025:10025"
      - "10080:10080"
      - "10110:10110"
    extends:
        file: build/docker-compose.common.yml
        service: inbucket
  openldap:
    container_name: mattermost-openldap
    ports:
      - "389:389"
      - "636:636"
    extends:
        file: build/docker-compose.common.yml
        service: openldap
  elasticsearch:
    container_name: mattermost-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    extends:
        file: build/docker-compose.common.yml
        service: elasticsearch
  dejavu:
    container_name: mattermost-dejavu
    ports:
      - "1358:1358"
    extends:
        file: build/docker-compose.common.yml
        service: dejavu
  keycloak:
    container_name: mattermost-saml
    ports:
      - "8484:8080"
    extends:
        file: build/docker-compose.common.yml
        service: keycloak

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    networks:
      - mm-test
    depends_on:
      - mysql
      - postgres
      - minio
      - inbucket
      - openldap
      - elasticsearch
    command: postgres:5432 mysql:3306 minio:9000 inbucket:10080
openldap:389 elasticsearch:9200

networks:
  mm-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.254.0/24
          ip_range: 192.168.254.0/24

**Comment by isacikgoz** [comment]
This doesn't seem to be related with `docker-compose`. @girish17 what does `which go` and `go version` command print?

**Comment by girish17** [comment]
`which go` prints  `/usr/local/go/bin/go`

`go version` prints `go version go1.15.7 linux/amd64`

**Comment by agnivade** [comment]
The error is that your shell is unable to find the `go` binary in your $PATH. 

Most likely, that's because since you are running as root, the changes to the $PATH variable that you have made to your `.bash_profile` is not visible when the user is root, and therefore you are getting this error. The developer setup guide does not mention running the make commands under root.

If you prefer to keep running as root, you would need to login as root and fix all `$PATH` references and run the app as root. Otherwise, you can use a normal user and fix the other permission issues that led you to run as root in the first place.

**Comment by girish17** [comment]
Thanks @agnivade . That fixed it. I am currently running as root.  However, that does not work for a non-root user because docker requires root permission on my system to launch the containers. This could be fixed by altering docker related settings. 

If the [developer setup documentation](https://developers.mattermost.com/contribute/server/developer-setup/) is not user agnostic then, I think it would be more helpful.  The commands mentioned there could begin with either a '$' or '#' (login prompt) to indicate whether the command should be run as normal user or root user. This makes it easier to understand. Having said that, I find that it is really not an obligation to clarify this in the documentation.
