### ISSUE TITLE
{PATCH} is included in the version view.

### ISSUE THREAD

**Issue by ynott** [mattermost/mattermost-server#16830]
#### Summary
I have tried to display the version information of Mattermost Server using several version checking methods, but it contains the string `{PATCH}`.

##### 1. WebUI
1. Menu --> "About Mattermost"
![image](https://user-images.githubusercontent.com/2724312/106402326-56c61600-646c-11eb-8c32-381041db7967.png)
##### 1. mmctl command
```shell
mmctl system version
```

```shell
Server version 5.30.0.5.31.6{PATCH}.459172dc38493dd6abc3ba29d7e3dafb.false
```

This seems to be a mixture of the `DB Schema version` and the `Mattermost Version` notation.

##### 1. mattermost version

```
Version: 5.30.0
Build Number: 5.31.6{PATCH}
Build Date: Fri Jan 15 02:26:25 UTC 2021
Build Hash: 5c6f37ee6db78c8440145a27320baebdcc6e8311
Build Enterprise Ready: false
DB Version: 5.31.0
```

#### Expected behavior

{PATCH} is not included in the version notation

**Comment by agnivade** [comment]
The `{PATCH}` section was an error during the release process, and will be fixed in future versions. You can find more discussion on this here: https://community.mattermost.com/core/pl/zsuaan8su78p3qzsq1oapa8nqh.
