### ISSUE TITLE
Organize tags for mattermost-enterprise-edition container

### ISSUE THREAD

**Issue by b-a-t** [mattermost/mattermost-server#16845]
Being Enterprise Edition customer we found it sub-optimal that we have to rebuild Mattermost container for each release with mattermost/mattermost-docker.

Someone pointed us out to the https://hub.docker.com/r/mattermost/mattermost-enterprise-edition which states:

> This is the official Mattermost Docker image for the Mattermost Enterprise Edition.

"Hurrah, no more hassle! Let's pick the latest release tag and pull it to our server."

Well... There are literally thousands of hashed tags there, seems every CI/CD build pushes new image directly to the Hub. Not a problem by itself, although it's impossible to find anything in such a huge... collection.

By inverting the sort I've found that there are `release-5.2*` tags also available(Hurrah!), but the latest one ends at `5.29`.

Nothing was found by the `v5.` filter either.

Update: Trying `5.30` as a filter revealed tags for newer releases. Great, something to work with!

#### Summary
https://hub.docker.com/r/mattermost/mattermost-enterprise-edition doesn't document tagging policy and tags for at least recent releases.

#### Steps to reproduce
Try to install docker container for MM 5.31.0 for example, looking for exact name in https://hub.docker.com/r/mattermost/mattermost-enterprise-edition/tags

#### Expected behavior
As with many other Docker Hub images I expect to find short description that would say:

For MM-EE v 5.31.0 you need to pull `docker pull mattermost/mattermost-enterprise-edition:5.31.0`

#### Observed behavior (that appears unintentional) 

I got swamped in thousands of build tags, trying to find any recent release.

#### Possible fixes
Can we get something like https://hub.docker.com/_/alpine main page, for example?

**Comment by amyblais** [comment]
This is likely related to the discussion here on our community server https://community.mattermost.com/core/pl/m3yecz6h1pn5zroto8isy3rdbo. It is planned to be implemented in the future.
