### ISSUE TITLE
Anybody can exclude members in a private channel

### ISSUE THREAD

**Issue by chassi** [mattermost/mattermost-server#16857]
#### Summary
Anybody can exclude members in a private channel

#### Steps to reproduce
Mattermost Version: 5.31.0
Database Schema Version: 5.30.0
Database: postgres

Web Client : Brave

A System admin user create a private channel in a public team and invite at least two normal users

One of the invited users enter in this new private channel and use the exclude members menu. He can exclude anybody

#### Expected behavior
Normaly as describe here : https://docs.mattermost.com/help/getting-started/welcome-to-mattermost.html#channels Only System admin and team owner should be able to exclude members. So the exclude members menu is not supposed to be accessible to the invited user.

**Comment by amyblais** [comment]
@chassi Are you on Team Edition or are you using Advanced Permissions https://docs.mattermost.com/cloud/cloud-user-management/advanced-permissions.html?

**Comment by chassi** [comment]
We are using the free edition on our own server . We have not access to the advanced permissions in the system console. 

Regards, 

Didier C 

Didier Chassignol 
Architecte au Service Application 
Tél: +33 4 76 61 53 70 

DSI - Service Applications 
Innovallée 
655 avenue de l'Europe - Montbonnot 
38334 Saint Ismier Cedex France 
[ https://www.inria.fr/ | www.inria.fr ]

**Comment by amyblais** [comment]
Opened a ticket https://mattermost.atlassian.net/browse/MM-32577.

**Comment by amyblais** [comment]
Our devs took a look and it seems that the documentation your were reading is not up-to-date.

You should be able to remove a member from a channel if:
 - you have MANAGE_PUBLIC_CHANNEL_MEMBERS or MANAGE_PRIVATE_CHANNEL_MEMBERS depending if the channel is public or private.
 - the channel is not group constrained or the user is a bot.
 - it's not the default channel or you are not a guest.

By default we are giving users the ability to do this for both public and private channels. If you have access to Advanced Permissions (https://docs.mattermost.com/cloud/cloud-user-management/advanced-permissions.html), then you can change the behaviour.

E.g. this part of the documentation describes it correctly: https://docs.mattermost.com/help/getting-started/organizing-conversations.html#removing-members-from-a-channel.

I've opened a Github issue in the docs repo to clarify it https://github.com/mattermost/docs/issues/4287.
