### ISSUE TITLE
Bleve search doesn't support wildcard search if the search term starts with an uppercase letter

### ISSUE THREAD

**Issue by jprusch** [mattermost/mattermost-server#16868]
#### Steps to reproduce
Using Mattermost 5.31.0 searching with * (wildcard) as last character of the search term starting with an uppercase letter shows no result.

Example: Make sure that messages can be found with a standalone term without wildcard (eg. "**problem**", "**Problem**", "**Probleme**" and "**probleme**" should return results).
![image](https://user-images.githubusercontent.com/9337414/106924359-4a151c80-670f-11eb-9cc9-96f778da5188.png)

![image](https://user-images.githubusercontent.com/9337414/106924441-5c8f5600-670f-11eb-881b-fc3b788ed458.png)

![image](https://user-images.githubusercontent.com/9337414/106924803-c0198380-670f-11eb-89f2-f24657686a81.png)

![image](https://user-images.githubusercontent.com/9337414/106924671-995b4d00-670f-11eb-8deb-8b9b558a7554.png)

![image](https://user-images.githubusercontent.com/9337414/106924526-72048000-670f-11eb-8a61-3a4c1f14894a.png)

#### Expected behavior
Searching for "**Problem***" should return the results of "**Problem**" and "**Probleme**".

#### Observed behavior (that appears unintentional) 
No results are shown for "**Problem***"
![image](https://user-images.githubusercontent.com/9337414/106924992-f2c37c00-670f-11eb-9cc0-dcde8494e478.png)

**Comment by amyblais** [comment]
@mgdelacroix Can you help confirm that this is a bug?

**Comment by mgdelacroix** [comment]
It is indeed a bug, and I can reproduce it consistently in `master`

**Comment by amyblais** [comment]
Thanks, opened a ticket https://mattermost.atlassian.net/browse/MM-32713.

**Comment by agnivade** [comment]
Closing this as it's tracked here https://github.com/mattermost/mattermost-server/issues/19846
