### ISSUE TITLE
Youtube previews not showing up in web or desktop apps

### ISSUE THREAD

**Issue by wom-bat** [mattermost/mattermost-server#16864]
Youtube previews show up on the Android app but not in browser or desktop clients.
#### Steps to reproduce
Post a link to a Youtube video.  View the channel on the browser, and on the desktop app, and on an Android client.
Make sure 'link preview' is set ON in global settings, and for your own account.

Mattermost Version: 5.28.1
Database Schema Version: 5.28.0
Database: postgres

Desktop version: 4.6.0-7302 (Debian packaged)
Android app version: 1.39.0 (build 3000341)

#### Expected behavior
I expect to see a screenshot from the video. Instead I just see the URL on the browser and desktop app.  The Android client correctly shows the preview.
Previews of links posted late last year still show up.

**Comment by wom-bat** [comment]
Looks like this is a duplicate of #16429 which I didn't spot because I was searching only for open issues.

**Comment by gamesguru** [comment]
I have this issue on Android too.

Other links load a preview, but not youtube or youtube music.
