### ISSUE TITLE
wrong link ！ https://releases.mattermost.com/5.25.7/mattermost-5.25.7-linux-amd64.tar.gz?src=arc

### ISSUE THREAD

**Issue by renchili** [mattermost/mattermost-server#16872]
please check thi link point to version 5.25.0 not 5.25.7
after installing the version show
![image](https://user-images.githubusercontent.com/33677006/107013846-df7ae400-67d5-11eb-9562-2438a63ad585.png)

and I am sure it running the correct bin with same md5 
81627dce5516b3e6ecbeb664d02ca151

**Comment by amyblais** [comment]
This was an error in our build process at the time, and exists in v5.25.7, 5.27.2, 5.28.2 and 5.29.1 where the same bug fix was backported. The issue doesn't occur in other releases. The version ``ee_onprem_54e0ea38be141a6ec2b440ba4e260950b388fbe9`` is correct for v5.25.7.

**Comment by renchili** [comment]
? if it was 5.25.7 how can be the md5 is the same as 5.25.0 that means no change at all in code?
