### ISSUE TITLE
Issue not be fixed at all

### ISSUE THREAD

**Issue by renchili** [mattermost/mattermost-server#16873]
https://github.com/mattermost/mattermost-server/issues/15188 this issue for long time waiting for the fix be released 
now tried every version of 5.25.0 this issue still presist

**Comment by amyblais** [comment]
@renchili Can you help confirm your environment details and server logs as described at https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by renchili** [comment]
> @renchili Can you help confirm your environment details and server logs as described at https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

I do not think this anything with the os the environment.
But as you wish:
OS ubuntu 16.04  
mattermost server version 5.25.6
log:
```
{"level":"error","ts":xxxxxxxx,"caller":"mlog/log.go:175","msg":"You do not have the appropriate permissions.","path":"/api/v4/users/xxxxxx/tokens","request_id":"xxxxxx","ip_addr":"xxxxxx","user_id":"xxxxxxx","method":"POST","err_where":"Permissions","http_code":403,"err_details":"userId=xxxxxxx, permission=create_user_access_token, attempted access by oauth app"}
```

**Comment by renchili** [comment]
Any update about this issue?
I read the change code that `seems` to fix, but that will not fix anything at all.
I cannot understand why login with GitLab third part OAuth plugin, is not admin.

why create a token will trigger a permission error.
create_user_access_token, attempted access by oauth app then if any group using mattermost with OAuth app then cannot create bot with token?
what ridiculous logic?
https://github.com/mattermost/mattermost-server/blob/572f861675b66d762326cbf19f2af4c83795cc68/api4/user.go#L2187

**Comment by renchili** [comment]
Any update about this issue?

**Comment by amyblais** [comment]
@ahmaddanialmohd / @sbishel Would you be able to provide guidance on this -- relates to https://github.com/mattermost/mattermost-server/issues/15188 / https://mattermost.atlassian.net/browse/MM-27623?

**Comment by amyblais** [comment]
Response was posted here https://github.com/mattermost/mattermost-server/issues/15188#issuecomment-778973730

**Comment by renchili** [comment]
can you read my response the issue is line 2187  the if condition whatever I am system admin or not  if IsOAuth is true then will return no permission error 
![image](https://user-images.githubusercontent.com/33677006/108335777-481e8380-720e-11eb-8b43-c721f2aaa4c7.png)

That is nothing related to any permission stored in DB. I am very certain about this

**Comment by amyblais** [comment]
cc @ahmaddanialmohd ^

**Comment by renchili** [comment]
anyupdate?

**Comment by ahmaddanialmohd** [comment]
@renchili I am not entirely well versed with the codes since you are certain that it has nothing to do with the permissions. The reason why I looked into that initially was because I was unable to reproduce the problem on a fresh deployment of the same Mattermost Server version.

@amyblais it will be best to refer this to the dev / engineering team for further assistance on this.

**Comment by amyblais** [comment]
@renchili Would you be open to posting about this in our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? Someone on our dev team or in the community may be able to help. Another good place to post would be our troubleshooting forum here: https://forum.mattermost.org/.

**Comment by renchili** [comment]
@amyblais  seems nobody in the p2p help channel  should I ask @ someone or?
