### ISSUE TITLE
TLS: the first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by un-fuf-a-doo** [mattermost/mattermost-server#16879]
#### Summary
Following posted documentation for Email setup, I am using Amazon SES, but Mattermost is not happy.

#### Steps to reproduce
Installed Mattermost per your documentation into a Debian 10 VM, then  Following these steps, https://docs.mattermost.com/install/docker-local-machine.html#setting-up-smtp-email-recommended, but I am not using Docker, Mattermost simply is not connecting to Amazon, Google, Localhost (Postfix), nothing works.

```
Feb  6 19:28:50 mm420 mattermost[7631]: {"level":"error","ts":1612661330.5867755,"caller":"mlog/log.go:232","msg":"Connection unsuccessful: SendMail: Failed to open TLS connection., tls: first record does not look like a TLS handshake","path":"/api/v4/email/test","request_id":"18nj8ubw9ibcpqs53bqgycqyie","ip_addr":"10.71.1.104","user_id":"9brfte9d7fg4tfhg56scogi3to","method":"POST","err_where":"testEmail","http_code":500,"err_details":""}
Feb  6 19:28:50 mm420 mattermost[7631]: {"level":"debug","ts":1612661330.5871649,"caller":"web/handlers.go:101","msg":"Received HTTP request","method":"POST","url":"/api/v4/email/test","request_id":"18nj8ubw9ibcpqs53bqgycqyie","status_code":"500"}
```

#### Expected behavior
There are not anymore details.

#### Observed behavior (that appears unintentional) 
See log above.

#### Possible fixes
Nothing I have tried works to resolve this issue.

**Comment by un-fuf-a-doo** [comment]
UPDATE

Seems that once my domain and email were validated on Amazon SES, only STARTTLS works.  Forced TLS does still present the same error.

**Comment by amyblais** [comment]
Would you be open to posting this on our troubleshooting forum forum.mattermost.org? Our community and support teams are more active there.

**Comment by un-fuf-a-doo** [comment]
Sure. I can do this. Thank-you!

**Comment by amyblais** [comment]
I'll close this for now as it's an older issue, but I recommend posting at https://forum.mattermost.org/ or at our [community server's Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) if the issue persists,

**Comment by amks1** [comment]
I've self-hosted using image tag 9.8.0, Enterprise Edition. In the System Console, I filled in the SMTP settings as follows (I use Mailersend):
- SMTP Server: `smtp.mailersend.net`
- SMTP Server Port: `587`
- Enable SMTP Authentication: `true`
- SMTP Server Username: `<my username>`
- SMTP Server Password: `<my password>`
- Connection Security: `TLS (Recommended)`
- Skip Server Certificate Verification: `false`
- Enable Security Alerts: `true`


I get this:
![image](https://github.com/mattermost/mattermost/assets/68153785/866834f3-8868-4d8b-928b-683b4a1c1e8e)

API response:
```javascript
{
    "id": "app.admin.test_email.failure",
    "message": "Connection unsuccessful: unable to connect to the SMTP server through TLS: tls: first record does not look like a TLS handshake",
    "detailed_error": "",
    "request_id": "ziqfkwsfqp8ruxbbg9y6r3hb4e",
    "status_code": 500
}
```

Log event in Server Logs:
```javascript
{
  "caller": "web/context.go:115",
  "err_where": "testEmail",
  "error": "testEmail: Connection unsuccessful: unable to connect to the SMTP server through TLS: tls: first record does not look like a TLS handshake",
  "http_code": 500,
  "ip_addr": "172.18.0.4",
  "level": "error",
  "method": "POST",
  "msg": "Connection unsuccessful: unable to connect to the SMTP server through TLS: tls: first record does not look like a TLS handshake",
  "path": "/api/v4/email/test",
  "request_id": "ziqfkwsfqp8ruxbbg9y6r3hb4e",
  "timestamp": "2024-05-27 10:03:37.666 Z",
  "user_id": "ezhhwcbtdiy13cyktd3qgy5xaa"
}
```
