### ISSUE TITLE
Not getting desktop notifications

### ISSUE THREAD

**Issue by DiptiShitole** [mattermost/mattermost-server#16881]
Hi,

Since past few days, I am not getting desktop notifications. I tried all the settings but it is not working. 
PFA screenshot for the settings which I have done.

Thanks and Regards,
Dipti

![Mattermost](https://user-images.githubusercontent.com/70362627/107188553-dc6a3880-6a0d-11eb-82df-b65e1b2d61bc.PNG)

**Comment by amyblais** [comment]
@DiptiShitole 
1. What OS and version are you on? 
2. What Mattermost server version are you on?
3. What desktop app version are you using?

**Comment by DiptiShitole** [comment]
Hello,

The issue is fixed after allowing notifications in Chrome.
Thanks for your help.

Regards,
Dipti
