### ISSUE TITLE
Static files not found when running as a Plesk service (Extension)

### ISSUE THREAD

**Issue by thistehneisen** [mattermost/mattermost-server#16884]
#### Summary
Static files are not being found. 404.

#### Steps to reproduce
Mattermost with Plesk (as an Extension)

#### Expected behavior
Working normally, currently just a blank page appears in both Desktop client and web.

#### Observed behavior (that appears unintentional) 
```
Preload of https://www.***ience/fonts/mattermosticons/mattermosticons.eot?16343536 was ignored due to unknown “as” or “type” values, or non-matching “media” attribute. mattermost
Preload of https://www.***ience/fonts/mattermosticons/mattermosticons.eot?16343536#iefix was ignored due to unknown “as” or “type” values, or non-matching “media” attribute. mattermost
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). fingerprint-protection.js:343:25
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9
GEThttps://www.***ience/fonts/mattermosticons/mattermosticons.eot?16343536
[HTTP/2 404 Not Found 63ms]

GEThttps://www.***ience/mattermost/static/main.5bf83e691752447d6ea0.css
[HTTP/2 404 Not Found 119ms]

GEThttps://www.***ience/mattermost/static/main.b1f20482eb9e1b512977.js
[HTTP/2 404 Not Found 134ms]

GEThttps://www.***ience/fonts/mattermosticons/mattermosticons.eot?16343536#iefix
[HTTP/2 404 Not Found 118ms]

Loading failed for the <script> with source “https://www.***ience/mattermost/static/main.b1f20482eb9e1b512977.js”. mattermost:1:1
GEThttps://www.***ience/mattermost/static/icon_152x152.png
[HTTP/2 404 Not Found 0ms]

GEThttps://www.***ience/mattermost/static/images/favicon/favicon-16x16.png
```
Together with a blank screen.

#### Possible fixes
Any way to regenerate the static files and/or point them correctly?

**Comment by amyblais** [comment]
Would you be open to posting this on our troubleshooting forum here: forum.mattermost.org? Our community and support teams are more active there and will likely be able to help troubleshoot this!

**Comment by thistehneisen** [comment]
@amyblais just did, thank you for suggestion.

**Comment by amyblais** [comment]
I'll close this for now as it's an older issue, but I recommend posting at https://forum.mattermost.org/ or at our [community server's Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) if the issue persists,
