### ISSUE TITLE
default notification settings

### ISSUE THREAD

**Issue by spbdimka** [mattermost/mattermost-server#16902]
When registering a user, the settings for user notifications are in the "Only with mentions and private messages" mode, as well as keywords. Is it possible to somehow set the default values so as not to explain to each user how to enable notifications?

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @spbdimka,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by ecker00** [comment]
Is this still not a possibility? (Ability to adjust the default notification settings for all users, or a team?) We got some teams with low message volume, so it makes sense to get notified for every interaction by default.
