### ISSUE TITLE
Update the Office 365 app link

### ISSUE THREAD

**Issue by haydenwalker980** [mattermost/mattermost-server#16919]
the link is now https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps

**Comment by amyblais** [comment]
@haardikdharma10 Hello, would you be able to help let me know where this link is located at?

**Comment by haardikdharma10** [comment]
Hi @amyblais, I think you meant to tag @haydenwalker980 here :)

**Comment by amyblais** [comment]
Oops, yes, sorry about this. @haydenwalker980 let me know if you'd be able to help let me know where the link you described is located at?

**Comment by haydenwalker980** [comment]
@amyblais System Console > OAuth 2.0 > Office 365.

**Comment by amyblais** [comment]
@haydenwalker980 I wasn't able to find this link from that page - is it a link within the help text? What server version are you on?
