### ISSUE TITLE
Update list of available timezones

### ISSUE THREAD

**Issue by gabrieljackson** [mattermost/mattermost-server#16918]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-32804)

Timezones must be enabled using the experimental config "ExperimentalTimezone"

______
 
This ticket is to update the current timezone selector UX in Account Settings > Display > Timezone

1. Update list of available timezones to this: https://github.com/dmfilipenko/timezones.json/blob/master/timezones.json

**Comment by IndushaS** [comment]
As a contributor that worked on https://github.com/mattermost/mattermost-webapp/pull/7384
Here are some findings for this issue:

- Current list of timezones: https://github.com/mattermost/mattermost-server/blob/master/services/timezones/default.go
- New timezone list has a different format than the current list so it will have to be refactored 
- Timezones would have to be updated for both Web App and Mobile

**Comment by lindy65** [comment]
@emilyacook please tag this for QA hacktoberfest

**Comment by emilyacook** [comment]
QA issue created: https://github.com/mattermost/quality-assurance/issues/20

**Comment by esethna** [comment]
Completed internally
