### ISSUE TITLE
Import Slack Theme Does Not Work

### ISSUE THREAD

**Issue by frakman1** [mattermost/mattermost-server#16932]
#### Summary
Slack theme import doesn't work

#### Steps to reproduce
Copy Slack Theme values:
- Click on top right user icon
- Select Preferences
- Select Themes
- Select "Create a custom theme"
- Click on any of the themes. The color color values will all change
- Copy values in box
![image](https://user-images.githubusercontent.com/5826484/107861257-b8926280-6e12-11eb-90ef-c3648d8ee24b.png)

Paste into Mattermost Theme builder:
- Goto Account Settings
- Select Display
- Select Import Theme Colors From Slack
- Paste values from Slack
- Observe Error:

![image](https://user-images.githubusercontent.com/5826484/107861297-f8594a00-6e12-11eb-9f7e-72bbb7575bf0.png)

#### Expected behavior
The Theme should import without issue

#### Observed behavior (that appears unintentional) 
Format of theme is unrecognized. Only allowed after deleting last two values. After that, the imported theme was still wrong.

**Comment by amyblais** [comment]
Closing as a dup of https://github.com/mattermost/mattermost-server/issues/16268. There is a [ticket open](https://mattermost.atlassian.net/browse/MM-30531) and this is listed as a known issue in [the changelog](https://docs.mattermost.com/administration/changelog.html).

**Comment by l-hermann** [comment]
2023: It still doesn't work.

**Comment by Normanras** [comment]
Yep ☝🏼 Found this issue googling for the same thing. Latest update of Slack doesn't let me import a custom theme.

**Comment by pepehandsjpg** [comment]
2024: It still doesn't work

**Comment by Preciouaga** [comment]
#3F0E40,#350d36,#1164A3,#FFFFFF,#350D36,#FFFFFF,#2BAC76,#CD2553,#350d36,#FFFFFF


Try the above

**Comment by mhaslinsky** [comment]
2026, still not working
