### ISSUE TITLE
Self-DM channel is "unread"

### ISSUE THREAD

**Issue by JohnRillos** [mattermost/mattermost-server#16933]
#### Summary
My DM channel with myself is showing up as "unread" whenever I check Mattermost.

#### Steps to reproduce
After updating from 5.26.0 -> 5.31.1, my self-DM channel keeps showing up as "unread". 
If I open my DM channel it gets marked as read (temporarily).  
After a minute or so, it gets marked as "unread" again, as if I got a new message from myself.  

#### Expected behavior
I don't expect to have any unread indicators on my DM channel.

#### Observed behavior (that appears unintentional) 
My self-DM channel keeps showing up as "unread".  This happens across desktop and mobile.  If I open my DM channel it gets marked as read (temporarily).  
After a minute or so, it gets marked as "unread" again, as if I got a new message from myself.  

Seeing these errors in the logs:
```{"level":"error","ts":1613262073.30307,"caller":"mlog/log.go:232","msg":"Unable to update the last viewed at time.","path":"/api/v4/channels/members/me/view","request_id":"dq3qnii9xbbhbba8kqh34rtt8h","ip_addr":"136.34.206.199","user_id":"dcd37cbz43fdfe981y4jgems5r","method":"POST","err_where":"MarkChannelsAsViewed","http_code":500,"err_details":"failed to fetch threads: Error 1267: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='"}```

**Comment by JohnRillos** [comment]
Update: This is now happening with every channel that someone posts in.  The channels do not stay "read" if someone's posted after the update from 5.26.0 -> 5.31.1

**Comment by amyblais** [comment]
Are you on MySQL or Postgres?

**Comment by streamer45** [comment]
From the error it looks like MySQL.

@JohnRillos 

Are you able to run the following queries on your database and share the output?

```sql
SHOW FULL COLUMNS FROM Threads;
SHOW FULL COLUMNS FROM ChannelMembers;
```

**Comment by JohnRillos** [comment]
It's using MySQL.  

@streamer45 Here's the output

```+--------------+-------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| Field        | Type        | Collation          | Null | Key | Default | Extra | Privileges                      | Comment |
+--------------+-------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| PostId       | varchar(26) | utf8mb4_0900_ai_ci | NO   | PRI | NULL    |       | select,insert,update,references |         |
| ChannelId    | varchar(26) | utf8mb4_0900_ai_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
| ReplyCount   | bigint      | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| LastReplyAt  | bigint      | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| Participants | longtext    | utf8mb4_0900_ai_ci | YES  |     | NULL    |       | select,insert,update,references |         |
+--------------+-------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
```

```+--------------+-------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| Field        | Type        | Collation          | Null | Key | Default | Extra | Privileges                      | Comment |
+--------------+-------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| ChannelId    | varchar(26) | utf8mb4_general_ci | NO   | PRI | NULL    |       | select,insert,update,references |         |
| UserId       | varchar(26) | utf8mb4_general_ci | NO   | PRI | NULL    |       | select,insert,update,references |         |
| Roles        | varchar(64) | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| LastViewedAt | bigint      | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| MsgCount     | bigint      | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| MentionCount | bigint      | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| NotifyProps  | text        | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| LastUpdateAt | bigint      | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| SchemeUser   | tinyint     | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| SchemeAdmin  | tinyint     | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| SchemeGuest  | tinyint     | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
+--------------+-------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
```

**Comment by JohnRillos** [comment]
FWIW the output above was generated after I switched back to 5.26.0

**Comment by streamer45** [comment]
@JohnRillos 

Yes, so the issue is that the new table got created with a different collation. I am assuming you are using MySQL 8 which defaults to `utf8mb4_0900_ai_ci`. In our [documentation](https://docs.mattermost.com/install/requirements.html#database-software) we recommend to convert the existing tables to the new collation.

It essentially means executing queries like:

```sql
ALTER TABLE table_name CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
```

For every table that is still using `utf8mb4_general_ci`. Once that's done you can safely upgrade and shouldn't get any more related issues.

**Comment by JohnRillos** [comment]
@streamer45 Thanks, that worked! Updated to `5.32.1`, not seeing any problems or errors so far.
