### ISSUE TITLE
The docker tag '5' is no longer updated

### ISSUE THREAD

**Issue by calvinbui** [mattermost/mattermost-server#16935]
#### Summary

The docker tag for '5', e.g. `mattermost/mattermost-team-edition:5` has not been updated for [2 months](https://hub.docker.com/layers/mattermost/mattermost-team-edition/5/images/sha256-be0d644eb65cc6c8b997f51a5bc7d1af0a852aa54adb714bde897765b8d74475?context=explore) and is stuck on 5.29.

#### Steps to reproduce

N/A

#### Expected behavior

The '5' tag should be always pointing to the latest stable '5.XX.YY' release.

#### Observed behavior (that appears unintentional) 

N/A

#### Possible fixes

Update the Docker build or Jenkins build

**Comment by amyblais** [comment]
I've created a ticket for our DevOps team to take a look,

**Comment by amyblais** [comment]
The tag has been updated,
