### ISSUE TITLE
26-characters channels not found

### ISSUE THREAD

**Issue by aopom** [mattermost/mattermost-server#16939]
#### Summary
Same issue as #8328, on Mattermost Server 5.31.1.

#### Steps to reproduce
- Create a channel of exactly 26 characters.
From the web frontend :
- Open this channel
- Go to another team. (Leave the current team on this 26-characters channel)
- Reload the page
- Go back to the first team. The frontend doesn't found the channel and propose to go back to Town Square. From Town Square, you can go back to your 26-characters channel.

#### Expected behavior
The channel should be found at first time.

#### Possible fixes
Rename the channel so its url name isn't 26 characters long. That's more a workaround than a fix ^^

Thanks for reading!

**Comment by steBracKa** [comment]
This also breaks the "invite to public channel by link" functionality if the path of the channel you try to invite to is 26 characters.

**Comment by astraldawn** [comment]
reproducible in 5.38.0
