### ISSUE TITLE
DM do not work correctly when chatting with someone outside of the current team

### ISSUE THREAD

**Issue by vlfesko** [mattermost/mattermost-server#16941]
#### Summary
DM do not work correctly when chatting with someone outside of the current team.

#### Steps to reproduce
Be able to DM to users outside of the team.
DM to someone.
Create additional team, switch to it.
Try to DM to the same person.

#### Expected behavior
DM chat is opened with previous conversation.

#### Observed behavior (that appears unintentional) 
DM chat is opened with infinite "Loading..." spinner.
If the page is refreshed - DM chat is opened but empty.
Switching back to previous team shows clear history or "Loading...", page refresh may show original history but not recent messages.
Buggy DMs can not be removed from favorites.
Buggy DM produces additional entries in "Direct Messages" list - the same user listed multiple times.
![Image Pasted at 2021-2-15 17-44](https://user-images.githubusercontent.com/3452636/107971099-b2d78100-6fba-11eb-8b72-a8c1a3ff3f99.png)

#### Possible fixes
Not known.

##### Affected version

Mattermost Version: 5.31.6{PATCH}
Database Schema Version: 5.30.0
Database: postgres

##### Not reproduced on
Mattermost Version: 5.30.6{PATCH}
Database Schema Version: 5.30.0
Database: postgres

**Comment by amyblais** [comment]
Does the other user have access to both teams? Do you see any server log errors?

**Comment by vlfesko** [comment]
As I see now, the issue happens even with users present in both teams, so it's not directly related to team membership.

I don't see any changes in server logs, new entries are not added.

After Cmd+Shift+R (page refresh with `cache-control: no-cache` header) the endless "Loading..." title does not show up again for that user for some period of time, but the DM shows empty history for the user in this and in other teams.

When I "brake" another user by DM to him in another team, then switch the current team, then open DM to that user again, the endless "Loading..." shows for this user and for previous "broken" users as well.

And also, Cmd+K DM filter becomes broken when I search for affected users, they are not filtered when typing, they shown together and not cleared right after I change filter text completely:

Must show only "valiu" user:
<img width="634" alt="Снимок экрана 2021-02-15 в 23 02 11" src="https://user-images.githubusercontent.com/3452636/107992882-52f4d080-6fe2-11eb-89c1-f77e8ec68b24.png">

Must show only "olkha" user:
<img width="594" alt="Снимок экрана 2021-02-15 в 23 02 32" src="https://user-images.githubusercontent.com/3452636/107992906-60aa5600-6fe2-11eb-819b-4d0801a2ccf3.png">

Must clear "valiu" suggested user and show only "pashu" user:
<img width="603" alt="Снимок экрана 2021-02-15 в 23 03 05" src="https://user-images.githubusercontent.com/3452636/107992933-6e5fdb80-6fe2-11eb-9395-05627bdeb24c.png">

If I open DM filter and right away search for unaffected user - then it works fine.
If I open DM filter and at first search for affected user - it shows as duplicated, then if I change filter text - affected user suggestion does not dissapear.

**Comment by vlfesko** [comment]
More to add - that empty DM chat seems to be actually new DM chat - messages in it does not appear in mobile application, and these conversation are shown for affected user on other side as two separate chats.
From my side - in mobile app and on desktop app / browser I see only one DM with affected user. These DMs are different - mobile app keeps old history, desktop app / browser started empty DM chat with new history.

**Comment by vlfesko** [comment]
May be related to https://github.com/mattermost/mattermost-server/issues/14382

**Comment by streamer45** [comment]
Hi @vlfesko,

are you able to run and provide output for the following database queries/commands after reproducing this issue?

```sql
\d channels;
```

```sql
SELECT Id FROM Channels WHERE Type IN ('D', 'G') AND TeamId != '';
```

**Comment by vlfesko** [comment]
Hi,
It looks like the issue was about duplicating DM channels as described in https://github.com/mattermost/mattermost-server/issues/14382

After we relocated posts and deleted duplicate channels the issue was resolved (and after a month now did not happen again).

It was an issue in upgrade path, we run mattermost for a few years now and never reinstalled it from scratch, only upgraded.

**Comment by streamer45** [comment]
Glad it's fixed now. Thank you for letting us know.
