### ISSUE TITLE
Previous/next channel or direct message shortcut should work differently with new side bar on 5.32.X

### ISSUE THREAD

**Issue by kalimanborges** [mattermost/mattermost-server#16963]
#### Summary
When I use the "previous/next channel or direct message shortcut" it goes to the message directly over or under the current one. With the new sidebar on 5.32.0 they should work as the new previous/back buttons on the new sidebar.

#### Steps to reproduce
Just go to a message and use the shortcuts. I'm using 5.32.0 on MacOS.

#### Expected behavior
When I use the "previous/next channel or direct message shortcut" it goes to the message directly over or under the current one. With the new sidebar on 5.32.0 they should work as the new previous/back buttons on the new sidebar. It should go to the last message I was when hitting OPTION + DOWN or the next hitting OPTION + UP.

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-33001

**Comment by amyblais** [comment]
@kalimanborges Here are explanations for our shortcuts: https://docs.mattermost.com/help/messaging/keyboard-shortcuts.html. ALT+LEFT or CMD+[ would go to the previous channel in your history.

Can you help clarify the expected behaviour?

**Comment by amyblais** [comment]
@kalimanborges Here are explanations for our shortcuts: https://docs.mattermost.com/help/messaging/keyboard-shortcuts.html. ALT+LEFT or CMD+[ would go to the previous channel in your history.

Can you help clarify the expected behaviour?

**Comment by kalimanborges** [comment]
I'm so sorry. The shortcut I was expecting to work already exists, is the one you indicated.
I didn't see it because it was classified as a Browser Built-in shortcut instead of a Navigation Shortcut.

Thank you.
