### ISSUE TITLE
version of postgres used in building docker image mattermost/mattermost-prod-db is no longer compatible with mattermost app version 5.32

### ISSUE THREAD

**Issue by danhimalplanet** [mattermost/mattermost-server#16978]
#### Summary

Mattermost v5.32 drops support for Postgres 9.4.
Using Postgres with Mattermost now requires Postgres version 10.

The image at https://hub.docker.com/r/mattermost/mattermost-prod-db is built from Dockerfile here:
https://github.com/mattermost/mattermost-docker/blob/master/db/Dockerfile , which is built on postgres 9.4

Mattermost version used in https://hub.docker.com/r/mattermost/mattermost-team-edition is Mattermost v5.32

if you use the available docker images of mattermost/mattermost-team-edition and mattermost/mattermost-prod-db , it will not work.

The error you see in Mattermost app startup explains that Mattermost requires postgres 10.

#### Steps to reproduce
Run a mattermost app and db stack with current available version of mattermost-prod-db and mattermost/mattermost-team-edition . It will not work.

app:
https://hub.docker.com/layers/mattermost/mattermost-prod-db/v5.32.1/images/sha256-3baa91f119e21747d6faba73940731aeb8e9f07d0b09a3e245b45093b5070f0f?context=explore

db:
https://hub.docker.com/layers/mattermost/mattermost-prod-db/v5.32.1/images/sha256-3baa91f119e21747d6faba73940731aeb8e9f07d0b09a3e245b45093b5070f0f?context=explore

#### Possible fixes
the version of postgres ( postgres 9.4) used in building the image mattermost/mattermost-prod-db is not compatible with mattermost anymore
https://github.com/mattermost/mattermost-docker/blob/master/db/Dockerfile#L1

A separate issue would be automating upgrading your postgres 9.4 database to postgres 10.
I ended up manually dumping the entire db with the postgres 9.4 version of mattermost-prod-db, then created a new container with a postgres 10 mattermost-prod-db image with a clean, empty, uninitialized db, and importing the dump from the previous version.

**Comment by caugner** [comment]
See also: https://github.com/mattermost/mattermost-docker/issues/489
