### ISSUE TITLE
Tray icon displays a new message notification on muted channels

### ISSUE THREAD

**Issue by inaun** [mattermost/mattermost-server#16981]
#### Summary
Tray icon displays a new message notification on muted channels

#### Steps to reproduce
Mute a channel, wait for a message to be posted, observe tray icon response

#### Expected behavior
Muted channels should not display any notifications

#### Observed behavior (that appears unintentional) 
Muted channels do display a notification

#### Possible fixes
Change tray icon notification filter to exclude muted channels when determining if a new message is available for reading.

**Comment by amyblais** [comment]
@inaun What Mattermost server version are you on? Are you using webapp or desktop app? Which OS are you using?
