### ISSUE TITLE
Spell checking in French when set to English

### ISSUE THREAD

**Issue by jillsley** [mattermost/mattermost-server#16989]
#### Summary
Despite spell checking being set to English (UK), it is actually spell-checking in French.  

#### Steps to reproduce
Version 4.3.2

#### Expected behavior
Expected behavior would be for me to type in English and only misspelled words to be underlined indicating a misspelling.  

#### Observed behavior (that appears unintentional) 
When typing in English, 90% of my words are underlined to indicate a misspelling when they are actually spelled correctly.  French words, however, are recognized as spelled correctly in 90% of the words, understandably highlighting words which should use unique French letters not available on the keyboard (e.g. c's).  
![image](https://user-images.githubusercontent.com/79343227/108577056-8bdbc080-72d4-11eb-9ff7-a3d89f54bcc9.png)
Let me know if that picture doesn't work.  

#### Possible fixes
No idea, but I have tried switching the language settings, restarting the app, and restarting the computer.

**Comment by amyblais** [comment]
@jillsley Do you see the same issue on desktop app version v4.6.2 (the latest version)?
What is your server version?
