### ISSUE TITLE
Recent Mentions search needs to add "OR" logic for the terms

### ISSUE THREAD

**Issue by afreiberger** [mattermost/mattermost-server#17020]
When additional mention triggers are enabled in Notifications bar, such as nickname, username, "Your case-sensitive first name", or "Other non case-sensitive words, separated by commas", the resultant search for Recent Mentions results in few if any results.

How to reproduce:
Configure other non case-sensitive words in "Words That Trigger Mentions" as: searchterm1,searchterm2
Type the following messages into a channel:

@username this is a message for me
this is a match for searchterm1
this is a match for searchterm2
@username this should match both searchterm1 and searchterm2

(replace @username with your actual mention username)

Actual result:
Click the Recent Mentions button and witness only the fourth line is returned, and the search bar contains:
@username searchterm1 searchterm2

Expected result:
Click the Recent Mentions button and all four messages should be returned in the search results.
Search bar should contain
@username|searchterm1|searchterm2

Workaround:
If you place a | (pipe) between each of the mention words in the resulting search bar after clicking Recent Mentions, it will perform the proper "OR" search for the terms.

**Comment by afreiberger** [comment]
I did find that |@ is a trigger for search to not function, so you have to remove @ signs if using the | workaround.

**Comment by amyblais** [comment]
@afreiberger What Mattermost server version are you on? I wasn't able to reproduce this on v5.32.1 just now.

**Comment by afreiberger** [comment]
I'm seeing this on 5.32.1 with postgres backend.

**Comment by amyblais** [comment]
@lindy65 Would you be open to help test this at https://postgres.test.mattermost.com/? I don't have access to create an account there and I'm not sure which other test servers are on postgres. (I wasn't able to reproduce this community report on a mysql server)

**Comment by afreiberger** [comment]
My apologies.  I have re-tested on 5.32.1 and found this has been resolved.  This was affecting me last week, but I do see we've had a recent upgrade and I'm now able to see all my mentions as expected.

Thank you for your time!

**Comment by lindy65** [comment]
Thanks for letting us know your issue is resolved @afreiberger 

//cc @amyblais
