### ISSUE TITLE
Viewing a specific channel makes MM permanently unrensposive

### ISSUE THREAD

**Issue by hjek** [mattermost/mattermost-server#17077]
#### Summary
Viewing a specific channel makes MM permanently unrensposive

#### Steps to reproduce
Navigate to the specific channel (`~town-square`) on a specific team (`[redacted]`). This causes MM to become unresponsive.

```
Mattermost Version: 76d18fe2cd6d43423526c1445df903511d7ea246
Database Schema Version: 5.28.0
Database: mysql
```

The issue happens in Chromium (`88.0.4324.182-1`), Brave (`1.22.49`) and Mattermost Desktop (`4.6.2-7881`). Chromium and Brave display a **Page Unresponsive** dialog. The issue *does not* happen in Firefox (`86.0-1`).

#### Expected behavior
We expected the channel to load.

#### Observed behavior (that appears unintentional)
The entire MM interface (including sidebar) becomes unresponsive while (sometimes) showing the **Loading…** animation. It is impossible to navigate away from the channel in question, except by using the browser address bar. In the MM Desktop app it appears like it is not possible to navigate away from the channel at all.

**Comment by amyblais** [comment]
@hjek.

1. Are you able to get any server log errors from around the time the issue happens?
2. Are you able to access the channel from, e.g. the mobile app to delete the content that may be causing the issue? (e.g. there could be an image or markdown that causes an issue)
3. We've done some bug fixes related to specific content (e.g. image or markdown) that can cause a blank screen, would you be open to upgrading to v5.32 (latest version) to see if the issue goes away?

**Comment by hjek** [comment]
@amyblais

1. I don't have direct access to server logs. I can try to ask but I believe the debug log is disabled due to performance issues.
2. I can access the channel from Firefox and I think I've found out which message is causing the issue. Since new messages have been posted in the channel, the issue doesn't appear right away, but only when scrolling up in history until the specific message is loaded. The message has 56 user mentions and 1 channel mention, so perhaps that's somehow making any Blink-based browser / app hang?
3. I can ask the server admins.

**Comment by hjek** [comment]
This issue doesn't happen when **Enable Post Formatting** is set to **Off**. That is of course a strong indication that it's a markdown formatting issue affecting Blink-based clients, so I'm not sure how useful server logs will be. I'm happy to do some more digging on this in Chromium if that can help.

**Comment by amyblais** [comment]
@hjek Would you be able to share the raw content of the post that causes the issue so we can take a look at what markdown could be causing it? Of course, please edit or remove any sensitive content, or create a new post that has a rough draft of what the original post content would be like.

**Comment by hjek** [comment]
>  the raw content of the post that causes the issue [...], please edit or remove any sensitive content, 

```
@someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone,, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone, @someone

#### xxxxxxxxx xxx xxxxxx, xx xxxxxxxxx x xxxxxxxxxxx xx xxxxxxx. xxxx xxxx xxxxxxx xxxx  :heart_eyes: :green_heart: :fire:
xxxxx xxxxxxxxx xxxxxxxxxxxxxx xxxxxxx xxxxxxxxxx x xxxxxxxxxx xxxxxxxxxx xx xxxxxxxxx xx ~some-channel xx xxxxx xxxxx xxxxx xxxxxxx xxxxx xxxxx x xxxxxxxxxxx, xxxxxxxx, xxxxx, xxxxxx, xxxxxxxxx. xxxxx xxxxxxx xxxxxx xxx xxxxxx xxxxxxxxxx xx xxxxxxx, xxxxxxxx xxx xxxxxxxxxxx xx xxxxx xxxxx xxx xxxxxx. xx xxxxxxxxxxxx xxxxxxxxxxxx xxxxxxx xxxxxxxxx

#### xxxxxxxxxxxxx x xxxxxxxxxx xxxxxxxxx
xx xxxxxxx xxxxxxxxx xxx x xxxxxxxx xxxxx xxxxxx/xxxxxxxx. xxxx x xxxxxxxxxxxxx x xxxxxxxxx x xxxxxxxxxxxx. xxxxx xxx xxxxxx x xxxx :pray: :hibiscus: :pray:
```

**Comment by amyblais** [comment]
@hjek Are you able to reproduce it on our [community server here](https://community.mattermost.com/)? It's on the latest version and you can post in a testing channel.

**Comment by hjek** [comment]
@amyblais I'd feel awkward about sending notifications to 56 random strangers. You're sure it's okay?

**Comment by hjek** [comment]
The issue doesn't happen on the otherwise affected server when literally notifying `@someone` 56 times. It looks like they have to be distinct real users.

**Comment by amyblais** [comment]
I created a post in a test server with over 50 distinctive usernames, with the same markdown (including valid emojis and channel links) but I wasn't able to reproduce it. @hmhealey Do you know what in a post like this could cause Mattermost to become unresponsive when viewing a channel with the post https://github.com/mattermost/mattermost-server/issues/17077#issuecomment-791581114?

**Comment by hjek** [comment]
> would you be open to upgrading to v5.32 (latest version) to see if the issue goes away?

We're upgrading this Tuesday. I'll check whether the issue remains.

**Comment by hmhealey** [comment]
The large number of at-mentions definitely stands out to me, but I'm not aware of any issues around that. That's strange that it only affects Chromium-based browsers though since those issues usually come up from a bad piece of regex which would affect everything. The issue being fixed when post formatting is disabled definitely lines up with that being the issue though.

Perhaps it's something specific to how we handle at-mentions since I know there's some ugly code around that, and as strange as it sounds, it might depend on the specific names of the users mentioned. I've definitely seen weirder stuff in that code. If you have an account on https://community.mattermost.com/, would you maybe be able to DM me a text file containing the original post text there? My username is just `@harrison` there.

**Comment by hjek** [comment]
> Perhaps it's something specific to how we handle at-mentions since I know there's some ugly code around that, and as strange as it sounds, it might depend on the specific names of the users mentioned.

That makes sense. Perhaps a code cleanup or some fuzzing would help. Unfortunately usernames are text messages are not something I can pass on as I have to respect their privacy.

**Comment by hmhealey** [comment]
Totally fair. I can try to guess at some things that might cause issues then. Do any of the usernames start or end with numbers, underscores, or any other punctuation?

Those characters, particularly at the end of usernames, have caused issues in the past since we have to do some tricky logic around whether or not something like `@user.name.` is a mention for someone named `user.name.`, `user.name`, `user.`, or `user`, so something like that could be a factor.

**Comment by amyblais** [comment]
I'll close this for now, but feel free to re-open this if the issue persists on the latest version,
