### ISSUE TITLE
New Message Issue

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#17092]
This is a need and it is much better that
When I receive a new message
Display the person's name **at the top of the list** ...

@tbalthazar @MerlinDMC @lurcio @mauricio @cored

**Comment by amyblais** [comment]
1. What Mattermost server version are you on?
2. What OS and version are you on?
3. Can you help share a screenshot to illustrate what you mean by "at the top of the list"?

**Comment by majidit** [comment]
Thank you very much for your answer
And that I am from Iran
We are using the web version
[https://s17.picofile.com/file/8427521700/Capture.PNG](url)

**Comment by majidit** [comment]
Mattermost Enterprise Edition
Mattermost Version: 5.30.1

**Comment by amyblais** [comment]
@majidit Thank you,
1. What OS and version is the Mattermost server installed (e.g. Windows 10, etc.)?
2. Do you see any Mattermost log errors, or browser console errors?

**Comment by majidit** [comment]
1) Windows 10 And Mattermost Version: 5.30.1 
2) No !!

**Comment by majidit** [comment]
I think they should pay attention to this issue in the next versions...

Because when the list of people is long
The new message icon at the bottom of the list is not visible

https://s17.picofile.com/file/8427521700/Capture.PNG

**Comment by amyblais** [comment]
Would you be open to upgrading to the latest version to see if the issue still reproduces? We have also done improvements to the channel sidebar in the most recent version.

**Comment by majidit** [comment]
OK
We will try the new version
And I will inform you of it
Thanks again for answering

**Comment by majidit** [comment]
> Would you be open to upgrading to the latest version to see if the issue still reproduces? We have also done improvements to the channel sidebar in the most recent version.

Thanks Again ...
