### ISSUE TITLE
new message symbol is not displayed

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#17098]
When the chat window with someone is open
And I go elsewhere
The new message symbol is not displayed on the person's name

@tbalthazar @MerlinDMC @lurcio @mauricio @cored

**Comment by isacikgoz** [comment]
Hey @majidit 👋 thanks for the feedback! Could you elaborate your issue a little bit? We already have a guideline [here](https://mattermost.org/filing-issues/) if it helps. Can you also add what version are you using? (both server and client)

**Comment by majidit** [comment]
The version we use: Web Server (Mattermost Version: 5.30.1)
 When you are on a conversation page with someone, for example, you get up from behind the desk and do something else
And the person sends a new message
This message is displayed on the talk page
But I may not be aware of this new message
Because the new message icon is not displayed on that person's name

**Comment by isacikgoz** [comment]
Oh I see. If I understood this correctly; you want to receive a desktop notification/or a sound even Mattermost webapp is in the focus. Is it correct?

**Comment by majidit** [comment]
Hi ... @isacikgoz 

When I'm not behind the computer , Sound does not make sense ... !!
All that remains is for a symbol or a new message counter to appear on the person's name ...

**Comment by majidit** [comment]
PLZ

**Comment by amyblais** [comment]
If the window is in focus with the same channel open, no notification is expected. Please share this as a feature request idea here https://mattermost.uservoice.com/forums/306457-general!

**Comment by majidit** [comment]
Thanks A lot ...
I shared this as a feature ...
https://mattermost.uservoice.com/forums/306457-general/suggestions/43078287-new-message-symbol-is-not-displayed 
@amyblais
