### ISSUE TITLE
Incorrect data type in notify_props

### ISSUE THREAD

**Issue by alexmorbo** [mattermost/mattermost-server#17106]
#### Summary
Invalid data types in object notify_props via user api `GET /api/v4/users`
In Api documentation fields: email, desktop_sound, channel, first_name must be boolean, but in API response i got strings with bool values like `"true"`, or `"false"`
```
	"notify_props": {
		"channel": "true",
		"comments": "never",
		"desktop": "mention",
		"desktop_sound": "true",
		"email": "false",
		"first_name": "false",
		"mention_keys": "",
		"push": "mention",
		"push_status": "away"
	},
```

#### Steps to reproduce
Call user api `GET /api/v4/users/me`

#### Expected behavior
**Boolean** values for fields email, desktop_sound, channel, first_name

#### Observed behavior (that appears unintentional) 
**String** values for fields email, desktop_sound, channel, first_name

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-33730

**Comment by alexmorbo** [comment]
Same with Timezone model
useAutomaticTimezone - in documentation boolean, in api - empty string for me

```
	"timezone": {
		"automaticTimezone": "",
		"manualTimezone": "",
		"useAutomaticTimezone": "true"
	},
```

**Comment by amyblais** [comment]
Thanks, updated the ticket.

**Comment by alexmorbo** [comment]
I found another one

In `POST /posts`, Post Model has post.props.from_bot same problem

```
		"from_bot": "true"
```

**Comment by amyblais** [comment]
We understand that ideally they should be boolean. But notify_props is a map[string]string (as are the others), and we cannot change it without bumping model version and the API version.
