### ISSUE TITLE
Please clean up the tasks

### ISSUE THREAD

**Issue by BElluu** [mattermost/mattermost-server#17103]
Hi,
If you can please clean up the tasks - assigned people and whether the issue is still valid.

Examples:
https://github.com/mattermost/mattermost-server/issues/13223  - assigned more than 1 year ago :)
https://github.com/mattermost/mattermost-server/issues/13468 - assigned almost 1 year :D 
https://github.com/mattermost/mattermost-server/issues/13474 - half year

and more more more. :)

Best Regards!

**Comment by amyblais** [comment]
Thanks, for letting us know, I've pinged devs on the issues,
