### ISSUE TITLE
Sign-in Method buttons not showing for SAML/OIDC if there is no AD/LDAP configured

### ISSUE THREAD

**Issue by muratbayan** [mattermost/mattermost-server#17121]
#### Summary
If a user/customer only has OpenID or SAML set up, the Account Settings UI does not show the button to switch Sign-in method

#### Steps to reproduce
* On a cloud workspace, set up a SAML or an OpenID Connect provider in the System Console
* Ensure that there is no AD/LDAP set up on the workspace (System Console -> Authentication -> AD/LDAP -> `Enable sign-in with AD/LDAP` set to `false`
* As a user currently with email/password authentication go into Account Settings -> Security
* Click on `Sign-in Method`
* Verify that there is a `Switch to Using OpenID SSO` button (or SAML equivalent) that is displayed
* Click on the button to be redirected to the Identity provider

#### Expected behavior
The user should see the `Switch to Using OpenID SSO` button in the UI to switch their authentication method

#### Observed behavior (that appears unintentional) 
The user does not see the `Sign-in Method` option in the Account Settings -> Security Settings
![image](https://user-images.githubusercontent.com/6051508/110934379-d970a980-8325-11eb-9f78-0d0c71f23c16.png)

If the Mattermost workspace has System Console -> Authentication -> AD/LDAP -> `Enable sign-in with AD/LDAP` set to `true`, then the user (with Email/Password auth) can see both `Switch to Using OpenID SSO` and `Switch to using AD/LDAP`
![image](https://user-images.githubusercontent.com/6051508/110934639-2b193400-8326-11eb-93d5-6882e57d8a9f.png)

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-33791
