### ISSUE TITLE
Allow Authentication Transfer setting keeps reverting to false in the System Console

### ISSUE THREAD

**Issue by muratbayan** [mattermost/mattermost-server#17120]
#### Summary
The Allow Authentication Transfer (System Console -> Experimental -> Features) cannot be set to true, keeps reverting to false

#### Steps to reproduce
* On a Cloud workspace, in the system console go to Experimental -> Features
* Set the `Allow Authentication Transfer` setting to true
* Save the changes
* Reload the page

#### Expected behavior
The value of the setting should be `true`

#### Observed behavior (that appears unintentional) 
The value stays as `false`
![image](https://user-images.githubusercontent.com/6051508/110932853-ed1b1080-8323-11eb-836a-7d88ee33ef96.png)

There is no access to system logs on the Cloud workspaces so I don't have much insight on what the underlying issue could be

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-33792
