### ISSUE TITLE
Emojis are moving around in the emoji picker

### ISSUE THREAD

**Issue by hjek** [mattermost/mattermost-server#17162]
#### Summary
Emojis are moving around in the emoji picker

#### Steps to reproduce
- Click on the emoji picker
- Click on an emoji, say :unamused:
- Now, before :unamused: is actually picked, the emoji picker will suddenly display a vertical scrollbar and shuffle the emojis around
- Another emoji, in this case :clown_face:, is accidentally picked instead

#### Expected behavior
I expect the emojis in the emoji picker to remain calm and in place. When an emoji is clicked then I expect that exact emoji to be picked.

#### Observed behavior (that appears unintentional)
The wrong emoji is either added to a draft or as a reaction. It can be embarrassing as a reaction because they are posted immediately.

![mm_emoji](https://user-images.githubusercontent.com/11958965/111381601-35c92580-86a6-11eb-96bc-f6b08b43258a.gif)

#### Possible fixes
Maybe `overflow-y: scroll;` in the emoji picker CSS?

**Comment by amyblais** [comment]
@hjek 
What OS and version are you on?
What Mattermost server version are you on?
I wasn't able to reproduce this just now, so any other information that you can share about your environment will be helpful.

**Comment by hjek** [comment]
> What Mattermost server version are you on?
This happens on `cloud-2021-02-10` (https://community.mattermost.com) and on `5.31.1`.

> What OS and version are you on?
I'm running Debian Unstable. I can see that this happens in Firefox 86. The delayed scrollbar loaded also happens in Chromium 89 but it doesn't shuffle the emojis.

I suspect you may not see this issue on more powerful devices where complex web pages load faster.

**Comment by amyblais** [comment]
Thanks, ticket here: https://mattermost.atlassian.net/browse/MM-33920

**Comment by hjek** [comment]
Looks like this issue is solved in the latest ESR.
