### ISSUE TITLE
i can not activate plugin

### ISSUE THREAD

**Issue by axac** [mattermost/mattermost-server#17212]
hello I can not activate all the plugins, for example.:

Jitsi (jitsi - 2.0.0)
Jitsi audio and video conferencing plugin for Mattermost.
Désactiver - Retirer - Paramètres

`Ce plugin n’a pas pu démarrer. Veuillez vérifier vos journaux à la recherche d’erreurs.

Todo (com.mattermost.plugin-todo - 0.4.0)
This plugin makes it easy to keep track of Todo issues and get daily reminders.
Désactiver - Retirer - Paramètres

Ce plugin n’a pas pu démarrer. Veuillez vérifier vos journaux à la recherche d’erreurs` .

this a new yunohost installation on an VM DEBIAN 10.  the version of mattermost is : 5.32.1

thanks

-- Logs begin at Thu 2021-03-18 21:59:27 UTC, end at Fri 2021-03-19 09:39:33 UTC. -- Mar 19 08:33:15 mattermost[962]: {"level":"error","ts":1616142795.3456683,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"com.mattermost.plugin-todo","error":"unable to start plugin: com.mattermost.plugin-todo: fork/exec plugins/com.mattermost.plugin-todo: permission denied","errorVerbose":"fork/exec plugins/com.mattermost.plugin-todo: permission denied\nunable to start plugin: com.mattermost.plugin-todo\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:268\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:132\nruntime.goexit\n\truntime/asm_arm64.s:1148"} Mar 19 08:43:26 mattermost[962]: {"level":"info","ts":1616143406.4263694,"caller":"expirynotify/worker.go:85","msg":"Worker: Job is complete","worker":"ExpiryNotify","job_id":"k6g4bugidj8898ejsm4g76sjyc"} Mar 19 08:53:26 mattermost[962]: {"level":"info","ts":1616144006.521327,"caller":"expirynotify/worker.go:85","msg":"Worker: Job is complete","worker":"ExpiryNotify","job_id":"jgb3rehudb899qaom7h9kq7qrr"} Mar 19 09:03:26 mattermost[962]: {"level":"info","ts":1616144606.627167,"caller":"expirynotify/worker.go:85","msg":"Worker: Job is complete","worker":"ExpiryNotify","job_id":"4rqb3kh97pnitnjcfcysmrcato"} Mar 19 09:13:26 mattermost[962]: {"level":"info","ts":1616145206.7178981,"caller":"expirynotify/worker.go:85","msg":"Worker: Job is complete","worker":"ExpiryNotify","job_id":"7ex4bggp6j85bx6pdo3f4orzza"} Mar 19 09:20:04 mattermost[962]: {"level":"info","ts":1616145604.2046227,"caller":"app/server.go:767","msg":"Stopping Server..."} Mar 19 09:20:04 mattermost[962]: {"level":"info","ts":1616145604.2048132,"caller":"app/web_hub.go:115","msg":"stopping websocket hub connections"} Mar 19 09:20:04 mattermost[962]: {"level":"info","ts":1616145604.2048814,"caller":"app/plugin.go:303","msg":"Shutting down plugins"} Mar 19 09:20:04 systemd[1]: Stopping Mattermost... Mar 19 09:20:04 mattermost[962]: {"level":"info","ts":1616145604.229865,"caller":"jobs/workers.go:270","msg":"Stopped workers"} Mar 19 09:20:04 mattermost[962]: {"level":"info","ts":1616145604.2299707,"caller":"jobs/schedulers.go:160","msg":"Stopping schedulers."} Mar 19 09:20:04 mattermost[962]: {"level":"info","ts":1616145604.230017,"caller":"jobs/schedulers.go:92","msg":"Schedulers stopped."} Mar 19 09:20:04 mattermost[962]: {"level":"info","ts":1616145604.2305436,"caller":"app/server.go:845","msg":"Server stopped"} Mar 19 09:20:04 systemd[1]: mattermost.service: Succeeded. Mar 19 09:20:04 systemd[1]: Stopped Mattermost. Mar 19 09:20:04 systemd[1]: Starting Mattermost... Mar 19 09:20:04 mattermost[8486]: {"level":"info","ts":1616145604.733002,"caller":"app/server.go:226","msg":"Server is initializing...","go_version":"go1.14"} Mar 19 09:20:04 mattermost[8486]: {"level":"info","ts":1616145604.7338126,"caller":"app/web_hub.go:83","msg":"Starting websocket hubs","number_of_hubs":4} Mar 19 09:20:04 mattermost[8486]: {"level":"info","ts":1616145604.737171,"caller":"utils/i18n.go:91","msg":"Loaded system translations","for locale":"fr","from locale":"/var/www/mattermost/i18n/fr.json"} Mar 19 09:20:04 mattermost[8486]: {"level":"info","ts":1616145604.7569275,"caller":"sqlstore/store.go:255","msg":"Pinging SQL","database":"master"} Mar 19 09:20:05 mattermost[8486]: {"level":"info","ts":1616145604.9999325,"caller":"app/server.go:511","msg":"Current version is 5.32.1 (dev-linux-arm64-v5.32.1/Wed Feb 17 22:17:20 UTC 2021/8e4b90726ce863f46952ab8acf62ecb57438aa86/none)","current_version":"5.32.1","build_number":"dev-linux-arm64-v5.32.1","build_date":"Wed Feb 17 22:17:20 UTC 2021","build_hash":"8e4b90726ce863f46952ab8acf62ecb57438aa86","build_hash_enterprise":"none"} Mar 19 09:20:05 mattermost[8486]: {"level":"info","ts":1616145605.0000436,"caller":"app/server.go:522","msg":"Team Edition Build","enterprise_build":false} Mar 19 09:20:05 mattermost[8486]: {"level":"info","ts":1616145605.0000923,"caller":"app/server.go:526","msg":"Printing current working","directory":"/var/www/mattermost"} Mar 19 09:20:05 mattermost[8486]: {"level":"info","ts":1616145605.0001457,"caller":"app/server.go:527","msg":"Loaded config","source":"file:///var/www/mattermost/config/config.json"} Mar 19 09:20:05 mattermost[8486]: {"level":"info","ts":1616145605.0199456,"caller":"bleveengine/bleve.go:295","msg":"UpdateConf Bleve"} Mar 19 09:20:05 mattermost[8486]: {"level":"info","ts":1616145605.1017828,"caller":"app/server.go:950","msg":"Starting Server..."} Mar 19 09:20:05 mattermost[8486]: {"level":"info","ts":1616145605.1027718,"caller":"app/server.go:1027","msg":"Server is listening on 127.0.0.1:8065","address":"127.0.0.1:8065"} Mar 19 09:20:05 mattermost[8486]: {"level":"info","ts":1616145605.1032257,"caller":"commands/server.go:117","msg":"Sending systemd READY notification."} Mar 19 09:20:05 systemd[1]: Started Mattermost. Mar 19 09:20:22 mattermost[8486]: {"level":"info","ts":1616145622.705041,"caller":"mlog/log.go:218","msg":"Starting up plugins"} Mar 19 09:20:22 mattermost[8486]: {"level":"info","ts":1616145622.7051804,"caller":"app/plugin.go:226","msg":"Syncing plugins from the file store"} Mar 19 09:20:22 mattermost[8486]: {"level":"info","ts":1616145622.7365327,"caller":"app/plugin.go:286","msg":"Syncing plugin from file store","bundle":"plugins/jitsi.tar.gz"} Mar 19 09:20:22 mattermost[8486]: {"level":"info","ts":1616145622.7365413,"caller":"app/plugin.go:286","msg":"Syncing plugin from file store","bundle":"plugins/com.mattermost.plugin-todo.tar.gz"} Mar 19 09:20:24 mattermost[8486]: {"level":"error","ts":1616145624.8360932,"caller":"app/plugin.go:288","msg":"Failed to sync plugin from file store","bundle":"plugins/jitsi.tar.gz","error":"installExtractedPlugin: Unable to restart plugin on upgrade., unable to start plugin: jitsi: fork/exec plugins/jitsi: permission denied"} Mar 19 09:20:24 mattermost[8486]: {"level":"error","ts":1616145624.9380643,"caller":"app/plugin.go:288","msg":"Failed to sync plugin from file store","bundle":"plugins/com.mattermost.plugin-todo.tar.gz","error":"installExtractedPlugin: Unable to restart plugin on upgrade., unable to start plugin: com.mattermost.plugin-todo: fork/exec plugins/com.mattermost.plugin-todo: permission denied"} Mar 19 09:20:25 mattermost[8486]: {"level":"error","ts":1616145625.178744,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"jitsi","error":"unable to start plugin: jitsi: fork/exec plugins/jitsi: permission denied","errorVerbose":"fork/exec plugins/jitsi: permission denied\nunable to start plugin: jitsi\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:268\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:132\nruntime.goexit\n\truntime/asm_arm64.s:1148"} Mar 19 09:20:25 mattermost[8486]: {"level":"error","ts":1616145625.178918,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"com.mattermost.plugin-todo","error":"unable to start plugin: com.mattermost.plugin-todo: fork/exec plugins/com.mattermost.plugin-todo: permission denied","errorVerbose":"fork/exec plugins/com.mattermost.plugin-todo: permission denied\nunable to start plugin: com.mattermost.plugin-todo\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:268\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:132\nruntime.goexit\n\truntime/asm_arm64.s:1148"} Mar 19 09:20:25 mattermost[8486]: {"level":"info","ts":1616145625.179654,"caller":"jobs/workers.go:98","msg":"Starting workers"} Mar 19 09:20:25 mattermost[8486]: {"level":"info","ts":1616145625.1807325,"caller":"jobs/schedulers.go:89","msg":"Starting schedulers."} Mar 19 09:20:25 mattermost[8486]: {"level":"info","ts":1616145625.1880112,"caller":"app/license.go:67","msg":"License key from https://mattermost.com required to unlock enterprise features."} Mar 19 09:20:32 mattermost[8486]: {"level":"info","ts":1616145632.4936903,"caller":"sqlstore/post_store.go:1853","msg":"Post.Message has size restrictions","max_characters":16383,"max_bytes":65535} Mar 19 09:20:32 mattermost[8486]: {"level":"info","ts":1616145632.4967363,"caller":"bleveengine/bleve.go:295","msg":"UpdateConf Bleve"} Mar 19 09:20:32 mattermost[8486]: {"level":"error","ts":1616145632.8727527,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"com.mattermost.plugin-todo","error":"unable to start plugin: com.mattermost.plugin-todo: fork/exec plugins/com.mattermost.plugin-todo: permission denied","errorVerbose":"fork/exec plugins/com.mattermost.plugin-todo: permission denied\nunable to start plugin: com.mattermost.plugin-todo\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:268\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:132\nruntime.goexit\n\truntime/asm_arm64.s:1148"} Mar 19 09:20:32 mattermost[8486]: {"level":"error","ts":1616145632.8862858,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"com.mattermost.plugin-todo","error":"unable to start plugin: com.mattermost.plugin-todo: fork/exec plugins/com.mattermost.plugin-todo: permission denied","errorVerbose":"fork/exec plugins/com.mattermost.plugin-todo: permission denied\nunable to start plugin: com.mattermost.plugin-todo\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:268\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:132\nruntime.goexit\n\truntime/asm_arm64.s:1148"} Mar 19 09:20:35 mattermost[8486]: {"level":"info","ts":1616145635.2910535,"caller":"bleveengine/bleve.go:295","msg":"UpdateConf Bleve"} Mar 19 09:20:35 mattermost[8486]: {"level":"error","ts":1616145635.6265264,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"jitsi","error":"unable to start plugin: jitsi: fork/exec plugins/jitsi: permission denied","errorVerbose":"fork/exec plugins/jitsi: permission denied\nunable to start plugin: jitsi\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:268\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:132\nruntime.goexit\n\truntime/asm_arm64.s:1148"} Mar 19 09:20:35 mattermost[8486]: {"level":"error","ts":1616145635.6306155,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"com.mattermost.plugin-todo","error":"unable to start plugin: com.mattermost.plugin-todo: fork/exec plugins/com.mattermost.plugin-todo: permission denied","errorVerbose":"fork/exec plugins/com.mattermost.plugin-todo: permission denied\nunable to start plugin: com.mattermost.plugin-todo\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:268\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:132\nruntime.goexit\n\truntime/asm_arm64.s:1148"} Mar 19 09:20:35 mattermost[8486]: {"level":"error","ts":1616145635.6479757,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"jitsi","error":"unable to start plugin: jitsi: fork/exec plugins/jitsi: permission denied","errorVerbose":"fork/exec plugins/jitsi: permission denied\nunable to start plugin: jitsi\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:268\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:132\nruntime.goexit\n\truntime/asm_arm64.s:1148"} Mar 19 09:20:35 mattermost[8486]: {"level":"error","ts":1616145635.648648,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"com.mattermost.plugin-todo","error":"unable to start plugin: com.mattermost.plugin-todo: fork/exec plugins/com.mattermost.plugin-todo: permission denied","errorVerbose":"fork/exec plugins/com.mattermost.plugin-todo: permission denied\nunable to start plugin: com.mattermost.plugin-todo\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:268\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:132\nruntime.goexit\n\truntime/asm_arm64.s:1148"} Mar 19 09:30:40 mattermost[8486]: {"level":"info","ts":1616146240.3396077,"caller":"expirynotify/worker.go:85","msg":"Worker: Job is complete","worker":"ExpiryNotify","job_id":"

**Comment by amyblais** [comment]
@axac Would you be open to posting about this on our [troubleshooting forum here](https://forum.mattermost.org/), or in our [community server's Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? Our devs or community members may be able to help troubleshoot this.

**Comment by axac** [comment]
@amyblais Thank you.
I'm going to community server's Peer-to-peer Help
Sorry.
