### ISSUE TITLE
Mattermost Desk App is not receiving all the messages, though the IOS app is receiving all

### ISSUE THREAD

**Issue by salvadorreyesc** [mattermost/mattermost-server#17221]
#### Summary
The IOS app receives all the messages, but when i open de Desk App to see them, some are there, but most of them doesnt appear.

#### Steps to reproduce
Its just dont appear. No steps involved.

#### Expected behavior
I want you to fix this issue, iss impacting all the communication between teams, losing valuable information.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@salvadorreyesc 
1. Please help with details on your environment via https://docs.mattermost.com/process/support.html#general-questions-for-any-issues.
2. Please also help with any desktop console errors via https://docs.mattermost.com/install/desktop.html#reporting-issues.
