### ISSUE TITLE
x509: certificate signed by unknown authority - iOS Push-Notification not working

### ISSUE THREAD

**Issue by tzeroem** [mattermost/mattermost-server#17239]
#### Summary
I had to update my iOS-Push certificate. After the update I got the error message about the mattermost push proxy -> x509: certificate signed by unknown authority

#### Environment Information

- Device Name: iPhone 8, iPad Air 2
- OS Version: iOS14.3, iOS14.4.1
- Mattermost App Version: 1.41.0
- Mattermost Server Version: 5.31.1
- Push-Proxy Version: 5.22.4
- Ubuntu-Server 18.04 

#### Steps to reproduce
Since https://api.push.apple.com uses GeoTrust Global CA, this means connections to it fail from any up to date Ubuntu and/or Debian installation.

#### Observed behavior
 got the error message about the mattermost push proxy -> x509: certificate signed by unknown authority

#### Possible fixes
Follow these steps on: https://github.com/sideshow/apns2/issues/182
In my case: https://github.com/sideshow/apns2/issues/182#issuecomment-776735889

```shell
wget --no-check-certificate -c https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem   \
    && mkdir /usr/local/share/ca-certificates/extra                                                                       \
    && mv GeoTrust_Global_CA.pem /usr/local/share/ca-certificates/extra/GeoTrust_Global_CA.crt                            \
    && update-ca-certificates
```

**Comment by amyblais** [comment]
@tzeroem Let me know if this guide helps: https://jeffschering.github.io/mmdocs/upgrade/install/troubleshooting.html#x509-certificate-signed-by-unknown-authority.

**Comment by tzeroem** [comment]
> @tzeroem Let me know if this guide helps: https://jeffschering.github.io/mmdocs/upgrade/install/troubleshooting.html#x509-certificate-signed-by-unknown-authority.

The solution is not correct in this case. I just wanted to show another possible solution that can arise in connection with the mattermost-push-proxy and Apple iOS.

I saw that the source code had dependencies on sideshow/apns2.
To solve my problem, I had to dig in that direction.

In the end, this solution solves it.
https://github.com/sideshow/apns2/issues/182#issuecomment-776735889

Maybe you could include this in the documentation and close the issue.
