### ISSUE TITLE
Track thread structure correctly/completely.

### ISSUE THREAD

**Issue by pde** [mattermost/mattermost-server#17237]
Presently, the Mattermost schema for messages contains two fields, a `root_id`, and a `parent_id`. 

Reportedly `parent_id` exists for historical reasons, and it is currently set to the same value as the `root_id`, but this is unfortunate for several reasons, including:

* Replies in threads are sometimes rendered in confusing and incorrect ways (#17236)
* It is impossible to write bots that engage in dialog with a clear tree structure. This is of interest for instance to anyone who is  developing a chatbot and would like to have it sit in a mattermost channel where multiple developers observe with an interact with it.

**Comment by pde** [comment]
Very superficially, it appears this could incrementally fixed by:

- Adding an optional `in_reply_to` field to the API for create_post
- populating the existing (historical) `parent_id` field with the `in_reply_to` parameter if it is supplied by a client

Fixing #17236 would then be easy as a rendering change back from `root_id` to `parent_id` in the appropriate places.

**Comment by amyblais** [comment]
Closing out some older issues. Feel free to share this improvement idea on Uservoice here https://mattermost.uservoice.com/forums/306457-general.
