### ISSUE TITLE
Upgrade to Desktop 4.6.2 deletes user-defined categories

### ISSUE THREAD

**Issue by Stanley-G** [mattermost/mattermost-server#17312]
This isn't reproducible since the categories are gone. Not sure if the problem is on the server or desktop client.

**Comment by amyblais** [comment]
@Stanley-G What Mattermost server version are you on and which version did you upgrade from?
Do you see any Mattermost log errors or browser console errors?

**Comment by Stanley-G** [comment]
I am glad to report that the issue has been resolved. Our Mattermost server administrator had accidentally enabled the "legacy sidebar" option during the upgrade to server version 5.33.3. Now the categories are back.
