### ISSUE TITLE
config.json are reset to defaults when using the admin UI

### ISSUE THREAD

**Issue by guillaume-perreal** [mattermost/mattermost-server#17329]
#### Summary
config.json are reset to defaults when using the admin UI

#### Steps to reproduce
With Mattermost 5.33.3, migrated from a previous 5.23 version :
Use the admin UI to modify the configuration.

#### Expected behavior
Only relevant sections of config.json should be modified.

#### Observed behavior (that appears unintentional) 
Some sections of the config.json files are reset to defaults. It seems to be sections that are not concerned by the panel used in the admin UI, e.g. SiteURL when you edit SMTP config, ...

#### Possible fixes
Not a fix but a workaround : the --disableconfigwatch switch prevents this from happening.

**Comment by amyblais** [comment]
This is listed as a known issue in the [changelog](https://docs.mattermost.com/administration/changelog.html). We have a ticket here to address it: https://mattermost.atlassian.net/browse/MM-32390.

**Comment by amyblais** [comment]
Closing as the ticket was addressed some time ago,
