### ISSUE TITLE
Delivery Option

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#17331]
I have an essential suggestion for future updates 💯 

Add the Delivery option to let the user know if the recipient has read the message
This option has many advantages:
1) The recipient is online but has not yet read the message
2) The sender may want to edit his message before it is seen
Etc

@tbalthazar @MerlinDMC @lurcio @mauricio @cored

**Comment by majidit** [comment]
Hello ...PLZ ... 
@tbalthazar @MerlinDMC @lurcio @mauricio

**Comment by amyblais** [comment]
@majidit Thank you for sharing! Our feature request issue for this is here for tracking: https://mattermost.uservoice.com/forums/306457-general/suggestions/12595398-read-receipts-implement-a-visual-indication-for-m.
