### ISSUE TITLE
Shift+arrow up only opens thread pane if input field has focus

### ISSUE THREAD

**Issue by runejuhl** [mattermost/mattermost-server#17341]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The keyboard shortcut to open the thread pane for the last message in the current channel only works when the input field has focus.

**Environment**
- Operating System: irrelevant, but Ubuntu 20.10
- Mattermost Desktop App version: 4.6.2 
- Mattermost Server version: 5.31.1 

**Steps to reproduce**
+ write a message in a channel
+ take focus away from input field (e.g. click somewhere outside of input field)
+ hit `shift+arrow up`

**Expected behavior**
Thread pane should open.

**Observed behavior**
Nothing happens.

**Workaround**
Hit any regular keyboard key to input character into input field, making it take focus. Hit backspace to delete, then `shift+arrow up` to open thread pane.

Alternatively use keyboard shortcut `ctrl+shift+l` to focus input field, then hit `shift+arrow up`.

**Possible fixes**
Keyboard shortcut should work everywhere, not just from input field.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-34637

**Comment by amyblais** [comment]
We discussed in triage that this is currently working as expected. @runejuhl Feel free to open a feature idea here if you'd like: https://mattermost.uservoice.com/forums/306457-general.

**Comment by runejuhl** [comment]
Hi @amyblais 

Although I respect your decision I can't help but wonder what the reasoning is here. The keyboard shortcut doesn't conflict with any other shortcuts. What often happens is that I'll chat in one thread, and close the thread pane it by hitting `ctrl+.`. When that happens focus isn't given back to the input field, requiring me to manually focus before I can hit `shift+arrow up` to open the thread pane for the last message.

I guess the issue could also be that the input field doesn't get focus after the thread pane closes. That would probably solve the issue as I experience it.

**Comment by amyblais** [comment]
@lindy65 Can you help remind me the reason behind this being expected behaviour?

**Comment by lindy65** [comment]
Sure @amyblais :)

1. Say you're in Off-Topic channel and make a post - your cursor will be focused in the center channel of Off-Topic after making the post. 
2. Then you press "Shift+up arrow" which opens the RHS to reply to the post.  Cursor is now focused in RHS comment input box. You reply to the post and cursor is still focused in RHS
3. Now you switch to Town Square in the center- cursor focus moves to center channel Town Square
4. Pressing "Shift+up arrow" opens RHS with the last post you made in the channel showing in Thread view

From the above scenario you can see how "Shift+up arrow" works as expected

If, however, focus is not in the center channel message input box, pressing "Shift+up" won't work as the app doesn't "know" that you're in the channel view so doesn't know to open the Thread view.

You can press "CTRL+Shift+L" which will always put the focus of your cursor into the center panel's message input box, after which you can press "Shift+up arrow" and then it'll work.

**Comment by Willyfrog** [comment]
@lindy65 that makes a lot of sense, but there still is the question if `ctrl+.`, which closes the RHS, should move the focus to the center channel?

**Comment by lindy65** [comment]
Oh, apologies @Willyfrog!  I missed that bit as I was concentrating on responding to Amy about a conversation we'd had in Triage the day before (we hadn't chatted about the CTRL+.

I see this reproduces for me too - pressing CTRL+. closes the RHS but does not put focus back into the Write to_ field in the center panel.  Although this has always been the behaviour, it doesn't make good sense so perhaps we should open a story ticket to implement CTRL+. putting focus back into the center panel? @amyblais ? 

The workaround at present for putting focus back in the center panel would be "CTRL+Shift+L"

**Comment by amyblais** [comment]
Opened a Story ticket: https://mattermost.atlassian.net/browse/MM-34728

**Comment by amyblais** [comment]
This is already implemented, typing after the RHS is closed auto-focuses the input.
