### ISSUE TITLE
Incorrect error message when trying to change handle via API to another one that already exists

### ISSUE THREAD

**Issue by nikkilocke** [mattermost/mattermost-server#17366]
#### Summary
When trying to change your handle **via the api**, if you try to change it to another handle that already exists, you get the wrong error message "Unable to find the existing account to update" instead of "An account with that name already exists"

#### Steps to reproduce
Version: v5.31.1
Send a handle change request to the API like:
```
/api/v4/users/7e7m75d4a3g9dxpfmnh3zdo11e/patch
{
  "username": "henry",
  "password": "a;sdkljhas;k"
}
```

#### Expected behavior
Response containing an error message that says the account already exists.

#### Observed behavior (that appears unintentional) 
Response is:
```
{"id":"app.user.update.find.app_error","message":"Unable to find the existing account to update.","detailed_error":"","request_id":"ad934wbri7873x8y6eipg6fx3r","status_code":400}
```
#### See also fixed similar issue with emails
https://mattermost.atlassian.net/browse/MM-30415

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-34725
