### ISSUE TITLE
Mattermost hijacks hardware media keys

### ISSUE THREAD

**Issue by Davdinges** [mattermost/mattermost-server#17367]
#### Summary
As a user mattermost is hijacking hardware media keys since update 5.33.3 even when no audio or media is displayed in Mattermost entirely.

#### Steps to reproduce 
As a user:
- Use two or more applications, for example Spotify and Mattermost.
- Play music/audio/media in the other application
- Use mattermost without any media in the window present (no embeds, just chat messages)
- Try using media keys on an external or internal keyboard (eg Play/Pause, next/previous)

#### Expected behavior
I expect Mattermost to not affect hardware media keys in any way whenever no audio, video or media is displayed in mattermost in any way. Only when there is media actively being played in an embed I expect media keys to be used by Mattermost.

#### Observed behavior (that appears unintentional) 
Hardware media keys have no effect on anything when Mattermost is opened more recent than any application playing media. When Mattermost is turned off hardware media keys resume working as expected. Mattermost does take control as you can can modify the state of embeds (pause/resume). 

#### Possible fixes
Mattermost seems to be chromium based. Chrome itself has flags to disable "Hardware Media Key Handling": chrome://flags/#hardware-media-key-handling. Mattermost does not seem to support this flag as a command line option, which means there is no way for a user to change the behavior of Mattermost related to hardware media keys. 
Before update 5.33.3 Mattermost seems to not affect hardware media keys in any way.

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-34727

**Comment by amyblais** [comment]
@Davdinges What Mattermost desktop app version are you on?

**Comment by Davdinges** [comment]
I am using Desktop version 4.3.2 on a Windows 10 machine, update version
2004.

Sadly I also noticed that the issue seemingly resolved itself yesterday,
and reoccurred today. A reboot did not resolve the issue today.
I understand this makes the troubleshooting a lot harder, if I find out an
exact pattern or a way to reproduce it exactly I will update the ticket.

**Comment by amyblais** [comment]
@Davdinges Does this reproduce on the latest desktop app version (v4.6.2)?

**Comment by Davdinges** [comment]
For an unknown reason both version v4.6.2 and v4.3.2 were installed at the same time, I removed both from the device and reinstalled version v4.6.2.
To this date I have not figured out how to reproduce the issue anymore, it's not unlikely that it was a random issue on my device specifically. If I figure out how to reproduce it in future with a decent reproduction rate then Ill reopen this issue or make a new one.
