### ISSUE TITLE
White or light grey notification icon on teams with new messages / activity - unable to customize

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#17374]
Running Mattermost EE 5.33.2 and found an odd new issue while modifying the color theme.  It appears that there is a white or light grey circle / dot on the upper right of team icons on the leftmost sidebar now.  When there is an @mention there is a count and I can define the color of the dot with "Mention Jewel BG" (`mentionBg` & `mentionBj` seem to be the same when changed via account settings), but I cannot seem to isolate the name of the little dot that indicates activity for a team.

Here's a screenshot that's blown up of this "dot" in question:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/9ZuxXY1W/0189aefe-45c6-48cf-b802-e1e200311107.jpg)

**Comment by amyblais** [comment]
@ylluminate Can you help share reproduction steps?

**Comment by ylluminate** [comment]
Sorry, I didn't think reproduction was necessary since this seems self explanatory. 

1) have 2 user accounts you can test with and that are on the same teams
2) have 1 user in another team and have the other user in another team
3) send a message (no @ mention) with the first user and watch for the dot to appear with the second user

**Comment by amyblais** [comment]
@ylluminate You mentioned that you modified the color theme. What changes did you make? What are mentionBg & mentionBj set to?

**Comment by ylluminate** [comment]
@amyblais I tried it with defaults as well with the same result. This is the "custom" theme I'm using (Account Settings -> Display -> Copy Theme Colors):
```
{"sidebarBg":"#21252b","sidebarText":"#abb2bf","sidebarUnreadText":"#abb2bf","sidebarTextHoverBg":"#3a3f4b","sidebarTextActiveBorder":"#de0d0d","sidebarTextActiveColor":"#d7dae0","sidebarHeaderBg":"#282c34","sidebarHeaderTextColor":"#abb2bf","onlineIndicator":"#98c379","awayIndicator":"#d19a66","dndIndicator":"#be5046","mentionBg":"#7f2222","mentionBj":"#7f2222","mentionColor":"#ffffff","centerChannelBg":"#282c34","centerChannelColor":"#abb2bf","newMessageSeparator":"#c67add","linkColor":"#61afef","buttonBg":"#4d78cc","buttonColor":"#ffffff","errorTextColor":"#f44747","mentionHighlightBg":"#525a69","mentionHighlightLink":"#61afef","codeTheme":"monokai"}
```

**Comment by amyblais** [comment]
Ah I see, we have this ticket open that seems to match with your report: https://mattermost.atlassian.net/browse/MM-34745

**Comment by ylluminate** [comment]
Interesting, you might try to see if Unito or some other service that does offer GitHub issues + JIRA, etc. sync might be available for open source projects for free: https://unito.io/integrations/jira-github/
