### ISSUE TITLE
Push notifications on Mobile

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#17389]
I’m not receiving push notifications on my device ...
@tbalthazar  @MerlinDMC  @lurcio  @mauricio  @cored 

I did all these steps :
https://docs.mattermost.com/mobile/mobile-testing-notifications.html

BUT ... But nothing happened ...

**Comment by MerlinDMC** [comment]
@majidit can you please not ping me in your tickets anymore? I'm not working on this project.

**Comment by amyblais** [comment]
I'll close this as a duplicate.
