### ISSUE TITLE
Timezone <no value> in E-Mails

### ISSUE THREAD

**Issue by DVTrast** [mattermost/mattermost-server#17407]
#### Summary
Timezone "no value" in E-Mails instead of CEST

#### Steps to reproduce
Write a private message to a person, who is absent so that a e-mail will be generated.

#### Expected behavior
The actual timezone should be set (in our case CEST).
![Timezone](https://user-images.githubusercontent.com/61227869/114826923-5af5a480-9dc8-11eb-9670-cdd0974ab9e3.png)

#### Observed behavior (that appears unintentional) 
The timezone on the mattermost-server ist set correctly to "Time zone: Europe/Vienna (CEST, +0200)". If I change the value at the setting "ExperimentalTimezone" to "true" or "false" in the config.json the problem will not be fixed.
Mattermost-Server Version 5.33.2

#### Possible fixes
"DisplaySettings": {
        "CustomUrlSchemes": [],
        "ExperimentalTimezone": false

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-34886

I'm guessing this could be because of a missing translation, but I'll confirm with the team.

**Comment by ctlaltdieliet** [comment]
Fyi: the same issue occurs in Dutch.

**Comment by DVTrast** [comment]
Issue exists in mattermost version 5.34.2 too.

**Comment by DVTrast** [comment]
It is fixed in version 5.36.1
![Timezone](https://user-images.githubusercontent.com/61227869/123783687-f0d4a200-d8d6-11eb-9e76-f91b8f784da4.png)

**Comment by amyblais** [comment]
Great, thanks!
