### ISSUE TITLE
Mattermost 5.34.1 cannot start

### ISSUE THREAD

**Issue by NgoHuy** [mattermost/mattermost-server#17419]
I upgraded mattermost to 5.34.1 but it refused to start, I cannot see any log because server mode not started.
How can I debug it with verbose log?

**Comment by amyblais** [comment]
@streamer45 @agnivade Would you be able to help?

**Comment by streamer45** [comment]
Hi @NgoHuy,

you can set either `LogSettings.FileLevel` or `LogSettings.ConsoleLevel` to `DEBUG` in `config.json`.

**Comment by NgoHuy** [comment]
thank you very much. I found that new version cannot access to database using password. The mattermost can not read password from config file, old version is fine.
```
{"level":"info","ts":1618581395.4449666,"caller":"sqlstore/store.go:270","msg":"Pinging SQL","database":"migrations"}
{"level":"error","ts":1618581395.4476974,"caller":"sqlstore/store.go:282","msg":"Failed to ping DB","error":"Error 1045: Access denied for user 'user@'localhost' (using password: YES)","retrying in seconds":10}
```

**Comment by streamer45** [comment]
Thank you. It seems potentially related to the new migration system. Is that the only error you are getting?

**Comment by NgoHuy** [comment]
yes, I only get this error.

**Comment by streamer45** [comment]
Alright. What database and version are you using?

**Comment by NgoHuy** [comment]
I use mariadb version: 10.3.27-0+deb10u1 from official repository.

**Comment by streamer45** [comment]
@nronas @mgdelacroix Would any of you be able to help here? This failure seems related to the newly introduced migration logic.

**Comment by nronas** [comment]
@streamer45 it seems that the problem is when we are trying to ping the database, which is not associated with the new migrations tool. We've just changed the var name from snake case to camel case on that commit https://github.com/mattermost/mattermost-server/commit/809affd6d1e5b73889cb3e34623981edd17cdfd1#diff-0ac00b8d5c25f7be41575e336cef33b3c0a75dcd7947c37c4452b660d4e71515R265

**Comment by streamer45** [comment]
@nronas 

I was thinking that `appendMultipleStatementsFlag()` might be involved since it touches the connection string.

**Comment by nronas** [comment]
@NgoHuy can you share an anonymised(without sensitive information, like a password) version of the datasource URL that you are using?

**Comment by NgoHuy** [comment]
it looks like this
"DataSource": "user:randompasswith@character@unix(/var/run/mysqld/mysqld.sock)/mattermost?charset=ut
f8mb4,utf8\u0026readTimeout=30s\u0026writeTimeout=30s",

**Comment by agnivade** [comment]
@NgoHuy - Would you be able to show us the full startup logs. There should be two log lines related to pinging the DB.

Something like:

```
2021-04-16T20:27:43.936+0530	INFO	sqlstore/store.go:283	Pinging SQL	{"database": "master"}
2021-04-16T20:27:43.938+0530	INFO	sqlstore/store.go:283	Pinging SQL	{"database": "migrations"}
```

If both fails, then it should be a genuine issue, but if one passes, and other one fails, then it's possibly something to do with `appendMultipleStatements`.

**Comment by NgoHuy** [comment]
yeah, it's here
```
{"level":"info","ts":1618581428.1455708,"caller":"i18n/i18n.go:93","msg":"Loaded system translations","for locale":"en","from local
e":"/home/teamworking/mattermost/i18n/en.json"}                                                                                    
{"level":"info","ts":1618581428.1506002,"caller":"sqlstore/store.go:270","msg":"Pinging SQL","database":"master"}                  
{"level":"info","ts":1618581428.1512384,"caller":"sqlstore/store.go:270","msg":"Pinging SQL","database":"migrations"}              
{"level":"error","ts":1618581428.1516094,"caller":"sqlstore/store.go:282","msg":"Failed to ping DB","error":"Error 1045: Access den
ied for user 'user'@'localhost' (using password: YES)","retrying in seconds":10}  
```

**Comment by nronas** [comment]
So we've run the logic for `appendMultipleStatements()` and that is outputting this:

```
user:randompasswith@character@unix(/var/run/mysqld/mysqld.sock)/mattermost?charset=utf8mb4%2Cutf8&multiStatements=true&readTimeout=30s&writeTimeout=30s
```

**Comment by nronas** [comment]
aha so it looks like it has to do with an `?` being present in the password field.

**Comment by agnivade** [comment]
@NgoHuy  Thanks! Just a quick test- Would you be able to try the datasource mentioned above and see if pinging the master DB fails or not? That would clarify if adding this query param is causing the issue.

But it's really strange to see an access denied error for a possibly invalid query param.

I assume MariaDB 10 supports the `multiStatements=true` query param?

**Comment by nronas** [comment]
@agnivade so actually the `url.Parse` does not returning any error when a `?` is in the password

**Comment by NgoHuy** [comment]
adding `&multiStatements=true` resulted in same error
```
{"level":"info","ts":1618587153.5752234,"caller":"sqlstore/store.go:270","msg":"Pinging SQL","database":"master"}
{"level":"info","ts":1618587153.5760868,"caller":"sqlstore/store.go:270","msg":"Pinging SQL","database":"migrations"}
{"level":"error","ts":1618587153.5765362,"caller":"sqlstore/store.go:282","msg":"Failed to ping DB","error":"Error 1045: Access denied for user 'teamwork'@'localhost' (using password: YES)","retrying in seconds":10}
```

**Comment by NgoHuy** [comment]
my password not including `?` character.

**Comment by nronas** [comment]
We are introducing a hotfix that does not `url.Parse` the datasource URL any more https://github.com/mattermost/mattermost-server/pull/17428 that should fix the issue.

**Comment by gramakri** [comment]
We had a similar issue when updating the Cloudron package.

```
15:59:29 - {"level":"error","ts":1618613969.5000048,"caller":"sqlstore/store.go:1337","msg":"Invalid database url found","error":"parse \"001e32067310ff44:32696156ea41a85196821efa1cf60cf69bccec264078a16c@tcp(mysql:3306)/001e32067310ff44?charset=utf8mb4,utf8\": first path segment in URL cannot contain colon"}
```

It seems the issue is that if the mysql username starts with a number, the parsing fails. I can confirm that if the username starts with a alphabet it works. @nronas does your fix cover this case too?

**Comment by agnivade** [comment]
Yes, it does cover the case. We use MySQL's native parser now.

**Comment by amyblais** [comment]
v5.34.2 dot release is now available,

**Comment by NgoHuy** [comment]
thank the mattermost's team very much. it's fixed

**Comment by gramakri** [comment]
Same, can confirm issue is fixed.
