### ISSUE TITLE
[Mattermost 5.34.1] 'mention' autocomplete does not work

### ISSUE THREAD

**Issue by WithGJR** [mattermost/mattermost-server#17427]
#### Summary
After upgrading to the version 5.34.1, the 'mention' autocomplete functionality is not working now.

Originally, when you type an @ symbol, an autocomplete list of members will appear. But now only @here, @channel, and @all are showing on the list. Even you have typed someone's name, you still can not see that person appears on the list.

#### Steps to reproduce
1. Upgrade to the version 5.34.1.
2. Mention anyone on the channel using web client or desktop app client.
3. (The problem does not happen on the iOS app client) (I don't have an Android phone, so I'm not sure if it is working on the Android app client)

I have used the Chrome's Dev Tools to check the API request, and I found that the issue happened because the API responds with an empty JSON array. So, I guess the problem is caused by the mattermost-server.

**Comment by amyblais** [comment]
@WithGJR What version did you upgrade from?

**Comment by WithGJR** [comment]
@amyblais I upgraded it from the version 5.34.0 (enterprise edition)

**Comment by amyblais** [comment]
Do you use ElasticSearch and have Enable Elasticsearch for autocomplete queries enabled? (Or Bleve, and use the same?)

If the response contains entries that then don’t show up client-side, it helps pinpoint the issue client-side. Do you see any console errors at that point?

@lieut-data FYI this seems similar to https://forum.mattermost.org/t/not-all-persons-inside-a-channel-are-shown-anymore/11482/7

**Comment by WithGJR** [comment]
@amyblais  I installed my self-hosted Mattermost using the official Docker image too. I think Bleve is used because I can see it is enable on the System Console page.

**Comment by WithGJR** [comment]
@amyblais  I disabled Bleve and it works now!

**Comment by mgdelacroix** [comment]
Hi @WithGJR! Did you have your bleve data folder mounted from the host into the docker container? If that was not the case, a possible explanation would be that updating the docker image rebuilt the container and the data was removed as it was not exported.

In that case, reindexing and enabling Bleve again after the update will fix the issue.

**Comment by WithGJR** [comment]
@mgdelacroix Yes, you are right! I didn't create a bind mount for the Bleve index directory. Thanks a lot!

**Comment by mgdelacroix** [comment]
Glad we were able to help! :relaxed:

**Comment by WithGJR** [comment]
@mgdelacroix  After reindexing finished, I found a new bug. If I type @ at a private channel, members of the channel will be listed on 'not in this channel' list.
It's not a crucial bug though.
