### ISSUE TITLE
[Bleve] Mention autocomplete for private channel does not correctly work 

### ISSUE THREAD

**Issue by WithGJR** [mattermost/mattermost-server#17434]
#### Summary
My original issue is here: [#17427](https://github.com/mattermost/mattermost-server/issues/17427)

After reindexing finished, I found a bug.  If I type the @ symbol on a private channel and the autocomplete list pops up, members of that channel will be listed on 'not in this channel' list. This problem does not happen on public channels.

I guess current implementation of Bleve does not index this type of information for private channels?

#### Steps to reproduce
1. Version: 5.34.1
2. Enable Bleve for autocomplete. 
3. Go to one of private channels and type the @ symbol.

**Comment by amyblais** [comment]
@mgdelacroix Are you able to reproduce with Bleve?

**Comment by amyblais** [comment]
@lindy65 @ogi-m Are you able to reproduce this with Bleve?

**Comment by ogi-m** [comment]
I was able to repro:
![Screenshot (69)](https://user-images.githubusercontent.com/15314183/115399788-d8fee480-a1e8-11eb-9306-340915b442cb.png)

**Comment by mgdelacroix** [comment]
@amyblais is reproducible in both Bleve and ES. I've created [a ticket to track the issue](https://mattermost.atlassian.net/browse/MM-35036)
