### ISSUE TITLE
Separation of sent and received chats 

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#17432]
Hello friends
Annoying enters 

One of the things that can greatly increase the beauty and efficiency of the program
Separation of sent and received messages
Like WhatsApp and Telegram messengers where the sent messages are displayed on the right and the received messages are displayed on the left
And the username is displayed on the same side

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @majidit,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
