### ISSUE TITLE
Pin button not visible anymore on the top right

### ISSUE THREAD

**Issue by biva** [mattermost/mattermost-server#17440]
#### Summary
I don't see the "Pin" button on the top right anymore.

#### Steps to reproduce
In order to see all pinned messages, I used to click on the pin button on the top right 
![image](https://user-images.githubusercontent.com/9964305/115208833-4fbeb380-a0fd-11eb-9c86-e6a9d5d78367.png)

I don't see it anymore (Mattermost Team Edition v5.34.2). I have the todo plugin and Jitsi plugin activated (and I see the buttons). What I see now is:
![image](https://user-images.githubusercontent.com/9964305/115209049-84cb0600-a0fd-11eb-94d8-70fc3df59712.png)

**Comment by amyblais** [comment]
@biva Do you see the pinned posts list in the left side, beside the "Members" button?

**Comment by zembo-etienne** [comment]
Yes, I see it, thanks @amyblais 

I suggest updating this documentation then: https://docs.mattermost.com/help/messaging/pinning-messages.html

I could do it, but my screenshots would include private information unfortunately, so I can't be very helpful. Sorry :/

**Comment by amyblais** [comment]
@zembo-etienne Would you be open to creating an issue in our docs repo here https://github.com/mattermost/docs/issues? Our Tech Writers can help with the docs.

**Comment by biva** [comment]
Yes, I see it, thanks @amyblais

I suggest updating this documentation then: https://docs.mattermost.com/help/messaging/pinning-messages.html

I could do it, but my screenshots would include private information unfortunately, so I can't be very helpful. Sorry :/

**Comment by biva** [comment]
For reference: https://github.com/mattermost/docs/issues/4504
