### ISSUE TITLE
MySQL Config not recognizing config.json settings

### ISSUE THREAD

**Issue by cybrpimp** [mattermost/mattermost-server#17455]
I’m having to set up a new server and our config file looks like this;

```
"DriverName": "mysql",
"DataSource": "mysql://custom_mmuser:Password@tcp(127.0.0.1:3306)/custom_mattermost_db?sslmode=disable\u0026connect_timeout=10",
```
I’m getting this error when we run the server;

`Failed to ping DB","error":"Error 1045: Access denied for user 'mysql'@'localhost' (using password: YES)","retrying in seconds":10}`

Notice the username “mysql@localhost” does not match what is in the config.json as custom_mmuser.

Also, the localhost does not match what I have in the config.json as 127.0.0.1 either.

For some reason it does not seem to be reading the config.json file, however, every time I run mattermost.exe and close the app, it updates the config file and I have to reload the changes in the editor so it seems to be updating the correct config.json.

What am I doing wrong?

**Comment by agnivade** [comment]
Hey @cybrpimp - which version of Mattermost are you using? We recently fixed this in a dot release with 5.34.2.

**Comment by cybrpimp** [comment]
Sorry, I forgot to mention, I'm running the latest, 5.23.2

**Comment by agnivade** [comment]
Yes, it is supposed to be fixed with 5.34.2. You can find more details here: https://docs.mattermost.com/administration/changelog.html#release-v5-34-feature-release.

Are you getting the same error with 5.34.2 also? Can you post a complete log of the server startup in DEBUG level?

**Comment by cybrpimp** [comment]
Yes, I appear to be getting the same error in 5.34.2.  Let me clear the log and run again and post here in a few mins.

**Comment by agnivade** [comment]
Ok, so this looks to be a different issue. It seems like Mattermost genuinely cannot connect with the DB. Are you able to manually connect to the DB with the given credentials?

We can ignore `mysql@localhost`, that is just a template format for the datasource that MySQL spits out.

**Comment by cybrpimp** [comment]
I just went to an earlier version that I originally had.  If I get time, I might upgrade and try again.

**Comment by rogue73** [comment]
I have noticed a similar problem with 5.34.2. I do also a fresh installation with mysql configured and prepared with an empty database. 
The information from the logfile is that it tries to reach the database on port 5432 which is postgres, 
I have tried the same thing with an older version (5.27.0) and it works.

**Comment by amyblais** [comment]
I'll close this for now, but feel free to re-open this as needed,
