### ISSUE TITLE
Channel notifications are hard too see

### ISSUE THREAD

**Issue by MH42069** [mattermost/mattermost-server#17450]
Channels with unread messages can be hard to see when you have a multitude of channels, expecially if you have a low-res monitor or a poor sight.

It would be really useful to have a bettere highlight method instead of just making channels with unread messages in bold font

I suggest to add an unread messages counter just like for DMs, which also makes it easier to spot, example:
![example](https://user-images.githubusercontent.com/26208133/114563111-68e3e200-9c6f-11eb-8d2a-59f9d80e2f43.png)

Any other kind of visual highlight would also be good tho.

**Comment by amyblais** [comment]
@hmhealey FYI

**Comment by hmhealey** [comment]
@esethna @matthewbirtch Some feedback on the colouring in the sidebar

**Comment by MH42069** [comment]
After around a week or so after asking my users to try @cbrand-ludlums and @amyblais suggestions i haven't received any other complains from those users.
However I would still suggest the devs to consider an implementation of a clearer default highlight method for channels.
