### ISSUE TITLE
Visibility of the Pinned Post

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#17471]
Hello to all
The post pin option is very good, but it is better to be able to see the post I am pinning at the top of the channel.
Not that you have to click on the icon to see it
Because some channel users may not notice the icon and see the post

And I think this can be done for all versions of different platforms

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @majidit,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by majidit** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/43230489-visibility-of-the-pinned-post

**Comment by jasonblais** [comment]
Thanks @majidit! Appreciate adding it to our feature idea forum. Thanks for being a Mattermost user! 🙌 

For feature ideas and bugs:
 - For suggestions and feature proposals, here is the process on how to contribute them https://mattermost.org/feature-ideas/
 - For bug reports, here's how to report them https://mattermost.org/filing-issues/

Hope the above links are helpful! Thanks again :)

**Comment by jasonblais** [comment]
Closing in favor of the feature proposal forum: https://mattermost.uservoice.com/forums/306457-general/suggestions/43230489-visibility-of-the-pinned-post
