### ISSUE TITLE
Email notifications received even with the account setting set to "Never"

### ISSUE THREAD

**Issue by parnic-sks** [mattermost/mattermost-server#17477]
#### Summary
I am receiving email notifications from Mattermost for certain cases (namely: `@all`-type notifications in channels) despite having email notifications set to "never" in my account settings.

#### Steps to reproduce
My email notifications are set to "Never". Any time someone `@all`s a channel that I'm in, I get an email notification a few minutes later, even if I was active on Mattermost at the time. This started happening somewhere around the v5.31.1/v5.32.0 updates and was not an issue prior to that.

#### Expected behavior
Never receive email notifications if account settings are set to "never".

#### Observed behavior (that appears unintentional) 
I receive emails for messages that include `@all`. I don't see any emails for any other types of notifications (direct messages, etc.), only `@all`, so it may only be an issue with that.

Of note: I am an admin on our server. Another user who is _not_ an admin reports that he does not receive emails with his setting set to "Never". So it could be something specific to my account somehow.

**Comment by amyblais** [comment]
@parnic-sks 
1. Do you see any Mattermost log errors from around the time the issue occurs?
2. In case a cache issue, would you be open to logging out from your active sessions from Account Settings > Security to see if it helps?

**Comment by parnic-sks** [comment]
Thanks for your reply.

1. I don't see any errors specific to this problem. The only errors showing up in the log are the following, for these two session IDs. I don't know who/what they correspond with. I wouldn't guess that it's related to this problem, though.
```
{"level":"warn","ts":1618881048.4655254,"caller":"app/session.go:112","msg":"Error while creating session for user access token","error":"createSessionForUserAccessToken: Invalid or missing token., resource: UserAccessToken id: token=dc3tnmksppfu7xunpgcdunw6ey"}
{"level":"info","ts":1618881048.4657888,"caller":"mlog/log.go:218","msg":"Invalid session","error":"GetSession: Invalid session token=dc3tnmksppfu7xunpgcdunw6ey, err=, "}
{"level":"warn","ts":1618881049.335172,"caller":"app/session.go:112","msg":"Error while creating session for user access token","error":"createSessionForUserAccessToken: Invalid or missing token., resource: UserAccessToken id: token=f3notommxjgmxeusryx1fosz3w"}
{"level":"info","ts":1618881049.3354332,"caller":"mlog/log.go:218","msg":"Invalid session","error":"GetSession: Invalid session token=f3notommxjgmxeusryx1fosz3w, err=, "}
```
2. Sure, I'll try this now and let you know.

**Comment by parnic-sks** [comment]
@amyblais I logged out of every session (there were a lot!), logged back in, had someone use `@all` in a channel while I was active on the server, and still received an email notification.

**Comment by amyblais** [comment]
@streamer45 @agnivade How do we investigate, or would another team own this?

**Comment by streamer45** [comment]
@parnic-sks 

Are you able to run and share the output of the following database query:

```sql
SELECT NotifyProps FROM ChannelMembers WHERE UserId = 'USER_ID' AND ChannelId = 'CHANNEL_ID';
```

Where `USER_ID` is you user id and `CHANNEL_ID` the id of a channel where you were able to reproduce this.

**Comment by parnic-sks** [comment]
@streamer45 sure thing:
```
=> SELECT NotifyProps FROM ChannelMembers WHERE UserId = 'u63ytfmwmjfxjnubsthj5pxpnh' AND ChannelId = 'tx6kdgqto3fo7cg88ymgjo79xh';
                                                   notifyprops
------------------------------------------------------------------------------------------------------------------
 {"desktop":"default","email":"default","ignore_channel_mentions":"default","mark_unread":"all","push":"default"}
(1 row)
```

And here's the NotifyProps from `users` for my username:
```json
{"auto_responder_active":"false","auto_responder_message":"Hello, I am out of office and unable to respond to messages.","channel":"true","comments":"any","desktop":"mention","desktop_notification_sound":"Bing","desktop_sound":"true","email":"false","first_name":"false","mention_keys":"@parnic","push":"none","push_status":"away"}
```

**Comment by streamer45** [comment]
Thanks. Everything looks in order there. 

Just to confirm, you are saying this is happening on `@all` mentions only. Have you also verified both `@here` and `@channel` don't have the same effect?

Also, what MM version are you currently running?

**Comment by parnic-sks** [comment]
> Just to confirm, you are saying this is happening on `@all` mentions only. Have you also verified both `@here` and `@channel` don't have the same effect?

I have not verified here/channel. It's possible/likely that my team only really uses `@all`, but that's all I'm seeing email notifications for right now. I can test the other types if needed.

> Also, what MM version are you currently running?

Currently we're on v5.34.1. This started happening somewhere around the v5.31.1/v5.32.0 updates and was not an issue prior to that.

**Comment by amyblais** [comment]
@ahmaddanialmohd Has this issue come up for support team before and do you have any additional troubleshooting ideas?

**Comment by amyblais** [comment]
@parnic-sks Do you have any words set in Account Settings > Words that trigger mentions > Other non case-sensitive words, separated by commas: that might be causing the issue (i.e. still sending an email even although you have email set to "never")?

**Comment by parnic-sks** [comment]
@amyblais I have the following settings:
![image](https://user-images.githubusercontent.com/62021255/116707928-d17fce00-a994-11eb-85cb-224e1980eeb7.png)

**Comment by amyblais** [comment]
@parnic-sks Do you have any other accounts on that server? My thought is that maybe that other account is getting the email notifications if the account has a similar username as your main admin account.

**Comment by parnic-sks** [comment]
That's a wonderful question that I'm embarrassed to not have considered sooner...

Yes, it looks like one of the bot users we created has a distribution list that I'm a member of as its email address.

Terribly sorry for the confusion - I appreciate all the help!

**Comment by amyblais** [comment]
No worries!
