### ISSUE TITLE
Websocket upgrade fails when using wildcards in MM_SERVICESETTINGS_ALLOWCORSFROM

### ISSUE THREAD

**Issue by kari-awake** [mattermost/mattermost-server#17497]
#### Summary
Websocket upgrade fails when using wildcards in AllowCorsFrom.

#### Steps to reproduce
Set AllowCorsFrom in config.json or environment variable:

MM_SERVICESETTINGS_ALLOWCORSFROM=https://*.mydomain.com

#### Expected behavior
Websocket upgrade should work with wildcards in AllowCorsFrom

#### Observed behavior (that appears unintentional) 
Websocket upgrade fails when there are wildcards in AllowCorsFrom

Errors in mattermost logs:

```
{"level":"error","ts":1619164829.9423554,"caller":"api4/websocket.go:28","msg":"websocket connect err.","error":"websocket: request origin not allowed by Upgrader.CheckOrigin"}
{"level":"error","ts":1619164829.942429,"caller":"mlog/log.go:229","msg":"Failed to upgrade websocket connection.","path":"/api/v4/websocket","request_id":"...","ip_addr":"...","user_id":"...","method":"GET","err_where":"connect","http_code":500,"err_details":""}
```

#### Possible fixes
When websocket is upgraded `CheckOrigin` function is used and it fails since it seems to be just comparing strings..

e.g. "*.mydomain.com" does not match "foobar.mydomain.com"

https://github.com/mattermost/mattermost-server/blob/ff657bfdef2467ab38641c39c5df171000c77eb6/utils/api.go#L31

**Comment by amyblais** [comment]
@kari-awake What Mattermost server version are you on? cc @agnivade

**Comment by agnivade** [comment]
Hello @kari-awake - Yes, unfortunately we don't match wildcards in subdomains. It's either `*`, or you have to add the list of domains that you want to support.

I am not sure if this was intentional or not, because I see other libraries supporting this. I'll check with our security team to be sure.

**Comment by kari-awake** [comment]
> @kari-awake What Mattermost server version are you on? cc @agnivade

we are using 5.28

I was asking this since wildcards seem to work for http(s) but not for the websocket upgrade.


If we configure `*`, mattermost returns `access-control-allow-origin: *`. Is there a way to make mattermost rewrite origin? It would be just like `*` but would allow credentials..

**Comment by agnivade** [comment]
> I was asking this since wildcards seem to work for http(s) but not for the websocket upgrade.

Yes, unfortunately the code to handle CORS for normal http(s) and websocket upgrades are different.

> Is there a way to make mattermost rewrite origin? It would be just like * but would allow credentials..

No I don't believe so. You can set `"CorsAllowCredentials"` to true to allow credentials, but everything else will remain the same.

**Comment by amyblais** [comment]
I'll close this for now, but feel free to re-open this as needed,
