### ISSUE TITLE
gitlab auth broken in 5.34.2

### ISSUE THREAD

**Issue by sooslaca** [mattermost/mattermost-server#17499]
#### Summary
5.34.2 Team edition version we get gitlab auth "Error Gitlab SSO through OAuth 2.0 not available on this server."

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
5.34.2 Team Edition.
enable gitlab auth, try login with gitlab

#### Expected behavior
Should be able to login with gitlab

#### Observed behavior (that appears unintentional) 
Team edition. On login screen click "gitlab" icon, which gives
"Error Gitlab SSO through OAuth 2.0 not available on this server."

#### Possible fixes
NA, it worked in 5.30 for sure

**Comment by sooslaca** [comment]
Also found in debug logs:
```
{"level":"info","ts":1619182038.5610273,"caller":"mlog/log.go:218","msg":"Gitlab SSO through OAuth 2.0 not available on this server.","path":"/oauth/gitlab/login","request_id":"81cgp1f4gpgr7f6dw11u6f6fco","ip_addr":"a.b.c.d","user_id":"","method":"GET","err_where":"getSSOProvider","http_code":501,"err_details":""}
```

**Comment by sooslaca** [comment]
Maybe here?
https://github.com/mattermost/mattermost-server/blob/dd9a1918e1bf76fbfa41d022a424d76b9e928486/app/oauth.go#L570

**Comment by amyblais** [comment]
@furqanmlk @sbishel Are you able to reproduce this?

**Comment by furqanmlk** [comment]
Let me test

**Comment by sooslaca** [comment]
hi, we figured partially:
this line : https://github.com/mattermost/mattermost-server/blob/dd9a1918e1bf76fbfa41d022a424d76b9e928486/app/oauth.go#L574

doesn't work well with our own implementation (self hosted) gitlab

here are our settings
```
    "GitLabSettings": {
        "Enable": true,
        "Secret": "xxxx",
        "Id": "yyy",
        "Scope": "openid profile",
        "AuthEndpoint": "https://gitlab.corp/oauth/authorize",
        "TokenEndpoint": "https://gitlab.corp/oauth/token",
        "UserApiEndpoint": "https://gitlab.corp/api/v4/user",
        "DiscoveryEndpoint": "",
        "ButtonText": "",
        "ButtonColor": ""
    },
```

**Comment by sbishel** [comment]
Yes. I am able to duplicate. It appears when the GitLabSettings are edited. They are getting saved with incorrect "Scope" settings. Simple work-around is to remove the "Scope" values from the config. Having OpenId in the scope is attempting to use OpenId with GitLab, which is not supported in TE, only OAuth. I'm still investigating a fix.
```
"Scope": "",
```

**Comment by sbishel** [comment]
Actually, with a fresh config. I am NOT able to duplicate. Was this server upgraded and downgraded? When updating the scope for OpenID, we set it to -
```
        "Scope": "profile openid email",
```
So, I'm not sure how the configuration got "openId" in the scope. But removing it will resolve this issue.

**Comment by sooslaca** [comment]
we're trying, we need the openid in the scope. It was upgraded from 5.30 -> 5.34.2

**Comment by furqanmlk** [comment]
I am not able to reproduce in v5.34.2

**Comment by dmagyar** [comment]
It is definitively broken for me as well. Tried with a 5.31 test instance and it was still working.

**Comment by bastien-solutions** [comment]
+1 confirm this is also broken for me (with or without scope).

**Comment by sbishel** [comment]
@sooslaca - Why do you need "openid" in scope? TE supports Gitlab auth via OAuth which should only require "read_user" scope.

**Comment by bastien-solutions** [comment]
It was simply the scope set by default in previous versions.
Anyway, whatever the scope set in ["","openid","read_user"], this doesn't work.

**Comment by sbishel** [comment]
What error do you see with `"Scope": ""`?

**Comment by bastien-solutions** [comment]
The HTTP router seems not respond to the redirect URL  : https://my_domain/signup/gitlab/complete&state.... (get a HTTP 404).

**Comment by sbishel** [comment]
That is a different issue, not an issue with scope.

**Comment by bastien-solutions** [comment]
This is a "gitlab auth broken" issue :)

**Comment by amyblais** [comment]
@ahmaddanialmohd Would someone on support team be able to help take a look at this?

**Comment by sooslaca** [comment]
Just a feedback, my issue got solved after I added scope: "read_user". With empty scope it did not work for me.
I dunno about others, but from my end it is ok to close this one.

Thanks for the help !

**Comment by simaotwx** [comment]
@sooslaca I can confirm that just `read_user` as scope works but leaving it empty or with `profile email openid read_user` does not.

**Comment by fleXible** [comment]
Thank you so much guys! I too can confirm that setting the scope to `read_user` both in Gitlab and Mattermost finally got it working. I really didn't want to enable `api` scope in Gitlab just for the Mattermost auth to work.

**Comment by almereyda** [comment]
Since this is usable with some workarounds, I suggest to also change the documentation at https://docs.mattermost.com/onboard/sso-gitlab.html#step-1-add-an-openid-connect-application-to-your-gitlab-account where it says:

> c. Do not select any options under **Scopes**.

Surfacing the Scopes parameter from `config.json` to the System Console page of the GitLab Authentication scheme can also help finding and setting this parameter. Changing in the file/environment is possible with an application restart, and not explicitly explained in the documentation.

**Comment by amyblais** [comment]
@cwarnermm Please see this above latest comment for a suggested documentation update ^

**Comment by cwarnermm** [comment]
Thanks, @amyblais! And thanks @almereyda for your documentation correction! I've logged https://community-daily.mattermost.com/boards/workspace/g4k9s1f953n4bytz5f9sz9orer/bm1j7wcrrspoymkjermbydid97h/vcwyy7xnhh4qits4thrb3pte53e/7tjsmdaww59mmxq4nfu9kzigera for this documentation correction.
