### ISSUE TITLE
Error logs if user disables notifications

### ISSUE THREAD

**Issue by vblz** [mattermost/mattermost-server#17496]
#### Summary
If a user uses browser and disables notifications, every message to them will cause error log

#### Steps to reproduce
Client and server versions are 5.34.2
1. Open mattermost in a browser
2. Disable notifications for the site
3. Change tab in the browser (probably not needed)
4. Receive a message from anyone
5. Check server logs in System console

#### Expected behavior
No error logs

#### Observed behavior (that appears unintentional) 
Logs with `error` level like ` {"level":"error","ts":1619162621.9221675,"caller":"api4/system.go:372","msg":"Client Logs API Endpoint Message: {\"name\":\"Error\",\"message\":\"Notifications already requested but not granted\",\"stack\":\"Error: Notifications already requested but not granted\\n at u (https://domain/static/main.7f1adff8ffa2e2fea570.js:2:2594331)\\n at https://domain/static/main.7f1adff8ffa2e2fea570.js:2:2060839\\n at https://domain/static/main.7f1adff8ffa2e2fea570.js:2:5443193\\n at https://do","type":"client_message","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36"}`

#### Possible fixes
Probably [this frontend error](https://github.com/mattermost/mattermost-webapp/blob/634519609096b14a5e789153f83e4aefae6264d8/utils/notifications.tsx#L54)
```
    if (Notification.permission !== 'granted' && requestedNotificationPermission) {
        throw new Error('Notifications already requested but not granted');
    }
```
left uncaught and unhandled, that's why it's considered as an error at the server

**Comment by amyblais** [comment]
@isacikgoz Would you know if this would be a bug?

**Comment by amyblais** [comment]
cc @streamer45

**Comment by streamer45** [comment]
@vblz 
Thanks for the report. Indeed this looks like a client-side issue.

@amyblais  
I think it makes sense to create a ticket and assign it to the appropriate team (Web Platform maybe).

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-35175

**Comment by vblz** [comment]
Hello. Is there any estimates regarding this issue? I'm asking because it's quite annoying when you try to read server logs. Checked that at our server logs now, there are 337 `Notifications already requested but not granted` messages in 1060 lines of logs, a third part.
