### ISSUE TITLE
Text after quote in message unintentionally indented

### ISSUE THREAD

**Issue by Michael-E-Rose** [mattermost/mattermost-server#17502]
#### Summary
Text in message following a quote indented as well

#### Steps to reproduce
Write a message:
```
> Some quote
Some normal text
```

#### Expected behavior
"Some normal text" should not be indented

#### Observed behavior (that appears unintentional) 
"Some normal text" is indented

![Screenshot from 2021-04-23 22-36-32](https://user-images.githubusercontent.com/7095926/115927289-7aee2d80-a484-11eb-96fe-668e0d940de3.png)

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-35156

**Comment by amyblais** [comment]
@Michael-E-Rose A dev commented that this is likely expected. 
Does it work properly if you add a newline in between?

**Comment by amyblais** [comment]
Confirmed with devs that the original report and the other note https://github.com/mattermost/mattermost-server/issues/17502#issuecomment-827127968 are currently expected.

**Comment by Michael-E-Rose** [comment]
Some other rather ugly behavior is when I start my message with a quote. In this case the indent equals the length of my name. Aesthetically, this is just weird; Slack automatically starts the quote on the next line.

Must I report another issue for this?
