### ISSUE TITLE
Unread messages banner displays code

### ISSUE THREAD

**Issue by JoannaLe** [mattermost/mattermost-server#17519]
#### Summary
Unread messages banner ("Jump to ...") displays code

#### Steps to reproduce
i'm on version 5.33.3 of the Mattermost app.
1. Click on a channel with unread messages
2. The issue appears with the banner at the top of the channel underneath the header

#### Expected behavior
The banner should display information in clear English. It looks like the banner was intended to also display the number of unread messages as well.

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/22846643/116116776-2237b400-a681-11eb-9066-0555e0274d6e.png)
Clicking on the banner jumps to the most recent messages as expected.

#### Possible fixes
N/A

**Comment by amyblais** [comment]
This was listed as a known issue in the changelog for v5.33 and there is [a ticket](https://mattermost.atlassian.net/plugins/servlet/mobile?originPath=%2Fbrowse%2FMM-33829#issue/MM-33829) but it seems to have been closed recently as “cannot reproduce”. Can we reopen it? @lieut-data @Willyfrog

**Comment by Willyfrog** [comment]
@JoannaLe hi! and thanks for reporting, can you reproduce consistently or do you recall any details on the moment it happened. Also if you can reproduce, can you capture the console logs and share with us (if it contains sensitive data you can DM me the info in our [community server](https://community.mattermost.com))

@amyblais we can reopen, but I'd love any info on how to reproduce it as I've been unable to.

**Comment by JoannaLe** [comment]
Yes, this happens every time I go to a channel with unread messages since the last time I visited the channel. There are no error messages on the console, and element inspection doesn't reveal anything useful either - everything seems to be abstracted under `<webview id="mattermostView0" preload="file://etc" src="https://etc">`
![image](https://user-images.githubusercontent.com/22846643/116486048-58785d80-a852-11eb-8a18-b51c7d56d165.png)
