### ISSUE TITLE
Unable to join a public channel with 26-characters channel names from channel link

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-server#17515]
#### Summary
When clicking a public channel link with 26-characters channel name (e.g.:`~abcdef12345678901234567890`), displayed `Channel Not Found` error page and can't join the channel.

#### Steps to reproduce
1. Create a public channel with 26-characters channel name (e.g.: `abcdef12345678901234567890`)
2. Write channel link to the channel (e.g.: `~abcdef12345678901234567890`) in other channel
3. Other user who never join the channel clicks the channel link

#### Expected behavior
User will join the channel and see its contents

#### Observed behavior (that appears unintentional) 
Display `channel not found` error.
<img width="940" alt="スクリーンショット 2021-04-26 21 33 43" src="https://user-images.githubusercontent.com/1453749/116083424-8d13da00-a6d7-11eb-8211-9550ebf2f110.png">

And Chrome devtool records the request to `/api/v4/channels/${channel_id}` which resulted in 404 Not Found.
<img width="1760" alt="スクリーンショット 2021-04-26 21 36 53" src="https://user-images.githubusercontent.com/1453749/116083622-c8aea400-a6d7-11eb-887f-a909d0b1deb5.png">

#### Possible fixes
The **channel name** of channel link to 26-characters channel name is considered as **channel ID**. I think that It's caused by `getPathFromIdentifier`.

https://github.com/mattermost/mattermost-webapp/blob/3fe62b033135553ff22f16434c55657009182957/components/channel_layout/channel_identifier_router/actions.ts#L75-L84

I don't know a much about `mattermost-redux`, but `getOtherChannels` should return `true` here?

**Comment by amyblais** [comment]
@kaakaa Could this be related to https://github.com/mattermost/mattermost-server/issues/16939? (A ticket is here: https://mattermost.atlassian.net/browse/MM-32912)

**Comment by kaakaa** [comment]
Ah, i missed it. It seems to had been discussed about this issue in jira ticket.
Close this. Thanks @amyblais!
