### ISSUE TITLE
Error: Cannot find module 'imagemin-gifsicle'

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-server#17521]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bug report in one concise sentence

I downloaded the "WebApp" 5.34.2 package today and tried only "make run" but it failed. No problem until 5.33.3 and occurred since 5.34. I thought there was a problem with my current server and tried to install it on New Amazon Linux 2 but failed, either.

Server #1 : failed
- os : ubuntu 18.04
- node : v10.24.1
- npm : 7.9.0

Server #2 : failed
- os : amazon linux 2
- node : 14.16.1
- npm : 7.9.0

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

Error message was same, "imagemin-gifsicle" The reproduction is simple.
1. Create new machine.
2. Generate env (make user, folder and install node&npm and other.)
3. wget https://github.com/mattermost/mattermost-webapp/archive/refs/tags/v5.34.2.tar.gz
4. extract and make run. 

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

`Running mattermost Webapp for development
npm run run &

> mattermost-webapp@0.0.1 run
> webpack --progress --watch

fatal: not a git repository (or any of the parent directories): .git
95% emitting emit(node:14080) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
PublicPath: /static/
.
.
.

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  i18n/bg.9e2eff6ab491194ae5ca5c0e5e3d3b08.json (623 KiB)
  i18n/de.6393eec50e9937b7622f1ddda0c15368.json (396 KiB)
  i18n/es.d5f451b4cce3647f48d6eacc5d2f6e93.json (453 KiB)
  i18n/fr.c4f8ee04b6ce6014ff02071b7c07a54f.json (438 KiB)
  i18n/it.8f4faa56e400c1c36667e025e922619c.json (381 KiB)
  i18n/ja.758ee65ecdc2ca39a6bc9b152e272527.json (516 KiB)
  i18n/ko.06486c90eb45fa4e7f3c471f4875653e.json (339 KiB)
  i18n/nl.8be7fc9cd21ff2aa80a877f8e9e9abbd.json (448 KiB)
  i18n/pl.5dfee044283b921c66a7048d50a55198.json (361 KiB)
  i18n/pt-BR.71048a8cc69202e5e8e6e22550f1a3be.json (443 KiB)
  i18n/ro.f72f348c0337594dfd821d0893fb1336.json (454 KiB)
  i18n/ru.ff833a5f7cc699768661f2d3103eafb5.json (625 KiB)
  i18n/sv.fb95fa25501cb7595fffea889aa4a768.json (431 KiB)
  i18n/tr.c71cd3779a557da1d9d9b903cbdfc2f7.json (457 KiB)
  i18n/uk.e2f268bcfce78ad86d1d5613bc82e2c5.json (403 KiB)
  i18n/zh-TW.340c84542af074b74786974853402e6c.json (349 KiB)
  i18n/zh-CN.156f25983fd1b149a009636fcbd933ea.json (370 KiB)
  main.e9a9750509dfb40c3ead.js (33.8 MiB)
  pdfjsWorker.d87968cd0a9bde9c335e.js (4.11 MiB)
  components_root_index_js.8fe6c4f253750a0f675a.js (14.2 MiB)
  components_admin_console_index_ts.11ad53c0ee76b9d6e6b0.js (6.46 MiB)
  components_user_settings_index_ts.ff23b8b6b63606a196d5.js (1.2 MiB)
  vendors-node_modules_katex_dist_katex_js.798e9c371cfeaf99ccbc.js (1.52 MiB)
  components_backstage_index_js.f8aa08bda3f6efcb2194.js (1.21 MiB)
  vendors-node_modules_crypto-browserify_index_js.b881d19b493b2c1a2197.js (2.86 MiB)
  vendors-node_modules_react-color_lib_index_js.9934651c577b34ebeb67.js (794 KiB)
  vendors-node_modules_stripe_react-stripe-js_dist_react-stripe_umd_js-node_modules_stripe_stri-c927c7.b3bd93030e6665967893.js (11.1 MiB)
  vendors-node_modules_chart_js_dist_Chart_js-node_modules_core-js_modules_es_promise_finally_j-3e4fbe.2338863099a0cc7f9000.js (1.41 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (33.8 MiB)
      main.e9a9750509dfb40c3ead.js

ERROR in ./fonts/compass-icons/compass-icons.eot?93326238
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.module.exports (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/image-webpack-loader/index.js:72:20)
 @ ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./sass/styles.scss 38:0-95 161:74-104 162:74-104
 @ ./sass/styles.scss 2:12-157 9:17-24 13:15-29
 @ ./root.jsx 18:0-26

ERROR in ./fonts/compass-icons/compass-icons.svg?93326238
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.module.exports (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/image-webpack-loader/index.js:72:20)
 @ ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./sass/styles.scss 42:0-95 166:74-104
 @ ./sass/styles.scss 2:12-157 9:17-24 13:15-29
 @ ./root.jsx 18:0-26

ERROR in ./fonts/compass-icons/compass-icons.ttf?93326238
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.module.exports (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/image-webpack-loader/index.js:72:20)
 @ ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./sass/styles.scss 41:0-95 165:74-104
 @ ./sass/styles.scss 2:12-157 9:17-24 13:15-29
 @ ./root.jsx 18:0-26

ERROR in ./fonts/compass-icons/compass-icons.woff?93326238
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.module.exports (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/image-webpack-loader/index.js:72:20)
 @ ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./sass/styles.scss 40:0-96 164:74-104
 @ ./sass/styles.scss 2:12-157 9:17-24 13:15-29
 @ ./root.jsx 18:0-26
 .
 .
 .
ERROR in ./sounds/upstairs.mp3
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.module.exports (/home/mattermost/go/src/github.com/mattermost/release/mattermost-webapp-5.34.2/node_modules/image-webpack-loader/index.js:72:20)
 @ ./utils/utils.jsx 55:0-43 217:148-156
 @ ./root.jsx 20:0-59 40:8-17 48:2-19

webpack 5.20.2 compiled with 265 errors and 2 warnings in 21312 ms (fccf4b6801815ce37459)`

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

I don't have any good ideas.

Is there anything I missed for 5.34?

**Comment by amyblais** [comment]
@Gloriashield Would any of these previous threads help?
 - https://github.com/mattermost/mattermost-server/issues/17452
 - https://github.com/mattermost/mattermost-server/issues/17420

cc @hmhealey

**Comment by hmhealey** [comment]
To summarize those other issues, downgrading to Node 14 should hopefully fix these issues, but seeing as we're getting so many reports of this, I'm going to file an issue to fix this better. Obviously our image loader is the problem here, and I also saw issues with it once or twice when using NPM v7, but that was from a different dependency

**Comment by Gloriashield** [comment]
@amyblais 
Thank you! It was a mistake I didn't look for enough. It was same #17420. I could solve it : npm install gifsicle

@hmhealey 
I think it will be solved well. Thank you!

Have a nice day!
