### ISSUE TITLE
Fallback text is occasionally displayed alongside the attachment message text

### ISSUE THREAD

**Issue by tangtony** [mattermost/mattermost-server#17528]
#### Summary
When sending a message to Mattermost using a webhook, the fallback text is occasionally displayed alongside the message text:
<img width="250" src="https://user-images.githubusercontent.com/5085394/116266350-858d1900-a749-11eb-91ee-e7288366c489.png">

A few notable points:
* The above was seen on the web client
* Refreshing the web client causes the fallback text to disappear from the message
* In the mobile notification, the fallback text is displayed twice sometimes.

#### Steps to reproduce
Found on Mattermost Enterprise Edition - Version 5.31.3

Unsure what causes this to happen, but spamming the following curl command will usually cause it happen and will be seen in the web client.
```json
curl -X POST -H "Content-Type: application/json" -d "{\"channel\":\"test-channel\",\"attachments\":[{\"color\":\"danger\",\"text\":\"@all\",\"fallback\":\"This is the fallback text\"}]}" <Webhook URL>
```
#### Expected behavior
The fallback text should not be shown

#### Observed behavior (that appears unintentional) 
The fallback text is displayed alongside the formatted message. 

Another example where all of the various text fields are provided. It seems the fallback text is being added to the regular message text:
<img width="479" alt="mattermost-bug" src="https://user-images.githubusercontent.com/5085394/116280071-503af800-a756-11eb-81ee-5c29060b9d2e.PNG">
```json
curl -X POST -H "Content-Type: application/json" -d "{\"channel\":\"test-channel\",\"text\":\"Normal Text\",\"attachments\":[{\"color\":\"danger\",\"text\":\"attachment text @all\",\"fallback\":\"Fallback Text\",\"pretext\":\"Pretext\"}]}" <Webhook URL>
```

**Comment by amyblais** [comment]
@DHaussermann Are you able to reproduce this?

**Comment by amyblais** [comment]
@tangtony Does this reproduce on a more recent version of Mattermost?
