### ISSUE TITLE
[MM-8897] DND(do not disturb) scheduling for work hours and overriding DND for important messages

### ISSUE THREAD

**Issue by Dinoryong** [mattermost/mattermost-server#17547]
we initiate on new project #15640 
[our server repo link](https://github.com/SF03PJT/mattermost-server/tree/MM-8897)
[our web-app repo link](https://github.com/SF03PJT/mattermost-webapp/tree/MM-8898)
it's originally a gsoc idea [link](https://developers.mattermost.com/contribute/gsoc/#do-not-disturb-improvements)

our first design 
https://www.figma.com/file/YUa3E5iKzYypyoDw1UU1Ig/thumbnail?ver=thumbnails/f81b77de-2e48-4e35-974d-492d943072b3
![image](https://user-images.githubusercontent.com/65714228/116640010-c6349e80-a9a4-11eb-9628-644af1954605.png)

we'll be working on
1.  specifying working hours for dnd status improvement
2. overriding DND for important messages

Join us if you're intereted in !

**Comment by 5ujin** [comment]
like the idea! I'd like to join you
