### ISSUE TITLE
Timezone selection dropdown theming issue

### ISSUE THREAD

**Issue by darkLord19** [mattermost/mattermost-server#17552]
<img width="765" alt="Screenshot 2021-05-01 at 10 09 53 PM" src="https://user-images.githubusercontent.com/16662014/116788965-1d805f00-aaca-11eb-971a-6556c9bd928c.png">

**Comment by amyblais** [comment]
Thanks, ticket: https://mattermost.atlassian.net/browse/MM-35377.

**Comment by amyblais** [comment]
@darkLord19 Are you still able to reproduce this? If yes, on what version?

I was able to reproduce this last week, but not anymore.

**Comment by darkLord19** [comment]
@amyblais yes after testing now issue is present on community(v5.34) but looks to be fixed in community-daily(5.35)
