### ISSUE TITLE
DB issues when migrating from docker image app to enterprise edition

### ISSUE THREAD

**Issue by sbaloo9168** [mattermost/mattermost-server#17554]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Error in migration of mattermost from docker image 

#### Steps to reproduce
run a docker compose with
 mattermost/mattermost-prod-web:latest 
mattermost/mattermost-prod-db:latest (postgres db)
mattermost/mattermost-prod-app:latest

change the app image to the mattermost/mattermost-enterprise-edition:latest and restart

you will have error like :
{"level":"error","ts":1619959507.357612,"caller":"sqlstore/store.go:170","msg":"Failed to apply database migrations.","error":"migration failed: syntax error at or near \"NOT\" (column 17) in line 18: CREATE TABLE IF NOT EXISTS teams (\n    id VARCHAR(26) PRIMARY KEY,\n    createat bigint,\n    updateat bigint,\n    deleteat bigint,\n    displayname VARCHAR(64),\n    name VARCHAR(64),\n    description VARCHAR(255),\n    email VARCHAR(128),\n    type VARCHAR(255),\n    companyname VARCHAR(64),\n    alloweddomains VARCHAR(1000),\n    inviteid VARCHAR(32),\n    schemeid VARCHAR(26),\n    UNIQUE(name)\n);\n\nCREATE INDEX IF NOT EXISTS idx_teams_name ON teams (name) ;\nCREATE INDEX IF NOT EXISTS idx_teams_invite_id ON teams (inviteid);\nCREATE INDEX IF NOT EXISTS idx_teams_update_at ON teams (updateat);\nCREATE INDEX IF NOT EXISTS idx_teams_create_at ON teams (createat);\nCREATE INDEX IF NOT EXISTS idx_teams_delete_at ON teams (deleteat);\nCREATE INDEX IF NOT EXISTS idx_teams_scheme_id ON teams (schemeid);\n\nALTER TABLE teams ADD COLUMN IF NOT EXISTS allowopeninvite boolean;\nALTER TABLE teams ADD COLUMN IF NOT EXISTS lastteamiconupdate bigint;\nALTER TABLE teams ADD COLUMN IF NOT EXISTS description VARCHAR(255);\nALTER TABLE teams ADD COLUMN IF NOT EXISTS groupconstrained boolean;\n (details: pq: syntax error at or near \"NOT\")"}
{"level":"error","ts":1619959527.0474377,"caller":"sqlstore/store.go:170","msg":"Failed to apply database migrations.","error":"Dirty database version 1. Fix and force version."}
{"level":"error","ts":1619959548.1160693,"caller":"sqlstore/store.go:170","msg":"Failed to apply database migrations.","error":"Dirty database version 1. Fix and force version."}
{"level":"error","ts":1619959770.1233387,"caller":"sqlstore/store.go:170","msg":"Failed to apply database migrations.","error":"Dirty database version 1. Fix and force version."}

the trouble is here:
CREATE INDEX IF NOT EXISTS idx_teammembers_team_id ON TeamMembers (teamid);
sql execution said:
/* ERROR:  syntax error at or near "NOT"
LINE 1: CREATE INDEX IF NOT EXISTS idx_teammembers_team_id ON TeamMe...
                        ^ */

#### Expected behavior
Should do the migration with no issues

#### Observed behavior (that appears unintentional) 
No idea

**Comment by amyblais** [comment]
@cpanato @agnivade Are you familiar with this issue, or do you know who I could ask to take a look?

**Comment by cpanato** [comment]
i dont maybe @streamer45

**Comment by streamer45** [comment]
I think this is a known issues due to an outdated (and now unsupported) PostgreSQL version (<10). More info can be found in the repository home page: https://github.com/mattermost/mattermost-docker.

**Comment by sbaloo9168** [comment]
Thanks i will have a look. But so if i understand well the actual docker image for the mattermost/mattermost-prod-db:latest is not uptodate for now. It should be in posgres 10

**Comment by streamer45** [comment]
> Thanks i will have a look. But so if i understand well the actual docker image for the mattermost/mattermost-prod-db:latest is not uptodate for now. It should be in posgres 10

That's correct. Newer Mattermost versions support 10+.
