### ISSUE TITLE
command make run-server

### ISSUE THREAD

**Issue by yousef-soliman** [mattermost/mattermost-server#17568]
#### Summary
when run command `make run-server` it will show this error
```
go run ./build/docker-compose-generator/main.go mysql postgres inbucket  minio | docker-compose -f docker-compose.makefile.yml -f /dev/stdin run --rm start_dependencies
Pulling inbucket (jhillyerd/inbucket:release-1.2.0)...
ERROR: pull access denied for jhillyerd/inbucket, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:174: start-docker] Error 1

```
#### Steps to reproduce
`make run-server` for first time

#### Possible fixes
i think the docker image `jhillyerd/inbucket` is deleted we should replace it with `inbucket/inbucket`
i have search for this docker image but i couldn't find it

**Comment by darkLord19** [comment]
It's been updated in latest master, you should pull latest commits and try again.
