### ISSUE TITLE
cycling back with arrows

### ISSUE THREAD

**Issue by ggrrll** [mattermost/mattermost-server#17575]
are there progresses on this? 

https://mattermost.uservoice.com/forums/306457-general/suggestions/13744383-make-up-arrow-behavior-configurable 
(it was on 2016...)

(btw, slack has that, and it is very handy :) )

**Comment by ggrrll** [comment]
(sorry, my fault! -- you are totally right)

**Comment by amyblais** [comment]
Thank you for upvoting the feature request,
