### ISSUE TITLE
Feature request - Integration with WebDAV

### ISSUE THREAD

**Issue by alexandremottier** [mattermost/mattermost-server#17628]
I don't think there's already a request for this but it would be wonderful to be able to synchronize presence status with a calendar.

I saw this in the forum but no response : [Forum item](https://forum.mattermost.org/t/syncing-mattermost-user-status-with-webdav-calendar/10132)

If you need more explanation about that request, please let me know by responding to that issue.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @alexandremottier,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Closing this for now, but hopefully you will be able to open a feature request on uservoice,
