### ISSUE TITLE
iPad OS smiles in horizontal position (with magic keyboard, for example)

### ISSUE THREAD

**Issue by alexander-potemkin** [mattermost/mattermost-server#17637]
#### Summary
Not all smiles are visible in Mattermost iOS app on iPad OS. For example, you won't see thank you smile - 🙏
<img width="704" alt="MM smiles" src="https://user-images.githubusercontent.com/2323840/118662618-d2b85400-b7f8-11eb-9d16-e80bb59ccf22.png">

#### Steps to reproduce
Open Mattermost, put (or leave) your iPad in horizontal position (in my case, that's what happens, when I attach it to my magic keyboard), open smiles screen - get that.

#### Expected behavior
See all smiles, like it's happening in vertical position.

#### Observed behavior (that appears unintentional) 
Please, see the screenshot below. It feels, like something inside the app doesn't react on the fact, that the iPad is now horizontal, and hence not all of the smiles appear in place.

**Comment by amyblais** [comment]
@josephbaylon May I ask your help to help try repro any of these iPad reports (this one ^, https://github.com/mattermost/mattermost-server/issues/17638, and https://github.com/mattermost/mattermost-server/issues/17639)

**Comment by josephbaylon** [comment]
@amyblais I can reproduce this issue on iPad Pro (12.9-inch) 5th generation.

**Comment by amyblais** [comment]
Thanks, opened a ticket https://mattermost.atlassian.net/browse/MM-35846
