### ISSUE TITLE
collapsed thread - up arrow edits main posting not last reply

### ISSUE THREAD

**Issue by dovholuknf** [mattermost/mattermost-server#17641]
#### Summary
in a collapsed thread, hitting the up arrow key to edit your last reply will edit the main posting (the post that started the thread) and not my 'last reply'.

#### Steps to reproduce
- Start a collapsed thread 
- get someone else to make a comment
- reply to the comment
- hit up arrow
- observe you're editing the main post and not the last reply from 'you'

#### Expected behavior
I expected to edit my last reply

#### Observed behavior (that appears unintentional) 
I saw the main post get edited

#### Possible fixes

I am using the browser to access the daily using the brave browser:
https://community-daily.mattermost.com/core/channels/folded-reply-threads

Specifically: https://community-daily.mattermost.com/core/pl/tmatpsy3ztn6jbdiq9iaczys4w

Image showing the issue follows:
![image](https://user-images.githubusercontent.com/46322585/118685550-329b0480-b7d1-11eb-8344-fe29b044cc8f.png)

**Comment by esethna** [comment]
Thanks! Filed a bug here: https://mattermost.atlassian.net/browse/MM-35840

@dovholuknf how is your experience with the feature aside from the bugs and known issues?
