### ISSUE TITLE
Caching issue with status emojis

### ISSUE THREAD

**Issue by pferreir** [mattermost/mattermost-server#17664]
#### Summary
When I set back a status which uses a custom emoji (after some days set to something else) the emoji doesn't show up.

#### Steps to reproduce
1. Create a status with a custom emoji
![image](https://user-images.githubusercontent.com/2699/119113287-3f179b00-ba25-11eb-8906-674c5ed1a24f.png)

2. Clear your status or set a different one
3. Come back like 1 day later and try to set back your old status
4. The status has lost its emoji
![image](https://user-images.githubusercontent.com/2699/119113324-48a10300-ba25-11eb-87a9-2ce0a5980aae.png)
5. As soon as you include the custom emoji e.g. in a message, it just magically shows up

#### Expected behavior
I would expect the emoji to be visible.

#### Observed behavior (that appears unintentional) 
The emoji seems to not be fetched client-side, unless you force it by including it e.g. in amessage.

**Comment by amyblais** [comment]
@pferreir What Mattermost server version are you on? What OS and version are you on?

**Comment by pferreir** [comment]
@amyblais It's v5.34.2, I'm on Firefox 88.0.1 on macOS.

I haven't tried reproducing on the community server. I will give it a try, but it general takes a few hours/days for the problem to appear.

**Comment by pferreir** [comment]
Oh, it actually just happened on the community server:

![image](https://user-images.githubusercontent.com/2699/119140116-1521a100-ba44-11eb-870b-0d61bb64b999.png)

vs.

![image](https://user-images.githubusercontent.com/2699/119140183-2b2f6180-ba44-11eb-9cec-a1b6aae922f8.png)

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-35930.
