### ISSUE TITLE
Persistent unread badge on sidebar hamburger menu

### ISSUE THREAD

**Issue by wezm** [mattermost/mattermost-server#17689]
#### Summary

There is a persistent red badge in the sidebar hamburger menu that I can seem to dismiss. It's happening for my user on two different Mattermost instances I run but not other users. I am the admin of the instances.

#### Steps to reproduce

1. Log into Mattermost in a browser
2. Observe unread badge in menu:

![Screenshot_2021-05-28 Town Square - Rust Melbourne Rust Melbourne](https://user-images.githubusercontent.com/21787/119911338-7f829600-bf9c-11eb-9ad2-97f947c3a095.png)
![Screenshot_2021-05-28 Mornings - Wizards League Mattermost](https://user-images.githubusercontent.com/21787/119911339-80b3c300-bf9c-11eb-8da1-400a1fdfe803.png)

This started happening after I upgraded from 5.33.0 to 5.35.1.

The only thing in the logs that seems possibly relevant is this line:

```
{"level":"warn","ts":1621563471.2294595,"caller":"app/channel.go:2562","msg":"Failed to get membership","error":"resource: ChannelMember id: channelId=83nd1zcakt878kceyudpxbz8nc, userId=6onqad66hir48jj4egwcegq1yw"}
```

The `userId` corresponds to my user.

**Environment:**

* Mattermost: version 5.35.1 downloaded from https://releases.mattermost.com/5.35.1/mattermost-team-5.35.1-linux-amd64.tar.gz
* Database: PostgreSQL 12.7
* Browser: Firefox 88.0.1 on Linux

#### Expected behavior

1. There is an obvious reason for the badge and there is some way to dismiss it.

#### Observed behavior (that appears unintentional) 

1. The badge is always present.

#### Possible fixes

None so far. I've tried:

* Hard refresh
* Clearing all cookies and site data
* Logging out and in
* Tried using a different browser (Chromium)

**Comment by amyblais** [comment]
@wezm Does the badge go away when you enable Plugin Marketplace via https://docs.mattermost.com/administration/plugins.html#marketplace-server, and then go to Main Menu > Plugin Marketplace?

This looks related to https://mattermost.atlassian.net/browse/MM-32882.

**Comment by wezm** [comment]
Yes! Thank you @amyblais. Plugin Marketplace was already on but Enable Plugins was not:

<img width="924" alt="Screenshot_2021-06-02 System Console - Mattermost" src="https://user-images.githubusercontent.com/21787/120399589-ab788f80-c37f-11eb-9189-fa726a12fe71.png">

After turning that on, and returning to the main area there was a Marketplace item in the hamburger menu with a red dot, visiting that cleared the dot on the menu :tada: 

<img width="244" alt="Screenshot from 2021-06-02 08-49-15" src="https://user-images.githubusercontent.com/21787/120399680-d6fb7a00-c37f-11eb-842d-b5e096dca7b6.png">

Sounds like there is a bug in the implementation of that linked Jira ticket. Thanks for your assistance.

**Comment by amyblais** [comment]
Yes, sounds like a bug, @DHaussermann @catalintomai can you confirm?

If Enable Plugins is disabled, then upgrading to v5.35 will cause a persistent unread badge which can't be dismissed because the Plugin Marketplace option is not visible in the hamburger menu. https://mattermost.atlassian.net/browse/MM-32882

**Comment by catalintomai** [comment]
@amyblais , yes, it is likely a bug, we should not be showing the persistent unread badge if the EnablePlugins or the EnableMarketplace flags are false. I'll start working on a fix, @DHaussermann , please open a ticket. Thanks.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-36160

**Comment by DHaussermann** [comment]
Thanks for creating the ticket @amyblais I was also able to reproduce this just now on `master`  branch.
