### ISSUE TITLE
Document content extractor thinks ODTs are ZIPs and won't extract their contents

### ISSUE THREAD

**Issue by willmatheson** [mattermost/mattermost-server#17688]
#### Summary
5.35 brings the exciting feature of being able to search document content, not just file names. Unfortunately, I cannot get this to work with ODTs, which is important to us as we are a LibreOffice shop. Our Mattermost instance is running on an Ubuntu 18.04 virtual machine.

#### Steps to reproduce
1. Upload a LibreOffice Writer or potentially other ODT with some text that isn't also in the filename. Or run the mattermost CLI to extract the content ( extract-documents-content ).**
2. Using the web desktop client, search for aforementioned text.

#### Expected behavior
When searching for that text that isn't also in the filename, the ODT should appear as a File result.

#### Observed behavior (that appears unintentional) 
The ODT does not appear as a File result, perhaps because the document contents have not been extracted as they should be.

** - A warning like this appears in the terminal after every alleged ODT 'extraction': {"level":"warn","ts":1622139271.0618308,"caller":"docextractor/combine.go:35","msg":"unable to extract file content","error":"error unzipping data: zip: not a valid zip file"}

**Comment by amyblais** [comment]
@jespino Can you help take a look?
Is this fixed via https://github.com/mattermost/mattermost-server/pull/17675?

**Comment by jespino** [comment]
@amyblais, no it is not, it is another problem.

**Comment by jespino** [comment]
@willmatheson I found the problem and here is the PR #17700

**Comment by amyblais** [comment]
5.35.2 dot release is now available with this fix,
