### ISSUE TITLE
Mattermost slack_attachment duplication rendered in Webapp

### ISSUE THREAD

**Issue by renchili** [mattermost/mattermost-server#17698]
#### Summary
the text been rendered multiple times 
![image](https://user-images.githubusercontent.com/33677006/120305720-ac6bdb80-c303-11eb-9b83-7e48465825da.png)
After ctrl+F5 it will return normal in user's browser
#### Steps to reproduce
call mattermost 5.31.3 by  using grafana slack notification
this is not targeting 1 specific grafana version. we have 3 different versions all will duplicate

#### Expected behavior
display normally

#### Observed behavior (that appears unintentional) 
as screenshot show duplication

#### Mattermost info
![image](https://user-images.githubusercontent.com/33677006/120306049-09679180-c304-11eb-8274-64b44f899934.png)
#### Server hosted mattermost
ubuntu  mattermost-worker-live-10-129-9-36 4.15.0-42 #46~16.04.1+4

**Comment by amyblais** [comment]
We have a ticket here that seems related: https://mattermost.atlassian.net/browse/MM-30980. The ticket refers to Jira but it can happen with any messages with fallback text.

**Comment by renchili** [comment]
@amyblais  hi I see in the ticket that the fix is only for 5.37 at 1 month later. 
Question :
1 is that mean the LSV no longer LSV?  we can only use the latest version?
2 why an issue such impact to user need 1 month to fix and such low priority?

**Comment by renchili** [comment]
we are using the 5.31 ESR  but, it seems no support was made on it and already not in maintenance?
![image](https://user-images.githubusercontent.com/33677006/120950554-9b92ee00-c779-11eb-8ac0-eed9827abcb1.png)

**Comment by amyblais** [comment]
@renchili Sounds good, we'll take into consideration backporting this to v5.31, please stay tuned.

**Comment by amyblais** [comment]
This has been backported to v5.31.6,
