### ISSUE TITLE
Markdown preview option shows up in read-only channels

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#17694]
#### Summary
Markdown preview option shows up in read-only channels. It should not though as it's only of use when a user can enter and edit messages.

#### Steps to reproduce
Navigate to any read-only channel in Mattermost. For example, the Reception channel on Community.

#### Expected behavior
Markdown Preview option show not appear in read-only channels

#### Observed behavior (that appears unintentional) 
Markdown Preview option does appear in read-only channels

#### Possible fixes
Haven't seen the code but can check it out.

**Comment by amyblais** [comment]
https://mattermost.atlassian.net/browse/MM-36109
