### ISSUE TITLE
MMCTL - Help text examples differ from actual flags

### ISSUE THREAD

**Issue by hackercat3211** [mattermost/mattermost-server#17693]
#### Summary
The examples for creating a user via mmctl use flags containing a hyphen instead of an underscore.

#### Steps to reproduce
On the command line, run 'mmctl user create --help

#### Expected behavior
When the user executes the command to get the usage text (help) for creating a user, the flags in the examples provided should match the actual flags that are accepted.

#### Observed behavior (that appears unintentional) 
The flags in the examples in the usage text contain hyphens instead of underscores (see attached image)

#### Possible fixes
Update the usage text to have the proper flags in the examples.
![mmctl](https://user-images.githubusercontent.com/85130511/120230454-545aa980-c21d-11eb-9102-bd887698879d.png)

**Comment by agnivade** [comment]
Indeed, great catch @hackercat3211 ! Would you be open to send a PR to fix this?

**Comment by amyblais** [comment]
Ticket for reference: https://mattermost.atlassian.net/browse/MM-36108.

**Comment by hackercat3211** [comment]
> Indeed, great catch @hackercat3211 ! Would you be open to send a PR to fix this?

I apologize for not responding sooner.  I have been really busy with work.  I would love to submit a PR for this.  I will work on it soon.
