### ISSUE TITLE
Crazy idea - what about editing my own messages in one click - just like in text editors

### ISSUE THREAD

**Issue by tchv71** [mattermost/mattermost-server#17704]
To edit my own messages I need go to the menu on the right or press Up key, but only for the last message
Simple don't allow editing for messages from others and click-and-edit for my own inplace

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @tchv71,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
