### ISSUE TITLE
Search field does not get focus when clicking on magnifier glasse (Mac desktop)

### ISSUE THREAD

**Issue by mwid2020** [mattermost/mattermost-server#17705]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Search field does not get focus when clicking on magnifier glasse (Mac desktop)

**Environment**
- Operating System: macOS 10.15.7
- Mattermost Desktop App version: 4.6.2
- Mattermost Server version: 4.6.2.7883 

**Steps to reproduce**
Click on the magnifier glass to start a search

**Expected behavior**
The focus is set on the search field.

**Observed behavior**
The focus remains on the messaging field.

**Possible fixes**

**Comment by curiousercreative** [comment]
> We have a ticket open for this here: https://mattermost.atlassian.net/browse/MM-35713.

The linked ticket appears to have been closed and in the Mattermost chat, I see that the search UI has moved away from the sidebar search pane, obsoleting this UX.
