### ISSUE TITLE
Upload .jpeg in Linux

### ISSUE THREAD

**Issue by neallred** [mattermost/mattermost-server#17728]
#### Summary
On Pop-OS Linux & Chromium, I am unable to upload `.jpeg` files, only `.jpg` files.

#### Steps to reproduce

Mattermost version info (standard make/docker compose dev setup):
```
Mattermost Version: dev
Database Schema Version: 5.36.0
Database: postgres
```

OS Version:
```
head -2 /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
```

Browser version:
```
Chromium: 83.0.4103.116 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)
Revision: 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS: Linux
JavaScript: V8 8.3.110.13
Flash: (Disabled)
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Command Line: /usr/lib/chromium/chromium --show-component-extension-options --enable-gpu-rasterization --no-default-browser-check --disable-pings --media-router=0 --enable-remote-extensions --load-extension --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --file-url-path-alias=/gen=/usr/lib/chromium/gen
Executable Path: /usr/lib/chromium/chromium
Profile Path: /home/n/.config/chromium/Default
```

1. Open the user menu in the top left.
2. Select Account Settings.
3. Click the Edit text for Profile Picture.
4. Click Select.
5. Use the Operating System native UI to browse to a folder containing both `.jpeg` and `.jpg` files.
6. Observe that only `.jpg` files are listed.

![file-types-before](https://user-images.githubusercontent.com/13738432/120875739-06260d00-c573-11eb-97ac-79dde026ef1a.png)

#### Expected behavior

Be able to upload files ending in `.jpeg`

#### Observed behavior (that appears unintentional)

Was only able to upload files ending in `.jpg`, even though identical files (except for filename extension) existed on disk in the same folder.

#### Possible fixes

This has been discussed before, and it was thought to be fixed, although there was uncertainty around whether it still happened on other platforms:

https://mattermost.atlassian.net/browse/MM-1921
https://github.com/mattermost/mattermost-server/issues/1874

I was able to get it working locally by making the following code changes:
https://github.com/mattermost/mattermost-webapp/compare/master...neallred:jpegs-r-kewl

I tested it for profile picture upload, but not for the other image uploaders. If this is a change we want to make, I'd need to confirm those spots still work, too.

![file-types-after](https://user-images.githubusercontent.com/13738432/120875734-00302c00-c573-11eb-970b-477319308965.png)

**Comment by amyblais** [comment]
@neallred Are you interesting in opening a PR for this, or would you like me to open a new ticket for our team?

**Comment by neallred** [comment]
Yeah, I'll open a PR!

**Comment by neallred** [comment]
Fixed in https://github.com/mattermost/mattermost-webapp/pull/8224
