### ISSUE TITLE
ESR was already been depercated?

### ISSUE THREAD

**Issue by renchili** [mattermost/mattermost-server#17738]
This is not related to any functions
Just many newly imported features are so-called is introduced into new version instead put a patch to ESR
is it normal?
![image](https://user-images.githubusercontent.com/33677006/120950748-fa586780-c779-11eb-8177-3807370a74e0.png)

I think this version still be a validated version.

And as I see now Mattermost puts more priorities on features and functionalities instead of qualities.

**Comment by amyblais** [comment]
Hi @renchili, as mentioned in the [ESR documentation](https://docs.mattermost.com/administration/extended-support-release.html), Mattermost backports high severity or high impact security fixes to the previous three monthly releases. Extended Support Releases (ESRs) are releases that will receive backports for security fixes and major bug fixes for the length of their life cycle. New features are not backported to the ESR.
