### ISSUE TITLE
emoji autocomplete not working

### ISSUE THREAD

**Issue by Adesfire** [mattermost/mattermost-server#17772]
#### Summary
Using the web interface of the mattermost-5.35.2 version, pressing ":" doesn't bring up the emoji autocomplete modal as expected.

### Environment Information
  - Device Name: Windows computer / Google Chrome
  - OS Version: 21H1 / Google Version 91.0.4472.101 (Official Build) (64-bit)
  - Mattermost App Version: mattermost-5.35.2
  - Mattermost Server Version: mattermost-5.35.2

#### Steps to reproduce
Deploy the package from here: https://releases.mattermost.com/5.35.2/mattermost-5.35.2-linux-amd64.tar.gz?src=docker

#### Expected behavior
While writing a message, typing : should display an emoji modal to pick one from.

#### Observed behavior (that appears unintentional)
Nothing happens

#### Possible fixes
No idea.

Thank you.

**Comment by amyblais** [comment]
@Adesfire Are you using Docker? Do you reproduce it on our [community server here](https://community.mattermost.com/core/channels/release-process)?

**Comment by amyblais** [comment]
@Adesfire Here are the instructions for using emojis: https://docs.mattermost.com/help/messaging/emoji.html#adding-emojis-to-messages.

"...open the emoji autocomplete by typing : followed by at least two characters of the word describing the emoji."

**Comment by Adesfire** [comment]
Hi everyone,
my mistake, I was not typing as much chars as it requires to popup...
Everything works fine, I apologize.
