### ISSUE TITLE
Format for sending colored text

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#17780]
Hello dear friends
there is no format for coloring part of the text !!! 
Please ....

Colored text is very necessary to send a message and emphasis

We are <color = green>green</color> with envy

@tbalthazar @mauricio @cored

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback.  @majidit 

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

-----

As mentioned earlier, please also refrain from at-mentioning specific individuals in your posts, given they may not be working at Mattermost or be subject matter experts. The core team and the community regularly review issues in this repository.
