### ISSUE TITLE
Limited length of roles column can break user logins and other features

### ISSUE THREAD

**Issue by opalmer** [mattermost/mattermost-server#17788]
#### Summary
If a user has multiple system roles assigned this can result in the session token having a `roles` field that is longer than the `session.roles` column allows in the database. When this happens all logins that create a new session will be rejected for that user and the server will log the following error message:

```
{"level":"error","ts":1623799834.4000835,"caller":"web/saml.go:167","msg":"CreateSession: Unable to save the session., failed to save Session with id=REDACTED: pq: value too long for type character varying(64)"}
```

In our case, we created a read-only admin role and assigned it to the user resulting in a `roles` field that was 82 characters in length when added to the other permissions:

`system_user system_user_access_token system_post_all_public system_read_only_admin`

#### Steps to reproduce
1. Create a user
2. Create one or more custom system roles.
3. Assign these role(s) to a user.
4. Repeat steps 2 & 3 until the `roles` field is longer than 64 characters and the user is no longer able to login.

#### Expected behavior
1. Adding multiple roles to a user should not break logins.
2. Though indirect here, there shouldn't be a limit to the number of roles you can assign to a user

#### Observed behavior (that appears unintentional) 
See summary.

#### Possible fixes
Update the schema to support more than 64 characters or remove the limit on the `roles` columns? The session table was the place I encountered this problem but there might be others. A quick search yielded a couple of different places to potentially look into:
 - https://github.com/mattermost/mattermost-server/blob/daec0b3/scripts/mattermost-postgresql-5.0.sql#L69
 - https://github.com/mattermost/mattermost-server/blob/daec0b3/scripts/mattermost-postgresql-5.0.sql#L490
 - https://github.com/mattermost/mattermost-server/blob/daec0b3/scripts/mattermost-postgresql-5.0.sql#L532

As stop-gap, a warning dialog box in the admin interface when adding roles or an update to documentation could have also prevented this from happening.

**Comment by agnivade** [comment]
Thanks for creating the issue @opalmer ! Indeed, it looks like the `Roles` field in the `users` table was bumped to 256 [here](https://github.com/mattermost/mattermost-server/commit/5da5c0bbfb80cb5c9cf2699f42d17decc2d60f5b), but the corresponding column in the sessions table was not updated.

I have created a ticket here: https://mattermost.atlassian.net/browse/MM-36472.

**Comment by opalmer** [comment]
Thanks!!!
