### ISSUE TITLE
Dark theme: "Set a status" button hard to read

### ISSUE THREAD

**Issue by chruss2** [mattermost/mattermost-server#17802]
#### Summary
When you click on your own name in a chat, the "Set a status" button is hard to read.

#### Steps to reproduce
Ensure you have cleared your status.
Click on your own name in a chat room.
"Set a status" button uses a light font color on a white background in dark theme.

#### Expected behavior
"Set a status" button is readable in both dark and light themes.

#### Observed behavior (that appears unintentional) 
"Set a status" button uses a light font color on a white background in dark theme.
<img width="727" alt="Screen Shot 2021-06-19 at 2 20 29 PM" src="https://user-images.githubusercontent.com/8879219/122652188-73a57200-d10b-11eb-8d7d-081633b6efc7.png">

**Comment by amyblais** [comment]
This is fixed in the latest v5.36.0 release,
