### ISSUE TITLE
Emoji picker shows no emojis when adding reaction

### ISSUE THREAD

**Issue by daniel-jirca** [mattermost/mattermost-server#17805]
#### Summary
When adding a reaction to a post, the emoji picker popup does not show any emojis in any of the categories and displays the message "No results for "" Check the spelling or try another search"

#### Steps to reproduce
I tested using Firefox 89 and Chrome 91. Server version is Mattermost Team Edition 
```
Build Hash: faf9e8725b94f7a7bfb19547b49d770ff81f45a5
Webapp Build Hash: 969126b621d7bdbf25899872e2ed0b32285645ec
Build Date: Fri Jun 18 20:05:20 UTC 2021
Mattermost Version: master
Database Schema Version: 5.36.0
Database: postgres
```
To reproduce the issue just use the add reaction button beneath or to the right of any post.

#### Expected behavior
After clicking the add reaction button and the emoji picker popup appears, I expect the current emoji category to be filled with emojis. Also when clicking another category, a list of emojis should appear in the emoji picker.

#### Observed behavior (that appears unintentional) 
 In the current state the picker seems to open up with a blank string search which yields no results.

![image](https://user-images.githubusercontent.com/2178486/122673687-4f649680-d1da-11eb-9545-099f93354367.png)
![image](https://user-images.githubusercontent.com/2178486/122673701-5be8ef00-d1da-11eb-963b-48b171eb71c9.png)

**Comment by amyblais** [comment]
@Willyfrog @jgilliam17 Are you able to reproduce this on master and is this related to the Emoji 13 update?

**Comment by Willyfrog** [comment]
I might have this fixed in the [emoji-picker PR](https://github.com/mattermost/mattermost-webapp/pull/8282), we'll need to double check once that's merged

**Comment by jgilliam17** [comment]
I was able to see it for a brief moment before emoji picker loaded. I will re-test on the PR Guillermo mentioned.

**Comment by amyblais** [comment]
@daniel-jirca Does this issue repro for you on latest master? The PR mentioned above is merged https://github.com/mattermost/mattermost-webapp/pull/8282.

**Comment by daniel-jirca** [comment]
The bug is squashed in the current master version!
Thanks!

**Comment by Willyfrog** [comment]
thanks for double checking! I'm glad it worked for you :)
