### ISSUE TITLE
Copy from Google Sheet /Excel on Mac OS then past into mattermost will eat blank lines

### ISSUE THREAD

**Issue by renchili** [mattermost/mattermost-server#17820]
#### Summary
copy past on MAC OS from google sheet to mattermost  will eat white lines

#### Steps to reproduce

![image](https://user-images.githubusercontent.com/33677006/122910615-fb4be480-d388-11eb-921d-3d22c9eff26b.png)
it become
this
![image](https://user-images.githubusercontent.com/33677006/122910697-1585c280-d389-11eb-87ae-8082cd18af6f.png)

https://user-images.githubusercontent.com/33677006/122913965-b5911b00-d38c-11eb-9270-b0447b286292.mov

#### Expected behavior
as we know there needs 1 blank line to keep markdown work please check what happened

#### Observed behavior (that appears unintentional) 
as images show

**Comment by amyblais** [comment]
@hmhealey Is this a bug or expected?

**Comment by renchili** [comment]
for more information, this is not reproducible on Window OS

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-36619

**Comment by renchili** [comment]
any update 
it takes too long time

**Comment by amyblais** [comment]
A dev left a note in the Jira ticket saying that this will be addressed in the future as part of a larger effort around multiple paste issues.

**Comment by amyblais** [comment]
This has been fixed,
