### ISSUE TITLE
[BUG/ISSUE] Custom emojis don't load 

### ISSUE THREAD

**Issue by PxBCPG** [mattermost/mattermost-server#17836]
1. Confirm you’re filing a new issue. [Search existing tickets in Jira]

✅ 

2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy]

✅ 

3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary

Custom emoji don't load.

#### Steps to reproduce
Latest version of MM

#### Expected behavior

I can't see custom emojis (whatever the client is). 
The only way to do so is to click on the emoji button for them to be loaded. 

#### Observed behavior (that appears unintentional) 
This is not a problem with my reverse proxy (doesn't work in local mode)

#### Possible fixes
I really don't know

**Comment by amyblais** [comment]
@PxBCPG Can you help confirm your Mattermost server version, and what device and browser you're using?

**Comment by PxBCPG** [comment]
Latest version of MM server. 
For the emojis, it's universal

**Comment by amyblais** [comment]
Please re-open this issue or let me know if the problem persists on a recent Mattermost server version,
