### ISSUE TITLE
reply_count = 0 always returned for GET single Post on /posts/<postid> api

### ISSUE THREAD

**Issue by source-punk** [mattermost/mattermost-server#17834]
#### Summary
Fetching a single post using /posts/<postid> always returns `reply_count` field as 0.

#### Steps to reproduce
for Release 5.35.2, GET a single post with replies using /posts/<postid> and the returned reply_count is always 0 (due to golang initializing the value to empty default in returned model.Post?)

#### Expected behavior
Same as above. Its just a single GET call to a Message Post.

#### Observed behavior (that appears unintentional) 
No errors, just reply_count = 0 is returned always, even if that post is a root for multiple other posts.

#### Possible fixes
`func (s *SqlPostStore) GetSingle(id string, inclDeleted bool) (*model.Post, error)` method in `store/sqlstore/post_store.go` doesn't create the correct sql query with `count(id)`.

Please check the `func (s *SqlPostStore) Get(ctx context.Context, id string, skipFetchThreads, collapsedThreads, collapsedThreadsExtended bool, userID string) (*model.PostList, error)` in the same file for how the query should have been constructed for reference.

**Comment by amyblais** [comment]
@jwilander / @koox00 Is this related to collapsed reply threads?

**Comment by source-punk** [comment]
I also have a commit prepped using the sqlbuilder wrapper in mattermost, I’ll create a pr for it if you all think it’s an issue or needs to be fixed. I’m basically using something similar to  replyCountSubQuery to select the reply_count column.

**Comment by jwilander** [comment]
@amyblais yes this would be CRT related. Feel free to file a JIRA bug for it and assign to Apollo.

@source-punk do you happen to have the experimental feature flag for Collapsed Threads turned on?

**Comment by source-punk** [comment]
@jwilander yeah collapsed threads on and working on channel, thread apis.

Also, like I said I have a commit in my local build that fixes this issue and I can create a pr today.

**Comment by jwilander** [comment]
We'd love a PR for that :)

**Comment by amyblais** [comment]
Opened a ticket also: https://mattermost.atlassian.net/browse/MM-36711

**Comment by source-punk** [comment]
Thanks, I have signed that contribution agreement and will raise a pr to master in an hr or so.
