### ISSUE TITLE
Error message when doing request to API to /users/{user_id}

### ISSUE THREAD

**Issue by hammenm** [mattermost/mattermost-server#17858]
#### Summary
Cannot edit user information with the API for /users/{id} requests. I get the error `model.user.is_valid.create_at.app_error`

#### Steps to reproduce
Send a PUT request to http://your-mattermost-url.com/api/v4/users/{user_id}

#### Expected behavior
User modified

#### Observed behavior (that appears unintentional) 
Error message:

```
{
    "id": "model.user.is_valid.create_at.app_error",
    "message": "Create at must be a valid time.",
    "detailed_error": "",
    "request_id": "5bf7uc1caidbix8pzohpcbe43c",
    "status_code": 400
}
```

#### Possible fixes
This happens after an upgrade from 5.31.1 to 5.32.1. Maybe the upgrade broke something ? Is the database schema correct ?

**Comment by amyblais** [comment]
@hammenm Does this reproduce on a more recent version, such as 5.36?
@agnivade Could this be a bug?

**Comment by agnivade** [comment]
Thanks, I will take a look.

**Comment by hammenm** [comment]
@amyblais we have not done the test on a 5.36 server. We notice this behavior on our production server. Yesterday, we upgraded to 5.33.5 and the issue is still here.
We want to upgrade our server version by version every week. If this is okay for you, I can tell you if we have the same issue on 5.36 in 3 weeks.

I wanted to expose this issue already, but this is not critical for us. May you would like to wait 3 weeks for us to confirm the behavior on 5.36 ?

**Comment by agnivade** [comment]
@hammenm - It seems like you are not setting the `create_at` field in the user json body. Can you show me the full curl request that you are making? The behavior hasn't changed from 5.31 to 5.32. I can see the failure in both versions.

However, our API documentation is [incorrect](https://api.mattermost.com/#operation/UpdateUser) as it does not say that `create_at` is a required field for updating a user.

If you are looking to only update new fields, keeping old fields untouched, you might want to use the [patch](https://api.mattermost.com/#operation/PatchUser) API. The update API is to be used for sending entire user body.

**Comment by hammenm** [comment]
Hello @agnivade 

Thank you for this answer!

I should have send you the curl request before. My mistake was that I actually added the `create_at` field, but it was a string parameter and not an integer... I now did the request with this correction and it worked!

It was definitly my mistake, and it was not coming from Mattermost.

Thank you for your help! 🙂

**Comment by agnivade** [comment]
No worries :) I will create a separate HW ticket to fix our documentation.
