### ISSUE TITLE
Uneven rendering of attachment fields (Web and Desktop)

### ISSUE THREAD

**Issue by Pezhvak** [mattermost/mattermost-server#17859]
#### Summary
Using `short` attribute for multiple fields in message attachments renders uneven. (both web and desktop apps but it renders correctly in mobile apps)

#### Steps to reproduce
Using version 5.36.0, try to send this attachment with a message using API:

```
[

    'author_name' => 'Some Name',
    'title'       => 'Title',
    'text'        => 'Some text',
    'fields'      => [
        ['short' => false, 'title' => 'Assignee', 'value' => 'Assignee...'],
        ['short' => true, 'title' => 'Status', 'value' => 'Status here...'],
        ['short' => true, 'title' => 'Sprint', 'value' => 'Sprint name...'],
        ['short' => true, 'title' => 'Type', 'value' => 'Type of the issue'],
        ['short' => true, 'title' => 'priority', 'value' => 'Normal'],
        ['short' => true, 'title' => 'severity', 'value' => 'Normal'],
    ],
],
```

#### Expected behavior
Columns to align evenly under each-other as it is in mobile versions.

#### Observed behavior (that appears unintentional) 

MacOS and web version: (Renders uneven)
![Screen Shot 2021-07-02 at 12 36 28 PM](https://user-images.githubusercontent.com/3134479/124242620-2cb77380-db32-11eb-9f55-742062076fd2.png)

Android App: (renders correctly) 
![IMAGE 2021-07-02 12:37:49](https://user-images.githubusercontent.com/3134479/124242737-51135000-db32-11eb-9d62-677b487688f1.jpg)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

I have not studied the source code. so i don't know where the issue is.

**Comment by amyblais** [comment]
@larkox @DHaussermann Are you able to reproduce this?

**Comment by amyblais** [comment]
It looks like a valid bug, so I opened a ticket just in case https://mattermost.atlassian.net/browse/MM-36943
