### ISSUE TITLE
SMTP email message id missing

### ISSUE THREAD

**Issue by mightyBroccoli** [mattermost/mattermost-server#17862]
#### Summary
Mattermost Email Notifications are missing the message identifier `Message-ID` resulting in some providers marking emails as potential spam.

#### Steps to reproduce
Default SMTP setup.

#### Expected behavior
It would be quite nice to generate a proper message identifier for the generated email which is sent.

#### Observed behavior (that appears unintentional) 
Emails are missing the `Message-ID: <message.identifier.1337@smtp.example.tld>` header.

#### Possible fixes
The best solution would be for the Mattermost SMTP client to automatically create a message id for every message that is sent.

There is though a ghetto fix for this issue. Postfix is able to add missing headers which includes the message-id header. But this fix can cause some unforeseen issues as sometimes missing headers are useful.

**Comment by amyblais** [comment]
@mightyBroccoli Can you help share relevant [details about your environment from here](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues)?

**Comment by mightyBroccoli** [comment]
Sure but I am fairly sure that this issues is not influenced by my general setup.
OS: Archlinux
Mattermost Version: 5.35.3
Database Schema Version: 5.35.3
Database: mysql
I am not using a container.

The SMTP setup is as basic as it comes. I use an external SMTP server with a valid TLS certificate.
That's it. If there are some specific values you would like to know hit me up.

**Comment by amyblais** [comment]
@mkraft / @BenCookie95 Would this be a bug?

**Comment by mightyBroccoli** [comment]
I read up on the message id topic and it seems that it is not strictly necessary to add this header to form a valid email. But most spam filters will mark emails without it as spam ot even as invalid.

**Comment by mkraft** [comment]
> @mkraft / @BenCookie95 Would this be a bug?

@mightyBroccoli Yes, [RFC5322 states that messages "should" have a `message-id` field](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.4) with a globally unique value for use in replies and threading.

I wonder if this would also help to group post threads in mail clients like how Apple Mail is grouping the emails from this Github issue? 

@amyblais I've added [a Jira ticket](https://mattermost.atlassian.net/browse/MM-36872) for this and tentatively assigned it to Ursa team. 

@mightyBroccoli Thanks for the good suggestion.

**Comment by mightyBroccoli** [comment]
@mkraft thank you 😄

**Comment by mkraft** [comment]
This change has been merged with https://github.com/mattermost/mattermost-server/pull/18232.
