### ISSUE TITLE
Open PDF attachments using the associated system app

### ISSUE THREAD

**Issue by jasperroloff** [mattermost/mattermost-server#17868]
When opening a PDF attachment inside the Mattermost desktop app, it only shows a preview of the PDF. The preview has multiple disadvantages: on high-resolution displays (e.g. MacBooks) the preview looks blurry and pixelated. Also, it isn't possible to select and copy text.

The feature I'm requesting is to allow opening the PDF using the system-wide default application for PDF files. Currently, this is only possible by downloading the attachment file and then opening the file from the file explorer. Instead, clicking on the attachment should directly download the attachment into a temporary directory and open the file with the associated app.

Thank you!

**Comment by esethna** [comment]
@jasperroloff we have some awesome improvements for the Mattermost previewer lined up that will add a lot of commonly used PDF tools accessible within Mattermost: https://www.figma.com/file/i86bHWcB68HMiaJNoVxmsq/Image-Preview-Modal?node-id=665%3A80

**Comment by vineelyalamarthy** [comment]
Is this up for grabs

**Comment by Willyfrog** [comment]
there is no ticket for it as far as I know, is there one @esethna ? or is it fully covered in v6.0?

**Comment by esethna** [comment]
@Willyfrog @vineelyalamarthy @jasperroloff I'm going to close this ticket based on my comment above. We are integrating a lot of commonly used PDF tools into the Mattermost previewer in the coming months. Follow progress here: https://mattermost.atlassian.net/browse/MM-27310
