### ISSUE TITLE
High load time for 'Direct message' experience

### ISSUE THREAD

**Issue by abrahamgeorget** [mattermost/mattermost-server#17865]
#### Summary
High load time for 'Direct message' experience while launching the web app for the first time. (New user invited to join Mattermost Cloud professional )

#### Steps to reproduce
Access the invite link on email for a new user sign in from admin. After logging in, navigate to the 'Direct messages' experience on left rail to a user to start chat session [+].  (Browser: Edge chromium)

#### Expected behavior
Chat experience load time of 5s or less

#### Observed behavior (that appears unintentional) 
Chat experience loading screen seen for >5 mins. (screenshot attached)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem
![image](https://user-images.githubusercontent.com/80298442/124548101-19caca80-dde2-11eb-8219-602bc23d6164.png)

**Comment by amyblais** [comment]
@abrahamgeorget Can you help share relevant [details about your environment from here](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues)?

**Comment by amyblais** [comment]
cc @jwilander / @hmhealey This is on a Cloud server.

**Comment by abrahamgeorget** [comment]
> @abrahamgeorget Can you help share relevant [details about your environment from here](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues)?

Mattermost web app - Mattermost Version: cloud-2021-07-01-1
Web browser - Edge Chromium Version 91.0.864.54 (Official build) (64-bit)
OS - Windows 10 Home; OS build 19041.1052;Version 2004

**Comment by hmhealey** [comment]
If I had to guess, this isn't actually something taking a long time to load, but rather the loading screen just stays open even though the channel has actually been loaded in the background.

Judging by the screenshot, you just signed up, logged in, and immediately opened that DM. Does that sound correct?

**Comment by abrahamgeorget** [comment]
@hmhealey - That sounds about right. I logged in for the first time, navigated to the Direct message screen, added a participant and it was showing the 'Loading' screen for about 5 mins or so.

**Comment by hmhealey** [comment]
@amyblais Perhaps we can forward this onto whichever team handles Cloud issues? Perhaps they'd be able to look further back to see whether or not this instance had any errors occur at the time.

**Comment by jasonblais** [comment]
@hmhealey Amy actually escalated this to the Cloud team yesterday, but I thought it was messaging related. Sorry about that.

Is it that you're suggesting the Cloud team to check the logs for this particular workspace, to see what errors (if any) took place?

**Comment by hmhealey** [comment]
No worries. This is one of those things that's kind of difficult to have a single owner for since it's hard to tell who owns it until someone actually investigates it.

> Is it that you're suggesting the Cloud team to check the logs for this particular workspace, to see what errors (if any) took place?

Yeah, that's correct. Given we haven't had this reported anywhere else, I'd assume it's a possibly rare error occurring here that the web app isn't handling well.

**Comment by amyblais** [comment]
Please re-open this issue if you're still experiencing this,
