### ISSUE TITLE
Deleted thread message displays timestamp on top of "(message deleted)"

### ISSUE THREAD

**Issue by aigyptios** [mattermost/mattermost-server#17878]
#### Summary
Deleted thread message displays timestamp on top of "(message deleted)"

#### Steps to reproduce
Version 4.5.0.6629
User 1 creates a post (Message A)
User 2 replies to Message A with Message B
User 2 replies to Message A with Message C
User 2 deletes Message C 

#### Expected behavior
The timestamp should display to the left of the "(message deleted)". 

#### Observed behavior (that appears unintentional) 
The timestamp is displayed on top of the "(message deleted)" text. Additionally, the "x" to remove the deleted message is misaligned (positioned lower, under the "Write to [channel]..." textarea.

<img width="988" alt="Screen Shot 2021-07-07 at 3 42 56 PM" src="https://user-images.githubusercontent.com/3521269/124819660-822cbf80-df3a-11eb-90f6-61c628a82040.png">

**Comment by amyblais** [comment]
@aigyptios Would you be open to upgrading to a more recent version (our most recent version is 5.36.1)?

**Comment by aigyptios** [comment]
I think it's an enterprise account, and I'm not the system administrator 😅  so I can't exactly do that. But honestly I only opened the issue so as to make it known; if it's already been fixed or tracked or determined not to be an issue in later versions, feel free to close this out.

**Comment by amyblais** [comment]
Looks like there is a ticket actually https://mattermost.atlassian.net/browse/MM-32187 :)

**Comment by aigyptios** [comment]
Ah, my apologies for duplicating this! I didn't find that issue earlier--feel free to close this if necessary.
