### ISSUE TITLE
Notification only for mentions (not for direct message nor for username)

### ISSUE THREAD

**Issue by biva** [mattermost/mattermost-server#17873]
#### Summary
In order to limit the number of notifications and better concentrate on my work, I would like to have desktop notification **only** for mentions and **not** for direct messages **nor** for my username.

#### Current behavior
Currently, I can choose to receive notifications "Never" or "for all activity" or "Only for mentions **and** direct messages" (the '**and**' is my issue here).

#### Expected behavior
I would like to receive notifications **only** for a specific mention, for example: "**urgent**". 

#### Possible solution
The _Notifications preference menu_ could look like:
- Desktop notification
![image](https://user-images.githubusercontent.com/9964305/124757675-20feef00-df2e-11eb-84f8-c1a90d1ab873.png)

- And the words that trigger mentions
![image](https://user-images.githubusercontent.com/9964305/124757761-35db8280-df2e-11eb-8cf7-164482ff4464.png)

The consequence would be: 
> Mentions trigger when someone sends a message that includes any of the options selected above.

This would be great to limit the notifications in the real urgent/specific cases (and also to "call" or "ring" somebody as suggested in https://github.com/mattermost/mattermost-plugin-jitsi/issues/135).

**Comment by biva** [comment]
I'm not sure if this issue should be in desktop or server? I put it here because it should be valid for the web app as well.

For information, I think this feature is also asked here: https://mattermost.uservoice.com/forums/306457-general/suggestions/38108740-have-the-option-to-configure-special-specific-noti

**Comment by amyblais** [comment]
Thank you for upvoting the feature request,
