### ISSUE TITLE
Constantly requesting to update my status

### ISSUE THREAD

**Issue by byron-hawkins** [mattermost/mattermost-server#17885]
Every time my name appears in the chat sequence, it says "update your status". No, I will not update my status. Remove this text.

**Comment by amyblais** [comment]
@esethna FYI for feedback on custom statuses ^

**Comment by esethna** [comment]
Hi @byron-hawkins, you simply need to open the modal to clear that text: 
![image](https://user-images.githubusercontent.com/14333569/124961494-6aa11580-dfd2-11eb-82e5-536f98059993.png)

**Comment by hatton** [comment]
This bug still exists. We eventually found the work around, but it was a _significant_ turn off when we first started evaluating Mattermost.
