### ISSUE TITLE
Custom Status not properly synced across multiple clients

### ISSUE THREAD

**Issue by mmodrow** [mattermost/mattermost-server#17929]
In my company we use custom status icons to mark our physical location (in office vs home office). This results in users usually logging in to one system as 🏠 or 🏡 and to another as 🏢.
For some reason this is not synced in any way. When I leave the office pc and start the laptop I see my status as 🏡, but my colleagues still see 🏢. When I rdp into my pc I see 🏢 there and 🏡 on my laptop. 
Today a colleague came on and different people saw him with different statuses. 

The only thing that's sorting this out, apparently, is resetting the status with everybody online. 

We use an on-premise instance and my client tells me, we use gitlab mm team edition 5.33.3. As it also shows the db schema version, I expect this to be the server version.

**Comment by amyblais** [comment]
We've done some bug fixes related to custom statuses after the 5.33 release. Maybe you'd like to consider upgrading to a more recent version to see if that helps (v5.37.0 is releasing tomorrow)? We also have a [community server here](https://community.mattermost.com/) (on the latest version), where you could do some testing as well.

**Comment by mmodrow** [comment]
Our admin plans to update the gitlab instance soon. Let's see which MM version will be included. I will respond with an update regarding this issue afterwards.

**Comment by amyblais** [comment]
I'll close this for now, but feel free to re-open this if the problem persists after upgrading,
