### ISSUE TITLE
Mattermost server fails to start on Ubuntu 18.04

### ISSUE THREAD

**Issue by KallanX** [mattermost/mattermost-server#17935]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Mattermost Server won't start on Ubuntu Server 18.04 - fails on go error.

#### Steps to reproduce
wget latest release from Mattermost download site. Establish server files in /opt with proper user and data directory. Run binary Mattermost - /opt/mattermost/bin/mattermost server.

#### Expected behavior
Running Ubuntu 18.04, try to execute the Mattermost server binary and receive the following error output:

{"level":"info","ts":1626404539.2371008,"caller":"app/server.go:247","msg":"Server is initializing...","go_version":"go1.15.5"}
{"level":"info","ts":1626404539.237142,"caller":"app/web_hub.go:93","msg":"Starting websocket hubs","number_of_hubs":16}
{"level":"info","ts":1626404539.2400844,"caller":"i18n/i18n.go:93","msg":"Loaded system translations","for locale":"en","from locale":"/opt/mattermost/i18n/en.json"}
{"level":"error","ts":1626404539.2501786,"caller":"commands/server.go:79","msg":"cannot initialize server templates: function not implemented"}
Error: cannot initialize server templates: function not implemented

#### Observed behavior (that appears unintentional) 
Error executing binary file on supported platform.

#### Possible fixes
Upon investigating the Mattermost-server files, I found the possible culprit within /app/server.go doing some grep foo. Specifically line 397 references the error message. Not sure where to go from there.

**Comment by agnivade** [comment]
It looks like the inotify syscall is somehow failing, which is a bit strange given you are installing on Ubuntu 18.04. Just to confirm, you have downloaded the linux_amd64 release tarball correct?

Can you also show me the output of `sysctl fs.inotify` and `grep INOTIFY_USER /boot/config-$(uname -r)`?

**Comment by KallanX** [comment]
Interesting. So, I guess I have to be more specific to the environment I'm deploying this in. I'm actually running a FreeBSD server with a jailed Ubuntu 18.04. Do we have any options to deploying Mattermost with a compatibility layer between inotify and kqueue?

**Comment by agnivade** [comment]
> I'm actually running a FreeBSD server with a jailed Ubuntu 18.04. 

Ah ok so that's the issue.

> Do we have any options to deploying Mattermost with a compatibility layer between inotify and kqueue?

Underneath, we are just using [fsnotify](https://github.com/fsnotify/fsnotify/#file-system-notifications-for-go) which has support for both inotify and kqueue. I am guessing it depends on how exactly the translation layer is implemented. From what's happening, it seems like the syscall is failing with an `ENOSYS`, so the "jailing" is somehow blocking this syscall from firing.

I _think_ Mattermost should work on a FreeBSD system as well, but I haven't tested it myself. Otherwise, you might have to look into your setup and allow the syscall to function properly.

**Comment by KallanX** [comment]
**Update:** I started a new FreeBSD jail - 13.0-RELEASE-p3. Still running into the same issue:

{"level":"info","ts":1626460445.8579957,"caller":"app/server.go:247","msg":"Server is initializing...","go_version":"go1.15.5"}
{"level":"info","ts":1626460445.858042,"caller":"app/web_hub.go:93","msg":"Starting websocket hubs","number_of_hubs":16}
{"level":"info","ts":1626460445.8595695,"caller":"i18n/i18n.go:93","msg":"Loaded system translations","for locale":"en","from locale":"/opt/mattermost/i18n/en.json"}
{"level":"error","ts":1626460445.8704343,"caller":"commands/server.go:79","msg":"cannot initialize server templates: function not implemented"}
Error: cannot initialize server templates: function not implemented

The command I'm running is: _/opt/mattermost/bin/mattermost server --disableconfigwatch_

If I try to run the binary without the arg, I get this:

Error: failed to load configuration: failed to create store: failed to watch backing store: failed to create fsnotify watcher for /opt/mattermost/config/config.json: function not implemented.

All Linux modules are loaded (linux.ko & linux64.ko). Also, it appears all libraries are met and mapped to memory addresses:

_ldd /opt/mattermost/bin/mattermost_
/opt/mattermost/bin/mattermost:
	linux_vdso.so.1 =>  (0x00007ffffffff000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000000804400000)
	libc.so.6 => /lib64/libc.so.6 (0x0000000804800000)
	/lib64/ld-linux-x86-64.so.2 (0x00000008041db000)

I'll continue to hack away at this. But please feel free to give guidance.

**Comment by KallanX** [comment]
**Update:** Tried this on the bare metal FreeBSD 13 server. Same error.

{"level":"info","ts":1626473425.2693584,"caller":"app/server.go:269","msg":"Server is initializing...","go_version":"go1.15.5"}
{"level":"info","ts":1626473425.2698097,"caller":"app/web_hub.go:93","msg":"Starting websocket hubs","number_of_hubs":16}
{"level":"info","ts":1626473425.2705338,"caller":"i18n/i18n.go:93","msg":"Loaded system translations","for locale":"en","from locale":"/opt/mattermost/i18n/en.json"}
{"level":"error","ts":1626473425.2808423,"caller":"commands/server.go:77","msg":"cannot initialize server templates: function not implemented"}
Error: cannot initialize server templates: function not implemented

**Comment by agnivade** [comment]
A linux/amd64 build won't work on freebsd. You have to compile the server yourself.

**Comment by amyblais** [comment]
Closing for now, but feel free to re-open if you need further assistance here,
