### ISSUE TITLE
Misleading error message when a link preview target uses a bad SSL certificate

### ISSUE THREAD

**Issue by KuestenKeks** [mattermost/mattermost-server#17937]
#### Summary
When a link preview is generated for a website with a bad SSL certificate the user is presented with an error message stating that "There is a configuration issue with this Mattermost Server...". But this is not the case.

#### Steps to reproduce

- On Mattermost 5.35.4 post a link to a domain that uses an untrusted SSL certificate
- e.g.: http://besserhier.de/2021/06/09/der-wirtschaftsstandort-jork-obst-it-und-vieles-mehr
- This occurs even when the link uses the `http` protocol

#### Expected behavior
The message could say something like 

> The link target has a configuration issue, or ...

#### Observed behavior (that appears unintentional) 
![grafik](https://user-images.githubusercontent.com/1938271/125931340-472a6c62-ac8e-43d5-8198-fb18d8e31925.png)

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-37162

**Comment by amyblais** [comment]
No link preview is generated using an untrusted ssl, please reopen if there are new repro steps,
