### ISSUE TITLE
[Docker] Upgrade to Alpine 3.14

### ISSUE THREAD

**Issue by J0WI** [mattermost/mattermost-server#17991]
From https://github.com/mattermost/mattermost-docker/issues/484

#### Summary
Upgrade Docker base image to Alpine 3.14

#### Possible fixes
Similar to 10af90fa2749da89d065cd7e04991a3aca18ee4a or https://github.com/mattermost/mattermost-docker/commit/c1dea8605b8464d03a8150be24392c2983c424d7

```patch
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -1,4 +1,4 @@
-FROM alpine:3.12
+FROM alpine:3.14
```

**Comment by amyblais** [comment]
Closing as a duplicate,

**Comment by J0WI** [comment]
Where can I find the duplicate?

**Comment by amyblais** [comment]
Sorry about that, it looked the same as https://github.com/mattermost/mattermost-docker/issues/484. Since it's docker related I thought it makes sense to keep it in the docker repo, but feel free to re-open this issue if you'd like.

**Comment by J0WI** [comment]
From my understanding [the old Dockerfile](https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile) has been deprecated in favor of [this one](https://github.com/mattermost/mattermost-server/blob/master/build/Dockerfile).

**Comment by amyblais** [comment]
@J0WI Thank you for clarifying that, and apologies for missing this earlier!

I have created an internal ticket to fix this: https://mattermost.atlassian.net/browse/DOPS-605

**Comment by amyblais** [comment]
A PR for this has been merged https://github.com/mattermost/mattermost-server/pull/18450.
