### ISSUE TITLE
Fix staticcheck errors from _test.go files

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18004]
#### Summary

Remove the exclude section from .golangci.yml file for staticcheck

```
- linters:
      - staticcheck
      path: ".*_test.go|store/storetest"
```

Run `make golangci-lint`

Fix all the issues.

Please feel free to ping here for any questions.

**Comment by yedamao** [comment]
I'd like to work on this issue.

**Comment by haardikdharma10** [comment]
@yedamao, sure, please go ahead. Let us know if you have any questions 🙂
