### ISSUE TITLE
Mail send to SPAM folder with Gsuite

### ISSUE THREAD

**Issue by ladifire** [mattermost/mattermost-server#18025]
Hi,
I’ve deploy Mattermost on Ubuntu server, everything is ok but Email is not send to Inbox folder. It’s always marked as SPAM (Gmail). But when run on my local server with self-sign certificate, it’s OK (all mails is sent to INBOX folder). These are difference between them:

This is message was SUCCESS sent to INBOX:
![INBOX](https://user-images.githubusercontent.com/51266596/127491444-f6df5d07-1bb6-43ce-8d3f-43d1f7639ff9.png)

And this is message was sent to SPAM:
![FAILED](https://user-images.githubusercontent.com/51266596/127491466-51a61a0a-01da-4939-9028-e5738e245741.png)

I found out that only one thing difference between them is:

The success message were sent from “209.85.220.41”, but spam message were: “209.85.220.65”

I also found out that there is only thing difference between my local config and my remote server config:

// This is config on LOCAL, with self-sign certificate
```
"ConnectionSecurity": "TLS",
        "TLSCertFile": "./localhost.crt",
        "TLSKeyFile": "./localhost.key",
```
And this is my Remote config:

```
"ListenAddress": ":4100",
        "ConnectionSecurity": "",
        "TLSCertFile": "",
        "TLSKeyFile": "",
        "TLSMinVer": "1.2",
I used Nginx as a proxy.
```

So I tried to change my Remote config to match local (use TLS). So I followings these instruction:
https://docs.mattermost.com/install/config-tls-mattermost.html
And change config to:

```
"ListenAddress": ":4001",
        "ConnectionSecurity": "TLS",
        "TLSCertFile": "path/to/LetsendcryptCert.crt",
        "TLSKeyFile": "path/to/LetsendcryptKey.key",
        "TLSMinVer": "1.2",
        "TLSStrictTransport": false,
        "TLSStrictTransportMaxAge": 63072000,
        "TLSOverwriteCiphers": [],
        "UseLetsEncrypt": true,
        "LetsEncryptCertificateCacheFile": "./config/letsencrypt.cache",
        "Forward80To443": true,
```
Then Mattermost throw an error:

`443: bind: address already in use`

Can anyone tell me how to fix this problem? please!

**Comment by amyblais** [comment]
I'll close this one as there is discussion on our troubleshooting forum https://forum.mattermost.org/t/mail-send-to-spam-folder-with-gsuite/11988.
