### ISSUE TITLE
Incompatible table collation settings for new tables

### ISSUE THREAD

**Issue by paddy-hack** [mattermost/mattermost-server#18021]
#### Summary
Newly created tables do not use a collation setting that is compatible with existing tables.

#### Steps to reproduce
- set up an instance of Mattermost 5.34 with MySQL 8.0.25
- login and create a few posts (or restore from a sample dump)
- change the collation setting on all tables (except `schema_migrations`) to `utf8mb4_general_ci`.  Leave `schema_migrations` at `utf8mb4_unicode_ci`.
- upgrade to Mattermost 5.35 (or later)
- login or refresh the page

#### Expected behavior
Upon upgrades and after migrations have completed, I expect the database to be in a consistent and usable state.

#### Observed behavior (that appears unintentional) 
New tables were created with collation settings that were (almost all) incompatible with the collation settings of existing tables.
To be explicit, the upgraded added the tables below.  Note that `IR_System` is the only table with a collation setting that matches the existing tables in my setup.
```
+---------------------------+--------------------+
| TABLE_NAME                | TABLE_COLLATION    |
+---------------------------+--------------------+
| IR_Incident               | utf8mb4_0900_ai_ci |
| IR_Playbook               | utf8mb4_0900_ai_ci |
| IR_PlaybookMember         | utf8mb4_0900_ai_ci |
| IR_StatusPosts            | utf8mb4_0900_ai_ci |
| IR_System                 | utf8mb4_general_ci |
| IR_TimelineEvent          | utf8mb4_0900_ai_ci |
| RemoteClusters            | utf8mb4_0900_ai_ci |
| RetentionPolicies         | utf8mb4_0900_ai_ci |
| RetentionPoliciesChannels | utf8mb4_0900_ai_ci |
| RetentionPoliciesTeams    | utf8mb4_0900_ai_ci |
| SharedChannelAttachments  | utf8mb4_0900_ai_ci |
| SharedChannelRemotes      | utf8mb4_0900_ai_ci |
| SharedChannelUsers        | utf8mb4_0900_ai_ci |
| SharedChannels            | utf8mb4_0900_ai_ci |
+---------------------------+--------------------+
```
When logging in or refreshing the page in the browser, I see the following in the Mattermost logs
```
2021-07-29T01:44:49.476Z	error	mlog/log.go:251	We could not get all teams.	{"path": "/mattermost/api/v4/teams", "request_id": "[REDACTED]", "ip_addr": "[REDACTED]", "user_id": "[REDACTED]", "method": "GET", "err_where": "GetAllTeamsPage", "http_code": 500, "err_details": "failed to find Teams: Error 1267: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='"}
```
This clearly indicates that mixed collation settings on the Mattermost tables is a problem.

> A bit of background, my instance started out on MySQL 5.x with `utf8mb4_general_ci` as the collation setting.  I have not changed that to the new MySQL 8 default of `utf8mb4_0900_ai_ci` for reasons [documented elsewhere](https://github.com/mattermost/mattermost-server/issues/16206#issuecomment-784655077).

When running into #16206, I manually altered new tables to match and I tried that this time around as well.  This works fine for all new tables *except* the retention policies related ones.  These refuse to be converted with the following error
```
mysql> alter table RetentionPolicies CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ERROR 3780 (HY000): Referencing column 'PolicyId' and referenced column 'Id' in foreign key constraint 'FK_RetentionPoliciesChannels_RetentionPolicies' are incompatible.
mysql> alter table RetentionPoliciesChannels CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ERROR 3780 (HY000): Referencing column 'PolicyId' and referenced column 'Id' in foreign key constraint 'FK_RetentionPoliciesChannels_RetentionPolicies' are incompatible.
mysql> alter table RetentionPoliciesTeams CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ERROR 3780 (HY000): Referencing column 'PolicyId' and referenced column 'Id' in foreign key constraint 'FK_RetentionPoliciesTeams_RetentionPolicies' are incompatible.
```
Even after altering the collation settings on those tables where it succeeds, the `Illegal mix of collations` error persists in the Mattermost logs.

#### Possible fixes
No clue in terms of code but I think that using the collation settings of existing tables when creating new tables (or perhaps the value of MySQL's `collation_database`) would have avoided this.  Well, most of it at least as I think the incompatible columns in foreign key constraints might be unrelated, not sure.

Poking further in my setup, I also noticed a `charset=utf8mb4,utf8` query parameter on my `MM_SQLSETTINGS_DATASOURCE`.  Maybe adding a `collate=utf8mb4_general_ci` parameter could be used to fix things but I haven't been able to find any documentation on what parameters can be used :unamused:

**Comment by amyblais** [comment]
@streamer45 / @agnivade Let me know if you're familiar with this issue.

**Comment by streamer45** [comment]
@paddy-hack 

I believe the solution is to set the collation to `utf8mb4_0900_ai_ci` for every table as explained in https://docs.mattermost.com/install/software-hardware-requirements.html under "MySQL 8 Support".   
Let me know if you still have troubles after doing that.

**Comment by paddy-hack** [comment]
Thanks for the quick follow-up but I mentioned *why* I haven't changed to `utf8mb4_0900_ai_ci`.

> A bit of background, my instance started out on MySQL 5.x with utf8mb4_general_ci as the collation setting. I have not changed that to the new MySQL 8 default of utf8mb4_0900_ai_ci for reasons [documented elsewhere](https://github.com/mattermost/mattermost-server/issues/16206#issuecomment-784655077).

Just to be clear, I cannot take my instance off-line for what looks to be more than a day (and who knows how much longer).  So far, things have been working fine for me using `utf8mb4_general_ci` and I'd appreciate it if things stay that way.

I'll have another look at the time required to change the collation setting (using different hardware) and may try upgrading to 5.37 to see if the [database changes](https://docs.mattermost.com/install/self-managed-changelog.html#database-changes) have improved the situation.  That'll have to wait until next week, though.

**Comment by paddy-hack** [comment]
I see that I forgot to mention in the original description that my MySQL server (official Docker image, `mysql:8.0.25`) is running with the following configuration snippet
```
[mysqld]
  character-set-server=utf8mb4
  collation-server=utf8mb4_general_ci
  default-authentication-plugin=mysql_native_password
  ngram_token_size=2
```
where the `ngram_token_size` has been modified for better search results with Japanese.

**Comment by streamer45** [comment]
@paddy-hack 

Thanks for the additional context. The main reason the `Posts` table causes such long migrations is due to the presence of multiple full-text indexes that need rebuilding. To avoid downtime but still go ahead with the changes I'd suggest using an online schema change tool like https://www.percona.com/doc/percona-toolkit/3.0/pt-online-schema-change.html . Let us know if that could be a viable option for you or if you need help setting it up.

> Poking further in my setup, I also noticed a charset=utf8mb4,utf8 query parameter on my MM_SQLSETTINGS_DATASOURCE. Maybe adding a collate=utf8mb4_general_ci parameter could be used to fix things but I haven't been able to find any documentation on what parameters can be used unamused

Those are used by the underlying MySQL driver, you can find some documentation in https://github.com/go-sql-driver/mysql#collation

**Comment by paddy-hack** [comment]
Thanks for the feedback.  Looks like I can use that Percona Toolkit utility remotely so there's no need to install it in my MySQL container image.  Of course, (temporarily) installing it is not a problem either.  I may give this a spin.

The link to the `collation` parameter indicates that this only affect client-server communication so I'd expect no change in terms of table collation order.

Still, I do find it odd that the database server's collation settings are ignored when adding tables ... :thinking:

**Comment by paddy-hack** [comment]
I tried the `pt-online-schema-change` utilitiy against a test setup, like so
``` console
$ time ./pt-online-schema-change --execute --alter 'CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;' "h=$IP_ADDRESS,P=3306,p=$MYSQL_ROOT_PASSWORD,u=root,D=mattermost,t=Posts"
No slaves found.  See --recursion-method if host 8aa0353dda2f has slaves.
Not checking slave lag because no slaves were found and --check-slave-lag was not specified.
Operation, tries, wait:
  analyze_table, 10, 1
  copy_rows, 10, 0.25
  create_triggers, 10, 1
  drop_triggers, 10, 1
  swap_tables, 10, 1
  update_foreign_keys, 10, 1
Altering `mattermost`.`Posts`...
Creating new table...
Created new table mattermost._Posts_new OK.
Altering new table...
Altered `mattermost`.`_Posts_new` OK.
2021-08-03T10:43:51 Creating triggers...
2021-08-03T10:43:51 Created triggers OK.
2021-08-03T10:43:51 Copying approximately 357254 rows...
Copying `mattermost`.`Posts`:  24% 01:32 remain
Copying `mattermost`.`Posts`:  28% 02:28 remain
Copying `mattermost`.`Posts`:  32% 03:09 remain
Copying `mattermost`.`Posts`:  34% 03:50 remain
Copying `mattermost`.`Posts`:  37% 04:18 remain
Copying `mattermost`.`Posts`:  40% 04:52 remain
Copying `mattermost`.`Posts`:  43% 05:14 remain
Copying `mattermost`.`Posts`:  45% 05:26 remain
Copying `mattermost`.`Posts`:  47% 05:36 remain
Copying `mattermost`.`Posts`:  49% 05:42 remain
Copying `mattermost`.`Posts`:  51% 05:45 remain
Copying `mattermost`.`Posts`:  53% 05:46 remain
Copying `mattermost`.`Posts`:  56% 05:44 remain
Copying `mattermost`.`Posts`:  58% 05:38 remain
Copying `mattermost`.`Posts`:  62% 05:08 remain
Copying `mattermost`.`Posts`:  66% 04:47 remain
Copying `mattermost`.`Posts`:  69% 04:32 remain
Copying `mattermost`.`Posts`:  72% 04:09 remain
Copying `mattermost`.`Posts`:  75% 03:51 remain
Copying `mattermost`.`Posts`:  78% 03:27 remain
Copying `mattermost`.`Posts`:  81% 03:02 remain
Copying `mattermost`.`Posts`:  84% 02:31 remain
Copying `mattermost`.`Posts`:  88% 01:53 remain
Copying `mattermost`.`Posts`:  92% 01:18 remain
Copying `mattermost`.`Posts`:  95% 00:44 remain
Copying `mattermost`.`Posts`:  99% 00:08 remain
2021-08-03T11:05:54 Copied rows OK.
2021-08-03T11:05:54 Analyzing new table...
2021-08-03T11:05:55 Swapping tables...
2021-08-03T11:06:35 Swapped original and new tables OK.
2021-08-03T11:06:35 Dropping old table...
2021-08-03T11:06:35 Dropped old table `mattermost`.`_Posts_old` OK.
2021-08-03T11:06:35 Dropping triggers...
2021-08-03T11:06:35 Dropped triggers OK.
Successfully altered `mattermost`.`Posts`.

real	22m45.804s
user	0m2.242s
sys	0m0.592s
```
So that seems to work fine and complete in a reasonable time.

Just out of curiosity I also ran
``` console
mysql> ALTER TABLE Posts CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
Query OK, 406119 rows affected (1 hour 5 min 39.36 sec)
Records: 406119  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE Posts CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
Query OK, 406119 rows affected (52 min 9.72 sec)
Records: 406119  Duplicates: 0  Warnings: 0
```
on the same MySQL database.

Load on the machine running the database was more or less constant, so the online conversion is somewhat faster.

My earlier attempts taking 20+ hours were on an old, resource constrained laptop with a spinning disk.  This time around, I used something newer and more powerful with an SSD.   I still have to get a ballpark figure for my production setup but I think I can now (finally) switch to `utf8mb4_0900_ai_ci` :sweat_smile:

**Comment by streamer45** [comment]
That's great to hear, please let us know how that goes.

> My earlier attempts taking 20+ hours were on an old, resource constrained laptop with a spinning disk. This time around, I used something newer and more powerful with an SSD.

That makes sense given the bottleneck on these schema changes is almost always i/o throughput.

> Still, I do find it odd that the database server's collation settings are ignored when adding tables

Tables are explicitly created with `charset=UTF8MB4` so the collation defaults to whatever is mapped to that in `SHOW CHARACTER SET`.

> For CREATE TABLE statements, the database character set and collation are used as default values for table definitions if the table character set and collation are not specified.

**Comment by paddy-hack** [comment]
Thanks for the explanation.  However, this does not explain why the `IR_System` table ends up with `utf8mb4_general_ci`, in agreement with the `collation-server` in my setup.
