### ISSUE TITLE
Impossible to drag and drop text into inputs/textareas

### ISSUE THREAD

**Issue by Roy-Orbison** [mattermost/mattermost-server#18074]
I think this applies to mattermost-webapp, but I can't file bugs there, nor on Atlassian.

#### Summary
Cannot drag'n'drop text from other programs into any input or textarea within the Mattermost web app.

#### Steps to reproduce
1. Select text in any other program
2. Drag that selection into the Mattermost chat window, e.g. the message compose textarea, the Switch Channels search input, an Account Settings input.

#### Expected behavior
The text should be inserted as if typed/pasted, like any standard input.

#### Observed behavior (that appears unintentional) 
Nothing is inserted. No errors or other messages are shown.

I've observed this in Chrome on Windows, and in both Chromium and Firefox on Linux.

**Comment by amyblais** [comment]
@hmhealey / @devinbinnie Do we know if this is expected or a bug?

**Comment by hmhealey** [comment]
That does sound like a bug to me. I remember that there was a bug reported a long time ago about being able to drag and drop channel names into the textbox for whatever reason, so maybe this is because of that.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-37712

**Comment by Roy-Orbison** [comment]
I figured it's because those events are intercepted for uploading files, but no exception was made to allow text through. It's definitely the typical behaviour, see for yourself on a [control lacking any enhancement](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_textarea).

**Comment by hmhealey** [comment]
I started a thread in the UX Design channel on https://community.mattermost.com to discuss this behaviour and confirm that it's what we want to do.

Is there a particular use case that you'd want this for? I know it's more convenient than copy and pasting text that's visible on the current screen, but I'm curious if there's another use case I'm missing.

**Comment by Roy-Orbison** [comment]
A quick search gave me [this article](https://www.ctrl.blog/entry/clipboard-security.html) that I think sums up the issues nicely. It reduces the chances of exposed data. One doesn't necessarily have to be compromised for the clipboard to be a problem, e.g. Windows now offers cloud-backed, cross-device clipboard sharing. Other, legitimate programs may monitor or interact with clipboard contents. Dragging and dropping content gives the user a choice to explicitly bypass the clipboard.

I think the question should not be "what's the benefit of accommodating dnd?" but rather "what benefit is there to breaking the standard behaviour?"

**Comment by hmhealey** [comment]
That's a very good point. I feel like I've used it for that exact reason myself. Also I think like I've used it to copy something when I've had something else in my clipboard.

At the same time, no one on our end can remember why we would've blocked it, so we're all on the side of fixing it.

**Comment by hmhealey** [comment]
Opening this up for Help Wanted since I don't have time to finish up the PR for this.

For anyone who wants to take this on, feel free to work off my PR or start from scratch.

**Comment by sk409** [comment]
I would like to work on this issue.
