### ISSUE TITLE
CRT: Inconsistent Message Spacing

### ISSUE THREAD

**Issue by natewiebe13** [mattermost/mattermost-server#18094]
#### Summary
With Collapsed Reply Threads enabled, the spacing between the first and second consecutive message from the same user has extra spacing.

#### Steps to reproduce
- Enable Collapsed Reply Threads
- Ensure Message Display is set to Standard
- Send 3 messages in a row
- Note the spacing between the messages

#### Expected behavior
The spacing between all messages should be the same.

#### Observed behavior (that appears unintentional) 
The first and second message has more spacing than any further messages.

![image](https://user-images.githubusercontent.com/759228/128736330-76c9af54-660b-4044-8ebe-7c996c5e2fb1.png)

#### Note
This does not happen within a thread, just on the main channel.

**Comment by amyblais** [comment]
We have a ticket for this and it is queued to be fixed in an upcoming v6.0 release (September release) - https://mattermost.atlassian.net/browse/MM-36646 (PR for it was recently merged).
