### ISSUE TITLE
rsync backup failing due to file access issue

### ISSUE THREAD

**Issue by ansash** [mattermost/mattermost-server#18105]
#### Summary
rsync backup as backup user != mattermost does not have access rights to copy picture files.
running v5.36.1 on debian with postgres

here my ls -la output from a long running (multiple upgrades) instance (2y+):
me@server:/opt/mattermost/data/20210730/teams/noteam/channels/7ru8s8aiujfq5jjh7h866xoacr/users/9bnnf39wcpyctqbzboq5ekmqpe/j45c9kchbbfw
ubq1s1w537p58r$ ls -la
total 2116
drwxr-x---  2 mattermost mattermost    4096 Jul 30 21:01 .
drwxr-x--- 12 mattermost mattermost    4096 Jul 30 21:02 ..
-rw-------  1 mattermost mattermost 1729717 Jul 30 21:01 F1021475-7312-4C5C-85CD-20DED839649F.jpg
-rw-------  1 mattermost mattermost  414432 Jul 30 21:01 F1021475-7312-4C5C-85CD-20DED839649F_preview.jpg
-rw-------  1 mattermost mattermost    4599 Jul 30 21:01 F1021475-7312-4C5C-85CD-20DED839649F_thumb.jpg

#### Steps to reproduce
ls -la any jpg file below chanels

#### Expected behavior
access right is 600 - instead of 660

#### Observed behavior (that appears unintentional) 
described recipies do not work - f.e. https://mattermost.com/blog/mattermost-recipe-cold-backup-server/

#### Possible fixes
is manual reset to 660 sufficient prior backup - maybe fixed in a future release ?

**Comment by amyblais** [comment]
Have you also had a chance to take a look at our documentation related to backup https://docs.mattermost.com/deploy/backup-disaster-recovery.html?

**Comment by ansash** [comment]
Hi Amy, thats the issue - step 3 of the Backup is copying files. Without access right for other "backup" users - this fails.
The question for the developers - or other users running mattermost:
a) is this a upgrade error - which can be fixed using chmod 660 for all files
b) is this a bug of the server creating all files 600 only
Thanks in advance for feedback !

**Comment by ansash** [comment]
Issue solved. I assume implicitly that the rights were messed up during an update of the server.
Why ? In the installation doc https://docs.mattermost.com/install/install-debian.html - installing Mattermost Step 6 c the rights are to be set in the way needed (660).
