### ISSUE TITLE
Please implement underline tagging as per explanation

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#18109]
The following would be very helpful and I think evident as to why with the accompanying explanation:
https://forum.mattermost.org/t/important-underline-tagging-markup-necessary/12054

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @ylluminate,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
