### ISSUE TITLE
WebApp crash when opening admin_console/site_config/posts

### ISSUE THREAD

**Issue by KobeBergmans** [mattermost/mattermost-server#18149]
#### Summary
WebApp crashes and does not display anything when opening admin_console/site_config/posts.

#### Steps to reproduce
I am using a developer setup. I cloned the webapp and server repository and i am using the master branch of both (Current latest webapp commit: dce2093d1a9a88ad3690f47a8a87f8b01c0e8295). 

#### Expected behavior
The page must be loaded normally.

#### Observed behavior (that appears unintentional) 
The page just does not load, you get a white screen.
This error message shows up in the console:
![Screenshot_39](https://user-images.githubusercontent.com/55985776/129698928-f4129390-d2e9-4610-999d-3d24d477e44a.png)
 
#### Possible fixes
I can't seem to find where this error occurs

**Comment by KobeBergmans** [comment]
I tracked down the issue and the server code broke this page. This issue appears first on commit: 757dc96461ffb27b0c8a5a1e30cd5fbabc871eef

**Comment by amyblais** [comment]
@hanzei @streamer45 FYI on this ^

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-37985
