### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T3293 Entire thread appears and scrollable in the RHS"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18159]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T3293 Entire thread appears and scrollable in the RHS</h1>
<div>
<div>
<h3>Steps </h3><ol><li>Create a thread with several replies to make it scrollable in RHS</li><li>Create enough posts from another user (not related to the thread on the same channel) to not load on a first load (atleast 35)</li><li>Reply on original thread</li><li>Reload browser</li><li>Hit on reply to open thread on RHS</li></ol><h3>Expected</h3><ul><li>The entire thread appears in the RHS (scrollable)</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/messaging``
**Test code arrangement:**
```
describe('Messaging', () => {
    it('MM-T3293 Entire thread appears and scrollable in the RHS', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by poflankov** [comment]
Can I work on this one?

**Comment by saturninoabril** [comment]
Sure and thanks @poflankov!
