### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T244 Webapp: Post menu item `Mark as Unread` appearance"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18164]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T244 Webapp: Post menu item `Mark as Unread` appearance</h1>
<div>
<div>
<h3>Steps  #1</h3>Webapp: Post menu item `Mark as Unread<br>–––––––––––––––––––––––––<ol><li>Click on a 3 dot menu</li><li>Verify `Mark as Unread` as the 2nd option from the top, available just below Reply</li></ol><h3>Expected</h3><ul><li>Mark as Unread option is available</li></ul><hr><h3>Steps  #2</h3><ol><li>Shrink the window and verify post menu options in the mobile view</li></ol><h3>Expected</h3><ul><li>Mark as unread is available, verify divider lines are not doubled on the post menu in the mobile view</li></ul><hr><h3>Steps  #3</h3><ol><li>Verify there are no extra divider lines at the bottom of the menu for the non-admin user</li></ol><h3>Expected</h3><ul><li>There's no divider in the menu when the Edit and Delete options are missing for non-admin user</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/mark_as_unread``
**Test code arrangement:**
```
describe('Mark as Unread', () => {
    it('MM-T244_1 Webapp: Post menu item `Mark as Unread` appearance', () => {
        // code
    });

    it('MM-T244_2 title', () => {
        // code
    });

    it('MM-T244_3 title', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by poflankov** [comment]
Hello! Any cue how to verify the "divider line is not doubled"?
I'm trying to model the situation in DOM, and can't reproduce it.

It's a list of `<li>` with the `<button>` inside, and the `<button>` has the border which is shown as this divider.
So if I just, say, delete the button - everything looks nice.

The most resembling picture is probably when I delete the button content `<span>`:
![image](https://user-images.githubusercontent.com/87149297/143685242-6724cfe7-f5ac-4aa8-840a-66c496083d86.png)

**Comment by poflankov** [comment]
BTW I've probably found the bug. If you try to reach top menu items (including "Mark as Unread") for the first post in a channel - there is no way to do that, they are simply unreachable by the scrolling.
![image](https://user-images.githubusercontent.com/87149297/143685294-e6ab0e47-ce5d-4865-a71c-0b91f7753286.png)

And even decreasing browser zoom does not heal the situation
![image](https://user-images.githubusercontent.com/87149297/143685504-b3b30d46-4d26-42b5-b007-68cab55cd673.png)

**Comment by yasserfaraazkhan** [comment]
@saturninoabril @poflankov 
I'll be taking this up.  @poflankov Please let me know if this is in progress.

**Comment by yasserfaraazkhan** [comment]
@amyblais I guess, this can be closed
