### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T248 Mark DM post as Unread"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18166]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T248 Mark DM post as Unread</h1>
<div>
<div>
<h3>Test Preparation</h3>Left Chrome off for manual testing until&nbsp;<a href="https://mattermost.atlassian.net/browse/MM-23915">https://mattermost.atlassian.net/browse/MM-23915</a> is fixed.<hr><h3>Steps  #1</h3><ol><li>Create a DM with User A</li><li>Have user A post few messages</li><li>Read the posts and then mark as Unread using post menu</li></ol><br /><h3>Expected</h3><ul><li>New message line appears above the post, DM channel is marked as unread with mention bubble</li></ul><br /><strong>Note</strong>: Mention count <em>should not</em> include messages sent by you<hr><h3>Steps  #2</h3><ol><li>Leave DM channel</li></ol><h3>Expected</h3><ul><li>DM remains unread on LHS with the mention bubble</li></ul><hr><h3>Steps  #3</h3><ol><li>Open the DM channel</li></ol><h3>Expected</h3><ul><li>DM channel is marked as read, mention bubble disappears, New Message line is present when navigating back to DM</li></ul><hr><h3>Steps  #4</h3>1. Have user A post a message in a thread in the DM<br />2. Read the posts and then mark a post in the thread as Unread using post menu<h3>Expected</h3><ul><li>New message line appears above the post, DM channel is marked as unread with mention bubble</li></ul><hr><h3>Steps  #5</h3>Leave DM channel<h3>Expected</h3><ul><li>DM remains unread on LHS with the mention bubble</li></ul><hr><h3>Steps  #6</h3>Return to the DM channel<h3>Expected</h3>DM channel is marked as read, mention bubble disappears, New Message line is present when navigating back to DM<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/mark_as_unread``
**Test code arrangement:**
```
describe('Mark as Unread', () => {
    it('MM-T248_1 Mark DM post as Unread', () => {
        // code
    });

    it('MM-T248_2 title', () => {
        // code
    });

    it('MM-T248_3 title', () => {
        // code
    });

    it('MM-T248_4 title', () => {
        // code
    });

    it('MM-T248_5 title', () => {
        // code
    });

    it('MM-T248_6 title', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by poflankov** [comment]
Hi!
Can I take this?

**Comment by saturninoabril** [comment]
@poflankov Sure and thank you!

**Comment by poflankov** [comment]
I found some (maybe) inconsistency:

I did check this sequence 
- have user A post few messages
- mark some user A message as unread
- main user leaves DM channel **clicking** on another channel or **by visiting URL** of another channel
- the DM channel **remains in "unread" status** in LHS

If I add posting a message from main user before leaving the DM channel
- have user A post few messages
- mark some user A message as unread
- **main user posts a message** - _this is the key ingredient!_

then
- main user leaves DM channel **clicking** on another channel
- the DM channel **remains in "unread" status** in LHS - _as in the sequence above_

but if instead
- main user leaves DM channel **by visiting URL** of another channel
- the DM channel **looses "unread" status** in LHS

**Comment by saturninoabril** [comment]
@poflankov Thank you for reporting! Looks like a bug to me. Ticket filed - https://mattermost.atlassian.net/browse/MM-40289
