### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T1615 Pasting code block text into external apps does not include line numbers"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18161]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T1615 Pasting code block text into external apps does not include line numbers</h1>
<div>
<div>
<h3>Steps </h3><ol><li>Copy the text in the test data field to the right (and shown posted below)<img src="https://smartbear-tm4j-prod-us-west-2-attachment-rich-text.s3.us-west-2.amazonaws.com/embedded-f3277290f945470c4add5d21ef3dc7ca7b74388fc7152bfb6b99ae58c66a95a8-1583943919338-2020-03-11_12-24-09.png" style="width: 300px;" class="fr-fil fr-dib"></li><li>Post it in a channel</li><li>Copy the text from the channel</li><li>Paste into a program that supports rich text such as Textedit on Mac or an empty Google document</li></ol><h3>Test Data</h3>```javascript<br>var foo = 'bar';<br>function doSomething() {<br>&emsp;return 7;<br>}<br>```<h3>Expected</h3><ul><li>Only the code is pasted</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/messaging``
**Test code arrangement:**
```
describe('Messaging', () => {
    it('MM-T1615 Pasting code block text into external apps does not include line numbers', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by yasserfaraazkhan** [comment]
@saturninoabril I'll be taking this up.

Just to confirm, will checking if clipboard doesn't have the code (quotes) after clicking on 'copy code block' icon suffice ?

**Comment by yasserfaraazkhan** [comment]
@amyblais I guess, this can be closed
