### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T2503 Boolean value check"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18176]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T2503 Boolean value check</h1>
<div>
<div>
<h3>Steps </h3>Boolean value check<br>–––––––––––––––––––––––––<ol><li>Load demo plugin</li><li>Using webapp, launch interactive dialog with `/dialog` command</li><li>Set boolean values (boolean selectors) in the interactive dialog.</li><li>Using iOS app, launch interactive dialog and set boolean values.</li><li>Using Android app, launch interactive dialog and set boolean values.</li></ol><h3>Expected</h3><ul><li>For steps 3-5 verify that the values are boolean and not converted to strings when submitted (not `"true"` and `"false"` but `true` and `false`).</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/interactive_dialogs``
**Test code arrangement:**
```
describe('Interactive Dialogs', () => {
    it('MM-T2503 Boolean value check', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by simcard0000** [comment]
Hey Saturn! Picking this up to work on the side :)

**Comment by saturninoabril** [comment]
Thanks @simcard0000!

**Comment by saturninoabril** [comment]
Closing this now. Thanks Sim!
