### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T2367 Compact view"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18174]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T2367 Compact view</h1>
<div>
<div>
<h3>Steps </h3>Compact view<br>————————————————————————————<ol><li>Switch the Profile settings for the test user to enable Compact view</li><li>Browse the channel again</li></ol><h3>Expected</h3><ul><li>No scroll pop is visible</li><li>All posts are displayed correctly</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/scroll``
**Test code arrangement:**
```
describe('Scroll', () => {
    it('MM-T2367 Compact view', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by poflankov** [comment]
What is "scroll pop"?

**Comment by saturninoabril** [comment]
Sorry for this "internal" terminology that we're used to calling a scenario where a layout or scroll position suddenly changed visibly due to some background process/rendering happening in the page. Maybe a good setup is to have some posts with image attachments and link previews that would be rendered outside the view. Rendering of such attachment/previews should not make a sudden change in scroll position of posts in viewing window.

**Comment by yasserfaraazkhan** [comment]
@saturninoabril , I'll be taking this up. and pushed in this [PR](https://github.com/mattermost/mattermost-webapp/pull/10578)
