### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T341 Download link on preview - Image file (non-SVG)"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18179]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T341 Download link on preview - Image file (non-SVG)</h1>
<div>
<div>
<h3>Steps </h3>Download link on preview - Image file (non-SVG; that's tested separately with Chrome and mobile browser)<br>–––––––––––––––––––––––––<ol><li>Click the thumbnail of a non-SVG image attachment to open the previewer</li><li>Click the "Download" link in the previewer</li></ol><h3>Expected</h3><ul><li>Image should download</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/multi_team_dm``
**Test code arrangement:**
```
describe('Multi-Team + DMs', () => {
    it('MM-T341 Download link on preview - Image file (non-SVG)', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by poflankov** [comment]
Is this issue already done here?
https://github.com/mattermost/mattermost-webapp/blob/c779ce34530fcfb353910e1714301aed2dad0eda/e2e/cypress/integration/files_and_attachments/upload_files_spec.js#L156-L188

**Comment by saturninoabril** [comment]
Oh, right. You're correct. Thanks for checking @poflankov!
