### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T423 Online Status - Statuses update in center, in member icon drop-down, and in DM LHS sidebar"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18177]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T423 Online Status - Statuses update in center, in member icon drop-down, and in DM LHS sidebar</h1>
<div>
<div>
<h3>Test Preparation</h3><strong>Desktop App</strong>: Use compact view for this one<br>(Chrome still in standard view)<hr><h3>Steps </h3><ol><li>UserA open a Direct Message channel with another account userB that is online (so you can see the DM and the other user's status in the LHS channel list)</li><li>UserA switch to a different channel in the center</li><li>In another browser, have userB open that channel too, and post a message</li><li>UserA observe userB's status indicator on that post</li><li>UserA click the member icon drop-down at the top of the channel so you can see the userB's status icon there as well<br><strong>Note</strong>: Basically you want to observe that userB's status updates in all three places at once (center channel post, member drop-down, LHS DM list))</li><li>&nbsp;Have userB in the other browser set themselves to away (using status drop-down or slash command /away)</li><li>UserA watch all three status indicators; it will likely take about 30 to 60 seconds to change. Should all change to away at the same time (in the member icon drop-down this may also change where the user is sorted in the list)</li><li>Set userB offline and watch again until they all change</li><li>Set userB to Do Not Disturb and watch again until they all change</li></ol><h3>Test Data</h3><strong>Known</strong>: If a user sets themselves /away, and then types while in that status, other users will see them as online for the duration of their typing (expected due to performance concerns: <a href="https://mattermost.atlassian.net/browse/MM-6406" rel="noopener noreferrer" target="_blank">https://mattermost.atlassian.net/browse/MM-6406</a>)<h3>Expected</h3><ul><li>The other user's status indicator should update at the same time in all three places.</li></ul><br><strong>Note</strong>: It can take 30 to 60 sec to update each time.<ul><li>Clicking the status indicator should open profile popover in standard view, and should do nothing in compact view.(There is no status indicator in the profile popover)</li></ul><br><strong>Dark Theme only</strong>: Ensure that offline indicator has a light color border around the status jewel<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/multi_team_dm``
**Test code arrangement:**
```
describe('Multi-Team + DMs', () => {
    it('MM-T423 Online Status - Statuses update in center, in member icon drop-down, and in DM LHS sidebar', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by nidak7** [comment]
Hi @saturninoabril , 
I'll be taking this up

**Comment by yasserfaraazkhan** [comment]
Hi @saturninoabril ,
I'll be taking this up.
