### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T962 Configuration - Enable Insecure Outgoing Connections"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18186]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T962 Configuration - Enable Insecure Outgoing Connections</h1>
<div>
<div>
<h3>Steps </h3>Configuration - Enable Insecure Outgoing Connections<br>–––––––––––––––––––––––––<h3>Expected</h3><ul><li>Enable Insecure Outgoing Connections: is present</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/system_console/environment/web_server``
**Test code arrangement:**
```
describe('System Console/Environment/Web Server', () => {
    it('MM-T962 Configuration - Enable Insecure Outgoing Connections', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by ZeeshanAmjad0495** [comment]
Hi @saturninoabril , I would like to write the e2e test for this issue.

**Comment by saturninoabril** [comment]
Sure and thanks @ZeeshanAmjad0495!

**Comment by saturninoabril** [comment]
Closing now and will submit new set of help-wanted issues.
