### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T641 🚀 Edit incoming webhook, webhook posts attachment"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18182]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T641 🚀 Edit incoming webhook, webhook posts attachment</h1>
<div>
<div>
<h3>Steps </h3>Edit webhook, webhook posts attachment<br>–––––––––––––––––––––––––<ol><li>Go to Main Menu ➜ Integrations ➜ Incoming Webhook and click Edit on the incoming webhook you created above</li><li>Change the channel from Off Topic to another channel that you have access to, then click "Update"</li><li>Copy the URL listed under the name of the webhook you edited and send POST using test data below as payload</li></ol><h3>Test Data</h3>{"attachments":[{"fallback": "fallback text", "pretext": "Optional text that appears above the attachment block", "author_name": "Author's Name", "author_link": "http://mattermost.org", "author_icon": "http://www.mattermost.org/wp-content/uploads/2016/04/icon.png", "text":"This is the text of the attachment. It should appear just above the image. \nIt's very long, so it makes the text collapse behind a \"Show More\" button. If you click \"Show More\" the text should expand, and then if you click \"Show Less\" it should collapse again. The rest of the attachment should include one image of a graph and one thumbnail image of the Mattermost logo on the right hand side of the attachment. It should also include additional fields below the image that are formatted more like a table, in two columns. The left border of the attachment should be colored green. At the top of the attachment, there should be an author name followed by a bolded title. Both the author name and the title should be hyperlinks.","thumb_url":"http://www.mattermost.org/wp-content/uploads/2016/04/icon.png","title":"Testing Integration Attachments", "title_link":"https://www.google.com","color": "#00ff00","image_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/ScientificGraphSpeedVsTime.svg/2000px-ScientificGraphSpeedVsTime.svg.png","fields":[{"short":false,"title":"Area","value":"Testing with a very long piece of text that will take up the whole width of the table. And then some more space even because it is really not a short field."},{"short":true,"title":"Iteration","value":"Testing"},{"short":true,"title":"State","value":"New"},{"short":false,"title":"Reason","value":"New defect reported"}]}]}<h3>Expected</h3><ul><li>A post is made by a webhook in the channel the webhook was created for, and the attachment formatting is as described in the attachment.</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/integrations/incoming_webhook``
**Test code arrangement:**
```
describe('Integrations/Incoming Webhook', () => {
    it('MM-T641 🚀 Edit incoming webhook, webhook posts attachment', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by samia64saleem** [comment]
I'll take it @marianunez
