### ISSUE TITLE
Mattermost won't allow file uploads or binary pasting like screenshots upon upgrading to version 5.37.1

### ISSUE THREAD

**Issue by davesingh1** [mattermost/mattermost-server#18187]
#### Summary
Upon upgrading to the latest version of team edition 5.37.1, mattermost won't allow any file uploads or binary pasting like screenshots or short clips. Logs show the following error message:

**_error mlog/log.go:251 Unable to write the file. {"path": "/api/v4/files", "request_id": "", "ip_addr": "", "user_id": "", "method": "POST", "err_where": "WriteFile", "http_code": 500, "err_details": "unable write the data in the file data/20210817/teams/noteam/channels//users//*.pdf: unexpected EOF"}_**

#### Steps to reproduce
Upload file or copy paste a screenshot

Permissions double checked for correctness. I am using mattermost from 3 plus years. Always worked smooth and without the mentioned issue above.

**Comment by amyblais** [comment]
@ahmaddanialmohd @streamer45 Let me know who would be able to help take a look at this 🙏

**Comment by streamer45** [comment]
Hi @davesingh1,

can you help provide more information about your instance? A couple of questions:

- What operating system (and version) does your MM server run on?
- Does the issue happen with any file type? 
- Have you tried uploading to a different channel or as a different user?

**Comment by amyblais** [comment]
From Forum: "The issue is resolved. It was nginx user permissions which were causing problem. Nginx tmp directory was using wrong permissions. Exactly /var/lib/nginx user was reset upon nginx update."
