### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T624 Viewing attachments with invalid URL does not cause the application to crash"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18181]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T624 Viewing attachments with invalid URL does not cause the application to crash</h1>
<div>
<div>
<h3>Steps </h3><ol><li>Incoming Webhooks — Viewing attachments with invalid URL does not cause the application to crash<br>–––––––––––––––––––––––––<ol><li>Edit <a href="https://postgres.test.mattermost.com/v16/integrations/incoming_webhooks" rel="noopener noreferrer" target="_blank">the incoming webhook you created In Mattermost</a>:<ol><li><em>Uncheck</em> the box next to "Lock to this channel"<br><img src="https://smartbear-tm4j-prod-us-west-2-attachment-rich-text.s3.us-west-2.amazonaws.com/embedded-f3277290f945470c4add5d21ef3dc7ca7b74388fc7152bfb6b99ae58c66a95a8-1580868063861-2020-02-04_20-49-24.png" class="fr-fic fr-dii"></li><li>Click 'Update'</li><li>Replace the existing payload text with the text shown in the test data field</li><li>Send it</li><li>View it on the mobile app as well as webapp</li></ol></li></ol></li></ol><h3>Test Data</h3>{"channel": "off-topic", "username": "new_username", "text": "The image below should be broken due to the invalid URL in the payload text you just sent using Postman \n", "attachments":[{"image_url":"https://example.com"}], "icon_url": "http://www.mattermost.org/wp-content/uploads/2016/04/icon_WS.png"}<h3>Expected</h3><ul><li>The post can be viewed in the client without causing other issues. (The mobile app does not crash)</li><li>The image is broken as expected (invalid URL)</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/integrations/incoming_webhook``
**Test code arrangement:**
```
describe('Integrations/Incoming Webhook', () => {
    it('MM-T624 Viewing attachments with invalid URL does not cause the application to crash', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by simcard0000** [comment]
Also grabbing this to work on it :)

**Comment by saturninoabril** [comment]
Thanks @simcard0000!
