### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T639 🚀 incoming Webhook creates DM"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18183]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T639 🚀 incoming Webhook creates DM</h1>
<div>
<div>
<h3>Steps </h3>Webhook creates DM<br>–––––––––––––––––––––––––<ol><li>Ensure that System Console ➜ Integrations ➜ Integration Management ➜ Enable integrations to override usernames is set to true</li><li>Identify a user you have NOT created a direct message channel with before (can create a new user in a different browser if that's easier)</li><li>Go to Main Menu ➜ Integrations ➜ Incoming Webhook and create an incoming webhook. Copy the link and send POST using test data below as a payload</li></ol>{"channel": "@newuser", "text": "This is a message to a newly created direct message channel"}<br><br>⬆️ "newuser" is the user identified in step 2<h3>Expected</h3><ul><li>DM channel is opened with the newuser</li><li>DM channel is marked as unread with mention</li><li>Message posts "This is a message to a newly created direct message channel"</li><li>Message is posted by username `webhook`, with the `BOT` label</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/integrations/incoming_webhook``
**Test code arrangement:**
```
describe('Integrations/Incoming Webhook', () => {
    it('MM-T639 🚀 incoming Webhook creates DM', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by mvitale1989** [comment]
I'm interested in working on this
