### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T603 Place a string when a date is expected"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18180]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T603 Place a string when a date is expected</h1>
<div>
<div>
<h3>Steps </h3>Place a string when a date is expected<br>–––––––––––––––––––––––––<ol><li>Add any search term you know will return results to the search box</li><li>Add "on:", "before:" or "after:" into the search box and manually type a value that is not numerical ex: "on:hippo"</li></ol><h3>Expected</h3><ul><li>No results</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/search_date_filter``
**Test code arrangement:**
```
describe('Search Date Filter', () => {
    it('MM-T603 Place a string when a date is expected', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by poflankov** [comment]
Can I work on this?

**Comment by haardikdharma10** [comment]
Hey @poflankov, sure please go ahead 👍

**Comment by poflankov** [comment]
Could anyone please review my PR

**Comment by saturninoabril** [comment]
Oopss, sorry for the delay. I totally missed your PR. Thanks for pinging. Now reviewing.
