### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T642 Attachment does not collapse"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18184]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T642 Attachment does not collapse</h1>
<div>
<div>
<h3>Steps </h3>Attachment does not collapse<br>–––––––––––––––––––––––––<ol><li>Create an incoming webhook ad send POST with attachment</li><li>View the webhook post that has the attachment</li><li>Type /collapse and press Enter</li><li>Observe the integration post with the Message Attachment</li></ol><h3>Expected</h3><ul><li>Does not collapse</li></ul><hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/integrations/incoming_webhook``
**Test code arrangement:**
```
describe('Integrations/Incoming Webhook', () => {
    it('MM-T642 Attachment does not collapse', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by simcard0000** [comment]
Hello! Just jumping on this ticket so that I can produce a video about E2E testing for Hacktoberfest 2022.
