### ISSUE TITLE
Remove all instances of "zz" + model.NewId() in storetest/group_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18192]
#### Summary
We have typically used "zz" to avoid clashes with random strings while searching for names. The new function to use is `NewTestId`

1. Search for `"zz" + model.NewId()` in storetest/group_store.go
2. Replace them with `NewTestId()`

**Comment by redrru** [comment]
Hi, can I take this?

**Comment by agnivade** [comment]
Go for it @redrru !
