### ISSUE TITLE
Remove all instances of "zz" + model.NewId() in storetest/channel_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18190]
#### Summary
We have typically used "zz" to avoid clashes with random strings while searching for names. The new function to use is `NewTestId`

1. Search for `"zz" + model.NewId()` in storetest/channel_store.go
2. Replace them with `NewTestId()`

**Comment by yedamao** [comment]
What's the meaning of suffix "b" in some cases?  

e.g `c4.Name = "zz" + model.NewId() + "b"`  does the suffix "b" should be remove or keep it

**Comment by agnivade** [comment]
It should be removed, unless some test fails. In that case, keep it.
