### ISSUE TITLE
Remove all instances of "zz" + model.NewId() in storetest/user_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18195]
#### Summary
We have typically used "zz" to avoid clashes with random strings while searching for names. The new function to use is `NewTestId`

1. Search for `"zz" + model.NewId()` in storetest/user_store.go
2. Replace them with `NewTestId()`

**Comment by gozeloglu** [comment]
Hi @agnivade . I'd like to resolve this issue. But, it can take a little bit time. I'll fix it as soon as possible. Can you assign me?
