### ISSUE TITLE
Remove all instances of "zz" + model.NewId() in storetest/post_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18193]
#### Summary
We have typically used "zz" to avoid clashes with random strings while searching for names. The new function to use is `NewTestId`

1. Search for `"zz" + model.NewId()` in storetest/post_store.go
2. Replace them with `NewTestId()`

**Comment by gozeloglu** [comment]
If this issue still open to pull request, I can fix that issue?

**Comment by agnivade** [comment]
Hi @gozeloglu - unfortunately a PR has already been sent for this. You are of course most welcome to pick up another issue.
