### ISSUE TITLE
Remove all instances of "zz" + model.NewId() in storetest/thread_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18194]
#### Summary
We have typically used "zz" to avoid clashes with random strings while searching for names. The new function to use is `NewTestId`

1. Search for `"zz" + model.NewId()` in storetest/thread_store.go
2. Replace them with `NewTestId()`

**Comment by chitramdasgupta** [comment]
I am new to open source contributions. I would like to tackle this issue. Can I be assigned this one?

**Comment by haardikdharma10** [comment]
@chitramdasgupta go ahead 👍

**Comment by chitramdasgupta** [comment]
Thank you. I am on it.

**Comment by agnivade** [comment]
Hey @chitramdasgupta - welcome to Mattermost! Looking forward to your PR!

**Comment by chitramdasgupta** [comment]
I have made a pull request. Could you please take a look at it?
