### ISSUE TITLE
Bleve index key file too large

### ISSUE THREAD

**Issue by NgoHuy** [mattermost/mattermost-server#18245]
Hi team,

after upgrading to 5.38.1, bleve cannot complete indexing. It only showed error `error":"BleveIndexerWorker.BulkIndexPosts: Failed to in dex file batch., key too large"`

I can search some keyword, but not sure abouth the bug. Another issue, when I upgraded version, I must index it manually, I wonder if any way I can make it automate.

Environment: Debian Buster.

Best regards,
Severus

**Comment by amyblais** [comment]
@mgdelacroix Would this be a bug?

**Comment by amyblais** [comment]
cc @lindy65 Are you able to reproduce this (or do you know which team owns bleve)?

**Comment by lindy65** [comment]
Hey @amyblais - old Server team (Miguel) owned Bleve (I think MdlC still owns)

**Comment by mgdelacroix** [comment]
This would be a bug. It seems that it is a known problem of the type of indexes that we're using, and the recommendation is to migrate to the new index type, that will (amongst other improvements) fix this. We're tracking that migration [in this ticket](https://mattermost.atlassian.net/browse/MM-29916)

**Comment by mgdelacroix** [comment]
I've sent a PR to update the bleve version and index mechanism that should solve this bug

https://github.com/mattermost/mattermost-server/pull/18266
