### ISSUE TITLE
Verify address email misses the verify button for mail.com

### ISSUE THREAD

**Issue by gabriel-vasile** [mattermost/mattermost-server#18242]
#### Summary
Account verify email is missing the "Verify email address" button in the web client of mail.com

#### Steps to reproduce
1. [Register](https://community.mattermost.com/signup_user_complete/?id=codoy5s743rq5mk18i7u5ksz7e) using a [mail.com](https://www.mail.com/int/) email address.
2. Try to confirm your email address.

#### Observed behavior (that appears unintentional) 
The button is invisible.
![mmconfirmemail](https://user-images.githubusercontent.com/10602896/130409335-4cc62004-84db-47a5-91a0-2b3620a16a18.png)

#### Possible fixes
Maybe add the common "If you cannot see the `Verify address` button then click on the link bellow" fineprint somewhere in the email.

**Comment by amyblais** [comment]
@gabriel-vasile This sounds similar to https://github.com/mattermost/mattermost-server/issues/17605. For example, are you using ProtonMail, Tutanota or Rainloop?

**Comment by gabriel-vasile** [comment]
Hi, I'm using the web client of mail.com to view emails, but it seems the problem is the same. I will close this in favor of the existing issue.
