### ISSUE TITLE
Cannot create user with mmctl

### ISSUE THREAD

**Issue by ukahlert** [mattermost/mattermost-server#18323]
I am new to mattermost but as nearly anything else is working I have no clue on this.

Using mmctl I can list users, activate/deactivate users, change user's email, change username but when creating a new user I get
Error: Unable to create user. Error: : Login failed because of invalid password.

mattermost version is 5.38.1
mmctl that came with the archive is 5.35.0

mmctl auth list
gives reasonable output and as other user commands work I do not see which password could be wrong.

Thanks for any advice

Uwe

**Comment by streamer45** [comment]
Hi @ukahlert ,

looks like the password may not be valid. Could you confirm that it respects the requirements in the`PasswordSettings` section from `config.json`?

**Comment by ukahlert** [comment]
The password respects the settings

"PasswordSettings": {
        "MinimumLength": 10,
        "Lowercase": true,
        "Number": true,
        "Uppercase": true,
        "Symbol": true
    },

Otherwise I should not be able to login at all?

mmctl auth login
works and a token is stored in ~/.config/mmctl

I login with a mattermost "System admin" account

As I can do
mmctl user (de)activate
mmctl user email ....
mmctl user password ...
...

some level of authentification must work as these commands require access to the database via the mattermost server.

**Comment by streamer45** [comment]
@ukahlert 

I am referring to the password for the user you are trying to create. Also, validation is only checked on password setting/user creation. Logging in should work normally. That said, if you have verified the password you are trying to use is valid then we can exclude that as a potential cause.

**Comment by ukahlert** [comment]
Thanks!!
I would have never looked at this. In fact one requirement was missing.
