### ISSUE TITLE
Not collapsing in-line images over 100px where image resized to be below 100px

### ISSUE THREAD

**Issue by jonespaulr** [mattermost/mattermost-server#18331]
#### Summary
Image collapsing not working as expected for resized images

#### Steps to reproduce
For an in-line image over over 100px, add =(number less than 100) to the end of the image link. Image is now resized, but 'counts as' over 100px so triggers the image collapse (or if not collapsed/hidden, doesn't now display the image in-line and has the drop-down collapse arrow included).

#### Expected behavior
Ideally mattermost would see the image as less than 100px and not apply the collapse rules to it.

#### Observed behavior (that appears unintentional) 
This has changed in version 5.35 based off of the ticket https://github.com/mattermost/mattermost-server/issues/16636
We have quite a few channels were we pull through a thumbnail image as part of the post which now don't work as we'd expect them too - either image is automatically collapsed or not in line.

<img width="733" alt="Screenshot 2021-09-02 at 11 00 13" src="https://user-images.githubusercontent.com/89972964/131824304-b5b7604e-6438-45e3-a2f8-e55b048febb0.png">

Both of the images in the screenshot 'should' be in-line as they are both < 100px, but as the second image is resized down from a larger image by appending =80, it is not.

#### Possible fixes
I'm hoping someone would be willing to take a look at this edge case and add an exclusion for resized images. I'm afraid in terms of code I'm not the person to suggest how that would be done, but it would be a useful addition if it's simple enough to include.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-38323.

**Comment by hmhealey** [comment]
Thanks for the report! I think this should be fixed in 5.39 with https://github.com/mattermost/mattermost-webapp/pull/8622.

Do you have an example of the raw Markdown you used for this so we can double check that?

**Comment by jonespaulr** [comment]
Apologies for the slow reply on this:

The markdown used as above is

`some ![serena](https://photoresources.wtatennis.com/photo-resources/2019/10/08/8a6e1bdf-580c-4d4d-b2f1-6b64eaa5038b/ZyEFAiep.jpg?width=40&height=40) text`

`some ![serena2](https://ausopen.com/sites/default/files/styles/220x/public/serena_williams_v1.png =40) text`

So the first photo is 'natively' set at the URL, while the second is not so is being resized by the markdown =40. The first 'works', the second does not.

**Comment by hmhealey** [comment]
No worries at all. That is a similar issue to the one that prompted that PR then since it's fixed on our daily build server. 
![Screen Shot 2021-09-13 at 11 28 43 AM](https://user-images.githubusercontent.com/3277310/133112359-efa84309-b802-41b8-9b65-88e739257295.png)

Thanks again for the report!
