### ISSUE TITLE
Wrong Mattermost version displayed in "About... "

### ISSUE THREAD

**Issue by rhardtke** [mattermost/mattermost-server#18359]
#### Summary
Wrong Mattermost version displayed in "About... 

#### Steps to reproduce
Upgrade to 5.38.2, the version in "About..." is 5.**39**.2

#### Observed behavior (that appears unintentional) 
![grafik](https://user-images.githubusercontent.com/20564118/132684149-7628336f-d96d-41f5-b428-1797da0153a3.png)

**Comment by amyblais** [comment]
This is noted as a known issue in v5.38.2 changelog https://docs.mattermost.com/install/self-managed-changelog.html#known-issues, and is fixed for subsequent releases,
