### ISSUE TITLE
Images in desktop client help pages are mislinked

### ISSUE THREAD

**Issue by mpounsett** [mattermost/mattermost-server#18362]
#### Summary
Many images linked to in the desktop client's help text are incorrect.

#### Steps to reproduce
Tested with v4.6.1 on MacOS.  Go to the Help link below and to the right of the chat window.  View the help text and note that many images are broken.  For example the images next to the Reply Arrow or Markdown headings in the main page at /help/messaging, or the syntax highlighting rendering examples at /help/formatting.

#### Expected behavior
The correct images should be loaded.

#### Observed behavior (that appears unintentional) 
The help text is trying to link to images such as https://docs.mattermost.com/_images/syntax-highlighting-github.PNG, which is a 404.  

#### Possible fixes
Either place the images where the help document expects to find them, or correct the URLs in the help text.

**Comment by amyblais** [comment]
@mpounsett Do you see the same issue on desktop app v4.7.1? What Mattermost server version are you on?

**Comment by mpounsett** [comment]
> @mpounsett Do you see the same issue on desktop app v4.7.1? What Mattermost server version are you on?

The server is 5.31.3 ... 4.6.1 is what we get offered, so I don't know about 4.7.1.  This seems to have been a problem for a while though, so unless it was recently fixed it's probably still an issue in 4.7.1

A quick survey unbroken images suggests they are all linking to the local chat server hostname, and the broken images are linking to docs.mattermost.com URLs.

**Comment by amyblais** [comment]
@mpounsett Would you be open to testing this at https://community.mattermost.com/, and then sharing a screenshot of the images that are broken?

I wasn't able to reproduce this just now, but I may have misunderstood the reproduction steps, and a screenshot will help.

**Comment by mpounsett** [comment]
I can't reproduce it there, so perhaps this is fixed in more recent versions.  
Help links there have slightly different file names.  My example above where our server is trying to load https://docs.mattermost.com/_images/syntax-highlighting-github.PNG, the community MM server tries to load https://docs.mattermost.com/_images/syntax-highlighting-github.png

**Comment by amyblais** [comment]
It seems this is getting fixed via https://github.com/mattermost/mattermost-webapp/pull/8431 for upcoming v5.39 release,
