### ISSUE TITLE
win10 desktop notifications displaying sender's profile picture

### ISSUE THREAD

**Issue by kiroswu** [mattermost/mattermost-server#18364]
Currently the win10 desktop notifications' displaying image is all same and default as app icon.  Can we configure it? e.g. the sender's profile picture.
![Snipaste_2021-09-10_09-02-43](https://user-images.githubusercontent.com/19584792/132832363-7fe9eb4b-4e7f-4a41-a3cb-de0fe81edfd8.jpg)

**Comment by amyblais** [comment]
@kiroswu What desktop app version and Mattermost server version are you on?

**Comment by kiroswu** [comment]
> @kiroswu What desktop app version and Mattermost server version are you on?

Mattermost server Version: 5.38.2
Database Schema Version: 5.38.2
Database: mysql
Mattermost server is self-hosted in internal ubuntu18.04 server.

Win10 mattermost app version: 4.7.1  commit 20836c5
win10 version 20h2

**Comment by amyblais** [comment]
@kiroswu I believe this is currently not configurable, so would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

If you're interested in implementing, please say so and we'll prioritize the review. You get **10** votes in the feature idea forum, and each one influences the future of the project.
