### ISSUE TITLE
Version string in about dialog is not copyable

### ISSUE THREAD

**Issue by joachim-n** [mattermost/mattermost-server#18386]
#### Summary

Users reporting a bug need the version number. This can be selected in the About dialog, but copy doesn't work.

#### Steps to reproduce

Version 4.6.2 on MacOS.

1. Do Mattermost > About Mattermost in the menu
2. Select the version string
3. Do either CMD-C or Edit > Copy
4. Do paste somewhere else 

#### Expected behavior

The selected version string pastes

#### Observed behavior (that appears unintentional) 

Whatever I had previously in the clipboard pastes

**Comment by joachim-n** [comment]
Version 4.7.2 (4.7.2.13103)

^ yup, works on latest version.

(I had assumed the app would auto-update, I had no idea I was on an outdated version.)

**Comment by amyblais** [comment]
We are working on an auto-updater feature for the desktop app for a future release.
