### ISSUE TITLE
Mac app always opens on earlier server created on launch, rather than first in tab order or last used

### ISSUE THREAD

**Issue by joachim-n** [mattermost/mattermost-server#18384]
#### Summary

Whenever I open the app on MacOS, the same server tab is open. It is not the tab I had active when I closed the app, nor is it the tab I set to be first in the order. The only reason I can think why it's this one is that it's the first of the servers I set up on the app.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior

Either open on the first tab in tab order, or the last tab I had open.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@joachim-n What Mattermost desktop app version are you on? What Mattermost server version are you on?

**Comment by joachim-n** [comment]
Mattermost 4.6.2
I've no idea what version the servers I connect to are. How do I find that out?

**Comment by amyblais** [comment]
Are you able to reproduce it with desktop app v4.7.2?

**Comment by joachim-n** [comment]
It's fixed on the latest issue. Thanks for your help!
