### ISSUE TITLE
Migrate from gorp to sqlx in store/sqlstore/audit_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18407]
Mattermost is migrating from using `gorp` as a sql library to using `sqlx`.

This ticket is about migrating all usages of gorp in `store/sqlstore/audit_store.go` to sqlx.

The way to proceed would be as follows:

All SQL queries are usually executed from `GetMaster()` or `GetReplica()` calls which return the gorp instance for the DB. We have a corresponding method `GetMasterX`/`GetReplicaX` which return the sqlx instance instead.

All named params in SQL query strings should be replaced with `?` and then a list of args should be passed to the method. Here is a quick cheat sheet of the methods to replace with:

```
GetReplica().SelectOne() -> GetReplicaX().Get()
GetReplica().Get() -> GetReplicaX().Get()
GetReplica().Select() -> GetReplicaX().Select()
GetMaster().Insert() -> GetMasterX().NamedExec()
GetMaster().Update() -> GetMasterX().NamedExec()
GetMaster().Exec() -> GetMasterX().Exec()
```

For some practical examples of migrations, please feel free to take a look at:
https://github.com/mattermost/mattermost-server/pull/18302
https://github.com/mattermost/mattermost-server/pull/18301

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-38623

**Comment by yedamao** [comment]
I'd like to work on this.

**Comment by haardikdharma10** [comment]
@yedamao sure please go ahead 👍🏻
