### ISSUE TITLE
Deprecation of ExperimentalTimezone

### ISSUE THREAD

**Issue by wezm** [mattermost/mattermost-server#18406]
The [release notes for v5.39](https://docs.mattermost.com/install/self-managed-changelog.html#release-v5-39-quality-release) includes a section on upcoming deprecations in 6.0. It includes:

> `ExperimentalTimezone` configuration setting.

I've done some more searching here and in Jira and couldn't find more information on what this means exactly. If it means that this feature will be removed I'd like to voice my opposition to that. I've enabled this setting on my server as times shown to users were consistently wrong without it.

Anyway I just thought I'd open a discussion.

**Comment by amyblais** [comment]
The new channel sidebar covers a lot of the use cases for needing these experimental features. @esethna can share more details.

**Comment by esethna** [comment]
@wezm sorry we should be more clear on what that means. We are removing that config setting and promoting the feature to general availability (ie that is now the default behaviour). @amyblais can you help update the release notes and I'll update the blog?

**Comment by wezm** [comment]
Ahh that's good to hear. Feel free to close this issue then.
