### ISSUE TITLE
Double references in Jaeger span

### ISSUE THREAD

**Issue by Etienne-Carriere** [mattermost/mattermost-server#18427]
#### Summary

When activating Jaeger tracing, in an opentracing span, there reference to the parent (`child of` reference) is present twice in the span. 

#### Steps to reproduce

1. Activate Mattermost Jaeger tracing 
2. Do an action
3. See in Jaeger UI the trace : the reference for parent (`child of` is duplicated) 

#### Expected behavior

In the Jaeger span, the reference `child of` is not duplicated 

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes

In https://github.com/mattermost/mattermost-server/blob/master/services/tracing/tracing.go#L86, replace 
```
return opentracing.StartSpanFromContext(ctx, operationName, opentracing.ChildOf(parentSpan.Context()))
```
by 
```
return opentracing.StartSpanFromContext(ctx, operationName)
```

The opentracing-go library has already the `child of` logic implemented : https://github.com/mattermost/mattermost-server/blob/master/vendor/github.com/opentracing/opentracing-go/gocontext.go#L59-L65

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-38707

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
