### ISSUE TITLE
Wrong user avatar images - multiple users receive the same avatar image set by other user

### ISSUE THREAD

**Issue by vlfesko** [mattermost/mattermost-server#18439]
#### Summary
Wrong user avatar images - multiple users receive the same avatar image set by other user.

#### Steps to reproduce
Hard to say, we just noticed that multiple users received new wrong avatar which was set and belongs to other user.

#### Expected behavior
Avatar set by a user displayed only for his account and not applied to other's accounts.

#### Observed behavior (that appears unintentional) 
Multiple users receive the same avatar image set by other user:
![CleanShot 2021-09-22 at 09 25 34@2x](https://user-images.githubusercontent.com/3452636/134293401-17afccfa-0957-43e0-a114-fbaf9915ecdb.png)

The same result in observed in iOS application, desktop app and browsers and is reported by multiple users.

#### Possible fixes
No idea.

#### Versions

Mattermost Version: 5.37.2
Database Schema Version: 5.37.2
Database: postgres

**Comment by amyblais** [comment]
@vlfesko Would you be able to help post this troubleshooting question on [our troubleshooting forum here](https://forum.mattermost.org/) or on our [community server's Peer-to-peer Help channel here](https://community.mattermost.com/core/channels/peer-to-peer-help), and our community or devs will likely be able to help with this?
