### ISSUE TITLE
Problem of Formatting Text with Persian language

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#18465]
Hello friends

Look at the pictures to see the problem

![image](https://user-images.githubusercontent.com/29058805/134761769-96396615-a865-49a8-bfb4-458f21da6516.png)

![image](https://user-images.githubusercontent.com/29058805/134761781-2ff05804-9adb-4eec-8be3-945881430d16.png)

The subset is not done in Persian language mode

@tbalthazar @lurcio @mauricio @cored

**Comment by amyblais** [comment]
@majidit Did you use a plugin to enable the Persian language?

**Comment by majidit** [comment]
Yes ...

Mattermost RTL (ir.quera.mattermost-rtl - 0.2.0)
This plugin adds RTL support to Mattermost.

**Comment by mjnaderi** [comment]
This issue can be closed according to https://github.com/QueraTeam/mattermost-rtl/commit/7d0224fa42aff64419af0873f9e078c097187e1a.
