### ISSUE TITLE
Bug: Paste from clipboard to message editor by Ctrl+v when focus on chat box is not working 

### ISSUE THREAD

**Issue by slonm** [mattermost/mattermost-server#18461]
#### Summary
We could start input from keyboard anytime and if last clicked control have no input ability like chat box or contacts box then message editor got focus and take input instantly.
That's not true if we paste text from clipboard by Ctrl+v. That's often case for me then i copy-past message parts from chat box.

#### Steps to reproduce
Select couple words in chat box then copy it to clipboard by pressing Ctrl+C then paste it to message editor by pressing Ctrl+V

#### Expected behavior
Selection copied to new message at the cursor position in the message editor 

#### Observed behavior (that appears unintentional) 
No obvious action results. Selection is not pasted

**Comment by amyblais** [comment]
@slonm 

1. What OS and version are you on?
2. What is your Mattermost server version?
3. Are you experiencing the issues with the browser webapp, if so which one?
4. Are you experiencing the issues with the Mattermost Desktop App, if so what version and OS?

**Comment by slonm** [comment]
Q: What OS and version are you on?
A: Desktop client v 4.6.2 on Windows 10

Q: What is your Mattermost server version?
A: 5.35.2 

Q: Are you experiencing the issues with the browser webapp, if so which one?
A: I lost my login password and unable to check for a while

**Comment by amyblais** [comment]
@slonm When you have a chance, would you be able to upgrade and test if you can still reproduce the issue with these versions:

1. Desktop app v4.7..2.
2. Mattermost server version v5.37.2 or later. You can also test on our [community server here](https://community.mattermost.com), which is on the latest server version.

**Comment by slonm** [comment]
Confirmed fix in v4.7.2 and work as expected on community server in the Google Chrome.
Sorry for bother you.

I'm surprized desktop client don't check for upgrades

**Comment by amyblais** [comment]
Glad to hear! We're working on a desktop auto-updater for a future release,
