### ISSUE TITLE
Alt pressing set focus to menu and second pressing does not rewert focus to message editor

### ISSUE THREAD

**Issue by slonm** [mattermost/mattermost-server#18469]
#### Summary
Alt pressing set focus to menu and second pressing does not rewert focus to message editor

#### Steps to reproduce
1. Set focus to message editor and start write something.
2. Press Alt.
3. Press Alt again.
4. Continue writing.

#### Expected behavior
Focus revert to message editor and i can continue input.

#### Observed behavior (that appears unintentional) 
After press Alt focus stick to menu and does not back on second press. 

The issue observed on:
- Windows 10 + Google Chrome 93.0.4577.82
- Windows 10 + Desktop client v 4.7.2

The issue does not observed on Windows 10 + Firefox 92.0

Server versions: master-72307, 5.35.2

**Comment by amyblais** [comment]
@slonm Would you be open to testing if you can also reproduce this on desktop app v5.0-rc1 https://github.com/mattermost/desktop/releases/tag/v5.0.0-rc1?

If you'd prefer not to download the RC, I can ask QA to help test this as I don't have Windows.

**Comment by slonm** [comment]
Reproduced on desktop app v5.0-rc1

**Comment by hmhealey** [comment]
Thanks for the report, @slonm. This seems like it's an issue with Chromium on Windows since I'm able to reproduce it using both Chrome and Edge on Windows 11, but not using Chrome on Mac. It also reproduces on Google and on Slack, so I don't think it's something that we can change ourselves.
