### ISSUE TITLE
Migrate from gorp to sqlx in store/sqlstore/command_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18503]
Mattermost is migrating from using `gorp` as a sql library to using `sqlx`.

This ticket is about migrating all usages of gorp in `store/sqlstore/command_store.go` to sqlx.

The way to proceed would be as follows:

All SQL queries are usually executed from `GetMaster()` or `GetReplica()` calls which return the gorp instance for the DB. We have a corresponding method `GetMasterX`/`GetReplicaX` which return the sqlx instance instead.

All named params in SQL query strings should be replaced with `?` and then a list of args should be passed to the method. Here is a quick cheat sheet of the methods to replace with:

```
GetReplica().SelectOne() -> GetReplicaX().Get()
GetReplica().Get() -> GetReplicaX().Get()
GetReplica().Select() -> GetReplicaX().Select()
GetMaster().Insert() -> GetMasterX().NamedExec()
GetMaster().Update() -> GetMasterX().NamedExec()
GetMaster().Exec() -> GetMasterX().Exec()
```

For some practical examples of migrations, please feel free to take a look at:
https://github.com/mattermost/mattermost-server/pull/18302
https://github.com/mattermost/mattermost-server/pull/18301

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-38999

**Comment by gupsho** [comment]
I can take this.

**Comment by agnivade** [comment]
Hey @gupsho - how is it going with this? Let me know I can help in any way.

**Comment by gupsho** [comment]
@agnivade got busy for a few days. will create a PR in next couple days.

**Comment by gupsho** [comment]
> Hey @gupsho - how is it going with this? Let me know I can help in any way.

@agnivade I am getting error while running test.
"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Trigger,Method,Username,IconURL,AutoComplete,AutoCompleteDesc,AutoCompleteHint,D' at line 1". 
I cannot figure out what is the issue. Any help is appreciated. Could it be that Trigger is a keyword?

**Comment by agnivade** [comment]
Yep, that's right. Trigger is a keyword. Have a look at https://github.com/mattermost/mattermost-server/pull/18633 to see how we solved it :)

**Comment by gupsho** [comment]
> Yep, that's right. Trigger is a keyword. Have a look at #18633 to see how we solved it :)

Thank you. That fixed it.
