### ISSUE TITLE
Emoji list does not scroll correctly (gets stuck)

### ISSUE THREAD

**Issue by kirkaDev** [mattermost/mattermost-server#18519]
I confirm (by marking "x" in the [ ] below: [x]):

- [ ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10 Pro
- Mattermost Desktop App version: 4.6.2 
- Mattermost Server version: Unknown 

**Steps to reproduce**
1. Open any channel or direct correspondence.
2. Click on the button "Emoji".
3. Scroll list.

**Expected behavior**
See smooth scrolling

**Observed behavior**
Scrolling gets stuck at some point.
After scrolling has stopped, further rotation of the mouse wheel has no effect.
If in this case the position of the mouse pointer is slightly changed, then scrolling will resume.

It looks like it has nothing to do with receiving emoji from the server. when using the scrollbar everything is fine.
This occurs regardless of how quickly you turn the mouse wheel.

It looks like a problem with the UI, maybe a problem with the loss of focus in the list.

**Comment by amyblais** [comment]
@kirkaDev 
1. Are you able to reproduce it with Desktop app v4.7.2?
2. What Mattermost server version are you on (Main Menu > About Mattermost)?
3. Are there any errors in Mattermost logs?

**Comment by kirkaDev** [comment]
> @kirkaDev
> 
> 1. Are you able to reproduce it with Desktop app v4.7.2?
> 2. What Mattermost server version are you on (Main Menu > About Mattermost)?
> 3. Are there any errors in Mattermost logs?

1. Yes, in version v.4.7.2 everything is ok.
2. Server version is v.5.34.2

Sorry to bother you in vain.
