### ISSUE TITLE
Joining a channel without permission to leads to inconsistent errors

### ISSUE THREAD

**Issue by ac83943** [mattermost/mattermost-server#18513]
#### Summary
Depending on how you attempt to join a channel the UI is inconsistent in breaking / showing a misaligned error message.

#### Steps to reproduce
Give yourself invalid permissions to join a channel (e.g. group restrictions).  An easy way of doing this is to add the following lines onto the start of /api4/channel.go:addChannelMember:

```
// any permission issue can be used here.
c.SetPermissionError(model.PERMISSION_MANAGE_PRIVATE_CHANNEL_MEMBERS)
return
```

Then try to join the channel that you have given yourself invalid permissions for.

#### Expected behavior
A user is provided information that the channel they have requested is not join able.

#### Observed behavior (that appears unintentional) 
Depending on how you join the channel, it may:

1. Hang the application, leading to an infinite 'loading' screen
<img width="1166" alt="Screenshot 2021-10-03 at 00 08 50" src="https://user-images.githubusercontent.com/89583054/135733954-47ec661e-ff1a-4b9b-82d8-cd194c7a5302.png">

This happens if you visit it directly via the URL (in this case http://localhost:8065/abc/channels/some_test_private_channel).  It also happens if you use the channel switcher:
<img width="634" alt="Screenshot 2021-10-03 at 00 10 46" src="https://user-images.githubusercontent.com/89583054/135733985-d3737a15-ff0b-4442-85a0-18ca7db057e4.png">

2. Lead to an error message that is off the screen and you have to scroll down to reach
<img width="620" alt="Screenshot 2021-10-03 at 00 11 59" src="https://user-images.githubusercontent.com/89583054/135734015-c6c25be7-478f-42f5-8b11-4d45493d153c.png">

This happens if you try to join it via the "+" -> "Browse Channels" button.

#### Possible fixes
When loading a channel you don't have permission to, it should display a user visible error.  When trying to join a channel you don't have permission to, the error should be more visible and on screen (e.g. at the top of the channel select screen?)

**Comment by amyblais** [comment]
@ac83943 
1. What Mattermost server version are you on?
2. What OS and version are you on?

**Comment by ac83943** [comment]
1. This is running Mattermost Server v5.39.
2. My OS is MacOS 11.6.

Operating system is Firefox, latest version.

**Comment by amyblais** [comment]
@ac83943 Does this seem similar to this earlier report https://github.com/mattermost/mattermost-server/issues/18284?

A PR to fix it is here: https://github.com/mattermost/mattermost-webapp/pull/8739.

**Comment by ac83943** [comment]
The `loading...` hanging seems to stem from when the API responds to a request to join a channel with:

```
api.channel.add_members.user_denied
```

<img width="831" alt="Screenshot 2021-10-06 at 12 13 48" src="https://user-images.githubusercontent.com/89583054/136192464-40501e36-e431-4bf5-a2b2-cb3282b081cb.png">

This is not properly handled in the UI, which continues to try to get messages, etc.  These fail, due to not being a part of the membership of the channel:

<img width="835" alt="Screenshot 2021-10-06 at 12 13 56" src="https://user-images.githubusercontent.com/89583054/136192553-6708ceb5-ed45-4680-8424-8735c7f602d4.png">

**Comment by ac83943** [comment]
This should likely be two issues.  One for not handling errors when joining channels.  Another for the weird UI issue when trying to join a channel using the channel browser when you don't have permission.
