### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T1233 UP - Other user posts reply to first user's post: Parent post opens for editing for first user"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18522]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T1233 UP - Other user posts reply to first user's post: Parent post opens for editing for first user</h1>
<div>
<div>
<h3>Steps </h3>1. As UserA make a post
<br>2. As UserB, reply to UserA's post
<br>3. As UserA, click on Reply icon for the post you made in 1) so the RHS opens
<br>4. As UserA, press the UP arrow on your keyboard<h3>Expected</h3>After 4) UserA's parent post, made in step 1), opens to be edited.<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/keyboard_shortcuts``
**Test code arrangement:**
```
describe('Keyboard Shortcuts', () => {
    it('MM-T1233 UP - Other user posts reply to first user's post: Parent post opens for editing for first user', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by deepto98** [comment]
@saturninoabril I'd like to work on this, can you assign this issue to me?

**Comment by saturninoabril** [comment]
Sure @deepto98 and thanks for your interest!

**Comment by saturninoabril** [comment]
Closing now and will submit new set of help-wanted issues.
