### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T1228 CTRL/CMD+K - Open DM with user not on the current team"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18523]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T1228 CTRL/CMD+K - Open DM with user not on the current team</h1>
<div>
<div>
<h3>Steps </h3>CTRL/CMD+K - Open DM with user not on the current team<br>–––––––––––––––––––––––––<ol><li>Identify a user who doesn't belong to the same team</li><li>Press CTRL+K (Windows) or CMD+K (Mac)</li><li>Type the username from step 1 and select the username</li></ol><h3>Expected</h3>Direct message channel with the user opens<br><br>Note: Should test each case with "TeamSettings.RestrictDirectMessage" set to "any" and "team".<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/keyboard_shortcuts``
**Test code arrangement:**
```
describe('Keyboard Shortcuts', () => {
    it('MM-T1228 CTRL/CMD+K - Open DM with user not on the current team', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by AvineshTripathi** [comment]
can I give this issue a try ? also can you share some resources for the same

**Comment by saturninoabril** [comment]
Sure and thanks for your interest @AvineshTripathi!

Please see issue description and let me know if you have questions or would like to know specific resources. For quick info, 
- If you're new to Mattermost, then see https://developers.mattermost.com/contribute/getting-started/.
- For docs specific to our end-to-end testing, see https://developers.mattermost.com/contribute/webapp/end-to-end-tests/.
- If you'd like to see some actual code, you may go ahead and see [mattermost-webapp/e2e](https://github.com/mattermost/mattermost-webapp/tree/master/e2e) folder or [mattermost-webapp/e2e/cypress/integration/keyboard_shortcuts](https://github.com/mattermost/mattermost-webapp/tree/master/e2e/cypress/integration/keyboard_shortcuts) for tests that may be related to Keyboard Shortcuts.

**Comment by AvineshTripathi** [comment]
hey @saturninoabril  I am not able to setup the repo locally maybe due to OS version differnece so taking down my name for now till I do setup so that this issue gets done P.S if you have a solution for Linus setup for deb 20.4 let me know

**Comment by saturninoabril** [comment]
Thanks @AvineshTripathi for the update and no worries. I wonder if you've tried the Ubuntu "server" setup here - https://developers.mattermost.com/contribute/server/developer-setup/ . It's not updated for 20.04 but I assume it will be the same. For the "webapp" part, it's here -- https://developers.mattermost.com/contribute/webapp/developer-setup/.

**Comment by poflankov** [comment]
Hi! Can I take this?

The requirements say that the user we are looking for must not belong to the current team.
This may be in conflict with the note, which says that the "team" setting must also be covered.
But in this case, a user not belonging to the current team will not be found.
From the documentation, I understood that if that user belonged to the current and another team at the same time, then he would be found. Is this the case I need to cover in this test?

**Comment by saturninoabril** [comment]
@poflankov Sure and thanks for your interest! Good catch and question!

> But in this case, a user not belonging to the current team will not be found.

True. Please cover this case in test too.

> From the documentation, I understood that if that user belonged to the current and another team at the same time, then he would be found. Is this the case I need to cover in this test?

Yes.

**Comment by sinansonmez** [comment]
@saturninoabril should this issue be closed?

**Comment by saturninoabril** [comment]
@sinansonmez Thanks for checking! Closing now.
