### ISSUE TITLE
Not possible: ALTER TABLE mattermost.RetentionPolicies CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci

### ISSUE THREAD

**Issue by diolwe** [mattermost/mattermost-server#18624]
This could be a duplicate of / related to: https://github.com/mattermost/mattermost-server/issues/18021

#### Summary

I upgraded to mysql 8.0.26 (now: Debian Bullseye) and had to alter all the mattermost tables. Most of them didn't throw up any problems - but three of them did: those containing RetentionPolicies.

````
mysql> ALTER TABLE mattermost.RetentionPolicies CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
````

produces 

````
ERROR 3780 (HY000): Referencing column 'PolicyId' and referenced column 'Id' in foreign key constraint 'FK_RetentionPoliciesTeams_RetentionPolicies' are incompatible.
````
and the same is true for:

````
ALTER TABLE mattermost.RetentionPoliciesChannels CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;          
ALTER TABLE mattermost.RetentionPoliciesTeams CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;   
````

When Mattermost is used on CLI the problem appears as:

````
sudo -u mattermost bin/mattermost team list
[...]
{"level":"warn","ts":1633790940.5747385,"caller":"sqlstore/store.go:1164","msg":"Could not create foreign key: Error 1826: Duplicate foreign key constraint name 'FK_RetentionPoliciesChannels_RetentionPolicies'"}
{"level":"warn","ts":1633790940.5751045,"caller":"sqlstore/store.go:1164","msg":"Could not create foreign key: Error 1826: Duplicate foreign key constraint name 'FK_RetentionPoliciesTeams_RetentionPolicies'"}
[...]
````
Is there anything I can do to fix this problem - which is: to convert the three tables?

**Comment by streamer45** [comment]
@diolwe 

The warning log you shared is totally harmless and expected and also not related to the collation issues. Is there any other error you are seeing or some other malfunction?

**Comment by ironiemix** [comment]
No, there is no other malfunction, we are just unable to convert the db-tables . The site is up and productive, just thinking that there may be problems later on, when further upgrading will occur without having converted the tables?

**Comment by streamer45** [comment]
@ironiemix 

If that's the case I'd suggest to temporarily dropping the foreign keys, do the conversion on the affected tables and finally adding the constraints back. E.g.:

```sql
ALTER TABLE RetentionPoliciesChannels DROP FOREIGN KEY FK_RetentionPoliciesChannels_RetentionPolicies;
ALTER TABLE RetentionPoliciesTeams DROP FOREIGN KEY FK_RetentionPoliciesTeams_RetentionPolicies;

ALTER TABLE RetentionPolicies CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
ALTER TABLE RetentionPoliciesChannels CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;      
ALTER TABLE RetentionPoliciesTeams CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

ALTER TABLE RetentionPoliciesChannels  ADD CONSTRAINT FK_RetentionPoliciesChannels_RetentionPolicies  FOREIGN KEY (PolicyId) REFERENCES RetentionPolicies (Id)  ON DELETE CASCADE;
ALTER TABLE RetentionPoliciesTeams  ADD CONSTRAINT FK_RetentionPoliciesTeams_RetentionPolicies  FOREIGN KEY (PolicyId) REFERENCES RetentionPolicies (Id)  ON DELETE CASCADE;
```

**Comment by ironiemix** [comment]
FYI: Indeed there was a malfunction in the end which was caused from the wrong collation. There were no teams shown in the system console and the mmctl command failed to list the existing teams with the following error:

`
{"timestamp":"2022-03-17 21:57:04.207 +01:00","level":"error","msg":"We could not get all teams.","caller":"web/context.go:105","path":"/api/v4/teams","request_id":"ex17q8XXXXbe5nwynb86utfe1y","ip_addr":"79.XXX.2.195","user_id":"pubresupXXXX4jftj9n9jeksno","method":"GET","err_where":"GetAllTeamsPage","http_code":500,"err_details":"failed to find Teams: Error 1267: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='"}
`

Your fix from above allowed me to update the collations and fixed the issue with the team listings as well. Thanks for that!
