### ISSUE TITLE
Cannot leave group conversation

### ISSUE THREAD

**Issue by Germano0** [mattermost/mattermost-server#18625]
#### Summary
I have been added in a group conversation (not a channel), and even if I left this conversation, as soon someone writes a new message in such conversation, this conversation appears again in my conversations list that means that I am still inside the conversation

#### Expected behavior
No longer being added again into a foo group conversation once I had left it

#### Observed behavior (that appears unintentional) 
as soon someone writes a new message in such conversation, this conversation appears again in my conversations list that means that I am still inside the conversation.

```
Mattermost Team Edition
Mattermost Version: cern-ci
Database Schema Version: 5.39.0
Database: postgres
Build Date: Wed Sep 29 15:33:24 UTC 2021
```

**Comment by amyblais** [comment]
@Germano0 Do you have steps for how you leave the group message? If you're using the "Close" option, it just removes it from the left-hand side, but it is expected to re-appear if there are new messages. However, you can use the "Mute Conversation" option to mute it.

**Comment by Germano0** [comment]
Done, thank you
