### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T1234 CTRL/CMD+K

Setup for following tests

Display order of search results"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18643]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T1234 CTRL/CMD+K Setup for following tests Display order of search results</h1>
<div>
<div>
<h3>Steps </h3>On a team with enough channels to observe alphabetical order (with some channels that have the first letter in common):<br /><br />1. Ensure there are also GMs and DMs that can start with the same letter, or create GM channels and/or users if needed<br />2. Press CTRL+K (Windows) or CMD+K (Mac)<br />3. Type the first letter in the &quot;Switch Channels&quot; modal message box<h3>Expected</h3>- Channels are ordered by channels, DMs and GMs you belong to listed first<br /><br />- Results that *begin* with the letter you searched on appear (in alpha order) above results that just *contain* the letter (then in alpha order again) <br /><br />- Each channel type has an appropriate icon next to the channel name: [globe for public; lock for private; profile picture for DMs and GMs]<br /><br />- Display of DM / GMs matches message autocomplete, i.e. &quot;@username - FirstName LastName (Nickname)&quot;<br /><br />- Deactivated users appear at the bottom of the user list<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/keyboard_shortcuts``
**Test code arrangement:**
```
describe('Keyboard Shortcuts', () => {
    it('MM-T1234 CTRL/CMD+K Setup for following tests Display order of search results', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by poflankov** [comment]
Hi, can I take this?

**Comment by saturninoabril** [comment]
Sure and thanks @poflankov!

**Comment by saturninoabril** [comment]
@poflankov Btw, I wonder if you have account in our https://community.mattermost.com/. Just like to get in touch in case.

**Comment by saturninoabril** [comment]
Closing now and will submit new set of help-wanted issues.
