### ISSUE TITLE
Bulk import makes the system message the user message

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-server#18640]
#### Summary
System messages are changed to user messages when bulk export/import is processed.

**Before**
<img width="836" alt="スクリーンショット 2021-10-11 22 19 11" src="https://user-images.githubusercontent.com/1453749/136873367-1d323d4f-d30e-4536-af26-99c6976349bc.png">

**After**
(`kaakaa`'s message was system message in before instance. Its message body was translated into server default language when exporting)

<img width="794" alt="スクリーンショット 2021-10-11 22 19 44" src="https://user-images.githubusercontent.com/1453749/136873428-04871786-853f-4326-b198-272a06ebacd8.png">

#### Steps to reproduce
1. Do bulk export by `bin/mattermost export bulk data.json`
    - Exported data has the post that is system message such as `XX joined the team.` 
2. Import exported data to new mattermost instance by `bin/mattermost import bulk data.json --apply`

#### Expected behavior
System message will be imported to new instance as system message.

#### Observed behavior (that appears unintentional) 
System message was changed to user message, and its message body will be translated and exported into the server default language of the exported instance.

#### Possible fixes

Make `Post.Type`  the target of export/import

In the same way, should make `Post.EditAt` the target, because existing export/import will drop `edited` flag to the post.

**Comment by amyblais** [comment]
cc @streamer45 on this and https://github.com/mattermost/mattermost-server/issues/18641

**Comment by streamer45** [comment]
Make sense to open tickets. @isacikgoz would your team be able to own these or at least triage them accordingly?

**Comment by kaakaa** [comment]
Can I take this ticket?

**Comment by streamer45** [comment]
> Can I take this ticket?

That would be great @kaakaa . I've assigned it to you :+1:

**Comment by kaakaa** [comment]
@streamer45 I've created #18992
