### ISSUE TITLE
DesktopMinVersion setting not used by Desktop Application

### ISSUE THREAD

**Issue by GuiGuiSoft** [mattermost/mattermost-server#18701]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).  
--> Not very relevant 😄 
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The `DesktopMinVersion` parameter defined in `config.json` is not used by the Desktop Application.

**Environment**
- Operating System: Windows
- Mattermost Desktop App version: 4.7.2
- Mattermost Server version: 5.39.2 (embedded in GitLab Omnibus)

**Steps to reproduce**
1. Define the DesktopMinVersion setting to “5.0.0” in `config.json`
2. Restarted Mattermost server
3. Connect to the server with the Desktop Application (version 4.7.2)

**Expected behavior**
The user can not access the server and an explicit message is displayed.

Example/Suggestion:

> This server requires a least the version `DesktopMinVersion value` of the Mattermost Desktop Application.
> Please upgrade your Mattermost Desktop Application by downloading a newer version here : (link to `AppDownloadLink value`).

**Observed behavior**
The user access the server without any error/warning message.

**Possible fixes**

No idea :)

**Comment by devinbinnie** [comment]
Since the feature is incomplete and isn't actually being used by any of the apps, we're electing to close this issue and remove the existing code.

**Comment by GuiGuiSoft** [comment]
I understand, but disappointed.

It was a good and simple idea to encourage users to update their clients, especially when security issues are fixed on the desktop app (which does not contain any auto-update feature) :/

**Comment by devinbinnie** [comment]
> I understand, but disappointed.
> 
> It was a good and simple idea to encourage users to update their clients, especially when security issues are fixed on the desktop app (which does not contain any auto-update feature) :/

@GuiGuiSoft I apologize. We are working on an auto-update feature that will be released in v5.1

**Comment by GuiGuiSoft** [comment]
> We are working on an auto-update feature that will be released in v5.1

# \o/
