### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T1271 UP - Removing all text in edit deletes post"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18714]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T1271 UP - Removing all text in edit deletes post</h1>
<div>
<h3>Updated (Oct 19):</h3>
<p>The following steps and expectations were updated as observed in the <a href="https://github.com/mattermost/mattermost-server/issues/18714#issuecomment-945993723">comment</a>. See <a href="https://automation-test-cases.vercel.app/test/MM-T1271">https://automation-test-cases.vercel.app/test/MM-T1271</a> for updated test case.</p>
<div>
<h3>Steps </h3>1. Post a message (in center, no attachments)<br />2. Press UP<br />3. Remove all text from the edit box and press ENTER<br />4. Observe confirmation modal and press ENTER again<h3>Expected</h3>Message is deleted and "(edited)" is displayed <br /><br />(If message had an attachment, it is not deleted)<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/keyboard_shortcuts``
**Test code arrangement:**
```
describe('Keyboard Shortcuts', () => {
    it('MM-T1271_1 UP - Removing all text in edit deletes post if without attachment', () => {
        // code
    });

    it('MM-T1271_2 UP - Removing all text in edit does not delete post if with attachment', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by saturninoabril** [comment]
@iOSGeekster Thanks for pointing out and you're totally correct! For your question, other user will be shown with ephemeral post of "(message deleted)" if the client initially received the post. Otherwise, nothing will be shown to other user.
I've updated the description above linking to the updated test case from our test management system - https://automation-test-cases.vercel.app/test/MM-T1271. Let me know if you have more question/clarification.

**Comment by iOSGeekster** [comment]
Cool, thanks. I'll try that out later today.
