### ISSUE TITLE
Empty emoji picker with 6.0.0 and cleared cache

### ISSUE THREAD

**Issue by Netpilgrim** [mattermost/mattermost-server#18739]
#### Summary
After a server update to 6.0.0 the emoji picker is empty except for custom emoji. Not all web browsers seem to be affected.

#### Steps to reproduce
- Update Mattermost server to 6.0.0.
- Open an affected client (tested: Desktop App 4.7.0 for Windows, Desktop App 5.0.0 for Linux and Windows, Firefox 93.0 for Linux).
- Clear cache and reload.
- Open the emoji picker (either next to the message entry form or below a mesage for reactions).

#### Expected behavior
- The emoji picker shows all emoji.

#### Observed behavior (that appears unintentional) 
- The emoji picker shows only custom emoji (Desktop App) or only custom emoji and a few scattered, in some cases cropped, standard emoji (Firefox).
- Chromium 94.0.4606.81 for Linux seems unaffected and shows all emoji.

![screenshot_20211018T132223](https://user-images.githubusercontent.com/995046/137725957-b21c36cd-7dc9-4125-9638-3e5fa2367f61.png)
![screenshot_20211018T140048](https://user-images.githubusercontent.com/995046/137726271-63389e02-877e-41d8-81ca-84b31439872c.png)

#### Possible fixes
(none)

**Comment by amyblais** [comment]
@hmhealey @jgilliam17 Do you recall seeing/hearing about reports like this in the past?

**Comment by jgilliam17** [comment]
@amyblais I don't recall seeing this in the past. I am not able to repro on my end using Win10 Desktop 5.0 or Firefox and Edge browsers on Win10

**Comment by Netpilgrim** [comment]
> If you want for a minute or close and reopen the emoji picker, do they start to load in? That component definitely has some performance issues that we're going to be working on in the next month or two, so it might just be really slow, especially after the cache is cleared.

Keeping the emoji picker open for a long time (up to 30 minutes) did not result in more emoji being loaded (tested in Firefox). On the other hand, in my desktop app, which is the one I have running continuously, all emoji have suddenly reappeared after not opening the dialog for some time.
Most colleagues are still reporting the problem, although there is some indication that it is more prevalent with users working from home and thus having a slower connection to the server, which is located at our company's site.

> Also, what version did you upgrade from to 6.0? It's possible that this would've gotten worse a few releases earlier when we added support for many new emojis. I don't think 6.0 had any major changes to the emoji picker itself, so that'd help us isolate what might be causing this.

The update was from 5.39.0 to 6.0.0.

**Comment by amyblais** [comment]
Let us know if you're still experiencing this on a more recent server version. We are also planning emoji picker performance improvements for v6.6 (April) release.
