### ISSUE TITLE
No more preview in posts

### ISSUE THREAD

**Issue by isAAAc** [mattermost/mattermost-server#18731]
Hello, 
i opened an issue about preview in mosts in [mattermost_ynh](https://github.com/YunoHost-Apps/mattermost_ynh/issues/295) but the maintainer think it could be an issue in the generic mattermost , so i post it here too.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-40448.

**Comment by ddeenniiss** [comment]
Same issue here, even after upgrading to the latest version

**Comment by clevertree** [comment]
youtube links fail even after adding API key in latest version. Not much we can do about it. It's corporate sabotage by centralized chat software to stay in profit.
