### ISSUE TITLE
File content extraction resulting in "invalid byte sequence for encoding" error

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-server#18735]
#### Summary
Log reports

> failed to save the extracted file content: failed to update FileInfo content with id=xxx: pq: invalid byte sequence for encoding "UTF8": 0xe2 0xe3 0xcf

#### Steps to reproduce
Unknown

Mattermost 5.38.2 installed via GitLab Omnibus 14.3.3

#### Expected behavior
No error in logs

#### Observed behavior (that appears unintentional) 
Error above

#### Possible fixes
Unknown

**Comment by bbodenmiller** [comment]
@jespino I'm not sure how to figure out what file triggered the error as that doesn't seem to be in the log message.

**Comment by amyblais** [comment]
I'm cleaning up some older issues. If you need further assistance on this, I recommend reaching out to our devs / community via https://forum.mattermost.com/ or via our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help).
