### ISSUE TITLE
Custom Emoji page: next button disappears after clicking previous button on next page

### ISSUE THREAD

**Issue by hgs81** [mattermost/mattermost-server#18741]
#### Summary
`Next` button disappears after clicking `Previous` button on next page in Custom Emoji page.

#### Steps to reproduce
- Go to Custom Emoji page
- Click `Next` to navigate to next page (2/2)
- Click `Previous` to navigate to previous page (1/2)
- Now, `Next` button disappears

#### Expected behavior
`Next` button should appear on first page.

#### Observed behavior (that appears unintentional) 
Next button disappears.
I found this issue in version v5.29.0, but still exists after upgrading to latest v6.0.0.

#### Possible fixes
It looks like a small bug that can be fixed with the modification of a few lines of code.

**Comment by shrzkhn** [comment]
@amyblais Hi, I am looking to fix this. Could you please assign this issue to me.
