### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T2044 Clear fields, values revert"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18819]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

## MM-T2044: Clear fields, values revert

---

**Step 1**

Clear fields, values revert\
————————————\
1\. Go to User menu > Profile > Profile Settings > Full Name > Edit\
2\. Change fields to blank\
3\. Cancel

**Expected**

Full name field reverts to previous value (should not be blank).

**Test Folder:** ``/cypress/tests/integration/channels/profile_settings``
**Test code arrangement:**
```
describe('Profile Settings', () => {
    it('MM-T2044 Clear fields, values revert', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by prapti** [comment]
Sorry for the delay on this one. I'll work on it soon!

**Comment by saturninoabril** [comment]
No worries and thanks for the update Prapti!

**Comment by sinansonmez** [comment]
If @prapti is not working on this I can try @saturninoabril

**Comment by saturninoabril** [comment]
@sinansonmez Sure and thanks!

**Comment by adj2908** [comment]
Hi @saturninoabril ,

If @sinansonmez is not working on this then can I please try this? 

Thanks.

**Comment by sinansonmez** [comment]
I was busy with other tickets so i couldnt work on this. Please go ahead @adj2908

**Comment by adj2908** [comment]
Thanks @sinansonmez. @saturninoabril Please assign me this issue.

**Comment by saturninoabril** [comment]
Thanks for your interest @adj2908!

**Comment by adj2908** [comment]
@saturninoabril Just to clarify, these tests should be written just for the first name or for all the fields. Thanks.

**Comment by saturninoabril** [comment]
Hello @adj2908, good question. Only for full name. You may find updated test case at https://github.com/mattermost/mattermost-test-management/blob/main/data/test-cases/channels/profile-settings/MM-T2044.md. With that, please add spec to this folder: `/cypress/channels/profile_settings` (new folder to be created). I've updated the description as well.

**Comment by adj2908** [comment]
Thanks. Any reason why we are not writing tests for other fields in the profile modal?

**Comment by saturninoabril** [comment]
It should be covered by other test case.

**Comment by adj2908** [comment]
So will you create a separate ticket for that? If yes I will be interested in working on that.

**Comment by saturninoabril** [comment]
Cool, let me check and will let you know. Thanks @adj2908!

**Comment by saturninoabril** [comment]
There are still some tests that are yet to be automated for Profile Settings. You may look directly at [mattermost-test-management --> test-cases/channels/profile-settings](https://github.com/mattermost/mattermost-test-management/tree/main/data/test-cases/channels/profile-settings) (or in any other folder for other test area), pick a test case then search in [mattermost-webapp/e2e/cypress](https://github.com/mattermost/mattermost-webapp/tree/master/e2e/cypress) for the search test key (MM-Txxx). If nothing returned, then it's available to be automated. Let me know if you find anything and if you have question.

**Comment by adj2908** [comment]
Hey @saturninoabril, Are you sure that the test needs to be added to  `/cypress/channels/profile_settings`?  I don't think that this is related to channels at all. I think this should be inside `e2e/cypress/tests/integration/profile_settings`. Can you confirm? Thanks.

**Comment by saturninoabril** [comment]
Yes, it should be at `/cypress/tests/integration/channels/profile_settings` (updated the description). As we transition to multi-product architecture, the folder structure follows the same with the "channels" in the context of products (such as Channels, Playbooks, Boards, Calls), and it will eventually follow the folder structure at the previously linked test cases in https://github.com/mattermost/mattermost-test-management/tree/main/data/test-cases.

**Comment by adj2908** [comment]
We can close this as changes have been merged. Thanks

**Comment by saturninoabril** [comment]
Thanks @adj2908!
