### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T2075 Profile Picture: Cancel out of adding profile picture"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18814]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T2075 Profile Picture: Cancel out of adding profile picture</h1>
<div>
<div>
<h3>Steps </h3>Profile Picture<br />&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;<br />1. Go to Profile -&gt; Profile Settings -&gt; Profile Picture -&gt; Edit<br />2. Click &quot;Select&quot;<br />3. Upload a picture, observe preview of image<br />4. Cancel<h3>Expected</h3>Profile picture does not update.<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/account_settings``
**Test code arrangement:**
```
describe('Account Settings', () => {
    it('MM-T2075 Profile Picture: Cancel out of adding profile picture', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by poflankov** [comment]
Can I take this?

**Comment by saturninoabril** [comment]
Sure and thanks @poflankov!

**Comment by poflankov** [comment]
Can I gather the code for this ticket with the code for #18815 into [9457](https://github.com/mattermost/mattermost-webapp/pull/9457)?
The tasks are pretty close.

**Comment by saturninoabril** [comment]
I agree, thanks for checking @poflankov!

**Comment by poflankov** [comment]
It's already merged, so i will make another PR

**Comment by poflankov** [comment]
Should I first add a profile picture (aka "old profile picture") as in #18815 first step?
Or should  I verify that "Profile picture does not update" against "no picture"?.

**Comment by saturninoabril** [comment]
I'd suggest to have them both. First is doing cancel when no profile picture yet, then last when there's a profile picture already.
