### ISSUE TITLE
Mattermost server throwing 50x errors - Too many open files

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-server#18810]
#### Summary
A few times now on various versions (at least 5.38.2 & 5.33) of Mattermost we've started getting 500 errors and logs showing `too many open files`. Restarting server fixed issue (didn't try just restarting Mattermost first).

#### Steps to reproduce
Unknown

#### Expected behavior
Properly close file handlers

#### Observed behavior (that appears unintentional) 
50x errors for users

Thousands of `too many open files` errors over <15 minutes

Our limits look like they should be sufficiently high

```
$ cat /proc/${PID}/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            10485760             10485760             bytes
Max core file size        0                    0                    bytes
Max resident set          unlimited            unlimited            bytes
Max processes             unlimited            unlimited            processes
Max open files            50000                50000                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       62793                62793                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

Interestingly `sudo ls -halt /proc/${PID}/fd` seems to show oldest FD is only 90 minutes old and currently we're nowhere near `50000` limit

#### Possible fixes
Unknown

Could a plugin cause this issue? How might we debug that?

**Comment by vineelyalamarthy** [comment]
@amyblais  any help needed?

**Comment by amyblais** [comment]
I'm cleaning up some older issues. If you need further assistance on this, I recommend reaching out to our devs / community via https://forum.mattermost.com/ or via our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help).
