### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T2077 Profile Picture: Non-image file shows error"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18820]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T2077 Profile Picture: Non-image file shows error</h1>
<div>
<div>
<h3>Steps </h3>Profile Picture<br />&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;<br />1. Find or create a text file<br />2. Rename file to have extension `.png` instead of `.txt`<br />3. Try to upload as profile pic<h3>Expected</h3>Error message &quot;Could not save profile image. File does not appear to be a valid image.&quot;<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/account_settings``
**Test code arrangement:**
```
describe('Account Settings', () => {
    it('MM-T2077 Profile Picture: Non-image file shows error', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by sinansonmez** [comment]
Hello, @saturninoabril I just created a PR for this. Please let me know if you have any comments

**Comment by saturninoabril** [comment]
Awesome, thanks! It's up for review 💯
