### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T2076 Profile Picture: Non-square image is cropped and centered"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-server#18823]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T2076 Profile Picture: Non-square image is cropped and centered</h1>
<div>
<div>
<h3>Steps </h3>Profile Picture<br />&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;<br />1. Go to Account Setitngs -&gt; Profile -&gt; Profile Picture -&gt; Edit<br />2. Click &quot;Select&quot;<br />3. Upload a picture that is not square (wider than tall, or taller than wide), can use:<br />https://www.mattermost.org/wp-content/uploads/2016/03/logoHorizontal.png<br />4. Verify before saving that orientation appears correct<br />5. Save<h3>Expected</h3>Profile picture updates.<br />Picture is cropped to show the center of the image, and image is not stretched.<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/account_settings``
**Test code arrangement:**
```
describe('Account Settings', () => {
    it('MM-T2076 Profile Picture: Non-square image is cropped and centered', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by ezhilkumaran** [comment]
Hi! I'd like to work on this.

**Comment by ezhilkumaran** [comment]
@saturninoabril @amyblais I'm not able to reproduce the issue. Has it been fixed already? Can someone confirm?

**Comment by saturninoabril** [comment]
Hello @ezhilkumaran, this issue or help-wanted ticket is for writing automated test with Cypress and not about any specific bug in product. I wonder what's you're trying to do.

**Comment by ezhilkumaran** [comment]
@saturninoabril  I'm so sorry. I mistook this to be a bug in the profile picture display. My bad!

**Comment by saturninoabril** [comment]
No worries @ezhilkumaran :)

**Comment by ZeeshanAmjad0495** [comment]
Hi @saturninoabril , I would like to write the e2e test for this issue.

**Comment by saturninoabril** [comment]
Sure and thanks @ZeeshanAmjad0495!

**Comment by adj2908** [comment]
Hi @saturninoabril ,

I would like to work on this if @ZeeshanAmjad0495 is not working on this.

Thanks.

**Comment by saturninoabril** [comment]
Thanks for your interest @adj2908!

**Comment by saturninoabril** [comment]
Closing now and will submit new set of help-wanted issues.
