### ISSUE TITLE
Add copy markdown cell button

### ISSUE THREAD

**Issue by RobinFrcd** [mattermost/mattermost-server#18848]
Hi,
The markdown formatting is really cool, but it would be even better if a `copy` button was available to copy the cell content to the clipboard.
Would it be possible to add like link ? Somewhere next to the `bash` title in the top right corner for example.

![image](https://user-images.githubusercontent.com/29704178/138928461-60f6cfdc-b70a-4f88-be5e-ae5c3d7915fb.png)

Thanks to the whole Mattermost's team for the awesome work !

**Comment by amyblais** [comment]
I'll close as a dup of https://github.com/mattermost/mattermost-server/issues/18851
