### ISSUE TITLE
It is not added to the reaction

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#18857]
Hello friends

Someone put a reaction on a post and I want to put the same reaction, 

but when I click on that reaction, **_it is not added to it_**!

@mgielda @jnugh @dmeza @alerque @it33

**Comment by esethna** [comment]
@furqanmlk thanks, can you help open a bug ticket and route to Ursa team triage?

**Comment by furqanmlk** [comment]
> @furqanmlk thanks, can you help open a bug ticket and route to Ursa team triage?

Done ✅ 
https://mattermost.atlassian.net/browse/MM-39749

**Comment by shieldsjared** [comment]
@esethna - Apologies on the delayed response. No, we've not enabled any of the experimental town-square features. Only thing unique about our town-square is that we renamed it.

Our issue is slightly different than what has been described by @furqanmlk.  Our issue isnt removing a reaction, but adding a reaction (by clicking on an already-existing reaction on the post).  The workaround is to add a reaction through the hover menu. Interestingly enough, it only impacts about 50% of our users. And the problem follows from browser to browser.

**Comment by shieldsjared** [comment]
Also, when a user clicks on an already-existing reaction on a post, No POST is being made to the `/reactions` endpoint, so this appears to be a client-side issue. Nothing seems to standout in the dev-tools console. I also enabled developer mode, and no errors appear there either. /shrug

**Comment by esethna** [comment]
Thanks for the info! Wonder if it has to do with the renaming of town square. @furqanmlk are you able to test based the above and file a ticket if needed? ^

**Comment by furqanmlk** [comment]
> Thanks for the info! Wonder if it has to do with the renaming of town square. @furqanmlk are you able to test based the above and file a ticket if needed? ^

Hi @esethna 
Yes I already filed the bug. 
I will add more details to the ticket as described by @shieldsjared

**Comment by esethna** [comment]
Thanks, closing this and the ticket
