### ISSUE TITLE
Deletes are not propagated when android/web-app is offline. [Reopen: #16339]

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#18863]
The closed issue #16339 is still or again an issue: Deletes are not propagated when android/web-app is offline.

Versions:
+ MM 6.0.1
+ Android app 1.47.2

Calling
https://xxx/api/v4/channels/CHANNEL_ID/posts?since=1635282122676&skipFetchThreads=false
returns the correct posts, including the deleted posts (without content).

But for some reason the android app doesn't seem to care and neither does the Web-App.

Therefore the deletes are no longer propagated.
+ Edits of deleted posts are not propagated either.
+ Edits are propagated correctly.

#### Steps to reproduce
see #16339

#### Expected behavior
see #16339

#### Observed behavior (that appears unintentional) 
see #16339

**Comment by amyblais** [comment]
I wasn't able to reproduce this on iOS. @josephbaylon Can you help test this on Android?

**Comment by someone-somenet-org** [comment]
https://user-images.githubusercontent.com/5354356/139875246-c721edf2-68e1-4ff8-abfd-6a232e7c2eff.mp4


After writing the messages, i switched to the laptop/chromium.
+ deleted Delme 1
+ edited Editme 1
+ Turned off data on the phone
+ deleted Delme 2
+ edited Edit Delme1
+ edited Editme 2
+ Turned off data on the phone, only not-deleted edit got propagated.

**Comment by someone-somenet-org** [comment]
> @amyblais Not sure if it's a bug but it looks like deletes don't propagate when app is offline on all platforms (webapp, desktop, android, iOS). Seems like a current limitation right now. Might need a PM to determine if this feature should be available.

Imho it is very important to show the same content to everyone who has internet right now. Deletes are propagated when the apps are online and consistency should not depend on whether somebody had flakey internet in the past.

As in: being on a train can totally change the topic of a discussion when deleted or worse: edited, and later delete posts keep showing up for some people in some previous version and can render moderation fully ineffective.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-39853.

**Comment by Moongaze05** [comment]
@someone-somenet-org @amyblais @josephbaylon 
Im currently experiencing this issue, and its true, still, deleted posts when mobile app is offline are never gonna be deleted in app, and yet editing works like charm
Could you please investigate this moment, or show in code where the editing (offline) part is, for me to understand it properly
