### ISSUE TITLE
Threads view shows deleted messages -and they never disappear

### ISSUE THREAD

**Issue by KlavsKlavsen** [mattermost/mattermost-server#18890]
#### Summary
Threads view shows deleted messages -and they never disappear

#### Steps to reproduce
write in a channel.. have someone else reply to it - so it shows up in Threads unreads
Then delete both the message on the thread and the thread starting message

#### Expected behavior
When message is deleted, it should be removed from Threads view too :)

#### Observed behavior (that appears unintentional) 
message keeps being showed in "Unread" in Threads view - and message below it shown as (deleted) - and if I say "open this in channel" - I get a "this message does not exist page" in mattermost desktop client.

#### Possible fixes
Seems "delete" - needs to take "Threads" into account and delete there too?

**Comment by amyblais** [comment]
@koox00 @anurag6713 Would you know if we have any known issues / an open ticket for this?

**Comment by amyblais** [comment]
cc @jgilliam17 Would you know if we have any known issues / an open ticket for this?

**Comment by jgilliam17** [comment]
@amyblais I created a ticket for follow up last week https://mattermost.atlassian.net/browse/MM-39750
