### ISSUE TITLE
Permission  view_members not working

### ISSUE THREAD

**Issue by cheluskin** [mattermost/mattermost-server#18904]
#### Summary
view_members not working

#### Steps to reproduce
Remove view_members from role system_user in database record and restart docker compose

#### Expected behavior
User must not see members

#### Observed behavior (that appears unintentional) 
User can see members

**Comment by amyblais** [comment]
@cheluskin 
1. What Mattermost server version are you on?
2. Do you see any errors in Mattermost logs?

**Comment by cheluskin** [comment]
I'm not sure what this is related to, it seems the functionality just doesn't work.

```
{"timestamp":"2021-11-01 21:22:14.851 +02:00","level":"error","msg":"Unable to get the team members.","caller":"web/context.go:105","path":"/api/v4/teams/k4j678y8i7be9kh7ubbxdxijwo/members","request_id":"d6po479t93ysp8uarh1cgmkywh","ip_addr":"192.168.128.4","user_id":"5nqrd3gbuib4iromije7wkgdfc","method":"GET","err_where":"GetTeamMembers","http_code":500,"err_details":"failed to find TeamMembers with teamId=k4j678y8i7be9kh7ubbxdxijwo: pq: column reference \"username\" is ambiguous"}
```

**Comment by amyblais** [comment]
@streamer45 @agnivade Would you have knowledge on this issue?

**Comment by streamer45** [comment]
Given that directly modifying roles from the database is not something I'd recommend, if there's an actual issue maybe someone more closely involved with the permissions system could be of help. @mkraft do you know who could have a look at this?

**Comment by cheluskin** [comment]
Thanks. The point is that I have not found a way to limit the visibility of the participants. Therefore, I tried to do it through this field in the database. I can see the value is being used in the code, but changing it doesn't seem to do what the name says

**Comment by mkraft** [comment]
@cheluskin I've created https://mattermost.atlassian.net/browse/MM-40543 to track this as a feature request.
