### ISSUE TITLE
Cannot view file from messages history

### ISSUE THREAD

**Issue by bodynar** [mattermost/mattermost-server#18901]
#### Summary
Not loaded image from "Recent files" crashing page

#### Steps to reproduce
1. Open "**Recent files**" tab
2. Select "**Image**" filter
3. Open image which is not presented in chat _(to see this image in chat you need to scroll up and load previous messages)_

#### Expected behavior
After selecting image in Recent files I expect to observe image in modal

#### Observed behavior (that appears unintentional) 
Page crashes to white empty screen with console errors

#### Possible fixes
Fix next file `FilePreviewModalInfo.tsx`
Some values are "undefined" and not checked before using (or not initialized properly)

![image](https://user-images.githubusercontent.com/22620134/139654120-e7f8ad19-4385-4326-9d61-257f5c8b7942.png)

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-39788
