### ISSUE TITLE
Error API Rest: POST Create User

### ISSUE THREAD

**Issue by sz2000** [mattermost/mattermost-server#18940]
#### Summary
Lately I have updated mattermost from version 5.32 to 6.0, from that moment it has stopped considering the string "username" valid for when I create a user using the API. Other GETs or POSTs that I usually use do not give problems.

#### Steps to reproduce
`curl -s --location --request POST "$urlMattermost/api/v4/users" --header 'Content-Type: application/json' --header "Authorization: Bearer $apitoken" --data-raw { "email": "pippo.pluto@domain.net", "username": "pippo.pluto", "first_name": "Pippo", "last_name": "Pluto", "password": "password", "locale": "it", "props": { }, "notify_props": { "email": true, "desktop_sound": true, "mention_keys": "string", "channel": true, "first_name": true }}`

#### Expected behavior
create user as defined in json

#### Observed behavior (that appears unintentional)
`{"id":"api.context.invalid_body_param.app_error","message":"user non valido o mancante nel corpo della richiesta.","detailed_error":"","request_id":"ds6k8846dpg1tba4ekseeksnie","status_code":400}  `

**Comment by amyblais** [comment]
@furqanmlk Would you or anyone from QA be able to help test if this reproduces?

**Comment by furqanmlk** [comment]
@amyblais 
I am able to reproduce this issue on `Master` branch and `Cloud`

![image](https://user-images.githubusercontent.com/6909890/140386538-e2519097-4639-4011-8f61-42fdbdefd037.png)

**Comment by agnivade** [comment]
Hey @sz2000 - This is failing because your "notify_props" map is not a purely string -> string map. This was like this in 5.32 as well, so there's no change.

**Comment by sz2000** [comment]
If I try to reduce everything to only the required parameters (username and email) the problem persists.
https://api.mattermost.com/#operation/CreateUser

**Comment by agnivade** [comment]
I am not able to reproduce that. @furqanmlk - could you check this with just username and email params and see if you see the same error again? Thanks.

**Comment by furqanmlk** [comment]
@agnivade @sz2000  I am not able to reproduce the error when using just ```username``` and ```email``` in 5.32 and Master

![image](https://user-images.githubusercontent.com/6909890/148984919-c87b25e2-f1c1-4012-ab61-d8338fa764ef.png)

![image](https://user-images.githubusercontent.com/6909890/148986735-8c5191b7-2ba4-43ee-bd09-2121ec791cc1.png)

I have found following results: (**None string property of "notify_props" is failing** only in 6.0 onwards )  
### Master Branch

![image](https://user-images.githubusercontent.com/6909890/148979552-8e8f166b-91b5-4ce7-b679-f5faf2950499.png)

![image](https://user-images.githubusercontent.com/6909890/148980814-d4955f4e-df83-427d-b3d4-02b126ebae45.png)

### Following version is passing in "None string and String Property"
### 5.32 
![image](https://user-images.githubusercontent.com/6909890/148979981-e1d00f83-d37e-4c76-afb9-9982432d6e53.png)

#### 5.39.3

![image](https://user-images.githubusercontent.com/6909890/148985769-407e7df0-e10e-4793-9be2-d3f0ce668ef3.png)
