### ISSUE TITLE
invalid config for logging, error creating log target _defFile: error decoding file target options: invalid character 'm' in string escape code

### ISSUE THREAD

**Issue by frapps** [mattermost/mattermost-server#18950]
#### Summary
When starting MM server I get the following error. "invalid config for logging, error creating log target _defFile: error decoding file target options: invalid character 'm' in string escape code" MM does not log an other errors after. 

#### Steps to reproduce
This is after installing version 6.0.2. Installed on Windows. 

#### Expected behavior
When starting MM server I get the following error. "invalid config for logging, error creating log target _defFile: error decoding file target options: invalid character 'm' in string escape code" MM does not log an other errors after. 

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
I've tried manually changing the FileLocation property in the LogSettings object, but this is ignored.

**Comment by amyblais** [comment]
@frapps Would you be open to posting about this either on our troubleshooting forum https://forum.mattermost.org/ or on our [community server's Peer-to-Peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? Our engineers or community members may be able to help with this.
