### ISSUE TITLE
Pass expiry time from outside in `*SqlTokenStore.Cleanup`

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18965]
#### Summary
The `Cleanup` method calculates the expiry time from inside the method.

https://github.com/mattermost/mattermost-server/blob/ba5f1f3f5c5ccb4fef269969a7771617665220ab/store/sqlstore/tokens_store.go#L77-L83

This does not give control to caller, and makes the method hard to test. Apparent from the fact that this store does not have any tests at all.

The objective of this ticket is to calculate and pass the expiry time from the upper layers, and also add a unit test.

Take a look at how jobs are cleaned for example:

https://github.com/mattermost/mattermost-server/blob/ba5f1f3f5c5ccb4fef269969a7771617665220ab/app/server.go#L1557-L1562

**Comment by agnivade** [comment]
cc @isacikgoz

**Comment by krotovkk** [comment]
Hello! I'd like to pick this up.

**Comment by agnivade** [comment]
Go for it!
