### ISSUE TITLE
Error getting column info for migration check,"caller":"sqlstore/upgrade.go:966","table":"SidebarCategories","column":"Id","error":"sql: no rows in result set"}

### ISSUE THREAD

**Issue by necipakca** [mattermost/mattermost-server#18975]
MatterMost version is : 5.39.1
Try to upgrade Versiyon is : 6.0.2 

We are getting this error because ;

In Turkish  we have a latter  I that
uppercase --> I
lowercase --> ı

GetColumnInfo func in upgrade.go you are using 

WHERE lower(table_name) = lower($1)
AND lower(column_name) = lower($2)

the problem is when you use lower() function in PostgreSQL the out put is

 lower('Id') output is :  ıd

so this cause "sql: no rows in result set".

Possible fix are
1-)  we can configure our database is to "en_EN.UTF-8" charset. This is workaround. Also it can break some functions storing and searching Turkish letters. So I do not prefer.
2-) You can change code to use no lower() function in PostgreSQL. Because already table and cloumn names are case-insensitive in PG.

**Comment by amyblais** [comment]
@necipakca 
1. What Mattermost server version are you on?
2. What Mattermost server version are you upgrading from?

**Comment by necipakca** [comment]
> @necipakca
> 
> 1. What Mattermost server version are you on?
> 2. What Mattermost server version are you upgrading from?

Sorry for that. I have update the issue @amyblais .

**Comment by amyblais** [comment]
cc @isacikgoz @streamer45 If you have thoughts on this.

**Comment by isacikgoz** [comment]
Thanks for the feedback @necipakca! I think we should handle the lower case issue in the application level. WDYT @streamer45?

**Comment by streamer45** [comment]
> Thanks for the feedback @necipakca! I think we should handle the lower case issue in the application level. WDYT @streamer45?

Agreed.

**Comment by isacikgoz** [comment]
Created the ticket here: https://mattermost.atlassian.net/browse/MM-40028 cc @amyblais @necipakca

**Comment by amyblais** [comment]
Closing this as a Help Wanted Issue was opened for this.
