### ISSUE TITLE
Mattermost Board - Team Not Found

### ISSUE THREAD

**Issue by tschlue** [mattermost/mattermost-server#18986]
#### Summary
If I create a Board or try to enter one I always geht the error site

>Team Not Found
>The team you're requesting is private or doesn't exist. Please contact your Administrator for an
> invitation.

#### Steps to reproduce
* Goto an channel
* Push the board button once
* Push the button '+Board hinzufügen' (+Add board?)
* Choose 'Leeres board' (Empty board)
-> Error screen

#### Expected behavior
The board should load without error

Maybe it have something to do that I tried to run focalboard on the same server.
Is there a way to reset mattermost? I just updated to Version 6.0.2 with the hope it fixes it.
I have the version 0.9.4 of the Mattermost Boards plugin installed.

**Comment by amyblais** [comment]
@tschlue Would you be open to re-opening this issue at https://github.com/mattermost/focalboard/issues?

**Comment by tschlue** [comment]
Sorry and thanks for open the issue in the other repo.
