### ISSUE TITLE
Guest accounts inactive after certain amount of time

### ISSUE THREAD

**Issue by ihqtzup** [mattermost/mattermost-server#18988]
#### System
Mattermost Enterprise E20 v.6.0.2

#### Summary
We have created guest users and just noticed after a week or so that they have been suddenly deactivated for no reason.

#### Steps to reproduce
Invite guest accounts. Wait a certain amount of time, maybe a week or two. See if guest accounts are inactive (users can not log in any longer).

#### Expected behaviour
Guest accounts are active.

#### Observed behaviour (that appears unintentional) 
Guest accounts are inactive.

#### Possible fixes
I do not know why guest accounts expire because there is no mention of that in the documentation.

**Comment by ihqtzup** [comment]
Mattermost Enterprise E20.

**Comment by amyblais** [comment]
@ihqtzup Do you see any errors in Mattermost logs when the issue occurs?

**Comment by amyblais** [comment]
@ihqtzup Is there any other information that you'd be able to help share? Another option would be to contact our Support team via https://support.mattermost.com/hc/en-us/requests/new to further troubleshoot this.

**Comment by ihqtzup** [comment]
I was not able to find anything odd from the logs. It is a bit difficult as we do not know the exact date when these guest accounts were inactivated. 

This happened three times. First, we thought it was because of server restart, but it also happened even without any modifications or restarts of the cluster. From now on, we have decided to not use guest accounts until this is resolved.

**Comment by amyblais** [comment]
@lindy65 Would this be something that QA would be able to help test?

**Comment by lindy65** [comment]
Sure @amyblais - I can set up some test guest accounts to try to reproduce this - obviously will have to wait a week (or 2?) to see if the users become deactivated but I'll report back here on results.

In the meantime, I'm not sure whether @ogi-m might have any idea why this could be happening. He QA'd the feature while it was in development so might have some insight.

**Comment by lindy65** [comment]
@ihqtzup - in order to more closely try to reproduce your issue, can you tell me what the guest accounts have access to - e.g. private or public channels, open team (Allow any user with an account on this server to join this team) or not?  Thanks!

**Comment by ogi-m** [comment]
Only one scenarios where this is expected comes to mind:
If the guest accounts feature is deactivated at any point, then so are the guest users. After enabling the feature again, all those guest users need to be reactivated manually again. 
@ihqtzup Was the guest accounts feature disabled (and re-enabled) at any point maybe?

**Comment by ihqtzup** [comment]
No, the feature was not deactivated at any point. The first time guest users were active about 2-4 weeks. (not sure exactly how long). Then it was something like 1-2 weeks.

Guest users had access to one team and public channels of that team.

Also, the channel says that there is still guest users, even though we do not have any guest users. See attachments.
![screenshot](https://user-images.githubusercontent.com/1743396/143408825-7292566c-0c6a-4ddf-b980-2d3230221c66.png)
![screenshot](https://user-images.githubusercontent.com/1743396/143408873-ceaf9bc1-b56a-48c8-b82f-36fef66d1cfb.png)

**Comment by ogi-m** [comment]
@ihqtzup Are the users shown as inactive the system console, or are they completely gone? Looking at the screenshot, it seems the guest users don't exist in the system at all anymore, is that correct?

**Comment by ihqtzup** [comment]
When guest users got inactivated, they were shown as "inactive" in the system console, so not completely gone. The screenshot is our current situation because we have now stopped using guest users until this is resolved. 

We "promoted" those guest users as members until this is resolved so we do not have any guest users at the moment (even though the channel header claims otherwise).

**Comment by lindy65** [comment]
Hi @amyblais - do you think it would be helpful to involve the dev team who own guest accounts to help troubleshoot?  I'm wondering whether other features like LDAP Groups or permissions might also be affecting the guest accounts?

@ihqtzup - can you share more information about your config (e.g. login method, whether you make use of LDAP groups and any specific permissions you have set up)?

I haven't yet seen any change to the guest accounts I set up on my test server (v6.2 rc1, Enterprise E20).  They are still active.

**Comment by ihqtzup** [comment]
We have normal user accounts. Most of them are members and of course few admins.

We do not use LDAP groups. Users log in with email and password. Users are forced to use MFA. It is a very basic configuration in that sense.

**Comment by lindy65** [comment]
@amyblais @ihqtzup FYI, the guest accounts I set up are still active (since 24 November)

**Comment by amyblais** [comment]
@ihqtzup Let me know if you'd be open to contacting our Support team via https://support.mattermost.com/hc/en-us/requests/new to further troubleshoot this.

**Comment by lindy65** [comment]
Following up that I am not able to reproduce your issue @ihqtzup - the guest accounts I created on 24 Nov are still active.

**Comment by ihqtzup** [comment]
Thanks for reporting. Let's wait until 1 month has passed.

**Comment by amyblais** [comment]
I'm cleaning up some older issues and we haven't been able to reproduce this internally. If this still reproduces on the latest version, I recommend reaching out to our Support team via https://support.mattermost.com/hc/en-us/requests/new to further troubleshoot this.

Another option is to post about this at https://forum.mattermost.com/ or via our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) for our community to take a look.

**Comment by ihqtzup** [comment]
It seems that guest accounts get disabled every time when the server restarts.

**Comment by ihqtzup** [comment]
@amyblais @lindy65

**Comment by amyblais** [comment]
@ihqtzup Me and Lindy haven't been able to reproduce this so far. What are your thoughts on contacting our Support team to help troubleshoot this further https://github.com/mattermost/mattermost-server/issues/18988#issuecomment-1069619462?

**Comment by ihqtzup** [comment]
Will do. Thanks.
