### ISSUE TITLE
Error pulling team-edition Master from github.com

### ISSUE THREAD

**Issue by karoolpl** [mattermost/mattermost-server#18993]
Hello,

I use microk8s/1.22-stable, today i found error when my k8s tried to download newver verison of master image. Error:

```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  29s               default-scheduler  Successfully assigned mattermost/mattermost-deployment-64774687b7-tqwnq to cj-ubuntu-srv01
  Normal   Pulled     8s (x3 over 28s)  kubelet            Container image "mattermost/mattermost-team-edition:master" already present on machine
  Warning  Failed     5s (x3 over 26s)  kubelet            Error: failed to create containerd container: error unpacking image: failed to extract layer sha256:7dfe6fa66dc3d74da06469cd8ce6ccf4619c79d3e7dbe5f1cb012ccddedf5237: gzip: invalid checksum: unknown
  ```
  
  When i changed image from master to relase-6.1 everything works fine, i got same error on 1.20-stable. I think thats some error with master image, plz check it out :)

**Comment by amyblais** [comment]
Would you be open to asking about this on [our community server here](https://community.mattermost.com/core/channels/developers)? Our devs will likely be able to help.

**Comment by amyblais** [comment]
@karoolpl Were you able to get help for this? If not, I can help ping a dev to take a look
