### ISSUE TITLE
The official docker images on dockerhub are completely undocumented

### ISSUE THREAD

**Issue by Trolldemorted** [mattermost/mattermost-server#19007]
The official docker images on dockerhub ([team](https://hub.docker.com/r/mattermost/mattermost-team-edition), [ee](https://hub.docker.com/r/mattermost/mattermost-enterprise-edition)) don't link to any documentation that'd tell us how to configure them.

Could you document:
- which environment variables can be used for configuration
- which volumes are required to ensure no data is lost when a container is removed
- which ports should be exposed
- where configuration files and TLS certs should be mapped

It'd reduce the inhibitions to trying out Mattermost significantly :)

**Comment by teutat3s** [comment]
You can check out this repo: https://github.com/mattermost/docker
I agree there could be a link to that repo on the docker hub page.

**Comment by amyblais** [comment]
Thank you for sharing. I've created an internal ticket to consider adding a link to the docs,
