### ISSUE TITLE
Log files are not rotated

### ISSUE THREAD

**Issue by adsche** [mattermost/mattermost-server#19017]
#### Summary
Log files are not rotated as they grow beyond 10k lines. 

#### Steps to reproduce
Enable file logging and wait until the log file grows beyond 10k lines.

#### Expected behavior
The setting documentation (**edit:** in the admin console) for file logging states:
> Typically set to true in production. When true, logged events are written to the mattermost.log file in the directory specified in the File Log Directory field. **The logs are rotated at 10,000 lines and archived to a file in the same directory, and given a name with a datestamp and serial number.** For example, mattermost.2017-03-31.001. Changing this setting requires a server restart before taking effect.

Therefore, I expect multiple log files with <= 10k lines in the log file directory.

#### Observed behavior (that appears unintentional) 
```
wc -l *
   112029 mattermost.log
   258369 notifications.log
   370398 total
```

Neither log file has been rotated.

**Comment by adsche** [comment]
Side note: I, personally, would be totally happy to use `logrotate` for rotation, if you would implement or document a safe way to rotate the log files externally (e.g. sending a signal).

**Comment by amyblais** [comment]
@wiggin77 @furqanmlk Are we able to test / reproduce this? The reporter is on server v6.0.2.

**Comment by adsche** [comment]
Maybe this is a doc bug or fixed in a newer version (true, I'm on 6.0.2): In the [online documentation](https://docs.mattermost.com/configure/configuration-settings.html#output-logs-to-console) (weirdly, in the section about console logging!) a rotation threshold of 100MB is mentioned. 

But that limit has been in there also for the [6.0.0 docs](https://github.com/mattermost/docs/blob/5b648593fab097b30f11e32ca70fe63289454c4b/source/configure/configuration-settings.rst).

In any case, it is inconsistent with what the admin console displays. I will edit above to clarify that this is from admin console.

**Comment by wiggin77** [comment]
@amyblais, @adsche.  Thanks for reporting this.  Reviewing the code I can see this was unintentionally changed for V6.  The rotation size is supposed to be specified in megabytes but I think the default was mistakenly changed thinking it was KB.  It's currently set to 10,000 meaning 10GB.  

1. I will create a PR with a simple fix today. This will revert the default to 100MB.
2. A work-around is to modify the config to use advanced logging instead as described here https://docs.mattermost.com/configure/configuration-settings.html#advanced-logging

**Comment by adsche** [comment]
Sounds good, but just to make sure: Note that the values I gave were **lines**, not KB or MB, so I can't confirm if that is actually the bug.

I additionally see two documentation bugs (at least for the self-hosted version), still present in 6.1.0 (I updated meanwhile).
1) In the system console, the description for the setting still says "10,000 lines" in v6.1.0
2) In the docs, the 100MB limit is listed under console logging which does not make sense. There is no limit listed under file logging.

**Comment by wiggin77** [comment]
@cwarnermm, as reported above, the documentation for when file logs get rotated should be moved from the console logging section to file logging section.  https://docs.mattermost.com/configure/configuration-settings.html#output-logs-to-console

**Comment by wiggin77** [comment]
> 1. In the system console, the description for the setting still says "10,000 lines" in v6.1.0

Thanks.  I am creating a separate ticket for this.

**Comment by cwarnermm** [comment]
Thanks, @wiggin77 and @adsche for raising this documentation issue. This issue is being corrected via https://github.com/mattermost/docs/pull/5273
