### ISSUE TITLE
Mattermost server and mmctl not same version

### ISSUE THREAD

**Issue by ukahlert** [mattermost/mattermost-server#19023]
The binaries for mattermost server 6.1.0 (starter) come with mmctl version 6.0.0 .
So mmctl refuses to operate on the 6.1.0 server.

Recompiling the sources for mmctl 6.1.0 results in mmctl with version 6.0.0. So maybe the wrong version is "somewhere" hidden in the source files?

**Comment by amyblais** [comment]
@cpanato @puerco Would you be able to help take a look at this?

**Comment by cpanato** [comment]
will work on that this week, but looks like the mmctl that is included is from a previous version

**Comment by amyblais** [comment]
Fixes have been merged in the mmctl repo and we've added a process for the monthly releases to check that mmctl version is updated. If there is a v6.1.1 planned, the fix for this will be included.

**Comment by ukahlert** [comment]
Thanks
