### ISSUE TITLE
Nagging tip of the day cannot be disabled

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/mattermost-server#19021]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Since the latest update, every morning after resuming my computer the MM client "greets" me with a tip of the day message that cannot be disabled.
No checkbox or similar ion the message nor anything in settings. 

**Environment**
- Operating System: Linux, Debian/unstable
- Mattermost Desktop App version: 4.7.2
- Mattermost Server version: 6.0.2

**Steps to reproduce**

**Expected behavior**
TotD has a checkbox to disable it permamently or at the very least a setting somewhere

**Observed behavior**
No way to get rid of that thing for good.

**Possible fixes**

**Comment by amyblais** [comment]
I'm not sure if there is a way to disable it permanently. @esethna

**Comment by esethna** [comment]
@2019-05-10 that screen should only appear once. After you've seen it you shouldn't be seeing it again. Can you confirm?

As an Admin you can disable In-product Notices in the system console: https://docs.mattermost.com/configure/configuration-settings.html#enable-admin-notices

cc// @amyblais

**Comment by 2019-05-10** [comment]
> @2019-05-10 Do you see the same issue with Mattermost Desktop App version v5.0.2?
> @2019-05-10 that screen should only appear once. After you've seen it you shouldn't be seeing it again. Can you confirm?

After upgrade to 5.0.2 the prompt is gone.
Once again: MM needs a working update mechanism, ideally a deb/rpm repository, or at the very least a notification when a new relase is available.

**Comment by amyblais** [comment]
We are working on an auto-updater feature for desktop app for a future release,
