### ISSUE TITLE
Can't create new boards

### ISSUE THREAD

**Issue by alevashov** [mattermost/mattermost-server#19036]
#### Summary
No way to create a new board in the interface.
Mattermost version 6.1.0
Tried both in the last updated Windows client and web interface - the result is the same

#### Steps to reproduce
First time tried to create new boards
Created 3 of them
Understood that don't need that many
Tried to delete some, probably deleted all
Now don't see a possibility to create new boards at all. There is just no UX element for that

Screenshot link - https://1drv.ms/u/s!AoGcPMshePGepC7iW9WiV1Fr0VPb?e=SeLVka

#### Expected behavior
Be able to create new board (+ icon in bottom left corner in documentation)

#### Observed behavior (that appears unintentional) 
No way to create new board
#### Possible fixes
Fix UX

**Comment by amyblais** [comment]
@alevashov Would you be open to creating this issue at https://github.com/mattermost/focalboard/issues?

**Comment by alevashov** [comment]
Done, https://github.com/mattermost/focalboard/issues/1860
