### ISSUE TITLE
mmctl errors, version mis-match, fails to find local socket

### ISSUE THREAD

**Issue by djbusby** [mattermost/mattermost-server#19047]
We are using Mattermost 6.1.0; recently installed; upgraded from 5.37

We run the mmctl tool to remove a team.
The first issue, is that this was a newly extracted package and we get this warning:
```
WARNING: server version 6.1.0.6.1.0.6341e8e78e09a04b921cabdb4c210a03.false doesn't match mmctl version 6.0.0
```

The second issue is that MMCTL cannot find it's local file:
```
./mattermost/bin/mmctl team delete TEAM_NAME --local
Error: socket file "/var/tmp/mattermost_local.socket" doesn't exists, please check the server configuration for local mode
```

Our server is configured for local mode:
```
grep Local mattermost/config/config.json 
"EnableLocalMode": true,
"LocalModeSocketLocation": "/var/tmp/mattermost_local.socket",
```

And the file exists, and is owned by the user that has started mattermost server and is running mmcli
```
stat /var/tmp/mattermost_local.socket
  File: /var/tmp/mattermost_local.socket
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 800h/2048d	Inode: 13          Links: 1
Access: (0600/srw-------)  Uid: (  420/ openthc)   Gid: (  420/ openthc)
Access: 2021-11-24 23:00:45.011295506 +0000
Modify: 2021-11-24 23:00:45.011295506 +0000
Change: 2021-11-24 23:00:45.011295506 +0000
 Birth: 2021-11-24 23:00:45.011295506 +0000
```

**Comment by amyblais** [comment]
The first issue looks the same as https://github.com/mattermost/mattermost-server/issues/19023.
cc @mgdelacroix if you have thoughts on the second issue.

**Comment by amyblais** [comment]
Fixes have been merged in the mmctl repo and we've added a process for the monthly releases to check that mmctl version is updated. Please re-open this if the issue persists on a more recent version,
