### ISSUE TITLE
mmctl import upload fails with "Error: failed to create upload session: : Unable to upload file. File is too large."

### ISSUE THREAD

**Issue by geverl** [mattermost/mattermost-server#19042]
Mattermost Version: 6.0.2
Database Schema Version: 6.0.2
Database: mysql

After completing steps 1-3 of https://docs.mattermost.com/onboard/migrating-to-mattermost.html#migrating-from-slack-using-the-mattermost-mmetl-tool-and-bulk-import, mmctl fails to import a Slack export with the message "Error: failed to create upload session: : Unable to upload file. File is too large."
The zip file to be imported is 5.3 GB in size.
Given that this is not a browser upload, why should there be upload size restrictions?

**Comment by amyblais** [comment]
@geverl Do you see any other errors in Mattermost logs?

**Comment by geverl** [comment]
No

**Comment by amyblais** [comment]
cc @mgdelacroix @streamer45 If you have thoughts on this issue.

**Comment by streamer45** [comment]
@geverl As you have probably noticed the config setting `FileSettings.MaxFileSize` still applies. You could temporarily bump it to allow for the import upload to succeed.

**Comment by geverl** [comment]
Thank you, that helped to get the mmctl import upload succeed. But now the mmctl import process job fails.

bin/mmctl import process rxrtabsmo3ncpy3y1pa4pk6ape_mattermost-bulk-import.zip
Import process job successfully created, ID: mm8hpqirmbb7m89rbg5y8qs66e

bin/mmctl import job list
ID: mm8hpqirmbb7m89rbg5y8qs66e
Status: error
Created: 2021-11-24 17:47:02 +0000 UTC
Started: 2021-11-24 17:47:10 +0000 UTC

**Comment by hrdwdmrbl** [comment]
Just a note to anyone still struggling with this:

**It is the size of your backup / migration / import file that matters. `mattermost-bulk-import.zip`**

It is NOT the size of the largest attachment.
