### ISSUE TITLE
Unable to make changes via Channel Configuration. Endless "Saving Config" state.

### ISSUE THREAD

**Issue by DummyThatMatters** [mattermost/mattermost-server#19051]
#### Summary
Unable to make changes via Channel Configuration window in `System Console` -> `User Management` -> `Channels`: Infinite "Saving Config" state on saving changes with no result.

#### Steps to reproduce
Using Mattermost server 6.1.0 Team Edition (postgres (PostgreSQL) 12.1 as a DB) go to the `System Console` -> `User Management` -> `Channels` menu, pick random channel, try change some user Role from Member to Channel Admin or try to make channel private. Press `Save` button. 

#### Expected behavior
I can change user role and channel privacy settings via `Channel Configuration` menu and save those changes.

#### Observed behavior (that appears unintentional) 
No real changes observed after doing manipulations in Channel Configuration modal. Having Saving Config endlessly with no changes after refreshing page.
![изображение](https://user-images.githubusercontent.com/51426114/143426422-cec7b5c5-3fa9-4a69-820c-46ad3248e6d3.png)
![изображение](https://user-images.githubusercontent.com/51426114/143427688-0bc75341-3f67-4c88-bc73-2dcc83f786ec.png)
Network requests:
![изображение](https://user-images.githubusercontent.com/51426114/143426998-bb8aaa85-327f-4d2c-ad91-bd8396ad083e.png)

**Comment by amyblais** [comment]
I wasn't able to reproduce this at mysql.test, do we have a Team Edition server to test this at? @lindy65 @saturninoabril

**Comment by DummyThatMatters** [comment]
@amyblais What is mysql.test? Forgot to mention (if it is important)  - we use postgres (PostgreSQL) 12.1 as a db on a separate pod,

**Comment by amyblais** [comment]
My apologies and no worries, my note was for our QA team, I've pinged them above to help with testing this.

**Comment by lindy65** [comment]
Hi @amyblais @DummyThatMatters 

I tested on our Team Edition server (team.test.mattermost.com) which is on v6.1 rc2 and I can easily reproduce your issue with the steps you provided.

I'm seeing these errors in the js.console

![image](https://user-images.githubusercontent.com/13020833/143474421-43f415c2-62e8-409c-8de1-ad7951e2aade.png)

![image](https://user-images.githubusercontent.com/13020833/143474494-8ba077b3-2535-4617-a0b7-2296c490410e.png)

Will you create a Jira ticket Amy or should I?

**Comment by amyblais** [comment]
Yep, I'll create a ticket today and I'll link it here.

**Comment by amyblais** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-40360

**Comment by DummyThatMatters** [comment]
So this functionality should not be supported in Team Edition at all? Or just a bug?

**Comment by amyblais** [comment]
I'm not sure yet, but our dev team will triage / look at it.

**Comment by drudgede** [comment]
Is there any update to this? I suffer from the same problem and unfortunately, I have a private channel where everyone is a member only and I cannot make any user a designated channel administrator. Hence, due to the rights in the system schema, no one in the channel is able to manage its members. I could mitigate this by allowing everyone to manage the channel members but this is not wanted in this case.

**Comment by amyblais** [comment]
There is a PR submitted to fix this: https://github.com/mattermost/mattermost-webapp/pull/9538.

**Comment by tjfayaz120** [comment]
same problem here on team edition 6.3.0, any updates?

**Comment by amyblais** [comment]
@mkraft Let me know if there is a status update on this. Multiple users have reported this issue.

**Comment by c0deright** [comment]
Same issue here

**Comment by amyblais** [comment]
I've reached out to our dev team to prioritize this.

**Comment by majidys** [comment]
> I've reached out to our dev team to prioritize this.

Hello
Thanks for following up
Is there no time to fix the problem?
We need it a lot
