### ISSUE TITLE
I want to know how to configure 401 authentication for mattermost

### ISSUE THREAD

**Issue by Ak74-577** [mattermost/mattermost-server#19091]
I access mattermost through nginx reverse proxy, I want to know how to configure 401 authentication for access, how should I configure it, thank you

**Comment by amyblais** [comment]
@ak74-911 Would you be open to asking about this at our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)?

**Comment by amyblais** [comment]
I'll close this for now, but please post in our Peer-to-Peer Help channel for best assistance!
