### ISSUE TITLE
Error When Deleted Custom Emoji Reaction Kept in Recently Used Emoji

### ISSUE THREAD

**Issue by jackytsa** [mattermost/mattermost-server#19095]
#### Summary
Deleted custom emoji kept in recently used emoji in emoji picker will break mattermost into blank page once page loaded.
Once the deleted emoji was added back, the issue will gone, and,
once the deleted emoji no longer within the recently used list, the issue will gone.

#### Steps to reproduce
Mattermost Server: 6.1
Mattermost Mac Client: 5.0.2
1. Added a custom emoji
2. Use that custom emoji as a reaction to a message
3. Remove the custom emoji
4. Reload mattermost
5. The Mattermost gone blank after loaded

#### Expected behavior
Deleted Emoji will be removed from recently used reaction list in emoji picker without error.

#### Observed behavior (that appears unintentional) 
The Mattermost gone blank after loaded with the following error logs
![Screenshot 2021-11-29 at 11 13 43 AM](https://user-images.githubusercontent.com/95198487/143803088-b8511969-bb0d-4950-96cf-2eea2ca00267.png)

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-40381
