### ISSUE TITLE
Crashes when `Quick reactions on messages` feature is enabled

### ISSUE THREAD

**Issue by matthbad** [mattermost/mattermost-server#19101]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When `Quick reactions on messages` is enabled, Mattermost crashes few seconds after starting.

**Environment**
- Operating System: Ubuntu 20.04
- Mattermost Desktop App version: 5.0.2
- Mattermost Server version: 6.1.0

**Steps to reproduce**
- Enable `Quick reactions on messages`  
- Create a custom emoji.
- Use it
- Delete the previously created custom emoji
- The application should crash

**Expected behavior**

**Observed behavior**

`TypeError: Cannot use 'in' operator to search for 'short_name' in undefined : react-dom.production.min.js:209`

```js
                y(this, "emojiName", ((e,t)=>{
                    return (n = ("short_name"in e ? e.short_name : e.name).replace(/_/g, " "))[0].toLocaleUpperCase(t) + n.slice(1);
                    var n
                }
```

The bug is here. e is undefined.
Does work in the web version, no exception raised.

**Possible fixes**

I deleted a lot of things that were cached in `~/.config/Mattermost`.

**Comment by amyblais** [comment]
May be related to https://github.com/mattermost/mattermost-server/issues/19095.
