### ISSUE TITLE
Create helper function to handle columns on reserved names

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#19105]
#### Summary
Due to the way Postgres and MySQL handles column names, for reserved names, we have to capitalize the first letter in MySQL's case.

See below:
https://github.com/mattermost/mattermost-server/blob/f0756901950ad9793913c938b14df9ad3df7ece0/store/sqlstore/command_store.go#L69-L73

#### Task
The objective of this ticket is to refactor this functionality into a common function so that it can be reused in future. A similar case is also there in compliance_store.go. We would want to call the common function from both of these places.

cc @isacikgoz

**Comment by olaysco** [comment]
Hi @agnivade, can this be assigned to me? I would love to work on this.

**Comment by agnivade** [comment]
Go for it!
