### ISSUE TITLE
There should be a page number on the Server Log page (Improvement)

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19118]
why it required.
==============
1) as per The Current Functionality of the Server log page there is No pagination, if The user see the old logs and he want to Find the same page Again then hes not able to Find that page and Time to time the logs added in the page so it will more difficult to find the same page because when new logs added then its possible that the Page Number will change so if there is a Pagination then User directly redirect on that page and save some times. 

It should be something like this.

![Pagination (1)](https://user-images.githubusercontent.com/89907719/144404749-1a29e279-b588-421e-8b9c-aa81abb1557d.jpg)

**Comment by dipak-demansol** [comment]
Related point #19117

**Comment by amyblais** [comment]
Would you be open to submitting this as a feature request on our uservoice forum here https://mattermost.uservoice.com/forums/306457-general?

**Comment by dipak-demansol** [comment]
> Would you be open to submitting this as a feature request on our uservoice forum here https://mattermost.uservoice.com/forums/306457-general?

Done
