### ISSUE TITLE
Log page Buttons are not visible Properly (UI)

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19117]
#### Summary
:- Log page Buttons are not visible Properly (UI Issue)

#### Steps to reproduce
 1) Go in the admin_console page.
 2) search the Log and open The "Server Logs".
 3) you will find that buttons are not visible Properly in the page. (when you click on the next button then both buttons will visible)

#### Expected behavior
  :- Both Buttons Should be Visible Properly.
  :- Buttons name should be something as per that user can identify where he will find the old or New logs, **may be Next button name should be "Old" or "Old Logs", and Previous button name should be "New" or "New Logs"**

#### Observed behavior (that appears unintentional) 
  :- Buttons not visible Properly in the Server Logs page.
  OS :- ubantu 20
  browser :- Chrome, Fire Fox.

![LogScreen Button UI issue](https://user-images.githubusercontent.com/89907719/144400444-84e8df67-64f2-4d83-9a69-d4ef54b2ca58.jpg)

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-40454.
