### ISSUE TITLE
regression: props no longer fully copied/retained when editing posts.

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#19127]
#### Summary
When editing posts **``props``** are not fully retained.

We have a bot that basically creates spoiler posts, not showing spoiler content before clicking a button. On button click it will send the user a ephemeral message containing the spoiler text.

When the poster edits the post, the button stops working.

**This worked before. Current server version: MM 6.1.0**

#### Steps to reproduce
1) Create post with prop metadata. (with an integration for example)
2) Edit post in Webapp manually.
3) Try to access metadata. (with an integration for example)

#### Expected behavior
The ``props`` being fully retained.

#### Observed behavior (that appears unintentional) 
Looking into the DB:

Original post's prop field:
```
{
  "attachments": [
    {
      "id": 0,
      "ts": null,
      "text": "This post contains spoilers.",
      "color": "",
      "title": "",
      "fields": null,
      "footer": "",
      "actions": [
        {
          "id": "pxi7d6gi67gdxqwys33zc5x9ca",
          "name": ":ghost: show me the spoilers :ghost:",
          "integration": {
            "url": "http://localhost:18065/hkggr5x857d3pmzr8wt194guqh/spoiler/interactive",
            "context": {
              "action": "show_spoiler",
              "spoiler_text": "asdf"
            }
          }
        }
      ],
      "pretext": "",
      "fallback": "",
      "image_url": "",
      "thumb_url": "",
      "title_link": "",
      "author_icon": "",
      "author_link": "",
      "author_name": "",
      "footer_icon": ""
    }
  ],
  "from_webhook": "true"
}
```

edited post's prop field:
```
{
  "attachments": [
    {
      "id": 0,
      "ts": null,
      "text": "This post contains spoilers.",
      "color": "",
      "title": "",
      "fields": null,
      "footer": "",
      "actions": [
        {
          "id": "pxi7d6gi67gdxqwys33zc5x9ca",
          "name": ":ghost: show me the spoilers :ghost:"
        }
      ],
      "pretext": "",
      "fallback": "",
      "image_url": "",
      "thumb_url": "",
      "title_link": "",
      "author_icon": "",
      "author_link": "",
      "author_name": "",
      "footer_icon": ""
    }
  ],
  "from_webhook": "true"
}
```

The integration part is missing!

**Comment by agnivade** [comment]
Thanks @someone-somenet-org. Would you know which version it worked previously? That would help us track down the regression.

**Comment by someone-somenet-org** [comment]
> Thanks @someone-somenet-org. Would you know which version it worked previously? That would help us track down the regression.

It works on MM ``6.0.3`` 

https://user-images.githubusercontent.com/5354356/144906734-34bd19b7-2140-46d1-9363-e3962eacd8fe.mp4

and stops working on ``6.1.0``

https://user-images.githubusercontent.com/5354356/144907208-84e80d79-f00c-45f8-b6e4-ec9d5a7d16bf.mp4

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-40509

**Comment by hanzei** [comment]
@someone-somenet-org Do you see any related error messages in the sever logs? Something along the lines of `Action integration error.`?

**Comment by someone-somenet-org** [comment]
> @someone-somenet-org Do you see any related error messages in the sever logs? Something along the lines of `Action integration error.`?

Nope.

All errors we have (from the last 24 hours) are a few (imho unrelated) `Failed to upgrade websocket connection.` errors. No warnings. Some Infos about completed Jobs and (not) sent Notifications. Obviously i reproduced my report before looking in the logs.
