### ISSUE TITLE
SMTP Connection unsuccessful: Sender Rejected - MAILFROM must be a valid domain (Empty Variable?)

### ISSUE THREAD

**Issue by sm4rtk1dz** [mattermost/mattermost-server#19125]
Hi! And thank you for this review,

I'm trying to configure the SMTP server on Mattermost v6.1, I upload the credentials and the smpt domain as usual and the following error is displayed:

````
Connection unsuccessful: Connection unsuccessful: failed to close connection to the SMTP server: 550 <> Sender Rejected - MAILFROM must be a valid domain. Ensure the mailfrom domain: "" has a valid MX or A record.
````

I know the credentials are good, I was using the same credentials in another Mattermost installation (Mattermost v.5.31) and it worked seamlessly.  

I already tried every possible combination of configurations, using TLS, no authentication and STARTTLS, the mail account does work perfectly fine. the domain for the mail account is already present in ``/etc/localdomains``, it's not a gmail account, i'm linking a godaddy account, so apparently it's not the smtp server's fault (i know it because it works on the other mattermost install with the same email address).

So looking at the error shown, i see that is says ``mailfrom domain: ""`` with empty quotes, so maybe the Mattermost server is not filling some variable or something like that.

Does anybody know whats going on? Thank you very much!

**Comment by amyblais** [comment]
@sm4rtk1dz 
1. Can you help share more about your SMTP settings? (https://docs.mattermost.com/configure/smtp-email.html)
2. Would you be open to checking if this troubleshooting thread might help https://forum.mattermost.org/t/smtp-not-working/8119?

**Comment by sm4rtk1dz** [comment]
It worked! The troubleshooting page had the solution. Thank you very much!

**Comment by Karinadr** [comment]
Hello good Morning. I have the same error that sm4rtk1dz, I hope you can help me please

**Comment by sm4rtk1dz** [comment]
Have you already checked the links?
https://docs.mattermost.com/configure/smtp-email.html  
https://forum.mattermost.org/t/smtp-not-working/8119
