### ISSUE TITLE
"Failed to reset read timeout from datasource"

### ISSUE THREAD

**Issue by skitsanos** [mattermost/mattermost-server#19140]
Hi,

Can't start the server with MySQL config, always getting `Failed to reset read timeout from datasource`. Followed instructions from https://docs.mattermost.com/install/install-rhel-8.html?src=dl

Any idea what can be an issue here?

**Comment by agnivade** [comment]
Can you show us the full error message? It contains the error and the original datasource. Feel free to redact any sensitive info.

**Comment by skitsanos** [comment]
Found it, it wass a misstype... my appologies. Can confirm it works smoothly with Postgre and MySQL both. No issues.
```
