### ISSUE TITLE
There is the private channel in the channel list, but I cannot open the private channel .

### ISSUE THREAD

**Issue by wuyinhrong** [mattermost/mattermost-server#19176]
#### Summary
There is the private channel in the channel list, but I cannot open the private channel .
MM Server：5.33.3
Client：4.6.2

#### Steps to reproduce
There is the private channel in the channel list, but I cannot open the private channel .I also make sure that the user has joined the private channel.

**Comment by wuyinhrong** [comment]
Supplement ：
The user who created the channel at the time suddenly couldn't click to enter the channel.

**Comment by amyblais** [comment]
@wuyinhrong Are you able to reproduce this on a more recent version? We support versions 5.37+.

**Comment by wuyinhrong** [comment]
Thank you very much for your reply!
 I will try to update the console to this version.
