### ISSUE TITLE
2nd time the "Leave Channel" button is not working but the same Functionality is working from the Channel header section, pls see the video

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19190]
#### Summary
2nd time the "Leave Channel" button is not working 

#### Steps to reproduce
1) from the side panel click on the 3 dot menu of the private channle
2) click on the leave channel button and user will see the popup for the confirmation, Click on the cancel button.
3) again do the same thing as click on the leave channel button.
**issue** :- the leave channel button will not work.

#### Expected behavior
Every time when user click on the leave channel button then it should work.

#### Observed behavior (that appears unintentional) 
2nd time when i hit the leave channel button then it's not working

https://user-images.githubusercontent.com/89907719/146248934-05bba2c1-4c76-469c-82af-fa6a186374b4.mp4

**Comment by amyblais** [comment]
Thank you, opened a ticket here: https://mattermost.atlassian.net/browse/MM-40681

**Comment by amyblais** [comment]
Closing as a Help Wanted Issue was opened for this,
