### ISSUE TITLE
How can a bot send an image to a channel?

### ISSUE THREAD

**Issue by fengwang** [mattermost/mattermost-server#19206]
With telegram, the corresponding command is something like `/usr/bin/curl -s -X POST https://api.telegram.org/{private_key}/sendPhoto -F chat_id={private_id} -F photo="@{photo_path}"` 
But I cannot find a similar one for mattermost, the one I tried but failed:
`curl -i -X POST -H 'Content-Type: application/json' -d '{"channel_id":"xxxxxxxxxxxxxxxxxx", "message":"This is a message from a bot", "props":{"attachments": [{"pretext": "Look some text", "image": "data:image/jpg;base64,xxxxxxxxxxxxxxxxxxxxxxxxx"}]}}' -H 'Authorization: Bearer xxxxxxxxxxxxxx' http://mattermost.local:8065/api/v4/posts`

**Comment by amyblais** [comment]
@fengwang Would one of these documents help?
 - https://developers.mattermost.com/integrate/admin-guide/admin-message-attachments/
 - https://docs.mattermost.com/developer/webhooks-incoming.html

**Comment by fengwang** [comment]
@amyblais 
Thanks for looking at this issue.

I walked through these two links before filing this issue.

I intended to do some automation job with a python application. This application will generate some messages/pictures/videos in the real-time, and I would like to push these files to a channel.
With the first link, I will have to upload the pictures/videos to a new place, and send the URL to the channel using a JSON file. This requires me to set up a server to hold these pictures/videos.
The second link gives somehow the same information as the first one.

Given the fact that a normal user can upload files as attachments in a channel, I guess there could also be a way for a bot to do so. But I cannot find it in the documents.

Meanwhile, the [Python Driver](https://github.com/Vaelor/python-mattermost-driver/blob/master/src/mattermostdriver/endpoints/files.py#L7) gives a `upload_file` interface, but it is unclear to me how to use it.

**Comment by amyblais** [comment]
Based on this FAQ, we currently don’t support the ability to attach files to a post made by an integration: https://docs.mattermost.com/developer/integration-faq.html#what-are-attachments. Would you be open to creating a feature request via uservoice https://mattermost.uservoice.com/forums/306457-general?

**Comment by fengwang** [comment]
@amyblais 

Thanks for the suggestion.

But as I limit my files to videos and pictures, I found a solution from [StackOverflow](https://github.com/Vaelor/python-mattermost-driver/issues/45) using the Python interface. 

This fulfills my requirements, and I will close this issue.

I list the code in case someone runs into the same problem :

```python
token = '*****************************'
channel_name = 'messages'
team = 'workspace'
filename = 'e2.jpg'
file_path = './e2.jpg' # works with image
file_path = './sm.webm' # works with video

from mattermostdriver import Driver
import json
mm = Driver({ 'url': '******************', "token": token, 'scheme': 'http', 'port': 8065 })
mm.login()
print( f'login successful' )

channel=mm.channels.get_channel_by_name_and_team_name(team, channel_name)
channel_id=channel['id']
print( f'got {channel_id=}' )

form_data = { "channel_id": ('', channel_id), "client_ids": ('', "id_for_the_file"), "files": (file_path, open(file_path, 'rb')) }

pp = mm.files.upload_file(channel_id, form_data)
file_id = pp['file_infos'][0]['id']
print( f'got {file_id=}' )

mm.posts.create_post(options={ 'channel_id': channel_id, 'message': 'This is a test through the API, trying to upload a file', 'file_ids':[file_id] })
print( f'post successful' )

```
