### ISSUE TITLE
Category name should not be only space

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19215]
#### Summary
issue :- 1) User is able to save category name as only space.
            2) if user add 5 space and then add channel name and save then in the web the save will be trim and category name will look good but in the android mobile app the the space is not trim and user can see the space there, pls see the Screenshot.
Mattermost Version: cloud-2021-12-08-1
Database Schema Version: 6.3.0
#### Steps to reproduce
pls see the video
https://user-images.githubusercontent.com/89907719/146825594-1db50a16-63ff-487b-be3c-73eeaf4335be.mp4

![1640030132061](https://user-images.githubusercontent.com/89907719/146825930-6346ad59-19e7-42df-8386-cc48b5600f46.JPEG)

#### Expected behavior
it should give you the validation message.

#### Observed behavior (that appears unintentional) 
by adding only space the user is able to save the category.

#### Possible fixes
1) you can give the validation message if user only add space or
2) block the user to add the first character as space. ( do not allow user to add space as first character)

**Comment by amyblais** [comment]
Thanks, opened: https://mattermost.atlassian.net/browse/MM-40736.
