### ISSUE TITLE
Database schema version 6.1.0 is not supported [Gitlab-ce]

### ISSUE THREAD

**Issue by khurshid-alam** [mattermost/mattermost-server#19248]
#### Summary
After upgrading gitlab to 14.6 which upgrades mattermost to 6.1 from 5.39.2, when it completes database upgrade it throws error

#### Steps to reproduce
Upgrade gitlab-ce to 14.6.

It hangs during updating database and takes long time (we can see that from log)

Then it throws this error

```
{"level":"error","ts":1640289636.4285412,"caller":"sqlstore/store.go:257","msg":"Failed to upgrade database.","error":"Database schema version 6.1.0 is not supported. This Mattermost server supports only >=5.39.3, <6.0.0. Please upgrade to at least version 6.0.0 before continuing.","errorVerbose":"Database schema version 6.1.0 is not supported. This Mattermost server supports only >=5.39.3, <6.0.0. Please upgrade to at least version 6.0.0 before continuing
```

except it is upgrading to 6.1 instead of 6.0

/opt/gitlab/embedded/service/mattermost/VERSION still showing 5.39.2...so may be it fails to update version but updates the database schema ?

How to make old version work with new database schema ?

#### Expected behavior
It shouldn't throw that error.

**Comment by isacikgoz** [comment]
Hey @khurshid-alam if the database version is saved it means that migrations are either completed or there is no need for a database update. Either way if you run mattermost-server v6.1 it is going to save DB version to `6.1`. Somehow your service file may have incorrect information. Could you check version with the mattermost-cli? See https://docs.gitlab.com/ee/integration/mattermost/#mattermost-command-line-tools-cli

And note that mattermost 6.x is a major upgrade from 5.x so it's expected to have long running migrations especially if you have big database.
