### ISSUE TITLE
Incorrect string value by using focalboard

### ISSUE THREAD

**Issue by Redor** [mattermost/mattermost-server#19257]
#### Summary
It is not possible to create a new card on the focalboard.

#### Steps to reproduce
After creating a new board in focalboard, hit the "New" button to create a new card (error occurs)

#### Expected behavior
I should be able to create a new card.

#### Observed behavior (that appears unintentional) 
The client tries to POST to https://xx.xx.de/plugins/focalboard/api/v1/workspaces/ip4oipmidjgq9fqidcendjcfrc/blocks, but gets 500 error.

Payload:
`[{"id":"7ensjq1fw6xdcpreo6bc8cii9pc","schema":1,"workspaceId":"","parentId":"bd7eq9i1cr7nzzbee3j5c7cheoy","rootId":"bd7eq9i1cr7nzzbee3j5c7cheoy","createdBy":"","modifiedBy":"","type":"card","fields":{"icon":"🐚","properties":{},"contentOrder":[],"isTemplate":false},"title":"","createAt":1640695203782,"updateAt":1640695203782,"deleteAt":0}]`

On the server-side in the logs I see:
```
{"timestamp":"2021-12-28 13:06:42.710 Z","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:924","plugin_id":"focalboard","code":"500","error":"\"Error 1366: Incorrect string value: '\\xF0\\x9F\\x90\\x81\",...' for column 'fields' at row 1\"","_msg":"","api":"/api/v1/workspaces/ip4oipmidjgq9fqidcendjcfrc/blocks"}
Waiting for data... (interrupt to abort)
```

Side info: I used focalboard for the first time, after installing mattermost 6.2.1

**Comment by amyblais** [comment]
@Redor Would you be open to re-opening this issue at https://github.com/mattermost/focalboard/issues?
