### ISSUE TITLE
Can not "Enable Team Creation" in System Console (Team Edition 6.2.1-0 on Debian 10)

### ISSUE THREAD

**Issue by rolance** [mattermost/mattermost-server#19265]
#### Summary
System Console is not showing the "enable team creation" flag.

#### Steps to reproduce
New install of Team Edition 6.2.1-0 on Debian 10
Go to /admin_console/site_config/users_and_teams
"Enable Team Creation" option is not displayed.

#### Expected behavior
Should be able to create new Teams. Desired: 
![image](https://user-images.githubusercontent.com/6423347/147866607-bf898d4d-ef12-4864-8928-d0b460db9a8c.png)

Actual:  
![image](https://user-images.githubusercontent.com/6423347/147866621-828df0b2-cf88-4dd4-862e-90e553625b74.png)

**Comment by amyblais** [comment]
@rolance Is team creation enabled under Permissions > System Scheme https://docs.mattermost.com/onboard/advanced-permissions.html#system-scheme?

**Comment by amyblais** [comment]
@marianunez @mkraft Wondering if you know if this a bug or expected - I was able to reproduce this on an Enterprise Edition test server. (I wasn't sure which team owns this)

**Comment by amyblais** [comment]
I've created a ticket while waiting for a response from dev: https://mattermost.atlassian.net/browse/MM-40834.

**Comment by mkraft** [comment]
@rolance The intent was that the permissions would drive the behavior instead of the configuration which was deprecated. Are you able to get your desired behaviour working with the permissions via System Console > User Management > Permissions > All Members > Create Teams?
