### ISSUE TITLE
Unable to create a new direct message channel

### ISSUE THREAD

**Issue by akhmerov** [mattermost/mattermost-server#19269]
#### Summary
After an upgrade to 6.1.0 we're unable to create new direct message channels due to a server error.

#### Steps to reproduce
- Get a mattermost 5.39 via gitlab-omnibus + docker (v14.4.0)
- Upgrade to mattermost 6.1 via gitlab-omnibus v14.6.0
- Attempt to create a direct message channel with the user one didn't message with previously

#### Expected behavior
- New DM channel is created

#### Observed behavior (that appears unintentional) 
- Observe that the channel isn't created (response 500 with error message `{"id":"app.channel.create_direct_channel.internal_error","message":"Unable to save direct channel.","detailed_error":"","request_id":"<...>","status_code":500}` and server logs showing `{"timestamp":"2022-01-03 15:45:55.364 +01:00","level":"error","msg":"Unable to save direct channel.","caller":"web/context.go:105","path":"/api/v4/channels/direct","request_id":"<...>","ip_addr":"<...>","user_id":"<...>","method":"POST","err_where":"createDirectChannelWithUser","http_code":500,"err_details":"default_channel_roles_select: context deadline exceeded"}`

**Comment by mxschumacher** [comment]
not a solution yet, but a part of the code we could investigate to pin down this issue: https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/channel_store.go#L1631

**Comment by amyblais** [comment]
@agnivade @streamer45 Do the log errors indicate a bug?

**Comment by agnivade** [comment]
The error says "context deadline exceeded" which means the query timed out. The query is simple, so I don't think there's anything bad with the query itself. I think this might be a symptom of some other issue.

- Is everything else working perfectly, and only DM channels are not being created?
- Are group channels working fine?
- Is adding a user to channel working fine?

I'd also suggest to look at the DB health in general to rule out anything causing problems with the application.

**Comment by akhmerov** [comment]
I examined the logs once again. In addition to this error, I see `"msg":"Access to route for non-existent plugin"`, which seems bening. I also see seemingly related errors

```
{"timestamp":"2022-01-03 12:13:31.245 +01:00","level":"error","msg":"Unable to get the channel member.","caller":"web/context.go:105","path":"/api/v4/channels/<...>/members/<...>","request_id":"<...>","ip_addr":"<...>","user_id":"<...>","method":"GET","err_where":"GetChannelMember","http_code":500,"err_details":"fa
iled to get ChannelMember with channelId=<...> and userId=<...>: context deadline exceeded"}
{"timestamp":"2022-01-03 12:29:11.370 +01:00","level":"error","msg":"Unable to get the channels.","caller":"web/context.go:105","path":"/api/v4/users/me/teams/<...>/channels","request
_id":"<...>","ip_addr":"<...>","user_id":"<...>","method":"GET","err_where":"GetChannelsForUser","http_code":500,"err_details":"failed to get channels wi
th TeamId=<...> and UserId=<...>: context deadline exceeded"}
```

Manually opening the endpoints seems to work for me though.

There's also this error:

```
2022-01-04_12:06:25.10530 ERROR:  duplicate key value violates unique constraint "linkmetadata_pkey"
2022-01-04_12:06:25.10532 DETAIL:  Key (hash)=(2074136487) already exists.
2022-01-04_12:06:25.10533 STATEMENT:  insert into "linkmetadata" ("hash","url","timestamp","type","data") values ($1,$2,$3,$4,$5);
2022-01-04_12:06:25.26360 ERROR:  duplicate key value violates unique constraint "linkmetadata_pkey"
2022-01-04_12:06:25.26362 DETAIL:  Key (hash)=(749650719) already exists.
2022-01-04_12:06:25.26363 STATEMENT:  insert into "linkmetadata" ("hash","url","timestamp","type","data") values ($1,$2,$3,$4,$5);
```

That DB error looks bad, but also largely unrelated. Group channels are working fine, so does creation of new channels, and inviting users to new channels.

How to check DB health in general? I know how to get to the psql console, but I don't know what else and how to check.

**Comment by agnivade** [comment]
It seems like multiple queries are timing out, which indicates that the DB is becoming slow to respond in general.

Check your DB load, CPU, memory and query times. Check slow query logs and see if there's any specific query which is slow, or all queries are slow. If all queries are slow, maybe do a full vacuum analyze to recompute the statistics.

If you have Grafana setup, also take a look at the graphs to get an idea of where the problem lies.

**Comment by akhmerov** [comment]
This runs on a 24 cpu / 128 GB instance; CPU and memory usage show no noticeable problems or spikes at any time. Vast majority of queries also goes without delay.

On the other hand `docker restart mattermost` has seemingly resolved the problem :rofl: 

Thanks for the advice; I'll close this and reopen if the issue reappears.

**Comment by syspark** [comment]
Ok, thanks. I thought the 24 CPU / 128 GB instance was for the database, not for Mattermost.

**Comment by akhmerov** [comment]
It seems that the problem reappeared. This time I've upgraded mattermost to 7.0, and `docker restart` doesn't help anymore.

**Comment by akhmerov** [comment]
The entire integrity check runs in 30 seconds, and therefore this doesn't seem to be related to database load. The integrity finds the following orphans:

```
Found 4604 in relation FileInfo orphans of relation Posts
Found 187982 in relation Audits orphans of relation Sessions
Found 2 in relation ChannelMemberHistory orphans of relation Users
Found 1 in relation Status orphans of relation Users
```

**Comment by akhmerov** [comment]
Turning playbooks and boards plugins off and back on for some reason resolved the issue.
