### ISSUE TITLE
Add the Default Clock Display option in System Console

### ISSUE THREAD

**Issue by kamarado** [mattermost/mattermost-server#19272]
## Issue
This is a feature request for adding a new server-wide setting to self-hosted Mattermost servers aimed to set the default clock display format for new users (12h or 24h). 

### Does it reproduce in a web browser?
Yes. Mattermost lacks such a setting regardless of desktop or web app.

### Try "Clear Cache and Reload"
Irrelevant.

### Write detailed information
 + How to reproduce:
   * Add a new user to any self-hosted Mattermost server
   * Open user's settings > Display
 + Expected behavior:
   * Clock Display should depend on the corresponding server-wide setting
 + Desktop App version: 5.0.2
 + Operating System: Windows 10
 + Mattermost Server version: 6.1.0

## Feature idea
Display Clock format (12h | 24h) for newcomers should depend on the corresponding server-wide setting.

## Pull request
Doesn't exist yet.

This issue addresses mattermost/desktop#874

**Comment by devinbinnie** [comment]
Moved to server repo as this requires server work.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @kamarado, 

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by Uatschitchun** [comment]
This one is truely missing!

**Comment by joho1968** [comment]
How can this still be an issue in 2025 ... 🤔
