### ISSUE TITLE
go get: installing executables with 'go get' in module mode is deprecated.

### ISSUE THREAD

**Issue by jsoref** [mattermost/mattermost-server#19284]
#### Summary
Bug report in one concise sentence

#### Steps to reproduce
1. Visit https://app.circleci.com/pipelines/github/mattermost/mattermost-server/30193/workflows/54e7f1bd-35f3-415e-af31-e9c951950ba6/jobs/223480
2. See:
   > Please update the migration bindata using go get -modfile=go.tools.mod github.com/go-bindata/go-bindata/...
3. Run `go get -modfile=go.tools.mod github.com/go-bindata/go-bindata/...`

#### Expected behavior
Instructions shouldn't suggest things that are deprecated/don't work

#### Observed behavior (that appears unintentional) 
```
% go get -modfile=go.tools.mod github.com/go-bindata/go-bindata/...
go: downloading github.com/go-bindata/go-bindata v3.1.2+incompatible
go get: installing executables with 'go get' in module mode is deprecated.
        To adjust and download dependencies of the current module, use 'go get -d'.
        To install using requirements of the current module, use 'go install'.
        To install ignoring the current module, use 'go install' with a version,
        like 'go install example.com/cmd@latest'.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

#### Possible fixes
#18329 has mention of related things.

**Comment by amyblais** [comment]
cc @agnivade

**Comment by agnivade** [comment]
We recommend using Go 1.16 for now. We haven't yet made the necessary changes to properly support higher versions of the toolchain.

**Comment by agnivade** [comment]
This is fixed now via https://github.com/mattermost/mattermost-server/commit/b6f3f580bc282357ff3b6c26474890c8149ce788
