### ISSUE TITLE
When User Mouse Hover On The Channel Then Notification count should note be hide

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19294]
#### Summary
When User Mouse Hover On The Channel Then Notification count should note be hide

#### Steps to reproduce
Mouse hover on the channel who have 1 notification then Notification will hide, pls see the video. 

#### Expected behavior
Notification Count **Should NOT be Hide.**

vidoe :- https://user-images.githubusercontent.com/89907719/148534026-edad1092-d515-4612-8cd7-3df90262b25f.mp4

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-40878.

**Comment by hmhealey** [comment]
Thanks for the report, @dipak-demansol. This is actually working as intended. We have limited space in the sidebar, and we want to show as much of the channel's name as possible, so we swap the notification badge with the menu on hover to avoid covering up any of the channel's name.
