### ISSUE TITLE
does not respond to smaller screens

### ISSUE THREAD

**Issue by Svetlana-T** [mattermost/mattermost-server#19303]
#### Summary
Does not show boards properly in 1024 x 768 screen res - boards that have a far in the future completion date are not visible on screen. Changing page zoom to 67% "helps".

#### Steps to reproduce
Open any mattermost board with more than five deadlines in a 1024 pixels wide Firefox window. There will be more than five columns. 

#### Expected behavior
Very prominently indicate that there are more columns available. Include a navigation feature to scroll to these columns which are off screen.

#### Observed behavior (that appears unintentional) 
Boards that have a far in the future completion date are not visible on screen. Changing page zoom to 67% "helps". Note that I am not including a screenshot here, as this is an internal instance; if you have a demo then I can test for the issue there and upload a screenshot.

#### Possible fixes
This is a CSS issue. Someone could adjust the CSS style of the boards page.

**Comment by Svetlana-T** [comment]
Note that this is not a server issue, this is issue with frontend. If there is another github project for the front-end please let me know. (Came to here from https://mattermost.org/filing-issues/ page). Thank you for your time.

**Comment by amyblais** [comment]
@Svetlana-T Would you be open to re-opening this issue at https://github.com/mattermost/focalboard/issues?

**Comment by Svetlana-T** [comment]
Hi @amyblais The issue is at example.org/boards/workplace/, and as far as I know it has nothing to do with example.org/plugins/focalboard/workspace/ which I don't use. Are you sure that the link you gave is the correct place to report this bug? Please confirm, then I will follow your instructions.

**Comment by amyblais** [comment]
Yes, they are the same. Focalboard was recently re-named to Boards. The GitHub repository wasn't renamed, but it's referring to Boards.
