### ISSUE TITLE
When mattermost is loading at that time there should be a skeleton loader. (User Experience improvement point)

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19305]
#### Summary
When Mattermost Page load then for few sec (depend on internet Connection) i can see the blank page. **pls see the video.**

#### Steps to reproduce
:- refresh your mattermost site and when the page will load then you can see the blank page for few sec. (May be you will not able to see it in the local mattermost)

#### Expected behavior
:- when page is loading then there should be a skeleton loader so user will not see a blank screen. (user Experience improvement point)

#### Possible fixes
:- **please add skeleton loader When page is loading.** 

https://user-images.githubusercontent.com/89907719/148767167-47c71996-b84f-4210-82ba-1aaa1936c269.mp4

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-40913
