### ISSUE TITLE
https://community.mattermost.com is not working

### ISSUE THREAD

**Issue by codedsun** [mattermost/mattermost-server#19318]
#### Summary
Bug report in one concise sentence
https://community.mattermost.com is not working

#### Steps to reproduce
Open the link https://community.mattermost.com
#### Expected behavior
It should open

<img width="757" alt="image" src="https://user-images.githubusercontent.com/20026440/149092898-d0ba8420-832b-48cd-ba4d-3427cc6e4365.png">

**Comment by Willyfrog** [comment]
Hello and thanks for reporting!
Community is again online. Sorry if this caused any inconvenience.
