### ISSUE TITLE
Error while creating direct conversation

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [mattermost/mattermost-server#19315]
#### Summary
I am calling 3 apis one after the other while trying to create direct chat.
The apis are as mentioned below.

**Request URL: /v4/channels/direct
Request Method: POST
Status Code: 201 Created
Payload: ["omjiw51g93fpxcefmnixq9sibw","ikm54hoaj7ytmj7u9xjtipixcw"]**
Response: 
````javascript
{"id":"a6ftn18n8igj3ehaw3ky5pzgxh","create_at":1641534856457,"update_at":1641534856457,"delete_at":0,"team_id":"","type":"D","display_name":"","name":"ikm54hoaj7ytmj7u9xjtipixcw__omjiw51g93fpxcefmnixq9sibw","header":"","purpose":"","last_post_at":0,"total_msg_count":0,"extra_update_at":0,"creator_id":"","scheme_id":null,"props":null,"group_constrained":null,"shared":null}
````

**Request URL: /v4/teams/ompypkc5pt87pk6r4y1r31yy9w/channels/name/ikm54hoaj7ytmj7u9xjtipixcw__omjiw51g93fpxcefmnixq9sibw
Request Method: GET
Status Code: 200 OK**
Response: 
````javascript
{"id":"a6ftn18n8igj3ehaw3ky5pzgxh","create_at":1641534856457,"update_at":1641534856457,"delete_at":0,"team_id":"","type":"D","display_name":"","name":"ikm54hoaj7ytmj7u9xjtipixcw__omjiw51g93fpxcefmnixq9sibw","header":"","purpose":"","last_post_at":0,"total_msg_count":0,"extra_update_at":0,"creator_id":"","scheme_id":null,"props":null,"group_constrained":null,"shared":null}
````

**Request URL: /v4/users/ikm54hoaj7ytmj7u9xjtipixcw/preferences
Request Method: PUT
Status Code: 400 Bad Request**
Payload: 
````javascript
[{"user_id":"ikm54hoaj7ytmj7u9xjtipixcw","category":"direct_channel_show","name":"omjiw51g93fpxcefmnixq9sibw","value":"true"},{"user_id":"ikm54hoaj7ytmj7u9xjtipixcw","category":"channel_open_time","name":"a6ftn18n8igj3ehaw3ky5pzgxh","value":1641534837689}]
Response: {"id":"api.context.invalid_body_param.app_error","message":"Invalid or missing preferences in request body.","detailed_error":"","request_id":"o5jy8uk5ibgste95dihrx93gxw","status_code":400}
````

Anyone has idea about this issue?

#### Steps to reproduce
Try to create direct chat

#### Expected behavior
Should be able to create direct chat

#### Observed behavior (that appears unintentional) 
It's giving error as mentioned above

#### Possible fixes
NA

**Comment by amyblais** [comment]
@rajeshwarpatlolla What Mattermost server version are you on?

**Comment by rajeshwarpatlolla** [comment]
This is what it's showing.

<img width="579" alt="Screenshot 2022-01-12 at 9 12 46 AM" src="https://user-images.githubusercontent.com/9896335/149060041-4c51fe40-3231-4d4c-aad7-74b1786412c6.png">

**Comment by amyblais** [comment]
@rajeshwarpatlolla Thank you, we currently support versions 5.37+, would you be open to upgrading your server?

**Comment by rajeshwarpatlolla** [comment]
@amyblais We have upgraded the server, but still getting the same error as mentioned above.

<img width="653" alt="Screenshot 2022-01-30 at 11 12 33 AM" src="https://user-images.githubusercontent.com/9896335/151688178-2c87a329-3477-43d8-bfc7-f1f6c5f22cce.png">

**Comment by streamer45** [comment]
@rajeshwarpatlolla How are these requests generated? Are they coming from a custom client? Looking at the failed one (updating user's preferences) the value field should always be a JSON string, even if it identifies a numeric timestamp. Fixing that should make the request go through.

**Comment by rajeshwarpatlolla** [comment]
@streamer45  which API u r referring to. I mentioned 3 APIs which I am calling one after the other. So i want to know which API you are referring to.

**Comment by streamer45** [comment]
> @streamer45 which API u r referring to. I mentioned 3 APIs which I am calling one after the other. So i want to know which API you are referring to.

That would be the third one, the only one returning an error.

**Comment by rajeshwarpatlolla** [comment]
Oh, yes, after making it a string instead of a number it worked. Thanks
