### ISSUE TITLE
Migrate SqlChannelStore.GetMembersByIds/GetMembersByChannelIds to squirrel

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#19336]
#### Summary

The `SqlChannelStore.GetMembersByIds/GetMembersByChannelIds` query is written by hand using a static string `channelMembersForTeamWithSchemeSelectQuery`.

We would like to convert the query to be generated using [squirrel](https://github.com/Masterminds/squirrel) and then use sqlx to make the DB call.

If you are interested to work on this issue and need some guidance, please feel free to ping @agnivade or @isacikgoz in this thread.

**Comment by aliraad79** [comment]
Hi. It's my first time contributing.
Can i work on this?

**Comment by agnivade** [comment]
Go for it @aliraad79 !

**Comment by aliraad79** [comment]
I have trouble running test it's usually took a long time.
Is test-server-quick enough for this subject because test-server took long time and i think it's not responding

**Comment by aliraad79** [comment]
Is there a faster way to test exactly that test?
test-server took ages to run

**Comment by agnivade** [comment]
Hey @aliraad79, yes you can run an exact test by passing the test name. You can see our documentation here: https://developers.mattermost.com/contribute/server/developer-workflow/#running-only-specific-server-unit-tests, or you can look up the Go testing documentation using `go help test`

**Comment by agnivade** [comment]
Hey @aliraad79 - how is it going with this? Let me know if you need any help.

**Comment by aliraad79** [comment]
hi. i tried to fix it but can't help it. sorry for that. if anyone want to try move on.

**Comment by prakharporwal** [comment]
I would like to work on this .

**Comment by prakharporwal** [comment]
I would like to try this.
I can't test changes I made. How can I run the program and test the function. I tried logging data but the make run-server failes . How can I trigger the function ?

**Comment by agnivade** [comment]
Hey @prakharporwal - You can test the changes by running the `ChannelStore` tests from store/sqlstore. Please see https://developers.mattermost.com/contribute/server/developer-workflow/#running-only-specific-server-unit-tests on how you can run specific tests.

**Comment by agnivade** [comment]
Hey @prakharporwal - how is it going with this?

**Comment by prakharporwal** [comment]
I made some changes . idk tests are failing .

**Comment by agnivade** [comment]
Can you send a PR? I can take a look.

**Comment by prakharporwal** [comment]
Ok . I am sending in

**Comment by prakharporwal** [comment]
some issue with my github login . will take some time.

**Comment by noxer** [comment]
I'd like to take over this issue.
