### ISSUE TITLE
Migrate SqlChannelStore.performGlobalSearch/performSearch to use squirrel

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#19333]
#### Summary

The `SqlChannelStore.performGlobalSearch/performSearch` query is written by hand with lots of complicated logic around creating the parameters for the query.

We would like to convert the query to be generated using [squirrel](https://github.com/Masterminds/squirrel) and then use sqlx to make the DB call.

This requires in-depth knowledge of the squirrel API as the query is not very straightforward.

Fixing this eventually means fixing the top-level callers of this method also. They are:
1. AutocompleteInTeam
2. SearchInTeam
3. SearchArchivedInTeam
4. SearchForUserInTeam
5. SearchMore
6. Autocomplete

If you are interested to work on this issue and need some guidance, please feel free to ping @agnivade or @isacikgoz in this thread.

**Comment by src-r-r** [comment]
I'm taking this issue.

**Comment by src-r-r** [comment]
@agnivade, pinging you for the PR merge.

Thanks for your suggestions and help.
