### ISSUE TITLE
Migrate SqlChannelStore.SearchGroupChannels to squirrel

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#19335]
#### Summary

The `SqlChannelStore.SearchGroupChannels` query is written by hand with lots of complicated logic around creating the parameters for the query.

We would like to convert the query to be generated using [squirrel](https://github.com/Masterminds/squirrel) and then use sqlx to make the DB call.

This requires in-depth knowledge of the squirrel API as the query is not very straightforward.

If you are interested to work on this issue and need some guidance, please feel free to ping @agnivade or @isacikgoz in this thread.

**Comment by vinod-designer1** [comment]
Hi @agnivade, i can work on this issue.

**Comment by agnivade** [comment]
Hi @vinod-designer1 - how is it going with this? Let me know if you need any help.

**Comment by agnivade** [comment]
Hey @vinod-designer1 - just checking if you are still working on this?

**Comment by src-r-r** [comment]
I'd like to take this. Thank you.

**Comment by vinod-designer1** [comment]
@agnivade hey sorry, I got stuck with some deliverable at the workplace couldn't work on it.

**Comment by agnivade** [comment]
Closing since this is done now.
