### ISSUE TITLE
Migrate SqlChannelStore.autocompleteInTeamForSearchDirectMessages to use squirrel

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#19334]
#### Summary

The `SqlChannelStore.autocompleteInTeamForSearchDirectMessages` query is written by hand with some parts manually modified with `fmt.Sprintf`

We would like to convert the query to be generated using [squirrel](https://github.com/Masterminds/squirrel) and then use sqlx to make the DB call.

This would also mean migrating `AutocompleteInTeamForSearch` as well.

If you are interested to work on this issue and need some guidance, please feel free to ping @agnivade or @isacikgoz in this thread.

**Comment by pankajhirway** [comment]
I would like to take this up please.

**Comment by agnivade** [comment]
Go for it @pankajhirway !

**Comment by pankajhirway** [comment]
@agnivade Thanks !!, One question, Will the existing Tests cover this logic ? What is the best way to test my changes locally.

**Comment by agnivade** [comment]
Yes, the tests should cover the logic. The best way would be to run the ChannelStore tests manually and see if they pass. You can refer to https://developers.mattermost.com/contribute/server/developer-workflow/#running-only-specific-server-unit-tests for more info on that.

**Comment by pankajhirway** [comment]
@agnivade Hi, The mattermost cli doesnt support "mattermost sampledata" command from the link you shared above. 

Is there any other way I can generate sample data ?

Also Can you point me to the UI screen where this query will display data ?

**Comment by agnivade** [comment]
The sampledata command should be working AFAIR. Please ask in the Contributors or Peer to Peer help channel in the community server if you are facing issues.

> Also Can you point me to the UI screen where this query will display data ?

I don't know off the top of my head. You'll have to back trace the query and find out from which API method it gets called.

I think solving this doesn't strictly need verification from UI. You can just run the unit tests and verify that they pass.

**Comment by agnivade** [comment]
Hi @pankajhirway - how is it going with this? Let me know if I can help in any way.

**Comment by agnivade** [comment]
Awesome!

**Comment by pankajhirway** [comment]
@agnivade  PR is created

**Comment by noxer** [comment]
I'd like to take over this issue.

**Comment by noxer** [comment]
Thank you @agnivade and @isacikgoz.
