### ISSUE TITLE
Boards missing since 6.3.0 Update (Teams)

### ISSUE THREAD

**Issue by terehov** [mattermost/mattermost-server#19342]
#### Summary
After upgrading to version 6.3.0 the Boards plugin is missing in the menu bar.

#### Version

Mattermost Team Edition
Mattermost Version: 6.3.0
Database Schema Version: 6.3.0
Database: mysql

<img width="316" alt="Screenshot 2022-01-17 at 12 12 48" src="https://user-images.githubusercontent.com/490885/149759803-398fcc73-50db-493d-a9c6-c19885d2b0ff.png">

**Comment by amyblais** [comment]
@terehov Would you be open to re-opening this issue at https://github.com/mattermost/focalboard/issues?

**Comment by terehov** [comment]
sure
