### ISSUE TITLE
mattermost Boards not showing in the webpage version of the app?

### ISSUE THREAD

**Issue by gstlouisgit** [mattermost/mattermost-server#19355]
after upgrading mattermost I have started using Boards. I recall I could not use boards because I had to upgrade my app, once I did I could see the bullseye.

However now, a user just told me that they cannot see the bullseye in the webpage app. Why is that? I tried a refresh and clear cache and still can’t see it. I tried login into as my user using chrome and still can’t see it myself !?

I’ve tried chrome, brave and firefox. None show the Boards integration, and when I look from the web into channels → marketplace and find board, it show like it is not installed. try to add and says

Unable to move plugin from temporary directory to final destination. Another plugin may be using the same directory name.

**Comment by amyblais** [comment]
Responded in Forum,
