### ISSUE TITLE
When activating uBlock Origin, analytics keep sending failing requests.

### ISSUE THREAD

**Issue by trollepierre** [mattermost/mattermost-server#19380]
#### Summary
Bug report in one concise sentence
When activating uBlock Origin, analytics keep sending failing requests.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?) 
v6.2.1
1. Use Firefox,
2. install https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
3. open console, look at errors

#### Expected behavior
Describe your issue in detail
uBlock Origin blocks any tracking. Those requests are blocked. But Mattermost keeps trying

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots
![Capture d’écran 2022-01-20 à 10 53 32](https://user-images.githubusercontent.com/8363334/150315420-bee93382-6206-432a-b30e-73dd373697b1.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem
Option 1:
- propose option for user to stop using analytics

Option 2:
- if 5 failings analytics request, stop using analytics requests

Option 3:
- if uBlockOrigin detected, stop using analytics requests

thanks, good luck!

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-41176.

**Comment by hmhealey** [comment]
Thanks for the report, @trollepierre! This has bugged me for ages, but I've never gotten around to fixing it. Thanks for giving me a reminder to 😄
