### ISSUE TITLE
Threads tab is not displaying because of "Null" participants 

### ISSUE THREAD

**Issue by Szymon-Rysztof** [mattermost/mattermost-server#19401]
#### Summary
User is unable to view "Threads" because he deleted only message in a conversation. 

#### Steps to reproduce
Can't reproduce this issue. 

#### Expected behavior
After deleting only message in conversation, conversation should be removed

#### Observed behavior (that appears unintentional) 
After deleting only message in conversation, participants array was "Null" which leaded to frontend bug, because of it, threads were not displaying at all. 

#### Possible fixes
Problem was existing in one user's desktop and browser session - After inspecting inside browser deubgger, we found out, that response with all threads was successfully recived by browser, but there was uncaught error 
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'map')
    at threads.ts:43:117
    at Array.map (<anonymous>)
    at threads.ts:43:80
```
Said line: 
```
if (userThreadList?.threads?.length) {
            await dispatch(getMissingProfilesByIds(uniq(userThreadList.threads.map(({participants}) => participants.map(({id}) => id)).flat())));
```
After inspecting json with threads we found one thread with "Null" participants
![image](https://user-images.githubusercontent.com/61685853/150771765-d656a685-ba4f-4392-84c9-5f5734972d87.png)
After this, we were able to find this conversation manually and "Unfollow it" (Notice, that it wasn't actually "conversation" - because there were no repllays, but `unfollow` button was there anyway) which fixed the issue. 

Sadly, we weren't able to reproduce the issue. 

IS there any way to "safely" remove conversations like this from database? This case was simple, because user was able to find out manually said conversation inside Mattermost frontend. 

Software versions: 
MATTERMOST_IMAGE=mattermost-team-edition
MATTERMOST_IMAGE_TAG=6.1.0
Database: POSTGRES_IMAGE_TAG=13-alpine
Oficial docker repo.

**Comment by amyblais** [comment]
@koox00 @ashishbhate Could this be related to https://mattermost.atlassian.net/browse/MM-40636, or do you know other known issues related to the above report?

**Comment by amyblais** [comment]
The reporter mentioned version v6.1.0. @Szymon-Rysztof Are you also able to reproduce this on the latest v6.3.1?

**Comment by Szymon-Rysztof** [comment]
@amyblais 
I'm not sure - because it's our production environment and we were not planning upgrading server at this moment, 
Qlso i had no luck in reproducing it myself BUT the same user, that had this problem in first place, told me today, that it occured again. 
I can try to collect some additional logs, if you tell me which one you want.

**Comment by amyblais** [comment]
cc @koox00 if additional logs would be helpful.

**Comment by koox00** [comment]
hey @Szymon-Rysztof, app debug logs around the time of the issue would help, thank you.

**Comment by Szymon-Rysztof** [comment]
@koox00 @amyblais 
Do i need to redact anything from debug log? I doesn't seem like confidential info, but i'lll ask anyway.

**Comment by amyblais** [comment]
You can redact any confidential data, such as passwords.

**Comment by amyblais** [comment]
@Szymon-Rysztof Does this reproduce on a more recent version of Mattermost?

**Comment by amyblais** [comment]
I'll close this for now, but if this still reproduces on a recent version, let me know or re-open this issue with details on the Mattermost server log errors.
