### ISSUE TITLE
Password reset message says the link is good for 24 hours when it expires after two

### ISSUE THREAD

**Issue by zaengerlein** [mattermost/mattermost-server#19438]
#### Summary
Same issue which was reported some time back. For some reason the password reset link expires faster than in 24h
The issue was closed before, because it could not be reproduced.
https://github.com/mattermost/mattermost-server/issues/7195

#### Steps to reproduce
v 6.3.0
- Request password reset
- Wait for a few hours but less than 24h
- Try to reset password with link provided in e-mail

#### Expected behavior
Link should work up to 24h

#### Observed behavior (that appears unintentional) 
Mattermost replied that link had expired when it was clicked.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-41343.

**Comment by arjitc** [comment]
Just to confirm -- Is this where the 1 hour PasswordRecoverExpiryTime is inherited from?

https://github.com/mattermost/mattermost-server/blob/master/app/user.go#L38

I see it's used during the checks here,

https://github.com/mattermost/mattermost-server/blob/master/app/user.go#L1258-L1260

**Comment by Emeka-Ugbanu-hub** [comment]
I would love to help with this. Can you assign it to me?

**Comment by Emeka-Ugbanu-hub** [comment]
I would love to help with this but I don't know the GO programming language

**Comment by amyblais** [comment]
No problem! I've unassigned you from this.

**Comment by Emeka-Ugbanu-hub** [comment]
ok thanks

**Comment by TylerStilson** [comment]
I would like to help with this if possible!

**Comment by amyblais** [comment]
Thank you! But it looks like our team submitted a PR for this just an hour ago: https://github.com/mattermost/mattermost-server/pull/19484. :)
