### ISSUE TITLE
The view for the display of an individual thread remains empty in Safari 13.1.2

### ISSUE THREAD

**Issue by rpkoller** [mattermost/mattermost-server#19466]
#### Summary
With "collapse reply threads" (beta)-feature active if I try to view an individual thread in Safari 13.1.2 the thread view remains empty and the content of the thread isn't shown.
 
#### Steps to reproduce
I am running MacOS High Sierra 10.13.6 with all the latest patches applied and Safari 13.1.2. 

#### Expected behavior
I've simply activated the "collapse reply threads" feature in the settings and then tried to access a thread in Safari
 
#### Observed behavior (that appears unintentional) 
On the left Safari 13.1.2 (13609.3.5.1.5) and on the right Firefox 96.0.3 (works as expected)
![safari-firefox](https://user-images.githubusercontent.com/1665422/152067600-208b55b2-51e4-4860-9680-2e5b329a6463.png)

The devtools console in Safari is outputting the following errors: 
![console](https://user-images.githubusercontent.com/1665422/152068480-41ae098f-6fe3-4df0-9dd0-7e185b0a895d.png)

**Comment by amyblais** [comment]
@rpkoller What Mattermost server version are you on?

**Comment by rpkoller** [comment]
it is version cloud-2022-01-27-1

**Comment by amyblais** [comment]
@koox00 @ashishbhate Are additional logs needed to take a look at this issue?

**Comment by koox00** [comment]
@amyblais this is most probably a client side styling issue, since it's OK in Firefox, let's open a ticket

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-41704.

**Comment by rpkoller** [comment]
i would be open but i am unable to. i am stuck to Safari 13.1.2 since Safari updates aren't provided for High Sierra by Apple anymore (i am still using a mbp 13" early 2011 - will order a new in the coming weeks)). but I've just reported the issue since https://docs.mattermost.com/install/software-hardware-requirements.html#software-requirements has listed Safari v12+ as the minimum technical requirement. but already suspected that the issue couldnt be reproduced on the current safari verison. :/

**Comment by amyblais** [comment]
@rpkoller Makes sense, we had an internal discussion and we'll be updating the software requirements guide to note that we recommend a more recent Safari version.

Until you order a new device, one option could be for you to use another browser in the meanwhile.

**Comment by rpkoller** [comment]
yep i agree upgrading the minimum software requirement is a reasonable step ( tbh would make sense to even support only the versions of safari apple supports - users still have the option to use firefox, chrome or alike) . 

and one odd detail i am using the mattermost desktop app ( even though the minimum requirement is macos 10.14+  it works nevertheless without any complaint) and the odd part about is since the electron app is utilising webkit therefor it is strange why it isnt working in safari but in the mattermost app using webkit? that is the only detail that makes me scratch my head.

**Comment by amyblais** [comment]
Docs have been updated,
