### ISSUE TITLE
Saving changes in channel member list (in system console ) always fails

### ISSUE THREAD

**Issue by zaengerlein** [mattermost/mattermost-server#19503]
#### Summary
Saving changes in channel member list always fails 

#### Steps to reproduce
v 6.3.0
In either the web view or the Mac desktop app as administrator user go to the system console. 
There select channel, select a private channel (not tested for public channand try to change something the member list for that channel. Either add a member or switch one to channel administrator.
Then try to hit the blue save button in the lower left corner.

#### Expected behavior
I would expect that the changes are saved on the server and the member list is displayed in an updated state.

#### Observed behavior (that appears unintentional) 
The blue button has a spinner an keeps displaying the text "Saving settings" indefinitely. The changes can not be saved, as any other action triggers a pop up asking to cancel the changes.

From my point of view this issue is major, as I have no workaround (e.g. mmctl) for some variations of this issue (e.g. switching a member in a channel to channel admin, is not possible for me at all, as mmctl does not support this).

Tried both in Edge and Safari browser.

#### Possible fixes
Sorry, can not help with that...

**Comment by amyblais** [comment]
I'll close this as a dup of https://github.com/mattermost/mattermost-server/issues/19051.
