### ISSUE TITLE
Emoji category offset causes multiple renders

### ISSUE THREAD

**Issue by HarshaLaxman** [mattermost/mattermost-server#19517]
#### Summary
For each emoji category, setting the offset causes another render of the EmojiPicker, adding a total of about 300ms before user can interact.

#### Steps to reproduce
```
Build Hash: 09e13360c2e24efee26d5dc989a1d7d7ada1f014
Webapp Build Hash: 2895b6fc70d934bb85b29a884155b878aedfaa08
```
Type something into the EmojiPicker ie 'banana' which will remove the category sections.
With React Profiler enabled, delete what was previously typed which will cause the category sections to return.

#### Expected behavior
The offset changing should not require a render as the value is only used on click of the category picker.

#### Observed behavior (that appears unintentional) 
An additional ~30ms render is done for each category, totaling ~300ms (tested on a local build with no custom emojis added)

<img width="1275" alt="Flamegraph Ranked" src="https://user-images.githubusercontent.com/19939186/152884249-13dbd1da-c81b-4797-bab0-33c4d48ecef3.png">

#### Possible fixes
Store offsets in the redux store. EmojiPicker will not need to render on offset change, and on clicking the category picker, it can retrieve the offset from store.
<img width="1273" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/19939186/152884599-04bb428e-5a30-4812-901d-b9d8a0fca3bb.png">

**Comment by M-ZubairAhmed** [comment]
We are not using offsets in our new implementation of emoji picker https://github.com/mattermost/mattermost-webapp/pull/9597 let us know how to improve :)

**Comment by HarshaLaxman** [comment]
Hi @M-ZubairAhmed thanks for the heads up, looking forward to the new emoji picker implementation!
