### ISSUE TITLE
Custom Terms of Service Feature throwing error 1062 Duplicate PRIMARY

### ISSUE THREAD

**Issue by Neptoos** [mattermost/mattermost-server#19512]
#### Summary
Since Version 6.3.3. we are facing an issue, that our custom terms of service cannot be accepted anymore. 

#### Steps to reproduce
Mattermost v6.3.3 Enterprise Edition (HA Cluster) 
Mysql DB (Master and 2 replicas)

1. (Re-)enable Custom Terms of Service and trigger a new "Accept Terms of Servcie", click on "Accept".
2. Error Message shows up, that it cannot be saved

#### Expected behavior
Accepting Terms of Service should be saved and disappear. 

#### Observed behavior (that appears unintentional) 
error web/context.go:105 timestamp=2022-02-07 15:15:45.183 Z path=/api/v4/users/me/terms_of_service request_id=gxqt9z3gcjn8iyj6en8sm6ycba ip_addr=100.0.4.6 user_id=i1ogswk573feif31yi8tczee4r method=POST err_where=SaveUserTermsOfService http_code=500 err_details=failed to save UserTermsOfService with userId=i1ogswk573feif31yi8tczee4r and termsOfServiceId=3zbqei53zpg49nxrd8c17bra6r: Error 1062: Duplicate entry 'i1ogswk573feif31yi8tczee4r' for key 'PRIMARY' Unable to save terms of service.

**Comment by amyblais** [comment]
This is being scheduled for v6.5 and v6.3.5.
