### ISSUE TITLE
Team sidebar shows scrollbar even when not needed in Chrome (Mac)

### ISSUE THREAD

**Issue by chenilim** [mattermost/mattermost-server#19534]
#### Summary
Team sidebar shows scrollbar on hover, even when not needed

#### Steps to reproduce
1. Open Mattermost community server in Chrome 98 for Mac.
2. Hover over team sidebar

#### Expected behavior
Scrollbar should not appear when content fits

#### Observed behavior (that appears unintentional) 
Scrollbar appears on hover

#### Notes:
Mattermost Version: cloud-2022-02-03-1
Database Schema Version: 6.4.0

I have 4 teams in my sidebar.
<img width="93" alt="Screen Shot 2022-02-10 at 9 47 37 AM" src="https://user-images.githubusercontent.com/46905241/153510493-ba064445-ffa8-4a28-92f3-da02706aeeb6.png">

Doesn't repro in FireFox (Mac), Safari (Mac), or Edge (Windows) for me.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-41744.
