### ISSUE TITLE
Updating to 6.3.3 "failed adding column CategoryName to table IR_Playbook: Error 1118: Row size too large."

### ISSUE THREAD

**Issue by DVTrast** [mattermost/mattermost-server#19572]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
After updating mattermost to 6.3.3, "failed adding column CategoryName to table IR_Playbook: Error 1118: Row size too large." in /var/log/messages

#### Steps to reproduce
Update to version 6.3.3 (in my case I did an update from 6.2.1 to 6.3.3

#### Expected behavior
I´ve updated mattermost from 6.2.1 to 6.3.3
After the update, I´ve found the following entry in the /var/log/messages:
`Feb 16 07:50:55 mattermost: {"timestamp":"2022-02-16 07:50:55.899 +01:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"playbooks","error":"failed to run migrations: failed to complete migrations: error executing migration from version 0.25.0 to version 0.26.0: failed adding column CategoryName to table IR_Playbook: Error 1118: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"}`

**Comment by amyblais** [comment]
@lieut-data @crspeller Is there a Playbook related issue here?

**Comment by amyblais** [comment]
@DVTrast What Mattermost Playbooks version are you using?

**Comment by crspeller** [comment]
@amyblais I suspect this is a database configuration issue. 

@DVTrast Can you provide the DB and version you are using? It's possible you are running into a MySQL issue. Maybe: https://stackoverflow.com/questions/22637733/mysql-error-code-1118-row-size-too-large-8126-changing-some-columns-to-te

**Comment by DVTrast** [comment]
I use this MYSQL-Version: mysql  Ver 15.1 Distrib 10.5.15-MariaDB, for Linux (x86_64) using readline 5.1
I´ll check the MySQL-Issue.
Thank you

**Comment by lieut-data** [comment]
@DVTrast, any luck looking into this issue on your side?

**Comment by DVTrast** [comment]
Unfortunately no - I had no time. I´ll report as soon as possible the result.

**Comment by amyblais** [comment]
Feel free to re-open with details on your findings if you need more help with this,
