### ISSUE TITLE
[Question] Anyone working on adding custom roles?

### ISSUE THREAD

**Issue by gc-ss** [mattermost/mattermost-server#19599]
I am curious whether there's anyone working on adding custom roles?

For example, each role essentially has a set of options that an admin can activate or deactivate for each role and then assign different users to roles

**Comment by gc-ss** [comment]
@amyblais Thank You!

Is this something that will be available in `mattermost-team-edition`?

Also, I'm interested in `Team Override Schemes`. Is this something:

1. available in `mattermost-team-edition` or only to available in Mattermost Enterprise and Professional licensees?
2. that will allow me to create more than the default "System Admin", Member Roles
3. Tangentially, is enabling Guest access in `mattermost-team-edition` possible? (If so, do let me know and I will file a bug/PR indicating how I was struggling to discover this info)

**Comment by amyblais** [comment]
@mkraft @laneycs Would you have more details on what SKU the custom groups feature (https://github.com/mattermost/mattermost-server/pull/18839) will be available in?

1. Team Override Schemes is currently not available in Team Edition https://docs.mattermost.com/onboard/advanced-permissions.html#team-override-scheme.
2. Guest Accounts is currently also not available in Team Edition https://docs.mattermost.com/onboard/guest-accounts.html.

**Comment by mkraft** [comment]
> @mkraft @laneycs Would you have more details on what SKU the custom groups feature (#18839) will be available in?
> 
>     1. Team Override Schemes is currently not available in Team Edition https://docs.mattermost.com/onboard/advanced-permissions.html#team-override-scheme.
> 
>     2. Guest Accounts is currently also not available in Team Edition https://docs.mattermost.com/onboard/guest-accounts.html.

@amyblais It'll be available in Professional and Enterprise.
