### ISSUE TITLE
Unable to find api for saving a post and getting list of saved posts

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [mattermost/mattermost-server#19614]
#### Summary
I would like to know what is the API to save the post and list saved posts. I saw the mattermost API at [Mattermost API Reference](https://api.mattermost.com/#tag/posts) but couldn’t see any API which can be used for saving the post.

It would be really helpful if someone can help to find the API to save the post and to list the saved posts.

#### Steps to reproduce
Unable to find the APIs to save or get saved posts

#### Expected behavior
Unable to find the APIs to save or get saved posts

#### Observed behavior (that appears unintentional) 
Documentation is not showing api for saving a post

#### Possible fixes
Please kindly add save api if it's not there already in the api doc.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-42021.
