### ISSUE TITLE
mmctl giving incorrect example (typo)

### ISSUE THREAD

**Issue by digdilem** [mattermost/mattermost-server#19637]
```
# mmctl version
mmctl v5.39.1 -- bdc509d9aae4e95a2f89246362ec6538dd441934

# ./mmctl team users add help
Error: requires at least 2 arg(s), only received 1
Usage:
  mmctl team users add [team] [users] [flags]

Examples:
  team add myteam user@example.com username
```

The 'users' word has been omitted from this example, which makes the example not valid. 

This should be:    _mmctl team **users** add myteam user@example.com username_

Appreciate version may not be current, but searching the above string in issues does not return any hits, suggesting it is still unresolved.

**Comment by agnivade** [comment]
@digdilem - Thank you for the report! Would you be open to send a PR? The repo is here: https://github.com/mattermost/mmctl. The same also applies for `team users remove`.
