### ISSUE TITLE
Profile dialog doesn't appear when there is RHS content (e.g. thread)

### ISSUE THREAD

**Issue by chenilim** [mattermost/mattermost-server#19645]
#### Summary
Unable to open profile menu when there is RHS content.

#### Steps to reproduce
1. Open a thread in the RHS
2. Click on the profile in the global nav

#### Expected behavior
The profile menu appears

#### Observed behavior (that appears unintentional) 
Nothing appears

#### Video

https://user-images.githubusercontent.com/46905241/155812476-3175843a-056b-4f18-a857-cafa2cc413eb.mov

#### Possible fixes
It seems that the profile menu is z-ordered below the RHS content. If there is no RHS, the menu appears correctly. This repros on community-daily.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-41817
