### ISSUE TITLE
Broken API calls in plugins with NGINX sub directory setup

### ISSUE THREAD

**Issue by ndgayan** [mattermost/mattermost-server#19656]
I set up the Mattermost server using NGINX and subpaths (e.g., example.com/mattermost). API calls are sometimes NOT rewritten with the subpath resulting in broken images in plugins.

Actual behavior from the GET requests:
example.com/api/v4/users/*

![Tmp](https://user-images.githubusercontent.com/1891059/156173365-ebfb9a0c-bf83-4bdf-b600-797ea28f47ea.jpg)

Expected behavior from the GET requests:
example.com/mattermost/api/v4/users/*

**In the config file, I set up the site URL to https://example.com/mattermost**

![Tmp](https://user-images.githubusercontent.com/1891059/156173202-fc4a2f57-6641-426a-845c-7c9be0138baf.jpg)

I do not know this issue is related to the Mattermost server and/or the plugin API. I appreciate any help to point me in the correct direction.

**Comment by amyblais** [comment]
@ndgayan 
1. What Mattermost server version are you on?
2. What OS and version are you on?
3. Do you see any Mattermost log errors when the issue happens?

**Comment by ndgayan** [comment]
Thanks for the quick reply.

These are the info:

What Mattermost server version are you on?
![image](https://user-images.githubusercontent.com/1891059/156189559-8b697105-a3d8-4e24-baf1-bb656e18eee8.png)

What OS and version are you on? 
The server is hosted on Ubuntu LTS 20.04
Issues in both Windows 10 - Desktop app and Chrome Browser.

I have Chrome debugger Console output:
(Broken Standup Raven profile images: request from a plugin)
GET https://example.com/api/v4/users/wcfk4ybb8tym7rasrsw9pmwxyh/image **_404_** 

Expected GET request should be (This rewritten URL loading the correct profile thumbnails)
GET https://example.com/mattermost/api/v4/users/wcfk4ybb8tym7rasrsw9pmwxyh/image

Only this issue with plugins. (Standup Revan, gif etc.) This hope my NGINX configurations are correct.

**Comment by amyblais** [comment]
@agnivade @mickmister Let me know if there could be a bug here.

**Comment by mickmister** [comment]
Hi @ndgayan, which plugins in particular are affected by this? It seems that the standup raven plugin is affected based on your screenshot. Plugins need to be individually modified to support Mattermsot servers being hosted on a subpath. The standup raven plugin is not maintained by Mattermost, so it would make sense if the plugin isn't updated to use subpaths properly.

**Comment by mickmister** [comment]
If it is the case that you only experience this with the standup raven plugin, would you be open to creating in a ticket in the repo https://github.com/standup-raven/standup-raven?

**Comment by mickmister** [comment]
@ndgayan It seems that images are failing to load, yet in the ticket description, it's stated that the `/api/v4/users` route is affected. It's important to know exactly which requests are being affected, so we can pinpoint which code is the offending code, as this very well could be an issue in the web application itself.

Can you please mention me in any follow-up responses? Thank you @ndgayan!

**Comment by ndgayan** [comment]
Hi @mickmister,

Thanks for the information request.

In Standup Raven, user profile images are broken.  
https://example.com/api/v4/users/n56knom1n7dizrm4zk15zgw3jo/image
This should be;
https://example.com/mattermost/api/v4/users/n56knom1n7dizrm4zk15zgw3jo/image

In other words, plugin API requests should use the site URL in the config file (https://example.com/mattermost). I don't know this issue in the Mattermost-server or the plugin itself. 

in the gif plugin, the broken request is shown below (powered-by-giphy.png plugin profile image).
https://example.com/plugins/com.github.moussetc.mattermost.plugin.giphy/public/powered-by-giphy.png
when I updated it with the correct subdirectory, it still failed to load. (I don't know this is the right location for plugin static images.)
https://example.com/mattermost/plugins/com.github.moussetc.mattermost.plugin.giphy/public/powered-by-giphy.png

**Comment by ndgayan** [comment]
@mickmister Thank you for taking care of this issue.
