### ISSUE TITLE
 profile pic max size Value showing Wrong

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19667]
#### Summary
 profile pic max size Value showing Wrong

#### Steps to reproduce
1) Click on Profile pic Icon from RHS.
2) Click on "profile" option.
3) Click "Edit" button of "Profile-picture" option.
4) you will see the text that inform us "Maximum file size: 100MB" (in the mattermost/core, the max file size is 1000MB, For image upload)
![image](https://user-images.githubusercontent.com/89907719/156513638-53201105-0bf1-4499-a50a-54a67279b925.png)

5) from the LHS burger menu open "System Console", -> open "File Storage" menu by searching it, -> Find the "Maximum File Size:" input box and Change the Value ex:- 20 MB and Click on the Save button.
![image](https://user-images.githubusercontent.com/89907719/156514414-3b205367-dd83-496f-b794-643db8d81517.png)
![image (1)](https://user-images.githubusercontent.com/89907719/156514860-b8d16931-b346-4f47-a788-1d2262eae4fb.png)
![image (3)](https://user-images.githubusercontent.com/89907719/156515290-849f7ff5-3579-4c0f-94fb-768f48778c84.png)

6) again goto the Profile section (step 4)
![image (4)](https://user-images.githubusercontent.com/89907719/156515713-4a845353-cb81-476f-a014-4200c669f001.png)

7) you will see that "max file size is Now 20MB" as you changed it from "System Console/File Storage".

**issue :- 8)** upload any 15 or 18 MB image and you will not able to upload it that means whatever value we change in the "System Console/File Storage/maximum-File-Size" that same value we can see in the profile-picture section but only value is changing, if you upload the image as per that value then its not working, so we should show the different value for the profile picture maximum limit.

#### Expected behavior
:- as per the file size the image should be upload.

#### Observed behavior (that appears unintentional) 
:- Video

https://user-images.githubusercontent.com/89907719/156327297-1e6a5f96-d1a5-4db2-961f-1c37abfa29bb.mp4

#### Possible fixes
:- as per the profile pic upload rules there should be a Right value of the file size.

**Comment by amyblais** [comment]
@dipak-demansol Can you help add clearer reproduction steps / description? (It's easier to read than find it from the video) Thanks!

**Comment by dipak-demansol** [comment]
> @dipak-demansol Can you help add clearer reproduction steps / description? (It's easier to read than find it from the video) Thanks!

Done.

**Comment by dipak-demansol** [comment]
@amyblais 
Q :- If uploading 15 or 18 MB image doesn't work, then do you think it's just an issue with the value shown in the profile-picture section?
A :- **yes, value is showing wrong on the profile pic section**, but when 15 or 18 MB image upload fail then there is no proper validation that Shows what's the exact issue with the uploaded image, here is the issue reported for that https://github.com/mattermost/mattermost-server/issues/19666#issuecomment-1057277317 
 
Q :- What do you think the expected value shown in the profile-picture section should be?
A:- that's hard to say because the bigger Pixel image the higher File Size and in this case mattermost not accepting high pixel image so the size should be small but i don't know what it should be exact max size.

Q:-I'm just wondering why the 15 or 18 MB image upload fails and if there is a "bigger" issue.
A:- The same image i'm not able to upload in the slack so may be its not a bigger issue, but i don't know how it was in the older version so no idea about its a bigger issue or not.  in slack i'm getting validation that its only support 4000px*4000px image but in mattermost there is not that kind of validation. i think there should be a crop functionality so the user don't have to worry about the image pixel size.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-42296.

**Comment by agnivade** [comment]
@dipak-demansol - Have you ensured that your image is under the "FileSettings.MaxImageResolution" setting?

**Comment by dipak-demansol** [comment]
> @dipak-demansol - Have you ensured that your image is under the "FileSettings.MaxImageResolution" setting?

Hi @agnivade, 
1) i Found that there is **MaxImageResolution** in the Config file of the code but the same setting is not available on Front-end so admin don't have access of changing that.
2) As you can see in the below image, there is a **MaxImageResolution** as 33177600 but as a resolution i was expecting value like ex 4000px*4000px because The resolution value should be as per height and width.

**Comment by agnivade** [comment]
1. That might be intentional. Maybe a PM question as to why there's no sysconsole setting for that.
2. Height and Width individually doesn't matter. What matters is the total number of pixels in the server side.

This seems to be an UI issue to distinguish between max file size and max resolution.

**Comment by dipak-demansol** [comment]
pls do whatever is the best to improve the user experience :+1:
