### ISSUE TITLE
Direct message -> Search For people input box, When user insert so much data then input box not looking proper.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19664]
#### Summary 
Direct message -> Search For people input box, When user insert so much data then input box not looking proper. **pls see the video**

#### Steps to reproduce
:- open the direct message. 
:- in the search input add somany text and issue will regenerate.

#### Expected behavior
:-  no matter how much data user insert, the input box should look proper.

#### Observed behavior (that appears unintentional) 
 **:- pls see the video**

https://user-images.githubusercontent.com/89907719/156313338-7dc4b19b-b7cc-44b0-838d-e390043dc9ae.mp4

#### Possible fixes
   1) there should be a max length of the direct Message Search input box.
   2) no matter how much data user insert, the input box should look proper.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-42259.

**Comment by kkennethlee** [comment]
Hi everyone, getting my feet wet here. I'll tackle this one if no one has taken it yet.

**Comment by kkennethlee** [comment]
Because there is no minimum length set, setting maximum length will collapse the input box horizontally.
I have a potential fix which is working but it involved making `scss` change to `_react-select.scss` and `_multi-select.scss`

Please let me know if this will work

**Comment by amyblais** [comment]
> Because there is no minimum length set, setting maximum length will collapse the input box horizontally. I have a potential fix which is working but it involved making `scss` change to `_react-select.scss` and `_multi-select.scss`
> 
> Please let me know if this will work

cc @hmhealey

**Comment by hmhealey** [comment]
I'd need to see what those changes end up looking like to be sure, but that sounds like it'd probably be fine. We'd just need to be careful that they're not affecting any other areas of the apps since some of that CSS is reused in a few different places.

**Comment by kkennethlee** [comment]
Yeah, I had to ask for that exact reason. I tried to look for other components that uses those files but it's been difficult to comb through the application
