### ISSUE TITLE
Start call Functionality, Screen Sharing Stop working and not able to Stop and start screen sharing again, only option is to leave a call and join again.  

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19710]
#### Summary
:- "Start call" Functionality, Screen Sharing Stop working and user is not able to Stop and start screen sharing again, only option is to leave a call and join again.  

#### Steps to reproduce
1) From RHS header section, Click on the "Start Call" Icon.
![2022_03_04_136_Kleki](https://user-images.githubusercontent.com/89907719/156817120-586c5c05-1bcf-4ea2-b35c-e5112caf8718.png)

2) Click on the maximize icon.
![2022_03_04_13a_Kleki](https://user-images.githubusercontent.com/89907719/156817781-a3fd8967-666d-4be5-91c3-c7aea799429f.png)
3) Start Screen Sharing.
![2022_03_04_13e_Kleki](https://user-images.githubusercontent.com/89907719/156818268-c845aaa4-ecec-4605-bacb-4a0a386dedc3.png)
4) Click on the Cancel Icon of the extended Model.
![2022_03_04_13l_Kleki](https://user-images.githubusercontent.com/89907719/156819325-664ef8a1-056b-464b-9122-10ce1b63286f.png)
**issue :- now by click on Stop screen sharing icon as described on below screen shot, screen sharing will not stop, only option is to leave call and join again. after close the extended window, other User will not able to see the screen share, they will see the last image of screen sharing**
![2022_03_04_13q_Kleki](https://user-images.githubusercontent.com/89907719/156820166-bb5482aa-af3e-4178-abf9-ac3569427352.png)
![2022_03_04_13u_Kleki](https://user-images.githubusercontent.com/89907719/156820444-20527ed9-6ad1-4732-aede-cd988a177cd8.png)

#### Expected behavior
:- User Should able to Stop the Screen sharing.

#### Observed behavior (that appears unintentional) 
:- after starting the screen sharing if the user direct close the extended screen (model) then User will not able to stop the screen sharing and other user Will not able to see the screen sharing, it will stuck. (technically the screen sharing was stop at the time user close that extended window, but at frontend side by click on Stop screen sharing, nothing is happening)

**Comment by dipak-demansol** [comment]
2 way to generate the issue.
1st :- Start call > Start screen sharing > Click on extend icon > click on cancel icon to close the model (window) > now user will not able to stop the screen sharing. (Stop screen sharing button will not work)
2nd :- Start call > Click on extend icon > Start screen sharing > click on cancel icon to close the model (window) > now user will not able to stop the screen sharing. (Stop screen sharing button will not work)
**pls let me know if you need a video of the issue.**

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-42315.
