### ISSUE TITLE
Setting -1 for 'Global Edit Post Time Limit' is possible

### ISSUE THREAD

**Issue by sinansonmez** [mattermost/mattermost-server#19716]
#### Summary
I was working on a [TypeScript migration](https://github.com/mattermost/mattermost-server/issues/17257) of `components/admin_console/permission_schemes_settings/edit_post_time_limit_modal`. I realized something which was strange to me. In the modal, it is possible to set -1 for Global Edit Post Time Limit

#### Steps to reproduce
1. Go to 'System Console'
2. Click 'Permissions'
3. Click  'Edit Scheme'
4. Go to 'Manage Posts' --> 'Edit Posts'
5. Click 'Anytime' 
6. Click 'Can edit for'
7. Set time -1 and click 'Save Edit Time'   

#### Expected behavior
I assume the system shouldn't allow users to set the time to -1

#### Observed behavior (that appears unintentional) 

https://user-images.githubusercontent.com/37421564/156941677-e690322d-eab3-442e-a61c-96aaaa9e951f.mov

#### Possible fixes
I don't have the possible fix but if the bug is confirmed I can try to fix together with TypeScript migration

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-42340.
