### ISSUE TITLE
Running Mattermost 6.4.1, I see Unable to activate plugin (playbooks)

### ISSUE THREAD

**Issue by joho1968** [mattermost/mattermost-server#19727]
#### Summary
After upgrading from MM 6.3.x to .6.4.1, I see this in the log: "Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"playbooks"

#### Steps to reproduce
I don't know, I get it every time I re-start MM

#### Expected behavior
I would expect any migration to successfully complete.

#### Observed behavior (that appears unintentional) 
```
{"timestamp":"2022-03-07 19:55:58.715 Z","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"playbooks","error":"failed to run migrations: failed to complete migrations: error executing migration from version 0.25.0 to version 0.26.0: failed adding column CategoryName to table IR_Playbook: Error 1118: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"}
{"timestamp":"2022-03-07 19:56:03.920 Z","level":"warn","msg":"Unrecognized config permissions tag value.","caller":"api4/config.go:379","tag_value":"sysconsole_write_*_read"}

```
#### Other information
- Ubuntu 20.04.LTS
- MariaDB 10.6
- MM 6.4.1 (upgraded from MM 6.3.x)

**Comment by amyblais** [comment]
@joho1968 Would you be open to reopening this at https://github.com/mattermost/mattermost-plugin-playbooks?

**Comment by joho1968** [comment]
Sorry 'bout that. My bad.

https://github.com/mattermost/mattermost-plugin-playbooks/issues/1077
