### ISSUE TITLE
Incoming webhook sends message to webhook author when channel specified is a direct message

### ISSUE THREAD

**Issue by dougbranton** [mattermost/mattermost-server#19762]
#### Summary
Incoming webhook sends message to webhook author when channel specified is a direct message.

#### Steps to reproduce
1. Create an incoming webhook (specifying all fields, except unselecting "lock to this channel").  
  * In our example we're specifying a Username of "jenkins" (which is not a user in our Mattermost)
2. Click update
3. Construct and execute the following curl 
  * replacing the `@user.name` with a valid user - a different user that is **not** the author of the incoming webhook)
  * replacing the endpoint with a valid mattermost incoming webhook url
```
 curl -i -X POST -H "Content-Type: application/json" -d "{\"channel\":\"@user.name\",\"text\":\"This is a test of the incoming webhook\"}" https://hook.endpoint.goes.here
 ```

#### Expected behavior
The DM should originate from the username specified when creating the webhook (in our example jenkins) and send a private direct message **only** to the `@user.name`.

#### Observed behavior (that appears unintentional) 
The DM is being sent to `@user.name` **and** the `@author`

**Comment by amyblais** [comment]
@dougbranton What Mattermost server version are you on?

**Comment by dougbranton** [comment]
Mattermost Server 6.2.1

**Comment by dougbranton** [comment]
I've written it up here: https://mattermost.uservoice.com/forums/306457-general/suggestions/44925319-incoming-webhook-option-to-not-include-webhook-aut
