### ISSUE TITLE
is it possible to disable spell check ?

### ISSUE THREAD

**Issue by necipakca** [mattermost/mattermost-server#19774]
We are trying to use in Turkish language. 
But most of auto correction are irrelevant and It cause funny situations. :)
Is there any way to disable spell check at system level ?

Browser : Safari (Spell Check disabled)
MatterMost Version : 6.0.2

**Comment by amyblais** [comment]
@necipakca There is a "Check spelling" setting that can be changed, please see docs at https://docs.mattermost.com/messaging/managing-desktop-app-options.html.

**Comment by necipakca** [comment]
@amyblais I saw this. But I am talking abouth web browser not Desktop App.

**Comment by amyblais** [comment]
Got it, I checked on Safari and I was able to disable spell check via the browser's Edit > Spelling and Grammar.
What Safari version are you on? Are you able to upgrade to a more recent Mattermost version to see if you can still reproduce it?

**Comment by necipakca** [comment]
Yep I already disabled it but I think this is not related with MatterMost. 
MacOS : Monterey

Ok I fixed it from System Preferences --> Keyboard --> Text       
Uncheck "Correct speelling automaticly".

Thanks ;)

**Comment by amyblais** [comment]
Awesome!
