### ISSUE TITLE
Search bar function does not work.

### ISSUE THREAD

**Issue by LianaSaat** [mattermost/mattermost-server#19772]
#### Summary
Search bar does not work.

#### Steps to reproduce
Version 5.0.1. Typing anything in the Search bar does not bring up any results.

#### Expected behavior
Typing in the Search bar should show past messages that contain that key word.

#### Observed behavior (that appears unintentional) 
Please see screenshot. This happens for all words, even those that can for sure be found in the channel.
<img width="307" alt="Screenshot 2022-03-11 102404" src="https://user-images.githubusercontent.com/61862871/157790100-73faeb10-8180-4520-a10c-7fd835f7b007.png">

**Comment by amyblais** [comment]
@LianaSaat 
1. Do you see the same issue on Desktop app v5.0.4?
2. What Mattermost server version are you on?
3. Do you see any Mattermost server log errors or console errors?
4. What OS and version are you on?

**Comment by LianaSaat** [comment]
@amyblais Hi Amy!

**Comment by LianaSaat** [comment]
@amyblais Hi Amy!
1. Yes, issue persists after upgrading.
2. Is this the same as Mattermost Version? If yes, then 
Mattermost Version: 5.31.9
Database Schema Version: 5.31.9
3. There are no log errors, only a main.txt in logs
4. I'm on Windows 10.
