### ISSUE TITLE
Integrate the mattermost application in our web application

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [mattermost/mattermost-server#19798]
#### Summary
We are trying to integrate mattermost web application in our existing web application. We would like to use mattermost web application for the chat feature.

#### Steps to reproduce
Currently, we are using mattermost APIs to integrate the chat features. But we are not able to build seamless applications like mattermost web apps. We are not sure if our choice of integrating APIs is a good idea. We also have issues while trying to add WebSockets, which will help us reduce a lot of multiple API calls. And it is taking a long time to match the features with the existing mattermost application using the APIs.

#### Expected behavior
If there is a way to include mattermost application in our web app, it would be easier for us to use all the features of mattermost. We are not looking at the iframe approach as it's not looking great and it's not seamless.

What we are looking at is shown in the below image. We want to have our own branding of application and mattermost within our app as shown below.
![Screenshot 2022-03-16 at 9 35 56 PM(1)](https://user-images.githubusercontent.com/9896335/158635684-c9a360d5-9185-4e13-bcc2-919af473a9ce.png)

#### Observed behavior (that appears unintentional) 
NA

#### Possible fixes
NA

**Comment by amyblais** [comment]
We have some documentation here that may be helpful: https://docs.mattermost.com/integrations/embedding.html.

There is also a feature request here that you could help upvote: https://mattermost.uservoice.com/forums/306457-general/suggestions/40351702-support-embedding-a-channel-in-a-web-page.

I also recommend sharing about either at https://forum.mattermost.com/ or via our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help), and someone on our dev team or community may have experience with this.
