### ISSUE TITLE
Slow delete of posts after upgrade from 5.37.x LTS to v6.3.5 LTS

### ISSUE THREAD

**Issue by 42wim** [mattermost/mattermost-server#19807]
#### Summary
Slow delete > 90s when having a Posts table > 10mio entries

#### Steps to reproduce
Have 10mio posts, run v6.3.5 try to delete a Post

#### Expected behavior
Posts deletion speed is fast/normal

#### Observed behavior (that appears unintentional) 
Posts deletion takes too long 

```
{"timestamp":"2022-03-19 17:42:38.625 +01:00","level":"error","msg":"Unable to delete the post.","caller":"web/context.go:105","path":"/api/v4/posts/nsd9o4mkppya8d5c9545ubnmzo","request_id":"b16ecb6n4frezfbhp9pczc7gxw","ip_addr":"xxxx","user_id":"55nng1835fyj5eeutfxquqtrxr","method":"DELETE","err_where":"DeletePost","http_code":500,"err_details":"failed to update Posts: context deadline exceeded"}
```

Running the `UPDATE` query (that's responsible for the deletes) manually on the database shows that it takes up to 90 seconds to delete a Post.

#### Possible fixes

Fixed by backporting https://github.com/mattermost/mattermost-server/pull/19191 to v6.3.x
We're running with this fix now and deletes are fast again.

**Comment by amyblais** [comment]
We'll plan this for the next v6.3 ESR dot release.
