### ISSUE TITLE
5 user is connected but only shows 2 for some user, other can see the 5 participent properly.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19825]
#### Summary
5 user is connected on call but only shows 2 for some user, other Connected user can see the 5 participent properly

#### Steps to reproduce
don't know the repro steps because required multiple people to join the call and for which user the issue will generate that i don't know, it can be anyone. 

#### Expected behavior
all the User on all should able to see to all the connected participent.

#### Observed behavior (that appears unintentional) 
on the call i was not able to see all the connected participant but other all was able to see all the participant properly so i was the only who show the issue but if i expand the model (you can see it in the video) then i was able to see all of them.

image : 
![image](https://user-images.githubusercontent.com/89907719/159680267-8ef3f1d0-c072-4a78-80af-58d22dc968d0.png)
video : https://drive.google.com/file/d/1Oo4q8QIg8k01qF2dQ3aecFcSWmeGwraD/view?usp=sharing

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-42727.
