### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by suciokhan** [mattermost/mattermost-server#19842]
Sorry, I can't find anywhere else to post this request- can you please add instructions on how to uninstall mattermost-server in your documentation? I've been searching through docs.mattermost.com and googling for 10 minutes and I can't find anything on this topic. I want to uninstall it and install Mattermost Teams instead but can't figure out how to remove it properly.

**Comment by amyblais** [comment]
We have a related docs Issue open here: https://github.com/mattermost/docs/issues/3005.
If this doesn't match with what you're looking for, feel free to open a new Issue in the docs repo at https://github.com/mattermost/docs/issues!
