### ISSUE TITLE
Workspace Optimization does not load

### ISSUE THREAD

**Issue by fduraibi** [mattermost/mattermost-server#19863]
#### Summary
"Workspace Optimization" reporting page does not load when mattermost is served under a sub path

#### Steps to reproduce
- Configure Apache to server and proxy mattermost under a subpath `/mm`
- Configure mattermost subpath `./mmctl config subpath --assets-dir /opt/mattermost/client/ --path /mm`
- Start mattermost and visit the page `https://10.0.0.1/mm`

#### Expected behavior
"Workspace Optimization" report will show up

#### Observed behavior (that appears unintentional) 
The page doesn't load, a `Loading...` message is displayed on the screen
In the console we see the request is sent without the subpath `/mm`
`https://10.0.0.1/api/v4/latest_version` instead of `https://10.0.0.1/mm/api/v4/latest_version`

![mattermost-issue](https://user-images.githubusercontent.com/432460/160618780-e6ef94b2-9bed-48c5-9d22-89caa468e3b6.png)

#### Possible fixes
Fix the sub path for that report.

#### Note
- Everything is working fine except this and some requests to fonts `https://10.0.0.1/static/Metropolis-SemiBold.woff2`

**Comment by amyblais** [comment]
@furqanmlk Is there a way for QA to test this on a sub path server?

**Comment by fduraibi** [comment]
Regarding the fonts issue, i think it is caused by including the slash before the font path:
From the page source we see `src:url(/static/Metropolis-SemiBold.woff2)`, the slash `/` before the word `static` will tell the browser to use that as the root path and not a path relative to the page sub path

**Comment by furqanmlk** [comment]
@amyblais Yes, I can reproduce this issue.

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-42885.
