### ISSUE TITLE
WebsocketSecurePort param

### ISSUE THREAD

**Issue by ZazaKumar** [mattermost/mattermost-server#19909]
Hello. I try to setup websocket with separate url wss-mm.local and port 8443
i set "WebsocketURL": "wss://wss-mm.local:8443" but i what should i do with WebsocketSecurePort param? Keep 443 or set 8443?

**Comment by amyblais** [comment]
@ZazaKumar Would you be open to posting about this on our [community server's Peer-to-peer Help channel here](https://community.mattermost.com/core/channels/peer-to-peer-help)? Someone in the community or one of our devs may likely be able to help with this.

**Comment by amyblais** [comment]
Closing out some older issues. Feel free to post about this on our [community server's Peer-to-peer Help channel here](https://community.mattermost.com/core/channels/peer-to-peer-help) or the [troubleshooting forum here](https://forum.mattermost.com/).
