### ISSUE TITLE
PNG images with transparency are displayed incorrectly.

### ISSUE THREAD

**Issue by george-polevoy** [mattermost/mattermost-server#19947]
#### Summary
PNG images with transparency are displayed incorrectly.

#### Steps to reproduce
Version 6.5
Attach a PNG with semi-transparent image to a thread.

#### Expected behavior
I expect semi-transparent image to display the same way it looks locally when attached to a thread.
Here I've made an opaque white circle with nice soft shadow with color gradient.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/2792885/162395738-1b5e3867-7d73-4142-9b4d-2cd5972dad21.png">

#### Observed behavior (that appears unintentional) 
See it is displayed incorrectly against default white background. Only the fully opaque white circle in the middle displays correctly. Nice soft color shadow is replaced with black pixels. Fully transparent region outside of original soft shadow appears ok.
Also, it displayed incorrectly after downloading it locally.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/2792885/162395802-9f7dda3c-0450-4fdd-af81-973a53e44cc5.png">

#### Possible fixes
One possibility is that the backend interprets alpha channel incorrectly. There could be variants: premultiplied alpha and unpremultiplied alpha. Another possibility is that semi-transparency is flattened to just fully transparent and opaque pixels.

**Comment by amyblais** [comment]
We have a ticket open here: https://mattermost.atlassian.net/browse/MM-36295.

**Comment by Roy-Orbison** [comment]
No idea why but that issue's comment thread has this problem described as "rather low-impact". It's literally impossible to share a PNG file, even when using the attachment icon, because Mattermost thinks it knows better. It will blindly recode even a tiny, optimised PNG into a larger JPEG file, and destroy any transparency in the process. It's just bad UX to mess with people's files.
