### ISSUE TITLE
Error logged when SendEmailNotifications is not true

### ISSUE THREAD

**Issue by edouardlp** [mattermost/mattermost-server#19967]
#### Summary
Our deployment of Mattermost has [disabled email notifications](https://docs.mattermost.com/configure/configuration-settings.html#enable-email-notifications). This leads to an error on the server startup. Note that this bug report is different, in fact almost the reverse of [this ticket](https://mattermost.atlassian.net/browse/MM-26021).

#### Steps to reproduce
Set `SendEmailNotifications` to `false` in `config.json` and restart the server

#### Expected behavior
Emails are not sent for posts and no error are logged in the console.

#### Observed behavior (that appears unintentional) 
An error is logged in the console.

<img width="871" alt="error" src="https://user-images.githubusercontent.com/1356312/163035320-6d1d37d2-1aef-4a7e-b394-b35fff06f4a1.png">

#### Possible fixes
Do not log an error when testing the SMTP connection when `SendEmailNotifications` is false.
- [Calling site](https://github.com/mattermost/mattermost-server/blob/5cb31a114a8ae9400c985ee1b015fa07b942ba17/app/server.go#L1196)
- [Condition](https://github.com/mattermost/mattermost-server/blob/5cb31a114a8ae9400c985ee1b015fa07b942ba17/shared/mail/mail.go#L212) that raises the error

**Comment by amyblais** [comment]
@edouardlp 
1. What Mattermost server version are you on?
2. What OS and version are you on?
3. Do you see any additional errors in the Mattermost server logs?

**Comment by edouardlp** [comment]
Thank you for the fast reply and apologies for the missing information

> 1. What Mattermost server version are you on?

`mattermost-enterprise-edition` version `6.5.0`

> 2. What OS and version are you on?

We are running in AWS EKS 1.21 and nodes are running Amazon Linux 2 (kernel version 5.4.141-67.229.amzn2.x86_64) 

> 3. Do you see any additional errors in the Mattermost server logs?

Yes but those are not related. By looking at the code there is no surprise as to why the error is happening.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-43443.

**Comment by amyblais** [comment]
Closing this as a dup of the Help Wanted issue that was opened.
