### ISSUE TITLE
Mentioning @all couse out of memory with server crash

### ISSUE THREAD

**Issue by broneq** [mattermost/mattermost-server#19986]
#### Summary
When mentioning with @all keyword on channel with 150 (or 209) users server runs out of memory and is crashing.
Eairlier on mattermost/mattermost-docker version 5.31 everything was ok. After upgrade to to new version mattermost/docker v6.3.1 problems started. Yesterday I have upgraded it to 6.3.6, but issue still exists.

Setups is on 8 cores VM with 12GB RAM on SSD disk (own hypervisor). On mattermost server we have 217 active users.

#### Steps to reproduce
type "@all test message" on channel with 150 users.

#### Expected behavior
fix memory leak

#### Observed behavior (that appears unintentional) 
https://gist.github.com/broneq/19a168310d76e85ff259efc7537b827a

#### Possible fixes
don't know

**Comment by amyblais** [comment]
@agnivade Is this related to https://mattermost.atlassian.net/browse/MM-41752 and should this be backported?

**Comment by agnivade** [comment]
Yes it's that issue. It's not a regression from what I can see. So I'll leave it to you if you want to backport, and to which versions.

**Comment by amyblais** [comment]
@broneq For now this has been fixed in v6.6. Do you normally stay on ESRs?

**Comment by broneq** [comment]
> @broneq For now this has been fixed in v6.6. Do you normally stay on ESRs?

Normally Yes, we are doing updates twice in the year. For me it isn't problem to upgrade 6.6 But I think that update should go to ESR

**Comment by amyblais** [comment]
We found that the PR that fixes this was built on top of some refactoring work that went in for Collapsed Reply Threads feature work, and backporting the fix to a previous version is difficult. This bug has been present for a long time (including 5.37 ESR). The fix is available in v6.6 and will be available in the next upcoming ESR as well.

**Comment by amyblais** [comment]
@broneq As mentioned in my previous comment, backporting it was difficult so the fix wasn't backported. The fix is available in v6.6 and later versions This bug has been present for a long time (including 5.37 ESR).

**Comment by broneq** [comment]
Sorry I misunderstood "next upcoming ESR as well". Ok, I need to read about changes in 6.6. Thanks for reply.
