### ISSUE TITLE
There is a problem integrating Zapier

### ISSUE THREAD

**Issue by wuyinhrong** [mattermost/mattermost-server#19999]
#### Summary
There is a problem integrating Zapier

#### Steps to reproduce
Mattermost Server 5.33.3

#### Expected behavior
There is a problem integrating Zapier：
The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
⚠️ Allowing string evaluation comes at the risk of inline script injection.

**Comment by wuyinhrong** [comment]
Supplementary explanation：
When logging into Mattermost in the Zapier interface, an error message (Invalid client id.).

![image](https://user-images.githubusercontent.com/48433729/163504532-7829fdc3-268a-4fa5-83d2-48410c2594ee.png)
![image](https://user-images.githubusercontent.com/48433729/163504564-111e21ae-343b-4c13-be9f-a7196f6eb98a.png)

**Comment by amyblais** [comment]
We have a ticket open here: https://mattermost.atlassian.net/browse/MM-41519.

**Comment by arnalyse** [comment]
hi @amyblais, we've also encountered the problem described in https://mattermost.atlassian.net/browse/MM-41519

In the Jira there is mention of a Zapier integration version 1.9.1 … do you happen to know where to get this version of the zapier integration? 

any help is much appreciated.

**Comment by amyblais** [comment]
I believe @catalintomai and @aaronrothschild can share access with you to that version.

**Comment by aaronrothschild** [comment]
@arnalyse can you send me your email so we can invite you to the new Zapier connector beta?

**Comment by arnalyse** [comment]
@aaronrothschild Thanks so much for reaching out. I've just sent you an email with my contact details.

**Comment by cmeisel** [comment]
How can I get access to the beta? I tried the integration yesterday and encountered this showstopper error and I would like to try the beta too so I can move forward.

**Comment by amyblais** [comment]
> How can I get access to the beta? I tried the integration yesterday and encountered this showstopper error and I would like to try the beta too so I can move forward.

I believe @catalintomai / @mickmister can share access with you to the latest Zapier version.

**Comment by catalintomai** [comment]
> > How can I get access to the beta? I tried the integration yesterday and encountered this showstopper error and I would like to try the beta too so I can move forward.
> 
> I believe @catalintomai / @mickmister can share access with you to the latest Zapier version.

@cmeisel - actually @aaronrothschild can give you access. We are also planning to release the beta publicly soon (like in a week or so) if you can wait.

**Comment by cmeisel** [comment]
I emailed @aaronrothschild yesterday so hopefully, he sees it. If I have to wait, I of course can but I would rather try this earlier than later.

**Comment by mickmister** [comment]
@cmeisel We have released the new version of the Zapier connector today (2 hours ago as of writing). Let us know if you experience any issues. Thank you for using Mattermost!

**Comment by Thj-hash** [comment]
We're currently seeing this on attempting to link Zapier. Unsure of cause, 

![image](https://user-images.githubusercontent.com/33691071/230622167-a5656df7-0d24-4dff-ba4f-0f7daf14f6ae.png)
