### ISSUE TITLE
Profile image persists after user account deletion

### ISSUE THREAD

**Issue by tyrandus** [mattermost/mattermost-server#19996]
#### Summary
When deleting a user account via `mmctl`, the profile image is not being removed. Similar behavior has been found for accounts imported from LDAP (see https://mattermost.atlassian.net/browse/MM-41157), but I assume that it applies to all accounts.

#### Steps to reproduce
The following steps have been performed in a local `mattermost-server` setup with the latest version (v6.6.0). The same result was produced on `mattermost-docker-preview` (v6.6.0).

1. Create a user.
2. Log in with the user account.
3. Set a profile image.
4. Note the user's ID (e.g., using `mmctl --local user search <username>`).
5. Enable account deletion in `config/config.json`.
6. Delete the new user (e.g., using `mmctl --local user delete <email>`).
7. Check the folder `data/users/<userid>/` which still contains `profile.png`.

```shell
$ make run-server
$ mmctl --local sampledata
$ mmctl --local user create --email user@example.com --username test --password mypassword
--- login + image upload
$ mmctl --local user search test
id: eqopgh7c8bdwibwfiso8yqb46y
username: test
nickname: 
position: 
first_name: test
last_name: 
email: user@example.com
auth_service: 
$ ls data/users/eqopgh7c8bdwibwfiso8yqb46y/
profile.png
$ mmctl --local user delete user@example.com
Have you performed a database backup?
  no
> yes
Are you sure you want to delete the users specified? All data will be permanently deleted?
  no
> yes

WARNING: This operation is not reversible.
Deleted user 'test'
```

#### Expected behavior
Normally, and especially with regard to regulations like GDPR, the profile image should be deleted.

#### Observed behavior

The profile image persists:

```
$ mmctl --local user search test
1 error occurred:
        * user test not found
$ ls data/users/eqopgh7c8bdwibwfiso8yqb46y/
profile.png
```

#### Possible fixes
As far as I could track this down, there is simply no statement in `app/user.go#PermanentDeleteUser` (starting in line 1500) deleting the profile image.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-43444.

**Comment by plant99** [comment]
https://forum.mattermost.com/t/solved-how-do-i-delete-a-user/7208/2 from this, it looks like no changes in web-app is needed? Please correct me if I'm wrong.
