### ISSUE TITLE
Signing (public) key missing from Keybase

### ISSUE THREAD

**Issue by uusijani** [mattermost/mattermost-server#20008]
#### Summary
Keybase key for [verifying the tar archive's signature](https://docs.mattermost.com/upgrade/version-archive.html) is missing.

#### Steps to reproduce
1. try to download https://keybase.io/mattermost/key.asc

#### Expected behavior
Get a public key to verify the tar archive's signature.

#### Observed behavior (that appears unintentional) 
404 not found

**Comment by paddy-hack** [comment]
I have been using a slightly different URL (for more than a year) without trouble.  My CI/CD job at 2022-04-16 19:03 now gets
``` console
$ curl https://keybase.io/mattermost/pgp_keys.asc 
SELF-SIGNED PUBLIC KEY NOT FOUND
```

**Comment by paddy-hack** [comment]
The link in the [version archive documentation](https://docs.mattermost.com/upgrade/version-archive.html) to https://keybase.io/mattermost gives

![Screenshot_2022-04-18_09-38-35](https://user-images.githubusercontent.com/6804372/163738311-49477756-bd6a-436e-ac8c-b02e568a2946.png)

**Comment by amyblais** [comment]
I've opened a ticket for our DevOps team to take a look: https://mattermost.atlassian.net/browse/DOPS-945.

**Comment by paddy-hack** [comment]
Thanks.  FYI, it happened again 2022-04-23 19:05 UTC.

**Comment by paddy-hack** [comment]
And on 2022-04-03 19:03 UTC as well as 2022-05-07 19:03 UTC.  
FWIW, I run a weekly CI/CD job that checks for newer versions and builds a slightly customized image if there is one.  This will keep failing until you fix this, one way or another.

BTW, that DOPS-495 issue requires one to log in.  Any reason why this info is not publicly accessible?

**Comment by pfltdv** [comment]
For a quick fix, you may use our public key located at https://deb.packages.mattermost.com/pubkey.gpg.

**Comment by pfltdv** [comment]
Created a PR to update our documentation to use public keys hosted at our infrastructure. https://github.com/mattermost/docs/pull/5651

**Comment by paddy-hack** [comment]
Just run the CI/CD job manually.  Fetching the key worked fine.

**Comment by pfltdv** [comment]
Public keys are updated in keybase.

```
mmm:~> curl https://keybase.io/mattermost/pgp_keys.asc 
-----BEGIN PGP PUBLIC KEY BLOCK-----
...........
..............
...........
mmm:~> 
```
