### ISSUE TITLE
MM 6.6, channel info removed Channel Id

### ISSUE THREAD

**Issue by EricZimmerman** [mattermost/mattermost-server#20018]
#### Summary
Add Channel Id back to Channel info

#### Steps to reproduce
in 6.6, view channel info sidebar. Id is now gone =(

#### Expected behavior
Add it back

#### Observed behavior (that appears unintentional) 
Not sure why it was removed, but we used it for all kinds of other integrations without needing to make API calls.

**Comment by amyblais** [comment]
This is fixed as part of this PR https://github.com/mattermost/mattermost-webapp/pull/10071, which is scheduled for v6.7.
