### ISSUE TITLE
Display time of person being messaged above text box

### ISSUE THREAD

**Issue by userbradley** [mattermost/mattermost-server#20013]
Similar to slack, it would be nice show the time of the person that is being messaged, above the text box - or even next to their name at the top od the Private message window

https://mattermost.uservoice.com/forums/306457-general/suggestions/45045922-display-local-time-of-person-you-re-messaging-abov

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @userbradley.

Thank you for [contributing this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/). We track feature requests on Uservoice, so I'll close this Github issue for now.

If you're interested in implementing, please say so and we'll prioritize the review.
