### ISSUE TITLE
Oauth 2.0 applications vanish after upgrade

### ISSUE THREAD

**Issue by haivala** [mattermost/mattermost-server#20022]
#### Summary
After upgrade to 6.6 (team edition) Oauth 2.0 Applications have vanished and even if they are created again they vanish. (Haven't had time to debug this further)

#### Steps to reproduce
* Upgrade from 6.5 to 6.6
* Oauth application list is empty and they don't work.
* create new
* it works for a while and then it vanishes. (Haven't tested further yet)

#### Expected behavior
Oauth applications should stay in their place

#### Observed behavior (that appears unintentional) 
`{"timestamp":"2022-04-19 0...","level":"error","msg":"An error occurred while finding the OAuth2 Apps.","caller":"web/context.go:105","path":"/api/v4/oauth/apps","request_id":"","ip_addr":"","user_id":"r4mstpyqztgmmkst8boi8dkdmy","method":"GET","err_where":"GetOAuthApps","http_code":500,"err_details":"failed to find OAuthApps: sql: Scan error on column index 11, name \"mattermostappid\": converting NULL to string is unsupported"}` 
and the Oauth 2.0 Application list is empty
![2022-04-19_005430-area](https://user-images.githubusercontent.com/3918267/163883819-a74e269b-9c1c-49aa-9abe-d8110500e6cd.png)

I have Bleve enabled.

**Comment by twnk** [comment]
To Fix if using MySQL:

```sql
UPDATE OAuthApps SET MattermostAppID = '';
```

**Comment by twnk** [comment]
The issue is that the database migration which introduces a new column to the OAuthApps table as part of the Apps 1.0 General Availability release will cause a Null value to be entered into the database for rows that already exist. But Go doesn't play nicely with this unexpected Null https://github.com/mattermost/mattermost-server/commit/7710a2fe3741d42b6eba7f4904a9e653e789f7c3

**Comment by twnk** [comment]
This migration needs to set a non-null value for existing rows; https://github.com/mattermost/mattermost-server/blob/master/db/migrations/mysql/000078_create_oauth_mattermost_app_id.up.sql

alternatively the Go code needs to handle Null but I'm not sure where to point on that

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-43500.

**Comment by haivala** [comment]
Thank you! I tried to run console command `db migrate` but that did not help.

We use Postgres. Can I have quick fix for that as this prevents our users to login easily to our other services?

**Comment by twnk** [comment]
@haivala my suggested quick fix should work on Postgres too, but because I don't use Postgres, I cannot test it for you. 

You will need to log into the database and execute it as an SQL command, `db migrate` won't work as this isn't an existing migration.

**Comment by haivala** [comment]
Just telling what I did after I created the issue.

I can run (and test) the SQL command but I would need it in postgres format.

**Comment by twnk** [comment]
I understand, thanks for clarifying. I believe the statement above: 
`UPDATE OAuthApps SET MattermostAppID = '' WHERE MattermostAppID IS NULL;`

**Comment by twnk** [comment]
I understand, thanks for clarifying. I believe the statement above is valid SQL and relies on no special features of MySQL. So it's also valid PostgreSQL. It will execute, and will replace the NULL values in your Postgres table with empty strings. 

My only caveat is that I have not tested it myself on a Postgres instance, and I couldn't tell you whether this alone is sufficient to completely fix the issue or whether additional steps are necessary. I have no reason to think that anything else is needed, I just can't guarantee it myself :) 

If you try to run

`UPDATE OAuthApps SET MattermostAppID = '' WHERE MattermostAppID IS NULL;` 

do you get any errors?

**Comment by haivala** [comment]
```
UPDATE OAuthApps SET MattermostAppID = '' WHERE MattermostAppID IS NULL;
UPDATE 3
```

**Comment by haivala** [comment]
And the list and the apps work now. I'm I going to face problems from next db migration?

**Comment by twnk** [comment]
I don't expect us to have issues next migration as the database table is in a valid state, `''` (the empty string) is what Mattermost itself sets that column to when you create a new OAuth App on the latest version.

**Comment by haivala** [comment]
ok! thank you for your help!
