### ISSUE TITLE
Permalinks to private messages can add system administrators to other teams without further confirmation

### ISSUE THREAD

**Issue by 3c7** [mattermost/mattermost-server#20032]
#### Summary
Permalinks in private chats always include the current team used to access the private (1:1) chat. When sharing a permalink to a specific message while viewing the chat from another team, which does not include the other participant and if the participant is a system administrator, the other participant joints the team without further confirmation. This was tested with version `6.4.2`.

#### Steps to reproduce
- Two teams, other participant uses a system administrator account and is only member of one of the teams
- Copy a permalink from a private conversation with said participant out of the other team
- If the participant clicks the link, the account will be added to the other team silently

#### Expected behavior
Permalinks to messages should not automatically add system administrators to other teams. This is not a security issue, as admins can join other teams, but it should need a confirmation. In the current state this happens silently for the system administrator.

#### Possible fixes
A confirmation modal or something similar would prevent accidentally joining other teams.

**Comment by 3c7** [comment]
Actually, I don't know if this is related to the server or https://github.com/mattermost/mattermost-webapp.

**Comment by amyblais** [comment]
I tested this and I was given a prompt to confirm if I want to join the private channel (see screenshot).

@BenCookie95 @ashishbhate  Is there a setting that admins can configure to get these prompts?

<img width="596" alt="Screenshot at Apr 20 10-52-50" src="https://user-images.githubusercontent.com/29708087/164259540-dcc09c83-2aa4-4c24-9f61-4b5e9010e267.png">

**Comment by 3c7** [comment]
I don't know if this makes a difference, but this was not about joining a private channel, but "silently" (for the user clicking the link) joining a team through clicking on a link that contains the ID to a message of a channel I'm already part of (in my case it was a direct conversation with another user), if I'm using an administrative account.

**Comment by amyblais** [comment]
Got it, opened a ticket: https://mattermost.atlassian.net/browse/MM-43591.

**Comment by ashishbhate** [comment]
I'm not sure if this is a bug, I think this is how its intended to work (i.e. automatic team join). Maybe @esethna could clarify.

**Comment by 3c7** [comment]
> I'm not sure if this is a bug, I think this is how its intended to work (i.e. automatic team join). Maybe @esethna could clarify.

Well, if the permalink points to a chat room in the specific team, this is an expected behaviour. However, this is about a permalink to a message within a private conversation between two participants in different teams, not a private room within a team. So permalinks created by both participants of the conversation use different "team parts" in the URLs.

**Comment by esethna** [comment]
Makes sense, agree with what's been mentioned and the ticket has been opened. Thanks for the report @3c7

**Comment by esethna** [comment]
Closing to follow progress in the jira tix
