### ISSUE TITLE
SqlSystemStore attempts to UPDATE without WHERE

### ISSUE THREAD

**Issue by dodgex** [mattermost/mattermost-server#20048]
#### Summary
It seems that the SqlSystemStore attempts to do an `UPDATE` without a `WHERE` clause.

#### Steps to reproduce
I think install any current version of MM and let it do an update in `systems` table. (in our case the security update check caused the update)

We currently have v6.5 in use, but the problematic code is still found in master.

#### Expected behavior
Update the value with a where statement and succeed.

#### Observed behavior (that appears unintentional) 
The update is missing the WHERE clause and is (luckily) causing a PG error due to the unique constriant. without that constraint ALL rows would have been overridden/updated.

> FEHLER:  doppelter Schlüsselwert verletzt Unique-Constraint »systems_pkey«
> DETAIL:  Schlüssel »(name)=(LastSecurityTime)« existiert bereits.
> ANWEISUNG:  UPDATE Systems SET Name=$1, Value=$2

#### Possible fixes
Add `WHERE  Name=:Name`  in https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/system_store.go#L81

**Comment by dodgex** [comment]
Looks like [this commit](https://github.com/mattermost/mattermost-server/commit/e1eb0a0cf3a93714d347630b740835d2c037426f) by @YairFernando67 introduced the bug

**Comment by dodgex** [comment]
Also tagging @agnivade and @isacikgoz who have done the review of the related PR https://github.com/mattermost/mattermost-server/pull/18893

**Comment by agnivade** [comment]
Oops great catch @dodgex !

**Comment by amyblais** [comment]
Opened a ticket https://mattermost.atlassian.net/browse/MM-43653.
