### ISSUE TITLE
Webapp die if you leave chanel in "show only unread" mode

### ISSUE THREAD

**Issue by vovsemenv** [mattermost/mattermost-server#20065]
#### Steps to reproduce
1. Select "Filter by unread"
2. Leave any chanel

Page become white and app die.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
<img width="1280" alt="изображение" src="https://user-images.githubusercontent.com/20096510/165165917-073a76be-3bf7-4cd8-befe-3ac163989c1d.png">

<img width="1278" alt="изображение" src="https://user-images.githubusercontent.com/20096510/165165970-221c8de8-8bff-4818-a660-68e887a02c6f.png">

**Comment by vovsemenv** [comment]
I can take ticket

**Comment by sinansonmez** [comment]
hey @vovsemenv how is this going? If you are not working on this I can try my chance

**Comment by vovsemenv** [comment]
@sinansonmez Totally forgot about this. We have mostly completed PR for this, i'l check it again today

**Comment by sinansonmez** [comment]
Thanks for the update. However in the linked PR, it seems like your fixing another issue and not this one

**Comment by vovsemenv** [comment]
@sinansonmez ughh, sorry 😬 You can take it if you want.

**Comment by sinansonmez** [comment]
@amyblais could you please assign this to me
