### ISSUE TITLE
Websockets: not connecting in local machine while developing

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [mattermost/mattermost-server#20083]
#### Summary
Websockets are not connecting in the local machine(localhost:< port >) while developing. The same code once deployed to the server, it's showing all the events-related messages.

In localhost:
<img width="784" alt="Screenshot 2022-04-27 at 10 45 56 PM" src="https://user-images.githubusercontent.com/9896335/165583013-5038e861-6db0-4906-bfbd-63e23ebdb03b.png">

On server:
<img width="1048" alt="Screenshot 2022-04-27 at 10 46 09 PM" src="https://user-images.githubusercontent.com/9896335/165583046-30e5dbc5-7a56-4473-af17-fcb21b4c5cc9.png">

#### Steps to reproduce
Try to connect to web sockets from the local machine (localhost:< port >)

#### Expected behavior
Websocket connection should work even from the local machine

#### Observed behavior (that appears unintentional) 
Events are not showing/generating in the local machine

#### Possible fixes
NA

**Comment by rajeshwarpatlolla** [comment]
@amyblais any update on this?

**Comment by BenCookie95** [comment]
@rajeshwarpatlolla Do you have anything in your server logs? Also, are you running your local on windows, linux or mac?

**Comment by Willyfrog** [comment]
apart from what @BenCookie95 asked:

is the siteURL the same for both? or are these different instances?

do you have a firewall in your local machine, does it work if you **temporarily** disable it?

**Comment by BenCookie95** [comment]
@sanju2010 Are you using mattermost-webapp to connect to the server or do you have your own custom frontend solution? What are the request headers that are sent when trying to create a websocket connection?

Can you try make a websocket connection in postman using the following:
ws://localhost:3000/api/v4/websocket?connection_id=&sequence_number=0

Headers:
```
Pragma:no-cache
Accept-Language:en-US,en;q=0.9
Upgrade:websocket
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Cache-Control:no-cache
Cookie:MMAUTHTOKEN=<MMAUTHTOKEN-value>; MMUSERID=<MMUSERID-value>; MMCSRF=<MMCSRF-value>
Connection:Upgrade
Sec-WebSocket-Version:13
```

Just make sure to update your cookie values from what I have pasted

**Comment by rajeshwarpatlolla** [comment]
Thanks for the response @BenCookie95. We are getting Cookie:MMAUTHTOKEN  and MMUSERID cookies, but we are not getting MMCSRF cookie. How do we get MMCSRF cookie?

**Comment by sunilkolluru** [comment]
@BenCookie95 @amyblais 

guys, would greatly appreciate any help on this issue. We are completely stuck with this issue and don't know how to resolve it. Please let us know if you need any further information to help resolve the issue.

**Comment by BenCookie95** [comment]
@rajeshwarpatlolla @sunilkolluru It's hard to diagnose the exact issue without seeing your code but I can try give some suggestions.

Are you able to hit API endpoints from postman on your local environment?

Can you provide the exact headers you're sending for a GET request after you have completed your login?

What are you using for your frontend local development environment? It could be a webpack config issue, have you looked at our configs in mattermost-webapp? https://github.com/mattermost/mattermost-webapp/blob/master/webpack.config.js#L440

**Comment by rajeshwarpatlolla** [comment]
Thanks for the response @BenCookie95 for your response.

Please check the below headers for GET request after login.
<img width="1413" alt="Screenshot 2022-07-13 at 10 15 32 PM" src="https://user-images.githubusercontent.com/9896335/178787358-805df3c4-c0a5-4540-a407-a6af8555b10c.png">

We are not using any separate config for webpack, as it's a react app that was created with React CLI itself.

**Comment by BenCookie95** [comment]
> Thanks for the response @BenCookie95 for your response.
> 
> Please check the below headers for GET request after login. <img alt="Screenshot 2022-07-13 at 10 15 32 PM" width="1413" src="https://user-images.githubusercontent.com/9896335/178787358-805df3c4-c0a5-4540-a407-a6af8555b10c.png">
> 
> We are not using any separate config for webpack, as it's a react app that was created with React CLI itself.

Well we have some exceptions in our config when working on a local environment, if you're missing those it could be the cause of your websocket connection issues.

Also it might be a good idea to bring your issue to our community server, this channel could be of help https://community.mattermost.com/core/channels/peer-to-peer-help

**Comment by rajeshwarpatlolla** [comment]
@BenCookie95 the headers I sent above are from the hosted application, it is not in the local development. We have also tried to find some solutions in mattemost peer-to-peer help,  but we didn't get an answer which can fix our issue.

**Comment by BenCookie95** [comment]
@rajeshwarpatlolla I just need to clarify a few things from earlier replies

1. Earlier you said `We are using our own server APIs for login. Our API is getting two cookies, but it’s not getting the MMCSRF token.`. I'm not really sure what you mean here? Do you mean to say you're connecting your local frontend to your hosted server backend?

**Comment by rajeshwarpatlolla** [comment]
@BenCookie95 we have issues both on the local environment (localhost:3000) and also after deploying the frontend code to a secure domain(dev.xxxx.com) as well.
The server is always hosted on our domain(dev.xxxx.com/api) itself, even when we are testing the frontend local.

Now we have fixed the CSRF cookie issue, but still, the POST, PUT, and PATCH APIs are not working and also WebSockets are not connecting.

**Comment by BenCookie95** [comment]
@rajeshwarpatlolla Thanks for that information

Websockets are working for your frontend code on dev.xxxx.com right?

POST, PUT, and PATCH APIs might be broken because you are missing this header: `X-CSRF-Token`. It uses the same value as `MMCSRF`

**Comment by rajeshwarpatlolla** [comment]
@BenCookie95 WebSockets are not working on both local and also on dev.xxxx.com, same with POST, PUT, and PATCH APIs.

I added **x-csrf-token** token now, POST, PUT, and PATCH APIs are working fine. Thanks for the info about the header.
Websockets are still not connecting. Please check below screenshot for the headers. Let me know if we are missing anything.

<img width="1400" alt="Screenshot 2022-07-14 at 10 41 32 AM" src="https://user-images.githubusercontent.com/9896335/178904118-32f3ec2c-d0df-41ef-97b2-2147bc8ae594.png">

**Comment by rajeshwarpatlolla** [comment]
Thanks @BenCookie95 for all your help. We are able to fix the issue with web sockets too.

**Comment by BenCookie95** [comment]
@rajeshwarpatlolla No problem, would you be able to share what the fix was for people looking at this in the future?
