### ISSUE TITLE
Bug with Date Picker CSS

### ISSUE THREAD

**Issue by BeastBreacher** [mattermost/mattermost-server#20100]
#### Summary
In deckstop app see a bug with date picker in notification wrapper. Picker icon moves a side when you hover it by mouse cursor. But in webapp all works normally.

![Безымянный](https://user-images.githubusercontent.com/104623979/165923852-b6f9acad-0e43-4486-94cc-61602d376f60.png)

#### Steps to reproduce
 - MM version 6.4.1
 - Go to profile
 - "Do not disturbed" status and choose "custom"
 - Focus the data picker

#### Expected behavior
All hover up icons work normally

#### Observed behavior (that appears unintentional) 
Hover up move to a side and lookes broken

**Comment by MANISHPANDEY06** [comment]
Hello all,

I want to resolve this issue *; please assign this issue to me
@amyblais
