### ISSUE TITLE
Code / Architecture walk through for new contributors.

### ISSUE THREAD

**Issue by vineelyalamarthy** [mattermost/mattermost-server#20112]
Can some one help code walkthrough. Are there any such recorded videos?

**Comment by amyblais** [comment]
Hi @vineelyalamarthy!

For new contributors, please see our [Developer's Guide here](https://developers.mattermost.com/contribute/getting-started/).

We also have [videos on Youtube here](https://www.youtube.com/results?search_query=mattermost+code+walkthrough) that may help you.

Please also come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team!
