### ISSUE TITLE
by mouse hover on the link, preview model blink.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#20115]
#### Summary
by mouse hover on the link, preview model blink.

#### Steps to reproduce
1) Click on any link From Mattermost and User will redirect on new tab.
2) Come back on the same page.
issue :- 3) now mouse hover on the same link that you clicked on step 1 and the issue will regenerate.

#### Expected behavior
The preview model Should not blink.

#### Observed behavior (that appears unintentional) 
https://user-images.githubusercontent.com/89907719/166212605-bee856a3-b2e8-4320-ae9c-ba9b4ffe4c0c.mov

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-43906.
