### ISSUE TITLE
Remove metadata from photos, shared files

### ISSUE THREAD

**Issue by cyberflaneuse** [mattermost/mattermost-server#20126]
It would be a great privacy feature to have the possibility to remove EXIF metadata from photos, videos and other types of files one shares on Mattermost.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @cyberflaneuse.  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
