### ISSUE TITLE
when user edit the search then auto-suggestion is hide behind the model 

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#20124]
#### Summary
when user edit the search then auto-suggestion is hide behind the model 

#### Steps to reproduce
1) Search like this ex "from:dipak-demansol-qa in:qa-contributors " .
2) now remove the current user name and add different name.
issue :- 3) when you add new user name then you can see that user name auto-suggestion is hide behind the model.  

#### Expected behavior
User Should able to see the list properly when hes editing something. 

#### Observed behavior (that appears unintentional) 

https://user-images.githubusercontent.com/89907719/166428824-77616e1a-3a67-4d41-bb51-ecb9171db3d7.mov

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-43933.
