### ISSUE TITLE
User mentions in posts remain after user is deleted

### ISSUE THREAD

**Issue by tyrandus** [mattermost/mattermost-server#20135]
#### Summary
When deleting a user account, posts directly mentioning this user (e.g., `hey, @user!`) stay the same. Thus, the username is still visible (and the mention may be falsely referring to another user signing up later with the same username). 

#### Steps to reproduce
The following steps have been performed in a local `mattermost-server` setup with the latest version (v6.6.0).

1. Create two user accounts.
2. Mention user A in a message from user B. (e.g., `Hi, @aaa!`)
3. Delete user A.

#### Expected behavior

Naively, I would assume that the user mention would have been anonymized, first of all to remove the personal connection to the deleted user, but also to avoid the above-mentioned reconnection problem.

#### Observed behavior

The mention stays the same.

#### Possible fixes

A rather easy fix for this would be to replace all direct mentions with a default mention like `@deletedUser`. This tag is not used as all user names are lower-case only. Also, it is generally understandable, although a more advanced solution could even make this user tag translatable. An example implementation has been proposed here: https://github.com/mattermost/mattermost-server/pull/20136.

**Comment by agnivade** [comment]
@laneycs @esethna - Any thoughts on this?

**Comment by esethna** [comment]
Thanks for bringing this up @tyrandus. I will let @laneycs answer here since this is her area of ownership. 

My gut reaction from the Channels perspective it that it could still be useful to know who was mentioned in past messages, even if the user in question was deleted. Another alternative would be to convert the `@aaa` to plain text (not clickable). Will defer to @laneycs

**Comment by laneycs** [comment]
Yeah, good call @esethna @agnivade. Let's go with the plain text (not clickable) option.

**Comment by tyrandus** [comment]
Thank you for the feedback. First, I assume that the plaintext solution is what is already in place (user accounts are deleted, so their mentions become unclickable). The problem of another user signing up with the same name, thereby reviving old mentions, is still there, though. 

And second, according to GDPR, service providers in Europe have to delete personally identifiable information once “the personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed” (§ 17/1a GDPR, unless a different bullet point in the article applies). Arguably, this exception does not apply in the majority of cases. At the same time, little is lost if the deleted user is just called “deletedUser.” The context information remains untouched – and can sometimes tell way more about a person (cf. this [feature request](https://forum.mattermost.com/t/feature-request-anonymize-posts-on-user-deletion/13367)). In this sense, the replacement of user mentions is the minimum solution one should, from my perspective, strive for to be GDPR-compliant.

**Comment by mkraft** [comment]
Opened https://mattermost.atlassian.net/browse/MM-45185.

**Comment by claudio-salvio** [comment]
Hello

I do not agree in the least with this proposal.
Please allow this to be configurable.
We are not all caught by the excesses of GDPR. 

Those of us who have experienced this type of situation on other communication platforms know how bizarre it is to read historical conversations full of @deletedusers interacting with other @deletedusers in absolutely confusing ways.
It is useful to remember that in many organizations conversations are full of knowledge and it is important to identify the interlocutors.

I consider that the minimum necessary to maintain some consistency in conversations is to replace the original name with a specific but anonymizing one.
For example:
@johnfisher -> @deletedeuserrandomnumber1.
@maryjones -> @deleteduserrandomnumber2
where @deletedeuserrandomnumber1 is used to replace all mentions to @johnfisher and @deleteduserrandomnumber2 all mentions to @maryjones

Best regards,
Claudio Salvio

**Comment by mkraft** [comment]
@claudio-salvio Thank you for your feedback about wanting this to be configurable or at minimum differentiated via a unique identifier per deleted user. I'll ensure that our product team is aware of your thoughts.

**Comment by mkraft** [comment]
@claudio-salvio Please see https://mattermost.atlassian.net/browse/MM-45185?focusedCommentId=129804 from our product manager.

**Comment by claudio-salvio** [comment]
Hello @mkraft 

Thanks for your reply and for the link to the corresponding [PR](https://mattermost.atlassian.net/browse/MM-45185?focusedCommentId=129804).
I am glad to hear that you are aware of these inconveniences.

Best regards,
Claudio Salvio
