### ISSUE TITLE
Editing comment with preformatted text is not possible

### ISSUE THREAD

**Issue by razilein** [mattermost/mattermost-server#20149]
#### Summary
We updated Mattermost from 6.5.0 to 6.6.1.

After the update, comments with preformatted text can not be edited, because after pressing ENTER to send the comment, only a linebreak is inserted. Even with CTRL + ENTER a linebreak would appear.
It is impossible to edit such comments. The editing can only be canceled with ESC.

#### Steps to reproduce
- create a comment with preformatted text (3 backtics)
- press arrow up to edit the text
- press ENTER after editing (the comment won't be saved)

#### Expected behavior
ENTER should save the comment
CTRL + ENTER should add a new linebreak

#### Observed behavior (that appears unintentional) 
![editing-formatted-text.gif](https://user-images.githubusercontent.com/13280522/167124284-17f50d72-083e-4a98-83af-abdb828bb743.gif)

**Comment by amyblais** [comment]
We have a ticket open: https://mattermost.atlassian.net/browse/MM-43349. It seems to happen at least when **Send messages on cmd+enter** setting is set to **On only for code blocks**.
