### ISSUE TITLE
The popup on hovered message blocks selecting certain part of that message

### ISSUE THREAD

**Issue by devtud** [mattermost/mattermost-server#20187]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. If you have having issues, please send us a message in the [Peer-to-peer Help](https://community-daily.mattermost.com/core/channels/peer-to-peer-help) or the [Developers: Desktop App](https://community-daily.mattermost.com/core/channels/desktop-app) channels on the Mattermost Community server
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

The floating action bar displayed when a message is hovered blocks word/words selection - making the copying of the text annoying and time consuming.

**Steps to reproduce**

Send or receive a message having at least 1 full row. Try to select/copy a word from top-right side of this message.

I noticed this behavior on any desktop app version on Windows and Linux.

**Expected behavior**

When I place the cursor over any word in the message I can easily select it.

**Observed behavior**

When I place the cursor over the words at the top-right side of the message, a popup covers parts of the message blocking the selection of the covered text.

When the message is not hovered by cursor:

![no hover](https://user-images.githubusercontent.com/6808024/167904416-3475f5cd-3d35-4bcf-9e98-fa74dea9bb4b.png)

When the message has cursor over it. Some words on the first row are covered so I cannot select them (eg "of passages of Lorem"):

![hover](https://user-images.githubusercontent.com/6808024/167904447-9948e50e-db96-443f-a938-3090ebf6e009.png)

**Possible fixes**

Display the popup outside of the hovered message (above for example).

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-44128.
