### ISSUE TITLE
"Unlock increased productivity" spam

### ISSUE THREAD

**Issue by uusijani** [mattermost/mattermost-server#20210]
#### Summary
I'm getting these unrequested emails from my self-hosted instance, with no apparent way to disable them. This is bad, bad behavior.

#### Steps to reproduce
Host an instance running Mattermost 6.6.1. Leave it "collecting a bit of dust".

#### Expected behavior
Not to get spammed with unwanted emails.

#### Observed behavior (that appears unintentional) 
![Screenshot from 2022-05-15 15-35-12](https://user-images.githubusercontent.com/4244772/168473273-90e7b2e4-b368-49eb-99be-0e8fb2cb482a.png)

**Comment by amyblais** [comment]
With the latest 6.7.0 release (released today), these emails can now be disabled via a config setting https://docs.mattermost.com/configure/configuration-settings.html?highlight=config#disable-inactive-server-email-notifications.
