### ISSUE TITLE
Database query errors on startup

### ISSUE THREAD

**Issue by greatdragon6cloki** [mattermost/mattermost-server#20222]
When I built the most important database after upgrading the Mattermost version to 6.3

I have a problem like this, I don't know why it happens

![image](https://user-images.githubusercontent.com/105716752/168797480-ee744e93-8f4a-4ed8-b960-f2ccf235c836.png)

Do you have any solutions for this issue

Thank you and Best regards !

**Comment by amyblais** [comment]
@greatdragon6cloki Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or other community members will likely be able to help with this.

**Comment by amyblais** [comment]
@greatdragon6cloki Did you have a chance to post to the troubleshooting channel or do you still need help with this?
