### ISSUE TITLE
mmctl errors fails to find local socket

### ISSUE THREAD

**Issue by greatdragon6cloki** [mattermost/mattermost-server#20221]
There are some problems and the mattermost system is not working 

> Error: socket file "/var/tmp/mattermost_local.socket" doesn't exists, please check the server configuration for local mode

The reason is that I execute the **mmctl command** with **local mode** before the **mattermost_local.socket** file is created.

As you can see, the socket file is generated at "/var/tmp/mattermost_local.socket" by default! 

![image](https://user-images.githubusercontent.com/105716752/168794227-34a39bd8-6a9f-4396-b25a-18f0e42fc820.png)

Do you have any solutions for this issue 

Or how can I create a new socket file instead of making it created by default

Thank you and Best regards !

**Comment by amyblais** [comment]
@greatdragon6cloki What Mattermost server version are you on?

**Comment by greatdragon6cloki** [comment]
@amyblais my Mattermost server version is 6.3.8 ( I just upgraded from 5.37.9 )

**Comment by amyblais** [comment]
@isacikgoz Would you be able to help take a look at this issue?

**Comment by isacikgoz** [comment]
@greatdragon6cloki There are two settings in `ServiceSettings` as:
```json
{
        "EnableLocalMode": true,
        "LocalModeSocketLocation": "/var/tmp/mattermost_local.socket"
}
```
Can you check if local mode is enabled and the socket location is a valid path on **server** settings? If so, it should be able to run commands in local mode. Keep in mind that if you change the socket path from settings, you need to specify the socket path from mmctl side as well (via env var or flags).

Another things is that, if you updated the config while the server is running, you will need to restart the server to make local mode work.

**Comment by p4ulb** [comment]
i have the same issue and i have created the file and still cannot fix it.
i am trying to add users to the server. 

" Error: invalid file mode for file "/var/tmp/mattermost_local.socket", it must be a socket with 0600 permissions "

**Comment by davidus05** [comment]
Fixed it by setting `EnableLocalMode` to true in `config.json`. Sadly it is mentioned nowhere that this error messages relates to that.
https://docs.mattermost.com/configure/configuration-settings.html#enable-local-mode

**Comment by amyblais** [comment]
@davidus05 Would you like to edit the documentation, or open a docs Issue at https://github.com/mattermost/docs/issues for our team to update the documentation?

**Comment by amyblais** [comment]
Opened a docs issue at: https://github.com/mattermost/docs/issues/5833.
