### ISSUE TITLE
Unicode hardcoded characters in config.json

### ISSUE THREAD

**Issue by petersamokhin** [mattermost/mattermost-server#20248]
Hello! The default `config.json` file coming with the mattermost (including the docker container) contains the below:
```json
{
  // ...
  "SqlSettings": {
    "DriverName": "postgres",
    "DataSource": "postgres://mmuser:mostest@localhost/mattermost_test?sslmode=disable\u0026connect_timeout=10\u0026binary_parameters=yes",
    // ...
  }
  // ...
}
```

Is there a reason why `\u0026` is not `&` here?
Our scripts do some manipulation with the config before the deployment, and it becomes `&` anyway, and it doesn't look possible to keep the Unicode notation hardcoded. If some tools do not support `&`, must it be a bug for them then?
Should it be kept like this or will `&` unexpectedly break anything?

**Comment by amyblais** [comment]
@petersamokhin Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or other community members will likely be able to help with this.

**Comment by amyblais** [comment]
@petersamokhin Did you have a chance to post to the troubleshooting channel or do you still need help with this?

**Comment by amyblais** [comment]
Closing this for now. Please let me know if you'd prefer re-opening this, or if you've had a chance to ask about this either at [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/. Our community and developers will likely be able to help with this.
