### ISSUE TITLE
Desktop App (Mac App Store): Boards shows error on initial launch

### ISSUE THREAD

**Issue by chenilim** [mattermost/mattermost-server#20251]
#### Summary
Opening the Boards tab after install shows a "Not a valid workspace" error

#### Steps to reproduce
1. Download the desktop app [from the Mac App Store](https://apps.apple.com/us/app/mattermost-desktop/id1614666244?mt=12)
2. Log into your server (I logged into https://community-daily.mattermost.com, using OneLogin)
3. Click on the Boards tab
4. See an error:
<img width="1577" alt="Screen Shot 2022-05-19 at 9 53 24 AM" src="https://user-images.githubusercontent.com/46905241/169356082-080e043a-a5d8-4598-bcb8-8e8cd7e69795.png">

#### Expected behavior
No error, Boards opens.

#### Observed behavior (that appears unintentional) 
Worse, it's not obvious how to correct this.
1. Clicking on the "Back to Home" buttons opens the Channels tab
2. Re-selecting the Boards tab now shows the Channels UI in it
3. Refreshing (Cmd+Shift+R) also did not fix the issue

Video:
https://user-images.githubusercontent.com/46905241/169356914-8fb3a58b-21a7-40e8-af8d-591829bdabeb.mov

**Comment by chenilim** [comment]
Also tracked by this issue in the Boards repo: https://github.com/mattermost/focalboard/issues/3068

**Comment by amyblais** [comment]
If this ends up not being a Focalboard specific issue, feel free to re-open this at https://github.com/mattermost/desktop/issues.
