### ISSUE TITLE
Credential issue when using mmctl cli Mattermost 6.3.8

### ISSUE THREAD

**Issue by greatdragon6cloki** [mattermost/mattermost-server#20269]
**Summary**
Credential issues with Mattermost 6.3.8:  

Because in Mattermost 5.37.9 we use Mattermost cli and it does not require authentication so when we update to Mattermost 6.3.8 we change Mattermost cli to mmctl cli so we need to login! But the main point is we don't have any account to login my mattermost server (For Example: http://10.116.144.52:83/mattermost/ (We use this Url before)) and I really don't know how to create a new account in my docker file when "docker-compose up" 

**Expected behavior**
We may have credentials or how to create  to login 

**Observed behavior**
After upgrading to Mattermost 6.3.8 I noticed that to create new user with mmctl command we need to use local mode or login first but all we want is to have credential to login first

However, we don't know how to create a new account or the default account to log in

How can I fix this issue? And did anyone encounter similar issues? 

![image](https://user-images.githubusercontent.com/105716752/169950270-fe67447b-5530-4bdd-9b0d-86b06cdd4a6e.png)

![image](https://user-images.githubusercontent.com/105716752/169947445-129453bd-8094-4705-80f2-7ece52c6f682.png)

![image](https://user-images.githubusercontent.com/105716752/169947533-85f53ab2-25aa-4a83-aa65-8ff4e4879b85.png)

**Comment by amyblais** [comment]
@greatdragon6cloki Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or other community members will likely be able to help with this.

**Comment by amyblais** [comment]
@isacikgoz Can you help take a look at this?

**Comment by gc-ss** [comment]
@greatdragon6cloki The file pointed to by `--config` is meant to override the default mmctl's config at `mmctl/config` - it SHOULD NOT be mattermost's own config at `/mattermost/config/config.json` - this could render your mattermost server unusable (especially after a restart)

Here's what you need to do:

- locate an admin user for your mattermost server. let's say it's `mmadmin`
- run `mmctl auth login https://mattermost_server --name default_connection --username mmadmin`
- this will ask for you for the password
- after you enter that, verify with `mmctl auth list`

I'm happy to help with a hands on session over zoom as well.

**Comment by alexisfrjp** [comment]
No luck.

```
$ mmctl auth login http://localhost:8065 --name default_connection --username admin
Password: 
Error: mkdir /mattermost/.config: read-only file system


$ cat /mattermost/.config 
cat: /mattermost/.config: No such file or directory
```
