### ISSUE TITLE
Non-square custom emoji overflow div when set as status

### ISSUE THREAD

**Issue by ReagentX** [mattermost/mattermost-server#20264]
#### Summary
Non-square custom emoji overflow the `statusSuggestion__icon` div when set as the current status symbol.

#### Steps to reproduce
1: Add a non-square emoji
![pig_boss](https://user-images.githubusercontent.com/1920666/169829876-179b7edd-98f7-4a10-a340-c7d0a99a7624.png)
2: Set that emoji as your status

#### Expected behavior
The image displays with padding, like it does for messages and reactions:
<img width="64" alt="image" src="https://user-images.githubusercontent.com/1920666/169830149-eb527896-81d5-4011-be61-a8aaea160812.png">

#### Observed behavior (that appears unintentional) 
The emoji image is cut off:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/1920666/169829843-892627b2-c931-4806-99d9-510749e71313.png">

#### Possible solutions:
Removing the `background-size` property resolves the issue:
<img width="188" alt="image" src="https://user-images.githubusercontent.com/1920666/169830751-09654957-ee7f-4663-ae77-4b5b9e062fb3.png">
<img width="69" alt="image" src="https://user-images.githubusercontent.com/1920666/169830803-0f9fc3c5-5fa4-4275-b0cd-787125c88eb6.png">

**Comment by amyblais** [comment]
@ReagentX What Mattermost server version are you on?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-44513.

**Comment by Ballista01** [comment]
I can work on this.
