### ISSUE TITLE
Mattermost still tries to verify certificate SAN for outgoing connections

### ISSUE THREAD

**Issue by braunsonm** [mattermost/mattermost-server#20313]
#### Summary
Mattermost will still try to verify the certificate SAN for outgoing connections with "Enable Insecure Outgoing Connections".

#### Steps to reproduce
1. Create a self signed cert for your S3 storage without a SAN
2. Set "Enable Insecure Outgoing Connections" to true
3. Try to use that S3 storage as your file store (ex: upload a profile picture)

#### Expected behavior
The S3 storage should work.

#### Observed behavior (that appears unintentional) 
Error log:
```
Get <url>: x509: certificate is not valid for any names, but wanted to match <url>
```

#### Possible fixes
Disable SAN checking when this option is enabled.

**Comment by amyblais** [comment]
@braunsonm 
1. What Mattermost server version are you on?
2. What OS are you using?
3. Are there any additional Mattermost server logs?

**Comment by braunsonm** [comment]
@amyblais good questions. Sorry for not including them.

- Mattermost 6.7.0
- OS is Ubuntu but deployed in Kubernetes using the Mattermost Operator
- No additional relevant logs.

**Comment by amyblais** [comment]
Thanks, opened: https://mattermost.atlassian.net/browse/MM-44667.

**Comment by agnivade** [comment]
Hey @braunsonm - The insecure check was only being applied for other requests made by our HTTP client and wasn't applied for the s3 client. Are you interested in submitting a fix? Let me know and I can guide you.

**Comment by agnivade** [comment]
Sure, I'll create a help wanted issue.

**Comment by agnivade** [comment]
I created https://github.com/mattermost/mattermost-server/issues/20356, so I'll close this one out. That has more details on what needs to be done.
