### ISSUE TITLE
mmctl version v6.4.1 packaged with mattermost 7.0.0

### ISSUE THREAD

**Issue by gc-ss** [mattermost/mattermost-server#20324]
#### Summary
mmctl version v6.4.1 packaged with mattermost 7.0.0 causing inability to use `mmctl`

#### Steps to reproduce
`mmctl config set EmailSettings.FeedbackEmail "email@dom.com"`

#### Expected behavior
`mmctl config set` is successful

#### Observed behavior (that appears unintentional) 
`Error: could not check version mismatch: Cannot parse version range 7.0.0.master.88fa7b74a829f62672a1cc6825f23dbe.false: Invalid Semantic Version`

#### Possible fixes
Package the proper mmctl version

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-44688.

**Comment by gc-ss** [comment]
This is an issue with `mattermost/mattermost-team-edition:7.0.0-rc1` too (previous tag was `master`)

```
~ $ mmctl version
mmctl:
Version:        v6.4.1
GitCommit:      d09913b80c4c9991adb602e896137a1d65238fe9
GitTreeState:   "clean"
BuildDate:      2022-05-26T16:47:35Z
GoVersion:      go1.17
Compiler:       gc
Platform:       linux/amd64
~ $ mattermost version
Version: 7.0.0
Build Number: 7.0.0-rc1
Build Date: Fri May 27 13:42:41 UTC 2022
Build Hash: 8a50c1c2b23298ff9d30f919a3ffec8b8fb2b511
Build Enterprise Ready: false
```

**Comment by gc-ss** [comment]
How's the `master` tag image built?

- Off the `master` branch?
- So anytime code is merged into the `master` branch, a new `master` image will be built?

**Comment by mailo84** [comment]
same problem with 7.1.1

**Comment by amyblais** [comment]
We are working on a 7.1.2 to fix it.
