### ISSUE TITLE
self-hosted push proxy returns "mismatched sender id"

### ISSUE THREAD

**Issue by footsim** [mattermost/mattermost-server#20329]
I installed self-hosted push proxy service for MM using this guide https://developers.mattermost.com/contribute/mobile/push-notifications/service
But tests fails with following error:
`Android response failure: &{7289498074377076443 0 1 0 [{  mismatched sender id}] [] 0 <nil>} type=android_rn`
I suppose that I should insert my FCM Sender ID in the push proxy's config. But I didn't find such reference.
Could you provide detailed information?

**Comment by amyblais** [comment]
@footsim Would you be open to posting this troubleshooting question either on our [Peer-to-peer Help channel here](https://community.mattermost.com/core/channels/peer-to-peer-help) or on our [troubleshooting forum here](https://forum.mattermost.com/)? Someone on our community or one of our devs will likely be able to help with this.

**Comment by footsim** [comment]
@amyblais Hi, I've found similar questions on forum:
https://forum.mattermost.com/t/notification-server-fails/9779
https://forum.mattermost.com/t/mattermost-push-proxy-is-not-working/10350
But they're still not resolved. Maybe this issue will be more productive on the way of finding solution?

**Comment by footsim** [comment]
@amyblais Sorry, I've found my mistake, I haven't yet my own app with my FCM Sender ID. https://developers.mattermost.com/contribute/mobile/build-your-own/

**Comment by estan** [comment]
Sorry for necroposting, but is it really not possible to run your own self-hosted push proxy and use it with the officially built app distributed on Play and App Store?

**Comment by georgelucker** [comment]
> Sorry for necroposting, but is it really not possible to run your own self-hosted push proxy and use it with the officially built app distributed on Play and App Store?

Hi, did you happen to find a solution to the problem, is there any possibility to use the offiicial app with MPN?
