### ISSUE TITLE
Default avatar doesn't get regenerated with new initials after username change

### ISSUE THREAD

**Issue by antonbuks** [mattermost/mattermost-server#20417]
#### Summary
Default avatar picture doesn't get regenerated with new initials when username is changed through webapp settings

#### Steps to reproduce
On mattermost community create a user, then change the username in the settings, the avatar will contain initials for the old username.

#### Expected behavior
The image gets regenerated with new initials or that the frontend uses html instead of images for the default avatar

#### Observed behavior (that appears unintentional) 
<img width="162" alt="Screenshot 2022-06-09 at 12 41 11" src="https://user-images.githubusercontent.com/11543153/172829718-18c35093-d070-44c5-915f-f32d1a687d43.png">

you can see that the new username doesn't match initials in the avatar

#### Possible fixes
use html instead of images for the default avatar

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-44954.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was created for this.
