### ISSUE TITLE
Assign multiple users for a single task in playbooks

### ISSUE THREAD

**Issue by ikjnv** [mattermost/mattermost-server#20411]
It would be great to be able to assign one or multiple users for a single task simultaneously in playbooks since it is very common to assign several people to assign for one task at the same time. Currently, only a single user can be assigned for one task.

**Comment by amyblais** [comment]
@ikjnv Would you be open to re-opening this in the Playbooks repo https://github.com/mattermost/mattermost-plugin-playbooks/issues?

**Comment by ikjnv** [comment]
@amyblais sure.
