### ISSUE TITLE
Adding GIS function to Mattermost

### ISSUE THREAD

**Issue by MrC2D** [mattermost/mattermost-server#20452]
Hello! So I'm not the greatest programmer or software developer, however I thought it would be cool to add a GIS function to Mattermost. I grabbed the Earth enterprise from GitHub and setup the fusion and earth server on a separate VM and I have communications between my host machine and the VM, however when I try to upload the plugin the only error I get is failed to fetch on Mattermost? Any ideas on why this error comes up when trying to upload plugins to Mattermost?

**Comment by amyblais** [comment]
Troubleshooting thread: https://community.mattermost.com/core/pl/qboumdbiipgo8kmm3r371qh5or.
