### ISSUE TITLE
sign-in verification email sent without port

### ISSUE THREAD

**Issue by esguti** [mattermost/mattermost-server#20475]
#### Summary
Send sign-in email address without port

#### Steps to reproduce
Mattermost Version: 6.3.9 self-hosted in a non HTTPS standard port (ex: 3455 instead of 443).
1. Create a channel
2. Invite members using email
3. The invitation email contains a URL without the port:
       https://myserver.com/signup_user_complete/....
       Instead of
       https://myserver.com:3455/signup_user_complete/....

      NOTE: if I use the option "copy the link", the link is correct

#### Expected behavior
the invitation URL should be sent with the server port in the URL

#### Observed behavior (that appears unintentional) 
There are no errors in the log files.

#### Possible fixes
include the port in the invitation sent by email

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-45112.

**Comment by amyblais** [comment]
@esguti The ‘Copy invite link’ gets the site URL from browser’s window object hence the URL is with port and is correct. 
Our suggestion would be to specify the URL with port in ServiceSettings.SiteURL in config.json file located in mattermost.server.
