### ISSUE TITLE
GitLab Single Sign-On broken

### ISSUE THREAD

**Issue by leitmori** [mattermost/mattermost-server#20499]
#### Summary
GitLab Single Sign-On is broken (at least in Mattermost Team Edition v7.0.0).

#### Steps to reproduce
1. Configure SSO as described in [docs](https://docs.mattermost.com/onboard/sso-gitlab.html)
2. Verify settings in `config.json` (and restart mattermost afterwards):
```json
"GitLabSettings": {
        "Enable": true,
        "Secret": "<Secret>",
        "Id": "<Application ID>",
        "Scope": "openid read_user",
        "AuthEndpoint": "https://gitlab.com/oauth/authorize",
        "TokenEndpoint": "https://gitlab.com/oauth/token",
        "UserAPIEndpoint": "https://gitlab.com/api/v4/user",
        "DiscoveryEndpoint": "",
        "ButtonText": "",
        "ButtonColor": ""
    }
```
3. Authenticate via GitLab

#### Expected behavior
User is logged in

#### Observed behavior
Error: "Could not parse auth data out of gitlab user object."
![Screen Shot 2022-06-17 at 20 31 53](https://user-images.githubusercontent.com/29522608/174357297-545acd5a-c4bc-4429-a19b-a4900e8e480e.png)
Log entry: `{"timestamp":"2022-06-17 23:05:16.226 +02:00","level":"debug","msg":"Could not parse auth data out of gitlab user object.","caller":"web/context.go:101","path":"/signup/gitlab/complete","request_id":"g1bp87g93tn6pko1559pf8m48y","ip_addr":"127.0.0.1","user_id":"","method":"GET","err_where":"LoginByOAuth","http_code":400,"err_details":"user id can't be 0"}
`

**Comment by amyblais** [comment]
@furqanmlk @lindalumitchell Are you able to reproduce this on Team Edition?

**Comment by leitmori** [comment]
Update: When setting the `Scope` to `openid read_user` you get the following error: `{"timestamp":"2022-06-17 23:21:16.936 +02:00","level":"info","msg":"Gitlab SSO through OAuth 2.0 not available on this server.","caller":"web/context.go:103","path":"/oauth/gitlab/login","request_id":"dacfys18u7ntxcjije1okh4w6c","ip_addr":"127.0.0.1","user_id":"","method":"GET","err_where":"getSSOProvider","http_code":501,"err_details":""}`
![Screen Shot 2022-06-17 at 23 31 37](https://user-images.githubusercontent.com/29522608/174403921-74366c83-3fc4-4146-93be-1acf559aef9d.png)
I then turned GitLab Authentication off and on again in the settings, resetting the scope to an empty string. Then the authentication works, but you get the initial described error. So the cause seems to be related to the fact that the Team Edition does not allow the necessary scope `openid read_user`.

**Comment by leitmori** [comment]
Got it working now with scope `read_user` (see #17499). The documentation should definitely be updated, as the following statement is misleading:  **At a minimum, openid is a required scope for the connector to work.**
