### ISSUE TITLE
Upload file button fails

### ISSUE THREAD

**Issue by gabrielctn** [mattermost/mattermost-server#20497]
#### Summary
When click on button "Upload file" in the message box, a small white box with shadow appears but is empty.

#### Steps to reproduce
1. Use Mattermost Server 7.0.0 and Mattermost Desktop 5.1.0 with on any OS, or even on the web.
2. In the message box, click on the paperclip icon for file upload.
3. A small white box with shadow appears empty

Only the button fails. Dropping a file or doing CTRL+U work fine.

#### Expected behavior
On click, a file upload box should appear to be able to select the file(s) we want to upload from our filesystem.

#### Observed behavior (that appears unintentional) 

https://user-images.githubusercontent.com/25644865/174302952-b167b5b7-fcf3-4fe9-923f-c92173ed1fe6.mov

**Comment by gabrielctn** [comment]
Indeed I have the Draw plugin enabled, and the problem is solved when disabled !

**Comment by Podesta** [comment]
Issue also happening if the Voice plugin is enabled.
`Voice (com.mattermost.voice - 0.2.2)`
