### ISSUE TITLE
Chat |Code and Quote buttons

### ISSUE THREAD

**Issue by BrianSalestrekker** [mattermost/mattermost-server#20514]
﻿Code and Quote buttons are not working as they should in chat. Their functions are switched. When you click on Code button you are getting Quote, and when you click on Quotes button you are getting Code.

Attachments:

﻿Code:
![image (6)](https://user-images.githubusercontent.com/107915796/174747557-3b2ee137-36f8-48e0-a709-4cb461d496b2.png)

﻿Quote:﻿
![image (7)](https://user-images.githubusercontent.com/107915796/174747660-e58cb19e-6423-4414-b251-149685683d5f.png)

**Comment by amyblais** [comment]
I believe this is working as expected per documentation, but let me know if I missed anything.

The first screenshot shows code https://docs.mattermost.com/channels/format-messages.html#code-blocks.
The second screenshot shows quotes https://docs.mattermost.com/channels/format-messages.html#block-quotes.
