### ISSUE TITLE
Large pop-up advertising Mattermost Cloud shown to my users (self-hosted)

### ISSUE THREAD

**Issue by wezm** [mattermost/mattermost-server#20520]
#### Summary
Large pop-up advertising Mattermost Cloud shown to my users (self-hosted instance).

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

I don't have precise steps however this morning one of the users on my self-hosted Mattermost instance commented on seeing a pop-up advertising Mattermost Cloud. When I switched to my laptop (from my phone) I was also shown the pop-up. I am the only user with the "System Admin" user status.

Clients: Mattermost in Firefox on Linux
Server: Mattermost Version: 7.0.0

#### Expected behavior
I expect that advertising is not shown to my users.

#### Observed behavior (that appears unintentional) 
One of the users of my self-hosted install was show this pop-up, as was I:

![Screenshot 2022-06-22 at 08-39-57 di - Wizards League Mattermost](https://user-images.githubusercontent.com/21787/174909524-13a2b3cc-1d79-4a02-ba82-6f95b6647c2b.png)

**Update:** I run a second instance for a different community and was shown the pop-up there too.

#### Possible fixes

I searched the issue trackers and codebase on both this repo and `mattermost-webapp` for the string "Use Mattermost Cloud for free forever" and got no results. I also did the same search in Jira and got no results. It's suspicious where this is coming from. I hope that you aren't using Google Tag Manager or something to dynamically add scripts to the webapp.

**Comment by ramilehti** [comment]
Advertisements IMHO do NOT qualify as "End User Notices", which I had enabled. If I disable them can someone please assure me that my users will not get ads.

**Comment by amyblais** [comment]
This is used to share visibility of the new free forever plan for Cloud. It's only sent once.

It's part of our in-product notices feature for new releases or versions - they can be disabled via the System Console: https://docs.mattermost.com/configure/configuration-settings.html#notices.

This is the GitHub repository https://github.com/mattermost/notices.

**Comment by wezm** [comment]
> This is used to share visibility of the new free forever plan for Cloud.

That's not entirely unreasonable but I think it only makes sense to show it to admins. I don't think it's worth disrupting all the users on an instance with this information that doesn't necessarily make any sense to them.

**Comment by amyblais** [comment]
> That's not entirely unreasonable but I think it only makes sense to show it to admins. I don't think it's worth disrupting all the users on an instance with this information that doesn't necessarily make any sense to them.
> 
> **Edit:** It seems there's already a separation between [Administrator notices](https://docs.mattermost.com/manage/in-product-notices.html#id1) and [End user notices](https://docs.mattermost.com/manage/in-product-notices.html#id2). I'm not sure why this one was sent as an end-user notice.

I'll ping the product team to confirm on that decision cc @jasonblais @esethna

**Comment by endgame** [comment]
> First, rest assured, we are not using Google Tag Manager or such tool to dynamically add scripts to the webapp.

I for one am glad to hear this, thanks for confirming.

> Do you envision these types of notices being suitable for both admins and end users?

As an end user, I think new client features are very relevant to my interests.

**Comment by itsupportcmsukorg** [comment]
Today's example is in my view an ad for an _alternative_ service and not a notice about 'relevant end user features' of our internal Mattermost. Notices like this appear to end users as if our Mattermost Admin is endorsing/encouraging them to go and set-up additional Mattermost instances in the cloud away from our internal organisational app.

We like your animated notices introducing new features, they are helpful to both Admins and End Users. This one today was not helpful for our particular user context.

**Comment by jasonblais** [comment]
Thanks both for the feedback! Very helpful for future notices to ensure they remain relevant for the audience. 

cc @esethna on the above thread as well
