### ISSUE TITLE
Attached unnecessary ellipsis to context menu text with Japanese translation

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-server#20537]
#### Summary
With Japanese translations, ellipsis dots is added to context menu text even though any characters are not omitted.

<img width="445" alt="スクリーンショット 2022-06-24 15 17 39" src="https://user-images.githubusercontent.com/1453749/175475236-4aa7da0a-a8c4-4ded-8201-aa09c71533b3.png">

#### Steps to reproduce

1. Set language to 日本語 (Japanese) from **Settings > Display > Language**.
2. Open context menu for channels

#### Expected behavior

All text and icons is visible without any unnecessary characters.

#### Observed behavior (that appears unintentional) 

An ellipsis is added at the end of a menu even though any characters are not omitted.

#### Possible fixes

Set `max-width` to `244px` or more.
https://github.com/mattermost/mattermost-webapp/blob/1e91440a56a9f543187a0e9c9328344e94479629/components/sidebar/sidebar_header/sidebar_header.tsx#L46

<img width="1313" alt="スクリーンショット 2022-06-24 15 20 48" src="https://user-images.githubusercontent.com/1453749/175475285-ef5e5e98-2552-4807-ab1f-86b4a8f4a2d4.png">

---

I'm a Japanese localization maintainer and I know that shortening translation text can fix this issue, but it is hard to shorten text from the aspect of Japanese speaker.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-45314.
