### ISSUE TITLE
Cannot access the create account button on safari for iOS.

### ISSUE THREAD

**Issue by dillfrescott** [mattermost/mattermost-server#20536]
#### Summary
Cannot access the create account button on safari for iOS.

#### Steps to reproduce
Invite someone to your team who has an iPhone, the create account button is blocked by the search bar and you cannot scroll down.

#### Expected behavior
You should be able to scroll the page down to reach the button.

#### Observed behavior (that appears unintentional) 
It is blocked by the safari search bar in newer versions of iOS.

#### Possible fixes
No code linking, but I had to have someone use their desktop computer to sign up because they tried to reach the create account button and couldn't.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-45313.
