### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [mattermost/mattermost-server#20539]
Hi!

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know).

This kind of information is important for the end-users.

Thanks in advance!

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-45316. 

I'm guessing the information could be added at https://docs.mattermost.com/getting-started/architecture-overview.html or at https://docs.mattermost.com/install/software-hardware-requirements.html.

**Comment by agnivade** [comment]
We use Go to build our software. You can take a look at this page: https://github.com/golang/go/wiki/MinimumRequirements#architectures.

We don't use any `GOAMD64` version, so that means all 64-bit x86 processors are supported.

**Comment by agnivade** [comment]
@zamazan4ik - Officially, we don't support ARM. You are welcome to build Mattermost for ARM, but you would need to maintain it yourself.

> Also, could you please put a note about the supported architectures somewhere in your documentation? 

Sure.
