### ISSUE TITLE
[Feature Request] Automatically reindex bleve after upgrade new version

### ISSUE THREAD

**Issue by NgoHuy** [mattermost/mattermost-server#20547]
Hi MatterMost team,

#### Summary
Every time I upgraded new mattermost version, I must reindex bleve manually. Should we have api or feature to reindex automatically?

#### Steps to reproduce
Upgrade mattermost-server to new version. Search on search bar, nothing returned.

#### Expected behavior
After upgrading new version, We can use old index or auto reindex.

Best regards,
Severus

**Comment by agnivade** [comment]
Unless the release notes mention it specifically, you should not need to reindex bleve. You mention "Every time", can you give an example source -> destination version? In recent times, except the 6.2 [upgrade](https://docs.mattermost.com/install/self-managed-changelog.html#id73), I don't think we changed the index structure.

**Comment by NgoHuy** [comment]
```
Mattermost Version: 7.0.1
Database Schema Version: 85
Database: mysql
```
I use latest version.

**Comment by agnivade** [comment]
I understand that now you are on the latest version. I'd like to know what were your previous versions and what versions you upgraded to, that caused you to reindex bleve, since you mentioned "Every time".

**Comment by NgoHuy** [comment]
Sorry, my fault, I set the custom index directory,  then when the upgrade is running, I forgot to exclude this directory and then it was removed after.
Close issue here.
