### ISSUE TITLE
Unable to activate plugin: Caller

### ISSUE THREAD

**Issue by ZS-Andisch** [mattermost/mattermost-server#20549]
My Mattermost is self hosted in Version 7.0.1

The new Caller Plugin doesn't work.

In my mattermost.log i find this line:
{"timestamp":"2022-06-27 07:00:11.363 Z","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:139","plugin_id":"com.mattermost.calls","error":"unable to generate webapp bundle: com.mattermost.calls: unable to read webapp bundle:  com.mattermost.calls: open client/plugins/com.mattermost.calls/main.js: no such file or directory"}

I go to this Folder "client/plugins/com.mattermost.calls/" and there is only a folder "files" in it. But the main.js is missing. The same Error on Version 7.0.0.

What can i do?

**Comment by amyblais** [comment]
@ZS-Andisch Would you be open to moving this issue to the Calls repo https://github.com/mattermost/mattermost-plugin-calls/issues? When you do so, please also help include the following details if possible:

**JS Console Logs**

1. Dots menu -> View -> Developer Tools for Current Tab.
2. Right Click -> Save as…

**Comment by ZS-Andisch** [comment]
Moved this request to https://github.com/mattermost/mattermost-plugin-calls/issues/133
