### ISSUE TITLE
Insights thread opening

### ISSUE THREAD

**Issue by antonbuks** [mattermost/mattermost-server#20553]
#### Summary
In insights you can open threads from the top threads section, if you open a thread from a channel you are not in from team insights, it opens a blank RHS sidebar

#### Steps to reproduce
From the insights tab, go to team insights and from top threads open a thread in a channel you are not in.

#### Broken thread example
<img width="1485" alt="Screenshot 2022-06-27 at 13 50 04" src="https://user-images.githubusercontent.com/11543153/175934707-e834ca8b-b8cf-46c2-aafe-404270cbfdd9.png">

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-45350.
