### ISSUE TITLE
Inserting an image tag breaks code block new lines

### ISSUE THREAD

**Issue by Yinameah** [mattermost/mattermost-server#20552]
#### Summary
Inserting an image tag (`![title](url)`) breaks code block new line (`<br>` displayed instead)

#### Steps to reproduce
Type the following in a message :

```
    ```
    a code block
    on multiple lines
    ```

    ![figure](https://i.redd.it/w3kr4m2fi3111.png)
```

#### Expected behavior
The code block and the image should appear normally

#### Observed behavior (that appears unintentional) 
The newlines inside the code block are transformed in `<br>` tags.

![image](https://user-images.githubusercontent.com/7933289/175933032-4906e4cd-1704-4f29-90d6-0d8f00350070.png)

#### Possible fixes
No idea, sorry

#### Version
Mattermost Version: 7.0.0
Database Schema Version: 85
Database: mysql

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-45349.
