### ISSUE TITLE
Mattermost 7 build failed

### ISSUE THREAD

**Issue by ru2mm** [mattermost/mattermost-server#20566]
#### Summary
I try to make a port for FreeBSD for mattermost server v.7.0.1. The build process failed with errors.

#### Steps to reproduce
Build process failes because of missing "vendor" folder in v.7.0.0 and v.7.0.1 repositories. 
You can open the list of files for version 6.7.2 an older and see the folder "vendor" https://github.com/mattermost/mattermost-server/tree/v6.7.2/vendor.
If I add "vendor" folder from v.6.7.2 and additionaly add files from squirrel project https://github.com/mattermost/squirrel the build process complites succefuly.

#### Expected behavior
The "vendor" folder should be added to v.7.x repositories.

#### Observed behavior (that appears unintentional) 
Build failes due to missing "vendor" folder.

#### Possible fixes
Return the folder to its original location as in versions 6.7.2 and older or provide recommendation how to build mattermost server without files in folder "vendor".

#### List of errors below:

===>  Building mattermost from ./cmd/mattermost
services/docextractor/documents.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[code.sajari.com/docconv](http://code.sajari.com/docconv)
app/product_notices.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/Masterminds/semver/v3](http://github.com/Masterminds/semver/v3)
app/login.go:17:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/avct/uasurfer](http://github.com/avct/uasurfer)
services/awsmeter/awsmeter.go:11:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/aws/aws-sdk-go/aws](http://github.com/aws/aws-sdk-go/aws)
services/awsmeter/awsmeter.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/aws/aws-sdk-go/aws/credentials](http://github.com/aws/aws-sdk-go/aws/credentials)
services/awsmeter/awsmeter.go:13:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds](http://github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds)
services/awsmeter/awsmeter.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/aws/aws-sdk-go/aws/ec2metadata](http://github.com/aws/aws-sdk-go/aws/ec2metadata)
services/awsmeter/awsmeter.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/aws/aws-sdk-go/aws/session](http://github.com/aws/aws-sdk-go/aws/session)
services/awsmeter/awsmeter.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/aws/aws-sdk-go/service/marketplacemetering](http://github.com/aws/aws-sdk-go/service/marketplacemetering)
services/awsmeter/awsmeter.go:17:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/aws/aws-sdk-go/service/marketplacemetering/marketplacemeteringiface](http://github.com/aws/aws-sdk-go/service/marketplacemetering/marketplacemeteringiface)
app/plugin.go:19:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/blang/semver](http://github.com/blang/semver)
services/searchengine/bleveengine/bleve.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/blevesearch/bleve/v2](http://github.com/blevesearch/bleve/v2)
services/searchengine/bleveengine/bleve.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/blevesearch/bleve/v2/analysis/analyzer/keyword](http://github.com/blevesearch/bleve/v2/analysis/analyzer/keyword)
services/searchengine/bleveengine/bleve.go:17:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/blevesearch/bleve/v2/analysis/analyzer/standard](http://github.com/blevesearch/bleve/v2/analysis/analyzer/standard)
services/searchengine/bleveengine/bleve.go:18:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/blevesearch/bleve/v2/mapping](http://github.com/blevesearch/bleve/v2/mapping)
services/searchengine/bleveengine/search.go:11:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/blevesearch/bleve/v2/search/query](http://github.com/blevesearch/bleve/v2/search/query)
services/cache/lru_striped.go:11:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/cespare/xxhash/v2](http://github.com/cespare/xxhash/v2)
app/license.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/dgrijalva/jwt-go](http://github.com/dgrijalva/jwt-go)
shared/mfa/mfa.go:13:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/dgryski/dgoogauth](http://github.com/dgryski/dgoogauth)
app/emoji.go:23:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/disintegration/imaging](http://github.com/disintegration/imaging)
app/opengraph.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/dyatlov/go-opengraph/opengraph](http://github.com/dyatlov/go-opengraph/opengraph)
model/auditconv.go:9:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/francoispqt/gojay](http://github.com/francoispqt/gojay)
shared/templates/templates.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/fsnotify/fsnotify](http://github.com/fsnotify/fsnotify)
app/server.go:28:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/getsentry/sentry-go](http://github.com/getsentry/sentry-go)
app/server.go:29:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/getsentry/sentry-go/http](http://github.com/getsentry/sentry-go/http)
store/sqlstore/retention_policy_store.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/go-sql-driver/mysql](http://github.com/go-sql-driver/mysql)
store/sqlstore/store.go:27:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/golang-migrate/migrate/v4/source/file](http://github.com/golang-migrate/migrate/v4/source/file)
app/users/profile_picture.go:19:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/golang/freetype](http://github.com/golang/freetype)
app/users/profile_picture.go:20:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/golang/freetype/truetype](http://github.com/golang/freetype/truetype)
app/server.go:30:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/gorilla/handlers](http://github.com/gorilla/handlers)
app/integration_action.go:33:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/gorilla/mux](http://github.com/gorilla/mux)
web/webhook.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/gorilla/schema](http://github.com/gorilla/schema)
app/web_conn.go:20:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/gorilla/websocket](http://github.com/gorilla/websocket)
api4/graphql.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/graph-gophers/dataloader/v6](http://github.com/graph-gophers/dataloader/v6)
model/custom_status.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/graph-gophers/graphql-go](http://github.com/graph-gophers/graphql-go)
api4/graphql.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/graph-gophers/graphql-go/errors](http://github.com/graph-gophers/graphql-go/errors)
app/plugin.go:20:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/h2non/go-is-svg](http://github.com/h2non/go-is-svg)
plugin/hclog_adapter.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/hashicorp/go-hclog](http://github.com/hashicorp/go-hclog)
plugin/api.go:10:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/hashicorp/go-plugin](http://github.com/hashicorp/go-plugin)
shared/mail/mail.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/jaytaylor/html2text](http://github.com/jaytaylor/html2text)
store/sqlstore/sqlx_wrapper.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/jmoiron/sqlx](http://github.com/jmoiron/sqlx)
services/docextractor/pdf.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/ledongthuc/pdf](http://github.com/ledongthuc/pdf)
store/sqlstore/retention_policy_store.go:13:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/lib/pq](http://github.com/lib/pq)
shared/i18n/i18n.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/go-i18n/i18n](http://github.com/mattermost/go-i18n/i18n)
api4/handlers.go:9:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/gziphandler](http://github.com/mattermost/gziphandler)
model/config.go:21:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/ldap](http://github.com/mattermost/ldap)
shared/mlog/levels.go:6:8: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/logr/v2](http://github.com/mattermost/logr/v2)
shared/mlog/mlog.go:21:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/logr/v2/config](http://github.com/mattermost/logr/v2/config)
shared/mlog/tlog.go:13:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/logr/v2/formatters](http://github.com/mattermost/logr/v2/formatters)
shared/mlog/tlog.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/logr/v2/targets](http://github.com/mattermost/logr/v2/targets)
store/sqlstore/store.go:19:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/morph](http://github.com/mattermost/morph)
store/sqlstore/store.go:22:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/morph/drivers](http://github.com/mattermost/morph/drivers)
store/sqlstore/store.go:23:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/morph/drivers/mysql](http://github.com/mattermost/morph/drivers/mysql)
store/sqlstore/store.go:24:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/morph/drivers/postgres](http://github.com/mattermost/morph/drivers/postgres)
store/sqlstore/store.go:30:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/morph/sources/embedded](http://github.com/mattermost/morph/sources/embedded)
shared/mfa/mfa.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/rsc/qr](http://github.com/mattermost/rsc/qr)
store/sqlstore/audit_store.go:7:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mattermost/squirrel](http://github.com/mattermost/squirrel)
services/docextractor/archive.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/mholt/archiver/v3](http://github.com/mholt/archiver/v3)
app/email/email.go:26:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/microcosm-cc/bluemonday](http://github.com/microcosm-cc/bluemonday)
shared/filestore/s3store.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/minio/minio-go/v7](http://github.com/minio/minio-go/v7)
shared/filestore/s3_overrides.go:10:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/minio/minio-go/v7/pkg/credentials](http://github.com/minio/minio-go/v7/pkg/credentials)
shared/filestore/s3store.go:17:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/minio/minio-go/v7/pkg/encrypt](http://github.com/minio/minio-go/v7/pkg/encrypt)
app/imaging/decode.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/oov/psd](http://github.com/oov/psd)
services/tracing/tracing.go:11:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/opentracing/opentracing-go](http://github.com/opentracing/opentracing-go)
app/opentracing/opentracing_layer.go:37:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/opentracing/opentracing-go/ext](http://github.com/opentracing/opentracing-go/ext)
app/opentracing/opentracing_layer.go:38:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/opentracing/opentracing-go/log](http://github.com/opentracing/opentracing-go/log)
model/utils.go:28:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/pborman/uuid](http://github.com/pborman/uuid)
shared/filestore/filesstore.go:10:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/pkg/errors](http://github.com/pkg/errors)
app/product_notices.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/reflog/dateconstraints](http://github.com/reflog/dateconstraints)
app/server.go:33:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/rs/cors](http://github.com/rs/cors)
services/telemetry/telemetry.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/rudderlabs/analytics-go](http://github.com/rudderlabs/analytics-go)
app/imaging/orientation.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/rwcarlsen/goexif/exif](http://github.com/rwcarlsen/goexif/exif)
cmd/mattermost/commands/db.go:11:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/spf13/cobra](http://github.com/spf13/cobra)
app/featureflag/feature_flags_sync.go:13:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/splitio/go-client/v6/splitio/client](http://github.com/splitio/go-client/v6/splitio/client)
app/featureflag/feature_flags_sync.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/splitio/go-client/v6/splitio/conf](http://github.com/splitio/go-client/v6/splitio/conf)
store/storetest/audit_store.go:10:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/stretchr/testify/assert](http://github.com/stretchr/testify/assert)
store/storetest/mocks/AuditStore.go:9:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/stretchr/testify/mock](http://github.com/stretchr/testify/mock)
utils/emoji.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/stretchr/testify/require](http://github.com/stretchr/testify/require)
app/email/service.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/throttled/throttled](http://github.com/throttled/throttled)
app/email/service.go:13:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/throttled/throttled/store/memstore](http://github.com/throttled/throttled/store/memstore)
model/session_serial_gen.go:9:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/tinylib/msgp/msgp](http://github.com/tinylib/msgp/msgp)
services/tracing/tracing.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/uber/jaeger-client-go](http://github.com/uber/jaeger-client-go)
services/tracing/tracing.go:13:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/uber/jaeger-client-go/config](http://github.com/uber/jaeger-client-go/config)
services/tracing/tracing.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/uber/jaeger-client-go/zipkin](http://github.com/uber/jaeger-client-go/zipkin)
services/tracing/tracing.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/uber/jaeger-lib/metrics](http://github.com/uber/jaeger-lib/metrics)
model/websocket_client.go:17:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/vmihailenco/msgpack/v5](http://github.com/vmihailenco/msgpack/v5)
jobs/export_delete/worker.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/wiggin77/merror](http://github.com/wiggin77/merror)
utils/markdown.go:11:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/yuin/goldmark](http://github.com/yuin/goldmark)
utils/markdown.go:12:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/yuin/goldmark/ast](http://github.com/yuin/goldmark/ast)
utils/markdown.go:13:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/yuin/goldmark/extension](http://github.com/yuin/goldmark/extension)
utils/markdown.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/yuin/goldmark/extension/ast](http://github.com/yuin/goldmark/extension/ast)
utils/markdown.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/yuin/goldmark/renderer](http://github.com/yuin/goldmark/renderer)
utils/markdown.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[github.com/yuin/goldmark/util](http://github.com/yuin/goldmark/util)
app/server.go:34:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/crypto/acme/autocert](http://golang.org/x/crypto/acme/autocert)
model/user.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/crypto/bcrypt](http://golang.org/x/crypto/bcrypt)
app/plugin_signature.go:14:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/crypto/openpgp](http://golang.org/x/crypto/openpgp)
app/plugin_signature.go:15:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/crypto/openpgp/armor](http://golang.org/x/crypto/openpgp/armor)
model/remote_cluster.go:17:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/crypto/scrypt](http://golang.org/x/crypto/scrypt)
app/imaging/decode.go:17:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/image/bmp](http://golang.org/x/image/bmp)
app/imaging/decode.go:18:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/image/tiff](http://golang.org/x/image/tiff)
app/opengraph.go:13:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/net/html/charset](http://golang.org/x/net/html/charset)
store/sqlstore/user_store.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/sync/errgroup](http://golang.org/x/sync/errgroup)
model/user.go:17:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[golang.org/x/text/language](http://golang.org/x/text/language)
shared/mail/mail.go:18:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[gopkg.in/mail.v2](http://gopkg.in/mail.v2)
model/manifest.go:16:2: cannot find package "." in:
        /usr/home/user2/ports/mattermost-server/work/mattermost-server-7.0.1/vendor/[gopkg.in/yaml.v2](http://gopkg.in/yaml.v2)
*** Error code 1

Stop.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-45452.

**Comment by agnivade** [comment]
Hi @ru2mm - are you open to logging in to our community server at https://community.mattermost.com/ and asking for help in ask-r&d or the developers channel? Someone should be able to help you out.

**Comment by neflyte** [comment]
I seem to have this working on FreeBSD 12.3-RELEASE-p5. I'm having some issues with packaging, but the build is successful.

**Comment by ru2mm** [comment]
Thank you @agnivade for advice. I found the information I needed in community server https://community.mattermost.com/core/pl/5jyuapkcofrqxdnt5huaif8eso.

I use FreeBSD 13.1. Thanks to Raul for making the port for FreeBSD https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264232.
