### ISSUE TITLE
Cannot exit from editing preformatted block

### ISSUE THREAD

**Issue by rdivia** [mattermost/mattermost-server#20561]
#### Summary
Impossible to exit from edit of preformatted block

#### Steps to reproduce
Web browser. Create a post with a preformatted block. Then edit it, placing the cursor inside the preformatted block. Once edited, try to confirm the edit (CR).

#### Expected behavior
Exit from editing a preformatted block should be possible via a CR with the cursor outside the block.

#### Observed behavior (that appears unintentional) 
CR would add a CR, also when the cursor was outside the preformatted block.

#### Possible fixes
Nope

**Comment by amyblais** [comment]
@rdivia What Mattermost server version are you on? What OS are you using?

**Comment by rdivia** [comment]
Web. Chromium/Linux (but I also saw it on Chrome/W10).

**Comment by rdivia** [comment]
I did not try CTRL+Enter (saw it just now).

**Comment by rdivia** [comment]
For me CR works if the edit has no preformatted block, so I guess it is a different issue.

**Comment by amyblais** [comment]
@rdivia 

1. What Mattermost server version are you on? (**Main Menu > About Mattermost**)
2. What are your settings set to at **Settings > Advanced > Send Messages on ⌘+ENTER**?

**Comment by rdivia** [comment]
Mattermost Version: cern-ci
Database Schema Version: 82
Database: postgres

Build Hash: 503ead4fbb82924ca060bd62095b7abe41c88631
EE Build Hash: none
Webapp Build Hash: fce4b8e02a548e6aab52597a41287ef2ce7118e7
Build Date: Mon May 9 11:05:54 UTC 2022

The CTRL+ENTER (I am on Linux, not on a Mac) settings is "On only for code blocks starting with ```".

I think next time something like this will happen I will try CTRL+ENTER (I did not know this option existed).

**Comment by rdivia** [comment]
Good news, I tried the CTRL-Enter combination and it worked nicely. Problem solved :-)
