### ISSUE TITLE
Images (build badges) break channel header

### ISSUE THREAD

**Issue by cgraf-spiria** [mattermost/mattermost-server#20589]
#### Summary
Images (like build badges) in channel header are not shown anymore and hide text after them.
They produce a line break before and after therefore hiding themselves and the rest of the header text.

Tested on Windows Client & Web page client.
Android App doesn't show images in channel header at all, maybe separate bug ?

#### Steps to reproduce
Add an image to a channel header with text before and text after the image.

#### Expected behavior
See the text before, the image and the text after. All on one single line

#### Observed behavior (that appears unintentional) 
We can see the text before, but the image is on a new line (can be seen when previewing or clicking channel info) and the text after is also on a new line. Therefore the full channel header is not visible in the channel. 

#### Possible fixes
Not sure, something must have changed with the way images are rendered with markdown.

**Comment by streamer45** [comment]
@cgraf-spiria Thanks for the report. Could provide the following information?

- Current Mattermost server version.
- A screenshot of the issue would be helpful since it's UX related.

Also, do you know if this behaviour changed after upgrading perhaps? I assume it worked as expected before.

**Comment by roderickgreen** [comment]
just want to note that this affects us as well. we have the same use case: build badges in the channel header.  thx!

**Comment by cgraf-spiria** [comment]
Link to bug in Mattermost's issue tracker: https://mattermost.atlassian.net/browse/MM-45540
