### ISSUE TITLE
Removing Members from Channel

### ISSUE THREAD

**Issue by jasonmacer** [mattermost/mattermost-server#20588]
Summary
Unable to remove a user as a members from a single channel.

Steps to reproduce
Mattermost Enterprise Edition
Modern communication from behind your firewall.

Mattermost Version: 7.0.0
Database Schema Version: 85
Database: mysql

Web Based, Mobile, AND Desktop based connection
Expected behavior
I am attempting remove users from a channel; however it only gives me ( an admin ) permission to "make channel admin."

Click on channel > click on channel name drop down > View Members > Manage > click on user permissions

Only see "Make channel admin"

#### Observed behavior (that appears unintentional) 
Missing "remove from channel"
 Possible fixes
This channel was originally the "town square," are users not able to be removed from the town square channel?

Thank you!

**Comment by streamer45** [comment]
Hi @jasonmacer , that's correct, Town Square being the default channel with everyone in the team present so users cannot be removed from it unless they get removed from the team.
