### ISSUE TITLE
S3 upload fail

### ISSUE THREAD

**Issue by baek-sang** [mattermost/mattermost-server#20582]
#### Summary
s3 ( [Cloudflare R2](https://developers.cloudflare.com/r2/) ) upload fail.

#### Steps to reproduce
![mattermost-s3-setup](https://user-images.githubusercontent.com/69100154/177157865-dc9e32b2-88cc-4a8f-8a61-6a3d9bbfd24d.png)
1. Setting s3 & Test Connection confirm
2. Try file upload

#### Expected behavior
File upload success.

#### Observed behavior (that appears unintentional) 
Server log
```
{"timestamp":"2022-07-04 08:55:02.217 Z","level":"error","msg":"Unable to write the file.","caller":"web/context.go:105","path":"/api/v4/files","request_id":"request_id","ip_addr":"1.2.3.4","user_id":"user_id","method":"POST","err_where":"WriteFile","http_code":500,"err_details":"unable write the data in the file 20220704/teams/noteam/channels/~/~/test-image.png: The XML you provided was not well formed or did not validate against our published schema."}
```

#### Environment
Mattermost server 7.0.1 ( self-host, docker )
Desktop 5.1.1, iOS Mobile 2.0 beta

**Comment by streamer45** [comment]
Hi @baek-sang , this looks to be a [known issue](https://community.cloudflare.com/t/r2-multipart-uploads-not-working-with-minio-client/396536/13 ) with R2 not accepting the minio upload due to a mismatch in the request format.

/cc @agnivade

**Comment by lahdekorpi** [comment]
Is this still broken or should R2 work now?
I'm testing with similar config as in the screenshot but keep getting:
```
"msg": "Unable to connect to S3. Verify your Amazon S3 connection authorization parameters and authentication settings."
```

**Comment by lahdekorpi** [comment]
Oh, I had some issue in the config and now got the same issue of Cloudflare missing CRC32C.
But this is just the default in minio, mattermost could define some other checksum for those calls that is supported?
