### ISSUE TITLE
Function clearDeadQueue will not reset the deadQueuePointer if the deadQueue didn't roll over.

### ISSUE THREAD

**Issue by tangvis** [mattermost/mattermost-server#20622]
#### Summary
clearDeadQueue will return without reset the deadQueuePointer to 0 when deadQueue didn't roll over.

#### Steps to reproduce
[code link](https://github.com/mattermost/mattermost-server/blob/c3d2602dfefa3d91588d9a0aa5a24aa050ae20e0/app/web_conn.go#L580-L588)
```
func (wc *WebConn) clearDeadQueue() {
	for i := 0; i < deadQueueSize; i++ {
		if wc.deadQueue[i] == nil {
			return
		}
		wc.deadQueue[i] = nil
	}
	wc.deadQueuePointer = 0
}
```
In the above code, when deadQueue didn't roll over and we call the function.

#### Expected behavior
Set every element of  deadQueue to nil and set deadQueuePointer to 0.

#### Observed behavior (that appears unintentional) 
Didn't set deadQueuePointer to 0.

#### Possible fixes
```
func (wc *WebConn) clearDeadQueue() {
	wc.deadQueuePointer = 0	
	for i := 0; i < deadQueueSize; i++ {
		if wc.deadQueue[i] == nil {
			return
		}
		wc.deadQueue[i] = nil
	}
}
```

**Comment by agnivade** [comment]
Nice catch. Thanks @tangvis :)
