### ISSUE TITLE
Not showing fullname in adding people to channel modal dialog

### ISSUE THREAD

**Issue by stillya** [mattermost/mattermost-server#20637]
**Problem**

When I'm trying to add people in channel I can't see their fullname, only **nickname**.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/39978392/178426628-dd18d60b-5ab3-4193-8c73-6a09f69bc39c.png">
But search working with all attributes of users(**including fullname**) and from server we getting all information about user. 

**Summary**

I think it's wrong behaviour and information about user must be full like in mention modal dialog.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/39978392/178427131-2717d930-32bd-41ef-a7f8-27bbb3d29261.png">

**Environment**

- Operating System: Any
- Mattermost Desktop App version: 5.1.1
- Mattermost Server version: 7.0.0

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-45686.
