### ISSUE TITLE
Mismatched sender id when doing test push message

### ISSUE THREAD

**Issue by altyne** [mattermost/mattermost-server#20656]
#### Summary
Error when testing push message notification to android device

#### Steps to reproduce
1. I followed diligently this guide (android) - https://developers.mattermost.com/contribute/mobile/push-notifications/service/

2. When testing the push. I used this command - in linux box:
curl http://19X.168.X.XXX:5066/api/v1/send_push -X POST -H "Content-Type: application/json" -d '{"type": "message", "message": "test", "badge": 1, "platform": "android_rn", "server_id": "na9fautnmidgbkoygjbrtXXXXX", "device_id": "XXXXXi32TNqV-3 Xa6MNFag:APA91bFK2el8OxNnf5Nz2YUIDgEwgYDVG7tnNaSyZSFQgmb6vV06nLJXw0XwoGXSV0myOG2mmpMHoVp4r9tLOGf2D_kagtCZYrDEb293ViGZNXXXXXMnPE4RxLbwetV_rtHR5krqLZx0", "channel_id": "uxe3jdph8pbodkwkdj8s9XXXXX"}'

X XX - just replace for security purposes

Error message: **{"error":"mismatched sender id","status":"FAIL"}**

This is the error in mattermost-push-proxy log:
INFO: 2022/07/14 22:06:50 logger.go:62: Sending android push notification for device=android_rn type=message ackId=
ERR: 2022/07/14 22:06:50 logger.go:80: Android response failure: &{2224993203732305747 0 1 0 [{  mismatched sender id}] [] 0 <nil>} type=android_rn

#### Expected behavior
Success without error

**Comment by amyblais** [comment]
@altyne What Mattermost server version and mobile app version are you on?

**Comment by amyblais** [comment]
@altyne I also recommend posting about this at https://community.mattermost.com/core/channels/peer-to-peer-help, where you can get troubleshooting help from community and staff.

**Comment by altyne** [comment]
> @altyne What Mattermost server version and mobile app version are you on?

Mattermost serve 7.1 (https://hub.docker.com/r/mattermost/mattermost-team-edition - master)
Mobile App - 1.54.0

**Comment by altyne** [comment]
@amyblais raise question on (https://community.mattermost.com/core/channels/peer-to-peer-help) channel this issue

**Comment by gamesguru** [comment]
I am also facing this issue with both legacy and new firebase server token / key IDs

**Comment by amyblais** [comment]
@gamesguru I recommend posting about this at https://community.mattermost.com/core/channels/peer-to-peer-help, where you can get troubleshooting help from community and staff.

**Comment by gamesguru** [comment]
The issue was that you can't use your own custom firebase keys (to do that, you must recompile the react native app with configuration changes).

I ended up switching back to the provided test server, and it worked.
