### ISSUE TITLE
[Feature] views for most active and last active threads

### ISSUE THREAD

**Issue by cmprmsd** [mattermost/mattermost-server#20658]
#### Summary
This is not a bug but a usability feature request. 
When you use threads excessively you'll notice that older threads might "run away" in the history. Topics get lost and lose track. 
There is of course the "conversations" view. But this does not include unsubscribed threads and currently is very basic in type of filtering etc.

#### Possible fixes
In another chat product `Zulip` there is "Recent topics", which does exactly this. 
You'd be able to search for last active conversations even if you are not subscribed yet and would be able to see where most chat activity is happening. 

Often it does not make sense to put everything into separate channels but into long lasting threads that people could subscribe also later on (e.g. chatbots that feed news into the chat).

![image](https://user-images.githubusercontent.com/73472903/179186787-a44f516f-abba-408b-9194-4d735a83ef61.png)

In addition to this it might be a great idea to have a second view that shows very active threads.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @cmprmsd,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by anx-ag** [comment]
I think [Insights](https://docs.mattermost.com/welcome/insights.html) is trying to do what you're requesting here. It's getting more and more insights every release, it already has a list of `Top threads` per user and per team and with the next version (already available on the community server), you will also be able to see the `Least active channels`.

Would that help you?
