### ISSUE TITLE
No way to know if a particular user ever logged in to Mattermost

### ISSUE THREAD

**Issue by chrish42** [mattermost/mattermost-server#20685]
When doing a gradual migration from another enterprise communication solution to Mattermost, for example, users will come onboard to Mattermost at different dates. Some will be early adopters, and others will take a bit more time to create their login and move over. Currently, there's no way to know if a particular user has ever logged in to Mattermost, or is just offline at the moment. Both show up as "offline", but in the first case, it's better to reach out to that person on the old platform, while in the second, it's fine to send the message on Mattermost (and they'll get it the next time they come online).

Having a way in to tell if a user has never logged in to Mattermost in the "user card" info, either via a "Last login" timestamp or a "Never logged in" flag would be really helpful in that example, and in other cases when trying to figure out what is the best way to reach out to a particular person.

**Comment by amyblais** [comment]
Thanks @chrish42,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)? Please include a link back to this GitHub issue. If you're interested in implementing, please let us know.

Feel free to also post about this idea at https://community.mattermost.com/core/channels/peer-to-peer-help and/or at https://forum.mattermost.com/. One of our community or staff members may have some ideas on this topic.

**Comment by anx-ag** [comment]
You could use the [GetSessions API call](https://api.mattermost.com/#tag/users/operation/GetSessions) to get a list of the user's sessions. It's not a perfect solution, but will at least get you going.

Additionally, you could also run a simple DB query to print out all users that do not have a valid session at the moment:

`
mm720=# select username from users where id NOT IN (SELECT userid FROM sessions) AND id NOT IN (SELECT userid FROM bots);
 username
----------
(0 rows)
`
