### ISSUE TITLE
Export of chats "impossible"

### ISSUE THREAD

**Issue by Hu1buerger** [mattermost/mattermost-server#20719]
#### Summary
Trying to print a chat from the mattermost web chat results in only one page, with multiple messages stacked ontop of each other.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Version unknown.

1. Write a chat with a user on mm.
2. Load the chat in Chrome on MacOS (but most likely an other OS)
3. Try to print the chat. (Hit Cmd+P)
4. Select as PDF

Inspect the PDF

#### Expected behavior
The PDF should contain the whole chat. 

#### Observed behavior (that appears unintentional) 
Any chat, regardless of length, only the current section gets printed.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

1. AFAIK a page can present the browser with a view optimized for printing
2. Offer a way to export the chat

**Comment by amyblais** [comment]
https://mattermost.atlassian.net/browse/MM-46140

**Comment by mkraft** [comment]
We don't plan to add this feature. Please refer to the various export features in the product.

**Comment by Hu1buerger** [comment]
@mkraft the jira ticket mentions the export of chats via printing, i do believe this issue is far greater than anticipated, as the core rights of the user is at stake. As mattermost seems to be a tool that values openness and transparency i fell that the gdpr and the right to data access of the subject should fall into that.

**Comment by Hu1buerger** [comment]
> `mmctl export` 

is that a tool run remote or locally by the user?

**Comment by mkraft** [comment]
> ...the core rights of the user is at stake ... i fell that the gdpr and the right to data access of the subject should fall into that.

I just want to ensure I understand what you're advocating. You're saying end users have a right to export data from the system and printing to PDF is an accessible way to do so?

> is that a tool run remote or locally by the user?

It can be run remotely or on the local server.
