### ISSUE TITLE
(Documentation?) Bug: `RestrictDirectMessage` Does Seem to Affect Messaging Permissions on Server (Contrary to Documented Behaviour)

### ISSUE THREAD

**Issue by gohrner** [mattermost/mattermost-server#20721]
#### Summary
The help text for the `RestrictDirectMessage` setting is wrong, it actually DOES influence permission checking on the server.

#### Steps to reproduce
1. Enable WelcomeBot and make sure it works, e.g. sending a message to new users or auto-adding new users to Channels.
2. Set `"RestrictDirectMessage": "team"`

#### Expected behavior
WelcomeBot still works.

#### Observed behavior (that appears unintentional) 
WelcomeBot does not work any more for new users, even though the plugin is running and reacts to slash commands.

You will see the following error messages in the server logs:

```
{"timestamp":"2022-07-11 19:15:43.993 +02:00","level":"error","msg":"failed to query direct message channel","caller":"app/plugin_api.go:928","plugin_id":"com.mattermost.welcomebot","user_id":"xxxxxxxxxxxxxxxxxxxx"}
```

During debuggin I then tried channel-specific welcome messages I had never used before, and these triggered a more helpful error message:

```
{"timestamp":"2022-07-12 06:41:34.823 +02:00","level":"info","msg":"{\"level\":\"error\",\"msg\":\"error occured while creating direct channel to the user\",\"fields\":[{\"Key\":\"UserId\",\"Type\":15,\"Integer\":0,\"String\":\"xxxxxxxxxxxxxxxxxxxx\",\"Interface\":null},{\"Key\":\"error\",\"Type\":25,\"Integer\":0,\"String\":\"\",\"Interface\":{\"id\":\"api.channel.create_channel.direct_channel.team_restricted_error\",\"message\":\"A direct channel cannot be created between these users because they do not share a team in common.\",\"detailed_error\":\"\",\"status_code\":403}}]}\n","caller":"io/io.go:425","plugin_id":"com.mattermost.welcomebot","source":"plugin_stderr"}
```

#### Possible fixes
Fix the documentation: Apparently, `"RestrictDirectMessage": "team"` DOES influence server side messaging permissions.

Current help text (which does not fit to observed behaviour):

> ‘Any member of the team’ limits the ability in the Direct Messages ‘More’ menu to only open Direct Message channels with users who are in the same team. Note: This setting only affects the UI, not permissions on the server.

The WelcomeBot misbehaviour, which also does not match this plugin's documented behaviour, is reported as https://github.com/mattermost/mattermost-plugin-welcomebot/issues/93

**Comment by amyblais** [comment]
https://mattermost.atlassian.net/browse/MM-46139
