### ISSUE TITLE
Upgrade from 6.3.9 to 7.1.2 fails

### ISSUE THREAD

**Issue by jelmd** [mattermost/mattermost-server#20779]
#### Summary
DB migration fails with **Error 1267: Illegal mix of collations** `(utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='`

#### Steps to reproduce
Upgrade version 6.3.9 to 7.2.1 - install and start the new instance.

#### Expected behavior
db migration should work and server start.

#### Observed behavior (that appears unintentional) 
```
Aug 06 05:38:50 mmtest mattermost[45757]: {"timestamp":"2022-08-06 05:38:50.890 Z"
,"level":"fatal","msg":"Failed to apply database migrations.","caller":"sqlstore
/store.go:165","error":"driver: mysql, message: failed when applying migration, 
command: apply_migration, originalError: Error 1267: Illegal mix of collations (
utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='
, query: \n\nCREATE TABLE IF NOT EXISTS Preferences (\n    UserId varchar(26) NO
T NULL,\n    Category varchar(32) NOT NULL,\n    Name varchar(32) NOT NULL,\n   
 Value text,\n    PRIMARY KEY (UserId, Category, Name)\n) ENGINE=InnoDB DEFAULT 
CHARSET=utf8mb4;\n\nSET @preparedStatement = (SELECT IF(\n    (\n        SELECT 
COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS\n        WHERE table_name = 'Preference
s'\n        AND table_schema = DATABASE()\n        AND column_name = 'Value'\n  
      AND data_type != 'text'\n    ) > 0,\n    'ALTER TABLE Preferences MODIFY V
alue text;',\n    'SELECT 1'\n));\n\nPREPARE alterIfExists FROM @preparedStateme
nt;\nEXECUTE alterIfExists;\nDEALLOCATE PREPARE alterIfExists;\n\nSET @preparedS
tatement = (SELECT IF(\n    (\n        SELECT COUNT(*) FROM INFORMATION_SCHEMA.S
TATISTICS\n        WHERE table_name = 'Preferences'\n        AND table_schema = 
DATABASE()\n        AND index_name = 'idx_preferences_category'\n    ) > 0,\n   
 'SELECT 1',\n    'CREATE INDEX idx_preferences_category ON Preferences(Category
);'\n));\n\nPREPARE createIndexIfNotExists FROM @preparedStatement;\nEXECUTE cre
ateIndexIfNotExists;\nDEALLOCATE PREPARE createIndexIfNotExists;\n\nSET @preparedStatement = (SELECT IF(\n    (\n        SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS\n        WHERE table_name = 'Preferences'\n        AND table_schema = DATABASE()\n        AND index_name = 'idx_preferences_name'\n    ) > 0,\n    'SELECT 1',\n    'CREATE INDEX idx_preferences_name ON Preferences(Name);'\n));\n\nPREPARE createIndexIfNotExists FROM @preparedStatement;\nEXECUTE createIndexIfNotExists;\nDEALLOCATE PREPARE createIndexIfNotExists;\n\nCREATE PROCEDURE RenameSolarizedThemeWithUnderscore()\nBEGIN\n    DECLARE finished INTEGER DEFAULT 0;\n    DECLARE curUserId VARCHAR(26);\n    DECLARE curName VARCHAR(32);\n    DECLARE curValue text;\n\n    DECLARE preference\n        CURSOR FOR\n            SELECT UserId, Name, Value\n            FROM Preferences\n            WHERE Category = 'theme' AND Value LIKE '%solarized_%';\n\n    -- declare NOT FOUND handler\n    DECLARE CONTINUE HANDLER\n    FOR NOT FOUND SET finished = 1;\n\n    OPEN preference;\n\n    getPreference: LOOP\n        FETCH preference INTO curUserId, curName, curValue;\n        IF finished = 1 THEN\n            LEAVE getPreference;\n        END IF;\n\n        -- update affected rows\n        UPDATE Preferences\n        SET Value = replace(curValue, 'solaraized_', 'solarized-')\n        WHERE Category = 'theme'\n        AND UserId = curUserId\n        AND Name = curName;\n    END LOOP getPreference;\nEND;\n\nCALL RenameSolarizedThemeWithUnderscore();\n\nDROP PROCEDURE IF EXISTS RenameSolarizedThemeWithUnderscore;\n\nSET @preparedStatement = (SELECT IF(\n    (\n        SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS\n        WHERE table_name = 'Preferences'\n        AND table_schema = DATABASE()\n        AND index_name = 'idx_preferences_user_id'\n    ) > 0,\n    'DROP INDEX idx_preferences_user_id ON Preferences;',\n    'SELECT 1'\n));\n\nPREPARE removeIndexIfExists FROM @preparedStatement;\nEXECUTE removeIndexIfExists;\nDEALLOCATE PREPARE removeIndexIfExists;\n\n"}
Aug 06 05:38:50 mmtest systemd[1]: mattermost.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited

```

#### Possible fixes
Not sure, whether this one is correct, but at least migration got finished and server started:
```
ALTER DATABASE mmtest CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```
Before the default was `utf8mb4_unicode_ci`.

#### Question
Shouldn't the server explicitly specify, which charset and collation should be used to avoid any headaches?

**Comment by agnivade** [comment]
Hi @jelmd - Ideally the collation is a user specific setting and something the admin should set depending on their language preferences. That's why we avoid setting the values by ourselves. We do have some checks that check for differences between connection collation and database collation, but it is up to the admins to fix it for themselves.

We do have the scenario documented here: https://docs.mattermost.com/install/self-managed-changelog.html#id59

**Comment by jelmd** [comment]
Ooops, isn't this an application specific database? Shouldn't the application dictate, what it needs/expects? If anyone may choose charset and collation on desire, and the app does not correct it, the app is unreliable/inconsistent and may break any time (e.g. if it gets xfered to another db, where the global defaults are different)?

BTW: The problem happens with 6.3.9 - the docs you refer to say, starting with 6.4.0 ...

**Comment by agnivade** [comment]
Ideally, an application should be agnostic of user language preferences. The application cannot know which language the user will use, and hence cannot dictate what it needs. If the admin transfers the data to another database, they are responsible to maintain the same global defaults.

The error message that you are showing only exists from 6.4.0 onwards. It seemed like you were already on 6.3.9 and trying to upgrade to 7.1.2. Can you clarify if that is not correct?

**Comment by jelmd** [comment]
Hi @agnivade,

> Ideally, an application should be agnostic of user language preferences.

Hmmm, if this means, that it should always work and produce consistent results no matter, what the current settings are, then yes.

> The application cannot know which language the user will use,

Well, app channel settings, app user profile, app defaults, browser settings - it seems that there are a lot of ways to determine/know/set, what should be used.

> and hence cannot dictate what it needs.

Sure it can. And IMHO it actually should, otherwise it is more or less a lottery game and as shown even essential things like app's own db migrations break ...

> If the admin transfers the data to another database, they are responsible to maintain the same global defaults.

But what if they can't change the DB defaults because there is another ignorant app which got already deployed to the DB which should accommodate other "to be consolidated" instances? I think there are good reasons, that at least mySQL (and probably others, too) allow one to set defaults per db instance, per table and even per connection ...

> The error message that you are showing only exists from 6.4.0 onwards. It seemed like you were already on 6.3.9 and trying to upgrade to 7.1.2. Can you clarify if that is not correct?

Yes, "extended release" to "extended release". 6.4.x is an intermediate, isn't it?

**Comment by agnivade** [comment]
Thinking some more, it would be somewhat possible to map the `DefaultServerLocale` config value to a DB collation value, but it's not exactly clear what the mapping should be. Alternatively, the collation value can be a config option and the application can directly set the collation from the config.

> Yes, "extended release" to "extended release". 6.4.x is an intermediate, isn't it?

I was referring to your statement: `BTW: The problem happens with 6.3.9 - the docs you refer to say, starting with 6.4.0 ...`.

The error message you are seeing is only present from 6.4 onwards. Which means the problem doesn't happen in 6.3.9, but from 6.4 onwards.

Anyways, I think it's definitely possible to expose a config option for DB collation and let the application set that. However, that seems to be a problem specific to MySQL, so it would be a bit weird to have a config setting only for MySQL. If you find a clean solution, definitely send a PR, and I'll be happy to look into it.

I will close the issue since the original problem seems to have resolved.
