### ISSUE TITLE
channel files does not work anymore after upgrade to 7.1.2

### ISSUE THREAD

**Issue by jelmd** [mattermost/mattermost-server#20780]
#### Summary
After upgrade from 6.3.9 to 7.1.2 `channel files` in the web client (FF) does not show any files anymore.

#### Steps to reproduce
Upgrade from 6.3.9 to 7.1.2, go to a channel which has any attachments and click on `channel files`.

#### Expected behavior
Right sidebar should show all attachments of the channel.

#### Observed behavior (that appears unintentional) 
The sidebar shows the `No files yet` page. The mattermost logfile shows entries like this each time on clicks on the `channel files` button:
```
{"timestamp":"2022-08-06 20:13:41.270 Z","level":"warn","msg":"error getting channel id by name from in filter","caller":"app/post.go:1280","error":"GetChannelByName: Channel does not exist., resource: Channel id: TeamId=1yjgt17r53f5dcfszz1taxm7er&Name=bfem1r9xj7ry7cqwwec8uhnpcc"}
{"timestamp":"2022-08-06 20:13:41.273 Z","level":"warn","msg":"error getting channel id by name from in filter","caller":"app/post.go:1280","error":"GetChannelByName: Channel does not exist., resource: Channel id: TeamId=1yjgt17r53f5dcfszz1taxm7er&Name=bfem1r9xj7ry7cqwwec8uhnpcc"}
```

#### Possible fixes
n/a

**Comment by amyblais** [comment]
@jelmd What browser do you use? Do you see this issue on our community server https://community.mattermost.com/?

**Comment by jelmd** [comment]
@amyblais FF 100.0 (64-bit) on Ubuntu 20.4 (focal)

**Comment by amyblais** [comment]
I wasn't able to reproduce this. Would you be open to raising this issue at https://community.mattermost.com/core/channels/peer-to-peer-help or at https://forum.mattermost.com/? One of our community or staff members may be able to help troubleshoot this.

**Comment by jelmd** [comment]
Hi Amy,

I checked the FileInfo tables from the old and new instance. The old one had ~12K, and the new one ~2.5K entries. So dropped the FileInfo table, pulled in the dump of it from the old instance and applied the FileInfo related migration steps manually. This solved the problem.
