### ISSUE TITLE
Go path causes errors in dependent libraries

### ISSUE THREAD

**Issue by parnic-sks** [mattermost/mattermost-server#20817]
#### Summary
Mattermost's go.mod path is defined as /v6, but the version number is actually 7.x, which causes complaints when other applications try to depend on Mattermost

#### Steps to reproduce
In another Go application, run `go get github.com/mattermost/mattermost-server/v6@v7.2.0`

#### Expected behavior
Import is successfully added

#### Observed behavior (that appears unintentional) 
Receive error message
```
go: github.com/mattermost/mattermost-server/v6@v7.2.0: invalid version: module path includes a major version suffix, so major version must match
```

This is preventing, for example, Github's Dependabot from being able to trigger new builds of the Mattermost additional-platforms project over at https://github.com/SmartHoneybee/ubiquitous-memory where the auto-update script is currently encountering this:
> go: errors parsing go.mod:
/go.mod:6:2: require github.com/mattermost/mattermost-server/v6: version "v7.1.2" invalid: should be v6, not v7

And for full coverage, attempting to use an (invalid) /v7 suffix results in:
```
go: github.com/mattermost/mattermost-server/v7@v7.2.0: invalid version: go.mod has non-.../v7 module path "github.com/mattermost/mattermost-server/v6" (and .../v7/go.mod does not exist) at revision v7.2.0
```

#### Possible fixes
Change the go.mod path for Mattermost to `github.com/mattermost/mattermost-server/v7`

cc @kemenaran

**Comment by amyblais** [comment]
Opened a ticket for our team https://mattermost.atlassian.net/browse/CLD-3953.

**Comment by isacikgoz** [comment]
Thanks for the feedback @parnic-sks! We haven't updated our module version yet as you mentioned. But as a workaround you can point the commit hash as `87cbeafd36` for `v7.2.0` for instance. You should be able to update your dependency with following command:

```
go get github.com/mattermost/mattermost-server/v6@87cbeafd36
```

Meanwhile, we will discuss the timing about upgrading the version of the module.

**Comment by parnic-sks** [comment]
Thanks! Unfortunately this doesn't allow Dependabot to easily find newer versions, but we'll keep doing manual updates until the module version is incremented. 🙂

**Comment by agnivade** [comment]
Hello @parnic-sks - sorry to hear about this. Unfortunately, Mattermost release versions are now separate that Mattermost module versions. The release versions are controlled by our product team, and they are free to bump up to new major versions depending on if there are brand new features to publicize.

Unfortunately, this decision is out of our hands, and will break a lot of idiomatic module upgrade workflow. For now, the solution is to pin to a given commit hash. But I will raise this again to the product team to make them aware.

Thanks for raising this!
