### ISSUE TITLE
API v4 get /users pagination does not work

### ISSUE THREAD

**Issue by thepra** [mattermost/mattermost-server#20810]
#### Summary
The `per_page` query parameter is not respected and returns always a max. of 200 records.

#### Steps to reproduce
/api/v4/users?page=0&per_page=2000

#### Expected behavior
Get 2000 records

#### Observed behavior (that appears unintentional) 
Got 200 max. records

#### Possible fixes
Make `page` & `per_page` apply to the query correctly

**Comment by thepra** [comment]
Just a guess but `OrderBy`, `Offset` and `Limit` shouldn't be applied at the end of the `query` instead of at the beginning?
![immagine](https://user-images.githubusercontent.com/7032509/184310449-8d265765-ac88-49c2-91b0-5a14f213af40.png)

**Comment by amyblais** [comment]
@thepra Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this question.

**Comment by amyblais** [comment]
Closing this for now. Please let me know if you'd prefer re-opening this, or if you've had a chance to ask about this either at [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/. Our community and developers will likely be able to help with this.
