### ISSUE TITLE
Still having MTA for Googlemail with 7.2.0

### ISSUE THREAD

**Issue by dragonpil** [mattermost/mattermost-server#20828]
So the regular notification error is gone with 7.2.0 here I don't get the MTA any more. 
I still get the MTA for google addresses  for:

- invitation to a team by email-address
- Welcome Email  after invitation 
- Password reset mails

Can we reopen this one or should I create a new one?
Robert

_Originally posted by @dragonpil in https://github.com/mattermost/mattermost-server/issues/20604#issuecomment-1216280999_

**Comment by amyblais** [comment]
Thanks, opened: https://mattermost.atlassian.net/browse/MM-46416.

**Comment by luvwinnie** [comment]
same problem happening here, is this already been solved?

**Comment by anx-ag** [comment]
I have no idea what I'm doing, but [this PR](https://github.com/mattermost/mattermost-server/pull/20891) should fix it.

**Comment by agnivade** [comment]
https://github.com/mattermost/mattermost-server/pull/18232 did the initial work on this by passing the Message-ID for only thread reply mails but not others.

For anyone looking to fix this, please take a look at the comment [here](https://github.com/mattermost/mattermost-server/pull/20891#discussion_r956675479). 

The domain for the message-id should be the hostname of the SiteURL. We should change that here: https://github.com/mattermost/mattermost-server/blob/7deb408898aaf88aa4644652d7f250a26fb5bdbc/app/notification_email.go#L116, and also get that via the smtp config in the case where message-id is not passed.

And for the unique identifier, we can do a `model.NewRandomString - time.Now()`. Therefore, the full id should be `model.NewRandomString - time.Now() @ hostname >`

cc @engineereng in case you are still interested :)

**Comment by anx-ag** [comment]
Basically the message id needs to generated and can be unique - what agnivade was trying to say here is that you could create a random string in the local part of the message ID + the current timestamp. So let's say `model.newRandomString` returns `alskdjflasjdfasf` and `time.Now()` returns `1223492898234` and the hostname of your mattermostserver is `mattermost.mycompany.com`, then the resulting messageid would be:

`<alskdjflasjdfasf-1223492898234@mattermost.mycompany.com>`

**Comment by Azanul** [comment]
@anx-ag Do we have any specifications for the ```newRandomString``` ? also, does it need to be added in model ?

**Comment by anx-ag** [comment]
I'm not sure I understand this question, sorry. This is a function available in `model/utils.go`:

```golang
// NewRandomString returns a random string of the given length.
// The resulting entropy will be (5 * length) bits.
func NewRandomString(length int) string {
        data := make([]byte, 1+(length*5/8))
        rand.Read(data)
        return encoding.EncodeToString(data)[:length]
}
```

**Comment by Azanul** [comment]
@anx-ag You gave me the correct answer without understanding the question.

**Comment by agnivade** [comment]
Thank you @anx-ag for jumping in! And thank you @Azanul for offering to help on this! Let me know how it goes.

**Comment by Azanul** [comment]
@agnivade, I've done the task and raised the PR, do check it out and let me know how I may improve.
