### ISSUE TITLE
Highlighting part of a code block and choosing "Copy" copies the entire code block, instead of the portion highlighted

### ISSUE THREAD

**Issue by blueapple128** [mattermost/mattermost-server#20826]
#### Summary
Highlighting part of a code block and choosing "Copy" copies the entire code block, instead of the portion highlighted

#### Steps to reproduce
- Type a multiline code block (the kind surrounded by three backticks)
- Highlight a portion of the code block
- Right click -> Copy (instead of "Copy code block")
- Paste somewhere else

Reproduces on Version 5.1.1 of Ubuntu 20 desktop client, Ubuntu 20 Firefox client, and Ubuntu 18 Chrome client.

#### Expected behavior
- Only the highlighted portion is pasted.

#### Observed behavior (that appears unintentional) 
- The entire code block is pasted instead.

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-46415.

**Comment by amyblais** [comment]
Closing as there is a Help Wanted issue open for this.
