### ISSUE TITLE
New users are not receiving mattermost activation email

### ISSUE THREAD

**Issue by vmuoio23** [mattermost/mattermost-server#20832]
<img width="1195" alt="Console log" src="https://user-images.githubusercontent.com/104649227/184920280-476b112e-ca9e-4667-8a70-29a8e8260289.png">

New users are not receiving mattermost activation email (not in junk or inbox yet).

**Comment by amyblais** [comment]
@vmuoio23 Would you be able to help share more details on:

1. Your Mattermost server version.
2. OS and version.
3. Reproduction steps.
4. Any server log errors.

**Comment by vmuoio23** [comment]
We were able to resolve the issue, thank you
