### ISSUE TITLE
entrypoint.sh not returnig the value of {$DOMAIN}

### ISSUE THREAD

**Issue by Gedulis12** [mattermost/mattermost-server#20856]
#### Summary
Docker container is restarting after being deployed

#### Steps to reproduce
Following the exact steps in https://mattermost.com/deploy/

#### Expected behavior
Expecting docker container to spin up into "Up" state

#### Observed behavior (that appears unintentional) 
Docker container stays in "Restarting" state after `sudo docker-compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d` command
`docker ps` output:
```
CONTAINER ID   IMAGE                                          COMMAND                  CREATED          STATUS                          PORTS                                                                        NAMES
f82e0157fd89   mattermost/mattermost-enterprise-edition:7.1   "/entrypoint.sh matt…"   5 minutes ago    Restarting (1) 54 seconds ago                                                                                docker_mattermost_1
dc139a4b0d44   postgres:13-alpine                             "docker-entrypoint.s…"   5 minutes ago    Up 5 minutes                    5432/tcp                                                                     docker_postgres_1
```
`docker logs f82e0157fd89` output:
```
Error: failed to load configuration: failed to create store: unable to load on store creation: invalid config: Config.IsValid: Site URL must be a valid URL and start with http:// or https://., parse "https://${DOMAIN}": invalid character "{" in host name
Usage:
  mattermost [flags]
  mattermost [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  db          Commands related to the database
  export      Export data from Mattermost
  help        Help about any command
  import      Import data.
  jobserver   Start the Mattermost job server
  server      Run the Mattermost server
  version     Display version information

Flags:
  -c, --config string   Configuration file to use.
  -h, --help            help for mattermost

Use "mattermost [command] --help" for more information about a command.
```

#### Possible fixes
Looks like the issue is in entrypoint.sh, instead of returning value for variable {$DOMAIN} the script uses it as a literal string "{$DOMAIN}"

**Comment by amyblais** [comment]
@Gedulis12 Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this question.

**Comment by anx-ag** [comment]
Hi @Gedulis12 ,

the problem most likely is that your `docker-compose` version is too old. Please see [this forum post](https://forum.mattermost.com/t/setting-up-using-docker/13891/10?u=agriesser) which talks about this issue. tl;dr: you need to update your docker-compose version.

**Comment by Gedulis12** [comment]
@anx-ag , Thank you, updating docker-compose has fixed the issue.
