### ISSUE TITLE
*WebConn.Session.Props seems to be vulnerable to concurrent reads/writes

### ISSUE THREAD

**Issue by ITCDEK** [mattermost/mattermost-server#20880]
#### Summary
*WebConn.Session.Props seems to be vulnerable to concurrent reads/writes  

#### Steps to reproduce
Version is 7.1.2 Team Ed.  
Cause is [here](https://github.com/mattermost/mattermost-server/blob/master/app/web_conn.go#L792), as of current appearance.
To reproduce, make concurrent read\write to *WebConn.Session.Props or just wait one month or so.  

#### Expected behavior
Push notifications should not fail server's state

#### Observed behavior (that appears unintentional) 
Once in a month, we get our server down with this log:
Aug 25: fatal error: concurrent map read and map write  
Aug 25: goroutine 4297 [running]:  
Aug 25: runtime.throw({0x2337125?, 0x44f372?})  
Aug 25: runtime/panic.go:992 +0x71 fp=0xc030c4b4e8 sp=0xc030c4b4b8 pc=0x437af1  
Aug 25: runtime.mapaccess1_faststr(0x1fe8840?, 0xc038eaff40?, {0x22c0684, 0x8})  
Aug 25: runtime/map_faststr.go:22 +0x3a5 fp=0xc030c4b550 sp=0xc030c4b4e8 pc=0x4148a5  
Aug 25: github.com/mattermost/mattermost-server/v6/app.(*WebConn).shouldSendEvent(0xc00619e2a0, 0xc02c7f9800)  
Aug 25: github.com/mattermost/mattermost-server/v6/app/web_conn.go:792 +0x730 fp=0xc030c4b768 sp=0xc030c4b550 pc=0x1ac25f0  

#### Possible fixes
Do not protect entire *Session with atomic.Value, protect it's fields (i.e. Props)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-46604.
