### ISSUE TITLE
(Web)client: reaction emoji overlay is blocking part of the message it belongs to

### ISSUE THREAD

**Issue by Jay2k1** [mattermost/mattermost-server#20923]
#### Summary
When hovering over a chat message, the reaction emoji overlay appears and (potentially) blocks part of the message if it's long enough (or the window/viewport small enough), making it impossible to select part of the message to copy

#### Steps to reproduce
Using macOS mattermost from App Store (5.1.1) and the web client of mattermost server 7.0.1. Write a message long enough to get close to the right side of the viewport and then try to select part of the message with your mouse.

#### Expected behavior
Even when hovering over the message, I expect the full message to be visible and I expect to be able to select any part of it for copying

#### Observed behavior (that appears unintentional) 
Part of the message becomes blocked by the reaction overlay, because it's rendered directly over the message, instead of above it.
Here's my message:

![image](https://user-images.githubusercontent.com/2070503/187697816-ec008978-8e4f-4d01-b3c6-a76b184ed923.png)

I want to copy the bash command, but when I move the mouse over the message, the overlay pops up and doesn't let me:

![image](https://user-images.githubusercontent.com/2070503/187700477-fefc048c-2f0b-44f9-a958-27e353805da9.png)

#### Possible fixes
Render the reaction picker somewhere else, maybe above a message, like Discord does:

![image](https://user-images.githubusercontent.com/2070503/187701263-ecf152ce-69a4-42f9-b25f-9d167af558dd.png)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-46819.

**Comment by babinderrathi** [comment]
I would like to work on this .
