### ISSUE TITLE
Preview images that are a lot higher than larger overflow their container

### ISSUE THREAD

**Issue by bfontaine** [mattermost/mattermost-server#20936]
#### Summary
If you paste a link to a website with an `og:image` that’s a lot higher than larger, the image overflows on the top and the bottom.

#### Steps to reproduce
* Mattermost Version: 7.1.3
* Database Schema Version: 89
* Database: postgres

1. Paste this URL into a chat message: https://files.bxapp.eu/m.html

This is a test HTML file that contains `<meta property="og:image" content="https://files.bxapp.eu/p.jpg" />` in its header. This `p.jpg` is a cropped pony image of dimensions 1280x2470.

You can see the issue in the wild with this URL as well: https://mypresta.eu/modules/administration-tools/delete-orders-free.html

#### Expected behavior
The image preview should not overflow its container.

#### Observed behavior (that appears unintentional)
The image overflows its container.

If there is no focus, the image takes the full height of the message:
![focus on the message](https://user-images.githubusercontent.com/1334295/188117933-a54d79a1-8582-4bb8-bd09-1a6738e5c3fd.png)

If you focus on the message, it takes the full height of the chat messages container:
![no focus](https://user-images.githubusercontent.com/1334295/188117930-6d10aa3c-a29b-484a-b728-9ef1359fbaa0.png)

**Comment by amyblais** [comment]
@bfontaine I wasn't able to reproduce this on the latest version (v7.2) and I believe this is fixed with https://mattermost.atlassian.net/browse/MM-45505. Feel free to do some testing at https://community.mattermost.com/ and let me know if you still can reproduce it.

**Comment by bfontaine** [comment]
Yes @amyblais I can confirm it has been fixed. Thank you; sorry I didn’t find that issue when I searched in Jira.
