### ISSUE TITLE
Jitsi not working - channel not found 

### ISSUE THREAD

**Issue by timowevel1** [mattermost/mattermost-server#20964]
#### Summary
Once a user tries to start a meeting using the standard jitsi server, after clicking on "Join Meeting" the error
`
Channel Not Found
The channel you're requesting is private or does not exist. Please contact an Administrator to be added to the channel.`
appears.

#### Steps to reproduce
Start a Jitsi Meeting

#### Expected behavior
Not sure, I guess a meeting gets started/you get redirected into the meeting?

#### Observed behavior (that appears unintentional) 
"Channel Not Found
The channel you're requesting is private or does not exist. Please contact an Administrator to be added to the channel."

It redirects to this link: https://domain.com/standard/channels/meet.jit.si/StrongBonobosQuestionAccusingly#config.callDisplayName=%22Jitsi%20Meeting%22
Maybe a wrong redirect?

**Comment by amyblais** [comment]
I'll close this here as you opened an issue at the Jitsi repo - thank you!
