### ISSUE TITLE
CPU spike following 7.1 upgrade 

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-server#21012]
#### Summary
Following 6.8 to 7.1 upgrade CPU usage is 20% higher

NOTE:
- I do not have video calling, screen sharing, or collapsed reply threads enabled
- Using Mattermost free via GitLab Omnibus 15.3 with PostgreSQL 12.10

#### Steps to reproduce
See above

#### Expected behavior
CPU usage should not have changed

#### Observed behavior (that appears unintentional) 
CPU usage is 20% higher

#### Possible fixes
No idea

Related: https://forum.mattermost.com/t/database-performace-has-degraded-considerable-after-upgrading-to-7-1/14014, https://forum.mattermost.com/t/unable-to-get-the-file-count-for-the-channel/13859

**Comment by anx-ag** [comment]
Hi,

since you already linked some forum posts: Did you also try the suggestions in there and if so, which of them have you tried with what results?

**Comment by agnivade** [comment]
Hello @bbodenmiller - to clarify it is the CPU of the Mattermost instance which is 20% higher? Is it consistently high, or has spikes? Would you be able to capture a CPU profile for the period and post it here?

cc @agarciamontoro

**Comment by bbodenmiller** [comment]
@agnivade yes the Mattermost instance. It is consistently high during the workday. How do I capture a CPU profile?

**Comment by bbodenmiller** [comment]
@anx-ag 

- https://forum.mattermost.com/t/unable-to-get-the-file-count-for-the-channel/13859 just calls for a bigger server. This is already running on a big server and getting more resources is not trivial.
- https://forum.mattermost.com/t/database-performace-has-degraded-considerable-after-upgrading-to-7-1/14014 says to disable insights but this is a Mattermost free version so that shouldn't be relevant. I ran `VACUUM VERBOSE ANALYZE;`

**Comment by agnivade** [comment]
@bbodenmiller - If you set MetricsSettings.Enable to `true`, you can run `curl http://localhost:8067/debug/pprof/profile?seconds=10 -o cpu.pprof` to get a CPU profile.

More information here: https://docs.mattermost.com/scale/performance-monitoring.html#standard-go-metrics. These are available in the free edition.

**Comment by agarciamontoro** [comment]
Another question just to understand the impact: you mention that the CPU usage is 20% higher, but how high is it in absolute terms? And how was it before?

**Comment by bbodenmiller** [comment]
It is maxing out the system. See below, upgrade was completed 9/9.

![image](https://user-images.githubusercontent.com/1192780/190594033-279dd1f8-7bbb-4092-b502-83eb54bc9c8b.png)

**Comment by bbodenmiller** [comment]
@agnivade how can I view the content of `cpu.pprof`?

**Comment by agnivade** [comment]
Here is the official blog on that: https://go.dev/blog/pprof, but there are hundreds of articles on the web that explains it as well. The profile does not contain any sensitive info if that's what you are thinking.

**Comment by anx-ag** [comment]
Can you install [pg_activity](https://github.com/dalibo/pg_activity), run it and see if there are any specific queries that cause the high CPU usage?
