### ISSUE TITLE
 Incoming Webhooks do not handle Attachment Actions properly 

### ISSUE THREAD

**Issue by crrdean** [mattermost/mattermost-server#21036]
#### Summary
Incoming Webhooks do not handle attachment actions properly

#### Steps to reproduce
1. Create an incoming webhook.
2. Send webhook data containing an input attachment (button, dropdown)
3.
```json
{
    "username": "Bot",
    "channel":"@username",
    "attachments":[
    {
      "actions": [
        {
          "id": "test",
          "name": "Click Me",
          "integration": {
            "context": {
              "action": "do_something"
            },
            "url": "https://test.test/action"
          }          
        }
      ]
    }
  ]
}
```
4. Click on the button/dropdown

#### Expected behavior
I would expect the buttons to work the same was as if they were implemented through a Plugin.

#### Observed behavior (that appears unintentional) 
Neither the URL nor the Context are handled properly.  It turns into a 400 error and I can see that the provided URL is not used and the provided Context is not in the payload.

#### Possible fixes
I believe the incoming webhook files are not properly handing off the attachments.

**Comment by mickmister** [comment]
I made an issue for documentation here https://github.com/mattermost/mattermost-developer-documentation/issues/1115

**Comment by crrdean** [comment]
Thank you.  Would you like me to close this?

**Comment by mickmister** [comment]
@crrdean Sounds good to me 🙂
