### ISSUE TITLE
Show/Hide Formatting pointless

### ISSUE THREAD

**Issue by ariephim** [mattermost/mattermost-server#21046]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. If you have having issues, please send us a message in the [Peer-to-peer Help](https://community-daily.mattermost.com/core/channels/peer-to-peer-help) or the [Developers: Desktop App](https://community-daily.mattermost.com/core/channels/desktop-app) channels on the Mattermost Community server
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The Formatting toolbar takes up previously available space. It has a hide button that removes the toolbars functionality, but reclaims no space.

**Steps to reproduce**
Ctrl+Alt+T or click the button present in any mattermost desktop post 7.0

**Expected behavior**
Hides the toolbar to get space back, or possibly an advanced setting to hide toolbar

**Observed behavior**
Button is worthless

**Possible fixes**
Allow user to regain the old message box, the toolbar provides 0 additional functionality for those already familiar with markdown and serves no purpose but to consume space.

**Comment by devinbinnie** [comment]
Moved to server repo since this is a webapp issue not a desktop app issue.

**Comment by amyblais** [comment]
There is an existing ticket open: https://mattermost.atlassian.net/browse/MM-45008.
