### ISSUE TITLE
mattermost-push-proxy not send push

### ISSUE THREAD

**Issue by serjsv87** [mattermost/mattermost-server#21111]
installed mattermost-push-proxy on the server, as well as on the docker. But push notifications do not come. Although there are no errors and I get a positive answer.
in log all good

```
INFO: 2022/09/22 14:23:59 logger.go:62: Push proxy server is initializing...
GitVersion:    v5.23.0
GitCommit:     f9e1e09570ad6363c2d7b8323b3575a73b6a7a0e
GitTreeState:  clean
BuildDate:     '2022-04-26T11:34:53Z'
GoVersion:     go1.17.6
Compiler:      gc
Platform:      linux/amd64

INFO: 2022/09/22 14:23:59 logger.go:62: Initializing Android notification server for type=android_rn
INFO: 2022/09/22 14:23:59 logger.go:62: Initializing Android notification server for type=android
INFO: 2022/09/22 14:23:59 logger.go:53: Server is listening on :8066


INFO: 2022/09/22 14:24:29 logger.go:62: Sending android push notification for device=android type=message ackId=dhdwxjcw8p8ruyz69w5ay9tnny
INFO: 2022/09/22 14:24:29 logger.go:62: Sending android push notification for device=android type=message ackId=mzg3nq7nm3n8dbao8k7waj511r
INFO: 2022/09/22 14:24:45 logger.go:62: Sending android push notification for device=android type=message ackId=suuishorgj8ti835q1jue64zbc

```

when test sending to firebase

```
 curl -X POST --header "Authorization: key=AAAxxx:xxxxxxeU3y5	" \
    --Header "Content-Type: application/json" \
    https://fcm.googleapis.com/fcm/send \
    -d '{"to":"dgjAaLV2SCGe5CEbgJwioO:APA91bFxxxxxxxxbC8s6cwAKwNuH9o","notification":{"title":"Hello333","body":"Yellow444"}}'
```

I get push.
I tried to parse the code. I saw that a similar request is going

````
     curl -X POST --header "Authorization: key=AAAxxx:xxxxxxeU3y5" \
    --Header "Content-Type: application/json" \
    https://fcm.googleapis.com/fcm/send \
    -d '{"to":"dgjAaLV2SCGe5CEbgJwioO:APA91bFxxxxxxxxxbC8s6cwAKwNuH9o","data":{"post_id":"post_id","id_loaded":"id_loaded","sender_id":"","sender_name":"sender_name","team_id":"team_id", "message":"message", "type": "message", "server_id": "9n5k1h3n3xxxxx8qnh"}, "priority": "high"}'

````

I get an answer

```
{"multicast_id":2435644366889326912,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1663859867379871%c366a54ef9fd7ecd"}]}
```

But the push does not come to the device

**I will be glad for any help**

**Comment by amyblais** [comment]
@serjsv87  Would you be open to raising this issue at https://community.mattermost.com/core/channels/peer-to-peer-help or at https://forum.mattermost.com/? One of our community or staff members will be able to help troubleshoot this.

**Comment by serjsv87** [comment]
yes, sure
for those who find this message, I will leave links where I left messages

https://community.mattermost.com/core/pl/abusw7w9c7ywdcjzaxapa5si6c
and

**Comment by amyblais** [comment]
Thank you, specifically the "Peer-to-peer Help" channel is a good one for posting troubleshooting questions https://community.mattermost.com/core/channels/peer-to-peer-help,

**Comment by serjsv87** [comment]
Thank you

чт, 22 вер. 2022, 21:56 користувач Amy Blais ***@***.***>
пише:

**Comment by amyblais** [comment]
Awesome, we can continue the discussion at https://community.mattermost.com/core/channels/peer-to-peer-help or at https://forum.mattermost.com/ if the issue comes back,
