### ISSUE TITLE
Visiting Mattermost on ChromeOS/Chromebook suggests I use desktop app

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-server#21125]
#### Summary
Visiting Mattermost on ChromeOS/Chromebook suggests I use desktop app which doesn't exist

#### Steps to reproduce
1. Visit https://community-daily.mattermost.com/ from ChromeOS
2. Notice it prompts user to use non-existent Desktop app

#### Expected behavior
No prompt to use Desktop app

#### Observed behavior (that appears unintentional) 
Prompts to use Desktop app

![image](https://user-images.githubusercontent.com/1192780/192148715-ee97e373-a818-46d7-945b-895155643785.png)

#### Possible fixes
Check user agent. On ChromeOS my user agent is like

`Mozilla/5.0 (X11; CrOS x86_64 x.x.0) AppleWebKit/x.x (KHTML, like Gecko) Chrome/x.0.0.0 Safari/x.x
`

**Comment by amyblais** [comment]
@bbodenmiller This was implemented via https://mattermost.atlassian.net/browse/MM-36439 / https://github.com/mattermost/mattermost-webapp/pull/10573. What do you mean by "non-existent desktop app"?

**Comment by amyblais** [comment]
What screen do you get when you click on "View in Desktop App"?

**Comment by bbodenmiller** [comment]
@amyblais since ChromeOS is generally just a browser there isn't any Mattermost desktop app for it.

**Comment by amyblais** [comment]
Got it, opened a ticket: https://mattermost.atlassian.net/browse/MM-47169.
