### ISSUE TITLE
`Team Admin` should not be allowed to post in private channels of `Users`

### ISSUE THREAD

**Issue by FaizanNehal** [mattermost/mattermost-server#21124]
#### Summary
There are 3 main roles the `system admin`, `team admin` and `user`. System admins have access to all the information and private data of every users but the access of team admin is limited as they are only there for managing the public channels. Now channels that are private are not visible to the team admin and they are not authorized to view them but through this vulnerability they are able to add messages into the private channels even if they are not part of it and cannot view them. The request is getting send to the endpoint /api/v4/posts

#### Steps to reproduce
You can reproduce by following the steps below:
 - Create a mattermost instance and add 3 memebers in it. One will be system admin, second will be team admin and third will be user.
 - Go to the user account and create a private channel and don't add the team admin into it.
 - Add a message in this private channel and intercept the request and send it to repeater.
 - Now replace the cookie of user with the cookie of team admin and add your own message and forward the request.
 - You will notice that a message from team admin will be added in the private channel and the team admin will not have the access still.

#### Expected behavior
`Team Admin` should not be allowed to post in private channels of `Users`

**Comment by amyblais** [comment]
@FaizanNehal What Mattermost server version are you on? What OS and version are you using?

**Comment by FaizanNehal** [comment]
I am using the latest version and the OS is MacOS 12.4 Monterey

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-47165.

**Comment by safakkizkin** [comment]
It's too early to say, but I'd like to take it!

**Comment by mkraft** [comment]
We're going to be having a discussion about whether membership in channels will be a requirement to read and post in private channels. I'll circle back with our decisions.

**Comment by amyblais** [comment]
The ticket was closed as won't fix. We use the permissions system not membership as a conditional for authz to post.
