### ISSUE TITLE
Failed to apply database migrations when migrating from 7.1 to 7.2

### ISSUE THREAD

**Issue by gregoryR** [mattermost/mattermost-server#21146]
#### Summary
Migration from Mattermost 7.1 to 7.2 fail with ` Failed to apply database migrations.`

#### Steps to reproduce
I'm using Mattermost server 7.1.2 bundled in the gitlab-ee 15.3.3-ee.0

Wen upgrading gitlab-ee to 15.4.0-ee.0 the Mattermost server fail to start after upgrade ; via `aptitude safe-ugrade`. I get 502 Bad Gateway accessing the web interface.

#### Expected behavior
The Mattermost server should restart normally.

#### Observed behavior (that appears unintentional) 
In the Mattermost logs I can see errors

```
root@vgitlab:~# gitlab-ctl  tail mattermost
...
{"timestamp":"2022-09-27 06:58:02.084 +02:00","level":"fatal","msg":"Failed to apply database migrations.","caller":"sqlstore/store.go:165","error":"driver: postgres, message: failed to execute migration, command: executing_query, originalError: pq: could not create unique index \"teams_name_key\", query: \n\nDO\n$$\nBEGIN\n  IF NOT EXISTS (SELECT * FROM pg_type typ\n                            INNER JOIN pg_namespace nsp ON nsp.oid = typ.typnamespace\n                        WHERE nsp.nspname = current_schema()\n                            AND typ.typname = 'channel_type') THEN\n    CREATE TYPE channel_type AS ENUM ('P', 'G', 'O', 'D');\n  END IF;\nEND;\n$$\nLANGUAGE plpgsql;\n\nALTER TABLE channels alter column type type channel_type using type::channel_type;\n\nDO\n$$\nBEGIN\n  IF NOT EXISTS (SELECT * FROM pg_type typ\n                            INNER JOIN pg_namespace nsp ON nsp.oid = typ.typnamespace\n                        WHERE nsp.nspname = current_schema()\n                            AND typ.typname = 'team_type') THEN\n    CREATE TYPE team_type AS ENUM ('I', 'O');\n  END IF;\nEND;\n$$\nLANGUAGE plpgsql;\n\nALTER TABLE teams alter column type type team_type using type::team_type;\n\nDO\n$$\nBEGIN\n  IF NOT EXISTS (SELECT * FROM pg_type typ\n                            INNER JOIN pg_namespace nsp ON nsp.oid = typ.typnamespace\n                        WHERE nsp.nspname = current_schema()\n                            AND typ.typname = 'upload_session_type') THEN\n    CREATE TYPE upload_session_type AS ENUM ('attachment', 'import');\n  END IF;\nEND;\n$$\nLANGUAGE plpgsql;\n\nALTER TABLE uploadsessions alter column type type upload_session_type using type::upload_session_type;\n\n"}
```

In the Postgresql logs :

```
root@vgitlab:~# gitlab-ctl tail postgresql
...
2022-09-27_05:58:14.75140 ERROR:  could not create unique index "teams_name_key"
2022-09-27_05:58:14.75143 DETAIL:  Key (name)=(stage-ia) is duplicated.
2022-09-27_05:58:14.75143 STATEMENT:  DO
2022-09-27_05:58:14.75143     $$
2022-09-27_05:58:14.75144     BEGIN
2022-09-27_05:58:14.75144       IF NOT EXISTS (SELECT * FROM pg_type typ
2022-09-27_05:58:14.75144                                 INNER JOIN pg_namespace nsp ON nsp.oid = typ.typnamespace
2022-09-27_05:58:14.75144                             WHERE nsp.nspname = current_schema()
2022-09-27_05:58:14.75144                                 AND typ.typname = 'channel_type') THEN
2022-09-27_05:58:14.75145         CREATE TYPE channel_type AS ENUM ('P', 'G', 'O', 'D');
2022-09-27_05:58:14.75145       END IF;
2022-09-27_05:58:14.75145     END;
2022-09-27_05:58:14.75145     $$
2022-09-27_05:58:14.75146     LANGUAGE plpgsql;
2022-09-27_05:58:14.75146     
2022-09-27_05:58:14.75146     ALTER TABLE channels alter column type type channel_type using type::channel_type;
2022-09-27_05:58:14.75146     
2022-09-27_05:58:14.75146     DO
2022-09-27_05:58:14.75147     $$
2022-09-27_05:58:14.75147     BEGIN
2022-09-27_05:58:14.75147       IF NOT EXISTS (SELECT * FROM pg_type typ
2022-09-27_05:58:14.75147                                 INNER JOIN pg_namespace nsp ON nsp.oid = typ.typnamespace
2022-09-27_05:58:14.75147                             WHERE nsp.nspname = current_schema()
2022-09-27_05:58:14.75148                                 AND typ.typname = 'team_type') THEN
2022-09-27_05:58:14.75148         CREATE TYPE team_type AS ENUM ('I', 'O');
2022-09-27_05:58:14.75148       END IF;
2022-09-27_05:58:14.75148     END;
2022-09-27_05:58:14.75148     $$
2022-09-27_05:58:14.75149     LANGUAGE plpgsql;
2022-09-27_05:58:14.75169     
2022-09-27_05:58:14.75180     ALTER TABLE teams alter column type type team_type using type::team_type;
2022-09-27_05:58:14.75185     
2022-09-27_05:58:14.75190     DO
2022-09-27_05:58:14.75194     $$
2022-09-27_05:58:14.75200     BEGIN
2022-09-27_05:58:14.75210       IF NOT EXISTS (SELECT * FROM pg_type typ
2022-09-27_05:58:14.75215                                 INNER JOIN pg_namespace nsp ON nsp.oid = typ.typnamespace
2022-09-27_05:58:14.75221                             WHERE nsp.nspname = current_schema()
2022-09-27_05:58:14.75225                                 AND typ.typname = 'upload_session_type') THEN
2022-09-27_05:58:14.75229         CREATE TYPE upload_session_type AS ENUM ('attachment', 'import');
2022-09-27_05:58:14.75232       END IF;
2022-09-27_05:58:14.75236     END;
2022-09-27_05:58:14.75248     $$
2022-09-27_05:58:14.75252     LANGUAGE plpgsql;
2022-09-27_05:58:14.75256     
2022-09-27_05:58:14.75260     ALTER TABLE uploadsessions alter column type type upload_session_type using type::upload_session_type;
2022-09-27_05:58:14.75264    
```
I reverted the upgrade using a vm snapshot

#### Possible fixes

After the revert I can access the web console.

In the Teams I can see two teams when searching for `stage-ia`

![mattermost-stage-ia](https://user-images.githubusercontent.com/1171861/192706451-ebb7d8d2-d3a4-4b72-98d2-ae1bf9b2dec8.png)

I don't know if they are the root of the problem : I can see one team with an hyphen `stage-ia` and one with an undescore `STAGE_IA`. Maybe there is an archived team with `stage-ia` name that I can't see in the web console ?

Before Mattermost 6 I used the `mattermost` cli command to list the teams.

Since 6 the `mattermost` cli have been replaced by `mmctl` but it don't work here. I've enabled the local mode

```
root@vgitlab:/opt/gitlab/embedded/service/mattermost# grep Local /var/opt/gitlab/mattermost/config.json
        "EnableLocalMode": true,
        "LocalModeSocketLocation": "/var/tmp/mattermost_local.socket",
    "LocalizationSettings": {
        "DefaultServerLocale": "en",
        "DefaultClientLocale": "en",
        "AvailableLocales": ""
        "LocaleAttribute": "",
```

and restarted the mattermost service

```
root@vgitlab:~# gitlab-ctl restart mattermost
ok: run: mattermost: (pid 1638) 0s
```

but the `mmctl` command keeps complaining about the lack of socket

```
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl --local team list
Error: socket file "/var/tmp/mattermost_local.socket" doesn't exists, please check the server configuration for local mode
```

In `/var/tmp` there's no socket

```
root@vgitlab:/opt/gitlab/embedded/service/mattermost# ls -la /var/tmp/
total 0
drwxrwxrwt  4 root root 171 Sep 28 00:00 .
drwxr-xr-x 11 root root 139 Apr 17  2018 ..
drwx------  3 root root  17 Sep 27 08:02 systemd-private-18a2f4d9ad07439aa4af355c978c6873-nagios-nrpe-server.service-QUOk29
drwx------  3 root root  17 Sep 27 08:02 systemd-private-18a2f4d9ad07439aa4af355c978c6873-ntp.service-4nzWdN
```

checked a permission pb but it don't seems to be the case. `mattermost` can write in this directory.

```
root@vgitlab:/opt/gitlab/embedded/service/mattermost# sudo -u mattermost touch /var/tmp/plop
root@vgitlab:/opt/gitlab/embedded/service/mattermost# ls -la /var/tmp/
total 0
drwxrwxrwt  4 root       root       183 Sep 28 06:58 .
drwxr-xr-x 11 root       root       139 Apr 17  2018 ..
-rw-r--r--  1 mattermost mattermost   0 Sep 28 06:58 plop
drwx------  3 root       root        17 Sep 27 08:02 systemd-private-18a2f4d9ad07439aa4af355c978c6873-nagios-nrpe-server.service-QUOk29
drwx------  3 root       root        17 Sep 27 08:02 systemd-private-18a2f4d9ad07439aa4af355c978c6873-ntp.service-4nzWdN
```

I'm stuck

**Comment by anx-ag** [comment]
Hi,

can you please post the output of the following SQL query:

```
SELECT * from teams;
```

With regards to the local mode: Can you confirm that after you restart Mattermost, the `LocalMode` Setting is still active in your `config.json`?
Did you maybe move the configuration to the database (which could explain why the setting doesn't work)?

You can try to set up `mmctl` with authentication via HTTPs in order to at least connect it to your instance to run additional commands for troubleshooting, like `mmctl config show` which would show us the "running" config of your Mattermost server to verify that the socket is being active and local mode is enabled.

**Comment by gregoryR** [comment]
Thanks for your quick reply

> can you please post the output of the following SQL query:
> 
> ```
> SELECT * from teams;
> ```

The complete dump may not be necessary now that I know the table

I can find two teams with stage-ia in the `name`. The `displayname` is different
I have exluded columns `email` and `inviteid`

```
mattermost_production=# select id,createat,updateat,deleteat,displayname,name,description,type,companyname,alloweddomains,lastteamiconupdate,schemeid,groupconstrained,cloudlimitsarchived from teams WHERE name LIKE '%stage-ia%';
             id             |   createat    |   updateat    | deleteat | displayname |   name   | description | type | companyname | alloweddomains | lastteamiconupdate | schemeid | groupconstrained | cloudlimitsarchived 
----------------------------+---------------+---------------+----------+-------------+----------+-------------+------+-------------+----------------+--------------------+----------+------------------+---------------------
 m3zxoj9djirs3fdst7zm8mc9io | 1612769908565 | 1612769908565 |        0 | stage-ia    | stage-ia |             | I    |             |                |                  0 |          |                  | f
 uc1j8ownpibf7fcqii61wcqyba | 1655904217548 | 1655904217548 |        0 | STAGE_IA    | stage-ia |             | O    |             |                |                  0 |          |                  | f
(2 rows)
```
Note : I'm no pro with postgresql but if I use `=` instead of `LIKE` to perform the search, it only retrieve 1 row. Maybe a problem with character encoding or a trailing space ? In don't understand why `=` show only one row. That maybe the root cause of the problem ?

```
mattermost_production=# select id,createat,updateat,deleteat,displayname,name,description,type,companyname,alloweddomains,lastteamiconupdate,schemeid,groupconstrained,cloudlimitsarchived from teams WHERE name='stage-ia';
             id             |   createat    |   updateat    | deleteat | displayname |   name   | description | type | companyname | alloweddomains | lastteamiconupdate | schemeid | groupconstrained | cloudlimitsarchived 
----------------------------+---------------+---------------+----------+-------------+----------+-------------+------+-------------+----------------+--------------------+----------+------------------+---------------------
 uc1j8ownpibf7fcqii61wcqyba | 1655904217548 | 1655904217548 |        0 | STAGE_IA    | stage-ia |             | O    |             |                |                  0 |          |                  | f
(1 row)
```

> With regards to the local mode: Can you confirm that after you restart Mattermost, the `LocalMode` Setting is still active in your `config.json`? Did you maybe move the configuration to the database (which could explain why the setting doesn't work)?
> 
> You can try to set up `mmctl` with authentication via HTTPs in order to at least connect it to your instance to run additional commands for troubleshooting, like `mmctl config show` which would show us the "running" config of your Mattermost server to verify that the socket is being active and local mode is enabled.

The settings is persisted yes in `config.json` even after restart

But I can't login in https mode I think. This Mattermost instance is bundled in gitlab. I don't have local user. Authentication is delegated to gitlab (via Oauth ?) The `root` user of gitlab instance have admin rights on Mattermost. But it's not a local user

```
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl auth login https://gitlabchat.ifremer.fr
Connection name: debug
Username: root
Password: 
Error: could not initiate client: : Enter a valid email or username and/or password, or sign in using another method.,
```

**Comment by anx-ag** [comment]
Thanks, that's interesting. So you're saying when you run `SELECT * from teams where name='stage-ia`;` that you only receive one row instead of two?
There's no "space" for a trailing space, otherwise the column would be broader.

Is there a specific reason why you have two teams with almost the same name? One being open and one being invite-only?

It would be interesting to see if you have users in both teams, so could you please run the following query:

``` 
select count(*) from teammembers where teamid='m3zxoj9djirs3fdst7zm8mc9io';
select count(*) from teammembers where teamid='uc1j8ownpibf7fcqii61wcqyba';
```

If one of the teams is empty, we might as well just choose to get rid of it to fix this problem.

I'm still thinking about the `mmctl` local issue - will get back to you once I have a better idea.

**Comment by gregoryR** [comment]
> so could you run the following command, please?
> 
> ```
> $ echo "select name from teams;" | psql mattermost | od -ch
> ```

Yes, no pure psclient on this server but I think I can use the gitlab equivalent

```
root@vgitlab:~# gitlab-psql -d mattermost_production -c "select name from teams where name LIKE '%stage-ia%';" | od -ch
0000000               n   a   m   e              \n   -   -   -   -   -
           2020    6e20    6d61    2065    2020    2d0a    2d2d    2d2d
0000020   -   -   -   -   -  \n       s   t   a   g   e   -   i   a  \n
           2d2d    2d2d    0a2d    7320    6174    6567    692d    0a61
0000040       s   t   a   g   e   -   i   a  \n   (   2       r   o   w
           7320    6174    6567    692d    0a61    3228    7220    776f
0000060   s   )  \n  \n
           2973    0a0a
0000064
```

> Is there a specific reason why you have two teams with almost the same name? One being open and one being invite-only?
> 
> It would be interesting to see if you have users in both teams, so could you please run the following query:
> 
> ```
> select count(*) from teammembers where teamid='m3zxoj9djirs3fdst7zm8mc9io';
> select count(*) from teammembers where teamid='uc1j8ownpibf7fcqii61wcqyba';
> ```
> 
> If one of the teams is empty, we might as well just choose to get rid of it to fix this problem.

When you create a group in gitlab, the creation of a corresponding Mattermost team is proposed

![gitlab-mattermost](https://user-images.githubusercontent.com/1171861/192762889-8d6ba9d4-e8fb-4722-97a4-1439bc2cab54.png)

It's now disabled by default but it was not always the case. gitlab's users didn't bother this checkbox and a lot of empty teams were created before I manage this preference.

I know that the open team have only one user, the creator of the gitlab group because I can see it in the web console. The name for the two teams are the same but the users are different

```
root@vgitlab:~# gitlab-psql -d mattermost_production -c "select count(*) from teammembers where teamid='m3zxoj9djirs3fdst7zm8mc9io';"
 count 
-------
     1
(1 row)

root@vgitlab:~#  gitlab-psql -d mattermost_production -c "select count(*) from teammembers where teamid='uc1j8ownpibf7fcqii61wcqyba';"
 count 
-------
     2
(1 row
```

I know that I can delete the team `m3zxoj9djirs3fdst7zm8mc9io` but in the web console I can only "archive" the team and I think that it will not resolve my problem. The line will be in the database and I think the migration will fail again. I make an assumption here, I can be wrong.

**Comment by agnivade** [comment]
It seems like your DB schema had incorrect constraints from the start. The `teams` table should have a `ADD CONSTRAINT teams_name_key UNIQUE (name);` which was added very early in Mattermost. The fact that it wasn't present caused this to be added in the first place.

To fix this, we either need to delete the team using mmctl (`mmctl delete <teamID>`), or rename the team with display name `STAGE_IA` to also have name `STAGE_IA`. And then add the constraint `teams_name_key UNIQUE (name)` to the table.

**Comment by gregoryR** [comment]
> It seems like your DB schema had incorrect constraints from the start. The `teams` table should have a `ADD CONSTRAINT teams_name_key UNIQUE (name);` which was added very early in Mattermost. The fact that it wasn't present caused this to be added in the first place.

The unique key seems to be there. Yes I know, that's weird `:(`

Every day I backup via pgdump the mattermost_production database. I can see the constraint. Relevant parts of the dump

```
CREATE TABLE public.teams (
    id character varying(26) NOT NULL,
    createat bigint,
    updateat bigint,
    deleteat bigint,
    displayname character varying(64),
    name character varying(64),
    description character varying(255),
    email character varying(128),
    type character varying(255),
    companyname character varying(64),
    alloweddomains character varying(1000),
    inviteid character varying(32),
    allowopeninvite boolean,
    lastteamiconupdate bigint,
    schemeid character varying(26),
    groupconstrained boolean,
    cloudlimitsarchived boolean DEFAULT false NOT NULL
);

ALTER TABLE public.teams OWNER TO gitlab_mattermost;

--
-- Name: teams teams_name_key; Type: CONSTRAINT; Schema: public; Owner: gitlab_mattermost
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_name_key UNIQUE (name);

--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: gitlab_mattermost
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);
```



> To fix this, we either need to delete the team using mmctl (`mmctl delete <teamID>`), or rename the team with display name `STAGE_IA` to also have name `STAGE_IA`. And then add the constraint `teams_name_key UNIQUE (name)` to the table.

That was my plan, but I can't. I hit another pb no `mmctl` console for me. `mmctl` is available

```
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl version
mmctl:
Version:	v7.0.1
GitCommit:	a60dace71816ac4e38567c1ef766e51cac3b3a20
GitTreeState:	"clean"
BuildDate:	2022-07-19T07:27:46Z
GoVersion:	go1.17
Compiler:	gc
Platform:	linux/amd64
```

But I can't use the `--local` option because even if LocalMode seems enabled in config.json there's no socket in `/var/tmp`

```
root@vgitlab:/opt/gitlab/embedded/bin# grep 'LocalMode' /var/opt/gitlab/mattermost/config.json
        "EnableLocalMode": true,
        "LocalModeSocketLocation": "/var/tmp/mattermost_local.socket",
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl --local config show
Error: socket file "/var/tmp/mattermost_local.socket" doesn't exists, please check the server configuration for local mode
```

And I can't use the remote authentification via https : all my users are SSO users. no local user. And I can't create a user through the web console ?

May I ALTER directly the team's `name` in the DB via `psql` ? Won't do this without confirmation.

**Comment by agnivade** [comment]
Can you run a `\dS+ teams` on your database and paste the output? If the constraint is there, it can only mean that the name has some empty characters around it.

Re: mmctl, can you check the file location of `/var/tmp/mattermost_local.socket` and ensure a file exists there?

Sure, you can change the team's name via psql. But deletion is only recommended via mmctl, as there are dependent rows which won't be deleted otherwise.

**Comment by gregoryR** [comment]
> Can you run a `\dS+ teams` on your database and paste the output? If the constraint is there, it can only mean that the name has some empty characters around it.

Yes here is the output, I think I can see the constraint

```
mattermost_production=# \dS+ teams
                                                  Table "public.teams"
       Column        |          Type           | Collation | Nullable | Default | Storage  | Stats target | Description 
---------------------+-------------------------+-----------+----------+---------+----------+--------------+-------------
 id                  | character varying(26)   |           | not null |         | extended |              | 
 createat            | bigint                  |           |          |         | plain    |              | 
 updateat            | bigint                  |           |          |         | plain    |              | 
 deleteat            | bigint                  |           |          |         | plain    |              | 
 displayname         | character varying(64)   |           |          |         | extended |              | 
 name                | character varying(64)   |           |          |         | extended |              | 
 description         | character varying(255)  |           |          |         | extended |              | 
 email               | character varying(128)  |           |          |         | extended |              | 
 type                | character varying(255)  |           |          |         | extended |              | 
 companyname         | character varying(64)   |           |          |         | extended |              | 
 alloweddomains      | character varying(1000) |           |          |         | extended |              | 
 inviteid            | character varying(32)   |           |          |         | extended |              | 
 allowopeninvite     | boolean                 |           |          |         | plain    |              | 
 lastteamiconupdate  | bigint                  |           |          |         | plain    |              | 
 schemeid            | character varying(26)   |           |          |         | extended |              | 
 groupconstrained    | boolean                 |           |          |         | plain    |              | 
 cloudlimitsarchived | boolean                 |           | not null | false   | plain    |              | 
Indexes:
    "teams_pkey" PRIMARY KEY, btree (id)
    "teams_name_key" UNIQUE CONSTRAINT, btree (name)
    "idx_teams_create_at" btree (createat)
    "idx_teams_delete_at" btree (deleteat)
    "idx_teams_invite_id" btree (inviteid)
    "idx_teams_scheme_id" btree (schemeid)
    "idx_teams_update_at" btree (updateat)
Access method: heap
```
> Re: mmctl, can you check the file location of `/var/tmp/mattermost_local.socket` and ensure a file exists there?
> 
> Sure, you can change the team's name via psql. But deletion is only recommended via mmctl, as there are dependent rows which won't be deleted otherwise.

This one is my bad, sorry `:-[` We just found the pb

In my `/etc/gitlab.gitlab.rb` I changed long time ago, I can't store mattermost data locally on the server (vm without a lot of space) There's an nfs mount on a filer for that

```
root@vgitlab:~# grep gitlabdata/mattermost /etc/gitlab/gitlab.rb 
mattermost['home'] = '/home/gitlabdata/mattermost'
mattermost['file_directory'] = "/home/gitlabdata/mattermost/data"
mattermost['plugin_directory'] = "/home/gitlabdata/mattermost/plugins"
mattermost['plugin_client_directory'] = "/home/gitlabdata/mattermost/client-plugins"
```

So the config.json used by Mattermost isn't `/var/opt/gitlab/mattermost/config.json` but `/home/gitlabdata/mattermost/config.json`

After an edit of the file and a restart of the I get my socket.

```
root@vgitlab:~# grep LocalMode /home/gitlabdata/mattermost/config.json 
        "EnableLocalMode": true,
        "LocalModeSocketLocation": "/var/tmp/mattermost_local.socket",
root@vgitlab:~# gitlab-ctl restart mattermost
ok: run: mattermost: (pid 30254) 0s
root@vgitlab:~# ls -l /var/tmp/mattermost_local.socket 
srw------- 1 mattermost mattermost 0 Sep 30 09:39 /var/tmp/mattermost_local.socket
root@vgitlab:~# cd /opt/gitlab/embedded/bin
```

and `mmctl` is available, exemple

```
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl --local team list
...
srh-bretagne
stage
stage-aurelie
stage-cell-dali
stagehugo
stage-ia
stageia
stage-ia
stageifremer
stage-ist-ric
stage-maelle
stage-pauline
stage-tc-2021
...
There are 463 teams on local instance
```

Not sure how I'll delete the *bad* team, the `team search` command return only one team

```
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl --local team search stage-ia
stage-ia: stage-ia (m3zxoj9djirs3fdst7zm8mc9io)
```

fortunatly it seems to be the one I want to delete, the one with a unique user : https://github.com/mattermost/mattermost-server/issues/21146#issuecomment-1260749092

**Comment by gregoryR** [comment]
> You can delete the bad team by passing the teamID. I definitely think there are some trailing spaces around the name which is causing it to pass the constraint, and also not return two teams as you'd expect.

I could, many thanks but only with the name not with ID

```
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl --local team delete m3zxoj9djirs3fdst7zm8mc9io
Unable to delete team 'stage-ia' error: : We encountered an error updating the team., 
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl --local team delete stage-ia
Deleted team 'stage-ia'
```

but... it seems the one deleted by name is not the one returned by `search' `:)`

```
root@vgitlab:/opt/gitlab/embedded/bin# gitlab-psql -d mattermost_production -c "select id,name,displayname from teams where name LIKE '%stage-ia%';"
             id             |   name   | displayname 
----------------------------+----------+-------------
 m3zxoj9djirs3fdst7zm8mc9io | stage-ia | stage-ia
(1 row)
```

**Comment by agnivade** [comment]
Interesting, I'd be curious to see the server logs when deleting the team by id. In any case, glad to see everything has worked well. If there's nothing else pending, please feel free to close the issue.

**Comment by gregoryR** [comment]
> Interesting, I'd be curious to see the server logs when deleting the team by id. In any case, glad to see everything has worked well. If there's nothing else pending, please feel free to close the issue.

It's possible, everything is possible `:)` Seems related to the constraint again

```
2022-09-30_08:15:48.02755 {"timestamp":"2022-09-30 10:15:48.027 +02:00","level":"error","msg":"We encountered an error updating the team.","caller":"web/context.go:105","path":"/api/v4/teams/m3zxoj9djirs3fdst7zm8mc9io","request_id":"ssendbbxxiry3mmqybbbuu4mer","ip_addr":"","user_id":"","method":"DELETE","err_where":"PermanentDeleteTeam","http_code":500,"err_details":"failed to update Team with id=m3zxoj9djirs3fdst7zm8mc9io: pq: duplicate key value violates unique constraint \"teams_name_key\""}
```

**Comment by gregoryR** [comment]
> If there's nothing else pending, please feel free to close the issue.

Upgrade done today, went smoothly

Thanks for all the help

```
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl --local system version
Server version 7.2.0.7.2.0.87db91c615603443c21a607cb3240c75.false
root@vgitlab:/opt/gitlab/embedded/bin# ./mmctl --local system status
Server status: OK
Android Latest Version: 
Android Minimum Version: 
Desktop Latest Version: <no value>
Desktop Minimum Version: <no value>
Ios Latest Version: 
Ios Minimum Version: 
Database Status: OK
Filestore Status: OK
```
