### ISSUE TITLE
mattermost-webapp build error, maybe related to React version 16 -> 17.

### ISSUE THREAD

**Issue by andrewwutw** [mattermost/mattermost-server#21178]
#### Summary

mattermost-webapp build failure on commit 8ca0eeefc . But build successfully on previous commit 83627c386 .

#### Steps to reproduce

Ubuntu 20.04.5 LTS (Focal Fossa)
node : v16.17.1
npm : 8.15.0

Run :

```bash
git clone https://github.com/mattermost/mattermost-webapp.git && cd mattermost-webapp
git co 8ca0eeefc
make
```

Failed. output is :

```
Getting dependencies using npm
node skip_integrity_check.js
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: dynamic-virtualized-list@1.0.0-beta
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@">=16.8.0" from @floating-ui/react-dom@0.7.2
npm ERR!   node_modules/@floating-ui/react-dom
npm ERR!     @floating-ui/react-dom@"0.7.2" from the root project
npm ERR!   19 more (@hot-loader/react-dom, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from dynamic-virtualized-list@1.0.0-beta
npm ERR! node_modules/dynamic-virtualized-list
npm ERR!   dynamic-virtualized-list@"github:mattermost/dynamic-virtualized-list#77a0cb4c565bc239bab1ce5414b95bdd9a570963" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^15.0.0 || ^16.0.0" from dynamic-virtualized-list@1.0.0-beta
npm ERR!   node_modules/dynamic-virtualized-list
npm ERR!     dynamic-virtualized-list@"github:mattermost/dynamic-virtualized-list#77a0cb4c565bc239bab1ce5414b95bdd9a570963" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/vagrant/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2022-10-03T08_58_43_116Z-debug-0.log
make: *** [Makefile:43: node_modules] Error 1
```

But if we checkout to the parent commit (83627c386) .

```bash
git co 83627c386
make
```

It build successfully.

Show what did 8ca0eeefc do :

```bash
git show 8ca0eeefc
```

Output is :

```
commit 8ca0eeefcc8131aec58ddaad11361a3935bedc46
Author: na <[nevyana.angelova@mattermost.com](mailto:nevyana.angelova@mattermost.com)>
Date:   2022-07-21 23:04:51 +0700

    [MM-34187] - Update React version to 17* (#10739)

    * [MM-34187] - Update React version to 17*

    * bump jest adapter

    * update snapshots

    * Update tests

    * PR comments
```

This commit updates React version to 17, maybe it is the problem?

[MM-34187]: https://mattermost.atlassian.net/browse/MM-34187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amyblais** [comment]
cc @hmhealey @nevyangelova

**Comment by nevyangelova** [comment]
@amyblais @andrewwutw there is a revert PR here https://github.com/mattermost/mattermost-webapp/pull/11232

**Comment by hmhealey** [comment]
I just merged the revert PR. There's a chance this won't help the issue though since I believe it's also related to NPM 8. We currently focus on supporting NPM 7.24. If you're using `nvm`, you can switch to our supported version by running `nvm use` in the web app repo

**Comment by andrewwutw** [comment]
@nevyangelova Thanks, this PR works for me. 😄

**Comment by andrewwutw** [comment]
@hmhealey Ok, I tried to use ```nvm``` to switch to node.js ```v16.10.0``` and npm ```7.24.0```, then I can build commit ```8ca0eeefc ``` successfully (This commit updates to React 17).

So, what is the preferred version of Node.js and NPM for webapp? 

The [Developer setup](https://developers.mattermost.com/contribute/more-info/webapp/developer-setup/) only says ```Then, use NVM to install the correct version of Node.js for the Mattermost web app```. But what is the correct version?

Or should I open another issue for this question?

**Comment by hmhealey** [comment]
The preferred version is whatever's in `.nvmrc` at the moment (so Node 16.10.0). Before we added that file, we used to list it in the dev docs as well, but we removed it afterwards since we didn't want to worry about it getting out of sync.

That'll be used whenever you run `nvm install` or `nvm use`, but it's possible that you need to re-run one of those every time a new terminal is opened if it defaults to something else. We had discussed having the Makefile automatically run `nvm use` to ensure that people are on the correct version, but I don't think we ever ended up doing that, partly since I wasn't sure if it would slow down those Makefile commands noticeably.

**Comment by andrewwutw** [comment]
@hmhealey Ok, thank you for your reply. I close this issue. 😄
