### ISSUE TITLE
Minipreview data is not generated and/or stored for images imported from Slack

### ISSUE THREAD

**Issue by RobBie1221** [mattermost/mattermost-server#21228]
#### Summary
On a clean mattermost install, I imported data exported from Slack. What I experience is very slow loading of channels, especially channels with a lot of images. In a web browser, I can open these channels but it takes a long time (~30-60 seconds). On a mobile app, I'm not even able to open some channels. The CPU usage goes server side to abnormal high levels. The result is unusable for channels with images.

When looking into the database, I can see that after import, the miniPreview field is [null]. After opening a channel, when the images are displayed, the field is still [null]. The only thing I can see in the logging is:

`{"timestamp":"2022-10-05 20:50:38.860 +02:00","level":"debug","msg":"GetImageOrientation failed","caller":"app/file.go:989","error":"failed to decode exif data: EOF"}`

This should however, if I look correctly in file.go not bother generation of miniPreview images.

On a test machine, I tried different mattermost versions. If I use mattermost 6.1, channels are much faster. If I look in the database, initially miniPreview data is [null], but after I opened a channel, this is filled with byte arrays. I also get the exif errors on 6.1. Somehow it seems this has broken between 6.1 and 7.3

If I try to upload a new image, the miniPreview data is filled in the database. It only seems to affect slack imported images.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
- Deploy postgres 14.5-alpine docker image
- Deploy mattermost-team-edition 7.3 docker image
- Import data from Slack (with images)
- Open channel with images
- Check db if miniPreview images are generated

#### Expected behavior
Fast loading channels (or even loading at all), miniPreviews that are not generated every time someone accesses a channel

#### Observed behavior (that appears unintentional) 
Slow loading channels, every time someone accesses a channel, CPU load goes high, seemingly because it tries to generate miniPreview images.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by RobBie1221** [comment]
I think this may have broken it (specifically splitting the declaration and assignment of miniPreview):
https://github.com/mattermost/mattermost-server/pull/18445

`var miniPreview []byte`

Versions from before this pull request seem to work.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-47367.

**Comment by RobBie1221** [comment]
Ok, forget about my previous comment, it has nothing to do with that pull request.

The problem is in writing to the database. In `file.go`, function `Upsert is called`
https://github.com/mattermost/mattermost-server/blob/8edb8157f108b3c89b48e528e30f17780f00acb2/app/file.go#L1051

In upsert, the update query string doesn't include the mini preview:
https://github.com/mattermost/mattermost-server/blob/8edb8157f108b3c89b48e528e30f17780f00acb2/store/sqlstore/file_info_store.go#L169-L188

I tested by building a server where I extended map above with "MiniPreview", this works. Once changed, it updates the database with mini previews.

**Comment by agnivade** [comment]
Nice catch @RobBie1221 ! Would you be willing to send a PR for this?

**Comment by RobBie1221** [comment]
Yes, I can do that

**Comment by RobBie1221** [comment]
https://github.com/mattermost/mattermost-server/pull/21304
