### ISSUE TITLE
Spelling error in Mattermost E-Mail caused by absence

### ISSUE THREAD

**Issue by DVTrast** [mattermost/mattermost-server#21232]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://www.mattermost.com/feature-ideas/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Spelling error in Mattermost E-Mail caused by absence

#### Steps to reproduce
Open mattermost and wait, until the status of the person, who you are writing to, has the status absent. A E-Mail to the recipient will be written. If the language of the mail is german, there is a typo in it: 
`**Währen** du weg warst, hat dir Vorname Nachname eine neue Direktnachricht gesendet.`

#### Expected behavior
The correct spelling is:
`**Während** du weg warst, hat dir Vorname Nachname eine neue Direktnachricht gesendet.`

![Mattermost_Typo](https://user-images.githubusercontent.com/61227869/194247501-d506936d-19d9-4d8b-9ffc-27d6c9f4365a.png)

**Comment by jprusch** [comment]
Fixed the German translation.

**Comment by DVTrast** [comment]
@jprusch Thank you :-)
