### ISSUE TITLE
PDF-Preview: Not all pages are rendered

### ISSUE THREAD

**Issue by LukasFiniarel** [mattermost/mattermost-server#21283]
#### Summary
When opening a received PDF file in Preview, not all pages are rendered. 
Pages at the end are not displayed.
If you download the file and then open it with another reader, the file is complete.

#### Steps to reproduce
 - Send or get sent PDF file.
 - Open file in preview
 
Server version: 7.3.0
Windows Desktop Client: 5.1.1
Error also occurs in the web app.
I cannot reproduce the error in the iOS app.

In the picture you can see a PDF with 10 pages. Currently page 8 is displayed. Above you can see page 7, after that no more pages are displayed.

![pdf-preview-bug](https://user-images.githubusercontent.com/7648443/194558279-192e27df-a80d-4907-b565-d922fedff749.PNG)

**Comment by esethna** [comment]
@LukasFiniarel feel free to submit a PR for the fix if you have ideas!

**Comment by LukasFiniarel** [comment]
The problem persists.
Also in server version 7.4.0 and Windows Desktop Client: 5.2.0.
I have no idea how to solve the problem

**Comment by esethna** [comment]
Okay thanks. @philkunz it's being added to our queue, but if you or anyone else reading this has an idea how to solve it, please feel free to contribute the fix

**Comment by msklywenn** [comment]
Still buggy on our side after upgrading to 7.8.0

**Comment by esethna** [comment]
cc// @AshishDhama ^

**Comment by msklywenn** [comment]
Actually, nevermind, it works now. It looks like previously uploaded PDFs keep being broken, but new ones are ok !

**Comment by msklywenn** [comment]
@AshishDhama while looking for such PDFs I finally noticed that they actually do load. It just takes some time for the subsequent pages to show up. I jumped the gun on this comment two weeks ago. Sorry about that.
