### ISSUE TITLE
Priorities are sorted out of order

### ISSUE THREAD

**Issue by peterklingelhofer** [mattermost/mattermost-server#21326]
#### Summary
Priorities are sorted out of order.

#### Steps to reproduce
Version 5.1.1 (20700)
Create a project board with various priorities, go to the Task Overview section on the left, and sort the Priorities category.

#### Expected behavior
`High`
`Medium`
`Low`

#### Observed behavior (that appears unintentional) 
`High`
`Low`
`Medium`
<img width="132" alt="Screen Shot 2022-10-08 at 11 11 17 AM" src="https://user-images.githubusercontent.com/60944077/194717091-6aee3e03-cf73-4930-85e0-bb0724860127.png">

#### Possible fixes
Not sure, did some initial digging but didn't notice anything out of place with the sorting, may have not been looking in the right areas though.

**Comment by amyblais** [comment]
@peterklingelhofer Would you be open to re-opening this in the Focalboard repo here https://github.com/mattermost/focalboard/issues?
