### ISSUE TITLE
mattermost 7.3.0 upgrade failure 

### ISSUE THREAD

**Issue by unboxcoms** [mattermost/mattermost-server#21357]
**Summary**
DB migration fails with Error 1064

**Steps to reproduce**
upgrade version 6.4.2 to 7.3.0 on k8 cluster using external HA MySQL 8 cluster

**Expected behavior**
db migration should work and server start.

**Observed behavior (that appears unintentional)**

```
2022/10/11 11:54:18 ==  update_configurations_sha: migrating  ==========================================================
Error: failed to load configuration: failed to initialize: driver: mysql, message: failed when applying migration, command: apply_migration, originalError: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '""' at line 1, query: 

SET @preparedStatement = (SELECT IF(
    (
        SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
        WHERE table_name = 'Configurations'
        AND table_schema = DATABASE()
        AND column_name = 'SHA'
    ) > 0,
    'SELECT 1',
    'ALTER TABLE Configurations ADD COLUMN SHA char(64) DEFAULT "";'
));

PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

```

**Comment by amyblais** [comment]
@unboxcoms Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this question.

**Comment by amyblais** [comment]
Looks like this was resolved on Forum,
