### ISSUE TITLE
Clearing Deleted Messages from UI

### ISSUE THREAD

**Issue by jasonmacer** [mattermost/mattermost-server#21399]
#### Summary
When messages are deleted from database using web-hooks the messages will not clear from channels unless application restart is performed.

#### Steps to reproduce
Mattermost Version: 7.0.0
Database Schema Version: 85
Database: mysql

#### Expected behavior
When using a API call to delete a message from bot interaction the messages are deleted but place holders showing "deleted message" remains in the UI until either the user manually deletes them using the "close" button to the right OR they restart the application.

#### Observed behavior (that appears unintentional)
"soft or hard deleted messages will stay in the UI channel until the application is restarted or a user deletes the place holders using the "close" icon.

#### Possible fixes

Please see image.
<img width="733" alt="mattermost-deleting-messages" src="https://user-images.githubusercontent.com/24413841/195620095-d54f5163-9a75-4410-8c6c-7abbf6d2c8d0.PNG">

**Comment by amyblais** [comment]
@jasonmacer Does refreshing the app also clear out the "message deleted" placeholders? 
What do you think is the expected behaviour? Why do you prefer that the "message deleted" placeholders wouldn't be visible?

**Comment by jasonmacer** [comment]
@amyblais while I do not know how to "refresh" the app, I believe the expected behavior is for there to be an easy way to clear the "(message deleted)" messages, either through a call or automatically. If you did not clear them out you would get a constant string of these deleted messages and the "common" user could become confused.  I know there are ways to perform this action in similar applications. 

How do you "refresh" the application without restarting it and I will attempt that; however, having every user do this constantly creates a problem for computer-illiterate individuals who do not "know" how to do this.

**Comment by amyblais** [comment]
Are you on webapp or desktop app?
Do you have examples of clearing the messages through a call or automatically that some other apps use?
