### ISSUE TITLE
Text inside Cancel Button is not aligned

### ISSUE THREAD

**Issue by sinansonmez** [mattermost/mattermost-server#21404]
#### Summary
Cancel button text within `ChannelInviteModal` is not aligned

#### Steps to reproduce
1. Click channel members button <img width="77" alt="Screen Shot 2022-10-14 at 00 39 43" src="https://user-images.githubusercontent.com/37421564/195723690-e807eff9-6834-4bf0-ad3d-250753bdfcf0.png">
2. Click `Add` button
3. Check `Cancel` button

#### Expected behavior
Text should be aligned

#### Observed behavior (that appears unintentional) 
Text is not aligned

<img width="609" alt="Screen Shot 2022-10-14 at 00 35 48" src="https://user-images.githubusercontent.com/37421564/195723849-da45622d-8a36-4f11-943a-45f43e23c44a.png">

#### Possible fixes
Add `justify-content: center;` to the line below

https://github.com/mattermost/mattermost-webapp/blob/7ea7c5d1a410c6ef558c92cd7579f8e962300e2c/sass/components/_channel-invite-modal.scss#L152-L153

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-47563.

**Comment by sinansonmez** [comment]
Closing as there is a separate issue from Mattermost
