### ISSUE TITLE
Help text when creating new slash-command is wrong

### ISSUE THREAD

**Issue by redfast00** [mattermost/mattermost-server#21434]
#### Summary

The help text for creating a new slash command, says it's for creating a new incoming webhook.

#### Steps to reproduce

Version 7.4.0.

#### Expected behavior

It should say 'Describe your slash command', not 'Describe your incoming webhook.'

#### Observed behavior (that appears unintentional) 

![2022-10-17-184249_951x372_scrot](https://user-images.githubusercontent.com/10746993/196235278-6edc8a5c-cec2-49e1-b13a-4d18d78f7d60.png)

**Comment by amyblais** [comment]
Thanks, opened: https://mattermost.atlassian.net/browse/MM-47634.
