### ISSUE TITLE
Offline Mattemost instance - Icon emoji preview not loaded due to unpkg.com reference on boars

### ISSUE THREAD

**Issue by TheMasterFX** [mattermost/mattermost-server#21444]
#### Summary
We operate a Mattermost instance in an offline environment (no connection to internet), and e.g. when you want to select a Symbol on a board task the preview of an icon/emoji is not visible since the "<button aria-label" is referecing to "https://unpkg.com/emoji-datasource-apple@5.0.1/img/apple/sheets-256/64.png"" which is of not available on isolated networks

#### Steps to reproduce
1. Install a Mattermost instance in an offline environment
2. Got to Boards => Create New Board (from any Template you like)
3. Open a Task
4. Click on the Symbol => Pick icon => Preview is emtpy

#### Expected behavior
Preview of icon is visible

#### Observed behavior (that appears unintentional) 
No Icon preview visible due to reference to (hardcoded?) background-image: url("https://unpkg.com/emoji-datasource-apple@5.0.1/img/apple/sheets-256/64.png");

#### Possible fixes
Make sheets-256/64.png offline available

**Comment by amyblais** [comment]
@TheMasterFX Would you be open to re-opening this in the Focalboard repo here https://github.com/mattermost/focalboard/issues? (Boards is the same as Focalboard)
