### ISSUE TITLE
no more Boards after mattermost upgrade

### ISSUE THREAD

**Issue by gstlouisgit** [mattermost/mattermost-server#21448]
I have recently upgraded mattermost server.  I am on mariaDB and everything was working well, I was even getting all my users on Boards.

This new upgrade 
Mattermost Version: 7.4.0
Database Schema Version: 93
Database: mysql

Now Boards is gone, and I can see in the plugin mgmt that mariaDB is no longer supported.  That sucks.  Everything was working well.

Why is MariaDB no longer supported?  What are the features missing from mariadb vs mysql?  Are there any future support for this or have I lost my Boards forever and must look for an alternative?

Thank you

**Comment by devinbinnie** [comment]
Moved to server repo since this is not a Desktop App issue.

**Comment by amyblais** [comment]
Please help re-open this issue in the Focalboard repo here https://github.com/mattermost/focalboard/issues. This existing issue may help you: https://github.com/mattermost/focalboard/issues/3891.

**Comment by esethna** [comment]
@wuwinson ^

**Comment by wuwinson** [comment]
Thanks @esethna.

@gstlouisgit Unfortunately mariaDB is not an offically supported database. We're working on https://github.com/mattermost/focalboard/pull/3929 to fix the broken Boards issue, but recommend you switch to one of our [supported DBs](https://docs.mattermost.com/install/software-hardware-requirements.html#database-software) moving forward. Please see https://github.com/mattermost/focalboard/issues/3891#issuecomment-1270805874 for more details. Thanks.
