### ISSUE TITLE
pq: permission denied for schema public

### ISSUE THREAD

**Issue by thepra** [mattermost/mattermost-server#21442]
Ubuntu 20.04 LTS HWE

#### Summary
Starting (through systemd) Mattermost based on PostgreSQL 15(on the same server) stops immediately on this error:
>{"timestamp":"2022-10-18 18:40:27.382 +02:00","level":"fatal","msg":"Failed to apply database migrations.","caller":"sqlstore/store.go:166","error":"pq: permission denied for schema public"}

#### Steps to reproduce
Following the installation guide.
Starting Mattermost like: `systemctl start mattermost.service`
Immediately ending.

#### Expected behavior
Installation instruction working

Is there a missing instruction to apply to PostgreSQL? Or what else it can be?

**Comment by amyblais** [comment]
@thepra Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this question.

**Comment by thepra** [comment]
Thanks to Alexander this is solved.
for  PSQL 15 you need extra grants for the user:
```
GRANT ALL ON DATABASE mattermost TO mmuser;
ALTER DATABASE mattermost OWNER TO mmuser;
GRANT USAGE, CREATE ON SCHEMA PUBLIC TO mmuser;
```

**Comment by anx-ag** [comment]
Forum link: https://forum.mattermost.com/t/pq-permission-denied-for-schema-public/14273

Will see if I can reproduce that based on [the instructions](https://docs.mattermost.com/install/installing-ubuntu-2004-LTS.html) you followed and will update the forum post then.
