### ISSUE TITLE
Channel named with leading asterisk indicates unread when selected

### ISSUE THREAD

**Issue by ducttapecoder-vt** [mattermost/mattermost-server#21450]
#### Summary
Channels with a leading asterisk in display name will cause client to show unread channel indicated when selected

#### Steps to reproduce
Occurs in 5.31, 5.37.10, and 7.3.0.
Name a channel with a leading asterisk, e.g. "* Test"/ "* Town Square".

#### Expected behavior
After selecting a "* Town Square" channel and scrolling to latest, the unread indicator for the MM client should disappear.

#### Observed behavior (that appears unintentional) 
When selecting a "* Town Square" or "* Test" channel, the unread channel indicator (red dot on MM icon) will always be present. Selecting a different channel will cause the indicator to disappear. Returning to the "* Test" channel will cause the indicator to reappear even when no new messages are present.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-47771.

**Comment by amyblais** [comment]
Closing as we haven't been able to reproduce this. Let us know if this reproduces on the latest version (v7.7.1).
