### ISSUE TITLE
Users with narrow screens cannot see their profile.

### ISSUE THREAD

**Issue by nikkilocke** [mattermost/mattermost-server#21455]
#### Summary
Users with narrow screens cannot see their profile.

#### Steps to reproduce
Mattermost Version: 6.3.6
Database Schema Version: 6.3.6
Database: mysql

Open Mattermost using a web browser with the window width less than 760 pixels or so.
Your picture at the top right disappears.
If you now click on the 3 bar menu, you see this:
![image](https://user-images.githubusercontent.com/684025/196970938-32994349-3a01-4290-bb4d-5844763bc612.png)
there is a Profile option, but clicking it takes you to your Settings:
![image](https://user-images.githubusercontent.com/684025/196970740-a3176603-f0bf-45da-9332-c34f479d37b1.png)

rather than your profile settings:
![image](https://user-images.githubusercontent.com/684025/196970633-eae36d1b-4c1b-4efe-ab92-1c17b0abf72c.png)

#### Expected behavior
You should be able to see and edit your profile settings on narrow screens.

#### Possible fixes
There should be two options on the bar menu for narrow screens - Profile and Settings, rather than a single Profile option that actually takes you to Settings.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-47797.

**Comment by nikkilocke** [comment]
Just FYI, the order of the screenshots is muddled up in the Jira post.

**Comment by amyblais** [comment]
Thanks, fixed now.

**Comment by kostaspt** [comment]
Hey, I'd like to work on this one.
