### ISSUE TITLE
Downloading file does not overwrite existing files despite confirmation

### ISSUE THREAD

**Issue by andreas-zeller** [mattermost/mattermost-server#21478]
#### Summary
If I download a file (a PDF) from Mattermost, and a file of the same name already exists, the existing file is not overwritten despite confirmation.

#### Steps to reproduce
This is with Version 5.1.1 (20700) on macOS
1. Find a (PDF) file in Mattermost.
2. Download the file (to Downloads). Click on "Save"
3. You get a message "Download complete"
4. Download the file again (or another file with the same name, but different content). Click on "Save".
5. You get a message "<file> already exists. Do you want to replace it?"
6. Confirm with "Replace".
7. All dialogs close, but the existing file is NOT replaced or overwritten.

#### Expected behavior
As above, but in Step 7, following the click on "Replace":
* The file should be downloaded, overwriting the existing file; and
* There should again be a confirmation "Download completed".

#### Observed behavior (that appears unintentional) 
See above.

**Comment by amyblais** [comment]
@andreas-zeller What Mattermost server version are you on? You can go to the Main Menu (at the top on the left hand-side), then open About Mattermost. 

![image](https://user-images.githubusercontent.com/29708087/197202304-a18d8beb-336a-4a6a-8672-4b380820721c.png)

**Comment by andreas-zeller** [comment]
This is
Mattermost Team Edition
Mattermost Version: 7.1.2
Database Schema Version: 89
Database: postgres

**Comment by andreas-zeller** [comment]
Don't know about the MAS build, but this is indeed a duplicate of the earlier report. Thanks!
