### ISSUE TITLE
invalid state after login

### ISSUE THREAD

**Issue by mbl-ncp** [mattermost/mattermost-server#21487]
**Summary**

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 5.0.2
- Mattermost Server version: 7.3.0

**Steps to reproduce**
- Open Mattermost Desktop app
- log in via GitLab LDAP Authentication
- Error Invalid State
![image002](https://user-images.githubusercontent.com/116275219/196955976-9f8291e3-e046-4346-9fa2-9d27c402ef32.png)

I have tried reinstalling Mattermost and deleting AppData\Roaming\Mattermost
This issue only occurs for one device and only on Windows10

**Comment by amyblais** [comment]
@mbl-ncp Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this question.

**Comment by mbl-ncp** [comment]
I just did, thanks for all the advice. https://forum.mattermost.com/t/invalid-state-after-login/14307
Should i close this issue for the time being?
