### ISSUE TITLE
Many errors in logs-  "websocket.NextReader: closing websocket"

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/mattermost-server#21515]
#### Summary
We face many entries in logs with errors: 
`{"timestamp":"2022-10-26 14:04:59.515 +05:00","level":"error","msg":"websocket.NextReader: closing websocket","caller":"app/web_conn.go:830","user_id":"grfze6dkeb8bige7737ibojecr","error":"read tcp 127.0.0.1:8065->127.0.0.2:33418: i/o timeout"}`
Overwise, Mattermost works normally at this time. Maybe, you knows what errors or bugs can triggers such entries in system log?

**Comment by amyblais** [comment]
@KakEgorka Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this question.

**Comment by solo-wanderer** [comment]
Hello, I am having the same exact issue as KakEgorka. Any possible fix?

Mattermost 7.1.3
Using TLS and HSTS with vanilla NGINX

**Comment by amyblais** [comment]
@solo-wanderer Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this question.

I also found this existing forum topic that may help you: https://forum.mattermost.com/t/constant-websocket-errors/13597/41

**Comment by solo-wanderer** [comment]
@amyblais Thanks for the link to the forum topic, I created a ticket yesterday, see: <https://forum.mattermost.com/t/websocket-and-tls-errors/14325>
