### ISSUE TITLE
Calls share screen UX improvement

### ISSUE THREAD

**Issue by francislavoie** [mattermost/mattermost-server#21512]
#### Summary

Related to https://github.com/mattermost/desktop/issues/2320

Feature request: I'd appreciate a button to go straight to full-screen from the small call widget instead of having to click "Pop-out" _and then_ click full-screen.

The usecase is that if I'm full-screen currently (to better read the text on the presenter's screen), I have to click _twice_ to minimize it so I can go open a chat to reference something or send a quick message, then click twice again to pop-out and fullscreen to get back to the call.

Using Mattermost 7.2.0 (and desktop Linux 5.1.1)

#### Steps to reproduce

- Start call with someone
- Ask them to share screen
- Click Pop-out
- Click Full-screen
- Realize I received a message, or want to send a message to someone while on the call
- Click to close full-screen (or ESC, whatever)
- Click to "un-popout"
- Send message or w/e
- Have to click two times again to fullscreen again

#### Expected behavior

I'd like a full-screen button directly from the small widget (to the right of pop-out probably).

**Comment by amyblais** [comment]
Please reopen this issue at https://github.com/mattermost/mattermost-plugin-calls/issues!

**Comment by francislavoie** [comment]
Thanks, done! https://github.com/mattermost/mattermost-plugin-calls/issues/230
