### ISSUE TITLE
Signing up to the community via apple app on desktop produces error

### ISSUE THREAD

**Issue by davidrenne** [mattermost/mattermost-server#21540]
#### Summary
 
Getting error on joining link via app

#### Steps to reproduce

Went here to join the community.  https://mattermost.com/community/.  Installed latest app in app store and am on latest apple OSX version.

And it pops up with this:

<img width="997" alt="Screen Shot 2022-10-27 at 2 28 47 PM" src="https://user-images.githubusercontent.com/117254/198376761-729c3c08-320f-4bef-94f1-7e35b4347ecb.png">

#### Expected behavior

Should log me into the community.

**Comment by amyblais** [comment]
@davidrenne What did you fill in as the server name and URL? What Mattermost desktop app version are you on?

**Comment by amyblais** [comment]
Closing as there hasn't been a response for a while. Feel free to re-open as needed.
