### ISSUE TITLE
Email notifications for DMs from Playbooks contain broken URLs

### ISSUE THREAD

**Issue by BenLloydPearson** [mattermost/mattermost-server#21572]
#### Summary
Email notifications for direct messages from Playbooks plugin contains invalid URLs. 

#### Steps to reproduce
1. Setup your account to receive email notifications when someone sends you a DM.
2. Trigger an action that results in Playbooks sending you a DM.
3. Click links that are inside the email that is sent to you. The two links that are broken are in highlighted in red circles in the attached image.

#### Expected behavior
The URLs should be properly formatted to send you to the appropriate DM in Mattermost.
 
#### Observed behavior (that appears unintentional) 
The two links in the red circles send you to URLs that are formatted like so: http:///playbooks/playbooks/foo
<img width="579" alt="Screen Shot 2022-11-01 at 3 37 12 PM" src="https://user-images.githubusercontent.com/7205829/199275311-ee1cdc0a-6c1e-4660-bf44-6004b32bb9ae.png">

#### Possible fixes
Unknown

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-48089
