### ISSUE TITLE
Draft saved messages: draft 'pencil' icon for posts but not for thread replies

### ISSUE THREAD

**Issue by MynaITLabs** [mattermost/mattermost-server#21589]
#### Summary
Draft saved messages: 'pencil' icon for posts but not for thread replies.

#### Steps to reproduce
Web/html app:  Mattermost Enterprise Edition
Modern communication from behind your firewall.

Mattermost Version: 5.37.9
Database Schema Version: 5.37.9
Database: mysql

1) Open a channel  "Testing Alphabet"
2) Post a message "AAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHH"
3) Post a 2nd message "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
4) Type in a 3rd message "CCCCCCCCCCCCCCCCCCCCCC", but don't send it.
5) Reply to the "AAAAAAAAAAA" message, with "DDDDDDDDDDDDDDDDDDDDDDD" (hit submit)
6) Reply to the "AAAAAAAAAAA" message, with "EEEEEEEEEEEEEEEEEE" (don't submit)
7) Change to a different Channel "Testing Numbers".
8) Notice that "Testing Alphabet" has a 'pencil' icon on it, indicating 'draft message' is still available.
9) Change back to "Testing Alphabet"
10) Notice that your "CCCCCCCCCCCCCCCCCC" message is now available to finish and submit.
11) Notice there is no indication that there is a reply-draft message availabe to "AAAAAAAAAAAA".
12) Click on 'reply' for "AAAAAAAAAAAAAAA"
13) Notice that your draft message "EEEEEEEEEEEEEEEE"  is now available too edit and submit.

Q.E.D. No indicator of draft replies are available.

#### Expected behavior
An icon or indicator that Reply has a draft message available to edit and submit.

#### Observed behavior (that appears unintentional) 
No icon or indicator is seen

#### Possible fixes
Have a section, menu item, or icon called "View drafts"  which lilsts all the drafts available.  Maybe in search ?
Have a 'reply' icon which is a different color, size, or shape to indicate draft is available.

**Comment by amyblais** [comment]
@MynaITLabs v5.37.9 is an unsupported server version. Are you able to reproduce this on a supported version? (We support versions 7.1.0 and later)

**Comment by MynaITLabs** [comment]
> @MynaITLabs v5.37.9 is an unsupported server version. Are you able to reproduce this on a supported version? (We support versions 7.1.0 and later)

Ah. I thought we just upgraded a few months ago.  I'll check with IT admin and schedule an update. Then followup and see if issue still there.  Tanks.

**Comment by amyblais** [comment]
I was able to reproduce also on the latest version - ticket: https://mattermost.atlassian.net/browse/MM-48185.
