### ISSUE TITLE
Feature request - Add ability to block people on mattermost.

### ISSUE THREAD

**Issue by Porthorian** [mattermost/mattermost-server#21592]
#### Summary
I wanna be able to block users on Mattermost from ever seeing their faces again on the client.

#### Steps to reproduce
Feature Request

#### Expected behavior
Shouldn't be able to see the user message me or talk in a public channel.

#### Observed behavior (that appears unintentional) 
N/A

#### Possible fixes
N/A

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @Porthorian,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by Porthorian** [comment]
Hi @amyblais  appreciate it for pointing me in the right direction.

For any future people that discover this issue.

https://mattermost.uservoice.com/forums/306457-general/suggestions/45943825-add-ability-to-block-people
