### ISSUE TITLE
Information sidebar not displaying profiles properly

### ISSUE THREAD

**Issue by ritsku** [mattermost/mattermost-server#21637]
#### Summary
When clicking on a person's profile picture, the profile does not persist, but instead flashes and disappears.

#### Steps to reproduce
In any channel with more than two people, open the info bar top right, click on members, and then on a member profile picture.

#### Expected behavior
Expected behavior is that the profile picture will display as it would when clicking on a team member's name in chat, or in DMs. 

#### Observed behavior (that appears unintentional) 
When clicking on the profile picture, specifically in in a chat or channel with more than two people, under the info bar > members, the profile information flashed and disappeared instead of persisting after the click. This occurs in both the desktop app and the web browser versions of Mattermost 7.3. Checking on the mobile app, it also seems that I cannot get to members' profiles through the channel information. Members are simply displayed, and you cannot click on them.

#### Possible fixes
I have no idea.

**Comment by amyblais** [comment]
Open ticket: https://mattermost.atlassian.net/browse/MM-45789.
