### ISSUE TITLE
Failed to apply database migrations when upgrade from 6.3.3 to 7.1.4

### ISSUE THREAD

**Issue by mrpolaris** [mattermost/mattermost-server#21684]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://www.mattermost.com/feature-ideas/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Upgrade from 6.3.3 to 7.1.4  Also noticed there are missing tables like the db_migrations table

#### Steps to reproduce
noticed error in the logs about migrations not running

#### Expected behavior
NA

#### Observed behavior (that appears unintentional) 
mattermost db migrate
{"level":"warn","msg":"DefaultServerLocale must be one of the supported locales. Setting DefaultServerLocale to en as default value."}
{"level":"warn","msg":"DefaultClientLocale must be one of the supported locales. Setting DefaultClientLocale to en as default value."}
{"level":"warn","msg":"AvailableLocales must include DefaultClientLocale. Setting AvailableLocales to all locales as default value."}
{"level":"warn","msg":"DefaultServerLocale must be one of the supported locales. Setting DefaultServerLocale to en as default value."}
{"level":"warn","msg":"DefaultClientLocale must be one of the supported locales. Setting DefaultClientLocale to en as default value."}
{"level":"info","msg":"Pinging SQL","fields":{"database":"master"}}
{"level":"fatal","msg":"Failed to apply database migrations.","fields":{"error":"\"open migrations\\mysql: file does not exist\""}}
{"level":"debug","msg":"Deleting any unused pre-release features"}
Database successfully migrated

Also when running the version cmd I get the error below
{"level":"warn","msg":"DefaultServerLocale must be one of the supported locales. Setting DefaultServerLocale to en as default value."}
{"level":"warn","msg":"DefaultClientLocale must be one of the supported locales. Setting DefaultClientLocale to en as default value."}
{"level":"warn","msg":"AvailableLocales must include DefaultClientLocale. Setting AvailableLocales to all locales as default value."}
{"level":"warn","msg":"DefaultServerLocale must be one of the supported locales. Setting DefaultServerLocale to en as default value."}
{"level":"warn","msg":"DefaultClientLocale must be one of the supported locales. Setting DefaultClientLocale to en as default value."}
{"level":"info","msg":"Pinging SQL","fields":{"database":"master"}}
{"level":"fatal","msg":"Failed to apply database migrations.","fields":{"error":"\"open migrations\\mysql: file does not exist\""}}
{"level":"debug","msg":"Deleting any unused pre-release features"}
Error: failed to get schema version: unable to select from db_migrations: Error 1146: Table 'mattermost.db_migrations' doesn't exist

**Comment by agnivade** [comment]
Hey @mrpolaris - let's use the forum post to continue the conversation: https://forum.mattermost.com/t/mattermost-7-4-failed-to-apply-database-migrations/14464. I'll close this one.
