### ISSUE TITLE
Show a user local time near the nickname in the chat and/or in a user short description

### ISSUE THREAD

**Issue by artempronevskiy** [mattermost/mattermost-server#21694]
This would be very useful for teams working in different time zones so teammates will see what local time is for all other teammates.

Examples:

- near the nickname in the chat: https://pasteboard.co/CzDeCVgFApN1.png
- in short description: https://pasteboard.co/ugEbnXLCz6ww.png
- how it can be set up in client settings: https://pasteboard.co/SnYXdEnAjobv.png

**Comment by devinbinnie** [comment]
Thanks for the suggestion! Transferring to server repo for better visibility.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @artempronevskiy.

Would you like to [contribute this in the feature idea forum](https://portal.productboard.com/mattermost/33-what-matters-to-you) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.
