### ISSUE TITLE
Version 7.02 New formating toolbar breaks file uploads

### ISSUE THREAD

**Issue by TrentBie** [mattermost/mattermost-server#21691]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://www.mattermost.com/feature-ideas/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Version 7.0.2 broke the file uploads - the send can see the file in the message but the receiver just gets a blank message

#### Steps to reproduce
Upload a file and send it

#### Expected behavior
Receiver should get file

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
 Version 6.x worked fine until we upgraded to 7.0.2 then uploads do not work

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@TrentBie We currently support versions v7.1 and later. Would you be open to upgrading to see if this still reproduces on a supported version? Another option is that you can do some testing on our community server here https://community.mattermost.com/, which is on the latest version.

**Comment by TrentBie** [comment]
I can get a test server built up and test but I have not seen any bugs that were fixed for the issue in the 7.1 version.  At one point we were at that version and had the same issue But I will test again

**Comment by TrentBie** [comment]
@amyblais  So updated to 7.2.1 still have file upload issues and also seen a migration issue  seems a file is missing

{"level":"error","msg":"Could not initiate logging","fields":{"error":"\"invalid config for logging, error creating log target _defFile: error decoding file target options: invalid character 'm' in string escape code\""}}
{"level":"info","msg":"Server is initializing...","fields":{"go_version":"go1.18.1"}}
{"level":"info","msg":"Pinging SQL","fields":{"database":"master"}}
{"level":"fatal","msg":"Failed to apply database migrations.","fields":{"error":"\"open migrations\\mysql: file does not exist\""}}

**Comment by TrentBie** [comment]
@amyblais   More log info
{"level":"debug","msg":"Received HTTP request","fields":{"method":"POST","request_id":"4i6wgmjhc7g5j8nqsio5dtsbxy","status_code":"200","url":"/api/v4/channels/members/me/view"}}
{"level":"debug","msg":"Scheduling Job","fields":{"scheduler":"migrations"}}
{"level":"debug","msg":"All migrations are complete.","fields":{"scheduler":"migrations"}}
{"level":"debug","msg":"Next run time for scheduler","fields":{"next_runtime":"\"\u003cnil\u003e\"","scheduler_name":"migrations"}}
{"level":"debug","msg":"Received HTTP request","fields":{"method":"POST","request_id":"6twozcj5ijnbjf37zfoqrz3awo","status_code":"200","url":"/api/v4/channels/members/me/view"}}
{"level":"debug","msg":"Received HTTP request","fields":{"method":"POST","request_id":"ki59gt71hpgyxm3w3q8qg4tcgw","status_code":"200","url":"/api/v4/channels/members/me/view"}}
{"level":"debug","msg":"Received HTTP request","fields":{"method":"POST","request_id":"rq6uzrk5atyuxksemx1pzcrrto","status_code":"200","url":"/api/v4/channels/members/me/view"}}
{"level":"debug","msg":"Received HTTP request","fields":{"method":"POST","request_id":"czun6zd1nbnd8cztuhyw36dcgc","status_code":"201","url":"/api/v4/files"}}
{"level":"warn","msg":"Failed to invalidate the fileInfo cache.","fields":{"error":"\"failed to get FileInfo with id=3xer9ogn73g7mep1bm5uzr6bdh: Error 1054: Unknown column 'FileInfo.Archived' in 'field list'\"","file_info_id":"3xer9ogn73g7mep1bm5uzr6bdh"}}

**Comment by amyblais** [comment]
What type of file are you attempting to upload? We also have this open issue https://github.com/mattermost/mattermost-server/issues/21604.

**Comment by TrentBie** [comment]
@amyblais Just a plan .txt file

**Comment by amyblais** [comment]
Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this migration issue.

**Comment by TrentBie** [comment]
Sure

**Comment by amyblais** [comment]
@TrentBie Sounds like disabling option "Enable document search by content" fixed it?

**Comment by TrentBie** [comment]
So seems there is some DB migrations issue in the windows zip deployments maybe.  Seems migrations are not getting applied.  so Alexander Griesser had me do the migrations manually bit now the server will not even start.

{"timestamp":"2022-12-08 10:30:38.363 -06:00","level":"info","msg":"Server is initializing...","caller":"app/server.go:258","go_version":"go1.18.1"}
{"timestamp":"2022-12-08 10:30:38.364 -06:00","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:225","database":"master"}
{"timestamp":"2022-12-08 10:30:38.399 -06:00","level":"fatal","msg":"Failed to apply database migrations.","caller":"sqlstore/store.go:162","error":"open migrations\\mysql: file does not exist"}

**Comment by anx-ag** [comment]
This is the [forum post](https://forum.mattermost.com/t/mattermost-files-uploads-no-longer-work-after-7-0-2/14491/8) and I'm not sure where this message is coming from, found it in the code but cannot make sense of `db.Assets()` :-/
