### ISSUE TITLE
Email notifications broken

### ISSUE THREAD

**Issue by leitmori** [mattermost/mattermost-server#21695]
#### Summary
Since upgrading from v7.4.0 to v7.5.1, email notifications sometimes contain only a user avatar.

#### Steps to reproduce
- Set Email Notifications to "Every 15 minutes".
- Another user replies in followed thread.

#### Expected behavior
A properly formatted email notification is sent.

#### Observed behavior (that appears unintentional) 
Email notification sometimes contains only a user avatar.
<img width="784" alt="Screenshot 2022-11-19 at 16 12 03" src="https://user-images.githubusercontent.com/29522608/202857661-cb00451a-6bac-45f4-95a9-f77e5fba7574.png">
<img width="827" alt="Screenshot 2022-11-19 at 16 12 37" src="https://user-images.githubusercontent.com/29522608/202857682-bab76283-278d-41c1-8574-74bcfd05b439.png">

**Comment by amyblais** [comment]
@leitmori What OS and version are you on? What email do you use (gmail, outlook, etc.)?

**Comment by leitmori** [comment]
The system is running Ubuntu 22.04.1 LTS. We operate our own mail server (Postfix 3.6.4).
As a workaround we have disabled email batching, then the problem does not occur.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-48521.

**Comment by H-B-Schmidt** [comment]
I can confirm the problem after upgrade 7.4 -> 7.5.1 Professional on self hosted Ubuntu 20.04.5 LTS. 

I informed support but got no reply yet.

The error in the logfile is
> error [2022-11-21 09:19:47.353 +01:00] Unable to render email                        caller="email/email_batching.go:344" error="template: messages_notification.html:664:33: executing "messages_notification" at <.MessageAttachments>: can't evaluate field MessageAttachments in type *email.postData"

**Comment by noxer** [comment]
Thank you for the report. I can confirm that disabling email batching fixes the issue.

**Comment by someone-somenet-org** [comment]
+1 to email batching is broken and produces empty emails.

**Comment by 7-plus-t** [comment]
+1 same issue on our installation after updating to 7.5.1

**Comment by tsueri** [comment]
Will this be fixed in 7.6 or in 7.7? I'm a bit confused since 7.6 is not yet released.

**Comment by leitmori** [comment]
v7.6 release was cancelled, so probably in v7.7

**Comment by leitmori** [comment]
According to the release notes the bug should be fixed in v7.5.2: ["Fixed an issue where email notifications looked broken when email batching was enabled [MM-48521]"](https://github.com/mattermost/docs/blob/ecc5933f2ae1511fb6f53a1dbc33b984b654de9f/source/install/self-managed-changelog.md?plain=1#L22)

**Comment by amyblais** [comment]
This is now fixed in v7.5.2 dot release,
