### ISSUE TITLE
Web app incorrectly scales text in channel list (firefox)

### ISSUE THREAD

**Issue by stolk** [mattermost/mattermost-server#21701]
#### Summary
In web-app, scaling content in Firefox will cause bad rendering in channel list.

#### Steps to reproduce
1. Browse to mattermost web app using firefox.
2. Increase content scale to 200% by holding CTRL and scrolling mouse wheel.

#### Expected behavior
Properly rendered channel list names, in larger font.

#### Observed behavior (that appears unintentional) 
Illegible channel list.

![image](https://user-images.githubusercontent.com/455280/203115126-54545ef6-f586-48b5-b3e8-8b152a58b837.png)

#### Possible fixes

unknown.

#### Notes

The content itself, in the chat, is rendered properly. But the channel list and direct-message contacts are incorrectly rendered as shown in screenshot.

#### Versions

*Firefox:* 106.0 

*OS:* Ubuntu 22.10

*Mattermost:* 6.6.0

**Comment by amyblais** [comment]
@stolk What Mattermost server version are you on? What Firefox version are you using?

**Comment by amyblais** [comment]
@stolk We currently support Mattermost server version v7.1.0 and newer. Would you be open to upgrading to see if the issue persists on a supported version?

**Comment by stolk** [comment]
I do not run the server myself, I just use the company server. If it can’t be reproduced on current server, feel free to close.

**Comment by amyblais** [comment]
@stolk Sounds good, would you be open to do some testing on our community server here https://community.mattermost.com/? It is on the latest version.

**Comment by stolk** [comment]
It is highly likely that this is a firefox bug, not a mattermost bug.
