### ISSUE TITLE
Code formatting has support for `delphi`, but not `pascal` and `pas` for `pascal`

### ISSUE THREAD

**Issue by bogen85** [mattermost/mattermost-server#21711]
#### Summary
Not every `pascal` programmer is going to want to have say (or even think of saying) ` ```delphi ` when specifying `pascal`, especially if they are not using `delphi`

#### Steps to reproduce
Mattermost Team Edition, Version: 7.2.0

Specifiying `pas` `pascal` or `freepascal` in a ` ``` ` code block does not highlight the code as `pascal`.

```pas
program mattermostrocks;
begin
  writeln('Mattermost rocks!');
end.
```

```pascal
program mattermostrocks;
begin
  writeln('Mattermost rocks!');
end.
```

Github syntax highlighting supports it.

#### Expected behavior

For the code to be highlighted appropriately.

I see that `delphi` can be specified.

```delphi
program mattermostrocks;
begin
  writeln('Mattermost rocks!');
end.
```
![image](https://user-images.githubusercontent.com/52499484/203449956-b6af392b-5218-4526-b562-573abb07ad01.png)

#### Observed behavior (that appears unintentional) 

![image](https://user-images.githubusercontent.com/52499484/203449856-c7da5f74-b98d-4c06-9ab1-f1af4b45b402.png)

#### Possible fixes

The following all define `pas`, `pascal` and `freepascal`
```shell
components/help/components/formatting.tsx
packages/mattermost-redux/src/constants/files.ts
utils/constants.tsx
i18n/*.json # many in here
```

This even goes far as to say all the extensions that are pascal related
```js
utils/constants.tsx:1737:        delphi: {name: 'Delphi', extensions: ['delphi', 'dpr', 'dfm', 'pas', 'pascal', 'freepascal', 'lazarus', 'lpr', 'lfm']},
```
However, from all those, only `delphi` is explicitly supported.
```js
types/external/highlightjs.d.ts:15:declare module 'highlight.js/lib/languages/delphi.js';
utils/syntax_highlighting.tsx:98:        delphi: () => import('highlight.js/lib/languages/delphi'),
```

Adding `pas`, `pascal` (and optionally `freepascal`) to the registration in `utils/syntax_highlighting.tsx` would remedy this issue.

#### Discussion

Is this intentional? `delphi` is a commercial project. Not a programming language in and of itself. It is a variant of a programming language.

If someone is using `pascal` but, but not `delphi` they should not have to specify a commercial product they don't use (if they are not using that product).
Would be like having to specify `msvc` to get `c` which to most `*nix` `c` programmers would be very strange.

Same goes for `pascal` programmers who only use `open source` `pascal` variants like `free pascal` (`fpc`).

I see in the `async function registerLanguage(languageName: string)` function that only the language categories are mentiond.
`delphi` is not a language category, `pascal` is.

Even if `utils/constants.tsx` calls `delphi` a programming language category, that is wrong, in this case `object pascal` is the programming language category.

[Wikipedia entry for Delphi](https://en.wikipedia.org/wiki/Delphi_(software))

`Delphi` is a [general-purpose programming language](https://en.wikipedia.org/wiki/General-purpose_programming_language) and a software product that uses the Delphi dialect of the [Object Pascal](https://en.wikipedia.org/wiki/Object_Pascal) [programming language](https://en.wikipedia.org/wiki/Programming_language)

#### Conclusion

Can you allow `pascal` to specify `pas` or `pascal` to highlight `pascal` code?
If someone is using `delphi` it may make sense to specify `delphi` but if not, it makes no sense to specify a commercial product they are not using.

(`freepascal` and `fpc` and all the other `delphi` (incorrect as the whole category, but I digress...) extensions) would be nice as well, but I'm not asking for those. 

Like I already said, having to specify `delphi` for `pascal` is like having to specify having to specify `msvc` to get `c`.
That makes no sense if said programmer is not using that specific commercial variant.

I guess this may be more of a `hightlightjs.d.ts` issue.... (but would still need to addressed in Mattermost to resolve this issue).

**Comment by bogen85** [comment]
A more general fix that benefit all other languages would be to iterate over the extensions in `utils/constants.tsx` and register all of them for each language category in `utils/syntax_highlighting.tsx`. But that may have a lot of collisions. I guess any collision could be ignored and not allowed, but that might not make sense for more common languages.
```js
        H: ['h', 72],
        cpp: {name: 'C/C++', extensions: ['cpp', 'c', 'cc', 'h', 'c++', 'h++', 'hpp'], aliases: ['c++', 'c']},
```
But I see that 'c' and 'cxx' both work for 'c'...
So my above `possible fixes` might not makes sense.
(Although the `discussion` and `conclusion` still apply.)

Maybe the extensions only needed to be added to the following:
```js
./components/search/search.tsx:315:            props.actions.filterFilesSearchByExt
./packages/mattermost-redux/src/constants/files.ts:6:    CODE_TYPES: 
```

**Comment by bogen85** [comment]
Ok, so maybe the `delphi` entry just needs an aliases section.

in `utils/constants.tsx:1737`:        
```js
delphi: {
   name: 'Delphi', extensions: ['delphi', 'dpr', 'dfm', 'pas', 'pascal', 'freepascal', 'lazarus', 'lpr', 'lfm'],
   aliases: ['pas', 'pascal']
},
```
That would likely be the most simple fix.

However, without correcting the whole **delphi is a product** not a **language** mess, the following would be nicer:

```js
delphi: {
   name: 'Delphi', extensions: ['delphi', 'dpr', 'dfm', 'pas', 'pascal', 'freepascal', 'lazarus', 'lpr', 'lfm'],
   aliases: ['pas', 'pascal', 'freepascal', 'fpc']
},
```
I mean, if `delphi` is a `label` for `pascal` might as well add the free object pascal variant `freepascal` as a `label` or `pascal` as well.

**(`fpc` == `free pascal compiler`)**

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-48578.

**Comment by hchorfispiria** [comment]
@amyblais Would you mind assigning this issue to me?
