### ISSUE TITLE
Android App - Boards wont load

### ISSUE THREAD

**Issue by bcfdadmin** [mattermost/mattermost-server#21760]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://www.mattermost.com/feature-ideas/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
In the android app, when you click on the board in the channel listing, it opens up focalboard but displays a white screen, will not load. 

#### Steps to reproduce
Just downloaded the newest mattermost app off google play, logged in as a admin, clicked on the line @admin linked the board XXXXX with this channel. Once the link is clicked it opens up focalboard in the top right corner, displays a white screen, and doesnt load anything

#### Expected behavior
Expected it to open the board that was linked

#### Observed behavior (that appears unintentional) 
See above

#### Possible fixes
N/A

**Comment by amyblais** [comment]
@bcfdadmin Would you be open to re-opening this in the Focalboard repo https://github.com/mattermost/focalboard/issues?
