### ISSUE TITLE
Many channels are not marked and the red badge do not show on Dock icon to indicate unread messages

### ISSUE THREAD

**Issue by apieceoy** [mattermost/mattermost-server#21763]
#### Summary
In recent days, many channels are not marked and the red badge do not shown on Dock icon to indicate unread messages.

#### Steps to reproduce
1. It usually happens on specified channels (including private and public), but the mentions and direct messages work correctly.
2. I do not mute the channels, and others also have this problem. It was working correctly before.
4. Upgrade to 7.5.1 from 5.37.10 can't solve. (self-hosted)
5. Browser and OS: Chrome on Mac, Desktop on Mac (5.2.1), Mattermost APP on iPhone

#### Expected behavior
Correctly show red badge on Dock icon and mark channels to indicate unread messages.

#### Observed behavior (that appears unintentional) 
Several situations I have observed so far:
1. Not show on "Unreads" section and not marked.
2. Show on "Unreads" section and be marked in the background, but disappear suddenly on section and 
has been unmarked after focus the browser/app. (Usually accompanied by another channel that has not been read and has not yet been focused)

**Comment by amyblais** [comment]
@apieceoy Do you see errors in the Mattermost server logs?

**Comment by apieceoy** [comment]
No, I don't see any special errors in server logs. (mattermost.log)

**Comment by amyblais** [comment]
What version did you upgrade from? You mentioned that it used to work, so I'm wondering if there was a recent server upgrade or any other recent updates.

**Comment by apieceoy** [comment]
It used to work, but only recently started having this problem. So we upgrade it expects to fix this.

Originally version: 5.37.2 (it used to work, but recently started having this problem)
Upgrade to: 5.37.10 (current version, still has this problem)
Upgrade to: 7.5.1 (use a different domain and different machine, still has this problem)

**Comment by apieceoy** [comment]
Other observations:

I'm currently observing that these channels seem to have the following in common: (not sure if it's related)
1. A user has set up "incoming webhooks" and is also in these channels. (like a bot)
2. In the database, the "Channels" table field "Header"  is empty for these channels.

**Comment by amyblais** [comment]
@apieceoy Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by apieceoy** [comment]
@amyblais I finally tried to set the "MsgCount" field of the table "ChannelMembers" to zero, let it recalculate automatically, which solved the problem.

The reason is because we periodically delete data, but did not adjust this field at the same time. I didn't know the value of this field would cause this problem. Thank you for your help!
