### ISSUE TITLE
Several step-by-step interactive dialogs

### ISSUE THREAD

**Issue by iBelow** [mattermost/mattermost-server#21767]
Hi, how i can create a several interactive dialogs? 
we have a limit for a 5 elements, but if i need more? 

for example, after selecting certain fields (radio button), I would like to further prompt the user to fill in more specific fields, how can I implement this? natively calling next url by submit button was unsuccessful

**Comment by amyblais** [comment]
@iBelow  Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.
