### ISSUE TITLE
Incoming webhook munging the payload...

### ISSUE THREAD

**Issue by PromoFaux** [mattermost/mattermost-server#21800]
#### Summary
When sending a certain payload to an incoming webhook, the server appears to attempt to convert it into a hyperlink of some sort..

Mattermost Version: 7.5.0
Database Schema Version: 95
Database: postgres

#### Steps to reproduce
Send payload with this as the text: 

```
{
    "Text":"`if(status_int < QUERY_UNKNOWN || status_int >= QUERY_STATUS_MAX)`",
}
```

![image](https://user-images.githubusercontent.com/1998970/205709723-5fbcfa0e-d97a-4299-a6c2-5616c0645d43.png)

As can be seen in the screenshot, this does not happen when typing/pasting directly into the web app

It appears that the `< QUERY_UNKNOWN || status_int >` part is getting interpreted as an HTML tag?

**Comment by rdwebdesign** [comment]
Another assumption is the text `< QUERY_UNKNOWN || status_int >` is being read as an "alternative" Markdown link, in the format:

`<some text used as URL | text used as title>`

converted to:
`[text used as title](some text used as URL)`

![image](https://user-images.githubusercontent.com/1385443/205712438-7be094bd-763a-42c5-922d-d26d75612781.png)

But this is not expected inside a code block.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-48860.

**Comment by PromoFaux** [comment]
In case anyone is interested, this is the part of the code that is munging the value:

https://github.com/mattermost/mattermost-server/blob/3b043c1f126634d87327f9bc794fb171492bb5da/app/webhook.go#L266-L268

See here: https://go.dev/play/p/fcpTlalboA8 for an interactive example.

I am not very good with regex so unsure what alternative to suggest, though it is maybe worth noting that this transformation does not happen when one copies and pastes into the web interface. Is it to maintain compatibility with slack webhook formats?

**Comment by amyblais** [comment]
Closing as there is now a Help Wanted issue open for this.
