### ISSUE TITLE
Boards doesn't work for some users

### ISSUE THREAD

**Issue by JakubRybakowski** [mattermost/mattermost-server#21904]
#### Summary
Boards doesn't work only for some users in web browser.

#### Steps to reproduce
Clean install Mattermost self hosted v7.5.1 on ubuntu 22.10.

Boards do not work for some users in the browser.

For the same user:
Chrome - not working
Chrome incognito - works
Safari - works
Macos app - works.

I tried clearing the cache or cookies etc. It didn't help.

<img width="992" alt="Zrzut ekranu 2022-12-18 o 11 37 39" src="https://user-images.githubusercontent.com/18492129/208293752-ac54abdc-bac0-46eb-9e23-345405b14258.png">

The token has been replaced with stars:

{"timestamp":"2022-12-18 10:33:55.631 Z","level":"warn","msg":"Error while creating session for user access token","caller":"app/session.go:90","error":"createSessionForUserAccessToken: Invalid or missing token., resource: UserAccessToken id: token=*********************"} 
{"timestamp":"2022-12-18 10:33:55.632 Z","level":"error","msg":"no session token","caller":"app/plugin_api.go:976","plugin_id":"focalboard"}

**Comment by amyblais** [comment]
@JakubRybakowski Would you be open to re-opening this issue in the Boards repo here https://github.com/mattermost/focalboard/issues?
