### ISSUE TITLE
[Collapse reply threads] Put the unread messages in the bottom

### ISSUE THREAD

**Issue by biva** [mattermost/mattermost-server#21915]
#### Summary
Hello, thank you so much for the great features of "collapse reply threads". When there's a new message in an old thread, the updated thread remains at its position in the channel, potentially pretty high up in the channel. I wonder if it would be possible to move the latest updated thread down in the channel, so that we see directly, navigating in the channel, where there are new replies.

I know that I could use the "Threads" button on the top left, but habits are hard to change and in my team, we're used to seeing the latest updated threads in the bottom, and it makes sense for us. (in the same way that any new message in an old conversation (or thread) on WhatsApp would push the old conversation (thread) to the top.

#### Steps to reproduce
1. Post a new message in the channel "First thread"
2. Post a second message 'Second thread" in this same channel, but not within the "First thread"
3. Post a reply with the "First thread"

#### Observed result
Without "collapse reply threads", we had this (the latest message is at the bottom):
![image](https://user-images.githubusercontent.com/9964305/208517770-f10e7847-3f5d-4bc1-a4bf-b574f1cacad1.png)

With "collapse reply threads", we have this (while the replies to the first thread were posted after "Second thread", the "First thread" remains above):
![image](https://user-images.githubusercontent.com/9964305/208518089-52e09cd4-7df5-4aeb-b856-00688fa0d3aa.png)

#### Expected behaviour:
I'd like to see "First thread" at the bottom so that I see this is the latest updated thread:
![image](https://user-images.githubusercontent.com/9964305/208523622-6e427520-bd32-463a-981a-5e267088ce2b.png)

Would that make sense?

#### Additional issue (might be linked?)
In addition (but maybe there's already an issue or I should create a new one?), when there's an unread message in a thread that I follow, I see the small blue dot next to the thread, I also see the thread in the Unread section of the "Followed threads" section, but the channel name in the left bar doesn't show that there's an unread message (it doesn't turn bold). Is it a bug or a feature?

#### Configuration
Server 7.4.0 (PostgreSQL)
Desktop 5.2.2 (Windows 11)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49250.

**Comment by biva** [comment]
I created a dedicated issue for the "additional issue" about unread messages: https://github.com/mattermost/mattermost-server/issues/21937

**Comment by amyblais** [comment]
Closing as this is working as expected based on notes from our product manager,

**Comment by biva** [comment]
Hello @amyblais , thanks for your quick feedback. Nevertheless, I understand that this suggestion might be interesting if I read this answer:

> while this is good feedback this is not a bug. [...] UX feedback about existing features can be routed to the feature channel or team. 

May I suggest reopening this ticket with a "UX feedback" or "Feature request" label?

**Comment by amyblais** [comment]
Hi @biva! I'd suggest sharing feedback and questions in our community server - we have a dedicated channel for collapsed reply threads here https://community.mattermost.com/core/channels/folded-reply-threads.

**Comment by biva** [comment]
Thanks for the suggestion, done :) https://community.mattermost.com/core/pl/sck1oog7q3bpmjp1egngdb651o
