### ISSUE TITLE
Collapse reply threads: unread messages are not displayed clearly

### ISSUE THREAD

**Issue by biva** [mattermost/mattermost-server#21937]
I create this dedicated issue because I think it's different from https://github.com/mattermost/mattermost-server/issues/21915

#### Summary
When there's an unread message in a thread that I follow, I see the small blue dot next to the thread, I also see the thread in the Unread section of the "Followed threads" section, but the channel name in the left bar doesn't show that there's an unread message (it doesn't turn bold). Is it a bug or a feature?

In my opinion, this is a bug because it prevents me to see the channels with unread messages.

#### Configuration
Server 7.4.0 (PostgreSQL)
Desktop 5.2.2 (Windows 11)

**Comment by biva** [comment]
I also just realise that even if I'm mentioned in a post, messages might not be displayed in the "Unread section" of "Threads". In the example below, the channels marked with a blue sticker "1" were in fact read by me (I even replied to the thread) > "Collapse reply" view is correct, but somehow didn't update the status for the "not collapse reply" view

Without "Collapse reply" activated:
![image](https://user-images.githubusercontent.com/9964305/208987187-91f16096-91ab-4d0d-921f-7cebb89e7124.png)

With 
![image](https://user-images.githubusercontent.com/9964305/208987296-6e2c7597-fea2-4dad-a753-a751e99af83a.png)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49347.

**Comment by amyblais** [comment]
Our product manager added notes to the ticket:

This is expected behaviour as the unread goes to the threads view now. This avoids duplicate badges in the sidebar as you now have a single location to go to view your thread replies. 

> I also just realise that even if I'm mentioned in a post, messages might not be displayed in the "Unread section" of "Threads". In the example below, the channels marked with a blue sticker "1" were in fact read by me (I even replied to the thread) > "Collapse reply" view is correct, but somehow didn't update the status for the "not collapse reply" view

This is also expected at the moment given you viewed the thread from the threads view and didn’t actually open the channel. Not ideal but we don’t expect users to flip between CRT and non-CRT frequently. Related ticket https://mattermost.atlassian.net/browse/MM-38879.

Closing based on the comments,

**Comment by biva** [comment]
Hello @amyblais,
Thanks for the quick feedback and explanation. Nevertheless, I still have difficulties managing unread messages. In the screenshot below, I see that my "Unread" threads is empty, and in the channel list on the left, I see a channel with a blue dot and a number inside, meaning that I have unread messages where I'm mentioned. If I look into these "unread messages" within the channel, it appears that they correspond to threads that I have read and responded to within the "Threads" view. 

Is it also an expected behaviour?

![image](https://user-images.githubusercontent.com/9964305/210454161-b0afb3b1-10c6-4515-93b9-6997e1fd3e91.png)

**Comment by biva** [comment]
Hello, am I the only one to see this? It happens to me today as well that a new direct message didn't appear in my "Unread" messages: isn't it a bug?

**Comment by amyblais** [comment]
Hi @biva! Feel free to post feedback and questions in the collapsed reply threads channel here https://community.mattermost.com/core/channels/folded-reply-threads.
