### ISSUE TITLE
Mattermost Server `make run-server` fails on mysql listen

### ISSUE THREAD

**Issue by candronikos** [mattermost/mattermost-server#21965]
Following the setup instructions [here](https://developers.mattermost.com/contribute/more-info/server/developer-setup/) I get the following error when running this in ubuntu server version 2022.04.

```
make run-server
./scripts/setup_go_work.sh 
Creating a go.work file
MMCTL already exists in bin/mmctl not do
wnloading a new version.
Starting docker containers
docker-compose rm start_dependencies
No stopped containers
go run ./build/docker-compose-generator/
main.go mysql postgres inbucket  minio |
 docker-compose -f docker-compose.makefi
le.yml -f /dev/stdin  run -T --rm start_
dependencies
Starting mattermost-postgres ... done
Starting mattermost-mysql    ... done
Starting mattermost-inbucket ... done
Starting mattermost-minio    ... done
Creating mattermost-server_start_depende
Creating mattermost-server_start_depende
Waiting for mysql to listen on 3306...
sleeping
sleeping
Service mysql:3306 did not start within 300 seconds. Aborting...
ERROR: 1
make: *** [Makefile:255: start-docker] Error 1
```

I expected the make process to complete so I can ping the mattermost API server but I'm not able to get that far.

Any assistance would be appreciated.

**Comment by amyblais** [comment]
@candronikos Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.
