### ISSUE TITLE
Can not switch account when sign in with Google

### ISSUE THREAD

**Issue by lhnoah** [mattermost/mattermost-server#21968]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://www.mattermost.com/feature-ideas/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
I want to sign in with another Google account. But after I logged out and clicked `Sign in with Google Apps`, it logged in directly without my new account. 

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Mattermost 5.2.2 (26066)
1. Log in with google account A
2. Log out
3. Try to log in with google account B, but I can not switch

#### Expected behavior
I can log in with another google account B

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/16415671/210293902-fa4dce00-14b1-45dc-85c1-dccfc5cff1dd.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/16415671/210293933-def2d3c0-425c-457c-9ac7-e8bba4a9d105.png">

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@lhnoah What Mattermost server version are you on?

**Comment by amyblais** [comment]
> @lhnoah What Mattermost server version are you on?

You can find this information from hamburger menu > About Mattermost.
<img width="331" alt="Screenshot at Jan 03 12-36-35" src="https://user-images.githubusercontent.com/29708087/210410964-da2ba1de-59a0-48d7-a139-8bc6f30ebd16.png">
