### ISSUE TITLE
Mattermost container for ARM

### ISSUE THREAD

**Issue by czochblanl** [mattermost/mattermost-server#21979]
Running on MacOS Montery, Apple M1 Max: 

docker run -d mattermost/mattermost-team-edition -p 80:8080
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by amyblais** [comment]
@czochblanl Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by agnivade** [comment]
Hey @czochblanl - Looks like we don't build docker images for `linux/arm64` platform. You should be able to run `linux/amd64` images using Rosetta2 emulation.

**Comment by orbatschow** [comment]
@agnivade 

I think another use case is the usage of Mattermost on a Raspberry Pi. Building the image on your own is possible, but it would be nice to have official images.

**Comment by iiiw** [comment]
@orbatschow 
+1 for linux arm64 images.
Did you notice, there are arm + arm64 builds at [https://github.com/SmartHoneybee/ubiquitous-memory]()?
Saves one step, in combination with [https://github.com/mattermost/mattermost-server/blob/master/build/Dockerfile]().

**Comment by cyberb** [comment]
Still no arm64 image :(

**Comment by iiiw** [comment]
> Still no arm64 image :(

Did you notice this repo? https://github.com/remiheens/mattermost-docker-arm

**Comment by cyberb** [comment]
Even that I could not find on docker hub is it published?
Ideally the official image should have arm64 version: https://hub.docker.com/r/mattermost/mattermost-enterprise-edition/tags

I can build locally no problem.

**Comment by iiiw** [comment]
@cyberb 
Afaik it is not published. It is an interim solution, you have to build locally.
+1 for an official image /arm64 version

**Comment by davidbarratt** [comment]
I was looking to install Mattermost on a Pi (it has an NVMe SSD so should have plenty of horsepower), but was disappointed that there aren't ARM docker images.

**Comment by davidbarratt** [comment]
Although, I'm using k8s and I noticed the `mattermost-operator` **does** have an ARM image:
https://hub.docker.com/r/mattermost/mattermost-operator/tags
does that mean it will work on ARM through k8s? or will it fail at some point?

**Comment by stafot** [comment]
@davidbarratt  mattermost-operator has arm support itself but you need arm build of mattermost application which is not supported at the moment.

**Comment by danielehrhardt** [comment]
Update here?

**Comment by jtama** [comment]
Building an ARM image would really be nice.

All it really take is a matrix env build in the github workflows.

**Comment by davidbarratt** [comment]
> All it really take is a matrix env build in the github workflows.

I think that's trivializing the work because it might take a lot more work than that.
