### ISSUE TITLE
Multi-line code blocks do not work in table

### ISSUE THREAD

**Issue by mkbaldwin** [mattermost/mattermost-server#21970]
#### Summary
Multi-line code blocks do not work in markdown tables.

#### Steps to reproduce

Create a message with the following markdown code:

```
| Test | Test |
|------|------|
| X    | ``` this
breaks```|
```

#### Expected behavior
The text inside the ` ``` ` string should appear formatted as a code block.

#### Observed behavior (that appears unintentional) 
The text ` ``` this` is displayed in the table and then the remaining `breaks ``` ` text is displayed after the table.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-49450.

**Comment by hmhealey** [comment]
Thanks for the report, @mkbaldwin.

Unfortunately, that's something that's not possible with how Markdown tables work. They don't allow newlines within table rows, and they similarly don't allow block elements (code blocks, lists, block quotes, etc) inside of a table. That's also why it doesn't work on GitHub ([link to their formal specification](https://github.github.com/gfm/#tables-extension-)).

We do still appreciate the report though!
