### ISSUE TITLE
`Playbooks` list collapses with all playbooks under it overlapping in a single line

### ISSUE THREAD

**Issue by prapti** [mattermost/mattermost-server#22010]
#### Summary
In the Playbooks section, when the user clicks the `PLAYBOOKS` section header on the LHS to collapse the section, all of the playbooks in the section converge visibly into one line.

Env seen:
* Google Chrome
* Mattermost Version - cloud-2022-12-22-1

#### Steps to reproduce
* In Mattermost, go to the Playbooks area (click from the top left grid panel).
* If you don't have multiple playbooks, create them.
* Once you have more than 1 playbooks, click the `PLAYBOOKS` header on LHS to collapse the playbooks section

#### Expected behavior
Playbooks section collapses cleanly hiding all playbooks

#### Observed behavior (that appears unintentional) 
Playbooks collapse where all existing playbooks overlap and converge in 1 line

Screenshot for reference:
<img width="262" alt="Screenshot 2023-01-06 at 8 13 42 AM" src="https://user-images.githubusercontent.com/691331/211055668-60093735-84a3-4867-a0bd-75cd0b60b160.png">

**Comment by amyblais** [comment]
Hi @prapti! I'll move this to the Playbooks repo.

**Comment by prapti** [comment]
Hi Amy!! :)
Absolutely! And done

**Comment by prapti** [comment]
Should I go ahead and close this one?

**Comment by amyblais** [comment]
Thank you! I'll close this one.
