### ISSUE TITLE
Using database search because no other search engine is available.

### ISSUE THREAD

**Issue by andrei0807** [mattermost/mattermost-server#22016]
Bug report in one concise sentence
When I search text in mattermost, I got error message in server.
I tried to search text in mattermost chatting page.
but I got only "Searching..." message.
so I checked server msg.
![image](https://user-images.githubusercontent.com/32348752/211202128-819b31d3-52a8-4404-a595-c7dbd16e7ccc.png)
I got this error.
How can I solve this issue?

**Comment by anx-ag** [comment]
Hi andrei,

do you have any other search engines active in your setup, like Elastichsearch or Bleve? Is database search disabled (System console -> Environment -> Database -> "Disable database search")?
