### ISSUE TITLE
WebApp: Presence State Indicator not updating in time

### ISSUE THREAD

**Issue by anx-ag** [mattermost/mattermost-server#22059]
See the following discussion on the community server:
https://community.mattermost.com/core/pl/tdp65p898tgwuexyqx3jq3toyr

In a nutshell:
We just found out that the online presence state only gets updated when you reload the browser view. Switching channels etc. does not reload the presence state for others in the channel. Is this intentional and if so, how long is the cache and what else would cause a refresh? I can see the updated status for myself immediately when I change it, but when others do, this change does not get reflected on my screen. 

A coordinated status change was not reflected even after waiting for 10 minutes.

To reproduce:
* Find a friend to test it with (the hardest part)
* Both users in the same channel, both have the status "online"
* One changes the status to "away" or "offline" or anything else but "online"
* The other one should see the updated status "in time" (I'd expect it to happen instantly, but waiting for 30s-1min should in practice not be an issue, but throughout our testings, even after 10 minutes the status was not correct)

Workaround:
CTRL-r immediately updates the status of the other party.

**Comment by thomich** [comment]
Tested from my side on:
. Google Chrome Version 109.0.5414.74 (Official Build) (64-bit)
. Mattermost Desktop App 5.2.0

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49633.

**Comment by thomich** [comment]
hello

i saw that there was a new mattermost community version and reloaded my mattermost desktop.

currently i think, the state indicator works... was that a part of the mattermost community update?
will have an eye on it and report, if i see it not working

regards
thomi

**Comment by amyblais** [comment]
I'm not sure if there was a fix submitted for it, but please report back if you see it again.

**Comment by anx-ag** [comment]
Hi Amy,

we did some further testing today and observed the following behaviour.
The intervals decreased to a point where it actually doesn't matter anymore, we could reproroduce on Community that every status change is reflected within 60s at max, but it sometimes also only takes 1s. Not sure if this is related to the processing load somewhere or if there's a timer running that handles such things, but nevertheless, after 60s at maximum, we saw the changed status from the other party.

What's interesting though is, that custom status changes happen immediately for all channel members, so the custom status change to be seen by the other party happens almost immediately, in both directions (setting it and clearing it), it's just the online status indicator, which takes up to a minute.

We tested it using the GUI settings and the slash commands (`/away`, `/dnd`,  `/online` and `/status`). Should be easy to reproduce now. Wondering what the difference between the custom and online status update method is.

**Comment by agnivade** [comment]
So this seems like expected behavior.

Custom status updates are sent via websocket. Presence status updates aren't, due to excessive server load that is generates. Instead they are polled in a 60s interval. Sometimes, they can be fetched as part of other UI actions as well which is why you sometimes see it get updated immediately.

**Comment by anx-ag** [comment]
Alright, thanks for the clarification, Agniva - greatly appreciated.
I think it's safe to close this issue now, the update interval of 60s at max is absolutely OK for this setting, when we started to debug it, it took a lot longer for unknown reasons but since we're not able to reproduce it anymore, it might have been fixed along the road.

@thomich OK with the closure?

**Comment by thomich** [comment]
hey all

thanks a lot.. and yes, this issue can be closed.. all clear ;)

regards
thomi
