### ISSUE TITLE
command: apply_migration, originalError: Error 1845: LOCK=NONE is not supported for this operation. Try LOCK=SHARED.

### ISSUE THREAD

**Issue by laimison** [mattermost/mattermost-server#22056]
#### Summary

Upgrading Mattermost docker image from 6.1 to 7.7 fails at schema migration because LOCK=NONE is not supported. 

#### Steps to reproduce

Use Percona XtraDB cluster

#### Expected behavior

Schema used to succeed, LOCK=NONE probably started to use in latest Mattermost versions (in between 6.1 to 7.7)

#### Observed behavior (that appears unintentional) 

```
{"timestamp":"2023-01-11 11:53:09.043 Z","level":"fatal","msg":"Failed to apply database migrations.","caller":"sqlstore/store.go:169","error":"driver: mysql, message: failed when applying migration, command: apply_migration, originalError: Error 1845: LOCK=NONE is not supported for this operation. Try LOCK=SHARED., query: \n\nSET @preparedStatement = (SELECT IF(\n    (\n        SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS\n        WHERE table_name = 'Posts'\n        AND table_schema = DATABASE()\n        AND index_name = 'idx_posts_create_at_id'\n    ) > 0,\n    'SELECT 1;',\n    'CREATE INDEX idx_posts_create_at_id on Posts(CreateAt, Id) LOCK=NONE;'\n));\n\nPREPARE createIndexIfNotExists FROM @preparedStatement;\nEXECUTE createIndexIfNotExists;\nDEALLOCATE PREPARE createIndexIfNotExists;\n\n"}
```

#### Possible fixes

Do you have method not to use LOCK=NONE? Any workaround to pass schema migration? So I can use Mattermost as usual once this is done.

**Comment by amyblais** [comment]
@agnivade @isacikgoz Is this a new regression in v7.7?

**Comment by agnivade** [comment]
No, this is an old issue. Mattermost does not support Percona XtraDB cluster.

The workaround is to run `CREATE INDEX idx_posts_create_at_id on Posts(CreateAt, Id)` manually and then upgrade Mattermost.

**Comment by laimison** [comment]
Thanks. Did you mean starting container with sleep so does nothing, then run this query and lastly start container as usual?

Just for your awareness, I have been using this set up for 2.5 year without Mattermost DB issues. So Mattermost is close of supporting Percona XtraDB. Maybe this is not production grade, but the fact that it is working, except reported issue experienced first time.

**Comment by anx-ag** [comment]
You can run this query anytime, it will create the index in a compatible way for Percona and when you upgrade the application then, it will find out that the index already exists and skip this step.

**Comment by laimison** [comment]
Cool, thanks a lot for an advice. Now I can unblock my test environment with an upgrade. Test this and go with prod. I will just switch of mattermost pod/container and then run query on idling DB so no interference ensured.

**Comment by agnivade** [comment]
> Just for your awareness, I have been using this set up for 2.5 year without Mattermost DB issues. So Mattermost is close of supporting Percona XtraDB.

Yes there are lots of variants of MySQL where it can work for several years, but it is not officially supported by Mattermost and can stop working any time, as it did now.

Fortunately, there was a workaround this time. But there might not be one in future. I'd suggest to use Oracle MySQL or Postgres to remain fully supported.

**Comment by laimison** [comment]
Understood. Not the perfect outcome, but solution is there. I will prefer to contribute to Percona as long as app allows it. Please close an issue.
