### ISSUE TITLE
JSON encoded string inside JSON string for 'posted' websockets events

### ISSUE THREAD

**Issue by jorants** [mattermost/mattermost-server#22110]
#### Summary
The web socket event 'posted' contains a json encoded string inside a json encoded string.

#### Steps to reproduce
I am on version 7.1.3.

1. Open a websocket for a bot account using the API v4
2. Post a message to the bot
3. Decode the JSON for the received message the field `data->post` is a string, as is `data->mentions`

#### Expected behavior
The fields should be a javascript dictionary and list.

#### Observed behavior (that appears unintentional) 
It is a JSON encoded string:
```json
{

    "event":"posted",
    "data":{
        "channel_display_name":"@xxx",
        "channel_name":"xxx_xxx",
        "channel_type":"D",
        "mentions":"[\"xxxx\"]",
        "post":"{\"id\":\"xxx\",\"create_at\":1674132302437,\"update_at\":1674132302437,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"xxx\",\"channel_id\":\"xxx\",\"root_id\":\"\",\"original_id\":\"\",\"message\":\"here\",\"type\":\"\",\"props\":{\"disable_group_highlight\":true},\"hashtags\":\"\",\"pending_post_id\":\"xxx:000\",\"reply_count\":0,\"last_reply_at\":0,\"participants\":null,\"metadata\":{}}",
        "sender_name":"@xxx",
        "set_online":true,
        "team_id":""
    },
    "broadcast":{
        "omit_users":null,
        "user_id":"",
        "channel_id":"xxx",
        "team_id":"",
        "connection_id":""
    },
    "seq":3

}
```
I am not familiar with the rest of the API, but this seems strange behavior. It required clients to call a JSON parser extra times by hand.

#### Possible fixes
This seems to be due to https://github.com/mattermost/mattermost-server/blob/bf9d1166d617474756786b313df401db3757a8d7/app/notification.go#L532

(and a bit below for the mentions and possibly follows)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49765.

**Comment by agnivade** [comment]
Yes we are aware of this, and unfortunately this is a deeply entrenched pattern which needs fixes from server and webapp, and will probably break other websocket clients using the server API. And even then, there's the mobile client we need to think about where there can never be a breaking change. Which means even if we _do_ fix this, we have to have both stringified and non-stringified representations at the same time in the response until the last server version goes out of support.

This is a good to have thing for v8, but somewhat of a low priority.
