### ISSUE TITLE
Bulk import crashes with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ogmueller** [mattermost/mattermost-server#22142]
#### Summary
When using `mattermost import bulk file.jsonl` the import crashes with `panic: runtime error: invalid memory address or nil pointer dereference`

#### Steps to reproduce
I have a mattermost server v7.7.1 running on Ubuntu with MySQL. I want to migrate the data to a mattermost docker installation v7.7.1 using postgres now. So I exported the data with quite some utf8mb4 chars in the posts (like emojis "☣️", "I ❤️my job", "👩‍🦯👩‍🦯👩‍🦯👩‍🦯", ...) using `mattermost export bulk file.jsonl`.

When I tried to import the data using `mattermost import bulk file.jsonl`, the import crashed (see Observed behavior).

#### Expected behavior
Bulk import should finish without errors.

#### Observed behavior (that appears unintentional) 
```
# mattermost import bulk file.jsonl
...
{"timestamp":"2023-01-25 00:39:51.357 +01:00","level":"debug","msg":"using plugin","caller":"plugin/hclog_adapter.go:52","plugin_id":"playbooks","wrapped_extras":"version1"}
{"timestamp":"2023-01-25 00:39:51.382 +01:00","level":"info","msg":"registered collection and topic type","caller":"app/collection.go:33","plugin_id":"playbooks","collection_type":"run","topic_type":"status"}
{"timestamp":"2023-01-25 00:39:51.382 +01:00","level":"info","msg":"registered collection and topic type","caller":"app/collection.go:33","plugin_id":"playbooks","collection_type":"run","topic_type":"task"}
{"timestamp":"2023-01-25 00:39:51.397 +01:00","level":"debug","msg":"Not auto installing/upgrade because plugin was disabled","caller":"app/plugin.go:1038","plugin_id":"com.mattermost.calls","version":""}
{"timestamp":"2023-01-25 00:39:51.398 +01:00","level":"debug","msg":"Not auto installing/upgrade because plugin was disabled","caller":"app/plugin.go:1038","plugin_id":"focalboard","version":""}
Running Bulk Import Data Validation.
** This checks the validity of the entities in the data file, but does not persist any changes **
Use the --apply flag to perform the actual data import.

{"timestamp":"2023-01-25 00:39:51.408 +01:00","level":"info","msg":"Stopping Server...","caller":"app/server.go:652"}
{"timestamp":"2023-01-25 00:39:51.408 +01:00","level":"info","msg":"Shutting down plugins","caller":"app/plugin.go:384"}
{"timestamp":"2023-01-25 00:39:51.408 +01:00","level":"debug","msg":"Disabling plugin health check job","caller":"plugin/environment.go:620"}
{"timestamp":"2023-01-25 00:39:51.411 +01:00","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"com.mattermost.nps","wrapped_extras":"pathplugins/com.mattermost.nps/server/dist/plugin-linux-amd64pid129"}
{"timestamp":"2023-01-25 00:39:51.411 +01:00","level":"debug","msg":"plugin exited","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.mattermost.nps"}
{"timestamp":"2023-01-25 00:39:51.411 +01:00","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"playbooks","wrapped_extras":"pathplugins/playbooks/server/dist/plugin-linux-amd64pid161"}
{"timestamp":"2023-01-25 00:39:51.411 +01:00","level":"debug","msg":"plugin exited","caller":"plugin/hclog_adapter.go:54","plugin_id":"playbooks"}
{"timestamp":"2023-01-25 00:39:51.412 +01:00","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"com.mattermost.apps","wrapped_extras":"pathplugins/com.mattermost.apps/server/dist/plugin-linux-amd64pid148"}
{"timestamp":"2023-01-25 00:39:51.412 +01:00","level":"debug","msg":"plugin exited","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.mattermost.apps"}
{"timestamp":"2023-01-25 00:39:51.413 +01:00","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"zoom","wrapped_extras":"pathplugins/zoom/server/dist/plugin-linux-amd64pid119"}
{"timestamp":"2023-01-25 00:39:51.413 +01:00","level":"debug","msg":"plugin exited","caller":"plugin/hclog_adapter.go:54","plugin_id":"zoom"}
{"timestamp":"2023-01-25 00:39:51.413 +01:00","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"pathplugins/com.github.manland.mattermost-plugin-gitlab/server/dist/plugin-linux-amd64pid139"}
{"timestamp":"2023-01-25 00:39:51.413 +01:00","level":"debug","msg":"plugin exited","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"timestamp":"2023-01-25 00:39:55.607 +01:00","level":"info","msg":"stopping websocket hub connections","caller":"platform/web_hub.go:115"}
{"timestamp":"2023-01-25 00:39:55.607 +01:00","level":"info","msg":"Server stopped","caller":"app/server.go:734"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1cabc80]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/v6/app.(*App).bulkImport(0xc000776010, {0x2ccc360, 0xc000652ea0}, {0x2cad040?, 0xc00067e210?}, 0x0, 0x1, 0x2, {0x0, 0x0})
	github.com/mattermost/mattermost-server/v6/app/import.go:259 +0xe80
github.com/mattermost/mattermost-server/v6/app.(*App).BulkImportWithPath(...)
	github.com/mattermost/mattermost-server/v6/app/import.go:179
github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands.bulkImportCmdF(0x414c600?, {0xc00027a760, 0x1, 0x1?})
	github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands/import.go:155 +0x4e5
github.com/spf13/cobra.(*Command).execute(0x414c600, {0xc00027a700, 0x1, 0x1})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x414cbc0)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands.Run(...)
	github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands/root.go:14
main.main()
	github.com/mattermost/mattermost-server/v6/cmd/mattermost/main.go:20 +0x86
```

**Comment by anx-ag** [comment]
Hi Oliver,

did you also try to use the `mmctl` export and import functions? I know that there have been some changes in the last few weeks with regards to memory errors during export/import in the tooling, so please give it a try.

Alternatively, you might want to look at the unofficial guide for migrating the database directly which a user posted here:
https://github.com/mattermost/mattermost-server/issues/18351#issuecomment-1237389445

**Comment by ogmueller** [comment]
Yes, I have tried that as well, but got an error `pq: invalid byte sequence for encoding "UTF8": 0x00`. So that was a dead end, too.
I followed this [migration guide](https://www.tim-kleyersburg.de/articles/migrate-mattermost/).

Now I will give your recommendation a try. Maybe pgloader can solve it.

**Comment by szent** [comment]
I have the same problem with import.
-- Server
bin/mattermost version
Version: 7.7.1
Build Number: 7.7.1
Build Date: Thu Jan 19 00:48:34 UTC 2023
Build Hash: 63149c4869898f8c1d3a94ea728370ec4a07575f
Build Enterprise Ready: true

-- Bulk file
cat team.json 
{"type":"version","version":1}
{"type":"team","team":{"name":"office","display_name":"office","type":"O","description":"","allow_open_invite":false}}

-- Command
bin/mattermost import bulk team.json


-- Result
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1ccde40]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/v6/app.(*App).bulkImport(0xc002c82dd0, {0x3467480, 0xc0027057a0}, {0x3440480?, 0xc0006dead8?}, 0x0, 0x1, 0x2, {0x0, 0x0})
	github.com/mattermost/mattermost-server/v6/app/import.go:259 +0xe80
github.com/mattermost/mattermost-server/v6/app.(*App).BulkImportWithPath(...)
	github.com/mattermost/mattermost-server/v6/app/import.go:179
github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands.bulkImportCmdF(0x520b100?, {0xc00027df80, 0x1, 0x1?})
	github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands/import.go:155 +0x4e5
github.com/spf13/cobra.(*Command).execute(0x520b100, {0xc00027def0, 0x1, 0x1})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x520b6c0)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands.Run(...)
	github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands/root.go:14
main.main()
	github.com/mattermost/mattermost-server/v6/cmd/mattermost/main.go:20 +0x86

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49959.

**Comment by ArchZion** [comment]
Sorry for necroing the issue, we are also experiencing this. This is with version 9.8.

Also with Email notifications disabled, as we see that most releases states that slack imports will fail due to email notifications being enabled.
