### ISSUE TITLE
order users in switch modal for the single user searched to be at the top/ default

### ISSUE THREAD

**Issue by drw-CFL** [mattermost/mattermost-server#22152]
#### Summary

When you use the CTL K to search for a user, the user searched for is show at the bottom of potentially a long list of users including them and other users.

When I search of a user I want that user to be the default and shown at the top of the list followed by groups in which they also participate with other users

#### Steps to reproduce
CTL K type single user intitals,
see a long list of groups they participate in, and then on their own at the bottom of the list 
 
#### Expected behavior
CTL K type single user intitals,
see a long list of groups they participate in, and the individual user searched for  defaulted at the top of the lists 

#### Possible fixes
Order the list by the single user firts and defualt them so that return switches you to them

**Comment by amyblais** [comment]
@drw-CFL What Mattermost server version are you on?

**Comment by drw-CFL** [comment]
Version 4.7.2 

 

 



 

 

David Ward
Product Manager, CoreFiling Limited
Tel: +44 1865 203 192 ext. 1322
 <https://www.corefiling.com/> www.corefiling.com

 

 <https://www.linkedin.com/company/corefiling>   <https://twitter.com/CoreFiling>

**Comment by amyblais** [comment]
@drw-CFL We currently support server versions v7.1.0 and newer. Would you be open to upgrading?
