### ISSUE TITLE
Developing plugins. Watch mode.

### ISSUE THREAD

**Issue by catz** [mattermost/mattermost-server#22173]
#### Summary
Watch mode doesn't work for plugins

#### Steps to reproduce
1. Run test plugin  (https://github.com/mattermost/mattermost-plugin-test/) in watch mode
make watch MM_DEBUG=1 MM_SERVICESETTINGS_ENABLEDEVELOPER=on
2. Open plugin page
3. Make any changes in your code editor
4. Browser refreshes the page
5. team_controller.tsx throws an error because "plugins" channel name is reserved

```
            if (Constants.RESERVED_TEAM_NAMES.includes(teamNameParam)) {
                throw new Error('Team name is reserved');
            }
```

#### Expected behavior
Stays on the same plugin page

#### Observed behavior (that appears unintentional) 
Redirect to team not found route. It worked on 7.5.2 tag of webapp. 

needs_team.tsx

```
        if (Constants.RESERVED_TEAM_NAMES.includes(props.match.params.team)) {
            return;
        }
```

#### Possible fixes
Do not throw an error message for RESERVED_TEAM_NAMES as before or add plugins specified case?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50072.

**Comment by mickmister** [comment]
Also, the mattermost-plugin-test repo is meant for use in automated tests, rather than for plugin development. Check out the https://github.com/mattermost/mattermost-plugin-starter-template repo

**Comment by catz** [comment]
Hello @mickmister 

I'm registering a route for my plugin like this. As far as I understand 'plugins' is the recommended "prefix" for plugins routes, right?

`
    registry.registerProduct(
      `/plugins/${pluginId}/calendar`,
      'calendar-outline',
      ...
`

No, this PR is unrelated. I definitely need a logged in route.

**Comment by mickmister** [comment]
> `registry.registerProduct(/plugins/${pluginId}/calendar, 'calendar-outline', ...`

@catz I don't think using `/plugins` is the right solution here. That prefix is meant for unauthenticated routes, served by the plugin's server hook [ServeHTTP](https://developers.mattermost.com/integrate/plugins/components/server/reference/#Hooks.ServeHTTP).

Here's an example usage of `registerProduct` from [mattermost-plugin-playbooks](https://github.com/mattermost/mattermost-plugin-playbooks/blob/428da300f6f43bbaad3844e4a91fab0a49ea0812/webapp/src/index.tsx#L175-L184):

```js
registry.registerProduct(
    '/playbooks',
    'product-playbooks',
    'Playbooks',
    '/playbooks',
    BackstageWrapped,
    GlobalHeaderCenter,
    GlobalHeaderRight,
    enableTeamSidebar
);
```

**Comment by catz** [comment]
And what is the right solution for user plugins?

I can't use route like /calendar because in this case I will get into team not found case.
/playbooks works because this is predefined name in Constants.RESERVED_TEAM_NAMES. /boards another example that works 

And yes, we use urls like /plugins/:name/api/... as plugin API endpoint. And at the same time as client routing urls. It's very convenient to use urls like /plugins/:name/client/whatever it gives users ability to open plugin directly on the given page.

**Comment by mickmister** [comment]
@catz At the moment, I don't think there is a proper solution for user plugins to hook into this functionality. If you're trying to integrate into the MM webapp, using `/plugins/*` is probably not the way to go, as the webapp isn't served from this URL.

> And at the same time as client routing urls.

I'm not familiar with the use case of using the `/plugins/*` prefix for this

> /playbooks works because this is predefined name in Constants.RESERVED_TEAM_NAMES

I suppose we'll need to change how `registerProduct` works to support other route names. There is currently a warning comment in the code above the definition of `registerProduct`, that says it's only for internal use at the moment, so I think other plugins haven't been taken into account.

https://github.com/mattermost/mattermost-webapp/blob/86fb1ca093dd69613120888dac9a425c75a9b58f/plugins/registry.ts#L971-L977:

```js
    /**
     * INTERNAL: Subject to change without notice.
     * Register a Product, consisting of a global header menu item, mainComponent, and other pluggables.
     * @remarks DANGER: Interferes with historic routes.
     * @see {@link ProductComponent}
     * @returns {string}
     */
```

**Comment by catz** [comment]
@mickmister 

Well, ok. We have been successfully using /plugins/:id/* for quite long time and do not see any issues, except this one. But this inconvenience is during development only.  So, for dev purposes we just replaced throw to return as from previous webapp versions and hot reload works perfect.

**Comment by mickmister** [comment]
> But this inconvenience is during development only

Does the error occur in production when you upgrade the plugin?

@trilopin What are your thoughts on this issue?

**Comment by catz** [comment]
No, this particular issue is only for development and for plugin reloads in watch mode.

btw for direct plugin urls and page reloads we took the idea from playbooks plugin because haven't found any examples in docs.

1. goto url like /plugins/:id/calendar/
2. plugin server's part redirects to /plug/r:id/calendar/  (see registerCustomRoute, register a component to be displayed at a custom route under /plug/:pluginId)
3. plugin intercepts it and redirects to plugin url  /plugins/:id/calendar/ (idea from playbooks)

`
        // Redirect old routes
        registry.registerNeedsTeamRoute('/error', OldRoutesRedirect);
        registry.registerNeedsTeamRoute('/', OldRoutesRedirect);
`

>I'm not familiar with the use case of using the /plugins/* prefix for this

Maybe idea was /plug/:id ? Maybe we need to add /plug into Constants.RESERVED_TEAM_NAMES list?

**Comment by trilopin** [comment]
We recently had a similar issue at playbooks and was solved [here](https://github.com/mattermost/mattermost-webapp/pull/12022/files). 

I've checked that ["plugins"](https://github.com/mattermost/mattermost-webapp/blob/master/utils/constants.tsx#L1503) is listed as a reserved team name and therefore,  a name collision is not possible.

@catz could you confirm if still fails with a recent version of mattermost-webapp? The fix was merged 3 weeks ago.

**Comment by trilopin** [comment]
That said, Even if the code works once the mattermost-webapp is updated, I'm still not sure if `/plugins/Xxx` URLs should be used.

**Comment by catz** [comment]
@trilopin I will try tomorrow, but looking at the code, it should be working.

**Comment by mickmister** [comment]
> Based on this document, I do not see that registerProduct is not recommended path. Methods like registerCustomRoute aren't described enough either.

That page is generated from the source code [here](https://github.com/mattermost/mattermost-webapp/blob/86fb1ca093dd69613120888dac9a425c75a9b58f/plugins/registry.ts#L971-L977). I'm not sure why the internal comments weren't carried over

**Comment by catz** [comment]
Hello @trilopin @mickmister 

Yes, I can confirm on the latest master this issue doesn't exist. Thanks.
This is what we needed https://github.com/mattermost/mattermost-webapp/pull/12022/files
