### ISSUE TITLE
Mattermost v7.7 "Unable to save channel."

### ISSUE THREAD

**Issue by ekarani** [mattermost/mattermost-server#22184]
#### Summary
Upgraded from Mattermost version 5.38 to version 7.7. I made intermediate upgrades, like from 5.38 to 6 and so on, following the instructions at the upgrade notes (https://docs.mattermost.com/upgrade/important-upgrade-notes.html). Almost everything is doing fine, but I can't create a new channel.

#### Steps to reproduce
Deploy Mattermost server with the docker images provided here, using MySQL 5.7 as database.
Upgrade from 5.38 to 6.0 with database changes. 
Upgrade from 6.0 to 6.7. 
Upgrade from 6.7 to 7.1.
Upgrade from 7.1 to 7.2.
Lastly, upgrade from 7.2 to 7.7

#### Expected behavior
When I choose to create a new channel or new direct message, it should immediately be created.

#### Observed behavior (that appears unintentional) 
No new channel is created and the logs shows this message: 
```
{"timestamp":"2023-01-30 17:04:31.619 Z","level":"error","msg":"Unable to save direct channel.","caller":"web/context.go:117","path":"/api/v4/channels/direct","request_id":"36jh7z3kxpdw7qmcs6b9nkop4e","ip_addr":"xxx.xxx.xxx.xxx","user_id":"ht6hpmtgu7rydbw58we78xc1na","method":"POST","err_where":"createDirectChannelWithUser","http_code":500,"error":"createDirectChannelWithUser: Unable to save direct channel., save_channel: id=kfh4mkojkbyhfdys4843ywm3oe: Error 1054: Unknown column 'LastRootPostAt' in 'field list'"}
```

#### Possible fixes
Tried to add the uknown column to the database, but it broke the application.
Also tried to follow the solution suggested at this issue: https://github.com/mattermost/mattermost-server/issues/19269
Still nothing.

**Comment by amyblais** [comment]
@ekarani Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by anx-ag** [comment]
Hi @ekarani ,

I'm wondering why this happened, but you should be able to fix that with the following queries:

```sql
ALTER TABLE Channels ADD COLUMN LastRootPostAt bigint AFTER TotalMsgCountRoot;
UPDATE Channels SET LastRootPostAt=0 WHERE LastRootPostAt IS NULL;
```
