### ISSUE TITLE
feature proposal: add support to customize the Incoming Webhook URL

### ISSUE THREAD

**Issue by PengBAI** [mattermost/mattermost-server#22212]
Hello the team,

**Context:** 
We have double URL for Mattermost, one Internal URL and one External URL. By default, we define External URL as SiteURL.

But for the Incoming Webhooks, we would like to have Internal URL by default for users to bypass the proxy etc.

![image](https://user-images.githubusercontent.com/6213328/216099888-e0e3ccb1-10e4-4c94-b694-118f3ac7eeef.png)

Feature Proposal:
* support the customized incoming webhooks url

```json
...
"EnableIncomingWebhooks": true,
"IncomingWebhooksBaseURL": ""
"EnableOutgoingWebhooks": true,
...
```

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @PengBAI,

Would you like to [contribute this in the feature idea forum](https://portal.productboard.com/mattermost/33-what-matters-to-you)? Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by PengBAI** [comment]
Hello @amyblais 
Thanks for the quick feedback. 
Idea submitted on that portail. 
regards

**Comment by asatkinson** [comment]
Hi @PengBAI.  Thanks for the request.  Are you looking for the ability of a single incoming webhook to have two urls?

**Comment by PengBAI** [comment]
> Hi @PengBAI. Thanks for the request. Are you looking for the ability of a single incoming webhook to have two urls?

Hi @asatkinson, 
Not exactly, 1 URL is OK for my case. But I'm looking for the way to overwrite/customize the default one.
For my use case, we have 2 urls for MM service, 1 internal one and 1 external . For normal use, we use external URL(default URL) via proxy from association's internal networking, and for the incoming webhook, we would like to use the internal URL to ease the proxy pression for internal alerting/monitoring etc.
Today, user can change the URL to internal manually, But if we could customize the incoming webhook url in config file, it would be like a charm. :)
