### ISSUE TITLE
API call to create playbook run does not respect the option to attach to existing channel

### ISSUE THREAD

**Issue by bizlabs** [mattermost/mattermost-server#22220]
#### Summary
Mattermost 7.7 introduces the option to link a playbook to an existing channel instead of creating a new channel.  This works fine when creating a playbook run interactively from the web console but not when playbook run created from API.

#### Steps to reproduce in mattermost 7.7.1 enterprise
1. Go to Playbooks and create a playbook or select an existing one
2. Select  "Link to an existing channel" under "Actions" and select a channel.
3. Create a playbook run using the following api call
4. POST 'http://localhost:8065/plugins/playbooks/api/v0/runs' {body}
5. playbook run and a new channel is created with same name and linked.  The run is not linked to the requested link channel.
6. optionally, verify playbook is valid by creating a run interactively with the blue "run" button at top right of playbook page and verify that new run is linked to the channel requested in step 2.

#### Expected behavior
expected that the new playbook run will be linked to the existing channel requested in step 2 above.

#### Observed behavior (that appears unintentional) 
no error message.  Just doesn't link the playbook run to the expected channel

**Comment by amyblais** [comment]
Hi @bizlabs, would you be open to re-opening this issue in the Playbooks repo https://github.com/mattermost/mattermost-plugin-playbooks/issues?
