### ISSUE TITLE
Search doesn't work for dates (/numbers?)

### ISSUE THREAD

**Issue by klux2** [mattermost/mattermost-server#22252]
#### Summary
Searching for messages with dates in the ISO 8601 format (YYYY-MM-DD) doesn't work

#### Steps to reproduce
1. Write a message with a date ("2023-02-04")
2. Search for that date 

The version is Mattermost Professional v7.7.1 (but it's been like this for a month now I think)

#### Expected behavior
The message with the date shows up

#### Observed behavior (that appears unintentional) 
The message can't be found
![grafik](https://user-images.githubusercontent.com/33726251/216766952-b6f281f7-c88f-4696-aa64-d1dbb4b683d1.png)

Searching for just the year works, but searching for the whole date or just month or day doesn't.

#### Possible fixes
No idea, but this still worked in one of the recent versions (I think 7.5?).

**Comment by anx-ag** [comment]
Hi,

what search engine do you use? Database or Bleve? I cannot reproduce that using the Elasticsearch engine on my system.

**Comment by klux2** [comment]
Right, sorry. We're using database search (but no Elasticsearch).

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-50346.

**Comment by agnivade** [comment]
@klux2 - what database you are using and at what version?

**Comment by klux2** [comment]
> @klux2 - what database you are using and at what version?

We're using mysql. I have to check the current version (but it's a recent one).

**Comment by klux2** [comment]
The version is 8.0 (and we're using it in a Galera cluster, if that's relevant)

**Comment by agnivade** [comment]
This happens because "-" is treated as a special character and gets converted into a space. So we split the search term at "-" and build it again with "+" and a space. This fails in searches with dates, but this is necessary to satisfy other kinds of searches.

In short, DB search is not 100% perfect, and we recommend to use a dedicated search engine like Elasticsearch or Bleve for an improved experience.
