### ISSUE TITLE
"Threads" menu entry shows unread messages even though there are none

### ISSUE THREAD

**Issue by nt7** [mattermost/mattermost-server#22288]
#### Summary
"Threads" menu entry shows unread messages flag, even though there are no unread threads.

#### Steps to reproduce
Upgraded to v7.7, then enabled Collapsed Reply Threads, got the new menu entry on the left and got unread messages displayed there
Mattermost Version: 7.7.0
Database Schema Version: 100

#### Expected behavior
There should be no flag (red circle with number 3) next to the menu entry.
When I click on it, and I go to unreads, it shows "no unread threads", as well as on the right side, it says "you are all caught up"
the "flag

#### Observed behavior (that appears unintentional) 
nothing out of the ordinary.
When I disable Collapsed Reply Threads, then there are no unread mesages anymore.
As soon as I activate the feature, it shows 3 unread messages again

![grafik](https://user-images.githubusercontent.com/6541486/217814201-ec88dd97-f502-4367-b047-c87adc7ef5ec.png)

#### Possible fixes
not sure... ?

**Comment by amyblais** [comment]
Closing as a duplicate of https://github.com/mattermost/mattermost-server/issues/22060.
