### ISSUE TITLE
Uploading Image stuck at processing

### ISSUE THREAD

**Issue by codihaus** [mattermost/mattermost-server#22335]
#### Summary
- Upload image files from clipboard stuck at processing (sometimes, not usually)
- Have to Ctrl V one more time (duplicate upload), then the first image will appear successfully.

#### Steps to reproduce
- Take screenshot to clipboard
- 1st try: Ctrl V -> Processing
- 2nd try: Ctrl V (again) -> 1st try image appear, 2nd try stuck at processing

#### Expected behavior
- It should upload successfully

====
MM 7.7.1
MM Desktop + Mobile: 5.2.2
Nginx Reserve Proxy

**Comment by agnivade** [comment]
cc @koox00 

Hey @codihaus - some quick questions:
1. Can you ensure that the uploaded image does not exceed the `nginx_max_body_size` or any other server side setting?
2. Can you disable `AllowSyncedDrafts` and check if that helps?

**Comment by codihaus** [comment]
Hello @agnivade 

Thank you for your response

1/ Nginx set 100Mb upload file size, files and images only around 700Kb to 5-6Mb each, upload to S3, S3 connectivity ok.

I'm using S3 compatible, so from my server to S3 service is close by

2/ I'm not sure, but before it does not have this issues, just around 7.5 and later have this.

**Comment by agnivade** [comment]
2. Yeah, the drafts feature is a new one introduced in 7.7. Can you please disable the feature and check if that fixes for you?

**Comment by codihaus** [comment]
I have disabled it and clear cache as well, I will keep it you updated if the problem appear soon.

**Comment by codihaus** [comment]
Hello @agnivade It still happend

Take screenshot and save to clipboard

- Ctrl V: Stuck at processing<img width="1135" alt="image" src="https://user-images.githubusercontent.com/68498487/218664277-7e9d6180-7ace-4a54-b4b2-e3107acef0ab.png">

- Ctrl V - Paste again: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68498487/218664535-975839fb-49c0-425a-861c-7e685c195ee0.png">

- Ctrl V - Paste again: the 2nd image appear immediately
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/68498487/218664791-b23a9664-5c72-4264-bff5-e24dd201efb0.png">

It seems that image is uploaded successfully, but couldn't call the thumbnail API for that image.
But after paste another one, it will call thumbnail and appear.

**Comment by agnivade** [comment]
@koox00 :point_up:

**Comment by koox00** [comment]
Thanks @codihaus for reporting, there are some fixes on file uploading not reflecting state in the UI, which are fixed for 7.8, see https://github.com/mattermost/mattermost-webapp/pull/12107

The issue was that if you edit the message while you are uploading the upload will appear stuck in processing.
Can you confirm that that is the case on your side?

Nevertheless we'll backport to 7.7 as well and let you know :)

**Comment by codihaus** [comment]
That's true, the link you gave above, I tried to follow, I had the same problem as well.

If I have something written already, then upload again, it will stuck at processing.

But in my case, it might happen without editing, that mean without typing anything already, it could happend as well.

All I can see is the upload success, but thumbnail API has not been called, so reserve to that, I think it could be something to prevent thumbnail API from called. Do you have any idea @koox00 ?

**Comment by koox00** [comment]
@codihaus the way it was handled before it was easy for something else to cancel the update function that was handling the UI after a successful upload.

Where you read "something else" it could be: a) editing the post, or b) blurring the text input.

The fix separates the file upload success handler so it can't be canceled if the above actions trigger a draft to be updated.

Try to paste an image but don't click anywhere outside the textinput to see if it successfully updates the processing state.

**Comment by amyblais** [comment]
Closing as a dup of https://github.com/mattermost/mattermost-server/issues/21903. This links to the ticket that has been fixed.
