### ISSUE TITLE
Server seems to have memory leak with *WebSocketEvent.PrecomputeJSON()

### ISSUE THREAD

**Issue by scriptdealer** [mattermost/mattermost-server#22351]
#### Summary
Server goes out of memory more and more often as users count grow.

#### Steps to reproduce
We have Mattermost: 7.7.0 TE over CentOS Linux release 7.7.1908 (Core)
Machine have 6 CPU cores, 16 Gb RAM, and PostgreSQL
2k users

#### Expected behavior
Server memory consumption should be under 4 Gb at any given time.

#### Observed behavior (that appears unintentional) 
Server regularly goes OOM, and at night times (with zero load) can easily use 6Gb
![memory_usage](https://user-images.githubusercontent.com/20861730/219674869-3e8542a6-8db0-44c7-9794-4b1d3a637258.png)

#### Possible fixes
I'm attaching heap use and heap objects snapshots, taken with pprof.
First candidate to check is *WebSocketEvent.PrecomputeJSON()
![heap_objects](https://user-images.githubusercontent.com/20861730/219675669-4c378307-e2fa-4865-9d37-b12dbea4d382.svg)
![heap_space](https://user-images.githubusercontent.com/20861730/219675674-cb04b2f5-4281-4f70-a12d-09ea686887dd.svg)

Check out [this](https://github.com/ozontech/insane-json) approach to json encoding, if you need to

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50589.

**Comment by agnivade** [comment]
@scriptdealer - Can you please attach the heap profile that you captured? I am looking for the entire file and not the screenshot.

**Comment by scriptdealer** [comment]
@agnivade Sure
[heap.zip](https://github.com/mattermost/mattermost-server/files/10773405/heap.zip)

**Comment by byigorv** [comment]
Do you have any ideas? I faced the same problem

**Comment by scriptdealer** [comment]
@byigorv Provide a heap profile, this might help. To do so, enable Performance monitoring in System console, then run `curl -sK -v http://yourmattermost:8067/debug/pprof/heap > heap.profile`

**Comment by agnivade** [comment]
I took a look. There isn't a leak, but spikes in allocation. I have some ideas that will reduce this. Will send a PR.

**Comment by scriptdealer** [comment]
Thanks, let us see if this solves the spikes. Is there a scheduled release number for this PR ?

**Comment by agnivade** [comment]
It won't fully resolve the spike, but should reduce the amplitude of it slightly. In your case, it seems like there are sudden bursts of websocket broadcasts which is causing this.

It should be released in 7.10.

**Comment by scriptdealer** [comment]
Yeah, I thought of this.. But why do you think it is not a leak ? On graph above there are clearly seen 5 working days, followed by 2 weekends. And I can see that even without spikes, memory consumption grows all the week long, though rolling back at nights - but not to the Sunday values

**Comment by agnivade** [comment]
Atleast from the profiles you attached, it shows that all allocated memory is coming from `*WebsocketEvent.PrecomputeJSON()` which just marshals to JSON. So it's an allocation issue where the memory will not be reclaimed until the next GC runs.
