### ISSUE TITLE
[CRITICAL] Error/Virus on Windows

### ISSUE THREAD

**Issue by m-salman-afzal** [mattermost/mattermost-server#22368]
#### Summary
![image](https://user-images.githubusercontent.com/53542416/220611832-4c3ac989-3ded-4429-9e2f-f96b5826e7b3.png)

#### Steps to reproduce
We are unable to access out mattermost app on windows. Our other users on Linux, Mac, Android are able to access it properly.

#### Expected behavior
Should run properly

#### Observed behavior (that appears unintentional) 
As in summary. Also, when going to out server on web, it starts downloading a zip file containing some Updaters.

#### Possible fixes
It seems like a virus, so kindly help resolve.

**Comment by amyblais** [comment]
@m-salman-afzal Thanks, would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by m-salman-afzal** [comment]
Sure. Should I close this issue then?

**Comment by m-salman-afzal** [comment]
We caught the issue. It is on our end in our server. It is infected with malware. Thanks for the help.
