### ISSUE TITLE
Site UI doesn't respect /path/ part of SiteURL

### ISSUE THREAD

**Issue by baznikin** [mattermost/mattermost-server#22369]
#### Summary
Links for password reset, invitaion, email validation doesn't work in emails it SiteURL contains come path.

#### Steps to reproduce
1. set SiteURL to something like https://DOMAIN/landing#
1. click 'Reset password' link
2. links in emails be like https://DOMAIN/landing/#/reset_password_complete?token=xxxx
3. if follow this link UI will show login screen not password reset form

#### Expected behavior
Password reset form showed

#### Observed behavior (that appears unintentional) 
Site UI doesn't respect /path/ part of SiteURL and show login form instead

**Comment by amyblais** [comment]
Hi @baznikin 
1. What Mattermost server version are you on?
2. Are there any server log errors?
3. What OS and version are you on?

**Comment by baznikin** [comment]
Hello @amyblais 

Regarding your questions:

1. 7.7.1
2. Server logs do not help here. As far as I see code for sending links in email ([password reset as example](https://github.com/mattermost/mattermost-server/blob/079449e30af683c5c8115b91e53661372b86da30/app/email/email.go#L377)) just get siteURL as is and add required path and arguments. Then when user click this link web UI loaded and should and should render right link.
3. Many users with various platforms report it to me (Windows, Linux, iOS)

First of all, sorry for misinformation, I provide wrong examples in first message.I edit to show connect SiteURL for my issue  (it is should be `https://domain/landing#`). I suppose now I see why run into this issue - because of anchor `#` in URL. I'll try to check it.

**Comment by baznikin** [comment]
I double-checked, Mattermost work fine with some /path in SiteURL. My issue was because of somehow introduced anchor (`#`) symbol in path. Closing issue.
