### ISSUE TITLE
Calls config page crashes with white screen of death

### ISSUE THREAD

**Issue by Roy-Orbison** [mattermost/mattermost-server#22395]
#### Summary
Test calls appear to work, but opening the _Calls_ config page in the System Console crashes.

#### Steps to reproduce
Upgrade from Team Edition ESR v7.1.5 to v7.8.0. Open _System Console > Plugins > Calls_.

#### Expected behavior
See a normal config page.

#### Observed behavior (that appears unintentional) 
I've visited `https://mm.redacted.example/admin_console/plugins/plugin_com.mattermost.calls` in two separate browsers (Chrome and Firefox). There's a very brief flash of the Console's main menu, then the entire page becomes empty with an off-white background.

The JS console shows the following errors:
``` none
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). 8 content-script.js:40:65
The Components object is deprecated. It will soon be removed. export.js:72:4
Uncaught (in promise) TypeError: can't access property "forEach", t is undefined
    Redux 12
apps.ts:109:4
TypeError: can't access property "rtcdserviceurl", t.Plugins[Bn.id] is undefined
    Gl com.mattermost.calls_b9e5bb24e35cc920_bundle.js:2
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
react-dom.production.min.js:216:199
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
TypeError: can't access property "rtcdserviceurl", t.Plugins[Bn.id] is undefined
    Yl com.mattermost.calls_b9e5bb24e35cc920_bundle.js:2
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
react-dom.production.min.js:216:199
TypeError: can't access property "rtcdserviceurl", t.Plugins[Bn.id] is undefined
    Kl com.mattermost.calls_b9e5bb24e35cc920_bundle.js:2
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
react-dom.production.min.js:216:199
Uncaught TypeError: can't access property "rtcdserviceurl", t.Plugins[Bn.id] is undefined
    Gl com.mattermost.calls_b9e5bb24e35cc920_bundle.js:2
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
com.mattermost.calls_b9e5bb24e35cc920_bundle.js:2:766451
```
#### Possible fixes
I got around it by disabling then removing the plugin, then deleting all records from the `PluginKeyValueStore` table where `PluginId` was `com.mattermost.calls`, then reinstalling the plugin.

**Comment by amyblais** [comment]
@Roy-Orbison Would you be open to re-opening this issue at https://github.com/mattermost/mattermost-plugin-calls/issues?
