### ISSUE TITLE
S3 file uploading is broken

### ISSUE THREAD

**Issue by asenchuk** [mattermost/mattermost-server#22433]
### Summary
S3 file uploading is broken in versions 7.7, 7.8
#22336 seems similar except I'm using AWS S3.

### Environment
1. 7.5.2 Team, self-hosted on EC2 in Docker
2. AWS S3 accessed with IAM role (no access key / secret)
3. Worked well in 7.3 and then in 7.5 after upgrade with no other action

### Steps to reproduce (mine)
1. Change version in dotenv to 7.7 (or 7.8)
2. Re-up docker compose
3. Upload a file in any chat - fails
4. Test Connection in System Console - File storage - fails

### Expected behavior
File storage continues working as it did after previous updates.

### Observed behavior (that appears unintentional)
Files are not uploading with such an error message:
```
mm-mattermost-1   | {"timestamp":"2023-03-03 23:52:06.876 +03:00","level":"error","msg":"Unable to write the file.","caller":"web/context.go:117","path":"/api/v4/files","request_id":"ufsfbyyqq7dedjnhcmwheq6rca","ip_addr":"172.18.0.4","user_id":"3mp4f8hwgibobkj8uyuuptt41c","method":"POST","err_where":"WriteFile","http_code":500,"error":"WriteFile: Unable to write the file., unable write the data in the file 20230303/teams/noteam/channels/x61keiucdbdt3g45jewwiciedh/users/3mp4f8hwgibobkj8uyuuptt41c/mnr71e1mip8smmqi9ruk9g9aic/as2hftou7pw3qi053ocgb53gwbu6oy6o.pdf: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded"}
```

File storage connection test fails with:
```
mm-mattermost-1   | {"timestamp":"2023-03-03 23:53:04.059 +03:00","level":"error","msg":"Unable to connect to S3. Verify your Amazon S3 connection authorization parameters and authentication settings.","caller":"web/context.go:117","path":"/api/v4/file/s3_test","request_id":"kf4c71bnwpryxf7ay9p13sewhw","ip_addr":"172.18.0.4","user_id":"3mp4f8hwgibobkj8uyuuptt41c","method":"POST","err_where":"TestConnection","http_code":500,"error":"TestConnection: Unable to connect to S3. Verify your Amazon S3 connection authorization parameters and authentication settings., unable to check if the S3 bucket exists"}
```

As the test connection failed with an advice to verify creds I tried to add access key + secret and Test Connection passed well. But uploads still no worked with the same issue in console. Reverted to 7.5 for now as I need chats working.

### Possible fixes
The only change in 7.5 -> 7.7 (and further) I spotted so far in relation to S3 is upgrading minio from `v7.0.34` to `v7.0.45` so the issue may be related to it.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51082.

**Comment by agnivade** [comment]
I am unable to reproduce this. Note that there is a timeout setting `AmazonS3RequestTimeoutMilliseconds` which controls API requests with AWS. If that's set to too low, you might get the `context deadline exceeded` error.

**Comment by asenchuk** [comment]
Thanks for taking care of it. I have a default `AmazonS3RequestTimeoutMilliseconds` and it's `30000`, but the error is logged almost immediately after I send a file (drag-n-drop it to a chat). There's probably 1 sec delay but definitely not 30 sec.

**Comment by agnivade** [comment]
This seems to be an unrelated error outside of Mattermost.

**Comment by abourget** [comment]
Errors to S3, or similar systems, will, from time to time, have errors, networks, etc.. I think a system should retry a few times, to avoid those situations. I have a similar issue during the import process.. so it's basically kill of files from being imported. It's annoying, I can live with it, but it wouldn't be hard to wrap the upload process with a retry loop, 3-5 times or something.
