### ISSUE TITLE
getUsersSidebarCategories incorrectly reports "sorting" value

### ISSUE THREAD

**Issue by theAkito** [mattermost/mattermost-server#22445]
#### Summary
When creating a new Category via [CreateSidebarCategoryForTeamForUser](https://api.mattermost.com/#tag/channels/operation/CreateSidebarCategoryForTeamForUser) with the following payload

```json
{
  "user_id": "user_id",
  "team_id": "team_id",
  "display_name": "My Category",
  "type": "custom",
  "sorting": "manual"
}
```

then retrieving all the categories from the user via [GetSidebarCategoriesForTeamForUser](https://api.mattermost.com/#tag/channels/operation/GetSidebarCategoriesForTeamForUser) results in the previously created Category containing an empty string as the value for `"sorting"` in the returned array of Category objects.

#### Steps to reproduce
1. Create a new Category via [CreateSidebarCategoryForTeamForUser](https://api.mattermost.com/#tag/channels/operation/CreateSidebarCategoryForTeamForUser) with `"sorting": "manual"`.
2. Retrieve all categories from the user via [GetSidebarCategoriesForTeamForUser](https://api.mattermost.com/#tag/channels/operation/GetSidebarCategoriesForTeamForUser) and notice, how `"sorting": ""`.

#### Expected behavior
Sorting attribute should be reported, correctly.

#### Observed behavior (that appears unintentional) 
The API wasn't aware of this issue.

In the GUI, the sorting was set to "manual". It might also be the case, that during the creation of a category the `sorting` attribute is ignored, which would be something to fix, either way.

#### Workaround
Update User's Sidebar Categories via [UpdateSidebarCategoryForTeamForUser](https://api.mattermost.com/#tag/channels/operation/UpdateSidebarCategoryForTeamForUser) or [UpdateSidebarCategoriesForTeamForUser](https://api.mattermost.com/#tag/channels/operation/UpdateSidebarCategoriesForTeamForUser) with `"sorting": "manual"` re-added, after retrieving the current category state via [GetSidebarCategoriesForTeamForUser](https://api.mattermost.com/#tag/channels/operation/GetSidebarCategoriesForTeamForUser).

**Comment by theAkito** [comment]
```
Mattermost Version: 7.5.2
Database Schema Version: 95
Database: postgres
```

**Comment by tanmaydatta** [comment]
Hi
As [theAkito](https://github.com/theAkito) suggested in the initial post, the sorting attribute is actually being ignored. Code pointer = https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/channel_store_categories.go#L338

I will fix this and soon raise a PR
This is the first time I am going to contribute, please let me know if need to take care of something else.
Thanks
