### ISSUE TITLE
Unable to set SMTP Server settings via system console

### ISSUE THREAD

**Issue by Morpheus0x** [mattermost/mattermost-server#22456]
#### Summary
Setting SMTP Server settings with authentication produced broken config

#### Steps to reproduce
1. Install the latest Mattermost with Ubuntu Omnibus (Ubuntu 22.04, Mattermost Version: 7.8.0, Database Schema Version: 101)
2. Create the first user and open the system console
3. Go to `Environment -> SMTP` and add an email server with authentication. I tried port 465 with TLS, 25 and 587 with STARTTLS
4. Save and click `Test Connection`

#### Expected behavior
Mattermost should successfully send test mail

#### Observed behavior (that appears unintentional) 
The following error is displayed after trying to send test mail: `Connection unsuccessful: Connection unsuccessful: unable to connect to the SMTP server: context deadline exceeded`
This is the Mattermost log output:
```
{"timestamp":"2023-03-08 06:09:28.749 Z","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:96","worker":"ProductNotices","job_id":"7qesrw671bb49nc9k1mps8breo"}
{"timestamp":"2023-03-08 06:49:42.842 Z","level":"warn","msg":"Unrecognized config permissions tag value.","caller":"api4/config.go:426","tag_value":"sysconsole_write_*_read"}
{"timestamp":"2023-03-08 06:49:42.897 Z","level":"warn","msg":"plugin configured with a nil SecureConfig","caller":"plugin/hclog_adapter.go:72","plugin_id":"com.mattermost.apps"}
{"timestamp":"2023-03-08 06:49:43.084 Z","level":"warn","msg":"plugin configured with a nil SecureConfig","caller":"plugin/hclog_adapter.go:72","plugin_id":"playbooks"}
{"timestamp":"2023-03-08 06:49:43.099 Z","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"com.mattermost.apps","wrapped_extras":"pathplugins/com.mattermost.apps/server/dist/plugin-linux-amd64pid7666"}
{"timestamp":"2023-03-08 06:49:43.099 Z","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:166","plugin_id":"com.mattermost.apps","error":"failed to ensure bot account: failed to set profile image: SetProfileImage: Couldn't upload profile image., "}
{"timestamp":"2023-03-08 06:49:43.224 Z","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"playbooks","wrapped_extras":"pathplugins/playbooks/server/dist/plugin-linux-amd64pid7672"}
{"timestamp":"2023-03-08 06:49:43.224 Z","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:166","plugin_id":"playbooks","error":"failed to ensure bot: failed to set profile image: SetProfileImage: Couldn't upload profile image."}
{"timestamp":"2023-03-08 06:49:48.713 Z","level":"warn","msg":"Error decoding the config","caller":"api4/system.go:202","path":"/api/v4/email/test","request_id":"144fatyu1bn4td11gihyubcujh","ip_addr":"127.0.0.1","user_id":"19kkfbshnfr3x85hfe8roagjka","method":"POST","error":"EOF"}
{"timestamp":"2023-03-08 06:49:58.714 Z","level":"error","msg":"Connection unsuccessful: unable to connect to the SMTP server through TLS: context deadline exceeded","caller":"web/context.go:117","path":"/api/v4/email/test","request_id":"144fatyu1bn4td11gihyubcujh","ip_addr":"127.0.0.1","user_id":"19kkfbshnfr3x85hfe8roagjka","method":"POST","err_where":"testEmail","http_code":500,"error":"testEmail: Connection unsuccessful: unable to connect to the SMTP server through TLS: context deadline exceeded"}
```

#### Possible fixes
The workaround I found was setting all SMTP options via environment variables. Doing this with the same values used in the system console works and now sending test mail is possible. Maybe a special character for the SMTP password produces a problem when set via system console?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51249.

**Comment by Morpheus0x** [comment]
> Do you think that the locales might be affecting (e.g.: using a german character that might not be supported?)

I don't know, but I first had a password with many special characters and then changed to one that only had one % sign and the other chars were only english letters and numbers and it still didn't work. My email server requires at least one special char, therefore I couldn't test without it

**Comment by agnivade** [comment]
@Morpheus0x - Indeed, it looks like the API to save the config from system console failed:

```
{"timestamp":"2023-03-08 06:49:48.713 Z","level":"warn","msg":"Error decoding the config","caller":"api4/system.go:202","path":"/api/v4/email/test","request_id":"144fatyu1bn4td11gihyubcujh","ip_addr":"127.0.0.1","user_id":"19kkfbshnfr3x85hfe8roagjka","method":"POST","error":"EOF"}
```

It's a bit strange that a password with special characters is not getting saved. Are other config changes in the system console working fine for you?
