### ISSUE TITLE
Small dot on AddChannelDropdown Menu

### ISSUE THREAD

**Issue by sinansonmez** [mattermost/mattermost-server#22473]
#### Summary
Small white dot appeared when AddChannelDropdown menu is opened

#### Steps to reproduce
Click the plus icon button on top left

#### Expected behavior
No dot should appear

#### Observed behavior (that appears unintentional) 
check the top left of screen show
<img width="269" alt="Screen Shot 2023-03-09 at 23 20 06" src="https://user-images.githubusercontent.com/37421564/224173644-deed8fea-6939-4b16-8bea-9ed7ff8c2489.png">

#### Possible fixes
It is caused by `background-color` on `Menu` class
<img width="316" alt="Screen Shot 2023-03-09 at 23 23 45" src="https://user-images.githubusercontent.com/37421564/224174028-c134716f-e44f-4024-8cbe-eefbac093b33.png">

**Comment by amyblais** [comment]
@sinansonmez What Mattermost server version are you on? What OS and version are you on?

**Comment by sinansonmez** [comment]
@amyblais I am seeing it on community server

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51309.
