### ISSUE TITLE
Calls dropping on Android, but functional on Desktop / iOS 

### ISSUE THREAD

**Issue by JackPala** [mattermost/mattermost-server#22486]
#### Summary
Mattermost calls, while fully functional on Desktop, and iOS, are not functional for Android users on both the stable Play Store and beta (f-droid) builds. 

#### Steps to reproduce
Attempt to enter a call on an Android Device. 

#### Expected behavior
A call

#### Observed behavior (that appears unintentional) 
The call on an Android device appears functional when the user is in a call by themselves, but when another user joins the call, the android app crashes and instantly closes. 

#### Possible fixes
Nothing has fixed it so far in our testing. It has been testing on Official Samsung devices, as well as GrapheneOS, LineageOS, and a number of other custom ROMs with both official and unofficial play services.

**Comment by amyblais** [comment]
Please re-open this issue with additional details at https://github.com/mattermost/mattermost-plugin-calls/issues. Thank you!
