### ISSUE TITLE
User can´t update their state

### ISSUE THREAD

**Issue by ghost** [mattermost/mattermost-server#22520]
Hi team,
This issue happend in some users.
- Clear status or change it from commands don´t works
- Manual updates not working
- I logged in incognito mode
- Cleared the cache
- Tried with different browsers
- All sessions closed not work
- It was updated directly in the database and it did not work

**Comment by amyblais** [comment]
Do you have details on your: 
- Mattermost server version
 - OS and version

Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or community members will likely be able to help troubleshoot this issue.
