### ISSUE TITLE
calls in test mode even if it's on OFF

### ISSUE THREAD

**Issue by cepelabs** [mattermost/mattermost-server#22529]
On self deployed Mattermost server we are not able to set calls not in test mode.
Flag is ok on OFF but calls still remain only for admin users. Not admin's user are able only to join an admin's created call.
Calls are working correctly.
Mattermost version: 7.8.1
Database schema version: 101
Any suggestion?

**Comment by Stromduster** [comment]
Interested in the solution (experience with Mattermost 7.10 and 0.15.1 for the Calls plugin).
