### ISSUE TITLE
Compact display... isn't

### ISSUE THREAD

**Issue by dmke** [mattermost/mattermost-server#22551]
#### Summary

Since the upgrade to Mattermost v7.9, compact message display takes much more space, contradicting its promise to "fit as many messages on the screen as we can."

Bug report in one concise sentence

#### Steps to reproduce

1. Go to "Settings" → "Display"
2. Set "Message Display" to "Compact"
3. Save

![image](https://user-images.githubusercontent.com/327411/225866337-1e952159-4d77-43eb-abc5-dfa3392ac30f.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/327411/225865728-20909dbd-6913-4cf4-aebf-837f9929a32a.png)

#### Observed behavior (that appears unintentional) 

![image](https://user-images.githubusercontent.com/327411/225866998-340f039b-270f-409c-9656-5556c10e4962.png)

#### Possible fixes

./.

#### Additional context

We're self-hosting via Docker Image, currently:

- Build Hash: `c4d8c1450ab2b9538bbc2690ca1ee865567a5888`
- EE Build Hash: `none`
- Webapp Build Hash: `12e0a9600fc4ea734462d65c9d909a49b6d3f9f6`
- Build Date: `Wed Mar 15 07:31:29 UTC 2023`

```
REPOSITORY                           TAG                          IMAGE ID       CREATED         SIZE
mattermost/mattermost-team-edition   7.9                          42155ca1d373   39 hours ago    727MB
```

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-51489.

**Comment by devicenull** [comment]
I just came to report this as well, this is a pretty annoying regression

**Comment by jb-leger** [comment]
I think this is the same issue, the compacity is not the only thing affected. It is more difficult to follow thread with the compact mode. See example with the same conversation (with myself), with the old behavior threads were clearly visible which is not the case with the new behavior.

Old behavior:
![Capture d’écran de 2023-03-17 14-37-47](https://user-images.githubusercontent.com/24868098/225922795-1a78405a-8c4f-4071-970e-f7a34540d76d.png)

New behavior:
![Capture d’écran de 2023-03-17 14-38-37](https://user-images.githubusercontent.com/24868098/225922868-7287ac68-6e8b-4dc3-8562-492a29ea2970.png)

**Comment by olalekanteeblaze** [comment]
Hi @amyblais I'll like to work on this

**Comment by dmke** [comment]
I can confirm that the update to 7.9.2 fixes this issue.

Thank you very much!
