### ISSUE TITLE
Mattermost v7.9.1 team-edition helm deployment issues

### ISSUE THREAD

**Issue by rjmedlin** [mattermost/mattermost-server#22565]
Env:
AWS EKS Cluster running **v1.23** Kubernetes
Using standard StorageClass gp2 provided by the EKS deployment

I am using the full values file for deployment:

**helm install mattermost-server mattermost/mattermost-team-edition -f mattermost-values.yaml  -n mattermost --set storageclass=gp2**

During deployment,  issues with permissions to create directories for plugins.

**Error Example**:
mattermost-team-edition {"timestamp":"2023-03-19 04:04:06.131 Z","level":"error","msg":"Failed to install prepackaged plugin","caller":"app/plugin.go:964","path":"/mattermost/prepackaged_plugins/mattermost-plugin-calls-v0.14.0-linux-amd64.tar.gz","error":"Failed to install extracted prepackaged plugin /mattermost/prepackaged_plugins/mattermost-plugin-calls-v0.14.0-linux-amd64.tar.gz: installExtractedPlugin: Unable to generate plugin webapp bundle., unable to copy webapp bundle directory: com.mattermost.calls: mkdir client/plugins/com.mattermost.calls: permission denied"}

mkdir client/plugins/com.mattermost.nps: permission denied"
mkdir client/plugins/playbooks: permission denied"
mkdir client/plugins/com.mattermost.calls: permission denied"
mkdir client/plugins/focalboard: permission denied"

After running exec into the pod, I am also unable to create the directories unless I change the permissions on the plugins directory to 777

There is also a nagging license error

I am prevented from installing gitlab plugin from the Console which is required for our testing.

Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by rjmedlin** [comment]
also found this error:
mattermost-server-mattermost-team-edition-76b9f98b65-zd9t4 mattermost-team-edition {"timestamp":"2023-03-19 15:56:12.417 Z","level":"error","msg":"Problem with file storage settings","caller":"app/server.go:884","error":"unable to write to the local filesystem storage: unable to open the file data/testfile to write the data: open data/testfile: permission denied"}

**Comment by amyblais** [comment]
Thank you, I see that you've opened a troubleshooting issue here https://forum.mattermost.com/t/mattermost-v7-9-1-team-edition-helm-deployment-issues/15434. We can track this there for now.

**Comment by michaelkoelle** [comment]
I found a workaround. Add this to you helm values:

```
extraInitContainers:
  - command:
      - sh
      - '-c'
      - chown -R 2000:2000 /client/plugins
    image: busybox
    name: changeowner
    volumeMounts:
      - mountPath: /client/plugins
        name: mattermost-plugins
```

This runs a init container which changes the owner of the plugins folder.
