### ISSUE TITLE
Suggestion dividers displaying "SUGGESTION.UNDEFINED"

### ISSUE THREAD

**Issue by avas27JTG** [mattermost/mattermost-server#22588]
#### Summary
Suggestion dividers displaying "SUGGESTION.UNDEFINED" for `/` or any emoji character name like `:+1` is typed in the post input box.
![image](https://user-images.githubusercontent.com/72438220/226916045-3438e678-0cba-4cbf-a779-564b11d2f7bc.png)

#### Steps to reproduce
Type `/` or any emoji character name like `:+1` is typed in the post input box.
Note: I was able to reproduce this on `v7.1.5`

#### Expected behavior
It should not appear.

**Comment by amyblais** [comment]
This has been fixed in v7.7.0 and the fix is included in v7.8.0 ESR.
