### ISSUE TITLE
Pressing pinned post causes every line to include today, yesterday etc.

### ISSUE THREAD

**Issue by miukumac** [mattermost/mattermost-server#22587]
#### Summary
When pinned posts is open, every single chat line includes "Today, yesterday" etc and overlaps chat.

#### Steps to reproduce
Click on pinned posts.

#### Expected behavior
Only relevant timestamps are displayed and only once. 

#### Observed behavior (that appears unintentional) 
Screenshot of the issue included.

We have confirmed the same behaviour on Firefox  and Chrome - both latest versions. Regression started after upgrading to the 7.9 series. 7.8 did not exhibit this behaviour. 

![broken1](https://user-images.githubusercontent.com/18749908/226866668-b103e422-26ae-4799-ab6e-8b65d018df5c.jpg)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51585.
