### ISSUE TITLE
Shared channels broken (no remote message nor participants) 7.9.1

### ISSUE THREAD

**Issue by haavardw** [mattermost/mattermost-server#22636]
#### Summary

After creating a secure connection and a shared channel, we can not see remote messages nor participants in the shared channel.
Both MM instances are 7.9.1.

#### Steps to reproduce
The secure connections were created with

instance A:
```
/secure-connection create --name test --displayname test --password <random_stuff>
```

instance B:
```
/secure-connection accept --name test --displayname test --password <random_stuff> --invite <blob from instance A>
```

A new channel was created on B and shared with
```
/share-channel invite --connectionID <connid>
```

#### Expected behavior
- See remote participants by clicking the channel members list.
- See remote messages 

#### Observed behavior (that appears unintentional) 
- No remote participants
- No remote messages

In the logs I see messages of this type
```
error [2023-03-22 08:39:05.575 Z] Failed to synchronize shared channel for remote cluster caller="sharedchannel/sync_send.go:270" channelId=pq########ca remote=dev error="failed to find shared channel remote with channelId=pq########ca, remoteId=6j#####5r: missing destination name description in *model.SharedChannelRemote"
```

Instance A:
![image (6)](https://user-images.githubusercontent.com/95774/227440780-550d00ff-0518-484c-8fb6-ddb3269bcbe0.png)

Instance B:
![image (7)](https://user-images.githubusercontent.com/95774/227440834-8a2f9ba4-5382-4d70-9232-17c851ff136e.png)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51705.

**Comment by wiggin77** [comment]
@haavardw it looks like a schema migration has failed somewhere in your previous upgrades.  There is a column in your `sharedchannelsremotes` table that hasn't existed in quite a while.  I am going to fix the code to ensure this column is ignored, but a quick fix for you would be to delete the `description` column in that table in both your databases.

**Comment by haavardw** [comment]
@wiggin77 
(this is postgres btw)
```
mattermost=> alter table sharedchannelremotes drop column description;
ALTER TABLE
mattermost=> \d sharedchannelremotes
                           Table "public.sharedchannelremotes"
      Column       |         Type          | Collation | Nullable |        Default
-------------------+-----------------------+-----------+----------+-----------------------
 id                | character varying(26) |           | not null |
 channelid         | character varying(26) |           | not null |
 creatorid         | character varying(26) |           |          |
 createat          | bigint                |           |          |
 updateat          | bigint                |           |          |
 isinviteaccepted  | boolean               |           |          |
 isinviteconfirmed | boolean               |           |          |
 remoteid          | character varying(26) |           |          |
 nextsyncat        | bigint                |           |          |
 lastpostupdateat  | bigint                |           |          | '0'::bigint
 lastpostid        | character varying(26) |           |          | ''::character varying
Indexes:
    "sharedchannelremotes_pkey" PRIMARY KEY, btree (id, channelid)
    "sharedchannelremotes_channelid_remoteid_key" UNIQUE CONSTRAINT, btree (channelid, remoteid)
```

Performed on both instances.

No change in channel behavior, but the logs are different:

```
{
    "caller": "sharedchannel/sync_send.go:270",
    "channelId": "t3xxxxxxxxxxxxxxxxxxxe",
    "error": "failed to find shared channel remote with channelId=t3xxxxxxxxxxxxxxxxxe, remoteId=e8xxxxxxxxxxxxxxr: missing destination name nextsyncat in *model.SharedChannelRemote",
    "level": "error",
    "msg": "Failed to synchronize shared channel for remote cluster",
    "remote": "test",
    "timestamp": "2023-03-25 09:40:56.282 Z"
}

```

**Comment by haavardw** [comment]
I also deleted the column `nextsyncat` after checking that it was not part of `server/channels/db/migrations/postgres/000037_create_sharedchannelremotes.up.sql`. I can now see messages on both sides, but I can still not see the remote participants in the channel member list.

**Comment by haavardw** [comment]
There's no more errors in the logs after deleting those two columns, but `/share-channel status` still shows nothing for `Last sync` (in addition to still no remote participants in the channel members list)

![image](https://user-images.githubusercontent.com/95774/227871288-095c92b3-af5e-4a9c-86af-b91f7412ed75.png)
