### ISSUE TITLE
btn-primary: SCSS leaves button white when not focussed.

### ISSUE THREAD

**Issue by particthistle** [mattermost/mattermost-server#22776]
#### Summary
Using Matterpoll bot for the first time tonight, I've discovered the webapp scss is applying white text on white background for btn-primary and so the button is not readable when focus is no longer on the button.

#### Steps to reproduce
Mattermost Version: cloud-2023-03-29-1

#### Expected behavior
Button should remain visible:
![image](https://user-images.githubusercontent.com/5515866/229284174-6926e107-517c-4665-96d8-04074a318c2a.png)

#### Observed behavior (that appears unintentional) 
Button is white text on white background:
![image](https://user-images.githubusercontent.com/5515866/229284300-d82c4b64-fb55-49b1-bda3-e25390d5aac8.png)

#### Possible fixes
Inspecting the CSS via web version:
`background: var(--center-channel-bg);`

The CSS variable assigned to background causes the issue. When I disable that style in the class while inspecting the code, I get the expected behaviour, instead of the observed behaviour.

![image](https://user-images.githubusercontent.com/5515866/229284385-dec3a1fd-4e51-42cd-b781-778214f8f0ab.png)

I'm not sure what else would be impacted by changing the SCSS here, otherwise would create a PR to resolve the problem and remove the line.
https://github.com/mattermost/mattermost-server/blob/4d2ed469bf707b5972dd8f63fe2ee9d0128a92e1/webapp/channels/src/sass/layout/_webhooks.scss#L379

**Comment by Safouene1** [comment]
Hey @amyblais , could these issues/bugs be picked up by the community?

**Comment by amyblais** [comment]
@Safouene1 Yes, let me know if you'd like me to assign this to you.

**Comment by hchorfispiria** [comment]
@amyblais Would you mind assigning this issue to me?
