### ISSUE TITLE
HTTP 500s on 

### ISSUE THREAD

**Issue by bigbenaugust** [mattermost/mattermost-server#22873]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Logs full of HTTP 500's after 7.1.3 -> 7.8.2 upgrade

#### Steps to reproduce
MySQL 8.0.32-24 Percona Server (GPL)
(it was upgraded from Percona MySQL 5.7 a couple of weeks ago)
Mattermost 7.1.3 ESR -> 7.8.2 ESR (this week)

#### Expected behavior
no HTTP 500s in log

#### Observed behavior (that appears unintentional) 
I'm not sure this appears in the UI at all. 

```
{"timestamp":"2023-04-06 16:33:32.407 Z","level":"error","msg":"Unable to get the teams unread messages.","caller":"web/context.go:117","path":"/api/v4/users/me/teams/unread","request_id":"cyy5ycap87nx8bt7dt79qfhtjr","ip_addr":"x.x.x.x","user_id":"dd9u91kb9ffz98xpizf9op38mh","method":"GET","err_where":"GetTeamsUnreadForUser","http_code":500,"error":"GetTeamsUnreadForUser: Unable to get the teams unread messages., failed to get total unread urgent mentions: Error 1267 (HY000): Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='"}

{"timestamp":"2023-04-06 16:38:44.597 Z","level":"error","msg":"Unable to get user threads","caller":"web/context.go:117","path":"/api/v4/users/dd9u91kb9ffz98xpizf9op38mh/teams/p89ryd5kttdsmm9wzes8px1bbe/threads","request_id":"tfyqgaq9cfda8ywo1guff975sh","ip_addr":"x.x.x.x","user_id":"dd9u91kb9ffz98xpizf9op38mh","method":"GET","err_where":"GetThreadsForUser","http_code":500,"error":"GetThreadsForUser: Unable to get user threads, failed to count urgent mentioned threads for user id=dd9u91kb9ffz98xpizf9op38mh: failed to count unread urgent mentions for user id=dd9u91kb9ffz98xpizf9op38mh: Error 1267 (HY000): Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='"}

{"timestamp":"2023-04-06 16:40:47.850 Z","level":"error","msg":"Unable to get user's Drafts.","caller":"web/context.go:117","path":"/api/v4/users/me/teams/frjnh34pwfdc3x1y9c9cgxp58w/drafts","request_id":"qw4xkgani3nh7fb7nnwas1u6by","ip_addr":"x.x.x.x","user_id":"13iomyr7c3bypqqu13dsqb3xxe","method":"GET","err_where":"GetDraftsForUser","http_code":500,"error":"GetDraftsForUser: Unable to get user's Drafts., failed to get user drafts: Error 1267 (HY000): Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='"}
```

#### Possible fixes
I took an outage and set all of the tables and the database to a collation of `utf8mb4_0900_ai_ci` and did a restart of Mattermost and the error persisted. So I did it again and set all tables and the database to a collation of `utf8mb4_general_ci`, and the error still persists. 

I did not see a failed database migration in the logs at Mattermost upgrade time.

**Comment by amyblais** [comment]
@bigbenaugust Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by jolu-dmt** [comment]
I have the same problem. Is there a solution yet?
Updated from 7.1.4 to 7.8.4

**Comment by bigbenaugust** [comment]
The solution for this is to take an outage and fix all collations and character sets at the:  

- database/schema level
- table level
- column level

(the SQL for each is in the MySQL docs or in StackExchange, this isn't my work box so I don't have them handy, sorry)
MySQL has all three levels for collation and character set and they need to agree (server-level character set/collation is not important here). In our case, since the majority of the database was on utf8mb4_general_ci from MySQL 5.7, that is what we standardized the database on. We found a few tables still in latin character sets and a few post-MySQL 5.8 upgrade, post-Mattermost 7.8 upgrade tables that were in utf8mb4_0900_ai_ci, but we made them all agree on utf8mb4_general_ci. 

Since we opted to change the minority of tables to match the majority, the changes took ~10 mins or so. Had we decided to change everything to the MySQL 8 default of utf8mb4_0900_ai_ci, the changes would have stretched into hours. Once verifiying that all character sets and collations agreed for columns, tables, and the mattermost schema itself, the mattermost app was started back up and the errors disappeared immediately. 

This is sadly a more of a MySQL issue with 8 having different defaults then 5.7 and us admins not knowing/noticing and allowing the Mattermost 7.8 upgrade to happily create new tables that disagreed with the old defaults.

**Comment by bigbenaugust** [comment]
One more thing before I close this (again, sorry I forgot to do so sooner): It does show up in the UI for some users as threading being broken, as some of the database queries involving threads/users can be affected. 

tl;dr: Not really a mattermost issue, it's a MySQL issue. Fix all database/table/column collations. Consult with your DBA as necessary. :D
