### ISSUE TITLE
Upgrade from 7.1.2 to 7.8.2 ESR fails

### ISSUE THREAD

**Issue by jelmd** [mattermost/mattermost-server#22874]
#### Summary
The upgrade from 7.1.2 to 7.8.2 ESR does not work. focalboard migration fails because of missing column and lot of attachments are missing. And other errors.

#### Steps to reproduce
Follow upgrade instructions of mm docs.

#### Expected behavior
There shouldn't be any errors in the logfile and mm should show _all_ files previously added by users.

#### Observed behavior (that appears unintentional) 
attachments are missing in the UI and other errors in the log
```
{"timestamp":"2023-04-06 16:23:46.590 Z","level":"info","msg":"Server is initializing...","caller":"platform/service.go:165","go_version":"go1.18.1"}
{"timestamp":"2023-04-06 16:23:46.591 Z","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:240","database":"master"}
{"timestamp":"2023-04-06 16:23:46.620 Z","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:240","database":"master"}
...
{"timestamp":"2023-04-06 16:23:54.284 Z","level":"error","msg":"Failed to update assets subpath from config","caller":"web/static.go:26","error":"failed to update root.html with subpath /: open /opt/mattermost/client/root.html: permission denied"}
...
{"timestamp":"2023-04-06 16:23:55.491 Z","level":"error","msg":"Failed to install prepackaged plugin","caller":"app/plugin.go:967","path":"/opt/mattermost/prepackaged_plugins/mattermost-plugin-calls-v0.13.0-linux-amd64.tar.gz","error":"Failed to install extracted prepackaged plugin /opt/mattermost/prepackaged_plugins/mattermost-plugin-calls-v0.13.0-linux-amd64.tar.gz: installExtractedPlugin: Unable to restart plugin on upgrade., failed to get public IP address: failed to get public address: write udp4 0.0.0.0:8443->52.72.139.62:3478: sendto: operation not permitted"}
...
{"timestamp":"2023-04-06 16:23:55.564 Z","level":"warn","msg":"plugin configured with a nil SecureConfig","caller":"plugin/hclog_adapter.go:72","plugin_id":"playbooks"}
{"timestamp":"2023-04-06 16:23:55.681 Z","level":"warn","msg":"plugin configured with a nil SecureConfig","caller":"plugin/hclog_adapter.go:72","plugin_id":"focalboard"}
{"timestamp":"2023-04-06 16:23:55.719 Z","level":"info","msg":"connectDatabase","caller":"app/plugin_api.go:973","plugin_id":"focalboard","dbType":"mysql"}
{"timestamp":"2023-04-06 16:23:55.736 Z","level":"info","msg":"{\"level\":\"info\",\"msg\":\"Pinging SQL\",\"fields\":{\"database\":\"master\"}}\n","caller":"io/io.go:428","plugin_id":"focalboard","source":"plugin_stderr"}
{"timestamp":"2023-04-06 16:23:55.768 Z","level":"error","msg":"Table creation / migration failed","caller":"app/plugin_api.go:976","plugin_id":"focalboard","error":"\"driver: mysql, message: failed to fetch applied migrations, command: select_applied_migrations, originalError: Error 1054 (42S22): Unknown column 'name' in 'field list', query: \n\nSELECT version, name FROM focalboard_schema_migrations\n\""}
{"timestamp":"2023-04-06 16:23:55.768 Z","level":"info","msg":"can't open new logfile: open focalboard_errors.log: permission denied\n","caller":"io/io.go:428","plugin_id":"focalboard","source":"plugin_stderr"}
{"timestamp":"2023-04-06 16:23:55.769 Z","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"focalboard","wrapped_extras":"path/data/mms/plugins/focalboard/server/dist/plugin-linux-amd64pid537"}
{"timestamp":"2023-04-06 16:23:55.776 Z","level":"error","msg":"Failed to install prepackaged plugin","caller":"app/plugin.go:967","path":"/opt/mattermost/prepackaged_plugins/focalboard-v7.8.2-linux-amd64.tar.gz","error":"Failed to install extracted prepackaged plugin /opt/mattermost/prepackaged_plugins/focalboard-v7.8.2-linux-amd64.tar.gz: installExtractedPlugin: Unable to restart plugin on upgrade., cannot activate plugin: error initializing the DB: driver: mysql, message: failed to fetch applied migrations, command: select_applied_migrations, originalError: Error 1054 (42S22): Unknown column 'name' in 'field list', query: \n\nSELECT version, name FROM focalboard_schema_migrations\n"}
{"timestamp":"2023-04-06 16:23:56.174 Z","level":"info","msg":"registered collection and topic type","caller":"app/collection.go:33","plugin_id":"playbooks","collection_type":"run","topic_type":"status"}
{"timestamp":"2023-04-06 16:23:56.174 Z","level":"info","msg":"registered collection and topic type","caller":"app/collection.go:33","plugin_id":"playbooks","collection_type":"run","topic_type":"task"}
...
```

BTW: Also wondering about "calling home"? Do we need to consider to drop mattermost because of GDPR violation?

**Comment by amyblais** [comment]
@jelmd  Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by jelmd** [comment]
No response yet.

Anyway, dropped the focal bloat and now I get
```
{"timestamp":"2023-04-06 20:46:11.887 Z","level":"error","msg":"HandleReminder failed to get playbook run","caller":"app/plugin_api.go:976","plugin_id":"playbooks","playbook_run_id":"7cwsq9tohpdturcrmwtc8en5co","error":"Error 1054: Unknown column 'StatusUpdateBroadcastChannelsEnabled' in 'field list'\nfailed to get playbook run by id '7cwsq9tohpdturcrmwtc8en5co'\ngithub.com/mattermost/mattermost-plugin-playbooks/server/sqlstore.(*playbookRunStore).GetPlaybookRun\n\tgithub.com/mattermost/mattermost-plugin-playbooks/server/sqlstore/playbook_run.go:731\ngithub.com/mattermost/mattermost-plugin-playbooks/server/app.(*PlaybookRunServiceImpl).GetPlaybookRun\n\tgithub.com/mattermost/mattermost-plugin-playbooks/server/app/playbook_run_service.go:1258\ngithub.com/mattermost/mattermost-plugin-playbooks/server/app.(*PlaybookRunServiceImpl).handleStatusUpdateReminder\n\tgithub.com/mattermost/mattermost-plugin-playbooks/server/app/reminder.go:64\ngithub.com/mattermost/mattermost-plugin-playbooks/server/app.(*PlaybookRunServiceImpl).HandleReminder\n\tgithub.com/mattermost/mattermost-plugin-playbooks/server/app/reminder.go:23\ngithub.com/mattermost/mattermost-plugin-api/cluster.(*JobOnce).executeJob\n\tgithub.com/mattermost/mattermost-plugin-api@v0.0.29/cluster/job_once.go:141\ngithub.com/mattermost/mattermost-plugin-api/cluster.(*JobOnce).run.func1\n\tgithub.com/mattermost/mattermost-plugin-api@v0.0.29/cluster/job_once.go:130\ngithub.com/mattermost/mattermost-plugin-api/cluster.(*JobOnce).run\n\tgithub.com/mattermost/mattermost-plugin-api@v0.0.29/cluster/job_once.go:133\nruntime.goexit\n\truntime/asm_amd64.s:1594","plugin_caller":"github.com/mattermost/mattermost-plugin-playbooks/server/app/reminder.go:66"}
```

So there is even more worse. I'll try to drop playbook stuff as well.

BTW: what does it say about a product, when not even an ESR release to next ESR release upgrade gets tested? What does it say, if a product is supported for 6 month, only and one needs 2 month to migrate to a new release? What does it say, if one needs to spend 1+ week (troubleshooting hours) to get an upgrade done? Obviously there isn't even time to fix simple things, which are in the issues queue for years. 

IMHO release management of mattermost is a real nightmare and disappointing (at least from an admin perspective). I probably should look for a reliable alternative to get our ~2.5K users happy and safe ...

**Comment by jelmd** [comment]
Removed *playground* and *calls* as well, so no migration errors appear in the log anymore, but still many files in UI are missing. So bugware.

**Comment by lieut-data** [comment]
Hi @jelmd, thanks for helping report this issue. It's always great to get direct community feedback when something slips by our testing!

Can you help me understand the two log lines below better?
```

...
{"timestamp":"2023-04-06 16:23:54.284 Z","level":"error","msg":"Failed to update assets subpath from config","caller":"web/static.go:26","error":"failed to update root.html with subpath /: open /opt/mattermost/client/root.html: permission denied"}
...
{"timestamp":"2023-04-06 16:23:55.491 Z","level":"error","msg":"Failed to install prepackaged plugin","caller":"app/plugin.go:967","path":"/opt/mattermost/prepackaged_plugins/mattermost-plugin-calls-v0.13.0-linux-amd64.tar.gz","error":"Failed to install extracted prepackaged plugin /opt/mattermost/prepackaged_plugins/mattermost-plugin-calls-v0.13.0-linux-amd64.tar.gz: installExtractedPlugin: Unable to restart plugin on upgrade., failed to get public IP address: failed to get public address: write udp4 0.0.0.0:8443->52.72.139.62:3478: sendto: operation not permitted"}
...
{"timestamp":"2023-04-06 16:23:55.768 Z","level":"info","msg":"can't open new logfile: open focalboard_errors.log: permission denied\n","caller":"io/io.go:428","plugin_id":"focalboard","source":"plugin_stderr"}
```

Can you share anything about the environment in which you deploy Mattermost that might prohibit the above operations? Note that, in the calls case, with the plugin enabled, this is just the WebRTC service establishing it's own public IP address for routing purposes when connecting clients. You can read more about this, and override to your own STUN server, at https://docs.mattermost.com/channels/make-calls.html#are-there-any-third-party-services-involved.

> but still many files in UI are missing.

I'm not sure to what this refers. Are you missing file attachments in posts? Are there any other errors 

The Playbooks issue also sounds outstanding: I'm sorry about that. Do you recall if Playbooks was in use prior to your upgrade? Are there any earlier error logs when upgrading Playbooks?

**Comment by jelmd** [comment]
> Hi @jelmd, thanks for helping report this issue. It's always great to get direct community feedback when something slips by our testing!

FWIW: I noticed, that a new release is out (7.1.3) and tried this one. Worked much better. Some users said, they lost their focalboards (even so there was no migration error message) but recovered from it by getting the missing stuff from the old instance.

> Can you help me understand the log lines below better?
> 
> ```
> ...
> {"timestamp":"2023-04-06 16:23:54.284 Z","level":"error","msg":"Failed to update assets subpath from config","caller":"web/static.go:26","error":"failed to update root.html with subpath /: open /opt/mattermost/client/root.html: permission denied"}
> ...
> {"timestamp":"2023-04-06 16:23:55.491 Z","level":"error","msg":"Failed to install prepackaged plugin","caller":"app/plugin.go:967","path":"/opt/mattermost/prepackaged_plugins/mattermost-plugin-calls-v0.13.0-linux-amd64.tar.gz","error":"Failed to install extracted prepackaged plugin /opt/mattermost/prepackaged_plugins/mattermost-plugin-calls-v0.13.0-linux-amd64.tar.gz: installExtractedPlugin: Unable to restart plugin on upgrade., failed to get public IP address: failed to get public address: write udp4 0.0.0.0:8443->52.72.139.62:3478: sendto: operation not permitted"}
> ...
> {"timestamp":"2023-04-06 16:23:55.768 Z","level":"info","msg":"can't open new logfile: open focalboard_errors.log: permission denied\n","caller":"io/io.go:428","plugin_id":"focalboard","source":"plugin_stderr"}
> ```
> Can you share anything about the environment in which you deploy Mattermost that might prohibit the above operations?

Sure: Policy is, that a software is not allowed to change its install base. Therefore mattermost runs as an unprivileged user (webservd), which has no permission to modify anything in /opt/mattermost. However, it has its own writable directory (e.g. /var/lib/mattermost), where it puts all generated stuff, like expanded plugins, attachments, etc.. For focalboard in pre 7.x I had to create a link to the datadir/plugins because it did not obey the PluginSettings:Directory .

> Note that, in the calls case, with the plugin enabled, this is just the WebRTC service establishing it's own public IP address for routing purposes when connecting clients. You can read more about this, and override to your own STUN server, at https://docs.mattermost.com/channels/make-calls.html#are-there-any-third-party-services-involved.

Hmmm, it should be customizable. a) We have our own STUN/TURN servers. b) it would not work because all related ports are closed by firewall. c) the instance isn't hidden behind NAT etc.
 
> > but still many files in UI are missing.
> 
> I'm not sure to what this refers. Are you missing file attachments in posts? Are there any other errors

Yes and no. It looked like it was not loading the attachment, just reserved the UI space for it. All this in an unpredictable manner, i.e. some could be seen, some not.

> The Playbooks issue also sounds outstanding: I'm sorry about that. Do you recall if Playbooks was in use prior to your upgrade? Are there any earlier error logs when upgrading Playbooks?

Haven't seen this with 7.1.3.

**Comment by lieut-data** [comment]
Thanks for the detailed response, @jelmd, and the good news that v7.8.3 has dramatically improved things. I admit I'm uncertain /why/, since v7.8.3 contained primarily security fixes that shouldn't have improved any of the issues you described.

Just to clarify on the Calls discussion:

> Hmmm, it should be customizable. a) We have our own STUN/TURN servers. b) it would not work because all related ports are closed by firewall. c) the instance isn't hidden behind NAT etc.

Yes, fully agree. By default, the plugin ships with settings that work "out of the box" for many installations, but requires customization in cases like yours. If you're interested in making this work, feel free to configure the plugin to point at your own STUN Server as described on https://docs.mattermost.com/channels/make-calls.html#are-there-any-third-party-services-involved.

Are there any outstanding issues I can help triage? I don't want to close out this ticket if I missed something that remains unresolved.

**Comment by jelmd** [comment]
OK. Thanx for the link. Right now calls plugin is disabled (will try it when I've time to).
Outstanding issues: not really. As said, the handful of user using focalboard can pull their old stuff from the old instance, so save some time and close it :).

**Comment by lieut-data** [comment]
Awesome, thanks again for working towards a solution. Let us know if we can help further :)
