### ISSUE TITLE
ERROR: for haproxy  Container ... is unhealthy.

### ISSUE THREAD

**Issue by thetagML** [mattermost/mattermost-server#22904]
Hi!

I'm trying to make a fresh new install of MM dev server and I'm facing permanently this issue:

Previously, I tried it with MM version 7.9 about 3 weeks ago and I had no such issue. 
Then I was facing this recent, new, monorepo approach that changed several things.
(I want to customize the webapp, not the server or any other main component. E. g. I want to add more shortcut keys to standard message actions and do some minor but necessary changes in the webapp. Other customizations are and will be add as an addon.)

I trying to install it into a VirtualBox VM with Ubuntu 20.04 and Xfce Desktop. Basic install. Nothing special setting. Network address is a Bridged adapter.

This is the screenshot:
![image](https://user-images.githubusercontent.com/128502274/230946613-1fe7f0b2-eab9-4ac8-8de0-72f2df7323d7.png)

Shall I tweak the Nginx settings (it is the haproxy)?
Because it is different than my working MM test VM's nginx conf. (Of course, because the backend is different in the MM dev version.)

It is not urgent to repair.

Btw, the install guide misses some steps of installing and using Docker to start the development process. (What can be found on the Docker site installing Docker misses certain steps line adding the docker user to the right user group.)

George
(UI. I'm using my friend's Github account who is interested in these customizations.)

**Comment by amyblais** [comment]
@thetagML Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by thetagML** [comment]
Sure. Thx! I did it and I closed this ticket here.
