### ISSUE TITLE
Webapp does not correctly display file upload error message

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-server#22967]
#### Summary

Currently when a file upload error occurs, the web application provides no feedback and appears to continue processing the file. The behavior currently works correctly for errors related to connection issues, but not for application-related errors generated by the server. There was [a change](https://github.com/mattermost/mattermost-webapp/pull/10169/files#diff-5c91b3e39bf372849225693764d8aeb6d70a9aa0e1a356e72c0dee876e289494) that broke this for the application-specific errors.

The task here is to have upload errors returned from the server, use the same error-handling logic as the connection issue errors.

#### Ticket Link

This issue was originally filed in the Antivirus plugin repo:
https://github.com/mattermost/mattermost-plugin-antivirus/issues/36

**Comment by MattSilvaa** [comment]
I can take this on
