### ISSUE TITLE
insights cannot be disabled, env flag does nothing

### ISSUE THREAD

**Issue by elandorr** [mattermost/mattermost-server#22994]
v7.10

Due to the performance decrease I want to disable this entirely unnecessary feature.

I set `MM_FEATUREFLAGS_INSIGHTSENABLED=false` in the `.env` where you would include other flags, but 'insights' still show up.

Also, please reconsider force-enabling playbooks etc. on next release. Why would we want to waste money running something we don't need? We use mattermost for its original purpose i.e. a more privacy friendly slack replacement.

**Comment by elandorr** [comment]
@amyblais Yes, full recreation. It doesn't show up in the console either:
![image](https://user-images.githubusercontent.com/56206745/232853829-cd6913b6-4997-443a-b808-6aadb94a24a5.png)

**Comment by amyblais** [comment]
You can add the following line under ``[Service]`` in your ``systemd`` service file for Mattermost: ``Environment="MM_FEATUREFLAGS_INSIGHTSENABLED=false"``. Can you help double-check if this helps?

**Comment by elandorr** [comment]
Running via docker

**Comment by amyblais** [comment]
Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or community members may have encountered this issue before and may be able to help troubleshoot this.

**Comment by elandorr** [comment]
I'd rather not create yet another account, sorry. This is a default setup with all experimental stuff disabled, so I couldn't say much about it anyway.

My only idea was that the string in the changelog is wrong, but it seems to be correct.

**Comment by amyblais** [comment]
Glad to hear it was fixed!

**Comment by elandorr** [comment]
@amyblais 

> Will it wipe the excess metadata it might have collected from the db on its own?

Would you let me in on that, please?

**Comment by amyblais** [comment]
> > Will it wipe the excess metadata it might have collected from the db on its own?

@BenCookie95 @sbishel Would you know the answer to this?

**Comment by elandorr** [comment]
Thanks, Ben! Interesting there is any slowdown at all, then, if it's just another ordinary query.

**Comment by BenCookie95** [comment]
> Thanks, Ben! Interesting there is any slowdown at all, then, if it's just another ordinary query.

Some of the queries are definitely quite heavy but they only run when you access the insights page directly. So unless you have a bunch of people constantly querying the insights page, turning it off might not make much of a difference

**Comment by amyblais** [comment]
I've shared this feedback with our team. They weren't sure what you meant by "...as MM inc. staunchly rejects GDPR for non-enterprise." Can you help share more details on this?

**Comment by elandorr** [comment]
Can't believe we're doing that again, but I'll humor you. You full well know what it means, that topic has been brought up on your various forums and platforms for years.

But, if you forgot: I've asked about privacy/storage cleanup years ago. You acted as if you didn't understand basic tech to avoid having to give an honest answer. I explained over and over, this went on for a while. I was confused, as there was nothing that could be misunderstood. Then I realized you simply do not want, because you obviously have been ordered to shut this up, and I stopped bothering.

Many others tried before, it was silly of me to even bother. It's probably silly of me to reply right now, too, but I am a sucker for replies.

I still don't believe that's a good strategy - there are other tools out there, and someone who couldn't pay for enterprise before, wouldn't magically do so just because you hide a bare essential feature behind a paywall. He'll just move on begrudgingly or do what I did. Or 'crack' his way into EE, know a guy who went that route, but that's not an option for us. That's also not that helpful, as you have to keep up with that, too, then.

But you're likely an employee, so I understand you're just 'doing your job' and don't have a say in it.

This guy went through it all a long time ago: https://github.com/someone-somenet-org/mattermost-privileged
https://mattermost.uservoice.com/forums/306457/suggestions/15357861
https://mattermost.uservoice.com/forums/306457-general/suggestions/13851123-automatically-delete-the-oldest-attachments-when-a

> [someone ](https://mattermost.uservoice.com/users/200320383-someone)shared this idea  ·  **Jul 24, 2016**

Even 2015: https://mattermost.uservoice.com/forums/306457-general/suggestions/10007076-add-a-way-to-prune-reset-clear-channels?page=2&per_page=20


Plus like a dozen posts at least in other forums I don't have a link handy for.

The only way to use MM if you:

- do not have a magic millionaire storage black hole that lets you upload files ad infinitum
- need to actually delete messages, really delete, not just flag

is to write your own tool.

I've used 'someone''s  (best nickname ever) code as basis. But that's obviously not very reasonable. It took a long time and a lot of work since you can't just blindly copy paste. I verified every single query as best I could. But we've already set MM up and didn't want to start with something else from scratch. MM itself is also quite usable. It's far less res intense than the major competitor rocketchat last time we tried. Still bloated and not like IRC, but a good option. Corporate decisions be damned, I set out to write a tool, and did. 

That's what led me to ask for avoiding breakage, as it works pretty well right now. Not updating is not an option due to security updates, so best I can do is ask nicely not to break this. This situation is not something you research every week, so you have to start looking into it from (almost) scratch again, which eats unreasonable amounts of time. The 'someone' dude has enough free time, he works at a uni. Everyone else just moves on, normally. Not just because of the work, also for stability. As an admin, I cannot take maintenance responsibility for 3rd party code. I don't pretend to understand half a dozen large codebases, or even less be able to reliably and timely react to changes.

Real deletion should simply exist everywhere, and is even a GDPR requirement. Cleaning up storage is a must too - or how do you expect servers to exist? Maybe in your world having terabytes to throw around is normal, or you reinstall every couple months. Everywhere else, one has to have real deletion, expiration, retention settings, whatever you want to call it.

I think I even asked you before how we could potentially export/import all settings/users/chans/everything except messages to seriously automate a full reinstall to cleanly circumvent the problem. That's still stupid, 'hey, dear users, today I'll have to kill everything once more', but cleaner than manually messing with the db.

But who am I telling, of course you're aware of this. for 7 years now you've been pushing this strategy, after all.

I flat out asked you long ago, if you couldn't just ask the guy responsible for the db to informally acknowledge which parts of it can be touched safely standalone, or to maybe post a small script. It's absolutely trivial, if you know the codebase. It's just a hassle to outsiders. But... you know. You try to sell it in the enterprise, after all.

Someone else searching up all the posts regarding this issue must be laughing his butt off. From 2016 to 2023 a clown show. This 'freemium' corporate profiteering is a cancer to the open source community and if it were up to me, we'd simply use IRC and a phpbb again. Uses almost no resources, has legit deletion, zero telemetry issues, no privacy nightmares, etc.

But it has no emojis, duh. Must-have in 2023. /s (Not so sure even. Aren't they in unicode? Whatever.)

Cheers anyway, I guess it's just your job.

**Comment by olodar** [comment]
> v7.10
> 
> Due to the performance decrease

Do you mean performance decreased after upgrade to 7.10? We have noticed after upgrade to 7.10 performance of client (webapp?) become extremely poor. Messages opens very slow and sometimes client can simply stuck with 100% core load. 
This problem is known?

**Comment by elandorr** [comment]
@olodar I'm sorry, I didn't particularly take note. If you have a lot of content, building a clean-up tool based on the [repo linked](https://github.com/someone-somenet-org/mattermost-privileged) may be of benefit in general.

That'd be unrelated to this issue post though; you may want to create a new one.

To turn off the 'insights', add the var to the compose file either directly set to false, or blank there and set in the .env. But that shouldn't be related based on the response above.

I'll close this one as the original issue has been solved, and the ensued discussion regarding clean-up won't be solved anyway, as it has been rejected for 7 years.
