### ISSUE TITLE
Duplicate Message Issue on Production

### ISSUE THREAD

**Issue by manzoor77** [mattermost/mattermost-server#23012]
Hi,
Facing Duplicate post issue when remind bot triggered in Production.  remindbot plugin version is  **com.github.scottleedavis.mattermost-plugin-1.0.0** , Mattermost version >7.2.

**Comment by amyblais** [comment]
@manzoor77 Would you be open to re-creating this issue at https://github.com/scottleedavis/mattermost-plugin-remind/issues?

**Comment by manzoor77** [comment]
Sure

**Comment by amyblais** [comment]
Thank you!
