### ISSUE TITLE
Invalid or expired session, please login again

### ISSUE THREAD

**Issue by luozhouyang** [mattermost/mattermost-server#23137]
#### Summary
Different responses with the same request

#### Steps to reproduce
deploy mattermost followed by the offical document, including mattermost-operator and mattermost.

mattermost version: 7.10.0

login user and get the auth token.

request first time:
```bash
curl -i -X GET http://mattermost.mattermost:8065/api/v4/users/username/jhdhdgd*** -H 'Authorization: Bearer gcqfg1*****p75ruqr'
HTTP/1.1 401 Unauthorized
Content-Type: application/json
Expires: 0
Permissions-Policy:
Referrer-Policy: no-referrer
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Request-Id: g1ezfufz178xdecbjj6snifpey
X-Version-Id: 7.10.0.7.10.0.f8597a60e47b5f997418b7c4b32136f5.false
Date: Wed, 26 Apr 2023 05:56:34 GMT
Content-Length: 186

{"id":"api.context.session_expired.app_error","message":"Invalid or expired session, please login again.","detailed_error":"","request_id":"g1ezfufz178xdecbjj6snifpey","status_code":401}
```

request at the second time:
```bash
curl -i -X GET http://mattermost.mattermost:8065/api/v4/users/username/jhdhdgd*** -H 'Authorization: Bearer gcqfg1*****p75ruqr'
HTTP/1.1 200 OK
Content-Type: application/json
Etag: 7.10.0.dqz14dtrrinqprgmuhxpjfx3pr.1682482268386..0.true.true.0
Expires: 0
Permissions-Policy:
Referrer-Policy: no-referrer
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Request-Id: 65qhif8313rpmxgo6fnps5pfaw
X-Version-Id: 7.10.0.7.10.0.c8341e89f54ed64a02d81b4e1edcae3e.false
Date: Wed, 26 Apr 2023 05:56:35 GMT
Content-Length: 437

{"id":"dqz14dtrrinqprgmuhxpjfx3pr","create_at":1682476428162,"update_at":1682482268386,"delete_at":0,"username":"jidofop295-at-ippals-com","auth_data":"","auth_service":"","email":"jidofo****","nickname":"jidofop*****","first_name":"","last_name":"","position":"","roles":"system_user","locale":"en","timezone":{"automaticTimezone":"","manualTimezone":"","useAutomaticTimezone":"true"},"disable_welcome_email":false}
```

#### Expected behavior

The two requests should be same.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Do any of these troubleshooting threads help:
 - https://forum.mattermost.com/t/solved-invalid-or-expired-session-please-login-again/6772/2
 - https://forum.mattermost.com/t/invalid-or-expired-session-please-login-again-only-on-desktop-app/10326
 - https://stackoverflow.com/questions/54907385/mattermost-invalid-or-expired-session-please-login-again

Optionally, would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or community members may have encountered this issue before and may be able to help troubleshoot this.

**Comment by luozhouyang** [comment]
Fixed. 
The versions of the two servers are different!
* Pod A: X-Version-Id: 7.10.0.7.10.0.f8597a60e47b5f997418b7c4b32136f5.false
* Pod B: 7.10.0.7.10.0.c8341e89f54ed64a02d81b4e1edcae3e.false

Deploy mattermost docker images with a hash rather than a version tag fixed this problem.
