### ISSUE TITLE
old chats in the private channels does not loads

### ISSUE THREAD

**Issue by shrepy** [mattermost/mattermost-server#23175]
#### Summary
old chats in the private channels does not loads

#### Steps to reproduce
On private channels when you go for the old chats which are usually 2 days older, you'll get to know the issue (
Mattermost Version: 5.13.0
Database Schema Version: 5.13.0
Database: postgres

#### Expected behavior
While loading old chats in the private groups the chats should load successfully.

#### Observed behavior (that appears unintentional) 
While loading old chats (usually chats older than 2 days) in the private groups the loader starts loading but it does not loads the older chats instead it shows "load more messages" and when we click on this it does not loads older messages.
![Screenshot from 2023-04-27 12-33-04](https://user-images.githubusercontent.com/112175004/234785630-72c90d63-f509-49fc-90e5-92b0b9a1f960.png)
![Screenshot from 2023-04-27 12-32-56](https://user-images.githubusercontent.com/112175004/234785641-dd5c4706-1ede-4435-b58e-8bbb25fc7664.png)
![Screenshot from 2023-04-27 12-31-40](https://user-images.githubusercontent.com/112175004/234785646-833feb28-2188-4924-8d57-84f605081447.png)

**Comment by amyblais** [comment]
@shrepy v5.13.0 is an unsupported version. Would you be open to upgrading to v7.8 or a later version?
