### ISSUE TITLE
Issue for partial search of a string

### ISSUE THREAD

**Issue by skotlex** [mattermost/mattermost-server#23281]
#### Summary
Hi, I'm installing mattermost on a physically isolated closed network and conducting a pilot test. Meanwhile, there was a problem that the search function didn't work as I thought. For example, partial search is not possible.
(ex. The result is not exposed when searching for `st` or 'te' in the `test` strings)

In other words, the search is displayed only when you enter a complete full string, and when you search for only a partial string, the search is not performed regardless of the language. 

Mattermost is using 7.10.0 and I installed and linked postgreSQL version 15.

#### Observed behavior (that appears unintentional) 
![20230504_111718](https://user-images.githubusercontent.com/31692408/236097352-2f56280a-7702-4764-8a44-9e5632cfa58f.jpg)

![20230504_111707](https://user-images.githubusercontent.com/31692408/236097360-9a904382-03e1-4cbe-9722-bd2aa546dcca.jpg)

#### Possible fixes
I wish I could search for a part of the string. Or let me know if I set something up wrong

**Comment by amyblais** [comment]
@skotlex This documentation page describes some limitations in search: https://docs.mattermost.com/channels/search-for-messages.html#notes-about-all-searches. Does the issue you're seeing align with any of the limitations mentioned here?

**Comment by skotlex** [comment]
> @skotlex This documentation page describes some limitations in search: https://docs.mattermost.com/channels/search-for-messages.html#notes-about-all-searches. Does the issue you're seeing align with any of the limitations mentioned here?

@amyblais 
I've already read the document you suggested. However, when I saw the document and saw the information about Korean on the following website (https://docs.mattermost.com/configure/enabling-chinese-japanese-korean-search.html), I decided that there was no problem because the document said that there was no need to set up additional settings for postgreSQL.

Also, the case of the screenshot I uploaded is a partial search for English, which does not appear to be included in the restrictions listed below.
```
PostgreSQL:
- URLs don’t return results.
- Hashtags or recent mentions of usernames containing a dash don’t return results.
- Terms containing a dash return incorrect results since dashes are ignored in the search engine.
- From Mattermost v7.1, search results respect the value instead of being hardcoded to English. We recommend that Mattermost system admins review this value to ensure it’s set correctly. default_text_search_config
```
I couldn't quite understand the contents of 'default_text_search_config' written at the end, but it's definitely not included for the rest.

I don't know English very well, so please explain if I understand anything wrong.

Thank you

**Comment by skotlex** [comment]
@amyblais I checked that the result is printed when searching for `matter*` in the text `mattermost`. However, if I search `*most`, it will not be searched. Is this something special about postgreSQL?

**Comment by amyblais** [comment]
Meant to ping @harshilsharma63 in my previous post - is the issue described here a known issue?

**Comment by harshilsharma63** [comment]
@amyblais this is a known thing.

@skotlex when using database (either MySQL or PostgreSQL) as search backend, you cannot search for partial strings or suffixes. For example, if there was a post with text 'mattermost`, you could search it by the term `matter*` or `the full word `mattermost`, but not my a substring like `tterm` or a suffix like `*ermost`. That's because of the way MySQL and Postgres full text search work, it very inefficient to search for substring or suffix unless there are small number of posts.

**Comment by harshilsharma63** [comment]
I Elasticsearch an option for you? (available only in Enterprise edition).
