### ISSUE TITLE
unintentional re-numbering in numeric list 

### ISSUE THREAD

**Issue by sKopheK** [mattermost/mattermost-server#23364]
#### Summary
Mattermost Channels - message auto-formatting screws intended order

#### Steps to reproduce
post new message with following content
```
1. ok
2. uplne bez problemu, napr. https://www.npmjs.com/package/sanitize-html
4. je na to uz ukol, nebo je toto prvni XD, kde se to menilo?
5. posunu, aby to bylo stejne v kategoriich, na jinych strankach (detailech) se to bude muset udelat zvlast
```

![imagen](https://github.com/mattermost/mattermost-server/assets/5802917/03e705a7-7fdb-4f9b-9524-f57f95ac1db6)

#### Expected behavior
the following numbers are printed out:
1.
2.
4.
5.

#### Observed behavior (that appears unintentional) 
this is printed out instead:
1.
2.
3.
4.

![imagen](https://github.com/mattermost/mattermost-server/assets/5802917/931da6c4-77b5-4c35-96ae-e2a260cbe908)

#### Possible fixes
check if the numbered list is really in un-interupted sequence, otherwise don't auto-number list items

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-52481.

**Comment by hchorfispiria** [comment]
@amyblais Would you mind assigning this issue to me?
