### ISSUE TITLE
mm on pi4(arm64) on docker?

### ISSUE THREAD

**Issue by dolphin-cat** [mattermost/mattermost-server#23462]
#23387 
> how do i compile a mattermost-server docker image for linux/arm64

> this previous issue may help answer the question: https://github.com/mattermost/mattermost-server/issues/21979.

> i see no clear instructions there, all i see is some outdated code and some non outdated code and a "use them together" without any explanation how to do so.

why was my issue closed when it wasn't resolved?

**Comment by amyblais** [comment]
I'll re-open the previous issue.
