### ISSUE TITLE
Migrate "components/markdown_image/index.js" to Typescript

### ISSUE THREAD

**Issue by saideepesh000** [mattermost/mattermost-server#23523]
#### Summary
Migrate "components/markdown_image/index.js" to Typescript

I want to familiarise myself with the codebase by migrating small files to ts, hence created this issue

**Comment by saideepesh000** [comment]
Picking this up

**Comment by drraghavendra** [comment]
import React from 'react';

interface MarkdownImageProps {
  src: string;
  alt: string;
}

const MarkdownImage: React.FC<MarkdownImageProps> = ({ src, alt }) => {
  return <img src={src} alt={alt} />;
};

export default MarkdownImage;


Added the TypeScript type annotations to the component props using the interface keyword. The MarkdownImageProps interface specifies the expected properties of the component, src and alt, both of type string.

Added type information to the component itself by using the React.FC (FunctionComponent) type. The MarkdownImage component now explicitly receives the MarkdownImageProps as its props. Inside the component, we're using the src and alt props to render an img element.

Finally, we export the MarkdownImage component as the default export of the module.

Remember to configure your build environment to support TypeScript, including the necessary TypeScript compiler and configuration files.

**Comment by M-ZubairAhmed** [comment]
this issue already exists as part of https://github.com/mattermost/mattermost-server/issues/21062
