### ISSUE TITLE
Mattermost Call

### ISSUE THREAD

**Issue by alifiroozi80** [mattermost/mattermost-server#23548]
Hello everyone,
I’ve successfully installed the Mattermost server on a bare-metal server ([omnibus](https://docs.mattermost.com/install/installing-mattermost-omnibus.html)), and it’s already installed the Call Plugin.

I opened all the necessary call ports, but after trying to establish a call, it failed.
Here is my JS Console Log:

[Picture](https://global.discourse-cdn.com/business7/uploads/mattermost/original/2X/c/c7c3c27b98b47bdc312caf73b42481d500824b26.jpeg

I also tried with Chrome and the same thing happend.

**Comment by amyblais** [comment]
Hi @alifiroozi80, would you be open to re-opening this issue at https://github.com/mattermost/mattermost-plugin-calls/issues? Thanks!

**Comment by amyblais** [comment]
When you re-open the issue, please also add details on your Mattermost server version as well as your OS version.

Let me know here once you've re-opened the issue at https://github.com/mattermost/mattermost-plugin-calls/issues.

**Comment by alifiroozi80** [comment]
Hello @amyblais,
I opened an [Issue](https://github.com/mattermost/mattermost-plugin-calls/issues/440) on the Mattermost Call Plugin page.
Also, I opened this issue on the Mattermost forum, but after waiting to answer that for about a week, I moved it here.
