### ISSUE TITLE
Czech (cs) translation and review

### ISSUE THREAD

**Issue by jkuchar** [mattermost/mattermost-server#2420]
Is there anyone who is going to help me with that?

**Comment by turcapat** [comment]
Hi, I would like to help you. Which files exactly needs to be translated ?

**Comment by enahum** [comment]
Please feel free to speak Czech, [you can see other threads speaking non-English as well](https://github.com/mattermost/platform/issues/2221)

[Translation guide here](http://docs.mattermost.com/developer/localization.html). Please also [join the localization channel](https://pre-release.mattermost.com/core/channels/localization), as there are new tools being developed to make translation easier.

**Comment by jkuchar** [comment]
Tak tedy, budeme tykat nebo vykat?

**Comment by svarnypetr** [comment]
Pracuje se na lokalizaci?

**Comment by jkuchar** [comment]
Ještě nikdo nezačal, pokud vím.

**Comment by jasonblais** [comment]
If anyone would like to contribute and help make Mattermost a Czech experience, please join the [Mattermost Translation Server](http://translate.mattermost.com/cs/mattermost/) to get involved, and our [Localization community channel](https://pre-release.mattermost.com/core/channels/localization) to meet other contributors.

**Comment by Laupe** [comment]
Ahoj, tak co budeme to překládat? Já jsem dneska začal kdo se přidá a kolik nás už je?

Diskuze můžeme zde https://pre-release.mattermost.com/core/channels/i18n-czech

**Comment by hanzei** [comment]
Closing this one as it's not the right place to look out for new translation contributors.
