### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by tlebeitsuk** [mattermost/mattermost-server#2767]
Anyone interested in working on a swedish translation?

**Comment by mackelito** [comment]
Sure.. I can help out! :)

**Comment by jasonblais** [comment]
Please feel free to speak Swedish if you'd like, [you can see other threads speaking non-English as well](https://github.com/mattermost/platform/issues/2221)

You can find our [translation guide here](http://docs.mattermost.com/developer/localization.html) and I encourage you to [join the localization channel](https://pre-release.mattermost.com/core/channels/localization) if you already haven't, as there are new tools being developed to make translation easier.

**Comment by fredrikcarno** [comment]
I want help too :) joining localization channel asap

**Comment by jasonblais** [comment]
Hi @fredrikcarno,

1. We have a discussion channel for [Swedish translation](https://pre-release.mattermost.com/core/channels/i18n-swedish), would welcome you to join and bring in any other members who might be interested from the community
2. We have created an instance for Swedish in our [Mattermost Translation server](http://translate.mattermost.com/sv/mattermost/)

Please let me know if there are any questions - as a Scandinavian myself, I would really love to see Swedish added as a supported language for Mattermost.

**Comment by psyc0** [comment]
i can probably help aswell

**Comment by jasonblais** [comment]
That would be great @psyc0, much appreciated!

You can join the [Mattermost Translation Server](http://translate.mattermost.com/sv/mattermost/) to get involved, and our [Localization community channel](https://pre-release.mattermost.com/core/channels/localization) to meet other contributors.

Hope to see you there!

**Comment by hanzei** [comment]
Closing this one as it's not the right place to look out for new translation contributors.
