### ISSUE TITLE
Hindi translation

### ISSUE THREAD

**Issue by tejasbubane** [mattermost/mattermost-server#3841]
Anyone interested in translating mattermost to `Hindi`?

**Comment by jasonblais** [comment]
We'd love to see Hindi translations in Mattermost!

You can find our [translation guide here](http://docs.mattermost.com/developer/localization.html) and I encourage you to [join the localization channel](https://pre-release.mattermost.com/core/channels/localization) if you already haven't, as there are new tools being developed to make translations easier.

We have also added Hindi in our [Mattermost Translation Server](http://translate.mattermost.com/hi/mattermost/), which is where translations are updated and tracked. You can also find [top contributors of the month in our welcome page](http://translate.mattermost.com/).

Please let us know if there are any questions! Hope to see you and other potential contributors for Hindi around,

**Comment by jasonblais** [comment]
If anyone else would like to contribute, please join the [Mattermost Translation Server](http://translate.mattermost.com/hi/mattermost/) to get involved, and our [Localization community channel](https://pre-release.mattermost.com/core/channels/localization) to meet other contributors.

**Comment by gupsho** [comment]
Hi, I can try helping out on this.

**Comment by hanzei** [comment]
Closing this one as it's not the right place to look out for new translation contributors.
