### ISSUE TITLE
[Help Wanted] Matterbot

### ISSUE THREAD

**Issue by yangchen1** [mattermost/mattermost-server#4333]
We're looking for anyone interested in helping contribute this improvement.
If you're interested please comment here and come join our "Contributors" community channel on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

Whenever a visible setting of the channel is changed (by a team or system admin), an automated System Message should appear in the channel. The message states what setting was changed, the previous state, and the new state. The message is visible to everyone in the channel.

A system message are sent out when the following are changed:
Channel Name
Channel URL
Channel Header (Already implemented, but needs to include quotation marks)
Channel Purpose [existing ticket link](https://mattermost.atlassian.net/browse/PLT-2978)

![image](https://cloud.githubusercontent.com/assets/5504605/19707182/27f6ba88-9ae4-11e6-8d4c-99e0fb4d8663.png)

The format of the message should be:
[username of user who changed the setting] updated the [setting name] from: “[previous setting]” to: “[new setting]”

In all system messages, the message reply button and context menus [...] should not be available upon hover.

"Private" system messages, in the form of a direct message from “Matterbot”, should also be sent in the following cases:

1. When a user is removed from a channel
Format: You have been removed from the private group/public channel GROUP_NAME by @username
2. A channel a user was part of is deleted (archived)
Format: @username archived the private group/public channel CHANNEL

![image](https://cloud.githubusercontent.com/assets/5504605/19707187/306d6d10-9ae4-11e6-8969-e6d793ca7c70.png)

3. The Matterbot should also send an introduction message when a user joins the team:
[Ticket here.](https://mattermost.atlassian.net/browse/PLT-1829)

---

Other system messages that will be implemented as part of other features:
When a pinned post is pinned by a user (included in pinned post spec - https://github.com/mattermost/platform/issues/4035)
Conversion of channel type
Private to Public, Group Message to Private, etc.

**Comment by jack-song** [comment]
We have a team willing to take this on

**Comment by yangchen1** [comment]
Wow that was fast @jack-song, awesome!

**Comment by ivernus** [comment]
Can this be closed?

**Comment by jack-song** [comment]
I think we might have some time in august! Is it possible to maybe review what the team thinks the approach should be?

**Comment by jasonblais** [comment]
@jack-song Sorry for the delay in responding!

We've been discussing it in length and feel we should first propose a more complete design to help with the implementation. As a result, despite your interest @jack-song which is very much appreciated, we'll be closing this help wanted issue for now.
