### ISSUE TITLE
[Help Wanted] Add a blue bar when email has been verified after changing your email address

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#4360]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-2333))

After changing your email and clicking the "verify" link received in an email, show a blue bar when the user is taken to Town Square saying "Your email has been verified."

**Comment by santos22** [comment]
Hi,

Is there anyway to turn on email verification locally? I modified the values in **config.json** (see screenshot below) but am not receiving any verification emails. 

<img width="1552" alt="screen shot 2018-01-07 at 6 19 59 pm" src="https://user-images.githubusercontent.com/7004949/34657093-b20d6c10-f3d7-11e7-8218-14b7f91f9043.png">

**Comment by CometKim** [comment]
Hello @santos22 ! There is a [command line tool](https://docs.mattermost.com/administration/command-line-tools.html#platform-user-verify) for that.

**Comment by santos22** [comment]
Hi @CometKim,

Thanks for the prompt response! I used the command line tool and it worked 👍 

I was hoping to actually receive the emails in order to click on the Verify Email and test my changes.

<img width="667" alt="screen shot 2018-01-07 at 6 55 57 pm" src="https://user-images.githubusercontent.com/7004949/34657617-cbbb7ca6-f3dc-11e7-9fea-e59ca200fbba.png">

**Comment by santos22** [comment]
Nvm! I am running a test SMTP server using Python thanks to this [link](https://docs.mattermost.com/developer/running-mattermost.html) 😄
