### ISSUE TITLE
[Help Wanted] Converting Public Channels to Private Groups

### ISSUE THREAD

**Issue by yangchen1** [mattermost/mattermost-server#4587]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

Difficulty: Intermediate

From the channel context menu, a “Convert to Private” option for public channels should be offered as an option to convert public channels to private groups. This should be visible to everyone. Additionally, the option should not be available for any team’s default town square channel.

![image](https://cloud.githubusercontent.com/assets/5504605/20448163/b15669b6-adb0-11e6-82e0-aca80e15abe2.png)

On click, a full-screen modal should appear with the layout and text shown below. Once confirmed, a **system message** should be be sent:
@channel: [USERNAME] has converted this channel to a private group.

![image](https://cloud.githubusercontent.com/assets/5504605/20450283/3e79bdf0-adbd-11e6-8ec1-a4610f2b9c30.png)

Convert [CHANNEL NAME] to a private group?

[CHANNEL NAME] is currently a public channel.

Converting it to a private group means:

- Only people currently in the channel will be able to see and message in the channel
- All previous uploaded files (unless accessed via the Public Link) and past conversations in the public channel will become inaccessible to users not in the channel
- Members will have to be invited to join this channel in the future

Are you sure you want to convert [CHANNEL NAME] to a private group?

[No, cancel] [Yes, convert to private group]

**Comment by cpanato** [comment]
I can try this one, I need to know an example to make this modal

**Comment by cpanato** [comment]
for this requirement: All previous uploaded files (unless accessed via the Public Link) and past conversations in the public channel will become inaccessible to users not in the channel

there are anything that clean the posts? if not how can I get a list of posts made to delete?

**Comment by cpanato** [comment]
@jasonblais @jwilander can you help me on this?

**Comment by jwilander** [comment]
Sorry, @cpanato missed your earlier post. If that happens again feel free to DM me on pre-release.mattermost.com

I think both 1. and 2. of your questions should be covered automatically by making the channel private. For 1. the files will automatically become inaccessible to anyone not in the channel since the permissions check for files is based on the channel the post is in. For 2. inaccessible means that no one not in the channel can see it, which should also be covered automatically by making the channel private

**Comment by cpanato** [comment]
ok, I will do some tests and proceed with the fix :) thanks @jwilander

**Comment by jasonblais** [comment]
Hey @cpanato - here's a link to a PR that previously implemented a full-screen modal: https://github.com/mattermost/platform/pull/4046

That might be helpful when building the page :)

**Comment by yangchen1** [comment]
Hey @cpanato, how's this coming along? Do you have any questions or issues I can help you with? :)

**Comment by andrefaria** [comment]
We are eager to see this feature =)

**Comment by cpanato** [comment]
@yangchen1 I'm working on that, but didnt have time this week :( I'm fighting with the react part which for me is hard :/

**Comment by cpanato** [comment]
releasing this ticket :( I dont have enough knowledge on React to move forward.
anyone can take this ticket

**Comment by yangchen1** [comment]
Hey @cpanato, no worries! Don't sweat it, I'm sure there's another contributor out there who can take this. We really appreciate your efforts to contribute, so I highly encourage you to take a look at our other Help Wanted issues and get your PR's in for our [hackfest](https://about.mattermost.com/mattermost-holiday-hackfest-2016/)!

**Comment by ruzette** [comment]
Hi! I'd like to try this one if this help wanted issue is still available. Thanks! :)

**Comment by jasonblais** [comment]
Thanks @ruzette! Please go ahead 👍 

Let us know if you have any questions. For the full-screen page, this PR might helpful https://github.com/mattermost/platform/pull/4046

**Comment by jasonblais** [comment]
@ruzette FYI, we changed the UI name of `private groups` to ` private channels`, so that might have a slight change to your work here.

**Comment by it33** [comment]
I was speaking to @lfbrock yesterday and we might want to limit this feature to only Team Admins or possibly only System Admins, 

@lfbrock wondering your thoughts? 

Also, I'm wondering if we should close this ticket and create a new one given it's a bit messy right now.

**Comment by charles-passille-smartnets** [comment]
@it33 @jasonblais 
Hello, just confirming, this has not been implemented in 3.10.0 yet, right?

**Comment by jasonblais** [comment]
@it33 we have an open PR here that's almost finished, so I think it's fine keeping this ticket open: https://github.com/mattermost/platform/issues/6067.

And correct, the functionality will be restricted to Team and System Admins.

@charles-passille-smartnets not yet, but it's pretty close and we're aiming for the July 16th release

**Comment by syamgk** [comment]
is the vise-versa(Private to Public) also getting implemented with this pach?

**Comment by jasonblais** [comment]
@syamgk No, as the worry is if someone accidentally (or purposelly) converts a private channel with confidential information to public.

We are planning to add a CLI command for it though (private <--> public), which admins could use.

**Comment by syamgk** [comment]
@jasonblais okey, thanks for the update

**Comment by maniankara** [comment]
@jasonblais any timeline on that cli ?

**Comment by jasonblais** [comment]
@syamgk @maniankara The CLI command should be available in v4.3 (released October 16th)

**Comment by jasonblais** [comment]
Reopened here: https://github.com/mattermost/mattermost-server/issues/7775
