### ISSUE TITLE
[Help Wanted] Autofocus cursor on edit box before modal fully loads

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#4593]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory

**Details**: 

[Jira ticket](https://mattermost.atlassian.net/browse/PLT-3041)
Original community report: https://github.com/mattermost/platform/issues/3105

Repro: 
1. Click up arrow to edit a post
2. Start typing right away

Observed: Typing starts to occur in centre channel before the cursor focuses to edit modal. 

Expected: Set the cursor focus in the edit modal earlier (right now it is explicitly set after the modal fully loads)

**Comment by diagramatics** [comment]
I was dabbling with it for a while until I realised that Bootstrap 3 has an enforced rule to trigger focus on the modal itself. Take a look in https://github.com/twbs/bootstrap/blob/master/js/modal.js#L100-L105.

I don't think there is a way to turn this off properly. You could probably intercept the event and stop the propagation, but that method is pretty hacky. If that's out of the way, this could easily be done with this:

```js
    onModalShow(e) {
        // Needs the `display: block` on the modal in order to toggle focus on a visible element.
        this.refs.modal.style.display = 'block';
        this.refs.editbox.focus();
        var button = e.relatedTarget;
        ...
```

**Comment by jwilander** [comment]
I'll be working on this.
