### ISSUE TITLE
[Help Wanted] Firefox: CTRL/CMD + U to upload a file does not work

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#4597]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Intermediate

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3230)

Repro: 
1. Sign into Mattermost on a Firefox browser
2. Set focus to a message box
3. Hit CTRL/CMD + U

Observed: No action taken

Expected: A dialog opens, letting you upload files.

**Comment by Rudloff** [comment]
I can't quite reproduce on Firefox 52.0a2 (on Linux). I get a warning about a popup window for some reason but if I allow popups it then works correctly.

**Comment by jasonblais** [comment]
@Rudloff I tried on Windows 10, Firefox and it seems to reproduce

I didn't get any warnings about a popup window so I'm not sure if that's why.

**Comment by tejasbubane** [comment]
I was not able to reproduce this on `Firefox 65.0.1 (64-bit)` on `MacOS Mojave 10.14.3 (18D109)`. Pressing Cmd-U opened a file upload box. Is this OS specific?

**Comment by DHaussermann** [comment]
I tested this on 2 different Windows 10 machines and can't repo an issue.

On FireFox 54 - I was prompted by the pop-up blocker and had to allow the pop-up (or trust the site) to get the file window open.

On Firefox 65 - The file window opened without issue.

It may be that some users are not seeing the prompt to allow the pop-up if the browser is configured to hide it.

**Comment by jasonblais** [comment]
Thanks @DHaussermann for verifying! Given it doesn't reproduce on Mac/Linux (from above testing, thanks all!), and we don't support Firefox 54, I'll close this issue.
