### ISSUE TITLE
[Help Wanted] Create screens to edit OAuth 2.0 Applications

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#4752]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-3919))

**Tip:** Before getting started, take a look at how [edit screens for slash commands were created](https://github.com/mattermost/platform/issues/4335) by @bolecki.

It's also a good idea to test the edit screens so you can see how they work for slash commands.

1 - Add an "Edit" button that offers an Edit screen (similar to the create screen) that saves back changes.

![image](https://cloud.githubusercontent.com/assets/13119842/21038148/551332d2-bda1-11e6-82c7-cb7e3fd5c922.png)
_Above: Add "Edit" button left of the "Delete" option_

![image](https://cloud.githubusercontent.com/assets/13119842/21038175/88ccc426-bda1-11e6-9e5b-0416490a071e.png)
_Above: Edit screen that opens after clicking "Edit" in the previous screenshot for OAuth 2.0 apps_

2 - If it's a change that will break existing integrations (a change to one of the callback URLs), add a confirmation dialog notifying the user of the consequences of the update.

The dialog has two buttons, where "Cancel" brings the user back to the edit screen, and "Update" updates the OAuth 2 app.

Text should read `Your changes may break the existing OAuth 2.0 application. Are you sure you would like to update it?`

Below: Sample confirmation dialog for slash commads
![image](https://cloud.githubusercontent.com/assets/13119842/21038001/3ce1c09e-bda0-11e6-8dc5-c720ba4eb547.png)

**Comment by justinwyer** [comment]
I'll have a look at this

**Comment by n1aba** [comment]
I would like to start working on this

**Comment by jasonblais** [comment]
That would be fantastic @n1aba. Let me know if you have any questions

**Comment by n1aba** [comment]
I believe this issue can be closed, all PRs were merged

**Comment by jasonblais** [comment]
Ah yes, you're correct. Big thanks @n1aba!
