### ISSUE TITLE
[Help Wanted] Improve join/leave messages

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#4755]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

**Details:** ([Jira Ticket](https://mattermost.atlassian.net/browse/PLT-3755))

**Part 1:** Join/leave messages should:

1. Never trigger a desktop notification unless you are mentioned by someone else (eg @lindsay added @asaad to the channel)
2. [Already implemented] Never trigger an “Unread” bolded channel name unless you are mentioned by someone else (eg @lindsay added @asaad to the channel)

**Part 2:** Update the grammar for the messages:

1. Switch the joined a channel message to say: `@lindsay joined the channel.`
2. Switch the left a channel message to say: `@lindsay left the channel.`
3. Switch the added to a channel message to say: `@lindsay added @asaad to the channel.`

**Part 3:** Combine Consecutive join/leave messages:

System messages related to joining, leaving, and adding/removing people from channels are combined into one post if they happen one after another, without any non-action messages in between. The messages are simply appended to the first message, and appear in the order that they occur.

Example:

`@lindsay joined the channel. @lindsay added @asaad to the channel. @lindsay left the channel. @jason joined the channel.`

**Comment by debanshuk** [comment]
I am interested in this ticket and am working on it. Also added a comment on JIRA ticket.

**Comment by grundleborg** [comment]
Hi @debanshuk . I was wondering if you are still working on this ticket?

**Comment by debanshuk** [comment]
@grundleborg, I didn't had time to work on the issue for some time. But I have resumed work on it. Though it looks like there need to be a lot of rework due to changes done in this PR https://github.com/mattermost/platform/pull/5209

**Comment by giladgd** [comment]
In my opinion, being able to disable join/leave messages for everyone in a specific channel would be great, or at least being able to disable join/leave messages entirely for all public channels (in config.json as a system admin) would be good enough.
You can also just change the design of the join/leave messages so that they will look similar to how they look in Telegram, which look much better and takes less space as these are less important than normal messages
