### ISSUE TITLE
[Help Wanted] Return cursor to input box after deleting a message.

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-server#4766]
Repro: 

- Post a message
- Delete the message

Expected: 

- Cursor returns to input box for "Write a message..." 

Observed: 

- Cursor DOES NOT return to input box for "Write a message..."

**Comment by S4KH** [comment]
Working on it.

**Comment by S4KH** [comment]
When I press delete from the dropdown it shows me a popup with a confirmation message. Popup is bound to `hidePostDeletedModal` on its `onHide` prop. It seems it not coming into the function. Any idea?

    hidePostDeletedModal() {
        this.setState({
            showPostDeletedModal: false
        });
        this.focusTextbox(); // Focus the "write message..." input box
    }

**Comment by hmhealey** [comment]
@S4KH Have you tried adding a `console.log` statement there to confirm that it's not calling `hidePostDeletedModal`? The modals have some code to prevent keyboard focus from leaving them so it could be preventing `this.focusTextbox` from being ran

**Comment by S4KH** [comment]
@hmhealey I was wrong about that `hidePostDeleteModal()` :slightly_frowning_face: . It is related to totally different modal. The component is `DeletePostModal` but this modal is getting called using `GlobalActions.showDeletePostModal(post, dataComments)` not by `<DeletePostModal/>`. How can we access to the textbox from component. Do we have to pass the textbox too when using the globalActions?

**Comment by jasonblais** [comment]
Thanks @S4KH! Would you be interested joining our [public Developers community channel](https://pre-release.mattermost.com/core/channels/developers)? You'll get faster responses there as both contributors and the Mattermost core team follow the channel regularly.

**Comment by EyesBear** [comment]
I am interested in picking this up.

**Comment by jasonblais** [comment]
Hey @PrincipalsOffice, anything we can help with here?

**Comment by letsila** [comment]
I would be glad to work on this :)

**Comment by jasonblais** [comment]
Thank you @letsila!
