### ISSUE TITLE
[Help Wanted] Desktop notifications for slash commands show escape characters

### ISSUE THREAD

**Issue by joernhees** [mattermost/mattermost-server#4932]
#### Summary
Desktop notifications by browser or desktop app don't seem to properly unescape `\\` and `\_`. Also, if the notification is triggered by a slash-command they pretend to originate from "webhook".

#### Steps to reproduce
Have someone notify you with `/shrug @yourname`, see the desktop notification.

#### Expected behavior
I'd expect something like `OtherUser wrote: ¯\_(ツ)_/¯`

#### Observed behavior
![mm_noficiation](https://cloud.githubusercontent.com/assets/464192/21608307/f4ec22d6-d1bb-11e6-8b70-077327f61f06.png)

NOTE: Slash command refers to Mattermost slash commands: https://docs.mattermost.com/developer/slash-commands.html

**Comment by jasonblais** [comment]
Thanks for the report! Ticket created: https://mattermost.atlassian.net/browse/PLT-5126

Would anyone in the community be interested helping with a fix?

**Comment by grundleborg** [comment]
The username part of this ticket was fixed separately a while back, but the escape characters issue still needs fixing.

**Comment by santos22** [comment]
I can take this one! Should we only be accounting for the case where a `/shrug` command is entered? I don't believe many users will be sending **\\,\\\,\\\\, etc.** messages to one another so the way we escape the `/shrug` command might affect how these messages are received

**Comment by jasonblais** [comment]
@santos22 On Windows at least you can file paths that start with `\` or `\\` if the user truncates the beginning.

**Comment by joernhees** [comment]
yepp, i also think that just handling `/shrug` is probably not cutting it...

**Comment by koxen** [comment]
I'll be fixing this soon as a part of something bigger

**Comment by DHaussermann** [comment]
This is now working as expected. This may have been resolved as part of a different PR. 

Can this PR be closed?

**Comment by jasonblais** [comment]
Thanks @DHaussermann! Closing
