### ISSUE TITLE
[Help Wanted] Add support for private/internal S3 VPC endpoints

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#5173]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Original community report](https://github.com/mattermost/platform/issues/5104)

Mattermost currently only supports public endpoints for S3. 

However, there are many use cases and legal requirements that require use of internal/private VPC endpoints (http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints-s3.html). Private endpoints would use the following syntax: `com.amazonaws...` (eg: `com.amazonaws.us-west-2.s3`)

It appears that adding the new k:v for each region in https://github.com/mattermost/platform/blob/f02620b291b988848392c455a7719699f6b5c00f/vendor/github.com/minio/minio-go/s3-endpoints.go would make the trick.

**Comment by jasonblais** [comment]
Hey @harshavardhana, would you be interested taking a look, as it's related to the Minio implementation you added?

**Comment by harshavardhana** [comment]
In minio-go we can provide to address this issue if needed.  What is hostname of an example VPC endpoint look like ?

**Comment by jasonblais** [comment]
hey @harshavardhana, an example of private endpoints use the following syntax: `com.amazonaws...` (eg: `com.amazonaws.us-west-2.s3`).

The additional issue report might have useful details as well: https://github.com/mattermost/platform/issues/5104

**Comment by harshavardhana** [comment]
Thanks @jasonblais

**Comment by cpanato** [comment]
this is off-topic for this ticket but maybe an improvement @jasonblais @harshavardhana can we add support to roles instead of using aws keys?

**Comment by jasonblais** [comment]
Thanks @cpanato for the suggestion. Would you like to ask that in our [public Developers channel](pre-release.mattermost.com/core/channels/developers) to hear feedback from the core team?

If you ask and get a response, can you help post it here so @harshavardhana knows as well?

**Comment by harshavardhana** [comment]
After reviewing the requirements here - i think that minio-go has nothing to do with these features - these are AWS S3 specific features and we should use aws-sdk-go instead.  My current proposal is to write a new S3 specific endpoint support which provides way to expand on these features. 

Now this is for Mattermost folks to decide to support all S3 features and perhaps encompassing some other features around it. Since these kind of things can come up often for S3 users. 

For example current requests.. 

- VPC Endpoints
- IAM Roles rather than AWS Keys.  (Would require a change in UI) 
... 
There could be more.. which might require change in UI.

**Comment by cpanato** [comment]
I agree that mattermost should support roles as well.

**Comment by jasonblais** [comment]
Sorry @harshavardhana for the delay..what UI would be needed for supporting IAM roles? UI in the System Console?

I think there's three things we'd consider, including
 1. IAM role support
 2. S3 (private) VPC endpoint support, to eliminate the need for Mattermost to go over the public Internet to write to S3
 3. S3 encryption support

@woooooopwop might be able to provide further details in case I missed any

**Comment by cpanato** [comment]
S3 encryption is just a flag you set when you upload

**Comment by jasonblais** [comment]
That's true @cpanato, but I think we'd need add support for it? It's not hard to implement

@harshavardhana would you need detail about the UI for IAM roles?

**Comment by woooooopwop** [comment]
Thanks guys for your work on this.

Why would you need a change in the UI to support IAM roles? 
Assuming we do have `amazons3` as `DriverName`, leaving `AmazonS3AccessKeyId` and `AmazonS3SecretAccessKey` should tell the application to use IAM role associated to the EC2.

**Comment by jasonblais** [comment]
>  My current proposal is to write a new S3 specific endpoint support which provides way to expand on these features.

@harshavardhana would you be interested in contributing that? Or was it a proposal for the Mattermost team?

**Comment by harshavardhana** [comment]
> @harshavardhana would you be interested in contributing that? Or was it a proposal for the Mattermost team?

I would have loved to but won't be able to due to some time constraints on my end @jasonblais.  Would be happy to review the PR and provide feedback for S3 specific things.

**Comment by jasonblais** [comment]
No worries, totally understand @harshavardhana. Really appreciate your input and your willingness to help with reviewing the PR.

Would anyone else in the community be interested helping contribute this improvement?

**Comment by harshavardhana** [comment]
@jasonblais  so we back on your drawing boards and decided to provide IAM support and an initial PR now supporting various credential mechanisms https://github.com/minio/minio-go/pull/646 including IAM is available here. Once perhaps its merged we can explore on adding these capabilities to mattermost as well.

> IAM role support

:+1: 

> S3 (private) VPC endpoint support, to eliminate the need for Mattermost to go over the public Internet to write to S3

Need to explore this, do not have any idea what it entails yet.

> S3 encryption support

We have implemented client side transparent encryption support already - https://github.com/minio/minio-go#full-examples--encrypted-object-operations which are compatible with AWS S3 java sdk implementations of client side encryption as well. 

We followed the spec published here - http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html

**Comment by jasonblais** [comment]
Thanks @harshavardhana! Much appreciated 👍 

Please let us know if you need more details or if we can assist in any way.

**Comment by tejaycar** [comment]
@harshavardhana @jasonblais  I could be mistaken, but it appears that amazon has changed the way VPC endpoints work and now handle them at the DNS or route table level.  IE, no need to use a different url anymore.  Do you guys read things the same way?

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints-s3.html

Also, mino has now added support for auth with instance profiles.  Is there any plan to expand MM support to include that in the near future?

**Comment by jasonblais** [comment]
@harshavardhana any thoughts on the post above regarding S3 VPC endpoint support?

IAM role support for Mattermost is possible thanks to Minio's implementation here: https://github.com/minio/minio-go/pull/646. Is that what you were referring to by `auth with instance profiles`?

**Comment by harshavardhana** [comment]
> IAM role support for Mattermost is possible thanks to Minio's implementation here: minio/minio-go#646. Is that what you were referring to by auth with instance profiles?

Yes @jasonblais - that's what @tejaycar mentioned.

> @harshavardhana any thoughts on the post above regarding S3 VPC endpoint support?

Not sure about this part yet @tejaycar if you can open a bug on minio-go end we can perhaps take a look at it

**Comment by tejaycar** [comment]
@harshavardhana not sure what bug I would open.  My point is that, if I
understand the current approach to VPC endpoints, there is nothing needed
on the software end.  I believe that they are now handled in the route
table on AWS.

**Comment by harshavardhana** [comment]
Oh then it should work right away. @tejaycar with no changes.

**Comment by tejaycar** [comment]
Yes, I agree.  The vpc endpoint should be good to go with no changes.
We'll need a PR on mattermost to get the instance profile part working.

**Comment by harshavardhana** [comment]
> Yes, I agree.  The vpc endpoint should be good to go with no changes.
> We'll need a PR on mattermost to get the instance profile part working.

Yes that would require mattermost to fallback to IAM roles or credentials file which can be changed together as well. - https://github.com/minio/minio-go/blob/master/pkg/credentials/chain.go

**Comment by jasonblais** [comment]
Closing, given support for private S3 VPC endpoints and S3 encryption has been added.

A separate ticket for IAM roles created [here](https://mattermost.atlassian.net/browse/PLT-8186), which we'll likely make help wanted next week.

**Comment by tejaycar** [comment]
I've already got a PR out there for the IAM roles.  It just needs to get
updated to point against the new split repos and incorporate a little bit
of feedback from your design team

**Comment by jasonblais** [comment]
@tejaycar Excellent point - I added a link to your PR in the ticket description.

We have a lot of community members working on help wanted tickets so I thought someone might pick this one up, since I know you're busy at the moment. If no one has when you get back to your PR, we'd be more than happy to work with you on it :)
