### ISSUE TITLE
[Help Wanted] Add automated unit tests that confirm the CSS and HTML generated from Markdown test inputs

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-server#5196]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

We are having too many regressions on changes to text processing. On pre-release right now we have line breaks inconsistently rendered because we merged a PR that didn't fail when CSS changes broke other parts of the system. We can't revert the PR because it changed the database. 

This ticket is to add unit tests that confirm the CSS and HTML generated from test inputs (https://github.com/mattermost/platform/blob/master/tests/test-markdown-lists.md) is consistent from release to release--or some other automated method to prevent regressions. 

Markdown rendering is critical, predictable functionality, regressions shouldn't be that hard to spot. 

Is there someone from the community to share their thoughts on how we can improve here? 

Also looking for help on this improvement.

**Comment by hmhealey** [comment]
Much of this functionality is covered by the [marked.js unit tests](https://github.com/mattermost/marked/tree/master/test/tests) and the [webapp's unit tests](https://github.com/mattermost/platform/tree/master/webapp/tests), but these focus only on the HTML that's generated without paying attention to how it is styled.

Additional unit tests for the HTML would be helpful, but the main thing that we would need is infrastructure to test the styling applied to the rendered HTML

**Comment by hanzei** [comment]
@hmhealey Would you please check if this ticket is still valid and if so make changes to the text accordingly?

**Comment by hmhealey** [comment]
I don't think this is needed any more. The markdown libraries have extensive tests for the HTML output, and we aren't changing the CSS that affects them any more. Are we good to close this, @jasonblais?

**Comment by jasonblais** [comment]
> The markdown libraries have extensive tests for the HTML output, and we aren't changing the CSS that affects them any more.

Seems like the original concerns no longer apply. We can close. Thanks Hanzei and Harrison
