### ISSUE TITLE
[Help Wanted] [PLT-3324] Support implied attachments for incoming webhooks

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#5265]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3324)

Slack will accept incoming webhook bodies that are the contents of Slack attachments without the `attachments` specifier. For example a normal incoming webhook with an attachment looks like:

```
{
    "attachments": [
        {
            "fallback": "Task set: @martinschenck set the task to `taskname`. All votes have been reset.",
            "color": "good",
            "fields": [
                {
                    "title": "Task set",
                    "value": "@martinschenck set the task to `taskname`. All votes have been reset.",
                    "short": false
                }
            ]
        }
    ]
}
```

But Slack will also accept:

```
{
    "fallback": "Task set: @martinschenck set the task to `taskname`. All votes have been reset.",
    "color": "good",
    "fields": [
        {
            "title": "Task set",
            "value": "@martinschenck set the task to `taskname`. All votes have been reset.",
            "short": false
        }
    ]
}
```

To be compatible with Slack we should also support the second case.

Thanks to apheleia for bringing this to our attention!
https://pre-release.mattermost.com/core/pl/hsop79ig7pym9beyhtz4nb96iy

**Comment by mkraft** [comment]
I'll take this one.

**Comment by jasonblais** [comment]
@mkraft As you found out, Slack no longer supports "implied attachments" and instead throws a 500 error.

Did you start working on code changes for this yet?

**Comment by mkraft** [comment]
@jasonblais I do have a branch that makes the change. It was in determining how to change/update tests that I ended up creating a Slack app and re-testing the original case. I think we not use the code I wrote though and rather close this issue so that we don't have to hassle with supporting undocumented payloads.

**Comment by jasonblais** [comment]
Thanks @mkraft, I agree. Sorry for the additional work on your part, I hope it wasn't too much..

Really appreciate your thoughtfulness.

**Comment by jasonblais** [comment]
Let me know if there is another issue you'd like to work on for Hacktoberfest?

**Comment by mkraft** [comment]
@jasonblais No worries. It helped me start to get familiar with the code. I'll choose something else. Thanks.
