### ISSUE TITLE
[Help Wanted] [PLT-5360] Clicking on email verification does not automatically fill in your email on mobile browser

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#5366]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5360)

This is a follow-up to https://github.com/mattermost/platform/pull/5140, whose PR can be found here and added this functionality for the desktop browser.

Repro (iOS, Safari browser):
1. Sign up to a site, and receive a verification email
2. On your phone, click the link in the email verification email
3. Click "Continue to browser" on the ios/android landing page.

Observed: Email verification is successful, but your email address is not filled in on the log in page. This is because you're redirected to the switch_team page instead (and in return to the login page without the email validation URL)

Expected: 
To improve the user experience, your email address in already filled in and cursor is in the password field. 

One solution is that if you're redirected to Mattermost via an email verification, bypass the ios/android landing page.

**Comment by jasonblais** [comment]
Resolved, thanks to @cpanato and @aautio!

**Comment by cpanato** [comment]
will take this one 😄

**Comment by cpanato** [comment]
@jasonblais I've tested that using current master and I was not able to reproduce. It works as expected in IOS/Safari and also in Android/Chrome.

**Comment by jasonblais** [comment]
@cpanato It's indeed fixed, verified by @lindy65. Thanks!
