### ISSUE TITLE
[Help Wanted] No feedback when trying to save localization settings in System Console when Available Languages doesn't include the default client language

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#5463]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5549)

There is no feedback when trying to save localization settings in System Console when Available Languages doesn't include the default client language.

Repro:

1) Go to System Console > Localization
2) Set Default Client Language to "Francais"
3) Set Available Languages to "Espanol"

Observed: Save button greyed out with no feedback to why it cannot be saved

Expected: 
   1. Save button not greyed out (to be consistent with other System Console pages)
   2. If Available Languages doesn't contain the default client language, AND the user clicks "Save", display an error message `Available Languages must include the Default Client Language.`

**Comment by santos22** [comment]
❓ 🤔   Should this issue be closed? I see there was a PR submitted for it -
 https://github.com/mattermost/mattermost-webapp/pull/97

**Comment by esethna** [comment]
Thanks for the catch @santos22, it should be closed.
