### ISSUE TITLE
[Help Wanted] [PLT-5270] Bold, italic and striked links should show link preview when available

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#5465]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5270)

Link previews with formatted text:
 - quoted ("> link") links currently show a preview, which is expected
 - inline code and code blocks don't show a link preview, which is expected
 - bold, italic and striked links are formatted accordingly but do not show a preview

Proposed change:

Bold, italic and striked links should be properly formatted AND show a preview. I.e. the following should be formatted and show a preview:
 - **https://about.mattermost.com**
 - *https://about.mattermost.com*
 - ~~https://about.mattermost.com~~

**Comment by cpanato** [comment]
in the current `master`  I can see those in the preview mode rendering correctly 

![screen shot 2017-06-26 at 15 53 05](https://user-images.githubusercontent.com/4115580/27542456-9641c9e8-5a87-11e7-8746-cbaa0b10d1d6.png)

**Comment by hmhealey** [comment]
@cpanato I thought that's what the ticket meant at first as well, but it's actually for link previews on posts that have been made, not the markdown preview box. Right now, posting `https://about.mattermost.com` shows a link preview, but posting `*https://about.mattermost.com*` or using any other markdown formatting does not

**Comment by cpanato** [comment]
like this @hmhealey 
![screen shot 2017-06-26 at 16 25 31](https://user-images.githubusercontent.com/4115580/27543986-1fd335c6-5a8c-11e7-9c33-f9bd01175817.png)

**Comment by cpanato** [comment]
or what is link preview ?

**Comment by hmhealey** [comment]
You need to enable them from User Settings > Advanced > Enable pre-release features. Here are 4 posts with different formatting, and you can see the first one has a preview while the others do not
![image](https://user-images.githubusercontent.com/3277310/27544246-8ac094dc-5a5a-11e7-9694-12c3f3f01f37.png)

**Comment by cpanato** [comment]
ah! will take a look on that later thanks @hmhealey

**Comment by lantran** [comment]
Hi Mattermost,
I would like to pick up this ticket. I am new and this is my very first ticket. (also don't know much abou t ReactJS).
I tried to reproduce the problem on my local but I couldn't. I do see the preview link feature on the app I installed.
Could you guys help me with that first?

**Comment by jasonblais** [comment]
@lantran First, big thanks for your interest working on this feature!

You will first need to enable link previews from System Console > Customization > Link Previews. Once enabled, website previews should show up on your instance.

Let us know if you have any other questions

**Comment by lantran** [comment]
@jasonblais : I looked the ticket and here is my approach. The idea is that I have to clean the url before I send the request to get OpenGraphData. Details:

* Removing markdown in `url` in `getOpenGraphMetadataForUrl` of `posts.js`
* Using similar logic from `removeCode` in `post_utils.jsx` to clean url

That is my plan. (I just looked at the code and how we implemented the feature) Let me know if it sounds ok to you.

**Comment by hmhealey** [comment]
That general idea should work, but I'd caution you that the logic may have to be more complicated than the stuff in removeCode since code blocks are simpler than other formatted text since code can't be nested and doesn't depend on how the text around it looks (like these_words dont_italicize, but `_these words do_`). I haven't looked too much into this, but it may have been mislabeled as being easier than it should've been

**Comment by jasonblais** [comment]
@lantran thanks for following up! I've posted your question in our community instance - to me it looks good but better to get someone with a stronger technical background to confirm,

https://pre-release.mattermost.com/core/pl/5keg13ugyiy8ic5ftjci49j54a

**Comment by lantran** [comment]
Thanks @hmhealey . I will try my best.

**Comment by jasonblais** [comment]
Hey @lantran , let us know if we can help with anything?

**Comment by CoolTomatos** [comment]
Hi Mattermost,
We are a group of four students, who are currently taking a course to study open source projects.
My teammates and I would love to help you fix this issue.

My teammates are: @GitHubJasper @lmikaellukerad @XinyueWang94
