### ISSUE TITLE
Make `/collapse` and `/expand` only apply to previous posts in the channel

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#5728]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4380)

Currently /collapse and /expand commands simply control the "Account Settings > Display > Default appearance of image link previews" setting. 

Proposed change: Have the command only apply to previous posts in the current channel. 

Example: Suppose 
 - "Account Settings > Display > Default appearance of image link previews" is set to "Expanded", and
 - user types /collapse in channel ABC.

Then
 - image links in existing posts in channel ABC collapse
 - new posts containing image links in channel ABC are expanded by default
 - image links in other channels are expanded by default

**Comment by KishoreFartiyal** [comment]
@jasonblais I would like to work on this issue.

**Comment by jasonblais** [comment]
Sweet, go for it @KishoreFartiyal!

**Comment by KishoreFartiyal** [comment]
@jasonblais 
What if user types /collapse in channel ABC , moves to the other channel and comes back to channel ABC?
In that case, previous image links in channel ABC will be collapsed or expanded?

**Comment by jasonblais** [comment]
@KishoreFartiyal They should stay collapsed if they switch back to the channel.

**Comment by panditsavitags** [comment]
@jasonblais 
By image links, do you mean the image attachments which have previews or the Youtube Embed? 
Please confirm.

**Comment by jasonblais** [comment]
@KishoreFartiyal @panditsavitags 

That's correct. Image link previews include:
 1. https://www.mattermost.org/wp-content/uploads/2016/03/logoHorizontal.png
 2. https://www.youtube.com/watch?v=A2GbEFFyzGw

![image](https://user-images.githubusercontent.com/13119842/33321507-f524c266-d413-11e7-8d0d-f7ffa5d68b34.png)

and image preview from website links, e.g.
 3. https://about.mattermost.com

![image](https://user-images.githubusercontent.com/13119842/33321535-0cf69dec-d414-11e7-8288-cd6cc406cc04.png)

**Comment by henricook** [comment]
If someone implements this are the powers that be happy with changing the meaning of /expand and /collapse? I'd imagine they're rarely used but if I was going to work on this i'd want this to be clear on the way in. The spec of this ticket is to change /collapse and /expand to just collapse/expand messages in the current channel and not affect any global settings or other channels, as I understand it - right?

**Comment by lfbrock** [comment]
@henricook - yes that's correct, it would be changing the behaviour to only affect previous posts in the current channel. This was based off of user requests to have it work more like other products.

However it does look this ticket looks like it could use a few more details on what happens when you change the setting, and updating the help text for it, so I'll send it back to the team to look at again.

**Comment by M-ZubairAhmed** [comment]
I have had discussion with @jasonblais regarding this issue, this issue seems to be updated to the new flow, awaiting for further discussions after holidays

**Comment by M-ZubairAhmed** [comment]
opened a conversation at mattermost community here at https://community.mattermost.com/core/pl/k1wgy1qak3d6ugasitw9btyzww

**Comment by jasonblais** [comment]
Based on the Jira comments, looks like this ticket needs a few more functional details, updated help text for the setting, and a decision on whether to keep a way to collapse all the channels.
