### ISSUE TITLE
[Help Wanted] from: followed by a space hides the autocomplete IE11

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#5736]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5827)

Repro steps:
1) Type `from:` in the search bar, then hit space

Observed: `from:` autocomplete closes
Expected:  `from:` autocomplete remains open

Reproduces on IE11

**Comment by KishoreFartiyal** [comment]
@jasonblais It's working in IE11 on my system. Autocomplete remains open after hitting space

**Comment by lindalumitchell** [comment]
@jasonblais @KishoreFartiyal I verified this does not reproduce for me either, on IE11. Closing issue.
