### ISSUE TITLE
[Help Wanted] Desktop notification is fired when viewing channel in Safari

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#5758]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5855)

Related PR: https://github.com/mattermost/platform/pull/4216

Repro steps:
1) Enable desktop notifications
2) Go to a channel 
3) In another window, go to the same channel with another account
4) Using that another account, send a delayed message by sending `/echo post 5`
5) Switch back to the first window before the post is made

Observed: A desktop notification is displayed
Expected: No desktop notification is displayed since the Safari window is in focus

**Comment by letsila** [comment]
I am ready to help on this :)

**Comment by jasonblais** [comment]
Yay, thanks @letsila!

**Comment by letsila** [comment]
I could not reproduce the bug. I receive notification only when the safari window is not in focus. Have it been fixed in some way ?

**Comment by jasonblais** [comment]
Ah yes, thanks @letsila. Looks like this was resolved in a recent release. 

Sorry about that..would there be another Hacktoberfest ticket you're interested helping with?

**Comment by letsila** [comment]
Hi @jasonblais it's ok. There's actually this issue #6483 that I claimed but haven't yet received reply from.
