### ISSUE TITLE
Change direct message list to be infinite scroll

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#5790]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4515)

Change direct message list to be infinite scroll.

Threshold will be 30 per list and load more when the scroll passes the threshold.

See initial commits [in this PR](https://github.com/mattermost/platform/pull/4375) to help you get started.

**Comment by deveshjadon98** [comment]
i would like to work on it.

**Comment by jasonblais** [comment]
Hey @deveshjadon98, let us know if there's anything we can help with?

**Comment by JayaKrishnaNamburu** [comment]
Hi @sudheerDev, I would like to contribute to this.

**Comment by jasonblais** [comment]
Thanks @JayaKrishnaNamburu!

**Comment by esethna** [comment]
Reopening here: https://github.com/mattermost/mattermost-server/issues/11241
