### ISSUE TITLE
[Help Wanted] Last viewed team isn't saved after logout

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#5977]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-6157))

Repro steps:
1) Join multiple teams with the current user
2) Switch to one that isn't the first team in their sidebar
3) Log out
4) Log back in

Observed: You're logged in to the first team in their sidebar
Expected: You're logged back into the last team you viewed

**Comment by VeraLyu** [comment]
Hi, Can I take this one?

**Comment by pradeepmurugesan** [comment]
@jasonblais  Looks like this feature has been implemented already.

I can see this behavior in the current setup..

**Comment by jasonblais** [comment]
@pradeepmurugesan Good catch, this was indeed implemented in Mattermost 5.4. Closing
