### ISSUE TITLE
[Help Wanted] Adding a member doesn't update member count until refresh

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#5978]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).a

----

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-6197))

Repro (also reproduces with other invite methods):

1) Go to Main Menu > Add Members to Team
2) Choose members, then hit "Go"

Observed: User joins the team, but channel member count for Town Square or Off-Topic don't update for existing users until refresh
Expected: Channel member count updates

**Comment by cpanato** [comment]
I have a fix for that @jasonblais 
Will submit this on Monday. :) forgot my yubico key at work, whitout that I cant commit lol

but the same issue happen when you remove a user from team, it not update the count. My fix also fix this. There is another ticket for this? if yes I will submit two prs then :)

**Comment by cpanato** [comment]
ok both add and remove is working :)

**Comment by jasonblais** [comment]
@cpanato I couldn't find a separate ticket for removing a user, so feel free to submit the fixes in a single PR

**Comment by cpanato** [comment]
sounds good @jasonblais thanks!

**Comment by cpanato** [comment]
PR https://github.com/mattermost/mattermost-webapp/pull/160

**Comment by jasonblais** [comment]
Thanks @cpanato!
