### ISSUE TITLE
OAuth2.0: Incorrect Client ID during authentication allows user to go "Back to Mattermost" in the authentication window

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6070]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4207)

If Auth2.0 Authentication fails because of an incorrect Client ID (see screenshots from Zapier), then the error message given provides an option for "Back to Mattermost" that opens Mattermost to the team selection page.

Expected:
No "Back to Mattermost" button, page should just display a helpful error message.

![image](https://cloud.githubusercontent.com/assets/13119842/24919681/77d39376-1eb2-11e7-9800-25ddaeaa53ea.png)

![image](https://cloud.githubusercontent.com/assets/13119842/24919686/7e2d752a-1eb2-11e7-8f96-f5d630996b88.png)

Note: The page accepts query parameters that should allow you to submit this change

**Comment by tharun208** [comment]
I can pick this one if it's still open. 👍

**Comment by esethna** [comment]
Awesome!
