### ISSUE TITLE
[Help Wanted] [PLT-5170] "Joined the channel" system message does not get posted for the person who created the channel

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6122]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5170)

Repro: 
1. Create a channel

Observed: No message saying "username joined the channel" for the person who created the channel

Expected: Message should appear

**Comment by yeoji** [comment]
Hey @jasonblais, this issue seems to be fixed. The linked JIRA ticket is closed.

**Comment by jasonblais** [comment]
@yeoji Good find, it's indeed resolved. Closing this issue
