### ISSUE TITLE
Add " v New messages below" indicator to the right-hand-side

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6123]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5082)

Add new messages indicator when scrolled up in the right-hand-side and new messages are posted on the thread.

Ticket for adding this functionality in the center channel: https://github.com/mattermost/platform/issues/4250
PR that added this functionality in the center channel: https://github.com/mattermost/platform/pull/4299

![image](https://cloud.githubusercontent.com/assets/13119842/25074486/a8561472-22c9-11e7-8f12-3a386f88e489.png)

**Comment by tborg** [comment]
I'd be happy to tackle this.

**Comment by amyblais** [comment]
Hi @tborg, thank you for your interest in helping with this ticket!

Apologies for late response, please let us know if you have any questions about how to get started.

**Comment by hanzei** [comment]
@esethna Is this ticket still valid or is this covered by infinity scroll?

**Comment by hanzei** [comment]
@esethna Gentle reminder about this

**Comment by larkox** [comment]
I would like to take this one. I have done some checks, and it does not seem to be covered in the current version.

**Comment by larkox** [comment]
Should we close this Issue for the same reasons as the PR? Or will you prefer to keep it open?

> Propose we close this PR given we have the new toast behaviour and likely some changes to RHS behaviour coming with the threading overhaul (designs in progress).

**Comment by esethna** [comment]
Thanks, yes we should close as per PR conversation: https://github.com/mattermost/mattermost-webapp/pull/4552#issuecomment-591135551
