### ISSUE TITLE
[Help Wanted] [PLT-4951] Don't send a desktop notification and don't mark channel unread if a comment thread for that channel is open in right hand sidebar, and Mattermost is in focus

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6126]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4951)

Don't send a desktop notification and don't mark channel unread if a comment thread for that channel is open in right hand sidebar, and Mattermost is in focus.

Environment:
1) comment thread for channel_A is open in right-hand sidebar, 
2) channel_B is open on the center pane
3) Mattermost is in focus

A) If someone posts a message on the comment thread that is open in the right-hand side, do not send a desktop notification, and do not bold the channel name on the left-hand sidebar
B) [implemented] If someone posts a message on channel_B, do not send a desktop notification, and do not bold the channel name on the left-hand sidebar
C) If someone posts a message on channel_A, but not in the comment thread that is open in the right-hand side, send a desktop notification and bold the channel name on the left-hand sidebar

**Comment by kulak-at** [comment]
I take this one!

**Comment by jasonblais** [comment]
You're awesome @kulak-at!! Thank you :)

**Comment by jasonblais** [comment]
Start of a PR here that was since closed: https://github.com/mattermost/platform/pull/6461

**Comment by jasonblais** [comment]
Reopened here: https://github.com/mattermost/mattermost-server/issues/7541
