### ISSUE TITLE
[Help Wanted] [PLT-4790] At mentions don't appear linked in message box preview mode, only after you've posted them

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6127]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4790)

At mentions don't appear linked in message box preview mode, only after you've posted them

Repro:
1) Go to "Account Settings > Advanced > Preview pre-release features" and enable "Show markdown preview option in message input box"
2) Type "@[username]" in the message box
3) Hit "Preview" below the message box, on the right side

Observed: "@[username]" no longer highlighted as a link
Expected: "@[username]" highlighted as a link, as before

**Comment by vgvenkat** [comment]
Hi @jasonblais I want to take this on.

(I had posted on [PLT-7774], but for starters, would start with a lesser difficulty issue)

**Comment by jasonblais** [comment]
Awesome, go for it @vgvenkat! Let us know if you have any questions, look forward to the pull request :)

**Comment by coreyhulen** [comment]
This is back up from grabs.

**Comment by Hyeongmin-Kwon** [comment]
I can take this :smiley:

**Comment by jasonblais** [comment]
Awesome, thanks @Hyeongmin-Kwon!
