### ISSUE TITLE
[Help Wanted] [PLT-6362] Add full date tooltip to post timestamps in right-hand sidebar and search results using system tooltip

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6172]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6362)

Add full date tooltip to post timestamps in right-hand sidebar and search results using system tooltip

See https://github.com/mattermost/platform/pull/5688 for a PR that added the tooltip to post timestamps in the center channel

**Comment by yeoji** [comment]
I have created a PR in mattermost-webapp for this issue

**Comment by jasonblais** [comment]
Thanks @yeoji!
