### ISSUE TITLE
[Help Wanted] [PLT-3540] All fields highlight red when an error is caused on switch authentication method screens

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6178]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3540)

When you enter incorrect information on:  
- Switch LDAP to Email password screen
- Switch Email/Password Account to LDAP

All the fields turn red. 

![image](https://cloud.githubusercontent.com/assets/13119842/25246791/bc89bcfe-25d6-11e7-86cf-12a918bde0e9.png)

Expected: Only the incorrect field turns red.

**Comment by jasonblais** [comment]
Resolved
