### ISSUE TITLE
[Help Wanted] [PLT-5894] Show all emoji aliases on the picker

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6276]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5894)

Repro:
1) Enable emoji picker from Account Settings > Advanced > Preview pre-release features.
2) Click emoji icon to open the emoji picker.
3) Find the thumbs up (or +1) emoji from the "People" category.

Observed: Only one of the emoji aliases for ":+1:" is shown when hovering an emoji on the picker

![image](https://cloud.githubusercontent.com/assets/13119842/25580564/005769f0-2e50-11e7-883c-f3e968000199.png)

Expected: All emoji aliases (":+1:", ":thumbsup") are shown when hovering an emoji on the picker.

See https://github.com/mattermost/platform/pull/5157 which added the emoji picker. 
See https://github.com/mattermost/platform/pull/5904 which added the emoji picker for reactions.

**Comment by Roy-Orbison** [comment]
Why close unresolved issues?

**Comment by jasonblais** [comment]
Hi @Roy-Orbison! Apologies, I should have included a note here as well. 

We had not received any feature requests for it, so we closed it over other priorities at the time.

If you're interested in this feature, would you be open to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)? Please include a link back to this GitHub Issue if you do.

**Comment by esethna** [comment]
Thanks for the PR!

**Comment by sudheerDev** [comment]
@jasonblais Closing this as related PR is merged
