### ISSUE TITLE
[Help Wanted] [PLT-5576] Add emoji picker for edit message dialog

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6277]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5576)

See https://github.com/mattermost/platform/pull/5157 which added the emoji picker.

Currently there is no emoji picker in the edit dialog - this ticket adds an emoji picker for that dialog.

![image](https://cloud.githubusercontent.com/assets/13119842/25580575/262d68e6-2e50-11e7-889d-4a04d5400538.png)

See https://github.com/mattermost/platform/pull/5157 which added the emoji picker. 
See https://github.com/mattermost/platform/pull/5904 which added the emoji picker for reactions.

**Comment by R-Wang97** [comment]
I can take a look at this!

**Comment by jasonblais** [comment]
Thanks @R-Wang97!

**Comment by R-Wang97** [comment]
@jasonblais I totally forgot about this ticket, if it's still open I can take a stab at it!

**Comment by jasonblais** [comment]
Looks like it's still open, feel free to take it! Thanks @R-Wang97!
