### ISSUE TITLE
[Help Wanted] [PLT-6039] When searching in emoji picker, remove categorization

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6279]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6039)

When searching in emoji picker, remove categorization and instead simply list all the emoji that match the search result, nine emoji per row.

Notes:
 1) The order should follow the order in emoji picker, i.e. "People" emoji first, followed by "Nature", "Food", etc.
 2) Recently used emoji shouldn't be included in the list, to avoid having the same emoji twice.
 3) At the header of the emoji picker, the "Recently Used" section should be highlighted when doing the search.

See https://github.com/mattermost/platform/pull/5157 which added the emoji picker. 
See https://github.com/mattermost/platform/pull/5904 which added the emoji picker for reactions.

**Comment by maruTA-bis5** [comment]
I'd like to try working on this

**Comment by jasonblais** [comment]
Awesome, thank you @maruTA-bis5!
