### ISSUE TITLE
[Help Wanted] [PLT-5574] Left/right/up/down arrows can be used to navigate through the emoji picker

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6283]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5574)

Currently you need to use your mouse to choose an emoji.

The proposed change is to allow left/right/up/down arrows to navigate through the emoji picker, with Enter selecting the emoji.

This is particularly useful after you've searched for an emoji, where the expectation is that you can use the arrow keys to choose the emoji you want.

See https://github.com/mattermost/platform/pull/5157 which added the emoji picker. 
See https://github.com/mattermost/platform/pull/5904 which added the emoji picker for reactions.

**Comment by pruthvip** [comment]
Will give it a try

**Comment by jasonblais** [comment]
Thanks @pruthvip, let us know if you have any questions!

**Comment by jasonblais** [comment]
@pruthvip Let us know if there's anything we can help with?

**Comment by stephenkiers** [comment]
Currently a emoji is not automatically selected. For this feature, you would need to always have a emoji selected (first one by default, I assume) and the arrows would move the selection around.
The selection would reset to default (0) on search term change.
Hitting enter would select the currently selected emoji.
Mouseover would change selection and would leave emoji selected when they leave the controller (for example if they go out the left side, the last emoji they crossed would stay selected)

This is a change from current functionality, which is specifically coded to deselect on mouseout. 

Is that an acceptable UX change?

**Comment by jasonblais** [comment]
@stephenkiers Are we forced to have an emoji selected when opening the picker? Instead of having the focus on the search bar by default?

Slack has the focus on the search bar, and clicking on the down-arrow brings you to the first emoji on the list.

----

Other notes:

> The selection would reset to default (0) on search term change
> Hitting enter would select the currently selected emoji.

Both sound good.

> Mouseover would change selection and would leave emoji selected when they leave the controller 

I can touch base with our UX team on that.

**Comment by stephenkiers** [comment]
Actual 'Focus' would still be in the search bar. The emoji would simply be highlighted

**Comment by jasonblais** [comment]
Thanks @stephenkiers, that makes sense.

Just curious: is this a requirement for this feature, or does it make implementation easier?

**Comment by stephenkiers** [comment]
It isn't a requirement, but in order to use keyboard short cuts (up, left,
right, down) I assume you need a visual way to see where the cursor is.
highlighting the emoji seems the most straight-forward to me, as it
piggybacks off current UI.

I guess you could only show selection once up down right or left is
clicked; but I don't think that is as intuitive for the end user. Having
one preselected hints that you can move it.

**Comment by stephenkiers** [comment]
I am open to other UX suggestions though.

**Comment by stephenkiers** [comment]
Perhaps Up for Grabs should be removed while this PR is pending.

**Comment by esethna** [comment]
Removed, thanks!

**Comment by jasonblais** [comment]
Thanks @stephenkiers 👍
