### ISSUE TITLE
[Help Wanted] [PLT-6229] Post should show a plus sign for adding to existing emoji reactions

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#6284]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6229)

When a post already has reactions, add an extra box next to the list of reactions, containing a + sign. When clicked upon, this box should open up the emoji picker.

See https://github.com/mattermost/platform/pull/5157 which added the emoji picker. 
See https://github.com/mattermost/platform/pull/5904 which added the emoji picker for reactions.

**Comment by R-Wang97** [comment]
I can give this a try!

**Comment by jasonblais** [comment]
Thanks @R-Wang97! :tada:
