### ISSUE TITLE
GIF images (custom emoji) and Profile Pics do not retain background transparency

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6299]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6455)

Original report: https://github.com/mattermost/platform/issues/6270

SUMMARY
GIF images (custom emoji) and Profile Pics do not retain background transparency.

STEPS TO REPRODUCE
Version: pre-release.mattermost.com

1. Custom Emoji > Add Custom Emoji
2. Save the image to your computer https://i.imgur.com/pmIfMVG.gif
![img](https://i.imgur.com/pmIfMVG.gif)
3. On the modal that was open from step 1 use the saved GIF from step 2
4. On the text preview in that page before clicking SAVE, it properly shows with transparency
5. After its saved and upload the background goes black, on the emoji
6. Using this emoji on any where will have its background black instead of transparent

EXPECTED BEHAVIOUR
The GIF will retain its transparency, like the original above.

OBSERVED BEHAVIOUR
The uploaded GIF had its background changed from transparent to black. It could be a global issue for any uploaded image that goes through Plan9 palette?

SIDE NOTE
Created it under the name :monkey-want: if want to test it on https://pre-release.mattermost.com.

**Comment by VeraLyu** [comment]
I'll look into it.

**Comment by tgaither** [comment]
Ran into this problem, the problem occurs when Mattermost has to resample your image. I took my 240x240 gif and resampled it to the expected size of 128x128 and the problem went away. Not sure if resolution is the only contributing factor, but it was for me :)

**Comment by akiross** [comment]
I am not sure if this issue is still open and if #19164 solved this issue, but in mattermost cloud the problem is still present when adding a custom emoji.

When adding a custom emoji:
![Screenshot from 2022-01-18 09-45-08](https://user-images.githubusercontent.com/884092/149902035-579daed0-93ac-42d2-afeb-d618c5d02981.png)

After adding it (and in subsequent uses):
![Screenshot from 2022-01-18 09-45-25](https://user-images.githubusercontent.com/884092/149902080-4538b34e-b075-4c81-885c-4f17060371c7.png)

**Comment by akiross** [comment]
Thanks for the kind offer, but I don't think I got the bandwidth rn, sorry

**Comment by esethna** [comment]
Thanks @akiross, we reproduced and have reopened the ticket

**Comment by jwlkns** [comment]
It looks like all tickets regarding this are closed. Has this just not been addressed since the last comment, or has the bug been reintroduced? Same behavior as described is happening for me. Preview has transparency, but the saved image has a black background.

**Comment by KaitoMuraoka** [comment]
This issue still occurs
