### ISSUE TITLE
[Help Wanted] [PLT-6432] Closing a DM/GM channel, then re-opening later, doesn't restore channel preferences

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6326]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6432)

CASE 1:

1) Open a direct message channel with someone
2) Favorite the channel
3) Click "x" on the left sidebar to close/hide the channel from the sidebar
4) Go to "More.." and re-open the direct message channel

Observed: Channel is no longer favorited
Expected: Channel should restore to be one of your favorites

CASE 2:

1) Go to a group message channel and click the channel name
2) Choose "Notification Preferences" from the dropdown
3) Set "Send desktop notifications" to "Never"
4) Leave the channel
5) Re-join the channel via "More..." list

Observed: Notification preferences of the channel reset to global defaults
Expected: "Send desktop notifications" preference should still be set to "Never"

**Comment by santos22** [comment]
I can take this! I'm running Mattermost locally and am still seeing this issue so I'm assuming it's still open 😄

**Comment by jasonblais** [comment]
It is! Thanks @santos22 :)
