### ISSUE TITLE
[Help Wanted] Migrate channel_info_modal.jsx to be pure and use Redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#6441]
If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/channel_info_modal.jsx`](https://github.com/mattermost/platform/blob/master/webapp/components/channel_info_modal.jsx) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://grundleborg.github.io/posts/react-component-testing-in-mattermost/). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**Comment by kulak-at** [comment]
@jasonblais I can take care of it :)

**Comment by cpanato** [comment]
@kulak-at I was working on that based on this spreadsheet: https://docs.google.com/spreadsheets/d/1AlFS2F4H74JsONxIS_VNZBxrVJolZxFh7yN46RNCwyg/edit#gid=0

but if you have a lot of work done then it's easier you take that.
please confirm.

**Comment by R-Wang97** [comment]
I can take this!
