### ISSUE TITLE
[Help Wanted] Migrate installed_outgoing_webhook.jsx to be pure and use Redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#6450]
If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/integrations/components/installed_outgoing_webhook.jsx`](https://github.com/mattermost/platform/blob/master/webapp/components/integrations/components/installed_outgoing_webhook.jsx) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://grundleborg.github.io/posts/react-component-testing-in-mattermost/). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

Start of a PR here: https://github.com/mattermost/mattermost-server/pull/7192

**Comment by sudheerDev** [comment]
@jasonblais I will take this one. Looks like it's similar to https://github.com/mattermost/platform/issues/6449 anyway

**Comment by sudheerDev** [comment]
@jasonblais Yes I pushed the commit changes to the new repository will be adding test cases soon. You can remove `up for grabs` label for now.
