### ISSUE TITLE
[Help Wanted] [PLT-6217] Update system message posted to Town Square after adding/removing someone from a team, or joining/leaving a team

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6483]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6217)

CASE 1:

Suppose “jason” adds “joram” to a team. 

Observed: System message: “joram added to the channel by jason” posted to “Town Square” channel
Expected: System message: “joram added to the team by jason” posted to “Town Square” channel

CASE 2:

Suppose “jason” removes “joram” from a team. 

Observed: No system message
Expected: System message: “joram was removed from the team” posted to “Town Square” channel

CASE 3:

Suppose “jason” joins the team. 

Expected: System message: “jason joined the team” posted to “Town Square” channel
Observed: System message posted about joining the channel

CASE 4:

Suppose “jason” leaves the team.

Expected: System message: “jason left the team” posted to “Town Square” channel
Observed: System message posted about leaving the channel.

**Comment by letsila** [comment]
Hi guys! I'd like to work on this issue :)

**Comment by jasonblais** [comment]
@letsila Sorry about missing your post! This is up for grabs, feel free to start working on it :)
