### ISSUE TITLE
[Help Wanted] [PLT-3505] Add a spinner to Account Settings dialog after you've clicked the "Save" button

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6487]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3505)

Repro:

1) Go to Account Settings
2) Edit any of the settings
3) Click the "Save" button

Observed: No feedback to the user, to indicate that saving the setting is in progress, [against Mattermost UX guidelines](https://docs.mattermost.com/developer/fx-guidelines.html#input-validation).

Proposed Change:

After the user clicks the "Save" button, the button
 - text changes to "Saving ..."
 - a loading spinner is placed left of the "Saving..." text

See example below when System Console configuration settings are changed, where the "Save" button changes to "Saving Config ..." with a loading spinner on the left side.

![image](https://cloud.githubusercontent.com/assets/13119842/21661138/a3774c6a-d2a0-11e6-9f38-2e8b4f59b3ae.png)

Notes: 
 - We already have the SpinnerButton or system console SaveButton components (see above), and this ticket is to include them with the SettingItemMax component used in account settings.
 - See this PR which added a spinner to the login button: https://github.com/mattermost/platform/pull/5046

**Comment by letsila** [comment]
Hi all, I'd love to work on this issue!

**Comment by jasonblais** [comment]
Awesome, go for it @letsila! Thanks for your interest!

If you have any questions, don't hesitate to let us know.
