### ISSUE TITLE
[Help Wanted] [PLT-5100] Add members count for the direct messages list

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6521]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5100)

Add a count displaying the number of members that are displayed in the direct messages more modal. 

Note that this should include only the members shown in the list, and should update depending on the filter chosen, and if there's a search done for a member.

Mobile view:
![image](https://cloud.githubusercontent.com/assets/13119842/26597794/2dbab386-4541-11e7-81a1-f2e804ab90ad.png)

Desktop view:
![image](https://cloud.githubusercontent.com/assets/13119842/26597798/33746f56-4541-11e7-9c91-63902296b58e.png)

**Comment by jsfeb26** [comment]
I'll take a shot at this one

**Comment by lisakycho** [comment]
I'll take this one!
