### ISSUE TITLE
[Help Wanted] [PLT-6712] /remove [username] slash command: Remove a member from the channel.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6557]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6712)

/remove [username] slash command: Removes a member from the channel.

Notes:
1. /remove [username] will remove the specified user from the channel. You can remove more than one user at the same time.
2. The slash command accepts either @[username] or [username] as the parameter, similar to /msg
3. Permission to use this command in private channels is set by the [private channel management policy settings|https://docs.mattermost.com/administration/config-settings.html#policy]. If the user enters "/remove @[username]" without permissions, post this ephemeral message:

```
You do not have the appropriate permissions to remove the member.
```

4. If the user tries to use the command in a direct or group message channel, post this ephemeral message:

```
You can't remove someone from a direct message channel.
```

5. Autocomplete: 
```
/remove @[username]
Remove a member from the channel
```

----

See start of a PR here, which was subsequently closed: https://github.com/mattermost/mattermost-server/pull/7124

**Comment by cpanato** [comment]
I will work on that

**Comment by jasonblais** [comment]
You're great, thank you @cpanato! Please also see the notes in https://github.com/mattermost/platform/pull/6566#issuecomment-306052464 before working on this one, since I think some of those notes would apply here too.

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/issues/6557

**Comment by JensTimmerman** [comment]
can this command be restricted to team admins?

**Comment by jasonblais** [comment]
@JensTimmerman Excellent question! You can restrict who can remove members in public and private channels using the Mattermost permission system: https://docs.mattermost.com/deployment/advanced-permissions.html

It is currently available in Enterprise Edition E10 and E20.

Charities, open source projects and nonprofit organizations are eligible for a nonprofit Enterprise license at https://mattermost.com/nonprofit/
