### ISSUE TITLE
[Help Wanted] [PLT-6739] Convert theme color pickers to use react-color

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6595]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6739)

The theme color pickers in "components/user_settings/custom_theme_chooser.jsx" use a jQuery plugin. We should switch to using the react-color library, similar to how it's done in "webapp/components/admin_console/color_setting.jsx"

**Comment by Zapix** [comment]
Hi. I'm interesting to work under current issue. Will read your Developer's Guide and then will be ready to discuss current task.

**Comment by jasonblais** [comment]
Awesome, thanks @Zapix!

**Comment by Zapix** [comment]
@jasonblais, should I write unit tests for components?

**Comment by Zapix** [comment]
HI. I've added ColorInput component and use it in `component/user_settings/custom_thme_chooser.jsx` Also I think we could use ColorInput `components/admin_console/color_settings.jsx`. 
Updated package dev dependencies to run enzyme 3 with react 15.

**Comment by jasonblais** [comment]
Sweet! And yes, unit tests for components would be good but looks like you added them @Zapix :)

**Comment by jasonblais** [comment]
Thanks @Zapix!
