### ISSUE TITLE
[Help Wanted] [PLT-6730] Update GitLab omnibus to configure Mattermost via environment variables

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6611]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6730)

When Mattermost is deployed with GitLab omnibus settings saved in Mattermost System Console are overwritten by GitLab's gitlab.rb settings on upgrade. 

Moving GitLab omnibus to environment variables to write just the settings they need from gitlab.rb can resolve this. 

Note: This change would be done in the GitLab omnibus repo. Please make sure to post in the [GitLab issue](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2377) if you start working on this ticket.

**Comment by jasonblais** [comment]
In progress by GitLab: https://gitlab.com/gitlab-org/omnibus-gitlab/merge_requests/1877
