### ISSUE TITLE
Change at-mention autocomplete to prioritize entries where the username starts with the search string

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6699]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6871)

Change at-mention autocomplete to prioritize entries where the username starts with the search string

For the at mention autocomplete, it should sort users based on their username, but any user with their username starting with the search string should go first.

To give some context, if you search for "te" in the auto-complete right now on pre-release, you get the following results.

![image](https://user-images.githubusercontent.com/13119842/27355839-615ff0ee-55da-11e7-92fe-199570296972.png)

What you expect is this (those starting with "te" appear first, followed by other users in alphabetical order)

![image](https://user-images.githubusercontent.com/13119842/27355844-6436647e-55da-11e7-9acd-287e697fd08f.png)

NOTE: You can compare to how the sorting is done for channel switcher shortcut (CTRL+K) https://github.com/mattermost/platform/pull/6486

Also, here is a start of a PR to get you started: https://github.com/mattermost/mattermost-webapp/pull/15

**Comment by mikaoelitiana** [comment]
Should this be done on the back or the front side? I am willing to fix this.

**Comment by lfbrock** [comment]
@mikaoelitiana - front end should be fine for this, thanks!

**Comment by hanzei** [comment]
This seams to be fixed. @jasonblais Would you please confirm as you are the reporter of the ticket?

**Comment by jasonblais** [comment]
@hanzei Not yet fixed, attached screenshot is from Mattermost 5.10

![image](https://user-images.githubusercontent.com/13119842/56836635-eb3a2800-6845-11e9-91af-df0d40ee7bfa.png)

**Comment by pqzx** [comment]
Hi, can I work on this one?

**Comment by jasonblais** [comment]
@pqzx certainly, thank you for your interest!
