### ISSUE TITLE
[Help Wanted] [PLT-6896] Add paging to system console log viewer

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6724]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6896)

1. The system console is hard coded to page=0 items_per_page=60.  The setting isn't very useful at the moment.
2. Recommend adding proper paging to getting the servers or switch it to only load the last page.
3.  Also increase the max_per_page metics which defaults to 200.  For log paging this is really low.

Also revert https://github.com/mattermost/platform/pull/6697

**Comment by kaakaa** [comment]
Hi all!
I'm working on this issue, and I added paging to system log viewer on webapp.
(I'm working on [this branch](https://github.com/kaakaa/mattermost-webapp/commit/8a5d9d141a6b937e9e46e5904cde44ab87664d0b))

But item 3 still remains.
> 3. Also increase the max_per_page metics which defaults to 200. For log paging this is really low.

Now, even if I set large number (Such as 1000) to `perPage` from client, server overrides that value to `PER_PAGE_MAXIMUM` in params.go and responses less log lines (200 lines).
[mattermost\-server/params\.go at master · mattermost/mattermost\-server](https://github.com/mattermost/mattermost-server/blob/master/api4/params.go#L160)


For getting enough log lines from server, I think that it had better to create new url query parameter `logs_per_view` and new constants `LOGS_PER_PAGE_DEFAULT (=1000)` and `LOGS_PER_PAGE_MAXIMUM (=10000)` to `params.go` in mattermost-server.
[mattermost\-server/params\.go at master · mattermost/mattermost\-server](https://github.com/mattermost/mattermost-server/blob/master/api4/params.go#L160)
And it also needs to add `LOGS_PER_PAGE_DEFULT` to mattermost-redux.  [mattermost\-redux/admin\.js at master · mattermost/mattermost\-redux](https://github.com/mattermost/mattermost-redux/blob/master/src/actions/admin.js#L13)

What do you think about this proposal? Is there another good way?

**Comment by jwilander** [comment]
Hi @kaakaa,

I think it makes sense to add the new query parameter. I'd prefer going with `logs_per_page` to match the constant names but other than that the rest sounds good to me 👍 

When submitting your PR, could you submit another one to [mattermost/mattermost-api-reference](https://github.com/mattermost/mattermost-api-reference) to update API reference?

**Comment by kaakaa** [comment]
Thanks @jwilander! and sorry for my late replying.
Got it! I'll do that and send PR later. I try to update API reference!

> I'd prefer going with logs_per_page to match the constant names 

woops...since it's my mistakes, I'll fix the constant names. Thank you!
