### ISSUE TITLE
[Help Wanted] [PLT-6950] Add v4 endpoint for bulk selecting reactions based on provided post IDs

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6798]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6950)

**Summary:** Add a new endpoint for bulk selecting reactions to posts. 
**Problem it solves:** Prevents needing to make a separate request for each post to load all the reactions in a channel.
**HTTP Verb:** POST
**Endpoint:** /api/v4/posts/ids/reactions
**Request body:** A JSON array of post IDs to get reactions for.
**Response body:** A JSON object mapping post IDs to arrays of reactions. Posts with no reactions should have an empty array.
**Implementation help:** This will likely need new app and store functions. Also please see https://docs.mattermost.com/developer/api4.html for details on implementing APIv4 endpoints. Please add the handler in the api4/reaction.go file.

Per https://github.com/mattermost/platform/issues/6740

**Comment by uriklagnes** [comment]
Interested

**Comment by jasonblais** [comment]
Awesome, thanks @uriklagnes! Let us know if there are any questions

**Comment by theblueskies** [comment]
I'd like to pick this up. Is that cool @jasonblais ?

**Comment by jasonblais** [comment]
That would be great, thank you @theblueskies!

**Comment by jasonblais** [comment]
@theblueskies Let us know if you have any questions?

**Comment by theblueskies** [comment]
@jasonblais Yes, i'll ask on the api v4 channel on the mattermost developer channel.

**Comment by gupsho** [comment]
Hi, I would like to try this.

**Comment by gupsho** [comment]
Still working on this. Should have a PR out sometime this week.

**Comment by gupsho** [comment]
Hi @hanzei I was not able to work on it for last few weeks and probably wont be able to during the holiday season. Can pick it up again in the new year but feel free to assign to somebody if they can work on it sooner. Apologies for the delay.

**Comment by hanzei** [comment]
Hey @gupsho,

Thanks for the reply. I will make this ticket available to the public again. If no one pick its put, it would be great if you work on this once you got the time!

**Comment by pradeepmurugesan** [comment]
I can pick this one

**Comment by hanzei** [comment]
Nice. Thanks @pradeepmurugesan!
