### ISSUE TITLE
[Help Wanted] [PLT-7078] .m4r file does not have the generic audio thumbnail

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6895]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7078)

.m4r file does not have the generic audio thumbnail (see attached)

![image](https://user-images.githubusercontent.com/13119842/29231732-4bcccf5e-7eb6-11e7-8a46-12d0c7390448.png)

**Comment by mikaoelitiana** [comment]
I am willing to work on this one but I se there is some discussion yet on the jira ticket. What should I do?

**Comment by jasonblais** [comment]
Good question! I've queued the ticket back to triage, I'll let you know on Thursday!

Thanks for your interest! :)

**Comment by jasonblais** [comment]
Hey @mikaoelitiana, let us know if you have any questions?

**Comment by cherealnice** [comment]
@jasonblais I can take a look at this if no one's claimed it yet

**Comment by jasonblais** [comment]
That would be great, thank you @cherealnice!

**Comment by cherealnice** [comment]
https://github.com/mattermost/mattermost-webapp/pull/122

Change was to the web app, unless I missed something.  Couldn't get tests to run on the web app, let me know if I should add a test here.

**Comment by jasonblais** [comment]
Thanks @cherealnice!
