### ISSUE TITLE
[Help Wanted] [PLT-7111] Slash command for creating and messaging a group

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6932]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7111)

Add a new command `/groupmsg`

1. Format for sending a group message: `/groupmsg @[username1],@[username2],@[username3] [message]`
   - Example: `/groupmsg @eric,@lindsay,@jason,@asaad this is my message`
   - Example: `/groupmsg @eric, lindsay ,jason , @asaad this is my message`

2. Format notes: 
  - Accepts spaces after or before the commas when listing usernames
  - Usernames do not have to contain the '@' character
  - The first word without a preceding comma is the first word of the message
  - The command does not have to contain a message (If not it'll just open or create the group but not post)

3. System error message if add more than 7 people in the command: "Group messages are limited to a maximum of 7 users."

4. Similar to current behaviour, the system error message if one or more of the users cannot be found on the system: 
   - `We couldn't find the user: @username`
   - `We couldn't find the users: @username, @username2, @username3`

5. Autocomplete hint:
```
/groupmsg @[username1],@[username2] 'message'
Sends a Group Message to the specified users
```

**Comment by jespino** [comment]
I'm working on it :)

**Comment by jasonblais** [comment]
Sweet, thanks @jespino! 👍
