### ISSUE TITLE
[Help Wanted] [PLT-6024] Ability to add multiple users to a channel from the "Add Members" Modal

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6996]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6024)

Standardize the "Add New Members to [Channel_Name]" modal to look and behave the same as the "Add New Members To [Team_Name] Team". This includes:

1. The ability to add up to 20 members at a time into the input box before clicking "Add"
2. The ability to use the up/down arrow keys to change the selected user in the list, ENTER adds the user to the input box.

![image](https://user-images.githubusercontent.com/13119842/31029502-eaddf07a-a51f-11e7-971e-7ad9ad48e6f9.png)

Note: To test the expected behavior, go to the Main Menu > Add Members to Team.

**Comment by R-Wang97** [comment]
I can try taking a look at this!

**Comment by jasonblais** [comment]
Thanks @R-Wang97!
