### ISSUE TITLE
[Help Wanted] [PLT-7228] Running Mattermost in Franz causes errors in the logs

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7046]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7228)

Running Mattermost in Franz (http://meetfranz.com/) causes errors in the logs (Franz runs on an older version of Firefox)

Guessing TypeError: Notification.requestPermission is an unsupported browser.

Seeing a bunch of errors for 
```
[2017/07/24 22:01:27 UTC] [EROR] /api/v3/general/log_client:client code=0 rid=XXXXXXX uid=XXXXXXX ip=0.0.0.0 msg: Uncaught TypeError: Notification.requestPermission is not a function row: 1 col: 173353 stack: TypeError: Notification.requestPermission is not a function url: https://pre-release.mattermost.com/static/main.5f76f4e6af1bfa5696c4.js [details: ]
```

**Comment by jasonblais** [comment]
hey @adlk,

We noticed that running Mattermost in Franz causes errors in the logs as noted above.

Wondering if you're aware of what might be causing them?

**Comment by jasonblais** [comment]
https://github.com/mattermost/platform/pull/7273 has cleared the errors.
