### ISSUE TITLE
[Help Wanted] [PLT-6303] Mouse cursor should change to a "hand selector" when hovering over paperclip icon to upload a file

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7115]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6303)

Repro: Hover over paperclip in message input box
Expected: Mouse cursor changes to a hand selector
Observed: Mouse cursor doesn't change.

**Comment by Whiteaj36** [comment]
I can take this one!

**Comment by jasonblais** [comment]
Thanks @Whiteaj36! If you have any questions, don't hesitate to let us know!

**Comment by sudheerDev** [comment]
@jasonblais I cannot replicate this. Mouse cursor does change to hand selector. I can take this up. Let me know if I am missing something

**Comment by jasonblais** [comment]
@sudheerDev Looks like it's fixed now. The textbox was redesigned in v4.2 and I suspect this got fixed at the same time.

Will close. Thanks @sudheerDev :)
