### ISSUE TITLE
[Help Wanted] [PLT-539] Update incoming webhooks to accept multipart/form-data content type such as that supplied by curl -F

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7172]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-539)

Update incoming webhooks to accept multipart/form-data content type such as that supplied by curl -F

**Comment by cpanato** [comment]
@esethna there is any test case to be able to test that? how can I check if the fix are correct?

**Comment by jwilander** [comment]
@cpanato this is essentially adding support to incoming webhooks to accept the Content-Type [multipart/form-data](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2)

**Comment by cpanato** [comment]
thanks @jwilander 
should I look into here? `HandleIncomingWebhook` in the `webhook.go` ?

**Comment by jwilander** [comment]
Probably in `incomingWebhook` in `api4/webhook.go` (see how we're handling "application/x-www-form-urlencoded" already)

**Comment by cpanato** [comment]
on it 😄

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-server/pull/7873
