### ISSUE TITLE
Mattermost unusably slow if a team has a channel with 1 million posts

### ISSUE THREAD

**Issue by j-p-k** [mattermost/mattermost-server#7180]
#### Summary

Mattermost uses queries on the Post table, which require loading all Post of a given channel. 

### Details:

Mattermost 4.0.3 EE
MySQL 5.7.16 on Amazon RDS

Mattermost frequently performs queries of the form

1. SELECT Id, UpdateAt FROM Posts WHERE ChannelId = ? ORDER BY UpdateAt DESC LIMIT 1
2. SELECT * FROM Posts WHERE ChannelId = ? AND DeleteAt = 0 ORDER BY CreateAt DESC LIMIT ? OFFSET ?

While Mattermost has create an index on the ChannelId field, no combined index on ChannelId and UpdateAt exists. This is inefficient in MySQL.

#### Possible fixes

1. Create index on (ChannelId, UpdateAt)
2. Create index in (ChannelId, DeleteAt, CreatedAt)

**Comment by jasonblais** [comment]
Hey @j-p-k, terrible sorry for the delay on this. Have reached out to our developers and we'll get back to you shortly.

Really appreciate you bringing this to our attention!

**Comment by hmhealey** [comment]
Hi @j-p-k,

Do you have any benchmarks that would demonstrate a speedup by doing this? We're interested in any performance improvements we could make, but we'd prefer to know what effects a change like this would have before implementing it

**Comment by lindy65** [comment]
Hi @j-p-k,

Circling back to see whether your issue is resolved?

**Comment by lindy65** [comment]
Hi @j-p-k, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
