### ISSUE TITLE
[Help Wanted] Migrate edit_post_modal.jsx to be pure and use Redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7236]
If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/edit_post_modal.jsx`](https://github.com/mattermost/platform/blob/master/webapp/components/edit_post_modal.jsx) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://grundleborg.github.io/posts/react-component-testing-in-mattermost/). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**Comment by jespino** [comment]
I'm working on it.

**Comment by jespino** [comment]
As part of this, I'm working on migrate to mattermost-redux the HistoryStore and the BrowserStore (the second one using the approach to convert it to a normal actions+reducer, and then use redux-offline to store the data in the localStorage/sessionStorage).

**Comment by jasonblais** [comment]
Thanks @jespino!!

**Comment by jespino** [comment]
Yes, is not complete yet. I have to migrate the BrowserStore and finally migrate the component. I've been a little busy this wee so I couldn't advance too much this week.

**Comment by jasonblais** [comment]
No worries! We're participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com), so your contribution will count towards the event if you submit in October ;)

**Comment by jespino** [comment]
I hope so :)
