### ISSUE TITLE
[Help Wanted] Migrate sidebar_right to be pure and use Redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7237]
If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/sidebar_right`](https://github.com/mattermost/platform/blob/master/webapp/components/sidebar_right) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://grundleborg.github.io/posts/react-component-testing-in-mattermost/). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**NOTE**: This migration will be very involved and more complicated than other [Redux migration tickets](https://github.com/mattermost/platform/labels/Redux). There are a lot of Flux stores being use to populate the state which will now need to be populated by Redux instead.

**Comment by Zapix** [comment]
I think I've got enough skills to work on current issue.

**Comment by jasonblais** [comment]
Sweet, thanks @Zapix!

**Comment by Zapix** [comment]
I've looked through sidebar_right component. Am I right that before this issue would be solved, SearchStore should be moved to redux? Issue: #7489

**Comment by jwilander** [comment]
Yes, you could probably get through this with some hacks without migrating the search store but it'll be much cleaner and simpler if you migrate/refactor the search store first

**Comment by Zapix** [comment]
@jwilander ok. thank you

**Comment by jwilander** [comment]
Yes, I think we can close this ticket. There is some other final redux migration going on but this ticket is close enough and the last usages you mention should be covered shortly
