### ISSUE TITLE
[Help Wanted] [PLT-5436] Render channel links in the channel header

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7257]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5436)

Repro:
1) Click a channel name
2) From the drop down menu, select "Edit Channel Header"
3) Paste the following: ~town-square

Observed: Header rendered as ~town-square
![image](https://user-images.githubusercontent.com/13119842/33341402-e4a84730-d44c-11e7-8068-6f89ecaf1e91.png)

Expected: Header rendered as ~Town Square, which works as a channel link.
![image](https://user-images.githubusercontent.com/13119842/33341543-455cbd9a-d44d-11e7-9b10-c1df496b9e8b.png)

Here's start of a PR to help you get started: https://github.com/mattermost/platform/pull/5334

**Comment by deveshjadon98** [comment]
working on it

**Comment by panditsavitags** [comment]
@jasonblais ,
Please elaborate what needs to be fixed.

My understanding: onClick of header should redirect to that particular channel.

**Comment by jasonblais** [comment]
@panditsavitags Attached two screenshots, let me know if that helps? Clicking `~Town Square` in the expected case should redirect the user to the particular channel.

**Comment by jasonblais** [comment]
Big thanks for your interest helping with this ticket by the way :)

**Comment by panditsavitags** [comment]
@jasonblais , What if there are multiple channel names in channel description ? Or only one channel name is allowed ?

**Comment by jasonblais** [comment]
@panditsavitags They would render similarly to a post, such as:

![image](https://user-images.githubusercontent.com/13119842/33432441-ec868d86-d5a5-11e7-9eb2-0b2fd9ad8ce9.png)

**Comment by panditsavitags** [comment]
@jasonblais , as of now the overlay after the click on the channel link shows the list of links again. So the should overlay text be channel links again?

**Comment by jasonblais** [comment]
Hey @panditsavitags! Do you mean the autocomplete that shows up after typing `~`?

![image](https://user-images.githubusercontent.com/13119842/34488456-98a3a6ac-efa6-11e7-92f1-911f2ae112ff.png)

If so, that should be the same for the channel header.

PS: Sorry for the delay, was out of office

**Comment by jasonblais** [comment]
@panditsavitags Nevermind, looks like this was already covered in the PR. Nice work!

**Comment by jasonblais** [comment]
Thanks @panditsavitags :)
