### ISSUE TITLE
[Help Wanted] [PLT-7387] Mattermost-Kubernetes: Add jobserver instances to cluster

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7331]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7387)

The goal of the Kubernetes repo at https://github.com/mattermost/mattermost-kubernetes has 2 objectives.
1) An easy to setup highly available reference implementation for running the load tests.
2) The longer term goal is a highly available production ready implementation.

The purpose of this ticket is to add an additional role to the `mattermost-app` container so that it can also run instances of the jobserver, and make the number of jobserver instances to run in the cluster configurable from 0 upwards. When jobservers are included in the cluster, the app servers should be configured to not run jobs.

**Comment by dlahn** [comment]
I'll take this one.

**Comment by jasonblais** [comment]
Great, thanks @dlahn !

**Comment by dlahn** [comment]
PR: https://github.com/mattermost/mattermost-kubernetes/pull/11
