### ISSUE TITLE
[Help Wanted] [PLT-7508] System Console: Setting to disable the channel wide mention confirmation modal

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7335]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7508)

Add a system console setting to disable the "Confirm sending notifications to entire channel" modal.

Below the setting "Max Notifications Per Channel" in System Console > General > Users and Teams add the following setting:

**Show @channel and @all confirmation dialog:**  [x] true   [  ] false
- Help text: "When true, users will be prompted to confirm when posting @channel and @all in channels with over five members. When false, no confirmation is required."
- Default value: true.

**Comment by jespino** [comment]
I'm working on it

**Comment by jasonblais** [comment]
Awesome, thanks @jespino!

**Comment by jespino** [comment]
I have added the 2 PR needed (one in webapp and one in server)

**Comment by jasonblais** [comment]
Sweet, great work!

**Comment by jespino** [comment]
I think this issue is ready to be closed (the 2 PR are merged) :)

**Comment by jasonblais** [comment]
Indeed. Thanks @jespino! :)
