### ISSUE TITLE
[Help Wanted] [PLT-7500] Include emojis with alternate skin tones

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7337]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7500)

Include emoji images with alternate skin tones.

[This bug ticket](https://mattermost.atlassian.net/browse/PLT-7339) is a result of using non-yellow emoji skin tone via the mobile app and is resolved by adding images of emojis with alternate skin tones.

For reference, when a user posts an emoji with an alternate skin tone, it shows up either as the unicode emoji in the default font if one exists, or as an empty box as other missing characters do. For example, here's how they appear in Chrome and IE11 on Windows 10

![image](https://user-images.githubusercontent.com/13119842/30034757-79d3a648-9171-11e7-9896-af5b582b73b3.png)

Note: Don't show the alternative skin tones in emoji picker or emoji autocomplete, simply include the images for them.

**Comment by mkraft** [comment]
In my tests this works correctly in macOS 10.13 in the following browsers...

Chrome 61.0.3163.100:
<img width="1440" alt="mac_chrome_61 0 3163 100" src="https://user-images.githubusercontent.com/1149597/31442881-cb2aabd4-ae65-11e7-9027-89c7a97c1587.png">

Safari 11.0:
<img width="1440" alt="mac_safari_11 0" src="https://user-images.githubusercontent.com/1149597/31442883-cb8627f2-ae65-11e7-8081-b5f0fdb769f7.png">

Firefox 56.0.1:
<img width="1440" alt="mac_firefox_56 0 1" src="https://user-images.githubusercontent.com/1149597/31442882-cb390896-ae65-11e7-8b73-4ab8c0cd5c4c.png">

... is this currently only a reported issue on Windows?

**Comment by jasonblais** [comment]
It reproduced on Mac desktop app a couple of months ago, and I believe on Mac Chrome as well.

I'll ask @lindy65 to see if it still reproduces and maybe share a link to the post on pre-release.mattermost.com

**Comment by hmhealey** [comment]
I think it may still affect Mac, but it isn't as obvious since we use the Apple emoji set in the app and the emojis provided by the OS/browser match ours. If you post a yellow version of one of those emojis next to the ones you have, they'll likely appear with slightly different positioning and size.

**Comment by mkraft** [comment]
@hmhealey Yes you're right.

Input:
![simulator screen shot - iphone 6 - 2017-10-11 at 10 10 25](https://user-images.githubusercontent.com/1149597/31445655-768713c2-ae6c-11e7-8fdc-9b7b4805d6b5.png)

Ouput macOS Chrome 61.0.3163.100:
<img width="231" alt="screen shot 2017-10-11 at 10 10 10 am 1" src="https://user-images.githubusercontent.com/1149597/31445715-9f0496da-ae6c-11e7-9f62-00a7aa1ed4fc.png">

**Comment by mkraft** [comment]
If we're going to keep using emoji images (rather than native support) maybe we should switch to a CDN for this purpose, a quick Google search services like this:

https://cdnjs.cloudflare.com/ajax/libs/emojione/2.2.7/assets/svg/1f443-1f3fb.svg
https://cdnjs.cloudflare.com/ajax/libs/emojione/2.2.7/assets/svg/1f443-1f3ff.svg

Thoughts?

**Comment by mkraft** [comment]
I'll take this one.

**Comment by jasonblais** [comment]
Awesome, thanks @mkraft!
