### ISSUE TITLE
Channel crashes when pasting certain text

### ISSUE THREAD

**Issue by Kastenfrosch2** [mattermost/mattermost-server#7341]
#### Summary
When I post a certain text into a channel, the channel crashes

#### Steps to reproduce
post the following text into any channel
*[edited]*

#### Expected behavior
The text is displayed

**Comment by lindy65** [comment]
Hi @Kastenfrosch2,

Thank you for your feedback,

Could you share which version of Mattermost you are using and whether you are experiencing this on the Desktop App or in a browser?  If browser, which browser are you using?

**Comment by jairbubbles** [comment]
@lindy65 We're using version 4.1.

Regarding the browser, I'll let @Kastenfrosch2 answer. I didn't test myself I was too afraid to corrupt my channels :smile:

**Comment by Kastenfrosch2** [comment]
I pasted the text with Firefox 54.0.1 (32-bit),
The channels are freezed also in other browsers (tested with chromium)

**Comment by lindy65** [comment]
Thanks @jairbubbles and @Kastenfrosch2 

I'm a little hesitant to test this on our servers so I'll ask one of our devs to test it locally in case it breaks something ;)

I'll post back here once I have feedback from them.

**Comment by lfbrock** [comment]
Thanks @Kastenfrosch2 & @jairbubbles, we're looking into this issue. Just a note - for anyone encountering this issue, try going into Account Settings > Advanced > Post Formatting and turn off the post formatting to see if you can access the channel. 

You should then be able to delete the post causing the issues, and access the channel normally again. 

<img width="823" alt="screenshot 2017-09-06 09 55 31" src="https://user-images.githubusercontent.com/9354841/30115811-ca10b618-92e9-11e7-81c6-c489ca4ae0f2.png">

**Comment by jasonblais** [comment]
@Kastenfrosch2 @jairbubbles We have created a ticket and plan to fix the issue for Mattermost v4.2.

Let us know if the above workaround from @lfbrock helps resolve the issue in the meantime.

**Comment by Kastenfrosch2** [comment]
@lfbrock @jasonblais Thanks for the workaround - it helped to recover the frozen channels 👍

**Comment by lindy65** [comment]
Thanks, I'll close this issue off for now as it's fixed with v4.2 releasing on September, 16th.  You can download the latest version [here](.mattermost.com/download/) after the 16th.
