### ISSUE TITLE
[Help Wanted] [PLT-7526] "More Channels" modal should not remember the page number when displaying search results

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7344]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7526)

#### Summary
The **More Channels** modal should not remember the page number when displaying search results.

#### Steps to reproduce
1. Click the **More...** button under **Public Channels**
2. Ensure that there are enough channels to cause the **Next** button to appear (create additional channels if necessary). Find a channel that isn't on the first page of channels (say **Channel A**)
3. Click **Next** to move to the second page of channels
4. Ensure that you aren't on the first page of channels, and then search for **Channel A**

#### Expected behavior
The expected behaviour is that **Channel A** appears in the first page of search results. There also should only be 1 page of results (if only 1 page matches **Channel A**)

![capture](https://user-images.githubusercontent.com/6836385/29954822-7b361b72-8e8f-11e7-9010-1c066e1f59b7.PNG)

#### Observed behavior (that appears unintentional) 
The modal seems to remember the position at **Step 3**.

![capture](https://user-images.githubusercontent.com/6836385/29954755-fddf989c-8e8e-11e7-83aa-7338a52961d1.PNG)

**Comment by R-Wang97** [comment]
I can take a look at this!
