### ISSUE TITLE
Mattermost 4.2

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7346]
This is a meta issue for v4.2 release updates.

You can find key dates for v4.2 release below, with links to testing servers, release candidate and changelog added retrospectively.

Dates are tentative and subject to change.

### September 5th (T-8): Code Complete

Release candidate is cut. After this date, only bugs can be committed to the release branch.

The following information will be updated after release candidate is cut:
- Download link to release candidate
- Testing server
- Changelog

### September 13 (T-2): Release Build Cut

The final release is cut.

### September 16 (T-0): Release Day

Mattermost v4.2 is released.

If an urgent and important issue needs to be addressed between major releases, a patch release (e.g. 4.2.1) may be created.

**Comment by jasonblais** [comment]
### v4.2.0 RC1 is cut

Test server: http://rctesting.reddogsofwar.com/
Download link: `https://releases.mattermost.com/4.0.2-rc1/mattermost-4.0.2-rc1-linux-amd64.tar.gz`

### Changelog

Changelog draft can be found here: https://github.com/mattermost/docs/blob/8b41b093006983f168cc781f97575dd303d009c5/source/administration/changelog.md#release-v420

### Approved fixes for RC2

**Comment by Twilek-de** [comment]
Download link is wrong!! Points to an old version.

**Comment by Hanzei** [comment]
The correct link is  https://releases.mattermost.com/4.2.0-rc1/mattermost-4.2.0-rc1-linux-amd64.tar.gz

**Comment by jasonblais** [comment]
@Twilek-de Sorry, fat fingers, thanks @Hanzei for the link

**Comment by jasonblais** [comment]
### v4.2.0 RC2 is cut

Test server: http://rctesting.reddogsofwar.com/
Download link: `https://releases.mattermost.com/4.2.0-rc2/mattermost-4.2.0-rc2-linux-amd64.tar.gz`

**Open tickets queued for 4.2**
1. [Email template sanitization printing warnings](https://mattermost.atlassian.net/browse/PLT-7563)
2. [Custom profile pictures not always displayed](https://mattermost.atlassian.net/browse/PLT-7558)
3. [Fix TestComplianceExportDirectMessages failing for postgres](https://mattermost.atlassian.net/browse/PLT-7556)
4. [Custom slash command using GET not returning expected response](https://mattermost.atlassian.net/browse/PLT-7553)
9. [Fix Enterprise build](https://github.com/mattermost/mattermost-server/pull/7393)

**Comment by jasonblais** [comment]
### v4.2.0 RC3 is cut

Test server: http://rctesting.reddogsofwar.com/
Download link: `https://releases.mattermost.com/4.2.0-rc3/mattermost-4.2.0-rc3-linux-amd64.tar.gz`

#### Approved fixes for RC4
1. Final translations PR

**Comment by jasonblais** [comment]
v4.2.0 is now cut and available here: https://releases.mattermost.com/4.2.0/mattermost-4.2.0-linux-amd64.tar.gz
