### ISSUE TITLE
Signin/login request shows my password in debugging tool like firebug.

### ISSUE THREAD

**Issue by Snehal1112** [mattermost/mattermost-server#7374]
#### Summary
while login in mattermost login request show password in debugging tool like firebug. 
#### Steps to reproduce
- install firebug or any other debugging tool
- try to login in mattermost 
- check that request in debugging tool you can see the password in text.
#### Expected behavior
password should be encrypted before sending login request to server.

**Comment by prixone** [comment]
AFAIK that will be the same for pretty much ANY website, even Hotmail and Google, you will be able to view your password using debugging tools.

If you are worried about some one intercepting the request, AKA MITM attack, even with SSL you would still suffer from it, you would need a combination of SSL with HPKP.

If you are worried about malicious code reading the password, then well that is even worst as the machine in question, would be infect in this case, and they could grab the password from before its hashed.

Further in, hashing is a one-way thing, so the server will not know the actual user password(per say) but anyone reading the request would still be able to use that hash as your password directly.

Here is a good article on that https://security.stackexchange.com/a/100961/1786

Maybe I am missing your point here, so if you could go a bit more in detail I would appreciate.

**Comment by Snehal1112** [comment]
@prixone i am totally agree with you about SSL, hashed password etc. stuffed but here problem is someone can get my password easily if debugger tool is already opened while login.

why login in google you can't able to see your password in plain text. also they are doing something very interesting, they clear the request history from debugging tools after getting login success response.

i think we could use this simple technics. 

what you think???

other than mattermost architecture is really impressive and awesome. great work .. :)

**Comment by prixone** [comment]
> while login in google you can't able to see your password in plain text. also they are doing something very interesting, they clear the request history from debugging tools after getting login success response.

Yes, you can, you are probably just not looking at the right request, but I can clearly see my password using firebug for both google and hotmail.

For someone to get your password using a debugger tool your machine needs at the very least to be infected or that person would required physical access to it,
