### ISSUE TITLE
Not overwrite config.json when upgrading

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost-server#7397]
I don´t know wether it would be a good idea to not put a config.json in the distribution archives but something like config.json-dist instead. It has happened to me twice now that I accidently overwrote my config when upgrading because I forgot to copy the original first and move the directory. Secondly it would make it easier to compare your own config with the distribution on to spot changes.

**Comment by towolf** [comment]
I've worked around this by changed the path to my own config file in the `mattermost.service` systemd unit:

`ExecStart=/opt/mattermost/bin/platform --disableconfigwatch --config foo-config.json`

Now `foo-config.json` won't be overwritten, and I can merge with upstream changes to `config.json`.

**Comment by Twilek-de** [comment]
Awesome, that´s a really good idea!

**Comment by lindy65** [comment]
Hi @Twilek-de and @towolf 

Thank you for your feedback,

From our devs, the solution seems to be to make sure to follow the upgrade steps and copy your config.json out and back in when upgrading.
