### ISSUE TITLE
Mattermost v4 HTTP 400 does not return useful response

### ISSUE THREAD

**Issue by jkae** [mattermost/mattermost-server#7403]
#### Summary
`/api/v4/users` POST (alongside most other routes) results in 400 error when using JSON format outlined in API documentation, with message simply being `Bad Request`.

#### Steps to reproduce
1. Mattermost 4.1.0
2. User exists: test@test.com / testadmin / password
3. Create JSON `{"email":"test@test.com", "username":"testadmin", "password":"password"}`
4. POST JSON to `/api/v4/users`

#### Expected behavior
I would expect this to fail, as it does, but I also expect a response message that indicates the failure reason. In the case of lacking a useful message I would expect a different response code, such as `409: Conflict`.

`400: Bad Request` indicates to me that my JSON formatting is incorrect, or I'm sending a malformed request. The Mattermost API documentation indicates that a 400 is returned when there are invalid/missing parameters in the URL or request body, not necessarily conflicting data.

**Comment by prixone** [comment]
Are you properly authenticating to the API and passing the token on the create request? perhaps the bad request comes from the token missing?

Also did u check the log file of mattermost? It usually contains additional useful information.

**Comment by lindy65** [comment]
Hi @jkae 

Please let us know whether your issue is resolved with `prixone's` help above...  If not, feel free to re-open the issue and we'll try to troubleshoot further :)

**Comment by jkae** [comment]
@prixone No, I did not get that with my response for some reason.

My suggestion is simply that some of the more helpful status codes be implemented. I know *why* a 400 would be returned in this case, but if I'm creating accounts programmatically I don't want to have to match strings to figure out how I should handle the same error that could occur for different reasons.

**Comment by prixone** [comment]
@jkae you don''t need to match strings in the JSON response you also have a status code with is an int.
