### ISSUE TITLE
mattermost markdown prepends http:// to URI schemes with digits

### ISSUE THREAD

**Issue by ryantm** [mattermost/mattermost-server#7405]
#### Summary
mattermost markdown prepends http: to valid URIs. For example:

```
[link text](myproto1:blah)
```
renders a link with "http://myproto1:blah" for the href attribute.

Since the markdown implementation is targeting gitlab compatibility, I checked and it does not prepend this markdown with "http://".

The mattermost markdown renderer handles URI schemes without digits correctly. I did not check ones with the other valid symbols. For reference, the URI scheme BNF is available here: https://tools.ietf.org/html/rfc3986#appendix-A

#### Steps to reproduce
Enable markdown, look at the rendering for "[link text](myproto1:blah)"

#### Expected behavior
The rendered href attribute should be "myproto1:blah"

#### Observed behavior (that appears unintentional) 
The rendered href attribute is "http://myproto1:blah"

**Comment by prixone** [comment]
https://github.com/mattermost/mattermost-webapp/pull/16

Should fix the above for both cases:

``myproto1:blah`` and ``[link text](myproto1:blah)``

**Comment by lindy65** [comment]
Hi @ryantm 

Please let us know whether you still experience the issue since the fix from `prixone` has been merged.

Thanks!

**Comment by prixone** [comment]
After it's merged ;)
