### ISSUE TITLE
Old messages are inaccessible by permalink

### ISSUE THREAD

**Issue by drmoose** [mattermost/mattermost-server#7437]
#### Summary
Clicking a link to jump to an old message in a popular channel hangs the client at "Loading..."

#### Steps to reproduce
Using MM server 4.1.0 backed by postgres (the "gitlab omnibus" version), on any client (tested on Electron and Firefox):
- Click a permalink (a url the form of `https://{domain}/{team}/pl/{post id}`) to a post written 6 months ago in a channel with >27k messages.

#### Expected behavior
- Message view jumps to that post.

#### Observed behavior (that appears unintentional) 
- The view hangs at "Loading..." seemingly indefinitely.

No error is logged anywhere that I can find. `gitlab-ctl tail mattermost` is empty. Nothing relevant is logged in the developer console. Running this postgres query:

```sql
SELECT count(*), sum(length(b.message)) 
  FROM posts a
  LEFT JOIN posts b ON b.createat > a.createat AND b.channelid=a.channelid 
  WHERE a.id=?;
```
returns immediately. There have been 14914 messages since the one we're currently interested in. 

#### Possible fixes
Unfortunately, since I can't seem to get logs, I have no idea what's happening behind the scenes. Potentially-relevant lines of code include [GetPermalinkPost](https://github.com/mattermost/mattermost-server/blob/master/app/post.go#L436) and its neighbors.

**Comment by lindy65** [comment]
Hi @drmoose,

Thank you for your feedback,

We have fixed this bug (ticket [here](https://mattermost.atlassian.net/browse/PLT-7416)) in v4.2 which will release on September 16th.

You can download the latest version [here](https://about.mattermost.com/download/).
