### ISSUE TITLE
ctrl + enter in mobile view does not send message

### ISSUE THREAD

**Issue by MufflerEU** [mattermost/mattermost-server#7439]
#### Summary
ctrl + enter in mobile view does not send message

#### Steps to reproduce
Enter mobile view (i.e by web panel in vivaldi) and write a message. Ctrl + enter does not send the message but double tab and enter does.

#### Expected behavior
ctrl + enter should work as in web view.

**Comment by lindy65** [comment]
Hi @MufflerEU,

Thank you for your feedback,

Could you share which version of Mattermost server you are using?  

I've tried to reproduce your issue on Win, Chrome from mobile view but CTRL+enter works for me.  I'm also not sure whether Vivaldi browser is supported.  You can check the software requirements [here](https://docs.mattermost.com/install/requirements.html#software-requirements).

**Comment by MufflerEU** [comment]
You are correct. I was way to fast on the trigger. Can't reproduce this in any other browser, just Vivaldis Web Panel. Sorry.

**Comment by lindy65** [comment]
No worries at all @MufflerEU :)
