### ISSUE TITLE
URLs containing IDN TLD and non-latin characters not clickable in the chat

### ISSUE THREAD

**Issue by kostich** [mattermost/mattermost-server#7441]
#### Summary
URLs containing IDN TLD and non-latin characters not clickable in the chat.

#### Steps to reproduce
Input in any channel/private message some URL containing IDN TLD and send it. The URL won't become "clickable". For example, send `https://гном.срб/Изашао-је-Гном-3-26/` or `https://гном.срб/%D0%98%D0%B7%D0%B0%D1%88%D0%B0%D0%BE-%D1%98%D0%B5-%D0%93%D0%BD%D0%BE%D0%BC-3-26/` to someone. The URL won't be clickable/detected as an URL.

#### Expected behavior
The URL should become clickable so anyone in the chat could open it without having to select and copy the whole URL.

#### Observed behavior (that appears unintentional) 
![2017-09-13 20-47-45](https://user-images.githubusercontent.com/4953862/30394994-18585fc0-98c5-11e7-8092-7b834a0e13a8.png)

**Comment by hmhealey** [comment]
Hi @kostich, thanks for the report. It looks like the URL gets cut off when any period in the URL is followed by a non-latin letter since it thinks that is supposed to be the end of a sentence. I've filed a Jira ticket if you'd like to track the issue [here](https://mattermost.atlassian.net/browse/PLT-7640).

**Comment by hmhealey** [comment]
Also, you can work around this issue in the meantime by posting your link using the `[link title](link)` format so in this case, yours would be `[link title](https://гном.срб/Изашао-је-Гном-3-26/)` which will render as [link title](https://гном.срб/Изашао-је-Гном-3-26/)

**Comment by kostich** [comment]
Great. Thanks for the tip and Jira ticket @hmhealey!

**Comment by lindy65** [comment]
Thanks @kostich 

I'll close this issue off for now and we can track via the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7640).
