### ISSUE TITLE
Slash integration "ephemeral" type attachments not showing up

### ISSUE THREAD

**Issue by guatedude2** [mattermost/mattermost-server#7453]
#### Summary
When adding a slash integration hook, and replying with an "ephemeral" response with an attachment and no "text" or blank "text" the attachment doesn't show up, but adding text does.

#### Steps to reproduce
Here's an example response of an integration attachment that won't show up:
```json
{
  "response_type": "ephemeral",
  "text": " ",
  "attachments": [
    {
      "text": "This is the attachment that doesn't show up."
    }
  ]
}
```

but adding a blank text makes the attachment appear:

```json
{
  "response_type": "ephemeral",
  "text": " ",
  "attachments": [
    {
      "text": "This is the attachment that shows up."
    }
  ]
}
```

#### Expected behavior
when the server responds with an attachment and no text, the attachment should show up as well.

#### Observed behavior (that appears unintentional) 
A blank entry in the chat from the bot.

#### Possible fixes
Possibly checking `app/command.go`  lines 50 - 59 in `CreateCommandPost()`. The checking the condition of the "text".

_tested with version 4.2.0_

**Comment by jasonblais** [comment]
@guatedude2 thanks for the report!

1) Just to confirm, if the following payload is sent by the slash command, the bot just sends a blank post?

```
{
  "response_type": "ephemeral",
  "attachments": [
    {
      "text": "This is the attachment that doesn't show up."
    }
  ]
}
```

2) Is the slash command posted in the center pane, or as a reply to an existing message?
3) What is your preferences set to in **Account Settings > Display > Message Display**? (Standard/Compact)

**Comment by seansackowitz** [comment]
1. I do not even get a blank message from the bot. The server acknowledges the slash command was successful, and had a full response (not blank), however nothing appears.
2. Center pane
3. Standard message display

**Comment by guatedude2** [comment]
Likewise for me

**Comment by ccbrown** [comment]
Looks like this has always been the behavior: https://github.com/mattermost/mattermost-server/pull/4999

As far as I can tell it wasn't intentional though. We can probably just remove that `if response.Text == "" { return ... }` block.

**Comment by ccbrown** [comment]
Yeah, removing that block seems to work fine. No adverse side-effects that I can see or think of. Put in a PR.

**Comment by lindy65** [comment]
Thanks @guatedude2 @seansackowitz @ccbrown 

I'll close this issue off for now then.
