### ISSUE TITLE
[Enhancement] New Line should go with STRG + ENTER

### ISSUE THREAD

**Issue by 001101** [mattermost/mattermost-server#7457]
Write messages using the text input box at the bottom of Mattermost. Press ENTER to send a message. Use SHIFT+ENTER to create a new line without sending a message.

-----------

It just should be STRG + ENTER as usual

greets

**Comment by lindy65** [comment]
Hi @001101,

Thank you for your feedback,

If I'm understanding your request properly, the feature available from Main Menu > Account Settings > Advanced > Send messages on CTRL+ENTER (on/off) is what you're looking for?

**Comment by 001101** [comment]
@lindy65 Are you a bot?? Please lern reading, i don't write chinese.

> [Enhancement] **New Line should go with STRG + ENTER**

**Comment by lindy65** [comment]
Hello @001101 

Must say, I'm a little offended by your message.  No, I'm not a bot, just someone trying to help.  Perhaps you should have mentioned you are using a German keyboard and that STRG = CTRL.

Obviously I totally misunderstood your message so I'll pass this on to our product team to see whether they can help you.

**Comment by 001101** [comment]
Ah okey I am sorry :-/

There are many other applications (Outlook, Skype, wire.com, zendesk) which used CTRL + ENTER to make a new line and it is good coding to keep such standards, so users does not need to remember any small keyboard shortcut change for any application, this just does not make sense, hope the team will change it soon, thank you very much :)

best wishes

**Comment by lindy65** [comment]
Hi @001101,

No worries, apology accepted ;)

It seems that what you're requesting is more a feature suggestion (requires code change).  Could we have your help opening a [feature suggestion](https://mattermost.uservoice.com/forums/306457-general) on our forum?  

Here, you and others can up-vote the suggestion up to 10 times.  The more popular a feature is, the more chance it has of making it into the product.

Thanks!

**Comment by 001101** [comment]
Unfortunately the Shift + Enter is really the standard for new line in most applications, so it should be :)

**Comment by MusikPolice** [comment]
Can we start over here? The waters have been a bit muddied, and I'm having a hard time following what's been requested. As I understand it, we all agree that SHIFT+ENTER currently adds a newline in the Mattermost text box, as opposed to ENTER, which sends the message. @001101 appears to be requesting that CTRL+ENTER

**Comment by 001101** [comment]
As I researched it appeared that in any other applications the SHIFT + ENTER is the accepted standard. But I have used several years also Steam to chat and there is the default STRG + ENTER, so I was thinking this is the standard, but i wasn't!

So please blame Valve for not stick to the standards!!

**Comment by MusikPolice** [comment]
Since we've come to an agreement, I'm going to close this issue for the time being. 

If you still feel strongly that this shortcut ought to be supported in Mattermost, consider submitting [a feature request](https://mattermost.uservoice.com/forums/306457-general). If others feel the same way, your request will be upvoted, and will have a better chance of being accepted into the project.
