### ISSUE TITLE
Link not opened from e-mail notification.

### ISSUE THREAD

**Issue by maxtar** [mattermost/mattermost-server#7458]
When user received notification about new message and click on link he can see loading message. And message not showing.
When user click to "Click here for going last message" opening all topic.

![default](https://user-images.githubusercontent.com/10290098/30537855-11428bfe-9c74-11e7-9013-5da932558a5f.png)

**Comment by lindy65** [comment]
Hello @maxtar 

Thank you for your feedback,

Could you tell me which version of Mattermost you are running?

v4.2 released on September 16th so perhaps try upgrading to the [latest version](https://about.mattermost.com/download/) to see if this fixes the issue for you.

**Comment by maxtar** [comment]
@lindy65 Thanx for answer. We have 4.1.0 version. Will trying upgrade.

**Comment by lindy65** [comment]
Thanks @maxtar 

Let us know if the issue still persists after you've upgraded.

**Comment by maxtar** [comment]
Yeap. problem has fixed in new version. Thanx!

**Comment by lindy65** [comment]
That's good to hear @maxtar !  I'll close this issue off then...
