### ISSUE TITLE
Updating interactive messages loses data and action buttons

### ISSUE THREAD

**Issue by seansackowitz** [mattermost/mattermost-server#7472]
#### Summary
When updating an interactive message, you cannot update the post, and maintain the action buttons, and other data is lost as well

#### Steps to reproduce
Have an integration server respond with an in_channel post that has interactive buttons, and then as a response to a user clicking the button, update the post.

```ruby
'{
    "response_type": "in_channel",
    "username": "%3$s",
    "icon_url": server_api_url + "/users/%4$s/image"
    "attachments": [{
        "title": "%2$s",
        "image_url": "%1$s",
        "actions": [{
            "name": "Next",
            "integration": {
                "url": server_url + "/next",
                "context": {
                    "request_text": "%2$s",
                    "user_name": "%3$s",
                    "user_id": "%4$s"
                }
            }
        }]
    }]
}' % [ request_hash['image_url'],
       request_hash['request_text'],
       request_hash['user_name'].capitalize,
       request_hash['user_id'] ]
```
As a response to `/next`, the server should update the message with altered information (in this case, image_url changes)
```ruby
'{
    "update": {
        "props": {
            "response_type": "in_channel",
            "username": "%3$s",
            "icon_url": server_api_url + "/users/%4$s/image",
            "attachments": [{
                "title": "%2$s",
                "image_url": "%1$s",
                "actions": [{
                    "name": "Next",
                    "integration": {
                        "url": server_url + "/next",
                        "context": {
                            "request_text": "%2$s",
                            "user_name": "%3$s",
                            "user_id": "%4$s"
                        }
                    }
                }]
            }]
        }
    } % [ request_hash['image_url'],
          request_hash['request_text'],
          request_hash['user_name'].capitalize,
          request_hash['user_id'] ]
}'
```

#### Expected behavior
I expect the post to be modified to reflect the message as if it was originally sent.

#### Observed behavior (that appears unintentional) 
An updated message does not change to fully reflect the updates requested. Actions do not appear, user icon_url gets replaced to the default image instead of the requested image.

**Comment by ccbrown** [comment]
Thanks. I've put in a PR for the fix.

**Comment by ccbrown** [comment]
Btw there's a separate ticket to improve icon behavior: https://mattermost.atlassian.net/browse/PLT-7631

**Comment by lindy65** [comment]
Thanks @ccbrown @seansackowitz 

I'll close this issue off for now and we can track icon behaviour via the above ticket.
