### ISSUE TITLE
Converting a channel to private/public doesn't work

### ISSUE THREAD

**Issue by tohn** [mattermost/mattermost-server#7476]
#### Summary
Contrary to the changelog of version 4.2.0 one cannot change a channel to private/public.

#### Steps to reproduce
Execute:
`./bin/platform channel modify [team]:[channel] --[public|private]`

#### Expected behavior
The channel should now be public/private.

#### Observed behavior (that appears unintentional) 
`Error: Feature requires an enterprise license. Please contact your system administrator about upgrading your enterprise license.`

#### Possible fixes
Maybe it was before only possible with the enterprise edition (or (still) is?), but then the documentation is misleading.

**Comment by bjoernr-de** [comment]
+1
Same here.

**Comment by grundleborg** [comment]
Thanks very much for the report. This was a bug and has been fixed for Mattermost Server 4.3, which will be released on 16th October.
