### ISSUE TITLE
Wordpress Pingback

### ISSUE THREAD

**Issue by dipuhasan** [mattermost/mattermost-server#7483]
**Edited**

**Comment by dipuhasan** [comment]
<?xml version="1.0"?>
<methodCall>
<methodName>wp.getUsersBlogs</methodName>
<params>
<param>
<value>
<string>admin</string>
</value>
</param>
<param>
<value>
<string>password</string>
</value>
</param>
</params>
</methodCall>


And no rate limit at checking username,password.

**Comment by jasonblais** [comment]
@dipuhasan: Please help report potential vulnerabilities via our Responsible Disclosure Policy process outlined herE: https://www.mattermost.org/responsible-disclosure-policy/
