### ISSUE TITLE
[Help Wanted] [PLT-7676] Refactor webapp search store and right hand sidebar view state

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7489]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7676)

The search store used by the webapp is really used for a conglomeration of different features:

- Storing search results when searching for posts
- Searching for recent mentions
- Displaying pinned posts for a channel
- Displaying flagged posts
- Partially controlling the view state of the right hand sidebar

It's grown organically into the mess it is now and it could really use some refactoring. My suggestion for how to do this is:

1. Create a webapp reducer/store for controlling the view state of the RHS. This should have all the information needed so that the RHS component knows what it should be displaying. For example what mode we're in (showing pins, showing flags, showing search results), and any extra information required by that mode to display content (what channel the pins are for, the search term produced the results, etc.)
2. The RHS component should then be refactored to take the state stored by the new reducer into it's props and render the state based on this
3. The webapp search store should then be demolished and the mattermost-redux search reducer should be used. Any other reducers used to store information lost by demolishing the webapp search store should be added to the appropriate mattermost-redux reducers

This will be an involved ticket. A good understanding of the webapp and mattermost-redux is recommended.

Ask @joram on pre-release.mattermost.com in the Redux channel if you need help or advice.

**Comment by Zapix** [comment]
I'll make this issue before #7237

**Comment by QuantumKing** [comment]
I'm working on this one
