### ISSUE TITLE
Slash character (/) not treated as a word separator during search

### ISSUE THREAD

**Issue by prateeksriv** [mattermost/mattermost-server#7491]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
If two words are separated by slash character (/) then they are no longer searchable.

#### Steps to reproduce
Version: 4.1.0
step 1: Create a post with the following text: `Alpha/Beta Gamma,Theta`
step 2: Search for `Gamma` from the search box. observation: The post is successfully found.
step 3: Search for `Beta` from the search box. observation: The post I just created is NOT found.
step 4: Search for `Alpha/Beta` from the search box. observation: The post created above is successfully found again.

#### Expected behavior
Slash is an important word separator, especially with Unix file paths. I should be able to find such paths in search. 
Or at least a setting needs to be provided to allow us to choose the behavior.

#### Observed behavior (that appears unintentional) 
As detailed in the reproduction steps above: I created a post and was not able to find it by the keyword just because there was a slash character `/` adjacent to it.

#### Possible fixes
Unfortunately I have no idea how to fix it.
I am submitting this ticket on behalf of my employer ( Enterprise license) because this issue is causing significant grief.

**Comment by lindy65** [comment]
Hi @prateeksriv 

Thank you for your feedback,

Elasticsearch, available with an enterprise licence, doesn't have this issue. However, it does seem to be present for SQL full-text search. I'm really not sure what, if anything, we can do about it in that case though, since I think the fulltext implementation of the SQL server dictates what the word boundaries are.

**Comment by jespino** [comment]
Looks like with MySQL works well, but with PostgreSQL fails. I will try to take a deeper look.

**Comment by tejaycar** [comment]
You might need to setup a custom collation for that column in order to get the desired word separators.

**Comment by jespino** [comment]
I'm not sure, but I think it can't be done through the collation. The proposals that I've seen are more oriented to preprocess the text before making the index, something like to_tsvector('english', translate(column, '/', ' ')) and we can do something similar in the to_tsquery.

I'm not sure is the cleaner and nicer approach, but I'll keep investigating it.

Other problem with this approach is that you can't search part of routes like "/usr/local" for example, will search any usr and local text, not "/usr/local" text.

**Comment by lindy65** [comment]
Thanks @prateeksriv @tejaycar @jespino 

I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7752) to investigate the issue.

**Comment by lindy65** [comment]
I'll close this issue off here and we can track it via the Jira ticket linked above.
