### ISSUE TITLE
[Help Wanted] [PLT-7396] Add the ability to revoke user sessions in System Console > Users

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7493]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7396)

Proposed changes:

1) Revoke sessions of a user

In System Console > Users

A) For dropdown on users list, add an option to “Revoke Sessions” below “Reset Password’. This lets an admin to revoke all sessions for a single user.

![image](https://user-images.githubusercontent.com/13119842/30709992-0cb28afc-9ed2-11e7-92cd-5ede1c17f686.png)

B) Clicking this option opens a popup, similar to the “Deactivate” popup menu attached below.
{code}
Title: Revoke sessions for {username}
Help text: This action revokes all sessions for {username}. They will be logged out from all devices. Are you sure you want to revoke all sessions for {username}?
Buttons:
 - Cancel: Closes the popup, takes no action.
 - Revoke Sessions: Revokes all user’s sessions immediately.
{code}

![image](https://user-images.githubusercontent.com/13119842/30709999-114ec1fc-9ed2-11e7-9d41-dc725e29b4cf.png)

2) Revoke sessions of all users in the system

In System Console > Users

A) To revoke all sessions in the system, add “Revoke All Sessions” button to the page. Useful if the admin suspects the system has been compromised and needs to neutralize the situation.

![image](https://user-images.githubusercontent.com/13119842/30710006-19129ddc-9ed2-11e7-914f-35a14a6c9d58.png)

B) Clicking this button opens a popup, similar to 1B above:
Title: Revoke all sessions in the system
Help text: This action revokes all sessions in the system. All users will be logged out from all devices. Are you sure you want to revoke all sessions?
Buttons:
 - Cancel: Closes the popup, takes no action.
 - Revoke Sessions: Revokes all user sessions immediately.

**Comment by rickbatka** [comment]
I'd like to take a swing at this, unless it's very urgent. It'll be my first contribution so I'm sure I'll have some friction, but I've already completed some of the work locally. 

I'd hope to submit a PR some time early next week.

**Comment by jasonblais** [comment]
That would be great @rickbatka! Let us know if you have any questions. Looking forward to the PR :)

**Comment by rickbatka** [comment]
I have some UX follow up questions:

1. In System Console > Users > User Actions Dropdown, should the "Revoke Sessions" option be available for the currently logged-in user? If so, we could:
    1. Immediately force the logout upon success (I think using forceLogoutIfNecessary)
    1. Display a modal and force logout either after they close it or after a short delay ("We are returning you to the login screen", or something along those lines).
    1. Revoke all sessions except for the active one, therefore not logging the current user out. This may be confusing - the user might expect to be logged out when they revoke their own sessions - so it may warrant some messaging that the operation succeeded.
1. Also in System Console > Users > User Actions Dropdown, after revoking sessions for any user, should we display any messaging? I think not, because setting a user inactive does not result in any messaging to the user (although it does have the effect of turning that user inactive, so in truth, some UX feedback is provided in that case). I could go either way on this.
1. In System Console -> Users -> "Revoke All Sessions" button: should the current user be included in that operation? If so, I assume I should apply the same logic as how we handle the current user above - do you agree?
    1. Also in "Revoke All Sessions", should there be any messaging that it was successful? If so, should it be similar / the same as what we use for individual users?

**Comment by jasonblais** [comment]
Hey @rickbatka 

1 - Propose we immediately force the logout. Otherwise I worry it will look as though the session weren't properly revoked.

(Also, if the admin wants to revoke his sessions, he'll likely go to the Account Settings rather than System Console)

2 - No feedback/messaging needed (for now at least). Similar to the note above, the user is logged out without messaging when their session exceeds the session length setting.

3 - Yes, I think it should include everyone including the System Admin (as that will revoke all of his/her sessions).

For messaging, were you thinking of something in the UI or in the logs? A server log message might be useful.

**Comment by rickbatka** [comment]
I was thinking of UI messaging, but if there's no precedent for it then I'm
perfectly happy to leave it out. Getting logged out (if you do it to
yourself) will be a form of UX feedback, anyway.

I'll look into the server logging. Thanks for the input!

**Comment by jasonblais** [comment]
@rickbatka, yeah I think no messaging is okay for now. We can always add it later if needed.

Huge thanks for your help working on this! It'll be a great improvement to have

**Comment by rickbatka** [comment]
I need some advice on the back end side of this.

Looking at the existing RevokeAllSessions() method in session.go, it will loop through a user's sessions and either delete the session or remove the access tokens, depending on whether or not it's an OAuth session. Additionally, it calls RevokeWebRtcToken() for every session, and ClearSessionCacheForUser() for every user - which removes the session cache keys (ClearSessionCacheForUserSkipClusterSend()) - and that, in turn, calls through to InvalidateWebConnSessionCacheForUser(), which gets us into invalidating users in the web hubs.

1. I'm not very clear on how the web hubs work yet. Is there a supported way to invalidate all users without going user by user, finding the web hub, and calling InvalidateUser() for each one?
1. I was thinking I would just write a second repo method to delete all sessions in the session table, delete all oauth records, and be done - but it seems like there is a little more going on than I once realized. Would it be acceptable to instead loop through all users and call RevokeAllSessions(userId), which in turn takes the appropriate action for every session? It has the drawback of needing to loop through all sessions in the system and do some work on each one, but this is probably a fairly rarely use feature so it might be worth the simplicity trade-off. 

The other option is for me to delete all sessions, delete all oauth tokens, revoke all users from all webhubs, and clear all session caches - am I missing anything? I also noticed the current session revoking logic "skips cluster send", and I don't know if that's the right thing to do here.

Thanks for the help, the back end got a little more complicated than I thought it would!

**Comment by jasonblais** [comment]
Thanks @rickbatka! 

Would you like to post your question in our [public Developers channel](https://pre-release.mattermost.com/core/channels/developers)?

Looks like you've already joined the channel and you'll more likely get a response there.

**Comment by rickbatka** [comment]
@jasonblais you can put this one back up for grabs. The back end touches more than web sessions.  This being the first MM task I grabbed, I haven't got a good enough grip on the project to test web hubs, clusters, websockets, oauth, user access tokens, etc. The guys over in the Developers channel are still hashing out how they want it to work.

If there's any value in it I can push my branch with the frontend; that part is done. Let me know if that would be useful.

**Comment by jasonblais** [comment]
@rickbatka Were you able to finish the first part (revoking an individual user session)? Seems like revoking all user sessions was posing difficulties, but I could split that part into a separate issue.

**Comment by rickbatka** [comment]
Oh, yes! I almost forgot - that part was easy. I’ll look at your
contribution docs and see about putting together a PR for just that piece.

**Comment by rickbatka** [comment]
Ok, 4 PRs should cover it. I made sure to add and run tests, i18n strings, and api documentation - let me know if there are any problems.

Thanks for your help! This was my first open source contribution. I learned a lot :)

https://github.com/mattermost/mattermost-server/pull/7623
https://github.com/mattermost/mattermost-redux/pull/267
https://github.com/mattermost/mattermost-webapp/pull/152
https://github.com/mattermost/mattermost-api-reference/pull/294

**Comment by jasonblais** [comment]
Excellent, thanks @rickbatka!

**Comment by jasonblais** [comment]
Re-opened the second part (revoking all user sessions) here: https://github.com/mattermost/mattermost-server/issues/7493

Thanks again @rickbatka for this :) Very excited to add it in the next release
