### ISSUE TITLE
[Help Wanted] [PLT-7395] Add the ability to search users by role in System Console > Users

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7494]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7395)

Proposed change:

Add a "Role" filter next to "Team" with the following options

 - "All Roles" (default, searches everyone)
 - "Inactive" (filters users who have been deactivated)
 - "User with Access Token Permission" (filters users who have permissions to generate an access token. This option is only shown if System Console > Integrations > Custom Integrations > Enable Personal Access Tokens is set to "true")
 - "System Admin" (filters users who are system admins)
 - "Member" (filters users who are members)

![image](https://user-images.githubusercontent.com/13119842/30709937-e953dcfa-9ed1-11e7-9fe1-5fc69594ec63.png)

**Comment by Zapix** [comment]
Hi. I've looked through api v4 for users and search. There isn't query param for filtering by role or another way to implement this. Should be api updated for this ticket?

**Comment by jasonblais** [comment]
@Zapix Excellent question. Looks like you're already signed up to https://pre-release.mattermost.com, would you like to post your question in the [APIv4 channel](https://pre-release.mattermost.com/core/channels/apiv4)?

(I would say yes, but a developer will be able to confirm it in the channel)

**Comment by jwilander** [comment]
Added Go label as this will require updates to the API for querying based on role

**Comment by jasonblais** [comment]
@Zapix If you're interested to learn Go or to add a new APIv4 endpoint, we have documentation here that guides you through the process (plus you're welcome to ask questions): https://docs.mattermost.com/developer/api4.html

However, feel free to pick another Hacktoberfest issue too if you'd prefer :)

**Comment by jwilander** [comment]
For more information, it will likely require a new database query or two, coresponding app layer functions and would be an addition to the `POST /api/v4/users/search` and `GET /api/v4/users` endpoints

**Comment by Zapix** [comment]
@jasonblais Thank you. I'll try to work on this issue on weekends I think.

**Comment by jasonblais** [comment]
@Zapix Let us know if you have any questions on this ticket?

**Comment by jkurian** [comment]
Hey! Is this issue still open / valid?

**Comment by jasonblais** [comment]
It is! Would you be interested helping with this improvement @jkurian?

**Comment by jkurian** [comment]
Yes! I would love to take this ticket.

**Comment by jasonblais** [comment]
Hey @jkurian - just checking how things are going and if you have any questions?

**Comment by jkurian** [comment]
Hi @jasonblais, sorry I have been swamped with work and I don't see it clearing up anytime soon. Maybe a good idea to open this back up to the public?

**Comment by jasonblais** [comment]
Thanks @jkurian! Sounds good, we've added the "Up For Grabs" label back.

**Comment by pradeepmurugesan** [comment]
I would take this one, if its still valid

**Comment by jasonblais** [comment]
That would be great! It is still open.

Thank you @pradeepmurugesan 🎉

**Comment by pradeepmurugesan** [comment]
Waiting for clarification - https://pre-release.mattermost.com/core/pl/y765b8tdaffbucqtxg7mw6tm7h
