### ISSUE TITLE
Users can't deactivate their own account

### ISSUE THREAD

**Issue by mathias-b** [mattermost/mattermost-server#7495]
Hello,

#### Summary
Users aren't enabled to deactivate their own account. It's a major privacy issue.

#### Expected behaviour
Users should be able to deactivate their own account, for exemple browsing "Account Settings" > "Advanced" > "Deactivate my account".

Thanks in advance,

🙇🏻

**Comment by lindy65** [comment]
Hi @mathias-b 

Thank you for your feedback,

We have a "Help Wanted" ticket for this: https://mattermost.atlassian.net/browse/PLT-1798

Would you be interested in working on this?

**Comment by lindy65** [comment]
I'll close this off for now and we can track via the Jira ticket.

**Comment by mathias-b** [comment]
Thanks for answering.

I'll see what I can do in your Jira.
