### ISSUE TITLE
Increase or remove limit for message size

### ISSUE THREAD

**Issue by maxtar** [mattermost/mattermost-server#7499]
Hi.
Now mattermost has limit for one message in 4000 chars. This is not useful fore stacktraces and other things from log. Could you increase this limit or maybe do feature in this case automatically create file and attach them to message.

**Comment by lindy65** [comment]
Hi @maxtar 

Thank you for your feedback,

Could we have your help creating a feature suggestion on our [forum](https://mattermost.uservoice.com/forums/306457-general) where you and others can up-vote it up to 10 times?

The more votes a suggestion has, the more chance it has of making it into the product.

Thanks!

**Comment by maxtar** [comment]
Forum contains the both suggestions :) I've voted.

**Comment by lindy65** [comment]
Awesome, thanks @maxtar :)
