### ISSUE TITLE
Cannot send any message on iPad (2017) when in landscape mode

### ISSUE THREAD

**Issue by jlegen** [mattermost/mattermost-server#7506]
#### Summary
On iPad in landscape mode, <return>-key always creates a new line, and there is **no** send icon aside the input field. Instead, there is an Emoji selector. 
Turning the iPad into portrait mode, the Emjoi selector icon changes into a send icon... o_O

#### Steps to reproduce
just use a fresh mattermost install (4.2) and latest iPad "classic" app. This is on IOS10...

#### Expected behavior
show send icon

#### Observed behavior (that appears unintentional) 
does not show send icon in landscape

**Comment by lindy65** [comment]
Hi @jlegen 

Thank you for your feedback,

At present, iPads are not supported.  Could we have your help adding your vote to [this feature suggestion](https://mattermost.uservoice.com/forums/306457-general/suggestions/20082079-add-a-tablet-ipad-version-of-second-generation-m) on our forum?

You and others can up-vote the suggestion up to 10 times.

Thanks!
