### ISSUE TITLE
Change "View/Manage Members" dialog to use the same UI component as "Add Members to Team"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7508]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7713)

Change "View/Manage Members" dialog to use the same UI component as "Add Members to Team". This will make these UI dialogs consistent with each other. We already have a ticket to do this for the "Add Members" dialog: https://mattermost.atlassian.net/browse/PLT-6024

Functionally the only change should be that you can navigate through the users list with up/down arrow keys to change the selected user in the list.

Note that ENTER should open the dropdown menu for the user that's in focus in the Manage Members modal, as it does now. 

Ideally, the escape key should then close the dropdown, with a second escape key dismissing the dialog. If that is not tehcnically feasible, we are open to other options.

**Comment by xjlim** [comment]
I will work on this

**Comment by esethna** [comment]
This ticket will need to be updated since the “Add members to team” flow was changed with the introduction of guest accounts and new “Invite People” flow.

**Comment by hanzei** [comment]
@esethna Do you see this ticket getting updated in the near term or should it just be closed for now?

**Comment by esethna** [comment]
We can close this for now
