### ISSUE TITLE
Allow spaces in file names

### ISSUE THREAD

**Issue by bios-ben** [mattermost/mattermost-server#7510]
#### Summary
Currently downloading a file with spaces will display like it has spaces "File Name.doc" but when it's downloaded will send "File+Name.doc" which is annoying to clean up after the fact.

#### Steps to reproduce
As of version 4.2, upload a file with spaces then download it.

#### Expected behavior & fixes
As per normal web headers, you can specify the content disposition "with quotes" to support sending spaces back to the client. I'd expect uploading "File Name.doc" returns that exact name when downloaded.

**Comment by lindy65** [comment]
Hi @bios-ben 

Thanks for your feedback,

I've filed a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7740) to track the issue.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the Jira ticket...
