### ISSUE TITLE
[Help Wanted] [PLT-7727] Update matterbuild to remove loadtest deployments after they have been run.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7513]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7727)

**Comment by cpanato** [comment]
I will take care this

**Comment by cpanato** [comment]
still waiting for more information

**Comment by jasonblais** [comment]
Who have you asked @cpanato?

**Comment by cpanato** [comment]
@jasonblais yes, in the pre-release and also in the JIRA

**Comment by amyblais** [comment]
Hi @cpanato, apologies for delay, have your questions been resolved or do you need help with anything?

**Comment by cpanato** [comment]
@amyblais I will speak again with @crspeller  this gets lost :(

**Comment by amyblais** [comment]
No problem, let me know if you need any help with reaching Chris.

**Comment by hanzei** [comment]
@cpanato Is this ticket still valid?

**Comment by crspeller** [comment]
No. This can be closed.
