### ISSUE TITLE
[Help Wanted] [PLT-7729] Create Jenkinsfile for mattermost-mobile and create build on new build server

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7516]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7729)

New build server repository: https://github.com/mattermost/mattermost-build

Current Jenkins build script
```
# Configure mattermost-mobile
cd -
cd src/github.com/mattermost/mattermost-mobile

echo assets/base/config.json
cat assets/base/config.json

# Compile assets
make dist/assets || exit 1

# Run tests
npm install || exit 1
touch .npminstall
touch .yarninstall

make check-style || exit 1
npm run test || exit 1
```

**Comment by cpanato** [comment]
will take this one as well :)

**Comment by Brunzer** [comment]
Is this still needed? I can work on it

**Comment by jasonblais** [comment]
@Brunzer looks like this is already covered. Would there be another help wanted ticket you'd like to tackle?
