### ISSUE TITLE
Create Jenkinsfile for mattermost-push-proxy and create build on new build server

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7518]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7730)

New build server: https://github.com/mattermost/mattermost-build

Current Jenkins server build script:
```
#!/bin/bash

echo
echo go version
go version
echo

export GOPATH=$WORKSPACE
echo GOPATH=$GOPATH

cd src/github.com/mattermost/mattermost-push-proxy

rm -rf dist

make
```

**Comment by dlahn** [comment]
I can work on this if it's available.

**Comment by dlahn** [comment]
PRs:
https://github.com/mattermost/mattermost-build/pull/2
https://github.com/mattermost/mattermost-push-proxy/pull/26

One question, where should the builds be pushed to? S3?

**Comment by amyblais** [comment]
Hi @dlahn, thank you for helping with this issue!

Apologies for the late response - I see that one of the PRs is merged, do you still need assistance with your earlier question on where the builds should be pushed to? Do you need any other assistance?

**Comment by hanzei** [comment]
@cpanato Is this ticket still valid?

**Comment by cpanato** [comment]
this is already done, closing
