### ISSUE TITLE
[Help Wanted] [PLT-7731] Create Jenkinsfile for mattermost-redux and create build on new build server

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7519]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7731)

New Jenkins sever: https://github.com/mattermost/mattermost-build

Current Jenkins build script
```
#!/bin/bash

echo
echo docker version
docker version
echo
echo Port: ${MMPORT}

docker exec mattermost-mysql-57 mysql --user=root --password=passwd -e 'create database `'$BUILD_TAG'`;'
echo 'Created database for mysql'

# Download and configure Mattermost
wget https://releases.mattermost.com/mattermost-platform/master/mattermost-enterprise-linux-amd64.tar.gz
tar -zxf mattermost-enterprise-linux-amd64.tar.gz

cd mattermost 
sed -i'' 's|mmuser:mostest@tcp(dockerhost:3306)/mattermost_test?charset=utf8mb4,utf8|root:passwd@tcp(localhost:3306)/'$BUILD_TAG'?charset=utf8mb4,utf8|g' config/config.json;
sed -i'' 's|:8065|:'${MMPORT}'|g' config/config.json;
sed -i'' 's|"EnableOpenServer": false|"EnableOpenServer": true|g' config/config.json;
sed -i'' 's|"EnableCustomEmoji": false|"EnableCustomEmoji": true|g' config/config.json;
sed -i'' 's|"EnableLinkPreviews": false|"EnableLinkPreviews": true|g' config/config.json;
sed -i'' 's|"EnableOAuthServiceProvider": false|"EnableOAuthServiceProvider": true|g' config/config.json;
sed -i'' 's|"EnableOnlyAdminIntegrations": true|"EnableOnlyAdminIntegrations": false|g' config/config.json;

echo
echo mattermost version
bin/platform version

# Run Mattermost
bin/platform &
echo 'Started Mattermost server'

# Configure mattermost-redux
cd -
cd src/github.com/mattermost/mattermost-redux

sed -i'' 's|:8065|:'${MMPORT}'|g' test/test_helper.js;

npm install --ignore-scripts || exit 1
touch .npminstall

# Check style

npm run check || exit 1

# Run tests

npm run test || exit 1

```

**Comment by dlahn** [comment]
I'll take this one.

**Comment by giwrgosdi** [comment]
Seems like an old issue, is this still open ?

**Comment by hanzei** [comment]
@cpanato Is this still valid or do you want to use circle ci for this?

**Comment by hanzei** [comment]
Closing as the original ticket got closed
