### ISSUE TITLE
Server accepts reactions to System Messages on React Native Client

### ISSUE THREAD

**Issue by karlding** [mattermost/mattermost-server#7522]
#### Summary

Server accepts reactions to System Messages

#### Steps to reproduce

1. Download the React Native client (I used the version in the Play Store, 1.2.0)
2. In the React Native client, tap and hold on a System Message (like `___ has joined the channel`)
3. Select an Emoji reaction

I tested this using the pre-release Mattermost server today.

#### Expected behavior

One would expect that you can't react to System Messages, since the Emoji picker is hidden on the other platforms. I would assume that the API server should reject this with some sort of error.

#### Observed behavior (that appears unintentional) 

You are able to react to the System Message, which is accepted by the server.

![capture](https://user-images.githubusercontent.com/6836385/30896888-1fb62368-a308-11e7-8bf8-76b04843420f.PNG)

#### Possible fixes

1. Fix React Native client to not display the Emoji picker on System Messages? Otherwise, if this is intended behaviour, show the Emoji picker on the other platforms?
2. Add validation on the Server to not accept reactions on System Messages?

**Comment by lindy65** [comment]
Hi @karlding,

Thank you for the report!

This seems like a bug on the React Native app and I've created a [Jira ticket](https://mattermost.atlassian.net/browse/RN-370) to track the issue.

**Comment by lindy65** [comment]
I'll close this issue off here and we can track it via the Jira ticket linked above.

**Comment by karlding** [comment]
Shouldn't there be an associated change on the server side to not accept requests that attempt to react to a system message? Otherwise someone could still hit the API directly, even if changes to the React Native client are made.
