### ISSUE TITLE
Command Line Tools, user still partially exist after platform user delete

### ISSUE THREAD

**Issue by chumbalum** [mattermost/mattermost-server#7525]
#### Summary
I deleted a (inactive) testuser with the command line tools **platform user delete {email}**. The script was executed without errors. I verified with **platform user search {email}** and the user wasn't found anymore. Despite of that, the user still shows up in the system console user list.

![mattermost users](https://user-images.githubusercontent.com/486034/30920829-3b331a5e-a3a5-11e7-96ed-256390c9faff.png)

The summary says that its showing 1-6 users of total 5 users. So there is some inconsistent state.

#### Expected behavior
The user should be deleted entirely.

#### Observed behavior (that appears unintentional) 
The user is still in the user list of the system console

#### Additional Information
Mattermost Server 4.2.0
Database: mysql
Ubuntu 16.04
(Installed with installation guide)

**Comment by chumbalum** [comment]
I found some time to restart the server and the problem is solved. So I guess this issue can be closed.

**Comment by lindy65** [comment]
Thanks for your feedback @chumbalum - I'll close the issue.
