### ISSUE TITLE
[Help Wanted] [PLT-7714] Have the Add User To Channel api route return a 400 error when trying to add users to a DM or GM channel

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7526]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7714)

Repro steps:
1) Create a direct or group message channel using the API ([link](https://api.mattermost.com/#tag/channels%2Fpaths%2F~1channels~1group%2Fpost))
2) Attempt to add a user to the channel using the API ([link](https://api.mattermost.com/#tag/channels%2Fpaths%2F~1channels~1%7Bchannel_id%7D~1members%2Fpost))

Observed: A 404 error is returned stating that a team member object cannot be found
Expected: A 400 error is returned stating that users cannot be added to that type of channel

**Comment by santos22** [comment]
I can take this!

**Comment by santos22** [comment]
I am creating a direct/group message channel using the API and correctly receive a 201 response. When I attempt to add a user to the channel using the API, I also correctly receive a 404 response.

However, isn't this status code determined by the HTTP request being created in [client4.go](https://github.com/mattermost/mattermost-server/blob/76bd1bb212177824379c485c553e54530a854009/model/client4.go#L322)? If so, how can we return a 400 error if this new request is returning an 404 error? Are we supposed to override it?

Instead of returning: `nil, BuildErrorResponse(r, err)` in [client4.go](https://github.com/mattermost/mattermost-server/blob/76bd1bb212177824379c485c553e54530a854009/model/client4.go#L1623), I am returning the following:
`nil, BuildErrorResponse(r, NewAppError("AddUserToChannel", "api.channel.add_user_to_channel.deleted.app_error", nil, "", http.StatusBadRequest))`

I am now expecting a 400 error but actual error is still 404.

**Comment by jasonblais** [comment]
Awesome, thanks @santos22!

**Comment by santos22** [comment]
I am creating a direct/group message channel using the API and correctly receive a 201 response. When I attempt to add a user to the channel using the API, I also correctly receive a 404 error. [I  created a Gist of the Go request I run while running Mattermost locally](https://gist.github.com/santos22/1cf0eb996d00b0b76dd307f7f3d33645).

However, isn't the response status code determined by `c.HttpClient.Do(rq)` in [client4.go](https://github.com/mattermost/mattermost-server/blob/76bd1bb212177824379c485c553e54530a854009/model/client4.go#L333)? If so, how can we return a 400 error for this route? Are we supposed to override the 404 error being returned?

**Comment by jasonblais** [comment]
Thanks @santos22!

If you can't find what you're looking for inside mattermost-server/store/sqlstore/, [APIv4 channel](https://pre-release.mattermost.com/core/channels/apiv4) is an excellent place to ask questions from the community and Mattermost developers :)

**Comment by santos22** [comment]
Before submitting a PR, are the following applicable to this issue? 

- Added API documentation (required for all new APIs)
- All new/modified APIs include changes to the drivers

**Comment by jasonblais** [comment]
@santos22 It would be good to add API documentation at https://github.com/mattermost/mattermost-api-reference and make the corresponding changes to the drivers.

If you have questions about either one, let me know and we can point you in the right direction.

**Comment by santos22** [comment]
For sure! When adding API documentation to the [Add a user](https://api.mattermost.com/#tag/channels%2Fpaths%2F%7E1channels%7E1%7Bchannel_id%7D%7E1members%2Fpost) route, what exactly would change? I see there is already a 400 in the list of response.

And I'm not sure what the drivers are for or where to find them.

**Comment by jasonblais** [comment]
Thanks @santos22! 

1) If you're not modifying an existing API call (or adding a new one), then no documentation is needed. Sounds like that might be the case.

2) We have two official drivers, one for [Javascript](https://github.com/mattermost/mattermost-redux/blob/master/src/client/client4.js) and another for [Go](https://github.com/mattermost/mattermost-server/blob/master/model/client4.go). They make it easier to interact with the Mattermost Web Service API. That being said, if you're not modifying an existing API call (or adding a new one), again no changes would be needed

---

If you're not sure whether you modified the call, we can also take a quick look at your branch for your changes before you submit a pull request. 

Big thanks for your continued help on this issue :)

**Comment by santos22** [comment]
Hi @jasonblais,

Thanks for the clarification on that. It does not look like I modified the call but I would appreciate a second look at the changes I've made. They can be found here: https://github.com/santos22/mattermost-server/tree/PLT-7714

Thanks!

**Comment by jasonblais** [comment]
Thanks @santos22! Yeah that looks good, shouldn't need any docs or driver changes. Once submitted, I'll queue this straight to dev review. 

Big thanks for your help :)

**Comment by jasonblais** [comment]
Thanks @santos22!
