### ISSUE TITLE
no send button on larger format devices when in landscape.

### ISSUE THREAD

**Issue by mcarpenterjr** [mattermost/mattermost-server#7537]
#### Summary
Users who default to `CTRL + Enter` for sending messages have no send button on large format mobile devices when they are in use in landscape mode.

#### Steps to reproduce
Find a large format device (Samsung Tab A 10", SM-T580) rotate into landscape and pull up an instance of mattermost, look for send button. Try sending a message using `CTRL + ENTER` with missing send button. Or adding a new line...

Or if no device is available, open a windowed instance of mattermost web client inspect window, drag side of window to resize, watch screen size and look for send button.

#### Expected behavior
Users should be able to send messages no matter their user preferences and format they are using mattermost.

#### Observed behavior (that appears unintentional) 

![mmstsendbutton](https://user-images.githubusercontent.com/11430497/31017736-8fec1b56-a4f7-11e7-8136-9c01e5ff70ab.gif)

**Comment by mcarpenterjr** [comment]
Similar to #4368

**Comment by lindalumitchell** [comment]
Filed in Jira to track: https://mattermost.atlassian.net/browse/PLT-7760

**Comment by lindy65** [comment]
Thanks @mcarpenterjr and @lindalumitchell 

I'll close off this issue here and we can track via the Jira ticket linked above.

**Comment by mcarpenterjr** [comment]
Thanks, Guys!
