### ISSUE TITLE
[Help Wanted] [PLT-4951] Don't send notifications or mark channel unread if a post is made to a comment thread that's open in right hand sidebar, and Mattermost is in focus

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7541]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4951)

Don't send desktop or push notifications and don't mark channel unread if a post is made to a comment thread that's open in right hand sidebar, and Mattermost is in focus.

Example:
1) comment thread for channel_A is open in right-hand sidebar, 
2) channel_B is open on the center pane
3) Mattermost is in focus
4) If someone posts a message on the comment thread for channel_A that is open in the right-hand side, do not send desktop and push notifications for that post, and do not bold channel_A in the left-hand sidebar.

Start of a PR here that was since closed: mattermost#6461

**Comment by esethna** [comment]
Re-opened here: https://github.com/mattermost/mattermost-server/issues/7718
