### ISSUE TITLE
[Help Wanted] [UX-65] In desktop web app, remove unnecessary steps for copying permalink

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7544]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/UX-65)

**Comment by letsila** [comment]
Hi guys! I'd love to work on this issue.

**Comment by jasonblais** [comment]
@letsila Aah sorry. We were meaning to add an updated mock up for this design but accidentally created a help wanted ticket for it.

I'll close this for now until we have the new mockup..would there be another ticket you'd be interested to work on?

Thanks for your interest!! :)

**Comment by letsila** [comment]
No worries I am gonna find another ticket :)
