### ISSUE TITLE
What is the meaning of the version which is described in the parentheses?

### ISSUE THREAD

**Issue by tochi-y** [mattermost/mattermost-server#7547]
#### Summary
The version is displayed `4.1.0 (4.1.1)` after Mattermost installation.  
I think the version 4.1.0 is installed, is my understanding correct?  
And what is the meaning of the version which is described in the parentheses, 4.1.1?

#### Steps to reproduce
1. Install the latest mattermost by [One-line Docker Install](https://docs.mattermost.com/install/docker-local-machine.html#one-line-docker-install).
2. Open the browser.
3. Click 'About Mattermost'.

#### Expected behavior
Display only `4.1.0`, not `4.1.0 (4.1.1)`.

#### Observed behavior (that appears unintentional) 
![02](https://user-images.githubusercontent.com/32325140/31065986-8995fb34-a784-11e7-8659-59f0bc2e91d8.png)

**Comment by lindy65** [comment]
Hi @tochi-y 

Thanks for your question.  Version numbering is explained [here](https://docs.mattermost.com/process/release-process.html#release-numbering).

Does this help?

**Comment by tochi-y** [comment]
Hi @lindy65

Thanks for your reply.

 I read the linked documentation, and I could understand Version numbering.
But I still need to help. 

What is the difference between '4.1.0' and'(4.1.1)' in '4.1.0 (4.1.1)'?

**Comment by lindy65** [comment]
Hi @tochi-y,

Ah, ok, thanks for clarifying!

`4.1.0` would be the version released and `4.1.1` would be a dot release where there was a bug fix or security fix.

**Comment by lindy65** [comment]
I'll close this issue off for now.  Please feel free to post back if you need further clarification @tochi-y
