### ISSUE TITLE
[Help Wanted] [PLT-7778] Pre-populate the ends of token/API endpoints for GitLab System console settings

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7558]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7778)

For GitLab endpoint settings, pre-populate the ends of token/API endpoints which are the same for all servers.

Current:
![image](https://user-images.githubusercontent.com/13119842/31132603-36106664-a82b-11e7-80ca-581754ced7fa.png)

Proposed:
1a) Add a new setting to the System Console for GitLab Site URL.

*Title:* GitLab Site URL
*Input hint:* E.g.: https://<your-gitlab-url>
*Help text:*
Enter the URL of your GitLab instance, e.g. https://example.com:3000. If your GitLab instance is not set up with SSL, start the URL with http:// instead of https://.

1b) Use this new setting to auto-generate the User API Endpoint, Auth Endpoint and the Token Endpoint. The endpoints are non-editable, similar to the OAuth 2.0 > Office 365 endpoint settings.
1c) NOTE: Config.json should remain unchanged. This is simply a setting in the System Console UI which makes it easier to configure your GitLab authentication for Mattermost.

![image](https://user-images.githubusercontent.com/13119842/31132614-3f5152d8-a82b-11e7-9350-ab50415dddbd.png)

**Comment by R-Wang97** [comment]
I can take this.

**Comment by jasonblais** [comment]
Thanks @R-Wang97!
