### ISSUE TITLE
[Help Wanted] [PLT-7777] Pre-populate SAML > Service Provider Login URL page with [Site URL]/login/sso/saml

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7559]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7777)

1 - If System Console > Site URL is set, 

1a) pre-populate SAML > Service Provider Login URL page with [Site URL]/login/sso/saml, e.g. https://pre-release.mattermost.com/login/sso/saml.
1b) make the input field non-editable, similar to the OAuth 2.0 > Office 365 endpoint settings.
![image](https://user-images.githubusercontent.com/13119842/31132575-1a6c9874-a82b-11e7-96c9-b91edd6252a6.png)

1c) change help text to "This field is also known as the Assertion Consumer Service URL."

If System Console > Site URL is not set, then don't make any changes from the existing behaviour (i.e. field not set, help text stays the same).

**Comment by yeoji** [comment]
I have created a PR in mattermost-webapp for this issue.
