### ISSUE TITLE
[Help Wanted] [PLT-7774] Add the Teammate Name Display setting back to Account Settings > Display, below "Clock Display" option.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7560]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7774)

Add the Teammate Name Display setting back to Account Settings > Display, below "Clock Display" option.

Title: Teammate Name Display
Help text: Set how to display other user's names in posts and the Direct Messages list.
Options:
 - Show username (default) // If username is chosen by the admin in System Console > Users and Teams > Teammate Name Display
 - Show nickname if one exists, otherwise show first and last name
 - Show first and last name

Notes:
1) The end user settings would have the same options as before, but defaults to the System config setting.
2) Push and email notifications would follow the System config setting.
3) If the System config setting is updated, only override the display setting for users who were using the default

Examples:
 a) User has not changed the display name and is using the system default (first/last name). System Admin changes the config setting from first/last name to nickname. User's display setting also *changes to nickname*.
 b) User has set the display name to *username*. System Admin changes the config setting from first/last name to nickname. User *continues to have the display name set to username*.
 c) User has set the display name to *first/last name*. System Admin changes the config setting from first/last name to nickname. User's *continues to have the display name set to first/last name*.

**Comment by vgvenkat** [comment]
I am still setting up my dev environment with docker. I would like to work on this. Is there a channel I can ping back for help?

**Comment by jasonblais** [comment]
Thanks @vgvenkat! 

The best channels would be [our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, or [our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers) for technical questions and advice.

**Comment by jasonblais** [comment]
I take it that you're planning to tackle this improvement?

**Comment by jasonblais** [comment]
I take it you're interested tackling this issue?

**Comment by jasonsmith425** [comment]
Glad to see this is potentially going to be picked up! My users were disappointed when this setting was removed from their menus. Some want to use nicknames and some want to use usernames, but I have to force them all to use display name because that's what most people prefer. I don't know why this is necessary/why it hurts to allow the user to configure this on their end.

**Comment by coreyhulen** [comment]
This is back up for grabs.

**Comment by KishoreFartiyal** [comment]
@jasonblais I would like to work on it

**Comment by R-Wang97** [comment]
I'll take this on if no one is working on it anymore.
