### ISSUE TITLE
[Help Wanted] [PLT-7776] Render at-mentions by the teammate name display

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7562]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7776)

CURRENT CONDITION: 

Currently, Mattermost uses the Teammate Name Display config setting to choose which name to display in the UI, including
 - channel member lists
 - email notifications
 - push notifications
 - DM channel sidebar

In many of the other lists like "Add Members", channel switcher and "More Direct Messages", all name variations are displayed.

The one place where we strictly use usernames in the UI is at-mentions.

CONTEXT (from a prospect):

We had to change our usernames from "first name" to the actual user name in LDAP config. 

As a result, people have random usernames like "xyz2fe". These random usernames appear in several places of the UI due to mentions, making the experience confusing.

PROPOSED CHANGE:

1) In the UI, render at-mentions by the teammate name display set in config.json. The entire name should be highlighted, and preceeded with an "@" symbol.

When writing a message draft, the at-mention should use the username, similar to channel linking, to guarantee the correct mention is fired (we might be able to do some fancier stuff later).

2) In system messages (e.g. user joined/left), use the teammate name display setting as well, instead of the default username.

**Comment by mikaoelitiana** [comment]
I want to work on this on.

**Comment by jasonblais** [comment]
Awesome!!

**Comment by jasonblais** [comment]
@mikaoelitiana Let us know if you have any questions about this ticket?

**Comment by philippe-granet** [comment]
@mikaoelitiana Do you work on this issue?

**Comment by mikaoelitiana** [comment]
@philippe-granet Yes I was but I got a computer issue for a few weeks now and I can't work on it yet. Are you willing to complete the PR?
