### ISSUE TITLE
[Help Wanted] [PLT-7803] Have shift+up switch keyboard focus to RHS if it's already open to the current thread

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7580]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7803)

Repro steps:
1) Press shift+up to open the latest thread in the channel in the RHS
2) Click into the post textbox
3) Press shift+up again

Observed: Nothing happens
Expected: The keyboard cursor moves to the RHS which is already open

**Comment by d1ndra** [comment]
I would like to work on this, any help would be appreciated.

**Comment by jasonblais** [comment]
Thanks @d1ndra! A good place to start is to review our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

**Comment by jasonblais** [comment]
Let us know if you have any questions :) 

By the way, this pull request originally added the shortcut, which might be helpful: https://github.com/mattermost/mattermost-server/pull/6549

**Comment by d1ndra** [comment]
Thanks @jasonblais

**Comment by d1ndra** [comment]
@jasonblais from my understanding, to shift the focus back to the already open RHS one would have to invoke the `componentDidUpdate` in `create_comment.jsx`, however since the state is the same there is no updating. Performing a `this.forcedUpdate()` also only invokes the method in `create_post.jsx`. Any advice on how to proceed? Thanks

**Comment by jasonblais** [comment]
Thanks @d1ndra, you got a response in the Developers channel: https://pre-release.mattermost.com/core/pl/6e18z4b9m7g4zxy8oztnwd9uce

Thanks for working on this issue!

**Comment by jasonblais** [comment]
@d1ndra Let us know if you have any other questions on this ticket?

**Comment by esethna** [comment]
Reopening this ticket if anyone is interested in taking it on

**Comment by jasonblais** [comment]
Great, thanks @lisakycho :tada:
