### ISSUE TITLE
[Help Wanted] [PLT-7794] Deactivate personal access tokens via Account Settings

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7583]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7794)

1) In Account Settings > Security > Personal Access Tokens, add an option to deactivate a token, in addition to deleting it.

Use case: A bot has gone crazy, so I deactivate the token, investigate the issue, then activate later. Deactivating lets me re-use the token and saves a few steps without needing to re-create the token from scratch and re-issuing it for my bots.

![image](https://user-images.githubusercontent.com/13119842/31252697-fef88ef6-a9ef-11e7-8aa8-8113ce5c8bba.png)

Clicking “Deactivate” temporarily disables the token and prevents integrations from using it.
Clicking “Activate” re-enables the token and allows integrations to start using it again.

![image](https://user-images.githubusercontent.com/13119842/31252705-06e3066e-a9f0-11e7-8149-c9b867042dce.png)

Note that there's no server support for deactivating personal access tokens yet. This will require a new database column on the UserAccessToken table.

2) Add two-client side telemetry events:
 - When a user deactivates a token via Account Settings > Security
 - When a user re-activates a token via Account Settings > Security

Please use category: ‘settings’ for the telemetry entry, in order for it to be distinguished from a System Admin deactivating/activating a token via the System Console.

**Comment by fraziern** [comment]
I can give this a go.

**Comment by jasonblais** [comment]
Thanks @fraziern!

**Comment by jasonblais** [comment]
@fraziern You can check the Integrations page -- we use that pattern when listing webhooks and slash commands

![image](https://user-images.githubusercontent.com/13119842/31391173-cc9d360c-ada3-11e7-9364-0a57d421e3be.png)

**Comment by jasonblais** [comment]
Hey @fraziern, let me know if you need any help with the webapp portion of the PR?

**Comment by fraziern** [comment]
Will do. The menu component structure has been a lot to grok and just identified an issue with the redux piece (fixed today in a PR). Getting there...
