### ISSUE TITLE
[PLT-7793] Manage Tokens page

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7584]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7793)

CONTEXT:

In large deployments, with several users creating personal access tokens, it’s essential for the System Admin to be able to find, manage and revoke these tokens as needed.

Some of this is currently handled by “Manage Tokens” option in the Users page, but the functionality is limited and tokens can only be viewed per users. There isn’t a single list of tokens available in the UI.

A Tokens page is a key request from some customers with respect to personal access tokens.

PROPOSED CHANGE:

1) Add a “Personal Access Tokens” page to the System Console, listed below “Users” in the sidebar. 

The list includes
 - Token ID and Token Description
 - User who created the token
 - Option to delete the token on the right

Tokens are sorted by
 - Alphabetically by token id.

Admin can search tokens by 
 - token ID
 - username
 - user ID

![image](https://user-images.githubusercontent.com/13119842/31242192-3f96b68e-a9d4-11e7-9984-af62071898d7.png)

2) Deleting the token - Clicking “Delete” will bring up a confirmation dialog similar to the one below when deactivating a user, with:

Title: Delete Token
Description: `Any integrations using this token will no longer be able to access the Mattermost API. You cannot undo this action.\n\nAre you sure want to delete the [description] token?`
Buttons: Cancel // Delete

Hitting “Cancel” closes the popup and does no action. Hitting “Delete” deletes the token.

![image](https://user-images.githubusercontent.com/13119842/31242199-4562aeb0-a9d4-11e7-8716-709225fee96a.png)

3) Add a client side telemetry event when a System Admin deletes a token via System Console > Access Tokens

Please use category: ‘system_console_tokens’ for the telemetry entry, in order for it to be distinguished from a System Admin deleting a token from the System Console > Users page.

4) Update the System Console > Custom Integrations help text for enabling a personal access token to: 

```
When true, users can create personal access tokens for integrations in Account Settings > Security. They can be used to authenticate against the API and give full access to the account.

To manage who can create personal access tokens or to search users by token ID, go to the Reporting > Users page. To manage tokens, go to the Reporting > Personal Access Tokens page.
```

**Comment by charle692** [comment]
I'll start working on this.

**Comment by jasonblais** [comment]
Sweet, thanks @charle692!

**Comment by jasonblais** [comment]
@charle692 Let us know if you have any questions on this ticket?

**Comment by watadarkstar** [comment]
I'll take this one! :)

**Comment by jasonblais** [comment]
Great! Thanks @watadarkstar!

**Comment by watadarkstar** [comment]
@jasonblais Hi Jason, I have a question - it says in the description of this ticket:

> Add a “Personal Access Tokens” page to the System Console, listed below “Users” in the sidebar.

If I follow the UI/UX of the other subsections, when I add “Personal Access Tokens” under "Users", I would need to create a new subsection called "USERS" and under that we will need two links. As the current UI/UX subsections titles are not clickable. I attached an image to explain what I mean:

![screen shot 2017-12-19 at 11 05 33 am](https://user-images.githubusercontent.com/3059371/34166761-bc25ed46-e4ad-11e7-8946-9cec6f2fe923.png)

See "AUTHENTICATION" it is not clickable in the current UI/UX. So making "USERS" clickable here would be inconsistent with the UX that already exists. Therefore, I have left "???" to be a placeholder to what needs to go below "USERS" - i.e. what should I call the existing page of "Users"? Or if this approach is not the right one please let me know.

**Comment by esethna** [comment]
Hi @watadarkstar, sorry for the confusion. The "Personal Access Tokens" page is **not supposed to be nested** under "Users", it's just supposed to appear between "Users" and "Logs" (at the same hierarchy level as those sections):

![image](https://user-images.githubusercontent.com/14333569/34175535-f4ad07f6-e4b9-11e7-9fe2-5b494dd1dab0.png)

Does that help clarify?

**Comment by watadarkstar** [comment]
@esethna Thanks Eric that makes sense! 😄
