### ISSUE TITLE
Add direct messages with user to search results

### ISSUE THREAD

**Issue by torgeirl** [mattermost/mattermost-server#7600]
#### Summary
Direct Messages (DMs) with an user, unless the user's real name or username is explicitly mentioned, isn't listed in search results for a search query on that user's real name or username.

#### Example
A search for 'bob' will currently not include a direct message conversation you had with the users 'bob' and 'paul', unless one of you mentioned bob explicitly in the conversation.

#### Expected behavior
Direct message conversation with a user that has a real name or username matching the search query should be appended to the search result.

**Comment by lindy65** [comment]
Hi @torgeirl,

Thank you for your feedback,

At the moment, this is not possible in Team Edition while in Enterprise Edition there is Elasticsearch which does bring back results for direct messages.

If you'd like to see the same feature in Team Edition, please consider opening a feature request on our [forum](https://mattermost.uservoice.com/forums/306457-general) where you and others can upvote it to increase its popularity.

Thanks!

**Comment by torgeirl** [comment]
Hi @lindy65,

I'm having trouble seeing why a distributed, RESTful search engine server like Elasticsearch would be needed to _append direct message conversation with a user that has a real name or username matching the search query to the search result_ – that can't be a time-costly operation (doesn't the search already goes through the same DMs looking for the explicitly mentions it currently finds?). It looks more like a development oversight, and something you would want to fix for all Mattermost editions, not just Team Edition?

Of note: Elasticsearch is [only available for Enterprise Edition E20](https://docs.mattermost.com/deployment/elasticsearch.html), not Enterprise Edition E10 as I assume most (myself included) run out of the Enterprise options.

**Comment by lindy65** [comment]
Hi @torgeirl,

Thank you for your feedback, 

I'll ask one of our product managers to weigh in on this conversation to address your concerns.

**Comment by lfbrock** [comment]
Hi @torgeirl - are you looking for Group Direct Messages with more than one user to show up in the Direct Message search? 

Would you be able to take a screenshot of where you're wanting them to show up, and then I can look at making a Jira ticket for it?

**Comment by torgeirl** [comment]
Hi @lfbrock,

No, more generally; I'm looking for direct messages, either group DMs containing that user or a DM between you and that user, to show up in a regular search, along with any other hit.

I'll see if I can get you a good screenshot of what I'm missing, but in a browser that would be the search results listings you get up on the right hand side.

**Comment by lfbrock** [comment]
Okay thanks @torgeirl a screenshot would be good to make sure I'm following. 

I think searching users to see their profiles there could make sense, but I'm just trying to envision how searching for a group DM or user DM would work and what info would be shown in the search result.

**Comment by lindy65** [comment]
Hi @torgeirl,

Have you had a chance to get a screenshot to add to this issue for `lfbrock`?

**Comment by lindy65** [comment]
Hi @torgeirl, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
