### ISSUE TITLE
Closed direct messages should be suggested under DMs > More

### ISSUE THREAD

**Issue by torgeirl** [mattermost/mattermost-server#7602]
#### Summary
Closed direct messages with multiple users should be listed in the direct messages menu.

#### Example
If you closed a direct message conversation with users 'bob' and 'paul' that conversation isn't listed along with the usernames you can chose from when making a new conversation.

#### Expected behavior
You can reconstruct a closed direct message conversation by making a "new" conversation with the same users, but not everyone remembers exactly who participated in given conversation and aren't always able to find it by searching.

Users expect previous conversations to be listed in the menu where you make direct message conversions as this is the norm with other messaging servers, and they should therefore be added to the searchable list of possibilities when making a new direct message conversion.

**Comment by lindy65** [comment]
Hi @torgeirl,

Thank you for your feedback!

Could we have your help opening a feature request on our [forum](https://mattermost.uservoice.com/forums/306457-general) where it can be upvoted by yourself and others to gain popularity?

**Comment by lindy65** [comment]
I'll close this issue off for now and perhaps @torgeirl can post a link to the feature suggestion once it's created.
