### ISSUE TITLE
Uploaded files are stored on a per day folder

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-server#7607]
#### Summary
Uploaded files are grouped per day starting with 4.2.0

#### Steps to reproduce
Upload a file in a chat/channel

#### Expected behavior
File is stored in `/data/teams/<teamname>/...` or `/data/teams/noteam/...`

#### Observed behavior (that appears unintentional) 
File is stored in `/data/<date-of-upload-as-YYYYMMDD>/teams/noteam/...`

**Comment by MusikPolice** [comment]
This change was made on purpose to support enhanced data retention options for our enterprise customers. You can see [the diff of the changes here](https://github.com/mattermost/mattermost-server/commit/50fc6e1e9e8d286fd6a406cef75e48a28f9427ad).

**Comment by licaon-kter** [comment]
A warning would have been nice, given that I'm not on Enterprise, hence I was not expecting this to happen.

**Comment by MusikPolice** [comment]
@licaon-kter Agreed. We typically report changes like this in our release notes, but this change was overlooked. Our apologies for any inconvenience that this might have caused. Our PM is aware of the issue, and will make sure that the release notes are updated so that other users are not impacted.

**Comment by jasonblais** [comment]
Thanks all, I've submitted a PR to update our changelog and upgrade notice for v4.2: https://github.com/mattermost/docs/pull/1554

Sorry for the inconvenience, and thank you for bringing this to our attention.
