### ISSUE TITLE
[Help Wanted] [PLT-7886] Move Link previews to Account Settings > Display

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7613]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7886)

Moving link previews out of beta by removing Account Settings > Advanced > Preview pre-release features > **For the first web link in a message, display a preview of website content below the message, if available**.

In Account Settings > Display above "Default appearance of image link previews", add:

**Website Link Previews**
                                  [ x ] On
                                  [  ] Off
                                  Help Text: "When available, the first web link in a message will show a preview of the website content below the message." 

Note: this setting should be hidden if System Console > Link Previews is set to "False"

**Comment by R-Wang97** [comment]
Would I be able to give this a try?

**Comment by jasonblais** [comment]
Go for it! :)

**Comment by jasonblais** [comment]
@R-Wang97 Actually, just found out a core committer had this in progress and is about to submit a pull request. Sorry about that, would there be another Hacktoberfest ticket you'd like to work on?

Closing this ticket,

**Comment by R-Wang97** [comment]
I'll find something, no worries! I haven't started it yet anyways :)
