### ISSUE TITLE
[Help Wanted] [PLT-7824] Slack-compatible webhooks: Support mentions with <@userid> and <!here>

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7615]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7824)

Slack integrations support 
 - mentioning users with <@userid>
 - special mentions such as <!channel> and <!here>

Slack is removing usernames ([see changelog|https://api.slack.com/changelog/2017-09-the-one-about-usernames]) and is pushing people to mention users with the userid instead.

Hence, to maintain Slack-compatibility, we should add support for integrations to
1) mention users with <@userid>

Example: 

a) Make a webhook post with the following payload: {"text": "hey <@beqkgo4wzbn98kjzjgc1p5n91o>"}
b) When the message is posted, "<@beqkgo4wzbn98kjzjgc1p5n91o>" should render as a user mention, such as:

![image](https://user-images.githubusercontent.com/13119842/31521827-004cc658-af79-11e7-85fb-8df281ba6e5c.png)

2) use special mentions for at-channel, at-here and at-all via "<!channel>", "<!here>" and "<!all>", respectively.

Example:

a) Make a webhook post with the following payload: {"text": "hey <!here>"}
b) When the message is posted, "<!here@beqkgo4wzbn98kjzjgc1p5n91o>" should render as "@here":

![image](https://user-images.githubusercontent.com/13119842/31521836-0721e0d0-af79-11e7-9d82-94871f70c99f.png)

NOTE: This change should be on the server-side, and only affect webhooks and custom slash commands.

**Comment by yeoji** [comment]
Hi, I gave this a go and have opened a PR :)
