### ISSUE TITLE
[Help Wanted] [PLT-7567] Team Icons

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7616]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7567)

See corresponding ticket for mobile: https://mattermost.atlassian.net/browse/RN-418

Team Icons will appear in the team sidebar within the border of the existing team icons:

![image](https://user-images.githubusercontent.com/14333569/31508824-88da5ce8-af3c-11e7-8f2f-4049fdd57aca.png)

 - The mention counter on the team sidebar should have a 1px stroke

Add a *Team Icon* setting to the *Team Settings* modal below the *Team Description* setting:
  - Collapsed text when image is set: "Image last updated MMM DD, YYYY"
  - Collapsed text when no image is set: "Click `Edit` to upload an image."

![image](https://user-images.githubusercontent.com/14333569/31508897-c2519658-af3c-11e7-8e4d-e88a4dafae21.png)

When editing the *Team Icon* the setting expands:
  - If no image has been uploaded, do not show an image preview until an image is selected:

![image](https://user-images.githubusercontent.com/14333569/31508908-cb835504-af3c-11e7-9b31-37413545df29.png)

  - If an image has been previously uploaded or a new image is selected, show the preview similar to the *Profile Picture* setting in *Account Settings*

![image](https://user-images.githubusercontent.com/14333569/31508929-dcdeb3d4-af3c-11e7-8223-4d53bda27d26.png)

Buttons (Same as Profile Picture setting in Account Settings):
  - "Select": Opens the file selector to choose a team icon. Once selected, the image preview is rendered in the modal.
  - "Save": Saves the new Team Icon after selecting a new image. Button is disabled unless an image is selected using the "Select" button.
  - "Cancel": Collapses the "Team Icon" setting.

**Comment by santos22** [comment]
I would like to take this one 👍

**Comment by esethna** [comment]
Awesome @santos22!

**Comment by esethna** [comment]
Hey @santos22 hope this is going well, please let me know if you have any questions about the design!

**Comment by santos22** [comment]
Hi @esethna,

Thanks for checking in! I'm making progress on the Go portion of this issue and will soon start working on the ReactJS portion 👍

**Comment by santos22** [comment]
Hi @esethna,

Does this issue also require changes to Redux?

**Comment by esethna** [comment]
Hey @santos22, adding @jwilander to help answer that.

**Comment by jwilander** [comment]
Yes, you'll need to add client driver functions, actions and possibly a reducer to mattermost-redux

**Comment by esethna** [comment]
Hey @santos22, hope all is well! Just letting you know that we have the cut off date for merging major features for the 4.5 release coming up on November 29th. Anything we can help with on this ticket?

**Comment by santos22** [comment]
Hi @esethna,

Thanks for checking in. Still working on the Redux portion to this issue - shooting for next month's release 😄

**Comment by santos22** [comment]
Hi @esethna,

I'm afraid I won't be able to complete this issue. Don't want to hold up this feature because it seems pretty important so someone else can take a look at it! I will make sure to provide more frequent updates on any other issues I work on 👍

**Comment by jasonblais** [comment]
Thanks @santos22 for the heads up! I'll add the `Up for Grabs` label back

**Comment by chumbalum** [comment]
Hello,

I'm all new to Mattermost developing but I would like to contribute to this issue. I already started developing and now I think I'm confident enough to say that I could get the job done.

![grafik](https://user-images.githubusercontent.com/486034/35942843-6f151712-0c57-11e8-9ec8-b8305aca8e62.png)

There is plenty of code concerning the profile-image, which I can orientate myself on. Since I've never done go before, I maybe need some support at some points.

**Comment by jasonblais** [comment]
@chumbalum That's great! Thank you so much for your interest.

As mentioned in the ticket description, you can [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers), for technical advice and questions. We're more than happy to help.

@santos22 Curious if you had a fork or a branch where you had started working on it, in case it was useful for @chumbalum to get started.

**Comment by santos22** [comment]
Welcome @chumbalum!

I do have some code that I worked on locally that I can push shortly. In the meantime, you can start by looking at API calls for user profile images here and the test files:
https://github.com/mattermost/mattermost-server/blob/master/api4/user.go
https://github.com/mattermost/mattermost-server/blob/master/api4/user_test.go

**Comment by chumbalum** [comment]
Thanks for your support. I will take a further look into the existing code and contribution procedure the next days and will deep dive into it on the weekend.

**Comment by chumbalum** [comment]
Hi,

just a quick update. Apart from minor ui logic, I'm almost done. Setting team icon works, tested with seperate users concerning change notification

![grafik](https://user-images.githubusercontent.com/486034/36080470-e477291e-0f90-11e8-8969-3d96ab76966f.png)

I'm going to make some further tests, put everything in a clean state the next days and would open a pull request. Have to take a look into that, since I've never done that before.

**Comment by jasonblais** [comment]
Huge thanks @chumbalum for helping with this feature! It's now merged and scheduled for v4.9 release on April 16th
