### ISSUE TITLE
[Help Wanted] [PLT-4340] Channel Mute and "/mute" command

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7617]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4340)

See corresponding ticket for mobile: https://mattermost.atlassian.net/browse/RN-417

**Functionality**
When a channel is muted, desktop, push and email notifications are not sent for the channel.

When a channel is unmuted, push, email and desktop notifications are sent as usual (According to the Account settings preferences, unless overridden by the channel notification settings "Send Desktop Notifications" and "Send mobile push notifications")

**User Interface**

1. **Channel Header:** When a channel is muted, a clickable icon appears next to the channel name in the channel header (see mock-up). 
   - on-hover tooltip: "Unmute"
   - Clicking the icon unmutes the channel and the icon disappears.

 
![image](https://user-images.githubusercontent.com/14333569/31508659-060d1b5c-af3c-11e7-8103-cea41e4f349e.png)

2. **Channel Sidebar:** When a channel is muted, the channel name in the left-hand sidebar is reduced to 30% opacity and the channel is sorted to the bottom of the sidebar section (secondary sorting of muted channels is based on standard channel sorting). The channel only bolds for unread mentions and the mention jewel also appears at reduced opacity:

![image](https://user-images.githubusercontent.com/14333569/31508684-14279262-af3c-11e7-85dc-fbef0218ef8a.png)

When a channel is unmuted, opacity of the channel name is increased to normal in the left-hand-side and the channel is resorted among the non-muted channels as usual.

3. **Channel Notification Preferences:** Add a setting to Channel > Notification Preferences, at the top.

```
    "Mute Channel"
    [ ] On
    [ x ] Off
    Help Text: Muting turns off desktop, email and push notifications for this channel. The channel will not be marked as unread unless you're mentioned.
```

When a channel is muted (via slash command or this setting), all other channel notification preferences are hidden in the UI, including "Send desktop notifications", "Send mobile push notifications", and "Mark Channel Unread".

When a channel is unmuted (via slash command, this setting, or the channel header icon), all other channel notification preferences are shown as usual below this setting. "Send Desktop Notifications", "Send mobile push notifications" and "Mark Channel Unread" settings return to the state they were in before muting. 

Remove the setting *Channel Notification Preferences* > *Mark Channel Unread*. Turn on *Mute Channel* for any channel which had been set to "Only for mentions".

**Slash Command**
Add a slash command "/mute". Autocomplete description:
```
/mute [channel]
Turns off desktop, email and push notifications for the current channel or the [channel] specified
```

1. "/mute" mutes the current channel
  - System message: "You will not receive notifications for [Channel UI Name] until Channel Mute is turned off."

2. "/mute" when the current channel is already muted will unmute the current channel
   - System message: "[Channel UI Name] is no longer muted."

3. "/mute ~channel-handle" mutes the channel listed.
   - System message: "You will not receive notifications for [Channel UI Name] until Channel Mute is turned off."

4. "/mute ~channel-handle" when the listed channel is already muted will unmute the listed channel.
   - System message: "[Channel UI Name] is no longer muted."

**Comment by chclaus** [comment]
Hey guys,

I think this could be my first contribution for this project. Tomorrow I'll be on a hackathon and will try to implement this very nice feature. :)

**Comment by esethna** [comment]
Sweet, thanks @chclaus!

**Comment by esethna** [comment]
Hey @chclaus, just checking in, any questions on this one?

**Comment by chclaus** [comment]
Hej @esethna it‘s in progress. I‘ve used the developers chan for info gathering ;)

But I think you have to wait a few more days until the feature is done.

**Comment by chclaus** [comment]
Hi @esethna here is a short status report: I've finished the slash command. I think I'll challenge the unit test tomorrow.

The UI extensions could take... hm... let's say a week. If you're fine with it, I will try to solve it. Otherwise I could send the PR after I've finished the unit test so that another guy can finish the rest.

**Comment by esethna** [comment]
@chclaus, awesome! That timeline is totally fine, but just so you're aware, cut-off for submitting new features for the November release is October 26, so if you'd like this in the next release the PRs have to be submitted by that date. Really looking forward to this feature!

**Comment by chclaus** [comment]
Ah. Important Info. Thanks 😃
