### ISSUE TITLE
[Help Wanted] [PLT-7364] Ability to Direct Message yourself

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7618]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7364)

1. In the "More..." DM list, your own username should be searchable.
2. If your own name is selected from the list, immediately open the direct message channel (rather than adding the name to the "Search and Add Members" box as if to start a group message) 
3. Your own name should appear with text "(you)" next to your username/full name in the 
   a) "More ..." DM list
   b) Left-hand sidebar Direct Messages section
   c) DM channel header
      - For example: "Eric Sethna (you)"
      - For Example: "eric.sethna (you)"

**Comment by cpanato** [comment]
I'm trying this one

**Comment by cpanato** [comment]
PRs:
Server: https://github.com/mattermost/mattermost-server/pull/7696
WebApp: https://github.com/mattermost/mattermost-webapp/pull/186
Redux: https://github.com/mattermost/mattermost-redux/pull/282
