### ISSUE TITLE
Inactive user can still login when sign-in method is gitlab

### ISSUE THREAD

**Issue by sergiofbsilva** [mattermost/mattermost-server#7632]
#### Summary
Inactive user can still login when sign-in method is gitlab.
The user is active and valid in gitlab but was deactivated in mattermost.

#### Steps to reproduce
Mattermost Server 4.1.0
1. Desactivate a user with Sign-in Method: Gitlab
2. The user can still login and chat in channels and with people

#### Observed behavior (that appears unintentional) 
An inactive user can login using gitlab and still chat with people and in channels.

#### Expected behavior
The user shouldn't be able to login when active in the oauth provider and inactive in mattermost.

#### Possible fixes
a simple check like [this](https://github.com/mattermost/mattermost-server/blob/v4.1.0/app/authentication.go#L76) can be added [here](https://github.com/mattermost/mattermost-server/blob/v4.1.0/app/oauth.go#L459)

**Comment by lindy65** [comment]
Hi @sergiofbsilva,

Thank you for your feedback!

Could you try upgrading to Mattermost [v4.3](https://about.mattermost.com/download/) which shipped yesterday to see whether the issue still reproduces for you?

I believe this was fixed in v4.2...

**Comment by sergiofbsilva** [comment]
Yes it is still reproducible on the latest release.

**Comment by lindy65** [comment]
Thanks @sergiofbsilva,

I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7932) to track the issue.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the Jira ticket linked above.
