### ISSUE TITLE
/invite_people: add support for username

### ISSUE THREAD

**Issue by WBTMagnum** [mattermost/mattermost-server#7638]
**Status quo**
As defined in [PLT-3131](https://mattermost.atlassian.net/browse/PLT-3131) the slash command `/invite_people` supports e-mail invites only.

**The problem**
If you use the `/invite_people` slash command with a user name, e.g. `/invite_people @username`, the following errors are reported:
* to the user: "Encountered an error sending email invite(s)"
* in the logs: "[2017/10/17 11:33:10 CEST] [EROR] InviteNewUsersToTeam: api.team.invite_members.invalid_email.app_error"

This is not helpful, since it's not obvious to the user why this error occurred.

**Proposed change**
To invite existing users to a channel or team it would be helpful if the command would also support user name resolution, e.g. `/invite_people @username`.

**Comment by lindy65** [comment]
Hi @WBTMagnum,

Thank you for your feedback,

The `/invite_people` slash command is intended for inviting people to a team to which they do not belong, hence the use of an email address.

For adding people to a channel, you can use the `members` list at the top of each channel and then click on `manage members` > `add new members` or by using the `v` to the right of the channel name and selecting `Add members`.

Does this help?

![image](https://user-images.githubusercontent.com/13020833/31708363-0c071e92-b3ef-11e7-9092-15974d0db971.png)

![image](https://user-images.githubusercontent.com/13020833/31708381-1d90698e-b3ef-11e7-8316-49311d0a412d.png)

![image](https://user-images.githubusercontent.com/13020833/31708422-3967a7d0-b3ef-11e7-8580-7d08e487a217.png)

**Comment by WBTMagnum** [comment]
Thank's for the clarification. We totally missed that. Sorry for the noise.
