### ISSUE TITLE
Export channel feature

### ISSUE THREAD

**Issue by etlweather** [mattermost/mattermost-server#7648]
I use Mattermost for Network Operations chat room. After an incident, I would like to archive the Mattermost chat with the Postmortem in my Git repository.

It would be nice to be able to export the text. Right now I scroll and scroll and then copy/paste. The text is hard to read because the threaded replies mess up the output. It is also tedious.

My preference would be a nice Markdown table with the text. Being able to provide a date/time range to export a channel content.

**Comment by lindy65** [comment]
Hi @etlweather,

Thanks for your feedback,

You can track the progress of this feature via this [ticket](https://mattermost.atlassian.net/browse/PLT-49).

We also have a [feature suggestion](https://mattermost.uservoice.com/forums/306457-general/suggestions/10907157-exporting-data) on our forum that you're welcome to add your vote to :)

**Comment by etlweather** [comment]
Thank you. I added my votes.

**Comment by lindy65** [comment]
Thanks @etlweather,

I'll close this issue off here then and we can track via the feature suggestion and ticket linked above.
