### ISSUE TITLE
Pinned Posts button should not change positions when showing the sidebar element

### ISSUE THREAD

**Issue by karlding** [mattermost/mattermost-server#7649]
#### Summary

Clicking the Pinned Posts button and showing the sidebar elements results in icons in the top bar moving positions.

#### Steps to reproduce

I tried this on the latest nightly URL in the `README.md`.

1. Log into any channel with pinned posts (I used **Reception**)
2. Hover your mouse over the Pinned Posts icon
3. Click the icon and show the right sidebar
4. Move your mouse, and then click the same icon to hide the right sidebar

#### Expected behavior

I expected that step 4 is unnecessary, since all you're doing is toggling whether the right sidebar is visible or not. I expect that I can click the same icon in quick succession without having to move my cursor.

#### Observed behavior (that appears unintentional) 

I see that the icon gets pushed to the left.

**Before**

![before](https://user-images.githubusercontent.com/6836385/31704360-c6edca58-b395-11e7-8283-739a71b7cdf2.PNG)

**After**

![after](https://user-images.githubusercontent.com/6836385/31704366-cdcbad22-b395-11e7-9031-a383122a8ae0.png)

Notice how the position of the icons have changed.

**Comment by lindy65** [comment]
Hi @karlding,

Thanks for your feedback,

What seems to be happening is that the size of the `Search` box changes when the right-hand-side is open which affects the buttons to the left of the search box (viz, channel members and pinned posts)

I've created a ticket [here](https://mattermost.atlassian.net/browse/PLT-7928) to track.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the Jira ticket linked above.
