### ISSUE TITLE
Custom emojis containing someone's username trigger mention notifications

### ISSUE THREAD

**Issue by karlding** [mattermost/mattermost-server#7670]
#### Summary

Emojis also trigger mention notifications.

#### Steps to reproduce

1. Create a custom emoji (either a username or a word that is Person A's list of words that trigger mention notifications). For example, Person A's username is `someusername`, so we create the custom emoji `someusername`
2. Have Person B use the custom emoji (`:someusername:`)

Repeat with a different emoji (say `:thinking:`) that isn't in Person A's list of words that trigger mention notifications.

I tried this on the nightly server.

#### Expected behavior

One would expect the emoji not to trigger a notification, as it is not a word.

#### Observed behavior (that appears unintentional) 

A mention notification is triggered on Person A's screen.

**Comment by lindy65** [comment]
Thanks for your report @karlding,

I've reproduced this on the nightly build server and have created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7950) to track.

**Comment by saturninoabril** [comment]
@lindy65 I guess this is similar issue on this ticket https://mattermost.atlassian.net/browse/PLT-7701 and could be solved by this PR https://github.com/mattermost/mattermost-server/pull/7663.

**Comment by lindy65** [comment]
Thanks @saturninoabril !

I didn't see that ticket when I looked earlier!

I've closed PLT-7950 as a duplicate...

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7701)
