### ISSUE TITLE
[Help Wanted] Migrate status_icon.jsx to be pure and use Redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7687]
If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/status_icon.jsx`](https://github.com/mattermost/mattermost-webapp/blob/master/components/status_icon.jsx) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://grundleborg.github.io/posts/react-component-testing-in-mattermost/). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**Comment by spiffcp** [comment]
@jasonblais I'm interested in taking a stab at this tonight. I just joined the community channel and will follow up if anything seem unclear. Thanks for providing all the detailed instructions!

**Comment by spiffcp** [comment]
After forking the web app, setting the upstream, fetching, and running initial tests, I received the following output:

![screen shot 2017-10-20 at 6 14 23 pm](https://user-images.githubusercontent.com/12717226/31843699-925eacba-b5c2-11e7-9a79-2b8243a009e6.png)

If the project is in a state of flux as far as a passing build I can still complete the issue as described. I just wanted to confirm that others were also pulling from a non passing build when starting work on redux migration tasks.

**Comment by jasonblais** [comment]
@spiffcp Yeah, some of the tests on the web app are failing, we have an in progress ticket to fix them: https://mattermost.atlassian.net/browse/PLT-7814

So you can safely ignore those for now -- we'll still expect tests to pass for `status_icon.jsx` though once submitted :) 

And thanks for your interest!

**Comment by tejasbubane** [comment]
I will work on this.

**Comment by jasonblais** [comment]
@tejasbubane Awesome, thank you!

**Comment by tejasbubane** [comment]
@jasonblais I tried working on this today - but have doubts. 

The `status_icon.jsx` component is already `pure` and it takes different statuses like userStatus, channelStatus, etc from parent components. So I think the `container` thing described [here](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) does not apply to this component - since we cannot bind the store directly to this component.

So I don't this there is anything to do here. Can anyone clarify and confirm this?

**Comment by jasonblais** [comment]
Thanks @tejasbubane! I'll check with one of our developers.

**Comment by lieut-data** [comment]
@tejasbubane is spot on here -- this component seems to have already been migrated as such in c10bc8513e822197e5af1c126bb26195baee63e8.

**Comment by jasonblais** [comment]
Thanks! I'll close this issue then, really appreciate looking into this @tejasbubane and @lieut-data
