### ISSUE TITLE
"Invalid or missing user in request body" error when saving notification prefs

### ISSUE THREAD

**Issue by Synchro** [mattermost/mattermost-server#7700]
#### Summary
"Invalid or missing user in request body" error when saving notification prefs. Using Gitlab CE 10.0.4 with embedded Mattermost 4.2.0 / postgres.

#### Steps to reproduce
* Go to account settings (either web or desktop client)
* Select notifications -> email notifications
* Click "save" button

#### Expected behavior
Notification settings are saved

#### Observed behavior (that appears unintentional) 
It displays "Invalid or missing user in request body" error.

![screen shot 2017-10-23 at 23 36 02](https://user-images.githubusercontent.com/81561/31917429-dfddf9ae-b857-11e7-8bec-0c29876ba430.png)

#### Possible fixes
Sorry, no idea.

**Comment by lindy65** [comment]
Hi @Synchro,

Thank you for the report,

We have this [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7929) to track the issue.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the Jira ticket linked above.
