### ISSUE TITLE
Don't send notifications or mark channel unread if a post is made to a comment thread that's open in right hand sidebar, and Mattermost is in focus

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7718]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4951)

Don't send desktop or push notifications and don't mark channel unread if a post is made to a comment thread that's open in right hand sidebar, and Mattermost is in focus.

Example:
1) comment thread for channel_A is open in right-hand sidebar, 
2) channel_B is open on the center pane
3) Mattermost is in focus
4) If someone posts a message on the comment thread for channel_A that is open in the right-hand side, do not send desktop and push notifications for that post, and do not bold channel_A in the left-hand sidebar.

Start of a PR here that was since closed: mattermost#6461

**Comment by sudheerDev** [comment]
@esethna I will work on this.

**Comment by jasonblais** [comment]
Yay!! Thanks @sudheerDev

**Comment by sudheerDev** [comment]
@jasonblais i forgot about this. Will check this over weekend. Into some performance PR's

**Comment by krjn** [comment]
Working on this.

**Comment by hanzei** [comment]
Thanks @krjn :+1:

**Comment by krjn** [comment]
PR here: https://github.com/mattermost/mattermost-webapp/pull/3009

**Comment by hanzei** [comment]
Wow, that was fast :rocket:

**Comment by krjn** [comment]
Ah, I started it before, and forgot to claim the issue after I was sure on a way forward.

One thing I'd have liked to do is clear the unread status of the channel in the following case:
> MM on channel #A, unfocused, with thread from #B on the RHS
  Message received on the thread on #B
  Unread status is applied on #B, because MM was unfocused
  Now, when MM receives focus, on #A, but with the thread on #B on the RHS, _if the only_ messages sent to #B were from the thread: then clear the unread

But I didn't find a quick and elegant way of doing that in short time, so I didn't extend the scope.

**Comment by hanzei** [comment]
@esethna :point_up:
