### ISSUE TITLE
Simplify build process

### ISSUE THREAD

**Issue by sokoow** [mattermost/mattermost-server#7738]
#### Summary
Can you guys simplify the build process a bit or produce a viable build tutorial. It's a bit of a nightmare at the moment and the entry point to contributing to mattermost is very high.

#### Steps to reproduce
Try to build mattermost and contribute to this repo

**Comment by ccbrown** [comment]
Sorry if you're having trouble. First and foremost, we'd love to help you out either here or on our [pre-release server](https://pre-release.mattermost.com) server if needed.

In addition to getting you up and running up and running faster, communicating the specific steps or points that you're finding difficult would go a long way towards helping us improve the documentation. Unfortunately, I think most of us believe that the [existing tutorial](https://docs.mattermost.com/developer/dev-setup.html) (referenced by the README) is actually viable, but it's hard for us to read or write these kinds of documents from the same perspective as someone who's totally unfamiliar with the tools or processes we use. So feedback from newcomers is always greatly appreciated.

Looking over them now, I do agree that there are simplifications that can be made though. We're working on eliminating the /etc/hosts edit as a requirement, I'm pretty sure edits to bash profiles are unnecessary or could be made unnecessary in most cases, and forking isn't strictly necessary either.

MacOS for example could probably be simplified to something like these (untested) steps:

1. Install [Docker](https://docs.docker.com/docker-for-mac/) and [Brew](https://brew.sh/).
2. Install additional dependencies with Brew:
    `brew install node yarn libpng go`
3. Add `127.0.0.1 dockerhost` to your /etc/hosts file:
    `getent hosts dockerhost || (echo '127.0.0.1 dockerhost' | sudo tee -a /etc/hosts)`
4. Create a directory for your source code and change to it:
    `mkdir -p $(go env GOPATH)/src/github.com/mattermost && cd "$_"`
5. Clone the server and webapp:
    `git clone https://github.com/mattermost/mattermost-server.git`
    `git clone https://github.com/mattermost/mattermost-webapp.git`

Aside from step one, which relies on Docker and Brew to have good installation guides, you just copy and paste commands. Then in another guide, we could have a "sharing your changes" guide that walks you through creating a fork.

How would you feel about that? I'm not sure it's quite the magnitude of change you were hoping for, but maybe you have other suggestions of feedback that might help us?

Thanks!

**Comment by lindy65** [comment]
Hi @sokoow 

We haven't received an update so we'll assume that the problem is fixed and help from `ccbrown` above was what you were looking for. 

If not, please reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by philippe-granet** [comment]
@sokoow @lindy65 @ccbrown 

I also have lots of problems to setup a developer machine on Win10 for push my PR https://github.com/mattermost/mattermost-webapp/pull/353

I try to build Mattermost with the current tutorial but I have had lots of errors.
Finally, I write a simple Dockerfile based on the tutorial, and all works fine, without having to install lots of tools on my computer, expect Docker.

You can find it here:
https://github.com/philippe-granet/mattermost-server/commit/1403f374964c9fdb8cc6e239eb11bcf91a965483

To use it on Windows:
- install Docker
- in a directory on your machine :
```
git clone https://github.com/{username}/mattermost-server.git
cd mattermost-server
git config core.eol lf
git config core.autocrlf input
git reset --hard HEAD
cd ..
git clone https://github.com/{username}/mattermost-webapp.git
cd mattermost-webapp
git config core.eol lf
git config core.autocrlf input
git reset --hard HEAD`
```
- launch `./mattermost-server/run.bat`
  it build docker dev image and run it
- then type `make run`
- wait Mattermost build then access to `http://localhost:8065` in your favorite navigator

This should work also on Linux ans MacOs (not tested)

**Comment by lindy65** [comment]
Thank you for posting back your solution @philippe-granet !
