### ISSUE TITLE
OSX Desktop App stuck in full screen

### ISSUE THREAD

**Issue by larsl** [mattermost/mattermost-server#7739]
#### Summary
When using Mattermost in OSX full screen mode, quitting the app, and then restarting it, one can not leave full screen mode because the necessary buttons are missing

#### Steps to reproduce
Mattermost Team edition 4.1 on OSX 10.13.
Bring the app to full screen (green button), quit and restart, try to get it into windowed mode again.

#### Expected behavior
A bar like this one should appear on top of full-screen windows
![menubar_and_today](https://user-images.githubusercontent.com/1218082/32160681-0a4d54c8-bd53-11e7-9344-0732d8864e05.jpg)

#### Observed behavior (that appears unintentional) 
No window control bar appearing

**Comment by jasonblais** [comment]
Agree, we have a ticket for it here on the desktop app repo: https://github.com/mattermost/desktop/issues/538

I believe the shortcut combination for toggling full-screen mode on Mac is CTRL+CMD+F. Let me know if that helps resolve it?

**Comment by lindy65** [comment]
Hi @larsl 

I'll close this issue off here for now and we can track via the ticket on the [desktop app repo](https://github.com/mattermost/desktop/issues/538)
