### ISSUE TITLE
Mattermost emails should set Auto-Submitted header

### ISSUE THREAD

**Issue by cpfeiffer** [mattermost/mattermost-server#7740]
#### Summary
Auto-generated emails should contain appropriate headers so that clients can handle the mails properly.

#### Steps to reproduce
Check the headers of a mattermost-generated email. They lack the `Auto-Submitted` and `Precedence` headers.

#### Expected behavior
Some MUAs automatically act on incoming emails, e.g. out-of-office agents. They try hard to send out-of-office mails only to individuals, that is, *not* to issue trackers, mailing lists or similar systems.

Mails that do not originate from individuals should be marked as auto-generated, by setting the `Auto-Submitted` header to `auto-generated` in order to make this work. Additionally one can set the header `Precedence: bulk` for compatibility with older systems.
See https://www.ietf.org/rfc/rfc3834.txt for details.

#### Observed behavior (that appears unintentional)
Out-of-office agents respond to mattermost mails.

**Comment by lindy65** [comment]
Thanks for the PR @cpfeiffer !

I'll close this issue off now that the PR has been merged :)
