### ISSUE TITLE
Mattermost v4.3.1 reports itself as v4.3.0

### ISSUE THREAD

**Issue by SmartHoneybee** [mattermost/mattermost-server#7758]
#### Summary
About Mattermost install version 4.3.1 reports itself as version 4.3.0.

#### Steps to reproduce
0. build mattermost-server/-webapp from source (using tag v.4.3.1)
1. install the result of the build
2. check the installed version in the menu

#### Expected behavior
Mattermost reports its version as 4.3.1 (Main Menu > About Mattermost > Version; log output).

#### Observed behavior (that appears unintentional) 
Mattermost reports its version as 4.3.0.

#### Possible fixes
* User error. Give pointer to source code that sets version number to 4.3.1.
* Version was not updated. Update version number in future releases.

Thanks!

**Comment by lindy65** [comment]
Thanks @SmartHoneybee,

I've created a [ticket](https://mattermost.atlassian.net/browse/PLT-8026) for our devs to look into this.

**Comment by jasonblais** [comment]
@SmartHoneybee Can you share a screenshot of your About Mattermost dialog?

**Comment by SmartHoneybee** [comment]
@lindy65 thank you!
@jasonblais sure:
![image](https://user-images.githubusercontent.com/18035422/32334673-62134c4a-bfeb-11e7-9dae-d82ceb8385a1.png)

Sorry to bother you with this. 

Which file / instruction determines the Mattermost version?
(I'd guess `model/version.go`.)
```shell
$ egrep -r '4\.3\.(0|1)'
./model/version.go:     "4.3.0",
./store/sqlstore/upgrade.go:    VERSION_4_3_0            = "4.3.0"
```

Other things that might help:
* [Mattermost binary](https://github.com/SmartHoneybee/ubiquitous-memory/releases/tag/untagged-64a5203a1a22821f95a2)
* [instructions used for build](https://github.com/SmartHoneybee/ubiquitous-memory/blob/eb0455fde5b7c3ab81529ac54d4d5d7c7926e24a/.travis.yml)
* [build log](https://travis-ci.org/SmartHoneybee/ubiquitous-memory/jobs/296006506)

**Comment by jasonblais** [comment]
@SmartHoneybee Sounds good. I found a related ticket here: https://mattermost.atlassian.net/browse/PLT-5482

We also have an open doc issue for documenting version info for server and database better, in case you want to share your feedback there: https://github.com/mattermost/docs/issues/979

Many thanks for bringing this up. I agree it is confusing and can be improved.

**Comment by SmartHoneybee** [comment]
@jasonblais thanks for sharing. Feel free to close this issue as duplicate then.
(In case I come up with a suggestion I'll post it there.)

**Comment by jasonblais** [comment]
Thanks @SmartHoneybee 👍
