### ISSUE TITLE
[Help Wanted] Migrate code_preview.jsx to be pure and use Redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7785]
If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/code_preview.jsx`](https://github.com/mattermost/mattermost-webapp/tree/master/components/code_preview.jsx) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://docs.mattermost.com/developer/webapp-component.html#testing-your-component). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**Comment by panditsavitags** [comment]
@jasonblais , I would like to take this up

**Comment by jasonblais** [comment]
Thanks @panditsavitags!

**Comment by santos22** [comment]
👋 @jasonblais 

Looks like there is a duplicate, newer issue: https://github.com/mattermost/mattermost-server/issues/9072

**Comment by jasonblais** [comment]
Good catch! Closing as a duplicate of https://github.com/mattermost/mattermost-server/issues/9072
