### ISSUE TITLE
[Help Wanted] Migrate emoji/components/delete_emoji_modal.jsx to be pure and use Redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7786]
If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/emoji/components/delete_emoji_modal.jsx`](https://github.com/mattermost/mattermost-webapp/tree/master/components/emoji/components/delete_emoji_modal.jsx) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://docs.mattermost.com/developer/webapp-component.html#testing-your-component). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**Comment by panditsavitags** [comment]
@jasonblais , i would like take this up.

**Comment by panditsavitags** [comment]
@jasonblais , Please can you help me with the functionality of this component?

**Comment by panditsavitags** [comment]
@jasonblais , I am not able to find and delete option for custom emojis, please can you let me know where on the UI can it be found?

**Comment by jasonblais** [comment]
@panditsavitags The steps are:

1) Go to System Console > Customization > Emoji
2) Enable custom emoji
3) Go back to a team
4) Click the hamburger menu next to your profile in top left corner, then click Custom Emoji
5) Add a custom emoji if one isn't added
6) You can then delete the emoji

![image](https://user-images.githubusercontent.com/13119842/33663005-33216fd0-da5c-11e7-8e3a-5162d1fc5de9.png)
