### ISSUE TITLE
[Help Wanted] Migrate filtered_user_list.jsx to be pure and use Redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7790]
If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/filtered_user_list.jsx`](https://github.com/mattermost/mattermost-webapp/tree/master/components/filtered_user_list.jsx) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://docs.mattermost.com/developer/webapp-component.html#testing-your-component). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**Comment by deveshjadon98** [comment]
I would like to work on it.

**Comment by jasonblais** [comment]
Go for it @deveshjadon98! 👍

**Comment by tejasbubane** [comment]
@jasonblais The component [is not used anywhere](https://github.com/mattermost/mattermost-webapp/search?utf8=%E2%9C%93&q=FilteredUserList&type=). Can it be removed?

**Comment by jasonblais** [comment]
Thanks @tejasbubane! I'll check with one of our developers on this one too.

**Comment by lieut-data** [comment]
I can confirm this component is not imported anywhere -- simply removing the file results in a successful webpack build. It looks like it's been dead for a while -- commit 65efd481192bd9974a8ca6e87bee6040acc37e4d (from 2016) replaced it with `SearchableUserList`. @tejasbubane, if you want to submit a PR removing this file, I think we can resolve this issue trivially :)
