### ISSUE TITLE
[Help Wanted] [PLT-840] Add option to outgoing webhooks to reply to the posted message as a comment

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7800]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-840)

Add a new JSON field in the outgoing webhook response that lets the outgoing webhook to reply to the posted message as a comment.

The name of the JSON field is "type" with options 
 - "post" if a new post is made
 - "comment" if a reply to the original message that triggered the request is made

If "type" isn't specified, the outgoing webhook response defaults to "post". This field should also be ignored in incoming webhooks.

**Comment by cpanato** [comment]
I will try this one

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-server/pull/7807
