### ISSUE TITLE
Message parsing hangs

### ISSUE THREAD

**Issue by kolis** [mattermost/mattermost-server#7803]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
The message below hangs the browser context. Chrome tab killed due to inresponsive.

#### Steps to reproduce
Paste the following message and try to post it to a channel. The message has been edited to remove information, but MM behaviour is the same as original message.

<pre>
Men vad nu :(
Nu funkar inte installern
```
(Reading database ... 24056 files and directories currently installed.)
 corrupted filesystem tarfile - corrupted package archive
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
```

Jag har testat validera den enligt https://askubuntu.com/questions/642665/how-to-inspect-and-validate-a-deb-package-before-installation
```
 new debian package, version 2.0.
 size 240215738 bytes: control archive=501259 bytes.
     176 bytes,     9 lines      control              
 1790087 bytes, 16007 lines      md5sums              
 Version: 2.21.0.0
 Section: devel
 Priority: optional
 Architecture: amd64
 Installed-Size: 1455719
 
```
</pre>

#### Expected behavior
Message should be posted to channel

#### Observed behavior (that appears unintentional) 
Javascript thread hangs

**Comment by kolis** [comment]
Server version: Version: 4.2.0
Also tested with MM desktop client: 3.7.1

**Comment by lindy65** [comment]
Hi @kolis 

Thank you for your feedback,

Could we have your help [upgrading to v4.3](https://about.mattermost.com/download/) of Mattermost to see whether the issue still reproduces?

Thanks!  and let us know how it goes :)

**Comment by kolis** [comment]
Our MM is tied to GitLab so I don't know when we are getting 4.3. I'll get back to you then if neccessary.

**Comment by lindy65** [comment]
Ah ok, thanks @kolis, appreciate it.

**Comment by lindy65** [comment]
I'll close this issue off for now @kolis 

If you still experience the issue after upgrading to the latest version, please feel free to reopen and we can help troubleshoot further.
