### ISSUE TITLE
[Help Wanted] [PLT-8093] Warning: The prop `link` is required in `GetLinkModal`, but its value is `undefined`

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7804]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8093)

Repro steps:
1) Run Mattermost from the Makefile
2) Post a file
3) Refresh the page

Observed: The following prop warning is printed to the console
![image](https://user-images.githubusercontent.com/13119842/32568459-4b3ec134-c48c-11e7-9748-ebb3f28c14d8.png)

**Comment by tkbky** [comment]
I'm on it.
