### ISSUE TITLE
Add the ability to revoke all user sessions of the system in System Console > Users

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7811]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-7854)

Proposed changes: Revoke sessions of all users in the system

In System Console > Users

A) To revoke all sessions in the system, add “Revoke All Sessions” button to the page. Useful if the admin suspects the system has been compromised and needs to neutralize the situation.

![image](https://user-images.githubusercontent.com/13119842/30710006-19129ddc-9ed2-11e7-914f-35a14a6c9d58.png)

B) Clicking this button opens a popup, similar to the “Deactivate” popup menu attached below.
Title: Revoke all sessions in the system
Help text: This action revokes all sessions in the system. All users will be logged out from all devices. Are you sure you want to revoke all sessions?
Buttons:
 - Cancel: Closes the popup, takes no action.
 - Revoke Sessions: Revokes all user sessions immediately.

![image](https://user-images.githubusercontent.com/13119842/30709999-114ec1fc-9ed2-11e7-9d41-dc725e29b4cf.png)

**Comment by cpanato** [comment]
I will work on that

**Comment by walidsebai** [comment]
can i work on this?

**Comment by rickbatka** [comment]
Fine with me, I haven't been active on this project in a while.

**Comment by walidsebai** [comment]
it seem that @cpanato  has taken care of it.

**Comment by jasonblais** [comment]
@walidsebai Actually it's up for grabs, so you're welcome to work on it if you have time :)

**Comment by walidsebai** [comment]
@jasonblais  can i work on it with somebody(i may have a friend willing to do so)? my react skill are null

**Comment by jasonblais** [comment]
@walidsebai Of course! Group work is encouraged 👍 

If your friend doesn't have time, you're welcome to ask in the [Contributors channel](https://pre-release.mattermost.com/core/channels/tickets) to see if someone is interested working with you on it :)

**Comment by jasonblais** [comment]
@walidsebai If you're worried about how to best attribute who worked on which changes, happy to discuss :)

**Comment by cpanato** [comment]
@walidsebai you can take it, I might forget that one since it was from last year. but feel free to work on that.

**Comment by walidsebai** [comment]
i'm gonna look into it

**Comment by walidsebai** [comment]
when we revoke all session, that's admin included right ?

**Comment by jasonblais** [comment]
@walidsebai That's correct 👍

**Comment by hanzei** [comment]
Hey @walidsebai,

Do you have any questions? How is your implementations going?

**Comment by walidsebai** [comment]
well i finished the go part but stuck in the testing  phase

**Comment by hanzei** [comment]
I not sure how to test the sqlstore. @lieut-data could you help with this?

**Comment by lieut-data** [comment]
@hanzei, thanks for the handoff! @walidsebai, if there's any specific questions you have, I'd be happy to help out. You might take a look at one of my active [PRs](https://github.com/mattermost/mattermost-server/blob/942645ac943e1837e59a590848f30c253f6d6edc/store/storetest/bot_store.go) that exposes a new suite of unit tests for a new store, though I suspect your case will be simpler since you're just updating an existing store's test.

**Comment by walidsebai** [comment]
i will have a look at it tonight

**Comment by lieut-data** [comment]
@walidsebai, I'm back from holidays -- feel free to ping me on community.mattermost.com (@jesse.hallam) if there's anything I can do to help :)

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by Willyfrog** [comment]
If this is again `up for grabs`, I'd like to claim it

**Comment by jasonblais** [comment]
Great, thank you @Willyfrog! Let us know if you have any questions :)

**Comment by Willyfrog** [comment]
My initial thought was that this would revoke all sessions, but while looking at all the pieces, I saw there is a filter in the list, is this filter supposed to be applied to the action? for example limiting the action to a team or a search by username?

Also, should I name the branch after PLT-7396 or MM-7854 (seems like you guys moved it from the original project) so jira can keep track of changes in github?

**Comment by jasonblais** [comment]
@Willyfrog Initially, the intent was to revoke "all" sessions regardless of the filter. However, that's a good point, I'll think about it from admin's user experience point of view and get back to you.

MM-7854 should be referenced, have updated. Good catch 👍

**Comment by jasonblais** [comment]
@Willyfrog Given

1. the primary use case (admin suspects the system has been compromised and needs to neutralize the situation),
2. revoking sessions based on the filter may lead to unclear outcomes (e.g. revoking sessions after filtering by inactive users won't really do anything)
3. revoking sessions based on the filter adds more testing overhead (more test cases, potential corner cases that are missed)

I'd propose we keep it so that all sessions are revoked, at least for this first phase. That said, I do wonder if the "Revoke All Session" button should be placed elsewhere on the page so that it's more clear it revokes everyone's sessions.

Tagging @wiersgallak in case she has additional perspectives for the admin experience.
Tagging @michaelgamble and @asaadmahmood if they have thoughts on the placement of the "Revoke All Sessions" button.

**Comment by Willyfrog** [comment]
great!
My guess in this case is outside and below the list component. Had it been affected by the filter I'd suggest to be a part of it, and even an upper placement, so it's close to the filter and the user can relate one to the other.
Also, I'd guess button's text should be something along the lines "Revoke all active sessions" so it's clear that the filter has no effect on it.

**Comment by jasonblais** [comment]
> My guess in this case is outside and below the list component. Had it been affected by the filter I'd suggest to be a part of it, and even an upper placement, so it's close to the filter and the user can relate one to the other.

This sounds good to me too. Follows the original proposal above where the button is placed outside of the list component

> Also, I'd guess button's text should be something along the lines "Revoke all active sessions" so it's clear that the filter has no effect on it.

I'm curious why the word `active` makes it more clear that it affects all sessions?

**Comment by Willyfrog** [comment]
To me, it implies there is a different filter applied, the active ones, instead of only the ones shown by the controls.
Of course a proper ux approach would require testing, but I think that can be done in parallel or afterwards

**Comment by Willyfrog** [comment]
What would be the appropiate permissions required for using this?

**Comment by jasonblais** [comment]
`PERMISSION_MANAGE_SYSTEM` seems reasonable to me 👍

**Comment by Willyfrog** [comment]
All three PRs are ready for reviewing. 
Also note that the last one (front) is failing as master redux doesn't have the new action yet. Is there a way to tell it to use the one from the branch for that test? Do I have to wait for the other PR's to merge and re-check?

**Comment by jasonblais** [comment]
Great, thank you @Willyfrog! We'll review the server and redux PRs first, followed by the webapp one :)

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/3033

Thank you very much @Willyfrog :tada:
