### ISSUE TITLE
[Help Wanted] [PLT-8102] Pinning a post causes one additional post to be loaded in the channel

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7813]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8102)

Repro steps:
1) Go to a public channel.
2) Scroll up the channel until you see "Load more messages" below the channel header
![image](https://user-images.githubusercontent.com/13119842/32680288-fa62adfe-c637-11e7-819a-fd326cd10117.png)

3) Pin the top-most message

Observed: Message is pinned to the channel but one additional post is loaded above it.
![image](https://user-images.githubusercontent.com/13119842/32680296-01ef4b2c-c638-11e7-924b-05b68d568290.png)

Expected: Message is pinned to the channel, no additional posts are loaded.

**Comment by deveshjadon98** [comment]
Working on it.

**Comment by jasonblais** [comment]
@deveshjadon98 Looks like this issue is fixed on `master`. I'll close this ticket.

Would there be another ticket you'd be interested helping with?

**Comment by deveshjadon98** [comment]
great, you can assign me any if you want. otherwise I'll browse through the issues.

**Comment by jasonblais** [comment]
@deveshjadon98 Here's a few good ones you can pick from, based on your interest:
 - https://github.com/mattermost/mattermost-server/issues/7774
 - https://github.com/mattermost/mattermost-server/issues/7316
 - https://github.com/mattermost/mattermost-server/issues/7257
 - https://github.com/mattermost/mattermost-server/issues/6283
 - https://github.com/mattermost/mattermost-server/issues/5790

Big thanks for helping on the project 👍

**Comment by deveshjadon98** [comment]
thanks @jasonblais
