### ISSUE TITLE
File upload is not working in development on master

### ISSUE THREAD

**Issue by tkbky** [mattermost/mattermost-server#7821]
#### Summary

Branch: master
Environment: development

File upload is not working.

#### Steps to reproduce

1. Check out the latest master for mattermost-server (as of this [commit](https://github.com/mattermost/mattermost-server/commit/ae8fd37332ad9f01b762ab37f5662cdd33f1e232)) & mattermost-webapp (as of this [commit](https://github.com/mattermost/mattermost-webapp/commit/2b090e3205bb2c7f2387aac294eba63d544f4342)).
2. Upload a file to any channel.

#### Expected behavior

A file can be uploaded successfully.

#### Observed behavior (that appears unintentional) 

File upload fails with the following error (shown in the browser console):

```
create_post.jsx?8c73:344 Uncaught TypeError: Cannot add/remove sealed array elements
    at Array.splice (<anonymous>)
    at CreatePost.handleFileUploadComplete (create_post.jsx?8c73:344)
    at FileUpload.fileUploadSuccess (file_upload.jsx?074b:62)
    at handleResponse (file_actions.jsx?32c2:67)
    at Request.callback (client.js?a879:618)
    at Request.eval (client.js?a879:439)
    at Request.Emitter.emit (index.js?624f:137)
    at XMLHttpRequest.xhr.onreadystatechange (client.js?a879:712)
```

**Comment by saturninoabril** [comment]
Thanks for your report! 
I am able to repo the same and have created a ticket at [Jira](https://mattermost.atlassian.net/browse/PLT-8121). 
I am closing this issue as it will be tracked there.

Again, thanks!

**Comment by saturninoabril** [comment]
Got an info from @jwilander that this was recently fix by this latest commit - https://github.com/mattermost/mattermost-webapp/pull/265
