### ISSUE TITLE
Thumbnails are too small and not configurable

### ISSUE THREAD

**Issue by tareko** [mattermost/mattermost-server#7822]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Image thumbnails are too small and not configurable. This means they are only really usable by clicking into them. It appears that a configuration setting for the width of thumbnails was removed several months ago.

#### Steps to reproduce
Post any image.

#### Expected behavior
Thumbnail should either be bigger so as to give true idea of the image (look at Slack and Whatsapp for examples) or should be configurable so it can be scaled up as needed.

#### Observed behavior (that appears unintentional) 
Images are too small

#### Possible fixes
Double (or more) the size of the thumbnail, or offer a configuration option to allow users to change the size as needed.

**Comment by esetera** [comment]
Just an extra piece of detail.. images appear too small when:

-  the image is **uploaded** to mattermost from any device

- the image is added by **including as an img url** from the mattermost app

When an image is added as an image url using a desktop browser, then it appears in the larger (desired) format.  Which is to say, the behaviour currently is inconsistent.

We would prefer the larger format to be the default for any method, but a config option would also be great as mentioned above.

**Comment by esethna** [comment]
Thanks @tareko @esetera for the feedback. We are definitely aware of the visual issues with image thumbnails and we are actually planning on implementing improvements over the next few releases. You can track the progress here of the first phase of implementation here: https://mattermost.atlassian.net/browse/PLT-7939

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the Jira ticket linked above.
