### ISSUE TITLE
List of pinned posts does not refresh when changing channel

### ISSUE THREAD

**Issue by tareko** [mattermost/mattermost-server#7823]
#### Summary
When a list of pinned posts is loaded, it does not refresh when a channel is changed to the pinned posts of that channel.

#### Steps to reproduce
* Click on "pinned posts" to load list of pinned posts for list.
* Change channel

#### Expected behavior
The pinned posts of the new channel should appear in the list of pinned posts

#### Observed behavior (that appears unintentional) 
The pinned posts of the *previous* channel appear in the list of pinned posts

#### Possible fixes
A refresh of the pinned post list should be triggered with channel change.

tarek : )

**Comment by lindy65** [comment]
Hi @tareko,

Thanks for your feedback!

This is something our UX team has been discussing and feel that having some types of right-hand-side content follow the current channel is desired. 

At other times, you wouldn't want the content in the right-hand-side to follow the current channel - e.g. for the selected thread or search.

We're also discussing whether to move the channel info or member list into the right-hand-side and, for example, we would expect these to be matched to the current channel (similar to pinned posts).

So, just wanted to let you know that there are discussions happening about these behaviors.  In the meantime, please feel free to open a [feature suggestion](https://mattermost.uservoice.com/forums/306457-general) which can be up-voted by yourself and others up to 10 times.

Thanks!

**Comment by lindy65** [comment]
I'll close this issue off here for now.  Please feel free to open a feature suggestion via the link above.
