### ISSUE TITLE
[bug][major] Message aren't sent in Direct message channel created via ctrl+k

### ISSUE THREAD

**Issue by giladgd** [mattermost/mattermost-server#7824]
#### Summary
Creating a new direct message channel via ctrl+k creates a channel in which sending a message result in being shown as sent without being sent

#### Steps to reproduce
1. create a new user userA in Mattermost
2. ‎create a new user userB in Mattermost
3. ‎log in to userA
4. ‎hit ctrl+K
5. ‎type the name of userB
6. ‎press enter - you'll see that the direct message channel is created in the sodebar but isn't focused and the ctrl+K windows is still open - this is another bug
7. ‎click with the mouse in the ctrl+K window, delete one character,and when the result is shown press enter again
8. ‎send some messages in the channel OR switch to another channel or direct message channel and send some messages there
9. ‎hit ctrl+shift+R and see that the messages wasn't sent at all

#### Expected behavior
The messages should be sent, and after hitting ctrl+shift+R they should still appear in the channel as sent by you

#### Observed behavior (that appears unintentional) 
The messages are shown as sent without being sent. Changing teams or channels won't help, trying to send message in any channel will show the message as sent without being sent. This is very frustrating

#### Possible fixes
It's probably a bug in the webapp.
Show a loading icon while the message is being sent and then a one tick for a sent message, like in Telegram.

**Comment by jasonblais** [comment]
Thanks @giladgd! This was actually fixed in 4.3.2, released on Friday and available for download: https://about.mattermost.com/download

**Comment by lindy65** [comment]
I'll close this issue off for now. Please feel free to reopen if you are still experiencing issues after downloading the latest version.  Thanks!

**Comment by giladgd** [comment]
I have checked and it seems that the issue has been fixed in the latest version.
Thank you! :)
