### ISSUE TITLE
AmazonS3Region defaults to us-east-1 no matter what AmazonS3Endpoint is set

### ISSUE THREAD

**Issue by mogul** [mattermost/mattermost-server#7829]
#### Summary
AmazonS3Region default doesn't match docs, which prevents S3 buckets in regions other than `us-east-1` from working.

#### Steps to reproduce

Given I set an `AmazonS3Endpoint` value of `s3-us-gov-west-1.amazonaws.com` 
When I try to attach a file to a post
Then I see the message: 
  `Encountered an error writing to S3` 
And in the logs I see: 
  `2017-11-13T19:00:13.64-0800 [APP/PROC/WEB/0] OUT [2017/11/14 03:00:13 UTC] [EROR] /api/v4/files:WriteFile code=500 rid=jm7ahpex3pnbpr9zix5eqfdgze uid=[redacted] ip=24.4.182.240 Encountered an error writing to S3 [details: The AWS Access Key Id you provided does not exist in our records.]`

#### Expected behavior

Given I set an `AmazonS3Endpoint` value of `s3-us-gov-west-1.amazonaws.com` 
When I try to attach a file to a post
Then I see the file attached to the draft post.

#### Observed behavior (that appears unintentional) 

Given default values in the config file, Mattermost is supposed to query the S3 endpoint for the correct region to use, and only fall back to `us-east-1` if that's not possible. If I clear the `AmazonS3Region`, Mattermost does that and everything works fine. There's no reason to set this default to anything other than ""! Doing so only causes problems for people like me who aren't using the US East region; there's no reason to risk the Endpoint and Region being out of sync.

#### Possible fixes

[This line](https://github.com/mattermost/mattermost-server/blob/master/config/default.json#L132) should have a value of `""`:

**Comment by lindy65** [comment]
Hi @mogul,

Thanks for the report and pull request!  I see you have signed the CLA - appreciated :)

Our devs will take a look at your PR as soon as they're able.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the PR linked above.
