### ISSUE TITLE
"No such file or directory .../mattermost-server/package.json" when trying to run tests

### ISSUE THREAD

**Issue by robinj** [mattermost/mattermost-server#7831]
#### Summary
When running `make test` or `make test-client` the tests fail to run for the webapp

#### Steps to reproduce
1. Follow the developer [setup](https://docs.mattermost.com/developer/dev-setup-ubuntu-1604.html)
2. Compile Mattermost using the [instructions](https://docs.mattermost.com/developer/dev-setup-compiling.html)
3. Run the tests as per the [developer flow](https://docs.mattermost.com/developer/developer-flow.html)
4. Tests fail to run

#### Expected behavior
The tests run successfully

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

Note: Someone else appears to have encountered this issue on the [forum](https://forum.mattermost.org/t/mattermost-separating-platform-into-two-repositories-on-september-6th/3708/10) but the proposed solution was to not run the whole test pack. 

```
[2017/11/14 22:27:23 GMT] [DEBG] Hub for index 14 is starting with goroutine 2253
[2017/11/14 22:27:23 GMT] [DEBG] Hub for index 15 is starting with goroutine 2254
npm ERR! path /home/robin/go/src/github.com/mattermost/mattermost-server/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/robin/go/src/github.com/mattermost/mattermost-server/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robin/.npm/_logs/2017-11-14T22_27_23_472Z-debug.log
Client Tests failed
exit status 1
make[1]: *** [internal-test-web-client] Error 1
make[1]: Leaving directory `/home/robin/go/src/github.com/mattermost/mattermost-server'
make: *** [test] Error 2
```

[2017-11-14T22_27_23_472Z-debug.log](https://github.com/mattermost/mattermost-server/files/1471194/2017-11-14T22_27_23_472Z-debug.log)

#### Possible fixes
No idea

#### Additional info
```
$ npm -v && node -v && docker -v
5.5.1
v9.1.0
Docker version 17.09.0-ce, build afdb6d4

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

This same error is reproducible on my Windows 10 machine

**Comment by saturninoabril** [comment]
This will be solved after this PR https://github.com/mattermost/mattermost-webapp/pull/303 gets merged.

I'm closing this ticket. Thanks!
