### ISSUE TITLE
[Help Wanted] [PLT-6309] Integrations: Use overwritten username in email and push notifications

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7832]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6309)

**Current behaviour**: 

When someone sets up an incoming webhook with an overwritten username, the webhook post is posted with that username.

However, email and push notifications continue to use the webhook creator's username.

**Proposed change**:

Use the overwritten username in email and push notifications

**Comment by cpanato** [comment]
i will work on this

**Comment by cpanato** [comment]
any update on this @jasonblais  ?

**Comment by jasonblais** [comment]
@cpanato It hasn't been tested yet, but once it is, the JIRA ticket will be closed if it's fixed (and I'll close this ticket)

**Comment by cpanato** [comment]
asking that, because I'm doing my trello planning 😄

**Comment by lindalumitchell** [comment]
@cpanato I tested and verified the JIRA ticket; email and push notifications now display the webhook's overriding username. No issues found!
