### ISSUE TITLE
hostname search failed in Mattermost

### ISSUE THREAD

**Issue by 6a7070** [mattermost/mattermost-server#7834]
#### Summary
When searching historical messages in Mattermost, the search engine does not return results for messages that involve only an FQDNs (ex. hostname.test.com) IF a part of the hostname is used as the search query.

#### Steps to reproduce
Setup 2 users. Have user1 message user2 with the message `hostname.test.com`. Have user2 search for `hostna` or `hostname`. 

#### Expected behavior
Ideally the user would see in the search results -- an entry for `hostname.test.com`.

#### Observed behavior (that appears unintentional) 
Instead, no results will be returned. User2 can search for `hostname.test.com` and find results, but this is not desired functionality. 

#### Possible fixes
Not familiar with code base.

**Comment by lindy65** [comment]
Hi @6a7070,

Thanks for your feedback!

Currently, search defaults to full-word matching.  For your example above, try using `hostna*` or `hostname*` which should return results.

**Comment by lindy65** [comment]
I'll close this issue off for now, please feel free to re-open if you have further questions or issues.
