### ISSUE TITLE
Mattermost behind Basic Auth

### ISSUE THREAD

**Issue by chumbalum** [mattermost/mattermost-server#7836]
#### Summary
We would like to use Mattermost behind Basic Auth, which unfortunately doesn't work without problems. Also, the behaviour differs between browsers. Especially Chrome and therefore the Mattermost Desktop Clients won't work well together with this scenario.

The issue seems to come from the websocket connection which is initiated after the root page is loaded. It seems that previously entered basic auth information are not passed in the initiating request for the websocket connection. The websocket requests use some kind of Bearer Authorization header and therefore does not propagate the Basic Auth Header. This will result in additional Basic Auth prompts in the browser. Reloading the page will then show the Mattermost login dialog. After submitting the login form, nothing happens because the websocket is still somewhat unauthenticated. Reloading the page again will finally show the chat (this behaviour differs between browsers).

#### Steps to reproduce
Ubuntu 16.04
Mattermost 4.3
Nginx Proxy with enabled Basic Auth
Use Chrome (62.0.3202.94) to access the Mattermost server
Authentication issues leads to bad behaviour

#### Expected behavior
Access the Mattermost server without any authentication issues

#### Observed behavior (that appears unintentional) 
Browsing to root page is guided by authentication issues which will prevent the page to initialize 100%. After some refreshs and basic auth prompts, page is shown (with login dialog). After Mattermost login, nothing happens because websocket requests are unauthenticated (missing Basic Auth header). Refreshing again finally shows chat window.

#### Possible fixes
I guess this may be complicated because the websocket connection uses other authentication mechanism with some kind of token or so? So unfortunately I can't give any tipps.

**Comment by esethna** [comment]
Thanks for the suggestion @chumbalum. Can I please ask your help in opening a [feature idea on our forum](https://mattermost.uservoice.com/forums/306457-general) and moving the discussion there? This isn't something we currently support but I can understand how this would be a requirement for certain companies.

**Comment by chumbalum** [comment]
Yeah, I can take that idea to the forums

**Comment by lindy65** [comment]
Thanks @chumbalum!

Please post a link to your feature request back here for continuity?

**Comment by chumbalum** [comment]
Hi @lindy65 

I created a feature suggestion: https://mattermost.uservoice.com/forums/306457-general/suggestions/32320387-support-mattermost-behind-basic-auth

greetings,
chumbalum

**Comment by lindy65** [comment]
Thanks so much @chumbalum :)

I'll close this issue off here for now and we can track progress via the suggestion linked above...

**Comment by xiaotuanyu120** [comment]
How is the feature going? I meet this problem too.
