### ISSUE TITLE
[Help Wanted] [PLT-8212] Team name can be edited to be only one character long

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7874]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8212)

Repro:

1) Main Menu > Create a Team
2) Try to enter a team name with just one character 
 --> observed: Error text: "Name must be 2 or more characters up to a maximum of 15. You can add a longer team description later."
3) Enter a team name with 2 to 15 characters and complete the team creation flow.
4) Main Menu > Team Settings > Team Name
5) Edit the name to be "a", then hit Save

Observed: Team name saved
Expected: Same error text from step 2.

NOTE: This should only be changed client-side, so that one-character team names aren't impacted by this change.

**Comment by pruthvip** [comment]
Will give it a try

**Comment by lindalumitchell** [comment]
Thanks @pruthvip, looks great! Closing this issue, as https://github.com/mattermost/mattermost-webapp/pull/351 has been merged.

**Comment by pruthvip** [comment]
@lindalumitchell merging [#351](https://github.com/mattermost/mattermost-webapp/pull/351) had created a bug. Fix for the bug was pushed in [#478](https://github.com/mattermost/mattermost-webapp/pull/478). The fix is not merged yet.

**Comment by lindalumitchell** [comment]
Ah, thanks @pruthvip, I missed that. I'll reopen this one then, until that fix is merged. Thanks for letting me know!
