### ISSUE TITLE
[Help Wanted] [PLT-8186] Add support for AWS Identity and Access Management (IAM) role, and add a button to test AWS connection

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7875]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8186)

Currently, you must manually specify the secret and access key to authenticate to S3.

*PROPOSED CHANGE*

By default use instance profiles via IAM roles to authenticate to S3, instead of a secret and access key which remain as an optional auth method. This is the recommended best practice from AWS as it allows for auto-rotation of keys: http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html

The benefit to instance profiles is that the code will create new keys under the covers every 15 minutes, thus providing a much higher level of security. It also simplifies initial admin setup and maintenance.

*IMPLEMENTATION DETAILS*

1) Start of a PR can be found here: https://github.com/mattermost/mattermost-server/pull/6927

2) The feature should be in TE and EE

3) No System Console setting will be added for IAM roles. Instead use IAM roles by default, unless the admin has configured the AWS secret and access key.

4) Update help text for AWS secret and access key, and move them below Amazon S3 Bucket and Amazon S3 Endpoint since the two settings are now optional. This is in System Console > Files > Storage.
 - Amazon S3 Access Key ID: (Optional) Only required if you do not want to authenticate to S3 using an IAM role. Enter the Access Key ID provided by your Amazon EC2 administrator.
 - Amazon S3 Secret Access Key: (Optional) The secret access key associated with your Amazon S3 Access Key ID. 

Note that "IAM role" in the Amazon S3 Access Key ID help text should link to https://about.mattermost.com/default-iam-role. This will in turn redirect to https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html

5) Add a “Test Connection” button below the Amazon S3 fields. Clicking the button will attempt to authenticate and connect to the S3 instance.

If successful, “Connection was successful.” appears below the “Test Connection” button.
If not successful, “Connection unsuccessful: [Error message]” appears where the error message comes from S3 to help the user debug what failed.

See an example "Test Connection" button implementation in System Console > Notifications > Email.

**Comment by cpanato** [comment]
I will take this one

**Comment by cpanato** [comment]
PRs:
- https://github.com/mattermost/mattermost-redux/pull/400
- https://github.com/mattermost/mattermost-webapp/pull/772
- https://github.com/mattermost/mattermost-server/pull/8243

**Comment by jasonblais** [comment]
Thanks @cpanato!
