### ISSUE TITLE
[Help Wanted] [PLT-7537] Post a system message when a channel is moved between teams

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7876]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7537)

There is a CLI command to move channels from one team to another. This ticket is to have a System Message that gets posted in the affected channel when it has been moved to a different team by the CLI command:

```
"This channel has been moved to this team from {old_team}."
```

**Comment by liusy182** [comment]
A similar function for posting system message is [PostRemoveFromChannelMessage](https://github.com/mattermost/mattermost-server/blob/master/app/channel.go#L1081). When this is invoked by system command `platform`.  `model.Post` struct field `UserId` is empty string which result to posting erroring out early.

My question is, is the behavior acceptable if "moving channel" posts system message when it is coming from rest API (which does not exist today), but NOT post system message when it is invoked by `platform channel` command?

**Comment by vordimous** [comment]
my PR addresses CLI message. but also implements a test. I will add a message posted into the actual channel.

**Comment by vordimous** [comment]
I updated the PR. I don't think it is possible to post a message to the channel from a command line argument since there is no current logged in user when executing commands form the CLI. I implemented an update to the header instead. So when moving a channel the header will have the desired message appended to it and a user can adjust it from there.

**Comment by jasonblais** [comment]
Thanks @vordimous!
