### ISSUE TITLE
[Help Wanted] [PLT-8185] User should be notified consistently when deleting parent post from RHS

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7878]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8185)

Currently, if I click to delete a parent post from center or reply RHS, I see a confirmation modal that tells me how many comments the parent post has.

But if I click to delete a parent post from RHS flagged, pinned, search, or recent mentions, the confirmation modal does not tell me how many comments the parent post has. Would be better if the behavior were consistent, and the number of comments displayed regardless of where the delete was initiated.

1. Flag a message
2. Reply to the message
3. Click flag icon to display flagged posts RHS
4. In RHS, click [...] > Delete

Observed: Confirmation modal says "Are you sure you want to delete this post?"
![image](https://user-images.githubusercontent.com/13119842/33092303-c371328c-cec7-11e7-8bc9-9663374c0538.png)

Expected: Confirmation modal says "Are you sure you want to delete this post?" with additional line "This post has 1 comment on it."
![image](https://user-images.githubusercontent.com/13119842/33092307-c840f612-cec7-11e7-9b69-a86d1a4bf7f4.png)

**Comment by sudheerDev** [comment]
@esethna I can take this up.

**Comment by esethna** [comment]
Thanks @sudheerDev!

**Comment by lindalumitchell** [comment]
Thanks @sudheerDev! Closing, as https://github.com/mattermost/mattermost-webapp/pull/372 has been merged.
