### ISSUE TITLE
[Help Wanted] [PLT-8173] Add username and profile picture to webhook set up pages

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7880]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8173)

On the pages used to add and edit incoming and outgoing webhooks, add the following settings to the bottom of the page: 

Username 
(Optional) Choose the username this integration will post as. Usernames can be up to 22 characters, and may contain lowercase letters, numbers and the symbols "-", "_", and "." .

Profile Picture 
(Optional) Choose the profile picture this integration will use when posting. Enter the URL of a .png or .jpg file at least 128 pixels by 128 pixels.

---

These settings should only appear if the respective config settings "EnablePostUsernameOverride" and "EnablePostIconOverride" are set to true. 

When set, this integration should use the given username and icon for posting, unless: 
 1. The config settings "EnablePostUsernameOverride" and "EnablePostIconOverride" are changed to false
 2. The webhook payload specifies a different username or icon

**Comment by jwilander** [comment]
There's no server support for this yet so the server will need changes first (mainly new DB columns).

**Comment by lieut-data** [comment]
Heads up that I'm tackling this issue at the moment.

**Comment by lindalumitchell** [comment]
These incoming webhooks changes have been merged and tested on master and look great! Closing this issue.
