### ISSUE TITLE
[Help Wanted] [PLT-8024] Support LOGIN authentication method for SMTP

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7881]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8024)

Difficulty: Intermediate

Currently, Mattermost only supports PLAIN authentication methods. However, there are two other ones as well, LOGIN and CRAM-MD5 (http://www.samlogic.net/articles/smtp-commands-reference-auth.htm).

The Outlook Web App doesn't support the PLAIN authentication method, and thus email notifications with an OWA enabled account fails. We'll need to add handling for the LOGIN method to support OWA. 

Go doesn't support it by default, but someone posted a [Gist](https://gist.github.com/andelf/5118732) of how to implement it fairly easily. We should aim to cover this feature with automated tests since we have a simulated mail server that runs during the tests.

See the GitHub issue: https://github.com/mattermost/mattermost-server/issues/7578 and discussion in Peer-to-Peer Help channel: https://pre-release.mattermost.com/core/pl/ik6rjyr9dtgptbwutt7a4qqzih

**Comment by cpanato** [comment]
I guess i can take this one

**Comment by jasonblais** [comment]
Thanks @cpanato! :)
