### ISSUE TITLE
[Help Wanted] [PLT-7972] Ability to reset your own password via System Console Users List

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7882]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7972)

Repro:

1) Sign in as a system admin
2) Go to System Console > Users and find yourself from the users list
3) Click "Reset Password"
4) Enter a new password and hit Enter

Observed: Error "Invalid or missing current_password in request body" as it expects for the current password
![image](https://user-images.githubusercontent.com/13119842/33100972-5f66091c-cee4-11e7-813a-761f5361e9b5.png)

Expected: Ask for the current password letting the password update be successful.

![image](https://user-images.githubusercontent.com/13119842/33341204-3b9f80c2-d44c-11e7-9307-a3ccdbd7351e.png)

**Comment by cpanato** [comment]
I will work on that

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-server/pull/7895

**Comment by cpanato** [comment]
this is the new pr based on the comments in the old PR : https://github.com/mattermost/mattermost-webapp/pull/389
