### ISSUE TITLE
[Help Wanted] [PLT-8214] Add "Add reaction" tooltip when hovering over the plus-icon for reactions

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7890]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8214)

Right now when you hover over the plus icon for emoji reactions, there is no tooltip.

Propose we add one with text "Add reaction". The style should match the tooltip for flags.

![image](https://user-images.githubusercontent.com/13119842/33104557-cfd5e570-cef6-11e7-94f6-dce4fffb3ccd.png)

![image](https://user-images.githubusercontent.com/13119842/33104563-d41eddbc-cef6-11e7-940a-bc57d6cb9da4.png)

**Comment by jasonblais** [comment]
@R-Wang97 Curious if you'd interested taking a look, given you added the "+" icon for emoji reactions.

I really like the feature by the way, nice work 👍

**Comment by R-Wang97** [comment]
@jasonblais I'd love to take a look!

**Comment by lindalumitchell** [comment]
Thanks @R-Wang97! Closing, as https://github.com/mattermost/mattermost-webapp/pull/354 has been merged. Looks great!
