### ISSUE TITLE
Ability to change own message background color

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#7894]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Ability to change own message background color

#### Steps to reproduce

Applicable on all versions from what I can see, no option to change this value.

Version: 4.4.0  (4.4.1)

#### Expected behavior

An option under Account Settings -> Display -> Theme with the option to change your own message background.

#### Observed behavior (that appears unintentional) 

No option currently to do this.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

post__body is the css variable(?) that needs to hold this value (?)

**Comment by lindy65** [comment]
Hi @arjitc 

Thanks for your feedback,

This feature is not yet available,

Could we have your help opening a feature suggestion on our [forum](https://mattermost.uservoice.com/forums/306457-general) where you and others can up-vote it up to 10 times to increase its popularity?

Thanks!

**Comment by lindy65** [comment]
Hi @arjitc,

For continuity and tracking, could you help share back the link to the feature suggestion once you've opened it on our forum please?

**Comment by arjitc** [comment]
I gave a +1 to https://github.com/mattermost/mattermost-server/issues/5072 :)

**Comment by lindy65** [comment]
Awesome, thanks so much @arjitc :)

I'll close this issue off here then and we can track via the UserVoice issues linked above.
