### ISSUE TITLE
How to Remove About Tab for MatterMost

### ISSUE THREAD

**Issue by deletedaccount2902031** [mattermost/mattermost-server#7896]
How do you remove the about tab on Mattermost server?

![image](https://user-images.githubusercontent.com/23587022/33159953-66b02dbc-cfe6-11e7-9b73-08cb9235f497.png)

**Comment by MusikPolice** [comment]
The About Tab is implemented by `mattermost-webapp`, not by `mattermost-server`. There is no way to remove it, short of forking and modifying the code. What are you trying to accomplish? There may be a different solution to your problem that we can help with.

**Comment by GlobalVPS** [comment]
@MusikPolice My question would be how would you change the webapp files from downloading the server, to change the about tab.

**Comment by MusikPolice** [comment]
If you want to change the information presented on the About Modal, you'd have to fork the `mattermost-webapp` project and make your changes in [about_build_modal.jsx](https://github.com/mattermost/mattermost-webapp/blob/master/components/about_build_modal/about_build_modal.jsx#L17-L16)

**Comment by GlobalVPS** [comment]
How would you put it with the server?

**Comment by GlobalVPS** [comment]
and how would I make licenses?

**Comment by MusikPolice** [comment]
If you're interesting in forking and modifying Mattermost, I'd suggest that you take a read through our [developer documentation](https://docs.mattermost.com/guides/developer.html). It will answer a lot of your questions. You can also consider joining our [pre-release chat](http://pre-release.mattermost.com/) if you need to ask questions. 

If you want to license Mattermost to get access to our E10/E20 features, you can check out [our pricing](https://about.mattermost.com/pricing/).

**Comment by lfbrock** [comment]
Just to summarize the conversation on pre-release for anyone else reading, you can modify the webapp with the following steps: 

1. Install the Mattermost server by following one of our installation guides
2. Fork the [mattermost-webapp](https://github.com/mattermost/mattermost-webapp) repository
3. Make your changes 
4. Run ``make package`` to create ``mattermost-webapp.tar.gz``
5. Copy ``mattermost-webapp-tar.gz`` to the location Mattermost was installed in Step 1
6. Remove the existing ``client`` folder
7. Run ``tar -xvf mattermost-webapp.tar.gz`` to extract your new customized ``client`` folder
8. Restart your Mattermost server 

Have a pull request here to add this to our documentation: https://github.com/mattermost/docs/pull/1652

**Comment by lindy65** [comment]
Hi @GlobalVPS,

Have `MusikPolice` and `lfbrock` addressed your questions?  Can I close this issue off?

**Comment by lindy65** [comment]
Hi @deletedaccount2902031,

I'll close off this issue for now.  Feel free to reopen if you still have questions.
