### ISSUE TITLE
MM_*SETTING_* environment variable settings only apply if there is an entry in config.json to override

### ISSUE THREAD

**Issue by bjjccl** [mattermost/mattermost-server#7898]
#### Summary
Environment variable configuration options don't apply unless there is an entry for the same configuration option on config.json.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Using GitLab Mattermost Version 4.2.0 (4.2.1), Build Hash: c0aafbcdc221970054869b6c03db77c1dcc63289

#### Expected behavior
I would like to set the Android App Download Link via environment variable as config.json is being managed by a different tool in my deployment (GitLab omnibus).
I expect to be able to run `MM_NATIVEAPPSETTINGS_ANDROIDAPPDOWNLOADLINK=https://example.com/foo platform` and find that the AndroidAppDownloadLink is set to `https://example.com/foo`.
However, when trying to set this, I find that the environment variable is ignored, and the default is used instead.

#### Observed behavior (that appears unintentional) 
- Select a configuration option which by default does not have an entry in config.json (e.g. I am using `NativeAppSettings/AndroidAppDownloadLink`).
- Launch Mattermost with the environment variable set, e.g. `MM_NATIVEAPPSETTINGS_ANDROIDAPPDOWNLOADLINK=https://example.com/foo platform -c test_config.json`
- In the Mattermost webapp, go to the System Console and observe that the default is used (https://about.mattermost.com/mattermost-android-app/) instead of our provided option 
- Change the setting to something else (e.g. make it blank) and save, causing test_config.json to be updated with entries for `AndroidAppDownloadLink.`
- Observe that the setting changes to https://example.com/foo (our provided option)

Thanks!

**Comment by bbodenmiller** [comment]
Having the same problem here

**Comment by lindy65** [comment]
Hi @bjjccl and @bbodenmiller,

Thanks for your feedback,

I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8264) for our devs to investigate.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above.
