### ISSUE TITLE
Favicon almost invisible on dark browser themes

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-server#7904]
#### Summary
When using e.g. Firefox 57's built-in "dark" theme, the favicon is almost invisible if the tab is not focused.

![image](https://user-images.githubusercontent.com/179599/33239020-90bcbdb8-d299-11e7-8159-7ef8a57736c6.png)

#### Steps to reproduce
Enable the "dark" theme in Firefox 57+ and open Mattermost.

#### Expected behavior
A favicon is visible.

#### Observed behavior (that appears unintentional) 
The favicon is almost impossible to see

#### Possible fixes
Use a brighter favicon or add an outline so it's well-visible on both bright and dark backgrounds.
The favicon of the Firefox Addons Manager (also included in the screenshot above) is actually a good example for this.

**Comment by lindy65** [comment]
Hi @ThiefMaster,

Thanks for your feedback!

I've created a ticket [here](https://mattermost.atlassian.net/browse/PLT-8232) for our UI/UX team to look into.

**Comment by lindy65** [comment]
I'll close this issue off here for now @ThiefMaster and we can track via the ticket linked above.
