### ISSUE TITLE
Emoji suggestions popup has thumbs up/down icons in an inconvenient order

### ISSUE THREAD

**Issue by dimsuz** [mattermost/mattermost-server#7906]
#### Summary
Emoji suggestions popup has thumbs up/down icons in an inconvenient order

#### Steps to reproduce
Open any channel
Type ":thumb" to cause emoji suggestions to show up

#### Expected behavior
👍 emoji should come first and is preselected because this is obviously a most often used one compared to 👎 .

#### Observed behavior (that appears unintentional) 
👎 comes first and preselected in the completion list which causes it to be wrongly inserted sometimes.

![screenshot from 2017-11-26 21-45-43](https://user-images.githubusercontent.com/42920/33243745-8ee7adc6-d2f4-11e7-9063-0a8d60ba23fb.png)

**Comment by esethna** [comment]
Thanks @dimsuz, totally makes sense, would you be interested in contributing this change? I've created a proposed help wanted ticket here: https://mattermost.atlassian.net/browse/PLT-8234

**Comment by dimsuz** [comment]
I don't think I could do that soon enough as I'm not a frontend dev, know only a little about how React works. Currently involved in Android apps development mostly...

**Comment by lindy65** [comment]
Thanks @dimsuz,

I'll close this issue off here and we can track via the ticket linked above.

**Comment by stephenkiers** [comment]
So, I can't comment on the atlassian ticket, but this seems to be fixed in the latest version

**Comment by stephenkiers** [comment]
![screen shot 2017-12-20 at 1 06 16 am](https://user-images.githubusercontent.com/1245512/34197065-16d2414e-e522-11e7-94f0-7e0d36382c8e.png)

**Comment by lindy65** [comment]
Hi @stephenkiers, 

Yes, it is indeed fixed in the latest version.  I'll alert the product manager so he can resolve the Jira ticket.

Thanks!

**Comment by dimsuz** [comment]
Wait, the screenshot above shows a different popup, the one on the smiley button. This issue is about the popup which is shown when **typing** emoji by hand. Did you try exact reproduction steps described above?

**Comment by lindy65** [comment]
Ah, you are quite correct @dimsuz !  

I've reopened this issue and un-commented on the Jira ticket :)  Thanks for the nudge on repro steps!

**Comment by stephenkiers** [comment]
Ahh, I misread the problem here. Thanks for confirming. I was wondering when the UI had changed to the list view from just thumbnails. My mistake. Thanks

**Comment by lindy65** [comment]
No worries @stephenkiers :)

Not sure why I reopened this issue though as previously I'd closed it saying we'd track via the Jira ticket - so I'll close it off again! ;)

**Comment by dimsuz** [comment]
Thanks everyone for quick reaction! :)
