### ISSUE TITLE
How to upload a file using the V4 API ?

### ISSUE THREAD

**Issue by kajkocar** [mattermost/mattermost-server#7907]
Could you provide a simple example about how to do it ?
Documentation over at: [https://api.mattermost.com/v4/#tag/files](https://api.mattermost.com/v4/#tag/files) did not explain it at all.

Regards,
Sasa Kajic

**Comment by jwilander** [comment]
Hi @kajkocar,

It's a standard `multipart/form-data` POST request using the fields mentioned in the reference. Here's an example of what it might look like:

```
POST /api/v4/files HTTP/1.1
Host: localhost:8065
Connection: keep-alive
Content-Length: 444
Accept: application/json
Authorization: bearer <your token here>
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary5a5WIBBw6R9BjHO7

------WebKitFormBoundary5a5WIBBw6R9BjHO7
Content-Disposition: form-data; name="files"; filename="test.txt"
Content-Type: text/plain

<your file content here>
------WebKitFormBoundary5a5WIBBw6R9BjHO7
Content-Disposition: form-data; name="channel_id"

<your channel id here>
------WebKitFormBoundary5a5WIBBw6R9BjHO7
Content-Disposition: form-data; name="client_ids"

<your optional client ids here>
------WebKitFormBoundary5a5WIBBw6R9BjHO7--
```

**Comment by lindy65** [comment]
Hi @kajkocar,

Does the example above from `jwilander` help solve your issue?

**Comment by kajkocar** [comment]
Hi @lindy65 and @jwilander 
I am sorry for late reply, and Yes, this has solved my problem.
For anyone else interested in how to do it in c#, here is snippet from my project:
Function returns ID of uploaded file.
Error handling omitted.
`
 public string UploadFile(string fileName, string channelID)
        {
            HttpRequestMessage pst = makeRequestMessage(HttpMethod.Post, Constants.MM_FILES);
            MultipartFormDataContent form = new MultipartFormDataContent();
            byte[] imagebytearraystring = File.ReadAllBytes(fileName);
            form.Add(new StringContent(channelID), "channel_id");
            form.Add(new ByteArrayContent(imagebytearraystring, 0, imagebytearraystring.Length), "files", Path.GetFileName(fileName));
            pst.Content = form;
            HttpResponseMessage response = client.SendAsync(pst).Result;
            string responseContent = response.Content.ReadAsStringAsync().Result;
            response.EnsureSuccessStatusCode();
            string sd = response.Content.ReadAsStringAsync().Result;
            JObject array = JsonConvert.DeserializeObject<JObject>(sd);
            sd = array["file_infos"].ToString();
            JArray fur = JsonConvert.DeserializeObject<JArray>(sd);
            MMFileUploadResponse fr = JsonConvert.DeserializeObject<MMFileUploadResponse>(fur[0].ToString());
            return fr.id;
        }
`
For reference...

`
 public class MMFileUploadResponse
    {
        public string id { get; set; }
        public string user_id { get; set; }
        public long create_at { get; set; }
        public long update_at { get; set; }
        public long delete_at { get; set; }
        public string name { get; set; }
        public string extension { get; set; }
        public int size { get; set; }
        public string mime_type { get; set; }
    }

 public HttpRequestMessage makeRequestMessage(HttpMethod method, string command)
        {
            // serverAddress = "http://xxx.xxx.xxx.xxx:xxxx/api/v4/"
            // command = "files"
            HttpRequestMessage request = new HttpRequestMessage(method, new Uri(serverAddress + command));
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", sessionToken);
            return request;
        }
`
