### ISSUE TITLE
onaddstream is deprecated! Use peerConnection.ontrack instead

### ISSUE THREAD

**Issue by jscongdon** [mattermost/mattermost-server#7908]
#### Summary
I'm trying to get WebRTC working.

#### Steps to reproduce
Firefox 57 Try to start video chat.

#### Expected behavior
That I would be able to carry on a video chat

#### Observed behavior (that appears unintentional) 
`onaddstream is deprecated! Use peerConnection.ontrack instead` error received in console

#### Possible fixes
Use `peerConnection.ontrack` instead ?

I've given up on trying to get WebRTC to work in a detached network situation with https... so I'm resorting to http. Using http in Chrome will not work because it will not allow capture audio / video in anything other that https. So, I'm using Firefox.
When the call is made it appears to connect and then I see the previously mentioned message in the console.

**Comment by lindy65** [comment]
Hi @jscongdon,

Could you share whether you've followed [these deployment instructions](https://docs.mattermost.com/deployment/webrtc.html)?  There is also [this doc for configuration settings](https://docs.mattermost.com/administration/config-settings.html#webrtc-beta).

Does this help?

**Comment by jscongdon** [comment]
Yes, I've followed those instructions.
As I stated, the call will connect... then the error is received.

It does not help.

**Comment by lindy65** [comment]
Thanks for the feedback @jscongdon,

I'll ask the team to help troubleshoot this and post feedback here

**Comment by jasonblais** [comment]
This most likely requires an update to the Janus driver. We've created a ticket for it @jscongdon https://mattermost.atlassian.net/browse/PLT-8250

**Comment by lindy65** [comment]
I'll close this issue off here for now @jscongdon and we can track via the Jira ticket linked above.
