### ISSUE TITLE
[Help Wanted] [PLT-8215] Group Message search in the Channel Switcher should filter on usernames, full names and nicknames

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7912]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8215)

Observed:
Group message search in the channel switcher only filters on the displayed name:
![image](https://user-images.githubusercontent.com/13119842/33341632-86f0ba86-d44d-11e7-970a-d9f32027a3f3.png)
![image](https://user-images.githubusercontent.com/13119842/33341639-8af90570-d44d-11e7-9495-a3d8a6d7c96d.png)

Expected:
Searching for full name, username or nickname in the channel switcher returns all group messages containing that person

**Comment by tborg** [comment]
Hey there, I'd like to work on this.

**Comment by enahum** [comment]
Great @tborg go ahead
