### ISSUE TITLE
[Help Wanted] [PLT-8221] setState warnings when switching to Display tab in Account Settings

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7918]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8221)

Repro steps:
1) Log into Mattermost on your local instance (ie in dev mode)
2) Open Account Settings
3) Switch to the Display tab

Observed: JavaScript warnings are logged to the console
![image](https://user-images.githubusercontent.com/13119842/33393765-3fa72d88-d50e-11e7-8d35-0a84331b2867.png)

**Comment by sudheerDev** [comment]
@esethna i submitted a PR for this :)

**Comment by esethna** [comment]
Thanks @sudheerDev!

**Comment by lindalumitchell** [comment]
Tested and verified on master. Looks great!

PR: https://github.com/mattermost/mattermost-webapp/pull/384
