### ISSUE TITLE
[Help Wanted] [PLT-8203] Code block created using four spaces triggers mention

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7923]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8203)

If I post a code block by starting my message with four spaces, an at-mention inside the code block triggers a mention for the other user. Reproduced on desktop app and OSX Chrome and Firefox, on master and v4.4.1.

1. Have another user logged on using a different / incognito browser, and not viewing the channel you're viewing
2. Type four spaces, then an at-mention of the other user, and press Enter

Observed: Other user sees a mention badge
Expected: Other user sees an unread, but not a mention badge

Notes:
- These also reproduce the issue: at-all, at-channel, at-here
- These do not repro the issue: posting a code block using either triple ticks and newlines, or `~~~text~~~`

**Comment by ccbrown** [comment]
Taking this one. I've been working on something that'll take care of it along with a lot of other similar cases.
