### ISSUE TITLE
Messages w/ Quick Responses Can Appear Out of Order

### ISSUE THREAD

**Issue by starlightknight** [mattermost/mattermost-server#7932]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Bug report in one concise sentence

When messages are exchanged quickly, sometimes they appear out of order (a person's response appears before the original message). This seems to be an artifact of all participants clocks not necessarily being in sync, and is more likely to surface with the server in a virtualized environment

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

1) Install an Ubuntu 16.04 KVM guest on a Ubuntu 16.04 KVM host, with kvmclock+ntp
2) Use Gitlab Omnibus Docker 10.1.3 w/ Mattermost 4.2.1 in the guest
3) Exchanges messages quickly (client does not matter). Number of participants does not seem to matter either (I've seen this with only 2 people active on the mattermost server)

Situation may be aggravated by multiple KVM guests on the same box (contributing to minor clock drift?). Box in question has 2 guests, 1 Windows and 1 Linux.

#### Expected behavior
Messages should never get desynced. If someone is responding to my message, they had to have seen it before sending their reply. It seems like a single source of truth for clock is not used when recording the timestamp on the server, leading to this being a possibility.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

Messages randomly appear out of order, and remain out of order (whether it be on the web, mobile, or desktop clients)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

Ensure a single source of truth is timestamping the messages as it receives them on the server and routes them for display. Then, even if the clock is slightly drifted, its always by the same amount. Not all devices in the conversation are guaranteed to have exactly in sync clocks

**Comment by lindy65** [comment]
Hi @starlightknight 

Thanks for your feedback,

This was an issue in an earlier version but has since been fixed.  Try upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost to see if the issue still reproduces.

**Comment by lindy65** [comment]
Hi @starlightknight,

Did upgrading to the latest version of Mattermost resolve the issue for you?

**Comment by lindy65** [comment]
Hi @starlightknight,

As we haven't heard from you, I'll assume your issue is fixed or is no longer valid.

I'll close this off for now but please feel free to come back after upgrading if you are still experiencing issues.

Thanks!
