### ISSUE TITLE
Message Self

### ISSUE THREAD

**Issue by T-rav** [mattermost/mattermost-server#7935]
#### Summary
I would be nice to message myself like I can in Slack

#### Steps to reproduce
Click plus symbol next to Direct Messages
Try and search for yourself in the popup.
Notice you cannot find yourself to message.

#### Expected behavior
I can find myself when searching int he Direct Messages popup.

#### Observed behavior (that appears unintentional) 
When searching for myself there are 'no items found'.
![no-results](https://user-images.githubusercontent.com/5384842/33555782-474afaba-d90a-11e7-8e90-720bf7ff0de3.png)

#### Possible fixes
Return myself in the user search so I can jot things down like I can in Slack. Currently this is a deal breaker. 
![results-found](https://user-images.githubusercontent.com/5384842/33555808-6185f524-d90a-11e7-8f06-120db9880615.png)

**Comment by lindy65** [comment]
Hi @T-rav,

Thanks for your feedback,

This feature should be shipping with v4.5 on December 16th!

**Comment by T-rav** [comment]
Awesome stuff. Thanks
