### ISSUE TITLE
[Help Wanted] [PLT-8273] In System Console > Team Statistics, add a banner to note that team stats don't include DMs

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7945]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8273)

ACTION

In System Console > Team Statistics, add a note to highlight that team stats exclude DMs.

```
Only data for the chosen team is calculated. Excludes posts made in direct message channels, which are not tied to a team.
```

NOTE: When the system has users that exceeds the "MaxUsersForStatistics" config.json setting, the banner should say:

```
Only data for the chosen team is calculated. Excludes posts made in direct message channels, which are not tied to a team.

To maximize performance, some statistics are disabled. You can re-enable them in config.json.
```

where "re-enable them in config.json" links to documentation as before.

CONTEXT

This has been brought up multiple times where admins are confused by the difference in team and site statistics. When the system only has a single team, they would expect the team and site statistics to match, but they don't because team stats exclude DM channels. Most recently, see https://forum.mattermost.org/t/inconsistent-statistics-for-site-and-team/4174

There is also an accompanying doc update for this, but not sure how many would discover the note: https://github.com/mattermost/docs/pull/1661

**Comment by R-Wang97** [comment]
I can take a look at this.

**Comment by lindalumitchell** [comment]
Thanks @R-Wang97! Closing as https://github.com/mattermost/mattermost-webapp/pull/436 has been merged.
