### ISSUE TITLE
[Help Wanted] [PLT-8278] Add a custom example to API reference for how to upload a file via the API

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7946]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8278)

We've received multiple questions from the community about how to upload a file via the APIs. E.g., see https://github.com/mattermost/mattermost-server/issues/7907

Propose adding an example of how to do this at api.mattermost.com. This will involve 
1. figuring out how to add custom examples on the site, which is auto-generated from https://github.com/mattermost/mattermost-api-reference.
2. creating an example for uploading the file via the API. A sample is given below

```
POST /api/v4/files HTTP/1.1
Host: localhost:8065
Connection: keep-alive
Content-Length: 444
Accept: application/json
Authorization: bearer <your token here>
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary5a5WIBBw6R9BjHO7

------WebKitFormBoundary5a5WIBBw6R9BjHO7
Content-Disposition: form-data; name="files"; filename="test.txt"
Content-Type: text/plain

<your file content here>
------WebKitFormBoundary5a5WIBBw6R9BjHO7
Content-Disposition: form-data; name="channel_id"

<your channel id here>
------WebKitFormBoundary5a5WIBBw6R9BjHO7
Content-Disposition: form-data; name="client_ids"

<your optional client ids here>
------WebKitFormBoundary5a5WIBBw6R9BjHO7--
```

3. Adding this example to https://github.com/mattermost/mattermost-api-reference/blob/master/v4/source/files.yaml

**Comment by cpanato** [comment]
i can do that

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-api-reference/pull/312
