### ISSUE TITLE
I can delete directly other people's message on channel

### ISSUE THREAD

**Issue by francisgg** [mattermost/mattermost-server#7954]
#### Summary
While chatting with our team, I found out that we could sometimes delete other people's messages on channel.

#### Steps to reproduce
I'm using Mattermost Enterprise Edition version 4.2.0

#### Expected behavior
- I hover to my team's message, a cross icon appears on top right hand side
- I click on this cross, it deletes the message directly
- Which will appear on public as ==> (message deleted)
- Other people on channel could also delete (some of) my message

#### Observed behavior (that appears unintentional) 
As mentioned above ==> (message deleted)

**Comment by lindy65** [comment]
Hi @francisgg,

Thanks for your feedback,

Could we have your help updating to the [latest version](https://about.mattermost.com/download/) of Mattermost?

I am not able to reproduce your issue on our nightly build server building off master.  Could you include a screenshot of the cross you're seeing when you hover on a teammate's message?

Thanks!

**Comment by lindy65** [comment]
Hi @francisgg,

Is your issue resolved?

Please send a screenshot of the cross you're seeing when you hover on a teammate's message so we can try to troubleshoot further?

**Comment by lindy65** [comment]
Hi @francisgg,

As we haven't heard from you, I'll assume your issue is fixed or is no longer valid.

I'll close this off for now but please feel free to reopen if you are still having issues after you have upgraded to the latest version.

Thanks!
