### ISSUE TITLE
Database integrity check

### ISSUE THREAD

**Issue by divanikus** [mattermost/mattermost-server#7955]
Please consider adding a database integrity check tool. Eventhough it's mentioned that you shouldn't do any direct manipulations with database, sometimes you just doesn't have any other option. So it would be nice to have a cli tool for integrity check. Most mature projects involving SQL have them.

Personal example: Team Statistics tab shows nothing, but endless "Loading...". No exceptions in the log, so I just can't find what is wrong with it.

**Comment by MusikPolice** [comment]
Are you sure that the problem is with the database? Awhile back, people who had an ad blocker enabled were seeing that behaviour on the Team Statistics tab. One of the ad block lists added the URL that is called by that tab to their block list. We petitioned to have it removed, but if you haven't updated your block lists lately, you may still be affected.

**Comment by divanikus** [comment]
Ah, yes, the Team Statistics is because of AdBlock. But sometimes we have to edit database directly so anyways integrity check should present imho.

**Comment by MusikPolice** [comment]
This ticket might be a better fit for our Uservoice forum. If you make a feature suggestion there, and it is upvoted by other users that want to see that feature implemented, we're more likely to get it done. GitHub tickets are used more for actual bugs in the software.

**Comment by divanikus** [comment]
It should be in core functionality, not a on-vote-request option.

**Comment by MusikPolice** [comment]
Maybe so, but requests are the process by which features like this get accepted into the core product. Like any team, we have limited resources and have to make hard decisions about what we choose to spend our time on.
