### ISSUE TITLE
Full CRUD for CLI tool

### ISSUE THREAD

**Issue by divanikus** [mattermost/mattermost-server#7956]
Current Mattermost CLI lacks of full CRUD for manipulations. If you want to delete a team, for example, you should be able to list them at least, which is not possible. You can't script stuff without it, you can't see contents without using browser or quering database directly. No good for a CLI app.

CRUD stands for Create, Read, Update, Delete. Read action is not implemented at all. Update action is very limited or not implemented too. You give us no choice but accessing DB directly.

**Comment by MusikPolice** [comment]
This ticket might be a better fit for our [Uservoice forum](https://mattermost.uservoice.com/forums/306457-general/). If you make a feature suggestion there, and it is upvoted by other users that want to see that feature implemented, we're more likely to get it done. GitHub tickets are used more for actual bugs in the software.

**Comment by divanikus** [comment]
It should be in core functionality, not a on-vote-request option.

**Comment by MusikPolice** [comment]
Maybe so, but requests are the process by which features like this get accepted into the core product. Like any team, we have limited resources and have to make hard decisions about what we choose to spend our time on.

**Comment by divanikus** [comment]
So you end up with poorly implemented admin interface which is unable to do most things, because most of user voted feature are about chat UI.

Your admin interface is really bad, both system console and CLI and mostlikely won't be improved anytime soon.

**Comment by MusikPolice** [comment]
I'm sorry you feel that way. For what it's worth, I think that your idea is fantastic, and would love to personally spend more time working on the CLI, but the project has procedures for accepting suggestions like this, and we have to abide by those procedures so that every member of our community gets a say in what features we choose to implement.

**Comment by divanikus** [comment]
How many voices do we need to raise your attention?

I don't want to be rude, but MM's administration abilities are currenlty mostly non-existant. What can I do with System Console? Let's check.

- Someone made a lot of Teams, by mistake or whatever. Can I delete them? No. Can I edit their name? No. I have to join it first. Every single team. Same goes with channels.
- Can I edit a user to simply change his nickname or drop his avatar because he uses a inappropriate pic? No. Hallelujah! We recently got an ability to "deactivate users". 
- Can I register, delete or move to another team a user? No.
- Do we have any bulk operations? No.
- What about attachments? How many do I have? Am I able to know how much space do they use? Can I clean them? No.

It's just a bunch of simple admin tasks I have faced during last year with day-to-day interaction with MM.

And CLI. It's one of most undeveloped and unclean CLIs I have ever faced. You can't do most of the parts in System Console, so also can't do almost anything with CLI. All we have is a bunch of hacks for user voiced actions.
