### ISSUE TITLE
How can I contribute to the client app ?

### ISSUE THREAD

**Issue by danedavid** [mattermost/mattermost-server#7960]
sorry for posting this as an issue, but how can I contribute to the React client app of this site ?

**Comment by santos22** [comment]
Hey @danedavid!

You can contribute to the webapp by working on an issue that includes a **ReactJ**S label. Once you're done, you can submit a pull request here: https://github.com/mattermost/mattermost-webapp

And if your work also include changes to the server, I think you would also create a pull request to the mattermost-server repo. Good luck 😄

**Comment by danedavid** [comment]
@santos22 Thanks
