### ISSUE TITLE
Send Email Invite form should check the syntax of email addresses

### ISSUE THREAD

**Issue by torgeirl** [mattermost/mattermost-server#7962]
#### Summary
The Send Email Invite form seems to lack an email syntax check.

#### Steps to reproduce
Open the Send Email Invite form, type in multiple addresses in the same field and click Send Invitation.

#### Expected behavior
If the content of an address field doesn't validate to the syntax of an email address clicking Send Invitation should as a minimum give an error, and fields that doesn't validate should be visually marked so the user understand which fields the need to correct.

#### Observed behavior (that appears unintentional) 
![screenshot from 2017-12-11 10-17-47](https://user-images.githubusercontent.com/796053/33824023-4a7020dc-de5d-11e7-92bc-e1c07478bc5f.png)

You will get no UI feedback whatsoever, but the Mattermost log will list an error:
`[EROR] Failed to send invite email successfully err=SendMail: utils.mail.send_mail.to_address.app_error, 501 5.1.3 Bad recipient address syntax`.

Checking further, the email server's log file (for this instance Postfix) will be a little more helpful: `warning: Illegal address syntax from localhost[127.0.0.1] in RCPT command: <john@example.com, jane@example.com, pete@example.com>`

**Comment by MusikPolice** [comment]
@torgeirl this is a known issue that we're tracking internally in [PLT-8248|https://mattermost.atlassian.net/browse/PLT-8248]. I'm hoping to get a fix in for this in the next couple of releases.
