### ISSUE TITLE
Message parsing hangs

### ISSUE THREAD

**Issue by Phorkyas** [mattermost/mattermost-server#7963]
#### Summary
A certain message consistently hangs the client (Linux client Version as well as the browser version on Chrome and Firefox)

Server Version: 4.1.0
Linux Client version: 3.5.0

#### Steps to reproduce
Send the enclosed [message](https://github.com/mattermost/mattermost-server/files/1547838/mattermost_bug.txt) to a chat and "Loading" will be displayed infinitely.

#### Expected behavior
Parsing the message should terminate and display it (even if the mark up would look a bit strange).

#### Observed behavior
The window becomes unresponsive, the whole GUI is frozen (Linux Client or Webpage). The same happens for the recipient of the message. If he opens the conversation you sent the sample text, his client hangs as well.

**Comment by lindy65** [comment]
Hi @Phorkyas,

Thanks for your feedback,

Could we have your help upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost to see whether this resolves the issue for you?

**Comment by Phorkyas** [comment]
Unfortunately I don't control the server, only observed it as client - but also in the browser that's why I filed it here.

With your docker image I could however verify that the current version seems to grok the message as it should (see ![screenshot](https://user-images.githubusercontent.com/24679825/33882679-2ca4713e-df39-11e7-81b8-29dc0fd948bf.png)). - So I can only ask our admins to upgrade?

**Comment by lindy65** [comment]
Hi @Phorkyas,

We recommend upgrading to the latest version as there have been numerous fixes since v4.1 (v4.5 releases on Friday, December 15th).

If this doesn't resolve your issue, please feel free to come back with further information and we can troubleshoot further.

Thanks!

**Comment by lindy65** [comment]
Hi @Phorkyas,

I'll close this issue off here for now.  Please feel free to come back and reopen once your admin has upgraded to the latest version if your issue is still not resolved :)

**Comment by Phorkyas** [comment]
Thanks! I wanted to close it myself. Our admin upgraded and the issue is solved. I was just curious what put the parser into limbo,.. but probably makes no sense to debug or bisect an issue already solved.

**Comment by lindy65** [comment]
Great news @Phorkyas :)

Glad to hear your issue is resolved!
