### ISSUE TITLE
[Help Wanted] [PLT-8333] Members count on manage members model briefly displays n-1 members instead of n members for the to value

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7964]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8333)

1. On a team with more than 50 users, log in to an account as a Team Admin (can log in as bot@mattermost.com w password on Assignments tab and promote your account to Team Admin if need be)
2. Click hamburger main menu and select Manage Members to open Manage Members dialog
3. Click the ""Next"" button to view the next page of users

Observed:
Displays 51-99 members for around half a second before changing to 51-100.

Expected:
Display 51-100 immediately.

**Comment by watadarkstar** [comment]
I'll take this one! 😄

**Comment by watadarkstar** [comment]
@esethna 

Found this related bug when investigating this issue. With exactly 50 users on a team the members count on the manage members model displays **51 - 50 members of 50 total** (see attached image below).

**Notes:**

1. On a team with **exactly** 50 users, log in to an account as a Team Admin (can log in as bot@mattermost.com w password on Assignments tab and promote your account to Team Admin if need be)
2. Click hamburger main menu and select Manage Members to open Manage Members dialog
3. Click the ""Next"" button to view the next page of users

Observed:
Displays 51-50 members when team size is exactly 50 members.

Expected:
Does not allow user to go to the next page by hiding the next button when there is exactly 50 users.

![example1](https://user-images.githubusercontent.com/3059371/33908306-f554515a-df55-11e7-8037-693f35629465.png)

**Comment by watadarkstar** [comment]
PR submitted https://github.com/mattermost/mattermost-webapp/pull/456

**Comment by watadarkstar** [comment]
@esethna @jasonblais This can be closed per https://github.com/mattermost/mattermost-webapp/pull/456 was merged.

**Comment by esethna** [comment]
Thanks @watadarkstar!
