### ISSUE TITLE
[Help Wanted] [PLT-8369] Pagination for team members modal shows a next button when there are no more users to show

### ISSUE THREAD

**Issue by watadarkstar** [mattermost/mattermost-server#7971]
#### Summary
Found this related bug when investigating #7964. With exactly 50 users on a team the members count on the manage members modal displays **51 - 50 members of 50 total** (see attached image below) when you press "Next".

#### Steps to reproduce

1. On a team with **exactly** 50 users or any multiple of 50, log in to an account as a Team Admin (can log in as bot@mattermost.com w password on Assignments tab and promote your account to Team Admin if need be)
2. Click hamburger main menu and select Manage Members to open Manage Members dialog
3. Click the ""Next"" button to view the next page of users

#### Expected behavior
Does not allow user to go to the next page by hiding the next button when there is exactly 50 users.

#### Observed behavior (that appears unintentional) 
Displays 51-50 members when team size is exactly 50 members.

#### Possible fixes
See [this line of code in searchable_user_list.jsx](https://github.com/mattermost/mattermost-webapp/blob/97cb44a06ec49e86800bbec8e5a13ebe84c75f26/components/searchable_user_list/searchable_user_list.jsx#L180-L193)

![example1](https://user-images.githubusercontent.com/3059371/33908306-f554515a-df55-11e7-8037-693f35629465.png)

**Comment by lindy65** [comment]
Thanks @watadarkstar :)

I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8369) to fix the issue.

**Comment by watadarkstar** [comment]
@lindy65 Thanks added PLT-8369 to the title 😃
