### ISSUE TITLE
Channel rename,edit purpose etc not working.

### ISSUE THREAD

**Issue by Ajita24** [mattermost/mattermost-server#7973]
Hello,

I have configured mattermost 4.4.0 successfully.
But I have found that some functionalities related to Channel Update like rename,edit channel purpose etc are not working and related API is not being called.
Screenshot of error being encountered in Console- https://www.screencast.com/t/p0sWuNny07

Please guide if something is being missed.

**Comment by MusikPolice** [comment]
Hi @Ajita24, how did you install Mattermost? Are you running it in a development environment, or did you install binaries/docker/packages? Based on the error that you're seeing, I would guess that one or more Mattermost dependencies were not properly installed.

**Comment by yassersheikh** [comment]
I have installed from git repository.I have install packages and running in production. But i am not getting any error of dependencies.

**Comment by himaniruwali** [comment]
I have installed from git repository.I have install packages and running in production. But i am not getting any error of dependencies.

**Comment by lindy65** [comment]
Hi @Ajita24 @himaniruwali 

We [had a bug](https://mattermost.atlassian.net/browse/PLT-8170) which will be fixed when v4.5 ships on December 15th.

**Comment by Ajita24** [comment]
ok.
Thank you.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
