### ISSUE TITLE
Multiple emoji's

### ISSUE THREAD

**Issue by Milack27** [mattermost/mattermost-server#7979]
Sometimes I want to insert more than one emoji in a sequence. In order to do that today, I need to open the Emoji Picker twice. Instead, I would like the Emoji Picker to keep open if I click while holding the Shift key, so that I can just choose the next emoji.

**Comment by lindy65** [comment]
Hi @Milack27,

Which server version of Mattermost do you have running?

If you upgrade to the [latest version](https://about.mattermost.com/download/) which shipped on the 16th, you will see that there is now a "plus sign" next to the emoji you add first where you can click and add another.

![image](https://user-images.githubusercontent.com/13020833/34099254-ab0dcd2e-e3e7-11e7-9feb-3839ab370cae.png)

If this is not what you have in mind, please consider opening a feature request on our [forum](https://mattermost.uservoice.com/forums/306457-general) where your request can be upvoted up to 10 times by yourself and others.

Thanks!

**Comment by Milack27** [comment]
Hi @lindy65, thank you for your response!

You're right, the version I'm using is 4.4.0 (4.4.5), from December 7th, so I don't see any plus sign. However, my suggestion was not about emoji's posted as a reaction, but rather about emoji's posted as part of a message in the conversation. If I want to insert multiple emoji's in a sequence, I could type them manually, but I prefer using the Emoji Picker. But as soon as I click an emoji to insert it, the Emoji Picker closes. I think there should be a way (like holding the Shift key) to keep it open so that I can insert the next emoji.

**Comment by lindy65** [comment]
Ah, gotcha @Milack27 :)  Thank you for expanding on what you require...

That would be a feature request / improvement and it would be great if we could get your help adding it to our [forum](https://mattermost.uservoice.com/forums/306457-general) where you, and others, can upvote it up to 10 times.

Thanks!

**Comment by Milack27** [comment]
Nice! I'll do it as soon as possible. Thank you!

**Comment by lindy65** [comment]
Perfect, thank you @Milack27!

Please post the link to your feature request back to this thread for continuity?

Thanks!

**Comment by Milack27** [comment]
Sure! Here it is:

https://mattermost.uservoice.com/forums/306457-general/suggestions/32664409-allow-consecutive-emoji-s-in-the-emoji-picker

**Comment by lindy65** [comment]
Awesome!  Thanks so much @Milack27 :)

I'll close this issue off here then and we can track via the forum suggestion you've linked above...
