### ISSUE TITLE
Main Menu - "Report a Problem" Option displays a page that does not exist

### ISSUE THREAD

**Issue by marisabell05** [mattermost/mattermost-server#7980]
#### Summary
The Menu Option " Report a Problem" is displaying a page that reads " Oops that Page doesn't exist"

Steps to reproduce:
1) Login to Mattermost demo site for any team
2) Click on main Menu located in upper left hand corner represented by three horizontal lines
3) Click on " report a problem" menu option
4) View and observe a page displays with " That page doesn't exist or is private"
5)Click on the Login button located in upper right hand corner 
6) Enter in credentials and view and observe user is not able to login to see the page either

#### Expected behavior
Upon click on the " Report a problem" menu option, a form to report the problem should display

![mattermost_screenshot_1](https://user-images.githubusercontent.com/34637471/34088075-18cbd43c-e375-11e7-82ae-92d2cb3ab7b1.JPG)
![mattermost_screenshot_2](https://user-images.githubusercontent.com/34637471/34088076-18da8d60-e375-11e7-8e0c-91fcc5b61e68.JPG)

**Comment by lindy65** [comment]
Hi @marisabell05,

Thank you for your feedback, nice catch!

The link should be pointing to: https://forum.mattermost.org/c/trouble-shoot

I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8422) to fix.

**Comment by lena1978** [comment]
This ticket needs to be reopened because the behavior is back. The report a problem link points to https://forum.mattermost.org/c/general/trouble-shoot instead of https://forum.mattermost.org/c/trouble-shoot

**Comment by lindy65** [comment]
Hi @lena1978,

I'm not able to reproduce your issue on our nightly build server...

Could you share which server version of Mattermost you have installed?

**Comment by lena1978** [comment]
It is the demo site located on https://oss.mattermost.com/joomla/channels/town-square

Steps to reproduce:
1.Login to Mattermost demo site for any team
2.Click on main Menu located in upper left hand corner represented by three horizontal lines
3.Click on " report a problem" menu option
4.View and observe a page displays with " That page doesn't exist or is private"

**Comment by lindy65** [comment]
Ah, thanks @lena1978 :)

The demo site is on v4.8 so when it is updated to v4.9 after release on April 16th this issue will be fixed. 

For stability, we don't update that site to the latest master as we do with the nightly build server, [pre-release](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676).
