### ISSUE TITLE
[Help Wanted] [PLT-1260] Refactor TeamSettingsModal to React-Bootstrap

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7985]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1260)

**Comment by R-Wang97** [comment]
I can try taking a look at this.

**Comment by jespino** [comment]
@jasonblais This issue is closed?

**Comment by jasonblais** [comment]
@jespino Looks like it, thanks!
