### ISSUE TITLE
SIGSEGV in platform import

### ISSUE THREAD

**Issue by tcutts** [mattermost/mattermost-server#7988]
#### Summary
platform import crashes with a SIGSEGV

#### Steps to reproduce
I'm running 4.5.0 under docker

1.  Dump a team from slack.
2.  Pre-create some of the users in mattermost, authenticated to an LDAP server (I suspect this may be part of the problem)
3.  Import the dump using platform import slack (I do this specifically with: docker-compose exec app ./platform import slack teamname /mattermost/data/dumpfile.zip having first copied the dump file to the volume bound into the container)

#### Expected behavior
I would expect the team data to import.  I have not been using the slack-advanced-exporter, yet. 

#### Observed behavior (that appears unintentional) 
The import crashes very quickly:

```
ubuntu@mattermost:~/mattermost-docker$ docker-compose exec app ./platform import slack isg /mattermost/data/isg-small-dump.zip 
Running Slack Import. This may take a long time for large teams or teams with many messages.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xd34d21]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/app.(*EmailBatchingJob).Add(0x0, 0xc423e01cc0, 0xc426f599e0, 0xc4261cb6b0, 0xc424c44d00)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/email_batching.go:87 +0xa1
github.com/mattermost/mattermost-server/app.(*App).AddNotificationEmailToBatch(0xc4215df340, 0xc423e01cc0, 0xc426f599e0, 0xc4261cb6b0, 0xd)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/email_batching.go:42 +0x6f
github.com/mattermost/mattermost-server/app.(*App).sendNotificationEmail(0xc4215df340, 0xc426f599e0, 0xc423e01cc0, 0xc423c86370, 0xc4261cb6b0, 0xc4213b7500, 0x6, 0xc426904000, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/notification.go:341 +0x780
github.com/mattermost/mattermost-server/app.(*App).SendNotifications(0xc4215df340, 0xc426f599e0, 0xc4261cb6b0, 0xc423c86370, 0xc426904000, 0x0, 0xc421b49d20, 0xc420000208, 0xc420059198, 0xc4200002b8)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/notification.go:180 +0x1492
github.com/mattermost/mattermost-server/app.(*App).handlePostEvents(0xc4215df340, 0xc426f599e0, 0xc426904000, 0xc423c86370, 0xc421af1200, 0x0, 0x18)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/post.go:260 +0x156
github.com/mattermost/mattermost-server/app.(*App).CreatePost(0xc4215df340, 0xc426f599e0, 0xc423c86370, 0x0, 0xc426f59b88, 0xc424150da0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/post.go:192 +0x6bc
github.com/mattermost/mattermost-server/app.(*App).postJoinChannelMessage(0xc4215df340, 0xc426e15540, 0xc423c86370, 0xc424150ce0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/channel.go:961 +0x30b
github.com/mattermost/mattermost-server/app.(*App).JoinDefaultChannels(0xc4215df340, 0xc4240d2040, 0x1a, 0xc426e15540, 0x1466664, 0xc, 0x0, 0x0, 0xc42728f417)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/channel.go:67 +0xecb
github.com/mattermost/mattermost-server/app.(*App).JoinUserToTeam(0xc4215df340, 0xc4201b6160, 0xc426e15540, 0x0, 0x0, 0x1)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/team.go:333 +0x195
github.com/mattermost/mattermost-server/app.(*App).SlackAddUsers(0xc4215df340, 0xc421debc00, 0x1a, 0xc4225a0480, 0x1b, 0x1c, 0xc420108230, 0x2)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/slackimport.go:171 +0x4f5
github.com/mattermost/mattermost-server/app.(*App).SlackImport(0xc4215df340, 0x1d0d5e0, 0xc42000f4f8, 0x63438f, 0xc421debc00, 0x1a, 0xc4204afd18, 0xc42015d4a0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/slackimport.go:673 +0x10d8
main.slackImportCmdF(0x241b400, 0xc4201a16a0, 0x2, 0x2, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/platform/import.go:74 +0x2a4
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x241b400, 0xc4201a1620, 0x2, 0x2, 0x241b400, 0xc4201a1620)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:696 +0x47a
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x241c2e0, 0x241ef80, 0x241f1a0, 0x241f3c0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:781 +0x30e
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(0x241c2e0, 0xc4204aff70, 0x119b19a)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:734 +0x2b
main.main()
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/platform/mattermost.go:28 +0x2d
```

#### Possible fixes

If I create a completely bare mattermost instance, and try the import in that through the GUI it works, so it's possible the Postgres database has something wrong which the code isn't coping with.

Disabling email notifications before importing the dump is a workaround.

**Comment by tcutts** [comment]
I've done some further testing.  Importing the dump through the web interface works (in practice - it claims to fail, but the records have been imported, as far as I can tell), so this is a difference in behaviour between the web import interface and the CLI

**Comment by tcutts** [comment]
I set up a new build environment, following the developer instructions.  The import works fine on that, although it's not a clean test, because I can't configure LDAP authentication in the developer environment.  Is there a way to get the developer build to enable enterprise features?

**Comment by tcutts** [comment]
Worked out how to do that - created a ../enterprise directory.  So I now have an enterprise test environment working.  Tried loading my licence into it, which it accepts, but it doesn't like it when I try to run the AD/LDAP test it says:

`[2017/12/21 14:36:30 UTC] [EROR] /api/v4/logs:client code=0 rid=jqsp1jtzap8ezgsei8bcgnj6py uid=djekyys7e3gj3euteqxgm66pqc ip=127.0.0.1 {"message":"AD/LDAP disabled or licence does not support AD/LDAP.","server_error_id":"ent.ldap.disabled.app_error","status_code":501,"url":"http://localhost:8065/api/v4/ldap/test"} [details: ]`

but maybe that's because [obviously] that licence is already in use on the production system

**Comment by tcutts** [comment]
Workaround:  Disabling email notifications allows the import to proceed (noticed the nil pointer for EmailBatch in the stack trace above)

**Comment by lindy65** [comment]
Hi @tcutts,

Thanks for your feedback,

I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8457) to track the issue.

**Comment by grundleborg** [comment]
@tcutts thanks for the bug report. I'm trying to reproduce the crash so I can make sure I fix it correctly, but I can't at the moment. Would you be able to share your `config.json`, with any sensitive values redacted, that you are using when the crash occurs?

**Comment by tcutts** [comment]
I think the following is what was running at the time.  The principal change which allowed me to work around it was to set "EnableEmailBatching": false.

{
    "ServiceSettings": {
        "SiteURL": "https://mattermost.sanger.ac.uk",
        "LicenseFileLocation": "",
        "ListenAddress": ":80",
        "ConnectionSecurity": "",
        "TLSCertFile": "",
        "TLSKeyFile": "",
        "UseLetsEncrypt": false,
        "LetsEncryptCertificateCacheFile": "./config/letsencrypt.cache",
        "Forward80To443": false,
        "ReadTimeout": 300,
        "WriteTimeout": 300,
        "MaximumLoginAttempts": 10,
        "GoroutineHealthThreshold": -1,
        "GoogleDeveloperKey": "",
        "EnableOAuthServiceProvider": false,
        "EnableIncomingWebhooks": true,
        "EnableOutgoingWebhooks": true,
        "EnableCommands": true,
        "EnableOnlyAdminIntegrations": true,
        "EnablePostUsernameOverride": true,
        "EnablePostIconOverride": true,
        "EnableAPIv3": false,
        "EnableLinkPreviews": true,
        "EnableTesting": false,
        "EnableDeveloper": false,
        "EnableSecurityFixAlert": true,
        "EnableInsecureOutgoingConnections": false,
        "AllowedUntrustedInternalConnections": "",
        "EnableMultifactorAuthentication": true,
        "EnforceMultifactorAuthentication": false,
        "EnableUserAccessTokens": true,
        "AllowCorsFrom": "",
        "SessionLengthWebInDays": 30,
        "SessionLengthMobileInDays": 30,
        "SessionLengthSSOInDays": 30,
        "SessionCacheInMinutes": 10,
        "SessionIdleTimeoutInMinutes": 0,
        "WebsocketSecurePort": 443,
        "WebsocketPort": 80,
        "WebserverMode": "gzip",
        "EnableCustomEmoji": true,
        "EnableEmojiPicker": true,
        "RestrictCustomEmojiCreation": "all",
        "RestrictPostDelete": "all",
        "AllowEditPost": "always",
        "PostEditTimeLimit": 300,
        "TimeBetweenUserTypingUpdatesMilliseconds": 5000,
        "EnablePostSearch": true,
        "EnableUserTypingMessages": true,
        "EnableChannelViewedMessages": true,
        "EnableUserStatuses": true,
        "ExperimentalEnableAuthenticationTransfer": true,
        "ClusterLogTimeoutMilliseconds": 2000,
        "CloseUnusedDirectMessages": false,
        "EnablePreviewFeatures": true
    },
    "TeamSettings": {
        "SiteName": "Sanger Mattermost",
        "MaxUsersPerTeam": 1000,
        "EnableTeamCreation": false,
        "EnableUserCreation": false,
        "EnableOpenServer": true,
        "RestrictCreationToDomains": "",
        "EnableCustomBrand": false,
        "CustomBrandText": "",
        "CustomDescriptionText": "",
        "RestrictDirectMessage": "team",
        "RestrictTeamInvite": "all",
        "RestrictPublicChannelManagement": "channel_admin",
        "RestrictPrivateChannelManagement": "all",
        "RestrictPublicChannelCreation": "team_admin",
        "RestrictPrivateChannelCreation": "all",
        "RestrictPublicChannelDeletion": "team_admin",
        "RestrictPrivateChannelDeletion": "all",
        "RestrictPrivateChannelManageMembers": "all",
        "EnableXToLeaveChannelsFromLHS": false,
        "UserStatusAwayTimeout": 300,
        "MaxChannelsPerTeam": 2000,
        "MaxNotificationsPerChannel": 1000,
        "EnableConfirmNotificationsToChannel": true,
        "TeammateNameDisplay": "nickname_full_name",
        "ExperimentalTownSquareIsReadOnly": false
    },
    "ClientRequirements": {
        "AndroidLatestVersion": "",
        "AndroidMinVersion": "",
        "DesktopLatestVersion": "",
        "DesktopMinVersion": "",
        "IosLatestVersion": "",
        "IosMinVersion": ""
    },
    "SqlSettings": {
        "DriverName": "postgres",
        "DataSource": "postgres://xxxxx:xxxxxx@db:5432/mattermost?sslmode=disable\u0026connect_timeout=10",
        "DataSourceReplicas": [],
        "DataSourceSearchReplicas": [],
        "MaxIdleConns": 20,
        "MaxOpenConns": 300,
        "Trace": false,
        "AtRestEncryptKey": “xxxxxxxxxxxxxxxxxxxxxxx",
        "QueryTimeout": 30
    },
    "LogSettings": {
        "EnableConsole": false,
        "ConsoleLevel": "INFO",
        "EnableFile": true,
        "FileLevel": "INFO",
        "FileFormat": "",
        "FileLocation": "",
        "EnableWebhookDebugging": true,
        "EnableDiagnostics": true
    },
    "PasswordSettings": {
        "MinimumLength": 5,
        "Lowercase": false,
        "Number": false,
        "Uppercase": false,
        "Symbol": false
    },
    "FileSettings": {
        "EnableFileAttachments": true,
        "EnableMobileUpload": true,
        "EnableMobileDownload": true,
        "MaxFileSize": 52428800,
        "DriverName": "local",
        "Directory": "/mattermost/data/",
        "EnablePublicLink": true,
        "PublicLinkSalt": "udGigR4W5ZKByqujJ8ctSmVBFaima3QCIZasQQvg0BnVxrgs",
        "InitialFont": "luximbi.ttf",
        "AmazonS3AccessKeyId": "",
        "AmazonS3SecretAccessKey": "",
        "AmazonS3Bucket": "",
        "AmazonS3Region": "us-east-1",
        "AmazonS3Endpoint": "s3.amazonaws.com",
        "AmazonS3SSL": true,
        "AmazonS3SignV2": false,
        "AmazonS3SSE": false,
        "AmazonS3Trace": false
    },
    "EmailSettings": {
        "EnableSignUpWithEmail": false,
        "EnableSignInWithEmail": true,
        "EnableSignInWithUsername": true,
        "SendEmailNotifications": true,
        "UseChannelInEmailNotifications": false,
        "RequireEmailVerification": false,
        "FeedbackName": "Mattermost Notification",
        "FeedbackEmail": "noreply@sanger.ac.uk",
        "FeedbackOrganization": "",
        "EnableSMTPAuth": false,
        "SMTPUsername": "",
        "SMTPPassword": "",
        "SMTPServer": "mail.internal.sanger.ac.uk",
        "SMTPPort": "25",
        "ConnectionSecurity": "",
        "InviteSalt": "U61qdCciv9FJqb91XDCPjND5pzsEIT4sJl8KoepHiSFc0mws",
        "SendPushNotifications": true,
        "PushNotificationServer": "http://push-test.mattermost.com",
        "PushNotificationContents": "full",
        "EnableEmailBatching": true,
        "EmailBatchingBufferSize": 256,
        "EmailBatchingInterval": 30,
        "SkipServerCertificateVerification": false,
        "EmailNotificationContentsType": "full"
    },
    "RateLimitSettings": {
        "Enable": true,
        "PerSec": 10,
        "MaxBurst": 100,
        "MemoryStoreSize": 10000,
        "VaryByRemoteAddr": false,
        "VaryByHeader": "X-Cluster-Client-IP"
    },
    "PrivacySettings": {
        "ShowEmailAddress": true,
        "ShowFullName": true
    },
    "SupportSettings": {
        "TermsOfServiceLink": "https://about.mattermost.com/default-terms/",
        "PrivacyPolicyLink": "https://about.mattermost.com/default-privacy-policy/",
        "AboutLink": "https://about.mattermost.com/default-about/",
        "HelpLink": "https://about.mattermost.com/default-help/",
        "ReportAProblemLink": "",
        "SupportEmail": "servicedesk@sanger.ac.uk"
    },
    "AnnouncementSettings": {
        "EnableBanner": false,
        "BannerText": "",
        "BannerColor": "#f2a93b",
        "BannerTextColor": "#333333",
        "AllowBannerDismissal": true
    },
    "ThemeSettings": {
        "EnableThemeSelection": true,
        "DefaultTheme": "default",
        "AllowCustomThemes": true,
        "AllowedThemes": []
    },
    "GitLabSettings": {
        "Enable": false,
        "Secret": "",
        "Id": "",
        "Scope": "",
        "AuthEndpoint": "",
        "TokenEndpoint": "",
        "UserApiEndpoint": ""
    },
    "GoogleSettings": {
        "Enable": false,
        "Secret": "",
        "Id": "",
        "Scope": "profile email",
        "AuthEndpoint": "https://accounts.google.com/o/oauth2/v2/auth",
        "TokenEndpoint": "https://www.googleapis.com/oauth2/v4/token",
        "UserApiEndpoint": "https://www.googleapis.com/plus/v1/people/me"
    },
    "Office365Settings": {
        "Enable": false,
        "Secret": "",
        "Id": "",
        "Scope": "User.Read",
        "AuthEndpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "TokenEndpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "UserApiEndpoint": "https://graph.microsoft.com/v1.0/me"
    },
    "LdapSettings": {
        "Enable": true,
        "EnableSync": true,
        "LdapServer": "ldap-ro.internal.sanger.ac.uk",
        "LdapPort": 389,
        "ConnectionSecurity": "STARTTLS",
        "BaseDN": "ou=people,dc=sanger,dc=ac,dc=uk",
        "BindUsername": “xxxxxxxxxxxxxx",
        "BindPassword": “xxxxxxxx",
        "UserFilter": "(\u0026(objectclass=sangerPerson)(sangerActiveAccount=TRUE))",
        "FirstNameAttribute": "givenName",
        "LastNameAttribute": "sn",
        "EmailAttribute": "mail",
        "UsernameAttribute": "uid",
        "NicknameAttribute": "",
        "IdAttribute": "uid",
        "PositionAttribute": "title",
        "SyncIntervalMinutes": 60,
        "SkipCertificateVerification": true,
        "QueryTimeout": 60,
        "MaxPageSize": 0,
        "LoginFieldName": ""
    },
    "ComplianceSettings": {
        "Enable": false,
        "Directory": "./data/",
        "EnableDaily": false
    },
    "LocalizationSettings": {
        "DefaultServerLocale": "en",
        "DefaultClientLocale": "en",
        "AvailableLocales": ""
    },
    "SamlSettings": {
        "Enable": false,
        "EnableSyncWithLdap": false,
        "Verify": true,
        "Encrypt": true,
        "IdpUrl": "",
        "IdpDescriptorUrl": "",
        "AssertionConsumerServiceURL": "",
        "IdpCertificateFile": "",
        "PublicCertificateFile": "",
        "PrivateKeyFile": "",
        "FirstNameAttribute": "",
        "LastNameAttribute": "",
        "EmailAttribute": "",
        "UsernameAttribute": "",
        "NicknameAttribute": "",
        "LocaleAttribute": "",
        "PositionAttribute": "",
        "LoginButtonText": "With SAML"
    },
    "NativeAppSettings": {
        "AppDownloadLink": "https://about.mattermost.com/downloads/",
        "AndroidAppDownloadLink": "https://about.mattermost.com/mattermost-android-app/",
        "IosAppDownloadLink": "https://about.mattermost.com/mattermost-ios-app/"
    },
    "ClusterSettings": {
        "Enable": false,
        "ClusterName": "",
        "OverrideHostname": "",
        "UseIpAddress": true,
        "UseExperimentalGossip": false,
        "ReadOnlyConfig": true,
        "GossipPort": 8074,
        "StreamingPort": 8075
    },
    "MetricsSettings": {
        "Enable": false,
        "BlockProfileRate": 0,
        "ListenAddress": ":8067"
    },
    "AnalyticsSettings": {
        "MaxUsersForStatistics": 2500
    },
    "WebrtcSettings": {
        "Enable": false,
        "GatewayWebsocketUrl": "",
        "GatewayAdminUrl": "",
        "GatewayAdminSecret": "",
        "StunURI": "",
        "TurnURI": "",
        "TurnUsername": "",
        "TurnSharedKey": ""
    },
    "ElasticsearchSettings": {
        "ConnectionUrl": "",
        "Username": "",
        "Password": "",
        "EnableIndexing": false,
        "EnableSearching": false,
        "Sniff": true,
        "PostIndexReplicas": 1,
        "PostIndexShards": 1,
        "AggregatePostsAfterDays": 365,
        "PostsAggregatorJobStartTime": "03:00",
        "IndexPrefix": "",
        "LiveIndexingBatchSize": 1,
        "BulkIndexingTimeWindowSeconds": 3600,
        "RequestTimeoutSeconds": 30
    },
    "DataRetentionSettings": {
        "EnableMessageDeletion": false,
        "EnableFileDeletion": false,
        "MessageRetentionDays": 365,
        "FileRetentionDays": 365,
        "DeletionJobStartTime": "02:00"
    },
    "MessageExportSettings": {
        "EnableExport": false,
        "DailyRunTime": "01:00",
        "ExportFromTimestamp": 0,
        "BatchSize": 10000
    },
    "JobSettings": {
        "RunJobs": true,
        "RunScheduler": true
    },
    "PluginSettings": {
        "Enable": false,
        "EnableUploads": false,
        "Directory": "./plugins",
        "ClientDirectory": "./client/plugins",
        "Plugins": {},
        "PluginStates": {}
    }
}

**Comment by lindy65** [comment]
I'll close this issue off here and we can track via the ticket linked [above](https://github.com/mattermost/mattermost-server/issues/7988#issuecomment-354260130)
