### ISSUE TITLE
Web client doesnt work in firefox/private mode

### ISSUE THREAD

**Issue by faljse** [mattermost/mattermost-server#7996]
#### Summary
Current (4.5) Mattermost web client doesnt work in a firefox private mode session.
#### Steps to reproduce
FF 57.0.2 private mode / Mattermost 4.5

#### Observed behavior (that appears unintentional) 
There are some Dom errors in the console
`Unhandled promise rejection 
DOMError
message: "A mutation operation was attempted on a database that did not allow mutations."
name: "InvalidStateError"
__proto__: DOMErrorPrototype { name: Getter, message: Getter, … }`

**Comment by sunrez** [comment]
I am experiencing the same issue ; Mattermost 4.5 / Debian 9.3 host

Clients, Firefox 56 Linux, and 54 OSX in Private Browsing; have disabled all plug-ins, still get the error

![mattermost_linux_ff_56](https://user-images.githubusercontent.com/17105174/34327745-b4bd62b4-e89a-11e7-883f-324cde40b58b.png)

mattermost@mattermost:/opt/mattermost$ ./bin/platform 
[2017/12/24 09:28:44 UTC] [INFO] Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
[2017/12/24 09:28:44 UTC] [INFO] Current version is 4.5.0 (4.5.0/Fri Dec 15 23:15:33 UTC 2017/03f5c939deb4a6ab2fd01639b5570799e4118bab/dc1a5c62b18d87b9effd4ec249f29c77d1ffdde0)
[2017/12/24 09:28:44 UTC] [INFO] Enterprise Enabled: true
[2017/12/24 09:28:44 UTC] [INFO] Current working directory is /opt/mattermost
[2017/12/24 09:28:44 UTC] [INFO] Loaded config file from /opt/mattermost/config/config.json
[2017/12/24 09:28:44 UTC] [INFO] Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
[2017/12/24 09:28:44 UTC] [INFO] Server is initializing...
[2017/12/24 09:28:44 UTC] [INFO] Pinging SQL master database
[2017/12/24 09:28:44 UTC] [INFO] Initializing plugin: ldapextras
[2017/12/24 09:28:44 UTC] [INFO] Able to write files to local storage.
[2017/12/24 09:28:44 UTC] [INFO] License key from https://mattermost.com required to unlock enterprise features.
[2017/12/24 09:28:44 UTC] [INFO] Starting up plugins
[2017/12/24 09:28:45 UTC] [INFO] Activated jira plugin
[2017/12/24 09:28:45 UTC] [INFO] Starting Server...
[2017/12/24 09:28:45 UTC] [INFO] Server is listening on 0.0.0.0:8065
[2017/12/24 09:28:45 UTC] [INFO] Initializing job API routes
[2017/12/24 09:28:45 UTC] [INFO] API version 3 is scheduled for deprecation. Please see https://api.mattermost.com for details.
[2017/12/24 09:28:45 UTC] [INFO] Starting 4 websocket hubs
[2017/12/24 09:28:45 UTC] [INFO] Starting workers
[2017/12/24 09:28:45 UTC] [INFO] Starting schedulers.

**Comment by lindy65** [comment]
Hi @faljse @sunrez 

Thanks for your feedback,

I'm not sure whether private browsing in Firefox is supported so I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8456) for one of our product managers to take a look at.

They're out for the holidays so should respond after January 2nd.

**Comment by moussetc** [comment]
Hello, some of our users have reported this issue. Has there been any advance on this bug, is it planned for the 4.6 release ? I guess not considering the date but one can hope. This bug is a troubling one and wasn't listed in the release notes for version 4.5. 
Thank you for your work.

**Comment by lindy65** [comment]
Hi @faljse @sunrez @moussetc 

Can you try accessing our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) via private mode in Firefox?

A bug fix related to Firefox not loading the web client has been implemented on the above server.

**Comment by moussetc** [comment]
Hi @lindy65 ! Thank you for your fast answer, we tested the nightly build server and it does work in private mode FF.

**Comment by lindy65** [comment]
Thank you @moussetc,

I've asked the devs for feedback on this issue.  I'll post back as soon as I hear from them.

**Comment by gyrodave** [comment]
I also encounter this annoying problem with Firefox V 52.4.2 in normal mode.

How is the bug fix going to be implemented for self hosted installation. I scanned quickly the PR and found nothing related to this issue.

Thank you !

**Comment by jasonblais** [comment]
@faljse @sunrez @gyrodave @moussetc 

We are preparing a dot release, v4.5.1. It should be released within the next couple of days. PR here: https://github.com/mattermost/mattermost-webapp/pull/603

The issue is also fixed on our v4.6.0 release, which is scheduled for January 16th.

**Comment by foldedpaper** [comment]
Hello, I have been seeing this problem as well in FIrefox (v57.0.4) normal mode.

I have updated my server to v4.6.0 and still see the issue. 

I also just tried logging in to the pre-release demo and run into the same issue there.

Viewing browser console, I see this error:
`﻿﻿ Unhandled promise rejection TypeError: e.RTCPeerConnection is undefined`

Not sure if it will be helpful to provide the stack trace that follows.

**Comment by jasonblais** [comment]
@foldedpaper Do you have any extensions or browser add-ons on your Firefox?

**Comment by foldedpaper** [comment]
I do, but I am not sure if they make a difference; I tried this: disabled all add-ons, restarted firefox, cleared cache, and then tried to login to mattermost--still ran into the same `Unhandled promise rejection` error.

**Comment by jasonblais** [comment]
Thanks! We'll touch base with an engineer

**Comment by jespino** [comment]
We have another user experiencing similar problem with Firefox, but was related to some kind of network problem with an intermediate proxy. Are you accessing directly to your mattermost server? or through any kind of proxy?

**Comment by whereswaldon** [comment]
@jasonblais I am also experiencing this after upgrading to 4.6.0. I have Firefox 58.0 running on Ubuntu 17.10. With plugins disabled, I still have this stack trace when I try to load your demo preview link from above:
```
TypeError: e.RTCPeerConnection is undefined
Stack trace:
shimRemoveStream@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3113027
e.exports@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3068261
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3067106
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3067070
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3061778
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3023726
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3000101
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2999711
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2997202
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2075497
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2074377
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:713
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:67
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
e.exports/<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:673108
U/</<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:224916
U/<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:224786
c@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:71827
```
It is followed by this error:
```
Unhandled promise rejection 
TypeError: e.RTCPeerConnection is undefined
Stack trace:
shimRemoveStream@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3113027
e.exports@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3068261
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3067106
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3067070
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3061778
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3023726
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3000101
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2999711
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2997202
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2075497
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2074377
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:713
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:67
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
e.exports/<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:673108
U/</<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:224916
U/<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:224786
c@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:71827
es6.promise.js:103
```
Let me know if you need any other information!

**Comment by whereswaldon** [comment]
@jasonblais I am also experiencing this after upgrading to 4.6.0. I have Firefox 58.0 running on Ubuntu 17.10. With plugins disabled, I still have this stack trace when I try to load your demo preview link from above:
```
TypeError: e.RTCPeerConnection is undefined
Stack trace:
shimRemoveStream@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3113027
e.exports@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3068261
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3067106
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3067070
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3061778
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3023726
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3000101
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2999711
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2997202
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2075497
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2074377
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:713
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:67
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
e.exports/<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:673108
U/</<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:224916
U/<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:224786
c@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:71827
```
It is followed by this error:
```
Unhandled promise rejection 
TypeError: e.RTCPeerConnection is undefined
Stack trace:
shimRemoveStream@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3113027
e.exports@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3068261
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3067106
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3067070
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3061778
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3023726
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:3000101
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2999711
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2997202
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2075497
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:2074377
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:713
@https://pre-release.mattermost.com/static/0.c37b4e7f0c2259f84ea1.js:1:67
t@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:96
e.exports/<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:673108
U/</<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:224916
U/<@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:224786
c@https://pre-release.mattermost.com/static/main.f8a448ba1f8150f4505f.js:1:71827
es6.promise.js:103
```
I am not using a proxy of any kind.
Let me know if you need any other information!

**Comment by foldedpaper** [comment]
Hi, I am not accessing through a proxy. I noticed today that the error may be OS-specific. I run into the `Unhandled promise rejection` error when I am using Firefox 58.0 on OS X 10.11.6

But if I access mattermost with Firefox 58.0 on Windows 10, no error. Site loads fine.

**Comment by jespino** [comment]
After testing it in Firefox 58.0 on OS X 10.11.6 in private window, looks like everything works correctly.

Could you try it against pre-release.mattermost.com? Could you try with another computer with Firefox 58.0 and OS X against your own instance? Looks like some kind of communication problem between your instance and your browser, normally it is related to proxies or firewalls.

**Comment by jespino** [comment]
After testing it in Firefox 58.0 on OS X 10.11.6 in private window, looks like everything works correctly.

Could you try it against pre-release.mattermost.com? Could you try with another computer with Firefox 58.0 and OS X against your own instance? Looks like some kind of communication problem between your instance and your browser, normally it is related to proxies or firewalls.

**Comment by TheJuln** [comment]
Hi @jespino, @lindy65 

I'm facing the same issue but I found the root cause (in my case).

**Setup**
- Firefox 58.0 (no addons) & Firefox 58.0 (uBlock-HTTPS Everywhere)
- Private Mode

For "security" reason I have disabled manually "WebRTC" in Firefox (about:config) :
`Set "media.peerconnection.enabled" to "false"`

WebRTC is a new communication protocol that relies on JavaScript that can leak your actual IP address from behind your VPN for example.
Demo : https://diafygi.github.io/webrtc-ips/

When I check the console :
```
TypeError: **e.RTCPeerConnection is undefined**
Stack trace:
shimMaxMessageSize@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:3221441
e.exports@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:3164066
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:3162799
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:3162763
t@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:96
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:3157471
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:3119419
t@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:96
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:3095794
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:3095404
t@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:96
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:3092895
t@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:96
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:2119297
t@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:96
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:2118177
t@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:96
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:713
@https://pre-release.mattermost.com/static/0.9e9ea31be215edf445f2.js:1:67
t@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:96
e.exports/<@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:702320
P/</<@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:199546
P/<@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:199416
c@https://pre-release.mattermost.com/static/main.ebd1b7ef2b2ff32e82d8.js:1:72180
bootstrap%20ebd1b7ef2b2ff32e82d8:141:42
Unhandled promise rejection 
```

So I decided to restore the default setting in Firefox :
`"media.peerconnection.enabled" to "true"` and it's working again !
Strangely, you won't have the problem if you block WebRTC through uBlock settings: "Prevent WebRTC from leaking local IP addresses"

I'm using Mattermost since few years (great job keep it up! 👍  ) , do you know why we have this behavior ?

**Comment by jespino** [comment]
Wow! Awesome, thank you very much @TheJuln, this is really helpful. @foldedpaper, @whereswaldon Could you try that solution. Anyway I going to investigate how to detect and prevent this behavior.

**Comment by foldedpaper** [comment]
Wow indeed. I followed @TheJuln 's suggestion and switched `"media.peerconnection.enabled"` to `"true"` (didn't realize I had it set to `"false"` in the first place), and I can successfully connect on OSX / Firefox.

Also, I tested on Win 10 / Firefox, and found that the issue is the same there. When `"media.peerconnection.enabled"` is `"true"`, Mattermost works. When it is `"false"`, Mattermost fails to load, showing the `e.RTCPeerConnection is undefined` error. 

My previous assumption that the issue might be platform-specific was wrong in this case. The Windows 10 machine here had the `"media.peerconnection.enabled"` FIrefox setting at its default `"true"`, and it appears that was the reason why Win10 would work while OSX would not.

Thanks again to everyone for the help.

**Comment by whereswaldon** [comment]
I'm not in a position to test at the moment, but I have vague memories 
of manually disabling that over a year ago. I'll try playing with that 
setting. If I recall correctly, it is a security hazard to have that 
on. Has that changed?

**Comment by jespino** [comment]
I think the security problem is still there. The mattermost problem is that we use WebRTC library which fails when that setting is deactivated. We are working to allow people to use the application with that setting disabled. It will work correctly but without WebRTC support (I expect).

**Comment by whereswaldon** [comment]
I can verify that that setting was the problem for me. Thanks for figuring that out everyone!

**Comment by whereswaldon** [comment]
Thanks! Will there be a patch release to fix this, or do we need to wait
for the next monthly release?

**Comment by jasonblais** [comment]
@TheJuln @whereswaldon @foldedpaper Currently the plan is to fix the issue with v4.7.0 released on February 16th, given the workaround.

Feedback welcome.

**Comment by whereswaldon** [comment]
I can live with WebRTC until then, I think

**Comment by TheJuln** [comment]
Hi,
 I'm glad I was able to help !
Let's wait the fix to test it ! 👍

**Comment by TheJuln** [comment]
Hi @jasonblais @jespino,

I checked on your demo instance : https://demo.mattermost.com/ (latest stable version)
Issue solved for me ;-)

Thx !
J

**Comment by jasonblais** [comment]
Great to hear!

If anyone has issues with v4.7.0 or later, let us know. Will close this issue as resolved.

**Comment by zoiezy** [comment]
hi @jasonblais. I'm using V4.7.1 (4.7.3) here. But when I use:
`curl -X GET -d "client_id=***&client_secret=***" https://<HOST>`
I got:
`<!DOCTYPE html> <html lang=en> <head> <meta http-equiv=Content-Security-Policy content="script-src 'self' cdn.segment.com/analytics.js/ 'unsafe-eval'"> <meta http-equiv=X-UA-Compatible content="IE=edge"> <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0"> <meta name=robots content="noindex, nofollow"> <meta name=referrer content=no-referrer> <title>Mattermost</title> <meta name=apple-mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-status-bar-style content=default> <meta name=mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-title content=Mattermost> <meta name=application-name content=Mattermost> <meta name=format-detection content="telephone=no"> <link rel=apple-touch-icon sizes=57x57 href=/static/files/78b7e73b41b8731ce2c41c870ecc8886.png> <link rel=apple-touch-icon sizes=60x60 href=/static/files/51d00ffd13afb6d74fd8f6dfdeef768a.png> <link rel=apple-touch-icon sizes=72x72 href=/static/files/23645596f8f78f017bd4d457abb855c4.png> <link rel=apple-touch-icon sizes=76x76 href=/static/files/26e9d72f472663a00b4b206149459fab.png> <link rel=apple-touch-icon sizes=144x144 href=/static/files/7bd91659bf3fc8c68fcd45fc1db9c630.png> <link rel=apple-touch-icon sizes=120x120 href=/static/files/fa69ffe11eb334aaef5aece8d848ca62.png> <link rel=apple-touch-icon sizes=152x152 href=/static/files/f046777feb6ab12fc43b8f9908b1db35.png> <link rel=icon type=image/png sizes=16x16 href=/static/files/02b96247d275680adaaabf01c71c571d.png> <link rel=icon type=image/png sizes=32x32 href=/static/files/1d9020f201a6762421cab8d30624fdd8.png> <link rel=icon type=image/png sizes=96x96 href=/static/files/fe23af39ae98d77dc26ae8586565970f.png> <link rel=icon type=image/png sizes=192x192 href=/static/files/d7ff68a7675f84337cc154c3d4abe713.png> <link rel=manifest href=/static/files/fee9721a6305a49662a40ffd052a7965.json> <link rel=stylesheet class=code_theme> <style>.error-screen{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding-top:50px;max-width:750px;font-size:14px;color:#333;margin:auto;display:none;line-height:1.5}.error-screen h2{font-size:30px;font-weight:400;line-height:1.2}.error-screen ul{padding-left:15px;line-height:1.7;margin-top:0;margin-bottom:10px}.error-screen hr{color:#ddd;margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee}.error-screen-visible{display:block}</style> <link href="/static/main.24a544c47d6d0deb4fe7fff736dbba2b.css" rel="stylesheet"><link href="/static/main.e9174e20b2779aa68c3bda09d882c5bc.css" rel="stylesheet"><script type="text/javascript" src="/static/main.91d3a516df3202227c6c.js"></script></head> <body class=font--open_sans> <div id=root> <div class=error-screen> <h2>Cannot connect to Mattermost</h2> <hr/> <p>We’re having trouble connecting to Mattermost. If refreshing this page (Ctrl+R or Command+R) does not work, please verify that your computer is connected to the internet.</p> <br/> </div> <div class=loading-screen style=position:relative> <div class=loading__content> <div class="round round-1"></div> <div class="round round-2"></div> <div class="round round-3"></div> </div> </div> </div> <noscript> To use Mattermost, please enable JavaScript. </noscript> </body> </html>`

Can help check about it?

**Comment by jasonblais** [comment]
Hey @zoiezy! 

At the end of the error message I noticed `To use Mattermost, please enable JavaScript.`. So it seems JavaScript has been disabled.

You can enable it with instructions here: https://www.enable-javascript.com/

Let me know if that helps?

**Comment by zoiezy** [comment]
@jasonblais  Sry, I don't wanna to use browser here.
I try to make a robot to change mattermost headers via API here. 
Is that possible?

**Comment by jasonblais** [comment]
Hmm, I'm not sure. What are you trying to accomplish by changing the headers via APIs?

**Comment by zoiezy** [comment]
@jasonblais Just a program to update headers of certain channels every week automaticly.

**Comment by jasonblais** [comment]
@zoiezy Certainly, that can be done via the API, here's documentation about the API call: https://api.mattermost.com/#tag/channels%2Fpaths%2F~1channels~1%7Bchannel_id%7D%2Fput

**Comment by jasonblais** [comment]
How are you making the http requests? With a terminal?
