### ISSUE TITLE
Tab and alt-tab keyboard navigations go the wrong way (reversed) for the login web page's bottom links.

### ISSUE THREAD

**Issue by antdude** [mattermost/mattermost-server#8000]
#### Summary
Tab and alt-tab keyboard navigations go the wrong way (reversed)

#### Steps to reproduce
1. Assuming never logged into MatterMost.com, go to https://oss.mattermost.com/login web page (last modified on (Wednesday, November 22, 2017 2:45:39 PM) in Internet Explorer v11/SeaMonkey v2.49.1 (User agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0 SeaMonkey/2.49.1) web browser (reproduced in both of them) in an updated 64-bit W7 SP1 OS (HPE for me).
2. Press tab key multiple times to reach to the bottom to Help link.
3. Pressing it more goes left links (e.g., Terms, Privacy, and About).

#### Expected behavior
Pressing tab key should go from left to right. Pressing both shift and tab keys go right with these bottom links.

#### Observed behavior (that appears unintentional) 
At the bottom links, pressing tab key goes to their left links (e.g., Terms, Privacy, and About). Pressing both shift and tab keys go right with these bottom links.

#### Possible fixes
Unknown.

**Comment by SmartHoneybee** [comment]
#### Possible fixes

* introduce wrapper around Terms, Privacy, About, ... content with class `pull-right`
* remove class `pull-right` from wrapper content
* reverse order of wrapper content (to maintain current ordering)
* should probably happen somewhere in `mattermost-webapp` ([`NotLoggedIn` class][1], maybe)

(Somewhat related example: https://www.bootply.com/fUltcZAv78 - `div` is wrapper; content has no `pull-right` class.)

[1]: https://github.com/mattermost/mattermost-webapp/blob/eae42c85a9ef04c50db3d046d3c063af208bb199/components/header_footer_template/header_footer_template.jsx

**Comment by lindy65** [comment]
Hi @antdude @SmartHoneybee 

Thanks for your feedback,

I've reproduced your issue and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8455) to track.

**Comment by antdude** [comment]
Thanks Lindy65. Wow, two bug trackers?

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.

**Comment by antdude** [comment]
OK, lindy65. :)
