### ISSUE TITLE
demo site - create new account allows empty space on email label

### ISSUE THREAD

**Issue by martincontuci** [mattermost/mattermost-server#8004]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Email field to create a new account allows empty spaces

#### Steps to reproduce
go to site https://oss.mattermost.com/signup_email
click on create new account
input an email with empty spaces such as hiirjrj @hfjfj.com

#### Expected behavior
field should alert that email is not valid

#### Observed behavior (that appears unintentional) 
it allows empty spaces on email

#### Possible fixes
Validate email field properly

**Comment by lindy65** [comment]
Hi @martincontuci,

Thanks for your feedback,

I believe [this ticket](https://mattermost.atlassian.net/browse/PLT-8248) will address your issue and will be fixed when v4.6 releases on January 16th.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can reopen if you still see issues after v4.6 ships.
