### ISSUE TITLE
The modal from "Account Settings" changes size when navigating through the different options

### ISSUE THREAD

**Issue by jgonzalezalbisu** [mattermost/mattermost-server#8007]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
The modal from **_Account Settings_** changes size when navigating through the different options.

#### Steps to reproduce

1. Go to http://demo.mattermost.com and login using valid credentials.
2. Once logged in, click in the _**Main Menu**_ button, and click _**Account Settings**_.
3. Once in _**Account Settings**_ modal, observe the size of the modal.
4. Navigate through the _**Account Settings**_ options by clicking on them (for example, click the _**Security**_ option). Observe the size of the modal.

#### Expected behavior
The **_Account Settings_** modal should not change its size when changing among options. The size should be the same.

#### Observed behavior (that appears unintentional) 
The modal from **_Account Settings_** changes size when navigating through the different options. For example, observing the screenshots you will see that the size of the modal when in _**General**_ menu, differs from the size of the modal when in _**Security**_.
<img width="413" alt="1" src="https://user-images.githubusercontent.com/23585745/34358926-9b69069e-ea32-11e7-8133-33cced022dba.png">
<img width="405" alt="2" src="https://user-images.githubusercontent.com/23585745/34358927-9b927556-ea32-11e7-9b3e-0d7059fe6508.png">

**Comment by lindy65** [comment]
Hi @jgonzalezalbisu,

Thanks for your feedback,

Although I have reproduced your issue on our nightly build server running v4.5, I believe this is by design and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8452) for one of our product managers to take a look at and verify the expected.

They're out for the holidays but will respond after January 2nd.

**Comment by lindy65** [comment]
I'll close this off for now and we can track via the ticket linked above.
