### ISSUE TITLE
Regular text is displayed as link

### ISSUE THREAD

**Issue by ronid** [mattermost/mattermost-server#8011]
Hey,
Regular text such as `aa:bb` displayed in channel as link, the problem seems to be when using text in format `\w*:\w*`.

Screenshot is attached.
<img width="218" alt="mattermost" src="https://user-images.githubusercontent.com/9270263/34411252-44cc7f16-ebde-11e7-9ffd-8d6a114f6d05.PNG">

**Comment by lindy65** [comment]
Hi @ronid,

Thanks for your feedback,

@hmhealey was working on this recently so perhaps he can chime in on this to clarify...

**Comment by hmhealey** [comment]
Hi @ronid,

The reason we do that is so that people can use links to arbitrary software like `phone:555-1234` or `steam://friends`, but that feature has been a bit too permissive so we're going to add a setting to better control that behaviour. I'll post back here once a ticket has been drafted.

**Comment by hmhealey** [comment]
The ticket to add a whitelist is [here](https://mattermost.atlassian.net/browse/PLT-8462). We're still reviewing a couple things with it, but once that's done, it'll be opened up as a Help Wanted ticket for anyone who wanted to work on it

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above.
