### ISSUE TITLE
[bug] Blank white screen appears when clicking on the edit button of the channel url in channel creation modal

### ISSUE THREAD

**Issue by giladgd** [mattermost/mattermost-server#8017]
#### Summary
A blank white screen appears when clicking on the edit button of the url in channel creation modal.

#### Steps to reproduce
Have Mattermost 4.5.0
1. Click on the '+' button to create a new public channel
2. Fill the title with "test test"
3. Click on the edit button of the url
4. A blank white screen will appear

#### Expected behavior
Being able to edit the url of the new channel (a side note of UX, I think that the edit button is redundant and being able to edit the url right away in the creation modal itself would be better for the user)

#### Observed behavior (that appears unintentional) 
A white screen appears and refreshing the page doesn't help. You have to go back to be able to continue use Mattermost, and you won't be able to create a channel with custom url.

#### Possible fixes
This is probably a bug in the webapp

**Comment by lindy65** [comment]
Hi @giladgd,

Thank you for your feedback,

I am not able to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master so it seems the issue has been fixed and will ship with the next release on January 16th.

**Comment by giladgd** [comment]
Hi @lindy65,
I've updated the steps to reproduce based on more tests I performed.
The bug seems to happen when a url could not be generated for the newly created channel due to a lack of English characters in the title text.
I suggest as a simple fix to generate a random text or string for the channel url when no relative-to-title url could be generated.

**Comment by giladgd** [comment]
open #8017

**Comment by jasonblais** [comment]
@giladgd We actually submitted a bug fix for this for v4.6, which releases on January 16th.

https://mattermost.atlassian.net/browse/PLT-8454

If you want to try if the fix is resolved, you can sign up to our demo instance at demo.mattermost.com
