### ISSUE TITLE
Wrong System Time

### ISSUE THREAD

**Issue by z906522** [mattermost/mattermost-server#8020]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by z906522** [comment]
![mattermost_demo_bug](https://user-images.githubusercontent.com/35064079/34517833-a4bf1ace-f074-11e7-9cf8-43a8fe02cade.png)
Summary: System time appears to be ahead 11min.
Expected behavior: Time should be accurate. 
Possible fixes: Adjust system clock.

**Comment by lindy65** [comment]
Hi @z906522,

Thank you for your feedback,

I'm not able to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master so I believe the issue has been fixed and will ship with the next release on January 16th.

![image](https://user-images.githubusercontent.com/13020833/34518094-64b3495c-f086-11e7-82d4-11481860010c.png)

**Comment by vincentvignali** [comment]
I have the exact same issue as @z906522 
Desktop app.
Macbook air intel 2018.
Mattermost Version 5.0.4 (5.0.4.17220).

<img width="986" alt="Screenshot 2022-04-27 at 12 37 48" src="https://user-images.githubusercontent.com/51534315/165500265-a23ec291-4e6c-451e-80ff-472500e67539.png">
.

Check time system display up right and the time display of the message sent on mattermost.
