### ISSUE TITLE
[Help Wanted] [PLT-8383] Numbered list item with 3+ digits extends left and overlaps other elements

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8024]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8383)

A post that starts with a number followed by a dot and then some text formats as a numbered list item. When the number is three or more digits, the indentation causes it to extend left of where the message should start, overlapping with other elements.

1. Post a message `12345. Test`

Observed: Message text displays further left than the expected position
Expected: Message text begins in the normal position, even if many-digit numbered list item

![image](https://user-images.githubusercontent.com/13119842/34582866-7a9e065c-f163-11e7-8def-b90e5fa50f9b.png)

**Comment by sudheerDev** [comment]
@esethna @jasonblais I have a one line css fix for this. If the below UI change is acceptable i can create a PR for this.
On master
![screen shot 2018-01-05 at 12 56 19 pm](https://user-images.githubusercontent.com/4973621/34599414-286be1dc-f218-11e7-8597-f71c8e1c2f8d.png)

With fix
![screen shot 2018-01-05 at 12 56 59 pm](https://user-images.githubusercontent.com/4973621/34599423-35a9c120-f218-11e7-9d7a-209b3a5edbbd.png)

**Comment by jasonblais** [comment]
Is the added indentation expected?
![image](https://user-images.githubusercontent.com/13119842/34610442-1e628016-f1ef-11e7-93f1-6de2ce59da99.png)

**Comment by sudheerDev** [comment]
@jasonblais That's the default behaviour. I was gonna use this property to fix this https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position

I can add some negative margin to pull them back to position but not sure of the consequences.

**Comment by jasonblais** [comment]
@sudheerDev You can submit a PR and we can get it reviewed and tested, that sounds good 👍

**Comment by sudheerDev** [comment]
@jasonblais I adjusted the alignment as well.
