### ISSUE TITLE
[Help Wanted] [PLT-8347] Docs needed for CLI commands in Docker preview image

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8031]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8347)

We have documentation on how to run CLI commands on the production Docker image, but not on the Docker preview image.

We should add a brief section for it in the CLI docs: https://docs.mattermost.com/administration/command-line-tools.html#using-the-cli-on-docker-install

**Comment by falcon78921** [comment]
I'll take a crack at this! :)

Any guidance is greatly appreciated!

**Comment by jasonblais** [comment]
Thanks @falcon78921! :tada:

Here's a guide on how to set up the Docker preview image: https://docs.mattermost.com/install/docker-local-machine.html#one-line-docker-install

Let us know if you have any questions :) 

The docs change would be done in this file https://github.com/mattermost/docs/blob/master/source/administration/command-line-tools.rst

**Comment by falcon78921** [comment]
Hi @jasonblais, 

I've been experimenting with the Mattermost docker preview for a couple weeks now. While using the docker preview, I found some potential improvements that might help users experience Mattermost better. First, when I ran the initial ``docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview``, the container was successfully deployed. However, unlike the Mattermost production container, I found issues running commands via ``docker exec``. I wasn't able to run, say, ``docker exec -it c75174398511 mattermost`` without going in via interactive Bash and executing the commands. To remedy this, I added the Mattermost bin directory to the container PATH variable. I'm now able to run ``docker exec -it c75174398511 mattermost`` and get output:

```
root@system1:/home/sysadmin# docker exec -it c75174398511 mattermost
{"level":"info","msg":"Stopping Server..."}
{"level":"info","msg":"stopping websocket hub connections"}
{"level":"warn","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","msg":"Server stopped"}
{"level":"error","msg":"unable to load Mattermost translation files: Unable to find i18n directory"}
Error: unable to load Mattermost translation files: Unable to find i18n directory
Usage:
  mattermost [flags]
  mattermost [command]

Available Commands:
  channel     Management of channels
  command     Management of slash commands
  config      Configuration
  export      Export data from Mattermost
  help        Help about any command
  import      Import data.
  jobserver   Start the Mattermost job server
  ldap        LDAP related utilities
  license     Licensing commands
  permissions Management of the Permissions system
  reset       Reset the database to initial state
  roles       Management of user roles
  sampledata  Generate sample data
  server      Run the Mattermost server
  team        Management of teams
  user        Management of users
  version     Display version information

Flags:
  -c, --config string        Configuration file to use. (default "config.json")
      --disableconfigwatch   When set config.json will not be loaded from disk when the file is changed.
  -h, --help                 help for mattermost

Use "mattermost [command] --help" for more information about a command.
```
I opened a pull request on the Dockerfile: https://github.com/mattermost/mattermost-docker-preview/pull/35.

Now, even after modifying the PATH variable, I'm still unable to execute commands like ``docker exec -it c75174398511 mattermost version`` without going into the bin directory. There are other fixes I'm trying to implement, but for the sake of brevity, I'll stop there.

Going back to the original issue, I'm trying to build documentation for docker preview commands. However, when I look at the available commands for the preview image, they're about identical to the production image: https://docs.mattermost.com/administration/command-line-tools.html#using-the-cli-on-docker-install. 

Is there something I'm missing or could the docs for production commands be reused for the preview? I guess I'm just looking for some clarification as I'm still very new to the Mattermost software. Thanks!

**Comment by lieut-data** [comment]
Good catch, @falcon78921! I'm wondering if the recently fixed https://mattermost.atlassian.net/browse/MM-6839 would assist with the issue locating the i18n assets above. Previously, the binary was very sensitive to the working directory, but will now search both there and relative to the binary itself.

Can you give this a shot either once we release Mattermost 5.1? Or feel free to test a custom image using https://releases.mattermost.com/5.1.0-rc2/mattermost-5.1.0-rc2-linux-amd64.tar.gz.

**Comment by falcon78921** [comment]
Thanks @jasonblais & @lieut-data! :)

@lieut-data - Yeah, I'll try with the 5.1.0 release candidate.

**Comment by falcon78921** [comment]
Good news @lieut-data :)

I'm able to run mattermost commands directly from ``docker exec`` with 5.1.0-rc2:

```
docker exec -it a4c2522ac455 mattermost
{"level":"info","ts":1531258791.242923,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'en' from '/mm/mattermost/i18n/en.json'"}
{"level":"info","ts":1531258791.243087,"caller":"app/app.go:194","msg":"Server is initializing..."}
{"level":"info","ts":1531258791.2490804,"caller":"sqlstore/supplier.go:200","msg":"Pinging SQL master database"}
{"level":"error","ts":1531258796.2878654,"caller":"sqlstore/supplier.go:212","msg":"Failed to ping DB retrying in 10 seconds err=dial tcp: lookup dockerhost on 8.8.8.8:53: no such host"}
```
Only problem is that one of the checks calls for DNS resolution of dockerhost. This can be easily solved by adding ``--add-host dockerhost:127.0.0.1``  to ``docker run``, like so:

``docker run -it --add-host dockerhost:127.0.0.1 5c41e2d919c0``

I opened a pull request for this in the mattermost/docs repo (https://github.com/mattermost/docs/pull/2144). I'm thinking that users might be experiencing this now, so I updated the documentation to reflect this fix.

**Comment by lieut-data** [comment]
Excellent! 

The `dockerhost` anomaly /should/ only be an artifact of our development environment. Any idea why the database configuration is pointing at `dockerhost` in the first place? I don't see anywhere in https://github.com/mattermost/mattermost-docker-preview where the `dockerhost` is used instead of just `localhost`.

**Comment by falcon78921** [comment]
@lieut-data I don't know either. I checked ``sqlstore/supplier.go`` and didn't see anything referencing ``dockerhost`` directly. The error is definitely related to opening the MySQL connection. I checked my Docker installation (Docker 18.03 CE) and didn't find anything odd either. 

I'll keep looking. If I find something, I'll be sure to ping! :)

**Comment by falcon78921** [comment]
Hi @jasonblais,

I think this should do it: https://github.com/mattermost/docs/pull/2310

**Comment by jasonblais** [comment]
Thank you @falcon78921 !
