### ISSUE TITLE
Improve how UI elements in the message view indicate focus

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8034]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7685)

For 508 compliance, each interactive element should have visible focus when the user tabs to the element using the keyboard. Some interactive elements on the page have visible focus using a dotted outline, change in color, or in the case of the + signs on the page getting brighter.  

Currently, the user is not able to determine where they are while tabbing because of frequent loss of a visible indicator of current focus.

Proposed changes for the expected tab order (follows Slack):
1. Assume message box is in focus
2. File upload paperclip icon (current: not tabbed + no visual cue when in focus)
3. Emoji picker icon (current: not tabbed + no visual cue when in focus)
4. "Preview" below message box (current: not tabbed + not underlined when in focus)
5. "Help" below message box (current: gets tabbed + visual cue)
6. Team icons and + sign in the team sidebar (current: gets tabbed + visual cue)
7. Profile status indicator in channel sidebar (current: not tabbed)
7. Main menu in channel sidebar (current:  gets tabbed + visual cue)
8. Channel sidebar from top to bottom, including "+" signs, channel names, "x" button on DMs, "More.." and channel switcher button. (current: get tabbed but no visual cue)
9. Channel header from left to right, including star, "v" next to channel name, channel description, channel member list, pin icon, search bar, at-mention icon, flag icon (current: most don't get tabbed nor have a visual cue)
10. "Set a header" in channel intro, if shown on the UI (current:  gets tabbed + visual cue)
11. For each message, tabs through profile picture, username, timestamp, flag icon, [...] menu, emoji icon, reply arrow, links in post, emoji reactions (current: only timestamp and links gets tabbed)
12. Right-hand sidebar, from top to bottom, including expand arrow, close sidebar icon, username, timestamp, [...], emoji, links, and reactions of messages, comment box, file upload icon, emoji picker icon, "Preview" link, "Help" link, "Add Comment" box (current: not tabbed)
13. URL bar if on browser
14. Back to center pane message box.

NOTE: Here's a branch that started the work on this issue: https://github.com/santos22/mattermost-webapp/commit/88b2d1e4ae6bbc6f764c1f1f6b0313888e63ef51, and here is a PR that completed about half of the above items: https://github.com/mattermost/mattermost-webapp/pull/919

You can consider using https://github.com/WICG/focus-ring to focus on each of the elements when tabbing.

**Comment by jasonblais** [comment]
@santos22 I saw a note from you on the JIRA ticket, would you be interested working on this one?

**Comment by santos22** [comment]
Hey @jasonblais I can take a look 😄

**Comment by jasonblais** [comment]
Hey @santos22, any questions so far? :)

**Comment by santos22** [comment]
Hey @jasonblais,

I just posted a question in the Contributors channel 👍

**Comment by santos22** [comment]
Hey @jasonblais,

A quick update - making slow progress on this but I am seeing the pin icon, search bar, at-mention icon, flag icon, etc. get visible focus while tabbing 👍 

Working on applying this to all the elements in the ticket

**Comment by jasonblais** [comment]
That's awesome!! Thank you @santos22 👍

**Comment by santos22** [comment]
Hey @jasonblais,

I won't be able to spend much time on this issue in the coming weeks - I understand the importance of it so hopefully someone else can complete the work! Regarding my previous comment, one can refer to the following commit on my fork - https://github.com/santos22/mattermost-webapp/commit/88b2d1e4ae6bbc6f764c1f1f6b0313888e63ef51

**Comment by jasonblais** [comment]
Thanks @santos22 for the heads up! I've included your commit in the issue description, really appreciate your help getting started on this issue 👍

**Comment by cpanato** [comment]
Hello @santos22, I can help on this, but also would like you to have the credits as well, can you please open the PR with all code you have so far, and then I can push commits to finish the work? if that you can the authored commits as well, since you already put a lot of effort on this.

what do you think?

**Comment by santos22** [comment]
Hey @cpanato! I would really appreciate that. There was really only one change where I added a `overflow: hidden` property and everything else was just commenting out the focus property where the outline was 0 or none. I will create the PR 👍

**Comment by cpanato** [comment]
link the PR here: https://github.com/mattermost/mattermost-webapp/pull/919
