### ISSUE TITLE
Password Reset Feature- No Account existence verified

### ISSUE THREAD

**Issue by Ojavedan** [mattermost/mattermost-server#8043]
#### Summary
Password Reset feature does not check for Account Existence.

#### Steps to reproduce
1-Navigate to Login Page (https://oss.mattermost.com/login)
2-Click the Forgot My Password link
3- Specify any Email Address and click the Reset My Password button.
#### Expected behavior
The Application should in the first place verify that the email provided by the user does not exist in the system database (Meaning it is not for a returning user) and/or not the email that the an existing user has provided as an alternate email address for password recovery.

#### Observed behavior (that appears unintentional) 
Without any verification the application seemingly proceeds with Password Reset feature and also shows a confirmation message that an email has been sent to the email address specified, The Email however is never received in the inbox

#### Possible fixes
The application should validate the email address used for Password Reset Feature.  It should be either the Original email that the user entered for his account or at least an alternate email address that the user specified for password recovery.
![password reecoved issue-bug](https://user-images.githubusercontent.com/33222072/34613694-78d0daaa-f250-11e7-90c1-8be90e18b65c.jpg)

**Comment by lfbrock** [comment]
Hi @Ojavedan - I think the behaviour here matches what's typical on other sites - generally, if the account exists a password reset email is sent and if not there is no notice given on the password reset page. 

However, if the account doesn't exist it might make sense to send an email saying something like "A password reset was requested for this email, but no account with that email exists." That way, it would be clear the incorrect email address was used for the password reset. 

Would that solve the problem for you?

**Comment by lindy65** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid.  If you still experience the same problem, try upgrading to the latest version.  If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
