### ISSUE TITLE
[Help Wanted] [PLT-8455] Tab and alt-tab keyboard navigations go the wrong way (reversed) for the login web page's bottom links

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8046]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8455)

**Comment by santos22** [comment]
I can take this!

**Comment by antdude** [comment]
FYI. https://github.com/mattermost/mattermost-server/issues/8000 for my 18 days old bug report. :)

**Comment by lindalumitchell** [comment]
Thanks! This has been merged and tested on master, and looks great. Closing this issue.
