### ISSUE TITLE
Login page cannot be opened after logout from the 'Account Settings' modal (incorrect userId value)

### ISSUE THREAD

**Issue by useitfortest** [mattermost/mattermost-server#8049]
#### Summary
The user cannot be redirected to login page after logout

#### Steps to reproduce
1. Go to https://oss.mattermost.com/login
2. Login
3. Go to Account Settings > Security > View and Logout of Active Sessions
4. Click Logout

#### Expected behavior
Login page is displayed (https://oss.mattermost.com/login)

#### Observed behavior (that appears unintentional) 
Blank page is displayed, the user has to refresh the page to get login form

#### Possible fixes
The following errors occur in the browser console. In accordance with error stack the issue is related with userId (index.jsx, line 15)

`[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (sessions, line 0)
[Error] TypeError: undefined is not an object (evaluating 't.id') — index.jsx:15
	l (main.084b36cb08417d5af430.js:1:1679689)
	s (main.084b36cb08417d5af430.js:1:1678484)
	y (main.084b36cb08417d5af430.js:1:1681737)
	v (main.084b36cb08417d5af430.js:1:1681465)
	m (main.084b36cb08417d5af430.js:1:1680704)
	p (main.084b36cb08417d5af430.js:1:1680111)
	enqueueSetState (main.084b36cb08417d5af430.js:1:1654538)
	setState (main.084b36cb08417d5af430.js:1:1633211)
	onPreferenceChange (0.0e5eff376b85e2243d7b.js:1:37608)
	emit (main.084b36cb08417d5af430.js:1:304425)
	value (main.084b36cb08417d5af430.js:1:493117)
	(anonymous function) (main.084b36cb08417d5af430.js:1:491475)
	u (main.084b36cb08417d5af430.js:1:971016)
	(anonymous function) (main.084b36cb08417d5af430.js:1:2025663)
	(anonymous function) (main.084b36cb08417d5af430.js:1:2031279)
	dispatch (main.084b36cb08417d5af430.js:1:1738279)
	(anonymous function) (main.084b36cb08417d5af430.js:1:402212)
	a (main.084b36cb08417d5af430.js:1:1613606)
	(anonymous function) (main.084b36cb08417d5af430.js:1:1614723)
	(anonymous function) (main.084b36cb08417d5af430.js:1:1613788)
	a (main.084b36cb08417d5af430.js:1:400373)
	(anonymous function) (main.084b36cb08417d5af430.js:1:400468)
	(anonymous function) (main.084b36cb08417d5af430.js:1:1594213)
	(anonymous function) (main.084b36cb08417d5af430.js:1:1594321)
	c (main.084b36cb08417d5af430.js:1:640152)
[Error] Unhandled promise rejection – TypeError: undefined is not an object (evaluating 't.id') — index.jsx:15
	(anonymous function) (main.084b36cb08417d5af430.js:1:1594562)
	exports (main.084b36cb08417d5af430.js:1:959350)
	(anonymous function) (main.084b36cb08417d5af430.js:1:1594433)
	exports (main.084b36cb08417d5af430.js:1:570504)
	(anonymous function) (main.084b36cb08417d5af430.js:1:639316)
	_ (main.084b36cb08417d5af430.js:1:639174)
	v (main.084b36cb08417d5af430.js:1:639199)
`

#### Environment
Last activity: January 6, 2018, 12:37
First time active: January 6, 2018, 12:37
OS: Intel Mac OS X 10_11_5
Browser: Safari/9.1.1

![2018-01-06 12 53 47](https://user-images.githubusercontent.com/35164265/34638629-da2684fe-f2e0-11e7-8fa3-8ce1355a7b45.png)
![2018-01-06 12 54 03](https://user-images.githubusercontent.com/35164265/34638630-da4e016e-f2e0-11e7-99ff-0bb97c58e7de.png)
![2018-01-06 12 54 33](https://user-images.githubusercontent.com/35164265/34638631-da6ef162-f2e0-11e7-9b78-54c2d879b053.png)

**Comment by lindy65** [comment]
Thanks @useitfortest,

I've reproduced your issue and have filed [this ticket](https://mattermost.atlassian.net/browse/PLT-8509) to track.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
