### ISSUE TITLE
Blank Screen on Firefox

### ISSUE THREAD

**Issue by newhinton** [mattermost/mattermost-server#8051]
#### Summary
Firefox has problems loading mattermost, it seems to falsely detect javascript beeing disabled and tries to show the appropriate error message, which also fails.

#### Steps to reproduce
Use Firefox to open the Mattermost web client, and reload
You need to be logged in

#### Expected behavior
Mattermost UI opens

#### Observed behavior (that appears unintentional) 
Blank screen, Error message does not load, but source code of the page reveals that javascript could not be loaded.

#### Possible fixes
Sometimes reloads, sometimes Ctrl+Shift+R
The Error Message does not display, regardless of what i do.

Using:
Ubuntu 16.04
mysql 14.14
Mattermost 4.5.0

(Firefox 57.0.4, addons:
noscript, greasemonkey, ublock, umatrix, idontcareaboutcookies
this problem exists regardless of the activation status of the addons.
I have also tested this on a clean firefox, and the mobile version of Firefox,
Opera and Internet Explorer. All show the same blank screen
The Login page seems to load fine.)

If you need further information, feel free to ask :)
And thank you for your help!  

The not really displayed error message:

`<!DOCTYPE html> <html> <head> <meta http-equiv=X-UA-Compatible content="IE=edge"> <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0"> <meta name=robots content="noindex, nofollow"> <meta name=referrer content=no-referrer> <title>Mattermost</title> <meta name=apple-mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-status-bar-style content=default> <meta name=mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-title content=Mattermost> <meta name=application-name content=Mattermost> <meta name=format-detection content="telephone=no"> <link rel=apple-touch-icon sizes=57x57 href=/static/files/787db8d8b82538cc1d5e8bcb8c21722d.png> <link rel=apple-touch-icon sizes=60x60 href=/static/files/cd9987714f4d92336c3ab203ff150a9a.png> <link rel=apple-touch-icon sizes=72x72 href=/static/files/1728fd5a009aabc77654b1f958c6f596.png> <link rel=apple-touch-icon sizes=76x76 href=/static/files/17cb12b7fc37d8229a6e72f3d6da0949.png> <link rel=apple-touch-icon sizes=144x144 href=/static/files/fba6362db1d8b3e27c9fb02fd0695c85.png> <link rel=apple-touch-icon sizes=120x120 href=/static/files/08959a08dc2488dfeb8660fc4630b145.png> <link rel=apple-touch-icon sizes=152x152 href=/static/files/bca263be9acd1df84b988b02c621b8ca.png> <link rel=icon type=image/png sizes=16x16 href=/static/files/b683bb2a73dff49849bd5c0de5499e69.png> <link rel=icon type=image/png sizes=32x32 href=/static/files/f3a30fd11b4f31d5b405a52bb18942ae.png> <link rel=icon type=image/png sizes=96x96 href=/static/files/14367343175bc65d6e20fd235c356db4.png> <link rel=icon type=image/png sizes=192x192 href=/static/files/0d367a00a16bde58f7e87c4481516a68.png> <link rel=manifest href=/static/files/fee9721a6305a49662a40ffd052a7965.json> <link rel=stylesheet class=code_theme> <style>.error-screen{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding-top:50px;max-width:750px;font-size:14px;color:#333;margin:auto;display:none;line-height:1.5}.error-screen h2{font-size:30px;font-weight:400;line-height:1.2}.error-screen ul{padding-left:15px;line-height:1.7;margin-top:0;margin-bottom:10px}.error-screen hr{color:#ddd;margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee}.error-screen-visible{display:block}</style> <script type="text/javascript" src="/static/main.f0aec68079cd6d39a4e5.js"></script></head> <body class=font--open_sans> <div id=root> <div class=error-screen> <h2>Cannot connect to Mattermost</h2> <hr/> <p>We’re having trouble connecting to Mattermost. If refreshing this page (Ctrl+R or Command+R) does not work, please verify that your computer is connected to the internet.</p> <br/> </div> <div class=loading-screen style=position:relative> <div class=loading__content> <div class="round round-1"></div> <div class="round round-2"></div> <div class="round round-3"></div> </div> </div> </div> <script>"function"!=typeof window.setup_root&&document.querySelector(".error-screen").classList.add("error-screen-visible"),window.setup_root()</script> <noscript> To use Mattermost, please enable JavaScript. </noscript> </body> </html> `

**Comment by newhinton** [comment]
It seems that this problem is fixed after an upgrade to Version: 4.6.0  (4.6.0-rc1).
I'll close this ticket in a few hours, when the issue does not reappear.

**Comment by lindy65** [comment]
Thanks @newhinton,

Let us know how it goes!

**Comment by newhinton** [comment]
This error did not show up under 4.6.0-rc1, so i will mark this as successfully closed. Thank you for your time!

**Comment by joernheissler** [comment]
I just got the same problem.

amd64, Ubuntu 17.10, Firefox 57.0.4 (Ubuntu version), Mattermost 4.6.0.
Could this please be investigated again?

**Comment by ezawadzki** [comment]
Same here :

mac OS (10.13.3) => Firefox 57.0.4 
debian 4.14.0-3-amd64 => Firefox 52.5.0

**Comment by lindy65** [comment]
@joernheissler @ezawadzki 

Thanks for your feedback,

We have a similar [issue](https://github.com/mattermost/mattermost-server/issues/7996) open where it seems the problem could relate to proxies or be OS specific.

Could we have your help trying to connect to our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) to see if the issue reproduces for you?

**Comment by joernheissler** [comment]
Nope, doesn't work.

**Comment by joernheissler** [comment]
But strangely it works on my other computer running Debian. FF 57.0.3 with noscript+ublock here.

**Comment by joernheissler** [comment]
Upgraded to Firefox 58.0 (Ubuntu version); still same issue.

**Comment by joernheissler** [comment]
Also tried the vanilla firefox  (i.e. not Ubuntu). Same problem.

**Comment by ezawadzki** [comment]
It works on Firefox if I run `make build-client` (so I guess in prod mode). But not with `make run` command.

**Comment by jasonblais** [comment]
@jespino Another ticket here with issues logging into Firefox.

**Comment by jespino** [comment]
@ezawadzki @joernheissler Could you check if this solution https://github.com/mattermost/mattermost-server/issues/7996#issuecomment-361053921 works for you? I want to confirm if that is the same bug or a different one.

**Comment by joernheissler** [comment]
Setting media.peerconnection.enabled to true fixed the issue.
I can't remember having it set to false, but it definitely sounds like something that I would have done :-)

Thank you!

**Comment by jespino** [comment]
Thank you. We going to try to fix the problem anyway, but until then, that is a good workaround. :)

**Comment by jespino** [comment]
Duplicated #7996
