### ISSUE TITLE
Leaving a channel causes js error & blank page as a result

### ISSUE THREAD

**Issue by useitfortest** [mattermost/mattermost-server#8053]
#### Summary
The user can leave a channel, but with the blank page after that

#### Steps to reproduce
1. Login as user A & create a new private channel then add user B there, logout
2. Login as user B & select created private channel
3. Expand context menu for the channel, then click 'Leave Channel'

#### Expected behavior
Default channel is opened, the private channel is not available for the user B

#### Observed behavior (that appears unintentional) 
Blank page is displayed, after refreshing it the user B doesn't have the private channel that has been left

#### Possible fixes
The following errors occur after clicking 'leave channel' (incorrect object value should be fixed in accordance with error stack):
![2018-01-06 18 29 46](https://user-images.githubusercontent.com/35164265/34641133-35599ada-f310-11e7-8502-f12dfe460889.png)
![2018-01-06 18 29 59](https://user-images.githubusercontent.com/35164265/34641221-cc991d48-f311-11e7-833d-a2577ca9685d.png)

After refreshing the page browser console contains the following one:
`Unrecognized Content-Security-Policy directive 'frame-ancestors'.`

#### Environment
OS: Intel Mac OS X 10_11_5
Browser: Safari/9.1.1

**Comment by lindy65** [comment]
Thanks @useitfortest 

I've reproduced your bug report and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8508) to track.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
