### ISSUE TITLE
Layout - Quote cut off when in header

### ISSUE THREAD

**Issue by catiwumpus** [mattermost/mattermost-server#8054]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
When a quote is entered into a room header, the text is cut off.

#### Steps to reproduce
Version: 4.6.0  (4.6.0-rc1)
Not browser specific
Repro Steps:
 - Enter a Channel
 - Click Channel title drop down
 - Select Edit Channel Header
 - Enter text with quote formatting (i.e. >testing )
 - click Save
 - Observe header is cut off horizontally

#### Expected behavior
Expect to fully see text displayed

#### Observed behavior (that appears unintentional) 
![capture](https://user-images.githubusercontent.com/11294372/34643946-616446d0-f2fb-11e7-903a-fc8ef19992ab.PNG)

**Comment by SmartHoneybee** [comment]
This looks similar to #8036.

**Comment by lindy65** [comment]
Thanks @catiwumpus @SmartHoneybee 

Yes, this issue is similar to #8036 except if a "quote" is used in the first line of the channel header it is definitely cut off.

I'll post to the product manager as they'll need to discuss this to see how / if they can make changes to the UI.

**Comment by lindy65** [comment]
Hi @catiwumpus @SmartHoneybee 

We've opened a [ticket](https://mattermost.atlassian.net/browse/PLT-8514) to improve the layout of the header so quotes can be accommodated.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
