### ISSUE TITLE
intermittent tool tips in message details

### ISSUE THREAD

**Issue by ChavdarEmilov** [mattermost/mattermost-server#8055]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
In the message detail panel when selecting an icon a tool tip is shown but is intermittent and the text can not be read.
![414a58b5-f850-4c0e-af0a-949dad748ce9](https://user-images.githubusercontent.com/31213355/34649022-53edb18e-f3a6-11e7-823c-af44b5115dc7.jpg)
#### Steps to reproduce
1 Access the message details section of any message
2 Move mouse over expand or close button

Browser: Vivaldi 1.13.1008.34 Windows 64bit
#### Expected behavior
The tool tip should be readable.
#### Observed behavior (that appears unintentional) 
The tool tip is intermittent and cannot be read.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lindy65** [comment]
Hi @ChavdarEmilov,

Thanks for your feedback,

Vivaldi is not a supported browser.  You can find a list of supported browsers [here](https://docs.mattermost.com/install/requirements.html#pc-web-experience).
