### ISSUE TITLE
Several history access log issues

### ISSUE THREAD

**Issue by ChavdarEmilov** [mattermost/mattermost-server#8056]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Two bugs have been observed in user configuration, security tab, history access log:
1 When a user successfully log in the platform extra event is recorded with status unsuccessful log in.
2 There are several events duplicated in the log. Possible incorrectly recorded or just a visualization problem. Not always occurring.
3 Suggestion: Add seconds to the time of the events for faster and more precise bug discovery and evaluation.
![c897687f-30d4-4243-9e1e-c26aa1ea5810](https://user-images.githubusercontent.com/31213355/34649103-4a2f0b32-f3a8-11e7-9b4c-03a834f948a9.jpg)

#### Steps to reproduce
The errors can be observed in the history access log modal in the security tab of the account configuration menu nested under main user menu.
#### Expected behavior
the log should not contain events that haven't occurred or repeated ones..

#### Observed behavior (that appears unintentional) 
Not existent events and repeated ones.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lindy65** [comment]
Hi @ChavdarEmilov,

Thank you for your feedback,

Could you help share which server version of Mattermost you're running as well as the exact steps we can follow to reproduce your issue?

**Comment by lindy65** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid.  If you still experience the same problem, try upgrading to the latest version.  If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
