### ISSUE TITLE
Reply icon is not in one line with other icons in Firefox 57.0.3 (64-bit)

### ISSUE THREAD

**Issue by alapanme** [mattermost/mattermost-server#8058]
#### Summary
Reply icon is not in one line with other icons in Firefox

#### Steps to reproduce
1. Hover the mouse to any post and observe.

#### Expected behavior
The [..], smiley icon and the reply icon should be on one line.

#### Observed behavior (that appears unintentional) 
The [..], Smiley icon is on one line but the reply icon is on next line.

![firefox_replyicon](https://user-images.githubusercontent.com/25705483/34650194-b1626062-f3e2-11e7-89d4-1de6d07da074.png)

**Comment by lindy65** [comment]
Thanks @alapanme,

I've reproduced your issue and have filed [this ticket](https://mattermost.atlassian.net/browse/PLT-8507) to track.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
