### ISSUE TITLE
No Preview for .tiff Images

### ISSUE THREAD

**Issue by alapanme** [mattermost/mattermost-server#8059]
#### Summary
No Preview for '.tiff' images

#### Steps to reproduce
1. Upload a .tiff image
2. Upon successful upload, observe the preview.

#### Expected behavior
A preview should be displayed.

#### Observed behavior (that appears unintentional) 
No image preview is displayed. An attachment icon is displayed.

![tiffimage](https://user-images.githubusercontent.com/25705483/34650505-47add8ee-f3e8-11e7-838c-caa40048fda4.PNG)

**Comment by lindy65** [comment]
Hi @alapanme,

Thanks for your feedback, 

I'm not sure what the expected is for .tiff files but will check with one of the product managers.

**Comment by lindy65** [comment]
Hi @alapanme,

I've checked what's expected in the product at the moment and .tiff file previews are not yet supported in the webapp but are in the mobile apps.  

Perhaps we could have your help opening a [feature request](https://mattermost.uservoice.com/forums/306457-general) for this feature in the webapp and post the link to the request back to this issue for continuity?

**Comment by lindy65** [comment]
Update:  It seems the fix for adding .tiff file previews is not a big code change so we've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8516) to track.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
