### ISSUE TITLE
Cursor change shows selectable link where link is un-selectable 

### ISSUE THREAD

**Issue by Misfit1982** [mattermost/mattermost-server#8060]
Summary: 
On the "Edit Channel Header" menu, hovering over the font format options the cursor changes to denote that the link can be clicked, however clicking this option does nothing.

Steps to Reproduce:
Go to achannel
Select the channel options drop down in upper left corner
Select to edit the channel header
hover over the text formatting options

Expected Result:
The cursor should not change to a clickable action unless the link is clickable. 

Actual Result:
The cursor changes to denote a clickable link when in fact is not clickable. 

*Note*
This issue appears on Safari, Chrome and FF.

![screen shot 2018-01-07 at 7 55 51 am](https://user-images.githubusercontent.com/35195359/34650676-3e5f66c4-f382-11e7-979b-cb677d7eb69b.png)
![screen shot 2018-01-07 at 7 55 49 am](https://user-images.githubusercontent.com/35195359/34650690-65caef58-f382-11e7-8b5a-bee851018f0e.png)

**Comment by lindy65** [comment]
Hi @Misfit1982,

Thanks for your feedback,

I've reproduced your issue and see that it also occurs anywhere these text formatting options occur (e.g. message text input box).  I've filed [this ticket](https://mattermost.atlassian.net/browse/PLT-8506) to track the issue.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
