### ISSUE TITLE
Mobile Classic App (browser) - the text box is hidden by the keyboard when replying to a post

### ISSUE THREAD

**Issue by alapanme** [mattermost/mattermost-server#8062]
#### Summary
The Textbox hides when clicked when replying to a Post on Mobile

#### Steps to reproduce
1. Click on the reply button.
2. Click on Post Text box.

#### Expected behavior
The keyboard shouldn't overlap the textbox and the textbox should be visible at all times.

#### Observed behavior (that appears unintentional) 
The Keyboard comes up, hiding the Post text box. Device: Galaxy S8, Android 7

![def2](https://user-images.githubusercontent.com/25705483/34651250-c67982bc-f3f3-11e7-91af-6dc2e3a4dbf7.gif)

**Comment by lindy65** [comment]
Hi @alapanme,

Thanks for your feedback,

Are you using the Classic App in the browser?  Or do you have the classic app installed on your phone?

I tried to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running v4.6 and wasn't able to.  However, I tested on Sony Xperia, Android 7.  I believe the behavior should be the same though.

**Comment by alapanme** [comment]
Hi @lindy65

I am using the classic App in browser. I am able to reproduce it every time as demonstrated in the attached GIF.

**Comment by lindy65** [comment]
Thanks @alapanme,

I tested in the Android App of Mattermost Classic so this must be browser-related behavior as it does not reproduce in the app.

I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8517) to track.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the Jira ticket linked above.
