### ISSUE TITLE
Wrong public channel displayed after closing a chat with a channel member 

### ISSUE THREAD

**Issue by StephaneColson** [mattermost/mattermost-server#8065]
#### Summary
Wrong public channel displayed after closing a chat with a channel member 

#### Steps to reproduce
- Using https://oss.mattermost.com
- Go see the public channel **"Buggy"**
- Say hi!
- Open the list member at the top and click on one of them to chat with him/her
- This new private conversation is now in the list of "Direct messages"
- Click on the cross of this new private conversation in order to "Remove (it) from list"

#### Expected behavior
Public channel **"Buggy"** which was the one previously selected is displayed.

#### Observed behavior (that appears unintentional) 
Public channel **"town-square1x"** is displayed. I don't know what is the rule, in this case "town-square1x" is the more followed public channel. See the video attached

![wrongchanneldisplayedafterclose](https://user-images.githubusercontent.com/1481595/34653823-13d14eb6-f3f2-11e7-94d9-59d335215184.gif)

Reproduced on MacOS 10.13.2 with Chrome 63.0.3239.84 and Firefox 57.0.3.

**Comment by lindy65** [comment]
Hi @StephaneColson,

Thanks for your feedback,

It is expected behavior to be returned to Town Square when closing direct messages, or when leaving public and/or private channels.

**Comment by lindy65** [comment]
I'll close this issue off for now.
