### ISSUE TITLE
https://api.segment.io/v1/t Failed

### ISSUE THREAD

**Issue by luisfellipe7** [mattermost/mattermost-server#8066]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
https://api.segment.io/v1/t Failed to response data

#### Steps to reproduce
When first interacting with others posts it gave me this

#### Expected behavior
It does not affect the user in way apparently

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/4549904/34674472-2906d26c-f46d-11e7-9d03-1898666a0174.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by jasonblais** [comment]
@luisfellipe7 Do you have a link of the JavaScript console when the error occured (same developer tools window from your screenshot, but on the "Console" tab)?

**Comment by luisfellipe7** [comment]
Sure, it also happens when I first enter the site
![image](https://user-images.githubusercontent.com/4549904/34682397-f868fc3e-f485-11e7-86c2-30cbe3678ebb.png)

**Comment by hmhealey** [comment]
Hi @luisfellipe7,

Those errors are because your ad blocker is blocking some analytics that we have running to track things like feature usage. More information about the analytics, as well as how to disable them on your own server, is available [here](https://docs.mattermost.com/administration/telemetry.html#error-and-diagnostics-reporting-feature)

**Comment by luisfellipe7** [comment]
Yeah, disabled adblocker and it not gave me an error anymore :)
