### ISSUE TITLE
[Help Wanted] [ABC-31] Mattermost-Kubernetes: Add persistent volume claims to Elasticsearch

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8071]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/ABC-31)

**Comment by dlahn-test** [comment]
@esethna It looks like there is an open PR for this one at https://github.com/mattermost/mattermost-server/issues/7330

**Comment by dlahn** [comment]
@esethna It looks like there is an open PR for this one at https://github.com/mattermost/mattermost-server/issues/7330

**Comment by esethna** [comment]
Looks like this is a dupe, thanks!
