### ISSUE TITLE
Mac Desktop App is not updating display after successfully changing the account email address

### ISSUE THREAD

**Issue by destayag** [mattermost/mattermost-server#8076]
#### Summary
Mac Desktop App is not updating display after successfully changing the account email address and user has verified the email.

#### Steps to reproduce
Version: 4.6.0  (4.6.0-rc1)
Device: Macbook

1. Log in to your account
2. Go to main hamburger icon > Account Settings > Email
3. Click Edit link
4. Change the email by providing a valid New Email and Confirm Email
5. Click Save
6. The app will display on the email section: ""New Address: <email>. Check your email to verify the above address". and on the top of the app, the message: ""Check your email at <email> to verify the address." is displayed.
7. Open the email received on the new email
8. Click Verify Email
9. Mostly the link will open on the browser like Chrome and the account will verify
10. Go back to the Mac Desktop app

#### Expected behavior
After the user has verified the new email, the Mac Desktop app should update based on the new email change and remove the message displayed on Email section on top of the App. As a user, I might be confused that the email is not updated realtime.

#### Observed behavior (that appears unintentional) 
On the Mac Desktop app, the display on the Email section and the top of the app is still displayed and didn't update after the user verified the new email. See images(attached).

Chrome Browser after verifying email change.
<img width="1680" alt="browser-1" src="https://user-images.githubusercontent.com/1924734/34731253-cbec105c-f59c-11e7-8a1f-8b1ba7bd8c92.png">

Mac Desktop App after verifying the email on Chrome
![ios-app-1](https://user-images.githubusercontent.com/1924734/34731254-cc21492a-f59c-11e7-9a51-6dca6f2624b1.png)

#### Possible fixes
The solutions I can think of are:
1. After clicking the Verify Email button from email, maybe we can open or confirm via Mac Desktop app? not sure if this possible but it has been done on mobile apps, also it will be easier since the customer has already been using the mac desktop app.
2. Update the Mac Desktop App realtime after verifying the email.

**Comment by lfbrock** [comment]
Hi @destayag - can you clarify if you mean the iOS mobile app, or the Mac desktop app? (It looks like the screenshots are of desktop app only, but not sure if the wrong one was attached).

**Comment by destayag** [comment]
@lfbrock my bad. I have updated the issue details and correct the mistake(from IOS app to Mac Desktop App).

**Comment by lindalumitchell** [comment]
Thanks Des! I filed a ticket with your report and ideas here: https://mattermost.atlassian.net/browse/PLT-8600

I'll close this issue and we can track the issue in the JIRA ticket.
