### ISSUE TITLE
"Commands have been disabled by the system admin" text appears if command has extra characters

### ISSUE THREAD

**Issue by gstormont** [mattermost/mattermost-server#8083]
OS: Windows 10 
Browser: Google Chrome (ver 63.0.3239.84)

#### Summary
If a command has an extra character at the end (ex. "/away," or "/away;") red text "Commands have been disabled by the system admin." appears below the text entry field. If the user deletes the extra character they have to tap enter twice to actually submit the corrected command. 

#### Steps to reproduce
1. In a conversation type: /away;
2. Hit enter twice on your keyboard
---->Observe: Red text appears 
3. Delete the extra character 
4. Hit enter twice again
---->Observe: It submits, despite the user just being told commands are locked

#### Expected behavior
If I have an extra character that doesn't belong in my command I should receive messaging that indicates I need to check my command and try again. Once I fix the error I should just be able to submit it right away. 

#### Observed behavior (that appears unintentional) 
Red text stating that commands have been locked by a system admin appears. The user also has to press enter twice to try resubmitting after correcting the error in the command. 

<img width="735" alt="mattermostbug" src="https://user-images.githubusercontent.com/35281948/34753523-c484f59e-f575-11e7-90a0-28a639cb6bbf.PNG">

**Comment by lindy65** [comment]
Hi @gstormont,

Thanks for your feedback,

Could you share which version of Mattermost server you're running?

I tested on Win 10, Chrome on our nightly build server running v4.6 RC2 and could not reproduce your issue.

If I type in an incorrect slash command, I get the correct error message below:

![image](https://user-images.githubusercontent.com/13020833/34763185-e764adac-f5f2-11e7-95e7-1235357c416f.png)

Looking at your error, are slash commands perhaps disabled by your system admin?

**Comment by lindy65** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid.  If you still experience the same problem, try upgrading to the latest version.  If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
