### ISSUE TITLE
Search and then click on a User in "Open Discussion Forum Members" modal does not select the User

### ISSUE THREAD

**Issue by swain-ritu** [mattermost/mattermost-server#8085]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by swain-ritu** [comment]
Summary- Search and Click on a User in "Open Discussion Forum Members" modal does not select the User
Steps-
1> Login to your account >  go to https://oss.mattermost.com/joomla/channels/town-square
2> click on Member popover > select to View Members
// opens modal titled "Open Discussion Forum Members modal"
3> click on any member on the list

Expected- Member gets selected and  next it should open a direct chat window with the selected member
Actual- Member is not selected and thus search a member from list and then initiate a chat functionality is broken

**Comment by lindy65** [comment]
Hi @swain-ritu,

Thanks for your feedback,

Please include a screenshot of which modal you're trying to open a direct message with a user from?

You should be able to click on the "message icon" from within the "members popover"

![image](https://user-images.githubusercontent.com/13020833/34818816-9c9ebbdc-f6c4-11e7-8c19-3cd62a1da830.png)

The "message icon" becomes visible only when hovering over the username.

![image](https://user-images.githubusercontent.com/13020833/34818850-bf1d97f0-f6c4-11e7-9fb8-b949f42fa4a7.png)

**Comment by lindy65** [comment]
Hi @swain-ritu,

Thank you for clarifying,

Before you click on "View members", hover over a name and you will see the "message bubble" - Click on that to direct message the person

![image](https://user-images.githubusercontent.com/13020833/34888149-bac39a2a-f7d1-11e7-9c4c-0b8fe1bcfe89.png)

I do see your point though that having to scroll through lots of users to find the one you're looking for is not ideal.

Why not try the shortcut key CTRL/CMD+K (channel switcher) and type the name of the person you're looking for and hit enter.  That will take you to a direct message with that person.

**Comment by lindy65** [comment]
Alternatively, you could open a feature request on our [forum](https://mattermost.uservoice.com/forums/306457-general) where you and others can up-vote the suggestion up to 10 times.
