### ISSUE TITLE
Profile picture uploader accepts images with a size less than 128px x 128 px not according as the instruction

### ISSUE THREAD

**Issue by cluisquijada** [mattermost/mattermost-server#8090]
#### Summary
Profile picture uploader accepts images with a size less than 128px x 128px not according to the instructions

#### Steps to reproduce
1. Go to **Account Settings**
2. In the **General** tab, click on **Edit** link on **Profile Picture**
3. When the **File Explorer** opens, select an image with a size less than 128 x 128.
4. Click on **Save**

#### Expected behavior
Application should enforce image size as instructed: _Upload a profile picture in BMP, JPG, JPEG or PNG format, at least 128px in width and 128px height._

#### Observed behavior (that appears unintentional) 
Application uploaded the uncompliant image.

#### Possible fixes
Set a validation to enforce the image size compliance for profile picture.

**Comment by lindy65** [comment]
Hi @cluisquijada,

Thank you for your feedback,

We've reproduced your issue and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8551) to track.

**Comment by lindy65** [comment]
I'll close this issue off here and we can track via the Jira ticket linked above.
