### ISSUE TITLE
Show TIF image thumbnail previews

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8092]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8516)

Currently .tif images are shown as generic attachment thumbnails. This ticket is to show the image preview in the thumbnail similar to other images (eg JPG).

Current TIF image thumbnail:
![image](https://user-images.githubusercontent.com/13119842/34856614-02900e42-f714-11e7-8b34-937c61db9e0f.png)

Current JPG thumbnail:
![image](https://user-images.githubusercontent.com/13119842/34856615-076a16c4-f714-11e7-9212-aae0f1300aba.png)

**Comment by pruthvip** [comment]
@jasonblais vl give it a try!!

**Comment by jasonblais** [comment]
Great, thank you @pruthvip!

**Comment by pruthvip** [comment]
@jasonblais I tried it. But there is a server side error coming 

`Unable to decode image err=tiff: unsupported feature: compression value 7`
`[2018/02/03 15:14:17 IST] [DEBG] GET - /api/v4/files/rjox7zfijpgm9r4tgg87b5zxbw/thumbnail
[2018/02/03 15:14:17 IST] [EROR] /api/v4/files/rjox7zfijpgm9r4tgg87b5zxbw/thumbnail:ReadFile code=404 rid=ex1utx9kffbmdnm6g14x6shbqa uid=aw9uf5whxpr97kuncmmd6kbyew ip=::1 Encountered an error reading from local server storage [details: open data/20180203/teams/noteam/channels/dzfuw1k7wtffbxam8mtsaxp5gc/users/aw9uf5whxpr97kuncmmd6kbyew/rjox7zfijpgm9r4tgg87b5zxbw/AMC_Pressbilder_BYAIH_thumb.jpg: no such file or directory]`

Looks like go is not able to generate thumbnails for tiff image. I dont have much knowledge of GO. Hence I needed some help with this

**Comment by ccbrown** [comment]
@pruthvip looks like Go doesn’t support that compression type yet (https://github.com/golang/go/issues/23115). I would try your code with other tiffs, and if it works for at least some of them, we can merge it and add support for that compression type in a follow-up PR (and maybe submit it to Go as well).

**Comment by hanzei** [comment]
Making this available for the public again as there hasn't been updates for some month.

**Comment by hanzei** [comment]
Hi @ejachang,

sorry for misleadingly removing the `go` label. It would be great, if you continue your work on this ticket!
Do you need help to set up your dev environment? Do you still have questions about this ticket?

**Comment by ejachang** [comment]
Hi Hanzei,

I'm good for now on my dev environment! I was experiencing problems with running make commands related to[ this](https://stackoverflow.com/questions/14219092/bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory), but it was solved. The other error was fixed with an update. 

I don't have any questions right now on this ticket, but will definitely let you know! Thank you so much!

**Comment by ejachang** [comment]
Hi @hanzei,
I'm having a little trouble decoding the tiff, but not sure if I am accessing the tiff data correctly? I understand the file data stream is `Input io.Reader`, but I get the following message when I try to decode using the tiff package from Input and find the decoded tiff image is nil.
`{"level":"error","ts":1546586445.681277,"caller":"app/file.go:735","msg":"Unable to decode image err=unexpected EOF"}`

 When I try to see the data from Input it seems to be pretty short. An example I see is: `{0xc001e3e810}` Is there something I might be missing?

**Comment by hanzei** [comment]
I'm not familiar with this part of the codebase. @hmhealey could you please help?

**Comment by hmhealey** [comment]
Hi @ejachang. How are you uploading the file? Is it just using the web app? It seems like either the data that you're using is bad or there's something preventing all of the data from being loaded

**Comment by ejachang** [comment]
Hi @hmhealey. Yes, I'm uploading just using the web app. I think I found the issue - I was using a tiff file with extension .tif, and that seems to have caused the problem. It worked fine when I used a file with the .tiff extension. Should I move forward with this for now?

**Comment by ejachang** [comment]
Hi @hanzei - I'm still working on the webapp part of the solution for this ticket, but was not sure if additional help is still needed since the Help Wanted label was added?

**Comment by jasonblais** [comment]
Hey @ejachang! We updated our Help Wanted issues by removing `[Help Wanted]` from the issue title and instead include it as a label. No new work/help is needed from what you're already working on.

Thanks for all your help on this issue! It's much appreciated :)

**Comment by ejachang** [comment]
Oh, got it @jasonblais ! Thanks for the clarification.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/2333 and https://github.com/mattermost/mattermost-server/pull/10170. Thank you very much @ejachang :tada:
