### ISSUE TITLE
Notification preference settings don't respect case sensitivity.

### ISSUE THREAD

**Issue by herooftimeandspace** [mattermost/mattermost-server#8093]
#### Summary
Notification preference settings don't respect case sensitivity.

#### Steps to reproduce
Platform / Webapp Version: 4.6.0  (4.6.0-rc3)

**NOTE: Username and First Name of the user match.**
Go to Account Settings → Notifications → Words that trigger mentions
Uncheck "Your non-case sensitive username "[username]""
Type your name with multiple case sensitive variants
The name highlights in all cases

#### Expected behavior
I expected that unchecking "Your non-case sensitive username "[username]"" would mention me on my case sensitive first name, but not any other variants.

#### Observed behavior (that appears unintentional) 
My first name is "Link", and my username is "link" in our local instance. As you can imagine, I get notified any time anyone uses the word "link" in any channel that I'm in. "Did you check out this link?" I want to prevent unnecessary notifications or mentions.
![screen shot 2018-01-11 at 1 14 43 pm](https://user-images.githubusercontent.com/32583822/34847833-7db9b1ba-f6d1-11e7-9ce9-882570affbfe.png)
![screen shot 2018-01-11 at 1 14 59 pm](https://user-images.githubusercontent.com/32583822/34847832-7d652758-f6d1-11e7-8aa7-24cb0962e8d1.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by jasonblais** [comment]
Thanks @herooftimeandspace for the report! 

We've created a ticket here: https://mattermost.atlassian.net/browse/PLT-8556

It appears to only affect the highlighting based on my testing. No mention notification is triggered if someone else posts a message containing "link" in your above example.

**Comment by lindy65** [comment]
Thanks @herooftimeandspace, I'll close the issue off here and we can track via the Jira ticket linked above.
