### ISSUE TITLE
Replica setting prevents Mattermost from starting

### ISSUE THREAD

**Issue by cjohannsen81** [mattermost/mattermost-server#8094]
I try to start a Mattermost cluster using an Enterprise license for testing. As soon as I add a replica (postgres) the service isn't longer supporting HA.

I started the cluster with replicas it failed, when started without the replicas setting the cluster comes up perfectly.

Here is what the failure in the logs describe:

`[2018/01/11 21:13:46 UTC] [INFO] License key has not been uploaded.  Loading license key from disk at /tmp/christians_demo__trial-82190.mattermost-license
[2018/01/11 21:13:46 UTC] [INFO] Failed to save license key loaded from disk err=addLicense: api.license.add_license.invalid_count.app_error, SqlUserStore.AnalyticsUniqueUserCount: store.sql_user.analytics_unique_user_count.app_error, pq: relation "users" does not exist
[2018/01/11 21:13:46 UTC] [INFO] License key from https://mattermost.com required to unlock enterprise features.
[2018/01/11 21:13:46 UTC] [INFO] Starting up plugins
`

The PostgreSQL server were setup like the setup describes it. Here are my settings:

"SqlSettings": {
        "DriverName": "postgres",
        "DataSource": "postgres://mmuser:mmuser_password@172.31.16.250:5432/mattermost?sslmode=disable\u0026connect_timeout=10",
        "DataSourceReplicas": ["postgres://mmuser:mmuser_password@172.31.26.117:5432/mattermost?sslmode=disable\u0026connect_timeout=10"],
        "DataSourceSearchReplicas": [],
        "MaxIdleConns": 20,
        "MaxOpenConns": 300,
        "Trace": false,
        "AtRestEncryptKey": "gt8gbortdr71io91yna1ydndobg1axf7",
        "QueryTimeout": 30

I checked that my replica does not have the relations when checking with psql. The "mattermost" database is created and user access is given. At what point will the relations be created on the replicas?

I validated that even without enabling HA as soon as a replica connection is added the server doesn't start anymore and the database on the replica server has no tables.

**Comment by jwilander** [comment]
Hi @cjohannsen81,

It looks like your trial license is failing to load because of this PostgreSQL error: `pq: relation "users" does not exist`. On server start-up when the license is loaded, the DB will be queried to check the license user count vs the actual user count on the server. This check is failing because it looks like your replica doesn't have the `users` table.

I'd check to make sure that the replica is set up correctly and that the data has been replicated from your master DB to the replica

**Comment by cjohannsen81** [comment]
@jwilander Since the replica server is 100% like the master server I was wondering at what point the tables are setup on the replicas?

**Comment by jwilander** [comment]
Mattermost itself does not do the replication, you'll need another service to handle that for you. Most people use something like AWS's RDS that has built-in support for replication. You can read more about postgres replication [here](https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling)

**Comment by cjohannsen81** [comment]
Thanks for clarifying @jwilander! I wasn't aware of the need to manage the replication myself since there was no mention in the documentation at all :) Thanks for your help!
