### ISSUE TITLE
Channel "Notifications Preferences" are applied to all channels in team.

### ISSUE THREAD

**Issue by Kelloggs** [mattermost/mattermost-server#8101]
#### Summary
Channel specific settings for notifications are applied to all channels.

#### Steps to reproduce
- Select one channel (e.g. Town Square)
- Click channel name and select "Notification Preferences"
- Change settings (e.g. set "Send desktop notifications" to "Never")

#### Expected behavior
I expect, that the setting is only applied to the selected channel and that the Notifications Preferences of other channels aren't modified.

#### Observed behavior (that appears unintentional) 
The setting is applied to all channels in the Team.

**Comment by jasonblais** [comment]
Thanks @Kelloggs! This is fixed in v4.6.0, which ships on January 16th.

**Comment by Kelloggs** [comment]
@jasonblais Great - thanks. I did see, that there were fixes regarding notification preferences but couldn‘t determine whether they are related.

**Comment by jasonblais** [comment]
@Kelloggs Certainly! Thanks for confirming 👍 

I'll close this issue then
