### ISSUE TITLE
Sending lots of > characters breaks a DM

### ISSUE THREAD

**Issue by AdityaGupta1** [mattermost/mattermost-server#8103]
#### Summary
Sending a message with a lot of `>` characters breaks a DM and permanently stops it from loading, but messages sent will still produce notifications.

#### Steps to reproduce
Version 4.1.0

Send a message with a lot of `>` characters in a DM (or maybe even a channel, haven't tried this yet) and see how it breaks.

The DM I tried this in is broken on the webapp, desktop app, and phone app. However, when the other person on the DM sends a message, I still receive an email notification.

#### Expected behavior
The message should just send as a lot of quotation symbols, or not send at all.

#### Observed behavior (that appears unintentional) 
Messages similar to the following kept spamming the console:
```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at 2.cd5eba4d01d6106f2535.js:1:716421
    at 2.cd5eba4d01d6106f2535.js:1:717073
    at 2.cd5eba4d01d6106f2535.js:1:612459
    at n (2.cd5eba4d01d6106f2535.js:1:712855)
    at 2.cd5eba4d01d6106f2535.js:1:712877
    at r.(anonymous function) (2.cd5eba4d01d6106f2535.js:1:716552)
    at e.exports (2.cd5eba4d01d6106f2535.js:1:717602)
    at 2.cd5eba4d01d6106f2535.js:1:717496
    at 2.cd5eba4d01d6106f2535.js:1:611088
    at t (2.cd5eba4d01d6106f2535.js:1:175788)
Promise rejected (async)
g @ channel_actions.jsx:249
l @ websocket_actions.jsx:92
(anonymous) @ websocket_actions.jsx:72
conn.onopen @ websocket_client.jsx:51
```

I removed the URL of the chat, but other than that, the stacktrace is exactly what I saw in the Chrome developer console.

The DM always looks like the following, and never loads:
![loading](https://user-images.githubusercontent.com/3106877/34912800-a8710678-f89e-11e7-9d91-944f9373cf7b.png)

#### Possible fixes
Not sure how to fix this.

**Comment by AdityaGupta1** [comment]
Update: For some reason it decided to start working today. I am not sure what caused the change.

**Comment by lindy65** [comment]
Hi @AdityaGupta1,

Thanks for your feedback,

I'm pleased your issue is resolved.

We suggest also upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost.
