### ISSUE TITLE
Error Mattermost Developer

### ISSUE THREAD

**Issue by diogorocha18** [mattermost/mattermost-server#8104]
Good evening,

Without messing with anything I'm having a bug in the developer summer of Mattermost
https://image.prntscr.com/image/jyBM48l4T7WBg7CDsynDtw.png
https://image.prntscr.com/image/FZRAFEIuQEm2qtsH7wLu8g.png

In addition, when a user edits his profile, the server will automatically shut down automatically, so that it is turned on again.

Is it bug?

greetings

**Comment by lindy65** [comment]
Hi @diogorocha18,

Thanks for your feedback,

I'm guessing your issue has something to do with [APIv3 being deprecated](https://docs.mattermost.com/administration/changelog.html?highlight=changelog#removed-and-deprecated-features) and replaced by APIv4.

Here is information on [APIv4](https://api.mattermost.com/) commands.

**Comment by diogorocha18** [comment]
Hi @lindy65

Okay, but I installed this developer version last night, which should have been updated, right?

**Comment by lindy65** [comment]
Did you install from [this link](https://about.mattermost.com/download/) @diogorocha18 ?

**Comment by diogorocha18** [comment]
@lindy65 A ticker was created to solve the problem that I am not the only one:
https://mattermost.atlassian.net/browse/ICU-632

**Comment by lindy65** [comment]
Hi @diogorocha18,

Ah, now I'm understanding your issue!  Apologies for the misunderstanding...

We'll track your issue via the Jira ticket linked above :)
