### ISSUE TITLE
When mySQL server goes down, Mattermost does not give insightful error messages

### ISSUE THREAD

**Issue by bwesterb** [mattermost/mattermost-server#8115]
#### Summary
If the mySQL server goes down, Mattermost will fail to login users with the error message "We couldn't find an account matching your login credentials".

#### Steps to reproduce
Shut down mySQL server of running Mattermost instance.  Visit Mattermost, try to login.

#### Expected behavior
Mattermost should say the database is down (and perhaps, request the user to contact the admin).

**Comment by lindy65** [comment]
Hi @bwesterb,

Thanks for the report :)

I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8594) to track the issue.

**Comment by lindy65** [comment]
I'll close this off here for now and we can track via the ticket linked above.
