### ISSUE TITLE
Per channel notifications not working

### ISSUE THREAD

**Issue by silverasu** [mattermost/mattermost-server#8116]
#### Summary
Per channel notifications not working

#### Steps to reproduce
Change in one channel -> Notification preferences-> Send desktop notifications -> Never.
Check other channel...
Desktop notification is also Never.

#### Observed behavior (that appears unintentional) 
Per channel notifications are changing globally.

#### Possible fixes
Per channel notifications should be changed per channel. (Worked in 4.2)

**Comment by lindy65** [comment]
Hi @silverasu,

Can you share which version of Mattermost server you have installed?

I am not able to reproduce your issue in the [latest version](https://about.mattermost.com/download/) on our nightly build server.

**Comment by silverasu** [comment]
Latest version 4.5

**Comment by lindy65** [comment]
Pleased your issue is resolved @silverasu :)  I'll close off this issue then...
