### ISSUE TITLE
"Direct channels" title is too long in French

### ISSUE THREAD

**Issue by Rudloff** [mattermost/mattermost-server#8117]
#### Summary
When using Mattermost 4.6.0 in French, the "Direct channels" is too long and because of that the Add button is not placed correctly.

#### Steps to reproduce
1. Install Mattermost 4.6.0.
1. Switch to French.

#### Expected behavior
The title and the button are on the same line.

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/840125/35047823-6f3d2b84-fb9b-11e7-94c0-ce76dde1a36f.png)

#### Possible fixes
Reducing the padding around the button by 1 or 2 px makes it fit:
![image](https://user-images.githubusercontent.com/840125/35047888-acb9dc00-fb9b-11e7-8001-2429402085d8.png)

**Comment by lindy65** [comment]
Hi @Rudloff,

Thank you for the report!

I've created [this ticket](https://mattermost.atlassian.net/browse/UX-91) to track the fix.

**Comment by lindy65** [comment]
I'll close this off here for now and we can track via the ticket linked above.
