### ISSUE TITLE
Creating new account: Easily able to defeat username rules and create invalid username

### ISSUE THREAD

**Issue by sescott285** [mattermost/mattermost-server#8118]
#### Steps to reproduce
1. open the login page in Chrome: https://oss.mattermost.com/login
2. Open Chrome's Developer tools
3. Click on the Create New Account link
4. In the Developer tools, change maxlength="-1" in the following line:
<input type="text" id="name" class="form-control" placeholder="" maxlength="22" spellcheck="false" autocapitalize="off">
5. create a new user with a valid email address, but an invalid username

#### Expected behavior
The user should receive an error message for an invalid username

#### Observed behavior (that appears unintentional) 
I saw a user with username SES login successfully and appear in the lobby. See attached image mattermost-4.
Please include relevant error messages and/or screenshots.
<img width="1292" alt="mattermost-2" src="https://user-images.githubusercontent.com/35537185/35056765-c613a73c-fb80-11e7-8a68-3c3a29abaa43.png">
<img width="290" alt="mattermost-4" src="https://user-images.githubusercontent.com/35537185/35056792-db744f32-fb80-11e7-990f-87f6a9eeeedc.png">

#### Possible fixes
Move your username validation out of the browser code.

**Comment by lindy65** [comment]
Hi @sescott285,

Thanks for the report,

I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8602) to track the issue.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above.
