### ISSUE TITLE
Code tagged code might freeze webapp

### ISSUE THREAD

**Issue by loofou** [mattermost/mattermost-server#8120]
#### Summary
One user has found a weird issue that sending certain snippets of code inside a code tag might result in a full freeze of the webapp content. The app itself is still fine, you can reload with the menu bar, but the content is completely frozen and unresponsive.

I have to say that his machine was the only one where we could reproduce the issue. The machine is running windows and we can reproduce it in the app and in chrome. Clearing the cache does not help preventing the freeze.

#### Steps to reproduce
1. copy & paste the following code:

> case Status::Abandoned:
>         ServerUnregisterCounters();
>         // start delay between guidance tasks
>         if (Type == Type::GuidanceTask)
>         {
>             Manager->ServerFinishedGuidanceTask();
>         }
>         else if (Type == Type::Ultimatum)
>         {
>     }

2. add code tags around it
3. try to send it to a channel

#### Expected behavior
The code snippet should send normally.

#### Observed behavior (that appears unintentional) 
The whole web app content freezes and is completely unresponsive.

#### Possible fixes
I assume it might have something to do with the snippet itself, as other code snippets work fine.

**Comment by lindy65** [comment]
Hi @loofou,

Thanks for the report,

I tried to reproduce your issue on our nightly build server but could not - nothing in the JavaScript console either.

If I remember correctly from another issue report, you're running Mattermost v4.6 server?

Does this user have any add-ons running in his browser or have any errors in the JavaScript console?

**Comment by loofou** [comment]
Hi @lindy65 ,

I could now reproduce it on my machine. No JavaScript errors though. Also no weird browser plugins (the standalone app wouldn't be affected by them anyway, right?)

The funny thing is: I think Markdown on github changes something about my snippet above, which makes it not trigger the issue. I tested it again with copy & pasting the snippet from the first post, but everything worked fine. So I have a text file attached to reproduce the error. Please download it and do exactly the following steps:

1. Hit the ` key to place the start of the code tag.
2. Copy & Paste the full content of the attached txt file from notepad to mattermost.
3. Hit the ` key again to place the end of the code tag.
3. Hit Enter.

The app should now freeze.

[test_freeze.txt](https://github.com/mattermost/mattermost-server/files/1651651/test_freeze.txt)

**Comment by lindy65** [comment]
Hi @loofou,

We had a similar report on the [forum](https://forum.mattermost.org/t/mattermost-crashes-when-posting-a-code-snippet-containing-white-space/4403) today which I did reproduce on our nightly build server and have created a [ticket](https://mattermost.atlassian.net/browse/PLT-8610) to investigate/track.

**Comment by lindy65** [comment]
I'll close this off here for now and we can track via the ticket linked above.
