### ISSUE TITLE
Missing validation when an invalid credentials is used

### ISSUE THREAD

**Issue by jeffdjet** [mattermost/mattermost-server#8122]
#### Summary
Missing validation when an invalid credentials is used

#### Steps to reproduce
1. Go to login page https://oss.mattermost.com/login
2. Enter a@a.com as email
3. Enter any password ie: pass123
4. Hit submit button

#### Expected behavior
The system should not redirect to a page stating sending verification email. It should validate the email and password if already exists or not.

#### Observed behavior (that appears unintentional) 
The page will be redirected showing an email was sent for email verification.
![1](https://user-images.githubusercontent.com/28149183/35130284-0f6957ee-fcfb-11e7-877d-c9fe2a04d030.gif)

**Comment by lindy65** [comment]
Thanks for the report @jeffdjet!

I've reproduced your issue on our nightly build server and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8607) to track.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
