### ISSUE TITLE
Edit indicator unintentionally moved to a new line (regression)

### ISSUE THREAD

**Issue by pocek** [mattermost/mattermost-server#8123]
#### Summary
This commit:
https://github.com/mattermost/mattermost-webapp/commit/97cb44a06ec49e86800bbec8e5a13ebe84c75f26

introduced in v4.6.0 breaks the CSS rules responsible for placing `(edited)` indicator inline with the last paragraph of a message. The exact reason is that there's an extra (spurious?) span element, so the rules:

https://github.com/mattermost/mattermost-webapp/blob/v4.6.0/sass/layout/_post.scss#L970

no longer work.

#### Steps to reproduce
Use v4.6.0, edit a message.

#### Expected behavior
The `(edited)` indicator is inline with the last paragraph.

#### Observed behavior (that appears unintentional) 
The `(edited)` indicator is not inline.

#### Possible fixes
Remove the extra span or fix the CSS.

**Comment by jasonblais** [comment]
@pocek 

1) Can you share an example message, or a screenshot, that reproduces this error?
2) Which OS and browser are you using?

I tried but it was working okay for me.

**Comment by lindy65** [comment]
Hi @pocek,

I've reproduced your issue on our nightly build server and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8604) to track.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
