### ISSUE TITLE
Character count enforced for previous message when moving to a new channel  

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-server#8124]
#### Summary
When moving from one channel to another, the character count of your message is stale as it is showing the character count from previous message. This prevents sending attachment with no text.

#### Steps to reproduce
1. Open a channel and type a message with more than 4000 Characters but do not post the message (observe error text below message input box)
2. Navigate to a new channel
3. Try to send an attachment without any text (drop attachment and push enter)

#### Expected behavior
Attachment is sent

#### Observed behavior (that appears unintentional) 
user is informed their message with no text is too long

#### Possible fixes
Refresh character count when I open a new channel to prevent incorrect length enforcement.
![charactercountoutdated](https://user-images.githubusercontent.com/35588783/35135414-2ad4adee-fcab-11e7-81f5-7ece7941c99e.PNG)
 enforcement.

**Comment by lindy65** [comment]
Thanks for the report @DHaussermann !

I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8603) to track.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above.
