### ISSUE TITLE
Internal server error when on channel search with char %

### ISSUE THREAD

**Issue by williamsmjunior** [mattermost/mattermost-server#8126]
#### Summary
Internal server error when on channel search with char %

#### Steps to reproduce
- Perform login
- Select some channel
- Press ⌘K
- insert %%% on search field

#### Expected behavior
- Normal search and nothing found

#### Observed behavior (that appears unintentional) 
- A message appear: "We encountered an error searching channels"
- The chrome console displays an internal server error (500)
Response:
{"id":"store.sql_channel.search.app_error","message":"We encountered an error searching channels","detailed_error":"","request_id":"wdqqyypj3pyiir3abnuhujypow","status_code":500}

**Comment by lindy65** [comment]
Thanks for the report @williamsmjunior!

I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8609) to track.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above.
