### ISSUE TITLE
Mattermost-push-proxy - Configured service not working

### ISSUE THREAD

**Issue by ronaldjhp** [mattermost/mattermost-server#8128]
Hello there, I followed the setup instructions for

mattermost-push-proxy from https://github.com/mattermost/mattermost-push-proxy

But am unable to connect to 127.0.0.1 over 8066

When I check out the logs I see

/bin/sh: 1: exec: bin/mattermost-push-proxy: not found

Which makes sense because mattermost-push-proxy isn’t in bin!

Did I miss something obvious in the instructions? There was no mention of making / building the application. Does that need to be done? If so are there instructions on that? I tried but kept hitting errors.

Thank you for the help!

**Comment by lindy65** [comment]
Hi @ronaldjhp,

Thanks for your feedback,

Yes, you do need to compile the mobile app to host your push notification server.  Perhaps these docs will help?
- https://docs.mattermost.com/mobile/mobile-compile-yourself.html
- https://docs.mattermost.com/mobile/mobile-faq.html#mobile-apps-faq

**Comment by lindy65** [comment]
Hi @ronaldjhp 

We haven't received an update so we'll assume that the problem is fixed or is no longer valid.  If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
