### ISSUE TITLE
Validation error message not cleared when switching between creating private / public channel

### ISSUE THREAD

**Issue by jeffdjet** [mattermost/mattermost-server#8129]
#### Summary
Validation error message upon creating channel should auto-clear when switching to private to public or vice versa

#### Steps to reproduce
- Create already exists private channel
- An inline validation error message appear
- Click Create a Public channel link

#### Expected behavior
The inline should automatically disappear when switching to another page

#### Observed behavior (that appears unintentional)
Inline error message is also appearing to another page when switching to private to public create channel or vice versa

![error message auto-clear](https://user-images.githubusercontent.com/28149183/35178430-c5721c4e-fd80-11e7-98f0-14807e716ce1.png)

**Comment by lindy65** [comment]
Thanks for the report @jeffdjet,

I think this is happening because the channel name remains in the web UI.  That said, it still needs to be fixed and I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8608) to track.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above.
