### ISSUE TITLE
Send message button is Private Message not necessary

### ISSUE THREAD

**Issue by jeffdjet** [mattermost/mattermost-server#8130]
#### Summary
The Send message button in a private message should no longer needed

#### Steps to reproduce
- Select a person for a Private Message under Direct Message
- Click the logo of the user in the Private Message room then click the Send Message button

#### Expected behavior
The Send message button in a private message should no longer needed. If this is intended then upon click it should place the cursor in the input box

#### Observed behavior (that appears unintentional) 
The user is already in the Private Message, upon clicking the Send Message nothing happens
![directmessage-inputbox](https://user-images.githubusercontent.com/28149183/35178596-33af9aae-fd83-11e7-832f-610f0e56c623.png)

**Comment by lindy65** [comment]
Thanks for the feedback @jeffdjet,

You make a good point!  I'll pass your feedback to one of the product managers for comment.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above.
