### ISSUE TITLE
Remove Hand mousepointer if no click action

### ISSUE THREAD

**Issue by jeffdjet** [mattermost/mattermost-server#8131]
#### Summary
Remove Hand mousepointer if no click action

#### Steps to reproduce
- In a private or public message
- type any text in the input box
- available text format is displaying upon typing
- mouseover on those options and then click

#### Expected behavior
If no action click is implemented then better to remove the hand mousepointer upon hover.

#### Observed behavior (that appears unintentional) 
Upon clicking the available text format nothing happens. 
![mousehover handpointer](https://user-images.githubusercontent.com/28149183/35178718-bb45daa4-fd84-11e7-9d7b-5e618856ed75.png)

**Comment by lindy65** [comment]
Hi @jeffdjet,

Thanks for the report!  We have [this ticket](https://mattermost.atlassian.net/browse/PLT-8506) to fix the issue.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above.
