### ISSUE TITLE
Deactivated users still appear in direct messages popup

### ISSUE THREAD

**Issue by shochdoerfer** [mattermost/mattermost-server#8132]
After marking a user as inactive, the user still appears in the "search and add members popup" for direct messages. Is it possible to hide/remove the users in this popup?

**Comment by jasonblais** [comment]
@shochdoerfer They appear in the modal so a user can open their old 1-1 direct message conversation with that user, and to preserve unlimited search history.

What is the use case for you to hide/remove them from the popup?

**Comment by shochdoerfer** [comment]
I see, that makes sense of course. We had to remove quite a few accounts and in other applications we use I could easily delete those accounts completely but not in Mattermost. I was looking for consistency ;)

**Comment by lindy65** [comment]
Thanks @shochdoerfer - I'll close this issue off here for now as this isn't a bug but rather a feature of the software for history purposes.
