### ISSUE TITLE
Arabic language issue

### ISSUE THREAD

**Issue by marinaco** [mattermost/mattermost-server#8133]
![mattermost-arabic](https://user-images.githubusercontent.com/35668544/35198843-b33cc1a8-fec2-11e7-9d63-301230b0f3b7.png)
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Arabic language support

#### Steps to reproduce
Open Discussing Forum - After adding Arabic language and switch to it to write, shows mattermost.com is not responding. Recover the page. Please view the attached screenshot.

#### Expected behavior
Typing using Arabic without any error

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by marinaco** [comment]
happened just once after adding the Arabic (Egypt) language for the first time

**Comment by marinaco** [comment]
![mattermost-arabic](https://user-images.githubusercontent.com/35668544/35199113-4b0ac328-fec7-11e7-8080-ac97bce46bc2.png)

**Comment by lindy65** [comment]
Hi @marinaco,

We have [this ticket](https://mattermost.atlassian.net/browse/ICU-632) which has a PR submitted so it should be fixed soon.  

Can you check your JavaScript console to see if there are any errors displayed and, if so, include a screenshot please?

**Comment by lindy65** [comment]
I'll close this issue off here and we can track via the ticket linked above.
