### ISSUE TITLE
Reaction popover text overflow for the emoji code

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-server#8134]
#### Summary
The text of the popover that appears when a user clicks on a reaction emoji can overflow is the emoji code is too long.

#### Steps to reproduce
Using the  4.6 web application on Firefox 57.0.4, add a 'stuck_out_tongue_winking_eye' emoji to an existing message. Then hover the mouse over the reaction emoji that was added. 

#### Expected behavior
A black popover appears, which displays who added this reaction and what is the code of the emoji. There should be no text overflow.

#### Observed behavior (that appears unintentional) 
The text overflows over the right border of the popover, see screenshot.
![image](https://user-images.githubusercontent.com/8834237/35217251-c91d7820-ff6a-11e7-92df-671e2891609b.png)

**Comment by lindy65** [comment]
Hi @moussetc,

Thanks for your feedback,

I've tested on our nightly build server with Firefox 57.0.4 and have reproduced your issue so have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8620) to track.

Strangely, the bug does not occur on Chrome!

**Comment by lindy65** [comment]
I'll close this issue off here and we can track via the ticket linked above.
