### ISSUE TITLE
[Help Wanted] [ICU-663] Add account creation redirect to channels

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8156]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/ICU-663)

**Comment by santos22** [comment]
HI @esethna - is this the same as https://github.com/mattermost/mattermost-server/issues/7879?

**Comment by esethna** [comment]
Thanks, closed the old dupe

**Comment by jasonblais** [comment]
Closing for now as an engineer brought up a few technical point that need to be evaluated. https://mattermost.atlassian.net/browse/ICU-663
