### ISSUE TITLE
[Help Wanted] [ABC-65] Kubernetes: Clean up of the Mattermost helm charts

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8177]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/ABC-65)

Clean up of the Mattermost helm charts in our Kubernetes repo.
 - Charts that don't need to be inline should be downloaded using helm dependency management.
 - Other helm best practices should be researched and implemented.

**Comment by Brunzer** [comment]
I'll take this

**Comment by jasonblais** [comment]
Closing as we split this into smaller tickets, which we might open to community contributions.

I know you've been busy but if you had anything already in progress, feel free to submit what you have to mattermost-kubernetes repo.
