### ISSUE TITLE
I am new to mattermost and trying to customize mattermost code for our requirements        .But getting this error in sctransport.js?500d:10 WebSocket connection to 'ws://localhost:5678/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED  . Do i need to give websocket urls somewhere or how to remove this error

### ISSUE THREAD

**Issue by sourabhlk** [mattermost/mattermost-server#8179]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lindy65** [comment]
Hi @sourabhlk,

Thanks for your feedback,

Here is some documentation that may be of assistance:
- https://docs.mattermost.com/deployment/customize-mattermost.html#customizing-mattermost
- https://docs.mattermost.com/overview/faq.html#how-can-i-create-an-open-source-derivative-work-of-mattermost

Let me know if this helps?

**Comment by lindy65** [comment]
I'll close this issue off for now as we haven't had an update so we assume this is fixed or no longer an issue.
