### ISSUE TITLE
The automatic scroll down is really slow when switching channel since 4.6.0

### ISSUE THREAD

**Issue by TheWhite147** [mattermost/mattermost-server#8180]
#### Summary
In version 4.4.2, when we were switching channel, the conversation screen was already scrolled down so we can see the last messages immediately. Now, in 4.6.0, the conversation screen is not scrolled to the bottom immediately: we have to wait 4-5 seconds before the screen scrolls down to the last message in the channel.

#### Steps to reproduce
Simply switch channels multiples time and wait for the conversation screen to scroll down to the last message. The bug occurs with every channel, but is worse with biggest channel (e.g.: Town Square).

#### Expected behavior
Normally, when switching channel, it would be normal to see the last mesasge immediately, not to wait before it scrolls down to it.

#### Possible fixes
This bug was not in version 4.4.2 of Mattermost Server.

**Comment by lindy65** [comment]
Hi @TheWhite147.

Thanks for your feedback,

We recently fixed this issue which should ship with v4.7 on February 16th.

We also have [this ticket](https://mattermost.atlassian.net/browse/PLT-7973) to investigate scroll pop in channels.

**Comment by lindy65** [comment]
I'll close this off for now and we can reopen if the issue still reproduces after v4.7 is released on Feb 16th.
