### ISSUE TITLE
Can't connect from Android phones

### ISSUE THREAD

**Issue by mr-rick-g** [mattermost/mattermost-server#8182]
I am self hosting Mattermost Enterprise edition (v 4.6) and cannot connect through the Mattermost app from Android phones. I receive this error "Cannot connect to the server. Please check your server URL and internet connection."

I can get to the site from the URL, from iPhones (app and url)....the site is up and running. The only issue I have is connecting through Android phones. 

I can connect to https://pre-release.mattermost.com through the app. 

I am not using nginx as a proxy but I plan to in the future. 

Any thoughts?

Thanks!

**Comment by lindy65** [comment]
Hi @mr-rick-g,

Thanks for your feedback,

Could you share an example of the URL you are using to connect via Android phone?

**Comment by mr-rick-g** [comment]
Sure, the URL is like this: https://mm.nameofcompany.com

*Rick Gould*
Network Administrator

*[image: cid:image001.jpg@01D1B279.8A1DA2C0]*
P.O. Box 1102 *(mailing address)*
10440 Little Patuxent Parkway, Suite 600 *(physical location)*
Columbia, MD 21044
(410) 715-0005 Office
(410) 715-0008 Fax
rgould@applieddefense.com
www.applieddefense.com
An EEO and eVerify Employer

**Comment by lindy65** [comment]
Thanks for the feedback @mr-rick-g 

I'll ask one of our engineers for their input...

**Comment by enahum** [comment]
Check your SSL certificate, the whole chain should be there, you can use ssllabs.com to verify it

**Comment by lindy65** [comment]
I'll close this issue off for now as we haven't had an update and assume this is no longer reproducing or an issue.

**Comment by chekoopa** [comment]
Same problem with an Android 7.0 phone. Nginx self-hosted, proper SSL wildcard cert, tried an advice with `ssl_ecdh_curve`. The recent app does connect to `pre-release.mattermost.com`, but writes "Can't connect...". Though the phone connects to the server through browsers. Another phone (Android 9) also works both through a browser and the app. The server version is 5.9.0, yet.
