### ISSUE TITLE
page preview renders � for non-ascii chars for charset="windows-1250"

### ISSUE THREAD

**Issue by hydrapolic** [mattermost/mattermost-server#8186]
#### Summary
Some link previews are displayed incorrectly when using charset="windows-1250". Non ascii chars are replaced with �.

#### Steps to reproduce
Mattermost version 4.6.1.

Enable link preview and just paste this to a channel:
http://www.dsl.sk/article.php?article=20733 or https://ekonomika.idnes.cz/taxi-praha-jancura-prodej-tick-tack-dug-/ekonomika.aspx?c=A180201_222515_ekonomika_dtt

#### Expected behavior
Link previewed with correct encoding

![mm-ok](https://user-images.githubusercontent.com/3277373/35727842-d36655c0-0809-11e8-8639-8e59477c6f88.png)

#### Observed behavior (that appears unintentional) 
Non ascii chars replaced with �.

![mm-fail](https://user-images.githubusercontent.com/3277373/35727854-dacebc94-0809-11e8-89d0-697a60533c0c.png)

**Comment by lindy65** [comment]
Hi @hydrapolic,

Thanks for your report!

I've reproduced the issue on our nightly build server running off the latest master and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8690) to track.

**Comment by hydrapolic** [comment]
Thank you very much @lindy65

**Comment by lindy65** [comment]
I'll close this issue off for now and we can reopen if the issue still reproduces once v4.7 is released on Feb 16th.

**Comment by hydrapolic** [comment]
@lindy65, same with 4.7.0.

**Comment by lindy65** [comment]
Ah, thanks for letting us know @hydrapolic,

I see from the [ticket](https://mattermost.atlassian.net/browse/MM-9072) that the fix was pushed to v4,8 which will release March 16th.

Let's check again after that release 👍
