### ISSUE TITLE
First user in the system cannot switch user login method from password to GitLab SSO

### ISSUE THREAD

**Issue by jk2K** [mattermost/mattermost-server#8202]
#### Summary
first user in the system cannot switch sign-in method from password to GitLab SSO

#### Steps to reproduce
- Mattermost version: 4.6.1
- MySQL version: 5.7.20
- CentOS version: 7.2

1. follow these [official instructions to install Mattermost](https://docs.mattermost.com/install/install-rhel-71.html)
2. Configure Mattermost to use GitLab as a single sign-on (SSO) service
3. `Account Settings > Security`  does not show the button that switchs the login method
4. If I use GitLab SSO in Login page, I will get below error, other people through GitLab SSO able to log in successfully

![image](https://user-images.githubusercontent.com/4025839/35839629-693db37a-0b2c-11e8-8e43-337a41d719ff.png)

`There is already an email account that uses a method other than gitlab for logging in. Please use email to log in`

#### Expected behavior
the option to switch login methods should be there if GitLab SSO enabled

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/4025839/35839765-3ef481e2-0b2d-11e8-814e-493a96ccbdda.png)

No option to switch account to GitLab SSO

**Comment by lindy65** [comment]
Thanks for the report @jk2K,

I've filed a [ticket](https://mattermost.atlassian.net/browse/PLT-8696) to look into this...

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
