### ISSUE TITLE
Cannot send request from posted button using `github.com/mattermost/mattermost-server/model` library to my server.

### ISSUE THREAD

**Issue by ShotaKitazawa** [mattermost/mattermost-server#8205]
#### Summary

Cannot send request from posted button using `github.com/mattermost/mattermost-server/model` library to my server.

#### Steps to reproduce

Execute as follows.

```
package main

import "github.com/mattermost/mattermost-server/model"

const (
        mattermostURL = YOUR_MATTERMOST_URL
        myServerURL   = YOUR_SERVER_URL

        email    = YOUR_EMAIL_ADDRESS_TO_LOGIN_MATTERMOST
        password = YOUR_PASSWORD_TO_LOGIN_MATTERMOST

        channelID = YOUR_MATTERMOST_CHANNEL_ID
)

func main() {
        client := model.NewAPIv4Client(mattermostURL)
        client.Login(email, password)

        props := make(model.StringInterface)
        props["attachments"] = setButton()

        post := &model.Post{
                ChannelId: channelID,
                Props:     props,
        }
        client.CreatePost(post)
}

func setButton() []*model.SlackAttachment {
        var result []*model.SlackAttachment

        button := new(model.SlackAttachment)
        parameter := new(model.PostAction)
        parameter.Integration = new(model.PostActionIntegration)
        parameter.Integration.Context = make(model.StringInterface)
        parameter.Name = "TEST"
        parameter.Integration.URL = myServerURL
        parameter.Integration.Context["button"] = "TEST"
        button.Actions = append(button.Actions, parameter)

        return append(result, button)
}

```

#### Expected behavior

Cannot send request from posted button using `github.com/mattermost/mattermost-server/model` library to my server.

#### Possible fixes

When I use `*Client4.CreatePost(post *Post)` method from `github.com/mattermost/mattermost-server/model` library intended to send a message with a button (https://github.com/mattermost/mattermost-server/pull/7274), I found a bug that request was not to sent when I pushed the button posted to Mattermost.

This bug is caused by assigning `nil` to `Integration` member variable in `PostAction` struct, in the `*Post.StripActionIntegrations()` called within `*Post.ToJson()` called within `*Client4.CreatePost(*Post)` .

- https://github.com/mattermost/mattermost-server/blob/master/model/post.go#L369
- https://github.com/mattermost/mattermost-server/blob/master/model/post.go#L121
- https://github.com/mattermost/mattermost-server/blob/master/model/client4.go#L1731

What's `*Post.StripActionIntegrations()` intending?

If there is no problem, I would like to make a correction as follows.

- https://github.com/ShotaKitazawa/mattermost-server/commit/429f81aaef5e211898d66be774cfe737a55d3153

**Comment by ccbrown** [comment]
The point of `StripActionIntegrations` is to sanitize the post before sending it to clients. As [documented](https://docs.mattermost.com/developer/interactive-message-buttons.html#button-options), one of the purposes of the integration context is to authenticate the Mattermost server to your integration. Exposing that to users defeats the security of action buttons entirely.

But that's only intended to happen when sending posts _to_ clients. When clients are sending posts to the server, the post shouldn't be sanitized. I've created a PR to fix this here: https://github.com/mattermost/mattermost-server/pull/8219

**Comment by ShotaKitazawa** [comment]
Thank you for PR. 
I wish that it will be committed soon.

**Comment by lindy65** [comment]
I'll close this issue off for now as the PR has been merged.
