### ISSUE TITLE
A "Failed Login attempt" entry is erroneously added to the  access history when logging out

### ISSUE THREAD

**Issue by stevewan** [mattermost/mattermost-server#8210]
#### Summary
A "Failed Login attempt" entry is erroneously added to the  access history when logging out

#### Steps to reproduce
1) Login to Mattermost
2) Logout of Mattermost
3) Login to Mattermost
4) Open up the Mattermost menu
5) Click Account Settings
6) Click Security
7) Click View Access History

#### Expected behavior
There should not be "FAILED Login attempt" entries in the access history when logging out of Mattermost. 

#### Observed behavior (that appears unintentional) 
There are "FAILED Login attempt" entries

Video attached in the zip file. 

<img width="563" alt="screen shot 2018-02-06 at 10 52 46 am" src="https://user-images.githubusercontent.com/17625450/35878033-e63a7c56-0b2b-11e8-86c2-0a92c4e00dfe.png">
[2018-02-02_13-32-41.mp4.zip](https://github.com/mattermost/mattermost-server/files/1700422/2018-02-02_13-32-41.mp4.zip)

 in the access history when logging out of Mattermost. 

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by qichengzx** [comment]
@stevewan 
Here, https://github.com/mattermost/mattermost-server/blob/121712ce5d61cd0bb35efa5bacd59f7f9daff326/api4/user.go#L925 
when the client login success ,server will log as "authenticated", and there is no special treatment in 
https://github.com/mattermost/mattermost-webapp/blob/fe8925c2edeabe24b7fb1c9dc11bd897bb9c0722/components/audit_table.jsx#L446 
`auditDesc = formatMessage(holders.failedLogin);`
, so webapp will show "FAILED Login attempt"

I'm not sure is there need to change.

My English is not very good, I hope I was explained it clearly.

**Comment by stevewan** [comment]
@qichengzx 

From a UI and audit log perspective, why would it ever display a "FAILED login event"? when that never actually happened?

**Comment by qichengzx** [comment]
@stevewan 
I'm not sure about it, it's not "failed" but success actually,maybe webapp should just show "authenticated" or nothing.

**Comment by lindy65** [comment]
Hi @stevewan @qichengzx 

I'll close this issue off here for now and we can track via the PR linked above 👍
