### ISSUE TITLE
Channel header display when text is in quote format

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-server#8213]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
When a channel header text contains a quote, the text is cut halfway through vertically

#### Steps to reproduce
Using the webapp, version 4.6.0, with Firefox 58.0.
Enter a quote in a header channel (the example on the screenshot below is ">Failure is not an option -- it comes bundled with Windows. ") & save it.

#### Expected behavior
Text should be displayed entirely (whether with the quote format or without, that's up to you).

#### Observed behavior (that appears unintentional) 
The text is cut 
![image](https://user-images.githubusercontent.com/8834237/35906945-a9e92c68-0bec-11e8-8cf0-6e77bf950436.png)

**Comment by lindy65** [comment]
Hi @moussetc,

Thanks for your feedback,

This has recently been fixed on master and will ship with v4.7 on February 16th.

![image](https://user-images.githubusercontent.com/13020833/35962486-4a56b800-0cba-11e8-85d0-cd6b66cb1756.png)

**Comment by lindy65** [comment]
I'll close this off for now and we can reopen if the issue reproduces after v4.7 releases on Feb 16th.
