### ISSUE TITLE
Search starting with in: doesn't reflect (changed) display name of a channel

### ISSUE THREAD

**Issue by chumbalum** [mattermost/mattermost-server#8215]
#### Summary
When the user searches with the prefix **in:**, the original channel name respectively channel url is used for display. Since the channel url for town-square cannot be changed, this can be confusing if town-square channel was renamed

![grafik](https://user-images.githubusercontent.com/486034/35922456-ee9b8d70-0c1d-11e8-9902-f955b0eed36e.png)

#### Steps to reproduce
* rename town-square channel
* do a search starting with in:

#### Expected behavior
current (display-)name of the channel should be used

#### Observed behavior (that appears unintentional) 
original name, respectively channel url is beeing shown

**Comment by lindy65** [comment]
Thanks for your report @chumbalum,

I believe this would require a code change so I'll ask one of our product managers for feedback on this one...

**Comment by lindy65** [comment]
Hi @chumbalum,

We have a conversation on our [team server](https://pre-release.mattermost.com/core/pl/7o55nwsxcjbxtnn7e7hyrhq7ih) that you can follow regarding this issue.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the conversation linked above.

**Comment by chumbalum** [comment]
ok thanks for the feedback :)
