### ISSUE TITLE
Insecure images are loaded by sending client before proxying

### ISSUE THREAD

**Issue by laCour** [mattermost/mattermost-server#8221]
#### Summary
With image proxying enabled, when a user sends a message with an insecure image, the original image will be loaded for that user but not others.

- **mattermost-server:** `release-4.7` @ `654fc2f`
- **mattermost-webapp:** `release-4.7` @ `685cab4`
- **Browser:** Chromium 64.0.3282.140

#### Steps to reproduce

1. Enable image proxying.
2. Send a message with an insecure image: `![](http://i.redd.it/6cohydckk6501.jpg)`

#### Expected behavior
Only the proxied image will be loaded.

#### Observed behavior (that appears unintentional) 
The original source image will be loaded in the background, but the message will display the secure image.

```
Mixed Content: The page at '--' was loaded over HTTPS, but requested an insecure image 'http://i.redd.it/6cohydckk6501.jpg'. This content should also be served over HTTPS.
```

**Comment by lindy65** [comment]
Hi @laCour,

Thanks for the report :)

I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8718) to investigate...

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
