### ISSUE TITLE
Cannot escape ~ (tilde) in markdown

### ISSUE THREAD

**Issue by robsdedude** [mattermost/mattermost-server#8228]
#### Summary
`~` cannot be escaped with backslash.

#### Description
Writing `\~\~strikethrough\~\~` should be turned into "\~\~strike through\~\~". However what you will see is literally "\\\~\\\~strike through\\\~\\\~".

#### Why even bother
Mattermost supports strikethrough using `~~`. Therefore, `~` is a special character which should be escapable. How else should one write "\~\~strike through\~\~"?

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
