### ISSUE TITLE
Mattermost server periodically shuts down 

### ISSUE THREAD

**Issue by torgeirl** [mattermost/mattermost-server#8239]
I don't know exactly how to explain this issue and what's relevant information as I don't know what's wrong, but in short: in the last few months the Mattermost server I manage have stopped without any error being logged.

All systemd services seems fine, but Nginx serves HTTP 502 bad gateway and the Mattermost server logs contains the following actions (two examples):

```
[2017/11/15 06:11:31 UTC] [INFO] Stopping schedulers.
[2017/11/15 06:11:31 UTC] [INFO] Schedulers stopped.
[2017/11/15 06:11:31 UTC] [INFO] Stopped workers
[2017/11/15 06:11:31 UTC] [INFO] Stopping Server...
[2017/11/15 06:11:31 UTC] [INFO] stopping websocket hub connections
```

```
[2018/02/10 06:45:17 UTC] [INFO] Stopping schedulers.
[2018/02/10 06:45:17 UTC] [INFO] Schedulers stopped.
[2018/02/10 06:45:17 UTC] [INFO] Stopped workers
[2018/02/10 06:45:17 UTC] [INFO] Stopping Server...
[2018/02/10 06:45:17 UTC] [INFO] stopping websocket hub connections
[2018/02/10 06:45:17 UTC] [INFO] Closing SqlStore
```

The issue is solved by restarting the Mattermost server service.

The system setup mimics the recommendation in the documentation: Ubuntu 16.04 LTS, Postgresql and Nginx. Please let me know what details could be useful in the diagnosis of the issue.

#### Steps to reproduce
I wish I knew how to provoke this, but I sadly don't.

**Comment by lindy65** [comment]
Hi @torgeirl,

Thanks for the report,

Can you share which server version of Mattermost you have installed?  If you're not on the [latest version](https://about.mattermost.com/download/), we recommend upgrading.  You could wait until v4.7 is released on February 16th if you wish?

**Comment by torgeirl** [comment]
Hi @lindy65,

Currently running v4.6. And the server usually get patched the same day a new patch is released.

In November, it happened the day before I upgraded from v4.3 to v4.4 so it seems to have been an issue for some time and across server versions.

**Comment by amyblais** [comment]
Hi @torgeirl,

Please take a look and follow the steps in our ["Mattermost is not working / The server keeps dying"](https://docs.mattermost.com/process/support.html?highlight=support#mattermost-is-not-working-the-server-keeps-dying) section of our documentation and let us know if this does or doesn't solve the issue you are experiencing.

**Comment by torgeirl** [comment]
Hi @amyblais,

Thank for you taking the time. I went through the list:

1. The server process (and processes for Postgresql and Nginx) didn't report any errors the times the issue has occurred.

2. Everything is enabled, and runs after a reboot (verified).

3. As I said in the opening post, the logs contains no reason for **why** the server shut down - it just stats that it did.

4. These are all the lines from `sudo journalctl -u mattermost.service` for the last morning the machine went down (`machinename` is a pseudonym for the actual machine name):
```
Feb 10 06:45:17 machinename systemd[1]: Stopping Mattermost...
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Stopping schedulers.
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Schedulers stopped.
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Stopped workers
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Stopping Server...
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] stopping websocket hub connections
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Closing SqlStore
Feb 10 06:45:17 machinename systemd[1]: Stopped Mattermost.
Feb 10 10:03:51 machinename systemd[1]: Stopped Mattermost.
Feb 10 10:03:51 machinename systemd[1]: Started Mattermost.
Feb 10 10:03:52 machinename platform[5553]: [2018/02/10 10:03:52 UTC] [INFO] Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
```

During working hours, the machine uses about 20 % of its available RAM so I don't think that should be an issue.

**Comment by crspeller** [comment]
@torgeirl 
```
Feb 10 06:45:17 machinename systemd[1]: Stopping Mattermost...`
```
This is systemd shutting down Mattermost. This is confirmed by the MM logs that show a normal shutdown. Not familiar with a reason why systemd would shut MM down like that. Do you have some automation setup like puppet or chef? Maybe a cron job is shutting down MM?

**Comment by torgeirl** [comment]
@crspeller: yes, as you pointed out the answer to who was right in front of me. I looked though systemd's logs since last restart (`journalctl -b`), and it seems a daily apt upgrade job caused the shutdown on February 10th:

```
Feb 10 06:45:12 machinename systemd[1]: Starting Daily apt upgrade and clean activities...
Feb 10 06:45:17 machinename systemd[1]: Reloading.
Feb 10 06:45:17 machinename systemd[1]: Started ACPI event daemon.
Feb 10 06:45:17 machinename systemd[1]: Stopping Mattermost...
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Stopping schedulers.
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Schedulers stopped.
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Stopped workers
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Stopping Server...
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] stopping websocket hub connections
Feb 10 06:45:17 machinename platform[1274]: [2018/02/10 06:45:17 UTC] [INFO] Closing SqlStore
Feb 10 06:45:17 machinename systemd[1]: Stopped Mattermost.
Feb 10 06:45:17 machinename systemd[1]: Stopped PostgreSQL RDBMS.
Feb 10 06:45:17 machinename systemd[1]: Stopping PostgreSQL Cluster 9.5-main...
Feb 10 06:45:18 machinename systemd[1]: Stopped PostgreSQL Cluster 9.5-main.
Feb 10 06:45:19 machinename systemd[1]: Reloading.
Feb 10 06:45:19 machinename systemd[1]: Started ACPI event daemon.
Feb 10 06:45:19 machinename systemd[1]: Reloading.
Feb 10 06:45:19 machinename systemd[1]: Started ACPI event daemon.
Feb 10 06:45:19 machinename systemd[1]: Starting PostgreSQL Cluster 9.5-main...
Feb 10 06:45:21 machinename systemd[1]: Started PostgreSQL Cluster 9.5-main.
Feb 10 06:45:21 machinename systemd[1]: Starting PostgreSQL RDBMS...
Feb 10 06:45:21 machinename systemd[1]: Started PostgreSQL RDBMS.
Feb 10 06:45:23 machinename systemd[1]: Started Daily apt upgrade and clean activities.
```

As I stated in the opening post, the system setup mimics the [recommendation in the documentation](https://docs.mattermost.com/install/install-ubuntu-1604.html). It instructs to [make a systemd unit file](https://docs.mattermost.com/install/install-ubuntu-1604.html#installing-mattermost-server) that makes sure Mattermost always get started after PostgreSQL, but perhaps it also should include some instructions on making sure Mattermost is restarted after PostgreSQL is automatically maintained as seems to be the cause of this issue?

**Comment by SmartHoneybee** [comment]
> making sure Mattermost is restarted after PostgreSQL is automatically maintained

It is probably hard to determine if the restart was caused by automatic maintenance. You could try to append `WantedBy=postgresql.service` to your Mattermost service definition. This should ensure that [whenever PostgreSQL is started, Mattermost is started too][1].

[1]: https://unix.stackexchange.com/q/375091

**Comment by torgeirl** [comment]
@SmartHoneybee: yes, that seems to be a fix to the issue. :+1: 

The only change to the unit file guidelines in mattermost/docs since the initial [Hackfest 2016 PR](https://github.com/mattermost/docs/pull/742) seems to be [adding the LimitNOFILE](https://github.com/mattermost/docs/pull/997) so I guess I'll make a PR there if this works.

If you guys don't mind I would like to keep this issue open till I'm ready with a PR (1-2 weeks to see that it doesn't cause other issues).
