### ISSUE TITLE
Jump to a Pinned post functionality sometimes displays incorrect post 

### ISSUE THREAD

**Issue by jimbothree** [mattermost/mattermost-server#8242]
#### Summary
On the Mattermost Demo site, using the 'Jump' functionality to pinned posts in the Open Discussion forum does not always navigate to the correct post.

#### Steps to reproduce
Assumption: Logged into an account on the Mattermost demo site (https://oss.mattermost.com)
- Actively in the Open Discussion Forum channel
- Click the 'Pinned Posts' icon to the right of the Channel name and Members icon at top of page. 
- All pinned posts on the Open Discussion Forum should appear as a tab on the right of the page 
- Click the 'Jump' link on a few pinned posts consecutive times
- The app will snap to and display a different post than was originally selected

#### Expected behavior
If a user attempts to jump to a previously pinned post on the channel, the app should snap to and display the Pinned message.  

#### Observed behavior (that appears unintentional) 
When I clicked 'Jump' on a Pinned post for the Open Discussion forum, the behavior i experienced was that the correct post was displayed for an instant and then the app would snap to an incorrect message that was not the selected Pinned post. 

![jumptoexample](https://user-images.githubusercontent.com/16659457/36083058-f1231a4c-0f7c-11e8-8248-1fb9e58fd7ac.png)

![jumptobug](https://user-images.githubusercontent.com/16659457/36083059-f356e334-0f7c-11e8-8f94-34e29cbf2c7d.png)

**Comment by lindy65** [comment]
Hi @jimbothree,

Thanks for the report,

I've just tried to reproduce your issue on oss.mattermost.com and am not able to.  Each time I click "jump" on a pinned post in the right-hand-side, I am taken to the correct highlighted post in the center channel.

Can you tell me if you tested when oss.mattermost.com was upgraded to v4.7 RC-1?  You can check the version by clicking on the hamburger main menu and selecting "About Mattermost".  Thanks!

**Comment by jimbothree** [comment]
Hi @lindy65 

I confirmed this morning that I tested oss.mattermost.com on version v4.7 RC-1.   Have you tried jumping to multiple different Pinned posts?  

When I tested this issue again this morning, I did see the correct message being highlighted in the center channel.  However - if continued to jump to other Pinned posts, I would experience the issue I reported.

**Comment by lindy65** [comment]
Hi @jimbothree,

Yes, I did test pinned posts quite extensively and couldn't reproduce the issue.  Perhaps there is some corner case I'm missing that you're perhaps hitting.

I've also tried testing on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and also cannot reproduce.  Could we have your help testing here to see if you can reproduce the issue?

**Comment by jimbothree** [comment]
Hmm.. I was able to re produce this using Google Chrome and Edge as my Browser - even on the nightly build server.  

In the public channel 'Reception' I was jumping between Ian Tien's pinned post on Meetups Posted Mon Nov 06 2017 and matterbot's Code of conduct post from Sat March 05 2016.   

While it did work some of the time, I 'spam jumped' between those two on Google Chrome and Edge and experienced the center area not snapping to the correct post.

**Comment by lindy65** [comment]
Hey @jimbothree,

I'm going to ask a few of my colleagues to try and reproduce your issue and will post feedback here...

I'm thinking it might have to do with image thumbnails as we have had some issues with them causing scroll pop...

**Comment by amyblais** [comment]
Hi @jimbothree, I'm able to reproduce on some pinned posts - there is a ticket related to this open here: https://mattermost.atlassian.net/browse/PLT-5395

**Comment by jimbothree** [comment]
Thanks for pointing that out @amyblais.  If that's the case I can close this issue so we don't have a duplicate or confusion.
