### ISSUE TITLE
Unable to log into my Mattermost instance

### ISSUE THREAD

**Issue by vedawms** [mattermost/mattermost-server#8248]
Mattermost for Android was working fine earlier, until I tried to log out and back in again. Now https://mattermost.teamworksapp.com gives a 404, and I can't log in at all. I downloaded the new version, same problem. 

Android 7.

**Comment by lindy65** [comment]
Hi @vedawms,

Thanks for the report,

Can you share which version of Mattermost server you have installed?  And which Android device you have?

**Comment by vedawms** [comment]
Yes, we're on 4.4.3. I'm running Android 7, Samsung S8. My colleague is running Android 8. We are both running the app store version, 1.6.0. Both of us are having spotty issues logging in. Sometimes it works, sometimes it doesn't...

**Comment by lindy65** [comment]
Thanks for the feedback @vedawms,

We recommend upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost which is v4.6.1 although you might want to wait until Feb 16th when v4.7 is released.

Let us know if this fixes the issue for you?

**Comment by lindy65** [comment]
Hi @vedawms 

I'll close this issue off here for now and you can let us know if the problem still persists after upgrading 👍
