### ISSUE TITLE
[Not Bug] Precompiled files close glibc dependencies (CGO_ENABLED)

### ISSUE THREAD

**Issue by mritd** [mattermost/mattermost-server#8257]
It is recommended to set `CGO_ENABLED = 0` in the precompiled binaries; I created a docker image based on alpine, but mattermost does not work well because the mattermost precompiled file depends on glibc.

my dockerfile: https://github.com/mritd/dockerfile/blob/master/mattermost/Dockerfile

**Comment by pichouk** [comment]
It is not an answer to your problem, but if you are interested we already have a new Alpine-based Docker image for Mattermost => https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile

**Comment by mritd** [comment]
@pichouk Thank you for your reply, the official dockerfile is not suitable for me; however, I refer to the official dockerfile installed libc6-compat to solve this problem.
