### ISSUE TITLE
Add Members List: Status icons do not display in any Add Members list

### ISSUE THREAD

**Issue by mattrampolla** [mattermost/mattermost-server#8258]
#### Summary
The Add Members lists, from both Main Menu > 'Add Members to Team' and Channel name drop-down > 'Add Members' do not display the status icon on users' profile pictures.
Status icons are currently displayed on all other Members lists.

#### Steps to reproduce

1. Log in to Mattermost - Version: 4.7.0 (4.7.0-rc2)
2. Select the Main hamburger menu > Add Members to [team_name] Team 
3. View 'Add New Members To Team' list
4. Close list
5. Select any public or private channel
6. Select the Channel name dropdown, above the chat window
7. Select 'Add Members'
8. View 'Add New Members to [channel_name]' list

#### Expected behavior
- All Members lists display a status icon on a user's profile picture.  
Members lists include: Channel name drop-down > Manage (or View or Add) Members, Main hamburger Menu > Add Members to Team, and Direct Message 'More...' user list. 

#### Observed behavior (that appears unintentional) 
-  Selecting Channel name drop-down > 'Add Members' or Main hamburger Menu > 'Add Members to Team' displays a list of users, but does not display a status icon on a user's profile picture.

![add members list status icon](https://user-images.githubusercontent.com/17954664/36139707-9ff75eda-106c-11e8-97e6-d3281cb5d419.gif)

**Comment by lindy65** [comment]
Hi @mattrampolla,

Thanks for the report!

I'm not sure whether this is the expected behavior or whether it is a bug.  I'll check with the team as there have been recent changes to the way members of a channel are listed (online / away / offline) and am not sure if the code for adding members to a channel or team was changed.

**Comment by lindy65** [comment]
Hi @mattrampolla,

Thanks for the feedback,

I'm checking with the product managers but I think the decision was that it's not really necessary to see whether someone is online or not when adding them to a team or channel...

I'll post here with their feedback...

**Comment by amyblais** [comment]
Hi @mattrampolla,

I have created a ticket here to add this feature as an improvement: https://mattermost.atlassian.net/browse/MM-9695

**Comment by lindy65** [comment]
I'll close this issue off here for now @mattrampolla and we can track via the ticket linked above 👍
