### ISSUE TITLE
gifv files do not display

### ISSUE THREAD

**Issue by basnijholt** [mattermost/mattermost-server#8260]
`![](http://somewebsite.gifv)` displays nothing:

<img width="232" alt="screen shot 2018-02-13 at 10 34 06" src="https://user-images.githubusercontent.com/6897215/36142815-76635762-10a9-11e8-8ab6-eb3d085fb048.png">

**Comment by lindy65** [comment]
Thanks for the report @basnijholt 

I've reproduced your issue and have filed [this ticket](https://mattermost.atlassian.net/browse/MM-9584) to track.

**Comment by jasonblais** [comment]
Hey @basnijholt! We've created a help wanted ticket here, if anyone in the community is interested helping with a fix: https://github.com/mattermost/mattermost-server/issues/8302
