### ISSUE TITLE
Attempted preview of attached document fails to finishing "loading" if the file extension doesn't match the actual file type

### ISSUE THREAD

**Issue by billybrown1** [mattermost/mattermost-server#8268]
#### Summary
Attempted preview of attached document fails to finishing "loading" if the file extension doesn't match the actual file type

#### Config:
Web browser:
• Google Chrome - MacOS X - Version 63.0.3239.132 (Official Build) (64-bit)

#### Steps to reproduce
1)  Login to https://demo.mattermost.com and go to the Joomla channel, and enter the main public channel, “Channel for bug finding”
2)  On the client desktop, make a copy of a legitimate valid JPEG photo file (such as this smiley face):
![smiley-face](https://user-images.githubusercontent.com/25070389/36156411-2f3a5d64-1094-11e8-8735-d0bb8ab7c0be.jpg)
3) While the file is still local on the client machine, rename the copy of file to be "Smiley-face JPG but with wrong extension.pdf" so that the dot-extension is something other than .jpg (.pdf for example)
4)  Now in the Channel for Bugfinding, type a sentence and attach this renamed file "Smiley-face JPG but with wrong extension.pdf"
<img width="704" alt="screen shot 2018-02-12 at 7 57 36 pm" src="https://user-images.githubusercontent.com/25070389/36156513-7c53b370-1094-11e8-8e06-a126c63e89cd.png">
5) Now press ENTER (or RETURN) so the upload happens.
6)  After the file has uploaded, attempt to preview the file by clicking on the dog-eared PDF document icon:
<img width="649" alt="screen shot 2018-02-12 at 7 53 46 pm" src="https://user-images.githubusercontent.com/25070389/36156565-aace552a-1094-11e8-8811-b1d7a35ebe74.png">
7)  Continue waiting… nothing ever times out...
*** The PREVIEW “loading” activity graphic just continues to spin and spin
*** (1) The preview of the file never seems to finish, it doesn’t seem to ever time-out
*** (2) An error is never displayed
*** (3) The file previewer depends too heavily on just the .filename extension, rather than attempting to parse the actual binary header in the file

#### Expected behavior
Some better visual feedback should be displayed, so that the user doesn't think it is just taking a long time trying to load the file.
For example, maybe if the file is invalid (and or the binary header of the file doesn't match the expected filename extension characters), something visual like a generic document but with a ghostbuster's style red-slash over it should be shown.  This way the user realizes something is wrong, and they aren't just left waiting and wondering if the preview will ever load.

#### Observed behavior (that appears unintentional) 
Currently an animated gif with 3 bars from left-to-right is displayed in a loop... and it appears to the user as if something is simply just taking a long time to load... when that is not actually the case, because the file is actually invalid (or at least the binary header of the file doesn't match the expected filename extension characters).

#### Possible fixes
Give the user some visual feedback that the attempted preview has failed, rather than just endlessly showing the 3-bar "busy" loop graphic.

**Comment by lindy65** [comment]
Hi @billybrown1 

Thanks for the report!

I've reproduced your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and have filed [this ticket](https://mattermost.atlassian.net/browse/MM-9583) to track.

**Comment by lindy65** [comment]
Hi @billybrown1 

I'll close this issue off here for now and we can track via the ticket linked above 👍

**Comment by billybrown1** [comment]
Agreed!  Sounds Good.

—
Billy Brown
