### ISSUE TITLE
The server-side time-stamps on demo.mattermost.com/joomla server are off by 12 minutes fast (in the future)

### ISSUE THREAD

**Issue by billybrown1** [mattermost/mattermost-server#8270]
#### Summary
The server-side time-stamps on the demo.mattermost.com/joomla server are off by 12 minutes fast (in the future)

#### Config:
Web browser:
• Google Chrome - MacOS X - Version 63.0.3239.132 (Official Build) (64-bit)

#### Steps to reproduce
1)  Login to https://demo.mattermost.com and go to the Joomla channel
2)  Under PUBLIC CHANNELS in the blue sidebar (on the left) select “Channel for bugfinding”
3)  Type some text into the channel, such as "time now is 15 minutes till the top of the hour, 8:45AM Mountain"
4)  The time-stamp on the text when displayed in the channel is seemingly off by 12 minutes fast in the future.
![server time off by 12 minutes fast](https://user-images.githubusercontent.com/25070389/36159209-6a26841e-109b-11e8-85da-340aa725c030.jpg)

#### Expected behavior
Since my MacOS X client's clock is syncronized via NTP, I would expect that the https://demo.mattermost.com server too would be more-or-less syncronized as well.

#### Observed behavior (that appears unintentional) 
The server-side time-stamp is off by about 12 minutes fast (in the future)

#### Possible fixes
Adjust the time, or NTP connection settings so the time on the server is correct.

**Comment by lindy65** [comment]
Hi @billybrown1 

Thanks for your feedback,

Linking [this issue](https://github.com/mattermost/mattermost-server/issues/8241) from a report a few days ago.  The fix will ship Feb 16th with v4.7.
