### ISSUE TITLE
[Help Wanted] [ABC-237] Cache custom emoji beyond a single session, so that they're not downloaded after each refresh, only after logout and re-login.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8271]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/ABC-237)

Cache custom emoji beyond a single session, so that they're not downloaded after each refresh, only after logout and re-login. This results in a better user experience when using the autocomplete.

Note: For questions, you can ask `joram` at https://pre-release.mattermost.com/core.

**Comment by santos22** [comment]
Hi @jwilander 👋 

Would this be similar to the caching being done in [status.go](https://github.com/mattermost/mattermost-server/blob/master/app/status.go)?

**Comment by jwilander** [comment]
Hi @santos22, actually this ticket is mislabeled. It's actually a React/Redux client side ticket. Essentially we fetch a bunch of custom emojis from the server and then throw them away when the client refreshes. So for this ticket we'd be using redux-persist to actually store them in local storage. We already do this for some Redux store entities (especially on mobile)

Let me know if that helps

**Comment by hanzei** [comment]
@jwilander Do you know if this ticket is still valid? I thought I saw a PR that fixed this.

**Comment by jwilander** [comment]
I don't think we're caching the metadata yet. I know the browsers cache the images though. @hmhealey will know better

**Comment by hmhealey** [comment]
The custom emojis are sent down as part of the post metadata, and they're sent fairly aggressively, so I don't think it makes sense to cache them on the client at this point. We can probably close this.

**Comment by hanzei** [comment]
@jwilander Are you fine with closing this one?

**Comment by jwilander** [comment]
Yep, closing
