### ISSUE TITLE
[Help Wanted] [PLT-8773] Link Previews Appear for Links Posted in Channel Header

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8273]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8773)

Repro:

1) Change header of a public channel to 
```
- One
- https://www.google.com
- Two
```

Observed: A system message appears announcing the change, and a link preview renders for https://www.google.com. 

Expected: No link preview appears for the system message.

**Comment by jkurian** [comment]
Interested in resolving this bug!

Anything I should know before beginning?

**Comment by satoshicano** [comment]
Hi, there. I have a question.
This bug seems fixed?
I try to reproduce this bug on pre-release, but it's not show any link preview.

**Comment by jasonblais** [comment]
@satoshicano You're correct. This appears to be resolved, closing the issue.

Any help wanted ticket you're interested investigating? :)
