### ISSUE TITLE
Account Settings - Email: Editing a user's email as the 'Current Email' should display a notification indicating the 'New Email' must differ from the 'Current Email'

### ISSUE THREAD

**Issue by mattrampolla** [mattermost/mattermost-server#8276]
#### Summary
When editing an account's email address, the user is able to save a 'New Email' that is the exact same as the 'Current Email'.  
A user should not have the ability to save a 'New Email' that is the same as the 'Current Email'.  Entering the same email and saving should return a message, indicating a new email must be different from the current email address.

While this is a lower level issue, a user should be informed that they did not change their email to anything new.

#### Steps to reproduce

1.   Login to Mattermost Version: 4.7.0 (4.7.0-rc2)
2. Select Main Menu (hamburger menu)   
3. Select Account Settings   
4. Select General tab if not the default selection. (Note: General will not   be selected if the browser window is of a smaller size.)   
5. Select anywhere in the 'Email' row, select 'Edit', or select the current email address (visible with smaller browser window)   
6. In the 'New Email' text box, enter the exact same email as the 'Current Email'
7. Input exact same email as the 'Current Email' in the 'Confirm Email' text box   
8. Select 'Save' 

#### Expected behavior
When a user enters a 'New Email' that is the same as the 'Current Email' a message should display, indicating the 'New Email' cannot be the same as the 'Current Email'/must differ from the 'Curren Email'.  

#### Observed behavior
When a user enters a 'New Email' that is the same as the 'Current Email' and selects 'Save', they are not given any feedback as to whether or not they successfully entered a new email address or that they made no real changes.

#### Possible fixes
Add a message/error/notification informing the user that a new email must differ from the current email address and/or that no changes were made. 

![2018-02-13_16-17-04](https://user-images.githubusercontent.com/17954664/36174367-1df4fc94-10da-11e8-94c3-c7370bdc629c.gif)

**Comment by lindy65** [comment]
Hi @mattrampolla,

Thanks for your report and apologies for the delay in responding!

I've created a [ticket](https://mattermost.atlassian.net/browse/MM-9691) to fix the issue so will close of this issue here and we can track via the ticket...

**Comment by amyblais** [comment]
Hi @mattrampolla,

Just wanted to let you know that [this ticket](https://mattermost.atlassian.net/browse/MM-9691) has been closed as "Won't Fix" because the engineers have clarified that what has been described here is actually expected (not a bug), as it follows our "forgiving" design principle.
