### ISSUE TITLE
Setting Mattermost with no rooms

### ISSUE THREAD

**Issue by c0fe** [mattermost/mattermost-server#8278]
Is it possible to setup Mattermost to have no rooms and for users not only be to chat with anyone else that isn't in their contact list? Such as what AIM and Skype allow?

**Comment by lindy65** [comment]
Hi @c0fe 

Thanks for your feedback,

At the moment, it's not possible and always loads with one default channel, being "Town Square".

**Comment by amyblais** [comment]
Hi @c0fe,

Thank you for your feedback, here is one suggestion:

Do you have an Enterprise license? If so, you can:
 - Use policy settings to not allow anyone to create public and private channels except the System Admin.
 - Use another setting to set Town Square as read-only.
With the above two settings, users who aren't System Admins can only post in 1-1 and 1-many direct message channels.

Let me know if this helps?

**Comment by lindy65** [comment]
Hi @c0fe 

Has the suggestion from `amyblais` helped solve your issue?

**Comment by c0fe** [comment]
@lindy65 they answered the question but didn't resolve the issue. It would appears that MatterMost is not a solution for me.

**Comment by lindy65** [comment]
Hey @c0fe,

Thanks for your feedback, if you'd like to try the enterprise edition for your company, you can request a trial licence [here](https://about.mattermost.com/trial/).  This might help you better assess whether Mattermost suits your requirements.
