### ISSUE TITLE
Disable Ios Nag Screen

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost-server#8288]
I have a user who solely wants to use the web interface of mattermost even on his Iphone. He is complaining that he always has to bypass the nag screen to use the native app and that sometimes this screen cannot be scrolled so that he cannot access the "Go to browser" option. Is there a way to turn the nag screen off? And if not it would be nice to have one.

**Comment by lindy65** [comment]
Hi @Twilek-de,

Thanks for your feedback,

I'll ask a product manager to give feedback about doing away with the 'nag screen'.  It's there because the mobile apps are far more reliable and faster than using the browser so I'm not sure we'd want to do away with it.  ;)

We have [a ticket](https://mattermost.atlassian.net/browse/MM-8004) to fix the issue of the landing page scrolling.

**Comment by Twilek-de** [comment]
I would not want to remove it completely, just an option to turn it off. What about a little checkbox "Do not show this again" to tick so that for that particular browser a cookie is set and the landing page is bypassed. Otherwise you only annoy people.

**Comment by Twilek-de** [comment]
Or something a little more unobstrusive like LinkedIn does it.
![img_3805](https://user-images.githubusercontent.com/8283684/36197296-adc6ad60-1173-11e8-9fb7-7586abf7da61.JPG)

**Comment by lindy65** [comment]
Hi @Twilek-de 

Thanks for clarifying,

Our mobile team will be discussing the option to be able to turn off the 'nag screen' and you can follow the conversation on our nightly build server [here](https://pre-release.mattermost.com/core/pl/9ikmgsn5gp8e786f57ijrgpb7y).

**Comment by lindy65** [comment]
Hi @Twilek-de 

I'm going to close this issue off here for now and we can follow in the conversation linked above.

**Comment by M1dgard** [comment]
Hi @lindy65, I tried to read the discussion on ~peer-to-peer-help but I couldn't see a resolution. Is this something you still track?

I just upgraded from TE 4.6.0 to 4.7.2 and it seems the nag screen has *increased*, it now appears at each and every page load – unbearably irritating! I'm even considering to downgrade.

Btw: also for Android, not only iOS.

**Comment by lindy65** [comment]
Thanks @M1dgard,

Apologies for the delay in moving forward with a decision on this one...  Our entire team has been travelling for the past week but we're back Monday so I hope to have an update for you then 👍

**Comment by M1dgard** [comment]
Hi Katrin

Thanks for your reply.

The hi-res tiles didn't load due to a browser policy. The issue has now been resolved!

Best regards
Ruben

**Comment by esethna** [comment]
FYI for those following this thread, we have a ticket here: https://mattermost.atlassian.net/browse/MM-12140 

Apologies for the delayed response.
