### ISSUE TITLE
Portforwarding will grab all port 80s

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost-server#8291]
#### Summary
When enabling Forwarding Port 80 MM seems to grab all IPs

#### Steps to reproduce
When having more than one Networkadapter and having MM listen on one of them on port 443, enabling portforwarding will have MM grab port 80 on all of them

#### Expected behavior
Only taking port 80 on the adress the server is listening on on port 443

**Comment by lindy65** [comment]
Hi @Twilek-de 

Thanks for the feedback,

I'm going to reference [this forum issue](https://forum.mattermost.org/t/tls-handhshake-error-acme-could-not-find-solver-for-http-01-acme-could-not-find-solver-for-dns-01/4420/15) where you report this happening so we have a cross-reference.

I'll also ask our engineers to take a look at this issue...

**Comment by lindy65** [comment]
Hi @Twilek-de,

I've made a [ticket](https://mattermost.atlassian.net/browse/MM-9623) to track this issue.

**Comment by Twilek-de** [comment]
Thanks, hmm somehow it seems even stranger than that. When I start mattermost with an IP4 Listenadress with port 443 (x.x.x.x:443) and enable redirect Port 80 to 443 mattermost binds to  port 80 in IPv6
`netstat -tulpn | grep :80
tcp6       0      0 :::80                   :::*                    LISTEN      9504/platform`

when I then try to start apache2 I get `apachectl[9552]: (98)Address already in use: AH00072: make_sock: could not bind to address x.x.x.x:80`. Clearly an IP4 Adress and one which Mattermost does not bind to. When I stop Mattermost, then start Apache and then start Mattermost again, there are no errors. netstat correctly reports ` netstat -tulpn | grep :80
tcp        0      0 x.x.x.x:80       0.0.0.0:*               LISTEN      9739/apache2
tcp        0      0 y.y.y.y:80        0.0.0.0:*               LISTEN      9739/apache2
tcp        0      0 z.z.z.z:80        0.0.0.0:*               LISTEN      9739/apache2`

binding Apache2 to three different IP4 Adresses Port 80 , but no IP6 Mattermost. I have no idea what is going on. Somehow the IP6 binding of Port 80 on all Networkadapters seems to block taking Port 80 on IP4 Adresses.

**Comment by Twilek-de** [comment]
When I turn Apache completely off and start Mattermost with Port 80 Forwarding and lets encrypt activated netstat shows the ipv6 binding and everything works. Apache complains that it cannot bind port 80 on the ip4 adresses.

**Comment by grundleborg** [comment]
@Twilek-de are you using Apache as a reverse-proxy in front of Mattermost, or are you trying to run Mattermost listening directly on port 80 without going through a reverse proxy, and also Apache listening on port 80 (on a different IP address) on the same machine?

**Comment by Twilek-de** [comment]
I have a debian sever with 4 IPs (all IPv4). Three are used by apache exclusively and I have checked that it does not listen on the fourth. The fourth is exclusively for mattermost which it directly listens to. I do not use any proxying. But as described somehow Mattermost does not bind to a single IP cleanly.

**Comment by SmartHoneybee** [comment]
```golang
	if *a.Config().ServiceSettings.Forward80To443 {
		if *a.Config().ServiceSettings.UseLetsEncrypt {
			go http.ListenAndServe(":http", m.HTTPHandler(nil))
		} else {
			go func() {
				redirectListener, err := net.Listen("tcp", ":80")
				if err != nil {
					listener.Close()
					l4g.Error("Unable to setup forwarding: " + err.Error())
					return
				}
				defer redirectListener.Close()

				http.Serve(redirectListener, http.HandlerFunc(redirectHTTPToHTTPS))
			}()
		}
	}
```
I'm not sure if it is a good idea to `http.ListenAndServe(":http", ...)` / `net.Listen("tcp", ":80")` [here][1].

[`net` documentation][2]:
> For TCP networks, if the host in the address parameter is empty or a literal unspecified IP address, Listen listens on all available unicast and anycast IP addresses of the local system.

[`net/http`][3] passes its address [to `net.Listen`][4].

[1]: https://github.com/mattermost/mattermost-server/blob/809a16458f7483a2b762cd546493780fea6220ea/app/server.go#L178
[2]: https://godoc.org/net#Listen
[3]: https://godoc.org/net/http#ListenAndServe
[4]: https://golang.org/src/net/http/server.go#L2707

**Comment by lindy65** [comment]
Hi @Twilek-de 

I'll close this issue off here for now and we can track via the [ticket](https://mattermost.atlassian.net/browse/MM-9623) which is scheduled for inclusion in v4.8.
