### ISSUE TITLE
Memory leak on client

### ISSUE THREAD

**Issue by divanikus** [mattermost/mattermost-server#8297]
#### Summary
Switching between channels causes growing memory consumption by both browser and desktop app.

#### Steps to reproduce
Mattermost 4.5.0 (4.5.1 - postgres) GitLab Ominbus 10.4.3.
Switch between 3-4 active channels for several minutes, look at the increasing memory usage by client or tab. I hit 1GB in 2-3 minutes.

#### Expected behavior
Switching between already visited channels shouldn't consume more memory. Client becomes unresponsive very soon on low memory devices (tablets, notebooks with 4 GB RAM, etc).

#### Observed behavior (that appears unintentional) 
![84320f00379ba237c0761a13ee52f7d2](https://user-images.githubusercontent.com/3438036/36254788-6e617aca-125d-11e8-9c5e-eb1f36549cc7.png)
![123](https://user-images.githubusercontent.com/3438036/36254838-a5b41ffa-125d-11e8-9759-705a6503a120.png)

**Comment by jasonblais** [comment]
Thanks @divanikus! 

We have made a few fixes for v4.6 and v4.7 to reduce memory leaks upon team and channel switching.

v4.7 releases tomorrow (February 16th). Would you like to download the new version and see if it helps once it's published at https://about.mattermost.com/download/?

**Comment by jasonblais** [comment]
Ah, I just noticed you're running GitLab Ominbus 10.4.3.

GitLab Omnibus 10.5 that ships on February 22nd will include Mattermost v4.6. You should see improvements already then.

**Comment by lindy65** [comment]
Hi @divanikus,

Is your issue resolved now that GitLab Omnibus 10.5 has shipped?

**Comment by divanikus** [comment]
Well, it seems to still consume more and more memory when you switch between channels. Good news it frees memory after a while, 20-30 seconds I guess. I will check it more during normal daily operation.

**Comment by sudheerDev** [comment]
@divanikus Every switch allocates objects, DOM node etc so it will keep increasing. That is the case with any webapp(SPA to be specific). 
Browsers don't garbage collect or free memory if they think it is not needed as trying to free might keep the system busy from the task's user is trying to do. They collect it when they think it might slow the system. i.e after 20-30s in your case(Frequency of it is proportional to the RAM available on the system).  
If the browser cannot garbage collect and keeps hogging memory till the tab crawls then there definitely some memory leaks. Let us know if there is anything strange you are noticing in the new version of MM.

**Comment by lindy65** [comment]
Hi @divanikus,

Any update on your issue since you upgraded to the new version of MM?

**Comment by divanikus** [comment]
Well, it doesn't try to consume all the memory now. So, yes, I guess it was fixed.

**Comment by lindy65** [comment]
Thanks @divanikus, I'll close this issue off here for now then :)
