### ISSUE TITLE
clicking 'Send Message' transfers to 'Town Square' channel

### ISSUE THREAD

**Issue by tmu-sprd** [mattermost/mattermost-server#8310]
#### Summary
Clicking 'Send Message' transfers to 'Town Square' channel

#### Steps to reproduce
1. Use Mattermost Server 4.7.0, any browser or desktop client on PC (mobile client doesn't have this issue)
2. log in, switch to any channel
3. click avatar of any user
4. click 'Send Message' in popup

#### Expected behavior
There is a new channel at 'Direct Messages'. Be transferred there to write a personal message to the user.

#### Observed behavior (that appears unintentional) 
There is a new channel at 'Direct Messages'. Be transferred to 'Town Square'.

#### Possible fixes
Wild guess: there is an '@' missing at this line: https://github.com/mattermost/mattermost-webapp/blob/master/components/profile_popover.jsx#L151 ?
Currently: `/messages/${user.username}`
Correct: `/messages/@${user.username}`

**Comment by tmu-sprd** [comment]
This fixed it for me. Please check.

```
root@mattermost01 [lej] ~/go/src/github.com/mattermost/mattermost-webapp # git diff
diff --git a/components/profile_popover.jsx b/components/profile_popover.jsx
index 10484f5..151161f 100644
--- a/components/profile_popover.jsx
+++ b/components/profile_popover.jsx
@@ -148,7 +148,7 @@ class ProfilePopover extends React.Component {
                 if (this.props.hide) {
                     this.props.hide();
                 }
-                browserHistory.push(`${TeamStore.getCurrentTeamRelativeUrl()}/messages/${user.username}`);
+                browserHistory.push(`${TeamStore.getCurrentTeamRelativeUrl()}/messages/@${user.username}`);
             }
         );
     }
```

**Comment by lindy65** [comment]
Hi @tmu-sprd,

Thanks for the report!

I'm not able to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master so I believe it has been fixed.

Please try on the above server and let us know if the issue still reproduces for you?

**Comment by tmu-sprd** [comment]
Hi @lindy65 ,

I tried at https://pre-release.mattermost.com and can't reproduce it either. Seems to be fixed there.
Closing this then.

Thank you.

My best

**Comment by lindy65** [comment]
Thanks for checking @tmu-sprd,

Glad the issue is resolved :)
