### ISSUE TITLE
[webapp] please reduce default verbosity of `make build`

### ISSUE THREAD

**Issue by SmartHoneybee** [mattermost/mattermost-server#8311]
#### Summary
Mattermost webapp `make build` produces too much output.

#### Steps to reproduce
Run `make build` on tag v4.7.0.

#### Expected behavior
Successful build should result in reasonable length of output.

#### Observed behavior (that appears unintentional) 
Running `make build` produced about 20000 lines of output.
(Opinion: that's too long to skim over or to read.)

#### Possible fixes
Remove `--verbose` for `webpack` in `package.json` (reduces output to about 300 lines):
```patch
diff --git a/package.json b/package.json
index d4eabf8..d076a53 100644
--- a/package.json
+++ b/package.json
@@ -146,7 +146,7 @@
   "scripts": {
     "check": "eslint --ignore-pattern node_modules --ignore-pattern non_npm_dependencies --ignore-pattern dist --ext .js --ext .jsx . --quiet",
     "fix": "eslint --ignore-pattern node_modules --ignore-pattern non_npm_dependencies --ignore-pattern dist --ext .js --ext .jsx . --quiet --fix",
-    "build": "cross-env NODE_ENV=production webpack --display-error-details --verbose --progress",
+    "build": "cross-env NODE_ENV=production webpack --display-error-details --progress",
     "run": "cross-env NODE_ENV=production webpack --progress --watch",
     "run-fullmap": "webpack --progress --watch",
     "test": "jest --forceExit",
```

**Comment by lindy65** [comment]
Hi @SmartHoneybee,

Thanks for your feedback!

From one of our engineers on this topic:

> That target is for the build server. Devs should run the "run" ones that start the watcher. The build log is a bunch of output anyway, I would rather have all the info I need to debug something rather than not having that info on Jenkins.

**Comment by SmartHoneybee** [comment]
Fair enough: I'll just continue to patch it way in my local copy. :wink:

Thanks!
