### ISSUE TITLE
[Help Wanted] [MM-9635] Remove mm_config and mm_license global state from webapp (Phase 2)

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8318]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9635)

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9584)

Following up on https://mattermost.atlassian.net/browse/MM-8589, there are a handful of remaining components and changes required to complete this effort.

You can see a set of sample PRs below:
 - https://github.com/mattermost/mattermost-webapp/pull/816
 - https://github.com/mattermost/mattermost-webapp/pull/819
 - https://github.com/mattermost/mattermost-webapp/pull/820
 - https://github.com/mattermost/mattermost-webapp/pull/821
 - https://github.com/mattermost/mattermost-webapp/pull/822
 - https://github.com/mattermost/mattermost-webapp/pull/823
 - https://github.com/mattermost/mattermost-webapp/pull/828

**Comment by jasonblais** [comment]
This is now in progress internally, so I'll close this help wanted ticket.
