### ISSUE TITLE
[4.7.0] Users were/are no longer able to switch to certain channels within our team when using the web frontend.

### ISSUE THREAD

**Issue by jvalesnet** [mattermost/mattermost-server#8328]
#### Summary
It is possible to create longer channel names (and displaynames) via API than in the web frontend.
We consider the limit in the web frontend to be some graphical css looks-nice foo only.
The API docs dont state it is unintended behavior and dont seem to mention any length limits therefore we heavily use this to automatically generate human readable channel names for all our courses and never had any issues before.

With the upgrade to 4.7.0 users were/are no longer able to switch to certain channels within our team when using the web frontend, if len(channel name) == 26.

This slipped thru our testing and after upgrading students started to complain about not being able to switch to certain channels they have been using the last semester.

#### Steps to reproduce
+ Click on a few certain channels in the left channel bar in the web browser.
+ Get redirected to town-square.

There is no problem with the android app.

#### Expected behavior
Getting to view that channel's content instead of being redirected to town-square.

#### Observed behavior (that appears unintentional) 
Since the upgrade to 4.7.0 when clicking on a channel with the name-length of exactly 26 characters, the (nginx-proxy-)server will log/return a 404 error and it seems that following that error, the web frontend will redirect to town-square.

```
"POST /api/v4/channels/advanced-internet-security/members HTTP/1.1" 404
"POST /api/v4/channels/deklaratives-problemloesen/members HTTP/1.1" 404
"POST /api/v4/channels/didaktik-in-der-informatik/members HTTP/1.1" 404
"POST /api/v4/channels/funktionale-programmierung/members HTTP/1.1" 404
"POST /api/v4/channels/informationsvisualisierung/members HTTP/1.1" 404
"POST /api/v4/channels/kommunikation-und-rhetorik/members HTTP/1.1" 404
"POST /api/v4/channels/vertrags-und-haftungsrecht/members HTTP/1.1" 404
```
We suspect some collision with private-message-"channels" as channels of any other name length dont seem to query /members and additionaly all other queries to /members in the nginx-log seem to target "userid-channels".

#### Possible fixes
Our workaround was to append the ``0`` character to the channel-name for channels with len(name) == 26, stopping the collision(?) and everything works again...
(At first we tried with ``-`` but due to a misleading error message we went into full panic mode)

Maybe you want check on what causes this and fix it more permanently than we did by teaching our channel management bot (you cant do this manually with a little under 1000 channels) to append a 0 to channels which name would end up being 26 characters long.
+ Preferably in the web frontend, as this doesnt seem to cause issues in the android App or the API.
+ ifneedbe deny the usage of exactly 26 character long channel names in API calls. (With a meaningful error message!)

**BUT please dont restrict the API to the web frontend's limits of name and displayname**
There already is a limit: the column in postgres is varchar(64) long which should still leave more than enough characters before web-servers and web-browsers start to refuse mattermost URLs due to being too long.

We heavily rely on the ability to automatically and deterministically generate human readable channel names from the university's course list. To list a few:
```
"technische-grundlagen-der-informatik-fuer-wirtschaftsinformatik"
"algebra-und-diskrete-mathematik"
"grundlagen-der-mikrooekonomie"
"algorithmen-und-datenstrukturen-2"
"einfuehrung-in-die-programmierung-2"
"programm--und-systemverifikation"
"dezentrale-automation"
"grundlagen-der-kommunikations-und-medientheorie"
"einfuehrung-in-die-kuenstliche-intelligenz"
"musikproduktion"
"didaktik-in-der-informatik"
"digital-forensics"
"fortgeschrittene-funktionale-programmierung"
"algorithmics"
"advanced-internet-computing"
"software-security"
"digital-preservation"
"betriebssysteme"
"virtual-a-a-reality"
"theoretische-informatik-und-logik"
"technische-grundlagen-der-informatik"
"theoretische-informatik-und-logik-fuer-wirtschaftsinformatik"
"analysis-2"
"security-for-systems-engineering"
"requirements-engineering-and-specification"
"verteilte-systeme"
"advanced-software-engineering"
"software-qualitaetssicherung"
"innovationsmanagement-und-marketing"
"informationsdesign-und-visualisierung"
"semi-automatic-information-and-knowledge-systems"
"statistik-und-wahrscheinlichkeitstheorie"
"algorithmen-und-datenstrukturen"
"codegeneratoren"
"machine-learning"
"grundlagen-der-kommunikations--und-medientheorie"
"interface-and-interaction-design"
"it-security-in-large-it-infrastructures"
"digital-design"
"einfuehrung-in-die-digitale-bildverarbeitung"
"semantik-von-programmiersprachen"
"deklaratives-problemloesen"
"network-engineering"
"einfuehrung-in-die-programmierung-1"
"advanced-services-engineering"
"computergraphik"
"biomedical-sensors-and-signals"
"datenmodellierung"
"fortgeschrittene-objektorientierte-programmierung"
"aufnahmeverfahren"
"assistive-technologien-1"
"verfassungs-und-verwaltungsrecht"
"visualisierung-1"
"objektorientierte-programmiertechniken"
"web-engineering"
"introduction-to-cryptography"
"basics-of-human-computer-interaction"
"introduction-to-security"
"analysis"
```
Many exceed the web frontend's limit, but as it worked without any issues so far and dont seem to contradict any docs we consider the limit in the web-frontend to be only relevant for the web-frontend - like some css stuff, that would look ugly if it got longer.

If you ever imposed the web frontend's limit on the API too (which doesnt make much sense, imho), please think of a way to automatically shorten channel names and not just deny its creation and fix existing channels... :)
+ Obviously we cannot just cut the name after n characters as this would make the courses "algorithmen-und-datenstrukturen-2" the same as "algorithmen-und-datenstrukturen", which they are defninitely not.
+ Nor can we start to maintain a long and changing set of regexes to shorten a few repetitive words like advanced, einführung, ... because people rely on the guessability of the generated channel names and some prof.s even use them on their slides, without having a mattermost account at all (as far as we know :) So we cannot afford to have this functionality broken.
+ QR-Codes or some random IDs are therefore not really an option either.

**Comment by amyblais** [comment]
Hi @jvalesnet 

Thank you for this report,
Just wanted to let you know that we are working on a 4.7.2 dot release to fix this bug. We are expecting 4.7.2 to be released this week. Ticket is open here: https://mattermost.atlassian.net/browse/MM-9654.

**Comment by lindy65** [comment]
Hi @jvalesnet,

FYI, [v4.7.2](https://about.mattermost.com/download/) has been released so I'll close this issue off here for now and you can reopen if you still experience an issue after upgrading.

The download links should be updated on the website by end of today!
