### ISSUE TITLE
An Error occurs if you try to upload 0KB attachment

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-server#8329]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
An error occurs if you try to upload 0KB attachment.
Helper.js throws an error if I try to attach an attachment 0KB in size.
Uncaught TypeError: n is not a function 		Helper.js:34

#### Steps to reproduce
1. Create a file 0KB in size - created in the OS with name but holds no data.
2. Try attaching it to a message

#### Expected behavior
The application should let me know the file is empty. 

#### Observed behavior (that appears unintentional) 
- The upload begins and then hangs and The message box and upload control become unresponsive.
- Dev tools show the error.
- Trying to cancel the upload using the "X" causes further errors in the dev console. and the message box is still unresponsive.
![attachmentbreak-0kbfile](https://user-images.githubusercontent.com/35588783/36396929-5fafe7f8-158e-11e8-9925-a8103ccc1396.PNG)

#### Possible fixes
Attaching 0KB files should be validated to prevent user error. As is the case with this ticket tracker.

**Comment by lindy65** [comment]
Hi @DHaussermann,

Thanks for the report,

I've reproduced your issue and have filed [this ticket](https://mattermost.atlassian.net/browse/MM-9656) to track...

**Comment by coderafei** [comment]
the server also crashed
and this is log
{"log":"[2018/02/21 13:56:52 UTC] [WARN] unable to prepare namespace: unable to mount sandbox system mount points: unable to mount proc: operation not permitted\n","stream":"stdout","time":"2018-02-21T13:56:52.369100589Z"}

**Comment by lindy65** [comment]
Thanks @DHaussermann @coderafei,

I'll close this issue off here for now and we can track via the ticket linked above 👍
