### ISSUE TITLE
Mattermost did not find the minimum supported version of 'go' installed.

### ISSUE THREAD

**Issue by psongpin** [mattermost/mattermost-server#8333]
#### Summary
I installed Go using homebrew and it installed v1.10 but running `make run` shows an error that I did not met the minimum requirement of 1.9.2

#### Steps to reproduce
- run `brew install go`
- run `make run`

#### Expected behavior
It should not notify me since I'm running a higher version of go

#### Observed behavior (that appears unintentional) 
<img width="802" alt="screen shot 2018-02-20 at 12 15 25 am" src="https://user-images.githubusercontent.com/26339364/36422885-d4ca90e8-1678-11e8-9670-0fab4131a9a7.png">

**Comment by SmartHoneybee** [comment]
```bash
$ echo -e "1.10\n1.9" | sort -nr
1.9
1.10
$ echo -e "1.10\n1.9" | sort -Vr
1.10
1.9
```
So, perhaps one should [switch to `sort -V`][1] (otherwise `1.9` is smaller than `1.10` and thus does not satisfy the requirements).


[1]: https://stackoverflow.com/a/24067243

**Comment by lindy65** [comment]
Thanks @SmartHoneybee!

And thank you for the pull request @gnufede!

I'll close this issue off here for now @psongpin and we can track via the PR.
