### ISSUE TITLE
[Help Wanted] [MM-9663] Return cursor to reply thread input box after deleting a reply from the right-hand sidebar

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8336]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9663)

This PR adds support returning cursor to the center channel input box after deleting a message. Propose doing the same for the right-hand side

https://github.com/mattermost/mattermost-webapp/pull/710

Repro: 

1. Post a message
2. Click the [...] menu, then "Reply" to open the right-hand sidebar, and post a reply.
3. Delete the reply you made in step 2

Expected: 

- Cursor returns to input box on right-hand sidebar for "Add a comment..." 

Observed: 

- Cursor doesn't return to input box on right-hand sidebar for "Add a comment..."

**Comment by letsila** [comment]
Hi @esethna, I am ready to work on that as a continuation of the previous [PR](https://github.com/mattermost/mattermost-webapp/pull/710)

**Comment by jasonblais** [comment]
Thanks @letsila! That would be great :)
