### ISSUE TITLE
[Help Wanted] [MM-9072] page preview renders � for non-ascii chars for charset="windows-1250"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8341]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9072)

Initial GitHub report: https://github.com/mattermost/mattermost-server/issues/8186

Summary
Some link previews are displayed incorrectly when using charset="windows-1250". Non ascii chars are replaced with �.

Steps to reproduce
1. Mattermost version 4.6.1.
2. Enable link preview and just paste this to a channel:
http://www.dsl.sk/article.php?article=20733 or https://ekonomika.idnes.cz/taxi-praha-jancura-prodej-tick-tack-dug-/ekonomika.aspx?c=A180201_222515_ekonomika_dtt

Expected behavior
Link previewed with correct encoding

Observed behavior
Non ascii chars replaced with �.

![image](https://user-images.githubusercontent.com/13119842/36486414-70a33920-16ec-11e8-8a7a-0bb6876ad25c.png)

**Comment by cometkim** [comment]
I will take this.

Have the same problem when I share a Korean news site which uses EUC-KR.

I think to change server side would be a better option than client side. it needs to check the charset in parsing page and to convert to UTF-8 if it uses something else.

**Comment by amyblais** [comment]
Hi @cometkim,

Thank you for your interest in taking this ticket! Please let us know if you have any questions about how to get started.
