### ISSUE TITLE
[Help Wanted] [MM-8971] Code Theme not saved unless other colours changed

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8342]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8971)

#### Steps
1. In Account Settings > Display > Theme, configure and save the "Mattermost Dark" theme
2. Post a ```code block``` in a channel
3. In Account Settings > Display > Theme, select "Custom Theme", then expand "Center Channel Styles" and change the "Code Theme" to something other than "Solarized Dark"
4. Observe code block
5. Observe selected theme in Account Settings > Display > Theme
6. Refresh the page
7. Observe code block

#### Expected
- Code block displays selected selected "Code Theme" immediately
- Selected theme in Account Settings > Display > Theme is "Custom theme"
- Code block displays retained selected "Code Theme" immediately after refresh

#### Observed
- Code block displays selected selected "Code Theme" immediately
- Selected theme in Account Settings > Display > Theme is "Mattermost Dark"
- Code block displays reverts to "Solarized Dark" after refresh

**Comment by samueljohnston96** [comment]
Can this issue be removed since the Jira ticket says this is closed?

**Comment by hanzei** [comment]
Good catch @samueljohnston96, closing this one.
