### ISSUE TITLE
[Help Wanted] [MM-5859] Group Messaging: Show existing group messages in the DM More list

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8347]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-5859)

Currently, the only way to find a previously created group message channel is through the CTRL/CMD+K channel switcher.

Propose adding the ability to open a previously created group message channel from the "More Direct Messages" list as well.

Example use case: Suppose Janet wants to open a group conversation with Eric, Jason and Lindsay. She goes to the Direct Messages more menu, and begins typing “eric” into the selector. She notices that in the list, there is an old group conversation containing the people she wants to talk to. She uses the arrows to navigate down to highlight the option, and clicks enter to select it. 

![image](https://user-images.githubusercontent.com/13119842/36498466-58f60008-170c-11e8-9b59-990b3b844477.png)

Note that the number icon will need to be styled depending on the theme colors, so should be created with html.

This adds “Eric”, “Jason”, and “Lindsay” to the search bar. 
	
![image](https://user-images.githubusercontent.com/13119842/36498457-54e5d8d0-170c-11e8-92ff-de07a462f098.png)

She then clicks “Enter” again to open the conversation. The previous group conversation is added to her Direct Message sidebar, and the past conversation history is still visible in the group message.

**Comment by pradeepmurugesan** [comment]
I would like to work on this... 👍

**Comment by pradeepmurugesan** [comment]
@jasonblais @esethna I have ignore the following, thinking it can be done in the next iteration.

1. I open the more direct messages dialog
2. filter and click on a group message option
3. the users in that group gets added 
4. the same group message option still comes in the suggestion list. 

though, clicking on the same has no effect. i.e won't add the users again.

Kindly let me know if filtering the "group message channels" from the suggestion list is critical.

**Comment by jasonblais** [comment]
Thanks @pradeepmurugesan! Can you add the note to the PR as well, so the PR reviewers will be aware of it?
