### ISSUE TITLE
Slack import: duplicate messages

### ISSUE THREAD

**Issue by WGH-** [mattermost/mattermost-server#8348]
#### Summary
Sometimes, when importing Slack exports through the web interface, messages are duplicated.

#### Steps to reproduce
I'm using clean Docker image `mattermost/platform` (Mattermost 4.7.1, Build Hash: a9d4c7d4c1f6398bebba732d07108fe30ddd6319, Build Date: Sat Feb 17 00:47:16 UTC 2018) for every import attempt.

My Slack workspace is relatively large, it contains more than 30k messages. Archive with attachments (obtained with [this tool](https://github.com/grundleborg/slack-advanced-exporter)) weighs 145 MB.

So, I start the Docker image, navigate to http://172.17.0.2:8065/ (for some reason, `--publish 8065:80` doesn't work for me), create new empty team in Mattermost, raise the limit of users per team, and upload the zip file through the web interface.

#### Observed behavior (that appears unintentional) 
When importing through the web interface, there's a great chance (in fact, I think I never managed to import archive without messages being duplicated) that messages will be duplicated. Usually they're only duplicated twice, but on one occasion there were 9 copies of each message. 

#### Possible fixes
I don't have any ideas why this happens, but I have a couple of observations.

First, it seems to never happen when importing through the CLI (`./bin/platform import slack ...`).

Pruning the history a bit by opening archive and removing JSONs with old posts will result in archive that imports correctly. So this issue likely depends on the size of the archive.

I carefully read the log when messages where duplicated 9 times, and noticed an interesting pattern. At the end of Slack import, Mattermost purges its caches (https://github.com/mattermost/mattermost-server/blob/c5e8cb25caa39ed018ede5270e1566e8f7448396/app/slackimport.go#L682), which results in a logged message (`[2018/02/21 17:02:07 UTC] [INFO] Purging all caches`). In the log these line repeated exactly 9 times, and after each one (except the last) the same warnings about some user missing e-mail were logged. It looks as if, for some reason, the archive was processed 9 times in a row.

As of import report, it only included messages from the "last" import attempt, i.e. all users and all channels were merged with existing ones.

**Comment by WGH-** [comment]
Forgot to mention one import thing: you'll need to add user e-mails to the archive using this grundleborg/slack-advanced-exporter#5 (not yet merged).

Slack exports don't contain e-mails addresses any more (#8081), and if the archive doesn't contain addresses, the issue will never manifest. The reason is Mattermost Slack import code ignores duplicate users on import if they have different e-mail addresses. If user has no e-mail during the import, Mattermost will generate random placeholder e-mail, which will never match the one generated during the previous import attempt.

**Comment by grundleborg** [comment]
So I've seen a bug like this before, but never managed to pin it down. Thanks very much for the detailed investigation @WGH- 

It's definitely interesting that it doesn't trigger if the email addresses are missing.

**Comment by lindy65** [comment]
Thanks for the report @WGH-,

I've created a [ticket](https://mattermost.atlassian.net/browse/MM-9692) for us to investigate so I'll close this issue off here for now and we can track via the ticket :)
