### ISSUE TITLE
BUG: in chat, clicking on a username -> "Send Message" link, redirects to default team channel

### ISSUE THREAD

**Issue by rilian** [mattermost/mattermost-server#8356]
#### Summary
in chat, clicking on a username, then "Send Message" link redirects to default Team channel

#### Steps to reproduce
*Environment: MacOS 10.13.2, Mattermost desktop, Version 4.0.0 (4.0.0.43)*

Open any active chats
Click on any person that did a message
See popup block with Avatar, nickname, and a `Send Message` link
<img width="255" alt="_scr_ 2018-02-23 at 12 28 57" src="https://user-images.githubusercontent.com/155563/36589770-2858babe-1895-11e8-9a89-8d5aaa2aecdc.png">
Click Send Message

#### Expected behavior
You are redirected to a direct message with that person

#### Observed behavior (that appears unintentional) 
You are redirected to a default team channel

#### Possible fixes
`¯\_(ツ)_/¯`

**Comment by SmartHoneybee** [comment]
This sounds like #8310 for the desktop client.

@rilian, are you able to reproduce that with a supported browser:
* on your server (What's your Mattermost version?)
* on https://pre-release.mattermost.com/

If not, this might be a desktop client bug. In that case I'd suggest you fill an issue [there][1].

[1]: https://github.com/mattermost/desktop

**Comment by rilian** [comment]
@SmartHoneybee 

1) i can reproduce it in our Mattermost installation in Firefox browser .. 
2) cannot reproduce in https://pre-release.mattermost.com/ in browser.
3) cannot reproduce in Mattermost client on https://pre-release.mattermost.com/ server

Looks like it is fixed. We'll wait for a new version..
