### ISSUE TITLE
v4.7.2 reports as version v4.7.1

### ISSUE THREAD

**Issue by ryantm** [mattermost/mattermost-server#8358]
#### Summary
v4.7.2 reports as version v4.7.1 in "About Mattermost".

#### Steps to reproduce
Build v4.7.2 server from GitHub release, go to the "About Mattermost", look at the version

#### Expected behavior
It shows "Version: 4.7.2"

#### Observed behavior (that appears unintentional) 
It shows  "Version: 4.7.1"

#### Possible fixes
I'm not sure if it's worth fixing, but I wanted to point it out.

**Comment by jasonblais** [comment]
@ryantm This is because the DB version is 4.7.1. So I believe the version number shows `4.7.1 (4.7.2)`

This is not obvious, I agree. We created a ticket to only report the server version number in that dialog https://mattermost.atlassian.net/browse/MM-9696

**Comment by ryantm** [comment]
Good to know! Our mattermost builder for nixpkgs must have an issue, because it looks like "Version: 4.7.1 ()" for me.

**Comment by SmartHoneybee** [comment]
@ryantm, have a look at the `BUILD_NUMBER` variable in the `Makefile`.

**Comment by ryantm** [comment]
@SmartHoneybee Thanks; I was able to use BUILD_NUMBER to specify the build version. 

@jasonblais Why is the BUILD_NUMBER not part of the source release?

**Comment by jasonblais** [comment]
Usually the version number is reported as `Database Version (Build Number)`. So in your case the build number should have been 4.7.2. Not sure why it's blank for you

**Comment by ryantm** [comment]
@jasonblais It's blank because the build recipe for [Mattermost on nixpkgs](https://github.com/NixOS/nixpkgs/blob/cf4c07734364e7e59414f486381360b42a9f88ea/pkgs/servers/mattermost/default.nix) does not supply the `BUILD_NUMBER` expected by the server. I am fixing that recipe; but I'm wondering why the build number isn't included inside the source release.

I downloaded the 4.7.2 release tarball from GitHub and grep'd for "4.7.2" and that string does not appear in archive. Whoever is doing the binary releases at Mattermost must be externally specifying the BUILD_NUMBER variable when invoking GNU make. Any idea why the BUILD_NUMBER is not part of the source release?

**Comment by jasonblais** [comment]
@ryantm not sure, have touched base with our engineers about it. Thanks for calling it out!

**Comment by jasonblais** [comment]
@ryantm it's because the build number is dynamic for dev releases. It's passed in by the build server
