### ISSUE TITLE
"Send Message"(username panel) redirecting to Town-square

### ISSUE THREAD

**Issue by thiyagaraj** [mattermost/mattermost-server#8365]
#### Summary
Clicking on a username in any channel results in a small overlay that has a "Send Message" link, this would allow us to private-message a user. Currently that is just loading the Town-square channel

#### Steps to reproduce
Mattermost v4.7.0 (Click on any username and then click on "Send Message" in the resulting overlay)
![image](https://user-images.githubusercontent.com/167320/36619639-8ac955be-18bd-11e8-9ff6-3ee43c628fd0.png)

#### Expected behavior
Private message window opens to message the username selected

#### Observed behavior (that appears unintentional) 
Cancels overlay and loads the Town Square channel

#### Possible fixes
Didn't debug yet

**Comment by jasonblais** [comment]
Hey @thiyagaraj - that issue was fixed in v4.7.2 which was released today and available on our download page: https://about.mattermost.com/download

**Comment by thiyagaraj** [comment]
Oops, thank you @jasonblais , I did check the release notes before filing this and didnt see this explicitly called out, I'll close this and will upgrade to 4.7.2, thank you!

**Comment by jasonblais** [comment]
@thiyagaraj Good catch, I'll add it to the release note as well
