### ISSUE TITLE
Clicking on member name to view past msg says 'no results found'

### ISSUE THREAD

**Issue by ssatyak** [mattermost/mattermost-server#8368]
#### Summary
From the reply comment statement, clicking on the member name to view the original post, system says 'No results found. Try again?'. However, the member name is present in the members list.

#### Steps to reproduce
1. Signup in http://demo.mattermost.com and select a channel
2. From the list of the existing messages, choose any comment and hover the mouse towards the right side.
3. Click on the more options [...] and then click on reply
4. Type any message as reply to the chosen comment
5. You can see your message as recent message. Click on the member name from that recent comment.	
Commented on <member_name>'s message: <message>
6. In the search bar at top right, the member_name is present but the search results show 'No results found. Try again?'

7. Click on the members tab which is present to the left side of the search bar .
8. Click on view members and then in the search give the name of the above member.
9. You can see that member name in the list.

#### Expected behavior
When searching with the member_name, system should display all the messages of that post as it is displaying when searching with the message name.

#### Observed behavior (that appears unintentional) 
Pls see the attached screen shot

#### Possible fixes
NA
![search_noresult_member_name](https://user-images.githubusercontent.com/22347144/36677379-f838a472-1adb-11e8-9223-3861ccb1ba5c.png)

**Comment by SmartHoneybee** [comment]
So, you'd expect a search for `from:username` instead of searching for messages containing the string `username`?

Something similar to the following might do the trick (react is not my strong suit):
```patch
diff --git a/components/post_view/post_body/post_body.jsx b/components/post_view/post_body/post_body.jsx
index 00484fe..93fd155 100644
--- a/post_body.jsx
+++ b/post_body.jsx
@@ -152,7 +152,7 @@ export default class PostBody extends React.PureComponent {
                 name = (
                     <a
                         className='theme'
-                        onClick={PostActions.searchForTerm.bind(null, username)}
+                        onClick={PostActions.searchForTerm.bind(null, 'from:' + username)}
                     >
                         {username}
                     </a>
```

**Comment by lindy65** [comment]
Thanks for the feedback @ssatyak,

If you're looking for the feature `SmartHoneybee` describes above, it is not yet implemented in the system.  

Feel free to create a feature suggestion on our [feature forum](https://mattermost.uservoice.com/forums/306457-general) where you and others can up-vote the increase it's popularity.

**Comment by lindy65** [comment]
@ssatyak - do you perhaps have a link to the feature request you created on the forum that we can link back to this issue for continuity?

**Comment by lindy65** [comment]
Hi @ssatyak,

I'll close this off here for now as there has not been any feedback so we're assuming it's no longer an issue...
