### ISSUE TITLE
Previous search text remains in the search bar

### ISSUE THREAD

**Issue by ssatyak** [mattermost/mattermost-server#8369]
#### Summary
Upon clicking the member_name, from the reply comment statement, the text bar displays the member_name. After that upon clicking on the message on any other comment statement from other member, search results display the correct message and the member names. But search bar still has the previous member_name.

#### Steps to reproduce
1. Signup in http://demo.mattermost.com and select a channel
2. From the list of the existing messages, choose any comment and hover the mouse towards the right side.
3. Click on the more options [...] and then click on reply
4. Type any message as reply to the chosen comment
5. You can see your message as recent message. Click on the member name from that recent comment.
Commented on <member_name>'s message:
6. Make a note of the text displayed in the search bar.
7. Now choose any other message thread and click on the message instead on the member_name.
Commented on <member_name>'s message: <actual_message> --> click on actual_message.
8. Verify the search results and they are appropriate.
9. Now verify the search bar. It still displays the same member_name as in step 6 above.

#### Expected behavior
The search bar should either display the actual_message that was clicked [step 7] or should be blank. It should not retain the previous member name in the latest search.

#### Observed behavior (that appears unintentional) 
Pls see the attached screenshot

#### Possible fixes
NA for the user
![previous_text_retains](https://user-images.githubusercontent.com/22347144/36678536-093c8ee8-1adf-11e8-9eed-dcb674be8044.png)

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above 👍
