### ISSUE TITLE
Mobile - iOS: Edit Channel Name does not display updated name until channel is reselected

### ISSUE THREAD

**Issue by mattrampolla** [mattermost/mattermost-server#8372]
#### Summary
When editing a Channel's Name, on iOS (App Version 1.7.0 Build 87), the name change is registered at the top of the start of the channel -- "Beginning of [channelName]" and "This is the start of the [channelName] channel...".  The change is not updated in the Channel Name Bar at the top of the screen, until the channel drawer is opened and the channel is reselected.

#### Steps to reproduce
1. Login on iOS, with App Version 1.7.0 Build 87
2. Select a channel
3. Select the channel's name, from the blue Channel Name Bar at the top of the screen
4. Select "Edit Channel"
5. Edit the Channel Name
6. Select "Save"
7. Verify a system message appears in the channel, indicating the name change
8. Scroll to the beginning/start of the channel, if it is not a new channel and note the text "Beginning of [name] has been updated, as well as the info text underneath, "This is the start of the [name] channel..."
9. Note the channel's name, at the blue Channel Name Bar at the top of the screen has not updated
10. Open the Channel Drawer (select hamburger menu or swipe right)
11. Reselect channel (with the updated name)

#### Expected behavior
When a Channel Name is edited, the change should update in all Channel Name locations, especially the Channel Name Bar.

#### Observed behavior (that appears unintentional) 
When the Channel Name is edited, the blue Channel Name Bar at the top of the screen does not update until the channel is re-opened.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by SmartHoneybee** [comment]
Sounds like you might want to [report an issue with `mattermost-mobile`][1].

[1]: https://github.com/mattermost/mattermost-mobile/issues/new

**Comment by mattrampolla** [comment]
Closing.  

Issue reported in mattermost-mobile as https://github.com/mattermost/mattermost-mobile/issues/1472.
