### ISSUE TITLE
Mobile - iOS: Preview is broken - 'Unexpected error occurred' and forces Relaunch of app

### ISSUE THREAD

**Issue by mattrampolla** [mattermost/mattermost-server#8375]
#### Summary
When tapping an JPG image, to preview, the app returns an "Unexpected error occurred" message and forces the user to select "Relaunch".  
The following message and stack trace were recorded when attempting to preview a jpg: 
Message: 
`n.refs.toolTip.hideMenu is not a function. (In 'n.refs.toolTip.hideMenu()', 'n.refs.toolTip.hideMenu' is undefined)`

Stack trace:
`hide@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:1408:777
hideOptionsContext@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:1334:1042
handlePreviewPress@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:1337:967
handlePreviewPress@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:1338:726
touchableHandlePress@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:173:1177
touchableHandlePress@[native code]
_performSideEffectsForTransition@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:165:8280
_performSideEffectsForTransition@[native code]
_receiveSignal@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:165:7067
_receiveSignal@[native code]
touchableHandleResponderRelease@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:165:4740
touchableHandleResponderRelease@[native code]
y@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:1204
invokeGuardedCallback@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:467
invokeGuardedCallbackAndCatchFirstError@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:582
H@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:2563
D@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:3325
forEach@[native code]
F@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:3122
Ne@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:14270
/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:14828
batchedUpdates@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:60045
_e@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:14043
He@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:14814
receiveTouches@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:46:15357
value@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:18:3471
/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:18:956
value@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:18:2898
value@/var/containers/Bundle/Application/6271716B-BEB6-43ED-9F55-8841C9CF72B8/Mattermost.app/main.jsbundle:18:928
value@[native code]
`

#### Steps to reproduce
1. Login on iOS (App Version 1.7.0 Build 87)
2. From any channel with a jpg, gif, mp4, mov, or doc tap the file to preview
3. Observe error message

#### Expected behavior
Tapping an approved file type (see https://mattermost.atlassian.net/browse/RN-15 for reference), will display a preview of the file. 

#### Observed behavior (that appears unintentional) 
Tapping any file to preview returns "Unexpected error occurred" and requires the user to "Relaunch".

**Comment by SmartHoneybee** [comment]
(Similar to #8372)
Sounds like you might want to [report an issue with `mattermost-mobile`][1].

[1]: https://github.com/mattermost/mattermost-mobile/issues/new

**Comment by mattrampolla** [comment]
Closing.

Issue reported in mattermost-mobile as https://github.com/mattermost/mattermost-mobile/issues/1473
