### ISSUE TITLE
API Attachment posts not longer collapsed

### ISSUE THREAD

**Issue by HLeithner** [mattermost/mattermost-server#8376]
#### Summary
It seams since Mattermost 4.7.2? API Posts using the attachment syntax are not longer collapsed. Or did I missed a setting?

#### Steps to reproduce
Create a webhook and post a message as attachment with a long content.

#### Expected behavior
After x characters you get [...] to expand the message

#### Observed behavior (that appears unintentional) 
The attachment is always "open" and its not possible to close it.

**Comment by hmhealey** [comment]
Hi @HLeithner,

Thanks for the report. I'm also seeing it on our pre-release server, so something definitely changed around this. I've filed a Jira ticket [here](https://mattermost.atlassian.net/browse/MM-9726) if you'd like to track the issue in more detail there

**Comment by HLeithner** [comment]
thx, it would be cool to have this as an option :-)

**Comment by lindy65** [comment]
Thanks @HLeithner,

I'll close this issue off here for now and we can track via the ticket that `hmhealey` linked above 👍
