### ISSUE TITLE
opening permalink scrolls to bottom

### ISSUE THREAD

**Issue by tmu-sprd** [mattermost/mattermost-server#8384]
#### Summary
opening permalink often scrolls to bottom of channel

#### Steps to reproduce
Go to any channel, scroll up to an older message and copy permalink.
Access the permalink with any browser.
When the channel is loaded and the message is displayed, it often scrolls down to the bottom of the channel.

[Imgur: a GIF showing the behavior at pre-release.mattermost.com](https://imgur.com/ZIW6WTL)

#### Expected behavior
Scrolling stops at the permalinked message.

#### Observed behavior (that appears unintentional) 
The browser scrolls to the end of the channel.

#### Possible fixes
Don't know.

**Comment by koxen** [comment]
this is a well known issue in core team; not sure when it will be fixed since scrool have been heavily refactored lately(fixed some bugs, added others...)

**Comment by koxen** [comment]
https://mattermost.atlassian.net/browse/MM-8994

**Comment by tmu-sprd** [comment]
Thank you for the link @koxen.
When there is a bug ticket already, I close this one.

My best
