### ISSUE TITLE
"Mozzilla" typo in templates/unsupported_browser.html

### ISSUE THREAD

**Issue by SmartHoneybee** [mattermost/mattermost-server#8385]
#### Summary
In the file `templates/unsupported_browser.html` Mozilla is misspelled.
![image of typo](https://user-images.githubusercontent.com/18035422/36795012-35c4fbde-1ca2-11e8-86c1-0d5fb544cadb.png)

#### Steps to reproduce
Visit `pre-release.mattermost.com` with user agent `Mozilla/5.0 (X11; Linux i686) AppleWebKit/601.1 (KHTML, like Gecko) Version/8.0 Safari/601.1 Ubuntu/15.10 (3.16.3-1ubuntu1) Epiphany/3.16.3`.

**Comment by cpanato** [comment]
pr to fix: https://github.com/mattermost/mattermost-server/pull/8395

**Comment by cpanato** [comment]
good catch @SmartHoneybee thanks!

**Comment by lindy65** [comment]
Thanks @SmartHoneybee @cpanato :)

I'll close this issue off here for now then...
