### ISSUE TITLE
Batch push notifications like email

### ISSUE THREAD

**Issue by koxen** [mattermost/mattermost-server#8388]
#### Summary
Currently push notifications are very unreliable, when set to send only on "away/offline" status.
This might cause you to miss notifications in some cases(I think mostly when you are on your phone; sometimes online status tends to change from away to online, or not change to away when you are away from computer).
The solution would be to send the push to mobile if you didn't mark the channel as read within i.e. one minute, five minutes.
I am pretty sure that either Slack or Discord is following this model.
I know that email notifications are a thing but we have them turned off for security reasons.
And the code for email notifications batching that is currently in mattermost-server is a great base to batch push notifications - the hardest work is already done here.

**Comment by lindy65** [comment]
Hi @koxen,

Thanks for your feedback,

Agree this would be a very nice feature to have 👍 

Could we have your help adding a feature request to our [forum](https://mattermost.uservoice.com/forums/306457-general) where you and others can up-vote it to increase it's popularity?  If you do make a feature request, could you post back a link to this issue for continuity?

Thanks!

**Comment by lindy65** [comment]
Hi @koxen,

Did you perhaps have a chance to open a feature request on the [forum](https://mattermost.uservoice.com/forums/306457-general)?  If so, could you post a link back to this issue for continuity please?

**Comment by lindy65** [comment]
As we haven't heard back from you we'll assume this is no longer an issue for you so we'll close this off here for now.
