### ISSUE TITLE
Incoming Webhooks: broken parsing of certain special characters

### ISSUE THREAD

**Issue by WGH-** [mattermost/mattermost-server#8392]
#### Summary
When sending message through Incoming Webhook, certain characters are interpreted incorrectly, resulting in broken message.

#### Steps to reproduce
This is a somewhat minimized test case. More "lifelike" test case is attached below.
```python

#!/usr/bin/env python3

import json
import requests

foo = '`<>|<>|`'

requests.post('https://REDACTED/hooks/REDACTED', data={'payload': json.dumps({"text": foo})})
```

#### Expected behavior
`<>|<>|`

#### Observed behavior (that appears unintentional) 
`[<](>)|`

#### Possible fixes
This is likely caused by Slack compatibility code (https://docs.mattermost.com/developer/webhooks-incoming.html#translate-slack-s-proprietary-data-format-to-mattermost), as this issue never manifests if you enter this message manually.

More sensible test case, where I originally noticed it, is as follows (should be inside triple backticks):

```
commit bc95839e4a430ace453e8b209a3723c000c1729a
Author: foo <foo@example.org>
Date:   Thu Mar 1 19:46:54 2018 +0300

    commit message 2 

 test | 1 +
 1 file changed, 1 insertion(+)

commit 5df78b7139b543997838071cd912e375d8bd69b2
Author: foo <foo@example.org>
Date:   Thu Mar 1 19:46:48 2018 +0300

    commit message 1

 test | 3 +++
 1 file changed, 3 insertions(+)
```
rendered like this
```
commit bc95839e4a430ace453e8b209a3723c000c1729a
Author: foo [ 1 +
 1 file changed, 1 insertion(+)

commit 5df78b7139b543997838071cd912e375d8bd69b2
Author: foo <foo@example.org](foo@example.org>
Date:   Thu Mar 1 19:46:54 2018 +0300

    commit message 2 

 test )
Date:   Thu Mar 1 19:46:48 2018 +0300

    commit message 1

 test | 3 +++
 1 file changed, 3 insertions(+)
```

**Comment by WGH-** [comment]
This is the culprit:

https://github.com/mattermost/mattermost-server/blob/51c7198d53a2fbc4c7d47b3eb308781b69bf4b51/app/webhook.go#L227-L229

https://play.golang.org/p/p6sFcnkIPT_C

**Comment by hmhealey** [comment]
Hi @WGH-,

Thanks for the report. It looks like that regex shouldn't accept pipes that are outside of the angle brackets, so it should be changed from
```
<([^<\|]+)\|([^>]+)>
```
to
```
<([^<\|>]+)\|([^>]+)>
```

I've filed a Jira ticket [here](https://mattermost.atlassian.net/browse/MM-9725) to go investigate further, but we'd also welcome a pull request in you're interested in making one.

**Comment by WGH-** [comment]
I think these sets should also exclude newlines (e.g. `<([^\n<\|>]+)\|([^\n>]+)>`), otherwise it will screw up ridiculous multi-line "links" (https://play.golang.org/p/lg9AoYMclI3)

**Comment by lindy65** [comment]
Thanks @WGH- 

This GitHub issue is noted in the above ticket so I'll close it off here for now and we can track via the ticket 👍
