### ISSUE TITLE
login.invalidPassword message may disclose information to the attacker

### ISSUE THREAD

**Issue by CoolTomatos** [mattermost/mattermost-server#8394]
#### Summary
`login.invalidPassword` message says `Your password is incorrect.`, which discloses that the entered email address is an existing one on the server, and may give information to the attacker.

#### Steps to reproduce
Version: 4.7
Entering an existing email address, but with a wrong password, and then click the `Sign in` button.

#### Expected behaviour
A warning message shows up, says `We couldn't find an account matching your login credentials.`

#### Observed behavior (that appears unintentional) 
A warning message shown up, said `Your password is incorrect.`

#### Possible fixes
Change the below line from [`mattermost-webapp/i18n/en.json`](https://github.com/mattermost/mattermost-webapp/blob/f7a5ee1fb3a2f66ed2e93a7fcccfcbe5f022f8b2/i18n/en.json#L1874)
>     "login.invalidPassword": "Your password is incorrect.",
into 
>     "login.invalidPassword": "We couldn't find an account matching your login credentials."
and change it accordingly for all languages.
- - - - - - - -
Or use `login.login.userNotFound` instead of `login.invalidPassword` in 
[`mattermost-webapp/components/login/login_controller/login_controller.jsx`](https://github.com/mattermost/mattermost-webapp/blob/f7a5ee1fb3a2f66ed2e93a7fcccfcbe5f022f8b2/components/login/login_controller/login_controller.jsx#L218-L229)

**Comment by SmartHoneybee** [comment]
Probably related: https://github.com/mattermost/docs/issues/885

**Comment by lindy65** [comment]
Thanks for your feedback @CoolTomatos,

`SmartHoneybee` is correct regarding the related issue linked above so I'll close off this issue here for now...
