### ISSUE TITLE
Change wording of messages indicating that push notifications are disabled.

### ISSUE THREAD

**Issue by MarkMaldaba** [mattermost/mattermost-server#8396]
_[Note, this is being reported in the context of the Android app, but I suspect it applies to all the Mattermost clients.]_

The wording of text when push notificiations are disabled is confusing to users.

Currently the text indicates that the system administrator has disabled the feature, which is not the case.  Push notifications are disabled by default and require slightly more knowledge to set up and configure than other features in Mattermost, and so I suspect it is not uncommon for this feature to be left disabled, particularly for intranet installations where most users will be using the desktop client.

The text should therefore indicate that they are a feature that has not been enabled, rather than a feature that has been disabled, which implies that there is functionality that has been arbitrarily removed.

Please can this text be reworded, for example by changing "disabled by system administrator" to "not currently enabled for this server".

(Note that there may be other instances of opt-in features that need similar rewording, e.g. e-mail.  I have not checked.)

**Comment by lindy65** [comment]
Hi @MarkMaldaba,

Good point!  Thanks for your feedback :)

I've created [this ticket](https://mattermost.atlassian.net/browse/MM-9721) for discussion by the team...

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the ticket linked above 👍
