### ISSUE TITLE
Duplicate keys "max-nested-callbacks" in mattermost-webapp/.eslintrc.json

### ISSUE THREAD

**Issue by CoolTomatos** [mattermost/mattermost-server#8397]
#### Summary
In [.eslintrc.json](https://github.com/mattermost/mattermost-webapp/blob/f7a5ee1fb3a2f66ed2e93a7fcccfcbe5f022f8b2/.eslintrc.json#L78-L79) there are duplicate keys `max-nested-callbacks`

```json
78    "max-nested-callbacks": [1, {"max":1}], 
79    "max-nested-callbacks": [2, {"max":2}],
```

**Comment by hmhealey** [comment]
Hi @CoolTomatoes, thanks for the report. That looks like it must've been from a merge conflict that was resolved incorrectly. If you'd like to submit a PR to fix that, we'd gladly take one.

**Comment by CoolTomatos** [comment]
@hmhealey but I don't know which max value you prefer, should it be 1, or should it be 2

**Comment by lindy65** [comment]
Thanks for the PR @CoolTomatos 👍 

I'll ask `hmhealey` for a response to your question :)

**Comment by CoolTomatos** [comment]
Thank you @lindy65 ,
`jespino` has already replied me in https://github.com/mattermost/mattermost-webapp/pull/895
