### ISSUE TITLE
Cannot get model.Post with props by rpcplugin.GetPost

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-server#8401]
#### Summary

I cannot get model.Post instance with props (e.g. `PostActionIntegration`) by using rpcplugin.GetPost.

#### Steps to reproduce
1. Write plugin code
  - [Sample Plugin](https://gist.github.com/kaakaa/7bcb52dc784e73637584a07e59bbaaf9)
2. Buildinng, Archiving with `plugin.json`, Uploading, and Activating plugin
3. `curl https://localhost:8065/plugins/sample?post_id=${POST_ID}`

#### Expected behavior

Can get response successfuly.

```
{"update":null,"ephemeral_text":"SUCCESS: hogehoge"}
```

#### Observed behavior (that appears unintentional) 

The following error message was responded.

```
{"update":null,"ephemeral_text":"ERROR: RemoteAPI.GetPost: plugin.rpcplugin.invocation.error, err=reading body EOF"}
```

And, the following error log was outputted in server side log
```
2018/03/04 00:30:51  rpc: gob error encoding body: gob: type not registered for interface: []interface {}
```

#### Possible fixes

I added `gob.Register([]interface{}{})` to func `init`.
https://github.com/mattermost/mattermost-server/blob/master/plugin/rpcplugin/api.go#L611

Then, `curl` response and server side log changed as follows.

* `curl` response
  * `{"update":null,"ephemeral_text":"ERROR: RemoteAPI.GetPost: plugin.rpcplugin.invocation.error, err=reading body gob: name not registered for interface: \"[]interface {}\""}`
* server side log
  * `2018/03/04 10:07:30 rpc: gob error encoding body: gob: type not registered for interface: map[string]interface {}`

Finaly, I understand that I need to regist `[]interface{}` and `map[string]interface{}` by `gob.Register`  in both of server side (in `rpcplugin.init` function) and plugin side (in e.g. `OnActivate`).
I think that it's hacky to write gob.Regist in plugin side.

Are there any other way to get model.Post instance with props?

**Comment by ccbrown** [comment]
We'll just need to add those types here, where we already do this:

https://github.com/mattermost/mattermost-server/blob/4c17bdff1bb871fb31520b7b547f584c53ed854f/plugin/rpcplugin/api.go#L612

I'm sure we can fit this into the 4.8 release next week.

Bug ticket here: https://mattermost.atlassian.net/browse/MM-9731

**Comment by lindy65** [comment]
Thanks @ccbrown - I'll close off this issue here and we can track via the ticket linked above 👍
