### ISSUE TITLE
KaTeX corrupts Webapp for incorrect syntax

### ISSUE THREAD

**Issue by enuit** [mattermost/mattermost-server#8402]
#### Summary
When I miss a closing "}" in Latex syntax a JavaScript error is thrown the WebApp shows no UI, just a blank page.

#### Steps to reproduce
With the Demo Server https://oss.mattermost.com/ or the latest Docker https://github.com/mattermost/mattermost-docker/commit/4e242572f1b54b3969bcc8e204fe8e6ee7aea7c2 start a Chat and type

```
```latex
a_{x
```_
```
(Ignore the last _, its only there to show the closing `)
On Sending the page will turn white and be unusable, the Error can not be corrected as no UI is available. 

#### Expected behavior
Incorrect syntax/ Errors in KaTeX should not harm the overall WebApp. Wrong Latex syntax should be rendered without parsing.

#### Observed behavior (that appears unintentional) 
When visiting a chat room with incorrect syntax the console shows:
```
ParseError: KaTeX parse error: Expected '}', got 'EOF' at end of input: a_{a
```
This happens for me on Firefox (58.02) and Chrome (64).

The Version of KaTeX used due to the package.json in mattermost-webapp is
**0.9.0-beta**. When I directly use the 0.9.0-beta1 provided by KaTeX and include that in my Website, I can't reproduce the failure. Latex simply remains unparsed.

#### Possible fixes
As I can't reproduce the problem when using KaTeX directly in an Document, I don't see why it kills the mattermost webapp.

**Comment by octomike** [comment]
So this shuts up every channel in mattermost right now? Holy..

**Comment by enuit** [comment]
It shuts up every channel where it is rendered, yes.

**Comment by jespino** [comment]
Hi, I'm investigating it. Looks like a problem with Katex. We are using `throwOnError: false` option, so It shouldn't raise a `ParseError`.

An example to make it fail is:

```javascript
var katex = require('katex');
katex.renderToString('a_{x', {throwOnError: false, displayMode: true})
```

I going to read a bit of Katex code to try to find the problem.

**Comment by jespino** [comment]
After investigating a bit, looks like `throwOnError` is a confusing name, because only handle certain cases. Looks like we have to handle that kind of parse errors.

**Comment by lindy65** [comment]
Thanks @jespino !

**Comment by octomike** [comment]
Any recommendations for a quick fix?

**Comment by jespino** [comment]
@octomike The workaround would be, go to any channel (without latex text on int), go to your user settings > Advanced > Enable post formating, and disable it. Go to the channel with the bad formated latex, fix it (or delete the entire message). Then, back to your account settings, and re-enable the post formating.

**Comment by lindy65** [comment]
As the PR to fix this has been merged, I'll close off this issue here for now.

**Comment by amyblais** [comment]
Hello @enuit,

Thank you for reporting this issue!

We have included a fix for this issue you discovered in our 4.7.3 release, and would like to recognize you in our [security research hall of fame](https://www.mattermost.org/responsible-disclosure-policy/) and our upcoming security update email, which acknowledge those who helped discover security issues.

We would also love to send you a Mattermost mug as a thank you. If you're interested, you can sign up to our public Mattermost instance at http://pre-release.mattermost.com/, and I can direct message you for contact details. Just let me know your username here if you've signed up.

**Comment by enuit** [comment]
Hey,
that would both be great. 
My username in the chat is also enuit :)

**Comment by lindy65** [comment]
Thanks @enuit,

I've direct messaged you on http://pre-release.mattermost.com/ 👍
