### ISSUE TITLE
Clicking a permalink inside the iOS app triggers safari instead of going directly to the post

### ISSUE THREAD

**Issue by CoolTomatos** [mattermost/mattermost-server#8403]
#### Summary
Clicking a permalink inside the iOS app triggers safari, instead of going directly to the post.

#### Steps to reproduce
Version: 1.6.1
Operation System: iOS 11.2.6
Device: iPhone 7 Plus

Click a permalink shared by other users from the iOS app.

#### Expected behaviour
Goes directly to the post within the app

#### Observed behaviour
Safari opened and asked me to sign in that mattermost server to view the post.

**Comment by lindy65** [comment]
Hi @CoolTomatos 

Thanks for your feedback :)

We have [this ticket](https://mattermost.atlassian.net/browse/MM-9374) open to resolve the issue.  A PR has been submitted so it should be in the next version update of the app.
