### ISSUE TITLE
Platform command to change user email address

### ISSUE THREAD

**Issue by torgeirl** [mattermost/mattermost-server#8404]
Sysadmins should be able to edit the email address of an user. There is no option for this from either the system console nor [the platform command line commands](https://docs.mattermost.com/administration/command-line-tools.html#platform-user).

There's already an unsolved issue on user editing from the system console ([MM-8490](https://mattermost.atlassian.net/browse/MM-8490)), but awaiting its implementation a new CLI command should be added.

I would suggest `platform user email {user} {new email address}`.

**Comment by lindy65** [comment]
Hi @torgeirl,

Thanks for your feedback, I've made [this ticket](https://mattermost.atlassian.net/browse/MM-9720) for discussion by the team 👍

**Comment by torgeirl** [comment]
@lindy65: thank you :+1:

**Comment by cpanato** [comment]
@lindy65  I can work on this.

**Comment by lindy65** [comment]
Thanks @cpanato -  appreciated 😊

**Comment by lindy65** [comment]
Hey @cpanato - do we have a ticket or PR that we can link to this issue for continuity?

**Comment by cpanato** [comment]
@lindy65 I'm did not get your question. I dont have this issue implemented yet. I will work on that later this week

**Comment by lindy65** [comment]
Thanks @cpanato 👍🏻

No rush, I was just asking whether there is a Jira ticket for this issue? Or is it not required?

**Comment by cpanato** [comment]
@lindy65  is this one: https://mattermost.atlassian.net/browse/MM-9720?

**Comment by lindy65** [comment]
🤦‍♀️ @cpanato - sorry about the confusion!  I had created the ticket above and didn't see it in my screen view when I asked about a ticket!  Sorry!

I'll close off this issue here for now and we can track via the Jira ticket linked above 👍

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-server/pull/8422
