### ISSUE TITLE
-e

### ISSUE THREAD

**Issue by MiDoTr** [mattermost/mattermost-server#8405]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by SmartHoneybee** [comment]
Hi @MiDoTr,

> `-e`

anything in particular you need help with?

Regards,
Bee

**Comment by MiDoTr** [comment]
I am sorry, I was not aware creating an issue, it was a couple of very long days ...

**Comment by SmartHoneybee** [comment]
No harm done! Thanks for the fast response.
:slightly_smiling_face:
