### ISSUE TITLE
[Help Wanted] [MM-9725] Slack compatibility code in webhooks captures incorrect text

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8407]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9725)

Originally reported on GitHub: https://github.com/mattermost/mattermost-server/issues/8392

This appears to do with the regex for Slack links looking for the first pipe while ignoring the fact that it's outside of the angle brackets. It's likely caused by [this regex](https://github.com/mattermost/mattermost-server/blob/51c7198d53a2fbc4c7d47b3eb308781b69bf4b51/app/webhook.go#L227-L229) and can probably by fixed by changing it to 
```
<([^<\|>]+)\|([^>]+)>
```
(with the > character excluded from the characters allowed between the < and the \|)

Repro steps:
1. Create an incoming webhook
2. Send a request to the webhook to post `<>|<>|`. See the attached GitHub issue for a python script that does this

Observed: The raw markdown for the post looks like `[<](>)|`
Expected: The raw markdown for the post looks like `<>|<>|`

**Comment by cpanato** [comment]
i will take this one

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-server/pull/8428
