### ISSUE TITLE
Firefox: Posts show wrong time if resistFingerprinting is enabled

### ISSUE THREAD

**Issue by M1dgard** [mattermost/mattermost-server#8419]
#### Summary
Firefox's new setting to resist [fingerprinting](https://wiki.mozilla.org/Security/Fingerprinting) [sets](https://bugzilla.mozilla.org/show_bug.cgi?id=1330890) the time zone to UTC.

#### Steps to reproduce
1. In Firefox's `about:config` enable `privacy.resistFingerprinting`.
2. Restart the browser.
3. Open Mattermost and send some messages.

#### Expected behavior
Either times are correct or the time zone is configurable.

#### Observed behavior (that appears unintentional) 
Times are displayed in UTC.

#### Possible fixes
Show a warning if the detected time zone is UTC. Add a user setting to override the time zone.

**Comment by lindy65** [comment]
Hi @M1dgard,

Thanks for the report :)

I've created [this ticket](https://mattermost.atlassian.net/browse/MM-9765) for discussion by the team as it will involve code change / feature development

**Comment by SmartHoneybee** [comment]
@M1dgard, what's your opinion on https://github.com/mattermost/mattermost-server/pull/8185 and https://github.com/mattermost/mattermost-webapp/pull/696?

**Comment by M1dgard** [comment]
@SmartHoneybee, that's great, hadn't found it while searching.

My only suggestion now would be to alert the user in some way when the detected time zone is UTC, because it's likely going to be a privacy feature. I think no-one selects "UTC" on itself as a real time zone, people in the UK e.g. should choose "Europe/London".

**Comment by lindy65** [comment]
Thanks @M1dgard,

I've noted your above comment on the ticket I opened and we'll be testing to see whether https://github.com/mattermost/mattermost-server/pull/8185 resolves this issue.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the Jira ticket and PR linked above.
