### ISSUE TITLE
[Help Wanted] [MM-9695] Add status icons on "add member to channel" and "add member to team" lists

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8425]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9695)

Original report here: https://github.com/mattermost/mattermost-server/issues/8258

#### Summary
The Add Members lists, from both Main Menu > 'Add Members to Team' and Channel name drop-down > 'Add Members' do not display the status icon on users' profile pictures.
Status icons are currently displayed on all other Members lists.

#### Steps to reproduce

1. Log in to Mattermost - Version: 4.7.0 (4.7.0-rc2)
2. Select the Main hamburger menu > Add Members to [team_name] Team 
3. View 'Add New Members To Team' list
4. Close list
5. Select any public or private channel
6. Select the Channel name dropdown, above the chat window
7. Select 'Add Members'
8. View 'Add New Members to [channel_name]' list

#### Expected behavior
- All Members lists display a status icon on a user's profile picture.  
Members lists include: Channel name drop-down > Manage (or View or Add) Members, Main hamburger Menu > Add Members to Team, and Direct Message 'More...' user list. 

#### Observed behavior (that appears unintentional) 
-  Selecting Channel name drop-down > 'Add Members' or Main hamburger Menu > 'Add Members to Team' displays a list of users, but does not display a status icon on a user's profile picture.

![add members list status icon](https://user-images.githubusercontent.com/17954664/36139707-9ff75eda-106c-11e8-97e6-d3281cb5d419.gif)

**Comment by CoolTomatos** [comment]
I would like to help you guys solve this

**Comment by lfbrock** [comment]
Pull request here - https://github.com/mattermost/mattermost-webapp/pull/957

**Comment by jasonblais** [comment]
Closing this help wanted ticket per PR above.
