### ISSUE TITLE
Korean Language: The DM notification mail will be sent with the subject is '<no value>'.

### ISSUE THREAD

**Issue by yth0625** [mattermost/mattermost-server#8427]
#### Summary
The DM notification mail will be sent with the subject is '<no value>'.

#### Steps to reproduce
Send DM to offline users who account setting is Korean.
Users who receive DM receive email notifications.

#### Expected behavior
The subject of the mail should be as shown in the image below.
![2018-03-09 16-34-25](https://user-images.githubusercontent.com/29148223/37195855-d1d20578-23b7-11e8-8815-ffefaec7b82f.png)

#### Observed behavior (that appears unintentional) 
The subject of the message is '<no value>'.
![2018-03-09 16-34-40](https://user-images.githubusercontent.com/29148223/37195858-d6138b0c-23b7-11e8-8c13-47269fdc2ade.png)

#### Possible fixes
this is Problem code line.
String of the Korean language file is different from the English language file.
id : 'app.notification.subject.direct.full'

ko : "translation": "{{.SubjectText}} on {{.TeamDisplayName}} at {{.Month}} {{.Day}}, {{.Year}}"
en : "translation": "[{{.SiteName}}] New Direct Message from {{.SenderDisplayName}} on {{.Month}} {{.Day}}, {{.Year}}"

**Comment by lindy65** [comment]
Thanks for the report @yth0625!

I've made [this ticket](https://mattermost.atlassian.net/browse/MM-9778) to fix the issue 👍

**Comment by jasonblais** [comment]
@yth0625 Would you like to help translate the string at our Translations Server? 

https://translate.mattermost.com/ko/mattermost/translate/#search=%7B%7B.SubjectText%7D%7D%20on%20%7B%7B.TeamDisplayName%7D%7D&sfields=source,target

It'll get added to v4.8 release if it's translated by Monday (March 12th) :)

**Comment by yth0625** [comment]
I translated this.
Thanks @jasonblais

**Comment by jasonblais** [comment]
Great! Thanks @yth0625 👍 

I'll close the issue. It will be resolved in Mattermost v4.8.
