### ISSUE TITLE
[Help Wanted] [MM-9771] Cursor focus doesn't return to comment box on the RHS after editing a message on the RHS by removing all of the text in the comment

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8429]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9771)

Repro steps:
1. Post a message.
2. Reply to that message.
3. On RHS, click dot [...] menu and select edit. (Edit Modal opens up).
4. On Edit modal, remove all text of a comment (leave it empty), and click Save. (Delete Modal opens up).
5. On Delete modal, confirm by clicking Delete.

Observed:
Focus is returned to center post textbox and not to RHS comment box.

Expected:
For me, I should expect it to return focus to RHS comment box.

Reported originally on this PR: https://github.com/mattermost/mattermost-webapp/pull/879#event-1512582059

**Comment by jasonblais** [comment]
Wondering if you were interested helping with this one too @letsila? :)

**Comment by letsila** [comment]
Sure. I can take care of this one.
