### ISSUE TITLE
[Help Wanted] [MM-9769] Posting a reply from preview mode leaves editor in preview mode

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8430]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9769)

#### Steps.

1. Draft a message in reply to an existing message
2. Enter preview mode
3. Click "Add Comment"

#### Expected

1. Preview mode exited, ready to type a new message

#### Observed

1. Preview mode stays on leaving an empty textbox that can't be edited until clicking `Edit message`

**Comment by CoolTomatos** [comment]
I would like to help you guys solve this!

**Comment by jasonblais** [comment]
Thanks @CoolTomatos, really appreciate it :)
