### ISSUE TITLE
mkdocs.yml can be deleted

### ISSUE THREAD

**Issue by Vorlif** [mattermost/mattermost-server#8431]
Not really a bug.

#### Summary
The root directory of the project contains the file mkdocs.yml.
I think the file is no longer needed. :)

#### Possible fixes
Delete mkdocs.yml

**Comment by Vorlif** [comment]
Yes, I will create one.

**Comment by jespino** [comment]
Great! Thanks! :smiley:

**Comment by lindy65** [comment]
Thanks for the PR @Vorlif 👍

**Comment by lindy65** [comment]
I'll close off this issue here now that the above PR has been merged...
