### ISSUE TITLE
[Help Wanted] [MM-9777] Having a custom emoji with the same name as a system emoji causes confusing behaviour in emoji picker

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8434]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9777)

Current situation:

In the UI, users are prevented from creating emoji with the same name as existing emoji. But it is possible to do through the API, and causes confusing behavior in the emoji picker (on message box and when adding a reaction).

1. Use the API to create an emoji named `croissant`
2. Click the emoji picker, either on message box or to add a reaction to a post
3. Type `croiss` in the search box to filter the emoji list

Observed: Both the system `croissant` emoji and the one you added appear in the filtered list. Clicking the one you added works to add it to the message (or as a reaction), but it is the system emoji that displays, not the one you added

Expected: Prevent creating a custom emoji with the same name as an existing emoji via the API. For custom emoji already created with the same name as a system emoji, hide the custom emoji from the emoji picker.

**Comment by gnufede** [comment]
I can take a look at this

**Comment by jasonblais** [comment]
Thanks @gnufede! :)

**Comment by santos22** [comment]
Hey @gnufede! If you have any questions, you can ping Harrison, a core contributor. Turns out the server doesn't have any knowledge of system emojis, so an easy fix for this would be to add some duplicate checking to the emoji picker. The check would basically hide any custom emojis that have the same name as a system one.
