### ISSUE TITLE
API v4 Documentation for Status/Get User Status does not match payload received.

### ISSUE THREAD

**Issue by scottliddick** [mattermost/mattermost-server#8436]
#### Summary
The [API documentation](https://api.mattermost.com/#tag/status%2Fpaths%2F~1users~1%7Buser_id%7D~1status%2Fget) for **status/get user status** does not match actual payload received from server as the active_channel property is missing.

#### Steps to reproduce
Perform an authenticated API request for /users/{userId}/status and view the response payload.

#### Expected behavior
Per API v4 documentation, the payload 
`{
  "user_id": "string",
  "status": "string",
  "manual": true,
  "last_activity_at": 0,
  "active_channel": "string"
}`

#### Observed behavior (that appears unintentional) 
`{ 
  user_id: 'wxaf11dne7bu8mn73e3r13q4ah',
  status: 'away',
  manual: false,
  last_activity_at: 1520640100796 
}`

**Comment by amyblais** [comment]
Hi @scottliddick,

Thank you for this report! 

I have created a ticket for this here for our engineers to fix: https://mattermost.atlassian.net/browse/MM-9798

**Comment by cpanato** [comment]
I can fix that @amyblais. I will assign that ticket to me

**Comment by amyblais** [comment]
Thank you @cpanato!

**Comment by cpanato** [comment]
pr: https://github.com/mattermost/mattermost-api-reference/pull/341

**Comment by lindy65** [comment]
As the PR above has been merged, I'll close this issue off here now...
