### ISSUE TITLE
Outdated instructions on Custom Emoji page

### ISSUE THREAD

**Issue by M1dgard** [mattermost/mattermost-server#8442]
The Custom Emoji page says:
> Type ':' in a message box to bring up the emoji selection menu. Other users may need to refresh the page before new emojis appear.

* The emoji selection menu is nowadays only triggered when you type ':' followed by two characters.
* New emojis appear for other users without refreshing the page. (Which is great btw! :D )

**Comment by lindy65** [comment]
Thanks for the report @M1dgard 👍 

I've created [this ticket](https://mattermost.atlassian.net/browse/MM-9821) for us to fix that help text!

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the Jira ticket linked above...
