### ISSUE TITLE
Accessibility issue - can't tell which channels are unread

### ISSUE THREAD

**Issue by pauljonesOH** [mattermost/mattermost-server#8443]
I'm logging some accessibility issues in Mattermost that are effecting the usability for a blind user. 

#### Summary
Can't tell which channels are unread

#### Steps to reproduce
(Mattermost 4.4.2 using JAWS screen reader software)
Receive any new message

#### Expected behavior
Say which channels have unread messages

#### Observed behavior (that appears unintentional) 
'X unread channels' shows in the taskbar, but impossible to know which channels without scrolling through each channel and checking

#### Possible fixes
Separate out X messages to 1 message in Y, 2 messages in Z etc. Have some dynamic channel ordering so channels with unread messages are always first

**Comment by lindy65** [comment]
Hi @pauljonesOH,

Thanks for your report :)

With v4.7, the "unreads" section was introduced which shows all unread channels in an "UNREADS" section at the top of the left-hand-side bar.  I'm sure upgrading to the [latest version](https://about.mattermost.com/download/) will fix this issue for you!

Thanks!

**Comment by lindy65** [comment]
Hi @pauljonesOH,

I'll close this issue off here for now as the 'unreads' section should solve this issue for you once you've upgraded to the latest version of Mattermost.
