### ISSUE TITLE
Accessibility issue - Can't post first message in channel

### ISSUE THREAD

**Issue by pauljonesOH** [mattermost/mattermost-server#8444]
I'm logging some accessibility issues in Mattermost that are effecting the usability for a blind user. 

#### Summary
Can't always type straight away into channel's message field

#### Steps to reproduce
(Mattermost 4.4.2 using JAWS screen reader software)
Select channel and start typing

#### Expected behavior
Starts typing in message field

#### Observed behavior (that appears unintentional) 
To bring message field into focus, have to scroll up to a previous message then back down again. This captures focus and can then start typing. For a channel with no posts, impossible to create the first message as no previous message exists that the workaround can be applied on.

#### Possible fixes
Properly take focus so typing starts automatically

**Comment by lindy65** [comment]
Hi @pauljonesOH,

Thanks for your report!

Please try upgrading to the [latest server version of Mattermost](https://about.mattermost.com/download/) as we've recently worked on cursor focus into the text input box so I'm wondering whether upgrading will fix the issue for you?

Thanks!

**Comment by lindy65** [comment]
@pauljonesOH - just popping in to see whether this issue was resolved once you upgraded to the latest version of Mattermost?

**Comment by lindy65** [comment]
As there hasn't been any feedback, we'll assume your issue is resolved and I'll close off this issue for now.  Please feel free to open a new issue if you are still having problems and we'll be glad to help troubleshoot.
