### ISSUE TITLE
Accessibility issue - emoji support

### ISSUE THREAD

**Issue by pauljonesOH** [mattermost/mattermost-server#8445]
I'm logging some accessibility issues in Mattermost that are effecting the usability for a blind user. 

#### Summary
Emoji don't display correctly

#### Steps to reproduce
(Mattermost 4.4.2 using JAWS screen reader software)
View emoji

#### Expected behavior
Emoji should display as the typed command e.g. :thumbsup:

#### Observed behavior (that appears unintentional) 
Emoji show as a line of 1s. On other pages/sites with emoji, they do display as expecting using the screen reader software.

#### Possible fixes
Resolve emoji display issue

**Comment by lindy65** [comment]
Hi @pauljonesOH,

Thanks for your report,

Could I ask your help upgrading to [the latest version of Mattermost](https://about.mattermost.com/download/) to see whether the emoji issue still reproduces?  We've recently done some work around emoji so I'm wondering whether upgrading will fix this issue for you...

Thanks!

**Comment by lindy65** [comment]
Hi @pauljonesOH,

Was the issue resolved after upgrading to the latest Mattermost version?

**Comment by pauljonesOH** [comment]
Hi,

Apologies for the very slow reply on this - it's taken a while to get the server updated!

This hasn't helped unfortunately - Emojis are still unreadable (they're just rendered as a number, depending on how many of each emoji are present), but no indication of what the emoji actually is. This is the same for the web client and the Windows desktop client.

Thanks,
Paul

**Comment by lindy65** [comment]
Hi @pauljonesOH :)

Thanks for coming back to us to let us know!

We have [this epic ticket](https://mattermost.atlassian.net/browse/MM-10063) open where we're working on a ton of accessibility issues...  I'd appreciate your taking a look at it and letting us know whether we need to open a separate ticket for this issue or whether it will be covered in the other improvements...

Thanks!

**Comment by lindy65** [comment]
As there hasn't been any feedback, I'll close this issue off for now and we can track via the above-linked ticket.
