### ISSUE TITLE
Windows 7 with IE11: Cursor jumps to end of line

### ISSUE THREAD

**Issue by cjohannsen81** [mattermost/mattermost-server#8451]
#### Summary
When editing a post using Windows 7 and IE11 the cursor always jumps to the end of the line.

#### Steps to reproduce
Just use a Windows 7 VM and Internet Explorer 11 and edit a message. Seems to happen with all IE11 patch levels so far.

#### Expected behavior
Cursor stays at the position to edit.

#### Observed behavior (that appears unintentional) 
See attached animated gif.

#### Possible fixes
Not sure, seems to be related to the handling of the code in IE11.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2995339/37327741-cfa9ddf6-2697-11e8-944e-f0e42bc85f98.gif)

**Comment by lindy65** [comment]
Hi @cjohannsen81,

I've reproduced your issue and have created a ticket [here](https://mattermost.atlassian.net/browse/MM-9819). 👍

**Comment by Merlin2001** [comment]
Shouldn't the expected behavior be:  
> Cursor ~~isn't~~ **is** staying at the position to edit as soon as you type.

?

**Comment by lindy65** [comment]
Thanks @Merlin2001 

Correct!  I've updated the expected behavior :)

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the Jira ticket linked above.
