### ISSUE TITLE
formatting issues from text coming from matterircd inside of webui [Edit: issue caused from MIRC color codes]

### ISSUE THREAD

**Issue by khronosschoty** [mattermost/mattermost-server#8456]
#### Summary
Formatting of text from matterircd is not always correctly shown on the web interface or the mobile app etc. 

#### Steps to reproduce
Use the IRC bot Malibu developed by Stinger for the browser game utopia-game.com

#### Expected behavior
Formatting should be the same in the IRC client (or near the same).  

#### Observed behavior (that appears unintentional) 
Some people report some of the formatting is off they see things like this

![encoding](https://user-images.githubusercontent.com/2358071/37365516-a9d2fafa-26f5-11e8-8838-830490efad23.PNG)

I can't reproduce the issue above but I also get strange issues. Edit: I can reproduce the issue above it happens only when using the desktop app, otherwise you get the issue from down below. 

![f95jrcd](https://user-images.githubusercontent.com/2358071/37367104-65e05dce-26fa-11e8-94c4-dd0639620ab2.png)

numbers displayed that should not be displayed like the '7' in front of "Quadratic" 
or the "Runes: 12 4k" should just read "Runes: 4k" and it displays properly on the irc gateway just not in the mattermost webui. 

#### Possible fixes
Ignore Mirc color codes coming form matterircd

**Comment by SmartHoneybee** [comment]
Hi @khronosschoty,

the issue you are experiencing is related to the way [`matterircd`][1] translates between IRC and Mattermost. Thus, this is an issue with `matterircd` and not with Mattermost. (As far as I can tell.)

By the way, if you open an issues and are aware of other similar issues, please do mention those in your report. In this case, e.g.:
* https://github.com/mattermost/desktop/issues/729
* https://github.com/42wim/matterircd/issues/149

Regards,
Bee

[1]: https://github.com/42wim/matterircd

**Comment by lindy65** [comment]
Thanks, I'll close this issue off here for now and we can track via the issues linked above.
