### ISSUE TITLE
Mattermost installation on UBuntu 14.04 LTS

### ISSUE THREAD

**Issue by ankiksri** [mattermost/mattermost-server#8463]
Hello everyone,

I am trying to install mattermost on ubuntu server 14.04 LTS.
My machine is Macpro -- I have installed Vmware fusion one that and on VM ware i have install ubuntu server.
I have completed alll the steps of configuration & when I am running this command "sudo -u mattermost ./platform" Its showing:
sudo -u mattermost ./platform
./platform: 1: ./platform:ELF����: not found
./platform: 2: ./platform: Syntax error: “(” unexpected
<img width="589" alt="screen shot 2018-03-15 at 12 12 56 pm" src="https://user-images.githubusercontent.com/37395348/37447964-496a1716-281c-11e8-97d8-5b81b9cf6b81.png">

**Screen shot attached, Please help me**

**Comment by SmartHoneybee** [comment]
Hi @ankiksri,

I suspect that you are running a 32bit (`i386`) VM while Mattermost requires 64bit (`amd64`). 

Regards,
Bee

**Comment by ankiksri** [comment]
Hi 
Can I install amd64 on mac by using VMware fusion? I mean to say I have mac inside that I have installed VMware fusion and in that can I install ubuntu 14.04 amd64 bit???

**Comment by SmartHoneybee** [comment]
Hi @ankiksri,

probably. (I'm no VMware Fusion/macOS enthusiast.) "Just try it" and/or ask for help in the [VMware Fusion forum][1]. Once you have a suitable installation, feel free to use the [Mattermost forum][2] for follow-up questions.

Hope that helps, if so, please close this issue.
Thanks.

Regards,
Bee

[1]: https://communities.vmware.com/community/vmtn/fusion
[2]: https://forum.mattermost.org/

**Comment by lindy65** [comment]
As there hasn't been any feedback, I'll close off this issue for now.
