### ISSUE TITLE
Pinned tab with FF : cannot clear a notification

### ISSUE THREAD

**Issue by fred-cm** [mattermost/mattermost-server#8465]
#### Summary
we use mattermost for our merge-requests   
until now, when someone sent me a MR (with @myUser), the mattermost logo of the tab became red and I could acknowledge by reading it
today, I always get a red notification, which disappears when I focus the page, but is back later, without new events

#### Steps to reproduce
This bug is always on !
![issue8465](https://user-images.githubusercontent.com/37414801/37480682-2990be22-2880-11e8-962a-03962cdc59ab.PNG)

#### Expected behavior
The pinned tab should stay mute when no new events

**Comment by lindy65** [comment]
Hi @fred-cm,

Thanks for your report!

Could you share which server version of Mattermost you have installed?  Also which version of Firefox are you using?

**Comment by fred-cm** [comment]
Hi @lindy65 

FF : 
quantum 58.0.2
MM : 
Version: 3.10.0  (3.10.2)
Database: postgres

**Comment by lindy65** [comment]
Hi @fred-cm,

Thanks for the info,

We'd definitely suggest upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost.  We fixed a couple of Firefox-related bugs a few releases back so I'm guessing that if you upgrade to v4.8 your issue will be resolved.

**Comment by fred-cm** [comment]
Hi @lindy65 

Thanks for you answer, ok for that !
