### ISSUE TITLE
Cannot Create User from Web

### ISSUE THREAD

**Issue by stone212** [mattermost/mattermost-server#8472]
#### Summary

Although "EnableUserCreation" is set to true, when I go to "mattermost.myserver.com" in a browser, I see the login boxes but I do not see the button to create an account.

#### Steps to reproduce

1. Follow these instructions to install Mattermost server: https://docs.mattermost.com/install/install-ubuntu-1604.html#

2. Then set EnableUserCreation to true in /opt/mattermost/config/config.json

3. Then navigate to "https://mattermost.yourserver.com" and you will not see a button to create users.

#### Expected behavior

Following these steps, I would expect the mattermost homepage to show a button to create a user account.

#### Observed behavior (that appears unintentional) 

The https://mattermost.myserver.com homepage is clearly customized with the company name, etc.  And the login fields work.  But there is no button to create an account.

#### Possible fixes

Well I am probably missing something obvious.

**Comment by lindy65** [comment]
Hi @stone212,

Thanks for your feedback,

Can you share which server version of Mattermost you have installed and which browser you're seeing this in?  

Also, do you have `Enable open server` checked in `Security > Sign Up`?  When true, anyone can signup for a user account on the server without the need to be invited.

**Comment by stone212** [comment]
@lindy65  

I checked with multiple browsers.  Mattermost 4.7.3.

> Also, do you have Enable open server checked in Security > Sign Up? 

Oh!  No I didn't.  Okay that fixed the problem in a way.

However the reason this was set to false is because I don't want just anyone able to sign up for an account.  Is there a way to moderate this so it requires admin approval?  I suppose I could also put the mattermost page behind a simple http password if necessary.
