### ISSUE TITLE
Can't show "user is typing..." in Japanese IME hiragana mode

### ISSUE THREAD

**Issue by dupont-kedama** [mattermost/mattermost-server#8473]
#### Summary
Input message in Japanese hiragana mode, can't show "user is typing..." to other user's UI.

#### Steps to reproduce
Input message in Japanese hiragana mode.

#### Expected behavior
Show "user is typing..." to other user in same channel.

#### Observed behavior (that appears unintentional) 
Can't show "user is typing..." to other user in same channel.

#### Other detail
In ASCII mode, not reproduce.

#### Environment
+ Client
  + Windows10pro
  + IE11/Chrome/DesktopApp
+ Server
  + Windows2012R2
  + Mattermost4.7.2

**Comment by lindy65** [comment]
Hi @dupont-kedama,

Thanks for your report!

I've created [this ticket](https://mattermost.atlassian.net/browse/MM-9912) for the team to investigate.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the [Help Wanted] ticket above...
