### ISSUE TITLE
Unicode code point entry doesn't work

### ISSUE THREAD

**Issue by kittykat** [mattermost/mattermost-server#8474]
#### Summary
It's not possible to trigger Unicode code point input

#### Steps to reproduce
Press Ctrl+Shift+U

#### Expected behavior
I can enter a code point to get a Unicode character. For example, Ctrl+Shift+U followed by 2026 to get a … character.

#### Observed behavior (that appears unintentional) 
Upload dialog opens

#### Possible fixes
Remove Ctrl+Shift+U as a shortcut for the upload dialog as Ctrl+U already opens the upload dialog

**Comment by jespino** [comment]
Hi @kittykat,

Yes, this is a bug, the defined behavior is Ctrl+U is for upload file, Ctrl+Shift+U is a unhandled case.

Do you want to make a PR with the change?

Probably you only have to add a !e.shiftKey check here: https://github.com/mattermost/mattermost-webapp/blob/master/components/file_upload/file_upload.jsx#L421

And one last thing, before accept your PR we will need you sign the contributors agreement here: https://www.mattermost.org/mattermost-contributor-agreement/

**Comment by lindy65** [comment]
As there hasn't been any feedback, I'll close this issue off for now.

**Comment by Gaibhne** [comment]
This issue shouldn't be closed, you still can't enter unicode code points in Mattermost :(

**Comment by kittykat** [comment]
Just saw this issue again because of the comment above.

I'm not a developer so won't submit a PR; I also don't feel that that's a valid reason to close the issue? I don't use Mattermost any more, but not being able to enter unicode code points in a chat app would be a deal breaker for me if I had a choice about which app to use.

**Comment by agnivade** [comment]
@Gaibhne / @kittykat - What version of Mattermost are you using? I just tested on latest master, and I can indeed press Ctrl+Shift+U and enter unicode code points.

**Comment by kittykat** [comment]
@agnivade I don't use Mattermost any more, it would have been the version that was latest stable at the time :+1:

**Comment by Gaibhne** [comment]
My client is 5.0.4 which I would expect to be the responsible part (despite this being the -server repo, but I came across this via Google). Not sure how to tell what version our server is.

**Comment by agnivade** [comment]
The desktop app just loads the Mattermost webapp. So we need to know the server version. You can find out the server version, by clicking "About Mattermost" -> Mattermost version.

**Comment by Gaibhne** [comment]
It seems our server is still on 5.x due to the upgrade being nontrivial, so that would explain why the hotkey doesn't work if it was fixed in server. I assumed something like hotkey handling would be a client aspect, which I was certain was up to date. Thank you for the explanation, and sorry for bumping this issue back up.

**Comment by agnivade** [comment]
No worries. It is indeed a client aspect, but the server and client are bundled together into one. The desktop client is nothing but an electron wrapper. The actual contents of the webapp are loaded from the server URL.
