### ISSUE TITLE
Access denied for user 'matteruser'@'172.17.0.1' (using password: YES)

### ISSUE THREAD

**Issue by dandingol03** [mattermost/mattermost-server#8481]
OS: mac 10.11.5
error:```Failed to ping DB retrying in 10 seconds err=Error 1045: Access denied for user 'matteruser'@'172.17.0.1' (using password: YES)```
Hi,i need help.thanks~

**Comment by lindy65** [comment]
Hi @dandingol03,

Thanks for your feedback,

So we can help troubleshoot, please let us know which server version of Mattermost you have installed as well as a little more information about your set up?

Thanks!

**Comment by cpanato** [comment]
This was solved together with @dandingol03  in the pre-release. Closing
