### ISSUE TITLE
[Help Wanted] [MM-9912] Can't show "user is typing..." in Japanese IME hiragana mode

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8483]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9912)

Original GitHub issue: https://github.com/mattermost/mattermost-server/issues/8473

This should be fixed by calling having the CreatePost/CreateComment components call GlobalActions.emitLocalUserTypingEvent on the Textbox's composition events since the key press event isn't fired as often in hirigana mode.

#### Summary
Input message in Japanese hiragana mode, can't show "user is typing..." to other user's UI.

#### Steps to reproduce
Input message in Japanese hiragana mode.

#### Expected behavior
Show "user is typing..." to other user in same channel.

#### Observed behavior (that appears unintentional)
Can't show "user is typing..." to other user in same channel.

#### Other detail
In ASCII mode, not reproduce.

Environment: Windows10pro / IE11/Chrome/DesktopApp. Server: Windows2012R2 / Mattermost4.7.2

**Comment by lmikaellukerad** [comment]
Hi, I'm interested in tackling this one, anything I should know?

**Comment by amyblais** [comment]
Hi @lmikaellukerad, thank you for your interest in helping with this issue! 

You can start with the Developer's Guide linked in the issue description above.

If you have any specific questions, please let us know!

**Comment by lmikaellukerad** [comment]
Would moving the emitLocalUserTypingEvent call to the handleChange method be an acceptable solution?

**Comment by amyblais** [comment]
@hmhealey / @saturninoabril The Jira ticket is tagged for ICU team, so I thought maybe one of you could help take a look at the question Luke posted above ^

**Comment by hmhealey** [comment]
@lmikaellukerad I don't believe that would work. `handleChange` isn't called when the user starts typing a character that requires multiple keypresses, like a Korean character or an accented one.

For reference, if you look [here](https://github.com/mattermost/mattermost-webapp/blob/master/components/suggestion/suggestion_box.jsx#L230) at the SuggestionBox component that's used for our autocomplete, we can't just call the autocomplete logic (`GlobalActions.emitSuggestionPretextChanged`) in `handleChange`. We also call it in `handleCompositionUpdate` so that we can offer suggestions if the user is typing a composite character

**Comment by maruTA-bis5** [comment]
Hi. I'd like to try working on this.

**Comment by hanzei** [comment]
Hey @maruTA-bis5,

Thanks for looking into this. :+1:  Let me know, if you have any questions.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/2358
