### ISSUE TITLE
Markdown formatting issue.

### ISSUE THREAD

**Issue by Hyeongmin-Kwon** [mattermost/mattermost-server#8492]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
- Number & item markdown formatting becomes strange..

#### Steps to reproduce
- Server version: 4.8
- Desktop app version: 4.0.0
- Type this message at channel:
```markdown
1. This is `1.`.
- This is `-`.
1. This is `1.`.
---
- This is `-`.
1. This is `1.`.
- This is `-`.
```
#### Expected behavior
- Each is formatted as a number or item.
---
1. This is `1.`.
- This is `-`.
1. This is `1.`.
---
- This is `-`.
1. This is `1.`.
- This is `-`.
---
#### Observed behavior (that appears unintentional) 

It will be formatted all lines with the number or item you started.
![image](https://user-images.githubusercontent.com/31919589/37756025-322b97ee-2deb-11e8-8ea5-a22299d1418f.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by hmhealey** [comment]
Hi @Hyeongmin-Kwon,

Thanks for the report. The Markdown library that we're currently using in the web app doesn't like to switch between list types when they're mixed like that, but we're going to be switching eventually to CommonMark like GitHub uses. You can already see it in use in our mobile app where this works as expected.
<img width="383" alt="screen shot 2018-03-22 at 10 09 35 am" src="https://user-images.githubusercontent.com/3277310/37775617-c5353676-2db9-11e8-9728-b42102673eec.png">

**Comment by Hyeongmin-Kwon** [comment]
I See. Thank you for answer. :)

**Comment by lindy65** [comment]
Thanks @hmhealey @Hyeongmin-Kwon,

I'll close this issue off here for now then...
