### ISSUE TITLE
Slack-Import: Mattermost only imports first user

### ISSUE THREAD

**Issue by dnl-09** [mattermost/mattermost-server#8493]
Hey,

im having a problem while importing a Slack export in Mattermost.

#### Summary
Mattermost only imports the first user from Slack-Import (users.json)

#### Steps to reproduce
I exported my Slack-Team like it is descriped in the documentation. I enabled the username-overwriting by plugins and added the e-mail-adresses with the Slack-Advanced-Exporter. Than i imported the new Zip-File in Mattermost 4.8, running with a Postgres 9.5 on Gentoo. 
I also tried the same setup on ubuntu 16.04 with the same problem.

#### Expected behavior
Mattermost creates the channels and imports the first user in the users.json-File. Also Mattermost imports all messages, that this user has sent. But only from the one.
Edit: If i delete the first user in the users.json, it imports only the next.

#### Observed behavior (that appears unintentional) 
I've attached screenshots from the MattermostImportSummary.txt and the server-log. 

#### Possible fixes
Maybe the format of the users.json? But proofed by multiple json validators, it should be valide.

I hope you can help me!

Thank you,
Daniel

![serverlog](https://user-images.githubusercontent.com/37614758/37761699-b24da0ba-2dba-11e8-982a-8b96e1e80ddc.PNG)
![mattermostimportsummary](https://user-images.githubusercontent.com/37614758/37761700-b28379e2-2dba-11e8-8904-516a388f739d.PNG)

**Comment by lindy65** [comment]
Hi @dnl-09,

Thanks for the report,

We've created [this ticket](https://mattermost.atlassian.net/browse/MM-9934) to track the issue.

**Comment by lindy65** [comment]
I'll close this issue off here as the PR is merged and will release with v4.9 on April 16th.

**Comment by fmantek** [comment]
I just upgraded a Bitnami installation to 4.9.2, and I am still observing this behaviour.

**Comment by lindy65** [comment]
Hi @fmantek 

Thanks for your feedback,

May I ask you to open a new issue so we can help troubleshoot from fresh information?

Please also share your set-up information, reproduction steps and the error log after import.  Thanks!

**Comment by fmantek** [comment]
Ticket filed under https://github.com/mattermost/mattermost-server/issues/8761

**Comment by lindy65** [comment]
Thank you @fmantek :)
