### ISSUE TITLE
[Help Wanted] [MM-9602] Move getFlaggedPosts action from webapp to mattermost-redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#8497]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9602)

The webapp has an implementation of the getFlaggedPosts action here: https://github.com/mattermost/mattermost-webapp/blob/master/actions/views/rhs.js#L127

This action belongs in mattermost-redux so it can be shared between multiple apps.

A few things should be done:
- Create a new action in `actions/posts.js` of the mattermost-redux repository
- Make the action follow the same pattern as other mattermost-redux actions
- Add a unit test for this action in `test/actions/posts.js`
- Submit a PR with these updates to mattermost-redux
- Once merged, update the webapp to use the new mattermost-redux action

Speak to @joram on [pre-release](pre-release.mattermost.com) (@jwilander on GitHub) for help if needed

**Comment by lisakycho** [comment]
I'll take this one!

**Comment by fraziern** [comment]
I can take a look.
