### ISSUE TITLE
Mattermost Personal Token Not shown even in version 4.8 (Solved partially)

### ISSUE THREAD

**Issue by limenleap** [mattermost/mattermost-server#8502]
Hi
Please refer the earlier issue that I had filed for version 4.5 

The problem persists even in version 4.8 

I now suspect that it is possibly to do with CaddyServer -- which is the proxy forward that I am using, (Something went wrong with Nginx, so I stopped using that) 

The screenshot below should explain -- there is a "Bad Gateway" message there which comes after a long time. 

I hope this issue gets solved. I like both CaddyServer as well as Mattermost and would love to use Matttermost but now I seem to be forced to shift

The Caddy configuration file is as follows

> abc.pqr.com:80 {
    gzip
    push
    tls off
    proxy / http://localhost:8065 {
        fail_timeout 0s
        websocket
        transparent
    }
}

![image](https://user-images.githubusercontent.com/20351066/37864255-1537f972-2f92-11e8-9b2a-9fffdf6a1826.png)

**Comment by limenleap** [comment]
In the Mattermost log I see this problem (which is to do with sending email once personal access token is created) 

SendUserAccessTokenAddedEmail: Failed to send "Personal access token added" email successfully, SendMail: Failed to open TLS connection, dial tcp 54.69.33.34:465: getsockopt: connection timed out

**Comment by limenleap** [comment]
Now it has got stranger

After the above calamity even more cascading issues:

a) I tried changing the Caddy timeout to 100s.  I tried restarting the Mattermost server. Didnt work
b) I removed Caddy from the loop; and tried to access Mattermost directly at its port. Didn't work
c) I brought back Caddy and it kept complaining that "no hosts available upstream"
d) I finally got this screenshot -- which contains the log and the last dying message when Mattermost itself had crashed 

![image](https://user-images.githubusercontent.com/20351066/37864538-9e286b1e-2f96-11e8-8d9c-137b296b79ef.png)

**Comment by limenleap** [comment]
Additional info:
My server is at Digital Ocean -- 2GB Ram Firewall is inactive

**Comment by limenleap** [comment]
I restarted the server and went to sleep overnight.  I was surprised to find that today morning; I was able to get to the server from my browser! 

So this is what I think is happening: There is some bootstrapping process that needs to be completed -- and that takes time! In the meantime, it is all blank screen in the browser -- this is on a slow network (I am in India)

Finally the issue of not showing the Private Token after creation (the one time display) is also resolved.

This is what I did: I switched off these two parameters in config.json

 "SendEmailNotifications": false,
 "RequireEmailVerification": false,

My unqualified suspicion of what could be happening is as follows:
a) The user applies to make a personal token
b) The personal token gets made
c) The server then attempts to send an email (If SendEmailNotifications is true in config.json) .... That take time. As there is something wrong in the SMTP configuration, it keeps trying till timeout is consumed. For some reason; maybe this timeout is really large
d) In the meantime, the user sitting at the browser gets impatient and does not see anything happening on the browser ... so he is perplexed and closes the window.
e) The server software did not realize that the personal token has to be displayed once. That part of the code is simply assuming that the user at the browser must have seen it (Maybe this is handled in a different part of the source code) and it happily allows the chap to close it 
f) **My strong recommendation: Set a flag when the token is created, change the flag when the one-time display of the private personal token gets done and change the flag again once the dialog is closed**
g) ALL the parts of the source code (such as the module which is happily waiting for the SMTP timeout) should take a look at the aforementioned flag. A warning must be displayed in case the server detects that the user actually may not have copied the private token from its one-time display
h) The private token system is critical for me -- as I dont plan to rely much on SMTP at all; and want to create all accounts via the API using the private token 

Hope this helps

**Comment by lindy65** [comment]
Thanks for the report @limenleap,

I'm just referencing your previous issue here for historical purposes: https://github.com/mattermost/mattermost-server/issues/8064

I'll ask our engineers for help troubleshooting this...

**Comment by jwilander** [comment]
@lindy65 can we file a bug for the steps in @limenleap's last post and link to this issue?

**Comment by lindy65** [comment]
Sure, [here's the ticket](https://mattermost.atlassian.net/browse/MM-9958) @jwilander @limenleap

**Comment by lindy65** [comment]
I'll close this issue off here as the PR is merged and will be fixed in v4.10 on May 16th.
