### ISSUE TITLE
Online and Idle users are not prioritized in Channel Members dropdown or View/Manage members user list

### ISSUE THREAD

**Issue by jimbothree** [mattermost/mattermost-server#8504]
#### Summary
Viewing Members and Channel Members dropdown user list in the channel 'Reception' 
and Manage Members user list in the channel 'Developers' do not prioritize users that are Online and Idle above offline users unless those users are searched for.  Once the users have been searched, they are prioritized as expected, Online, Idle, then offline users.

#### Steps to reproduce
Version: 
![image](https://user-images.githubusercontent.com/16659457/37885518-b79280ba-3083-11e8-8f1f-ff3625f06a5c.png)

Scenario 1 (screenshots below): ln the 'Receptions' channel, View the member list, some online/idle users may already be prioritized above the offline users.  Try searching for other online/idle users and after finding any additional users, viewing the member list will now show the online/idle users that were searched. 

Scenario 2 (screenshots below): Same steps as scenario 1 except testing functionality of the channel members drop down user list.

Scenario 3 (screenshots below): Same steps as scenario 1 except using the 'Developers' channel and testing functionality of the 'Manage Members' user list.

#### Expected behavior
The expected behavior is that when Viewing Members, Managing Members or Channel members dropdown, each respective user list should prioritize all Online users first, then idle users, and finally offline users.  These user lists should be updated in a way that doesn't require a user to be searched for to be prioritized correctly.  

#### Observed behavior (that appears unintentional) 

**Scenario 1**
**Viewing Reception's member list before searching**
<img width="1387" alt="members_1" src="https://user-images.githubusercontent.com/16659457/37884144-9bf9ecbe-307c-11e8-8796-8c1b32e2cbef.png">

**Searching for an online user that should already be prioritized**
<img width="1394" alt="members_2" src="https://user-images.githubusercontent.com/16659457/37884142-9bed512a-307c-11e8-926d-ca2edd072fad.png">

**Viewing Reception's member list now shows Online user is now prioritized correctly**
<img width="1393" alt="members_3" src="https://user-images.githubusercontent.com/16659457/37884141-9bddd54c-307c-11e8-85ea-a671a789f44e.png">

**Scenario 2**
**Channel members drop down of users before searching**
<img width="1388" alt="1" src="https://user-images.githubusercontent.com/16659457/37884213-dde72c5e-307c-11e8-8b22-32cd9e9790e7.png">

**Searching for an idle (or online) user that should already be prioritized**
<img width="823" alt="2" src="https://user-images.githubusercontent.com/16659457/37884214-ddf4e45c-307c-11e8-9b43-3c51546962be.png">

**Idle user is now prioritized in channel members drop down**
<img width="1396" alt="3" src="https://user-images.githubusercontent.com/16659457/37884212-ddd91722-307c-11e8-99e1-3ddb7fadea0e.png">

**Scenario 3**
**Manage members in 'Developers' channel before searching**
<img width="1276" alt="manage_developers" src="https://user-images.githubusercontent.com/16659457/37885113-6b4b2164-3081-11e8-9e75-58ccd06d707b.png">

**Searching for members with online/idle status in 'Developers' channel**
<img width="1273" alt="manage_developers2" src="https://user-images.githubusercontent.com/16659457/37885112-6b3d97f6-3081-11e8-814b-dbd82842b738.png">

**Manage members in 'Developers' channel after searching for Online/idle users**
<img width="1275" alt="manage_developers3" src="https://user-images.githubusercontent.com/16659457/37885161-ab225b7c-3081-11e8-827c-44e6e02dd265.png">

**Comment by lindy65** [comment]
Thanks for the report @jimbothree!

We have [this ticket](https://mattermost.atlassian.net/browse/MM-9781) which has a PR submitted to fix...  I think this is the same issue you are reporting?

**Comment by jimbothree** [comment]
Great, let me know if there's anything additional I can do to help.

**Comment by lindy65** [comment]
I'll close this issue off now as the PR is merged and will release with v4.9 on April 16th.
