### ISSUE TITLE
User can break 4000 character restriction (Direct message)

### ISSUE THREAD

**Issue by ddavid9755** [mattermost/mattermost-server#8508]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
User can break 4000 character restriction (Direct message)

#### Steps to reproduce
1. Log in to mattermost
2. Navigate to any Direct message
3. Enter 4000 character long message
4. Add an emoticon
5. Send the message

#### Expected behavior
The user should not break the 4000 character law in any way, although if there is an emoticon at the end of the message:
- the user can still send the message
- the emoticon will disappear
- there is a bad request error in the console

#### Observed behavior (that appears unintentional) 
Please see the uploaded video:
https://screencast.com/t/5g7vXYRuAYD

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lindy65** [comment]
Hi @ddavid9755,

Thanks for the report!  I've reproduced the issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master with some additional findings.

I've created [this ticket](https://mattermost.atlassian.net/browse/MM-9970) to track the issue.

**Comment by jasonblais** [comment]
We just created a help wanted ticket for the issue if anyone is interested helping with a fix: https://github.com/mattermost/mattermost-server/issues/8519

Thanks @ddavid9755 for the report!
