### ISSUE TITLE
[Help Wanted] [MM-9956] Remove last uses of IntegrationStore and delete the store

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8509]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9956)

Over the last year we've been slowly moving away from using our Flux stores and towards using redux. [More info on that here](https://docs.mattermost.com/developer/webapp-to-redux.html).

Now we're really close to being able to remove the IntegrationStore, which is one of those old Flux stores. The last component using it is [ConfirmIntegration](https://github.com/mattermost/mattermost-webapp/blob/master/components/integrations/confirm_integration/confirm_integration.jsx).

For this ticket: 
1. Replace the usage of IntegrationStore by passing in the redux state as a prop in the component's index.js file
2. Delete the stores/integration_store.jsx file
3. (Bonus) Also remove usage of UserStore in the ConfirmIntegration component, using redux instead

This component migration guide should have some helpful info if you need it.
https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps

Let Joram (@joram on pre-release, @jwilander on GitHub) know if you have any questions

**Comment by n1aba** [comment]
I would like to start working on this
