### ISSUE TITLE
[Help Wanted] [MM-9938] Add support for multiple responses from a slash command

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8511]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9938)

A sample response may look like

```
    [
      {
        "channel": "administrators",
        "text": "User @matthieu.brouillard requested a TODOs admin token.\n###Context:\n- team: France `id#eesgbz3nbfgj7dcax1zoxh1e6o`\n- channel: Development `id#ueeop5ssjjromrkem8n4oamy6a`"
      },
      {
        "response_type": "ephemeral",
        "text": "Your request has been send to the ~administrators group"
      }
    ]
```

Originally reported at: https://forum.mattermost.org/t/mention-or-push-message-to-another-channel-from-a-slash-command/4393

**Comment by adzimzf** [comment]
I interested to this one.

**Comment by jasonblais** [comment]
Awesome, thank you @adzimzf!! Let us know if you have any questions along the way :)

**Comment by adzimzf** [comment]
@jasonblais,
I have some question. 
below is my step by step to this issue.
1. add slash command available when slash is typed
2.  then create api to send message to another channel

is it correct ?

**Comment by jasonblais** [comment]
Hey @adzimzf! Thanks for your question. Here's the user flow I see:

1.  User 1 posts a message `/request-token` in `development` channel.
2. A message is posted in the `administrators` channel with text ```User @user1 requested a TODOs admin token.\n###Context:\n- team: France `id#eesgbz3nbfgj7dcax1zoxh1e6o`\n- channel: Development `id#ueeop5ssjjromrkem8n4oamy6a```
3. An ephemeral message is posted in the `development` channel with text ```Your request has been send to the ~administrators group```

Is that helpful?

**Comment by jasonblais** [comment]
@adzimzf Also, a huge thanks for helping with this improvement!

**Comment by jasonblais** [comment]
Great question @adzimzf! 

> why User 1 post a message /request-token ?

By `/request-token` I just referred to a custom [slash command](https://developers.mattermost.com/integrate/slash-commands/) that a developer would have created.

> What I got from this link https://forum.mattermost.org/t/mention-or-push-message-to-another-channel-from-a-slash-command/4393 is User can send message to another channel with slash command, is it correct ?

That is true, and we have a work-in-progress PR for that here: https://github.com/mattermost/mattermost-server/pull/8678

Basically, we broke https://forum.mattermost.org/t/mention-or-push-message-to-another-channel-from-a-slash-command/4393 into two features:
 - sending responses to another channel with a slash command
 - sending multiple responses with a slash command

If you'd like to work on both, or either one, that's fine too.

**Comment by jasonblais** [comment]
Let me know if that helps? More than happy to clarify anything.

**Comment by jasonblais** [comment]
@mickmister 

> I'd like to help on the issue of accepting the destination channel in the response.

Yes, that would be great, thank you. Help is much appreciated on this one :) 

If you have any questions, don't hesitate to let us know!

**Comment by jasonblais** [comment]
awesome, thank you very much @mickmister for the improvement 🎉
