### ISSUE TITLE
[Help Wanted] [MM-9937] Add support for sending a message to a different channel than where the slash command was issued from

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8512]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9937)

Sample use case: An admin wants to send out a message in the Announcements channel of their team. To achieve it, they issue a slash command from the channel they’re currently in, and specify they want to post a message in the Announcements channel.

The proposed change adds support for sending a message to a different channel than where the slash command was issued from.

This can be achieved by supporting a parameter “channel” parameter to set the destination channel, similar to incoming webhooks: https://docs.mattermost.com/developer/webhooks-incoming.html#override-the-channel

Note: The message can only be posted to channels
 - that are on the same team as the slash command (given slash commands are currently team-specific), AND
 - the creator of the slash command has permissions to post to. If personal access tokens are used, the creator could have permissions to post in all channels, or in all public channels of the team. See https://docs.mattermost.com/developer/personal-access-tokens.html for more details.

Originally reported at: https://forum.mattermost.org/t/mention-or-push-message-to-another-channel-from-a-slash-command/4393

**Comment by cpanato** [comment]
I can take this one

**Comment by jasonblais** [comment]
Thanks @cpanato! 👍

**Comment by cpanato** [comment]
@jasonblais we will have here the same issue as https://github.com/mattermost/mattermost-server/pull/8482

**Comment by mickmister** [comment]
I'd like to work on this

**Comment by mickmister** [comment]
Open PR for this issue: https://github.com/mattermost/mattermost-server/pull/9878

**Comment by cpanato** [comment]
thanks so much @mickmister

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/9878. Thanks you very much @mickmister! :tada:
