### ISSUE TITLE
Migrating from Slack

### ISSUE THREAD

**Issue by JohnMH** [mattermost/mattermost-server#8513]
Attempting to import slack data results in.. No new users, no new channels and no new messages. Additionally the only thing added to the server log is:

`License key from https://mattermost.com required to unlock enterprise features.`

**Comment by lindy65** [comment]
Hi @JohnMH,

Thanks for your feedback,

The message you're seeing about the licence key is informational and always appears when you run mattermost/ the CLI without an enterprise license.

We have [this ticket](https://mattermost.atlassian.net/browse/MM-9934) open for the slack import issue itself.

**Comment by JohnMH** [comment]
@lindy65 Why does the software complain that my non-enterprise install doesn't have an enterprise license every time I use the CLI tool?

**Comment by lindy65** [comment]
Hi @JohnMH,

It's just an informational message to indicate you're on the team edition and would need a licence to unlock enterprise-related features...

**Comment by JohnMH** [comment]
@lindy65 Is there a way to make it so that that only happens if I try to run something related to the enterprise version?

**Comment by lindy65** [comment]
Hi @JohnMH,

Thanks for your question,

At the moment, there isn't a way as it's just an informational message, reminding you that you're on the team edition and, if you want to use enterprise features, you'd require a licence.  It's not related to any particular enterprise only feature - just a general notice.
