### ISSUE TITLE
Uncaught errors when uploading and deleting empty files

### ISSUE THREAD

**Issue by BflySamurai** [mattermost/mattermost-server#8515]
#### Summary

Uncaught errors occur when uploading and deleting empty files.

#### Environment

Mattermost version: 4.8.0

Windows 10

Chrome (65.0.3325.181)

Firefox (59.0.2)

#### Steps to reproduce

1. Upload document through the message box (either by dragging and dropping or by using the paperclip to bring up the file explorer).
2. The file must be completely empty (0 bytes) and of any extension.
3. At this point, there is a **500 (Internal Server Error)** an **Uncaught TypeError**. The user cannot send messages.
4. The file cannot be removed. Trying to remove the file brings up an **Uncaught Error**.
5. To fix the issue, the page must be reloaded.

#### Expected behavior

File should upload without issues and without making the user unable to send messages. File should be able to be deleted.

#### Observed behavior

Uploading empty documents to the message box causes the document to get stuck loading, and the document cannot be removed. This makes the message box unable to send any messages until the page is refreshed.

![mattermost_bug](https://user-images.githubusercontent.com/6045676/37935748-8defab3c-3107-11e8-9eb8-a5ccff3b1aa5.gif)

**Errors when uploading file:**

`500 (Internal Server Error)`
`Uncaught TypeError: n is not a function`

**Error when trying to delete file:**

`Uncaught Error: To access the wrapped instance, you need to specify { withRef: true } in the options argument of the connect() call.`

**There is a similar issue that was recently submitted and fixed that dealt with just deleting files while they were uploading:**

Similar issue: [MM-9783](https://mattermost.atlassian.net/browse/MM-9783)

Similar issue fix: [mattermost-webapp/pull/961](https://github.com/mattermost/mattermost-webapp/pull/961)

**Comment by lindy65** [comment]
Hi @BflySamurai,

Thanks for your report!

With the fix in MM-9783, it was decided to not allow uploads of 0 bytes so the current behavior is to display an error message `You are uploading an empty file: testfile.txt` and allow the user to delete the uploading file on the `X`.

If you'd like to test this on our [nightly build server running off the latest master](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and report your findings?

I've just tested and am seeing a Javascript error (`Uncaught TypeError: n is not a function`) even although I get the error message when trying to upload a 0KB file and can delete it.

If we can confirm you are seeing the same, I will create a ticket for the JavaScript error...

**Comment by BflySamurai** [comment]
I followed the link to the nightly build. I am also seeing the Javascript error (`Uncaught TypeError: n is not a function`) when trying to upload a 0KB file and can also delete the file.

**Comment by lindy65** [comment]
Thanks for confirming @BflySamurai,

I've opened [this ticket](https://mattermost.atlassian.net/browse/MM-9975) to investigate...

**Comment by lindy65** [comment]
I'll close this issue off for now as the PR is merged and will release with v4.9 on April 16th.
