### ISSUE TITLE
Transition showPreview away from being mutable state on the textbox component

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8518]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9915)

We've seen a number of issues crop up around the textbox component re: mutable state, with recently competing changes trying to fix [one](https://github.com/delftswa2018/mattermost-webapp/commit/b2961a508133dedb24b1c1e22fad0b751b659611#diff-59fc657c354b43771e2e46f5089c1260) or [another](https://github.com/mattermost/mattermost-webapp/pull/935/commits/6fe03581b7bae7390e35d9be17d6ef958423bfc9) issue.

We should begin to transition the internal state of this component to props, starting with showPreview. Minimally, this means hoisting the state into the parent component(s) and removing the state mutation functions on the Textbox component. This in turn will likely cascade, probably resulting in this state being moved (on a per-parent basis) to the Redux state to avoid the race conditions identified in the linked commits above.

One complexity to consider is that this component appears in multiple places and the value of showPreview should be unique per instance. This will probably be handled by anchoring the state in the Redux tree by the corresponding parent component.

Ping @lieut-data (@jesse.hallam on https://pre-release.mattermost.com) as required to discuss.

**Comment by nadalfederer** [comment]
can I take this

**Comment by jasonblais** [comment]
Certainly, thanks @nadalfederer!
