### ISSUE TITLE
Cannot send messages using ENTER

### ISSUE THREAD

**Issue by L0rite** [mattermost/mattermost-server#8522]
#### Summary
Cannot send messages to group.
Per Mattermost End User Guide, users can "Press ENTER to send message."  

#### Steps to reproduce
Log into demo site.
Go to JOOMLA! team/PUBLIC CHANNELS/LBT_TESTING
Type message in Message box
Click ENTER

#### Expected behavior
Message should send 

#### Observed behavior (that appears unintentional) 
Clicking enter only creates carriage returns.  Message is not sent.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem
![bug_msg enter](https://user-images.githubusercontent.com/37845232/37983510-8cb3ae2a-31a8-11e8-99ca-0e67d84e44d8.PNG)

**Comment by lindy65** [comment]
Hi @L0rite,

Thanks for your feedback :)

Could you check whether the `Account Settings > Advanced > Send message on CTRL+ENTER` setting is NOT set to `true`?

**Comment by L0rite** [comment]
Hi lindy65,

The setting was set to “ON.”  I switched the setting to “OFF,” and *issue
is resolved*.

This is not a bug, but I believe shows an inconsistency with the End User
Guide.



The User Manual reads as if the default setting for this feature is “off.”

*Sending Messages*

Write a message by typing into the text input box, then press ENTER to send
it. Use SHIFT+ENTER to create a new line without sending a message. To send
messages by pressing CTRL+ENTER, go to *Main Menu > Account Settings >
Advanced > Send messages on Ctrl + Enter > Edit*.


Thank you!

Lori

**Comment by lindy65** [comment]
Hi @L0rite,

Thanks for your feedback,

I've just verified by signing up a new account that the setting is defaulted to "off" for a new account.

Was this setting perhaps changed by an admin or through the deployment?

**Comment by L0rite** [comment]
Hello! 
This was part of a demo exercise for an open position at Mattermost, and not part of a deployment.  I used the manual in place of a testing script and this very well could have been user error. My apologies! 

Best,
Lori

**Comment by lindy65** [comment]
Hi @L0rite,

No worries at all 😊

Thanks for testing!

I'll close this issue off as resolved for now then 😊
