### ISSUE TITLE
[Help Wanted] [MM-9828] Investigate getState usage in components/*_modal/*

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8526]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9828)

To facilitate https://mattermost.atlassian.net/browse/MM-8604, we need to ensure components do not access the Redux store in a way that influences rendering but that fails to trigger a re-render when the corresponding state changes. Typically, this means connecting the component to the store and passing in the requisite state only as props vs. ever invoking `store.getState()` directly from the component.

This issue captures the work to investigate said use of `store.getState()` in:
* edit_post_modal/edit_post_modal.jsx
* channel_invite_modal/channel_invite_modal.jsx
* quick_switch_modal/quick_switch_modal.jsx

Ping @lieut-data (@jesse.hallam on https://pre-release.mattermost.com) as required to discuss.

**Comment by amorriscode** [comment]
👋 Howdy!

I'd like to take a stab at this issue.

Thanks!

**Comment by amyblais** [comment]
Thank you @amorriscode!

**Comment by lieut-data** [comment]
https://mattermost.atlassian.net/browse/MM-9828 was resolved back in April, but it looks like we didn't close this issue. Sorry for the churn, @amorriscode, and thanks for your help in verifying that there's nothing else to do here :)
