### ISSUE TITLE
Can create or update names of channels to be the same

### ISSUE THREAD

**Issue by ClaytonStevenson** [mattermost/mattermost-server#8533]
#### Summary
You can create multiple channels with the same name, or change the name of the channels to be the same so long as the url is different.

#### Steps to reproduce
To Create new with same name:
On https://demo.mattermost.com/space-motors/channels
Go to Public Channels
Click Create public channel
Give any name you want
Click Create New Channel 
Go to Public Channels
Click Create public channel
Give same name as previous channel
Change the url
Click Create public channel

To change name to the same:
On https://demo.mattermost.com/space-motors/channels
Go to any channel
Click the dropdown for options and select Rename Channel
Enter name of an already existing channel
Click Save

#### Expected behavior
I would expect to receive an error similar to how it shows when you try to use the same url for two channels "A channel with that name already exists on the same team."

#### Observed behavior (that appears unintentional) 
It allowed me to create additional channels with the same name as shown in the screenshots, as well as changing the name of a channel to one which already exists. This makes the channel search feature "ctrl + k" more difficult to use.

![screenshot from 2018-03-28 18-02-33](https://user-images.githubusercontent.com/14799273/38022501-47aa6098-32b2-11e8-942c-85005cdd50ea.png)
![screenshot from 2018-03-28 18-02-44](https://user-images.githubusercontent.com/14799273/38022503-47eba260-32b2-11e8-9eda-2004f3d4c918.png)
![screenshot from 2018-03-28 18-02-55](https://user-images.githubusercontent.com/14799273/38022504-48287000-32b2-11e8-831d-d8546824c817.png)

**Comment by amyblais** [comment]
Hi @ClaytonStevenson,

Thank you for this report!

What you described is expected - we currently allow duplicate channel display names, they just need to have a different handle/URL (as you mentioned).

I'll close this Issue for now, but please let me know if you have any additional questions?
