### ISSUE TITLE
Cannot install latest version on Heroku

### ISSUE THREAD

**Issue by nsuchy** [mattermost/mattermost-server#8538]
#### Summary
The deploy to Heroku Button allows you to choose a specific version, deploying the newest version fails.

#### Steps to reproduce
1. Click the deploy to Heroku button in README.md
2. Change mattermost download uri to the latest .tar.gz package
3. Press deploy app
4. Wait

#### Expected behavior
Heroku's installer fails with detailed information in your apps logs.

#### Observed behavior (that appears unintentional) 
The app failed to launch.

#### Possible fixes
I am not sure at this time.

**Comment by lindy65** [comment]
Hi @nsuchy,

I asked on our team and it seems this is more of an Heroku-related issue.  Please create an issue in the [mattermost-heroku repo](https://github.com/mozilla/mattermost-heroku/issues) where the maintainer will be able to help with your issue.

Thanks!
