### ISSUE TITLE
[Help Wanted] [MM-9686] Add unit tests for channel routing

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8540]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9686)

The new channel routing behaviour was added, but it's not covered by unit tests. It should have unit tests added and possibly be refactored to be more easily testable.

The code for channel routing is in [here](https://github.com/mattermost/mattermost-webapp/blob/master/components/channel_layout/channel_identifier_router.jsx). The easiest way to make it testable would probably be to separate the logic for rewriting the URL and for setting the current channel ID, and then to test those independently.

**Comment by jwilander** [comment]
@sudheerDev is working on it

**Comment by sudheerDev** [comment]
This is not introductory though or did I make it complex than it seems!!

**Comment by jasonblais** [comment]
@sudheerDev Maybe I added the wrong label -- I've updated although let me know if I should bump it up further.

**Comment by sudheerDev** [comment]
@jasonblais that's ok. just surprised to see it as `introductory`. Anyway, I overdid in the PR!

**Comment by hmhealey** [comment]
Closing this since that code may be changing soon
