### ISSUE TITLE
[Help Wanted] [MM-9990] Add support to REST API for sending ephemeral messages to users

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8541]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9990)

It would be useful for bots and integrations to be able to send ephemeral messages to users by using the REST API.

For this ticket, you'll need to do a few things:
 
1. Add a new permission controlling who can send ephemeral messages to a user and give it to system admins
2. Modify the `POST /api/v4/posts` endpoint to accept `system_ephemeral` as a post type, check the new permission and send the ephemeral post (instead of going through the regular post creation flow)
3. Add API documentation detailing the changes to https://github.com/mattermost/mattermost-api-reference

If you have any questions, please ask Joram (@joram on pre-release and @jwilander on GitHub).

**Comment by DSchalla** [comment]
As discussed with @jwilander in the Contributors chat I'll take a shot at the issue and keep you posted on the progress here.

**Comment by DSchalla** [comment]
Update: Majority of the implementation is working, it was implemented in a own API handler since there was no nice way to merge it in the current `POST /posts` handler. I am fixing last issues and then open a PR for review, additional PRs to the webapp and api docs repositories will be required.

**Comment by DSchalla** [comment]
I think this issue can be closed after the merge, unless there are any questions left. :)

**Comment by jwilander** [comment]
Fixed by #8611
