### ISSUE TITLE
Switch Channel Command does not scroll through available channels

### ISSUE THREAD

**Issue by LecrishaB** [mattermost/mattermost-server#8545]
#### Summary
Using the Switch Channel Command (CTRL+K) on a Windows 10 PC in Chrome browser does not scroll through the available channels.

#### Steps to reproduce
1)  Enter the Switch Channel Command by pressing CTRL+K on your keyboard as instructed to onscreen and note the channel scroll box that shows up on screen.
2)  Press the up and/or down buttons on your keyboard to scroll through and choose an alternate channel to switch to.

#### Expected behavior
Upon entering the keyboard command (CTRL+K) as instructed onscreen to scroll through, select, and switch to an alternate channel, one would expect to see the channel scroll box appear on the screen, as well as be able to scroll through the channels to make a switch by pressing the up and/or down buttons on their keyboard.

#### Observed behavior (that appears unintentional) 
Upon entering the keyboard command (CTRL+K) and seeing the channel scroll box appear on the screen, I attempted to scroll through my channels by pressing the up and down buttons on my keyboard as instructed on the screen.  However, after pressing both the up and down buttons on my keyboard, none of my alternate channels appeared, but instead, the scrolling box remained empty as if indicating no other channels exist.

![scrollcommandbug](https://user-images.githubusercontent.com/37604510/38091283-b2884d76-332a-11e8-8052-3c1528be64e3.JPG)

**Comment by lindy65** [comment]
Hi @LecrishaB 

As there's been no feedback on this issue, I'll close it off for now.  Please feel free to open a new issue if you still experience problems and we'll be glad to help!
