### ISSUE TITLE
Expose function(s) to web app plugins allowing them to add their own reducers

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8546]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9996)

It would be very useful for plugins to be able to add their own reducers to the web app's redux store so that they can store their own state in the store. Using that the plugin's components would be able to pull that data/state into props as needed and the plugin's actions could modify that state.

Expose a function (or set of functions to allow for deregistering and other actions as well) for allowing plugins to register reducers against the web app redux store.

Note that when a plugin is deactivated or removed, we should deregister that plugin's reducers.

See https://github.com/mattermost/mattermost-webapp/blob/master/plugins/index.js#L16 for how to expose functions to plugins.

Some ideas for how this can be done:
* How Twitter does it http://nicolasgallagher.com/redux-modules-and-code-splitting/
* StackOverflow question with some good answers https://stackoverflow.com/questions/32968016/how-to-dynamically-load-reducers-for-code-splitting-in-a-redux-application

If you have questions, ask Joram (joram on pre-release, @jwilander on GitHub).

**Comment by a-c-sreedhar-reddy** [comment]
Hi. Can I work on this?

**Comment by a-c-sreedhar-reddy** [comment]
@jwilander Is this feature implemented. Because I see reducer registry

**Comment by jwilander** [comment]
Yes this is an old ticket that we forgot to close. Thanks for pointing it out

**Comment by a-c-sreedhar-reddy** [comment]
haha. I was really excited to implement this.

**Comment by jwilander** [comment]
Sorry about that haha
