### ISSUE TITLE
Not found a way to delete uploaded file from server.

### ISSUE THREAD

**Issue by kybin** [mattermost/mattermost-server#8561]
Because our chatting server does not have a big storage, I should manage it myself.
The biggest concern is uploaded file.
I tested whether it removes from server when I remove the (upload) message and/or the channel, and it seems not.
It is okay. But I think at least I could do it manually. 

If the function exists and only just I didn't find, please let me know the way.

**Comment by lindy65** [comment]
Hi @kybin,

Thanks for your feedback,

You might be able to do this via an [API command](https://api.mattermost.com)

**Comment by lindy65** [comment]
Hi @kybin,

As there's been no feedback on this issue, I'll close it off for now.  Please feel free to open a new issue if you still experience a problem and we'll be glad to help!

**Comment by Roy-Orbison** [comment]
@lindy65 where's the delete command? https://api.mattermost.com/#tag/files
