### ISSUE TITLE
More... and DIRECT COMMUNICATION tabs has same functionality

### ISSUE THREAD

**Issue by vuk12** [mattermost/mattermost-server#8563]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
More... and DIRECT COMMUNICATION tabs has same functionality

#### Steps to reproduce
1. Navigate to http://forum.mattermost.org/
2. On left menu click "+" icon next to "DIRECT COMMUNICATION"
3. Verify pop up window
4. Click on "More..." (last tab in left part of page)
5. Confirm that opened pop up is same as pop up from step 3.

#### Expected behavior
Different tabs on home page have different functionality 
As User for tab "More..." I would expect something more, additional and different
from other tabs.

#### Observed behavior (that appears unintentional) 
Different tabs on home page have same functionality.

#### Possible fixes
Different tabs have different functionality.

**Comment by lindy65** [comment]
Hi @vuk12,

Thank you for your feedback,

I'm sorry but I'm not understanding your issue... Did you mean to link to a different URL in 1) of your repro steps?  I'm not able to follow the repro at http://forum.mattermost.org/
