### ISSUE TITLE
Left side screen scroll doesn't work in Linux Firefox

### ISSUE THREAD

**Issue by cbruguera** [mattermost/mattermost-server#8564]
There's no left side scroll displayed in Firefox v59.0.1 Linux build (Chrome works ok).

There's no way to scroll down to the direct message contacts that are on the bottom.

**Comment by lindy65** [comment]
Hi @cbruguera,

Thanks for your feedback,

I've asked whether a teammate can reproduce this issue and, if so, we'll create a ticket for a fix.

Can you share which server version of Mattermost you are using?

**Comment by lindy65** [comment]
Hi @cbruguera,

As there's been no feedback on this issue, I'll close it off for now. Feel free to open a new ticket if you still experience the issue after upgrading to the [latest version](https://about.mattermost.com/download/#mattermostServer) of Mattermost server.

**Comment by cbruguera** [comment]
Sorry for the late reply. I should have closed this before since I couldn't reproduce the error myself. It's been working properly for a good while.
