### ISSUE TITLE
[Help Wanted] [MM-9751] Email verification prompt disappears before email is verified

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8567]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9751)

#### Steps

- Open Account Settings > General > Email
- Enter a new email address
- Save
- Observe `Check your email to verify the above address.` message in modal, as well as `Check your email at <new> to verify the address.` in the notification bar.
- Close and re-open Account Settings
- Reload the page

#### Observed

- Account Settings shows no indication of need to verify email
- Notification bar disappears on reload, never having been explicitly dismissed.
- No ability to re-send the email verification email (except on the log in screen).

#### Expected

- Account Settings continues to show verification reminder until email is verified. Text reads `Check your email to verify the above address. Cannot find the email? <Send again>.`
- Notification bar re-appears unless explicitly dismissed.  Text reads `Check your email at <new> to verify the address. Cannot find the email? <Send again>.`
- <Send again> is a link where clicking it resends the email address verification.

Note: When implementing, you can use the existing "EmailVerified" field for the "User" to check if email has been verified or not.

**Comment by maarsej** [comment]
Im interested in attempting to solve this problem, one clarification is what the notification bar is? Ive changed and saved my email on my local host a few times and have not seen any sort of notification before or after reload.

**Comment by jasonblais** [comment]
You can either contact us here or in [our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets).

If you have technical questions, [our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers) is probably your best bet as it's read by more developers on a daily basis than GitHub.

Many thanks for helping out here :)

**Comment by maarsej** [comment]
I think im getting pretty comfortable with the code base and understanding everything alright. 
However I cant find the EmailVerified variable anywhere on the webapp side in react and tried to join the community channel to ask about that but after creating an account and attempting to join at the links provided i was just caught in a loop of it sending me back to the point where i click on teams you can join contributors.

**Comment by maarsej** [comment]
I get a 400 when i click on the contributors with an empty token and invite id
the exact response is: "{"id":"api.team.add_user_to_team.missing_parameter.app_error","message":"Parameter required to add user to team.","detailed_error":"","request_id":"n63c3cyzwjge7eyuc6p3twicgh","status_code":400}"

**Comment by jasonblais** [comment]
@maarsej Thanks for letting me know. I tested account creation and there are multiple issue that I'm seeing. Have created an issue and asked for our team to help fix them soon

https://mattermost.atlassian.net/browse/MM-10310

In the meantime I'll ask one of our engineers to help answer your question so you're not blocked.

**Comment by jasonblais** [comment]
@maarsej In fact, sign ups are now fixed on pre-release.mattermost.com, so you can post your question at the community site.

Big thanks for letting us know about the sign up problems, much appreciated :)

**Comment by maarsej** [comment]
I apologize but I attempted to wait it out and thought I'd get some time to get back to working on this issue but it seems things are just going to continue to build up on my end. So I'd like to reopen this issue to the community as I can not commit to completing the fix. 

Thanks for giving me the opportunity and I will not hesitate to get involved with Mattermost in the future when I am looking to get into something open source again. Good luck!

**Comment by jasonblais** [comment]
Thank you @maarsej for the heads up! And completely understand, we're very thankful for your interest contributing to this project.

All the best! Hope to see you around later some time. :)

**Comment by jkurian** [comment]
I will be looking into this!
