### ISSUE TITLE
Error when uploading images

### ISSUE THREAD

**Issue by arturokunder** [mattermost/mattermost-server#8593]
#### Summary
When posting an image, Mattermost gets an error and the system reloads

#### Steps to reproduce
We are using version 4.8, and file storage in S3.
The error occurs when you paste or drop an image in any channel

#### Expected behavior
Describe your issue in detail

In earlier versions, everything worked fine when you copy/paste or drop an image into any channel.

#### Observed behavior (that appears unintentional) 
Most of the times, Mattermost server crashes and gets restarted. The images is not sent to the destination channel

**Comment by arturokunder** [comment]
Hi @hmhealey 
Thanks for the quick reply!
I forgot to attach the server log:
```
[2018/04/05 12:18:17 -03] [EROR] /api/v4/channels/undefined/posts:Context code=400 rid=joiqj85yfbXXXXj3wa83qkhf1e uid=w6mssXXXX7rq9kgnp7xf8h4wdo ip=XXX.XXX.XXX.XXX Invalid or missing channel_id parameter in request URL [details: ]
```
The server is only 1 GB RAM

It could be a memory issue, because the error happends most of the times but not always

**Comment by arturokunder** [comment]
Regarding the non-image files, the error doesn't occur when uploading other file types

**Comment by arturokunder** [comment]
Update:
We did a more detailed analysis, and we got 80% of RAM usage and 100% of CPU usage when mattermost procces crush

**Comment by arturokunder** [comment]
Last update:
Apparently it was the memory issue. We upgraded our server to 2GB and know is running ok

**Comment by hmhealey** [comment]
Looking at [our documentation](https://docs.mattermost.com/install/requirements.html#hardware-requirements), we recommend at least 4GB of RAM, but that is for 250-500 users. We don't have requirements listed for anything below that, but 2GB is my usual recommendation since that's what our test servers all run

**Comment by arturokunder** [comment]
ok! Should we close this issue then?

**Comment by hmhealey** [comment]
Yeah, it sounds like we're good to close it. I'm also going to open a follow up ticket to improve how we handle files since we could probably do it better so that it doesn't cause the server to run out of memory as easily
