### ISSUE TITLE
!channel mention is not working for incoming webhooks

### ISSUE THREAD

**Issue by gyp5y** [mattermost/mattermost-server#8598]
Incoming webhooks for specific channel with <!channel> mentions are not working&
`[2018/02/21 09:12:16 CST] [INFO] Incoming webhook received. Content={"channel": "#mychannel", "username": "zabbix", "text":":bangbang: <!channel> mysql process count too high: PROBLEM  Last value: 84  Event AGE: *0m*  Hostname: **myhosthere.com**    "}
[2018/02/21 09:12:17 CST] [EROR] /hooks/agqsz3s45igijncbdhzjweon1c:HandleIncomingWebhook code=404 rid=defanpdnkfdt586hhb84bj8roh uid= ip=10.10.10.10 Couldn't find the channel [details: err=Channel does not exist]`

To reproduse try to fire a message with <!channel> mention. Mattermost 4.8.0.

**Comment by icelander** [comment]
Unfortunately I'm not able to replicate this. It looks like the log is showing that the channel doesn't exist. Can you check that the channel name is correct?

**Comment by gyp5y** [comment]
Sure. Same message without `<!channel>` mention part works fine

**Comment by gyp5y** [comment]
Disregard. It was an issue with our notification bot
