### ISSUE TITLE
Mattermost allows nickname to be set as 'System'

### ISSUE THREAD

**Issue by tanskann** [mattermost/mattermost-server#8605]
#### Summary
Mattermost allows nickname 'System' which can be problematic since it's also used by Mattermost itself to announce users that joins different channels. By using nickname 'System' you could impersonate Mattermost System and e.g. ask for user's password or do some other phishing attack.

#### Steps to reproduce
1. Go to Account settings
2. Edit your Nickname to 'System'

#### Expected behavior
Changing your nickname to 'System' is not allowed and a friendly error to user will be shown.

#### Observed behavior (that appears unintentional) 
Changing the nickname to 'System' is allowed

#### Possible fixes
-

**Comment by lindy65** [comment]
Hi @tanskann 

Thanks for your feedback, 

I've reproduced your issue and have asked our product team for feedback.  We'll most probably create a ticket to fix this as I agree it's not ideal to have users with a nickname of `system` ;)

**Comment by lindy65** [comment]
Thanks for the PR @qichengzx!

I'll close this issue off here for now and we can track via the above-linked PR.
