### ISSUE TITLE
URLs are broken when a non-letter character follows a period

### ISSUE THREAD

**Issue by kosimus** [mattermost/mattermost-server#8614]
#### Summary
URLs are broken when a non-letter character follows a period

#### Steps to reproduce
1. Open any channel (be it via browser or the desktop app or the mobile app)
2. Paste the following URL: https://test.somedomain.com/display/SomeStuff/123.+Pagetitle
3. Send it.
4. Observe that the clickable URL ends at "3".

Reproduced this with server 4.6.0, in browser client, as well as on mobile (Android 8, app version 1.7.1) and in the desktop client (4.1.0-beta1, plus whatever the number of current stable version is).

#### Expected behavior
Entire URL should be clickable.

#### Observed behavior (that appears unintentional) 
URLs are cut (and thus broken) when a non-letter character follows a period. The entire URL is still visible, but as only a part of it is considered a URL, the click&go behavior does not work:
![linkswrong](https://user-images.githubusercontent.com/22074352/38671151-e8826f44-3e4a-11e8-8cfd-c3642269d511.png)
This style of ULRs (with a dot and the following +) is used commonly by Atlassian software (Confluence etc.), which makes this issue very annoying for anyone who works with it.

Potentially related issue: https://mattermost.atlassian.net/browse/MM-7033

#### Possible fixes
-

**Comment by jasonblais** [comment]
Thanks! I've created a ticket here: https://mattermost.atlassian.net/browse/MM-10180

**Comment by lindy65** [comment]
Hi @kosimus 

I'll close this issue off here for now and we can track via the above-linked ticket.
