### ISSUE TITLE
Slow query to find root posts.

### ISSUE THREAD

**Issue by dartwader** [mattermost/mattermost-server#8616]
#### Summary
Slow query: 
SELECT q2.* FROM Posts q2 INNER JOIN (SELECT DISTINCT q3.RootId FROM (SELECT RootId FROM Posts WHERE ChannelId = 'ncjjypf563d7xron969rr38dmy' AND DeleteAt = 0 ORDER BY CreateAt DESC LIMIT 30 OFFSET 0) q3 WHERE q3.RootId != '') q1 ON q1.RootId = q2.Id WHERE ChannelId = 'ncjjypf563d7xron969rr38dmy' AND DeleteAt = 0 ORDER BY CreateAt;

Empty set (2 min 7.55 sec)

#### Steps to reproduce
Table Posts have 3M rows, in  ChannelId = 'ncjjypf563d7xron969rr38dmy' 200k rows 

#### Possible fixes
add index:
ALTER TABLE `Posts` ADD INDEX `idx_posts_channel_id_delete_at_root_id` (`ChannelId`,`DeleteAt`,`RootId`);

Change query to:
(SELECT q2.* FROM Posts q2 INNER JOIN (SELECT DISTINCT q3.RootId FROM (SELECT RootId FROM Posts WHERE ChannelId = 'ncjjypf563d7xron969rr38dmy' AND DeleteAt = 0 ORDER BY CreateAt DESC LIMIT 30 OFFSET 0) q3 WHERE q3.RootId != '') q1 ON q1.RootId = q2.RootId WHERE ChannelId = 'ncjjypf563d7xron969rr38dmy' AND DeleteAt = 0) UNION (SELECT q2.* FROM Posts q2 INNER JOIN (SELECT DISTINCT q3.RootId FROM (SELECT RootId FROM Posts WHERE ChannelId = 'ncjjypf563d7xron969rr38dmy' AND DeleteAt = 0 ORDER BY CreateAt DESC LIMIT 30 OFFSET 0) q3 WHERE q3.RootId != '') q1 ON q1.RootId = q2.Id WHERE ChannelId = 'ncjjypf563d7xron969rr38dmy' AND DeleteAt = 0) ORDER BY CreateAt;
Empty set (0.02 sec)

**Comment by lindy65** [comment]
Hi @dartwader 

Could you share which server version of Mattermost you're using?

**Comment by saturninoabril** [comment]
Thanks @dartwader for looking into it! Actually our performance team c/o @lieut-data made some major optimizations to that query in v4.9. You may find the details here - https://pre-release.mattermost.com/core/pl/ezfwp364ct8bbewbji3ikpusrr

**Comment by lindy65** [comment]
Thanks @saturninoabril 👍 

@dartwader - v4.9 releases today (April 16th) so please let us know whether you still experience issues after upgrading to the [latest version](https://about.mattermost.com/download/)

I'll close this issue off here for now but please feel free to open a new issue if you're still having problems.

**Comment by lieut-data** [comment]
@dartwader, heads up that we'll be reverting this change in 4.9.1 due to some unforeseen issues in deployments where threads aren't heavily used. See the [write up](https://pre-release.mattermost.com/core/pl/n8bfq7wq77rkff8mgrrstqeuye) for more details, but don't worry: we'll revisit this one!
