### ISSUE TITLE
extreme lag in typing and scrolling with only 6 users simultaneously chatting

### ISSUE THREAD

**Issue by andyseubert** [mattermost/mattermost-server#8617]
#### Summary
Typing into the chat at the same time as others were typing became so delayed that the chat is unusable.
Restarting the client helped for a while but over time became too laggy again.

#### Steps to reproduce
To reproduce this we created a channel named "test channel" and 24 employees joined.
starting with 4 participants typing and posting text and images, we started seeing lag.
when more participants started typing and posting, the lag increased and more and more people reported the problem.
the lag is most evident when one person posts a post (like hits enter to submit a message) and as their message is appearing on the screen, my typing stops for up to several seconds. More posts seems to create more lag for me.
versions used:
version 3.6.0 client, version 4.0.1 client, 
Also evident in web client - tested in firefox and chrome
on premise server version 

#### Expected behavior
We expect to be able to participate in a multi-user chat session without significant lag in typing.

#### Observed behavior (that appears unintentional) 
I am attaching 2 videos taken while the test was under way.

#### Possible fixes
sorry I'm not a coder and have not attempted to find where this might be a problem in your code.

[ScreenRecordings.zip](https://github.com/mattermost/mattermost-server/files/1904525/ScreenRecordings.zip)

**Comment by andyseubert** [comment]
We are on version 4.0.1
Thanks.
We will definitely upgrade when the new version is available

**Comment by lindy65** [comment]
Hi @andyseubert 

v4.9 released today (April 16th) so you might like to upgrade and see whether the issue still reproduces for you.

Let us know how it goes!

**Comment by lindy65** [comment]
I'll close this issue off for now.  If you're still experiencing problems after upgrading, please feel free to open a new issue and we'll be happy to help troubleshoot!

**Comment by lindy65** [comment]
Thanks for the update and new issue opened.  We'll troubleshoot from the new issue linked above :)
