### ISSUE TITLE
Unexpected ability to list users in non-member teams (4.8.0)

### ISSUE THREAD

**Issue by s1shed** [mattermost/mattermost-server#8620]
#### Summary

As an authenticated user—without admin rights—it is possible to get a list of all users with accounts on the server, including users who are in teams that you are not a member of.

#### Steps to reproduce

On our server, *Enable users to open Direct Message channels with* is set to `Any member of the team`.

With Mattermost server 4.8.0, a user who does not have the `System Admin` role assigned will be able to see all of the users on the server by accessing the API endpoint at https://SERVER/api/v4/users. This also includes users who are in other non-member teams.

#### Expected behavior

I expect that users who do not have the `System Admin` role assigned would only be able see those users who are members of their teams.

#### Observed behavior (that appears unintentional) 

When *Enable users to open Direct Message channels with* is set to `Any member of the team`, users without the `System  Admin` role should not be able to see users who are not in any of their teams. 

This makes the Team functionality unsuitable for private collaboration with users outside of an organization.

**Comment by lindy65** [comment]
Hi @s1shed,

Thank you for your feedback,

I'll ask one of our engineers to get back to you about users who don't have system admin rights being able to access the API endpoint to view all users on the server...

**Comment by jasonblais** [comment]
Hi @s1shed - the setting only affects the UI, not permissions on the server. Hence, anyone can still retrieve users through the APIs.

We have plans to improve that setting or replace it with a new one that properly blocks direct message channels. This may or may not be in Enterprise Edition only.

**Comment by lindy65** [comment]
Thanks @jasonblais 👍 

I'll close this issue off here for now...
