### ISSUE TITLE
[Help Wanted] [MM-10185] Windows-1251 encoding causing issues with link preview

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8632]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10185)

**To reproduce:** Post a link to a web page with Windows-1251 encoding and non-ASCII characters in it to a channel, e.g. http://www.garant.ru/news/1190219/

**Expected behavior:** It shows the correct characters

**Observed behavior:** It shows unknown character characters - �  Screenshot attached

![image](https://user-images.githubusercontent.com/13119842/38823050-534e57b8-4173-11e8-82c8-f1c00bbf02fb.png)

**Comment by cometkim** [comment]
This issue is duplicated with #8341 
 
And I've already done from here #8631
