### ISSUE TITLE
[Help Wanted] [MM-10117] Add support to add/delete and enable/disable plugins via CLI

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8646]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10117)

Use case: Automatically install and enable a plugin via script.

1) Add a plugin
- description: Add a plugin for your Mattermost server. If adding multiple plugins, use a space-separated list.
- format: platform plugin add {plugin.tar.gz}
- example: platform plugin add hovercardexample.tar.gz pluginexample.tar.gz

2) Delete a plugin
- description: Deletes a previously uploaded plugin. Deleted plugins are immediately removed from the plugins directory and the user inteface.
- format: platform plugin delete {plugin.tar.gz}
- example: platform plugin delete hovercardexample.tar.gz

3) Enable a plugin
- description: Enable a plugin. If activating multiple plugins, use a space-separated list.
- format: platform plugin enable {plugin.tar.gz}
- example: platform plugin enable hovercardexample.tar.gz pluginexample.tar.gz

4) Disable a plugin
- description: Disable a plugin. Disabled plugins are immediately removed from the user interface and logged out of all sessions. They are not removed from plugins directory.
- format: platform plugin disable {plugin.tar.gz}
- example: platform plugin disable hovercardexample.tar.gz

5) List installed plugins and their status
- description: List all active and inactive plugins installed on your Mattermost server.
- format: platform plugin list
- example: platform plugin list

**Comment by DSchalla** [comment]
Would it make sense to have an additional subcommand to list currently installed plugins and their status?

**Comment by jasonblais** [comment]
@DSchalla That's a good idea. You're thinking of something like

```
platform plugin list
```

which outputs a list of plugins along with their status (active or inactive)?

**Comment by jasonblais** [comment]
@DSchalla Sounds good to me, I've added it to the list. 👍 

Let us know if you're interested working on this :)

**Comment by DSchalla** [comment]
I sadly won't have time the next weeks to tackle the issue, if it's still not taken until then I am more than happy to implement it. 

One question in advance since I've tried to take a stab at it, the commands use the `api` test client instead of the `app` one, which does not provide any `plugin` install helpers. Is this simply not implemented so far in the `api` client, does it need to be implemented as part of this issue or should one use the `app` test client? Since I am fairly new to the project, the difference when to use which client isn't particular clear to me so far.

**Comment by jasonblais** [comment]
No worries @DSchalla! Totally understand. Happy to work with you on this (or other issue) when you're back :) 

@jwilander thoughts on the question:
> One question in advance since I've tried to take a stab at it, the commands use the `api` test client instead of the `app` one, which does not provide any `plugin` install helpers. Is this simply not implemented so far in the `api` client, does it need to be implemented as part of this issue or should one use the `app` test client? Since I am fairly new to the project, the difference when to use which client isn't particular clear to me so far.

**Comment by santos22** [comment]
Hi @jasonblais  👋,

Can you confirm if these 4 commands can support multiple plugins or is the following the desired behavior:
* install/enable **multiple** plugins at a time
* delete/disable **one** plugin at a time

**Comment by jasonblais** [comment]
@santos22 For the other delete/disable commands such as `platform user deactivate` and `platform user delete`, can multiple items be deleted/disabled at once?

I assume it was only one at a time, so I proposed the same for plugins. But reading the documentation, I'm not sure if that's true.

**Comment by santos22** [comment]
@jasonblais looks like multiple users can be deleted and deactivated when running the command so I can change my implementation to be consistent 👍

**Comment by jasonblais** [comment]
Thanks @santos22! Let's do that

**Comment by lindalumitchell** [comment]
Resolved in https://mattermost.atlassian.net/browse/MM-10117
