### ISSUE TITLE
[Help Wanted] [MM-8427] Gitlab Mattermost CLI not usable because i18n Directory is missing

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8647]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8427)

See original report: https://gitlab.com/gitlab-org/gitlab-mattermost/issues/102

Summary
Can not delete a Team because the Mattermost CLI is missing the i18n Directory

Steps to reproduce
It used to work with Mattermost 3.*, since upgrading to Mattermost 4.0 it stopped working

execute /opt/gitlab/embedded/bin/mattermost --config=/var/opt/gitlab/mattermost/config.json team remove team on Mattermost Server

Expected behavior
Execute the command an delete the Team "team"

Observed behavior
The CLI could not find the i18n directory, I actually could find the i18n directory with the path /opt/gitlab/embedded/service/mattermost/i18n

**Comment by jespino** [comment]
I'm working on this embeding the static files in the binary.
