### ISSUE TITLE
mattermost on cloudron Failed: Must enable Forward80To443 when using LetsEncrypt

### ISSUE THREAD

**Issue by jimscarver** [mattermost/mattermost-server#8653]
#### Summary
Overnight one mattermost instance on my cloudron host failed with "Must enable Forward80To443 when using LetsEncrypt" and cannot be started.
#### Steps to reproduce
Try to start server and it fail to start
#### Expected behavior
is should start
#### Observed behavior (that appears unintentional) 
Received email that chat.divvydao.net was down.
Attempted to restart at my.divvydao.net and it is looping  trying to reastart prodicing the following log each time. I need help desperately to get the system back up.
Apr 19 18:45:24 => Creating config
Apr 19 18:45:24 => Updating config
Apr 19 18:45:25 json: updated "/app/data/config.json" in-place
Apr 19 18:45:25 => Changing ownership
Apr 19 18:45:25 => Start mattermost
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [INFO] Starting up plugins
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [EROR] failed to start up plugins: mkdir ./plugins: read-only file system
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [INFO] Starting Server...
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [INFO] Server is listening on [::]:8065
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [CRIT] Must enable Forward80To443 when using LetsEncrypt
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [INFO] Stopping Server...
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [INFO] stopping websocket hub connections
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [WARN] We appear to have already sent the stop checking for deadlocks command
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [INFO] Closing SqlStore
Apr 19 18:45:25 [2018/04/19 18:44:22 UTC] [INFO] Server stopped
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Using config file at /app/data/config.json
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Using config file at /app/data/config.json
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Loaded system translations for 'en' from '/app/code/i18n/en.json'
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Server is initializing...
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Loaded system translations for 'en' from '/app/code/i18n/en.json'
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Server is initializing...
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [DEBG] Parsing server templates at /app/code/templates
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Pinging SQL master database
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Pinging SQL master database
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Pinging SQL replica-0 database
Apr 19 18:45:26 [2018/04/19 18:45:26 UTC] [INFO] Pinging SQL replica-0 database
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [DEBG] Deleting any unused pre-release features
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [DEBG] Initializing built-in plugin: ldapextras
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Current version is 4.9.0 (4.9.0/Sat Apr 14 03:26:15 UTC 2018/3176e13b1f9b14192bef2337ff3fb9346f26ef66/none)
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Current version is 4.9.0 (4.9.0/Sat Apr 14 03:26:15 UTC 2018/3176e13b1f9b14192bef2337ff3fb9346f26ef66/none)
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Enterprise Enabled: false
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Enterprise Enabled: false
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Current working directory is /app/code
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Loaded config file from /app/data/config.json
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Current working directory is /app/code
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Loaded config file from /app/data/config.json
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Able to write files to local storage.
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Able to write files to local storage.
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Starting up plugins
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [EROR] failed to start up plugins: mkdir ./plugins: read-only file system
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Starting up plugins
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [EROR] failed to start up plugins: mkdir ./plugins: read-only file system
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Starting Server...
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Starting Server...
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Server is listening on [::]:8065
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [CRIT] Must enable Forward80To443 when using LetsEncrypt
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Stopping Server...
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Server is listening on [::]:8065
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [CRIT] Must enable Forward80To443 when using LetsEncrypt
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Stopping Server...
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] stopping websocket hub connections
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] stopping websocket hub connections
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [WARN] We appear to have already sent the stop checking for deadlocks command
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [WARN] We appear to have already sent the stop checking for deadlocks command
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Closing SqlStore
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Closing SqlStore
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Server stopped
Apr 19 18:45:27 Error: Must enable Forward80To443 when using LetsEncrypt
Apr 19 18:45:27 Usage:
Apr 19 18:45:27 platform [flags]
Apr 19 18:45:27 platform [command]
Apr 19 18:45:27
Apr 19 18:45:27 Available Commands:
Apr 19 18:45:27 channel Management of channels
Apr 19 18:45:27 command Management of slash commands
Apr 19 18:45:27 config Configuration
Apr 19 18:45:27 export Export data from Mattermost
Apr 19 18:45:27 help Help about any command
Apr 19 18:45:27 import Import data.
Apr 19 18:45:27 jobserver Start the Mattermost job server
Apr 19 18:45:27 ldap LDAP related utilities
Apr 19 18:45:27 license Licensing commands
Apr 19 18:45:27 reset Reset the database to initial state
Apr 19 18:45:27 roles Management of user roles
Apr 19 18:45:27 sampledata Generate sample data
Apr 19 18:45:27 server Run the Mattermost server
Apr 19 18:45:27 team Management of teams
Apr 19 18:45:27 user Management of users
Apr 19 18:45:27 version Display version information
Apr 19 18:45:27
Apr 19 18:45:27 Flags:
Apr 19 18:45:27 -c, --config string Configuration file to use. (default "config.json")
Apr 19 18:45:27 --disableconfigwatch When set config.json will not be loaded from disk when the file is changed.
Apr 19 18:45:27 -h, --help help for platform
Apr 19 18:45:27
Apr 19 18:45:27 Use "platform [command] --help" for more information about a command.
Apr 19 18:45:27
Apr 19 18:45:27 [2018/04/19 18:45:27 UTC] [INFO] Server stopped
#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by gramakri** [comment]
@jimscarver can you check if the following values are set correctly in your /app/data/config.json ?
```
        "UseLetsEncrypt": false,
        "Forward80To443": false,
```

Cloudron does not use mattermost's built-in LE integration.

**Comment by jimscarver** [comment]
that worked. I had to use

cloudron configure --debug --app 867da5ee-1136-4819-befb-0bd3675afacc

In order to get cloudron exec to work.

I have no clues how the options were changed.

Thanks.
