### ISSUE TITLE
Not working in LAN 

### ISSUE THREAD

**Issue by knuks** [mattermost/mattermost-server#8657]
i installed mattermost version 4.9 Team edition successfully but when want work with local network with IP (http://192.168.0.21:8065) from other PC in existing LAN it will show message ## **No sign-in methods are enabled. Please contact your System Administrator.**

i referred docs it is seeing enable sign in method but there is not such type of menu

**Comment by knuks** [comment]
Thanks for response @lindy65 

I set site URL as http://192.168.0.21:8065
and Enable account creation with email: true 
and Enable sign-in with email: true 
and Enable sign-in with username: true but not working

i installed on 192.168.0.21 and want to access on another PC on IP with same network

**Comment by qerosi** [comment]
Do you see any error notification in mattermost logs (/opt/mattermost/logs/mattermost.log)   ?

**Comment by knuks** [comment]
@qerosi thanks for reply, 
but when i push on digitaOcean no i cant access host to given IP i have to manually edit config.json ("EnableUserCreation": true) and then i can create user from apps but not from  web host...so please kindly request to you that solve if possible or step to deploy mattermost-server on DigitalOcean without docker and how to open for 1st use and register system admin or first user.... Thanks for previous reply..

**Comment by qerosi** [comment]
Check this Script out https://github.com/hwcltjn/mattermost-installer
For this questions i think its better if you join the community in here https://pre-release.mattermost.com/core/channels/peer-to-peer-help 
Github issues are more for bug types not configuration issues, this is just my opinion..

**Comment by knuks** [comment]
Sorry for that....i tried from last 3 days so i put all my questions on
github....bt i will join your community if required...and tomorrow i will
close that issue...
