### ISSUE TITLE
[Help Wanted] [MM-10272] Add a count for pinned posts header icon

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8661]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10272)

Add a count, similar to the channel member icon, to the pinned post icon in the channel header. The count should increment when a post is pinned and decrement when a post is unpinned.

Implementation suggestion is to add a pin count to the channel object. 

![image](https://user-images.githubusercontent.com/13119842/39166131-1a773fb6-4756-11e8-8384-fbc10953f6d1.png)

**Comment by lisakycho** [comment]
I'll take this!

**Comment by jasonblais** [comment]
Great, thanks @lisakycho! :)

**Comment by pepf** [comment]
1. Is @lisakycho  still working on this one?
2. If not, I have some questions:

- To get the number of pinned posts in a channel an api call has to be done, correct?
- If yes, what to show next to the pinned icon when doing that call? A spinner, or "0", or "-", or something else?

**Comment by jasonblais** [comment]
@esethna Would you have answers on the above questions from @pepf, or be able to gather that infomation?

**Comment by esethna** [comment]
@pepf I pinged Lisa to check but I think it's safe to take this one over. 

Regarding #2, I'm going to add @sudheerDev to help answer the question on the API. In terms of what to display during the call, do we have any existing behavior built into the channel member count component? As the proposal is to use the same component for the pinned count. I imagine the number is populated as part of channel loading and then it will update for users viewing the channel whenever new posts are pinned.

**Comment by sudheerDev** [comment]
@pepf Hey, Yes you would have to call an api but we dont have an explicit call for just count so you would have to use https://api.mattermost.com/#tag/channels%2Fpaths%2F~1channels~1%7Bchannel_id%7D~1pinned%2Fget

During the load you can follow the same behavior as the channel members count and show `-`. We cannot use the same component as channel members as it is a pop up component and this is slighly different but you can tweak the existing component `HeaderIconWrapper` and add a new prop.

Note: keep an eye out for socket events if the count is getting auto incremented if a team member pins a new post.

@esethna I see one problem with this though. Once pinned messages are opened they stay open for channel switch but the count which is in header is about the channel you are in so, this might be a little weird. What should be expected in this state? or how should it work?

**Comment by amyblais** [comment]
Pinging @esethna / @sudheerDev on the above questions ^

**Comment by sudheerDev** [comment]
Hey @mase00001, Thanks for the interest.

This ticket stirred up an internal conversation about the changes it needs for the behaviour described.

This most possibly requires server changes including socket emits and DB changes for the pin count to sync in real-time across browser tabs and devices.

We will update you soon with more information about this. Meanwhile please feel free to grab any other ticket if you find interesting to work on.

Cheers!

**Comment by jasonblais** [comment]
Hi @mase00001, completely our fault for opening the help wanted issue but only realizing some of the server changes that may be required, and which we are still thinking through.

Are there any other help wanted tickets you'd be interested tackling for Hacktoberfest?

**Comment by mase00001** [comment]
No problem at all, I'll have a look at some of the other mattermost react issues and see how I go :)

**Comment by hanzei** [comment]
@sudheerDev Is there an update about this ticket? If not, would you mind closing this issue, until the discussion is resolved.

**Comment by kaakaa** [comment]
This issue looks duplicated with #10145. 
If there is no action, this should be closed.

**Comment by hanzei** [comment]
Thanks for the hint @kaakaa!
