### ISSUE TITLE
[Help Wanted] [MM-9833] Avoid getState in i18n utility functions used by components to render

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8664]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9833)

To facilitate https://mattermost.atlassian.net/browse/MM-8604, we need to ensure utility functions used by components do not implicitly access the global Redux state and not triggering re-render when that state changes. Typically this means passing in any necessary global state into the utility function.

This issue captures the work to investigate said use of `store.getState()` in:
* i18n/i18n.jsx

Utility functions that are used exclusively to compute a point-in-time result (e.g. click handler) are probably ok, but anything in the `render()` pipeline needs to avoid `store.getState()`.

**Comment by tejasbubane** [comment]
Hi, I looked into this issue a bit. I see only one getState in the i18n.jsx file: https://github.com/mattermost/mattermost-webapp/blob/master/i18n/i18n.jsx#L142.

Do you intend to move the getState part in the components that call this function? I see two usages of that `getlanguages` function which calls `getState` - [[1]](https://github.com/mattermost/mattermost-webapp/blob/master/components/user_settings/display/manage_languages.jsx#L65), [[2]](https://github.com/mattermost/mattermost-webapp/blob/master/components/user_settings/display/user_settings_display.jsx#L638) 

I am a bit confused by the render pipeline part since both the usages are inside render function. Happy to send a PR if someone clarifies this part.

**Comment by lieut-data** [comment]
Hi @tejasbubane!

The original thrust of these investigation tickets was to remove this kind of "global" use of `store.getState()` where a state change might not be detected and trigger a necessary update. In this case, for example, if the configured set of `AvailableLocales` changes in the store, but the component using this helper method hasn't captured it as part of its `mapStateToProps`, the props won't change when that state changes and the component won't re-render.

In practice, something /else/ that is part of `mapStateToProps` does change, triggering a `render()` and re-invoking this method to effectively get the right state. But you can imagine edge cases where this doesn't happen and the component is effectively out of sync with respect to the store.

The ideal solution here would probably change `getLanguages` to accept a `config`, and then just invoke `getLanguages` as part of any necessary components' `mapStateToProps`, passing in the `config` off of the state passed to that method and ultimately passing the set of languages (locales) directly to the component that needs it.

**Comment by jasonblais** [comment]
Hey @tejasbubane! Would you be interested helping on this ticket?

**Comment by tejasbubane** [comment]
Yes I will send PR within a day or two.

**Comment by jasonblais** [comment]
Awesome, thank you @tejasbubane!

**Comment by hanzei** [comment]
Fixed by core team
