### ISSUE TITLE
Avoid getState in utility functions used by components to render

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8665]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9832)

To facilitate https://mattermost.atlassian.net/browse/MM-8604, we need to ensure utility functions used by components do not implicitly access the global Redux state and not triggering re-render when that state changes. Typically this means passing in any necessary global state into the utility function.

This issue captures the work to investigate said use of `store.getState()` in:
* utils/license_utils.jsx
* utils/channel_utils.jsx
* utils/post_utils.jsx
* utils.jsx

Utility functions that are used exclusively to compute a point-in-time result (e.g. click handler) are probably ok, but anything in the `render()` pipeline needs to avoid `store.getState()`.

**Comment by nevyangelova** [comment]
Grabbin this :)

**Comment by jasonblais** [comment]
Thanks @nevyangelova!
