### ISSUE TITLE
[Help Wanted] [MM-10335] Update email notification subject line and contents for Group Messages

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8670]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10335)

**Subject Line**
Current behavior example:
```
[Mattermost] Notification in {team name} on {Date}
[Mattermost] Notification in Contoso on November 8, 2017
```

Expected: 
```
[Mattermost] New Group Message in {channel name} on {Date}
Example: [Mattermost] New Group Message in eric, lindsay, lisakycho on April 24, 2018
```

**Contents**
Current behavior example:
![image](https://user-images.githubusercontent.com/13119842/39222794-7c54e240-480c-11e8-9108-0c048d76fbbc.png)

Expected:
```
You have a new group message.
Channel: {channel name}
{sender username} - {time/date}

Example:
You have a new group message.
Channel: eric, lindsay, lisakycho
lindsay - 12:41 UTC, November 8
```

**Email Batching:**
Leave unchanged from current behavior if email batching is enabled.

**Comment by tejasbubane** [comment]
Can be closed.
