### ISSUE TITLE
4k char limit not increasing with message column

### ISSUE THREAD

**Issue by tomryanx** [mattermost/mattermost-server#8671]
Reading between the lines about relaxing the message limit of 4000 chars (described here: https://github.com/mattermost/mattermost-server/pull/8478), I installed 4.9.0 then started and stopped MM, then changed the postgres column to a `varchar(16000)`

This had no effect on the char limit in the web client. In the startup logs I see: 

```
[2018/04/25 03:43:02 UTC] [INFO] Post.Message supports at most 4000 characters (16000 bytes)
```

Is this already available in 4.9.0? Is there an additional step I need to take? I also tried with a `text` field, which reported "at most 4000 characters (0 bytes)"

**Comment by lindy65** [comment]
Hi @tomryanx 

Some changes were made in v4.9 but there is still an open [ticket](https://mattermost.atlassian.net/browse/MM-9639) for v4.10 releasing on May 16th.
