### ISSUE TITLE
Town square channel disappearing from list

### ISSUE THREAD

**Issue by ryanschulze** [mattermost/mattermost-server#8681]
#### Summary
Town square channel disappears from list of channels if user switches to a different channel.

#### Steps to reproduce
Mattermost server version 4.9.0. Tested on the Windows App 4.0.1 as well as on Chrome.

Click on town square channel, then click on any other channel in the same team or a direct message chat.
Seems to only affect the town square channel.
Not sure if relevant, but tested with a non-admin user and the town square channel was read-only.

Short demo (our town square channel was renamed to "Announcements"): 
![Short demo](https://static.ryanschulze.net/files/mattermost_20180426.gif)

#### Expected behavior
Town Square channel doesn't disappear from list if another channel is selected. 

#### Observed behavior (that appears unintentional) 
Town Square channel disappears from the list of channels (and the list of available channels) if you switch to a different channel or chat.
If you switch to a different team, change channels/chats there, and then switch back to the original team, the town square channel still exists and is still selected.

#### Possible fixes
Not a fix, but `/join town-square` adds the channel back to the list (until the user clicks on a different channel and is back at square one).

**Comment by esethna** [comment]
@lindalumitchell when you have a chance can you please attempt to repro. Server has the ExperimentalTownSquareIsReadOnly config enabled.

**Comment by towolf** [comment]
FTR, I'm Admin on this instance and I've never seen this ... So `ExperimentalTownSquareIsReadOnly` may indeed be relevant.

**Comment by lindy65** [comment]
@ryanschulze @towolf @esethna 

I have reproduced this issue on pre-release as a non-admin user.  The only difference I have is that `Town Square` is no longer available for me to join (doesn't appear in the list of public channels to join) and is not visible in my left-hand-side bar either.  It's like it's disappeared completely - even after refreshing and switching teams.  Joining Town Square using `/join town-square` works.

I've created a [ticket](https://mattermost.atlassian.net/browse/MM-10430) to fix.

**Comment by jasonblais** [comment]
@herooftimeandspace & @dmeza A few end users feel hiding the default channel is unexpected behaviour. I was curious if anyone on your team has reported something similar, or agree with hiding Town Square when `ExperimentalTownSquareIsReadOnly ` is enabled?

**Comment by dmeza** [comment]
@jasonblais there's no specific feedback to the channel being hidden, so I assume that nobody has missed it. We did get some feedback that users were happy that they didn't get the noise of it any more, but it was related to it being read only.

**Comment by towolf** [comment]
@jasonblais for us the `town-square` channel was renamed to Announcements so that our HR can post curated messages there, but nobody else, to reduce noise getting sent to the whole company

**Comment by herooftimeandspace** [comment]
@towolf | The default channel reappears if any new posts are made to the channel.
@jasonblais | The value was high, in that they didn't have to scroll past a channel they couldn't interact with.

**Comment by jasonblais** [comment]
@herooftimeandspace And there haven't been any questions or concerns about how to access the channel again? Or new users wondering where the channel disappeared from their sidebar?

**Comment by Apollon77** [comment]
Even for a read-only channel the history and posted messages are interesting to users. So if you do not want to sell a "read once channel" as feature please fix that one. No other channel simply disappears, so why this one should? This is completely inconsistant.

**Comment by jasonblais** [comment]
@herooftimeandspace Thoughts on breaking out hiding Town Square from the sidebar into its own config setting? I would agree with @towolf / @ryanschulze / @Apollon77 that the existing behaviour feels unexpected.

If you're okay with that, I can create a ticket for it.

**Comment by herooftimeandspace** [comment]
@jasonblais | Totally fine with separating that out in the config.

**Comment by jasonblais** [comment]
Thanks, updated ticket with these two proposed changes: https://mattermost.atlassian.net/browse/MM-10430

1) If ExperimentalTownSquareIsReadOnly is set to "true", do not automatically hide Town Square channel when it has no unread messages.
2) Add ExperimentalHideTownSquareinLHS config.json setting, which lets Shift hide the Town Square channel when there are no unread messages. The channel should still be accessible via CTRL/CMD+K and the "More Channels" menus.

**Comment by lindy65** [comment]
Thanks, I'll close off this issue here for now and we can track via the above-linked ticket.
