### ISSUE TITLE
Adding users to group DM creates a new chat with no history

### ISSUE THREAD

**Issue by jcarrillo7** [mattermost/mattermost-server#8707]
#### Summary
When I have a multi-user DM if I add a new user to it it starts a new chat with no history instead of just adding the user to the current DM and showing them the history.

#### Steps to reproduce
version 4.9.0 
Create a DM with 3 users. 
Send a couple messages
Add member to DM

#### Expected behavior
Expected to add the member to the current DM and keep history

#### Observed behavior (that appears unintentional) 
New DM was created with no history.

#### Possible fixes
Unknown. Not sure if this is a bug or intentional?

**Comment by lindy65** [comment]
Hi @jcarrillo7 

Thanks for your report 👍 

This is by design for situations where the added user should not see the history.

**Comment by lindy65** [comment]
I'll close this issue off here for now...

**Comment by jcarrillo7** [comment]
I figured. It would be nice if there was an option to let them see the history.

**Comment by lindy65** [comment]
Hi @jcarrillo7 

Thanks for your feedback,

Perhaps you'd like to add a feature request to [our forum](https://mattermost.uservoice.com/forums/306457-general) where it can be upvoted by you and others to increase it's popularity?

If you do add a feature request, please add a link to it in this issue for continuity.  Thanks!
