### ISSUE TITLE
Plugins: Enable Uploads options not available

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#8709]
#### Summary
Plugin "Enable Uploads" options not available

#### Steps to reproduce
MM version 4.9.1.
Navigate to System Console > Plugins (Beta) > Configuration. Notice there is no option to enable plugin uploads.

#### Expected behavior
Plugin upload enable option should appear.

#### Observed behavior (that appears unintentional) 
Enable plugin uploads option is not visible.

This relates to https://github.com/mattermost/mattermost-docker/issues/265

**Comment by lindy65** [comment]
Hi @harshilsharma63 

Thanks for the report 👍 

I've reproduced your issue and have filed [this ticket](https://mattermost.atlassian.net/browse/MM-10451) to track...

**Comment by lindy65** [comment]
Hi @harshilsharma63 

Yes :)  When I discussed with the team yesterday, I discovered that the behavior is intentional but the documentation was incorrect so we have [fixed the documentation](https://github.com/mattermost/docs/pull/1979)

Thanks again for your report!

**Comment by lindy65** [comment]
I'll close this issue off here as the PR to fix the documentation has been merged.
