### ISSUE TITLE
Plugin configuration not saved in System Console

### ISSUE THREAD

**Issue by c-lan** [mattermost/mattermost-server#8713]
#### Summary
Plugin configuration gets corrupted upon saving the configuration via system console.

#### Steps to reproduce
1. Enable plugins (system console -> plugins -> configuration)
2. Attempt to configure e.g. Jira plugin (system console -> plugins -> jira). Save the form.
3. Switch to another system console panel and then come back to Jira plugin configuration.

Version: 4.9.1

#### Expected behavior
Jira configuration is saved correctly. Values are copied to `config.json`.

#### Observed behavior
Jira configuration is saved in a corrupted format. If `PluginSettings.Plugins.jira` tree does not exist in `config.json`, it is added with null values and wrong capitalization (should be UserName, it is saved as username). If `PluginSettings.Plugins.jira` tree does exist, settings are preserved but key capitalization is changed to lowercase, making those settings unavailable to plugins.

```
Expected:
"Plugins": {
    "jira": {
        "Enabled": true,
        "Secret": "randomly generated secret",
        "UserName": "user-selected-username"
    }
}

Actual:
"Plugins": {
    "jira": {
        "enabled": null,
        "secret": null,
        "username": null
    }
}
```

#### Possible fixes
Problem seems to be about `config.json` serialization. UI and plugins expect these JSON keys to be CamelCase, but the whole `PluginSettings.Plugin` tree is automatically converted to lowercase keys upon saving. I can get plugins to work by editing the config manually, however any attempt to save anything in the system console will corrupt existing plugin settings.

**Comment by amyblais** [comment]
@c-lan Just to confirm, does this only happen with Jira plugin or have you experienced this with other plugins as well?

**Comment by c-lan** [comment]
@amyblais Both pre-bundled plugins, Jira and Zoom are affected the same way.

**Comment by lindy65** [comment]
@c-lan @amyblais 

I've reproduced on `ci-linux-mysql` (v4.10) and `rctesting.reddogsofwar.com` (v4.10 rc1) and have created [this ticket](https://mattermost.atlassian.net/browse/MM-10492) to track...

**Comment by jwilander** [comment]
Submitted PRs for the upcoming 4.10.0 release and for 4.9.3

**Comment by lindy65** [comment]
Thanks, I'll close off this issue here for now as the PR for the fix has been merged ...
