### ISSUE TITLE
Error checking if bucket exists. [details: 400 Bad Request]

### ISSUE THREAD

**Issue by alecisec** [mattermost/mattermost-server#8714]
There looks to be a fault in the function TestS3TestConnection in system_test.go - line 753 https://github.com/mattermost/mattermost-server/blob/master/api4/system_test.go

I'm using a valid API key + secret but the test always fails.
I've verified that I can access the "aws s3api list-buckets" command from cli, using the same credentials
I've cleared all inputs other than the bucket name, s3 access key and s3 secret key.

With this same configuration, I have no issues actually uploading attachments to the server, it's only the test that fails in the system console.

Have tried with s3 debugging and with secure connections off/on, logs only ever show this one line: 

[2018/05/04 05:16:43 UTC] [EROR] /api/v4/file/s3_test:TestFileConnection code=500 rid=ixe19hh3p7rn8babe75we8qtha uid=68hoc9ne7bdrdehpyono5pqrra ip=###.###.###.### Error checking if bucket exists. [details: 400 Bad Request]

**Comment by icelander** [comment]
Do you have a way to capture the network request the system is making? That would let us compare it to the valid requests to see if there's something missing.

Also, what version of Mattermost are you using?

**Comment by alecisec** [comment]
I've had this error from about 4.7 to the present 4.9.1. I'll try get some captures.

**Comment by cpanato** [comment]
I will try to reproduce.

**Comment by cpanato** [comment]
Hello @alecisec 
I made some tests using version 4.9 and the RC for 4.10 and both cases I was able to test the connection.

Please make sure you set the `Amazon S3 Region` to match the same region where you create your bucket. Otherwise, it will fail.

if you still have the issue, is it possible enable the `Enable Amazon S3 Debugging` and post the logs?

thanks

**Comment by alecisec** [comment]
Can confirm that the Region is correctly set, I also have S3 Degugging enabled - the log only shows

[2018/05/08 04:27:05 UTC] [DEBG] POST - /api/v4/file/s3_test
[2018/05/08 04:27:05 UTC] [EROR] /api/v4/file/s3_test:TestFileConnection code=500 rid=5axd3m7gygs47jrjy37wbj4qew uid=68hoc9ne7sfdrdehpyono5pqrra ip=203.xxx.xxx.xxx Error checking if bucket exists. [details: Access Denied.]
[2018/05/08 04:27:06 UTC] [DEBG] 

But just to be clear here - That IP that is in the logs is (my) IP that I'm connecting to the server system console on, not the IP of the server itself. The s3 test is definitely issued by the server, right? not the client?

I have a fairly 'hardened' bucket config, as I said the platform can upload and get attachments from the s3 fine, it's literally only the test that fails, so I'm guessing some additional permissions are required for the test to succeed.

**Comment by cpanato** [comment]
@alecisec thanks for the input.

checking the code that checks the bucket and the documentation and also the log snipped you sent.  You need to check your permissions in the AWS for the AWS key that you are using.

per the documentation: to make the test you need at least these permissions: `s3:GetObject` and `s3:ListBucket` (doc for reference - https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html) and the piece of the code that does the check (https://github.com/minio/minio-go/blob/c6108c47ba5d86548404ebf9e51c5ca18769fe79/api-stat.go#L31)

Please if still have issues, enable the `Enable Amazon S3 Debugging` and post all the logs. with this set enable it shows the AWS request and response, not only the Mattermost logs.

answering your question: the server does the check, not the client.

**Comment by amyblais** [comment]
Hi @alecisec Following up on this - did Carlos' suggestion above help?

**Comment by amyblais** [comment]
Hi @alecisec, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by siddhant-mohan** [comment]
getting same error

logs:
---------START-HTTP---------
HEAD / HTTP/1.1
Host: ac-mattermost-assets.s3.dualstack.us-east-1.amazonaws.com
User-Agent: MinIO (linux; amd64) minio-go/v6.0.23
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190710/"us-east-1"/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190710T185953Z

HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Wed, 10 Jul 2019 18:59:53 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: 9tSGxROOwd4DXf4ievpHsUoD8FSL/xNPZ+JeGzzsQla9iiIph16HL3HWbwORjO6pg/sXatHF8Mk=
X-Amz-Request-Id: A1C864E895675D88

---------END-HTTP---------
{"level":"error","ts":1562785193.4305327,"caller":"mlog/log.go:172","msg":"Error checking if bucket exists.","path":"/api/v4/file/s3_test","request_id":"ia6opd5c1ty1zjmoofrtdp4ejo","ip_addr":"103.240.193.173","user_id":"tayh1fc95br59junp1wkdg3yoo","method":"POST","err_where":"TestFileConnection","http_code":500,"err_details":"400 Bad Request"}
