### ISSUE TITLE
[Help Wanted] [MM-10342] Document that CreateAt, UpdateAt and other time fields are in milliseconds

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#8717]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10342)

Document that CreateAt, UpdateAt and other time fields are in milliseconds.

This would be adding descriptions to the definitions for api.mattermost.com, such as in here: https://github.com/mattermost/mattermost-api-reference/blob/master/v4/source/definitions.yaml#L7

**Comment by chclaus** [comment]
Hej @jasonblais I'll take care of it

**Comment by jasonblais** [comment]
Thanks @chclaus :tada: 

Glad to see you here :)

**Comment by chclaus** [comment]
Hej,

PR is submitted: https://github.com/mattermost/mattermost-api-reference/pull/370 :grin:

**Comment by tejasbubane** [comment]
Can be closed.
