### ISSUE TITLE
[Help Wanted] [MM-10381] Improve file download API to stream files instead of loading them entirely into memory

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#8718]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10381)

The current version of the file download code requires loading an entire uploaded file into memory, which takes up a large amount of memory.

This could probably be improved to reduce the memory load caused by downloading large files. When working on the ticket, remember that we also need to support streaming to S3 via Minio. 

To help get started, you can take a look at this PR which does this change for the file **upload** API: https://github.com/mattermost/mattermost-server/pull/8679

Ping @crspeller (@christopher on https://pre-release.mattermost.com) as required to discuss.

**Comment by cometkim** [comment]
I will take this issue. I wanna look into Golang's stream APIs

**Comment by jasonblais** [comment]
Great, thank you @cometkim!

**Comment by jasonblais** [comment]
Hey @cometkim - just checking in if you have any questions thus far?

**Comment by jasonblais** [comment]
Thanks @cometkim! Sounds good

**Comment by cometkim** [comment]
I need to resolve a few build errors to before the PR. :cry: 

@jasonblais 
Question: Is this change request includes preview and thumbnail?

It would be easy to change the download API for the original, but not if it includes thumbnails and previews. 

Because these APIs have to provide byte size. Currently, It's provided via reading all bytes from the server. In the case of the original file, the byte size is stored in the `FileInfo` model, so doesn't need to read all bytes, but thumbnails and previews are not. (Could I find this info elsewhere?)

https://github.com/mattermost/mattermost-server/blob/master/api4/file.go#L334

```diff
-func writeFileResponse(filename string, contentType string, bytes []byte, forceDownload bool, w http.ResponseWriter, r *http.Request) *model.AppError
+func writeFileResponse(filename string, contentType string, bytesReader io.Reader, forceDownload bool, w http.ResponseWriter, r *http.Request) *model.AppError
	w.Header().Set("Cache-Control", "max-age=2592000, private")
-	w.Header().Set("Content-Length", strconv.Itoa(len(bytes)))
+//	w.Header().Set("Content-Length", strconv.Itoa(len(bytes))) // A problem here
	w.Header().Set("X-Content-Type-Options", "nosniff")

	...

-	w.Write(bytes)
+	io.Copy(w, bytesReader)
```

**Comment by crspeller** [comment]
@cometkim I don't think that is currently stored anywhere. You might be able to get it out of the file backends. But it also might be easier to just add the needed into to the FileInfo struct. You would have to have some logic for existing files to handle a 0 value.

**Comment by cometkim** [comment]
I just learned about `Content-Length` and `Transfer-Encoding` the HTTP's standard header and It was a very easy issue to fix.

`Content-Length` is unnecessary for what I want. I should use `Transfer-Encoding: chunked` for streaming and it will automatically by removing the `Content-Length` header.

PR here -> #9144
