### ISSUE TITLE
[Help Wanted] [MM-10389] Remove unused translations from logging de-internationalization.

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#8719]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10389)

Remove unused translations from logging de-internationalization.

**Comment by jasonblais** [comment]
@kaakaa Would you be interested taking a look?

Basically, there are a lot of unused strings in en.json files (in mattermost-server, mattermost-webapp and mattermost-mobile repositories), and it would be good to remove them, so you and others in the localization team don't spend time translating unused strings.

**Comment by jespino** [comment]
It will be done automatically by the new translations extraction mechanism.

**Comment by jasonblais** [comment]
@jespino Can we then just close the help wanted ticket?

**Comment by jespino** [comment]
Yes, but not yet the Jira ticket.
