### ISSUE TITLE
[Help Wanted] [MM-10406] Extra white space character will prevent slash commands from finding the user in the @mention

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#8720]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10406)

When using an @mention in a slash command, the user will not be found if I accidentally add a leading space in front of the @mention. The space character should be trimmed to prevent user error.

For example

```
/invite  @dylan.haussermann
``` 

will not find the user I am mentioning

Steps:
- Open a channel 
- Note a user who is not currently a member
- Attempt to invite the target user  but, include an extra space charter between the slash command and the @mention - "/invite  @dylan.haussermann"

Expected: Extra white space is trimmed
Actual: User I'm trying to invite is not found -"We couldn't find the user"

**Comment by R-Wang97** [comment]
I can take a look at this!

**Comment by tejasbubane** [comment]
@jasonblais I think this issue can be closed.

**Comment by jasonblais** [comment]
https://github.com/mattermost/mattermost-webapp/pull/1175
