### ISSUE TITLE
Makefile GOPATH set to :./vendor if not sent in system env

### ISSUE THREAD

**Issue by odontomachus** [mattermost/mattermost-server#8722]
#### Summary
make run sets GOPATH to ':./vendor' if GOPATH is not set in the environment. Build artifacts are created in a ":." directory in the project root

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
mattermost-server from master branch commit 5000eac24f8d9aeef9cd24a58af43597e6c62b02
GNU Make 4.2.1

#### Expected behavior
GOPATH should be set to $(shell go env GOPATH) or at least './vendor'

#### Observed behavior (that appears unintentional) 
Folder created in project root as ":." with "vendor" inside.

#### Possible fixes
https://github.com/odontomachus/mattermost-server/blob/fix-makefile-gopath/Makefile#L46

**Comment by lindy65** [comment]
Thanks for the report @odontomachus 👍 

And thank you for the PR which is currently in the review stage...  Much appreciated!

**Comment by crspeller** [comment]
Closed by https://github.com/mattermost/mattermost-server/pull/8724
Thanks!
