### ISSUE TITLE
Systemd Journal with 4.10 looks cluttered

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost-server#8733]
Just a cosmetic thing. The journal looks bad when starting Mattermost with Systemd with 4.10. For example
`Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.2765896,"caller":"commands/server.go:75","msg":"Current working directory is /opt/mattermost"}
Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.2766228,"caller":"commands/server.go:76","msg":"Loaded config file from /opt/mattermost/config/config.local.json"}
Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.2798414,"caller":"utils/file_backend_local.go:30","msg":"Able to write files to local storage."}
Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.2807157,"caller":"app/server.go:100","msg":"Starting Server..."}
Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.280871,"caller":"app/server.go:139","msg":"Server is listening on 188.68.44.81:443"}
Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.3025072,"caller":"api/api.go:117","msg":"API version 3 is scheduled for deprecation. Please see https://api.mattermost.com for
Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.302693,"caller":"app/web_hub.go:67","msg":"Starting 8 websocket hubs"}
Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.3375697,"caller":"sqlstore/post_store.go:1243","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}
Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.3985493,"caller":"jobs/workers.go:57","msg":"Starting workers"}
Mai 05 09:34:24 www.xxx.de platform[15808]: {"level":"info","ts":1525505664.3997555,"caller":"jobs/schedulers.go:62","msg":"Starting schedulers."}
`
That used to be much cleaner and readable...

**Comment by crspeller** [comment]
Hi @Twilek-de. Mattermost switched to using a structured logging solution in 4.10 for easier analysis in systems like [Kibana](https://www.elastic.co/products/kibana). 

If you don't use a log aggregation system. You can switch to a more human readable format by changing the new config settings `LogSettings->ConsoleJson` and `LogSettings->FileJson` to `false`.

Going to close the issue, but feel free to re-open if this doesn't solve your problem.
