### ISSUE TITLE
Blank screen in a channel when entering latex code with dollar signs

### ISSUE THREAD

**Issue by bkmgit** [mattermost/mattermost-server#8736]
#### Summary
Get a blank screen in a Mattermost channel upon entering latex 

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
When using version 4.7.1 if one types
```latex
a = b $ \approx$ m l
```

then one gets a blank screen for that channel and one cannot easily delete the post.

#### Expected behavior
Should see latex output or an error message

#### Observed behavior (that appears unintentional) 

No error message, screenshot showing blank screen is attached
![screenshot-2018-5-5 town square - adfl mattermost](https://user-images.githubusercontent.com/1679477/39664954-c04a3b22-5094-11e8-9457-9ef5859d2ef8.png)

#### Possible fixes
Not sure how to fix this.

**Comment by lindy65** [comment]
Hi @bkmgit 

Thanks for your feedback,

I'm not able to reproduce your issue on our nightly build server running off the latest master.

Could you try upgrading to [the latest server version](https://about.mattermost.com/download/#mattermostServer) of Mattermost to see if the issue still reproduces for you?

**Comment by amyblais** [comment]
Hi @bkmgit Following up on this - did Lindy's suggestions above help? Are you still experiencing the issue?

**Comment by amyblais** [comment]
Hi @bkmgit, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
