### ISSUE TITLE
[Help Wanted] [MM-10470] Add the ability to reset user emails in System Console > Users

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8747]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10470)

Use case: A customer has multiple locations and if employees move to a new office, their email domain changes. They currently have to update the user's email address in Mattermost via API/CLI, they want to be able to do this directly in the UI instead.

Proposed changes:

1) Reset email of a user in System Console > Users

A) For dropdown on users list, add an option to “Reset Email” below “Reset Password’. This lets an admin to reset the user's email.
![image](https://user-images.githubusercontent.com/13119842/39774631-6b0a9508-52c9-11e8-8c87-5867a6e74356.png)

B) Clicking this option opens a popup, similar to the “Reset Password” popup menu attached below.
```
Dialog title: Reset Email
Field title: New Email
Buttons:
 - Cancel // Closes the popup, takes no action.
 - Reset // Resets the user's email address. We should perform the same email address validation as when a user updates their email address.
```

![image](https://user-images.githubusercontent.com/13119842/39774647-745773d8-52c9-11e8-9e9e-cfe08ce21cf4.png)

NOTE: Here is the API call that lets you update someone's email address https://api.mattermost.com/#tag/users%2Fpaths%2F~1users~1%7Buser_id%7D%2Fput

NOTE 2: This will only work for email/password accounts, not for LDAP/SAML or OAuth since login credentials are handled via the service provider.

**Comment by R-Wang97** [comment]
I can try taking a look at this!

**Comment by jasonblais** [comment]
@R-Wang97 Yeah, that's correct 👍

**Comment by jasonblais** [comment]
Thanks @R-Wang97! :)
