### ISSUE TITLE
Post header elements overlap in search results

### ISSUE THREAD

**Issue by avasconcelos114** [mattermost/mattermost-server#8749]
#### Summary
When a username is long enough, the elements in post header overlap with one another

#### Steps to reproduce
1. Set username/nickname/first & last name to be a long string
2. Search for something you wrote (`from: myusername`)
3. Hover the mouse over one of the search results

Note: Best results seen when using a language where the "Jump" button is a longer string as well (works well with Korean, Russian, and Dutch)

#### Expected behavior
Elements in component render normally, with enough space from each other to tell them apart

#### Observed behavior (that appears unintentional) 
Elements (more specifically the `Flag` icon and the `Dot menu`) overlap, causing them not only to look "off", but also making it more difficult to click the Dot menu, as the `Flag` element is rendered in front of it.
![reply_thread](https://user-images.githubusercontent.com/29700158/39790809-fdb8a81e-5372-11e8-8ae4-c525bd792115.png)

#### Possible fixes
It may be necessary to break elements into the next line when the width of the `UserProfile` section is too long, though I reckon the decisions revolving this sort of behavior fall into the UI/UX team's decision-making process

**Comment by lindy65** [comment]
Thanks for the report @avasconcelos114!

I've reproduced your issue and have created [this ticket](https://mattermost.atlassian.net/browse/MM-10536) to track...

**Comment by amyblais** [comment]
Hi @avasconcelos114! Just wanted to give you an update that this has been fixed in v4.10 which was released yesterday. Would you like to upgrade and see if the issue still reproduces for you?

**Comment by avasconcelos114** [comment]
Ah yes, Just tested it and it's working great! :)

**Comment by amyblais** [comment]
Awesome, glad to hear that @avasconcelos114! :) Let us know if you encounter any other bugs!
