### ISSUE TITLE
Server Plugins - how to use logging?

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#8752]
I'm developing a Mattermost server plugin and I'm more than often left wondering why the plugin didn't work. Console output doesn't work, pkg/log doesn't work. How does logging work with a Mattermost server plugin?

**Comment by hmhealey** [comment]
Hi @harshilsharma63, there's nothing in the plugin API for logging yet, but it's something we'd like to add. If you're interested in discussing how that would work, you can sign up for https://pre-release.mattermost.com and  join the ~developer-toolkit channel where we can talk about it some more.

**Comment by DSchalla** [comment]
https://github.com/mattermost/mattermost-server/issues/8767 was logged to discuss / implement it. Might be worth closing this one and discuss everything else in #developer-toolkit and the issue itself?

**Comment by harshilsharma63** [comment]
@hmhealey I'm definitely interested in the discussion. Will discuss on the MM channel.

**Comment by harshilsharma63** [comment]
@DSchalla  yes, that makes sense.
