### ISSUE TITLE
Changing the clock on the server to the past will cause new messages to appear above old messages

### ISSUE THREAD

**Issue by navc-0001** [mattermost/mattermost-server#8754]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Changing the clock on the server to the past will cause new messages to appear above old messages

#### Steps to reproduce
Have a server with an incorrect time in the future.  Send a message. Change the time to the correct time.  Send another message.

#### Expected behavior
The new message will appear after the old message even though the servers time changed.

#### Observed behavior (that appears unintentional) 
The new messages appeared before old messages making it difficult to find messages.

#### Possible fixes
Order messages by received order rather than received time

**Comment by amyblais** [comment]
Hi @navc-0001! 

Just checking in - did you by chance open a feature request for this? If yes, can you help with a link for reference?

**Comment by amyblais** [comment]
Hi @navc-0001, we haven't received an update so I'll close this issue for now.

If you want to open a feature request, please let us know!
