### ISSUE TITLE
[Help Wanted] [MM-10569] Invite links won't work in mobile browser when the user is asked if they want to download the app

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8782]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10569)

If a user has never been to the server in the current browser session, users who click an invite link will be sent to a page to asked if they want to try the mobile app. When they then continue to the server the invite link will not work and they are brought to the login page.

Seems like if a user is sent to _get_android_app_,The invite code parameter is dropped from the query string of the request so, when the user clicks "_continue with browser_" they are no longer treated as though they followed an invite link and are sent to the login. 

This does not occur in FireFox mobile because of MM-10537 where users are never asked to try the mobile app.

Steps:
- Open a new Chrome browser session
- Enable mobile browsing mode 
- Click a team invite link or paste one in the browser address bar (ex:https://ci-linux-mysql.mattermost.com/signup_user_complete/?id=k4zbtzbqj3foija7gh8u3m7nno)
- _User is directed to [sever-adress]_/*get_android_app*
- Click "Continue in browser"
Expected: Account Creation selection page
Actual: User is brought to login page 

*Note*: This is not a regression. I reproduced it on the OSS server

**Comment by HeZumbu23** [comment]
I also can reproduce this issue, and I suffer from it. I think this issue should be have prrio "high", as it is not possible to spread the Mattermost client to new users, which should be the interest of Mattermost to be successful. 

I am trying to introduce Mattermost for my family, but I cannot invite the members via the Mattermost mechanism.  As a workaround, I have to create mattermost accounts manually (as admin) and send the credentials in clear text via email to them which is a security flaw and not a task for the admin.

I am using Team Edition Server version v5.0.0.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/1919
