### ISSUE TITLE
[Help Wanted] [MM-10537] Show the "Mattermost works best" page when opened in firefox mobile browser

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8783]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10537)

I tried it with firefox mobile using incognito window. With chrome appears correctly.

Steps to reproduce:
1. Install firefox browser in an android device.
2. Open an incognito tab.
3. Go to https://ci-linux-mysql.mattermost.com.

Expected behavior:
You see the "Mattermost works best..." page to suggest you use the mobile application.

Current behavior:
You will see directly the login page.

**Comment by tejasbubane** [comment]
The URL https://ci-linux-mysql.mattermost.com/ is giving `502 Bad Gateway`.

**Comment by jasonblais** [comment]
@tejasbubane should be back up now 👍
