### ISSUE TITLE
Github release method

### ISSUE THREAD

**Issue by chillinger** [mattermost/mattermost-server#8803]
#### Summary
releases are not listed on the Github release API

#### Steps to reproduce

`curl -s https://api.github.com/repos/mattermost/mattermost-server/releases 
`
returns no valid data

#### Expected behavior
curl -s https://api.github.com/repos/mattermost/mattermost-server/releases 
should return the list of all releases on github

#### Observed behavior (that appears unintentional) 

If one executes the following command:
`curl -s https://api.github.com/repos/mattermost/mattermost-server/releases/latest  `
a not found is returned

Running
`curl -s https://api.github.com/repos/mattermost/mattermost-server/releases
`reveals that the API does not recognize any releases. This seems to be due to the method used to releasing.
Please see https://github.com/bcit-ci/CodeIgniter/issues/3421 for a more detailed discussion

#### Possible fixes

It was mentioned that the API only lists "full" releases. If there is no negative impact of doing this, it might be a sufficient solution.

**Comment by amyblais** [comment]
Hi @chillinger, thank you for reporting this!

I checked with our engineers and it was suggested that this is something we could do, so I created an improvement ticket here: https://mattermost.atlassian.net/browse/MM-10637.

**Comment by amyblais** [comment]
Closing this for now, as this can be tracked with the ticket linked above.
