### ISSUE TITLE
Plugin - Allow Serving Static Files

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#8810]
I see no existing way for a webapp plugin to have its own set of static assets (images, css files) used on webapp. As a result, I'm currently hosting my images on imgur, which is usually slower than serving them directly from MM instance.

**Comment by lieut-data** [comment]
Hi @harshilsharma63! Any files you bundle into your plugin will be unpacked along with your executable. If you extract the path to your executable via `os.Executable`, you can serve up these assets from your server's executable using something like this:

```
package main

import (
	"net/http"
	"os"
	"path/filepath"

	"github.com/mattermost/mattermost-server/plugin"
)

type Plugin struct {
	handler http.Handler
}

func (p *Plugin) OnActivate(api plugin.API) error {
	exe, err := os.Executable()
	if err != nil {
		return err
	}

	p.handler = http.FileServer(http.Dir(filepath.Dir(exe)))
	return nil
}

func (p *Plugin) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	p.handler.ServeHTTP(w, r)
}
```

If your plugin id is `test`, then you can access the files on your Mattermost server from `/plugin/test/<filename>`.

Of course there's lots of ways to slice and dice this. Another option might be to bundle the files into your executable using something like https://github.com/rakyll/statik. Alternatively, you could embed assets into the client-side part of the plugin as javascript resources using something like webpack, and unpack them at runtime.

Let us know if this unblocks you :)

**Comment by amyblais** [comment]
Hi @harshilsharma63, did Jesse's information above help?

**Comment by harshilsharma63** [comment]
@amyblais hi, apologies for not replying. The above demonstrated method works perfectly.

**Comment by harshilsharma63** [comment]
You may close this issue now. Thanks!
