### ISSUE TITLE
EnableUserCreation doesn't default to true if not found in config.json

### ISSUE THREAD

**Issue by balasankarc** [mattermost/mattermost-server#8813]
Observed during testing of https://gitlab.com/gitlab-org/omnibus-gitlab/merge_requests/2522. Then I tested it out with regular Mattermost installation (not the one bundled with GitLab) and was able to reproduce it.

#### Summary

If `EnableUserCreation` configuration is not specified in `config.json`, it defaults to `false`. According to [docs, the default value of that configuration is `true`](https://docs.mattermost.com/administration/config-settings.html#enable-account-creation).

#### Steps to reproduce

Install Mattermost, delete the setting `EnableUserCreation` from `config.json`, start Mattermost by `sudo -u mattermost ./bin/platform` (as per the docs).

Note: You can even try putting `{}` in config.json and check if all settings are populated with default values.

#### Expected behavior

config.json gets re-populated with `EnableUserCreation: true`, which is the correct default value. And user creation works.

#### Observed behavior (that appears unintentional) 

config.json gets re-populated with `EnableUserCreation: false`. User creation fails.

**Comment by balasankarc** [comment]
@jasonblais Could you take a look, please. :)

**Comment by jasonblais** [comment]
Thanks @balasankarc - I think environment variables aren't fully supported yet, we had @hmhealey working on this. I'll ping him

**Comment by jasonblais** [comment]
@balasankarc To clarify, Mattermost v4.10 has changes that supports environment variables on GitLab Omnibus. We just released it yesterday and will be submitting to GitLab's `master` branch soon.

**Comment by balasankarc** [comment]
@jasonblais This isn't related to environment variables. If I don't have any environment variable set, if `EnableUserCreation` is not found in config.json, it should default to `true`, right? Because the docs say `true` is the default value for that setting.

**Comment by balasankarc** [comment]
BTW, this was reported in https://github.com/mattermost/mattermost-server/issues/7276 which was fixed by https://github.com/mattermost/mattermost-server/pull/7320. However, I see this comment there by @saturninoabril 
```
EnableUserCreation - no need to fix (default to false when missing, no panic, as a result no user could be created to a MM instance which is fine)
```
It says default to false while docs say default to true. Also the [config.json file shipped with Mattermost](https://github.com/mattermost/mattermost-server/blob/master/config/default.json#L71) has it set to true.

Any specific reason this should default to false?

**Comment by jasonblais** [comment]
Ah gotcha, I read your merge request and thought it was related.

I've created a bug ticket, that indeed appears to be incorrect: https://mattermost.atlassian.net/browse/MM-10640

**Comment by balasankarc** [comment]
Thanks @jasonblais . I have a PR open at https://github.com/mattermost/mattermost-server/pull/8815 . My understanding of Go is quite limited, so I wouldn't bet too much on that. Please discard it if doesn't make sense.

**Comment by jasonblais** [comment]
Awesome, thank you! I'll close this issue and we can track this via your PR.

Appreciate it!
