### ISSUE TITLE
Webp format

### ISSUE THREAD

**Issue by madvik** [mattermost/mattermost-server#8821]
#### Summary
I woiuld like used the webp format for the avatar image.

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback @madvik! 

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Hi @madvik! Checking in - did you open a feature request for this?

**Comment by amyblais** [comment]
Hi @madvik, we haven't received an update so we'll assume that the problem is no longer valid. 

If you would still like to open a feature request, please let us know and include a link back to this GitHub Issue.
