### ISSUE TITLE
Empty page on Android 4.2 browser

### ISSUE THREAD

**Issue by Rudloff** [mattermost/mattermost-server#8825]
#### Summary
When I load Mattermost 4.10 on the Android 4.2.2 browser, I get an empty page.

#### Steps to reproduce
1. Open the browser app.
2. Browse to a Mattermost server.

#### Expected behavior
The app loads or an error is displayed.

#### Observed behavior (that appears unintentional) 
The page stays empty.

#### Possible fixes
I see these errors in the console:
```
I/browser ( 1312): Console: Browser does not support websocket https://team.animafac.net/static/0.a1f77fc06a81028b69fd.js:1
E/browser ( 1312): Console: TypeError: Object [object DOMWindow] has no method 'requestAnimationFrame' https://team.animafac.net/static/main.58ecfdc1e6f7eb2c8d65.js:1
E/browser ( 1312): Console: Unhandled promise rejection https://team.animafac.net/static/main.58ecfdc1e6f7eb2c8d65.js:1
```

It is probably not worth supporting such an old browser, but could we maybe display some user friendly error asking the user to update its browser?

**Comment by amyblais** [comment]
Hi @Rudloff,

Thank you for reporting this!

I don't have an Android to test on, so I will ask someone from our team to take the repro steps and see what they experience.

**Comment by Rudloff** [comment]
Sorry, I just noticed my steps to reproduce where incomplete. The login form works correctly but once logged in I'm stuck on a blank page. (And then it goes straight to the blank page, which is why I forgot I was logged in.)

This is the first time I'm testing with this device so I don't know if it worked before 4.10.

Here is the user agent string of the browser: `Mozilla/5.0 (Linux; U; Android 4.2.2; fr-fr; revolution Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

I can also reproduce with my Android 4.2 tablet (`Mozilla/5.0 (Linux; U; Android 4.2.1; fr-fr; ASUS Transformer Pad TF300T Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30`).

I'm testing with our instance at https://team.animafac.net/.

**Comment by amyblais** [comment]
Hi @Rudloff!

I checked with a teammate and they weren't able to reproduce the issue even though they were logged in. I believe they tested on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676).

You provided the url for the instance that you use, would you be able to share access to a test account for an empty team so we can also try to test if we are able to reproduce with the instance that you use?

**Comment by Rudloff** [comment]
@amyblais Is there an e-mail address where I can send you credentials for a test account?

**Comment by amyblais** [comment]
@Rudloff Good point, yes, please join our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and you can message me there (username: @amyblais).

**Comment by amyblais** [comment]
Hi @Rudloff, sorry for the delay, I've been asking our engineers / support to take a look at the console errors but they haven't had a chance yet. Thanks for your patience.

**Comment by Rudloff** [comment]
I opened a feature request here: https://mattermost.uservoice.com/forums/306457-general/suggestions/34442647-handle-old-browsers-more-gracefully

**Comment by amyblais** [comment]
Thank you @Rudloff!

I'll close this issue for now as it can be tracked with the feature request linked above.
