### ISSUE TITLE
Desktop app on macOS logs out every few weeks

### ISSUE THREAD

**Issue by mmalina** [mattermost/mattermost-server#8831]
#### Summary
Desktop app on macOS logs out every few weeks

#### Steps to reproduce
Log in with your desktop app on macOS. Keep logged in. Eventually the app will log you out.

#### Expected behavior
Once I log in in the desktop app, I stay logged in indefinitely.

#### Observed behavior (that appears unintentional) 
Every once in a while the desktop app logs me out. This is especially annoying since I cannot have keychain will in the password for me - that doesn't work in apps. Every time the app logs me out, I have to go to keychain to search for my password. No other desktop app does this that I'm aware of. Skype doesn't do it, Adium doesn't do it..

#### Possible fixes
Perhaps integrate support for keychain in the app.

**Comment by amyblais** [comment]
Hi @mmalina! Thank you for reporting this!

We have a repo specific to desktop app, could I ask your help to resubmit this issue there: https://github.com/mattermost/desktop/issues?

While you do so, can you also help share what Mattermost desktop app version and server version you use?

Thanks! :)

**Comment by mmalina** [comment]
@amyblais thanks for the pointer, I resubmitted the issue here:
https://github.com/mattermost/desktop/issues/811

I included the info you requested as well. BTW, it might be a good idea to include something like **Environment** to your issues templates - if it was there, I would definitely have included such info.

**Comment by amyblais** [comment]
Thank you @mmalina!
