### ISSUE TITLE
[Help Wanted] [MM-10664] Grammarly affects Centre Channel scroll.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8839]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10664)

Repro steps:
1) Install and enable the Grammarly extension in Chrome
2) Open Mattermost
3) Open a post in the RHS
4) Shrink the window

Observed: The centre channel can scroll down past the bottom of the channel. This appears to happen when the Grammerly icon in the centre channel textbox gets pushed behind the RHS as in the attached screenshot

![image](https://user-images.githubusercontent.com/13119842/40396342-7dded360-5dfa-11e8-89d7-def2fa2feb33.png)

**Comment by cometkim** [comment]
It seems to be able to fix easily by adding `overflow: hidden;` into `<body>` tag. 
Let me file a PR.

**Comment by tejasbubane** [comment]
This can be closed.

**Comment by jasonblais** [comment]
Thanks @tejasbubane! And @cometkim for fixing it :)
