### ISSUE TITLE
empty MM_NATIVEAPPSETTINGS_ANDROIDAPPDOWNLOADLINK environment variable does not set setting to blank

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-server#8857]
#### Summary
Empty `MM_NATIVEAPPSETTINGS_ANDROIDAPPDOWNLOADLINK` environment variable does not set setting to blank

#### Steps to reproduce
1. Set  `MM_NATIVEAPPSETTINGS_ANDROIDAPPDOWNLOADLINK` to be empty/blank

#### Expected behavior
Setting should be blank in system console

#### Observed behavior (that appears unintentional) 
Is not blank

![image](https://user-images.githubusercontent.com/1192780/40573908-cb857300-607d-11e8-89e5-21509f365e9d.png)

#### Possible fixes
Unknown

**Comment by amyblais** [comment]
Hi @bbodenmiller! Thank you for reaching out.

Can you help with the following additional details:
1. Mattermost server version and Mattermost Android app version.
2. Are you following a specific Mattermost documentation and would you have a link?

**Comment by bbodenmiller** [comment]
4.9.1

Android app is not being used

Using environment variable section of https://docs.mattermost.com/administration/config-settings.html

**Comment by fbartels** [comment]
@bbodenmiller seems we have run into the same issue (just with different configuration options): https://forum.mattermost.org/t/how-to-properly-set-connection-security-through-env-variable/5029

**Comment by hmhealey** [comment]
I've filed a Jira ticket to look into this further with some additional information on the cause of the problem

https://mattermost.atlassian.net/browse/MM-10730

**Comment by amyblais** [comment]
I'll close this issue for now as this can be tracked with the ticket linked above.
