### ISSUE TITLE
Frontend breaks after hard-deleting team via API

### ISSUE THREAD

**Issue by mamhoff** [mattermost/mattermost-server#8858]
#### Summary

Frontend breaks after permanently deleting team via API

#### Steps to reproduce

0. Create two teams with yourself as member. 
1. Create a new team via the API using a token
2. Delete the new team via the API, adding the `permanent=true` query parameter
3. While logged in in the web app, change teams. I get a white screen and console errors: 
```
TypeError: e[n].roles is undefined
Stack trace:
t.getMyTeamRoles<@https://chat.unterbau.tech/static/main.58ecfdc1e6f7eb2c8d65.js:1:250810
s/</l<@https://chat.unterbau.tech/static/main.58ecfdc1e6f7eb2c8d65.js:1:79029
i/<@https://chat.unterbau.tech/static/main.58ecfdc1e6f7eb2c8d65.js:1:78456
s/</f<@https://chat.unterbau.tech/static/main.58ecfdc1e6f7eb2c8d65.js:1:79159
```

There's a few of these, not just one. 

This does not happen when soft-deleting.

### How can we reproduce the issue (what version are you using?)

Mattermost-Version: 4.10.0
Datenbankschema-Version: 4.10.0
Datenbank: postgres

Build Hash: 9301e575c880970dc5642605adcc37903d176227
EE Build Hash: fac85cb7ec5d2ae21e925db4fd5ec27859e19cb0
Webapp-Build-Hash: 8a4911bac5f5b51f8d40901026ed12fc6375fd70

Build-Datum: Wed May 16 00:31:32 UTC 2018

#### Expected behavior

Changing teams in the frontend should work with no interruption.

#### Observed behavior (that appears unintentional) 

White screen, aforementioned console errors

#### Possible fixes

The code in question seems to be here: https://github.com/mattermost/mattermost-redux/blob/a37d74ccee0fe74dc33361ebcebf92379a8f007c/src/selectors/entities/roles.js#L19

Maybe the permanent deletion API call should also delete the connections to users with that team.

**Comment by amyblais** [comment]
Hi @mamhoff! Thank you for reaching out and apologies for the delay.

I will ask one of our engineers to take a look at this.

**Comment by icelander** [comment]
Hi @mamhoff - I've reproduced the error and created a [JIRA ticket to track it](https://mattermost.atlassian.net/browse/MM-10737) Thanks for finding this!

**Comment by amyblais** [comment]
Hi @mamhoff - As an afterthought, can you help check if this ticket that has been previously opened  closely describes the issue you are seeing: https://mattermost.atlassian.net/browse/MM-10432?

We are including a fix for that ticket in an upcoming dot release (4.10.1), so it is possible that you'll see improvements when that is released.

**Comment by mamhoff** [comment]
@icelander excellent, thank you! 
@amyblais Yeah, it appears the ticket you're mentioning is closely related. However, there's no mention of the `permanent` flag. If I my (cursory) read of the source is correct, that's two different code paths. As well, the ticket you're linking mentions: 

> However I feel like the real fix to this would be to ensure a member's roles for a team also gets deleted when a team is deleted.

...which seems to be the proper fix.

Kudos, great work! :)

**Comment by amyblais** [comment]
Sounds good! I'll close this issue for now as it can be tracked with the ticket that was opened - https://mattermost.atlassian.net/browse/MM-10737.
