### ISSUE TITLE
French description of "Do Not Disturb" is cut

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-server#8859]
#### Summary
In French, the description of "Ne pas déranger" (Do not disturb) mode is cut off.

#### Steps to reproduce
Using Mattermost version 4.10.0 (the issue is also present on a 4.6.0 version), set the language to French, then click on the status icon to open the status menu.

#### Expected behavior
All texts should be entirely displayed.

#### Observed behavior (that appears unintentional) 
The text that explains the Do Not Disturb mode is cut at the end.
![image](https://user-images.githubusercontent.com/8834237/40603452-3c0a6060-625c-11e8-9b99-806d38cc229a.png)

**Comment by jasonblais** [comment]
Hey @wget - is this something you'd be able to take a look at translate.mattermost.com?

**Comment by wget** [comment]
@jasonblais This is something I have already reported, but this hasn't been fixed.
I can remove the end `for mobile`, but this considers the user knows what is a push notification and that the latter only concerns mobile devices using the mobile application.

So instead of "Disable desktop notifications and push on mobile", I can translate as it: "Disable desktop notifications and push" is that enough/correct for you?

**Comment by jasonblais** [comment]
How about translating it as `Disables desktop and push notifications`?

> This is something I have already reported, but this hasn't been fixed.

That's correct and I believe there's a ticket for it.

**Comment by wget** [comment]
Yes, but unfortunately, this sentence cannot be built like this in French as `desktop` and `push` need to come afterwards.

Or maybe: "Disables notifications for desktop and for mobile". That way, we do not need to specify the term push (and somewhat explain that term with additional items). What do you think?

**Comment by jasonblais** [comment]
In English, that sounds good for me (except we would say `Disables notifications for desktop and mobile`, but the "for" for mobile may be relevant in Frenc)

**Comment by wget** [comment]
@jasonblais D***. Even when shortening as much as I can the final result doesn't look good: the text isn't centered. You see the white padding at the right is not the same as the one at the left. So I definitely think the size of the menu needs to be computed depending of the size of the items.
![screenshot_20180528_144811](https://user-images.githubusercontent.com/2997662/40615257-56008006-6286-11e8-9d84-fa8e377e909c.png)

**Comment by wget** [comment]
I definitely think the bug which has been filled to recompute on the fly the size of the drop down menu needs to be fixed in order for this issue to be properly resolved.

**Comment by moussetc** [comment]
For information, this minor issue is also here for the German translation:
![image](https://user-images.githubusercontent.com/8834237/40615429-fe73e8a4-6286-11e8-968e-e2e2bccee88c.png)
And also Turkish...
![image](https://user-images.githubusercontent.com/8834237/40615485-42ce0a7a-6287-11e8-8161-c51465136238.png)
Shortening the French translation might be a temporary fix only ;)

**Comment by hmhealey** [comment]
What about just using "Disables notifications"? Or can you still get emails when in Do Not Disturb mode?

**Comment by wget** [comment]
Ok. I translated as this: "Disable notifications (except e-mails)" and this suits the space.

Corrected. Closing.
