### ISSUE TITLE
html2text: needless fork

### ISSUE THREAD

**Issue by onlyjob** [mattermost/mattermost-server#8865]
html2text is a needless fork:

  * https://github.com/mattermost/html2text
  * https://github.com/mattermost/mattermost-server/tree/master/vendor/github.com/mattermost/html2text

Reason for forking is no longer valid: https://github.com/ssor/bom/issues/1

Needless forking is harmful. Please switch back to original project:

  https://github.com/jaytaylor/html2text

Fork is used only in one place:

  https://github.com/mattermost/mattermost-server/blob/master/utils/mail.go#L21

**Comment by cpanato** [comment]
Hello @onlyjob thanks for this update. I will make some tests and talk with @jasonblais to we move forward

**Comment by cpanato** [comment]
resolved in https://github.com/mattermost/mattermost-server/pull/8900
