### ISSUE TITLE
please update github.com/throttled/throttled

### ISSUE THREAD

**Issue by onlyjob** [mattermost/mattermost-server#8872]
Newer release of [github.com/throttled/throttled](https://github.com/throttled/throttled) is available and it [can not be imported](https://github.com/throttled/throttled/pull/32) as `gopkg.in/throttled/throttled.v2` any more so [imports](https://github.com/mattermost/mattermost-server/blob/master/app/ratelimit.go#L17-L18) would have to be updated to `github.com/throttled/throttled`.

**Comment by amyblais** [comment]
@crspeller Is this something you can help with?

**Comment by crspeller** [comment]
Nice catch @onlyjob. I will change the import paths next time I upgrade the server dependencies.

**Comment by crspeller** [comment]
Fixed by https://github.com/mattermost/mattermost-server/pull/8981

**Comment by onlyjob** [comment]
Thanks.
