### ISSUE TITLE
LDAP sync breaks if user's ldap id changed

### ISSUE THREAD

**Issue by hannu78** [mattermost/mattermost-server#8878]
#### Summary
One user's LDAP username was changed and it caused Mattermost server LDAP configuration change and MM server restart during manual LDAP sync.

Mattermost server version: 4.9.3
Platform Debian Jessie 8.10 linux 64-bit
openldap-2.4.40
License: Enterprise edition

#### Steps to reproduce
1. Connect Mattermost to OpenLDAP
2. Change one user's username in LDAP (such user that has already been sync'd to Mattermost)
3. Sync LDAP manually from Mattermost System Console

#### Expected behavior
Use's username changes to new one.

#### Observed behavior (that appears unintentional) 
Mattermost server was restarted at the time of LDAP sync. At the same time the changed user's Mattermost id and password got written to server's config.json in LdapSettings sections:

"IdAttribute": "uid",
"PositionAttribute": "",

User's Mattermost uid went into IdAttribute and his password from LDAP into "PositionAttribute". Config file was not edited manually during the operations but server restart timestamp and modification timestamp of the config file matched.

This problem caused next LDAP syncs to sync only this one user's account and it didn't validate other user's LDAP crendentials anymore. Existing sessions stayed but no new sessions could be created as most of our regular users are from LDAP. Only after those two attributes were put back to the values above, the LDAP sync sync'd all users again. 

#### Possible fixes
-

**Comment by amyblais** [comment]
Hi @hannu78! Thank you for reaching out.

Can you help provide the following additional information as the first step:

1. Your LDAP settings from config.json (with sensitive info such username/password removed).
2. Your AD/LDAP server and version (e.g. Active Directory on Windows Server 2016).
3. Enabling debug logging and then running the sync from the admin console and attaching all of the Mattermost logs.
4. Taking a look at this doc to see if there is anything that might help: https://docs.mattermost.com/deployment/sso-ldap.html.

For a reference, there is also an open ticket to investigate LDAP login identifier issues: https://mattermost.atlassian.net/browse/MM-4998.

Happy to help investigate this further - let me know any questions!

**Comment by amyblais** [comment]
Hi @hannu78! Following up here - have you still experienced issues with LDAP sync?

**Comment by amyblais** [comment]
Hi @hannu78, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
