### ISSUE TITLE
[Help Wanted] [MM-10270] Number format in yaml specifies integer type for create_at, update_at, delete_at but returns int64

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8879]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10270)

Original Github report: https://github.com/mattermost/mattermost-api-reference/issues/345

"If the data coming back from the API is an int64, as it appears to be, the optional format flag should be used to specify it as int64, not just integer (which assumes int32). See
https://swagger.io/docs/specification/data-models/data-types/."

**Comment by phuihock** [comment]
I take this one.

**Comment by zeroimpl** [comment]
This appears to have already been resolved via duplicate issue MM-10605. See https://github.com/mattermost/mattermost-api-reference/pull/368.

**Comment by jasonblais** [comment]
Good catch @zeroimpl - closing.
