### ISSUE TITLE
4.10.0: fork of spf13/viper imported from original library path

### ISSUE THREAD

**Issue by onlyjob** [mattermost/mattermost-server#8883]
I run into another dependency problem in 4.10 - [fork](https://github.com/mattermost/viper) of [github.com/spf13/viper](https://github.com/spf13/viper) that is [imported from original library path](https://github.com/mattermost/mattermost-server/blob/master/Gopkg.toml#L49-L50). Downstream it creates practical problem of building Mattermost with reusable _spf13/viper_ library let alone abomination of library name space...

Therefore, please:

### Import the library from its own path without faking the original library.

Counterfeiting original library is ugly and wrong. Please don't do that.

### Make sure that fork is _really_ necessary and first try to work with developer of the library to avoid needless forking.

On this instance, forking _spf13/viper_ seems unnecessary because it is actively maintained.

**Comment by onlyjob** [comment]
FYI @hmhealey.

**Comment by hmhealey** [comment]
Hi @onlyjob,

I didn't realize that I forgot to change those references. We still need our fork since we added some functionality that hasn't been accepted back into the main repository yet.

I've filed a Jira ticket to track this better which I'll hopefully get to later this week.
https://mattermost.atlassian.net/browse/MM-10769

**Comment by amyblais** [comment]
Closing this issue for now as it can be tracked with the Jira ticket linked above.

**Comment by onlyjob** [comment]
I would prefer you to close this ticket when issue is actually fixed.

**Comment by onlyjob** [comment]
Here is upstream merge request which seems to be a reason for forking: https://github.com/spf13/viper/pull/479

**Comment by crspeller** [comment]
Resolved in: https://github.com/mattermost/mattermost-server/pull/8948

**Comment by onlyjob** [comment]
Thanks. :)
