### ISSUE TITLE
LICENSE refers to non-existent directories

### ISSUE THREAD

**Issue by onlyjob** [mattermost/mattermost-server#8885]
https://github.com/mattermost/mattermost-server/blob/master/LICENSE.txt#L15

**Comment by onlyjob** [comment]
Scope of _Apache-2.0_ could be better defined. Perhaps it would be better just to put `LICENSE` file into corresponding directories.

**Comment by amyblais** [comment]
Hi @onlyjob, giving you an update that this Issue will be discussed by our managers in a few days. Also the other two License.txt Issues that you opened are under discussion currently.

**Comment by hanzei** [comment]
This is fixed on `master`.
