### ISSUE TITLE
luximbi.ttf: non-free?

### ISSUE THREAD

**Issue by onlyjob** [mattermost/mattermost-server#8892]
`fonts/luximbi.ttf` is `Copyright (c) 2001 by Bigelow & Holmes Inc. Instructions copyright (c) 2001 by URW++` and __no license__ which makes it "non-free" due to implicit "All Rights Reserved".

Please either remove this font or document its license and origin.

**Comment by amyblais** [comment]
Hi @onlyjob! Thank you for finding this!

We discussed this as a team and decided to open a bug ticket to fix this: https://mattermost.atlassian.net/browse/MM-10766.

**Comment by amyblais** [comment]
Good question - our engineers follow Jira tickets for bugs that need to be fixed - I'll be closing this Issue soon.

**Comment by amyblais** [comment]
@onlyjob - We would like to recognize your contribution in finding this bug by awarding you a [Bug Hunter coin](https://forum.mattermost.org/t/mattermost-bug-hunter-awards/4979)!

Wondering if you would like to help with your address and phone number? You can give me the information at our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=kzpxpmpgjpr7dja477sf6t948e) and message me privately (@amyblais), or you can send me an email at amy.blais@mattermost.com.

Let me know any questions!

**Comment by amyblais** [comment]
Hi @onlyjob! 

Just following up on this - do you have any questions or concerns regarding the above note (Bug Hunter coin)?

In the meanwhile, we have started to discuss the other Issues that you have recently opened, including next steps for each.

We appreciate all the time you have taken to find these issues!

**Comment by onlyjob** [comment]
Thanks, @amyblais. Perhaps I'm too old to feel properly excited about the coin so I'll pass. However donations in AUD, LTC or BTC are always welcome. ;)

**Comment by amyblais** [comment]
No worries - I would like to let you know again that we appreciate you taking the time to find these different bugs/issues.

We will continue discussion as a team on the other Issues you have recently opened.

**Comment by grundleborg** [comment]
This has now been fixed in master and so will be fixed in the next releaes - 5.1. Thanks for bringing it to our attention @onlyjob
