### ISSUE TITLE
channel references (~ tilde) don't become links until 'more' button is clicked

### ISSUE THREAD

**Issue by jaythespacehound** [mattermost/mattermost-server#8899]
#### Summary
A channel referenced by using the ~ syntax (e.g. ~test) does not become a clickable link in the web client for other users until they press the 'more' button under 'public channels'

#### Steps to reproduce
v 4.10.1 and prior:
Requires two users to reproduce, here U1 and U2:
U1: make new channel (e.g. test)
U1: link/reference channel in 'town-square' using tilde: (e.g. join channel ~test)
U2: receives message tries to click ~test

#### Expected behavior
~test is a clickable link

#### Observed behavior (that appears unintentional) 
~test is not clickable for U2 (it does not become a link)
If U2 clicks the 'more' button under 'public channels' on the left sidebar ~test immediately turns into a link.

**Comment by amyblais** [comment]
Hi @jaythespacehound! Thank you for reaching out.

We can try to test this out, but just wanted to clarify a few more details:

Does this happen in webapp / desktop app / mobile app or across devices?

In the scenario that you described above, is either U1 or U2 a System Admin (or both or neither)?

**Comment by jaythespacehound** [comment]
I have tested only webapp, android app, and windows 10.
Same behaviour in all three.
I have tried with either U1 or U2 being sys admin and with neither. Same behaviour.

**Comment by amyblais** [comment]
Strange indeed. I'm able to repro but it doesn't happen every time, plus it seems to happen only after I log out and back in again and some of the tilde links are suddenly not links anymore.

Can you confirm if you see this after you log out and back in again, or does it happen straight away when someone posts the tilde link and you attempt to click it? Does it happen with all tilde links or just some?

**Comment by jaythespacehound** [comment]
Happens independent of fresh log in or not for all channels.
But only applies for new channels. If you've ever joined the channel in the past tilde links will always work in future (even if you've left it).

For channels you have (for lack of a better word) 'initialised' the link for by pressing 'more' all tilde links will work until log out and back in, at which point they stop working (for that channel) until 'more' is pressed.

At least that's the behaviour I'm seeing.

**Comment by amyblais** [comment]
Hi @jaythespacehound! Thank you for the additional info - seems that I'm also seeing this now even if I don't log out and it does seem to happen only in new channels.

Since I'm able to repro this I created a ticket: https://mattermost.atlassian.net/browse/MM-10789.

I will close this Issue for now as it can be tracked with the ticket linked above.
