### ISSUE TITLE
[Help Wanted] [MM-10745] Add checks for missing translation strings

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8906]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10745)

The server, web, and mobile apps need automated checks to confirm that translation strings have been properly added to the internationalization files when they're added to the UI

**Comment by jespino** [comment]
It will be done automatically by the new translations extraction mechanism.

**Comment by jasonblais** [comment]
@jespino Can this ticket be closed?

**Comment by jespino** [comment]
Yes :)
