### ISSUE TITLE
Issue joining default channels when the Off-Topic channel is renamed

### ISSUE THREAD

**Issue by brocoli** [mattermost/mattermost-server#8910]
#### Summary
When a new user joins a team, if the Off-Topic channel is renamed, Mattermost is unable to make them join the channel.

#### Steps to reproduce
Rename the default Off-Topic channel to something different, and have a new user create an account via email.

Version information:
Mattermost Version: 4.10.0
Database Schema Version: 4.10.0
Database: postgres

#### Expected behavior
The user should join the renamed Off-Topic channel

#### Observed behavior (that appears unintentional) 
The user does not join the renamed Off-Topic channel
The following line appears in the Logs feed:
```json
{"level":"error","ts":1234567890,"caller":"app/team.go:354","msg":"Encountered an issue joining default channels user_id=<some_hash>, team_id=<some_hash>, err=SqlChannelStore.GetByName: Channel does not exist, teamId=<some_hash>, name=off-topic, sql: no rows in result set","user_id":"<some_hash>"}
```

#### Possible fixes
Add a way to configure default channels for a team, preferably in the Team Settings screen.

The most relevant file is `app/channel.go`. The names `"town-square"` and `"off-topic"` are hardcoded.

**Comment by amyblais** [comment]
Hi @brocoli! Thank you for reaching out.

Looks like I'm not able to reproduce this.

What happens when a new user creates an account and tries to join Mattermost? Do they get an error message or a blank screen or something else?

**Comment by amyblais** [comment]
Hi @brocoli, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
