### ISSUE TITLE
Preview for ".yaml" but not for ".yml"

### ISSUE THREAD

**Issue by trash-anger** [mattermost/mattermost-server#8922]
#### Summary
There's no preview for yaml files with yml extension.

#### Steps to reproduce
Uploading a .yml file.

#### Expected behavior
It could be great to add the preview for files with extension .yml, there's more current than the .yaml and both are relevant. I saw in the code that yml is an alias of yaml, line 1174 :
https://github.com/mattermost/mattermost-webapp/blob/402808622c42b9101142235f44a56673c8fefabc/utils/constants.jsx

#### Observed behavior (that appears unintentional) 
![image](https://user-images.githubusercontent.com/7171011/41040703-73619068-699d-11e8-8dc6-968c5f04b1ab.png)

#### Possible fixes
I think the modification to make should be by there : 
https://github.com/mattermost/mattermost-webapp/blob/e76203baa0d85d772aeb47e276c249049d686347/utils/syntax_highlighting.jsx

**Comment by amyblais** [comment]
Hi @trash-anger! Thank you for reporting this.

To give you the best help we can, would you be able to provide the following additional information:
1. Your Mattermost server version
2. If you are using webapp / desktop app / mobile app

**Comment by trash-anger** [comment]
### Server : 
- Version: 4.7.1 (4.7.3)
- Database: postgres
- Build Hash: 659ce8c60012a7d5fd597997b1794ac512b3b155
- Build Date: Thu Mar 8 19:42:47 UTC 2018

### Front : 
- I'm using the webapp, the desktop app and both android and android beta app.
- Desktop app version: 4.0.1
- I think webapp version depend on the server version ...
- I think the preview is not implemented yet in the mobile app

**Comment by amyblais** [comment]
Hi @trash-anger! Thank you for the additional information.

Would you like to do a quick test at our [testing server](https://rctesting.reddogsofwar.com/signup_user_complete/?id=boxf78odd7dh9pow6wtr8pg9qh), on both mobile and webapp/or desktop app? It's on the latest version (v5.0 postgres).

My apologies, I don't mean to take too much of your time, but I'm not familiar with .yml files and I was wondering if you can do a quick test on the latest server version in case we have added support for .yml previews in one of our latest versions.

If you see the same issue on the latest version, just let me know and I will create a ticket for our engineers to fix this.

**Comment by trash-anger** [comment]
The issue is still occuring : 
![image](https://user-images.githubusercontent.com/7171011/41108972-2a75bad0-6a76-11e8-82c1-9a81c7b24d45.png)

**Comment by amyblais** [comment]
Thank you @trash-anger! 

Just to confirm, when you click on the .yaml file it will show a preview, but not for the .yml file?

**Comment by amyblais** [comment]
Hi @trash-anger!

We haven't received an update for a while, so I'll close this Issue for now. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
