### ISSUE TITLE
Video Player doesn't work with 4.x when server is installed on CentOS 7

### ISSUE THREAD

**Issue by DeviantEng** [mattermost/mattermost-server#8929]
#### Summary
Video player, when trying to watch an uploaded video, does not appear to work when mattermost-server is installed on CentOS 7.

#### Steps to reproduce
Install CentOS 7, install MariaDB, install Mattermost 4.10.1.

#### Expected behavior
I expect videos to play within the OSX or Android apps, or within a browser. 

#### Observed behavior (that appears unintentional) 
Videos won't play, and it just tries to download the file.  

#### Possible fixes
???

#### Other notes
I did a test install on a Debian Stretch (9) instance, and video player works just fine.  Video player does not work when Mattermost server is install on CentOS 7, regardless of version 4.8.0, 4.10.1, or 5.0.0-rc1, enterprise or team edition.

Here is an imgur album showing what I see when I upload and try to view a video file (mp4):
https://imgur.com/a/kDrzcbc

Here is my post on the support forums that might provide additional info:
https://forum.mattermost.org/t/in-client-video-player/5093/7

**Comment by amyblais** [comment]
Hi @DeviantEng! 

In addition to the information you have sent over here and previously, would you be able to send any Mattermost logs or check the Console for any errors while attempting to watch an uploaded video?

Let me know any questions!

**Comment by DeviantEng** [comment]
@amyblais, in testing this yesterday, I did run Mattermost via console to watch for logging and never saw any logs when trying to watch an uploaded video.  May need to increase logging level (mind sharing how this is done, else I'll look in the docs to see if I can find it), but was really hoping someone else could spin up a CentOS 7 instance and test themselves to see if they have the same issue.  Me and a colleague have each tested this in CentOS 7 LXC containers, and both have the same experience where uploaded videos will not play but instead try to download.

Thanks.

**Comment by amyblais** [comment]
Hi @DeviantEng! I just now realized that you are using MariaDB, which we currently do not support, so I'm wondering if this issue could be related to that?

**Comment by DeviantEng** [comment]
@amyblais Yes, I am using MariaDB which is a 100% drop-in DEFAULT replacement on EL (Red Hat, CentOS, Scientific Linux, Fedora).  I highly doubt that that would be causing any issues since message history and everything else is working just fine, but I can definitely test.  

Just FYI:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/selinux_users_and_administrators_guide/chap-managing_confined_services-mariadb

But to be thorough, I will test out MM with postgres on CentOS 7 and see what happens.

Is it possible that you (or someone else) can also test a CentOS 7 install to see what behavior you see?

**Comment by amyblais** [comment]
@DeviantEng 

No worries, it was an observation I made as I remembered that we don't support MariaDB, but definitely not necessarily related to the issue.

Certainly I will test this, or ask a colleague to help test!

**Comment by amyblais** [comment]
Hi @DeviantEng! There was a team discussion on this and we are thinking that this might be a server configuration issue.

You can see more details on [this old ticket](https://mattermost.atlassian.net/browse/MM-5101) - basically a recommendation would be to install a media player or other browsers on the server which would add the missing mime types and make it work.

We had also earlier added some steps to our [troubleshooting docs](https://github.com/mattermost/docs/pull/981/files) related to this issue but had removed them later because we weren't 100% sure of the exact troubleshooting steps at the time.

**Comment by sunnythaper** [comment]
I am running into this same issue and according to the official Dockerfile, mailcap is installed already:

https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile

All I can do is download the video no matter where I click.

**Comment by jasonblais** [comment]
@sunnythaper I'm not too familiar with the Docker set up, but are you able to check if mime types were installed successfully in `/etc/mime.types`?

**Comment by arunoruto** [comment]
I am running the gitlab integrated mattermost service and was wondering how to make this run.
