### ISSUE TITLE
referencing channel in macOS is broken for channels beginning with `n` and `a`

### ISSUE THREAD

**Issue by SimJoSt** [mattermost/mattermost-server#8931]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Using the channel shortcut `~` poses usability challenges on macOS with channels beginning with `n` or `a`.

#### Steps to reproduce
1. Use macOS
2. Type `~` (by pressing alt+n)
3. Start typing a channel beginning name with `n` or `a`

#### Expected behavior
A channel should be referenced, by having a string like `~newchannel`

#### Observed behavior (that appears unintentional) 
No channel is referenced, as macOS merges the `~` and `n` or `a` to either `ñ` or `ã`.

#### Possible fixes
This change was introduced with [Jira-Ticket MM-1618](https://mattermost.atlassian.net/browse/MM-1618). Originally a preceding `!` was proposed.
Or the usage of `#`, overriding the usage as a tag, if a channel by the same name exists.
I have no knowledge of forcing/changing the behaviour of macOS from a web application regarding this issue.

**Comment by amyblais** [comment]
Hi @SimJoSt! Thank you for reporting this.

To give you the best help I can, could you also help with the following additional details:

1. What is your Mattermost server version?
2. Are you seeing this on webapp or desktop app or both?

I was just testing with ``alt+n`` and it appears that it doesn't work with any letters so I'll need to find out what is the expected on that as well.

**Comment by amyblais** [comment]
Hi @SimJoSt, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by SimJoSt** [comment]
Sorry, didn't see the notification.

1. Mattermost server version 4.9.2
2. The problem exists on both the web as well as the desktop app.

It is dependend on anything Mattermost does or doesn't do. It's macOS thing.
If you enter `~` and directly after enter a button that can be extended with the tilde, it will merge them.

**Comment by amyblais** [comment]
Hi @SimJoSt would you be able to test if you see this issue on the [latest version](https://about.mattermost.com/download/). You can test on our [community server](https://community.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) if you prefer not to upgrade at this point.

**Comment by SimJoSt** [comment]
@amyblais I have upgraded to 5.20.0 an the problem still persists.  
As I said, it's not a Mattermost specific thing, but a macOS one. To right `ñ` and `ã` you would press `Option`/`alt`+`n` to get `~`. When the next letter is an `a` or an `n` without pressing the spacebar first, the `~` is converted to `ñ` or `ã` respectively.  
If the issue is not clear, I'll gladly create a screen recording.
