### ISSUE TITLE
Version number issue displayed (4.10.0 displayed while 4.10.1 installed)

### ISSUE THREAD

**Issue by florianproxi** [mattermost/mattermost-server#8932]
Hello, I updated mattermost 4.10.0 in 4.10.1 everything seems to work as it should. But going on About since Mattermost it always tells me 4.10.0, is this normal?

**Comment by amyblais** [comment]
Hi @florianproxi!

To give you the best help I can, could you help with the following additional details:

1. What OS and version is the Mattermost server installed?
2. Can you confirm if you followed the upgrade documentation (https://docs.mattermost.com/administration/upgrade.html or https://docs.mattermost.com/install/ee-install.html)?

Let me know any questions!
