### ISSUE TITLE
GetTeamByName and GetChannelByName - these search by internal name, not display name

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#8941]
#### Summary
`GetTeamByName` and `GetChannelByName` functions search by `name` column in database, not `displayName`. This leads to confusion as to why a team or channel is not getting found. A `name` is (as far as I can see) hyphenated-lowercase version of `displayName`.

#### Steps to reproduce
From a plugin use either of `GetTeamByName` or `GetChannelByName` function to search for a team or channel respectively using its display name ("Town Square", "Team 1" for example).

#### Expected behavior
I should be able to search for a channel or team via its display name.

#### Observed behavior (that appears unintentional) 
I'm unable to search for a channel or team via its display name.

#### Possible fixes
There are two possibilities here -
* Retain current behavior of `GetTeamByName` and `GetChannelByName` and add two new APIs - `GetTeamByDisplayName` and `GetChannelByDisplayName`, or
* Modify `GetTeamByName` and `GetChannelByName` to search using `displayName` instead of `nane`.

I'd go for the first approach as it won't break existing clients.

Please refer to following parts of code which cause this issue -
* Channel - https://github.com/mattermost/mattermost-server/blob/9517cccab017f67db973ef4a601de68656ce1713/store/sqlstore/channel_store.go#L849
* Team - https://github.com/mattermost/mattermost-server/blob/9517cccab017f67db973ef4a601de68656ce1713/store/sqlstore/team_store.go#L277

**Comment by amyblais** [comment]
Hi @harshilsharma63! Thank you for reporting this.

I will ask our team's opinion on what would be the best next step regarding this.

**Comment by harshilsharma63** [comment]
Another point, the fact that `name` is lowercase hyphenated version of `displayName` is only true for channel/team name which was used at the time of creation.

For example if I create a team named "Team 1" its `name` would become `team-1` and `displayName` `Team 1`. Now, if I update the team's name to "Team 1 - Developers" its `name` will remain the same `team-1` while only `displayName` is updated (which seems the right thing to do).

The problem this creates is that if I would like to obtain a channel name from user to post stuff into, I'd never reliably obtain the channel's ID via its name as all APIs search by `name` instead of `displayName`.

**Comment by hmhealey** [comment]
Hi @harshilsharma63,

We're consistent that methods that are "ByName" refer to the Name field and not the DisplayName field for whatever the object, so we wouldn't be changing those, but I could see adding additional methods.

May I ask what you're wanting those for? We only consider the web and plugin APIs as public for things like backwards compatibility, so I'd be interested if you're using the store API for something.

**Comment by harshilsharma63** [comment]
@hmhealey that makes sense.

In my case, I'm building a mattermost server plugin that would post some notifications to a specified channel, which is to be provided by the user. I was thinking that for the user, providing the display name for channel and team would be more user-friendly compared to finding their slugs.

I'm fine with using slugs right now though as I've already completed the plugin.

**Comment by hmhealey** [comment]
Ah, I knew I forgot one of the APIs. I'll forward the idea on to the people in charge of the plugin APIs since I believe there's some changes coming to them in the upcoming release

**Comment by hmhealey** [comment]
Also, if you're wanting to chat more about this, show off your plugin (assuming it's not private), or just say hi, feel free to join us on https://pre-release.mattermost.com, our public Mattermost server that we use every day. For more general discussion, we have the ~Developers and ~Contributors channels, and there's also the ~Developer-Toolkit channel where we discuss the plugin framework and the changes we're going to be making to it in the upcoming release

**Comment by harshilsharma63** [comment]
@hmhealey sure. Closing the issue now.
