### ISSUE TITLE
Upgrade 4.6.3 => 4.10 broke postgres connection

### ISSUE THREAD

**Issue by fmp777** [mattermost/mattermost-server#8945]
#### Summary
Postgres does not connect after upgrade when password contained certain characters.  Don't worry this password is trashed now so is safe to share.  

#### Steps to reproduce
The password that didn't work: r2Ti8nHna{b+irhnW(jr
This was the connection url: postgres://mmuser:r2Ti8nHna{b+irhnW(jr@localhost:5432/mattermost?sslmode=disable&connect_timeout=10  (in config it has \u0026 in place of &)

Because I was doing many things at same time, my memory on this is fuzzy, but it MIGHT'VE worked following the upgrade procedure documented here https://docs.mattermost.com/administration/upgrade.html - as I do recall logging in, to process step 13 (updating config schema)  -  so it might've occurred after the config schema was regenerated.  

While debugging I did a diff between my backup config.json and the new one after updating schema and it showed no difference, so I dismissed that.

#### Expected behavior
Connection without error.

#### Observed behavior (that appears unintentional) 
{"level":"error","ts":1528828419.1320748,"caller":"sqlstore/supplier.go:206","msg":"Failed to ping DB, server will exit err=parse postgres://mmuser:r2Ti8nHna{b+irhnW(jr@localhost:5432/mattermost?sslmode=disable&connect_timeout=10: net/url: invalid userinfo"}

#### Possible fixes
I am guessing the + in the password is the culprit but very well could be brace or parenthesis.  I had tested the connection to the database using the user and password in command line and all was working properly, there was no invalid userinfo.  Only when I changed the password to something without those symbols did it connect without complaint.

**Comment by amyblais** [comment]
Hi @fmp777! Thank you for reaching out.

To get started, can you help review these ["Important upgrade notes"](https://docs.mattermost.com/administration/important-upgrade-notes.html) and take a look if you catch anything that might apply to you?

**Comment by fmp777** [comment]
Hmm no, nothing applicable to my case

**Comment by amyblais** [comment]
Hi @fmp777,

Checked with an engineer about this and it seems that you need to escape special characters in your password, ie, in the ``xxx[]xxx`` will be ``xxx%5B%5Dxxx``.

You can see a brief thread/discussion about this on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) in the [Bugs channel](https://pre-release.mattermost.com/core/pl/w8gzzcs6u7fijysyjmgmz556oc).

**Comment by amyblais** [comment]
Hi @fmp777 - Following up - let me know if the above helps or if you have any questions? ^

**Comment by fmp777** [comment]
yes escaping works, just wanted to be sure you guys knew of the bug, took awhile to figure out what went wrong after update, good one to nip quick

**Comment by amyblais** [comment]
Glad to hear the issue was resolved!

I opened a PR to add a note about this to our upgrade docs: https://github.com/mattermost/docs/pull/2120.

Devs will review it and let me know if other action is needed.

**Comment by amyblais** [comment]
Hi @fmp777! A note about this has been added to the documentation: https://docs.mattermost.com/administration/important-upgrade-notes.html.

Thank you for reporting this!
