### ISSUE TITLE
Unable to add emoticons or click on channel list after expanding the message details sidebar

### ISSUE THREAD

**Issue by gpaddis** [mattermost/mattermost-server#8961]
#### Summary
After I expand the "message details" on the right sidebar, I cannot add emoticons or select a channel from the list on the left sidebar. I think that was possible up until the latest update.

#### Steps to reproduce
Mattermost 5.0.0:
- Click on the reply button on a conversation to open the sidebar "Message Details"
- Click on the double arrow icon on the top right to expand the sidebar
- Try to add an emoticon to an existing message with the smiley icon beside the message
- Try to click on a channel in the list on the left sidebar

#### Expected behavior
- Clicking on the smiley icon should open a popup to add an emoticon to the message selected
- Clicking on a channel in the list should collapse the message details sidebar and open the channel

**Comment by amyblais** [comment]
Hi @gpaddis! Thank you for reporting these!

I'm able to repro the issues so I created tickets for both: https://mattermost.atlassian.net/browse/MM-10959 and https://mattermost.atlassian.net/browse/MM-10960.

Not 100% sure if these are already known issues, but nevertheless I'll let you know the progress on these tickets.

**Comment by amyblais** [comment]
Update:

https://mattermost.atlassian.net/browse/MM-10959 has been assigned to an engineer to work on, but I don't yet have an exact release date yet.

https://mattermost.atlassian.net/browse/MM-10960 was closed as invalid as this never used to work before / is expected.

**Comment by gpaddis** [comment]
Thank you for the update, @amyblais! 
I think 10960 would be a nice improvement anyway - to me, it feels intuitive to click on the grayed list of channels and expect the expanded conversation to shrink and leave space for the channel; I had in memory that this was how it used to be, but surely I was mixing it with something somewhere else.

**Comment by amyblais** [comment]
Hi @gpaddis! 

For MM-10960, if you want to, you can [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/)! You get 10 votes and each one influences the future of the project. If you decide to open a feature request, please include a link back to this GitHub issue. If you're interested in implementing the improvement, please say so and we'll prioritize the review.

**Comment by amyblais** [comment]
Hi @gpaddis! Letting you know that https://mattermost.atlassian.net/browse/MM-10959 has been submitted and the fix is available in 5.1.

5.1 will be released in July 16th.

I'll close this Issue for now since the fix is available soon. If you encounter the bug after upgrading to 5.1, please reopen this Issue.
