### ISSUE TITLE
[Help Wanted] [MM-10957] Allow webhook message attachments to trigger mentions

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8964]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10957)

Mentions don't work if they're in any of the following fields. Propose they do trigger mentions.

```
        Attachments: attachments{
            attachment{
                Pretext:     "@here | This is optional pretext that shows above the attachment.",
                Text:        "@here | This is the text of the attachment. It should appear just ..."
```

Note that they do work if you just use the standard text: field.
```
    dataMap := payload{
        Channel:  "hyrule",
        Username: "Navi",
        Text:     "@here | Not the attachment text",
         }
```

![image](https://user-images.githubusercontent.com/13119842/41625894-7c19658c-73e8-11e8-85f5-740705df690b.png)

**Comment by pradeepmurugesan** [comment]
I can start to look into this.. 

Any code pointers would be helpful.  Thanks.

**Comment by jasonblais** [comment]
Thanks for your interest @pradeepmurugesan! 

For technical advice or questions, I recommend [joining our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers). You'll get faster responses there, as the channel is quite active by community and core committers.

**Comment by jasonblais** [comment]
Thanks @pradeepmurugesan!
