### ISSUE TITLE
babel: command not found

### ISSUE THREAD

**Issue by Ppjet6** [mattermost/mattermost-server#8965]
#### Summary

npm install call fails with `sh: babel: command not found` when building for production.

tag: v5.0.0

#### Steps to reproduce

```
git clone github.com:mattermost/mattermost-webapp && cd mattermost-webapp
git checkout v5.0.0
NODE_ENV=production make build
```

#### Expected behavior

JS files get generated in `dist/`

#### Observed behavior (that appears unintentional) 

```
ppjet@caska ..ithub.com/mattermost/mattermost-webapp (git)-[tags/v5.0.0] % NODE_ENV=production make build
Getting dependencies using npm
npm install
added 183 packages from 465 contributors and audited 75882 packages in 10.813s
found 24 vulnerabilities (1 low, 16 moderate, 5 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
cd node_modules/mattermost-redux; npm run build

> mattermost-redux@1.2.0 build /home/ppjet/go/src/github.com/mattermost/mattermost-webapp/node_modules/mattermost-redux
> babel src --out-dir . 

sh: babel: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE 
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mattermost-redux@1.2.0 build: `babel src --out-dir .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mattermost-redux@1.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ppjet/.npm/_logs/2018-06-19T15_38_44_602Z-debug.log
make: *** [Makefile:19: .npminstall] Error 1
NODE_ENV=production make build  14.08s user 1.95s system 135% cpu 11.825 total
```

#### Possible fixes

Doing `make build` before `NODE_ENV=production make build` seems to pull the correct dependencies first. What am I doing wrong? How do you build for prod?

**Comment by amyblais** [comment]
Hi @Ppjet6! Thank you for reporting this. I will ask our engineers about this.

**Comment by amyblais** [comment]
@AndersonWebStudio / @cpanato does this sound familiar to you to take a look at?

**Comment by cpanato** [comment]
hello @Ppjet6 
In the package.json the script that runs the build already set the `NODE_ENV=production` you dont need to set that.

however, I will check why in the first time if you hard set that it fails.

**Comment by cpanato** [comment]
I guess why because babel is a dev dependency and if you hard set that it will bypass the installation and it is needed to build.

**Comment by Ppjet6** [comment]
On 2018/06/20, Carlos Tadeu Panato Junior wrote:
> In the package.json the script that runs the build already set the NODE_ENV=production you dont need to set that.

Ok, I am confused. A few days ago I was hitting firefox being
cautious[0] when my mattermost deployment tried to reach socketcluster
on plain websocket, from an https page.

I had a look and apparently mattermost-redux only includes it in the
development build. So I added `NODE_ENV=production` when building
`-webapp` and it worked, or I thought. I can't reproduce the error
anymore. Maybe I was building on 4.10 and then tried on 5.0..

> I guess why because babel is a dev dependency and if you hard set that it will bypass the installation and it is needed to build.

Yes that's also what I assumed, dev dependencies not being pulled.

If the recommended way to build is just `make build` then I guess it's
fine. Sorry for the noise.


[0]: https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue

-- 
Maxime “pep” Buquet

**Comment by amyblais** [comment]
Sounds like the issue is resolved - if I'm wrong, or you encounter any other issues, feel free to reopen this ticket or open a new one!
