### ISSUE TITLE
SIGSEGV: segmentation violation - crash after startup 

### ISSUE THREAD

**Issue by Manawyrm** [mattermost/mattermost-server#8969]
#### Summary
After a reboot of the linux machine, mattermost doesn't start (either manually or via systemd), it instantly crashes with a segmentation fault. 
It has worked fine before, even after a reboot. 

#### Steps to reproduce
I'm using: 
Version: 4.9.0
Build Number: 4.9.0
Build Date: Sat Apr 14 03:08:33 UTC 2018
Build Hash: 3176e13b1f9b14192bef2337ff3fb9346f26ef66
Build Enterprise Ready: true
DB Version: 4.9.0

on Ubuntu 18.04 LTS with MariaDB as the database. 

#### Expected behavior
No seg. faults on startup :-) 

#### Observed behavior (that appears unintentional) 
```
mattermost@mattermost:/opt/mattermost$ bin/platform
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xcf6748]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/app.(*App).removePlugin(0xc4200a1d40, 0x13e6862, 0x4, 0x352701, 0x3ffe00)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/plugin.go:264 +0x1e8
github.com/mattermost/mattermost-server/app.(*App).InitPlugins(0xc4200a1d40, 0xc4215cfac0, 0x9, 0xc4215cfae0, 0x10, 0x0)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/plugin.go:421 +0x499
github.com/mattermost/mattermost-server/cmd/commands.runServer(0x13f6bce, 0xb, 0xc420086d00, 0xc420086de0, 0x0, 0x0)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/commands/server.go:91 +0x87b
github.com/mattermost/mattermost-server/cmd/commands.serverCmdF(0x24800c0, 0x24ba100, 0x0, 0x0, 0x0, 0x0)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/commands/server.go:53 +0x10d
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x24800c0, 0xc420064160, 0x0, 0x0, 0x24800c0, 0xc420064160)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:753 +0x475
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x24800c0, 0x0, 0xc420000260, 0xc42004bf40)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(0x24800c0, 0xc420064160, 0x24962a8)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:791 +0x2b
github.com/mattermost/mattermost-server/cmd.Run(0xc420064160, 0x0, 0x0, 0xc420000180, 0x1109719)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/cmd.go:14 +0x6d
main.main()
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/main.go:33 +0x63
mattermost@mattermost:/opt/mattermost$
```

Any ideas? Thanks for your time!

**Comment by amyblais** [comment]
Hi @Manawyrm! Thank you for reaching out.

As a first step, can you help review the ["Mattermost is not working"](https://docs.mattermost.com/process/support.html#mattermost-is-not-working-the-server-keeps-dying) section of our troubleshooting docs to see if that helps? If not, I'll ask our engineers for help.

**Comment by Manawyrm** [comment]
Hi @amyblais , 

I've already used that list to check for a source of the error. 
The same error listed in the first post is also given via the recommended "journalctl" commands. 
The server is only hosting Mattermost and has enough RAM. 

I'd appriciate any help from the engineering team :)

**Comment by SmartHoneybee** [comment]
> Version: 4.9.0

Not a "real" solution, but you could try to upgrade to a version `>= 4.10.0`.
Looks like #8692 added some checks, in particular a `!= nil` check in [`app/plugin.go#L264`][1], which might help you with your problem ([same line in `4.10.0`][2]).

[1]: https://github.com/mattermost/mattermost-server/blob/v4.9.0/app/plugin.go#L264
[2]: https://github.com/mattermost/mattermost-server/blob/v4.10.0/app/plugin.go#L264

**Comment by Manawyrm** [comment]
@SmartHoneybee it fixes my problem, so this definitely counts as a solution :-) 
Thank you very much, after updating to the new major release 5.0 my issues are gone and Mattermost works fine again :)
