### ISSUE TITLE
[Help Wanted] [MM-10995] Add support for underscores in team names

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8979]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10995)

Right now, they only support letters, numbers, and hyphens. They currently don't handle underscores because of when teams used to have their own subdomains.

**Comment by jasonblais** [comment]
We may not actually support this for now because FQDN's (fully qualified domain names) cannot have underscores. This might be problematic if we want to bring back sub-domains later.

Closing and keeping the ticket in the backlog for now.
