### ISSUE TITLE
Unable to Add new email invite

### ISSUE THREAD

**Issue by ashlz90** [mattermost/mattermost-server#8990]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary

This error keeps popping up when I attempt to send an email invite.
The following email addresses do not belong to an accepted domain: srobles823@yahoo.com. Please contact your System Administrator for details.

#### Steps to reproduce
Version: 4.6.0  (4.6.1)

#### Expected behavior
Unable to add new user via email invite.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Hi @ashlz90! Thank you for reporting this.

The error message means that your System Admin has restricted that domain (yahoo.com) from creating an account in your server. The new member should either use another email domain or you can contact your System Admin about changing the restriction on that domain. Let me know if that helps?

**Comment by ashlz90** [comment]
Hi Amy,

I also tried a gmail account she has. Mattermost didn’t utilize any of these restrictions when adding in other new members.
Who would my system administrator be?

Best Regards,

Ashley Pifer
Resort Manager

  [logo]

8678 North High Street
Columbus, Ohio 43235

Phone: 614-846-7100
Fax: 614-846-7101
Website: www.petsuitesofamerica.com<https://mail.nvanet.com/owa/redir.aspx?SURL=yQoa4MvLVmWmSRAufYPYM_OSL0ZcEzkuezQ6UPtGSQevCmLy-gfVCGgAdAB0AHAAOgAvAC8AdwB3AHcALgBwAGUAdABzAHUAaQB0AGUAcwBvAGYAYQBtAGUAcgBpAGMAYQAuAGMAbwBtAC8A&URL=http%3a%2f%2fwww.petsuitesofamerica.com%2f>

**Comment by amyblais** [comment]
Hi @ashlz90! I'm not sure who the System Admin of your server is. The System Admin would have access to the System Console to check settings and to help add new members to the system. Would you be able to ask the person who invited you to the server if they know who has a System Admin role?

**Comment by amyblais** [comment]
@ashlz90 - Also forgot to mention that another way to add new members to a team is by going to Main Menu > Get Team Invite Link > Copy Link, and then giving that link manually to the person (via email or other way).

**Comment by amyblais** [comment]
Hi @ashlz90, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
