### ISSUE TITLE
System Console allows Invalid Listen Address values

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost-server#8991]
#### Summary
Per [this forum post](https://forum.mattermost.org/t/solved-tcp-error-at-start/4025) the ListenAddress must contain a colon for it to be valid. However, the UI doesn't check for this, and the server will fail to start with a cryptic error message.

#### Steps to reproduce
1. Go to the system console of a Mattermost server
2. Set the value to `8065` and save the values
3. Restart the server

#### Expected behavior
Server is running on port 8065

#### Observed behavior (that appears unintentional) 
Mattermost fails to restart with this error in the log:

```
{"level":"error","ts":1529961281.7618864,"caller":"commands/server.go:112","msg":"listen tcp: address 8065: missing port in address"}
```

#### Possible fixes
 - Check the `ListenAddress` value when the user enters it for proper formatting
 - Ensure that the server properly handles a missing colon in the config value when starting up

**Comment by amyblais** [comment]
@icelander Were you able to repro this?

**Comment by icelander** [comment]
@amyblais Yes, I'm able to reproduce this on version 5.0

**Comment by amyblais** [comment]
If we can repro it internally you can create a Jira ticket.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-11301.
