### ISSUE TITLE
[Help Wanted] [MM-11040] Migrate to Flow file src/actions/general.js in mattermost-redux

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8996]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11040)

Mattermost is migrating mattermost-redux library to [Flow](https://flow.org/) and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate `src/actions/files.js` to Flow.

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/redux/redux-to-flow/)

You can also see an introductory video here: https://www.youtube.com/watch?v=kuHypTgU1ZY

If you need other examples you can see the PRs mattermost/mattermost-redux#488 and mattermost/mattermost-redux#489

**Comment by pepf** [comment]
Ill pick this one 👍

**Comment by jespino** [comment]
Awesome, Thanks! :)

**Comment by jespino** [comment]
Closed some time ago :tada:
