### ISSUE TITLE
[Help Wanted] [MM-9747] Support file attachments in bulk import

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9006]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9747)

Use case: A company migrates to Mattermost, and uses the bulk import tool to import existing data. Currently the bulk import tool doesn't support file attachments. This ticket adds support for them.

A patch created by the community, which is a good starting point: https://forum.mattermost.org/t/solved-uploading-an-image-with-api-v-4-not-working/4491

To know more about the bulk import data, you can see the documentation here: https://docs.mattermost.com/deployment/bulk-loading.html

You can also base the Attachment implementation in the ProfileImage implementation added here: mattermost/mattermost-server#8027

**Proposed changes:**

Add a new data type (not line type) Attachment, and include in each post or reply post a list of attachments.

Each attachment would have the information needed to create the attachment in mattermost, and the path of the attachment file in the local filesystem

**Comment by pradeepmurugesan** [comment]
I can give this a try.. I get an initial Idea of what we need to achieve.. 

I think some question might come up when starting to implement.

**Comment by jasonblais** [comment]
Sweet, thanks @pradeepmurugesan!

**Comment by saturninoabril** [comment]
Thanks @pradeepmurugesan!
