### ISSUE TITLE
[Help Wanted] [MM-10603] Workaround for links to access-restricted resources

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9008]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10603)

*Issue:*
When posting URLs which point to a resource that requires login, the preview of the login form is shown if preview is enabled. Also, when clicking such a link, the browser is in some cases handed a wrong URL. E.g. for a private gitlab instance which redirects all URLs to /users/sign_up when not logged in, all links pointing to that domain are rewritten by Mattermost to open the signup-page.

*Proposal:*
Always use the original URL to generate the link in the preview (not the result of the redirect).

*Original report:* https://forum.mattermost.org/t/mattermost-desktop-links-to-access-restricted-resources-not-well-handled/4903/8

**Comment by jasonblais** [comment]
Awesome, thank you @pietroglyph! 👍
