### ISSUE TITLE
Session expires without renewal after successful authentication via gitlab (ldap)

### ISSUE THREAD

**Issue by AlexanderWillner** [mattermost/mattermost-server#9023]
#### Summary
Session expires without renewal after successful authentication via gitlab (ldap)

#### Steps to reproduce
1. Login into mattermost.example.org > signing with gitlab
2. Redirect to mattermost.example.org/oauth/gitlab/login > gitlab.example.org/users/sign_in
3. Enter LDAP credentials

#### Expected behavior
User should always be authenticated while using the application (in the browser, mobile apps, ...).

#### Observed behavior (that appears unintentional) 
The use has to login after a while. Probably after the session times out. While the session should indeed have an expiration date, it should automatically be renewed while the user is using the service. Otherwise the whole meaning of having a collaborative chat application (e.g. running on iOS or in a window in the background) is undermined, as the user can't be sure that chat application sends notification in a reliable manner.

#### Possible fixes
Unknown.

**Comment by amyblais** [comment]
Hi @AlexanderWillner!

Thank you for reaching out. 👍 

To give you the best help we can, could you review [this web page](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues) and send us any additional relevant information you see that could help us diagnose the issue, e.g. your Mattermost server version, config settings, any log errors, etc.

**Comment by hmhealey** [comment]
Hi @AlexanderWillner. It sounds like you're running into the regular session length limits. I believe they're set to 30 days by default, but you can make them longer in the Security > Sessions section of the System Console. In particular, you'll want to change the "Session Length SSO" if you're using GitLab login. More information on those settings is [here](https://docs.mattermost.com/administration/config-settings.html#sessions)

**Comment by AlexanderWillner** [comment]
Hi @hmhealey, yes I assume the session expires. However, it seems (my current assumption) that the session is not automatically renewed when a user is using Mattermost. I.e., it doesn't matter how long the session is - at a given point in time it will expire and active users have to re-authenticate.

**Comment by amyblais** [comment]
@AlexanderWillner I remembered another report related to this recently and one of our product managers gave this reply: https://github.com/mattermost/desktop/issues/811#issuecomment-390983284.

Let me know if it helps?

**Comment by AlexanderWillner** [comment]
@amyblais Thanks. Actually, ```It is similar to your session on your bank account expiring after a fixed period of time``` - this is a good example. Using my online banking system, the session is renewed every time I click on something (i.e., after there is some activity from my side). Now image, the session would always time out after e.g. 10 minutes, regardless of whether a user is active or not. And this is imho what we experience here. The session always times out after a given timeout (```SessionLengthWebInDays``` or ```SessionLengthSSOInDays```), regardless of whether a user is chatting via gitlab or not.

**Comment by amyblais** [comment]
@AlexanderWillner There have been a few similar reports so I'll ask the team about this - can you help with details on what server version you use, and the versions of any apps that you use?

**Comment by AlexanderWillner** [comment]
Thanks. So if this is a absolute timer, there is nothing to fix here (i.e., works as expected) and I would close this issue. Maybe the documentation could be enhanced to reflect this security measure.

**Comment by amyblais** [comment]
Hi @AlexanderWillner - I've added to my to-do list to update our docs.

Our product managers also opened a ticket to improve user experience on this as we've seen other similar reports: https://mattermost.atlassian.net/browse/MM-11306

**Comment by AlexanderWillner** [comment]
Splendid. At https://github.com/mattermost/desktop/issues/811#issuecomment-404149609 it is also suggested to store credentials in the client to automatically login again.

**Comment by amyblais** [comment]
A fix for this issue was submitted for v5.4 release to notify users when their desktop/browser sessions expire: https://mattermost.atlassian.net/browse/MM-12205.
