### ISSUE TITLE
Notification E-Mails: Links and Channels not linked

### ISSUE THREAD

**Issue by dbrgn** [mattermost/mattermost-server#9024]
#### Summary

Links and Channels (`~channelname`) are not linked in notification e-mails.

#### Steps to reproduce

- Join a channel
- Subscribe to all notifications
- Write a message containing URLs and channel links, and mention `@all`
- You'll be getting a notification e-mail

#### Expected behavior

- In the HTML-Email, URLs should be linked
- Similarly, channel links should be resolved and linked to the channel URL

#### Possible fixes

Convert URLs and channel links into HTML before sending the notification E-Mail.

**Comment by dbrgn** [comment]
Might be related to https://mattermost.atlassian.net/browse/MM-10581

**Comment by amyblais** [comment]
Hi @dbrgn!

Thank you for reaching out 👍 

To give you the best help we can, could you review [this web page](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues) and send us any additional relevant information you see that will help us diagnose the issue, especially your server version, OS, device, etc?

**Comment by amyblais** [comment]
Hi @dbrgn! I tested this on v4.10 and v5.0 and this is what I see (see below screenshot).

Would you have a screenshot to share so I can compare with what you are seeing? Visualizing the issue in this case is helpful.

<img width="677" alt="test" src="https://user-images.githubusercontent.com/29708087/42064913-2750a6f8-7b06-11e8-8594-6b65dea44d5a.png">

**Comment by amyblais** [comment]
Hi @dbrgn! I'm able to repro the issue with channel links so I created a ticket: https://mattermost.atlassian.net/browse/MM-11102.

I'm not able to repro the issue with URLs, so possibly that's an issue in an earlier version (I tested this on v5.0).

**Comment by dbrgn** [comment]
@amyblais sure, here's a screenshot!

![screenshot](https://user-images.githubusercontent.com/105168/42078172-cf7c4286-7b7b-11e8-86ff-567a0548e403.png)

I just noticed that the emoji isn't converted either. The same message in the Mattermost webclient and in the app was properly processed.

**Comment by amyblais** [comment]
Hi @dbrgn! Apologies for late reply - giving you an update that the ticket to address the issue with channel links is under review by our product managers as it looks like this "feature" hasn't been implemented yet: https://mattermost.atlassian.net/browse/MM-11102.

I haven't been able to repro the issue with links, so I'm guessing that is an issue on an older version.

**Comment by amyblais** [comment]
Hi @dbrgn,

Again, thanks for the report! We have created a [Help Wanted issue here](https://github.com/mattermost/mattermost-server/issues/9399) and are looking for community's help. Let us know if you're interested in helping with a pull request!
