### ISSUE TITLE
Log Style and Timestamp broken

### ISSUE THREAD

**Issue by stephanfriedrich** [mattermost/mattermost-server#9037]
Hi i updated from Mattermost-server from "4.6.1" to "4.10.0" and since my Log within System-console (Webview) is broken  so i cant see the correct Timestamp see Example Log below

My server is an Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-128-generic x86_64).

```
{"level":"info","ts":1530127864.3477035,"caller":"jobs/schedulers.go:62","msg":"Starting schedulers."}
{"level":"error","ts":1530179094.8793137,"caller":"api4/context.go:222","msg":"/api/v4/channels/undefined/posts:Context code=400 rid=8ek7npzae3gbbxuhen89pmaxzh uid=dz1niok7f38wpym3k8dqayj8ac ip=95.91.242.112 Invalid or missing channel_id parameter in request URL [details: ]","user_id":"dz1niok7f38wpym3k8dqayj8ac"}
```

How can i Fix these.

**Comment by SmartHoneybee** [comment]
Hi,

as far as I know, those are Unix timestamps. The change is documented [here][0]:

> Server logs written to System Console > Logs and to the mattermost.log file specified in System Console > Logging > File Log Directory now use JSON formatting.

You can try: `jq '.ts |= strftime("%Y-%m-%d %H:%M")' your_mattermost.log`. (Details [here][1].)

Regards,
Bee

[0]: https://docs.mattermost.com/administration/important-upgrade-notes.html
[1]: https://stedolan.github.io/jq/manual/

**Comment by stephanfriedrich** [comment]
@SmartHoneybee thx for your response.
i know these are unix-timestamps.

**but i was wonderin** why mattermost-server change its default log-style to json and wont style the weblog correctly. seems to an style-issue for me

**Comment by SmartHoneybee** [comment]
According to the [documentation](https://docs.mattermost.com/administration/config-settings.html#output-console-logs-as-json) you should be able to switch to plain text output.

As for *why*, AFAICS, they wanted structured logging (https://github.com/mattermost/mattermost-server/pull/8673) and that logger is faster if you use JSON output.

**Comment by amyblais** [comment]
Hi @stephanfriedrich! Did `SmartHoneybee`'s suggestion help?

**Comment by amyblais** [comment]
Hi @stephanfriedrich, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
