### ISSUE TITLE
Sign in page cut off

### ISSUE THREAD

**Issue by Jessica-c53** [mattermost/mattermost-server#9046]
#### Summary
Sign in page cut off/ no scroll bar on testing server

#### Steps to reproduce
Testing Server Link
https://rctesting.reddogsofwar.com/login

#### Expected behavior
The page shows that there are other quick sign in options but they are cut off and there is no way to scroll down and get them.

#### Observed behavior (that appears unintentional) 
![testing link bug](https://user-images.githubusercontent.com/40774452/42238398-8641cfc2-7eb5-11e8-9f59-823b8674d22e.JPG)

**Comment by amyblais** [comment]
Hi @Jessica-c53! Thank you for reporting this 👍 

Would you be able to test if this reproduced on a different browser?
Are you able to see the whole page if you try to change the zoom level in the page?

I'm not able to repro this on Mac, Chrome, so I just want to get a sense of if this is device / browser specific issue.

**Comment by jkurian** [comment]
Just for more information here, I also noticed this issue. I am on a Mac book using Firefox and the login window does not resize. The window does resize however when in Safari. 

Firefox
<img width="1003" alt="screen shot 2018-07-04 at 8 57 39 am" src="https://user-images.githubusercontent.com/13214873/42278330-73ca2106-7f68-11e8-85b1-c0b28c99c5c5.png">

Safari
<img width="872" alt="screen shot 2018-07-04 at 8 59 11 am" src="https://user-images.githubusercontent.com/13214873/42278369-924a3f6c-7f68-11e8-9e50-726803f06ea1.png">

**Comment by amyblais** [comment]
Interestingly I'm not able to reproduce this on Mac or Windows on different browsers - @Jessica-c53 what zoom level do you have on the page just so that I can effectively test it out?

**Comment by Jessica-c53** [comment]
I was using 100% zoom level on Google Chrome on my PC. I can see the bottom
of the page if I decrease that percent. I tested this firefox and internet
explorer (on my PC) both were initially cutoff at 100% zoom but could be
adjusted to see everything with that lessened.

I have attached screenshots of Internet Explorer and Firefox at 100% zoom.

**Comment by SmartHoneybee** [comment]
Reproducible for me with Firefox (52.9.0) and its [Responsive Design Mode][1] after toggling orientation on the selected device (e.g. Google Nexus 4).

While disabling `overflow: hidden` for `.body` fixed the issue for me, I'm not sure if that's the right way to handle this. (Search for `overflow` in the [CSS Pane][2], move your mouse towards the highlighted entry, unselect the checkbox that appears. Now you should be able to scroll down.)

[1]: https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode
[2]: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/UI_Tour

**Comment by amyblais** [comment]
Hi all! Did `SmartHoneybee`'s suggestion help?

**Comment by Jessica-c53** [comment]
Yes! The link now leads to a sign in page with a scroll bar for me.
