### ISSUE TITLE
[Help Wanted] [MM-11180] Add experimental default channels feature

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9058]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11180)

Add an experimental configuration setting to config.json that takes an array of channel names to add users to when they first join the server. If the channel does not exist on the team, don't add them.

**Comment by adzimzf** [comment]
is this issue suitable for beginner ?

**Comment by jasonblais** [comment]
Hey @adzimzf! Thanks for your interest in contributing to Mattermost!

There is actually a PR opened for this feature https://github.com/mattermost/mattermost-server/pull/9068

We have some open introductory tickets here: https://github.com/mattermost/mattermost-server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Difficulty%3A+Introductory%22++label%3A%22Up+For+Grabs%22

Let me know if any of them are of interest? If not, I'd be happy to suggest some others too :)

**Comment by adzimzf** [comment]
Hey @jasonblais,
actually I'm go programmer,  can you suggest me some issues related to go ?

**Comment by jasonblais** [comment]
Hey @adzimzf! Some of those introductory tickets are for Go: https://github.com/mattermost/mattermost-server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3AGo+label%3A%22Up+For+Grabs%22

If none of them strike your interest, let me know as there are a few other areas we're working on at the moment.

**Comment by jasonblais** [comment]
@adzimzf  Are there any areas (apart from Go) that you'd be interested tackling? Not sure if any of the open Go help wanted tickets were of interest.

**Comment by hmhealey** [comment]
Closing as this has been implemented in @DSchalla's pull request
