### ISSUE TITLE
Implement "client banner" conditional on client software version

### ISSUE THREAD

**Issue by mcallaghan-sandvine** [mattermost/mattermost-server#9077]
#### Summary
For back-end Mattermost server upgrades, sometimes client versions are required to be upgraded. Further, there is no auto-update notification feature in the mattermost client. So administrators often employ a banner/notification to clients indicating that the server was upgraded, and they may need to upgrade their client.

It would be awesome if the admin could ONLY display the banner if version is less than some version, to not spam/notify users that are already running the latest version.

#### Steps to reproduce
Administrator puts out a banner w/ something like the following text:
> "Please upgrade your client to the latest software version. The server has been upgraded recently"

Applicable to all platforms (MAC, Linux, Windows, Mobile)

#### Workaround
 *) admin can set a condition on if/when to show the banner to the client based on their software version

#### Observed behavior (that appears unintentional) 
Clients suffer through a myriad of stale versions, without notification that there is a new version. Administrators resort to blanket banner reminding users to upgrade and it stays there for 1 week or something ...

#### Possible fixes
ONE OF: Either:
 1) Mattermost client starts handling updates to itself (client upgrades itself and auto-restarts)
 2) Mattermost client can automatically notify the user if there is a newer client version available (user upgrades manually)

**Comment by amyblais** [comment]
Hi @mcallaghan-sandvine! Thank you for reporting this 👍 

Can you help with more details on what Mattermost server version and mobile version you currently use?

There has been discussion about this, so I will ask our team about where this is in the roadmap / if there is an open Jira ticket, as I could not find specific information after doing some searching. I'll let you know the feedback.

**Comment by mcallaghan-sandvine** [comment]
@amyblais , MM server is `5.0.0` in this case.  Mobile version is N/A (it varies across all users). MOST users are on latest `4.1.2`.

**Comment by amyblais** [comment]
Hi @mcallaghan-sandvine!

There is actually a PR open here to implement auto-upgrader: https://github.com/mattermost/desktop/pull/582.

Here is a link to the original ticket: https://github.com/mattermost/desktop/issues/15.

If you are interested in helping out, let us know! All help is welcome.

**Comment by amyblais** [comment]
Hi @mcallaghan-sandvine, we haven't received an update for a while so I'll close this Issue for now.

You can follow the progress of this feature request in the ticket and PR that I linked above.

If you have any further questions, please reopen this Issue with the relevant questions/information and we'd be glad to help you where we can.

**Comment by mcallaghan-sandvine** [comment]
What's the ETA/roadmap/milestone for #15 though? -- the proposal here for a client banner MAY be a desired fast/interim solution -- this is especially important for being notified for security updates

Would prefer to re-open this issue for that reason.

**Comment by amyblais** [comment]
@mcallaghan-sandvine Update: I've asked our Product Managers to weigh on this and I'll let you know when I receive feedback

**Comment by amyblais** [comment]
Our Product Managers responded that this feature is aimed at v4.2.0 and the developer who is working on it is currently testing it / fixing bugs. The best option seems to be keeping our focus on finishing the updater feature as it is one of our key features that were are working on at the moment.

**Comment by amyblais** [comment]
I'll close this Issue for now as it can be followed on https://github.com/mattermost/desktop/issues/15 and the corresponding PR https://github.com/mattermost/desktop/pull/582.
