### ISSUE TITLE
Scaling mattermost to multiple servers

### ISSUE THREAD

**Issue by ziyadparekh** [mattermost/mattermost-server#9080]
How does Mattermost resolve scaling websocket connections to multiple instances of mattermost installed on different servers? If I have a cluster of servers running mattermost instances and user A has an open connection on server A while user B has an open connection on server B but they are both part of the same channel, how does mattermost resolve broadcasting a message from user A to all the users on the channel including user B?

I saw that the redis dependency has been taken out so I was wondering if there is a different pubsub model being employed to allow this. Or is there something else I am not seeing?

Thanks!

**Comment by acpower7** [comment]
good question

**Comment by amyblais** [comment]
Hi @ziyadparekh and @acpower7! Thank you for your questions 👍 

Here is some documentation that might help:
- https://docs.mattermost.com/deployment/scaling.html
- https://docs.mattermost.com/deployment/cluster.html

Let me know if this doesn't help and I'll ask the team for more details.

**Comment by aranjan7** [comment]
@amyblais Thanks for the response. But most of the question by @acpower7 is not answered in above links. Is there a brownbag on this topic. Specifically I want to know:
  a) how does 'inter-node' messaging works wrt web sockets / proxy connections of channel members being distributed. Any code pointers for the same.
  b) With members joining/leaving how do you invalidate in memory cache.
  c) Any scaling limitation or architecture goals of 'inter-node' message bus.
  d) Why Redis was removed/not considered. Or how is 'inter-node messaging layer' is better fit here.

I have searched forums and mattermost chat db, but could not find much.

Thanks

**Comment by amyblais** [comment]
Answers from our engineers:

@ziyadparekh:
For "How does Mattermost resolve scaling websocket connections to multiple instances of mattermost installed on different servers?":
We don't handle dynamically balancing websocket connections.

@acpower7:
1. The LB load balances requests between the app servers. It also provides a caching layer.
2. No, the DB is shared.
3. No strategy, the client can make requests to any app server.

@aranjan7:
a) All websocket events are broadcast to all clients of the current server and all peer servers, which in turn broadcast it to their users.
b) Direct requests to invalidate.
c) Nothing specific.
d) Simplicity and having 1 fewer dependency. However we are considering adding redis caching for performance anyway.

**Comment by amyblais** [comment]
Hi all, there haven't been updates on this Issue for a while so I'll close this for now.

If you have any further questions, please reopen this Issue with the relevant questions/information and we'd be glad to help you again where we can.

**Comment by aranjan7** [comment]
hi Amy,
I am trying to trace the code for internode communication/ clustering in Mattermost server. Are these interface function available in open source? Or these are part of closed source E20 build only.

Thank you.

**Comment by amyblais** [comment]
Hi @aranjan7, thank you for reaching out.

Yes, cluster is an Enterprise feature (E20): https://docs.mattermost.com/deployment/cluster.html.

**Comment by aranjan7** [comment]
Thanks @amyblais .. Thanks for clarification. I was somehow assuming that its a difference compilation knobs but entire code is available. 

So, the code which implements/links with these interfaces are not required to be open sourced. Is there an exception in place for these interfaces. I am just wondering from open source license perspective. I understand from monetization perspective it makes complete sense for the project.

**Comment by amyblais** [comment]
Hi @aranjan7, no worries, the source code in Github is of our Team Edition which is open source.

For Enterprise Edition features you'll need to purchase either E10 or E20 depending on the features you need: https://mattermost.com/pricing/.

**Comment by aranjan7** [comment]
I understand 'bout team edition. But when you build E10/E20 you link with the same source code. Doesn't that make the directly linked code making up E10/E20, open source. My main concern is if I deploy E20 with some extension at my workplace, are we complying with GPL.

**Comment by amyblais** [comment]
@aranjan7 The source code (https://github.com/mattermost/mattermost-server) only includes Team Edition. We build Enterprise features in a different, private Github repo. For more information on our open-source policy, you can visit these resources:

 - https://github.com/mattermost/mattermost-server/blob/master/LICENSE.txt
 - https://www.mattermost.org/licensing/
 - https://www.mattermost.org/trademark-standards-of-use/

**Comment by aranjan7** [comment]
@amyblais Many thanks. I see some of the exception for E20 now, but still have few clarifications. Is there a better channel to discuss this offline.

**Comment by amyblais** [comment]
@aranjan7 Sure thing, you can join the [Peer-to-peer Help channel](https://pre-release.mattermost.com/core/channels/peer-to-peer-help) on our Community server to ask more questions. Other team members and community members also often answer questions there.

**Comment by mrbkiter** [comment]
@ziyadparekh I have implemented a free version of Mattermost supporting clustering. You can check it out here: https://github.com/mrbkiter/mattermost-server

The tech behind is, I used Redis Pubsub to broadcast the messages, and then check to see if the receivers have web connections to send back to users.

**Comment by ysaakpr** [comment]
@mrbkiter Why don't we create a mattermost fork with clustering as a default feature and keep it maintained up with the upstream.
I would be interested very much interested to contribute and to be a maintainer for the same fork.

**Comment by jackielii** [comment]
I reckon there should be an websocket "coordinator" which uses a Redis store that saves all the live the machines' status. Then use a consistent hashing to distributing the userid to the live hosts. So when a connection comes, you'll know where to send to right?
