### ISSUE TITLE
[Help Wanted] [MM-11144] Introduce mlog/human package to consume and reformat structured logging

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9081]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11144)

Introduce a mlog/human package to consume structured logging (JSONL) and produce human readable output. Specific requirements include:
* consume line-by-line
* non-JSONL input lines should be passed through without error
* unix timestamps should be rendered as time.RFC3339Nano
* structured messages containing multiple lines should be exploded into multiple lines of output
* actual format up for design, but consider adopting ideas from https://github.com/sirupsen/logrus (including colour when appropriate?). In fact, it may even be appropriate to parse and feed structured logs directly into logrus.

Avoid over-designing up front to streamline this task. For example, while filtering to log level might be useful, this can be as easy as an additional pipe to `grep` for now.

**Comment by zeroimpl** [comment]
I'll take a look at this.

Note it seems that logrus always escapes newlines as \n (eg see https://github.com/sirupsen/logrus/issues/608). In this case, is it still worth integrating with logrus?

**Comment by amyblais** [comment]
Pinging @lieut-data on the question above ^

**Comment by lieut-data** [comment]
@zeroimpl, I think it would depend on the design, but it might still be useful to leverage logrus after exploding the incoming lines if only to get formatting and colorization. The proposal here is 100% meant for human consumption, so lots of flexibility.

**Comment by jasonblais** [comment]
Thank you @zeroimpl!
