### ISSUE TITLE
[Help Wanted] [MM-11283] Migrate components/navbar/navbar.jsx to Redux and PureComponent

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9093]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11283)

If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Advanced

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/navbar/navbar.jsx`](https://github.com/mattermost/mattermost-webapp/tree/master/components/navbar/navbar.jsx) to Redux.

This is more of an advanced ticket because it's a complex component and uses a lot of flux stores. It is also not named well, essentially this component is the mobile view navigation bar at the top of the app. This component only renders on small screens or when the window is small.

Before submitting the pull request, make sure it has proper component testing [as described here](https://docs.mattermost.com/developer/webapp-component.html#testing-your-component). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**Comment by cometkim** [comment]
What a code size :joy: 

I will take this one.

**Comment by jasonblais** [comment]
Awesome! Thanks @cometkim for taking up the challenge :)

**Comment by cometkim** [comment]
Quick dev questions for the navbar component.

Currently, the navbar component is a header for mobile layout, not shown up on PC(wide) and also it is responsible for managing the modals. Am I understanding this correctly?

If true, does this mean that the modal container should be separated from the navbar?

**Comment by jasonblais** [comment]
Closed by https://github.com/mattermost/mattermost-server/issues/9093
