### ISSUE TITLE
Users can delete themselves from Direct channels

### ISSUE THREAD

**Issue by gmccance** [mattermost/mattermost-server#9097]
#### Summary
Users can delete themselves from direct channels via the Mattermost API - which they cannot then add themselves back onto.

#### Steps to reproduce

With server version 5.0.0:

```
laptop ~$ curl -q -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" "https://$URL/api/v4/config/client?format=old" | jq ".Version"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5202    0  5202    0     0   116k      0 --:--:-- --:--:-- --:--:--  118k
"5.0.0"
```

A User is subscribed to two channels, one of which is a Direct channel. Everything is fine in the Mattermost web app - the two users on the direct channel can happily communicate.

```
laptop ~$ curl -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" https://$URL/api/v4/users/kqi44661tpywt8q1foeaanpipc/teams/31o17an6tibqjfp3om6tu4naio/channels | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   756  100   756    0     0  13393      0 --:--:-- --:--:-- --:--:-- 13500
[
   {
      "header" : "",
      "name" : "kqi44661tpywt8q1foeaanpipc__nswch7nkapyspdn79jniwiba3r",
      "delete_at" : 0,
      "extra_update_at" : 0,
      "type" : "D",
      "last_post_at" : 1531312065044,
      "team_id" : "",
      "scheme_id" : null,
      "purpose" : "",
      "creator_id" : "",
      "create_at" : 1531311843708,
      "update_at" : 1531311843708,
      "id" : "ix6cf8bdqpfomnhyfxcw7ya13o",
      "display_name" : "",
      "total_msg_count" : 3
   },
   {
      "header" : "This is where people post funny cat pictures and slack off (no pun intended).",
      "delete_at" : 0,
      "name" : "town-square",
      "type" : "O",
      "extra_update_at" : 1522754967459,
      "team_id" : "31o17an6tibqjfp3om6tu4naio",
      "last_post_at" : 1531311836025,
      "creator_id" : "",
      "purpose" : "",
      "scheme_id" : null,
      "create_at" : 1465889182932,
      "update_at" : 1511350497377,
      "total_msg_count" : 58,
      "display_name" : "Centre-ville",
      "id" : "sqgxfx8w93brue46fsfcgk3rsw"
   }
]
```

Channel membership of the direct channel looks fine showing the expected users:

```
laptop ~$ curl -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" https://$URL/api/v4/channels/ix6cf8bdqpfomnhyfxcw7ya13o/members  | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705  100   705    0     0  15146      0 --:--:-- --:--:-- --:--:-- 15326
[
   {
      "notify_props" : {
         "push" : "default",
         "desktop" : "default",
         "mark_unread" : "all",
         "email" : "default"
      },
      "explicit_roles" : "",
      "scheme_user" : true,
      "last_viewed_at" : 1531312065044,
      "user_id" : "nswch7nkapyspdn79jniwiba3r",
      "msg_count" : 3,
      "roles" : "channel_user",
      "scheme_admin" : false,
      "mention_count" : 0,
      "last_update_at" : 1531312065044,
      "channel_id" : "ix6cf8bdqpfomnhyfxcw7ya13o"
   },
   {
      "mention_count" : 0,
      "last_update_at" : 1531312065044,
      "channel_id" : "ix6cf8bdqpfomnhyfxcw7ya13o",
      "roles" : "channel_user",
      "scheme_admin" : false,
      "msg_count" : 3,
      "user_id" : "kqi44661tpywt8q1foeaanpipc",
      "explicit_roles" : "",
      "notify_props" : {
         "desktop" : "default",
         "mark_unread" : "all",
         "email" : "default",
         "push" : "default"
      },
      "scheme_user" : true,
      "last_viewed_at" : 1531312065044
   }
]
```

Now use the API to delete myself from the Direct channel `ix6cf8bdqpfomnhyfxcw7ya13o`:

```
laptop ~$ curl -X DELETE -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" https://$URL/api/v4/channels/ix6cf8bdqpfomnhyfxcw7ya13o/members/kqi44661tpywt8q1foeaanpipc  | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    170      0 --:--:-- --:--:-- --:--:--   172
{
   "status" : "OK"
}
```

The delete is accepted. At this point the Mattermost Webapp for the deleted user in the direct channel says "USERNAME has left the channel". Attempting to write a message to this window results in "Retry" box appearing in app, and attempting to send a message via the API gets permission denied. 

Any messages sent from the other user in the Direct channel is still accepted but are not seen by me, since I'm no longer a member of the channel.

Attempting now to read the Direct channel membership, as we did above, fails:

```
laptop ~$ curl -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" https://$URL/api/v4/channels/ix6cf8bdqpfomnhyfxcw7ya13o/members  | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0   3733      0 --:--:-- --:--:-- --:--:--  3787
{
   "request_id" : "jsqbqdj4ftr9jre6n8sebzme6r",
   "status_code" : 403,
   "message" : "You do not have the appropriate permissions",
   "id" : "api.context.permissions.app_error",
   "detailed_error" : ""
}
```

And adding myself back onto the channel isn't supported anyway:

```
laptop ~$ curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" https://$URL/api/v4/channels/ix6cf8bdqpfomnhyfxcw7ya13o/members -d '{ "user_id": "kqi44661tpywt8q1foeaanpipc" }' | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   228  100   185  100    43   4126    959 --:--:-- --:--:-- --:--:--  4204
{
   "detailed_error" : "",
   "message" : "Can not add user to this channel type",
   "status_code" : 400,
   "id" : "api.channel.add_user_to_channel.type.app_error",
   "request_id" : "j1bmgoi9nidw8jongq4shxg41o"
}
```

#### Expected behavior

Users should not be able to delete themselves from direct channels in the first place.

**Comment by amyblais** [comment]
Hi @gmccance! Thank you for reaching out 👍 

I remember a similar report just recently, and I was wondering if you can take a look if it describes the issue you are seeing: https://github.com/mattermost/mattermost-server/issues/9001.

Here is a ticket that was opened for it: https://mattermost.atlassian.net/browse/MM-11118.

If these do not describe the issue you are seeing, then of course let me know and I'll ask our devs to take a look!

**Comment by gmccance** [comment]
Hi @amyblais!

Indeed when trying to fix this I also noticed the issue #9001 - that you can delete a Direct channel entirely and then not be able to get it back.

This issue is slightly different - I'm not deleting the channel itself, I'm just deleting one of the channel members (myself), which results in a situation that can't then be rescued from the API. i.e. the Direct channel only has one member (the other guy) and I can't add myself back onto it.

I guess disallowing a channel member deletion when the channel type is Direct should fix it.

**Comment by lieut-data** [comment]
@gmccance, thanks for point this out. You're right that #9001 only restricted the ability to delete direct and group messages.

Would you be interested in helping fix this? It should be a straight-forward addition to https://github.com/mattermost/mattermost-server/blob/5ddb08dcb47f938c9ac3a3e6338d9b3cc61c20a7/api4/channel.go#L1029, with a few unit tests to complement the changes in https://github.com/mattermost/mattermost-server/blob/master/api4/channel_test.go.

**Comment by gmccance** [comment]
Back from vacation.. yes, sure - I'm happy to give it a go.

**Comment by amyblais** [comment]
Hi @gmccance,

Just following up, have you had a chance to take a look at this? No worries if you haven't, I can also help open a ticket for this for our devs to look at.

**Comment by gmccance** [comment]
Yeah sorry, waiting for our legal to approve the CLA :)  Might be worth opening the ticket on your side for this one...

**Comment by amyblais** [comment]
@gmccance Actually, there was already a fix submitted a few weeks ago: https://mattermost.atlassian.net/browse/MM-11593 :)

**Comment by amyblais** [comment]
The Jira ticket and associated PR are completed and we have tested internally that this works in v5.3 - feel free to re-open this Github Issue if the issue persists after upgrading to v5.3 (which will be released in Sept. 14th).
