### ISSUE TITLE
[Help Wanted] [MM-11293] Add server Makefile target to run Go static checker

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9100]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11293)

This ticket entails:

1. Add a Makefile target to add static code checking to the server repository
2. Fix all the issues reported by the static checker

A follow-up ticket will be used to add this to the CI pipeline once it's working and all issues are fixed.

Preferably use a Go-based checker so that the Makefile can install it as needed.

**Comment by DSchalla** [comment]
I'll take it.
