### ISSUE TITLE
Get channel-by-name does not return deleted channels

### ISSUE THREAD

**Issue by thePanz** [mattermost/mattermost-server#9115]
#### Summary
 API `/teams/{team_id}/channels/name/{channel_name}` is not returning the deleted channel

#### Steps to reproduce
0. Pre.requisites: a channel named `the-channel-name`, with ID `a1b2c3d4`
1. Delete a channel via the API
2. Use the `GET /teams/{team_id}/channels/name/{channel_name}` to fetch the channel (`GET /teams/{team_id}/channels/name/the-channel-name`), no results are found.
3. Use the `GET /channels/{channel_id}` to fetch the channel (`GET /channels/a1b2c3d4`) is instead returning the channel.

#### Expected behavior
The API `GET /teams/{team_id}/channels/name/{channel_name}` should return deleted channels, for consistency with `/channels/{channel_id}`

See discussion in https://pre-release.mattermost.com/core/pl/kxf717c543d18gga46dps8ei8c

**Comment by amyblais** [comment]
Hi @thePanz! I created a Jira ticket here that you can track: https://mattermost.atlassian.net/browse/MM-11350.

**Comment by jespino** [comment]
Hi @thePanz we discussed it in our Platform meeting, and we decided to keep it as is now (but we added a included_deleted parameter).
