### ISSUE TITLE
After team deleting "team statistics" page is stuck.

### ISSUE THREAD

**Issue by maxtar** [mattermost/mattermost-server#9116]
#### Summary
When I've delete a team, i couldn't see teams statistics.

#### Steps to reproduce
Mattermost version: 5.0.0.

1. Run following command: `mattermost team list`.
1. Run command `mattermost team delete <selected_team>`.
1. In web-gui open _System console_.
1. Open _Team statistics_ menu.

#### Expected behavior
I can see team statistic, and can select team in Combo-Box on the top-right corner.

#### Observed behavior (that appears unintentional) 
See screenshot:
![default](https://user-images.githubusercontent.com/10290098/42758125-0e83e4e2-890b-11e8-97a4-a6b960f2de20.png)

**Comment by amyblais** [comment]
Hi @maxtar! Thank you for reporting this!

Do you know if the team that you deleted was empty (didn't have any channels)?

**Comment by maxtar** [comment]
Hi @amyblais. No, Team was not empty. It have has two standard channels (Townsquare and off-topic.)

**Comment by amyblais** [comment]
@maxtar Thank you, that information is helpful!

I'll ask our team to help repro this.

In the meanwhile, if you want to, you could try adding a new team to see if that helps resolve the issue (as a temporary solution while we investigate).

**Comment by maxtar** [comment]
@amyblais Creating new team didn't resolve problem. :)

**Comment by amyblais** [comment]
@jespino Wondering if you can help test this on a test server and see if you can repro:

1. Run following command: `mattermost team list`.
2. Run command `mattermost team delete <selected_team>`.
3. Open System console and observe if the `Team Statistics` page loads.

**Comment by jespino** [comment]
Definitively, I can reproduce it.

**Comment by jespino** [comment]
I made a PR solving the bug.

**Comment by amyblais** [comment]
Hi @maxtar, the PR to fix this bug has been merged so I'll close this Issue for now.

If the issue persists, please reopen this Issue with the relevant information and we'd be glad to help you where we can.

**Comment by maxtar** [comment]
Hi @amyblais.
I've update mattermost to 5.1.0 version.
Problem is still reproducing.

**Comment by jespino** [comment]
@maxtar Yes, It was solved for 5.2 version.

**Comment by maxtar** [comment]
@jespino ups. thanx. 
When will to be released 5.2 version?

**Comment by jespino** [comment]
It'll be release on August 16th.

**Comment by maxtar** [comment]
@jespino  thanx. Will wait.

**Comment by maxtar** [comment]
@jespino Hi, Is mattermost 5.2 release delaying?

**Comment by Hanzei** [comment]
Yes, a bit. You can download it under https://releases.mattermost.com/5.2.0/mattermost-team-5.2.0-linux-amd64.tar.gz

**Comment by maxtar** [comment]
@Hanzei Thanx for answer!
