### ISSUE TITLE
Use link for access server local

### ISSUE THREAD

**Issue by florianproxi** [mattermost/mattermost-server#9119]
Hello, 
we use mattermost v5.1.0 and we would have liked that when we send links to our local DATA server which is in the form W:\DEVELOPPEMENTS\DAMIEN\test.xls this make it clickable, is this possible?

Thanks

**Comment by florianproxi** [comment]
Hi @amyblais i confirm it's the same issue.

**Comment by amyblais** [comment]
Thanks @florianorben - I'll close this Issue for now and you can follow the progress of this in the Desktop Issue I linked above.
