### ISSUE TITLE
Unable to play videos in mattermost

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#9122]
#### Summary
Unable to play videos in the in-mattermost video player.

#### Steps to reproduce
1. Upload video file into mattermost private message or channel
2. Click on it to play (video player opens up)
3. The play button gets hidden by a "File 1 of 1" text/overlay

#### Expected behavior
The play button should be click-able.

#### Observed behavior (that appears unintentional) 

As soon as the cursor goes over the play button,  The play button gets hidden by a "File 1 of 1" text/overlay

GIF of the behavior,
https://i.drop.cm/95b3648ec406e58f5e10.gif

#### Possible fixes
Not too sure, but what I do remember is, it worked fine in previous releases.

Currently running,
Mattermost Version: 5.1.0
Database Schema Version: 5.1.0
Database: mysql

**Comment by amyblais** [comment]
Hi @arjitc! Thank you for reporting this.

I'm able to repro this and it looks like one of our engineers just opened a ticket to fix this, you can follow its progress here: https://mattermost.atlassian.net/browse/MM-11378.

In the meanwhile, are you able to click in the middle of the video to play it (as a temporary solution)?

**Comment by arjitc** [comment]
> In the meanwhile, are you able to click in the middle of the video to play it (as a temporary solution)?

The play button/middle of video click didn't work in this case.

**Comment by amyblais** [comment]
The ticket to fix this has been closed as Resolved, so I'll close this Issue for now.
