### ISSUE TITLE
[Help Wanted] [MM-11388] Allow spaces in keywords that trigger mentions

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9140]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11388)

Repro:

1. Go to Account Setting > Notifications > Words that trigger mentions > Other non-case sensitive words, separated by commas
2. Enter a phrase with spaces, Save

Observed: After saving spaces are removed from the keywords
Expected: Spaces are saved and any keywords with spaces trigger mentions in Mattermost

Note that this will require rewrite of the existing mention parser that goes through the message word-by-word to identify mentions. One potential solution would be to implement a better string searching algorithm such as https://github.com/cloudflare/ahocorasick

**Comment by jasonblais** [comment]
Thank you!! Your're awesome @pradeepmurugesan

**Comment by pradeepmurugesan** [comment]
rewrite the existing mention parser is hard since the string matching algorithms usually find the substring and its hard to differentiate for the message 

```This is the message for user.name in channel x```

and the available keywords being 

```user.name and user. ```

In the above case both will be notified. 

So handled the spaces separately for now.

**Comment by hanzei** [comment]
With https://github.com/mattermost/mattermost-webapp/pull/1489#issuecomment-444560116 is mind: Can this issue be closed for now?

**Comment by jasonblais** [comment]
yes, good catch @hanzei. Closing as per this comment

> Based on internal discussion, it sounds like if we are going to find a new library used for searching mention keywords we need to get more clear on the expected for various cases of symbols, spaces etc and what we should be supporting. I can circle back with you once we have that and a proposed approach for how to solve this completely.
