### ISSUE TITLE
Video playback does not render for clients

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#9145]
#### Summary
Video playback is missing video in both the Client app + Chrome on macOS 10.13.6 when clicking the play button / image in a video preview within the client for videos such as YouTube videos. Audio plays, but no video.

#### Steps to reproduce
Using Mattermost server 5.1, in a chat on a client, I click a YouTube video preview and the image goes blank. Audio begins to play, but video is missing.

I'm using a dark theme with the following custom colors:
```
{"sidebarBg":"#1f1f1f","sidebarText":"#ffffff","sidebarUnreadText":"#f63030","sidebarTextHoverBg":"#302e30","sidebarTextActiveBorder":"#eb1013","sidebarTextActiveColor":"#ffffff","sidebarHeaderBg":"#1f1f1f","sidebarHeaderTextColor":"#ffffff","onlineIndicator":"#29c01a","awayIndicator":"#c1b966","dndIndicator":"#e81023","mentionBj":"#781214","mentionColor":"#f31515","centerChannelBg":"#1f1f1f","centerChannelColor":"#dddddd","newMessageSeparator":"#cc992d","linkColor":"#0d93ff","buttonBg":"#0177e7","buttonColor":"#ffffff","errorTextColor":"#ff6461","mentionHighlightBg":"#004d13","mentionHighlightLink":"#33a3ff","codeTheme":"solarized-dark","mentionBg":"#781214"}
```

#### Expected behavior
Video should play.

#### Observed behavior (that appears unintentional) 
Here's a screencast without audio. Note that when it goes blank, the audio for the video is playing. Then I let it play and pause it by clicking it. Once I do that and you see the "link finger" cursor pop up and I click it, a new video pops up in my default browser for YouTube videos. This demonstrates that the video and content from YouTube is active, but the video does not render or is somehow "covered up" by something in Mattermost.
![example](https://cl.ly/1z1X1n231N2E/Screen%20Recording%202018-07-23%20at%2010.42%20AM.gif)

**Comment by amyblais** [comment]
Hi @ylluminate! Thanks for reaching out 👍 

I'm not able to repro this with some other videos and the video you showed above doesn't seem to exist when I type the url.

Would you have a link to another video that I could help test out?

**Comment by ylluminate** [comment]
@amyblais hmm, odd as it happens with all YouTube videos I try... 

I looked into the JS console within Chrome and saw the following 2 embedded player errors:
```
www-embed-player.js:396 GET https://googleads.g.doubleclick.net/pagead/id 0 ()
Ye @ www-embed-player.js:396
Xe @ www-embed-player.js:382
(anonymous) @ www-embed-player.js:640
J @ www-embed-player.js:256
Ki @ www-embed-player.js:637
Ti @ www-embed-player.js:650
Yi @ www-embed-player.js:656
aj @ www-embed-player.js:661
(anonymous) @ www-embed-player.js:685
(anonymous) @ yutNM8AIkkk?autoplay=1&autohide=1&border=0&wmode=opaque&fs=1&enablejsapi=1:12
www-embed-player.js:423 GET https://static.doubleclick.net/instream/ad_status.js 0 ()
Hf @ www-embed-player.js:423
Ef @ www-embed-player.js:420
Df @ www-embed-player.js:419
Rf @ www-embed-player.js:435
(anonymous) @ www-embed-player.js:686
(anonymous) @ yutNM8AIkkk?autoplay=1&autohide=1&border=0&wmode=opaque&fs=1&enablejsapi=1:12
```

**Comment by amyblais** [comment]
1. In addition to the console errors, do you see any errors in logs that we could take a look at as well?

2. Also, not 100% sure if it's related but can you help check what your setting is set for [Google API key](https://docs.mattermost.com/administration/config-settings.html#external-services)?

**Comment by amyblais** [comment]
@ylluminate Something that came to mind is that this could be an issue with missing mime types - there is an [old ticket](https://mattermost.atlassian.net/browse/MM-5101) where a recommendation was to install a media player or other browsers on the server which would add the missing mime types and make it work.

**Comment by amyblais** [comment]
Hi @ylluminate, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by vegerot** [comment]
possibly related to https://github.com/mattermost/desktop/issues/1492
