### ISSUE TITLE
[Help Wanted] [MM-11375] When creating a new channel, you get two periods if you use a period at the end of the channel purpose

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9154]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11375)

Repro:
Create a new channel and fill in a channel purpose using a period at the end of the sentence

Observed: Two periods are shown in the welcome message at the top of the new channel

Expected: Only the period you inserted at the end of the sentence is shown.

**Comment by michaelkochub** [comment]
Hi @esethna, I am interested in working on this. This is would be my first contribution, so I think it is a good one to start with.

**Comment by esethna** [comment]
Awesome, thanks @michaelkochub! I'll remove the up for grabs label if you'll be taking this one

**Comment by michaelkochub** [comment]
@esethna, all done! https://github.com/mattermost/mattermost-webapp/pull/1480

**Comment by jasonblais** [comment]
Thanks @michaelkochub 🎉 

Fix will ship with Mattermost v5.3
