### ISSUE TITLE
[MM-11287] Add support for plus sign and period/dot in custom URL schemes

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9155]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11287)

Add functionality to allow `+` and `.` in custom URL schemes, in System Console > Customization > Posts > Custom URL Schemes (in addition to hyphen). Currently, custom URL schemes must start with a letter and contain only letters, numbers and hyphen (-). This needs to work on both the mobile and web apps, so the Markdown parsers for both ([marked](https://github.com/mattermost/marked) and [commonmark.js](https://github.com/mattermost/commonmark.js) respectively) need to have their URL parsers updated.

Original story: MM-9547

After implemented, error message on trying to save an invalid URL scheme (such as `%%`) should say: 

"The custom URL scheme {invalid entry} is invalid. Custom URL schemes must start with a letter and contain only letters, numbers, plus (+), period (.), and hyphen (-)."

Needs to be supported on webapp and mobile clients.

**Comment by letsila** [comment]
Hi, I'd love to work on this one.

**Comment by hanzei** [comment]
Hey @letsila,

Are you still interested in working on this issue?

**Comment by letsila** [comment]
Hi @hanzei. Yes I am.

**Comment by hanzei** [comment]
Great! Let me know if you have any questions @letsila

**Comment by letsila** [comment]
Hi @hanzei , I see in the issue description that I need to update both (marked)[https://github.com/mattermost/marked] and (commonmark.js)[https://github.com/mattermost/commonmark.js]. I guess that I need to serve these files from .node_modules to import them from the webapp react app. Is there some documentation on how I could achieve that?

**Comment by hanzei** [comment]
The first step would be to submit PR's to the two repositories. Then `package.json` in the webapp repo should be updated in a third PR

Does this solve your question?

**Comment by letsila** [comment]
The PR's steps makes sense. On the `mattermost-redux` there's the `npm run dev:watch` command, which allowed me to serve the dev repo of mattermost-redux into the mattermost-webapp. Hence I was wondering if there is something similar for the `marked`and `commonmark.js`repo.

**Comment by hmhealey** [comment]
I don't think that's needed for those repositories since I'm pretty sure they can be used with `npm link`. That doesn't work with `mattermost-redux` because of the way that we compile it to ES5

**Comment by letsila** [comment]
Thank you @hanzei
