### ISSUE TITLE
[Help Wanted] [MM-11464] Add pre and post login hooks

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9157]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11464)

**Comment by Ulisses-champ83** [comment]
I do what you team talk me . To do and together.  We can made
happening..is. good the l know l have teams..l was  thinking the l was
alone.. hey come Marc sey to increase the time

u.e.m
