### ISSUE TITLE
Channel can not be updated if user (system admin) is not in channel

### ISSUE THREAD

**Issue by Vaelor** [mattermost/mattermost-server#9162]
#### Summary
Refering to a bug here:
https://github.com/Vaelor/python-mattermost-driver/issues/28

The issue is, a public channel can not be updated if the user issuing the update for the channel, is not in it. Even though he is a system admin.
This does not seem to be an issue with my python-mattermost-driver, as I could reproduce it without.

#### Steps to reproduce
Tried last with Mattermost v5.0 (edit: Team Edition)
- Create a public channel

Using my python-mattermost-driver:
``` python
from mattermostdriver import Driver

driver = Driver({'debug': True, 'url': 'mattermost.url', 'login_id': 'system-admin@email.com', 'password': 'password', 'verify': False, 'port': 443})
driver.login()
team = driver.teams.get_team_by_name('teamname')
channel = driver.channels.get_channel_by_name(team['id'], 'testchannel')

# should update the name from testchannel to testchannel2
print(driver.channels.update_channel(channel['id'], {'id': channel['id'], 'display_name': 'testchannel2'}))
```
If you join the channel with the system-admin user and re run it works

#### Expected behavior
According to the docs it sounds like it should work.

#### Observed behavior (that appears unintentional) 
The channel is found:
```
{'id': '4w7jwj8x178dicdhp4f9wm1mzc', 'create_at': 1529430544568, 'update_at': 1532525400165, 'delete_at': 0, 'team_id': 'ptjmr19gs3g6fgc78womiwyorh', 'type': 'O', 'display_name': 'testchannel', 'name': 'testchannel2', 'header': '', 'purpose': '', 'last_post_at': 1532527896667, 'total_msg_count': 3, 'extra_update_at': 1532527896662, 'creator_id': '7zqya1d9j7bauct4rmnj34aqoo'}
```
Trying to update it results in:
> 404: No channel member found for that user ID and channel ID

**Comment by amyblais** [comment]
Hi @Vaelor!

Thanks for reporting this. I'll ask help from our team to try repro this.

**Comment by amyblais** [comment]
@Vaelor - Just to confirm, what would the repro steps be without python-mattermost-driver or is it the same?

**Comment by Vaelor** [comment]
@amyblais Using something like curl it would probably be somethin similar, get a token, get the channel id you want to update (it should also be available in the UI when viewing the channel info), and run curl (not 100% sure if the syntax is a 100% correct, currently typing on the phone and can't try it out)


’
curl -X PUT -i -H 'Authorization: Bearer token' -H 'Content-Type: application/json' -d "{'id': channel['id'], 'display_name': 'testchannel2'}" http://localhost:8065/api/v4/channels/channelid’

**Comment by Vaelor** [comment]
Oh maybe relevant: This happens using the Team Edition. Not sure if this happens on the Enterprise version!

**Comment by saturninoabril** [comment]
@Vaelor thanks for the report and additional info.  I'll try to test this out later today, cc @amyblais.

**Comment by saturninoabril** [comment]
@Vaelor Sorry but I am not able to repro the issue.  It works for me both on EE and TE, with sysadmin as not a channel member or even not a team member.

**Comment by Vaelor** [comment]
@saturninoabril @amyblais Thanks for both of your time, I tried to reproduce the issue again, but our admin had the time to update mattermost now, and yeah, 5.1 seems to fix this already, as I too couldn't reproduce it anymore (probably by accident as I couldn't see anything in the changelogs :-D I could swear 5.0 did not work! xD).

Well, sorry to keep you from doing something useful ;-) :-D

**Comment by saturninoabril** [comment]
No problem at all.  I didn't had a chance to try it in 5.0 but glad to know it's working on 5.1. 🎉
