### ISSUE TITLE
Unexpected highlighting/string substitution when searching with empty double quotes

### ISSUE THREAD

**Issue by TunnyTraffic** [mattermost/mattermost-server#9166]
#### Summary
using search terms followed by empty double-quotes in the search bar for web and desktop clients  (eg `test ""`)returns search results with what should be highlighted terms replaced with $MM_SEARCHTERM1, $MM_SEARCHTERM2. etc. This looks related to MM-10095 Unexpected highlighting/string substitution when searching with asterisk

#### Steps to reproduce
OS: Windows 10 1803
Desktop client: v4.0.0 and v4.1.2
Server version: v4.10.0
Issue not present in Android 1.10.0 (build 127) 

#### Expected behavior
Search term:
`test tool ""`
results
` do you know a tool for detecting SQLi in a whole website¿? I mean, I want it to crawl it and then just test a few payloads (', %27, waitfor delay '0:0:05') , and detect which URL, parameter is vulnerable. Best thing I found is this thing https://nmap.org/nsedoc/scripts/http-sql-injection.html but doesn't work like a charm`

With the words `test` and `tool` hightlighted
(this does work if `test tool` is used without quotes).

Example:

![clean-search-result](https://user-images.githubusercontent.com/25403372/43259934-d32516c4-90cf-11e8-8ee6-b4bcaa36af4b.PNG)

#### Observed behavior (that appears unintentional) 
Search term:
`test tool ""`
`do you know a $MM_SEARCHTERM5 for detecting SQLi in a whole website¿? I mean, I want it to crawl it and then just $MM_SEARCHTERM4 a few payloads ((&#39;, %27, waitfor delay  &#39;0$MM_SEARCHTERM305>&#39;) , and detect which URL, parameter is vulnerable. Best thing I found is this thing https://nmap.org/nsedoc/scripts/http-sql-injection.html but doesn>&#39;t work like a charm`

some characters are URL encoded and the web link is highlighted (as shown below)

![broken-search-results](https://user-images.githubusercontent.com/25403372/43259950-dea3d15c-90cf-11e8-810f-000afe13fd38.PNG)

empty single quotes results in clean results without broken formatting.

#### Possible fixes
mattermost-webapp/utils/text_formatting.jsx
Line 436: `export function highlightSearchTerms(text, tokens, searchPatterns) {`
I believe the second double quote is not escaped which is breaking this css.
```
                newTokens.set(newAlias, {
                    value: `<span class='search-highlight'>${alias}</span>`,
                    originalText: token.originalText,
                }```

**Comment by TunnyTraffic** [comment]
Updated Desktop client to 4.1.2, issue still present.

**Comment by amyblais** [comment]
Hi @TunnyTraffic! Thanks for reporting this 👍 

I'm able to repro also on v5.1, so I opened a ticket here: https://mattermost.atlassian.net/browse/MM-11503.
