### ISSUE TITLE
EnableLinkPreviews:false doesn't disable YouTube previews

### ISSUE THREAD

**Issue by M1dgard** [mattermost/mattermost-server#9173]
#### Summary
Setting EnableLinkPreviews to false doesn't disable YouTube previews

#### Steps to reproduce
1. Set EnableLinkPreviews to false in the server config
2. Send a message with a link to a YouTube video

#### Expected behavior
There's no preview for the YouTube video

#### Observed behavior (that appears unintentional) 
There's a preview for the YouTube video, causing non-protected browsers to automatically download an image from a third-party website

**Comment by amyblais** [comment]
Hi @M1dgard! Thank you 👍 

I was able to repro and created a ticket here: https://mattermost.atlassian.net/browse/MM-11508

**Comment by amyblais** [comment]
The Jira ticket has been resolved and tested internally. The fix will be available in v5.4 release.
