### ISSUE TITLE
Suggestion - Changing URL for default channel

### ISSUE THREAD

**Issue by xMateMCPE** [mattermost/mattermost-server#9181]
An option to change the url of the default channel would be good, our company has no english speaking people, so it would be nice to change it to something else.

**Comment by amyblais** [comment]
Hi @xMateMCPE, thank you for the feature request!

Would you like to upvote our existing feature requests related to this suggestion, or create a new request if the existing ones don't quite describe what you're looking for:

https://mattermost.uservoice.com/forums/306457-general/suggestions/13403289-easily-change-default-channel-town-square
https://mattermost.uservoice.com/forums/306457-general/suggestions/20226055-allow-admins-to-set-the-default-channels-when-a-me

**Comment by amyblais** [comment]
Hi @xMateMCPE, letting you know that v5.2 (released tomorrow) will be shipping with an experimental custom default channels feature (https://github.com/mattermost/mattermost-server/pull/9068).

**Comment by amyblais** [comment]
Hi @username, we haven't received other updates so I'll close this Issue for now.

Thank you for upvoting the Feature Request tickets for this!
