### ISSUE TITLE
Create example browser extension for Firefox

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9196]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11397)

You can use [sample Chrome plugin](https://github.com/mattermost/mattermost-chrome-extension) as an example for building a sample extension for Firefox.

**Comment by scottleedavis** [comment]
Hello!  I am interested in doing this one.  :)

**Comment by scottleedavis** [comment]
Had some time this afternoon to work on this, though as it is a near exact copy of @jwilander 's chrome extension except with some small tweaks, I don't deserve much credit for this.  :)

https://github.com/scottleedavis/mattermost-firefox-extension

**Comment by hanzei** [comment]
This is awesome! :rocket:  Please let me know, when this is ready for testing.

**Comment by scottleedavis** [comment]
Hi @hanzei I believe it is.  :) Happy to fix or change anything during evaluation.

**Comment by hanzei** [comment]
I'm currently short on time and won't be able to review this.

@jasonblais Could you please own the review of this extension?

**Comment by hanzei** [comment]
@jasonblais @aaronrothschild Who will take care of reviewing this?

**Comment by jasonblais** [comment]
Aaron has been assigned as the reviewer. Thanks @scottleedavis for the contribution1

**Comment by scottleedavis** [comment]
@aaronrothschild would you like to revisit this working on your machine with me via zoom, or perhaps we find someone to help validate?  I am not in a hurry, but also don't want to forget how to do it.  :)

**Comment by hanzei** [comment]
@aaronrothschild Gentle reminder about this issue

**Comment by aaronrothschild** [comment]
> @aaronrothschild Gentle reminder about this issue

Ha, it's still on my radar - I brought it up just yesterday with my team.  Still trying to get someone else to try it on their machine...

**Comment by scottleedavis** [comment]
Thank you @aaronrothschild .  Were you able to get this running with QA/Dylan?   I am happy to hop on zoom again to try getting this working.  :)

**Comment by scottleedavis** [comment]
I am unable to support continued Development and support of this repo https://github.com/scottleedavis/mattermost-firefox-extension 

However I have given @hanzei access in case there are changes needed.

**Comment by jasonblais** [comment]
Thank you Scott!

@hanzei @aaronrothschild wondering if we should close the help wanted issue and have further development / reports done via https://github.com/scottleedavis/mattermost-firefox-extension?

**Comment by hanzei** [comment]
:+1: I think we can close this issue. @aaronrothschild What do you think about listing the extension at https://integrations.mattermost.com/ ?

**Comment by KuSh** [comment]
Hi, I did convert the sample Chrome plugin to become a sample cross-browser plugin that also work in Firefox.
This should fix the issue
