### ISSUE TITLE
Error 1040: Too many connections (to DB)

### ISSUE THREAD

**Issue by Dropsik** [mattermost/mattermost-server#9215]
After upgade Mattermost from 4.9.0 (4.9.2/Thu May  3 23:19:23 UTC 2018/416c7523c3097af6759b7c40075df51d44624672/004f26d8eb84cd548eb6c56c37f8ca49413e1322) to 5.1.0 (5.1.0/Fri Jul 13 19:03:58 UTC 2018/54994502241bf40bebd9a9d7719c58f708aef5b1/none), few hours after running, Mattermost write to log:
`err=SqlStatusStore.SaveOrUpdate: Encountered an error saving the status, Error 1040: Too many connections"}`
before stop responding, I saw often in logs:
`{"level":"error","ts":1533298099.911097,"caller":"migrations/worker.go:105","msg":"Worker: Failed to run migration","worker":"Migrations","job_id":"r3cijrm9x3f4tbktcefsc5cpqo","error":"SqlChannelStore.MigrateChannelMembers: Failed to select the batch of channel members, sql: Scan error on column index 3: converting driver.Value type <nil> (\"<nil>\") to a int64: invalid syntax"}
`

DB is MariaDB, currently with increased max_connections to 251 and this also was reached:
`SHOW STATUS WHERE `variable_name` = 'Max_used_connections';
+----------------------+-------+
| Variable_name        | Value |
+----------------------+-------+
| Max_used_connections | 252   |
+----------------------+-------+
`

**Comment by amyblais** [comment]
Hi @Dropsik! Thank you for reaching out.

Can you help take a look at [Important Upgrade notes](https://docs.mattermost.com/administration/important-upgrade-notes.html) for between 4.9 and 5.1 to see if any apply in your case?

**Comment by Dropsik** [comment]
Of course I read these notes before upgrade.
I notice (after upgrade) that Mattemost have set Maximum Open Connections: 300
So in my case (default MariaDB max_connection = 151) could be an issue - but on previous verion works perfect about 2-3 months.

Anyway now observing. But what with migration job ?

**Comment by amyblais** [comment]
@Dropsik I checked with an engineer and they said you have two options:

1. Change the max amount of allowed connections in System Console -> Advance -> Database to match the max allowed connections of your Database.
2. Bump the allowed max connections of your Database.

Let us know if this helps!

**Comment by Dropsik** [comment]
Now I have in:
Mattermost: 300 connections
MariaDB: 301 max connections
lets see what happen.
I don't understand, why it's a problem after upgrade...

**Comment by Dropsik** [comment]
Nothing changed. DB connections still growing up.
For sure, we have (I think) small deployment:
Total Active Users: 191
Total Teams: 1
Total Channels: 143
So @amyblais for what value should I bumped the max allowed connection for this deployment ?
and why this not happend before upgrade ?

**Comment by amyblais** [comment]
Hi @Dropsik, apologies for the delay,

It looks like we'll need more details about your environment to troubleshoot this, can you help review this documentation and send us the relevant additional details: https://docs.mattermost.com/process/support.html?

**Comment by amyblais** [comment]
@Dropsik I think one thing to consider is that the max amount of allowed connections in System Console -> Advance -> Database should be the same as the max allowed connections of your Database.

**Comment by Dropsik** [comment]
Currently they have the same value

**Comment by amyblais** [comment]
@Dropsik Can you help set the log level to DEBUG to see if the logs will show more details / errors?

**Comment by amyblais** [comment]
@Dropsik What Database values do you currently have and do you see any difference when you increase the values?

**Comment by amyblais** [comment]
Hi @Dropsik, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by fincha** [comment]
havings similar issue here

```
{"level":"error","ts":1544461415.4741263,"caller":"migrations/worker.go:105","msg":"Worker: Failed to run migration","worker":"Migrations","job_id":"x7ii1pqappgzinpd8iya5fiwzc","error":"SqlChannelStore.MigrateChannelMembers: Failed to select the batch of channel members, sql: Scan error on column index 3, name \"LastViewedAt\": converting driver.Value type <nil> (\"<nil>\") to a int64: invalid syntax"}
```

**Comment by mschaaf** [comment]
The field LastViewedAt hat a null value for one of the entries in the table ChannelMembers. Setting this to 0 prevented the error. We did the same for LastUpdateAt and MsgCount. The error here leads to an ever-growing number of DB connections. Replacing the null values and avoiding the errors fixes this for us.

**Comment by gfra54** [comment]
> The field LastViewedAt hat a null value for one of the entries in the table ChannelMembers. Setting this to 0 prevented the error. We did the same for LastUpdateAt and MsgCount. The error here leads to an ever-growing number of DB connections. Replacing the null values and avoiding the errors fixes this for us.

This was the solution for me too. I had the same kind of error after migrating to version 5 : 

`{"level":"error","ts":1549445564.8085642,"caller":"migrations/worker.go:105","msg":"Worker: Failed to run migration","worker":"Migrations","job_id":"47qqpwwt7jbftp9ru65yfhf88r","error":"SqlChannelStore.MigrateChannelMembers: Failed to select the batch of channel members, sql: Scan error on column index 3, name \"LastViewedAt\": converting driver.Value type <nil> (\"<nil>\") to a int64: invalid syntax"}
F`
I changed all null values of LastViewedAt, LastUpdateAt and MsgCount in ChannelMembers from null to 0 and it did the trick
I think it might need to be more documented somewhere on the mattermost website. It was really a pain in the butt.

Thank you @mschaaf !
