### ISSUE TITLE
Recent mentions do not work with very short usernames

### ISSUE THREAD

**Issue by AsuMagic** [mattermost/mattermost-server#9221]
#### Summary
If your username is short enough (1 or 2 letters), recent mentions will not work, as it searches for `@<your username> <your username>` and results are getting excluded because your username is so short.

#### Steps to reproduce
Mattermost `4.10.0`.

1. have an username short enough (e.g. `ab`)
2. mention yourself or get mentioned by somebody else
3. hit "recent mentions"

#### Expected behavior
Your recent mentions should show up.

#### Observed behavior (that appears unintentional) 
"`No results found. Try again?`" shows.

#### Possible fixes
There could be an exception to the "`Two letter searches and common words like "this", "a" and "is" won't appear in search results due to excessive results returned.`" rule whenever the problematic word is also an username.  
I don't know whether such a fix would be problematic: Is this a thing because two characters searches take longer to find in the database or is it because having too much results is the problem?

**Comment by amyblais** [comment]
Hi @AsuMagic! Thanks for reaching out 👍 

Can you help with what steps you are taking to change username to 1-2 letters (I get an error message when I try to have a username with less than 3 letters)?

**Comment by AsuMagic** [comment]
Hi @amyblais, I can confirm I cannot change my username to 1-2 letters either on the version I reported this for actually. I am not the one who had the 2 characters short username but I could verify that he had this issue.

Perhaps it was possible on older versions from years ago but isn't possible anymore.

This seems like a very niche issue and its fix seems problematic, should I close it?

**Comment by amyblais** [comment]
Hi @AsuMagic - sounds like upgrading would be the best way to resolve this, perhaps the next step could be that you could ask the affected user what version they are using and if upgrading to a newer version would be an option for them?

**Comment by amyblais** [comment]
I see, yes the best solution then would be that the user changes their username to something longer 👍 

I'll close this Issue for now as this has a simple workaround,

**Comment by furai** [comment]
Not really a solution i was after when I've asked Asu to report it but thank you anyway. Will changing username change all the old highlights/mentions as well?

**Comment by amyblais** [comment]
Hi @furai,

No, when you change your username, the old mentions will not be highlighted anymore. I'll ask our devs if we should create a ticket for this.

**Comment by amyblais** [comment]
Hi @furai @AsuMagic, what version did you upgrade from?

There are two restrictions on usernames:

1. The UI doesn't let you create usernames shorter than 3 characters (which hasn't changed).
2. If you use LDAP or SAML to log in, your username is controlled by the LDAP/SAML server, which can be 1 or 2 characters long.

As for the recent mentions search, that might have broken at some point, so this is why we'd need to know the version you upgraded from.

**Comment by furai** [comment]
I've been upgrading this instance of mattermost since like early 2016. I was doing it whenever any bigger update was released, so I've been upgrading it pretty much monthly at the time. Can't pinpoint when the issue started happening. 
At the very beginning we've imported everything from slack. 
We don't use LDAP or SAML.

**Comment by amyblais** [comment]
Hi @furai,

One of our product managers directed me to this section of our docs: https://docs.mattermost.com/install/requirements.html#database-software. "For searching two characters, you will also need to set `ft_min_word_len` and `innodb_ft_min_token_size` to `2` and restart MySQL."

Is that something you could help try and see if it resolves the issue?

**Comment by furai** [comment]
Yes, sure. I'll try as soon as I'll be able to do it. Please remind me in few days if I don't get back to you.

**Comment by furai** [comment]
Ok, I've set it, did some `optimize table [tbl_name]` on mattermost database to rebuild fulltext index but it seems that only new messages are searchable right now with just 2 letters. Is there anything I can do about it?

**Comment by furai** [comment]
I ended up just dropping database and restoring from the mysqldump to rebuild all the old indexes. That have worked.

**Comment by amyblais** [comment]
@furai glad to hear the issue was resolved! I'll close this Issue for now but let me know if you encounter any other bugs,
