### ISSUE TITLE
[Help Wanted] [MM-11567] Allow searching in direct message channels using the "in:" modifier

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9232]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11567)

Requirements doc: https://docs.google.com/document/d/1HD9FfmlR1QdkXOauQyzq0EfE7Alf9tXfESBefNFoHK8/edit
Design: https://projects.invisionapp.com/share/3TJ8MNBPVKU#/screens

______

Design ticket: https://mattermost.atlassian.net/browse/MM-10123

**Comment by jasonblais** [comment]
Good catch @santos22! Have removed the restrictions.

**Comment by jasonblais** [comment]
Would you be interested helping with this improvement?

**Comment by santos22** [comment]
I would like to take a look but would rather keep the **Up For Grabs** label on here in case anyone else can get to it 👍

**Comment by jespino** [comment]
Finally this will be assumed by the core team, because we are changing some things in the search implementation.
