### ISSUE TITLE
Deleted user via CLI tools is appearing as "Someone" in direct messages section

### ISSUE THREAD

**Issue by domibarton** [mattermost/mattermost-server#9236]
#### Summary

When deleting a user via CLI tools `mattermost user delete ...`, the user and all its messages seem to be gone, but the direct messages sidebar now shows the user / conversation as `Someone` which can't be removed.

#### Steps to reproduce

- Write some direct messages with a user
- Make sure you've the user in your direct messages section of your sidebar
- Delete that user via CLI `mattermost user delete`

#### Expected behavior

- The user is removed from my direct messages section in the sidebar

#### Observed behavior (that appears unintentional) 

- The direct messages section now shows a `Someone` user with an invalid link (e.g. `https://mattermost.example.com/team/messages/@` with a missing username)
- The `Someone` user can't be removed from the sidebar

#### Possible fixes

n/a

#### Version

GitLab's Mattermost:

```
Mattermost Version: 4.10.1
Database Schema Version: 4.10.0
```

Running on Debian 9.

**Comment by domibarton** [comment]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/4124099/43804765-75e23b22-9a9d-11e8-815b-483decd3a8c2.png)

**Comment by domibarton** [comment]
Btw using GitLab's Mattermost integration:

```
Mattermost Version: 4.10.1
Database Schema Version: 4.10.0
```

**Comment by amyblais** [comment]
Hi @domibarton! Thanks for reaching out 👍 

Can you help try what happens when you add `CloseUnusedDirectMessages` option to the config?

**Comment by domibarton** [comment]
Setting `CloseUnusedDirectMessages` to `true` and restarting the service worked indeed :) Thanks @amyblais
