### ISSUE TITLE
Allow AllowedUntrustedInternalConnections for <SiteURL>/plugins by default

### ISSUE THREAD

**Issue by Hanzei** [mattermost/mattermost-server#9241]
#### Summary
When using plugins with interactive message buttons, admins have to add `localhost` to `AllowedUntrustedInternalConnections`. Otherwise mattermost will block all http request to the plugin.

#### Expected behavior
Untrusted connections to plugins are allowed

#### Observed behavior (that appears unintentional) 
Untrusted connections to plugins are prohibited by default

**Comment by Hanzei** [comment]
See [disscusion](https://pre-release.mattermost.com/core/pl/upke6c34utnkpn7zsqq6htcd9w) on pre-release.

cc @hmhealey

**Comment by amyblais** [comment]
Hi @Hanzei! Looks like Harrison started to look into this, I'll ping devs again after a few days to ask if we should create a Jira ticket for this depending on how the discussion goes.

**Comment by amyblais** [comment]
Hi @Hanzei, I created a ticket for our devs to look at: https://mattermost.atlassian.net/browse/MM-11693.

**Comment by harshilsharma63** [comment]
+1

**Comment by Hanzei** [comment]
This should be fixed in 5.3 with #9333.
