### ISSUE TITLE
Worker: Failed to run migration

### ISSUE THREAD

**Issue by Dropsik** [mattermost/mattermost-server#9253]
After upgade Mattermost from 4.9.0 (4.9.2/Thu May 3 23:19:23 UTC 2018/416c7523c3097af6759b7c40075df51d44624672/004f26d8eb84cd548eb6c56c37f8ca49413e1322) to 5.1.0 (5.1.0/Fri Jul 13 19:03:58 UTC 2018/54994502241bf40bebd9a9d7719c58f708aef5b1/none), few hours after running, Mattermost write to log:

`{"level":"error","ts":1534230250.7646399,"caller":"migrations/worker.go:105","msg":"Worker: Failed to run migration","worker":"Migrations","job_id":"t86u4sica7yedyfjpokzt61kxc","error":"SqlChannelStore.MigrateChannelMembers: Failed to select the batch of channel members, sql: Scan error on column index 3: converting driver.Value type <nil> (\"<nil>\") to a int64: invalid syntax"}`

I suspect that it can be related to https://github.com/mattermost/mattermost-server/issues/9215

**Comment by amyblais** [comment]
Hi @Dropsik - this seems to be the same error as in the other Issue you had opened. Did you try the suggestions given by our devs here https://github.com/mattermost/mattermost-server/issues/9215#issuecomment-411419187?

**Comment by Dropsik** [comment]
@amyblais yes, but I think it's a root cause - so I opened issue only for this. Maybe someone know, how to fix this.

**Comment by amyblais** [comment]
I'll close this Issue for now as it can be followed on https://github.com/mattermost/mattermost-server/issues/9215.
