### ISSUE TITLE
Relative URL's In Markdown Are Broken

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#9266]
#### Summary
Relative URLs in markdown are prepended with `http://`, causing them to fail.

#### Steps to reproduce
Enter a markdown message with a relative link, for example -

    [A Relative Link](/static/files/5b4a7904a3e041018526a00dba59ee48.png)

That link should be for the Mattermost logo image. Change if as required.

#### Expected behavior
The rendered link should navigate to the original relative URL on the current domain.

#### Observed behavior (that appears unintentional) 
The rendered link's URL has been modified to `http:///static/files/5b4a7904a3e041018526a00dba59ee48.png`, or in general `http://<the original relative URL>`.

Relative URLs in markdown are extremely useful for plugins as they allow linking to a plugin page or other resource without knowing the Mattermost domain. Otherwise, the plugin would have to include a redundant Mattermost domain setting.

**Comment by amyblais** [comment]
Hi @harshilsharma63!

What server version are you seeing this on?

**Comment by harshilsharma63** [comment]
@amyblais I used v5.1. I can try on v5.2 as well.

**Comment by harshilsharma63** [comment]
@amyblais I can confirm that this occurs on v5.2 as well.

**Comment by amyblais** [comment]
I'll close this Issue for now as the Jira ticket has been resolved and tested internally. The fix will be available in v5.4 (to be released in October 16th). Let us know if you still see the issue after upgrading,

**Comment by harshilsharma63** [comment]
@amyblais sure!
