### ISSUE TITLE
Image preview of multiple redirected URLs doesn't work

### ISSUE THREAD

**Issue by philiplb** [mattermost/mattermost-server#9267]
#### Summary
The image preview isn't triggered with URLs returning an HTTP 30x.

#### Steps to reproduce
In Mattermost 5.1.1

#### Expected behavior
When I send an URL redirecting to an image, the preview should be shown. Example:
https://www.dropbox.com/s/uyhaanh0aglo900/Screenshot%202018-08-17%2011.22.19.png?dl=0 leads to https://www.dropbox.com/s/raw/uyhaanh0aglo900/Screenshot%202018-08-17%2011.22.19.png
Which leads to https://uc6afe9ac150308892db14c446e8.dl.dropboxusercontent.com/cd/0/inline/AOIxUVmbaqcAxIquuFAr3XvfdBc-xwZIMAyO6kgYde_xdwys1_jsK8dZkkDtkPgGeCKD4I_ydlaTlceM8N89EU5M_xaSZww8qu4YacyG4-DAzuEWG6_tpKapg4HiL_9KFcHeGzBwSB22b2-JNdSPeotMggrU2v78uA7pxVKTrBZBY3hz1KwIdy-x-yP4EMM2-6U/file

See this curl:

```bash
curl -i https://www.dropbox.com/s/uyhaanh0aglo900/Screenshot%202018-08-17%2011.22.19.png\?dl\=0
HTTP/2 301
server: nginx
date: Fri, 17 Aug 2018 09:22:38 GMT
content-type: text/html; charset=utf-8
content-length: 0
cache-control: no-cache
content-security-policy: sandbox
location: /s/raw/uyhaanh0aglo900/Screenshot%202018-08-17%2011.22.19.png
pragma: no-cache
referrer-policy: origin-when-cross-origin
set-cookie: locale=en; Domain=dropbox.com; expires=Wed, 16 Aug 2023 09:22:38 GMT; Path=/; secure
set-cookie: gvc=MzA3NzIwNDQxMjEwMzQxNzEyMTM5NjMwNjU0Nzg1MTU1NzQ4ODA4; expires=Wed, 16 Aug 2023 09:22:38 GMT; httponly; Path=/; secure
set-cookie: flash=; Domain=dropbox.com; expires=Fri, 17 Aug 2018 09:22:38 GMT; Path=/; secure
set-cookie: puc=; expires=Fri, 17 Aug 2018 09:22:38 GMT; httponly; Path=/; secure
set-cookie: bang=; Domain=dropbox.com; expires=Fri, 17 Aug 2018 09:22:38 GMT; Path=/; secure
set-cookie: t=mQq8AVhrOUdBuIyhOYrHS4lm; Domain=dropbox.com; expires=Mon, 16 Aug 2021 09:22:38 GMT; httponly; Path=/; secure
set-cookie: __Host-js_csrf=mQq8AVhrOUdBuIyhOYrHS4lm; expires=Mon, 16 Aug 2021 09:22:38 GMT; Path=/; secure
x-content-type-options: nosniff
x-dropbox-request-id: 2187b16b44ae8f3d897b64aaf35d6f31
x-frame-options: DENY
x-robots-tag: noindex, nofollow, noimageindex
x-xss-protection: 1; mode=block
strict-transport-security: max-age=15552000; includeSubDomains
```
```bash
curl -i https://www.dropbox.com/s/raw/uyhaanh0aglo900/Screenshot%202018-08-17%2011.22.19.png
HTTP/2 302
server: nginx
date: Fri, 17 Aug 2018 09:39:56 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: https://uc6afe9ac150308892db14c446e8.dl.dropboxusercontent.com/cd/0/inline/AOIxUVmbaqcAxIquuFAr3XvfdBc-xwZIMAyO6kgYde_xdwys1_jsK8dZkkDtkPgGeCKD4I_ydlaTlceM8N89EU5M_xaSZww8qu4YacyG4-DAzuEWG6_tpKapg4HiL_9KFcHeGzBwSB22b2-JNdSPeotMggrU2v78uA7pxVKTrBZBY3hz1KwIdy-x-yP4EMM2-6U/file
cache-control: no-cache
content-security-policy: sandbox
pragma: no-cache
referrer-policy: origin-when-cross-origin
set-cookie: locale=en; Domain=dropbox.com; expires=Wed, 16 Aug 2023 09:39:56 GMT; Path=/; secure
set-cookie: gvc=MTY5MzI4MTYwMjIyOTY0MDY3NTc1NjEyMDA5ODQ0NzY2MDg3NTA3; expires=Wed, 16 Aug 2023 09:39:56 GMT; httponly; Path=/; secure
set-cookie: flash=; Domain=dropbox.com; expires=Fri, 17 Aug 2018 09:39:56 GMT; Path=/; secure
set-cookie: puc=; expires=Fri, 17 Aug 2018 09:39:56 GMT; httponly; Path=/; secure
set-cookie: bang=; Domain=dropbox.com; expires=Fri, 17 Aug 2018 09:39:56 GMT; Path=/; secure
set-cookie: t=5QIIgAsVQSc_Q9IUAhYBRxWz; Domain=dropbox.com; expires=Mon, 16 Aug 2021 09:39:56 GMT; httponly; Path=/; secure
set-cookie: __Host-js_csrf=5QIIgAsVQSc_Q9IUAhYBRxWz; expires=Mon, 16 Aug 2021 09:39:56 GMT; Path=/; secure
x-content-type-options: nosniff
x-dropbox-request-id: 0714989f63ba684ac9fa798e1f3be554
x-frame-options: DENY
x-xss-protection: 1; mode=block
strict-transport-security: max-age=15552000; includeSubDomains
```

#### Observed behavior (that appears unintentional) 
No image was shown in the Web Client.

**Comment by amyblais** [comment]
Hi @philiplb, thank you for reporting this!

We'll test this out and create a Jira ticket if we can reproduce this.

**Comment by amyblais** [comment]
@philiplb One of our developers helped fix this and said it looks fine for them although it shows through an OpenGraph preview instead, can you help check if you have that turned off?

**Comment by philiplb** [comment]
Hi,
I just tried it again with the most current version (5.2.0) and it isn't working for me. Actually, only the second URL (of the first redirect) shows an image for me: https://www.dropbox.com/s/raw/uyhaanh0aglo900/Screenshot%202018-08-17%2011.22.19.png

How can I check if I have turned off OpenGraph?

I tried it in Rambox (Electron-App) and Firefox, both show the same behaviour.

**Comment by amyblais** [comment]
Hi @philiplb,

I believe it is this setting in the System Console - it should be enabled: https://docs.mattermost.com/administration/config-settings.html#enable-link-previews.

**Comment by philiplb** [comment]
Hi,
thanks again. :)
Now the first URL works as website preview. I can see the image which is fine for us but it still is different. Here are the exact results/differences:
![screen shot 2018-08-23 at 17 13 37](https://user-images.githubusercontent.com/1672238/44534429-0e7d6800-a6f8-11e8-8916-3214f71148a7.png)

**Comment by amyblais** [comment]
Thanks @philiplb! I created a ticket for this here: https://mattermost.atlassian.net/browse/MM-11835.

**Comment by amyblais** [comment]
The Jira ticket was closed as the team determined that it's not a bug. One of the URLs is to a page on dropbox.com complete with open graph metadata, so it shows the open graph preview. The other is a direct link to a png file so shows the PNG file preview.

Closing this Issue for now,
