### ISSUE TITLE
Secret type field in plugin settings is not selectable/copy-able in Firefox.

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#9271]
#### Summary
Secret type field in plugin settings is not selectable/copy-able in Firefox.

#### Steps to reproduce
1. Open Mattermost on Mozilla Firefox web browser.
1. Open settings of any plugin that used a secret field - prepackaged Jira plugin will do.
1. Scroll to the secret field (`Webhook Secret` in case of Jira plugin).
1. Regenerate it's value if not already populated.
1. Try copying the generated value.

#### Expected behavior
The value in the secret field is selected and the user can now copy it.

#### Observed behavior (that appears unintentional) 
The value in the secret field is not selectable.
Note that it is perfectly selectable on Google Chrome. 

#### Possible fixes
One option would be to use `readonly="readonly"` instead of `disabled=""`. But `readonly` has issues of its own.

Another option is to render `div` instead of `input` for secret fields.

I'm on v5.2 :)

**Comment by amyblais** [comment]
Hi @harshilsharma63!

I was able to repro this and created a ticket here: https://mattermost.atlassian.net/browse/MM-11763.

**Comment by harshilsharma63** [comment]
@amyblais  thanks!

**Comment by amyblais** [comment]
The Jira ticket and associated PR are completed and we have tested internally that this works in v5.3 - feel free to re-open this Github Issue if the issue persists after upgrading to v5.3 (which will be released in Sept. 14th).
