### ISSUE TITLE
Search users by "Position" field.

### ISSUE THREAD

**Issue by spfuture** [mattermost/mattermost-server#9272]
Subj.

**Comment by amyblais** [comment]
Hi @spfuture,

Can you help with a description of the issue and your environment so that we can help troubleshoot this?

**Comment by spfuture** [comment]
i cant find any persons in channel or in personal messages by Position.

For example  i have 3 "web-developer" users, and 2 "c# developers", i can find then by FirstName, LastName, nickname but field "Position"  is out of search.

It would be great if the search for the field position was possible.

i think we need extend mattermost-server/store/sqlstore/user_store.go
32 line
`	USER_SEARCH_TYPE_ALL                = []string{"Username", "FirstName", "LastName", "Nickname", "Email"}
` to
`	USER_SEARCH_TYPE_ALL                = []string{"Username", "FirstName", "LastName", "Nickname", "Email", "Position"}
`

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @spfuture!  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by spfuture** [comment]
Done, thanks.
[https://mattermost.uservoice.com/forums/306457-general/suggestions/18601075-team-specific-position](url)
