### ISSUE TITLE
Inline base64 images not working

### ISSUE THREAD

**Issue by inakivb** [mattermost/mattermost-server#9274]
#### Summary
Images with inline source in base64 strips the base64 content.

#### Steps to reproduce
Insert one image with inline source
```
Red dot: ![red dot](data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
```

#### Expected behavior
Print the image with this html:
```html
<p>Red dot: <img class="markdown-inline-img" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA&#10;AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="red dot"></p>
```

#### Observed behavior (that appears unintentional) 
This html is printed
```html
<p>Red dot: <img class="markdown-inline-img" src="data:image/png;base64," alt="red dot"></p>
```

#### Possible fixes
Don't escape content after `,`

**Comment by inakivb** [comment]
Hi!
I find out a solution and maybe this is not a bug.
While in HTML, follow the `,` with a white char is a valid image source, it breaks mattermost.

To solve the issue just remove the empty space so the message looks like
```
Red dot: ![red dot](data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
```

**Comment by amyblais** [comment]
Hi @inakivb, thank you for reaching out.

What OS and Mattermost server version are you using?

**Comment by inakivb** [comment]
Hi @amyblais ,
Ubuntu 16.04 LTS
Postgresql 9.5
Mattermost 5.1

thank you!

**Comment by amyblais** [comment]
Hi @inakivb, thank you for the details and apologies for the delay,

Can you also help with details on what browser and device you are seeing this on?

**Comment by inakivb** [comment]
Hi @amyblais ,
I can test in web and iOS and it happens in both, but with different behaviour
**Desktop**: it generates the HTML from the first post
 ![image](https://user-images.githubusercontent.com/8626495/44569210-e59db700-a779-11e8-80f8-0ee40d00bcfd.png)

**iOS**: It doesn't parse the markdown
![image](https://user-images.githubusercontent.com/8626495/44569272-17af1900-a77a-11e8-9ef9-b0f4a32d3b2d.png)

As I said [in my previous response](https://github.com/mattermost/mattermost-server/issues/9274#issuecomment-414293161), maybe it is not a bug and it is now _documented_ with this issue

**Comment by amyblais** [comment]
Hi @inakivb!

I created a ticket for this as I'm able to reproduce this also without the spacing: https://mattermost.atlassian.net/browse/MM-11834.

Our developers will let me know if there is a known workaround for this.

**Comment by amyblais** [comment]
Hi @inakivb!

The ticket was closed as "Won't Fix" as it seems that we don't support inline base64 images yet - would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project

**Comment by inakivb** [comment]
Hi @amyblais 
Thank you for your time.
Just for the record, it seems that it works without problem if the space is deleted in all platforms.

```
Red dot: ![red dot](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
```
prints:
![image](https://user-images.githubusercontent.com/8626495/44780772-03588b00-ab83-11e8-95be-4ca59cdc6773.png)

Thank you!

**Comment by amyblais** [comment]
Good to hear, I'll close this Issue for now as this has a simple workaround,
