### ISSUE TITLE
Support Ninja Edits

### ISSUE THREAD

**Issue by towolf** [mattermost/mattermost-server#9276]
#### Summary
Ninja edits are post edits that occur very shortly after the initial submission. These edits do not receive the `(edited)` marking.

It would be nice to give users a little grace period to fix their spelling mistakes, e.g. 1 minute, before the `(edited)` label is appended to the message. On Reddit it works that way.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @towolf!

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by towolf** [comment]
[Post on MM uservoice](https://mattermost.uservoice.com/forums/306457-general/suggestions/35165791-support-ninja-edits)

**Comment by amyblais** [comment]
Thank you @towolf!

I'll close this Issue for now as it can be followed via the linked Uservoice ticket. If you're interested in helping implement the improvement, please let us know,
