### ISSUE TITLE
JIRA-plugin broken in v5.2.0

### ISSUE THREAD

**Issue by grajsor** [mattermost/mattermost-server#9278]
#### Summary
JIRA-plugin broken in v5.2.0

#### Steps to reproduce
Install Mattermost v5.2 fresh.

#### Expected behavior
JIRA-plugin accepting JSON-strings

#### Observed behavior (that appears unintentional) 
{"level":"error","ts":1534778830.9738247,"caller":"app/plugin_requests.go:33","msg":"Access to route for non-existent plugin","...ound: jira"}

#### Possible fixes
Enabling / disabling the JIRA-plugin i Mattermost v5.2 does not have any effect. Incomming webhooks works fine, but the JIRA-plugin does not.

**Comment by grajsor** [comment]
> {"level":"error","ts":1534836263.0501106,"caller":"app/plugin_requests.go:33","msg":"Access to route for non-existent plugin","missing_plugin_id":"jira","error":"plugin not found: jira"}
> {"level":"error","ts":1534836482.2647781,"caller":"app/plugin_requests.go:33","msg":"Access to route for non-existent plugin","missing_plugin_id":"jira","error":"plugin not found: jira"}
> {"level":"error","ts":1534836555.4179564,"caller":"app/plugin_requests.go:33","msg":"Access to route for non-existent plugin","missing_plugin_id":"jira","error":"plugin not found: jira"}
> {"level":"error","ts":1534837149.2953155,"caller":"app/plugin_requests.go:33","msg":"Access to route for non-existent plugin","missing_plugin_id":"jira","error":"plugin not found: jira"}
> {"level":"error","ts":1534838364.9250982,"caller":"app/plugin_requests.go:33","msg":"Access to route for non-existent plugin","missing_plugin_id":"jira","error":"plugin not found: jira"}
> {"level":"error","ts":1534838393.115814,"caller":"app/plugin_requests.go:33","msg":"Access to route for non-existent plugin","missing_plugin_id":"jira","error":"plugin not found: jira"}

**Comment by grajsor** [comment]
Sure thing!

![mm1](https://user-images.githubusercontent.com/18514409/44399906-907b5e80-a549-11e8-9b1f-f77aea5fdd5c.PNG)
![mm2](https://user-images.githubusercontent.com/18514409/44399912-95401280-a549-11e8-8e73-27a37c92ccfb.PNG)
![mm3](https://user-images.githubusercontent.com/18514409/44399915-9a9d5d00-a549-11e8-8490-380992bd51f6.PNG)

Thanks in advance <3

**Comment by jasonblais** [comment]
Thanks @grajsor for the quick follow-up - looks like on the Management page, the JIRA plugin isn't running.

Can you help click "Enable" on the Management page? 
![image](https://user-images.githubusercontent.com/13119842/44400106-ff3fc400-a517-11e8-8c41-f38913d72e59.png)

**Comment by grajsor** [comment]
Oh my, I wonder how on earth that managed to get disabled from V5.1 -> V5.2... 

This solved my problem, will investigate as to WHY this happened. Thanks a bunch! :+1:

**Comment by jasonblais** [comment]
Thanks @grajsor! If you find out the reason and suspect it might be a bug, let us know and we'll fix it

**Comment by sraupach** [comment]
Hey. I have the same issue on a 5.6 cluster and i can not enable it in cluster mode for both nodes over the System Console.

The configuration is fine (jira->true)

**Comment by jasonblais** [comment]
@sraupach Do you see any errors in the server logs (System Console > Logs)?

**Comment by sraupach** [comment]
@jasonblais there has been one error.

> {"level":"error","ts":1545201442.0596876,"caller":"app/plugin_requests.go:35","msg":"Access to route for non-existent plugin","missing_plugin_id":"jira","error":"plugin not found: jira"}

![grafik](https://user-images.githubusercontent.com/8362597/50203524-15448080-0362-11e9-972d-618d21fd2cb5.png)

In our config.json we have enabled jira but it does not start by application start which it did before upgrading to 5.6.

**Comment by jasonblais** [comment]
@sraupach Thank you for the report, we've reached out to our engineers for thoughts.

**Comment by jasonblais** [comment]
@sraupach We've identified the cause and fixed it. We'll release 5.6.1 this week along with a couple of other fixes. You can track progress of your JIRA ticket here: https://mattermost.atlassian.net/browse/MM-13558

Changelog for 5.6.1 is drafted here https://docs.mattermost.com/administration/changelog.html#release-v5-6

**Comment by jasonblais** [comment]
@sraupach To follow up - you can also take these steps to fix the issue on your JIRA plugin without waiting for our 5.6.1 release:

1. Remove the JIRA plugin archive in `prepackaged_plugins/` folder.
2. Upload an updated version of the JIRA plugin containing the fix in System Console > Plugins > Management. Here is the updated version of the plugin: https://github.com/mattermost/mattermost-plugin-jira/releases/download/v1.0.3/jira-1.0.3.tar.gz

If you have any questions, let us know!

**Comment by sraupach** [comment]
@jasonblais i did exchange the Plugin v1.0.2 with v1.0.3 on Mattermost 5.6.0.

The behaviour looks good to me but the plugin itself does not work.
<img width="458" alt="grafik" src="https://user-images.githubusercontent.com/8362597/50272180-388d2f80-0437-11e9-8bcb-4f4c44888739.png">

**Comment by jasonblais** [comment]
@sraupach Do you see errors in the **System Console > Logs** related to the JIRA plugin? Or any errors in **System Console > Plugins > Management**?

As a note, we're releasing 5.6.1 in a few hours that contains a fix for the JIRA plugin - the download links will be available at https://mattermost.com/download/ soon.

Appreciate your patience.

**Comment by jasonblais** [comment]
@sraupach Do you see errors in the **System Console > Logs** related to the JIRA plugin? Or any errors in **System Console > Plugins > Management**?

As a note, we're releasing 5.6.1 in a few hours that contains a fix for the JIRA plugin - the download links will be available at https://mattermost.com/download/ soon.

Appreciate your patience.

**Comment by sraupach** [comment]
@jasonblais we are logging on level ERROR and the logs are "clean". The Management Page looks fine aswell.

![grafik](https://user-images.githubusercontent.com/8362597/50294946-4bbfef80-0477-11e9-9fe2-7bda8a463bcc.png)

Do you guess that an update to 6.5.1 will solve the issue?

**Comment by lindy65** [comment]
Hi @sraupach,

Jason is out for a little while so I thought I'd let you know that the download links for 5.6.1 are now available at https://mattermost.com/download/

I'm guessing that the Jira plugin fix that went into this patch will help resolve your issue.  If you're still having problems after upgrading, please let us know and we can ask one of our devs to help troubleshoot further.

**Comment by jasonblais** [comment]
@sraupach There are still some reports of the JIRA plugin not working in 5.6.1 and we've been able to reproduce it.

The plan is to fix this with 5.6.2, which we expect to release shortly after the holidays. Here is the ticket to track: https://mattermost.atlassian.net/browse/MM-13581

**Comment by jasonblais** [comment]
@sraupach We have released 5.6.2 which should fix any remaining issues with the JIRA plugin. It is available to download here https://mattermost.com/download/

If you notice any further issues, please let us know.
