### ISSUE TITLE
Slash commands with GET crush query parameters on configured endpoint URL

### ISSUE THREAD

**Issue by andi-livn** [mattermost/mattermost-server#9279]
Following the fix for [MM-10201,](https://mattermost.atlassian.net/browse/MM-10201) that addressed the issue of GET slash commands including a payload in the request body, Mattermost's meta data is now URL encoded into the query string instead.

The only problem is, that while doing so, Mattermost also removes/crushes any query parameters that may exist on the configured slash command URL itself.

Example: We have a slash command that uses a GET call to the URL https://host.doesntmatter.com/mattermost?cmd=ourCommand

It is vital that the request include the query parameter `cmd=outCommand`.
Before version 5.0 and the fix for MM-10201, this worked as expected, but now instead of calling 

`GET https://host.doesntmatter.com/mattermost?cmd=ourCommand`

Mattermost actually calls something that looks like this (modified for brevity and security)

`GET https://host.doesntmatter.com/mattermost?channel_id=lkjhsdfljhlsdhjdfjljhsdf&channel_name=me&command=%2Fourslashcommand&response_url=https%3A%2F%2Fmattermost.doesntmatter.com%2Fhooks%2Fcommands%2Fkjhsdfkjhkjhskdjhf&team_domain=doesntmatter&team_id=jkhsddfkhjskjdhfkjsdf&text=&token=ljhsdfkjhsfdjhskdfhlkjs&user_id=lkjhsdfkjhskldjhfkjhsdf&user_name=itmattersnot`

So rather than adding its own data to the configured slash command endpoint URL as query parameters and preserving our own configured query parameter, Mattermost simply omits ourCommand from the request, which in our case breaks the implementation, because it depends on the ourCommand parameter being present.

Suggested fix: Rather than merely setting its own data as request query string, merge in any potential parameters from the configured endpoint URL. In the above example, we would expect to see this request:

`GET https://host.doesntmatter.com/mattermost?cmd=ourCommand&channel_id=lkjhsdfljhlsdhjdfjljhsdf&channel_name=me&command=%2Fourslashcommand&response_url=https%3A%2F%2Fmattermost.doesntmatter.com%2Fhooks%2Fcommands%2Fkjhsdfkjhkjhskdjhf&team_domain=doesntmatter&team_id=jkhsddfkhjskjdhfkjsdf&text=&token=ljhsdfkjhsfdjhskdfhlkjs&user_id=lkjhsdfkjhskldjhfkjhsdf&user_name=itmattersnot`

**Comment by amyblais** [comment]
Hi @andi-livn!

The developer who owns the fix / improvement for the ticket that you linked above is off this week, and I'll ask him about this as soon as he is back.

**Comment by amyblais** [comment]
@lieut-data I was wondering if you could help take a look if I should open a ticket for this? 

They are referring to this ticket and I decided to ping you since you're the 'owner' of the ticket: https://mattermost.atlassian.net/browse/MM-10201.

**Comment by lieut-data** [comment]
Hi @andi-livn -- thanks for the report!

Your suggestion seems reasonable. One ambiguity might be how to handle duplicate querystring parameters -- e.g. if your implementation requires a `channel_id` parameter of your own. I'd propose a simple concatenation, with the Mattermost fields added after the configured query string.

In the short term, is switching to the `POST` endpoint an option? Or can you key off the `token` that uniquely identifies this webhook instead? (I'm imagining that you're doing this because of a load balancer rule or some such.)

@amyblais, yes let's open a ticket to effect this change.

**Comment by amyblais** [comment]
Thanks all, created a ticket here: https://mattermost.atlassian.net/browse/MM-11895.

**Comment by andi-livn** [comment]
Thanks for taking this on board. Wish I had some Golang XP to offer my help. 

@lieut-data , We've now split up the service resources that drive our slash commands, removing the need for query paramters, but the use case for custom query parameters does of course still very much exist. Sadly there is simply nothing on duplicate query parameters in RFC 3986, the specs for URI-s, and every platform appears to handle dupes somewhat differently, e.g. by discarding all but the first/last value of a parameter key, automatic grouping into an array or concatenation into a single comma separated string. 
If I understand right, you are suggesting to concatenate the full query strings, rather than individual duplicate parameters, so for instance if the user defined base URL were 
`https://host.doesntmatter.com/mattermost?channel_id=ourValue`, 
you mean forming the request URL as 
`https://host.doesntmatter.com/mattermost?channel_id=ourValue&channel_id=lkjhsdfljhlsdhjdfjljhsdf&channel_name=...`, 
rather than 
`https://host.doesntmatter.com/mattermost?channel_id=ourValue,lkjhsdfljhlsdhjdfjljhsdf&channel_name=...`.

Given the URI specs do not explicitly forbid duplicate parameters, I think that is fair enough, even if it might mean loosing either value of the `channel_id` parameter, in this case, depending on the employed server side platform's handling of duplicates (Java only uses the first and discards repeats, PHP the other way around, .NET forms an array and so on).

What I would recommend, however, is to show a warning in any GUI forms this project maintains, that are used to configure slash commands, informing users about this behaviour and possibly discouraging the use of Mattermost's "reserved" keys (`channel_id, channel_name, command, response_url, team_domain, team_id, text, token, user_id, user_name`).

**Comment by lieut-data** [comment]
Yes, that's it precisely @andi-livn. I agree that a warning is in order explaining how any configured query string is merged when `GET` is configured.

**Comment by amyblais** [comment]
The Jira ticket has been resolved and tested internally and the fix will be available in v5.4 release.
