### ISSUE TITLE
Entering a chat with some website previews causes jumps in Safari

### ISSUE THREAD

**Issue by philiplb** [mattermost/mattermost-server#9297]
#### Summary
If you enter a chat with Safari containing some website previews, the position of the messages is a bit up and you need to scroll down.

#### Steps to reproduce
Use Safari and post a few messages with website previews, leave the chat and enter the chat again. Used version of Mattermost is 5.2.1, Safari is 11.1.2 on MacOS 10.13.6.

#### Expected behavior
The chat position should be at the bottom without need to scroll.

#### Observed behavior (that appears unintentional) 
![safariglitch](https://user-images.githubusercontent.com/1672238/44588214-64fcac00-a7b5-11e8-8774-7546921d22b2.gif)

**Comment by amyblais** [comment]
Hi @philiplb, thank you!

I opened a ticket here: https://mattermost.atlassian.net/browse/MM-11833.

**Comment by hanzei** [comment]
This was fixed with the new scrolling overhaul
