### ISSUE TITLE
[Help Wanted] [MM-11683] Bulk Import does not support attachments on GM/DM posts

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9304]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11683)

Bulk import supports file attachments on regular posts and their replies, but not on "DirectPosts" i.e. root posts in Direct or Group message channels.

**Comment by jespino** [comment]
@pradeepmurugesan Do you want to pick this one?

**Comment by pradeepmurugesan** [comment]
@jespino sure.. 👍

**Comment by jespino** [comment]
awesome! :)

**Comment by jespino** [comment]
Merged! One more time **thank you** @pradeepmurugesan
