### ISSUE TITLE
[Help Wanted] [MM-11424] Extend bulk import to support themes across teams

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9305]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11424)

The User JSONL object (https://docs.mattermost.com/deployment/bulk-loading.html#user-object) does currently support the full data model. The following items need to be added for 5.0:

Themes:
Existing model only supports a single theme. Users can select themes for each team they are a member of. The User object should be extended to add:

{noformat}
"user": {
   ...
  "themes": [
      {"team": "", "theme": ""}
      ...
   ]
   ...
}
{noformat}

Also need to add support for fields currently missing including:

Advanced Settings:
* 'feature_enabled_markdown_preview'
* 'formatting'

Sidebar Settings:
* 'show_unread_section'

**Comment by FurmanovD** [comment]
I'll work on this issue

**Comment by FurmanovD** [comment]
@esethna  @jespino looks like the "teams" array is much better object to place the "theme" selected by user because it has all other info related to user's teams.
my suggestion is to have a structure to import:
{noformat}
"user": {
...
"teams": [
{"name": "...", "roles": "..." , "theme":""  }
...
]
...
}
{noformat}
