### ISSUE TITLE
Ctrl+M is an undocumented shortcut and has surprising behavior on the Windows app

### ISSUE THREAD

**Issue by ryantm** [mattermost/mattermost-server#9306]
#### Summary
The Ctrl+M shortcut sends a message. Also, on the Windows app it sends the message right away, minimizes the window, then when you restore the window it looks like it is sending the message.

#### Steps to reproduce
Press Ctrl+M after composing a message. See that Ctrl+M is not documented in the Ctrl+/ menu 

![image](https://user-images.githubusercontent.com/4804/44603913-307af700-a799-11e8-94cf-e343050a5359.png)

#### Expected behavior
I didn't expect Ctrl+M to do anything. I found this out by accidentally typing it. It is also surprising that this keyboard shortcut is not mentioned in the preferences relating to Ctrl+Enter sending a message.

On the Windows App, I was not expecting Ctrl+M to minimize the window, since the standard minimize shortcut is Windows + Down Arrow (Ctrl+M is documented to minimize the app on the Window menu).

**Comment by amyblais** [comment]
Hi @ryantm, thank you for reporting this 👍 

Do you happen to know whether this reproduces on other apps or is this unique to Mattermost?

**Comment by ryantm** [comment]
> Do you happen to know whether this reproduces on other apps or is this unique to Mattermost?

What apps did you have in mind?
 
It doesn't seem to be a general feature of Google Chrome, for example, pressing Ctrl+M on this GitHub text box doesn't post the comment. I should probably make it extra clear that this Ctrl+M behavior happens in the web version of Mattermost too.

**Comment by amyblais** [comment]
Hi @ryantm,

I did some research on this and it looks like Ctrl+M behaves the same as Enter key: https://superuser.com/questions/595340/what-do-ctrl-j-ctrl-m-and-ctrl-i-mean-in-microsoft-notepad.

I also asked about this from the team and they believe this is the case. Probably we should add a note about this in our docs, I'll create a ticket soon for this.

**Comment by ryantm** [comment]
Mattermost isn't a terminal application where it might be difficult to distinguish between Ctrl+M and Enter. Here is a little test I did in Chrome:

![image](https://user-images.githubusercontent.com/4804/44670768-75d93780-a9d8-11e8-87a8-ca6fffbd8020.png)

**Comment by amyblais** [comment]
Update: I asked the team about the next steps for this and I'll let you know their feedback - if I don't get much feedback I'll open a ticket by tomorrow latest and this will then be discussed during a meeting within the next few days.

**Comment by amyblais** [comment]
I opened a ticket here and it will be discussed in the next few days: https://mattermost.atlassian.net/browse/MM-11896.

**Comment by amyblais** [comment]
Hi @ryantm,

Again, thanks for the report! We have created a [Help Wanted issue here](https://github.com/mattermost/mattermost-server/issues/9398) and are looking for community's help. Please let us know if you're interested in helping with a pull request.
