### ISSUE TITLE
[Help Wanted] [MM-11860] Expose slack attachment parsing functions in the model package

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9316]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11860)

Plugins use Slack attachments all the time to better render posts. We have some functions in the app package used for parsing and processing them. Refactor those functions into the model directory so that plugins have access to them.

These two functions in particular:
https://github.com/mattermost/mattermost-server/blob/master/app/post.go#L312

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by esethna** [comment]
Awesome, thanks @cjbirk! Feel free to reach out to us for guidance if needed. You can join the contributors channel on our pre-release server here: https://pre-release.mattermost.com/core/channels/tickets

**Comment by cjbirk** [comment]
I have code ready to merge but I'm not certain about the "Checklist" section of the PR guidelines. I don't see any option for 'code refactoring' and I don't think this is really a feature addition? Please let me know if I'm OK to submit this with a blank checklist.

I wrote a plugin to test this.. I can perhaps link to that in the PR?

**Comment by jespino** [comment]
@cjbirk You can submit it following the PR template and removing the checklist items that don't apply to your changes.

**Comment by jwilander** [comment]
Thanks @cjbirk!
