### ISSUE TITLE
"Jump To" is not finding all users / mobile / android + iPhone

### ISSUE THREAD

**Issue by arutkowska** [mattermost/mattermost-server#9322]
Observed: Currently when i use "Jump to conversation" I cannot find all users who belong to teams we use.
(it does not matter whether I had conversation with them before, reinstalling app didn't help)

Expected: with Jump To, I want to be able to find all available team members for all teams i belong to.

**Comment by amyblais** [comment]
Hi @arutkowska!

We have a ticket open for this here https://mattermost.atlassian.net/browse/MM-11816 and a fix for it will be included in v1.12: https://github.com/mattermost/mattermost-mobile/pull/2021.

**Comment by amyblais** [comment]
Hi @arutkowska!

The ticket I referenced above has been resolved - the fix will be available in v1.12 which is scheduled to be released tomorrow.
