### ISSUE TITLE
Permalink Behavior Different In SlackAttachment and Post Message 

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#9329]
#### Summary
A post's permalink, when used in markdown, has different behavior in post's message and post's `SlackAttachment`. `SlackAttachment` and `SlackAttachmentField` have same (incorrect) behavior though.

#### Steps to reproduce
1. Copy a post's permalink.
1. Create a new post from UI with markdown, linking some text to the copied permalink -

    [Some random text](<a post's permalink>)

1. Now create a post via plugin API and have the same markdown in `Post.SlackAttachment.Text`.

#### Expected behavior
Clicking on the link in `SlackAttachment` or `SlackAttachmentField` should work the same way as clicking on the link in post's message - navigating to destination post without a full page reload.

#### Observed behavior (that appears unintentional) 
Clicking on the link created in post's message leads to destination post without causing a page to reload. Clicking on the link from `SlackAttachment` or `SlackAttachmentField`, however, causes the page to reload, taking significantly more time.

**Comment by amyblais** [comment]
Thank you @harshilsharma63! I'll test this out soon.

**Comment by amyblais** [comment]
@harshilsharma63 Created a ticket for this here: https://mattermost.atlassian.net/browse/MM-11982.

**Comment by amyblais** [comment]
The Jira ticket has been resolved and tested internally, and will be available in v5.4 release.
