### ISSUE TITLE
Seen by for Direct Messages and Channels

### ISSUE THREAD

**Issue by emresaracoglu** [mattermost/mattermost-server#9332]
Hi,

I wonder. How do I know when the direct message read/unread the message _(like social messaging applications, tick)?_
I can not see the notification in the message lines.

Is there such a feature available?
Thank you.

**Comment by amyblais** [comment]
Hi @emresaracoglu! Thanks for reaching out.

To clarify, do you mean you want to know when another person has read a direct message and if he has not read it yet?

If yes, this feature hasn't been implemented yet but we have some feature requests open here which you can upvote:
 - https://mattermost.uservoice.com/forums/306457-general/suggestions/12595398-read-receipts-implement-a-visual-indication-for-m
 - https://mattermost.uservoice.com/forums/306457-general/suggestions/17142488-show-for-read-mark-for-me-when-opponent-reads-your

If you're interested to help implement this feature, let us know!

**Comment by amyblais** [comment]
Hi @emresaracoglu, I'll forward your feedback to our product managers and ask what the status of this feature request is currently. I'll let you know their feedback.

**Comment by amyblais** [comment]
Hi @emresaracoglu, our product managers came back on this and said that unfortunately this is not currently on our roadmap.

Thank you for this feature suggestion and thank you for upvoting the Uservoice ticket! We'll provide an update via Uservoice when this feature is completed.

**Comment by emresaracoglu** [comment]
@amyblais Thank you for return

**Comment by abunasar** [comment]
@amyblais is there any update on this? almost all other solutions (rocketchat) has read receipts, why not mattermost?

thanks

**Comment by amyblais** [comment]
Hi @abunasar, I'm not aware of any updates on this. You can follow the progress here: https://mattermost.uservoice.com/forums/306457-general/suggestions/12595398-read-receipts-implement-a-visual-indication-for-m.

**Comment by lephisto** [comment]
Is there any update? Unfortunately the decision for us to go E10 depends on this..
