### ISSUE TITLE
Blank screen when uploading images when responding

### ISSUE THREAD

**Issue by peter-janssen** [mattermost/mattermost-server#9336]
#### Summary
Blank screen when uploading images (*.png) with a size above the maximum dimension limit when responding to a message.

#### Steps to reproduce
1. Respond to a message.
2. In the message details pane upload an image either by the paperclip or by drag-and-drop. The image should be larger than the maximum dimension limit.

#### Expected behavior
An error message should be shown below the text box containing the following:
"File above maximum dimensions could not be uploaded: \<filename\>"

#### Observed behavior (that appears unintentional) 
A completely blank screen with below source code (head section removed for brevity and unintentional information disclosure). Observed in chrome 68, internet explorer 11 and the windows client 4.1.2. Mattermost server version 4.10.

``` html
<html lang="en">
  <script type="text/javascript">window["_gaUserPrefs"] = { ioo : function() { return true; } }</script> 
  <head>...</head> 
  <body class="font--open_sans"> 
    <div id="root" class="channel-view multi-teams"></div> 
    <noscript> To use Mattermost, please enable JavaScript. </noscript>   
  </body>
</html>
```

The following error is shown in the console along with two `Minified React error #31` errors:
```
client.js:772 POST https://<host>/api/v4/files 400 ()
```

#### Possible fixes
na

**Comment by amyblais** [comment]
Hi @peter-janssen, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
