### ISSUE TITLE
Plugin is activated even if server component fails

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#9338]
#### Summary
Up until Mattermost v5.1, is the server component of a plugin failed to activate, the whole plugin would fail and the error would be reported in the plugins management setting in the system console.

But, since v5.2, even if server component failed to load, (an error in OnActivate() hook for example), ther plugin still loads and gets activated with just the server component running. No error is reported in the UI whatsoever.

#### Steps to reproduce
1. Create a plugin containing both server and webapp components.
1. Intentionally fail the activation of the server component, for example by returning an error in the `OnActivate()` hook.
1. Load and activate the plugin. Notice that no error is reported in UI; the webapp component keeps running, and error for server com[opnent is reported in Mattermost logs.

#### Expected behavior
A plugin should not be enabled if either of server or webapp component fails to activate.

#### Observed behavior (that appears unintentional) 
The plugin gets enabled even if it's server component fails to activate

**Comment by amyblais** [comment]
Hi @harshilsharma63! 

Does this ticket look like the issue you are experiencing: https://mattermost.atlassian.net/browse/MM-11582?

**Comment by harshilsharma63** [comment]
@amyblais yes, it seems to be the same issue.

**Comment by amyblais** [comment]
The Jira ticket has been closed and tested internally, and will be available in v5.4 release,
