### ISSUE TITLE
OAuth state parameter invalid if its length > 128, vol 2.

### ISSUE THREAD

**Issue by mikroskeem** [mattermost/mattermost-server#9339]
See issue #7808

AuthorizeRequest has still [128 char limit](https://github.com/mattermost/mattermost-server/blob/570c52b4cc88d7d0864511b9a4cb6318a07a6dbb/model/authorize.go#L93) (checked in [/oauth/authorize](https://github.com/mattermost/mattermost-server/blob/d81a61398d01d839e70e2345da787e7ef89c0832/api4/oauth.go#L320)).

**Comment by amyblais** [comment]
Thanks @mikroskeem! I'll confirm on this with our devs.

**Comment by amyblais** [comment]
@jwilander ^

Context / reason for ping: You had previously worked on [this ticket](https://mattermost.atlassian.net/browse/MM-8558) so I thought you might know best whether I should create a ticket to fix the AuthorizeRequest 128 char limit?

Code here: https://github.com/mattermost/mattermost-server/blob/570c52b4cc88d7d0864511b9a4cb6318a07a6dbb/model/authorize.go#L93.

**Comment by mikroskeem** [comment]
Amazing, I hope this issue gets fixed before the release of v5.3 (if I understood correctly from issue 9930)

**Comment by amyblais** [comment]
Hi @mikroskeem,

Again, thank you for the report! We have created a [Help Wanted issue for this here](https://github.com/mattermost/mattermost-server/issues/9462) and are looking for community's help for the fix. Please let us know if you're interested in helping with a pull request.

I'll close this Issue for now as it can be tracked via the Help Wanted Issue,
