### ISSUE TITLE
When Mattermost obtains focus, always start typing in the message textfield when appropriate

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#9340]
Originally here: https://github.com/mattermost/desktop/issues/840 - but as per input belongs here.

One problem that I think most of us have experienced is when we click into the Mattermost client expecting to rip out a message on the tip of our fingers... and as we start to type, we find out that the darn input field "Write a message" is not focused!  This can be very frustrating.

It seems that much of the time the Mattermost client get's it right and you can click in the client or cmd-tab and bam, you're in business... but sometimes if you click in the "wrong spot" (and I'm not entirely sure what that is, perhaps quotes or rendered URL previews are a couple) and you can't type.  Instead of you have to click again down into the input field.

Mattermost should handle input field focus better.  Whenever keyboard entry happens and another location is not specifically selected like a search field or some config field, etc. the text input field for writing messages should be automatically focused and ready to go at the stroke of a finger.

**Comment by jasonblais** [comment]
Thanks @ylluminate! Does this help wanted ticket cover what you're looking for? https://github.com/mattermost/mattermost-server/issues/4142

**Comment by amyblais** [comment]
Hi @ylluminate,

Thanks for the report! I'll close this Issue for now as the progress can be followed via the [Help Wanted issue here](https://github.com/mattermost/mattermost-server/issues/4142). Let us know if you're interested in helping with a pull request.
