### ISSUE TITLE
System Console & Add Users to team menu items missing for admins

### ISSUE THREAD

**Issue by alecisec** [mattermost/mattermost-server#9344]
#### Summary
server_admin users can no longer add team members or access the system console

#### Steps to reproduce
version 5.1  - 5.2.1 server (patched and issue persisted)
Have checked role is assigned ($mattermost roles system_admin admin.username)
and verified in database that the 'role' field contains server_admin

#### Expected behavior
don't believe it was an issue on 5.0 

#### Observed behavior (that appears unintentional) 
Server admins only see the same menu-items as regular users

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by alecisec** [comment]
I've just observed that navigating to https://<mattermost.domain>/admin_console will indeed get to the system console - the issue seems to be that the menu item for system console is missing

**Comment by alecisec** [comment]
Further to this - clicking the 'System Scheme' option in the system console causes the web interface to hang and display 'Loading...'

debug logs give no indication as to the fault


mattermost    | {"level":"debug","ts":1536043411.3707733,"caller":"web/handlers.go:50","msg":"GET - /favicon.ico"}
mattermost    | {"level":"debug","ts":1536043411.6219316,"caller":"web/handlers.go:50","msg":"GET - /api/v4/config/client                                                                                                                    "}
mattermost    | {"level":"debug","ts":1536043411.6901603,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/pref                                                                                                                    erences"}
mattermost    | {"level":"debug","ts":1536043411.6926348,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/team                                                                                                                    s"}
mattermost    | {"level":"debug","ts":1536043411.6935337,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/team                                                                                                                    s/unread"}
mattermost    | {"level":"debug","ts":1536043411.6945596,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/team                                                                                                                    s/members"}
mattermost    | {"level":"debug","ts":1536043411.6950376,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me"}
mattermost    | {"level":"debug","ts":1536043411.6990337,"caller":"web/handlers.go:50","msg":"GET - /api/v4/license/clien                                                                                                                    t"}
mattermost    | {"level":"debug","ts":1536043412.0762,"caller":"web/handlers.go:50","msg":"GET - /api/v4/config/environme                                                                                                                    nt"}
mattermost    | {"level":"debug","ts":1536043412.0799837,"caller":"web/handlers.go:50","msg":"GET - /api/v4/config"}
mattermost    | {"level":"debug","ts":1536043412.2491825,"caller":"web/handlers.go:50","msg":"GET - /api/v4/analytics/old                                                                                                                    "}
mattermost    | {"level":"debug","ts":1536043412.2804224,"caller":"web/handlers.go:50","msg":"GET - /api/v4/analytics/old                                                                                                                    "}
mattermost    | {"level":"debug","ts":1536043412.3025503,"caller":"web/handlers.go:50","msg":"GET - /api/v4/analytics/old                                                                                                                    "}
mattermost    | {"level":"debug","ts":1536043412.3393335,"caller":"web/handlers.go:50","msg":"GET - /favicon.ico"}
mattermost    | {"level":"debug","ts":1536043412.3402023,"caller":"web/handlers.go:50","msg":"GET - /api/v4/analytics/old                                                                                                                    "}
mattermost    | {"level":"debug","ts":1536043415.0682619,"caller":"web/handlers.go:50","msg":"GET - /favicon.ico"}
mattermost    | {"level":"debug","ts":1536043440.069177,"caller":"web/handlers.go:50","msg":"POST - /api/v4/users/status/ids"}

**Comment by amyblais** [comment]
Hi @alecisec, thank you for reporting this.

Do you see the option "Manage Members" or "View Members" in the Main Menu?

Also, are you using Team or Enterprise edition?

**Comment by alecisec** [comment]
Both regular users and Admins see the following options:

Account Settings
---
View Members
Leave Team
---
Help
Keyboard Shortcuts
Report a Problem
Download Apps
About Mattermost
---
Logout

**Comment by amyblais** [comment]
Thank you @alecisec, can you try with `role="system_admin"` according to this documentation: https://docs.mattermost.com/install/troubleshooting.html#lost-system-administrator-account?

**Comment by alecisec** [comment]
The correct command to resolve this is 
mattermost roles system_admin <username>

**Comment by amyblais** [comment]
Hi @alecisec, that's correct, sorry about the confusion.

The command you posted is documented here: https://docs.mattermost.com/administration/command-line-tools.html#mattermost-roles.

Glad to hear the issue was resolved and I apologize again for the confusion,
