### ISSUE TITLE
Search problem

### ISSUE THREAD

**Issue by LeDOC666** [mattermost/mattermost-server#9353]
#### Summary
Hi, I have a problem with Search function.
When I search a word between wildcard in uppercase, it find nothing.

#### Steps to reproduce
Exemple:

```
message BOT: 
PROBLEM srvnagios at 10.4.1.74/MYSQL_threads-connected is WARNING
```
If I search "(wildcard)MYSQL(wildcard)", find nothing, if I search "(wildcard)threads(wildcard)", I find result
If I search "WARNING", I find a result too

I tryed to copy/paste the message on same channel
```
user: 
PROBLEM srvnagios at 10.4.1.74/MYSQL_threads-connected is WARNING
```
If I search "(wildcard)MYSQL(wildcard)", find nothing, if I search "(wildcard)threads(wildcard)", I can't find my message !
If I search "WARNING", I find a result.

#### Version release
My release is a latest docker-compose version of mattermost

**Comment by LeDOC666** [comment]
After more search, the only way I found to find the message is:
"PROBLEM***/MYSQL***"
Wildcard on start seems be problematic, and don't specify the / between the IP Address, and Service Name.

**Comment by amyblais** [comment]
Hi @LeDOC666, thank you for reaching out.

What Mattermost server version and OS are you using?

**Comment by amyblais** [comment]
Hi @LeDOC666,

I've begun testing this, but I'm getting some different results (e.g. for the user's post, I'm able to find results with "MYSQL" and "warning" (both lowercase and uppercase) but not with "threads").

I'll work on finalizing the testing, and I'm also working on going through our Jira tickets as there could already be a ticket open related to this.

**Comment by LeDOC666** [comment]
Hi,
MatterMost Version is: 5.2.1, running on Docker (hosted on CentOS7). Container run on Alpine 3.6

I can't write on github the keywords used cause of wildcart *
I edited first post to show (wildcard) = *
I tested on another MM used from another service of my company (running on Docker too, but with Mysql), result are the same as mine.

**Comment by amyblais** [comment]
Update: I'm getting different search results again (e.g. I'm able to find results with "mysql" but not with "threads" or "warning") - I'm continuing to investigate this.

In the meanwhile, can you help do some testing on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) (it's on v5.3 RC-1 version) and observe if you see anything different.

**Comment by amyblais** [comment]
I'll summarize the issue/findings here and I'll need to confirm with someone if this is a bug/expected as there seems to be some kind of pattern:

For this post `PROBLEM srvnagios at 10.4.1.74/MYSQL_threads-connected is WARNING`, search results are as follows:

**No results:**
“mysql”
"MYSQL"
"THREADS"
"threads"
"(wildcard)threads(wildcard)"
“(wildcard)WARNING(wildcard)”
“(wildcard)warning(wildcard)”
“(wildcard)connected(wildcard)”

**Can find results:**
"(wildcard)MYSQL(wildcard)"
"(wildcard)mysql(wildcard)"
“warning”
"WARNING"
"connected"
"CONNECTED"
"problem"
"PROBLEM"
"(wildcard)problem(wildcard)"
"(wildcard)PROBLEM(wildcard)"

**Comment by amyblais** [comment]
Hi @LeDOC666, I opened a ticket here for our devs to investigate: https://mattermost.atlassian.net/browse/MM-12059.

**Comment by amyblais** [comment]
Hi @LeDOC666,

Letting you know that the Jira ticket I opened was closed. 

The devs added a comment in it that we don't support preceding wildcards and that we treat "_" and "-" as part of words, so the "no results" cases that I listed are actually behaving as expected.

You can open a feature request ticket here for any changes that we can make for the search function: https://mattermost.uservoice.com/forums/306457-general.

**Comment by ntwrkguru** [comment]
I don't see how this is working as expected. I have noticed this as well and, as a user, I would expect that searching mysql would return the post with the message as indicated in the OP. As a user, I don't know what I don't know, including if the search term is uppercase, lowercase, mixed case, part of another word/term or by itself, and expect the search function to handle this for me. Arguably, the case sensitivity may be considered a feature request, but returning all results containing the term should absolutely work as OP believes it should. As it is, search is mostly useless for my needs.

Can we re-open this and take another look, please?

**Comment by globalqss** [comment]
In case somebody wants to support and vote this feature request I found one here:
https://mattermost.uservoice.com/forums/306457-general/suggestions/36538417-make-search-work-as-it-should
