### ISSUE TITLE
[Help Wanted] [MM-11895] Slash commands with GET crush query parameters on configured endpoint URL

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9356]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11895)

Original report: https://github.com/mattermost/mattermost-server/issues/9279

*Problem:*
Following the fix for MM-10201, Mattermost's meta data is now URL encoded into the query string instead. While doing so, Mattermost also removes/crushes any query parameters that may exist on the configured slash command URL itself.

*Example:* 
A user has a slash command that uses a GET call to the URL https://host.doesntmatter.com/mattermost?cmd=ourCommand. It is vital that the request includes the query parameter cmd=outCommand.

Instead of calling GET https://host.doesntmatter.com/mattermost?cmd=ourCommand, Mattermost actually calls something that looks like this: GET https://host.doesntmatter.com/mattermost?channel_id=lkjhsdfljhlsdhjdfjljhsdf&channel_name=me&command=%2Fourslashcommand&response_url=https%3A%2F%2Fmattermost.doesntmatter.com%2Fhooks%2Fcommands%2Fkjhsdfkjhkjhskdjhf&team_domain=doesntmatter&team_id=jkhsddfkhjskjdhfkjsdf&text=&token=ljhsdfkjhsfdjhskdfhlkjs&user_id=lkjhsdfkjhskldjhfkjhsdf&user_name=itmattersnot.

So rather than adding its own data to the configured slash command endpoint URL as query parameters and preserving our own configured query parameter, Mattermost simply omits ourCommand from the request, which in our case breaks the implementation, because it depends on the ourCommand parameter being present.

*Suggested fix:* 
Rather than merely setting its own data as request query string, merge in any potential parameters from the configured endpoint URL. In the above example, we would expect to see this request:

GET https://host.doesntmatter.com/mattermost?cmd=ourCommand&channel_id=lkjhsdfljhlsdhjdfjljhsdf&channel_name=me&command=%2Fourslashcommand&response_url=https%3A%2F%2Fmattermost.doesntmatter.com%2Fhooks%2Fcommands%2Fkjhsdfkjhkjhskdjhf&team_domain=doesntmatter&team_id=jkhsddfkhjskjdhfkjsdf&text=&token=ljhsdfkjhsfdjhskdfhlkjs&user_id=lkjhsdfkjhskldjhfkjhsdf&user_name=itmattersnot

It is fine if a query string parameter is duplicated when the query strings are combined. The interpretation of that is up to the slash command server receiving the request.

**Comment by kongr45gpen** [comment]
I could work on this!

**Comment by jasonblais** [comment]
That would be great, thank you @kongr45gpen! If you have any questions, let us know :)
