### ISSUE TITLE
[Help Wanted] [MM-11880] Have Team Settings modal use the patch endpoint instead of the update endpoint

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9358]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11880)

(React.js, introductory)

Currently, the Team Settings modal uses the the update team endpoint (PUT /api/v4/teams) instead of patch endpoint (PUT /api/v4/teams/patch). This can cause a minor race condition where two people changing different settings at the same time will overwrite one another, meaning one person's changes get lost. If we use the patch endpoint, only the field that each user is actually changing will be updated, so no changes will be lost.

**Comment by mojicaj** [comment]
I'd like to work on this.

**Comment by jasonblais** [comment]
Thank you @mojicaj!

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/1853 and https://github.com/mattermost/mattermost-redux/pull/651
