### ISSUE TITLE
[Help Wanted] [MM-11874] [RN] Add "Don't ask me again" behavior and interface for Out of Office in RN

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9363]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11874)

Currently, we haven't feature parity in RN to get out of Out Of Office state.  The RN application ask you if you try to get Out of Office, but I'm not sure if it does it automatically when you enter and you are Out of Office (that is the behavior in Desktop/Webapp) and I'm 4/5 it doesn't ask for the "Don't ask me again" preference, and don't use it either.

**Comment by lfbrock** [comment]
Accidentally opened, this needs design first
