### ISSUE TITLE
[Help Wanted] [MM-11936] Should we display "Shown for 5 seconds" for desktop notifications in Account Settings > Notifications?

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9364]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11936)

We show "Shown for 5 seconds" for desktop notifications in Account Settings > Notifications.

Is this expected given desktop notification duration cannot be edited in Mattermost?

As a note, desktop notifications for Windows app can be configured via the Windows system control panel, and hence may not be 5 seconds.

 !image-2018-08-31-10-39-11-121.png|thumbnail!

**Comment by lfbrock** [comment]
Accidentally opened, this needs design first
