### ISSUE TITLE
[Help Wanted] [MM-11716] Support selecting different skin tones in autocomplete and emoji picker 

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9365]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11716)

Need to update with design, and make help wanted. 

Requirements: 
1. Emoji picker: 
- Add a way to select a default skin tone

2. Emoji autocomplete: 
- Add the ability to select multiple skin tones. We may want to do this in the format `:emoji::skin-tone-2:` so imports from Slack render the emojis. 
- Autocomplete should show the default skin tone version of the emojis
- We should also add :skin-tone-2:, :skin-tone-3:, etc to the autocomplete. When selected by themselves, they should show up as a coloured square. When selected after a person emoji, the skin tone should be applied to the person instead of showing up as a separate square.

**Comment by lfbrock** [comment]
Accidentally opened, this needs design first

**Comment by wikiblue** [comment]
Is this still being worked on?
