### ISSUE TITLE
[Help Wanted] [MM-11784] Design: Collapsible threads

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9366]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11784)

Based on the spec JB started: https://docs.google.com/document/d/1Pcj2J6R205sUzJ-Z2n-5Luu4XmYFMifXRpeG88TMoAc/edit#heading=h.yadtbs8spm4x

Outdated spec: https://mattermost.atlassian.net/browse/MM-8254 

Related ticket with some info: https://mattermost.atlassian.net/browse/MM-8457

**Comment by lfbrock** [comment]
Accidentally opened, this needs design first
