### ISSUE TITLE
[Help Wanted] [MM-9463] Consecutive message repeats profile info in RHS

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9367]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9463)

h3. Steps
# Open a message to reply
# Post `One`, then `Two` and `Three` as separate, consecutive messages by the same user

h3. Expected
# Just like in the center, the profile info is not repeated:
!image-2018-02-09-16-57-37-292.png|thumbnail! 

h3. Observed
# Profile info is repeated in RHS, though not in center:
!image-2018-02-09-16-57-56-069.png|thumbnail!

**Comment by lfbrock** [comment]
Accidentally opened, this needs design first
