### ISSUE TITLE
[Help Wanted] [MM-8497] Ability to snooze live notifications for a specified period of time

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9368]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8497)

Use case: I am in meetings for two hours, and want to disable all notifications during that time to avoid distractions, without losing important messages when I'm back. Need the ability to snooze notifications for those 2 hours.

Use case: I don't want to get notifications when im sleeping or on weekends (need ability to set a schedule for no notifications)

Functionality needs:
Ability to turn off push and desktop notifications for specified time periods or on a recurring schedule. We need to maintain the ability to set do not disturb indefinitely (until the user turns it off).

Potential design option (note that the screens are outdated):
 !screenshot-1.png|thumbnail! 

Questions:
1. Should this be new functionality on the DND mode or a separate UI element?
2. What time options should we offer, for example: 1 hour, 2 hours, 4 hours, 8 hours, 12 hours, 24 hours? If we offer options at all.
2. Where should the schedule be set? Maybe Account Settings > Notifications

Investigative design: 
 !screenshot-2.png|thumbnail!

**Comment by lfbrock** [comment]
Accidentally opened, this needs design first
