### ISSUE TITLE
[Help Wanted] [MM-8404] Channel notification setting for disabling channel mentions

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9369]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8404)

Add a channel notification setting to disable (or enable) @-channel @-here @-all notifications in specific channels.

In the Channel Menu > Notification Preferences add the following setting below "Mark Channel Unread":

**Trigger mentions for @all, @channel, @here**

"On"
"Off"

Help Text: "Set whether @all, @channel, and @here trigger mentions in this channel."

________

Note: This setting should respect the global default in Account Settings > Notifications > Words that trigger mentions > "Channel-wide mentions @channel, @all, @here" unless explicitly changed by this setting.

**Comment by lfbrock** [comment]
Accidentally opened, this needs design first

**Comment by ternes3** [comment]
How can I change these settings for all members of a team. 
(Change the global standard?)

**Comment by jasonblais** [comment]
Hi @ternes3! You can use our bulk loading tool to update settings for existing members of a team.

https://docs.mattermost.com/deployment/bulk-loading.html

You can [create a user object](https://docs.mattermost.com/deployment/bulk-loading.html#user-object) containing the notification preferences and [run it via the command line](https://docs.mattermost.com/deployment/bulk-loading.html#running-the-bulk-loading-command).

**Comment by ternes3** [comment]
okay got it. I have to change in the database for every user the preferences on this or better i can use the bulk loading tool. 

But I cant change the default for this? So every new user would be directly fine.

**Comment by jasonblais** [comment]
Not currently, but we have an open feature proposal for it here: https://mattermost.uservoice.com/forums/306457-general/suggestions/33015193-allow-administrators-to-set-default-notification-s

Would you be open to contributing to the proposal? You get **10** votes in the feature idea forum, and each one influences the future of the project.
