### ISSUE TITLE
[Help Wanted] [MM-11870] Design: invite user to channel from profile pop-over

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9370]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11870)

Option to add user to a channel by clicking on their profile pop-over. See attached flow from slack:

 !image-2018-08-27-16-51-00-709.png|thumbnail! 

 !image-2018-08-27-16-51-20-550.png|thumbnail!

**Comment by lfbrock** [comment]
Accidentally opened, this needs design first
