### ISSUE TITLE
Help assessing risk by auto-updating mattermost-server

### ISSUE THREAD

**Issue by gelim** [mattermost/mattermost-server#9374]
Hello,

could you give some insight on the risk breaking things by auto-updating mattermost-server team edition **incrementally**. Do you have a specific policy for that purpose allowing to blindly auto-update, like "fine between minor version, blocker between major version).

Thanks for the help,

-- 
Mathieu

**Comment by amyblais** [comment]
Hi @gelim, thank you for your question!

We are in the process of implementing an auto-updater in the next desktop app release: https://github.com/mattermost/desktop/pull/582 (associated Github Issue here: https://github.com/mattermost/desktop/issues/15) - I believe we will have more details when the feature is implemented.

**Comment by amyblais** [comment]
Closing this Issue as there haven't been updates for a while.

You can follow the progress of the auto-updater feature on the above links and we can revisit this when the feature is ready to be implemented.
