### ISSUE TITLE
[Help Wanted] [MM-11863] Add key value store list method to the plugin API

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9377]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11863)

The plugin API gives access to a key-value store, through methods beginning with `KV*`. Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/.

Add a method to the plugin API called `KVList()` that returns a list of all the keys stored by the plugin.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go#L188
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go#L318
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_key_value_store.go
* https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/plugin_store.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by jasonblais** [comment]
That would be great! It is indeed unassigned, thank you for your interest. If you have any questions, let us know in the [Developer Toolkit community channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) :)

**Comment by hanzei** [comment]
Fixes with #9467
