### ISSUE TITLE
Azure Mattermost Instance - No way to authenticate users?

### ISSUE THREAD

**Issue by garethwarry** [mattermost/mattermost-server#9394]
#### Summary
Not sure how to authenticate users using the Azure deployment of Mattermost Team Server. All guides found in the Administration Guide doesn't apply to what I'm seeing in the System Console? For example, I can't authenticate users in any way. I tried setting up Azure Active Directory or Office 365 OAuth authentication, but there's not even a section called "OAuth 2.0" in the system console. Not sure how to proceed. It's currently just a brick wasting money in Azure.

#### Steps to reproduce
1. Deploy using Azure marketplace instance of Mattermost.
2. Attempt to do anything related to authentication, Ex: [Office 365 SSO](https://docs.mattermost.com/deployment/sso-office.html).

#### Expected behavior
OAuth 2.0 section exists

#### Observed behavior (that appears unintentional) 
OAuth section is missing

#### Possible fixes
No workarounds.

**Comment by amyblais** [comment]
Hi @garethwarry, thank you for reaching out 👍 

Are you using Mattermost Team Edition or Enterprise Edition?

**Comment by garethwarry** [comment]
Hi @amyblais! I'm using Mattermost Team Edition.

**Comment by amyblais** [comment]
Hi @garethwarry,

Yes, it's only available in Enterprise Edition (specifically E20). I believe in Team Edition you can use email-based auth: https://docs.bitnami.com/azure/apps/mattermost/#how-to-configure-outbound-email-settings.

**Comment by garethwarry** [comment]
I see. Is it possible to only allow emails from a specific domain? For example, test@example.com (example.com being the allowed domain for registering emails)?

**Comment by amyblais** [comment]
@garethwarry There is a config setting called [Restrict account creation to specified email domains](https://docs.mattermost.com/administration/config-settings.html#restrict-account-creation-to-specified-email-domains) - is this what you were looking for?

**Comment by garethwarry** [comment]
It is! Thanks so much! 🎉
