### ISSUE TITLE
Channel links should show as links in notification emails

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9399]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11102)

Original report: https://github.com/mattermost/mattermost-server/issues/9024

*Steps to repro:*
1. Turn on email notifications
2. Write a message to the account containing channel links (e.g. "~channel1")

*Expected behavior*
In the HTML-Email, channel should be linked to the channel URL, same as how they appear in Mattermost

*Observed:*
Channels in emails are not links, they appear as raw text in the form ~channel_name

**Comment by claytonlemons** [comment]
I'd be happy to take a stab at this!

**Comment by esethna** [comment]
Hey @claytonlemons , let us know if you have any questions, happy to help!

**Comment by waseem18** [comment]
@claytonlemons Are you still working on this? If not I would like to take this up.

**Comment by hanzei** [comment]
@waseem18 As there hasn't been any update on this one from @claytonlemons: Go ahead and work on this, please :+1:

**Comment by hanzei** [comment]
@waseem18 Did you already start an this issue? Do you have any questions?

**Comment by waseem18** [comment]
Not yet @HanzeiOn Jan 7, 2019 17:20, Hanzei <notifications@github.com> wrote:@waseem18 Did you already start an this issue? Do you have any questions?

**Comment by hanzei** [comment]
Thanks for the reply. Looking forward to your PR!

**Comment by sandlis** [comment]
@waseem18 If in case you are not working on this, can I pick this up?

**Comment by sandlis** [comment]
Okay, no problem.
Thanks for the response!

Regards,
Sandeep Sukhani

**Comment by waseem18** [comment]
Update : Started working on this.

**Comment by waseem18** [comment]
I plan to do this in this way : 

1. Use regex to find channel mentions in the message and check if the channel exists using `GetChannelByNameForTeamName`.
2. If the channel exists, wrap the channel mention in an anchor tag so that the HTML code can render this valid channel mention as a hyper link.

@hanzei Let me know if there's a better way to solve this.

PR on the way.

**Comment by hanzei** [comment]
This is a fine approach. Looking forward to your PR :tada:

**Comment by noxer** [comment]
I'd like to take this one...

**Comment by mjthomp95** [comment]
I see waseem18 finished most of this. I can finish it up with the suggestion from esethna to only link Public Channels.

**Comment by jasonblais** [comment]
Great, thanks @mjthomp95!

**Comment by saturninoabril** [comment]
PR recently merged.  Thanks @mjthomp95 for your contribution!
