### ISSUE TITLE
Closing new channel menu reopens archived channel

### ISSUE THREAD

**Issue by stevebunting** [mattermost/mattermost-server#9403]
#### Summary
After archiving a channel, closing the new channel menu will bring your archived channel back to the lhs bucket and move focus to that channel

#### Steps to reproduce
Mattermost OSX version 5.2.0
1. Make new private channel
2. Post in that channel at least once (I posted a # searchable link if it makes a difference)
3. Archive the channel and close it
4. Press the plus for public or private channels (doesn't happen for DM)
5. Press the x in the top right corner

You should get brought back to the archived room

#### Expected behavior
Popup closes and you are not brought back to the archived room

#### Observed behavior (that appears unintentional) 
Popup closes are you are brought back to the archived room

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Hi @stevebunting, thank you for reporting this.

I'm not able to repro this on v5.3 RC-4, so this has probably been fixed on v5.3. I also found a related resolved ticket that seems to describe the issue you're seeing: https://mattermost.atlassian.net/browse/MM-11805.

Do you have ["View archived channels"](https://docs.mattermost.com/administration/config-settings.html#allow-users-to-view-archived-channels-experimental) setting enabled or disabled?

**Comment by stevebunting** [comment]
Thanks for the quick response! I saw that ticket, but I wasn't sure if the root problem was the same so I just wanted to report to be safe. And we have "ViewArchivedChannels": true
If the issue is resolved in 5.3 I'll go ahead and close. Thanks for your help!
