### ISSUE TITLE
Public links for file remains when message is deleted

### ISSUE THREAD

**Issue by jsha** [mattermost/mattermost-server#9404]
#### Summary

If you accidentally share a Public Link to a file with a third party, then need to remove access to that file, it's currently impossible (AFAICT).

#### Steps to reproduce
Version 5.1.0

1. Post a message with an attached file.
2. Copy a Public Link to that file.
3. Delete the message.
4. Use the Public Link to download the file.

#### Expected behavior
One the message is deleted, it's no longer possible to download the file by any means (public link or not).

#### Observed behavior (that appears unintentional) 
After the message is deleted, it's still possible to download the file.

Note: Similarly, people who are authenticated to Mattermost shouldn't be able to access a file after it / it's message is deleted. But continued access to the public file seems like the biggest risk. Note that this risk is mentioned specifically in https://www.w3.org/TR/capability-urls/#handling-compromises:

> 4.3 Handling Compromises
> If a capability URL does leak out to unwanted recipients, the person who originally granted access through that URL needs to be able to revoke it.

**Comment by amyblais** [comment]
Hi @jsha, thank you for reaching out.

For step 1, do you mean posting a message that has a file attachment, or posting a message that has a link to a file (e.g. dropbox image)?

**Comment by jsha** [comment]
The former. Thanks for getting back to me so fast! Mattermost is great
software, and I really appreciate your work on it.

**Comment by amyblais** [comment]
Thanks @jsha,

I'm not able to repro this on v5.3 RC version - can you help do some testing on our [Community server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and report back what you see in case I missed anything?

**Comment by jsha** [comment]
I just tested against the Community server and was able to reproduce there as well. Here's a link to a file that I attached to a message in a DM chat with myself, where I subsequently deleted the message. The file is still fetchable: https://pre-release.mattermost.com/files/r1zem456o3do3gqkzdg1sbfz5c/public?h=JeeypNwoZxuVBcKfGt46-pVMRrTi5oT7FOMFySyhUsM.

**Comment by amyblais** [comment]
Sorry about that, you're right - I created a ticket for this here: https://mattermost.atlassian.net/browse/MM-12243.

**Comment by amyblais** [comment]
Hi @jsha, are you seeing the same issue when you have this setting disabled: https://docs.mattermost.com/administration/config-settings.html#enable-public-file-links.

**Comment by jsha** [comment]
No, when the setting is disabled, all existing public URLs stop working. My guess is that if you later turn back on the setting, the old public URLs start working again.

There's also a related issue: If people delete an attachment (by deleting the message), they might expect that the file is totally gone from the Mattermost server. This is useful if you accidentally upload sensitive data like passwords or social security numbers. But I think that currently there's no way to delete uploaded files.

**Comment by amyblais** [comment]
Hi @jsha,

I believe this is expected: 
> My guess is that if you later turn back on the setting, the old public URLs start working again.

As for permanently deleting files, all Mattermost "delete" features are a "soft" delete, meaning that it doesn't completely delete anything. Access to files from Mattermost is removed but it does not physically delete the file in the database. If you’d like to file this as a [feature request](https://mattermost.uservoice.com/forums/306457-general) or upvote [a similar idea](https://mattermost.uservoice.com/forums/306457-general/suggestions/15357861-add-actual-permanent-deletion-on-database-and-fi) posted by another user, that would be helpful so we can prioritize based on community feedback.

**Comment by amyblais** [comment]
Hi @jsha , we haven't received an update so I'll close this Issue for now,
