### ISSUE TITLE
[Help Wanted] [MM-12158] Add plugin API to return the current server version

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9408]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12158)

Add a plugin API method `getServerVersion()` that returns the current Mattermost server version.

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/.

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by Hanzei** [comment]
I would like to work on this.

**Comment by cpanato** [comment]
I dont think we have now, but you can take this example: https://github.com/mattermost/mattermost-server/pull/9101

@jwilander there are any docs to add an API for plugins?

**Comment by jwilander** [comment]
There's some documentation at the bottom here https://developers.mattermost.com/contribute/server/plugins/

**Comment by Hanzei** [comment]
Oh, my bad, sorry for the unnecessary question
