### ISSUE TITLE
Server error when posting messages with accents

### ISSUE THREAD

**Issue by Spone** [mattermost/mattermost-server#9409]
Hi, thanks for the awesome software :)

#### Summary
When posting messages with accented characters, there is a server error and the message is not saved.

#### Steps to reproduce
Mattermost 5.1.1, installed with Gitlab Omnibus.
Database schema version: 5.1.0
Database: postgres
OS: Debian jessie

#### Expected behavior
- I post this message in a channel: `Liberté, Égalité, Fraternité`
- The message should be posted.
- I post this message in the same channel: `Liberte, Egalite, Fraternite` (without accents)
- The message should be posted.

#### Observed behavior (that appears unintentional) 
- I post this message in a channel: `Liberté, Égalité, Fraternité`
- The message is not posted. I see the "Retry" link appear next to the message. When I click it, nothing happens.
- I post this message in the same channel: `Liberte, Egalite, Fraternite`
- The message is posted.

In the browser developer console, I can see the API response:

```
{
  "id": "store.sql_post.save.app_error",
  "message": "Impossible d'enregistrer le message",
  "detailed_error": "",
  "request_id": "5oejz4g8ytnd7djtqp59w71gro",
  "status_code": 500
}
```

In the server logs:

```
2018-09-13_17:36:49.26463 {"level":"error","ts":1536860209.264508,"caller":"web/handlers.go:142","msg":"We couldn't save the Post","path":"/api/v4/posts","request_id":"ykkfdmoo5pb9dmuyxfw61tz5tr","ip_addr":"151.127.31.49","user_id":"hyq5o9c5m7n15dmte1ecfn6huh","method":"POST","err_where":"SqlPostStore.Save","http_code":500,"err_details":"id=yjisqoxujirqdmgrum8dqiuhiw, pq: invalid multibyte character for locale"}
```

#### Possible fixes

Here is the line of code where the postgresql error comes from: https://github.com/postgres/postgres/blob/322548a8abe225f2cfd6a48e07b99e2711d28ef7/src/backend/utils/adt/pg_locale.c#L1758

**Comment by amyblais** [comment]
Hi @Spone, thank you for reporting this.

I tested this on Mattermost Gitlab, postgres test server and wasn't able to repro. However, the server version there was v5.0 so that might make a difference, so I'll ask our team if the test server can be upgraded to the latest version.

**Comment by Spone** [comment]
I'm still investigating this and I have similar errors when editing Gitlab issues with accented characters, so I think it's a problem in my database and not in Mattermost software.

**Comment by Spone** [comment]
I managed to fix the issue on Gitlab side by creating a backup of the DB and then restoring it.
But it doesn't work for Mattermost. Here is what I tried:

```
su - mattermost -c "/opt/gitlab/embedded/bin/pg_dump -U gitlab_mattermost -h /var/opt/gitlab/postgresql -p 5432 mattermost_production" > /tmp/mattermost_production_backup.sql

sudo gitlab-psql
psql (9.6.8)
Type "help" for help.

gitlabhq_production=# DROP DATABASE mattermost_production;
gitlabhq_production=# CREATE DATABASE mattermost_production;
WARNING:  could not determine encoding for locale "C.UTF-8": codeset is "ANSI_X3.4-1968"
DETAIL:  Please report this to <pgsql-bugs@postgresql.org>.
WARNING:  could not determine encoding for locale "C.UTF-8": codeset is "ANSI_X3.4-1968"
DETAIL:  Please report this to <pgsql-bugs@postgresql.org>.
CREATE DATABASE
gitlabhq_production=# \q

su - mattermost -c "/opt/gitlab/embedded/bin/psql -U gitlab_mattermost -h /var/opt/gitlab/postgresql -p 5432 mattermost_production" < /tmp/mattermost_production_backup.sql
```

**Comment by Spone** [comment]
Here is what I had to do to fix the issue with Mattermost :

After dropping the database, recreate it with the right encoding:

`CREATE DATABASE mattermost_production LC_COLLATE "en_US.UTF-8" LC_CTYPE "en_US.UTF-8" ENCODING "UTF8" TEMPLATE template0;`

Then importing the backup works correctly, and I can now post messages with accents :)
