### ISSUE TITLE
In the web-app, logging out does not clear the currently logged in user from the store.

### ISSUE THREAD

**Issue by chetanyakan** [mattermost/mattermost-server#9434]
#### Summary
When we log out, the currently logged in user from `UserStore.getCurrentUser()` is not cleared in the web app.

#### Steps to reproduce
1. Make sure you are logged in to Mattermost. You may also create a new account without joining any teams, so that you are on the `/select_team` route. 
2. Open the chrome developer tools. Make sure you have enabled 'Preserve Log' in the console and network tabs.
3. Log out and look closely at the URL of the page. It goes from `/select_team` to `/login` to `select_team` again and then goes to `/` and after loading for a while, goes to the `/login` page.
4. If you see the console and network tabs, you may notice that there is at least one API call that has returned 401.
***
What happens is that logout redirects to the login component. 
In the login component, in `componentDidMount`, we check for `UserStore.getCurrentUser()` to redirect the user to default team.
After making an API call, which returns 401, `forceLogoutIfNecessary` is invoked through mattermost-redux which clears the currently logged in user from the store and redirects again to the `/login` page as well.

#### Expected behavior
Logout should clear the currently logged in user from the store.

#### Observed behavior (that appears unintentional) 
Logout does not clear the currently logged in user from the store.

#### Possible fixes
https://github.com/mattermost/mattermost-webapp/blob/1d9df4ac3f9982bca29eef29225ed9f73b81fc01/actions/global_actions.jsx#L450

Maybe we can dispatch an action to clear currently logged in user from the store in the method above.

**Comment by amyblais** [comment]
Hi @chetanyakan, thank you for reaching out 👍 

What browser / device and Mattermost server version are you seeing this on?

**Comment by chetanyakan** [comment]
Chrome on Linux with the latest Web-app + API Master setup for development.

**Comment by amyblais** [comment]
Thank you, I created a ticket here for investigation: https://mattermost.atlassian.net/browse/MM-12257.

**Comment by amyblais** [comment]
The Jira ticket has been resolved and tested internally, and the fix will be available in v5.4 release,
