### ISSUE TITLE
Links will be accessed even if link preview is set to false

### ISSUE THREAD

**Issue by Dnic94** [mattermost/mattermost-server#9437]
#### Summary
Links posted in any channel will be accessed everytime a user loads the message even if the link preview is set to false. We use Mattermost 5.3.0.

#### Steps to reproduce
Post a link in a channel and read it with an other user. 
We noticed that the mattermost server looked up the domain in our DNS logs.

#### Expected behavior
Mattermost shouldn't do anything as long as the link preview is set to false.

#### Observed behavior (that appears unintentional) 
Mattermost tried to look up the domain from the link.

**Comment by amyblais** [comment]
Hi @Dnic94, thank you for reaching out.

Do you mean that the "Website Link Previews" in the Account Settings > Display is turned off? If yes, this just means that you are not able to preview the website content, but you will still be able to access the link.

If you want to disable sharing public links, you'll need to adjust this setting: https://docs.mattermost.com/administration/config-settings.html#public-links.

Let me know if I misunderstood the issue you are seeing?

**Comment by Dnic94** [comment]
Hi @amyblais ,
I meant the Setting in the System Console > Posts > Enable Link Preview is set to false.

But it seems that the Mattermost server is still trying to resolve the link everytime a user reads a message with a link. I dont know if there is a correlation between the Link Preview Feature and this behaviour it was just an assumption.

An example for the observed behaviour:

User A post in a Channel: "Hey look at this great site: hxxp://greatsite.com/link.html"
The Message is shown normaly in the channel without preview to the site, but everytime a user loads this message with his client the mattermost server asks our DNS server for greatsite.com.

I think the Mattermost server shouldn't do this as long as the Link Preview is disabled globally.

**Comment by amyblais** [comment]
Thank you for the clarification and additional details - can you help share sample log error message?

**Comment by Dnic94** [comment]
I think there is no Mattermost log which could help you, because this is not really an error for the application but a misbehaviour of the application. 

And I think a log from our DNS server which shows that the mattermost server is asking for a domain doesnt bring us forward as well.

Were you able to reproduce our Problem?

**Comment by rid3re** [comment]
Hi @amyblais ,
I have the same issue.

server OS: Debian 9.4
MM server: 5.3.1
browsers: Safari, Chrome, Firefox
Mattermost Desktop App: MasOS/Linux 4.1.2
80/443 ports closed from mm server to world

In browser web inspector: "GET /api/v4/redirect_location" responses get stuck

**Comment by Dnic94** [comment]
@rid3re 

> In browser web inspector: "GET /api/v4/redirect_location" responses get stuck

I can confirm this, same here.

**Comment by amyblais** [comment]
Hi all, there appears to be a bug, possibly caused by this PR: https://github.com/mattermost/mattermost-server/pull/9284. I opened a ticket here for investigation: https://mattermost.atlassian.net/browse/MM-12264.

**Comment by amyblais** [comment]
This issue has been resolved and tested internally. The fix will be available in v5.4 release,
