### ISSUE TITLE
User should be able to archive a thread

### ISSUE THREAD

**Issue by egel** [mattermost/mattermost-server#9446]
#### Summary (Feature Request)
As a Mattermost user (Manager/Admin of channel)

I would like to close some discussion which is not needed anymore in the main channel (have been resolved)

so that I can reduce the content noise in the channel content in the channel by displaying relevant content.

#### Observed behavior (that appears unintentional) 
In any channel where there are a lot of people, there is always much noise. I would like to archive those threads which are not needed anymore and display the relevant content in the main view. 

Usually, it might be discussions which end with some result/agreement, but the result doesn't need to be displayed/stored anymore in the main view.

#### Possible fixes
- add a button to archive the thread.
- add a view to display archived discussions
- add a possibility to add a title of the thread (to help organize threads)

**Comment by amyblais** [comment]
Thank you, appreciate your feedback @egel!  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Hi @egel, thank you for opening a Feature Request ticket! I'll close this Issue for now as it can be followed via Uservoice,
