### ISSUE TITLE
Markup doesn't take into account image preview settings

### ISSUE THREAD

**Issue by Ppjet6** [mattermost/mattermost-server#9451]
Version: 5.2
Soon updating to 5.3, but this particular issue is not mentioned in the changelog.

#### Summary
When posting images via markup, `![](someimagelink)`, user image preview settings are not taken into account.

#### Steps to reproduce
- Account Settings > Display > Default appearance of image previews > Collapse
- Send (or have somebody send) a message containing `![](someimagelink)` (replacing that with an actual url, of course).

#### Expected behavior
The image is not displayed, and a link to it is displayed instead, as if the person had pasted a link without using markup in the first place.

#### Observed behavior (that appears unintentional)
The image is fully displayed.

**Comment by Ppjet6** [comment]
I don't think this should be a feature request, this is a usability/accessibility issue, and has the same rationale as the `collapse` feature.

I would be interested in hearing what's particularly hard about detecting images in embedded markup.

**Comment by Ppjet6** [comment]
On 2018/09/24, amyblais wrote:
> Hi @Ppjet6, letting you know that I've reached out to our product managers for more information on this.

Thanks!

**Comment by amyblais** [comment]
@Ppjet6 Our product managers said that it requires some design work as currently there is no UI element that can be utilized to do the collapsing, since embedded images don't have a title header like image attachments do. 

I created an Improvement ticket for this here, as this is not technically considered a bug: https://mattermost.atlassian.net/browse/MM-12290.

**Comment by Roy-Orbison** [comment]
It should be a bug. If someone embeds a GIF this way, it will annoy you for eternity.

**Comment by esethna** [comment]
@Roy-Orbison sorry for the delay, but thanks for your thoughts on the ticket! 

Agree with your proposed solution and I've [updated the ticket to reflect that solution](https://mattermost.atlassian.net/browse/MM-12290). Would you or anyone else on this thread be interested in contributing this change for hacktoberfest?

**Comment by wiersgallak** [comment]
This was addressed with v5.35 with this PR: https://github.com/mattermost/mattermost-webapp/pull/7352 (and associated ticket https://mattermost.atlassian.net/browse/MM-12290)
