### ISSUE TITLE
possibility to disable shorturl redirect_location thing

### ISSUE THREAD

**Issue by zetaab** [mattermost/mattermost-server#9457]
#### Summary
When some user posts url to channel, all users are executing row https://github.com/mattermost/mattermost-webapp/blob/master/components/post_view/post_body_additional_content/post_body_additional_content.jsx#L95 which goes to https://github.com/mattermost/mattermost-server/blob/master/api4/system.go#L453 . However, this is really problematic if you have big channels. Lets say that I will write 10 times same url to channel which have 2000 members. Each user will make 10 requests to mattermost server, and mattermost server will make 2000*10 requests to that url. You can imagine what happens in service which will get these 20000 requests.

Also this is bad feature for servers which do not have access to internet. 

#### Possible fixes
1) make cache to server side function
2) make possibility to disable this whole feature from webapp and from server

**Comment by amyblais** [comment]
Hi @zetaab, thank you for reaching out.

We have a Jira ticket related to this open here: https://mattermost.atlassian.net/browse/MM-12264 - does it describe what you're seeing?

**Comment by zetaab** [comment]
this is related also to https://github.com/mattermost/mattermost-server/issues/9437

**Comment by amyblais** [comment]
Hi @zetaab, do you mean that you see this issue when `enableLinkPreviews` is set to `true` on your server?

**Comment by zetaab** [comment]
@amyblais we have enablelinkpreviews set to false, but it does not help. Mattermost is still calling this `redirect_location` backend url from `webapp` and backend is calling the real address in real internet.

**Comment by amyblais** [comment]
@zetaab What I meant is that the Jira ticket (https://mattermost.atlassian.net/browse/MM-12264) describes an issue with `redirect_location` when `enableLinkPreviews` is set to `false` - do you also see the same issue when `enableLinkPreviews` is set to `true`?

**Comment by zetaab** [comment]
@amyblais no, we have also value `false` but as I understand it should not call those links with value `false` and its bug?

**Comment by amyblais** [comment]
That's correct 👍 I'll add some of your notes in this Github Issue to the Jira ticket.

**Comment by zetaab** [comment]
@amyblais I did PRs for those, but I do not have idea is `master` correct branch where those should be committed. Maybe someone will say is it :)

**Comment by amyblais** [comment]
This issue has been resolved and tested internally. The fix will be available in v5.4 release,
