### ISSUE TITLE
Update base of mattermost-push-proxy container

### ISSUE THREAD

**Issue by J0WI** [mattermost/mattermost-server#9460]
#### Summary
From mattermost/mattermost-docker#303:
The container in [depends on an outdated Ubuntu](https://github.com/mattermost/mattermost-kubernetes/blob/master/docker/push-proxy/Dockerfile#L1) whereas Alpine or Debian are more common.

#### Possible fixes
Change `FROM` to `ubuntu:18.04`, `debian:stretch` or rewrite the Dockerfile based on `alpine:3.8` (basically by replacing `apt` with `apk`).

**Comment by SmartHoneybee** [comment]
Hi,

why is Ubuntu 16.04 outdated? (It's a LTS release with [EOL in 2021](https://wiki.ubuntu.com/Releases). Also, according to [this page](https://store.docker.com/images/ubuntu/plans/9e9c1933-4a5b-43e6-a1f6-63840afad5aa?tab=tags) `ubuntu:16.04` was last updated this month.)

Regards,
Bee

**Comment by amyblais** [comment]
There hasn't been updates on this for a while, so I'll close this Issue for now. Also, this will probably be addressed in the ticket created for https://github.com/mattermost/mattermost-server/issues/9459.
