### ISSUE TITLE
Searching all channels in all teams from all time?

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#9464]
I'm having some issue where it seems that the search functionality doesn't search through all channels for all teams for all time.  It appears to be quite limited to the current visible timeframe + the current channel.  Is there a way currently to do a shotgun search of everything across the entire system that is accessible to the current user that I'm missing?

By default it would be nice to search for a term and have it return everything from everywhere.  Right now it seems I can't even use `<term> in <team_name>` or `<term> in *`.

**Comment by amyblais** [comment]
Hi @ylluminate, we haven't received an update so I'll close this Issue for now.

Thank you for upvoting the feature request!

**Comment by ylluminate** [comment]
@amyblais this has [continued to grow](https://mattermost.uservoice.com/forums/306457-general/suggestions/20081047-search-through-all-teams) to a lot of votes for a request functionality. 

Have you seen / heard any other discussion of this? It's a super unfortunate lacking for Mattermost.

Can you or someone summarize what would need to be done to implement this?  I'm not sure if we have time to actually chew on this issue at the moment, but it has reached critical mass for us and we've been even having some discussion about other options since it is difficult to handle the way search is currently implemented in this system.

**Comment by ylluminate** [comment]
@amyblais I'm curious about looking into making a plugin for MatterMost that might facilitate this. Do you know if anyone has dabbled in this area yet?

**Comment by amyblais** [comment]
@ylluminate I'm not aware, but you could share about it in our [Integrations and Apps channel](https://community.mattermost.com/core/channels/integrations) and our staff / other community can help out with it. Thanks for your interest in making a plugin for this!

I can also help post about it in the channel if you are able to share more details about what type of plugin you're thinking of.
