### ISSUE TITLE
Opt out of analytics

### ISSUE THREAD

**Issue by LINKIWI** [mattermost/mattermost-server#9466]
I'm seeing hundreds of requests being made to api.segment.io from Mattermost on a new installation over the course of a day. It would be great to either:

1. Provide admins the ability to opt out of all server-side tracking and analytics
2. Be very clear and transparent by informing admins during installation that analytics data is automatically collected and there is no way to opt out

I understand that there are some easy workarounds:

1. Fork the project and remove all analytics and tracking logic
2. Route api.segment.io to an invalid host via DNS

But it would be ideal if this can be controlled natively as part of application logic during setup. (Apologies if this is already possible; I couldn't find any such option in the settings interface or in the config file.)

**Comment by SmartHoneybee** [comment]
Hi,

hope this helps: https://docs.mattermost.com/administration/telemetry.html

Regards,
Bee

**Comment by LINKIWI** [comment]
This seems to be what I was looking for, thanks!

**Comment by sneak** [comment]
Turns out the setting (documented nowhere) is `MM_LOGSETTINGS_ENABLEDIAGNOSTICS` = `"false"`.  I haven't tested it.

You can also do the following in a Dockerfile:

```
FROM mattermost/mattermost-team-edition:latest
RUN sed -i 's#api.segment.io#xx.example.com#gI' /mattermost/bin/mattermost"
RUN sed -i 's#cdn.segment.com#xxx.example.com#gI' /mattermost/bin/mattermost"
```

That should solve the issue.

**Comment by a3nm** [comment]
@sneak changing the environment variables indeed seems to solve the issue, thanks! Specifically, in `/lib/systemd/system/mattermost.service`, add:

```
Environment=MM_LOGSETTINGS_ENABLEDIAGNOSTICS=false
MM_SERVICESETTINGS_ENABLESECURITYFIXALERT=false
```

It then seems that mattermost no longer queries `segment.io`.

**Comment by sneak** [comment]
Really shameful and unethical that this happens without notifying the user, and that turning it off is not documented clearly anywhere.
