### ISSUE TITLE
Deleted team memberships returned by API

### ISSUE THREAD

**Issue by peterlloydcc** [mattermost/mattermost-server#9470]
#### Summary
API returns deleted team memberships and the only way of telling they are deleted is to look at an undocumented field.

#### Steps to reproduce
Using Mattermost 5.1.1

I have a user who according to the UI is not a member of a team.

Using `GET /api/v4/teams/{team_id}/members` the user is NOT shown as part of the team as expected.

Using `GET /api/v4/teams/{team_id}/member/{user_id}` DOES return a team membership.

The full JSON data returned by  `GET /api/v4/teams/{team_id}/member/{user_id}` is as follows
`
{ "team_id": xxxx, "user_id": xxxx, "roles": "team_user", "delete_at": 153798146547, "scheme_user": true, "scheme_admin": false, "explicit_roles":"" }
`

The only way of telling that the user is not actually part of the team is to look at the "delete_at" value and observe it is non-zero. Despite the user not being a member of the team the roles field has "team_user" set.

The "delete_at" value (as well as a few others) is undocumented. Only "team_id" "user_id" and "roles" are undocumented.

I'm not entirely confident of the reproduction steps yet (though it is reproducible), but this is what I believe has happened:
- user leaves team (setting delete_at to a nonzero value and setting roles to "")
- a script has done a `GET /api/v4/teams/{team_id}/member/{user_id}` and seen the is part of the team but has incorrect roles set
- the script has done a `PUT /teams/{team_id}/members/{user_id}/roles` to amend the roles
- the roles have been amended by the PUT but this does not set `delete_at` to 0 or join the user to the team.

#### Expected behavior
Using the API endpoint `/teams/{team id}/member/{member id}` it should only be possible to retrieve team memberships which also appear in `/teams/{team id}/members` .

#### Observed behavior (that appears unintentional) 
Team memberships of team members who have left the team also appear using API endpoint `/teams/{team id}/member/{member id}`. These can still have "team_user" set in roles and the only way of telling they are actually deleted is to reference the undocumented `delete_at` field.

#### Possible fixes
`store/sqlstore/team_store.go`, GetMember function does not contain a "TeamMembers.DeleteAt" test in the SQL query which the GetMembers function (below in the file) does.

**Comment by amyblais** [comment]
Hi @peterlloydcc, thank you for reporting this.

Wondering if you'd be able to verify if you see this also on the latest Mattermost server version (v5.3.1)? Here is a link to one of our test servers that runs on the latest version: https://rctesting.reddogsofwar.com/login.

**Comment by peterlloydcc** [comment]
Hi Amy

Thanks for the link to your v5.3.1 server. I've tried with that and the issue is easier to reproduce than I was expecting!

**Reproduction**

You'll need two accounts. I'll call them user1 and user2

1. Using the web interface, user1 joins the "RC testing" team.
2. Using the web interface, user2 joins the "RC testing" team.

3. Using the API as **user1**:

`curl -H 'Authorization: Bearer xxxxx' https://rctesting.reddogsofwar.com/api/v4/teams/6njza74j5tbiz8nk83ehfztheh/members/6k7989mucbfefntox85x5mbwoy
{"team_id":"6njza74j5tbiz8nk83ehfztheh","user_id":"6k7989mucbfefntox85x5mbwoy","roles":"team_user","delete_at":0,"scheme_user":true,"scheme_admin":false,"explicit_roles":""}
`
**this is as expected**

4. Now remove user1 from the team:
`curl -X DELETE -H 'Authorization: Bearer xxxxxx' https://rctesting.reddogsofwar.com/api/v4/teams/6njza74j5tbiz8nk83ehfztheh/members/6k7989mucbfefntox85x5mbwoy
{"status":"OK"}
`

At this point the UI has updated to reflect the fact that user1 has left the team.

User1 no longer has the ability to view team memberships of a team they are not a member of, so we use user2 to view the team memberships.

5. Using the API as **user2**:
`curl -H 'Authorization: Bearer yyyyy' https://rctesting.reddogsofwar.com/api/v4/teams/6njza74j5tbiz8nk83ehfztheh/members`

Observe that **user1** is not listed here as expected

6. Using the API as **user2**:
`curl -H 'Authorization: Bearer yyyyy' https://rctesting.reddogsofwar.com/api/v4/teams/6njza74j5tbiz8nk83ehfztheh/members/6k7989mucbfefntox85x5mbwoy
{"team_id":"6njza74j5tbiz8nk83ehfztheh","user_id":"6k7989mucbfefntox85x5mbwoy","roles":"team_user","delete_at":1538040992968,"scheme_user":true,"scheme_admin":false,"explicit_roles":""}
`

**Here, user1 is shown as a member with roles still set to `team_user`, even though they have left the team. The only clue is the undocumented `delete_at` field being nonzero**

Hopefully that clarifies things and you are able to reproduce it too.

**Comment by amyblais** [comment]
Thanks @peterlloydcc! I created a ticket for this here: https://mattermost.atlassian.net/browse/MM-12385.

**Comment by amyblais** [comment]
Hi @peterlloydcc, developers determined that the API behaviour is actually correct, but we added information in our docs to document the DeleteAt field via this PR: https://github.com/mattermost/mattermost-api-reference/pull/404.
