### ISSUE TITLE
How to build it the right way

### ISSUE THREAD

**Issue by fincha** [mattermost/mattermost-server#9480]
Hi all, 

I have pulled the current version and made some modifications we urgently need.

I have made a linux build, at least I have a bin bile in the bin folder.
But I don't see the licence menu there... how do I build it, so I can see the licence menu?

I am working on ubuntu 18
go version 1.9.x

**Comment by amyblais** [comment]
Hi @fincha, thank you for reaching out.

When you say "license menu", are you referring to "Edition and License" page in the System Console?

If not, can you help clarify what you mean with a screenshot?

If yes, I believe you'll need to be on Enterprise Edition to see the option.

**Comment by fincha** [comment]
Hi, 

usualy I would download the version and upload the licence file, so the server activates enterprice features.

![grafik](https://user-images.githubusercontent.com/2435678/46167947-6bd87c00-c297-11e8-9d85-bee626aa51f0.png)

I beleave the link with licence was at the bottom, but there is no... I see 2 options:

custom build -> no enterprice
dev build -> so maybe I am missing a flag?

**Comment by amyblais** [comment]
Hi @fincha, I encourage you to take a look at our documentation on how to build Mattermost: https://developers.mattermost.com/contribute/server/developer-setup/.

https://github.com/mattermost/mattermost-server is Team Edition only, so you won't see any Enterprise related features when you build Mattermost from the source.

**Comment by fincha** [comment]
@amyblais hm, so I can't activate auth 2 with office365? But the code is present?! 

Is there a way to intercept the complete action via plugin after login? Our usecase is, I want user to redirect to out app not to chat in one single special case.

**Comment by fincha** [comment]
@amyblais yes, I even uploaded the licence via cli, and it worked fine, but no frontend changes.

**Comment by amyblais** [comment]
Hi @fincha, please take a look if these docs help:

- https://docs.mattermost.com/install/ee-install.html#checking-your-mattermost-edition-and-version
- https://docs.mattermost.com/install/ee-install.html#upgrading-to-enterprise-edition-from-mattermost-team-edition
- https://docs.mattermost.com/administration/upgrade.html#upgrading-team-edition-to-enterprise-edition

**Comment by fincha** [comment]
well, as described in FAQs I need a separate binary. But the point is, I have made a modifications in the "signup/.../complete' action and we need them. So the sourcecode here in github is not the suiteable for enterprice?

**Comment by fincha** [comment]
@amyblais is it possible to get a enterprice build containing this lines:

https://github.com/fincha/mattermost-server/pull/1/files

?

**Comment by fincha** [comment]
@amyblais how long will this take to implement such thing? We are running out of time, and I was hoping to do a quick fix.

**Comment by amyblais** [comment]
@fincha The integration might take some time to do - can you help with more details on the step-by-step sign-up process that you are looking to implement? I can then check with our team if we already have a current solution as a workaround / alternative that you can use.
