### ISSUE TITLE
[Help Wanted] [MM-11829] Design & implement a method for including custom system console components for plugins

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9483]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11829)

An existing feature of the plugin infrastructure is to provide plugins with their own System Console settings page. These settings pages let system administrators configure settings specific to the plugin. The content of this page is described by the `settings_schema` field of the plugin manifest. Documentation for this field is here https://developers.mattermost.com/extend/plugins/manifest-reference/#settings_schema.

The existing schema provides options for a lot of basic setting types but oftentimes plugins need more advanced or customized configuration settings.

First, design a way to allow the plugin to specify custom setting types and to use those in the settings_schema. The custom setting should be defined by a React component as part of the [web app portion of the plugin](https://developers.mattermost.com/extend/plugins/webapp/). You'll likely want to add a new method to the [web app plugin registry](https://github.com/mattermost/mattermost-webapp/blob/master/plugins/registry.js) for letting plugins register their custom setting components.

Comment with a design proposal here or in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit).

Once the design is agreed upon, implement the design.

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by jwilander** [comment]
There may be a small amount of Go work required for this as well.

**Comment by jasonblais** [comment]
Re-opened here: https://github.com/mattermost/mattermost-server/issues/10320
