### ISSUE TITLE
[Help Wanted] [MM-11861] Design & implement a better way for plugins to update their own configuration

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9484]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11861)

Plugins have the ability to update their own configuration using the GetConfig() and UpdateConfig() API methods but these are very heavy-weight to use and require some knowledge of how the Mattermost configuration works under the covers. It also makes it very easy to screw up and accidentally change an important configuration setting that the MM server relies upon.

Design & implement new helper functions to be part of the code available to plugins to make self-configuration updates easier for plugins. These helper functions should not necessarily be new plugin API methods but rather helper functions part of the [plugin package](https://github.com/mattermost/mattermost-server/tree/master/plugin). It may be necessary to provide new plugin API methods to accomplish this in a race-free way (maybe by adding a PatchConfig() API method, for example).

Use cases where this would be helpful:
- Install wizards created by the plugin to set itself up
- Auto-generation of secrets/keys/etc.

Plugin contribution documentation is available here https://developers.mattermost.com/contribute/server/plugins/.

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by jasonblais** [comment]
@sandlis It would be great to have your help with this improvement! I've pinged one our engineers to help review your proposal.

**Comment by sandlis** [comment]
Thanks @jasonblais!
Will be waiting for a response. You want me to ask this in Contributors group as well?

**Comment by jasonblais** [comment]
Sure! I also posted it here if you want to add any more details https://pre-release.mattermost.com/core/pl/7a7rswu8mjnzm8dmwqdzzd67pa

I'll nudge our community as my message might have gotten missed (there was lots of chatter in that channel yesterday)

**Comment by crspeller** [comment]
@sandlis We would want to preserve the GetConfig and SaveConfig functions for plugins to modify the server config. New `GetPluginConfig` and `SavePluginConfig` functions would be preferable. Remember that this needs to be implemented in a race-free way.

**Comment by sandlis** [comment]
@crspeller Thanks for the response!
By race-free way do you mean having an exclusive lock while updating config in SavePluginConfig?

**Comment by jwilander** [comment]
Discussion is being continued here https://pre-release.mattermost.com/core/pl/ufm8ex9hq7nkfdxxaut88cwq4r

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/9712
