### ISSUE TITLE
[Help Wanted] [MM-12239] Remove "System Console > Plugins > Configuration" page, move enabling plugins setting to the Management page, and update help text for plugin uploads

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9485]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12239)

Right now there are two difference pages where plugins are configured/managed. System Console -> Management and System Console -> Configuration. Consolidate the pages into one by doing the following:

1. Move "Enable Plugins" setting from System Console > Plugins > Configuration to System Console > Plugins > Management
2. Remove System Console > Plugins > Configuration page
3. When plugin uploads aren't enabled, update help text for "Upload Plugins" to read "Enable plugin uploads in config.json. See <documentation> to learn more."

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by avasconcelos114** [comment]
I could help out with this one if that's okay.
  
Just got a couple of questions about the `Upload Plugins` part:
1. Which link are you looking to add to the `See documentation to learn more`  part? [This one](https://docs.mattermost.com/administration/config-settings.html#plugins-beta) makes sense to me but I was wondering if anything else fits better
2. Should the `Upload` button be disabled when Plugins aren't enabled? Or should users still be able to upload plugins without them being enabled?

**Comment by jasonblais** [comment]
Great questions!
1. You can use this link: https://about.mattermost.com/default-plugin-uploads
2. The `Upload` button should be disabled if plugins aren't enabled, or if plugin uploads aren't enabled.

**Comment by avasconcelos114** [comment]
Couple more things I want to make sure I get right before submitting a PR:
1. Some of these changes to strings require updates on the `i18n/en.json` file, can I just edit it directly or is there a separate process for this?
2. Given that we now went from 2 to 4 possibilities on `Upload` button's disabled state (combinations of `Enable` and `EnableUploads`), what exactly should the help text say when conditions for the button aren't met? Should it still just be `Enable plugin uploads in config.json. See documentation to learn more.`?

**Comment by jasonblais** [comment]
@avasconcelos114 Sorry for the delay on my part.

1 - Yes, you can edit the `i18n/en.json` file directly.
2a - If plugins are enabled, then we can keep the existing texts.
2b - If plugins are disabled, then the help text can read `To enable plugins, set **Enable Plugins** to true.`. It might also make sense to hide the `Installed Plugins` section when plugins are disabled, like we do toda.
