### ISSUE TITLE
[Help Wanted] [MM-12357] Create CLI command "command list"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9490]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12357)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `command list` command in the CLI.

Allow listing slash commands, for a team, or for all teams.

Example: `command list myteam`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by sonasingh46** [comment]
@esethna 
I would like to work on this issue.
Will raise a PR in some time

**Comment by jespino** [comment]
Awesome @sonasingh46! let me know if you need any help, here or in https://pre-release.mattermost.com.

**Comment by sonasingh46** [comment]
@jespino 
I have raise a PR... Please tell if I am going write or if any modification needs to be done etc.

**Comment by jespino** [comment]
closed by #9531
