### ISSUE TITLE
[Help Wanted] [MM-12304] Create CLI command "channel search"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9491]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12304)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `channel search` command in the CLI.

Allow searching channels like in `user search` command

Example: `channel search dev`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by satyamz** [comment]
Hi @esethna , I'd like to work on this.

**Comment by jespino** [comment]
Awesome @satyamz! let me know if you need any help, here or in https://pre-release.mattermost.com.

**Comment by satyamz** [comment]
Hi @jespino I implemented this for `mattermost channel search teamID:dev`. 
Is it ok or Do I need to implement it for other scenarios?

**Comment by jespino** [comment]
@satyamz I added a comment in the PR

**Comment by adzimzf** [comment]
Hi, I try to work with this one.

Here's the PR.
https://github.com/mattermost/mattermost-server/pull/10093
