### ISSUE TITLE
[Help Wanted] [MM-12356] Create CLI command "command delete"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9492]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12356)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `command delete` command in the CLI.

Allow deleting slash commands.

Example: `command delete w16zb5tu3n1zkqo18goqry1je`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by gupsho** [comment]
Hi, I would like to work on this.

**Comment by jasonblais** [comment]
That would be great, thank you @gupsho :tada:
