### ISSUE TITLE
Japanese word `#疑問` does not appeared as hashtag

### ISSUE THREAD

**Issue by maruTA-bis5** [mattermost/mattermost-server#9493]
#### Summary
`#疑問` does not appeared as hashtag.
Note: `疑問` is Japanese meaning `question`.

#### Steps to reproduce
enter `#疑問` and post them.

#### Expected behavior
`#疑問` display as the hashtag.

#### Observed behavior (that appears unintentional) 
`#疑問` does not hashtag.

![image](https://user-images.githubusercontent.com/1310661/38847473-c107566e-423c-11e8-8e50-05a57261136c.png)
https://pre-release.mattermost.com/core/pl/hfsfw3orsbfpprwq9fgwfzuq4y
*reproduced in Latest Firefox and Desktop App.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Thank you @maruTA-bis5, I opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-12384.

**Comment by amyblais** [comment]
Closing this as this can be tracked via the Help Wanted Issue that is open here: https://github.com/mattermost/mattermost-server/issues/9156.
