### ISSUE TITLE
[Help Wanted] [MM-11560] Allow plugins to add channel header tooltips

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9497]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11560)

An existing web app plugin feature is the [ability to register channel header actions](https://github.com/mattermost/mattermost-webapp/blob/master/plugins/registry.js#L89). This allows a plugin to display a button in the channel header that calls a JS function, defined by the plugin, when clicked.

Currently, the register function is `registerChannelHeaderButtonAction(icon, action, dropdownText)`. Add a new parameter named `tooltipText`. If specified on register, the plugin channel header button shown should have a tooltip appear on hover.

Note that more than one channel header buttons are registered (regardless of which plugins are doing the registering) they are collapsed into a dropdown menu which does not need any tooltips.

The tooltip should match existing channel header button tooltips for styling.

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by kaakaa** [comment]
I would like to work on this.
