### ISSUE TITLE
[MM-9563] Add a red dot to browser favicon when there are unread mentions

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9502]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9563)

When the user has unread mentions, the browser favicon should get a red dot, as in the following screenshot:

![image](https://user-images.githubusercontent.com/14333569/46235468-a7c31e00-c337-11e8-90cf-232bc152e91b.png)

Favicon asset: 
![favicon](https://user-images.githubusercontent.com/14333569/46235488-b9a4c100-c337-11e8-80d7-b31f193fc3a5.png)

This feature should be supported on Chrome and Firefox, but not on Edge or Safari due to caching issues which made the favicon not appear reliably.

**Comment by MathieuTougas** [comment]
I have a good experience with your  codebase. I'd like to work on this.

**Comment by jasonblais** [comment]
Thank you @MathieuTougas! Please let us know if you have any questions

**Comment by hanzei** [comment]
Hey @MathieuTougas 

Do you have any questions? Looking forward to this feature!

**Comment by hanzei** [comment]
Making this available to the public because there wasn't an update from @MathieuTougas for some time.

**Comment by b-lawrence** [comment]
I've managed to set up MM server and webapp. Everything looks good. I'd like to start with this.

**Comment by jasonblais** [comment]
Thank you @b-lawrence! Let us know if you have any questions while working on it.

**Comment by b-lawrence** [comment]
https://mattermost.atlassian.net/browse/MM-13643 indicates that updating the favicon when notifications are present was disabled for a reason. What's the verdict?

**Comment by jasonblais** [comment]
Hey @b-lawrence, good question. Let me verify with our UX team but my understanding is that the design proposed here is still the one we want to use.

**Comment by jasonblais** [comment]
@b-lawrence I've posted the question to our UX team here : https://community.mattermost.com/core/pl/mayikusee78xubmk69bgn4bfpe

**Comment by jasonblais** [comment]
@b-lawrence Have confirmed that the design proposed here is still accurate. If you're interested helping with the implementation, that would be very much appreciated!

**Comment by b-lawrence** [comment]
PR created

**Comment by jkl5616** [comment]
I'd like to take this!

**Comment by jasonblais** [comment]
Great, thank you @jkl5616! Let us know if you have any questions

**Comment by jkl5616** [comment]
@jasonblais It would be better if there are favicon assets of 32x32 and 96x96.

**Comment by jasonblais** [comment]
> It would be better if there are favicon assets of 32x32 and 96x96.

@asaadmahmood is this something you'd be able to help provide for @jkl5616?

**Comment by jkl5616** [comment]
@amyblais Does this issue need more additional work?

**Comment by amyblais** [comment]
@jkl5616 We made a decision to revert the original feature PR from v5.14 because it was causing this bug: https://mattermost.atlassian.net/browse/MM-17618. We are too close to v5.14 release day to have time to fix the bug at this point.

**Comment by jkl5616** [comment]
@amyblais Okay, then can I handle this as I am the original contributor of that PR?

**Comment by amyblais** [comment]
Sounds good, thank you.

**Comment by hmhealey** [comment]
FYI, we decided that this feature should only be supported on Chrome and Firefox since we've ran into issues with consistency when changing the favicon on Edge and Safari. I've updated the ticket description to reflect that

**Comment by hmhealey** [comment]
Hi @jkl5616. Are you still working on this? Is there anything we can help with?

**Comment by larkox** [comment]
May I take this one?

**Comment by jasonblais** [comment]
@larkox Go for it! As you can see above, there have been a couple of PRs opened previously that were closed, I'd propose reviewing them first to see what outstanding items there were.
