### ISSUE TITLE
[Help Wanted] [MM-11675] All system messages which have usernames should match join/leave styling and popover functionality

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9503]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11675)

All system messages that have usernames should link to the profile pop-over to be consistent with join/leave/added to channel system messages.

Cases being:
- User changed channel purpose
- User changed channel name
- User changed channel header
- User archived the channel

See join/leave/added to channel system messages:

 !screenshot-1.png|thumbnail!

**Comment by amorriscode** [comment]
Hi there! 👋 

I'm interested in completing this ticket.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/1808
