### ISSUE TITLE
[Help Wanted] [MM-9494] React Native: If the keyboard is open, swiping down past it should close it

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9504]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9494)

This ticket should be done on the mattermost-mobile repository: https://github.com/mattermost/mattermost-mobile

------

Repro: 
1. Click into the texbox to open the keyboard
2. Swipe down to scroll the channel, extending over top of the text input box

Observed: Keyboard stays open

Expected: 
Keyboard should close if the swipe action goes overtop the text input box. Do not close the keyboard if the swipe action is only on the channel, and not on the keyboard. 

[See iMessage, FB messenger, most other apps for example]

**Comment by SkipperEl** [comment]
I'll take this.

**Comment by hanzei** [comment]
@SkipperEl Great that you are working on this! :+1: Do you have any questions?

**Comment by hanzei** [comment]
Making this available for the public again. @SkipperEl feel free to pick it up again, if you have the time.

**Comment by esethna** [comment]
Closing and reopening a new ticket for this
