### ISSUE TITLE
[Help Wanted] [MM-8404] Channel notification setting for disabling channel mentions

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9505]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8404)

Add a channel notification setting to disable (or enable) @-channel @-here @-all notifications in specific channels.

Webapp: 
---------
https://github.com/mattermost/mattermost-webapp

In the Channel Menu > Notification Preferences add the following setting below "Mute Channel":

**Ignore mentions for @channel, @here, @all**

"On"
"Off"

Help Text: "When enabled, @channel, @here and @all will not trigger mentions or mention notifications in this channel."

React Native: 
---------
https://github.com/mattermost/mattermost-mobile

In the Channel Menu > below "Mute Channel":

**[@] Ignore @channel, @here, @all**                 [switch] 

________

Functional behavior: https://docs.google.com/document/d/14-Tp6elyWbXn2-X_qiWdlx_OSt_jwEXVaAHO64wBx80/edit#bookmark=id.g15kdcc96elc

**Comment by letsila** [comment]
Hi @esethna, I'd like to work on this issue.

**Comment by jasonblais** [comment]
Thanks @letsila! Let us know if you have any questions.

**Comment by hmhealey** [comment]
Closing this as all 4 PRs have now been merged. Thanks @letsila!

**Comment by towolf** [comment]
@hmhealey I can't seem to find this setting in the released version 5.6.2?

**Comment by towolf** [comment]
![image](https://user-images.githubusercontent.com/345210/50666322-916ed300-0fb4-11e9-8312-b6f79ec8ee36.png)

**Comment by jasonblais** [comment]
@towolf This was actually not merged to 5.6 release, it'll be available in 5.8 which comes out on Feb 16, 2019.

**Comment by towolf** [comment]
@jasonblais thanks for the info. People have been inquiring about this ...
