### ISSUE TITLE
Keyboard shortcut for adding reactions to last message in channel or thread

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9506]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12142)

*+Shortcuts modal+*
In the shortcuts modal, add the following entry below "Reply to last message in the channel"

```
React to last message in channel or thread      CTRL/CMD + Shift + \
```

+*Functionality*+
1. Viewing a channel but no text input boxes have focus, shortcut opens emoji picker above the center channel text input box and will add a reaction to the latest post in the center channel
2. Viewing a channel and the center channel text input box has focus, shortcut opens emoji picker above the center channel text input box and will add a reaction to the latest post in the center channel
3. Viewing a channel and the right-hand side text input box has focus to add a comment to a thread, shortcut opens emoji picker above the right-hand side text input box and will add a reaction to the latest post in the thread.

Emoji picker should open on the left side of the text input boxes to differentiate adding reactions vs emojis to the text draft:

 !image-2018-09-12-15-18-14-431.png|thumbnail! 

 !image-2018-09-12-15-19-25-049.png|thumbnail! 

_________
Community request: https://mattermost.uservoice.com/forums/306457-general/suggestions/31927360-emoji-reaction-keyboard-shortcut

**Comment by jasonblais** [comment]
Awesome, thank you @JayaKrishnaNamburu!

**Comment by hanzei** [comment]
@M-ZubairAhmed will work on this

**Comment by M-ZubairAhmed** [comment]
yay its been an year since it was opened and finally completed :-D
