### ISSUE TITLE
Add ability to remove custom branding image

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9507]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12068)

Add the ability to remove a custom branding image similar to the flow implemented in Team Settings > Team Icon.

In System Console > Custom Branding > Custom Brand Image:
1. Update button text: "Choose New Image" > "Select Image"
2. Remove the upload button so the image uploads automatically after being selected from the file picker. So the button presses would be:
*      "Select Image" > File picker opens, user selects image, then it uploads automatically and generates the image preview (like how it does now).

3. Add an "x" button to the brand image preview once an image is selected. Tool tip: "Remove brand image"
4. When "x" is clicked, remove the brand image preview, but don't save until the user clicks "Save" on the system console page.

Invision screens: https://projects.invisionapp.com/share/T6O2PN04EFC#/screens/320132211

**Comment by jlevesy** [comment]
Hi folks, I'm interested in working on this !
I'll reach for more informations soon !

**Comment by amyblais** [comment]
Thank you @jlevesy! Feel free to ask any questions.

**Comment by jlevesy** [comment]
Just to keep you posted, I started to work on this on [that](https://github.com/jlevesy/mattermost-webapp/tree/MM-12068) branch.

I'll open a pull as soon as I get something interesting :)

**Comment by jlevesy** [comment]
Okay so status update :) : 

- Server side implementation is done here #9552 (with documentation update here https://github.com/mattermost/mattermost-api-reference/pull/401)
- Redux and javascript client binding is here https://github.com/mattermost/mattermost-redux/pull/664
- I have a WIP branch [here](https://github.com/jlevesy/mattermost-webapp/tree/MM-12068) which does implement-ish the new UX.

Things that I still need to do:
- Trigger the `deleteBrandImage` call only when save is clicked (item 4). However I'm not sure how to do this because the save button only triggers a config update and I was not able to find a way to hook a custom action... I would love to get some insights about that :) !
- Style the `deleteBrandImage` button.

**Comment by amyblais** [comment]
@esethna Can you help with the questions on `deleteBrandImag` or ping a dev ^

**Comment by esethna** [comment]
@jespino any guidance you can provide on the first to do item above?

Regarding styling the button, we can have our team help with that after the PR is submitted if you'd prefer?

**Comment by jlevesy** [comment]
> Regarding styling the button, we can have our team help with that after the PR is submitted if you'd prefer?

Thanks. I'll give it a try first :)

**Comment by grundleborg** [comment]
I've merged the server changes into master (for 5.6).

**Comment by hanzei** [comment]
@jlevesy How is your implementation going? Do you have any questions?

**Comment by hanzei** [comment]
Making this available to the public because there wasn't an update from @jlevesy  for some time.

**Comment by steveperjesi** [comment]
I'll take this one.

**Comment by hanzei** [comment]
Thanks for looking into this @steveperjesi. Let us know, if you have any questions.

**Comment by hanzei** [comment]
Hey @steveperjesi,

I just want to check how your work on this going. Do you have any questions?

**Comment by steveperjesi** [comment]
Hi @hanzei I have all but the testing ready and it's been sitting in my dev. If my planets align tomorrow or Saturday, I'll put a PR so we can all take a look.

**Comment by hanzei** [comment]
Hey @stephenkiers,

Thanks for the update. Looking forward to your PR! :rocket:

**Comment by hanzei** [comment]
Hey @steveperjesi,

Just checking if you are still working on this and if you have questions.

**Comment by hanzei** [comment]
Hey @steveperjesi,

Just checking if you are still working on this and if you have questions.

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by hahmadia** [comment]
Hey, could I have a go at this ticket? 
Thanks :)

**Comment by hanzei** [comment]
Hey @hahmadia,

Thanks for working on this :+1:

**Comment by steveperjesi** [comment]
Sure go ahead! I only worked on it for a minute before life happened.
Thanks for picking up my slack 👍

**Comment by hahmadia** [comment]
Completed!
Awaiting code review and style review (I wasn't sure how to style the X button properly so any help and advice would be greatly appreciated since I didn't quite understand how to style a className.)

Thanks 😄

**Comment by saturninoabril** [comment]
PR has been merged.  Thank you @hahmadia for your contribution!
