### ISSUE TITLE
[Help Wanted] [MM-12366] Create CLI command "team restore"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9508]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12366)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `team restore` command in the CLI.

Allow restoring a archived team like in `channel restore` command

Example: `team restore myteam`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by sonasingh46** [comment]
@esethna 
I would like to work on this issue.

**Comment by jasonblais** [comment]
@sonasingh46 Great! Thank you 👍

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/9551
