### ISSUE TITLE
[Help Wanted] [MM-12363] Create CLI command "team archive"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9509]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12363)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `team archive` command in the CLI.

Allow archiving teams like in `channel archive` command

Example: `team archive teamname`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by waseem18** [comment]
Got a good understanding of the `team` command code, so would like to work on this.

**Comment by waseem18** [comment]
@esethna 
So `team archive` simply archives all the channels of the given team. Am I right?

**Comment by jespino** [comment]
I would expect to simply archive the team, but not the channels inside it.

**Comment by waseem18** [comment]
I've put up a PR for this issue - https://github.com/mattermost/mattermost-server/pull/9565

Please let me know if I'm on the right track.

Also I'll take a look at the build failure.

**Comment by waseem18** [comment]
I've been looking into the cause of build failure, I see the `test-te` command from `Makefile` failed for some reason. I'm not sure why it failed. 

Do you have any idea why the tests fail in `team edition` i.e `test-te` from Makefile. I haven't yet added any tests of the archive command though.

**Comment by jespino** [comment]
Yes, probably pre-release is the better way, because there you can stablish a proper conversation.

**Comment by jespino** [comment]
Anyway, sometimes we have some problems with the tests. We are working on improve the isolation between test runs in Jenkins to improve that. Sometimes you only need to close and reopen the PR to re-launch the tests in Jenkins, and they pass.

**Comment by waseem18** [comment]
I have a question @jespino 

After archiving a team, should it appear in `team list` and `team search` commands?

I'm now using the `SoftDelete` method to archive a team and after archiving I see that the `team` disappears from the Web app but still appears via `team list` and `team search` commands.

I'm writing test case for `archive` and wanted to know how to verify if a team is actually archived.

**Comment by waseem18** [comment]
I see `channels` add `archived` command to the team names in the results of `channel list` and `channel search`. 

Would be better if we follow the same approach. Will have to tweak the `team list` command then.

**Comment by jespino** [comment]
Yes, would be great to add that to the other commands, and makes sense to do it in the same PR :)
