### ISSUE TITLE
[Help Wanted] [MM-12367] Create CLI command "team search"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9510]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12367)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `team search` command in the CLI.

Allow searching teams like in `user search` command

Example: `team search dev`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by waseem18** [comment]
Quick update : 

I was able to run the API server and the Web app running but I'm facing issues with the CLI.

I ran `go install` in `mattermost-server/cmd/mattermost` to generate the executable but mostly all commands seems to throw an error. Here's the error log - https://pastebin.com/t77Mrraj

Could someone please help me with this?

Thanks

**Comment by waseem18** [comment]
Thanks for the response @jasonblais 

I didn't install the CLI actually, I'm trying to build it from source. 

And yes, I ran the command right from the directory where the executable is - the `bin` folder inside `GOPATH` i.e `/Users/wasimthabraze/go`

**Comment by jasonblais** [comment]
I see - what is the output you get from `./mattermost version`?

**Comment by waseem18** [comment]
The same error - https://pastebin.com/t77Mrraj

**Comment by jasonblais** [comment]
Thank you - I'll need to get a developer's help review the errr next. I linked some of the conversation from here to your post in the Developers channel https://pre-release.mattermost.com/core/pl/a5gdbgbzebfeiri6paabf6ca5o

**Comment by waseem18** [comment]
Thanks for that @jasonblais

**Comment by waseem18** [comment]
So I got it running finally by another way.

Instead of generating an executable and running it, I tried running  the `main.go` file present in the `cmd` directory with the with arguments as commands and it seems to work.

Example : `go run main.go team create --name mynewteam --display_name "My New Team"`

**Comment by jasonblais** [comment]
Glad you got it working :)
