### ISSUE TITLE
[Help Wanted] [MM-12371] Create CLI command "webhook list"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9522]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12371)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `webhook list` command in the CLI.

Allow listing webhooks, for a team, or for all teams.

Because this is the first webhook command, a new `webhook.go` file needs to be created in the `cmd/mattermost/commands` directory.

Example: `webhook list myteam`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by klebervirgilio** [comment]
Can I help on this one?

**Comment by lologarithm** [comment]
where do you get webhooks for slash commands?

**Comment by lologarithm** [comment]
"CommandWebhookStore" ?

**Comment by klebervirgilio** [comment]
so... @lologarithm are you taking over?

**Comment by lologarithm** [comment]
I have most the code done I just wasn't clear on some details. but I can drop it if you really want it :)

**Comment by lologarithm** [comment]
However, I am not setup with the contributor license agreement (https://developers.mattermost.com/contribute/getting-started/contribution-checklist/)

Perhaps I should let @klebervirgilio take over if he is more prepared.

**Comment by klebervirgilio** [comment]
No worries... no problem at all. Really @lologarithm, all good! I will follow you PR to learn how I can get mine done! :) thanks!

**Comment by jasonblais** [comment]
Thank you @lologarithm and @klebervirgilio! 

@jespino Can you help with the question above regarding `Did you want to list outgoing hooks, incoming hooks, or both?`. It would make sense to list incoming webhooks, outgoing webhooks and slash commands, but in separate commands (and potentially separate tickets)?

@klebervirgilio I see you're tackling https://github.com/mattermost/mattermost-server/issues/9523 :)

**Comment by jespino** [comment]
@klebervirgilio @lologarithm @jasonblais The idea is to list both, and split the "creation/modification" commands, but the show, list and delete will be the same. Slash commands are handled by other CLI command, so Is not needed here.

But this is a good time to split it if we want. What do you think @jasonblais @klebervirgilio and @lologarithm ? Do you prefer separated commands for incomming and outgoing webhooks, or you prefer one command to rule them all ;)

**Comment by lologarithm** [comment]
Its about consumer use case I think. If it was me I would probably just be generally auditing or looking for a specific hook.

If its a general audit you want everything. If you are looking for a specific hook then you can just find the hook from all the output I think.

I would lean towards a combined command
