### ISSUE TITLE
App header on iPhone X/XS very difficult to click -- touch-targets seem off

### ISSUE THREAD

**Issue by djakubiec** [mattermost/mattermost-server#9526]
#### Summary
App header on iPhone X very difficult to click -- touch-targets seem off

#### Steps to reproduce
Load the new Mattermost app onto an iPhone X or Xs.  Try tapping one of the header button (like Main/hamburger menu, or settings dots).

#### Expected behavior
Direct click over menu icons should open their corresponding windows.

#### Observed behavior (that appears unintentional) 
Tapping directly on the buttons will usually do nothing.  But if you press **very** low (or slightly below) the button it will open up.

The touch targets seem so far off that for weeks I thought the header menu had actually stopped working.

Note that on older iPhones without the new iPhone X header hardware the touch behavior works normally and just as expected.  So this seems to be some kind of touch target issue related to the new header hardware layout.

#### Possible fixes
Workarounds: touch carefully below the icons, or swipe left/right instead.

**Comment by amyblais** [comment]
Hi @djakubiec, thank you for reaching out.

Does this report describe the issue you are seeing: https://github.com/mattermost/mattermost-mobile/issues/2152?

**Comment by djakubiec** [comment]
iOS 12.0
Mattermost 1.12.0 (build 142)
Mattermost server 5.2.0

**Comment by jasonblais** [comment]
@djakubiec @amyblais Support for iPhone XR, XS and XS Max is in fact coming with the next release on Oct 16th:

https://github.com/mattermost/mattermost-mobile/pull/2153

**Comment by djakubiec** [comment]
Oh, that fix sounds very promising thank you!

**Comment by amyblais** [comment]
Closing this as the fix has been resolved and tested internally,
