### ISSUE TITLE
AD users no longer showing as verified

### ISSUE THREAD

**Issue by Ouroboros1977** [mattermost/mattermost-server#9527]
I'm not sure when it started, I'm assuming after our upgrade to 5.2.1 .  Our users are no longer receiving notifications and the logs show:

{"level":"error","ts":1538491555.589711,"caller":"app/notification.go:211","msg":"Skipped sending notification email to user@domain.com, address not verified. [details: user_id=7j4ckbm8kbyfdmnt76i7om8uie]"}

All of our users are AD authenticated.

Mattermost Version: 5.2.1
Database Schema Version: 5.2.0
Database: postgres

Let me know what other information may be needed.  I need to know if there's a way to re-verify all our users without them having to do much if anything at all.
Thank you

**Comment by amyblais** [comment]
Hi @Ouroboros1977, thank you for reaching out.

Can you help check what this setting is set to on your server: System Console > Security > Require Email Verification?

**Comment by Ouroboros1977** [comment]
Require email verification is turned on.  Users can't join unless they've been sent an invitation.

**Comment by amyblais** [comment]
@Ouroboros1977 Can you help with details on your LDAP config settings: https://docs.mattermost.com/administration/config-settings.html#ad-ldap.

**Comment by Ouroboros1977** [comment]
@amyblais Below is our AD/LDAP settings:
    "LdapSettings": {
        "Enable": true,
        "EnableSync": true,
        "LdapServer": "corp.domain.com",
        "LdapPort": 389,
        "ConnectionSecurity": "",
        "BaseDN": "DC=corp,DC=domain,DC=com",
        "BindUsername": "ldaplookupaccount",
        "BindPassword": "ldaplookupaccountpassword",
        "UserFilter": "(\u0026(objectCategory=Person)(sAMAccountName=*)(memberOf=cn=mattermost_group,OU=Groups,OU=,DC=corp,DC=domain,DC=com))",
        "FirstNameAttribute": "giveName",
        "LastNameAttribute": "sn",
        "EmailAttribute": "mail",
        "UsernameAttribute": "sAMAccountName",
        "NicknameAttribute": "name",
        "IdAttribute": "sAMAccountName",
        "PositionAttribute": "",
        "LoginIdAttribute": "sAMAccountName",
        "SyncIntervalMinutes": 60,
        "SkipCertificateVerification": true,
        "QueryTimeout": 60,
        "MaxPageSize": 0,
        "LoginFieldName": "Active Directory Username",
        "LoginButtonColor": "#0000",
        "LoginButtonBorderColor": "#2389D7",
        "LoginButtonTextColor": "#2389D7"
    },

**Comment by amyblais** [comment]
Hi @Ouroboros1977, I'm continuing to research more information on this, but one thing I noticed is that "FirstNameAttribute" has a typo - "giveName" should be "givenName".

**Comment by Ouroboros1977** [comment]
Hi @amyblais 
I fixed the typo and restarted the service but I'm still seeing the same error.

**Comment by amyblais** [comment]
Email notifications are also enabled in the System Console?

**Comment by Ouroboros1977** [comment]
Yes they are

**Comment by amyblais** [comment]
Hi @Ouroboros1977, do you have any restrictions on email domains: https://docs.mattermost.com/administration/config-settings.html#restrict-account-creation-to-specified-email-domains?

**Comment by Ouroboros1977** [comment]
Yes we do, we have it restricted to the same domain as the users primary smtp address.

**Comment by amyblais** [comment]
Hi @Ouroboros1977,

I asked our developers about this but haven't received feedback yet. Can you help with more details on:

1. Any other log errors you're seeing?
2. Any specific reproduction steps?

**Comment by Ouroboros1977** [comment]
That is the only prevalent log that I see.
Unfortunately I don't know when it started so I'm not really sure how to reproduce it.  Best I can tell is it happened after we upgraded and it just stopped working.

**Comment by amyblais** [comment]
Hi @Ouroboros1977, would it sound good if you submit a ticket via our customer support system for further troubleshooting: https://mattermost.zendesk.com/hc/en-us/requests/new?

My colleague is more familiar with LDAP and he will most likely be able to resolve this issue quickly.

I apologize for any inconvenience!

**Comment by Ouroboros1977** [comment]
Will do thanks for your help

**Comment by amyblais** [comment]
Thank you!
