### ISSUE TITLE
Cursor leaves search dialogue when clicking the "gifs" tabs in the emoji popup

### ISSUE THREAD

**Issue by thejacer87** [mattermost/mattermost-server#9529]
#### Summary
Cursor leaves search dialogue when clicking the "gifs" tabs in the emoji popup

#### Steps to reproduce
Click the emoji popup icon. you will notice the cursor go to the search. click the gif tab. and the cursor leaves. requiring an (agonising :) ) extra click before typing to search gfycat

#### Expected behavior
cursor should stay in the search test box

#### Observed behavior (that appears unintentional) 

![image](https://user-images.githubusercontent.com/6412919/46378369-398c9d00-c650-11e8-88a0-11be2cc09433.png)

cursor disappears

![image](https://user-images.githubusercontent.com/6412919/46378358-2f6a9e80-c650-11e8-8291-401990e9872a.png)

#### Possible fixes
something is telling the cursor to move to the search box when clicking the emoji icon (i.e. if you cursor is in the default message textbox, it moves to the emoji search dialogue when opened), so just do that when the gif/emoji tabs are clicked

**Comment by amyblais** [comment]
Hi @thejacer87, thank you for reporting this.

I tested this on our [Community server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and wasn't able to reproduce.

Can you help with more details on your device, OS and Mattermost server version?

**Comment by amyblais** [comment]
Hi @thejacer87, would you be able to upgrade to the latest server version (v5.3) and see if it fixes the issue for you? You can test it out first on our [Community server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) if you'd like.

**Comment by thejacer87** [comment]
looks like you are correct. sorry for the false alarm

thanks
