### ISSUE TITLE
[Help Wanted] [MM-12365] Create CLI command "team rename"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9533]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12365)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `team rename` command in the CLI.

Allow renaming teams like in `channel rename` command

Example: `team rename myteam newteamname --display_name "My New Team Name`

It will need to add a new `RenameTeam` function in the `app` layer, in the `app/team.go` file. The function would be based on the `RenameChannel` function from the `app/channel.go` file.

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by NGTmeaty** [comment]
I'm working on this!

**Comment by jespino** [comment]
Awesome! Thanks @NGTmeaty

**Comment by grundleborg** [comment]
Hi @NGTmeaty  . Just wondering how you are getting on with this ticket? If you have any questions please do let us know here or on the pre-release server mentioned at the start of the ticket description - we'll be very happy to help out.
