### ISSUE TITLE
[Help Wanted] [MM-12360] Create CLI command "config get"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9534]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12360)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `config get` command in the CLI.

Allow seeing the value of a config setting. It must read the config/config.json file.

Example: `config get SqlSettings.DriverName`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by mukulrawat1986** [comment]
Hi, can I work on this issue?

**Comment by jespino** [comment]
@mukulrawat1986 Sure! If you have any doubt or you need any advice let me know. You can find me over here, or in https://pre-release.mattermost.com.

**Comment by mukulrawat1986** [comment]
Thanks. I am going through the developer workflow and will let you know if I have any doubts.
