### ISSUE TITLE
[Help Wanted] [MM-12361] Create CLI command "config set"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9535]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12361)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `config set` command in the CLI.

Allow seting the value of a config setting. It must write the config/config.json file.

Example: `config set SqlSettings.DriverName mysql`

Probably during the development of this command would be easier to remove the `--disableconfigwatch` from the `run-server` task in the `Makefile` (but that change mustn't be include in the final PR).

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by mukulrawat1986** [comment]
@jespino I have started working on the "config get" command, so can I work on the set and show command too?

**Comment by jespino** [comment]
@mukulrawat1986 sure! makes a lot of sense to pick them together, it's not a requirement, but makes sense :)
