### ISSUE TITLE
[Help Wanted] [MM-12362] Create CLI command "config show"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9536]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12362)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `config show` command in the CLI.

Allow seeing the entire config setting (in a pretty format), like for example:
```
ServiceSettings:
    SiteURL: "http://localhost:8065"
    WebsocketURL: ""
    ...
```

or:
```
ServiceSettings.SiteURL: "http://localhost:8065"
ServiceSettings.WebsocketURL: ""
...
```
The second one would be harder to read, but easier to use with `config get`and `config set` new commands (in other help wanted tickets). Maybe we can accept a --tree flag, to show the first one, and show the 2nd one as defult.

Example: `config show`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by mukulrawat1986** [comment]
Just commenting here cause I am working on this issue too. Thanks.
