### ISSUE TITLE
[Help Wanted] [MM-12459] [Bulk Export] Include User Notify Props in the Bulk Export

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9537]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12459)

This ticket forms part of the Bulk Export campaign. The bulk export feature (implementation in `app/export.go` and `app/export_converters.go` is intended to provide a CLI-based means to export the data in a Mattermost instance to a JSONL file. It is the inverse of the much more well developed Bulk Import feature, so a data file exported from the Bulk Export feature should be importable with the Bulk Import feature.

This ticket is to add the `NotifyProps` field on the `User` import data object to the exporter. The field is called `NotfyProps` on the `UserImportData` struct in `app/import_types.go` and you can see how it works from the `ImportUser` function in `app/import_functions.go`.

**Comment by VPashkov** [comment]
Hi!
I would like to work on this issue.
Can I grab it?

**Comment by jespino** [comment]
@VPashkov Sure! Let me (or @grundleborg) know if you have any question. You can find us here or in https://pre-release.mattermost.com.

**Comment by grundleborg** [comment]
Hi @VPashkov , just wondering how you are getting on with this ticket? Do let me know if you have any questions at all about it, or if you need any help.

**Comment by VPashkov** [comment]
Hi, @grundleborg.
I have a working solution, but I have a couple of questions.
I contact you in https://pre-release.mattermost.com tomorrow if you don't mind.

**Comment by grundleborg** [comment]
Yup, that's fine. my username there is `@george`.
