### ISSUE TITLE
[Help Wanted] [MM-12462] [Bulk Export] Include favourite channels in Bulk Export

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9539]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12462)

This ticket forms part of the Bulk Export campaign. The bulk export feature (implementation in `app/export.go` and `app/export_converters.go` is intended to provide a CLI-based means to export the data in a Mattermost instance to a JSONL file. It is the inverse of the much more well developed Bulk Import feature, so a data file exported from the Bulk Export feature should be importable with the Bulk Import feature.

This ticket is to include the favourite-indicator of channels for each user in the bulk export. The field in question is `Favorite` on the `UserChannelImportData` struct in `app/import_types.go`. You can see how the *import* side of the process is handled in the  `ImportUserChannels()` function in `app/import_functions.go`.

**Comment by jespino** [comment]
@gupsho Awesome! Let me (or @grundleborg) know if you need any kind of help. You can find us here or in https://pre-release.mattermost.com

**Comment by grundleborg** [comment]
Hi @gupsho  , just wondering how you are getting on with this ticket? Do let me know if you have any questions at all about it, or if you need any help.

**Comment by gupsho** [comment]
@grundleborg I wasnt able to work on it yet. Apologies for the delay. Will create PR in next couple days.
