### ISSUE TITLE
Include the Theme property on UserTeamMemberships in Bulk Export

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9541]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12460)

This ticket forms part of the Bulk Export campaign. The bulk export feature (implementation in `app/export.go` and `app/export_converters.go` is intended to provide a CLI-based means to export the data in a Mattermost instance to a JSONL file. It is the inverse of the much more well developed Bulk Import feature, so a data file exported from the Bulk Export feature should be importable with the Bulk Import feature.

This ticket is to populate the Theme selection of each user at the per-team level. The field to be populated is the `Theme` field on the `UserTeamImportData` object in `app/import_types.go`. You can see how it is imported in the  `ImportUserTeams()` function in `app/import_functions.go`.

**Comment by lannonbr** [comment]
I'm interested in tackling this issue.

**Comment by grundleborg** [comment]
Hi @lannonbr , that's great. If you need any help at all with getting started, or want to discuss ideas about the implementation, do feel free to ask here or on the Mattermost server linked at the start of this ticket. You can find me there with the name `@george`.

**Comment by waseem18** [comment]
@lannonbr Are you still working on this issue? If not I would love to take up this.

**Comment by lannonbr** [comment]
@waseem18 I've been working on some other stuff and I haven't gotten around to doing this, so feel free to work on it.

**Comment by waseem18** [comment]
Thanks for the prompt reply @lannonbr 
I'll start looking into this.

**Comment by waseem18** [comment]
Update : I'm looking into this issue and got stuck at a point and have posted a question on pre-release. Here's the perma-link : https://pre-release.mattermost.com/core/pl/ww98dcat838qucq4bioaudwfor

**Comment by grundleborg** [comment]
This is for the *per-team* theme setting, where users can have a different theme for each team. The other ticket should just be exporting the user's default (system-wide) theme preference.

**Comment by waseem18** [comment]
Update : I've started working on this issue and will have a PR in a day or two.

**Comment by hanzei** [comment]
@waseem18 How is your implementation doing? Can we help with something?

**Comment by waseem18** [comment]
@hanzei I completely missed this issue. I have some code for this in a branch.

I'll look into it.

**Comment by hollabigj** [comment]
Trying to import bulk data with user's theme code. Got error: BulkImport: JSON decode of line failed., json: cannot unmarshal array into Go struct field UserTeamImportData.theme of type string. It looks like array is not added to Golang script.

**Comment by jasonblais** [comment]
FYI @grundleborg & @hanzei on above note from @hollabigj

**Comment by hanzei** [comment]
@hollabigj Could you please open a new issue for this with step to reproduce?

**Comment by waseem18** [comment]
Resuming work on this. Will hopefully have a PR today.

**Comment by hanzei** [comment]
Hey @waseem18,

I want to gently remind you about this ticket. I know are currently working on the Jenkins Plugin, but I want to check if you are still planing to work on this ticket.

**Comment by waseem18** [comment]
@hanzei At this point I don't think I'll be able to work on this ticket anytime soon.

**Comment by hanzei** [comment]
Hey @waseem18,

Thanks for the head up. Let's make this available for the public again. And if you still want to pick this up after you are done with the jenkins plugin, just tell me!

**Comment by renilJoseph** [comment]
hi. i would like to work on this.

**Comment by hanzei** [comment]
Thanks for taking a shot @renilJoseph :+1:

**Comment by hanzei** [comment]
Just want to check if you have any questions @renilJoseph so far.

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by noxer** [comment]
I´ll try to implement this one.

**Comment by hanzei** [comment]
Thanks @noxer :+1:
