### ISSUE TITLE
[Help Wanted] [MM-12463] [Bulk Export] Include Custom Emoji in the Bulk Export

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9542]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12463)

This ticket forms part of the Bulk Export campaign. The bulk export feature (implementation in `app/export.go` and `app/export_converters.go` is intended to provide a CLI-based means to export the data in a Mattermost instance to a JSONL file. It is the inverse of the much more well developed Bulk Import feature, so a data file exported from the Bulk Export feature should be importable with the Bulk Import feature.

Currently, custom emoji are not included in the bulk export. This ticket is to add them to the bulk export in a way that produces data that can be imported by the handling of custom emoji in the bulk importer. You can see how this is done in `app/import_functions.go` in the function `ImportEmoji()`. The relevant struct is `EmojiImportData` in `app/import_types.go`. Look at how other object types are handled in the bulk exporter, and try and build this feature in a way that is analogous to that.

**Comment by waseem18** [comment]
@Hyaxia Are you still working on this issue?

**Comment by Hyaxia** [comment]
@waseem18 Sorry didnt find the time for it. You can take it.

**Comment by waseem18** [comment]
Thanks for the prompt reply. Will work on this.

**Comment by waseem18** [comment]
@esethna I tried bulk export and found custom emojis in the JSON file, both as posts and reactions.

**Comment by esethna** [comment]
Thanks @waseem18, adding @grundleborg to help check on that ^

**Comment by grundleborg** [comment]
Hi @waseem18 sorry for the slow reply on this. This ticket is about exporting the emoji themselves, rather than the reactions made with them, so populating `ImportEmojiData` structs with the contents of the `Emoji` table from the database, rather than the reactions on Posts/Replies. Does that make sense?

**Comment by waseem18** [comment]
Hi @grundleborg ,

I see I made a mistake, I'm working on issue related to exporting reactions of posts and the above comment containing JSON is supposed to go on that issue and I mistakenly put it up here.

**Comment by waseem18** [comment]
@grundleborg Should I add this feature under the same command i.e `export bulk --all-teams` or create a new flag for exporting emojis? Something like `export bulk --custom-emojis`.

I think adding a new flag would be better.

**Comment by waseem18** [comment]
@grundleborg Could you also please help with the above question?

Thanks

**Comment by grundleborg** [comment]
Hi @waseem18. Sorry for being slow. I think the new flag `--custom-emojis` makes sense. I would expect to be able to pass both `--all-teams` *and* `--custom-emojis` and get an export with both in too.

On the other question, looking at the source of the Bulk Import feature, the `image` field expects a path to an image file, so you'll need to export the file into a folder (e.g. `exported_emoji`) and set that to the path to it, e.g.: `exported_emoji/custom123.png`.

**Comment by waseem18** [comment]
Thanks for the reply @grundleborg 
Will look into this today

**Comment by waseem18** [comment]
So I'm gonna do this in this way,

Will get the absolute path of the file (assuming `demo.json`) to which the data will be exported to. At this file location will create a folder named `exported_emoji` to where I'll copy the images from `data/emoji<ImageID>`. And the emoji content in `demo.json` will reference images from the newly created folder `exported_emoji`.

Made some progress with this approach. Will put a PR tomorrow. 😴

**Comment by grundleborg** [comment]
I think this makes sense.
