### ISSUE TITLE
Creating user through GitLab sign on fails - password length ?

### ISSUE THREAD

**Issue by consideRatio** [mattermost/mattermost-server#9548]
The [mattermost documentation](https://docs.mattermost.com/administration/config-settings.html#password) describes that the team edition now ships with a minimum password length.

Now, when I try to create an account on my deployment through GitLab as authentication mechanism, I fail like this:

![create-account-gitlab-auth](https://user-images.githubusercontent.com/3837114/46422511-d6286b00-c734-11e8-9607-79e27b47ec69.gif)

It doesn't make much sense to expect a password, right? Anyhow, I tried to work around this by configuring the mattermost server to relax this requirement, I get the following error in the mattermost-server logs:

```sh
{"level":"info","msg":"Server stopped"}
{"level":"error","msg":"Config.IsValid: Minimum password length must be a whole number greater than or equal to 5 and less than or equal to 64., "}
Error: Config.IsValid: Minimum password length must be a whole number greater than or equal to 5 and less than or equal to 64.,
```

PS: I have deployed mattermost using the [mattermost-team-edition Helm chart](https://github.com/helm/charts/tree/master/stable/mattermost-team-edition), of the version `1.1.2`.

**Comment by amyblais** [comment]
Hi @consideRatio, thank you for reaching out.

What is your "Minimum Password Length" setting currently set to?

**Comment by consideRatio** [comment]
mattermost -> gitlab - > azure ad

**Comment by consideRatio** [comment]
It worked, as long as I removed the openid part.
