### ISSUE TITLE
Wrong German translation in password reset dialog

### ISSUE THREAD

**Issue by dannykorpan** [mattermost/mattermost-server#9549]
#### Summary
Wrong german translation within the password reset dialog.

#### Steps to reproduce
Reset your password, receive the password reset email, click on the link in the email, enter a less secure password and you will receive the attached error text, instead a correct translation of mode.user.is_valid.pwd_lowercase_uppercase_number_symbol.app_error

![2018-10-03 18_35_23-mattermost](https://user-images.githubusercontent.com/8004507/46425579-53a3a980-c73c-11e8-9d02-ec399ad19606.jpg)

#### Expected behavior
I think a correct translation in mattermost-server/i18n/de.json is necessary
mode.user.is_valid.pwd_lowercase_uppercase_number_symbol.app_error

#### Possible fixes
mattermost-server/i18n/de.json

**Comment by amyblais** [comment]
Hi @dannykorpan, thank you for reporting this.

What Mattermost server version are you using?

**Comment by dannykorpan** [comment]
5.3.1

**Comment by amyblais** [comment]
Thank you, I'll forward this feedback to our translators.

**Comment by jespino** [comment]
Is a problem with the translation extraction tool and dynamically generated string. I going to fix that in the extraction tool.
