### ISSUE TITLE
[Help Wanted] [MM-12368] Create CLI command "webhook create-incomming"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9560]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12368)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `webhook create-incomming` command in the CLI.

Allow creating incomming webhooks.

Example: `webhook create-incomming myteam --title MyIncomminWebhook --description "My Incommin Webhook Description" --channel mychannel --lock-to-channel --icon http://localhost:8000/my-slash-handler-bot-icon.png`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by amogozov** [comment]
Hey @esethna @jespino ! I would like to brush up my go skills and try this issue

**Comment by amyblais** [comment]
Awesome! Let us know if you have any questions.
