### ISSUE TITLE
[Help Wanted] [MM-12374] Create CLI command "webhook move"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9561]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12374)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `webhook move` command in the CLI.

Allow moving webhooks from one team to another.

Example: `webhook move newteam oldteam:w16zb5tu3n1zkqo18goqry1je`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by shovanmaity** [comment]
Hi ! I'd like to help on this issue !

**Comment by jespino** [comment]
Awesome @shovanmaity! Let me know if you need anything, you can find me here or in https://pre-release.mattermost.com
