### ISSUE TITLE
[Help Wanted] [MM-12375] Create CLI command "webhook show"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9562]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12375)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `webhook show` command in the CLI.

Allow seeing the webhook detailed information.

Example: `webhook show w16zb5tu3n1zkqo18goqry1je`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by lucchmielowski** [comment]
Hi ! I'd like to help on this issue ! :smiley:

**Comment by jespino** [comment]
Awesome!, Let me know if you need any help. You can find me here and in https://pre-release.mattermost.com

**Comment by lucchmielowski** [comment]
Hi @grundleborg ! Sorry i did not give a sign of life earlier :disappointed: ... I lacked time in the last weeks but I'll create the PR this week to complete this task ! :smiley:

**Comment by grundleborg** [comment]
No worries @lucchmielowski . Looking forward to it :)

**Comment by palash25** [comment]
Hi there, I would like to take this up if the original assignee is not working on this anymore.

**Comment by lucchmielowski** [comment]
Hi there @palash25 / admins ! Yeah i'm lacking time to work on this task right now :disappointed: so feel free to reassign it please :smiley:  !

**Comment by hanzei** [comment]
Thanks @palash25! If you have any questions, lets us know.

**Comment by palash25** [comment]
Just one questions @hanzei  the `webhook show` command will use these two functions `GetIncomingWebhook` and `GetOutgoingWebhook` in `app/webhook.go` right ?

**Comment by hanzei** [comment]
That is correct

**Comment by dv29** [comment]
I'd like to take this up, just started with setting up the env

**Comment by hanzei** [comment]
@dv2 Great! 
Feel free to PM me on the [Mattermost Community Server](https://community.mattermost.com) if you needed help setting up the dev environment. Or if you have other questions. :wink:
