### ISSUE TITLE
[Help Wanted] [MM-12536] Migrate to idiomatic error handling the file `app/user_agent.go` in the mattermost-server

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9575]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12536)

**Comment by mukulrawat1986** [comment]
I would like to work on this.
