### ISSUE TITLE
Panic when modifying the config file and persisting change by using app.PersistConfig()

### ISSUE THREAD

**Issue by mukulrawat1986** [mattermost/mattermost-server#9580]
So I am working on the issue MM-12361 which involves creating the cli command `config set` which will update the value of a config setting. I have been able to build this command by using a custom function in `app.UpdateConfig()`. To persist the changes made to the config file I use the function `app.PersistConfig`. 

The writes made to the file do persist but it always panics. By doing some debugging, It seems to be a problem in the goroutine started in the function `NewConfigWatcher()` in `utils/config.go`

If I use the function `app.DisableConfigWatch()` and disable the `config watcher` everything works perfectly without any panic error.

The panic output is 
```
mattermost config set ServiceSettings.ReadTimeout 150
Debug UpdateConfig:  150
Debug UpdateMap:  150
Debug UpdateMap:  150
Debug mapStructure.Decode:  150
Debug mapStructure.Decode:  150
Debug UpdateConfig:  150
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a9b73f]

goroutine 3148 [running]:
github.com/mattermost/mattermost-server/app.New.func6(0xc002a43100, 0xc002a3ed80)
	/Users/manu/go/src/github.com/mattermost/mattermost-server/app/app.go:226 +0x3f
github.com/mattermost/mattermost-server/app.(*App).InvokeConfigListeners(0xc000110580, 0xc002a43100, 0xc002a3ed80)
	/Users/manu/go/src/github.com/mattermost/mattermost-server/app/config.go:138 +0x99
github.com/mattermost/mattermost-server/app.(*App).LoadConfig(0xc000110580, 0xc001ef2960, 0x4d, 0xc001e90d80)
	/Users/manu/go/src/github.com/mattermost/mattermost-server/app/config.go:72 +0x1a2
github.com/mattermost/mattermost-server/app.(*App).ReloadConfig(0xc000110580, 0xc00179a4e8)
	/Users/manu/go/src/github.com/mattermost/mattermost-server/app/config.go:78 +0x48
github.com/mattermost/mattermost-server/app.(*App).EnableConfigWatch.func1()
	/Users/manu/go/src/github.com/mattermost/mattermost-server/app/config.go:106 +0x2a
github.com/mattermost/mattermost-server/utils.NewConfigWatcher.func1(0xc0018e9e60, 0xc001751e60, 0xc001ef2960, 0x4d, 0xc001ef2960, 0x4d, 0xc001a5dbd0)
	/Users/manu/go/src/github.com/mattermost/mattermost-server/utils/config.go:214 +0x5ad
created by github.com/mattermost/mattermost-server/utils.NewConfigWatcher
	/Users/manu/go/src/github.com/mattermost/mattermost-server/utils/config.go:201 +0x19c
```

**Comment by amyblais** [comment]
Hi @mukulrawat1986, sorry for the delay, I was off yesterday for Thanksgiving.

@cpanato / @jespino can you help take a look at this? ^ (Pinging Dev on rotation for technical support and Dev who owns the Jira ticket that the reporter mentioned https://mattermost.atlassian.net/browse/MM-12361).

**Comment by jespino** [comment]
@mukulrawat1986 can you confirm if this was a problem with the usage of the App layer API, or it is something to fix in the application?

**Comment by mukulrawat1986** [comment]
I am not very sure about it, its probably to do with reloading the config file while the watcher is enabled. I looked up the file `app/admin.go`, and in the file inside the function `SaveConfig` I can see them first disabling the watchers, then reloading the config and then enabling the watchers. I have followed the same patter in my code and it works perfectly now.

**Comment by amyblais** [comment]
Sounds that this issue was resolved? Let me know if I understood wrong.

**Comment by mukulrawat1986** [comment]
@amyblais Well, the command I was working on works after making the changes, so you can mark this issue as resolved, though it would be great if someone could explain why it keeps on panicking if we reload the config while the watcher is enabled.

**Comment by amyblais** [comment]
Pinging @jespino to take a look at the question above ^

I'll close this Issue for now as the main problem is resolved,
