### ISSUE TITLE
[Help Wanted] [MM-12605] Migrate to idiomatic error handling in the file `app/preference.go` in the mattermost-server repo.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9583]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12605)

**Comment by waseem18** [comment]
I'd like to take up this.

**Comment by hanzei** [comment]
I would like to work on this.

**Comment by grundleborg** [comment]
That's great @hanzei . You can ping me on pre-release if you have any questions :)
