### ISSUE TITLE
Users can kick other users off a channel

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [mattermost/mattermost-server#9588]
The default settings in the configuration file for limiting the ability to delete a user from the channel by another normal user do not work.
         "RestrictPublicChannelDeletion": "system_admin",
         "RestrictPrivateChannelDeletion": "system_admin",
         "RestrictPublicChannelManagement": "system_admin",
         "RestrictPrivateChannelManagement": "system_admin",

**Comment by Pomazan-Bogdan** [comment]
https://forum.mattermost.org/t/users-can-kick-other-users-off-a-channel/4773

**Comment by amyblais** [comment]
Hi @Pomazan-Bogdan, thank you for reaching out.

Can you help confirm if you're on Enterprise Edition version?

**Comment by Pomazan-Bogdan** [comment]
> Can you help confirm if you're on Enterprise Edition version?
No

**Comment by amyblais** [comment]
Thanks, these settings are available in Enterprise Edition, so this is why they are not working on your server. Closing this Issue as this is not a bug,

**Comment by amyblais** [comment]
@Pomazan-Bogdan The settings are only available in Enterprise Edition both via config and System Console.
