### ISSUE TITLE
Create CLI command "config reset"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9596]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12623)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `config reset` command in the CLI.

Allow reset the value of a config setting to default value. It must write the config/config.json file. If the user doesn't pass the setting or pass a setting section, it will ask for confirmation and reset all the values (or all the values in the section).

Example: `config reset SqlSettings.DriverName`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by mukulrawat1986** [comment]
I would like to work on this.

**Comment by jespino** [comment]
Awesome :)

**Comment by grundleborg** [comment]
Hey @mukulrawat1986 - just wondering if you are still working on this ticket?

**Comment by mukulrawat1986** [comment]
@grundleborg I am. Just a bit under weather, I will make a PR by the weekend. Or do you want me to hurry it up?

**Comment by grundleborg** [comment]
No need to hurry! Take your time. I was just checking up on this ticket, that's all. Hope you feel better soon :)

**Comment by hanzei** [comment]
Hey @mukulrawat1986, How is your work on this ticket doing? Can we help with something?

**Comment by mukulrawat1986** [comment]
@hanzei  Hey, I am just busy with some personal things, I have done half of this already. I will try and push it soon.

**Comment by hanzei** [comment]
Thanks for the heads up @mukulrawat1986. No need to hurry, I just wanted to check if you are still working on this and if you need help. Looking forward to your PR!

**Comment by hanzei** [comment]
Hey @mukulrawat1986,

Just want to check out, if you are still working on this one.

**Comment by joshuabezaleel** [comment]
Hey @hanzei , if it is okay with you I would like to ask some questions just to wrap some understanding.
1. What is the default value or where can we get the value of the license [here](https://github.com/mattermost/mattermost-server/blob/ee9395f1b6a70cc9d34bf116de38da4b70153158/utils/config.go#L501)?

2. Since I can not find a config.json file at the config directory, do we create a new file named config.json or we overwrite the [default.json file](https://github.com/mattermost/mattermost-server/blob/master/config/default.json)?

Thank you very much.
Have a good day.

**Comment by hanzei** [comment]
Hey @joshuabezaleel,

1. The default values can be found in [`model/config.go`](https://github.com/mattermost/mattermost-server/blob/master/model/config.go).

2. I'm not sure I understand your question. This CLI commands is used to changes values in `config.json`.

**Comment by joshuabezaleel** [comment]
Hey @hanzei ,
Your previous answer is so helpful. Thank you.
I am really sorry if I will still ask more questions.

1.  Do you have any recommendation on how Mattermost team implement reading and writing to json file? Can I use the config set command? 
2. Do you have any recommendation on how Mattermost team implement the part of asking confirmation to the user?
3. How many arguments that a user can input to be passed for the setting/setting section? Can a user input more than one argument?

Thank you very much. Have a good day.

**Comment by hanzei** [comment]
1. Take a look at the `ReadConfig()` method in [`utils/config.go`](https://github.com/mattermost/mattermost-server/blob/master/utils/config.go).

**Comment by hanzei** [comment]
1. Take a look at the `ReadConfig()` method in [`utils/config.go`](https://github.com/mattermost/mattermost-server/blob/master/utils/config.go).
2. Are you talking about CLI? Then take at look at https://github.com/mattermost/mattermost-server/blob/master/cmd/mattermost/commands/channel.go#L318-L326
2. I think that would make sense.

Feel free to ask more questions :wink:

**Comment by joshuabezaleel** [comment]
Those two are what I am looking for, thank you @hanzei !
For the number of the arguments, do you think that there is a maximum number of it that can be passed by the user?

If it is okay, I would like to give a shot on this.

**Comment by hanzei** [comment]
I don't think there has to be a maximum @joshuabezaleel.

I think I didn't made clear that someone is working on this issue. Sorry.

**Comment by joshuabezaleel** [comment]
@hanzei it's okay, you haven't put the "up for grabs" label yet but I asked questions since the gap is too long. Thank you very much for answering the questions! :)

**Comment by joshuabezaleel** [comment]
Hi @hanzei , since @mukulrawat1986 is not giving any update since Monday, I tried to take a shot on this. 

I am sorry for any mistakes since this is my first PR here. Looking forward to your review.
Thank you very much.

**Comment by jaydeland** [comment]
I would like to look into this issue

**Comment by hanzei** [comment]
Hey @jaydeland,

Thanks for you interest in the project. We mark available ticket with the "Up for Grabs" label. In this case @joshuabezaleel is already working on this. You can find a list of the available tickets at https://github.com/mattermost/mattermost-server/labels/Up%20For%20Grabs

**Comment by jaydeland** [comment]
@hanzei - thank you for the details
