### ISSUE TITLE
Improve autocomplete highlighting when using mouse and keyboard together

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9598]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11888)

There are a few things around how autocomplete works today that could be improved upon relating to the highlighting effect.

Observed: If you type `~` or `@` in a message input box and use your mouse to hover over options, the highlight on the first suggestion remains in place (-092.png) and you get a second highlight where the mouse is hovering.

Expected: Highlight follows the mouse. No double highlight. (similar to how emoji picker works, vid attached in JIRA)

_______

Use your up/down keys on the keyboard to move the highlight, then hover your mouse over the suggestions.

Observed: Double highlight is shown where the mouse is hovering and for the keyboard arrow keys

Expect: If the mouse moves over the autocomplete, highlight follows the mouse as priority (similar to how emoji picker works, vid attached in JIRA)

________

When looking at these issues, take into account interactive menus on message attachments (https://mattermost.atlassian.net/browse/MM-8477) as well as all other autocomplete menus (e.g. screenshot-1.png)

**Comment by S4KH** [comment]
Will work on this. Is the component `suggestion_list.jsx`?

**Comment by amyblais** [comment]
Thank you @S4KH! @esethna can you help with the question or ping a dev ^

**Comment by S4KH** [comment]
The problem here is that the mouse hover background is done by CSS and keyboard selection is handled by the React. I think we need to remove CSS class and do it with onMouseOver like emojiPicker.

**Comment by jasonblais** [comment]
Thanks for the follow-up! Have asked @asaadmahmood who might be able to best help with this one.

**Comment by S4KH** [comment]
The class `--selected` is already there, wondering if we remove the hover class would there be any functionality missing issues?

**Comment by asaadmahmood** [comment]
We can remove the hover, and apply the `--selected` class on the item that is being hovered. Once you make this change, we can test and see if that creates any issues.

**Comment by larkox** [comment]
May I take this one?

**Comment by jasonblais** [comment]
@larkox Definitely, thanks for your interest! 👍
