### ISSUE TITLE
Add plugin API for GetTeamsForUser method

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#9607]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

The method `GetTeamsForUser(userId, etag string) ([]*Team, *Response)` is available in `model/client4.go`, the Go REST API driver for Mattermost, but does not have an equivalent in the plugin API.

Not having this method in the plugin API limits what plugins can do. Hence, we would like to add an equivalent plugin API for it.

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/. Most of these methods should have fairly simple equivalents in the `app` package, making them trivial to implement.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

----

This ticket is part of a larger campaign for adding plugin API methods. See here: https://github.com/mattermost/mattermost-server/issues/9458

**Comment by chclaus** [comment]
Hej hej, I will take care of it

**Comment by chclaus** [comment]
Hm okay.

Wanted to start right now but I think @czertbytes did it already.

**Comment by jasonblais** [comment]
@chclaus Sorry about that, I asked the contributor help add a note in the help wanted ticket as well so others know if it's been worked on.

If you're still interested on the plugin API methods, there are two more tickets open
 - https://github.com/mattermost/mattermost-server/issues/9634
 - https://github.com/mattermost/mattermost-server/issues/9640

If neither of them are of interest, let me know as there are a bunch of other help wanted tickets for plugin API we plan to add (some of them listed below). So I can create a few more for you to choose from. :)

![image](https://user-images.githubusercontent.com/13119842/46910723-6c1f7b00-cf17-11e8-800b-5848391a388e.png)

**Comment by hanzei** [comment]
Hey @jasonblais, I would like to work on the API methods related to plugins like `EnablePlugins()` or `GetPlugins()`. Would you create some tickets for them?

**Comment by hanzei** [comment]
@jasonblais ping ^

**Comment by jasonblais** [comment]
@hanzei Sorry for missing the ping earlier.

Certainly! There are 7 plugin API methods total - are you interested working on the two specifically (`EnablePlugins()` and `GetPlugins()`) or others as well?

**Comment by hanzei** [comment]
I would like to work on:

- GetPlugins()
- RemovePlugin()
- GetPluginStatuses()
- EnablePlugin()
- DisablePlugin()

**Comment by jasonblais** [comment]
@hanzei Awesome! Just created a help wanted ticket for it https://github.com/mattermost/mattermost-server/issues/9740
