### ISSUE TITLE
[Help Wanted] Add plugin API for UpdateUserActive method

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#9610]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

The method `UpdateUserActive(userId string, active bool) (bool, *Response)` is available in `model/client4.go`, the Go REST API driver for Mattermost, but does not have an equivalent in the plugin API.

Not having this method in the plugin API limits what plugins can do. Hence, we would like to add an equivalent plugin API for it.

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/. Most of these methods should have fairly simple equivalents in the `app` package, making them trivial to implement.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

----

This ticket is part of a larger campaign for adding plugin API methods. See here: https://github.com/mattermost/mattermost-server/issues/9458

**Comment by akhilanandbv003** [comment]
I would like to work on this.

**Comment by amyblais** [comment]
Thank you @akhilanandbv003!

**Comment by jasonblais** [comment]
@akhilanandbv003 Do you have any questions on this ticket? Anything we can help with?

**Comment by akhilanandbv003** [comment]
I would appreciate your help if you could point me to some documentation on running tests locally. This is my first open source contribution. Sorry about the delay in putting the PR.

**Comment by jasonblais** [comment]
Thanks @akhilanandbv003 for the follow up! Good question, I've asked our engineering team to help with this.

**Comment by akhilanandbv003** [comment]
Hey @jasonblais, thanks for the follow up. I have kind of figured out my way around running tests locally. Regarding the UpdateUserActive method. It should just update the user status to active(STATUS_ONLINE) right.

**Comment by jwilander** [comment]
Hi @akhilanandbv003 this actually isn't related to statuses. This is for setting a user to active or inactive, which is essentially soft deleting a user. An inactive user cannot login or access the system. Here is the REST API handler for this https://github.com/mattermost/mattermost-server/blob/master/api4/user.go#L806

**Comment by hanzei** [comment]
@akhilanandbv003 Do you have any more questions? Let me know if I can help with anything.
