### ISSUE TITLE
RFC: URLs are awfully long

### ISSUE THREAD

**Issue by jelmd** [mattermost/mattermost-server#9613]
#### Summary
Invite Mails (and possibly others) contain awfully long URLs, which makes them unusable in text a.k.a. terminal based mail readers (yes, power users still use them a lot). 

#### Steps to reproduce
Invite yourself and read the mail within an e.g. 80x25 terminal [with mutt].

#### Expected behavior
All URLs sent via e-mail should be short (i.e. not longer than 80 characters) and human-readable (and thus threat detectable).

#### Observed behavior (that appears unintentional) 
Text based readers wrap long lines and indicate this by adding a special character at the start or end of a line and thus links are broken. Neither the terminal gets it right nor is it easy to copy and paste the link into a browser (see attached screenshot)

#### Possible fixes
MM uses already a database. So all information attached to the URLs (which might be held a a security problem as well) should be stored in the DB using e.g. an UUID as unique key and the user should just get an URL like http://mmserv.do.main/signup_user_complete/${UUID} - no parameters or any special character, which needs en/decoding! This leaves 18 characters for the hostname w/o the need to wrap. But even if it is longer, wrapping occures only once (assuming, no-one uses FQDNs with > = 100 characters) and is easy to fix, by removing the single separator (`+` e.g. in mutt). 

Using UUIDs should be safe and sufficient (instead of using arbitrary long "doesn't make sense keys"). Old/unused information can be cleaned up on a certain interval or when the next "invite" related action gets triggered.

**Comment by jelmd** [comment]
![mm](https://user-images.githubusercontent.com/4813414/46832822-5ab76100-cda7-11e8-92cb-c07b162af89a.gif)

**Comment by amyblais** [comment]
Hi @jelmd! Thank you for reporting this.

I'll ask our developers tomorrow if we currently support this and I'll file a bug ticket if there is a bug here.

**Comment by amyblais** [comment]
Hi @jelmd,

A developer responded with this feedback: URL-shortening isn't something we currently support, and it might also not be beneficial. The resulting URL may be shorter, but it's not human-readable: in fact, hiding the real URL obscures any potential security issue (e.g. redirect to malicious-website.com).

Does this help?

You are also welcome to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) for further discussion and voting.

**Comment by lieut-data** [comment]
@jelmd, not sure about your setup (and I don't use `mutt` personally), but at least in terminals like iTerm for OSX, even urls that wrap can be clicked on and copied. Maybe you could investigate if such an option exists for your terminal?

**Comment by jelmd** [comment]
@amyblais The developer probably didn't get it right. This is not at all about URL shorteners - I hate them. This is about using URLs, which make sense and are readable by the user. E.g. I consider the following neither readable nor short: `+http://mm.your.doom.ain/signup_user_complete/?d=%7B%22display_name%22%3A%22Test+Te+am%22%2C%22email%22%3A%22testus%2Bmm%40another.doom.ain%22%2C%22name%22%3A%22test+-team%22%7Dt=mra1yk54edtbdqb797cbbzs346bgahi3znpn4u6wxkphdpjb98niazxm97ntze6k+`.

However, `http://mm.your.doom.ain/signup_user_complete/255044462d312e330a25e2e3cfd30d0a` would be something readable and reasonable short. There is no reason at all, to transport all the personal data back and forth.

**Comment by jelmd** [comment]
@lieut-data The problem is not the terminal per se, but the application - here mail client - running in a terminal. On Linux/Solaris/*x a.k.a gnome-terminals you can copy and paste URLs into it as well, when you just have a shell running or an editor, or anything else, where the terminal has the control, and click on it - xdg-open will be called with the URL - would work as well. But start mutt in an iTerm, and you'll see the same clutter, as shown above in the attached image.

Last but not least I forgot: Long URLs with lot of parameters are also error prone! E.g. all our plussed users can't finish creating an account, because mattermost thinks, the link is not valid ...

**Comment by lieut-data** [comment]
Thanks for the clarification -- I stumbled across a lot of similar reports online about mutt's limitations here.

The extra parameters being passed are currently required by the webapp to preflight information about the team to which the user is being invited. I agree we could change things here to query this information on demand given the token instead.

This probably won't make it onto our near-term roadmap, but we're always open to pull requests if you're inclined to try tackling this one yourself! Feel free to ping us here or on pre-release.mattermost.com if you wanted to go down that path and need some help getting started :)

**Comment by jelmd** [comment]
Ok, thanx. Unfortunately I haven't had time to get some `go` foo =8-( So probably can't provide a PR in the near future =8-( ...

**Comment by amyblais** [comment]
Hi @jelmd, let me know if you've had a chance to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) for further discussion and voting!

**Comment by amyblais** [comment]
Hi @jelmd, we haven't received an update for a while so I'll close this Issue for now. Thank you for considering adding this to the feature request forum,
