### ISSUE TITLE
Bug: The signup link does not appear to be valid

### ISSUE THREAD

**Issue by jelmd** [mattermost/mattermost-server#9614]
#### Summary
Link checking is probably buggy, so that certain users are not able to finish account creation.

#### Steps to reproduce
Invite a user with a [plussed e-mail address](https://www.cs.rutgers.edu/~watrous/plus-signs-in-email-addresses.html) .

#### Expected behavior
Creating an account should work.

#### Observed behavior (that appears unintentional)
Creating an account fails for plussed users (e.g. foo+bar@do.main).

#### Possible fixes
E-Mail address parsing should follow the rules described in RFCs. Can be simpified, but excluding '+' is a major design flaw. Sendmail supports it since version 8.7 (released 1995/09/16) and all notable mail servers (at least within the {L,U}*x world) support it. It is heavily used by our users!

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @jelmd!

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jelmd** [comment]
IIRC, I saw somewhere a test, which includes plussed e-mail addresses. So I think, this is really a bug and not a new feature.

**Comment by amyblais** [comment]
Hi @jelmd, what server version are you currently on?

**Comment by jelmd** [comment]
5.3.1-linux-amd64

**Comment by amyblais** [comment]
Thanks @jelmd, would you be able to do a quick test on our [Community server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) - if you see the same issue there I can open a bug ticket and we'll discuss it as a team. Let me know any questions.

**Comment by jelmd** [comment]
@amyblais seems to work - account created :)

**Comment by amyblais** [comment]
Hi @jelmd, following up on whether it looks like upgrading to v5.4 might fix the problem?

**Comment by amyblais** [comment]
Hi @jelmd, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by jelmd** [comment]
Just tested latest LTS (5.37.2) and it is still not fixed.
![mm-email-settings](https://user-images.githubusercontent.com/4813414/137417014-4ff13555-e61c-4f2f-ac2f-22ba394847f1.gif)
![mm-email-signin](https://user-images.githubusercontent.com/4813414/137417021-bdf2cebe-a193-425f-bf19-17cd81376967.gif)

**Comment by jelmd** [comment]
Yes, this works as expected, but this is not an option for several reasons.
