### ISSUE TITLE
[Help Wanted] Add plugin API for GetFile method

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#9621]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

The method `GetFile(fileId string) ([]byte, *Response)` is available in `model/client4.go`, the Go REST API driver for Mattermost, but does not have an equivalent in the plugin API.

Not having this method in the plugin API limits what plugins can do. Hence, we would like to add an equivalent plugin API for it.

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/. Most of these methods should have fairly simple equivalents in the `app` package, making them trivial to implement.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

----

This ticket is part of a larger campaign for adding plugin API methods. See here: https://github.com/mattermost/mattermost-server/issues/9458

**Comment by vaithak** [comment]
I would like to work on this.

**Comment by jasonblais** [comment]
@vaithak Any questions on this ticket? Let us know if we can help with anything :)

**Comment by jasonblais** [comment]
@vaithak Good question - I've posted it to our public Developer Toolkit channel to our plugin developers here https://pre-release.mattermost.com/core/pl/r74goy6kciykbjh8kio3nznkpa

**Comment by jasonblais** [comment]
Hey @vaithak - it should be similiar to the API call here: https://github.com/mattermost/mattermost-server/blob/master/api4/file.go#L146

**Comment by cpanato** [comment]
you can refactor the code into the app and reuse in both api/plugin calls

**Comment by vaithak** [comment]
@jasonblais @cpanato  Should the signature of API call be that in api4/file.go or the one mentioned in the issue description above ?

**Comment by cpanato** [comment]
@vaithak you define the new api for the plugin here: https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go and implement here https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

you can read more in this doc https://developers.mattermost.com/contribute/server/plugins/

**Comment by vaithak** [comment]
@cpanato I am asking that the api that I have to define in plugin/api.go, should that API's signature be similar to that written in api4/file.go or the one mentioned in issue description above ?

**Comment by cpanato** [comment]
@vaithak can be
`GetFile(fileId string) ([]byte, *model.AppError)`

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-server/pull/9820.

Thanks you very much @vaithak for the contribution! :tada:
