### ISSUE TITLE
Get a channel by name API Call not working as expected

### ISSUE THREAD

**Issue by fincha** [mattermost/mattermost-server#9648]
#### Summary
I am not able to retreive the deleted channel info. Server Version 5.1

#### Steps to reproduce
I have created a a channel via api, its a private channel. I have "deleted" channel via api. Channel was deleted, and I also not able to create a channel with the same name, so the channel is still in DB and is only marked as deleted.

I am trying to restore the channel, for this I first need the channel ID, so I do the call get channel by name, gut what ever I do, I am getting 

`{
  "id": "store.sql_channel.get_by_name.missing.app_error",
  "message": "Channel does not exist",
  "detailed_error": "",
  "request_id": "8rzkrt1ktiyqxqjjosw4rzux5y",
  "status_code": 404
}`

I have also noticed, the the client I am getting generated form the latest version of yaml file 4.0.0 does not support query params to include deleted channels. Any way, I have extended this single option, so I do send a query like this

/api/v4/teams/arxrae5xutncuyez416qn5gf7a/channels/name/1223?include_deleted=true

#### Expected behavior
I expect the generated client to contain the option for deleted channels
I expect the api call to return the deleted channel info

#### Possible fixes
set the include_deleted=true by default or add this option to swagger yaml
what ever is to do in the golang code :)

**Comment by amyblais** [comment]
Hi @fincha,

What Mattermost server version are you on?

**Comment by fincha** [comment]
@amyblais I have installed the 5.4.1 now

`{
    "timestamp": "2018-10-18T08:13:47.054+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "java.lang.NumberFormatException: Expected an int but was 1539850468788 at line 1 column 113 path $.delete_at",
    "path": "/project/12345/restore"
}`

**Comment by SmartHoneybee** [comment]
Hi,

> `java.lang.NumberFormatException`

that's not Mattermost complaining, right?

[`MAX_VALUE` for Integer is `2^(31)-1 = 2 147 483 647`](https://docs.oracle.com/javase/9/docs/api/java/lang/Integer.html#MAX_VALUE) and 1539850468788 is larger than that. (I'd guess it's represents a [timestamp](https://en.wikipedia.org/wiki/Unix_time).)

Regards,
Bee

**Comment by fincha** [comment]
More or less, its autoamtic generated client

> java.lang.NumberFormatException: Expected an int but was 1539850468788 at line 1 column 113 path $.delete_at
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1172) ~[gson-2.8.2.jar!/:na]
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:225) ~[gson-2.8.2.jar!/:na]
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217) ~[gson-2.8.2.jar!/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.2.jar!/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.2.jar!/:na]
	at com.google.gson.Gson.fromJson(Gson.java:888) ~[gson-2.8.2.jar!/:na]
	at com.google.gson.Gson.fromJson(Gson.java:853) ~[gson-2.8.2.jar!/:na]
	at com.google.gson.Gson.fromJson(Gson.java:802) ~[gson-2.8.2.jar!/:na]
	at mattermost.client.handler.JSON.deserialize(JSON.java:133) ~[classes!/:2.0.0]
	at mattermost.client.handler.ApiClient.deserialize(ApiClient.java:711) ~[classes!/:2.0.0]
	at mattermost.client.handler.ApiClient.handleResponse(ApiClient.java:914) ~[classes!/:2.0.0]

**Comment by SmartHoneybee** [comment]
Hi,

> the yaml file

This one: https://api.mattermost.com/static/mattermost-openapi-v4.yaml ?
No match for `long` - which in [swagger](https://docs.swagger.io/spec.html) is the common name for type `integer` with format `int64`. Looking for `delete_at` above file yield:
```
$ grep -nA3 delete_at: mattermost-openapi-v4.yaml
9041:      delete_at:
9042-        description: The time in milliseconds a user was deleted
9043-        type: integer
9044-        format: int64
--
9090:      delete_at:
9091-        description: The time in milliseconds a team was deleted
9092-        type: integer
9093-        format: int64
--
9140:      delete_at:
9141-        description: The time in milliseconds a channel was deleted
9142-        type: integer
9143-        format: int64
--
9222:      delete_at:
9223-        description: The time in milliseconds a post was deleted
9224-        type: integer
9225-        format: int64
--
9386:      delete_at:
9387-        description: The time in milliseconds a file was deleted
9388-        type: integer
9389-        format: int64
--
9489:      delete_at:
9490-        description: The time in milliseconds a incoming webhook was deleted
9491-        type: integer
9492-        format: int64
--
9517:      delete_at:
9518-        description: The time in milliseconds a outgoing webhook was deleted
9519-        type: integer
9520-        format: int64
--
9591:      delete_at:
9592-        description: The time in milliseconds the emoji was deleted
9593-        type: integer
9594-        format: int64
--
11211:      delete_at:
11212-        type: integer
11213-        format: int64
11214-        description: The time at which the scheme was deleted.
```

So, not sure what you're talking about.
Care to provide steps to generate that client / reproduce your issue?

Regards,
Bee

**Comment by fincha** [comment]
Hi @SmartHoneybee 

this is my yaml https://pastebin.com/b1uXWKHr

> delete_at:
        description: The time at which the emoji was deleted.
        type: long

before that, I hat 2 deleted_at as integer, all others where "long"

**Comment by amyblais** [comment]
Hi @fincha , we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
