### ISSUE TITLE
MPNS typos: notifications called "notificaitons"

### ISSUE THREAD

**Issue by uusijani** [mattermost/mattermost-server#9660]
#### Summary
The push proxy codebase refers to notifications as "notificaitons" once in the README and once in a `LogInfo()` call.

#### Steps to reproduce
    $ git clone https://github.com/mattermost/mattermost-push-proxy.git
    $ cd mattermost-push-proxy/
    $ git rev-parse HEAD
    41affc6595fc927a75de1184292cec89278b40a8
    nothing to commit, working tree clean
    $ git rev-parse HEAD
    41affc6595fc927a75de1184292cec89278b40a8
    $ grep -Ri "notificaiton" .

#### Expected behavior
    $ grep -Ri "notificaiton" .
    $
 
#### Observed behavior (that appears unintentional) 
    $ grep -Ri "notificaiton" .
    ./server/android_notification_server.go:	LogInfo(fmt.Sprintf("Initializing Android notificaiton server for type=%v", me.AndroidPushSettings.Type))
    ./README.md:For more in-depth instructions on setting up push notificaitons with your own build please follow the directions at [docs.mattermost.com](https://docs.mattermost.com/developer/mobile-developer-setup.html#push-notifications-with-your-own-build)

#### Possible fixes
[Here's a link to the line in `server/android_notification_server.go`](https://github.com/mattermost/mattermost-push-proxy/blob/53b38456503670b699f61e70953a0819d6df8f48/server/android_notification_server.go#L23), README.md link unavailable because Github doesn't allow per-line linking to Markdown files (that I know of). I think this should be pretty easy to fix and I can provide a pull request.

**Comment by amyblais** [comment]
Hi @uusijani! Thank you for reporting this.

If you're still interested, do feel free to open a pull request to fix the errors!
