### ISSUE TITLE
[Help Wanted] [MM-12372] Create CLI command "webhook modify-incoming"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9669]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12372)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `webhook modify-incoming` command in the CLI.

Allow modifying incoming webhooks.

Example: `webhook modify-incoming w16zb5tu3n1zkqo18goqry1je --title MyCommand --description "My Command Description" --channel mychannel --lock-to-channel --icon http://localhost:8000/my-slash-handler-bot-icon.png`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by amogozov** [comment]
Hey @esethna . I would be happy to continue working on this

**Comment by esethna** [comment]
FYI looks like there was a typo "incomming" > "incoming"
