### ISSUE TITLE
Create CLI command "team modify"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9670]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12364)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `team modify` command in the CLI.

Allow modifying the team privacy like in `channel modify` command

Example: `team modify myteam --private --username myusernamedev`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by waseem18** [comment]
I worked on building a couple of `team` commands, so can I please take this up?

**Comment by amyblais** [comment]
Thank you @waseem18!

**Comment by waseem18** [comment]
I've got a question, How should the UI respond when the privacy of a team is modified? Should it respond at all?

 For channels I see movement in UI whenever the privacy of channel is modified.

**Comment by amyblais** [comment]
Pinging @jespino ^

**Comment by amyblais** [comment]
Pinging @grundleborg ^

**Comment by waseem18** [comment]
Ping?

**Comment by waseem18** [comment]
Thanks for the response @grundleborg 
Will put a PR today.
