### ISSUE TITLE
[Help Wanted] [MM-12601] Migrate to idiomatic error handling in the file 'app/notification_email.go` in the mattermost-server repo.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9673]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12601)

This ticket is best suited to someone who is already familiar with what the "idiomatic error handling" migration is about. You can discuss this with us on the Mattermost server linked above, and see examples of these changes at commits such as: [https://github.com/mattermost/mattermost-server/commit/a6fa2b72d1375e554cc6f2e5ca2fd4884a8509f4]

Although suggests changing to , please don’t make these changes as part of this PR, as we have decided to keep the codebase consistent the way it is for the time being. At a future date, we will consider migrating the whole codebase.

**Comment by hanzei** [comment]
I would like to work on this.
