### ISSUE TITLE
[Help Wanted] [MM-12678] Order plugins in System Console sidebar in alphabetical order

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9679]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12678)

Order plugins in System Console sidebar in alphabetical order. Currently they are sorted based the order in which the plugins were installed.

[!image](https://mattermost.atlassian.net/secure/attachment/38932/image-2018-10-12-17-25-19-370.png)

Notes:
1. "Configuration" and "Management" should always be ordered first, then followed by plugins in alphabetical order.
2. System Console > Management page lists plugins in alphabetical order.

Changes will likely be made in or around https://github.com/mattermost/mattermost-webapp/blob/master/components/admin_console/admin_sidebar/admin_sidebar.jsx.

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by S4KH** [comment]
I'll try this one.

**Comment by S4KH** [comment]
Can someone tell me how install plugins in the development environment?

**Comment by hanzei** [comment]
There should be no difference to a normal server. Did you follow the steps on https://docs.mattermost.com/administration/plugins.html#set-up-guide?

**Comment by cpanato** [comment]
fixed via https://github.com/mattermost/mattermost-webapp/pull/1905
