### ISSUE TITLE
[Help Wanted] [MM-12765] Illustrate demo plugin settings schema

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9695]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12765)

The [Mattermost Demo Plugin](https://github.com/mattermost/mattermost-plugin-demo) is intended to illustrate everything a Mattermost plugin can do. Right now, however, it doesn't show off the full power of the manifest's settings schema in allowing the plugin to be configured via the system console.

This ticket would be task to design a `header`, `footer` and updated `settings` keys in the [plugin.json](https://github.com/mattermost/mattermost-plugin-demo/blob/master/plugin.json) based on the options documented on https://developers.mattermost.com/extend/plugins/manifest-reference/#settings_schema. It's not strictly necessary that these settings be "useful" (in terms of actually changing meaningful behaviour in the plugin), but at a minimum the plugin should be updated to [model](https://github.com/mattermost/mattermost-plugin-demo/blob/40d83bd9ca30f4b394f8a8a27334c0583ba68a0d/server/configuration.go#L19) all of these settings, and perhaps dump the new configuration to the demo channel when they change to prove that everything is wired up correctly. 

Note that `OnConfigurationChange` hook is called whenever /any/ configuration changes, not just when that particular plugin's configuration has changed. Ideally we avoid spamming the channel on every event, but instead intelligently detect the changes and emit them discretely.

Ideally, the [README.md](https://github.com/mattermost/mattermost-plugin-demo/blob/master/server/README.md) would reflect a screenshot of the system console showing some of the settings and explaining the new behaviour of dumping the configuration to the channel when it changes. The QA team at Mattermost could then have a reference by which to verify the expected plugin behaviour from release to release to ensure that the settings schema remains functional.

Feel free to join us the [community discussion](https://pre-release.mattermost.com/core/channels/developer-toolkit) if you have questions or want to flesh out a proposal.

**Comment by gabrieljackson** [comment]
I will take this!

**Comment by hanzei** [comment]
Thanks @gabrieljackson! If you have questions, feel free to ask the here or in ~developers-toolkit on the [Mattermost Community Server](https://community.mattermost.com).
