### ISSUE TITLE
Page no 1 is missing in pagination when a user is trying to surf pages in Direct Messages Modal.

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [mattermost/mattermost-server#9714]
#### Summary
When a user is trying to surf through the available pages in Direct Messages Modal, when clicked on next button the API call is directly happening from page no 2 which is resulting in missing of users which are available in page 1. Please check the screenshot for reference. It's happening in prerelease version of [mattermost](https://pre-release.mattermost.com)

#### Steps to reproduce
1. Visit pre-release mattermost and then click on Direct Messages.
2. It opens a modal and when you click on next and open your Network tab, you can see the call directly goes from page 2.

#### Expected behavior
Pagination should start on page 1.

#### Observed behavior (that appears unintentional) 
Pagination is starting on page 2

#### Possible fixes
Fixing the starting index of pagination can before calling the API call will fix the issue.

PS: The issue is being addressed in a PR, which is related to Direct Messages --> https://github.com/mattermost/mattermost-webapp/pull/1855

Video Url --> https://drive.google.com/file/d/1CRFupV8lwHkU_Myh6fabep7ec5X48vi1/view?usp=sharing

<img width="1280" alt="screen shot 2018-10-19 at 9 07 08 am" src="https://user-images.githubusercontent.com/11075561/47196914-bcb42f80-d380-11e8-97f6-8915e726171e.png">

**Comment by amyblais** [comment]
Hi @JayaKrishnaNamburu, I see that there is discussion on this in the PR, so I'll create a Jira ticket if a decision is made that this issue will be fixed in a separate PR.

**Comment by JayaKrishnaNamburu** [comment]
Hi @amyblais while working in that PR I fixed this issue as well, just created one thinking it might help for reference
