### ISSUE TITLE
[Help Wanted] [MM-12700] Migrate open direct/group message channel actions to redux

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9717]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12700)

Since switching to redux we've been moving all the component actions into the redux stores.  There are still a bunch of older actions that need to be migrated. The key change that needs to be made is getting rid of functions (primarily located in the actions directory of the web app code) are directly accessing and dispatching redux actions using the global store instance. Often these functions will be imported by a component and used directly. 

If needed convert the action to be a redux action, take a look if the action already exists in `mattermost-redux` and prefer the use of the library one unless you need to combine it with other actions into one view action.

Then update all the components that makes use of the action and finally add/update/delete the appropriate *unit tests*

_______

Example: you may have a component and activity such as

```
// actions/foo_actions.js
import * as FooActions from 'mattermost-redux/actions/foo';

import store from 'stores/redux_store';

export function doSomething() {
	return store.dispatch(FooActions.doSomething());
}

// components/my_button.js
import React from 'react';

import {doSomething} from 'actions/foo_actions';

export default class MyButton extends React.PureComponent {
	render() {
		return <button onClick={doSomething}>{'Click me!'}</button>;
	}
}
```

We should never be importing the global instance of the store directly. Instead, its dispatch method should be accessed through a mapDispatchToProps function passed to react-redux's connect function. Generally, this will also remove the need to have a file like `actions/foo_actions.js` or at least remove a significant amount of code from it. In this example, the correct code will look like

```
// components/index.js
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';

import {doSomething} from 'mattermost-redux/actions/foo';

import MyButton from './my_button';

function mapDispatchToProps(dispatch) {
	return {
		actions: bindActionCreators({
			doSomething,
		}),
	};
}

export default connect(null, mapDispatchToProps)(MyButton);

// components/my_button.js
import PropTypes from 'prop-types';
import React from 'react';

export default class MyButton extends React.PureComponent {
	static propTypes = {
		actions: PropTypes.shape({
			doSomething: PropTypes.func,
		}),
	}

	render() {
		return <button onClick={this.props.actions.doSomething}>{'Click me!'}</button>;
	}
}
```

**Comment by fraziern** [comment]
This is similar to another I'm working on, so I can take a look.

**Comment by enahum** [comment]
Closing as I'll be working on this
