### ISSUE TITLE
Failed to ping DB

### ISSUE THREAD

**Issue by MrSorcus** [mattermost/mattermost-server#9720]
#### Summary
Can't connect to PostgreSQL.

#### Steps to reproduce
Mattermost version: 5.4.0
PostgreSQL version: 10.5

1. Set sql driver in config

```
"DriverName": "postgres",
"DataSource": "postgres://mattermost:SECURE@[2a01:a:b:c::1234]:5432/mattermost?sslmode=disable&connect_timeout=10",
```

2. Run ./bin/mattermost

#### Expected behavior
Connected successful.

#### Observed behavior (that appears unintentional) 
```
# ./bin/mattermost
{"level":"info","ts":1540051228.7046776,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'"}
{"level":"info","ts":1540051228.7051837,"caller":"app/app.go:204","msg":"Server is initializing..."}
{"level":"info","ts":1540051228.714527,"caller":"sqlstore/supplier.go:209","msg":"Pinging SQL master database"}
{"level":"error","ts":1540051228.7573538,"caller":"sqlstore/supplier.go:221","msg":"Failed to ping DB retrying in 10 seconds err=pq: unknown authentication response: 10"}
```

But from another remote machine i can connect to PostgreSQL.

```
# psql --host=2a01:a:b:c::1234 --dbname=mattermost --username=mattermost --password
Password for user mattermost: 
psql (10.5)
Type "help" for help.

mattermost=> \conninfo 
You are connected to database "mattermost" as user "mattermost" on host "2a01:a:b:c::1234" at port "5432".
```

**Comment by MrSorcus** [comment]
I think that a problem with unsupported authentication method `scram-sha-256`.
See https://github.com/lib/pq/pull/608

**Comment by amyblais** [comment]
Hi @MrSorcus,

What server version did you upgrade from?

Also, can you help take a look at these related Forum posts/topics for any troubleshooting tips: https://forum.mattermost.org/search?q=failed%20to%20ping%20db?

**Comment by MrSorcus** [comment]
@amyblais version 5.4.0 builded from AUR (https://aur.archlinux.org/packages/mattermost).
And 5.4.0 precompiled (https://releases.mattermost.com/5.4.0/mattermost-team-5.4.0-linux-amd64.tar.gz)
Both binary doesn't work with `scram-sha-256`. But works with `md5`.
And i think this can be fixed when https://github.com/lib/pq will be has `scram-sha-256`.
See PRs https://github.com/lib/pq/pull/608 & https://github.com/lib/pq/pull/788

**Comment by amyblais** [comment]
Thank you @MrSorcus, I'll close this Issue for now as it can be tracked with the PRs that you linked above.
