### ISSUE TITLE
Impossible to connect to mattermost server from android app - web and windows ok

### ISSUE THREAD

**Issue by sabinobus** [mattermost/mattermost-server#9721]
Summary
When trying to access Mattermost from Android app it doesn’t connect.

Steps to reproduce
Mattermost Enterprise 5.4.1 Ubuntu 16.04  TLS on.
Works ok from Chrome in Windows.

Expected behavior
Working ok in Android app too

#### Observed behavior (that appears unintentional) 

i can connect with a PC to mattermost server but android app doesn’t work.

I’m using mattermost 5.4.0 and mattermost app 1.13.0 on android (latest releases), with TLS activated on mattermost (or disabled on mattermost and activated on nginx), i use a certificate released by let’s encrypt and manually added to configuration (setting use let’s encrypt:false)

I have made several tries, with and without nginx server. Using the APP the issue is present using direct connection to mattermost server or through the proxy.

Another interesting thing is that the app work well on first connection until i close it. When i reopen mattermost app the issue happen and the “Can’t connect, please verify the URL and your internet connection” error appears. if i reboot the android phone nothing changes.

Another really strange thing is this:
if i make a logout on the app i can’t pass the first address and connection step but i have found a strange workaround: i have to close the app, i have to set https://demo.mattermost.com, click on connect reaching username and password windows, now i have to go back setting my mattermost server address where i put my (https) server address and magically i can pass over the connect issue, set username and password and access to public channel and it work and i can send a message.
When i’m in also push notification works.

My actual configuration is:
This is our config:
“SiteURL”: “https://mydomain.com”,
“LicenseFileLocation”: “”,
“ListenAddress”: “:8065”,
“ConnectionSecurity”: “none"
“TLSCertFile”: “”,
“TLSKeyFile”: “",
“UseLetsEncrypt”: false,
“LetsEncryptCertificateCacheFile”: “./config/letsencrypt.cache”,
“Forward80To443”: false,

Nginx active with “standard” configuration
let’s encrypt certificate manually generated and set (no automatic generation or renew)
both http and https active, with automatic redirect to https.
tls enabled
other parameters set as indicated on mattermost web user guide.

It seems that newer version of mattermost app and server doesn’t solve the issue because i had the same issue with mattermost 5.3.1 and previous android app release.

Thankyou

**Comment by amyblais** [comment]
Hi @sabinobus, I see that you also posted this in the Forum, so I'll close this Issue here as a duplicate,
