### ISSUE TITLE
Outgoing webhooks not triggered by system-posts

### ISSUE THREAD

**Issue by stachoj** [mattermost/mattermost-server#9722]
#### Summary
Outgoing webhooks are not triggered by posts made by “System” user (e.g., _Bob joined the channel._)

#### Steps to reproduce
1. Set up simple HTTP service which will log POST requests made by webhook.
2. Set up outgoing webhook (no trigger words, calling URL from step 1).
3. Post some message to that channel. Webhook should be triggered and appear in log.
4. Leave/join that channel. Webhook is not triggered.

(Tested on version 4.10.0)

#### Expected behavior
Since posts made by “System” are shown in a similar way as regular posts (and also accessible via /api/v4/channels/.../posts), we would expect that they will trigger webhooks. **This would be very helpful for automating actions when user joins a channel/team.** Otherwise we have to check channels periodicaly, which is very ineffective.

#### Possible fixes
- Either start triggering webhooks by system-posts.
- Or when creating a webhook, make it possible to choose whether it should be triggered by system-posts or not (default).

**Comment by amyblais** [comment]
Hi @stachoj, letting you know that I'm asking our team if this should be possible, or if this is a potential feature request.

**Comment by amyblais** [comment]
Hi @stachoj,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
I'm asking our team again if there's any known workaround, but it looks like this hasn't been implement yet.

**Comment by amyblais** [comment]
Hi @stachoj, we haven't received an update for a while so I'll close this Issue for now. 

Thank you for considering adding this as a plugin, and let me know if there is anything else I can help clarify!
