### ISSUE TITLE
Please allow SVGs for team icons, user icons and logo

### ISSUE THREAD

**Issue by Tragen** [mattermost/mattermost-server#9726]
I can only use JPG, GIF, PNG today and SVGs are rejected.
I would be happy if I could use SVGs also everywhere as it's the superior format if you have only graphics.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @Tragen!

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Hi @Tragen, thank you for opening a feature request ticket for this - I'll close this Issue for now as it can be followed via Uservoice.
