### ISSUE TITLE
RangeError: Invalid language tag: de8z6nfkuid5mktznkxiwui95h

### ISSUE THREAD

**Issue by zetaab** [mattermost/mattermost-server#9733]
#### Summary
Webapp is returning RangeError: Invalid language tag: de8z6nfkuid5mktznkxiwui95h if we have more than one images in same post

#### Steps to reproduce
latest 5.4, it is difficult to reproduce because it does not happen often. No idea how to reproduce, anyways the key thing is to upload more than one image in same post. And Locale in user should be `''`

#### Expected behavior
Expected is that ui does not crash

#### Observed behavior (that appears unintentional) 

![screen shot 2018-10-24 at 11 12 15](https://user-images.githubusercontent.com/22482503/47416187-ccb38100-d77d-11e8-97ba-454af70c0c4a.png)

for some reason, some id is passed as "locale" and it crashes because of that.

**Comment by zetaab** [comment]
![screen shot 2018-10-24 at 11 17 20](https://user-images.githubusercontent.com/22482503/47416449-69761e80-d77e-11e8-8f36-91db4cdfa835.png)

if I go backwards in callstack it seems that locale variable is same than post id?

**Comment by zetaab** [comment]
it seems that the problem is in this function https://github.com/mattermost/mattermost-redux/blob/master/src/selectors/entities/i18n.js if the user locale is `''` it will fail because default locale is not loaded correctly (in my debugger it says undefined). If I setup my locale from mattermost to spanish, everything works fine.

**Comment by zetaab** [comment]
![screen shot 2018-10-24 at 12 08 24](https://user-images.githubusercontent.com/22482503/47419762-89f5a700-d785-11e8-8747-d42a3278f4c2.png)

like we can see locale is not correct 'es'

**Comment by zetaab** [comment]
now it looks like https://github.com/mattermost/mattermost-redux/blob/master/src/selectors/entities/i18n.js#L6 this row is imported incorrectly.

it should be
`import DEFAULT_LOCALE from 'constants/general';`
instead of
`import {DEFAULT_LOCALE} from 'constants/general';`

**Comment by amyblais** [comment]
Thank you @zetaab! Let us know if you're able to open a PR for this?

**Comment by jasonblais** [comment]
Thanks @zetaab for the PR that resolves this issue.
