### ISSUE TITLE
[Help Wanted] [MM-12802] Plugin: Add "min_server_version" in plugin.json manifest to enable built-in control for preventing load/enable of plugin if server version is not met

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9737]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12802)

Add "min_server_version" in plugin.json manifest to enable built-in control for preventing load/enable of plugin if server version is not met.

Pre-release discussion - https://pre-release.mattermost.com/core/pl/yt6h3pysafgabqmz6ydk63basy

Original post (SA):
Just a random thought: condition check for plugin not to load or enable if it does not meet minimum server requirement?

I’m thinking if adding an explicit item in plugin’s “plugin.json” like min_server_version: 5.4 is necessary so that the plugin will not accidentally load or enable into a server that does not support its feature and subsequently cause unpredictable server errors.

**Comment by hanzei** [comment]
I would like to work on this.
