### ISSUE TITLE
Bulk import direct_post with attach

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#9746]
Hello.

I couldn't find an ability to adding attach via a DirectPost object. Does it possible?
Or maybe you could suggest how to import direct message with attaching which sent via direct channel?

**Comment by amyblais** [comment]
Hi @swood,

Is this what you are looking for: https://docs.mattermost.com/deployment/bulk-loading.html?highlight=bulk%20import#fields-of-the-attachment-object?

**Comment by swood** [comment]
No, this isn't the same, exactly.
You sent a description of Post object, but I asked about the DirectPost object.
That are different objects.

**Comment by amyblais** [comment]
Apologies, I read it as "This object is a member of the Post / DirectPost object", so I thought it also applies to the DirectPost object - I'll ask a developer tomorrow to take a look at this.

**Comment by amyblais** [comment]
@grundleborg / @mkraft ``swood`` is looking to add attachments via a DirectPost object - can you help with this?

**Comment by harshilsharma63** [comment]
@amyblais  @swood it seems like `DirectPopst` object does support attachments, however, it's not documented.

`DirectPost` object documentation - https://docs.mattermost.com/deployment/bulk-loading.html#fields-of-the-directpost-object
`DirectPost` object source code - https://github.com/mattermost/mattermost-server/blob/fe9a81208e4d8290df7b8d89bac2d880c045b84b/app/import_types.go#L159

**Comment by amyblais** [comment]
I opened a PR to update our docs, and it will go through a Dev review.

**Comment by swood** [comment]
Thank you for this advice. It was helpful.

**Comment by amyblais** [comment]
The doc PR has been merged,
