### ISSUE TITLE
[Help Wanted] [MM-12599] Implement assets for Adaptive icons

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9758]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12599)

Assets attached to JIRA ticket. This ticket should be completed on the mobile repo: https://github.com/mattermost/mattermost-mobile

Guide: https://medium.com/google-design/designing-adaptive-icons-515af294c783

**Comment by bmd-kelvin** [comment]
Can I try to take this? but I'm new for react native. I just have basic knowledge react js

**Comment by kmandagie** [comment]
Can I take this issues? But maybe take long time because it's my first time for react native. i just have knowloedge in react js

**Comment by hanzei** [comment]
Sorry for the late reply. Surly you can work in this. Thanks @kmandagie! :+1: Let us know if you have any questions.

**Comment by enahum** [comment]
@kmandagie how are you doing? I’m just wondering how is this going, are you going to submit a PR soon? Do you need any help with this?

**Comment by hanzei** [comment]
Making this available for the public again.

**Comment by kmandagie** [comment]
Sorry for the really late response. just get back from my busy university project for the last 1 month.  so I have a question, I just confused is I need the beta logo or I can use the normal logo and pull request

**Comment by kmandagie** [comment]
I think, I not yet received the beta logo

**Comment by hanzei** [comment]
Hey @kmandagie,

I just want to check how your work on this going. Do you have any questions?

**Comment by kmandagie** [comment]
Hey @hanzei, I follow the JIRA still not update. still not received the logo
is it I get from chat or JIRA?
Maybe I will ask again in the channel

**Comment by hanzei** [comment]
Thanks for the update @kmandagie. I will make sure you get a reply.

**Comment by asaadmahmood** [comment]
@kmandagie Uploaded the beta logo as well, see if that works.

**Comment by kmandagie** [comment]
Create PR mattermost/mattermost-mobile#2663 if you have time you can review that thank you

**Comment by jasonblais** [comment]
Thank you @kmandagie! PR has been merged (https://github.com/mattermost/mattermost-mobile/pull/2663), closing the issue
