### ISSUE TITLE
[Help Wanted] [MM-12649] Convert Excel cells to markdown table when pasting in Mattermost

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9759]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12649)

Expected: Pasting a selection of cells from Excel into the text input box in Mattermost should convert the cells to markdown table format

Potential library to support this: https://github.com/github/paste-markdown

**Comment by amorriscode** [comment]
Looks like this needs doing! I'd be willing to take a stab at it. I also found [this resource](https://github.com/jonmagic/copy-excel-paste-markdown) which may be useful.

**Comment by hanzei** [comment]
Great @amorriscode! :+1:  Let us know, if you have questions.
