### ISSUE TITLE
Implement autocomplete feature to match webapp when editing posts, channel headers and channel purpose

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9760]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12775)

At present, on the webapp, you can use autocomplete when you edit a channel header, channel purpose or a message.  This ticket is to implement the feature on the RN app.

Examples:
When editing a message, channel header or channel purpose on webapp you can:
- type `~` and the channel autocomplete opens to select a channel
- type `@` and the user autocomplete opens to select a user

**Comment by jordeguevara** [comment]
is this still up for grabs?

**Comment by hanzei** [comment]
Sure. Do you want to work on this @jordeguevara?

**Comment by jordeguevara** [comment]
yes, please @hanzei. I'll see what I can do this following week but then I am going out of state for a week again and if needed I'll resume from there. Thanks!

**Comment by jordeguevara** [comment]
@hanzei I had a question. 
<img width="496" alt="header_" src="https://user-images.githubusercontent.com/34716202/66010323-5cc07700-e473-11e9-8dc7-aacdb98c0399.png">
<img width="558" alt="header" src="https://user-images.githubusercontent.com/34716202/66010325-5cc07700-e473-11e9-906a-24a9652f01ef.png">
<img width="530" alt="purpose_" src="https://user-images.githubusercontent.com/34716202/66010328-5fbb6780-e473-11e9-9e26-4e7e25de612d.png">
<img width="537" alt="header_2" src="https://user-images.githubusercontent.com/34716202/66010426-ac06a780-e473-11e9-8bbd-c11daf15a0f7.png">

It seems like editing the header does have auto-complete functionality but the purpose doesn't. 
I'm guessing it is okay to use that same logic and apply it to editing the purpose?

**Comment by hanzei** [comment]
That seams reasonable :+1:

**Comment by chuttam** [comment]
Fyi, there was already another open ticket for adding `<Autocomplete>` to the Edit Post screen with a PR in review at the moment.

* Issue: https://github.com/mattermost/mattermost-server/issues/10159
* PR: https://github.com/mattermost/mattermost-mobile/pull/3295

Hopefully the context in the PR conversation helps a bit with some of the finer details of adding autocomplete to the Channel Header text area in your effort with this ticket.

**Comment by enahum** [comment]
Thanks @chuttam closing issue
