### ISSUE TITLE
[Help Wanted] [MM-12861] Improve sorting of emoji in emoji autocomplete and emoji picker search results

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9761]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12861)

Improve sorting of emoji in emoji autocomplete and emoji picker search results to:

1. First, display recently used emoji that match the search term, in alphabetical order
2. Second, display emoji that start with the search term, in alphabetical order
3. Last, display emoji that contain the search term, in alphabetical order.

Search results should show the emojis in the order specified above with no visual indications of their sorting.

**Comment by amyblais** [comment]
@jasonblais ^

**Comment by jasonblais** [comment]
@amorriscode Good question. We won't be adding a new section for recently used emoji - we'll simply change the order of emojis so that recently used ones appear first.

Let me know if I can help clarify that? Big thanks for helping with this help wanted ticket :)

**Comment by hanzei** [comment]
@amorriscode Did @jasonblais answer help you? Do you have any other questions?

**Comment by amorriscode** [comment]
@hanzei Yes, that makes sense! Sorry for the delay. I'm going to do this ticket today.
