### ISSUE TITLE
Migrate to Flow file src/actions/websocket.js in mattermost-redux

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9762]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11039)

Mattermost is migrating mattermost-redux library to [Flow](https://flow.org/) and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate `src/actions/websocket.js` to Flow.

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/redux/redux-to-flow/)

You can also see an introductory video here: https://www.youtube.com/watch?v=kuHypTgU1ZY

If you need other examples you can see the PRs mattermost/mattermost-redux#488 and mattermost/mattermost-redux#489

**Comment by chrux** [comment]
I'm taking this!

**Comment by hanzei** [comment]
Hey @chrux,

Do you have any questions about this ticket?

**Comment by hanzei** [comment]
Making this available to the public because there wasn't an update from @chrux for some time.

**Comment by chrux** [comment]
Sorry, I haven't been able to go through the PR and apply the changes

**Comment by hanzei** [comment]
Do you still want to work on this @chrux?

**Comment by chrux** [comment]
I don't have time, so let's leave as `Up for grabs` and if I am able to dedicate some time I will come back, thanks

**Comment by tclain** [comment]
I can take it if you want guys. Any specifics I need to know about this ?

**Comment by tclain** [comment]
cool ! thanks this one pretty hard, I'll see what I can do.

**Comment by hanzei** [comment]
Hey @tclain,

How is the work on this ticket going? Do you have any questions?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by mzaks** [comment]
I'm taking this!

**Comment by hanzei** [comment]
Thanks @mzaks. Let us know, if you have any questions.

**Comment by mzaks** [comment]
@hanzei I actually have one :)
I did the conversion already and just a couple of minutes ago I had a look at https://github.com/mattermost/mattermost-redux/pull/849
Where there is a similar issues which I stumbled upon: `ActionFunc` being asynchronous.
I already migrated all the function to be `async`, but than I read the discussion and it seems to me that people are rather in favour of changing the `ActionFunc` type to be both.
However the discussion was happening about 10 days ago and I don't see any "resolution"

**Comment by mzaks** [comment]
I did some testing. If you define the `Hunk` type as following:

```
type Thunk = (DispatchFunc, GetStateFunc) => (Promise<ActionResult> | void);
```

Than there is no need for `async` and no need for `{data: true}`.
Which were both discussed as negative changes in the other PR.

**Comment by jasonblais** [comment]
@jespino or @hmhealey wondering if you'd be able to help on the above?

**Comment by jespino** [comment]
@mzaks sorry the delay in my reply, I think allowing sync/async functions would be a good thing, but I would keep the `ActionResult` type because enforces consistency in the returns, and I prefer that.

Your definition, I think is not exactly what is expected. If I'm right, that allows you to return async function that return an `ActionResult` or a sync function that returns `void`. I would suggest something like: 

```js
type Thunk = (DispatchFunc, GetStateFunc) => (Promise<ActionResult> | ActionResult);
```

**Comment by mzaks** [comment]
@jespino No worries about the delay.

Regarding the `Thunk` type, I specified the return type as `void` based on the patterns I saw in the `websocket.js` file. In `websocket.js` there is a certain "class" of functions which "dispatch schedulers" and by this I mean they call `dispatch` based on some logic without waiting for the response. There are many such functions starting from here:
https://github.com/mattermost/mattermost-redux/blob/master/src/actions/websocket.js#L197

I can introduce a `return {data: true}` statement for all of them or wrap the calls to those `handle...` functions in a function which calls the handlers and returns `{data: true}`, but I am personally not sure if it is helpful. However the `type Thunk` is defined globally for all actions and maybe it is just the `websocket.js` which is out of the ordinary. @jespino Please let me know what you think.

**Comment by jespino** [comment]
I think if the function is just "fire and forget" you still can return the `{data: true}` as a result. My concern is about being too permissive in a type to allow to express this case and then end up returning wrongly in other places. I prefer a bit extra data here. for me, if the action is a "fire and forget" as soon as you fire the action, you succeed, so... `{data: true}` looks sensible to me.

**Comment by mzaks** [comment]
Than it is settled 😀. I will add `{data: true}`.

**Comment by jespino** [comment]
Thanks! :tada:

**Comment by hanzei** [comment]
@mzaks Do you have any outstanding questions?

**Comment by mzaks** [comment]
> @mzaks Do you have any outstanding questions?

No, all good. As far as I remember, the PR addressing this issue already went through in July.

**Comment by mzaks** [comment]
> > @mzaks Do you have any outstanding questions?
> 
> No, all good. As far as I remember, the PR addressing this issue already went through in July.

Yes here it is: 
https://github.com/mattermost/mattermost-redux/pull/875

**Comment by jasonblais** [comment]
Thanks @mzaks, closing this issue. Thank you for the contribution!
