### ISSUE TITLE
[Help Wanted] [MM-12365] Create CLI command "team rename"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9764]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12365)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `team rename` command in the CLI.

Allow renaming teams like in `channel rename` command

Example: `team rename myteam newteamname --display_name "My New Team Name`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by vincealdrin** [comment]
I'd like to take a shot on this!

**Comment by grundleborg** [comment]
That's great @vincealdrin . If you have an questions at all, you can post them here, or contact us on the pre-release server mentioned in the ticket description.

**Comment by hanzei** [comment]
@vincealdrin Do you have any questions about this ticket? Can we help you with something?

**Comment by hanzei** [comment]
Making this available for the public since we didn't got an update from @vincealdrin for some time.

**Comment by dchukmasov** [comment]
Hi! I am looking for the project to make my first Go contribution and I feel that this is exactly the place ^_^

**Comment by hanzei** [comment]
Great @dchukmasov! :tada:  Let me know, if you have questions.

**Comment by dchukmasov** [comment]
@hanzei thanks! I actually come to the point where I have few. 
I have implemented a functionality and unit tests pass. How do you suggest I continue testing the CLI?
Also I am completing a pull request summary.
1) Does CLI counts for "UI changes"?
2) I had to make changes to store.sqlstore.team_store.go -> is this considered a critical section?

Thank you!

**Comment by hanzei** [comment]
Please add a test case to https://github.com/mattermost/mattermost-server/blob/master/cmd/mattermost/commands/team_test.go. And you can do some smoke testing by yourself. But after your submitted your PR, we will test it again :wink:.

1. No, it doesn't.
2. Yes, it does. But I suppose there should be any changes to `team_store.go`. What exactly did you need to change? You can just summit your PR and we can discuss this question then.

Looking forward to your PR! :+1:
