### ISSUE TITLE
Searches using LIKE queries are not optimized properly for Postgres

### ISSUE THREAD

**Issue by zeroimpl** [mattermost/mattermost-server#9781]
#### Summary
Some database queries use the LIKE clause to perform a prefix match, but the database indexes were not setup properly and so do not get used, resulting in poor performance.

#### Details
Database queries in Postgres which use the LIKE clause for prefix matching are able to use a B-Tree index, but only if the index is sorted correctly. The normal way to accomplish this is to add the "text_pattern_ops" modifier when creating the index. See https://www.postgresql.org/docs/current/static/indexes-opclass.html or https://dba.stackexchange.com/questions/188344/text-index-using-text-pattern-ops-with-utf-8-vs-default-operator-class-with-c for more details.

I confirmed that in the previous behaviour, searching for users was executing a sequential scan on the Users table. With this fix, indexes are used. 

In my own testing with about 5000 users, the result was the /api/v4/users/search API responded about 30% faster (the actual query is about 100x faster).

Could somebody try running a load test to confirm this?

Note I believe there are other APIs that can also be improved using this technique.

**Comment by amyblais** [comment]
@zeroimpl Thanks for the PR!

**Comment by lieut-data** [comment]
Hey @zeroimpl! I've asked @crspeller and @jespino to take a look here :)

**Comment by lieut-data** [comment]
Thanks, @zeroimpl :)
