### ISSUE TITLE
Content decoding failed.

### ISSUE THREAD

**Issue by MrSorcus** [mattermost/mattermost-server#9783]
#### Summary
Desktop Mattermost doesn't work if all responses compressed with brotli.

#### Steps to reproduce
Mattermost-Desktop Version: 4.1.2

Enable brotli in the nginx config.
```
brotli on;
```

Try connect to server from mattermost-desktop.

#### Expected behavior
Mattermost-Desktop must works correctly with brotli compressed responses.

#### Observed behavior (that appears unintentional) 
```
errorCode: -330
errorDescription: "ERR_CONTENT_DECODING_FAILED"
type: "did-fail-load"
```

**Comment by amyblais** [comment]
Thank you @MrSorcus,

We used to have a ticket to add support for brotli, but the ticket was closed since we now have webpack (see the comments at the bottom of the ticket): https://mattermost.atlassian.net/browse/MM-3880.

Would you be able to try with webpack? Or if you want to brotli, can you help submit a feature request here: https://mattermost.uservoice.com/forums/306457-general.

**Comment by MrSorcus** [comment]
> Would you be able to try with webpack?

How can i do that? And how that help to resolve issue?
Because chromium and derivatives supports `brotli` from 50 version.
Mattermost desktop uses electron that based on chromium engine.
And i thought that him must work with brotli from box.

**Comment by amyblais** [comment]
Hi @MrSorcus,

Thank you for the details - would you be able to reopen this Issue on our desktop app repo here: https://github.com/mattermost/desktop/issues.

Our developer who runs the desktop app might have more details on whether we support brotli or if this would be a feature request.

**Comment by MrSorcus** [comment]
> Hi @MrSorcus,
> 
> Thank you for the details - would you be able to reopen this Issue on our desktop app repo here: https://github.com/mattermost/desktop/issues.
> 
> Our developer who runs the desktop app might have more details on whether we support brotli or if this would be a feature request.

Must i close this issue?
