### ISSUE TITLE
Mattermost and Let's encrypt

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#9789]
Hello.

I'm trying to setup let's encrypt in mattermost with docker.
I have the next configuration:

`        "SiteURL": "https://my-domain.com",  `
`        "WebsocketURL": "", `
`        "LicenseFileLocation": "", `
`        "ListenAddress": ":443", `
`        "ConnectionSecurity": "TLS", `
`        "TLSCertFile": "", `
`        "TLSKeyFile": "", `
`        "UseLetsEncrypt": true, `
`       "LetsEncryptCertificateCacheFile": "./config/letsencrypt.cache", `
`        "Forward80To443": true` 

But. After I started container I see the text messages in the log:
{"level":"info","ts":1541156861.503802,"caller":"http/server.go:1763","msg":"http: TLS handshake error from GW_ADDR:12673: acme/autocert: missing server name","source":"httpserver"}

Could you tell me where I was wrong?

**Comment by amyblais** [comment]
Hi @swood, can you re-open this Issue in the Docker repo [here](https://github.com/mattermost/mattermost-docker/issues) and the community member who runs it will be able to help with any docker related problems. Thank you!

**Comment by swood** [comment]
I've solved my problem. Sorry, it was my mistake.
