### ISSUE TITLE
uploadFile: File above maximum dimensions could not be uploaded

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#9794]
Hello.

The mattermost is:

Version: 5.4.0
Build Number: 5.4.0
Build Date: Tue Oct 16 16:48:28 UTC 2018
Build Hash: d5b613cb1bbdaa856fa126e7102d94783b9e80b6
Build Enterprise Ready: false
DB Version: 5.4.0

I have a question with bulk inserting history. The image  is:
`PNG image data, 4320 x 8880, 8-bit/color RGBA, non-interlaced`

And I have the maximum size of images in config:
`"MaxFileSize": 262144000`

But I receive this error when I tried the bulk import. Why?

**Comment by amyblais** [comment]
Hi @swood, do you see any errors in logs? Also, do you see this on a specific device and browser?

**Comment by swood** [comment]
Unfortunately, I can see only this error message when I bulk import users history to mattermost via:
`./mattermost import bulk history.jsonl --apply`

**Comment by amyblais** [comment]
Hi @swood, can you help post the JSON formatting you used to import the image?

**Comment by swood** [comment]
Sure:

`{"type": "direct_post", "direct_post": {"channel_members": ["user1", "user2"], "create_at": 1507305803192, "message": "", "attachments": [{"path": "/export/users/files/BgrmZeUiGORTwNq/Layer3-01.png"}], "user": "user1"}}`

**Comment by swood** [comment]
@amyblais do you have any news?

**Comment by amyblais** [comment]
@swood Sorry, I was off for the past few days - I asked our team last week to take a look at this, and I will ping them again today as I haven't gotten any feedback yet.

**Comment by lieut-data** [comment]
Hey @swood! There is currently a hard-coded internal limit as to how big the image can be:
https://github.com/mattermost/mattermost-server/blob/7a758eae72b3938950111ed8faecbb03ee856cf8/app/file.go#L56

I suspect this limit came from memory issues around image transforms. If you're inclined to make this configurable (in units of megapixels), I suspect we'd welcome a PR as such :)

**Comment by swood** [comment]
Hey, @lieut-data, I can't agree with it. My image is only:

`# du -sh Layer3-01.png`
`200K	Layer3-01.png`

it's quite smaller then 36MB.

**Comment by lieut-data** [comment]
Hey @swood, this isn't about the file size on disk as . PNG, but about the amount of memory the image would require to unpack into memory as a raw image. 

If the dimensions are indeed `4320 x 8880` as you indicated, then although the image can be compressed down to `36MB` as a PNG (I'm assuming lots of solid colours?), the memory requirements of unpacking it for transformation are much higher.

This is not to say that the hard-coded check above is particularly elegant -- we can almost certainly do better here with respect to improving the pipeline/memory usage. But this check prevents someone from uploading a "small" image that unpacks to a much larger-in-memory image that crashes the server. At a minimum, it makes sense to allow it to be configurable.

**Comment by swood** [comment]
@lieut-data probably you are right. 
But I think there is another problem.
The import of room history has stop when the code faced with the same image and If it at the end of the file - okay. But if at the beginning and the history file is about 25k strings - it's quite sad. 

I suggest to leave that limit at the current place, but when I have been importing the chat history, I don't want to think about resources. I want to import all history!

@amyblais would you argue with it?

**Comment by lieut-data** [comment]
I'd agree with that: the import process shouldn't necessarily abort due to a failed image import. (Maybe a flag to suppress warnings along the way?)

**Comment by swood** [comment]
@amyblais  ?

**Comment by amyblais** [comment]
Hi @swood, thank you following up, I just opened a ticket to address this issue: https://mattermost.atlassian.net/browse/MM-13033.

**Comment by amyblais** [comment]
Hi @swood, letting you know that we've opened a Help Wanted issue here for our community to work on it: https://github.com/mattermost/mattermost-server/issues/10754.

Feel free to work on the issue if you want to and let us know any questions.

Closing this as a "duplicate",
