### ISSUE TITLE
Sometimes creating channel ends up with an error

### ISSUE THREAD

**Issue by vpecinka** [mattermost/mattermost-server#9796]
#### Summary
Sometimes creating private channel or multiparty direct message ends up with no associated members in the database.

#### Steps to reproduce
Using MM 5.4.0 It cannot be reproduced easily, as it happens sometimes. However, there are 2 repeated scenarios:

1. Channel already exists error: when creating new private channel (of no such name in the database), enter the name and display name in the form, after submitting the form I got an error, that channel already exists. If I check database, the channel was freshly created (cross check: looking at CreateAt column), but with no members (even the creator). It seems like being created by the form in the background... but happens only sometimes...

2. When creating multi party direct messages, sometimes the channel is created (creator sees it), but no other party can see it - looking to the database, there are no members associated (even the creator). The ChannelMembers is empty for the channelId, the same as in 1. I think, as direct messages and private channel have a lot in common, it can be very related to the case no 1.

#### Expected behavior
The members (and creator) should be members of the channel.

#### Observed behavior (that appears unintentional) 
I think, there is some race condition between creating channel and adding member. I do not know if this happens in a single transaction or not (then race condition is possible). But in both cases the channel is created, but with no members. In the first case it ends with error about already existing channel (but created by the form), in the second example the channel is created with no error, but members missing as well.

BTW we use Galera cluster as storage and there can be 2 different nodes involved if this is not a single transaction. However, galera cluster should deal with this...

**Comment by amyblais** [comment]
Hi @vpecinka,

For Issue 1, is there another existing channel that has the same name as the channel you're trying to create (including archived channels)? Also, just to confirm, are you using Advanced Permissions: https://docs.mattermost.com/deployment/advanced-permissions.html (perhaps you're seeing the error if there's permissions restrictions)?

For Issue 2, this seems expected - the other user will not see the DM channel until the member who starts it posts a message in it.

**Comment by vpecinka** [comment]
Ad 1 - no, there is no such a channel... would it be, the new one (with no members) could not be created as it would violate uniq key/index in table `Channels`. It really seems like the channels is (sometimes) created when I submit  the form for new channel, some race condition is met, the creation process fails (but database record is created), it tries again and got error that such a channel exists.

Issue 2 - the problem is not with seeing the channel, but that the table `ChannelMembers` contains no members for this channels. So even posting 7 messages to the channel (properly stored in the table `Posts`) means, that the other party cannot see the channes. Because they are not members. Their names are in the channel `displayName` column, but only presence in `ChannelMembers` table makes the channel accessible to them. It doesn't change when posting to the channel. I tried to add the members manualy to the `ChannelMembers` table and then it works.

So again, I think there is something in the "create channel" process which creates it twice, or a self-healing repeared proces on db error (?) or...

**Comment by amyblais** [comment]
Hi @vpecinka, apologies for the delay, I've asked our team to take a look at this but I haven't received any feedback yet, so I'll ping our team again today for this.

**Comment by amyblais** [comment]
Hi @vpecinka, I created a Jira ticket for our devs to look into this further: https://mattermost.atlassian.net/browse/MM-12986.

**Comment by vpecinka** [comment]
thank you!

**Comment by amyblais** [comment]
Hi @vpecinka, letting you know that the Jira ticket was closed as our developers determined that Galera seems to be a multi-master DB cluster which we don't actively support and haven't tested with. If we get reports of this for non-multi master clusters we can fix it or in the future we could potentially add support for multi-master DB clusters. I'll close this Issue for now as it seems that this won't be fixed for now.

You can add a feature request idea to our uservoice forum here: https://mattermost.uservoice.com/forums/306457-general.

Let me know any questions,
