### ISSUE TITLE
Selecting text in channel and selecting "Print" doesn't work in web app

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-server#9803]
#### Summary
Selecting text in channel and selecting "Print" doesn't work in web app

#### Steps to reproduce
1. In Chrome on Windows 10 select text in channel, then right click and select "Print".

![image](https://user-images.githubusercontent.com/177788/48065674-366d5b00-e180-11e8-962e-c9a95657b9c8.png)

#### Expected behavior
Text selected can be printed 

#### Observed behavior (that appears unintentional) 
Text to print is blank 

![image](https://user-images.githubusercontent.com/177788/48065639-235a8b00-e180-11e8-828b-62ed758afebe.png)

#### Possible fixes
I think this used to work, seems pretty basic, maybe something in CSS changed?

**Comment by amyblais** [comment]
Thank you @it33,

I wasn't able to reproduce this just now, but I'll continue to test this out today.

**Comment by amyblais** [comment]
Hi @it33, there haven't been updates on this for a while so we'll assume that the problem is fixed or is no longer valid. 

If the issue persists, please reopen this Issue with the relevant information and I'd be glad to help you where we can.
