### ISSUE TITLE
[Help Wanted] [MM-12354] React Native: Add ability to remove profile picture

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9808]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12354)

Add the ability to remove a profile image.

In Account Settings > General > Profile Picture, if we click on the Profile picture, we get 3 options currently. Proposing we add another option if a custom profile pic is uploaded, “Remove Photo”.

If however there is no custom profile pic uploaded, then that option will not appear.

Designs can be seen here:
https://invis.io/FZOH63CYP29\#/324515451_Mattermost\_\-\-\_Title|https://invis.io/FZOH63CYP29#/324515451_Mattermost_--_Title

**Comment by amyblais** [comment]
Thank you @bradjcoughlin!

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-mobile/pull/2428
