### ISSUE TITLE
html class for new alone post

### ISSUE THREAD

**Issue by sizvix** [mattermost/mattermost-server#9811]
New alone post has the same class "other--root" than response for an other thread.
I would like to make a ( little ) different style for alone messages which no-one has respond , but there isn't special class for those posts ...

**Comment by amyblais** [comment]
Hi @sizvix,

What is the use case for having a different style for alone messages?

**Comment by amyblais** [comment]
Hi @sizvix, just following up, let me know if there is anything I can help clarify?
