### ISSUE TITLE
Desktop notifications disappear

### ISSUE THREAD

**Issue by Dundee** [mattermost/mattermost-server#9815]
#### Summary
Mattermost is intended to be team collaboration and messaging tool. 
It functions fine when working with channels which are similar to forums or IRC channels.

But when sending direct messages, the UX is quite bad because desktop notifications disappear after 5 seconds and when user is concentrating to something else or is AFK he will miss the notification and doesnt know that someone is trying to reach him.

#### Steps to reproduce
Get direct message, do not click on desktop notification.

#### Expected behavior
The notification should stay visible.

#### Observed behavior (that appears unintentional) 
Notification will be closed after 5 seconds.

#### Possible fixes
* set `requireInteraction` to `true` as suggested in https://github.com/mattermost/mattermost-webapp/pull/2019
* add new configuration option which will set `requireInteraction`

**Comment by amyblais** [comment]
Hi @Dundee,

We used to have a setting for this but it was removed in v5.0: https://docs.mattermost.com/help/settings/account-settings.html#notification-duration. This is expected behaviour in this case (if you're on server v5.0 or later).

**Comment by amyblais** [comment]
Hi @Dundee,

Thank you for the feedback! I agree that 5 seconds is a short time and can lead to missed messages. The pull request that you opened will go through reviews from our product managers and developers - thank you for opening the pull request!

**Comment by Dundee** [comment]
This feature was already voted for and implemented - https://mattermost.uservoice.com/forums/306457-general/suggestions/15179742-make-notification-about-new-message-persistent
but it's not present any more.

**Comment by Dundee** [comment]
I now see that `requireInteraction` is not supported by some browsers, so this is not the way ho to solve it. I should probably open better PR with configurable duration option.
