### ISSUE TITLE
Import strange things

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#9821]
Hello.

It's me again.
I had been imported a lot of messages to Mattermost, and I have found a strange thing. Some user was in a private room. After some time he goes out from this room (I mean HipChat). There isn't this user in the HipChat export as a member of the private room, and there isn't this user in private channel after import to Mattermost.
But, this user could observe this group after login to Mattermost. I could understand the reason (he has a history of this room), however, this user hasn't been added to private channel in Mattermost. 
So, this is a bug or not?

**Comment by amyblais** [comment]
Hi @swood,

To confirm, after the import was done, the user got automatically added back to the private channel (in Mattermost)?

**Comment by swood** [comment]
Hello, @amyblais.
Yes, after the user has been login to Mattermost after import. Not before that moment.

**Comment by amyblais** [comment]
@swood Is that user an admin or just a regular non-admin user? If they are an admin, there is a chance that they have clicked a URL / link that redirected them to that private channel (admins can access private channels if they click a permalink).

**Comment by swood** [comment]
@amyblais no, this is non-admin user.

**Comment by amyblais** [comment]
Hi @swood, can you help confirm what command or JSON formatting was used for importing the private channel? Also, please let us know if there were any log errors or Console errors?

**Comment by swood** [comment]
Hey, @amyblais!
The command was very usual:

`./mattermost import bulk /path/to/file.jsonl -config /path/to/config.json --apply`

And the format as usual, I think. 

`{"post": {"message": "text", "create_at": timestamp, "user": "user", "channel": "channel_name", "team": "team_name"}, "type": "post"}`

Should I add something to?

**Comment by amyblais** [comment]
Hi @swood, some final questions:

Have you seen this with one user or multiple users?
Was there any system message in the private channel when the user 'joined' it, e.g. "[User] joined the channel".

I'll ask our team if there is a way for us to test this out and see if this is a bug.

**Comment by swood** [comment]
>> Have you seen this with one user or multiple users?
I found only one, but this installation has about 500 users and a lot of channels. I can't check all of them.

>> Was there any system message in the private channel when the user 'joined' it, e.g. "[User] joined the channel".

Unfortunately no. This user suddenly sends a message to a private channel. Without any special messages like you wrote.

**Comment by amyblais** [comment]
Hi @swood, thank you for that, I've asked our team to help verify if there is a bug here.

**Comment by amyblais** [comment]
@swood From our developer:

Presumably the issue here is that the bulk import file adds the user to the channel. If you don't want them to be added to he channel, you could fix your bulk import data to not add the user to the channel. 

Does this help?

**Comment by swood** [comment]
@amyblais I suppose no and this is a bug. No, the user don't in channel after bulk import. I checked it.
Although, the user could read the channel after login to the system. That the bug!

I can't edit my bulk data because I have a vast archive and I don't know about all situations. It's doesn't possible at all.

**Comment by amyblais** [comment]
Hi @swood, I've forwarded this feedback to our developer and I'll give you an update within the next few days.

**Comment by amyblais** [comment]
Hi @swood, feedback from a developer: 

The issue here seems to be that you are importing channel memberships for user-channel combinations where you don't want the user to be a member of a channel. If you don't want that, then you don't have to it. In other words, it seems that your data might be wrong. From one of your other Issues, we understand that you have written a script to translate a Hipchat export into the Mattermost bulk import format. It sounds like that script is broken and is generating channel memberships where it shouldn't.

**Comment by swood** [comment]
@amyblais In other words, if I have a history from 4 years of HipChat room with a member who isn't members of this room yet, but is active in general, I have to filter the past and drop current users history? It's nonsense!

My software based on the export of HipChat. I have a json-file, and in that file, there is an array with members of this room. So, only that users will be added to that private channel. However, there is a user, who was in that room, active at this moment, this users wrote to that secret room, but two years ago left from it.
So, that user there isn't on the private channel right away after the import (I've double checked it), but he can join back to the private channel after login to Mattermost.

**Comment by swood** [comment]
Hi, @amyblais.
Do you have an updates?

**Comment by amyblais** [comment]
Hi @swood, letting you know that our partner Herzum has released a new Hipchat import tool which has been working well - hopefully you'll have a more pleasant import experience if you choose to try this tool: https://github.com/herzum/HC2MM.

**Comment by swood** [comment]
Hey, @amyblais.
I'm not sure that it is a suitable tool. I didn't find any technical detail about "how it works".
Anyway, I wrote my tool: https://github.com/swood/varna and It works. I checked.

**Comment by amyblais** [comment]
Awesome, good to hear you were able to make it work.
