### ISSUE TITLE
Configurable desktop notifications duration

### ISSUE THREAD

**Issue by Dundee** [mattermost/mattermost-server#9823]
#### Summary
Mattermost is intended to be team collaboration and messaging tool.
It functions fine when working with channels which are similar to forums or IRC channels.

But when sending direct messages, the UX is quite bad because desktop notifications disappear after 5 seconds and when user is concentrating to something else or is AFK he will miss the notification and doesn't know that someone is trying to reach him.

#### Steps to reproduce
Get direct message, do not click on desktop notification.

#### Expected behavior
The notification should stay visible.

#### Observed behavior (that appears unintentional)
Notification will be closed after 5 seconds.

#### Possible fixes
* add new configuration option which will set duration of notifications

This was already implemented once, but removed later - https://github.com/mattermost/mattermost-server/pull/3883

**Comment by amyblais** [comment]
Hi @Dundee,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by Dundee** [comment]
@amyblais Sure, added: https://mattermost.uservoice.com/forums/306457-general/suggestions/35998885-configurable-desktop-notifications-duration

**Comment by amyblais** [comment]
Thank you @Dundee! I'll close this Issue here for now as it can be tracked via the feature request ticket,

**Comment by Dundee** [comment]
Ok, thanks!
