### ISSUE TITLE
"Participiant is writing" timeout

### ISSUE THREAD

**Issue by tyurderi** [mattermost/mattermost-server#9845]
#### Summary
When the user in a opened chat writes and sends their message the text "userX is writing..." is not gone immediately - the text is there for like 1-2 seconds afterwards.

#### Steps to reproduce
Version 5.4.0
Open a chat with a user, let him write some text to you and see a the text below the textbox.

#### Expected behavior
The text should immediate hide after text submission.

#### Observed behavior (that appears unintentional) 
-

#### Possible fixes
-

**Comment by amyblais** [comment]
Thank you @tyurderi,

I opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-13077.

**Comment by amyblais** [comment]
Hi @tyurderi, letting you know that the Jira ticket is resolved and the fix will be available in upcoming v5.7 release.
