### ISSUE TITLE
`mattermost` cli scramble plugins files ownership

### ISSUE THREAD

**Issue by sblaisot** [mattermost/mattermost-server#9853]
#### Summary

When using the `mattermost` cli for some purposes unrelated to plugins, the end result is that pluging files ownership are changed to the user running the cli, breaking the plugins.

#### Steps to reproduce

1. Install mattermost and configure it to run as user `mattermost`
2. Ensure zoom or jira plugin files under the `plugins` directory are owned by user `mattermost`
3. run `bin/mattermost team list` as root
4. as a result, plugin files for zoom and JIRA has been changed ownership to `root`

#### Expected behavior

No plugin file ownership change when running the cli for any purpose unrelated to plugins

#### Observed behavior (that appears unintentional) 

```
root@mattermost-server:/opt/mattermost# ll plugins/
total 20
drwxr--r--  5 mattermost mattermost 4096 Nov 20 09:41 ./
drwxr-xr-x 11 mattermost mattermost 4096 Oct 18 21:51 ../
drwxr--r--  3 mattermost mattermost 4096 Nov  5 09:53 com.github.matterpoll.matterpoll/
drwx------  2 mattermost mattermost 4096 Nov 20 09:41 jira/
drwxr--r--  4 mattermost mattermost 4096 Nov 20 09:41 zoom/

root@mattermost-server:/opt/mattermost# bin/mattermost team list
{"level":"info","ts":1542706919.7364259,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'fr' from '/opt/mattermost/i18n/fr.json'"}
{"level":"info","ts":1542706919.7370307,"caller":"app/app.go:204","msg":"Server is initializing..."}
{"level":"info","ts":1542706919.7449923,"caller":"sqlstore/supplier.go:209","msg":"Pinging SQL master database"}
{"level":"info","ts":1542706919.751758,"caller":"sqlstore/channel_store_experimental.go:47","msg":"Enabling experimental public channels materialization"}
{"level":"info","ts":1542706919.971731,"caller":"app/license.go:44","msg":"License key from https://mattermost.com required to unlock enterprise features."}
{"level":"info","ts":1542706919.9718752,"caller":"app/plugin.go:100","msg":"Starting up plugins"}
team1
team2
team3
{"level":"info","ts":1542706921.3413773,"caller":"app/app.go:283","msg":"Stopping Server..."}
{"level":"info","ts":1542706921.3418024,"caller":"app/web_hub.go:120","msg":"stopping websocket hub connections"}
{"level":"warn","ts":1542706921.3420546,"caller":"app/web_hub.go:125","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","ts":1542706921.3426452,"caller":"app/plugin.go:156","msg":"Shutting down plugins"}
{"level":"info","ts":1542706921.3533497,"caller":"sqlstore/supplier.go:852","msg":"Closing SqlStore"}
{"level":"info","ts":1542706921.3540993,"caller":"app/app.go:305","msg":"Server stopped"}

root@mattermost-server:/opt/mattermost# ll plugins/
total 20
drwxr--r--  5 mattermost mattermost 4096 Nov 20 09:42 ./
drwxr-xr-x 11 mattermost mattermost 4096 Oct 18 21:51 ../
drwxr--r--  3 mattermost mattermost 4096 Nov  5 09:53 com.github.matterpoll.matterpoll/
drwx------  2 root       root       4096 Nov 20 09:42 jira/
drwxr--r--  4 root       root       4096 Nov 20 09:42 zoom/

```

#### Possible fixes
- Forbid to run the cli as a different user from the user actually running the server
- Do not enforce the plugin file ownership in the server part of the cli
- Add a sticky bit on the `bin/mattermost` cli binary to force it to run under the right user even if launched by root

**Comment by amyblais** [comment]
Hi @sblaisot,

I asked our team about this and one of our community members noticed that this only happens for prepacked plugins. Please see this PR: https://github.com/mattermost/mattermost-server/pull/9149. On each start prepacked plugins are removed and then reinstalled (with permissions of current user).

**Comment by amyblais** [comment]
Hi @sblaisot, we haven't received updates for a while so I'll close this Issue for now. Please re-open this Issue if the problem persists.
