### ISSUE TITLE
instagram-py error "fatal error:: configuration file not found at /root/instapy-config.json"

### ISSUE THREAD

**Issue by TheMercyless1** [mattermost/mattermost-server#9870]
After lots of trial and error, I have finally made it to the very last step...but now I can't get passed this error message:

user123@computer123:/usr/share/wordlists$ sudo instagram-py -u username123 -pl rockyou.txt.gz
Instagram-Py 2.0.7 ,  Slick Instagram brute force command line tool.
Copyright (C) 2018 The Future Shell , Antony Jr.

[+] Started @ 2018-11-22 07:45:28.707465
fatal error:: configuration file not found at /root/instapy-config.json

**Comment by amyblais** [comment]
Hi @TheMercyless1,

What were the reproduction steps that led to this error? Can you help with more details on what you are working on here?

**Comment by amyblais** [comment]
Hi @TheMercyless1, letting you know that this Github repo is for Mattermost, not Instagram. Would you be open to creating an Issue on their repo: https://github.com/deathsec/instagram-py?

**Comment by TheMercyless1** [comment]
Oops. I'll do that right now. Happy turkey day!

**Comment by amyblais** [comment]
No worries! I'll close this Issue here for now,
