### ISSUE TITLE
@babel/plugin-syntax-dynamic-import doesn't perform necessary transform for using dynamic imports in node

### ISSUE THREAD

**Issue by nerboda** [mattermost/mattermost-server#9885]
#### Environment
- node 9.8.0
- npm 6.4.0

#### Summary
The .babelrc file currently uses @babel/plugin-syntax-dynamic-import to parse dynamic imports. Because that plugin doesn't perform the necessary transform for a node environment, dynamic imports like the one in [latex_block.jsx](https://github.com/mattermost/mattermost-webapp/blob/master/components/latex_block.jsx#L22) throw an `Unexpected token import` error when running the test suite.

#### Steps to reproduce
Setup the project and run `$ make test`.

#### Expected behavior
Expected babel to transform dynamic imports when running tests and for all tests to pass.

#### Observed behavior (that appears unintentional) 
All tests that used the latex_block.jsx component fail because that component uses the dynamic import syntax.

#### Possible fixes
Replace the `@babel/plugin-syntax-dynamic-import` with the [dynamic-import-node](https://github.com/airbnb/babel-plugin-dynamic-import-node) plugin in the test env in .babelrc.

```
env: {
        test: {
            presets: [
                ['@babel/preset-env', {
                    targets: {
                        chrome: 66,
                        firefox: 60,
                        edge: 42,
                        ie: 11,
                        safari: 12,
                    },
                    debug: false,
                    useBuiltIns: 'usage',
                    shippedProposals: true,
                }],
                ['@babel/preset-react', {
                    useBuiltIns: true,
                }],
            ],
            plugins: [
                '@babel/plugin-proposal-class-properties',
                'dynamic-import-node'
            ],
        }
    }
```

**Comment by amyblais** [comment]
Hi @nerboda, thank you for the report, I will ask our developers about this.

**Comment by nerboda** [comment]
@amyblais thanks. That code made it into master so the tests must be passing for others. I'm trying to figure out what would be different about my environment that might be causing the issue.

**Comment by nerboda** [comment]
@amyblais No not yet, I'll let you know as soon as I do.

**Comment by amyblais** [comment]
Hi @nerboda, The current recommended node version is 10.14.2. Did you already try it with a more recent version?

**Comment by amyblais** [comment]
Hi @nerboda , we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
