### ISSUE TITLE
failed to save license due to mattermost.Users not existing yet.

### ISSUE THREAD

**Issue by logand22** [mattermost/mattermost-server#9907]
#### Summary
License does not get saved in the database when specified in config.json due to mattermost.Users not existing .

#### Steps to reproduce
Start a new mattermost server with fresh mysql DB configured per the installation guide with a license key file location specified in config.json. 

I am using Mattermost 5.5 but have also experience this issue with version 5.4. 

#### Expected behavior
I expect that license should not attempt to save into database until database tables are created. The license depends on the user count which is unavailable until after that table is created. 

#### Possible fixes
Below is the link to the line that causes the error. 
https://github.com/mattermost/mattermost-server/blob/da265fbaf78a02333c00eec167540ac2119b2b89/app/license.go#L55

**Comment by logand22** [comment]
![screen shot 2018-11-28 at 4 42 22 pm](https://user-images.githubusercontent.com/38335829/49187540-6ea22c80-f32d-11e8-99d3-f8e0e92cec04.png)

**Comment by amyblais** [comment]
Thank you @logand22, would you be open to helping submitting a fix for this issue?

**Comment by logand22** [comment]
( As a note the below comments are what I believe to be true and might not actually be the case. It's only based on my own experiences debugging this issue. )

As an update to this issue. I found the issue to be with the MySQL replication and not the mattermost order of events. 

In my particular case I was orchestrating the deployment of the entire HA cluster. This had the unfortunate impact of starting mattermost before the slaves had connected to the master for replication. Mattermost would then attempt to get the users from a DataSourceReplication node but the values wouldn't have been replicated to them yet. 

This wouldn't be noticed in a normal, manual deployment as the delay in configuring everything would be enough time for the replication setup to be complete. 

How the Mattermost team wants to respond or address this issue is up to them because I believe this might be out of the scope of what the team wants to support as it's more of a side (e/a)ffect( I never know what to use ) of my particular circumstances then normal circumstances. A note about automated deployments could be made for those using tools such as Salt, Ansible, Chef, etc... Or if someone wanted to they could add a retry element to the line mentioned above. To be honest who knows. A lot of things are possible.

**Comment by amyblais** [comment]
Hi @logand22,

Thank you for sharing your findings, I'll close this Issue for now as the immediate problem is resolved.
