### ISSUE TITLE
[Help Wanted] [MM-13293] Migrate api4/user.go to idiomatic error handling

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9941]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13293)

This ticket is best suited to someone who is already familiar with what the "idiomatic error handling" migration is about. You can discuss this with us on the Mattermost server linked above, and see examples of these changes at commits such as: https://github.com/mattermost/mattermost-server/pull/9933/commits/6af927a1066186b5306eec2477ca839c2876d58c

Although golint suggests changing fooId to fooID, please don’t make these changes as part of this PR, as we have decided to keep the codebase consistent the way it is for the time being. At a future date, we will consider migrating the whole codebase.

**Comment by jespino** [comment]
@hanzei Do you want to take care of this?

**Comment by hanzei** [comment]
@jespino Sure :+1:
