### ISSUE TITLE
[Help Wanted] [MM-13302] Web: Remove usage of localizeMessage in input box placeholders by creating a reusable component that does the localization

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9945]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13302)

The reusable component will likely need to get the intl object either from this.context or from injectIntl so that it can perform the translation itself. See [here](https://github.com/mattermost/mattermost-mobile/blob/master/app/components/text_input_with_localized_placeholder.js) for an example of how it's done on the mobile app (although the web app's version probably doesn't need as specific of a name).

When doing this, make sure to double check that the new component can handle everything needed wherever it is used since it will likely need additional fields and methods to support places were a ref is used to talk to the DOM node directly

**Comment by kosgrz** [comment]
I would like to do this ticket. I have done a similar one, so that would be quite easy.

**Comment by hanzei** [comment]
Thanks @kosgrz! :+1:
