### ISSUE TITLE
[Help Wanted] [MM-13301] Web: Remove usage of localizeMessage from Team Settings modal

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9946]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13301)

If possible, this should be replaced by using a FormattedMessage, but if that won't work, we should change these to get the intl object either from this.context or from injectIntl and then use that to perform the translation.

**Comment by kosgrz** [comment]
I can take this.

**Comment by amyblais** [comment]
Thank you @kosgrz!
