### ISSUE TITLE
[Help Wanted] [MM-13299] Web: Remove usage of localizeMessage when editing a post from the DotMenu component

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9950]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13299)

If possible, this should be replaced by using a FormattedMessage, but if that won't work, we should change these to get the intl object either from this.context or from injectIntl and then use that to perform the translation.

**Comment by kosgrz** [comment]
@esethna I'd like to take this.

**Comment by hanzei** [comment]
Great, thanks @kosgrz :tada:

**Comment by hmhealey** [comment]
Thanks for your work on this, @kosgrz! There's a few other tickets similar to this if you'd be interested in helping with those as well.

Also, feel free to join us on our community server at https://community.mattermost.com where you can join in discussions and ask questions about Mattermost. You can also use https://community-daily.mattermost.com for that if you feel adventurous and want to try out the latest daily build as well.
