### ISSUE TITLE
Performance issues with many posts in a thread

### ISSUE THREAD

**Issue by somenet** [mattermost/mattermost-server#9956]
#### Summary
There are in-browser performance issues with many posts in a thread.

We are having a heated debate in a few paralell threads at once.

Once the post-count in the thread reaches above 350 posts, it becomes a major pain-point to load the channel and open the threadview.

It currently takes about 10 sec to load the thread view on a t480 lennovo thinkpad, debian, kde, chromium.

The MM-server-VM and the postgres-VM are not experiencing any relevant load. We have like 40 people having a heated debate in 3 350+ post threads and the time to open the threadview doesnt help to de-escalate the issues, because people are talking past each other in diffrent threads and are unable to switch as fast as needed between the threads.

(If this goes on, this will be known as the big MM-flamewar of 2018...)

#### Steps to reproduce
Version: 5.5.0

+ Have a thread with more than 350 posts.
+ Try to open the threadview by shift-up.
+ Wait 15 sec.
+ (join flamefest)
 
#### Expected behavior
Not to have to wait 10-15 sec for the thread view to show up

#### Observed behavior (that appears unintentional) 
It takes at around 15 sec to display a 400 posts-thread-threadview. (it became longer while writing this ticket)

#### Possible fixes
Make it more performant. ;)

Possibly dont load all the posts in a thread when switching to threadview.

i have not really an idea. :/

**Comment by amyblais** [comment]
Hi @somenet,

I'm able to reproduce this so I'll ask our performance team on if there is a known workaround for this or if I should create a ticket for further investigation.

**Comment by amyblais** [comment]
Hi @somenet, would you also be open to sharing any log errors or Console errors from the time this issue occurs?

**Comment by amyblais** [comment]
Hi @somenet, I opened a ticket for our performance team to investigate this: https://mattermost.atlassian.net/browse/MM-13390.

**Comment by somenet** [comment]
We have logging enabled at INFO-level. There seems to be nothing of interest in the stderr/systemd log.

There is also nothing of interest in the Chromium-Dev-console.

It just loads like 10 seconds and ``/usr/lib/chromium/chromium --type=renderer --field-trial-handle=12127118630963290989,13623375363994731109,131072 --service-pipe-token=17646642656924818212 --lang=en-US --extension-process --disable-client-    side-phishing-detection --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=17646642656924818212 --renderer-client-id=3 --no-v8-untrusted-code-mitigations --s    hared-files=v8_context_snapshot_data:100,v8_natives_data:101`` eats one full cpu core.

Users reported that Firefox started displaying "page is unresponsive [kill] [wait]" popups even earlier.

Sorry to not be of much help :(

**Comment by amyblais** [comment]
Hi @somenet,

Letting you know that the Jira ticket was closed as Won't Fix. Our developers said that we've already made a number of performance improvements to threads over the last while. If it becomes a sore spot in the future and many users are mentioning it then we can take a look at it closer. For now this is a won't fix.
