### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#9960]
#### Summary

Failed api request with invalid memory address or nil pointer dereference.

Mattermost Version: 5.6.0-rc1
Database Schema Version: 5.6.0
Database: mysql

#### Steps to reproduce

I wrote a simple script on Python:

> def` get_user_id(email):
    url = "/api/v4/users/email/%s" % email
    req = requests.get("%s%s" % (mattermost_base_url, url), headers=headers)
    res = req.json()
    return str(res['id'])

> def set_gitlab_auth(email):
    id = get_user_id(email)
    url = "/api/v4/users/%s/auth" % id
    data = {
        "auth_data": id,
        "auth_service": "gitlab",
        "password": ""
    }
    req = requests.put("%s%s" % (mattermost_base_url, url), headers = headers, data = json.dumps(data))
    res = req.json()
    return res

So, then I implement a function set_gitlab_auth.

#### Expected behavior

Auth type for you have to change from email to gitlab.

#### Observed behavior (that appears unintentional) 

Server crashed:

> {"level":"error","ts":1544006550.3966522,"caller":"app/server.go:142","msg":"Please check the std error output for the stack trace"}
{"level":"error","ts":1544006550.3968158,"caller":"app/server.go:143","msg":"runtime error: invalid memory address or nil pointer dereference"}
goroutine 5348 [running]:
runtime/debug.Stack(0xc005654ab8, 0xe71584, 0xc002d71940)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.log(0x15a7b80, 0xc0001f8a80, 0x15a7880, 0x20ee9d0, 0x1, 0xc005646830, 0x1, 0x1)
	/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:89 +0x71
github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x15b25e0, 0xc003d0c9a0, 0x15a7b80, 0xc0001f8a80, 0x15a7880, 0x20ee9d0, 0x1)
	/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:74 +0xda
panic(0x11ba980, 0x2090060)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/mattermost/mattermost-server/api4.updateUserAuth(0xc00445de00, 0x15b25e0, 0xc003d0c9a0, 0xc00445dd00)
	/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/api4/user.go:880 +0x10e
github.com/mattermost/mattermost-server/web.Handler.ServeHTTP(0xc0011ae000, 0x13dc170, 0x10101, 0x15b25e0, 0xc003d0c9a0, 0xc00445dd00)
	/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/web/handlers.go:135 +0x13e5
github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001f8a80, 0x15b25e0, 0xc003d0c9a0, 0xc00445dd00)
	/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x15a7b80, 0xc0001f8a80, 0x15a7880, 0x20ee9d0, 0x1, 0x15b25e0, 0xc003d0c9a0, 0xc00445db00)
	/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78 +0xb0
net/http.serverHandler.ServeHTTP(0xc0038e0c30, 0x15b25e0, 0xc003d0c9a0, 0xc00445db00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00562e6e0, 0x15b34e0, 0xc002addb80)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5

#### Possible fixes

I hope you know how to fix it better than me.

**Comment by amyblais** [comment]
Thanks @swood, I'll ask our developers about this.

**Comment by amyblais** [comment]
Hi @swood, one of our community members responded and said that this could either be a user error or a bug.

Possible user error: Reasons for App.UpdateUserAuth to fail include an invalid user password and missing required parameter. Can you help check that these are filled in correctly?

Possible bug:  If [App.UpdateUserAuth](https://github.com/mattermost/mattermost-server/blob/v5.6.0-rc1/app/user.go#L981) returns err != nil, then user is nil. But the code does not check if user is nil prior to using [user.AuthService](https://github.com/mattermost/mattermost-server/blob/v5.6.0-rc1/api4/user.go#L880). This causes the reported panic.

**Comment by swood** [comment]
Hey, @amyblais.
I've found a problem. 
The field AppData in the database is unique. So this is the main problem: the Mattermost server can't handle a situation of duplicate that data.

**Comment by lieut-data** [comment]
@swood, the uniqueness of that column is intentional, but you're right, the server should definitely not be crashing. Good news is that @crspeller has already fixed this in `master`: https://github.com/mattermost/mattermost-server/pull/10013.

**Comment by amyblais** [comment]
Closing this as there is a fix available for this issue,

**Comment by gharms80** [comment]
Tested 5.5.2, same error.

**Comment by lieut-data** [comment]
@gharms80, heads up that the fix for this won’t land in a release until 5.8, scheduled for February.

**Comment by gharms80** [comment]
This is 5.5!? Seems to me the patch is in. Maybe I'm wrong?
https://github.com/mattermost/mattermost-server/commit/0e31263320bd4c547de430e9291e91fe635c71d0
Otherwise I have to wait for February.

**Comment by lieut-data** [comment]
@gharms80, while we do select some patches to issue hot fixes against previous versions, this one is currently only in master.

We issue a release each month, but only cut from master every other month: so v5.6 and v5.7 are based on master from the end of November before this patch went in. Our v5.8 release in February will be cut from master near the end of this month, which should include this fix.

**Comment by gharms80** [comment]
Tested 5.8.0, same error.

**Comment by lieut-data** [comment]
Hey @gharms80, can you share some details on what you're seeing. This particular fix was for `api4. updateUserAuth`, but perhaps you might be seeing another issue?

**Comment by gharms80** [comment]
Fixed for me, see here: https://github.com/Crivaledaz/Mattermost-LDAP/issues/24
