### ISSUE TITLE
Boolean setting in plugins cannot be updated if their default value is true

### ISSUE THREAD

**Issue by chetanyakan** [mattermost/mattermost-server#9961]
#### Summary
In Admin Console page for plugin settings, boolean setting in plugins cannot be updated if their default value is `true`.

#### Steps to reproduce
1. Create a new plugin.
2. In the settings_schema, create a `bool` setting and set its default value to `true`.
3. Enable the plugin and from the plugin settings page, try to update its value to `false`.

Version: 5.4.0

#### Expected behavior
Expected the setting value to be updated to false.

#### Observed behavior (that appears unintentional) 
The setting value is set to true and cannot be updated to false.

#### Possible fixes
https://github.com/mattermost/mattermost-webapp/blob/e917fb12c4db23f03b5e5305fead57808b55ce5e/components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx#L40

The above line from current master, using `value || default` is not correct since the value may be false and default may be true.

**Comment by amyblais** [comment]
Thank you for the report @chetanyakan, would you be interested in submitting a fix for this?

**Comment by amyblais** [comment]
Thanks @chetanyakan! Opened a ticket for reference: https://mattermost.atlassian.net/browse/MM-13475.

**Comment by amyblais** [comment]
I'll close this Issue for now as the PR has been merged.
