### ISSUE TITLE
Usernames in system messages should open the profile info screen

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9986]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13413)

For system messages containing usernames, such as 

- User changed channel purpose
- User changed channel name
- User changed channel header
- User archived the channel

Expected: Tapping the usernames should open the profile pop-overs for those users.

This was implemented in webapp but not RN,

**Comment by sapnasivakumar** [comment]
I would like to work on this

**Comment by hanzei** [comment]
@sapnasivakumar How is your work on this issue going? Can we help with anything? Looking forward to your PR!

**Comment by sapnasivakumar** [comment]
@hanzei I'm trying to understand the environment and am working on the ticket. I would like to ask for some more time and will reach out in the meantime if I need some guidance on anything. I hope it is fine

**Comment by hanzei** [comment]
Sure. :+1:  If you need help, feel free to DM me on the [Mattermost Community Server](https://community.mattermost.com).

**Comment by sapnasivakumar** [comment]
I’m not be able to work on this further. Can someone please take this up

**Comment by hanzei** [comment]
Thanks for head up @sapnasivakumar. :+1: 

I will make this available for the public again.

**Comment by chuttam** [comment]
I'd like this one, please.

**Comment by hanzei** [comment]
Great! Thanks for working on this issue @chuttam :tada:
