### ISSUE TITLE
Rename "flag post" to "bookmark post"

### ISSUE THREAD

**Issue by somenet** [mattermost/mattermost-server#9990]
#### Summary
Users seem to expect that "Flag post" means "Report post" and do not think of it as a way to bookmark posts.

Especially as in the web-app "flag post" is not displayed along the other post-actions, but instead by the side of the posting username.

#### Possible fixes
Rename the "flag posts" feature to "bookmark posts".

In the webapp, move bookmark posts to the other post-actions to the right of the post.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @somenet!

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the pull request review.

**Comment by jasonblais** [comment]
Thanks @somenet for opening a feature proposal for it: https://mattermost.uservoice.com/forums/306457-general/suggestions/36299584-rename-flag-post-to-bookmarked-post

I'll close this ticket for now and we can track in the feature proposal forum. We also have a ticket here to add the flag option to the post menu, but we'd likely keep the flag icon as well: https://mattermost.atlassian.net/browse/MM-13380

An alternative approach that comes to mind is to create a plugin which can
1. Renames the action to "bookmark posts" for you, or
2. Implement an actual "report post" feature, in addition to flagging posts

If this is something of interest for your team, we have documentation here to learn more: https://developers.mattermost.com/extend/plugins/

**Comment by RohitKanojia** [comment]
How was this issue have been fixed? can you pls help me.

**Comment by jasonblais** [comment]
Hi @RohitKanojia - we have an open feature proposal for it at https://mattermost.uservoice.com/forums/306457-general/suggestions/36299584-rename-flag-post-to-bookmarked-post

Would you be open to upvoting the feature and/or sharing your use case in the discussion section? We monitor the feature proposal forum regularly to help guide future roadmap and product direction.
